### ISSUE TITLE
Using aws s3 cp in multiple process/threading

### ISSUE THREAD

**Issue by delbinwen** [aws/aws-cli#1018]
Hi,

First, please let me describe our aws cli usage scenario. We store a set of files on s3 with same prefix, say s3://my_bucket/, and a set of EC2 instances will copy the file, process it, and upload it to another bucket. We use SWF, and therefore multiple workers on EC2 will actually do the tasks, and we use aws s3 cp of course. I think this scenario is quite common.

It works well with less than 5 files to process. However, if we process many files (100+), things could go wrong. There are two observations:

1. aws s3 cp looks like stuck, it could take several hours to download a single file (less than 1 GB), or it never returns. We use basic command syntax, like aws s3 cp s3://my_bucket/file.1 /tmp/

2. aws s3 cp returns 0 code but did not complete all parts. We capture the standout in our log and looks like below:
'stdout': u'Completed 1 of 685 part(s) with 1 file(s) remaining\rCompleted 2 of 685 part(s) with 1 file(s) remaining\rCompleted 3 of 685 part(s) with 1 file(s) remaining\rCompleted 4 of 685 part(s) with 1 file(s) remaining\rCompleted 5 of 685 part(s) with 1 file(s) remaining\rCompleted 6 of 685 part(s) with 1 file(s) remaining\rCompleted 7 of 685 part(s) with 1 file(s) remaining\rCompleted 8 of 685 part(s) with 1 file(s) remaining\rCompleted 9 of 685 part(s) with 1 file(s) remaining\rCompleted 10 of 685 part(s) with 1 file(s) remaining\r\n'

I think --debug option might be required to help investigation. I will try to work on this, but this issue is quite urgent and therefore I want to know if there is any other information that we could provide to assist this.

Thanks,
Wesley

**Comment by jamesls** [comment]
Consolidating issues into tracking issues.  There's two that are relevant here:

1.  Limit bandwidth: https://github.com/aws/aws-cli/issues/1090
2. Set retry configuration: https://github.com/aws/aws-cli/issues/1092
3. Limit concurrency: https://github.com/aws/aws-cli/issues/907

Closing in favor of those issues.
