### ISSUE TITLE
AWS_CONFIG_FILE vs. AWS_CREDENTIAL_FILE

### ISSUE THREAD

**Issue by sopel** [aws/aws-cli#1037]
[Configuration and Credential Files]() within the official AWS CLI documentation differentiates between these two configuration files and resp. environment variable overrides `AWS_CONFIG_FILE` and `AWS_CREDENTIAL_FILE`:
- `AWS_CONFIG_FILE` – path to a CLI config file.
- `AWS_CREDENTIAL_FILE` – path to an AWS credentials file.

It elaborates on that in section _Storing Credentials in Config_:

> The default file locations can be overridden by setting the AWS_CONFIG_FILE and AWS_CREDENTIAL_FILE environment variables to another local path. See Environment Variables for details.
> 
> The AWS CLI will also read credentials from the config file. If you want to keep all of your profile settings in a single file, you can. If there are ever credentials in both locations for a profile (say you used aws configure to update the profile's keys), the keys in the credentials file will take precendence.

However, other than `AWS_CONFIG_FILE`, `AWS_CREDENTIAL_FILE` doesn't seem to work and exhibits the following two oddities:
1. using `aws configure` with `AWS_CREDENTIAL_FILE` set still yields the `credentials` file to be generated in the default location (whereas `AWS_CONFIG_FILE` is obeyed)
2. moving the credentials file generated in 1. to the location denoted in `AWS_CREDENTIAL_FILE` yields _'Unable to locate credentials. You can configure credentials by running "aws configure".'_ again - however, after changing that location to a non existing file, boto triggers the error _'The specified config file (<test file>) could not be found.'_  [as expected](https://github.com/boto/boto/blob/f580f73d3def7f47f087c66637e3aad8268e7973/boto/pyami/config.py#L71), so it attempts to read the file at least

:question: Any idea what's going on here, or am I missing how this is supposed to work? Thanks!

**Comment by sandys** [comment]
not supporting AWS_CREDENTIAL_FILE is a problem when we use sudo to run aws-cli, especially with users who dont have home directories (e.g. www-data). 

What is the right way to run aws-cli with "sudo" ?

**Comment by nchammas** [comment]
I agree with @sandys. It seems like a problem that you cannot point `aws` to a config file in a non-default location. This is handy when you need to something like `sudo aws s3 sync /local/path s3://remote/path`. The `sudo` may be required, for example, so that you can access local files. Having to set environment variables is a bit clunky given that the info you need is already available in a set of files.

**Comment by schollii** [comment]
See AWS_SHARED_CREDENTIALS_FILE

**Comment by rdonkin** [comment]
You need to set `AWS_CONFIG_FILE` and `AWS_SHARED_CREDENTIALS_FILE` environment variables, to the config file and credentials file respectively.  Works fine with AWS CLI latest version.

Ref https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#the-shared-credentials-file

**Comment by minlare** [comment]
I found I had to set another variable in `.env` to get this working

```
AWS_SHARED_CREDENTIALS_FILE=local/folder/credentials
AWS_CONFIG_FILE=local/folder/config
AWS_SDK_LOAD_CONFIG=1
```
