### ISSUE TITLE
Unable to use `cloudfront wait invalidation-completed`

### ISSUE THREAD

**Issue by cw-sudo** [aws/aws-cli#1059]
`cloudfront wait invalidation-completed` failed. 
after waiting about 10 minutes , following error has occurred.

```Shell
aws cloudfront wait invalidation-completed --distribution-id XXXXXXXXXXXXX --id XXXXXXXXXXXXX
Waiter InvalidationCompleted failed: Max attempts exceeded
```
and when I wait for completed invalidation , the same error has occurred.

My version: aws-cli/1.6.9 Python/2.7.6 Darwin/14.0.0

**Comment by kyleknap** [comment]
This should be fixed via https://github.com/boto/botocore/pull/426. Closing issue. Please reopen, if the issue persists.
