### ISSUE TITLE
RequestTimeTooSkewed when uploading large files?

### ISSUE THREAD

**Issue by evleeann** [aws/aws-cli#1065]
I've been using the awscli to push files from our local backup linux server to the S3 storage cloud, and for the most part it works. A few times a week though, my backup will fail, with 

"A client error (RequestTimeTooSkewed) occurred when calling the UploadPart operation: The difference between the request time and the current time is too large."

The first time it happened, I read up on the error, and set up ntp to run nightly to resync my local server time to the time server.

Today it happened while I was watching - so I immediately ran a check on the machine to see if the local time was off - 

me@bk1 ~$ curl http://s3.amazonaws.com -v
About to connect() to s3.amazonaws.com port 80 (#0)
Trying 54.231.32.32... connected
Connected to s3.amazonaws.com (54.231.32.32) port 80 (#0)
GET / HTTP/1.1
User-Agent: curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Host: s3.amazonaws.com
Accept: /
< HTTP/1.1 307 Temporary Redirect
< x-amz-id-2: mNLP6aO0f332BxDWUuOhd5zokYd2ZuPrl22tvP2juZ4ln152DEW64pj5CQqqhx1y
< x-amz-request-id: 4388A0673C619CF8
< Date: Thu, 18 Dec 2014 21:56:15 GMT
< Location: http://aws.amazon.com/s3/
< Content-Length: 0
< Server: AmazonS3
< 
Connection #0 to host s3.amazonaws.com left intact
Closing connection #0
me@bk1 ~$ date -u
Thu Dec 18 21:56:07 UTC 2014

So I am within a few seconds of the amazon official time - so it doesn't seem like this is really the actual problem - but I can't find any information on what else the problem might actually be.

Any ideas on what might be causing this error, when it's not actually a 15 minute time difference?

me@bk1 ~$ aws --version
aws-cli/1.6.2 Python/2.6.6 Linux/2.6.32-431.el6.i686

I'm connecting to S3 in Oregon if that makes any difference!
using the command

/usr/local/bin/aws s3 cp /backups/$i s3://mybucketname
and looping through each file to be uploaded.

The file in question is 7.6 gigs - and s3 was breaking it up into parts. It got to part 56 before it got the errors

Completed 56 of 524 part(s) with -1 file(s) remaining

**Comment by jamesls** [comment]
I'm trying to aggregate all these related issues into the main features requests for S3 command enhancements.  There's two features I think that would help here.

1. #1092: Add ability for S3 commands to increase retry account
2. #907: Limit number of parallel S3 transfers.

Closing this ticket in favor of these two issues.
