### ISSUE TITLE
--port all option not working

### ISSUE THREAD

**Issue by thirstyfish** [aws/aws-cli#1066]
When running the following command

```
aws ec2 authorize-security-group-ingress --group-id ${SEC_GROUP} --protocol tcp --port all --cidr ${NEWIP}/32
```

the client throws the following error:

```
A client error (InvalidParameterValue) occurred when calling the AuthorizeSecurityGroupIngress operation: TCP/UDP (from) port (-1) out of range
```

It works fine if I use a single port number instead of `all`.
Can someone please enlighten me how to set **all** ports in one command?

Cheers

**Comment by romanr** [comment]
This issue is not fixed. I read the docs http://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html
which say exactly: `You can specify all to mean all ports`
Wasted lot of time trying to quote the 'all' and whatnot.
want my 15 minutes back!

**Comment by jamesls** [comment]
@romanr Sorry you ran into trouble.  The fix for this is currently in the develop branch but is not in an actual release yet.  The docs will be updated in the next AWS CLI release.

**Comment by isuftin** [comment]
This actually is also an issue in the CloudFormation docs. :( Glad I found this issue here

**Comment by my2ter** [comment]
Hi, the doc is still not updated

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html#cfn-ec2-security-group-ingress-fromport

```
FromPort
Start of port range for the TCP and UDP protocols, or an ICMP type number. If you specify icmp for the IpProtocol property, you can specify -1 as a wildcard (i.e., any ICMP type number).```

**Comment by avvi00** [comment]
Hi, not just cloudformation - .net sdk has same issue and incorrect docs.

http://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2IpPermission.html&tocid=Amazon_EC2_Model_IpPermission

**Comment by jeremyd** [comment]
+1 still not updated, very confusing since usually these docs aren't wrong...
