### ISSUE TITLE
"aws s3 cp" fails silently when user has no write permissions on local directory  

### ISSUE THREAD

**Issue by senderista** [aws/aws-cli#1069]
I just spun up a new EC2 instance and formatted an ephemeral storage volume. When I attempted to copy a (very large) S3 object to the root directory of that volume, the command completed immediately, with no output at all. Eventually I determined that only root had write permissions on the root directory of the volume, and granted write permissions to ec2-user, after which the command completed successfully. It would have been very helpful to have been given some idea of the reason for the failure, or any output at all for that matter.

**Comment by SydOps** [comment]
I got the same issue with latest docker version 1.9 on ubuntu

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by rbwinslow** [comment]
I also just ran into this.

aws-cli/1.7.26 Python/2.7.9 Linux/3.14.42-31.38.amzn1.x86_64

**Comment by jamesls** [comment]
This was fixed in a later version of the AWS CLI ([1.9.8](https://aws.amazon.com/releasenotes/CLI/7167484435528139)).  If you upgrade to the latest version, these problems should go away.

**Comment by SydOps** [comment]
@jamesls 
Could you please share me the commits for this feature fix in 1.9.8? I am more interesting on the codes.

**Comment by jamesls** [comment]
Original fix was a community contribution: https://github.com/aws/aws-cli/pull/1646/files
I made some small changes and added integration tests: https://github.com/aws/aws-cli/pull/1648/files

**Comment by SydOps** [comment]
Thanks again. :+1:

**Comment by AndrewMcFarren** [comment]
Seeing the same issue since upgrade to 1.16.1.  My downloads are failing with aws s3 cp.  My environment is as follows.  From debug, I am wondering if python related.

aws-cli/1.16.1 Python/2.7.14 Linux/4.14.62-65.117.amzn1.x86_64 botocore/1.11.1
pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
Python 2.7.14
