### ISSUE TITLE
aws ec2 run-instances --block-device-mapping doesn't allow numeric device name suffixes

### ISSUE THREAD

**Issue by ehammond** [aws/aws-cli#1071]
aws-cli seems to think that /dev/sde1 is an invalid device name:

> A client error (InvalidBlockDeviceMapping) occurred when calling the RunInstances operation: Invalid device name /dev/sde1

This happens any time I add a number to the end of the device name, but these should be valid according to:

>  http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html

Here's a sample command that generates the error:

```
aws ec2 run-instances \
  --instance-type m3.medium \
  --image-id ami-4ae27e22 \
  --block-device-mapping '[{
    "DeviceName": "/dev/sde1",
    "Ebs": { "VolumeSize": 1 }
}]'
```

**Comment by kirang270** [comment]
I am facing the same issue while launching an aws ec2 instance through shellscript where the configuration is done in the shellscript for the instance, blockdevicemapping is also done in the script properly still when I try to run the script it gives me the error as follows. "An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Invalid device name C:/Program Files/Git/dev/sda1" Can you please give me the solution that worked for you?
