### ISSUE TITLE
s3 sync not syncing files locally with that have the same size but have been modified

### ISSUE THREAD

**Issue by Bazman** [aws/aws-cli#1074]
I originally posted this as a reply to #406 but I think its worth posting as a new issue as it seems like its a relatively straight forward but significant bug.

When doing an s3 sync from s3 to local, newer files (based on modified time) on S3 won't sync to local if the file size is the same.

It seems like its just because the compare_time() function is wrong.

In aws-cli/awscli/customizations/s3/syncstrategy/base.py, lines 207 - 223 (as of 9f56e8f):

        if cmd == "upload" or cmd == "copy":
            if self.total_seconds(delta) >= 0:
                # Destination is newer than source.
                return True
            else:
                # Destination is older than source, so
                # we have a more recently updated file
                # at the source location.
                return False
        elif cmd == "download":

            if self.total_seconds(delta) <= 0:
                return True
            else:
                # delta is positive, so the destination
                # is newer than the source.
                return False

There shouldn't be any logic difference between the cmd == "upload" or cmd == "copy" or cmd == "download". Its comparing source file and destination file times, and so all it needs to know is if the source file is newer than the destination or not.

i.e. Change the above block of code just to:

           if self.total_seconds(delta) >= 0:
                # Destination is newer than source.
                return True
            else:
                # Destination is older than source, so
                # we have a more recently updated file
                # at the source location.
                return False

Seems to fix the problem.

This same code was also in an issue in earlier versions where the sync strategies weren't split out, and the comparison code was in comparator.py

**Comment by kyleknap** [comment]
Thanks! This will have to be a feature request. We will look into/consider adding such a sync strategy.

**Comment by Bazman** [comment]
@kyleknap , we found using the --exact-timestamps solves our problem.  Not sure if its meant to be the solution to this is or not, but it seems to work perfectly.

Thanks.

**Comment by kyleknap** [comment]
That's right. I forgot about that option. Good to hear that it worked out for you. Closing issue.

**Comment by ChrisSLT** [comment]
I have Bazman's same use case - need to be able to sync up to S3, and then sync from S3 down to a different machine.  I don't think Exact Timestamps solves it.

I think with rsync this isn't an issue.   Would you be willing to look at the rsync logic?  I think it has worked out some issues that we're experiencing due to AWS CLI's sync operating according to a different logic.

**Comment by ChrisSLT** [comment]
Thinking about this more I see how it could be useful to have s3>local overwrite newer files on the local end.  For example if a user changes something locally and you want the s3 content to refresh/overwrite the user's content.

However, I still hope that there can be an option to do the above as well as an option to local>s3 and s3>local behave the same way (wherein a file goes from source to destination only if it's newer in the source, or doesn't exist, etc.)  

Thank you!

**Comment by daveFNbuck** [comment]
This is a really nasty bug and lead to an error in production that took me days to track down. Basic tools like this should just work without users having to know implementation details. Why doesn't sync use something sane like a checksum instead of a timestamp or file size?

**Comment by amunson2W** [comment]
It is 2018 and this is still a bug. In short, if you modified a file locally then ran `aws s3 sync $myBucket $localDirectory`. The older file in S3 will overwrite the newer file regardless of whether or not the sizes match. To test run:

`aws s3 sync $myBucket $localDirectory`
`touch -am $localDirectory/$localFile`
`aws s3 sync $myBucket $localDirectory`

The file that was modified after the bucket file will then be overwritten and the modified date on the local file will now match the older S3 bucket file's modified date. This is contrary to the documentation for the sync function provided by AWS: https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by bgiaccio** [comment]
Just to make the use case practical we had a diff in a properties file of
```
@@ -1,4 +1,4 @@
-server.ssl.client-auth=need
+server.ssl.client-auth=want
```
This change led to the same size property file, so the sync from the s3 bucket to the local machine failed to get the change.  Obviously very different behavior.

**Comment by zeightnoteight** [comment]
I'm being effected by this due to different timezones between the uploader and downloader.

**Comment by dawagner** [comment]
It seems that the explanation given in the first answer might be obsolete: when I sync a file from S3 to local, the local file then has the same last-modified time as shown on S3. I need a strategy opposite to the default one: when syncing from S3 to local, if S3 is newer, update the local file.

**Comment by dawagner** [comment]
@kyleknap would you mind reopening this issue or point me to a more recent duplicate of this issue, if any?

**Comment by ntrp** [comment]
We are still experiencing this problem, a local file `index.html` gets updated with only an hash and that makes the file stay the same size. The sync command does not upload the file.

Any update from the code maintainers?

**Comment by KAbakumov** [comment]
I have the same problem. Need to sync data from local machine to S3. Request the ticket to be reopened.

**Comment by inksink** [comment]
I have the same problem. 
At the very least, `awscli` should make sure that the documentation is consistent with the code.

**Comment by lalitkumarbTR** [comment]
I ran into the same problem, and using "--exact-timestamps" option worked. As per [documentation](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html), "The default behavior is to ignore same-sized items unless the local version is newer than the S3 version".

> --exact-timestamps (boolean) When syncing from S3 to local, same-sized items will be ignored only when the timestamps match exactly. The default behavior is to ignore same-sized items unless the local version is newer than the S3 version.

**Comment by macin** [comment]
How should I add the "--exact-timestamps" in the plugin config? I am having exactly the same problem...

**Comment by jono-channel-squirrel** [comment]
Still so many people being caught out by this, on many different threads. I think its pretty reasonable to at least have flag that uses a hash/checksum instead of size/timestamp so that we have have reliable sync behaivour (similar to rsync). At minimum this should be noted with a large highlighted warning in the docs, as this behaivour is not the expected/intuitive behaviour most would expect.

**Comment by jcphill** [comment]
Note that this behavior is contrary to other parts of the documentation, specifically:

> Example 3: Sync all S3 objects from the specified S3 bucket to the local directory
>
> The following sync command syncs files from the specified S3 bucket to the local directory by downloading S3 objects. An S3 object will **require downloading if** the size of the S3 object differs from the size of the local file, the last modified time of the **S3 object is newer** than the last modified time of the local file, or the S3 object does not exist in the local directory.
