### ISSUE TITLE
Best practice for third-party scripts wanting AWS config/credential data

### ISSUE THREAD

**Issue by Calrion** [aws/aws-cli#1095]
With reference to #847 and #1037, what's the current recommended best practice for third-party scripts trying to integrate with AWS and/or the AWS CLI tools?

I have a number of scripts that interface with AWS, including post-build scripts that upload releases to S3, a script to send an APNS message via SNS, and a script to make command-line MFA credentials easier to use.

In the past, I've looked for an `AWS_CONFIG_FILE` environment variable and used that, falling back to `~/.aws/config` if it's not defined. But the current tools seem to refuse to read credentials from this file, even if they're present. Additionally, my current script (the MFA one) needs to write credentials for future use.

How should I determine where to read and write credentials from—are there any tools to support this?

**Comment by jamesls** [comment]
The `~/.aws/config` and the `AWS_CONFIG_FILE` are an AWS CLI only configuration mechanism.  If you're only working with the AWS CLI, then you can still use these values.  However if you're using other AWS SDKs, then you can just use the `~/.aws/credentials` file.  This is a fixed location that's used by all the AWS SDKs, and is the recommended file to use for interop.

For writing configuration/credential values via a script, you do have the option of using the `aws configure set` [command](http://docs.aws.amazon.com/cli/latest/reference/configure/set.html), which will automatically create/update the configuration file and the shared credentials file based on what config values you're setting.

Let us know if you have any other questions.
