### ISSUE TITLE
Add waiter for ec2 create-image

### ISSUE THREAD

**Issue by cliff-wakefield** [aws/aws-cli#1105]
It would be great if a waiter could be developed for the ec2 create-image command such that when an image switches from the 'pending' state to 'available' state that you can make a ec2 modify-image-attribute command to share the image with another AWS account.

**Comment by sebsto** [comment]
+1 for this
my use case is to update an ASG Launch Configuration when the AMI is ready

**Comment by jamesls** [comment]
This is now available in the [1.7.16](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1716) release of the AWS CLI.

**Comment by sebsto** [comment]
Cool !  Thank you James
