### ISSUE TITLE
aws s3api wait bucket-not-exists does not handle success case

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#1111]
Given a bucket that does not exist:

```
$ aws s3api head-bucket --bucket foobar-asdfasdfasdf-123

A client error (404) occurred when calling the HeadBucket operation: Not Found
```

when we try to wait for that bucket to not exist, I'd expect the command to return immediately but instead we get an error:

```
$ aws s3api wait bucket-not-exists --bucket foobar-asdfasdfasdf-123

Waiter BucketNotExists failed: Unexpected error encountered.
```

This _should_ go away with the switchover to clients, but in the meantime this happens because we can't parse an error code out of the head object response because it does not have a response body to parse.

**Comment by kyleknap** [comment]
With this PR now merged: https://github.com/aws/aws-cli/pull/1220

Issue is now fixed. Closing.
