### ISSUE TITLE
aws s3 sync - file does not exist for /Users/username/Library

### ISSUE THREAD

**Issue by ChrisSLT** [aws/aws-cli#1115]
If you run on a mac:

aws s3 sync --exclude "[star]" --include "Documents/[star]" --include "Desktop/[star]" /Users/username/ to s3://bucket/user

the result is a bunch of errors / warnings about files contained within the Library, which should have been excluded.  Is this a bug and is it known?  Thank you.

**Comment by jamesls** [comment]
Right now it will still traverse into the directory.  It won't upload any files you've specified as excludes, but if the file is unreadable or some other error it will still print a warning.  For example:

```
/tmp $ mkdir demo
/tmp $ mkfifo demo/bad
/tmp $ touch demo/good
/tmp $ aws s3 sync demo/ s3://bucket/demo/ --exclude '*' --dryrun
warning: Skipping file /private/tmp/demo/bad. File is character special device, block special device, FIFO, or socket.
Completed 0 part(s) with ... file(s) remaining
```

However, I have noticed that the RC is non zero even if it's an excluded file, which I don't think is right.  I've filed https://github.com/aws/aws-cli/issues/1117 to track this issue.

**Comment by ChrisSLT** [comment]
If you sync from your home directory on a mac and exclude all but include just documents and desktop: it doesn't traverse into any other directory EXCEPT the library directory.  This seems odd and also really slow and inefficient.  Can you pls confirm?

**Comment by ChrisSLT** [comment]
Would you be able to comment on this issue - it seems very inefficient for SYNC to traverse into a folder that is excluded.  With a large directory try like ~/Library, this adds several minutes of wasted time for each sync operation.  Can this be fixed?

**Comment by tmadms** [comment]
Was there a solution for excluding the Library directory? It still has the same issue of traversing into it.
