### ISSUE TITLE
profiles are not recognized if the environment variables are set.

### ISSUE THREAD

**Issue by abualsamid** [aws/aws-cli#1120]
aws --profile does not do anything if you have defined the environment variables AWS_ACCESS_KEY_ID and AWS_SECRECT_ACCESS_KEY defined. 

i think the --profile parameter should override the environment variables and use the configured credentials.

**Comment by jamesls** [comment]
I agree.  There's an existing issue tracking this bug: https://github.com/aws/aws-cli/issues/113.  Let's track that issue over there.
