### ISSUE TITLE
AWS_DATA_PATH not working

### ISSUE THREAD

**Issue by jamesecahill** [aws/aws-cli#1127]
Setting AWS_DATA_PATH to introduce new json schemas isn't working in 1.7.4. I downgraded to 1.6.9 and it seems to be working in that version. `aws-cli/1.6.9 Python/2.7.6 Darwin/14.1.0` is the version it's working on.

**Comment by kyleknap** [comment]
Your JSON data models are probably the wrong name. Are you using the ``.api.json`` extension for your models? If you are, you will need to change them to ``.normal.json``. We made that change somewhere between the two versions of the CLI that you are switching between.

**Comment by jamesecahill** [comment]
Ahhh. Good to know! Thanks @kyleknap.
