### ISSUE TITLE
Explicit --profile option should have precedence over credentials env vars

### ISSUE THREAD

**Issue by ches** [aws/aws-cli#113]
I have credentials for a primary account set in `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to support other tools. When I try to pass a `--profile` option for an `aws-cli` command, the profile is not used and the account in env is -- I have to `unset` the env vars in order to use profiles. I believe that an option given explicitly should have precedence over the environment.

**Comment by cristianobaptista** [comment]
I'm currently having the same issue. As stated above I also think that explicitly defined options should have precedence over the environment. 

Setting `AWS_DEFAULT_PROFILE` also does not change the behaviour described above.

**Comment by cristianobaptista** [comment]
I would also like to add that if the default profile defined with environment variables belongs to the same AWS account as the credentials on the alternative profile, everything works just fine.

**Comment by pims** [comment]
I’ve been struggling with IAM setting up IAM policies and testing them with `--profile` before figuring out aws-cli is using my general environment variables. 

Any chance to get this into the next release?

**Comment by matheeeny** [comment]
Also having this issue.

**Comment by davidski** [comment]
What can we do to assist with closing out this nearly 2 year old issue? Folks seem unified that having explicitly defined option overridden by environment variables is a Bad Thing(tm). Is a PR needed to get this done?

**Comment by matheeeny** [comment]
This behavior contradicts the documentation found at http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence
![screen shot 2015-03-09 at 11 48 18 am](https://cloud.githubusercontent.com/assets/266679/6558376/42cb1664-c652-11e4-8315-26278066a98b.png)

**Comment by jamesls** [comment]
Taking a look.  I agree this should be fixed.

**Comment by kyleknap** [comment]
This is now fixed. See below:
```
$ export AWS_ACCESS_KEY_ID=foo
$ export AWS_SECRET_ACCESS_KEY=bar
$ aws s3 ls

A client error (InvalidAccessKeyId) occurred when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.

$ aws s3 ls --profile my-profile
2014-11-24 13:33:43 mybucket
....
....
```

Closing issue.

**Comment by ches** [comment]
:clap: :tada:
