### ISSUE TITLE
'aws support describe-services' fails if region not set to us-east-1

### ISSUE THREAD

**Issue by paulruiz** [aws/aws-cli#1133]
If any region but us-east-1 is set as region= in ini or AWS_DEFAULT_REGION results in an error

 HTTPSConnectionPool(host='support.<region>.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by <class 'socket.gaierror'>: [Errno 8] nodename nor servname provided, or not known)

If region is unset, it results in the error

 URL has an invalid label.

aws-cli/1.7.5 Python/2.7.9 Darwin/13.4.0

**Comment by kyleknap** [comment]
The issue that you are running into makes sense. AWS Support only has one endpoint and that is ``us-east-1`` region endpoint. Requests to any other region will result in the error that you are getting.

If I want to know what regions a service is available in, I like to refer to this doc: http://docs.aws.amazon.com/general/latest/gr/rande.html

We have got similar issues like this in the past, where based on the error message, it is not too obvious that the region is not supported by the service. We have been looking into how improving the error message by printing out which regions a service is supported in if given that error message.

Closing issue. But any other suggestions/feedback that you have on how to make it a better experience for you would be great.
