### ISSUE TITLE
MalformedCertificate is not a good error message when a file doesn't exists

### ISSUE THREAD

**Issue by diegows** [aws/aws-cli#1149]
Today I spent some time checking if my certificate chain was OK when I discovered that the problem is that amazon can't locate the file when you miss the file:// prefix. It would be great to have a better error messages on this cases.

Thanks!

**Comment by kyleknap** [comment]
Can you show me a set of steps that I can follow to repeat this and the exact error that gets displayed to you? That will help us identify how to go about improving the error message.

**Comment by diegows** [comment]
aws --profile myprofile iam upload-server-certificate
--server-certificate-name widgets-app --certificate-body
file:///tmp/app-prod.dws.la.crt  --private-key
file:///tmp/app-prod.dws.la.key  --certificate-chain
gsdomainvalsha2g2r1.pem --path /cloudfront/

That one fails, but adding file:/// to --cerfiticate-chain works. The error
is a bit confusing. The whole cmd line that works:

aws --profile changefactor iam upload-server-certificate
--server-certificate-name widgets-changefactor01 --certificate-body
file:///tmp/changefactor-js-prod.dws.la.crt  --private-key
file:///tmp/changefactor-js-prod.dws.la.key  --certificate-chain
file:///tmp/chain.pem --path /cloudfront/

On Tue, Feb 17, 2015 at 7:48 PM, Kyle Knapp <notifications@github.com>
wrote:

> Can you show me a set of steps that I can follow to repeat this and the
> exact error that gets displayed to you? That will help us identify how to
> go about improving the error message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-cli/issues/1149#issuecomment-74772134>.
>



-- 
Diego Woitasen
Infrastructure Developer, DevOps Engineer, Linux and Open Source expert
http://www.woitasen.com.ar

**Comment by JordonPhillips** [comment]
Looks like it's being interpreted as a string. Not sure that there's much we can do here since what looks like a valid file path could be a valid parameter for a service's function. @kyleknap what do you think?

**Comment by kyleknap** [comment]
Yeah it will be interpreted as a string. There are only a few instances were the actual file name should be used without ``file://``. The example in the docs also expresses that as well: http://docs.aws.amazon.com/cli/latest/reference/iam/upload-server-certificate.html and the docs explicitly says to use the contents of the certificate chain which would imply to use file://. I am not sure if there is much more we can do here given that sending the contents directly on the comand line i.e. no ``file://`` (while not probably the best idea) is still valid and all we can do at that point is display what error the server sends back.

**Comment by jamesls** [comment]
Closing out old issue.
