### ISSUE TITLE
Pinned versions of colorama and rsa

### ISSUE THREAD

**Issue by taion** [aws/aws-cli#1157]
The requirements currently include:

`'colorama==0.2.5'`
`'rsa==3.1.2'`

These are behind the current versions and conflict with other packages. I could put `awscli` in its own virtualenv, but that seems excessive for a command-line tool.

Is it possible to loosen those dependencies?

**Comment by danielgtaylor** [comment]
I've gone ahead and loosened them a bit to still support the older versions, but also accept the latest releases.

**Comment by taion** [comment]
Thank you!
