### ISSUE TITLE
AWS-CLI not working after installation using pip on Windows

### ISSUE THREAD

**Issue by asallamon** [aws/aws-cli#116]
I just did a fresh installation on Windows 7 64-Bit:
- Installed Python 2.7.4 (32-Bit)
- Installed distribute and pip from http://www.lfd.uci.edu/~gohlke/pythonlibs/
- Executed "pip install awscli"

It seems, that pip installs all packages.

When I tried to test the awscli the following appeared:

```
C:\Python27\Scripts>aws help
Traceback (most recent call last):
  File "C:\Python27\Scripts\aws.cmd", line 49, in <module>
    import awscli.clidriver
ImportError: No module named 'awscli'

C:\Python27\Scripts>pip install awscli --upgrade
Requirement already up-to-date: awscli in c:\python27\lib\site-packages
Requirement already up-to-date: botocore>=0.9.2 in c:\python27\lib\site-packages\botocore-0.9.2-py2.7.egg (from awscli)
Requirement already up-to-date: six>=1.1.0 in c:\python27\lib\site-packages\six-1.3.0-py2.7.egg (from awscli)
Requirement already up-to-date: colorama==0.2.5 in c:\python27\lib\site-packages\colorama-0.2.5-py2.7.egg (from awscli)
Requirement already up-to-date: argparse>=1.1 in c:\python27\lib\site-packages\argparse-1.2.1-py2.7.egg (from awscli)
Requirement already up-to-date: requests==1.2.0 in c:\python27\lib\site-packages\requests-1.2.0-py2.7.egg (from botocore>=0.9.2->awscli)
Requirement already up-to-date: jmespath==0.0.2 in c:\python27\lib\site-packages\jmespath-0.0.2-py2.7.egg (from botocore>=0.9.2->awscli)
Requirement already up-to-date: python-dateutil>=2.1 in c:\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg (from botocore>=0.9.2->awscli)
Requirement already up-to-date: ply==3.4 in c:\python27\lib\site-packages\ply-3.4-py2.7.egg (from jmespath==0.0.2->botocore>=0.9.2->awscli)
Cleaning up...
```

I tried this on a second PC with same result.
On the computers where it's already installed - it works fine.

**Comment by AndreLouisCaron** [comment]
@asallamon I ran into a similar issue (see #2372).  What did you set inside `PATH` for this to work?

**Comment by arsho** [comment]
I had similar issue with Windows 10 (64 bit). Python 3.5 and Python 2.7 are installed in my PC. I was getting `ImportError: No module named awscli.clidriver`.

Then I added `%USERPROFILE%\AppData\Roaming\Python\Python35\Scripts` in environment path variable and removed Python 2.7 from the environment path variable. Now I can successfully use `awscli`.

I have created a step by step AWSCLI installation guide in this Github repository: [https://github.com/arsho/installation/tree/master/awscli_installation](https://github.com/arsho/installation/tree/master/awscli_installation).

**Comment by Sanky93** [comment]
Hey, I am facing similar issue with my Linux instance.
Please help.
