### ISSUE TITLE
aws s3 sync has useless option: --recursive

### ISSUE THREAD

**Issue by DrStrangepork** [aws/aws-cli#1170]
Since at least 1.7.1, s3 sync always does --recursive even when it is not given as an option
https://forums.aws.amazon.com/thread.jspa?threadID=169794
https://forums.aws.amazon.com/thread.jspa?threadID=171968

**Comment by kyleknap** [comment]
Yep that is correct. Sync will always be recursive. Sync is not suppose to have the ``--recursive`` option. Specifying ``--recursive`` does not affect the sync at all.
