### ISSUE TITLE
aws s3 cp streaming download hangs when pipe breaks

### ISSUE THREAD

**Issue by tlunter** [aws/aws-cli#1178]
When using `aws s3 cp s3://some-bucket/some-key -` and the downstream pipe dies due to one error or another, aws-cli hangs.

The exception is raised by the IOWriterThread, but is not checked by the Executor.  New jobs are still being submitted to the executor to download files, but they get held up: [here](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/tasks.py#L420) and [here](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/tasks.py#L416).

In the first, the queue has a max size of 20 ([here](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/s3handler.py#L43)).  In the second, nothing is being added to the queue, so the current stream part number is never going to be incremented.  The program then halts and nothing happens until it is forcefully killed.  A keyboard interrupt doesn't even kill the process.

The `MultipartDownloadContext` does have a cancel method to prevent the workers from continuing to wait for their turn, but workers stuck at `self._io_queue.put` will remain there.

**Comment by kyleknap** [comment]
Thanks for looking into this!

I can confirm that if a downstream pipe breaks that the s3 streaming process does hang. However I have not been able to reproduce the keyboard interrupt issue. When I hit keyboard interrupt, it takes roughly 15 seconds to clean up (e.g. the length "Cleaning up. Please wait.." is being displayed).

For replication purposes here is the command, I was running:
```
aws s3 cp s3://mybucket/bigfile - | python some_process.py
```

Here is the ``some_process.py`` script that I wrote:
```
import sys

def main():
    total = 0
    kb = 1024
    mb = 1024 ** 2
    chunk = sys.stdin.read(kb)
    while chunk:
        total += len(chunk)
        if total > mb:
            raise Exception
        chunk = sys.stdin.read(kb)


if __name__ == "__main__":
    main()
```

This will cause the following to be displayed to screen:
```
Traceback (most recent call last):
  File "some_process.py", line 16, in <module>
    main()
  File "some_process.py", line 11, in main
    raise Exception
Exception
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Users/kyleknap/Documents/GitHub/aws-cli/awscli/customizations/s3/executor.py", line 164, in run
    bytes_print(data)
  File "/Users/kyleknap/Documents/GitHub/aws-cli/awscli/customizations/s3/utils.py", line 366, in bytes_print
    sys.stdout.write(statement)
IOError: [Errno 32] Broken pipe
```
We will look into fixing this.

**Comment by tlunter** [comment]
@kyleknap Thanks!

**Comment by kyleknap** [comment]
With the release of 1.10.57. This bug is now fixed. Rerunning the script, I now get it successfully erroring out and exiting:
```
$ aws s3 cp s3://mybucketfoo/100MB - | python some_process.py
Traceback (most recent call last):
  File "some_process.py", line 16, in <module>
    main()
  File "some_process.py", line 11, in main
    raise Exception
Exception

[Errno 32] Broken pipe
$ echo $?
1
```

Resolving issue

**Comment by tlunter** [comment]
Thanks @kyleknap !
