### ISSUE TITLE
"list indices must be integers, not dict" error for data-pipeline definitions that have a "values" object

### ISSUE THREAD

**Issue by dventimi** [aws/aws-cli#1179]
The AWS DataPipeline developer guide (https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-custom-templates.html) gives example JSON for parameter values wherein the values are in an array of objects:

```javascript
{
  "values":[{
      "myS3OutputLoc":"myOutputLocation"
  }]
}
```

This seems not to be correct, and causes the error shown in the subject line.  If, however, the value objects are provided not as an array of objects, then it works:

```javascript
{
  "values":{
      "myS3OutputLoc":"myOutputLocation"
  }
}
```

Either the documentation or the code should change.  I vote for the former.

**Comment by kyleknap** [comment]
Yep, you are correct. It looks like the documentation needs to be updated here. I will try to get this updated.

**Comment by kyleknap** [comment]
Looks like the documentation has been updated. I tested it out myself and it works. Closing issue.
