### ISSUE TITLE
If "Default region name" is not properly set you get a python error message

### ISSUE THREAD

**Issue by bawalsh3000** [aws/aws-cli#1194]
I attempted the following on ubuntu 14.04.2 LTS :
```
aws ec2 describe-regions
```
About 10 secs later, I got:
```
('Connection aborted.', gaierror(-2, 'Name or service not known'))
```
After an embarrassingly long amount of time trying to debug, I figured out I had set my default region to `us-west-2a` when it should've been `us-west-2` -- my bad. I think in this case the fact that the error message came from python led me astray ( I spent a lot of time checking my python setup instead of my aws config). If possible, it would be nice to have an aws specific error message, something along the lines of "Endpoint not found, check aws configuration"

**Comment by jamesls** [comment]
I agree we should clean up these error messages, there's a related issue in our botocore library (that we use to make AWS requests) for improving this as well: https://github.com/boto/botocore/issues/339.  I'll see what I can add.

**Comment by binaryanomaly** [comment]
+1
thx to this issue I was able to figure out what was wrong

**Comment by kyleknap** [comment]
I believe that this was fixed with this pull request: https://github.com/boto/botocore/pull/493

For me when I wipe out my configured region, I get the following:
```
$ aws ec2 describe-regions
You must specify a region. You can also configure your region by running "aws configure".
```

Closing issue. Feel free to reopen the issue if you have any subsequent requests or comments to further expand the error text.

**Comment by darkn3rd** [comment]
I am having this issue with `awscli (1.11.32)`
```
$ aws ec2 describe-regions
You must specify a region. You can also configure your region by running "aws configure".
$ pip list | grep aws
$ cat ~/.aws/config
[default]
region = us-west-2
output = json
```
