### ISSUE TITLE
"aws configure set" mixes up updating security token

### ISSUE THREAD

**Issue by zms** [aws/aws-cli#1197]
Calling _aws configure set_ updates _$HOME/.aws/credentials_ when asked to update aws_access_key and aws_secret_key but aws_security_token is placed in _$HOME/.aws/config_.  This would be okay if subsequent command invocations still managed to read both the files.  However, subsequent commands fail with:
> A client error (InvalidClientTokenId) occurred when calling the ListAccessKeys operation: The security token included in the request is invalid.

If I move the security token manually from _$HOME/.aws/config_ to _$HOME/.aws/credentials_, commands work.  Attempted hinting at the file to use by adjusting AWS_CONFIG_FILE and AWS_CREDENTIAL_FILE variables but no luck.

What am I doing wrong?

**Comment by jamesls** [comment]
`aws_security_token`is supported for backwards compatibility reasons, but to be consistent with other SDKs, we suggest using `aws_session_token`.

**Comment by jamesls** [comment]
Ah, it looks like our readme still mentions this value.  I double checked the rest of our docs and I believe they all use `aws_session_token`.  I'll get our readme updated.
