### ISSUE TITLE
aws s3 cp only grants a specific permission to one account if multiple are given on command line

### ISSUE THREAD

**Issue by rschultheis** [aws/aws-cli#1203]
This command results in an s3 object where only account-2 is granted read permissions:

````
aws s3 cp <some_file> s3://<some_bucket>/ --grants read=emailaddress=account-1@one.com --grants read=emailaddress=account-2@two.com
````

If I flip the --grants arguments, then only account-1 is granted read permissions:

````
aws s3 cp <some_file> s3://<some_bucket>/ --grants read=emailaddress=account-2@two.com --grants read=emailaddress=account-1@one.com
````

It only grants to the last account given for a specific grant (read in this example).

I can grant different grants to various account.  For example this works fine:

````
aws s3 cp <some_file> s3://<some_bucket>/ --grants full=emailaddress=account-1@one.com --grants read=emailaddress=account-2@two.com
````

But attempting to grant the same permission to multiple account does not seem to work.

Using version: aws-cli/1.7.8 Python/2.7.5 Darwin/13.4.0

**Comment by kyleknap** [comment]
Oh this is something that I improved in the documentation recently. Look for the description of the ``--grant`` parameter: http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

You need to specify it as:
```
--grants read=emailaddress=account-2@two.com,emailaddress=account-1@one.com
```

Closing for now. Please reopen if this does not work for you.

**Comment by rschultheis** [comment]
Documentation is clear now, thank you!
