### ISSUE TITLE
Use filter "launch-time" to find all instances newer than X date?

### ISSUE THREAD

**Issue by poolpog** [aws/aws-cli#1209]
I'd like to run a filter that searches as:

"Find all instances launched within the last 30 days"

Using Linux "find" command as an example, something like

find . -mtime -30

Is there any way to do this with "aws ec2 describe-instances --filters ..."

For example, this works, but doesn't do what I want:

aws ec2 describe-instances --filters "Name=launch-time,Values=2015-03\*"

**Comment by poolpog** [comment]
From what I can tell, this isn't possible. One must gather a list of instances and do date range filtering onesself. Seems that "boto" - the Python library - can't do this, either. Finally, the AWS UI (web console) *can* do this, so I know it is possible.

I'd love to see this added as a feature. How can I convert this issue to a feature request?

**Comment by danielgtaylor** [comment]
@poolpog it's actually possible to do something like this today with a [JMESPath query](http://jmespath.org/examples.html#filters-and-multiselect-hashes) that uses filters and multiselect hashes. For example:

```bash
aws ec2 describe-instances --query 'Reservations[0].Instances[?LaunchTime>=`2015-03-01`].{id: InstanceId, type: InstanceType, launched: LaunchTime}'
```

If you want to get really fancy you can calculate the date automatically as well:

```bash
#!/bin/bash

if date -v-30d > /dev/null 2>&1; then
    # BSD systems (Mac OS X)
    DATE=date -v-30d +%Y-%m-%d
else
    # GNU systems (Linux)
    DATE=date --date="-30 days" +%Y-%m-%d
fi

aws ec2 describe-instances --query 'Reservations[0].Instances[?LaunchTime>=`$DATE`].{id: InstanceId, type: InstanceType, launched: LaunchTime}'
```

Either way, the output will look something like the following:

```bash
[
    {
        "type": "t2.medium",
        "id": "i-123456789",
        "launched": "2015-03-11T18:40:24.000Z"
    }
]
```

Please let me know if you have any other questions!

**Comment by poolpog** [comment]
Thanks! This sounds promising. However, I get a parse error, for example:

    > aws ec2 describe-instances --query "Reservations[0].Instances[?LaunchTime>=2015-02-10].{id: InstanceId, type: InstanceType, launched: LaunchTime}"

    Bad value for --query Reservations[0].Instances[?LaunchTime>=2015-02-10].{id: InstanceId, type: InstanceType, launched: LaunchTime}: Invalid token.: Parse error at column 39 near token "2015" (NUMBER) for expression:
    "Reservations[0].Instances[?LaunchTime>=2015-02-10].{id: InstanceId, type: InstanceType, launched: LaunchTime}"
                                            ^

Perhaps my version of aws cli doesn't support this syntax?

    > aws --version
    aws-cli/1.7.6 Python/2.7.5 Darwin/13.4.0

**Comment by danielgtaylor** [comment]
@poolpog sorry, I was mistaken about exactly how the response works. Here is a better example:

```bash
aws ec2 describe-instances --query 'Reservations[].Instances[?LaunchTime>=`2014-01-01`][].{id: InstanceId, type: InstanceType, launched: LaunchTime}'
```

Note that we request all reservations via `[]` instead of `[0]`, and then flatten the filtered instance lists (also via `[]` after the filter step where we select based on launch time). In the output I'm now getting multiple instances from different reservations.

I've updated the posts above to use the fixed syntax as well, should others come and look at them with a similar question to yours.

**Comment by danielgtaylor** [comment]
I believe this should solve your issue, so I'm going to close it. Feel free to reopen if you have other questions about this use case!

**Comment by poolpog** [comment]
Thanks, that helped enormously.

**Comment by robintanner** [comment]
What about if I want to do a date range? Between two dates? I was trying this but it is not working

`aws s3api list-objects-v2 --bucket tb-nonprod-data --prefix qa/staging/hybris/orders --fetch-owner --query "reverse(sort_by(Contents[?LastModified>='2017-06-26',?LastModified<='2018-06-27'], &LastModified)[*].{Key:Key, LastModified:LastModified, Size:Size, Owner:Owner.DisplayName})" --output table --max-items 20`

**Comment by dragosrosculete** [comment]
For me it worked like this when trying to get the snapshots older then 7 days
#!/bin/bash

SnapshotDate=`date --date="-7 days" +%Y-%m-%d`
Region='eu-central-1'

aws ec2 describe-snapshots --region $Region --query 'Snapshots[?StartTime<=`'$SnapshotDate'`]' --filters Name=description,Values=mongo-*

I had to use `'the date'`  in order to pass it correctly .

**Comment by mstruser** [comment]
I am trying to move some files from one bucket to another bucket in s3, but I want to move files which are modified in last two days only. I am trying to run below mentioned command but getting the bad value for query error, I tried what @poolpog  has suggested but doesn't work out for me, please find the below command:
aws s3 ls --recursive s3://art-optimizelyx-data-archive/ --query '[?Last-Modified>`2018-09-29`]'

**Comment by AjithKumar-Raj** [comment]
What about getting all instances newer than X hours?

**Comment by ringerc** [comment]
It would be a huge help to see the *server-side filter API* extended to support simple relational operators and negation, such that we could write filters like:

```
[
    { 'Name': 'launch-time', Values: ['2019-06-20T12:40:28.028336'], 'Operator': '>'},
    { 'Name': 'launch-time', Values: ['2010-01-01T00:00:00.000000'], 'Operator': '<'}
]
```

or however you like to spell it.

**Comment by boboem123** [comment]
@AjithKumar-Raj - I know this is late but I've just had this exact issue and hopefully it'll help someone else

aws ec2 describe-instances --query "Reservations[].Instances[].[InstanceId,LaunchTime]" --output text

shows the output is in date '+%Y-%m-%dT%H:%M:%S.000Z' format
Therefore you can do something like
--query "Reservations[].Instances[?LaunchTime<='$(date --date='-12 hours' '+%Y-%m-%dT%H')']
for instances older than 12 hours

--query "Reservations[].Instances[?LaunchTime>='$(date --date='-20 minutes' '+%Y-%m-%dT%H:M')']
for instances NEWER than 20 minutes

Note: You will need to include the granularity of the filter (e.g. %M if using minutes), you can't simply just change the subtraction type and expect it to work as it's the output of the $(date xxx) command which is used for the comparison.

**Comment by AjithKumar-Raj** [comment]
thanks for the help

**Comment by RichardTMiles** [comment]
Note `date --date` is not an available flag on osx. You can refer to links below 

date -v -1d '+%Y-%m-%dT%H:%M:%SZ'  

https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-datetime-strings.html
https://apple.stackexchange.com/questions/115830/shell-script-for-yesterdays-date
