### ISSUE TITLE
aws s3 sync stucks with trickle

### ISSUE THREAD

**Issue by ltagliamonte** [aws/aws-cli#1215]
Dear developers,
i'm implementing a backup script that uses S3 as backup destination and the aws cli command in script get stucked during the upload (never for the same file)
To smooth the outgoing bandwidth i decided to use http://linux.die.net/man/1/trickle.
I'm running on Ubuntu 12.04.4
`Linux ip-10-0-1-147 3.8.0-37-generic #53~precise1-Ubuntu SMP Wed Feb 19 21:37:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
the command that i'm running is:

`/usr/bin/trickle -s -u 5000 /usr/local/bin/aws s3 sync ${LOCAL} ${DEST}`

the strace of the aws cli pid is:

```
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
gettimeofday({1426072840, 387624}, NULL) = 0
gettimeofday({1426072840, 387714}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
gettimeofday({1426072840, 389974}, NULL) = 0
gettimeofday({1426072840, 390045}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 4000})  = 0 (Timeout)
gettimeofday({1426072840, 394312}, NULL) = 0
gettimeofday({1426072840, 394392}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 8000})  = 0 (Timeout)
gettimeofday({1426072840, 402669}, NULL) = 0
gettimeofday({1426072840, 402742}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 16000}) = 0 (Timeout)
gettimeofday({1426072840, 419018}, NULL) = 0
gettimeofday({1426072840, 419099}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 32000}) = 0 (Timeout)
gettimeofday({1426072840, 451372}, NULL) = 0
gettimeofday({1426072840, 451456}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
gettimeofday({1426072840, 501729}, NULL) = 0
gettimeofday({1426072840, 501814}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
gettimeofday({1426072840, 552075}, NULL) = 0
gettimeofday({1426072840, 552146}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
gettimeofday({1426072840, 602418}, NULL) = 0
gettimeofday({1426072840, 602503}, NULL) = 0
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
gettimeofday({1426072840, 652829}, NULL) = 0
gettimeofday({1426072840, 652926}, NULL) = 0
...
```

aws-cli version:
`aws-cli/1.7.13 Python/2.7.3 Linux/3.8.0-37-generic`
boto version:
`2.2.2`

I'm not getting any errors without trickle.
Please if you need more info let me know.
Regards
L.

**Comment by danielgtaylor** [comment]
@ltagliamonte I was able to successfully run a few `aws s3 sync` commands using `trickle` like in your example above. It never got stuck or timed out. Does this happen every time for you? Can you run `aws` with `--debug`? Do you see exactly where it is getting stuck?

**Comment by ltagliamonte** [comment]
@danielgtaylor Thank you for a first issue review, yes it is always happening for me, here the output with the --debug:

'2015-03-12 07:18:06,343 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2015-03-12 07:18:06,343 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message=u'upload: ../../Index.db to s3://backup-us-east-1/Index.db', error=False, total_parts=None, warning=None)
2015-03-12 07:18:06,386 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140305592456960)>
2015-03-12 07:18:06,386 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, started daemon 140305105942272)>'

i forgot to mention the i'm also using the following options:
--no-guess-mime-type --only-show-errors (--debug)

Please let me know if you need more info.
Regards
L.

**Comment by kyleknap** [comment]
@ltagliamonte 

My guess is that since you are limiting the upload bandwidth, it is causing the threads that are uploading your data to starve (the threads are overly competing for the limited bandwith). This usually results in connection timeouts (as you are seeing in your strace). I would suggest reconfiguring your s3 transfer configuration to use less threads. Here is a document on how you can do that: https://github.com/aws/aws-cli/blob/develop/awscli/topics/s3-config.rst

Let me know how that works for you. Also if you could give us a full copy of the debug logs that would be helpful as well if problems still persists, instead of a partial copy of the debug logs.

**Comment by clementbethuys** [comment]
I was hit by the same problem, 
my version: aws-cli/1.7.24 Python/2.7.8 Linux/3.16.0-24-generic

by setting default.s3.max_concurrent_requests lower it seems to have succeded

**Comment by djwilli** [comment]
I am also seeing this issue.  When I run my script with Trickle in standalone added in, the command script hangs.

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 23, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 19, in main
    return awscli.clidriver.main()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 50, in main
    return driver.main()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 184, in __call__
    parsed_globals)
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/commands.py", line 181, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 436, in _run_main
    return cmd.run()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 727, in run
    file_list.append(components[i].call(files[i]))
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/s3handler.py", line 113, in call
    self.executor.wait_until_shutdown()
  File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/executor.py", line 126, in wait_until_shutdown
    thread.join(timeout=1)
  File "/usr/lib/python2.7/threading.py", line 678, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 262, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by h9k** [comment]
Same issue here, on Debian 8.6, trickle 1.07-10 and aws-cli/1.11.28 Python/2.7.9 Linux/4.4.35-1-pve botocore/1.4.85.
I run the command as so:
`nice -n 19 ionice -c3 trickle -s -u 50000 timeout 1h /usr/local/bin/aws s3 sync /source/path/ s3://mybucket/foo/ --quiet`
Removing trickle from the equation gets rid of  the hanging problem, but causes high IO load because of swap (weird), which is why I wanted to use trickle in the first place...

**Comment by JordonPhillips** [comment]
The solution, as Kyle mentioned, is to reduce the number of threads by lowering `max_concurrent_requests] (docs [here](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html#cli-aws-help-s3-config)). I'll update those docs to mention trickle.
