### ISSUE TITLE
`aws s3 cp` and `aws s3 mv` don't support adding `x-amz-meta` headers

### ISSUE THREAD

**Issue by rouge8** [aws/aws-cli#1218]
It would be useful to set custom `x-amz-meta` headers when uploading files to S3 buckets, but neither `aws s3 cp` nor `aws s3 mv` support this.

**Comment by flisky** [comment]
+1

**Comment by tim-kos** [comment]
+1

This is an essential feature, which should also be easy to implement ...

**Comment by kyleknap** [comment]
Closing this issue out in favor of https://github.com/aws/aws-cli/issues/1561. Let's use that issue to track this feature as if we add it to the ``sync``, we will also add it to ``cp`` and ``mv``.
