### ISSUE TITLE
aws datapipeline --schedule-interval parameter seems not to work

### ISSUE THREAD

**Issue by dventimi** [aws/aws-cli#1224]
Tried this command:

```
aws datapipeline list-runs --pipeline-id $ID --schedule-interval "2015-03-17,2015-03-18"
```

Produced this error:

```
A client error (InvalidRequestException) occurred when calling the QueryObjects operation: The given input is not valid: Operator: BETWEEN not suppoerted for field @scheduleStartTime in query
```

Presumably, the `--schedule-interval` parameter has the same format as the `--start-interval` parameter, namely as a comma-separated pair of dates.  I mention that because the similar operation using `--start-interval` succeeds without error:

```
aws datapipeline list-runs --pipeline-id $ID --start-interval "2015-03-17,2015-03-18"
```

Note also that there's a typo in the error message. The word "supported" is misspelled.

**Comment by kyleknap** [comment]
I can reproduce this issue. Working on a fix.
