### ISSUE TITLE
Windows Error 

### ISSUE THREAD

**Issue by SimplyCorey** [aws/aws-cli#1226]
Hello,

I am receiving the following error on a Windows Server 2008 after a fresh install.

    Traceback (most recent call last):
      File "aws", line 19, in <module>
      File "awscli\clidriver.pyc", line 16, in <module>
      File "botocore\session.pyc", line 26, in <module>
      File "botocore\config.pyc", line 18, in <module>
      File "botocore\compat.pyc", line 72, in <module>
      File "email\message.pyc", line 16, in <module>
      File "email\charset.pyc", line 13, in <module>
      File "email\base64mime.pyc", line 40, in <module>
      File "email\utils.pyc", line 27, in <module>
      File "random.pyc", line 885, in <module>
      File "random.pyc", line 97, in __init__
        so it is better to simply reseed.
      File "random.pyc", line 113, in seed
        This fixes the problem with randint() which includes the
        WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly

I am unable to run any commands including aws --debug.  Any help in solving this would be much appreciate and please let me know if you need anything else to further troubleshoot this.

Thank you.

**Comment by kyleknap** [comment]
Interesting. Was this on an ec2 instance? Also is it possible to run:
```
aws --version
```
Knowing the version would be great.

**Comment by SimplyCorey** [comment]
It was not on a EC2 instance.  I can not run aws--version.  i downloaded the 32 bit copy today from aws.amazon.com/cli for windows.

**Comment by kyleknap** [comment]
Thanks. We will look into it.

**Comment by SimplyCorey** [comment]
If it helps, I installed the 64 bit version first by mistake.  I know that 64 bit is not supported on windows server 2008.  I uninstalled it and then installed the 32 bit version.

**Comment by kyleknap** [comment]
Cool, yeah any information that you can provide to help us reproduce it would be awesome.

**Comment by SimplyCorey** [comment]
Where could I download an older copy of AWS CLI that has a past python release built into it?  This seems to be a bigger bug with Python because it is showing up in multiple projects.  I would like to test an older copy and see if I have the same issues.

http://stackoverflow.com/questions/27904936/python-exe-file-crashes-while-launching-on-windows-xp

**Comment by SimplyCorey** [comment]
Just an update.  This issue only appears to affect the .msi files.  Using python 2.7.9 and PIP, I was able to install AWS CLI just fine on Windows Server 2008.

**Comment by jasonirwinme** [comment]
I'm getting this same failure on a fresh Amazon AMI for Windows 2003 32 bit.

**Comment by vyarmak** [comment]
Got the same problem. Tested with older installation of AWSCLI32.msi (I had it on other server) and everything works perfect.

**Comment by deliverymanager** [comment]
Got the same error on a clean Windows XP SP3 computer.

**Comment by jamesls** [comment]
I'll need to do some digging here.  It seems that on anything pre windows 2008 r2, the 32bit MSI installer is not working correctly.  I'll see what I can find out.

In the meantime, the workaround is to install via pip install of the MSI.

**Comment by jamesls** [comment]
Version 1.7.35 of the CLI fixes this issue.  You should be able to use the MSI installers again for windows 2008.
