### ISSUE TITLE
1.7.15 issue - cloudfront commands giving broken output and are not currently working

### ISSUE THREAD

**Issue by PhillipHolmes** [aws/aws-cli#1234]
Some time between the middle of last week and the weekend the cloudfront commands stopped working for me on multiple machines.

After upgrading (and breaking):
```
$aws --version
aws-cli/1.7.15 Python/2.7.6 Darwin/14.1.0
```

The following command now gives this output:
```
$aws cloudfront list-distributions

u'ListDistributions2014_11_06'
```

Another command example (same result for valid data as well as the test below):
```
$aws cloudfront create-invalidation --distribution-id 1234 --invalidation-batch "{}"

u'CreateInvalidation2014_11_06'
```

`aws configure set preview.cloudfront true` was run previously - recreating the .aws/config or config/credentials file either manually or by using `aws configure` does not resolve the issue.

version 1.7.14 was working (~4 days ago), however I can't find that version available as a regression download - I'll keep looking as this has broken our ability to automatically deploy our website and then automatically invalidate old content within CloudFront.

**Comment by PhillipHolmes** [comment]
downgrading was easier than I thought it would be by using pip:

```
$sudo pip install awscli==1.7.14
Downloading/unpacking awscli==1.7.14
  Downloading awscli-1.7.14.tar.gz (298kB): 298kB downloaded
  Running setup.py (path:/private/tmp/pip_build_root/awscli/setup.py) egg_info for package awscli
...
```

I've downgraded and the commands are working once more.

I'll force using 1.7.14 until the issue with 1.7.15+ is fixed.

**Comment by jamesls** [comment]
Fixed via https://github.com/boto/botocore/pull/497, tests added in https://github.com/aws/aws-cli/pull/1237
