### ISSUE TITLE
aws ecs describe-container-instances does not understand `--output` option

### ISSUE THREAD

**Issue by RichardBronosky** [aws/aws-cli#1236]
For some odd reason, the `aws ecs describe-container-instances` command accepts `--query`, but not `--output`. This is a bit ugly in this command.

    aws ec2 describe-instances --instance-ids $(\
      aws ecs describe-container-instances --cluster $cluster --container-instances $(\
        aws ecs list-container-instances --cluster $cluster --query "containerInstanceArns[-1]" --output text\
      ) --query "containerInstances[0].ec2InstanceId" | tr -d '"'\
    ) --query "Reservations[0].Instances[0].PublicDnsName"

Where I have to get the ec2InstanceId via query but then trim the `"` chars with the `tr` command so that it can be used as an argument in another command.

If someone can confirm that this omission is not by design, I'll submit a pull request to fix it.

**Comment by jamesls** [comment]
I'm not seeing that issue.  Can you confirm the output by just running the describe-container-instances command directly.  For example, I tried:

```
$ aws ec2 describe-container-isntances --cluster <cluster> --container-instances <values> --output json

< I see JSON data come back>

$ aws ec2 describe-container-isntances --cluster <cluster> --container-instances <values> --output table

< I see table output>

$ aws ec2 describe-container-isntances --cluster <cluster> --container-instances <values> --output text

< I see text output>

```

Do you see the same behavior from running the above commands?

**Comment by RichardBronosky** [comment]
Okay. I'm now seeing the same thing you are. Unfortunately I was working on a temporary env and don't have access to the history to figure out exactly how I came to the conclusion that `--output` was getting the error `Unknown options: --output, text`. If I see it again I'll let you know.
