### ISSUE TITLE
multiple filters not working for describe-snapshots

### ISSUE THREAD

**Issue by dmusci** [aws/aws-cli#124]
When I try to use multiple filters for "aws ec2 describe-snapshots", not all filters are being applied.
# aws ec2 describe-snapshots --owner self --filter='{"name":"status","values":"completed"}' --filter='{"name":"start-time","values":"2013-05-20T11:46:40.000Z"}' --filter='{"name":"volume-id","values":"vol-3d1bb40d"}'

{
    "ResponseMetadata": {
        "RequestId": "f8af4548-aa79-43aa-9e5d-6a64581dd54d"
    },
    "Snapshots": [
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-9788ecb4 from vol-3d1bb40d",
            "VolumeId": "vol-3d1bb40d",
            "State": "completed",
            "VolumeSize": 1,
            "StartTime": "2013-05-17T13:38:06.000Z",
            "SnapshotId": "snap-30ee5f00",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-3d1bb40d",
            "VolumeId": "vol-3d1bb40d",
            "State": "completed",
            "VolumeSize": 1,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-e8c574d8",
            "OwnerId": "445015072241",
            "Progress": "100%"
        }
    ]
}#

As you can see, the last filter is applied, but the start-time filter is not applied.  Additionally, it cannot be determined if the first filter is working either, as all snapshots for the volume-id have status complete.  When I try ordering the filters differently, I see consistently that only the last filter is being applied.

The following command provides a list of all of my snapshots with status completed, regardless of start-time or volume-id:

aws ec2 describe-snapshots --owner self --filter='{"name":"start-time","values":"2013-05-20T11:46:40.000Z"}' --filter='{"name":"volume-id","values":"vol-3d1bb40d"}' --filter='{"name":"status","values":"completed"}' 

This command provides a list of all snapshots created at the specified start-time:
# aws ec2 describe-snapshots --owner self --filter='{"name":"volume-id","values":"vol-3d1bb40d"}' --filter='{"name":"status","values":"completed"}' --filter='{"name":"start-time","values":"2013-05-20T11:46:40.000Z"}'

{
    "ResponseMetadata": {
        "RequestId": "ba2e9caa-73bc-4f53-8082-93d1545790f2"
    },
    "Snapshots": [
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-85c46ab5",
            "VolumeId": "vol-85c46ab5",
            "State": "completed",
            "VolumeSize": 60,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-fcc574cc",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-ed1cb3dd",
            "VolumeId": "vol-ed1cb3dd",
            "State": "completed",
            "VolumeSize": 50,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-ffc574cf",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-c51cb3f5",
            "VolumeId": "vol-c51cb3f5",
            "State": "completed",
            "VolumeSize": 50,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-e2c574d2",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-ce1cb3fe",
            "VolumeId": "vol-ce1cb3fe",
            "State": "completed",
            "VolumeSize": 1,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-e5c574d5",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-3d1bb40d",
            "VolumeId": "vol-3d1bb40d",
            "State": "completed",
            "VolumeSize": 1,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-e8c574d8",
            "OwnerId": "445015072241",
            "Progress": "100%"
        },
        {
            "Description": "Created by CreateImage(i-e633eec4) for ami-2189ed02 from vol-291bb419",
            "VolumeId": "vol-291bb419",
            "State": "completed",
            "VolumeSize": 20,
            "StartTime": "2013-05-20T11:46:40.000Z",
            "SnapshotId": "snap-ebc574db",
            "OwnerId": "445015072241",
            "Progress": "100%"
        }
    ]
}#

The version I am using is reported as:
aws-cli/0.9.3 Python/2.6.8 Linux/3.4.43-43.43.amzn1.x86_64

**Comment by kumaran85** [comment]
How to filter between  a period of weeks snapshot backup?. For instance, one week backup.
