### ISSUE TITLE
[opsworks create-deployment] better --custom-json description

### ISSUE THREAD

**Issue by plentz** [aws/aws-cli#1243]
http://docs.aws.amazon.com/cli/latest/reference/opsworks/create-deployment.html#synopsis

in the `--custom-json (string)` parameter. it says "It is used to override the corresponding default stack configuration JSON values". But it really should say "It _can_ be used to override the corresponding default stack configuration JSON values".

**Comment by jamesls** [comment]
I'll pass this feedback along to the doc team, could you clarify what was confusing?

**Comment by plentz** [comment]
It's a bit confusing that you actually can override just some json attributes, it won't will override the entire "default json".

**Comment by justnance** [comment]
@plentz - Thank you for your feedback and reporting this issue.  Your request has been re-forwarded to our documentation team for review.  Thanks for your patience.

**Comment by justnance** [comment]
@plentz - Our documentation has been updated with the following:

> You can use this parameter to override some corresponding default stack configuration JSON values."

doc links.
http://docs.aws.amazon.com/cli/latest/reference/opsworks/create-deployment.html#synopsis
https://docs.aws.amazon.com/cli/latest/reference/opsworks/create-deployment.html#create-deployment

closing issue.
