### ISSUE TITLE
[opsworks] describe-rds-db-instances don't show DbPassword

### ISSUE THREAD

**Issue by plentz** [aws/aws-cli#1244]
Running: `aws opsworks describe-rds-db-instances --region='us-east-1' --stack-id=$STACK_ID ` it won't show DbPassword... instead, it shows `"*****FILTERED*****"`:
```json
{
    "RdsDbInstances": [
        {
            "Engine": "mysql", 
            "StackId": "xxx", 
            "MissingOnRds": false, 
            "Region": "us-west-2", 
            "RdsDbInstanceArn": "arn:aws:rds:us-west-2:062412373208255:db:qa-db1", 
            "DbPassword": "*****FILTERED*****", 
            "Address": "xxx.rds.amazonaws.com", 
            "DbUser": "xxx", 
            "DbInstanceIdentifier": "qa-db1"
        }
    ]
}
```

**Comment by jamesls** [comment]
Just to clarify, are you saying that when you run the `describe-rds-db-instances` command, the response currently displays `******FILTERED******` instead of the actual `DbPassword`?

**Comment by plentz** [comment]
@jamesls exactly

**Comment by jamesls** [comment]
Interesting.  Then that response is coming directly from the service response.  Let me follow up with the opsworks team and see what they say.

**Comment by plentz** [comment]
I've just found another thing: http://docs.aws.amazon.com/cli/latest/reference/opsworks/describe-layers.html

If you see the output in the example, it shows

`"MysqlRootPassword": "*****FILTERED*****",`

**Comment by tkaschwig** [comment]
The "*****FILTERED*****" output directly comes from the OpsWorks API. For security reason we stopped returning passwords and other sensitive data in the describe calls. These attributes are now basically read only.

We have now updated the documentation accordingly:
http://docs.aws.amazon.com/opsworks/latest/APIReference/API_RdsDbInstance.html

Thank you for your feedback and sorry for any inconvenience caused.

**Comment by plentz** [comment]
@tkaschwig cool. I just have one final question: if I can't retrieve the database password via the aws-cli, what's the point in informing it when attaching a RDS database to my OpsWorks layer?

**Comment by plentz** [comment]
@tkaschwig another thing, you need to update the docs where http://docs.aws.amazon.com/cli/latest/reference/opsworks/describe-rds-db-instances.html
