### ISSUE TITLE
No gp2 support for launch configurations?

### ISSUE THREAD

**Issue by mattfiocca** [aws/aws-cli#1266]
I'm testing out launch configuration creation with the cli, with device mappings, and when i try to specify the VolumeType as gp2 for a configuration, i get this error:

`Invalid value ('VolumeType') for param element of list:BlockDeviceMappings of type list`

Here is my call:

```
$ aws autoscaling create-launch-configuration \
--launch-configuration-name "launch-config-test" \
--image-id [INSERT_AMI_ID_HERE] \
--key-name [INSERT_KEY_NAME_HERE] \
--security-groups [INSERT_SG_HERE] \
--instance-type t2.medium \
--block-device-mappings "[{\"DeviceName\": \"/dev/sda1\",\"Ebs\":{\"VolumeType\":\"gp2\",\"VolumeSize\":8}}]"
```

According to the docs, `VolumeType` is a property of Ebs and should be supported:

http://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-launch-configuration.html?highlight=autoscaling

Is there something wrong with the way i'm making the call? Is gp2 not supported through the API? gp2 works through the console, but i'd really like to be able to use it here as well.

**Comment by kyleknap** [comment]
I did not have an issue running the command. What version of the CLI are you using? I am using 1.7.19. If you are not using the latest version of the CLI, I would suggest upgrading.

**Comment by mattfiocca** [comment]
When i run `$ aws --version`, i get:

```
aws-cli/1.2.9 Python/3.4.0 Linux/3.13.0-44-generic
```

I then ran `$ pip install --upgrade awscli` then `$ aws --version` again and I get the same version as above. This is on a new Ubuntu 14.04 AWS EC2.

```
$ which aws
/usr/local/bin/aws
```

**Comment by mattfiocca** [comment]
Ok, i think i just needed to refresh my shell session after the update. `$ pip show awscli`:

```
Name: awscli
Version: 1.7.19
Location: /usr/local/lib/python2.7/dist-packages
Requires: botocore, bcdoc, colorama, docutils, rsa
```

And I can now use gp2 in my launch configs!

Thanks for your help, this is closed
