### ISSUE TITLE
Incorrect exit status codes

### ISSUE THREAD

**Issue by jdc0589** [aws/aws-cli#1269]
Most of the aws cli subcommands return a `0` status code on process termination, regardless of what actually happened. This makes it pretty nasty to integrate in a build process.

*e.g.* I want to validate my cloudformation template as a precondition to a Jenkins job that rebuilds/updates my cloudformation stack. 

```bash
aws s3 cp cloudformation.json s3://mybucket/tmp.json

aws cloudformation validate-template --template-url s3://mybucket/tmp.json
>>> A client error (ValidationError) occurred when calling the ValidateTemplate operation: Template format error: JSON not well-formed. (line 2126, column 9)

echo $!
>>> 0
```

My only option at this point for failure checking is to look for the string "error" in the output of the `validate-stack` command, and hope it will always be there for every error condition.

**Comment by kyleknap** [comment]
@jdc0589 
What version of the CLI are you using? You can check it by running ``aws --version``. I tried it with the latest version 1.7.19 and I am getting an rc of 255, which is what is expected.

**Comment by jdc0589** [comment]
oops. I was using `$!` instead of `$?`. my bad.
