### ISSUE TITLE
`ls' works for a given bucket, but `sync' says the bucket does not exist.

### ISSUE THREAD

**Issue by cstrahan** [aws/aws-cli#1276]
$ aws s3 ls --profile blog s3://www.cstrahan.com --region us-east-1
                               PRE 2009/
                               PRE 2010/
                               PRE 2011/
                               PRE 2012/
                               PRE 2013/
                               PRE css/
                               PRE images/
                               PRE js/
    2013-03-18 12:53:54         13 CNAME
    2013-04-26 15:47:30        221 Gemfile
    2013-04-26 15:47:30       1406 Gemfile.lock
    2013-03-18 12:54:34        270 README.textile
    2013-04-26 15:47:30       1235 TODO
    2013-04-26 15:47:30       1735 about.html
    2013-04-26 15:47:30     229207 atom.xml
    2013-03-18 12:53:59      82726 favicon.ico
    2013-04-26 15:47:31       2278 index.html
    
    $ aws s3 sync . s3://wwww.cstrahan.com  --profile blog --region us-east-1
    A client error (NoSuchBucket) occurred when calling the ListObjects operation: The specified bucket does not exist
    Completed 1 part(s) with ... file(s) remaining

Anything I can do to help resolve this?

**Comment by cstrahan** [comment]
I'm getting by with `s3cmd` for now, but I wish I could use `aws` for all my aws/s3 needs...

**Comment by danielgtaylor** [comment]
@cstrahan running with the `--debug` option should give you more information about what is being sent over the wire. I'd also confirm that the bucket names really are the same because in your example above your `s3 sync` example uses a bucket name that has four `w`s instead of three.

**Comment by cstrahan** [comment]
> I'd also confirm that the bucket names really are the same because in your example above your `s3 sync` example uses a bucket name that has four `w`s instead of three.

@danielgtaylor Damn, that's embarrassing. I must have checked that 10 times. Sorry for the noise.

**Comment by danielgtaylor** [comment]
Happens to the best of us, no worries! :+1:

**Comment by captainRonak** [comment]
> @cstrahan running with the `--debug` option should give you more information about what is being sent over the wire. I'd also confirm that the bucket names really are the same because in your example above your `s3 sync` example uses a bucket name that has four `w`s instead of three.

Your evaluation helped me also, I was also doing Spelling mistake in bucket name.
It is always good that you do the copy paste regarding any object names. Thank you.
