### ISSUE TITLE
Can I get a list of instance types from aws cli?

### ISSUE THREAD

**Issue by StFS** [aws/aws-cli#1279]
euca2ools has the euca-describe-instance-types to get a list of the available instance types.

I can't seem to find a corresponding command in aws-cli. Am I missing something?

**Comment by danielgtaylor** [comment]
@StFS I don't believe that this is currently possible through an API call. You can view all of the instance types here, however:

http://aws.amazon.com/ec2/instance-types/

**Comment by jamesls** [comment]
Closing out issue.  Daniel is correct, there's no API to list the available instance types so we're not able to expose this via the CLI.

**Comment by acme** [comment]
This information is kind of accessible via the AWS Price List API

**Comment by qfissler** [comment]
as well as those two sources, botocore has the list defined in JSON docs. Looking in those is probably the most joined-up way of doing it.

> /usr/local/lib/python2.7/dist-packages $ grep -Rl InstanceType botocore/data/ec2
> botocore/data/ec2/2014-10-01/service-2.json
> botocore/data/ec2/2016-04-01/service-2.json
> botocore/data/ec2/2015-03-01/service-2.json
> botocore/data/ec2/2014-09-01/service-2.json
> botocore/data/ec2/2015-04-15/service-2.json
> botocore/data/ec2/2015-10-01/service-2.json
> /usr/local/lib/python2.7/dist-packages $

**Comment by philiprbrenan** [comment]
A more accessible list is available 30% of the way down at:

http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html

**Comment by gswallow** [comment]
I'm perplexed.  Why is this not a thing?  I see requests for this feature dating from 2012.

Trying to get instance types from spot price history has one major drawback I can identify off the top of my head: t2 instances can't be run as spot.

**Comment by Graham-M** [comment]
Further to @qfissler 's comment, I found them here:

```
$ cat /usr/local/lib/python2.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json \
| jq '.shapes.InstanceType.enum'

[
  "t1.micro",
  "t2.nano",
  "t2.micro",
  "...",
  "d2.8xlarge",
  "f1.2xlarge",
  "f1.16xlarge"
]
```

**Comment by nnsense** [comment]
If is just the list of types what you need, you can play with the `aws ec2 describe-spot-price-history help`, it have a list of types in it and I suppose it's also updated. But, and that's why I'm here as well, I was looking for something that could help while creating instances with aws, and a list is not exactly helpful since the names are pretty similar to each other, it's easy to remember most of them but what would be really usefull is a list of types with processors, memeory, purpose. I don't think would be sich a hard work to do it since aws, to work, it needs internet. Basically a simple, text page to fetch and elaborate from internet would be more than enough. Eventually, I'm writing a script to fetch `https://aws.amazon.com/ec2/instance-types/` and elaborate it with TableExtract but, the day amazon would slightly change that page, I'm off.

**Comment by riteshapatel** [comment]
Oh great. thx.

**Comment by lankygit** [comment]
Not every region - presumably a new feature not yet global - but that's hard to believe as this was added in 2015

https://aws.amazon.com/blogs/aws/aws-price-list-api-update-regional-price-lists/

```
$ aws pricing get-attribute-values --service-code AmazonEC2 --attribute-name instanceType --region eu-west-1

Could not connect to the endpoint URL: "https://api.pricing.eu-west-1.amazonaws.com/"
$
```

**Comment by mdemare** [comment]
`aws pricing help` tells you that there are only two endpoints, including `us-east-1`. So this will work:
```
aws --region us-east-1 pricing get-attribute-values --service-code AmazonEC2 --attribute-name instanceType
```

**Comment by pdomala** [comment]
Check out [ec2types.io](https://ec2types.io). It helps to get around all EC2 Instance Types. You can also search, filter and compare EC2 instance types based on Region. It helps you choose the right instance type based on configuration and budget

**Comment by Bosies** [comment]
I'm currently working on a cloud management system, and my team and I have been exploring the possibility of extracting all instance types despite the lack of an SDK from AWS. We've been considering the idea of using sites like ec2types.io to scrape this information via Selenium and storing all instance types and their information in our database. Has anyone looked into this option as a possible solution to dynamically retrieving and storing instance types?

**Comment by daluu** [comment]
If only sites like that offered an API so we didn't have to scrape the data off UI. This one is open source: https://github.com/powdahound/ec2instances.info, perhaps someone could build a REST wrapper to serve the info over HTTP as JSON for a given query rather than prettified HTML with javascript for interactive manual user queries.

**Comment by paceto256** [comment]
in chrome console:

fetch('https://view-prod.us-east-1.prod.plc1-prod.pricing.aws.a2z.com/pricing/1.0/ec2/region/us-east-2/ondemand/linux/index.json?timestamp='+ (+new Date()).toString())
  .then(function(response) {
    return response.json();
  })
  .then(function(myJson) {
    const res = {};
    myJson.prices.forEach(o => {
      res[o.attributes['aws:ec2:instanceType']] = {
        id: o.attributes['aws:ec2:instanceType'],
        price: o.price.USD,
        memory: o.attributes['aws:ec2:memory'],
        os: o.attributes['aws:ec2:operatingSystem'],
        vcpu: o.attributes['aws:ec2:vcpu'],
        clockSpeed: o.attributes['aws:ec2:clockSpeed'],
      };
    });
    console.log(res);
  });

**Comment by deppfx** [comment]
> 
> 
> Check out [ec2types.io](https://ec2types.io). It helps to get around all EC2 Instance Types. You can also search, filter and compare EC2 instance types based on Region. It helps you choose the right instance type based on configuration and budget

Do you have an API we can query with?

**Comment by thorstenhuhn** [comment]
The current version of the AWS CLI offers a new `describe-instance-types` command for the `ec2` service (see also [AWS CLI Reference](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html)):

```bash
$ aws --version
aws-cli/1.16.304 Python/3.7.5 Darwin/19.2.0 botocore/1.13.40
$ aws ec2 describe-instance-types --filters Name=current-generation,Values=true --query 'sort_by(InstanceTypes, &InstanceType)[].InstanceType'
[
    "a1.large",
    "a1.medium",
    "a1.xlarge",
    "c4.4xlarge",
    "c4.8xlarge",
    "c4.large",
    "c5.12xlarge",
    "c5.4xlarge",
    "c5.xlarge",
...
]
```

**Comment by mooreniemi** [comment]
Just to extend the above, here's a `jq` query that parses what I care about 99% of the time:

```
aws ec2 describe-instance-types --filters Name=current-generation,Values=true | jq ".InstanceTypes | .[] | {name: .InstanceType, memory_in_mib: .MemoryInfo.SizeInMiB, vcpus: .VCpuInfo.DefaultVCpus, disk_in_gb: .InstanceStorageInfo.TotalSizeInGB}" | less
```

Gives you (snippet of full output):

```
{
  "name": "m5zn.large",
  "memory_in_mib": 8192,
  "vcpus": 2,
  "disk_in_gb": null
}
{
  "name": "c5ad.24xlarge",
  "memory_in_mib": 196608,
  "vcpus": 96,
  "disk_in_gb": 3800
}
{
  "name": "r6g.16xlarge",
  "memory_in_mib": 524288,
  "vcpus": 64,
  "disk_in_gb": null
}
```
