### ISSUE TITLE
Support the now-standard AWS_PROFILE

### ISSUE THREAD

**Issue by justinsb** [aws/aws-cli#1281]
All the SDKs are now supposed to recognize the AWS_PROFILE env var as a default profile.  The AWS CLI, however, uses AWS_DEFAULT_PROFILE.

Please consider supporting AWS_PROFILE. 

The precedence --profile > AWS_DEFAULT_PROFILE > AWS_PROFILE should be non-breaking, though I think AWS_PROFILE > AWS_DEFAULT_PROFILE makes more sense long-term.

**Comment by jamesls** [comment]
I agree we should support this.  We will need to take the former order (`AWS_DEFAULT_PROFILE` then `AWS_PROFILE`) to remain backwards compatible.

**Comment by jamesls** [comment]
Implemented in boto/botocore#515
