### ISSUE TITLE
Remote signing mode

### ISSUE THREAD

**Issue by atulatri** [aws/aws-cli#1288]
Does AWS CLI supports remote request signing via some API as provided by https://aws.amazon.com/developertools/Amazon-S3/739?

I explored but could not find anything.

**Comment by jamesls** [comment]
We do not support the remote signing mode that the tool you've linked supports.  If you're on an EC2 instance you can use an IAM roles to avoid having to deploy credentials to your servers.  If you have a specific use case in mind, please let us know.

**Comment by atulatri** [comment]
We keep our AWS credentials on central server for security reasons.  That's why we were looking for this feature. 
It will be great if you can include this feature in AWS CLI. 
I have used PHP AWS SDK and we can extend it to support remote signing. Is it possible to extend AWS CLI?

**Comment by jamesls** [comment]
Yep.  The only caveat is that the interface is not stable yet and may change over time.  We actually use this functionality to implement the `AssumeRole` credential provider.  You can use this module as an example: https://github.com/aws/aws-cli/blob/develop/awscli/customizations/assumerole.py

You'd create a subclass of the `CredentialProvider` class similar to https://github.com/aws/aws-cli/blob/develop/awscli/customizations/assumerole.py that implements a `load()` method that returns a `Credentials` object.
