### ISSUE TITLE
aws glacier fails to work with archiveID's which start with a hyphen (-)

### ISSUE THREAD

**Issue by ConSeannery** [aws/aws-cli#1319]
Current argument parsing does not seem to be able to process Glacier archiveID's which start with a dash (hyphen).

Escaping \ and using bash builtin "--" to notify of no further command options does not work.

The uskudnik/amazon-glacier-cmd-interface project takes the approach of preceding hyphen-leading archiveID's with --.

Examples:
```
> aws glacier delete-archive --account-id - --vault-name myvault --archive-id "-test"
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id '-test'
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id '\-test'
A client error (Unknown) occurred when calling the DeleteArchive operation: 

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id "\-test"
A client error (Unknown) occurred when calling the DeleteArchive operation: 

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id \-test
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id -- \-test
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id -- "-test"
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument

> aws glacier delete-archive --account-id - --vault-name myvault --archive-id -- "\-test"
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --archive-id: expected one argument
```

**Comment by kyleknap** [comment]
Yeah having a dash in front of a value proves to be an issue from time to time, and would be difficult to fix as the issue sources itself from python's ``ArgParser``.

The good news is that I believe you can get around this issue by using param files. So save the text ``-text`` to some file say ``myarchive.txt``. And then run:
```
aws glacier delete-archive --account-id - --vault-name myvault --archive-id file://myarchive.txt
```

Let me know if that is a good work around for you.

**Comment by ConSeannery** [comment]
Hey Kyle,

That should work as a work around for now. Thanks for the response!

**Comment by geneparmesan** [comment]
I've had the same problem and I tried the suggested workaround which still failed for me (I got the same 'unknown client error' as when trying to delete the archive using '\-test')

However, I solved the issue by using the JSON parameter input method instead of the normal command-line inputs:
```
aws glacier delete-archive --account-id - --vault-name myvault --cli-input-json '{"archiveId": "-test"}'
```
Hope that helps anyone else who has been frustrated with this problem

**Comment by mtdowling** [comment]
Just wanted to note here that you can also use a different argument syntax here (i.e., `name='value'`). For example:

```
aws glacier delete-archive --account-id - --vault-name myvault --archive-id='-test'
```

**Comment by h110hawk** [comment]
The help documents should be updated to reflect this commonly encountered issue with the aws glacier CLI tools. Having it as a default method of specifying the id's would hopefully prevent people from encountering this in the future.

**Comment by dsoprea** [comment]
@h110hawk +1

**Comment by MKorostoff** [comment]
@mtdowling thanks!  That worked for me.

The other solution in this thread (creating a file with the archive ID) is pretty cumbersome if you're deleting a large number of archives, though I suppose you could script either solution.

**Comment by molomby** [comment]
This still seems to be an issue when using the `--archive-id '-text'` syntax. While there are several work arounds, maybe someone should still look at fixing the issue? It's been over 6 years and the bug has surely effected many users.

**Comment by monsur** [comment]
I'd like to second @molomby's request. This bit me for a while, and its weird I had to dig into this random bug from 6 years ago to find the answer. At the very least the note in the documentation should be updated to reflect this: https://docs.aws.amazon.com/amazonglacier/latest/dev/getting-started-delete-archive-cli.html

**Comment by vandykej17** [comment]
I just hit this issue this morning. Almost didn't read this bug since it was so old - but glad I did!
