### ISSUE TITLE
Request with requester pays

### ISSUE THREAD

**Issue by domoritz** [aws/aws-cli#1321]
How do I add the header `x-amz-request-payer` to the ls pr cp commands for `aws s3`?

**Comment by kyleknap** [comment]
@domoritz 

We do not have support for this in the ``aws s3`` command set. However, it is available in the ``s3api`` command set.  Its parameter is ``--requester-payer`` and you should set its value to ``requester``.

Let me know how that works.

**Comment by pgericson** [comment]
In the [aws s3api get-object](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html) documentation there is a `--request-payer` parameter. There are no parameter for `--request-payer` in [aws s3api list-objects](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html).

just to clarify, it is not `--requester-payer` but `--request-payer`

**Comment by kyleknap** [comment]
@pgericson 
Yeah my bad. Typo. It is is ``--request-payer``

**Comment by kyleknap** [comment]
Closing. Please reopen if any updates come in or if you have any further questions.
