### ISSUE TITLE
aws s3 sync fails if user does not own all files

### ISSUE THREAD

**Issue by nicwaller** [aws/aws-cli#1322]
I am finding that `aws s3 sync` will fail if the active user does not have ownership of files in the sync target, regardless of what permissions are set for group and other.

**Normal result**

    $ aws s3 sync s3://example.com/ example/
    download: s3://example.com/file.txt to example/file.txt

**Problematic result**

To reproduce the problem, create an empty file that is world-writable but owned by root. aws s3 sync will fail to sync this file, even though the effective permissions allow the user to write to the file.

    $ mkdir example && touch example/file.txt
    $ sudo chown root example/file.txt && sudo chmod 777 example/file.txt

    $ aws s3 sync s3://example.com/ example/
    download failed: s3://example.com/file.txt to example/file.txt
    [Errno 1] Operation not permitted: '/example/file.txt'

    $ ls -l example/file.txt
    -rwxrwxrwx  1 root  wheel  54  7 May 17:55 example/file.txt

However, when running as the root user (`sudo aws s3 sync`) I cannot reproduce the problem. The file downloads as expected.

**Environment**

I am able to reproduce this issue on both machines I've tried it on:

* aws-cli/1.7.25 Python/2.7.6 Darwin/14.3.0 (Mac OS X 10.10)
* aws-cli/1.7.10 Python/2.7.6 Linux/3.13.0-40-generic (Ubuntu 14.04)

**Comment by kyleknap** [comment]
I can confirm. The issue is that when we download the file we need to set the last modified/access time to that of the S3 file in order to be able to round trip syncing given our sync strategy. It is the call that is modifying the last modified time that is failing. You can see it by running the following python script on the ``file.txt`` file that you made:
```
>>> import os
>>> os.utime('file.txt', (1, 1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 1] Operation not permitted: 'file.txt'
```
Will need to do research into if there is any way around this, other than running the command as the root.

**Comment by stevenbrichards** [comment]
I dug deeper on this one and noticed a few things, `os.utime` works when `None` is specified as the second argument as it sets the time attributes to be the current time and it fails when times are specified. Digging into the `utime` and `utimes` syscall source code we see the following comment
```
  * If times==NULL, set access and modification to current time,
  * must be owner or have write permission.
  * Else, update from *times, must be owner or super user.
  */
 long do_utimes(int dfd, const char __user *filename, struct timespec *times,
                int flags)
{
``` 
If you specify `*times` (the time tuple in `os.utime`) then you must be super user or owner (root) in this case. But if you just want to update to the current time then you only need to have write access to the file.
