### ISSUE TITLE
Temporary Credentials in EC2 instance: Unable to locate credentials

### ISSUE THREAD

**Issue by JeanMertz** [aws/aws-cli#1325]
I have an EC2 instance which has access to temporary credentials:

```bash
% curl -s 169.254.169.254/latest/meta-data/iam/info
# {
#   "Code": "Success",
#   "LastUpdated": "2015-05-11T20:34:38Z",
#   "InstanceProfileArn": "arn:aws:iam::xxxx:instance-profile/yyyyy",
#   "InstanceProfileId": "xxx"
# }
```

Using: `aws-cli/1.5.1 Python/2.7.8 Linux/4.0.1`

When I run `aws ec2 describe-tags`, I get:

```
Unable to locate credentials. You can configure credentials by running "aws configure".
```

If I run the command again it works, but the first failure causes problems with my init setup, so I am unsure what is happening here.

**Comment by JeanMertz** [comment]
In fact, it looks like this always happens if the temporary security credentials have expired. So it happens on every first try when new credentials are required.

Re-running the command right after the failure, results in a successful request. All subsequent requests succeed, until the temporary credentials are revoked, in which case the first request again fails, and all requests after that succeed again. And so on.

**Comment by kyleknap** [comment]
@JeanMertz 
Can you try upgrading to the latest version of the CLI, 1.7.26? The version you are on is a little old and we have made some improvements with refreshing credentials since then. I have not seen issues when I launch an ec2 instance with an IAM role while using some of the most recent versions of the CLI.

Let me know if that works for you.

**Comment by kyleknap** [comment]
Closing. Please reopen if any updates come in or if you have any further questions.

**Comment by JeanMertz** [comment]
Sorry @kyleknap, this slipped by me. Indeed, I was unaware I was running an older version. This is solved in the latest release :+1:

**Comment by pwaller** [comment]
@kyleknap I'm hitting this with `aws-cli/1.7.34 Python/3.4.3 Linux/4.0.5` now, frequently. I'm having to retry all of my operations frequently.

I'm using the instance's IAM role to do S3 operations.

**Comment by kyleknap** [comment]
Can you catch a debug log of this happening? You can do so by appending the command you ran with ``--debug``.

**Comment by pwaller** [comment]
Unfortunately I've finished the operation where I was hitting it repeatedly, and now I'm off for a while, so unlikely, sorry :(. I think I was running with --debug at some point, and my interpretation of it was that access to the metadata endpoint was timing out. I am not certain if the metadata endpoint was being slow or if it was timing out, but the behaviour I observed was that while running tens of commands in sequence, separated by a few seconds each, maybe one in thirty was failing.

**Comment by FremanZhang** [comment]
Seems this happened on the EC2 roles temporary credentials refreshing. The refreshing spent time and interval would affect.

**Comment by rjamestaylor** [comment]
Using 
[ec2-user@ip-10-72-12-80 ~]$ aws --version
aws-cli/1.10.56 Python/2.7.10 Linux/4.4.11-23.53.amzn1.x86_64 botocore/1.4.46

I observed this behavior with a for loop like the following:

`for i in $(hexseq.sh 00 ff); do  aws s3api list-object-versions --bucket mybucket  --prefix $i &  done > versions.json`

(The hexseq.sh is a bash script to generate hex sequences similar to seq)

Many of the calls fail with the message

> Unable to locate credentials. You can configure credentials by running "aws configure".

By inserting a "sleep 1" before the aws s3api call, I avoid the error, but generating the calls obviously takes longer. Not a deal breaker (and probably better at not hammering the api...), but was unexpected.

**Comment by jamesls** [comment]
Any chance we could get a `--debug` log?  It should show what's happening and why we're not pulling credentials from instance metadata.

**Comment by rjamestaylor** [comment]
Redacted debug log -- hopefully redacted enough! 
[error.txt](https://github.com/aws/aws-cli/files/425857/error.txt)
