### ISSUE TITLE
aws <module> describe functions return inconsistent values when object is not found

### ISSUE THREAD

**Issue by jlchereau** [aws/aws-cli#1327]
like most APIs

```
aws ec2 describe-vpcs --query "Vpcs[?CidrBlock=='$VPC_CIDR'].[VpcId][0][0]" --output text
```
returns "None" (or null in JSON) when ```$VPC_CIDR``` is not found.

but

```
aws elb describe-load-balancers --load-balancer-name "$ELB_NAME" --query "LoadBalancerDescriptions[0].LoadBalancerName" --output text
```

raises an error when ```$ELB_NAME``` is not found:

```
A client error (LoadBalancerNotFound) occurred when calling the DescribeLoadBalancers operation: Cannot find Load Balancer my-load-balancer
```

This is inconsistent.

**Comment by kyleknap** [comment]
So the ``--query`` parameter is applied on the response from the service. It should not throw any errors if a particular element in the JSON does not exist as seen in your first example.

In the second example, you are requesting a particular load balancer from the service itself (i.e. the parameter value is in the request to the service). Thus the error being thrown is coming directly from the service. Likewise in your first example if you specified a non existent vpc you would get a similar error as in the elb command:
```
$ aws ec2 describe-vpcs --vpc-ids $VPC_ID --query "Vpcs[?CidrBlock=='$VPC_CIDR'].[VpcId][0][0]"

A client error (InvalidVpcID.NotFound) occurred when calling the DescribeVpcs operation: The vpc ID 'myfakevpc' does not exist
```

If you want to make the elb command more consistent with the vpc command in terms of error handling you should move the ``--load-balancer-name`` parameter value into the ``--query`` parameter:
```
$ aws elb describe-load-balancers --query "LoadBalancerDescriptions[?LoadBalancerName=='myloadbalancer'].LoadBalancerName"
[
    "myloadbalancer"
]

```

Likewise if the load balancer does not exist it would be:
```
$ aws elb describe-load-balancers --query "LoadBalancerDescriptions[?LoadBalancerName=='noexistloadbalancer'].LoadBalancerName"
```

Let me know if you have any more questions.

**Comment by jlchereau** [comment]
Crystal Clear! Thx.

**Comment by jlchereau** [comment]
I have checked again without queries and:

```
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names "bla"
```
returns no error:
```
{
    "AutoScalingGroups": []
}
```

and
```
aws autoscaling describe-launch-configurations --launch-configuration-names
```
returns no error
```
{
    "LaunchConfigurations": []
}
```

**but**

```
aws ec2 describe-vpcs --vpc-ids "bla"
````
returns error
```
A client error (InvalidVpcID.NotFound) occurred when calling the DescribeVpcs operation: The vpc ID 'bla' does not exist
```

and 
```
aws elb describe-load-balancers --load-balancer-name "bla"
```
returns arror
```
A client error (LoadBalancerNotFound) occurred when calling the DescribeLoadBalancers operation: Cannot find Load Balancer bla
```

Accordingly outputs are inconsistent which affects script logic.

**Comment by jlchereau** [comment]
BTW having all describe functions returning empty arrays without raising errors creates a better scripting experience IMO: easier to test values with JMESPath queries and better control over stdout.

**Comment by jlchereau** [comment]
Another exemple:

```
aws ecs describe-clusters --clusters bla
```

returns 

```
{
    "clusters": [],
    "failures": [
        {
            "reason": "MISSING",
            "arn": "arn:aws:ecs:eu-west-1:215711614536:cluster/bla"
        }
    ]
}
```

**Comment by kyleknap** [comment]
To get this type of consistency in the CLI would be quite difficult because these responses are coming directly from the service itself. In the case of the ec2 and elb commands run, the http response being sent back to the CLI has a 4xx status code, and so we throw an error. However, autoscaling and ecs respond back with a 2xx status code thus we display the response and not throw an error.

We try to avoid adding any extra service-specific logic on top of our response parsing and displaying because it tends to be less robust and users usually want to see the unmodified response from the service.

Typically, though, within a specific service you can expect a consistency across its various operations.

Let me know if you have any other suggestions on how we can improve the CLI experience.

**Comment by jlchereau** [comment]
Will do. Thx
