### ISSUE TITLE
Missing aws ec2 wait internet-gateway-deleted is needed

### ISSUE THREAD

**Issue by jlchereau** [aws/aws-cli#1331]
The following script fails without `sleep 1` (or an appropriate loop) in order to give AWS enough time to delete the internet gateway
### delete.sh

``` shell
#!/bin/sh
source ~/.bashrc

echo '------------------------------------------------------------'
echo '>>> vpc deletion'

if [ -z "$1" ]
then
    echo '>>> missig arguments'
    exit
fi

VPC_CIDR=$1
echo '>>> deleting vpc' $VPC_CIDR

# http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-vpcs.html
VPC_ID=$(aws ec2 describe-vpcs --query "Vpcs[?CidrBlock=='$VPC_CIDR'].[VpcId][0][0]" --output text)
echo '>>>' $VPC_ID 'found'

if [ "$VPC_ID" == "None" ]
then
    echo '>>>' $VPC_CIDR 'vpc already deleted'
else

    # TODO this script only works with one attachment only between gateway and vpc
    # http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-internet-gateways.html
    IGW_ID=$(aws ec2 describe-internet-gateways --query "InternetGateways[].{ InternetGatewayId: InternetGatewayId, VpcId: Attachments[0].VpcId } | [?VpcId == '$VPC_ID'].[InternetGatewayId][0][0]" --output text)

    if [ -z $IGW_ID ]
    then
        echo '>>>' $VPC_CIDR 'has no internet gateway'
    else

        echo '>>>' $IGW_ID 'internet gateway found'

        # http://docs.aws.amazon.com/cli/latest/reference/ec2/detach-internet-gateway.html
        aws ec2 detach-internet-gateway --internet-gateway-id "$IGW_ID" --vpc-id "$VPC_ID"
        echo '>>>' $IGW_ID 'internet gateway detached'

        # http://docs.aws.amazon.com/cli/latest/reference/ec2/delete-internet-gateway.html
        aws ec2 delete-internet-gateway --internet-gateway-id "$IGW_ID"
        echo '>>>' $IGW_ID 'internet gateway deleted'

    fi

    # TODO we need a waiter here
    sleep 1

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-subnets.html
    VPC_SUBNETS=$(aws ec2 describe-subnets --query "Subnets[?VpcId=='$VPC_ID'].[SubnetId][]" --output text)
    echo '>>>' $VPC_SUBNETS 'subnets found'

    for SUBNET_ID in $VPC_SUBNETS
    do
        echo '>>> deleting' $SUBNET_ID
        # http://docs.aws.amazon.com/cli/latest/reference/ec2/delete-subnet.html
        aws ec2 delete-subnet --subnet-id "$SUBNET_ID"
    done
    echo '>>>' $VPC_SUBNETS 'subnets deleted'

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/delete-vpc.html
    aws ec2 delete-vpc --vpc-id "$VPC_ID"
    echo '>>>' $VPC_CIDR 'vpc deleted'
fi
```

**Comment by jlchereau** [comment]
For testing purposes, I realize it might be worth having the creation script below in order to be able to run the deletion script above:

```shell
#!/bin/sh
source ~/.bashrc

echo '------------------------------------------------------------'
echo '>>> vpc creation'

if [ $# -lt 4 ]
then
    echo '>>> missig arguments'
    exit
fi

VPC_CIDR=$1
NET1_CIDR=$2
NET2_CIDR=$3
NET3_CIDR=$4
echo '>>> creating vpc' $VPC_CIDR 'with subnets' $NET1_CIDR $NET2_CIDR $NET3_CIDR

# http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-vpcs.html
VPC_ID=$(aws ec2 describe-vpcs --query "Vpcs[?CidrBlock=='$VPC_CIDR'].[VpcId][0][0]" --output text)
echo '>>>' $VPC_ID 'found'

if [ "$VPC_ID" == "None" ]
then

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/create-vpc.html
    VPC_ID=$(aws ec2 create-vpc --cidr-block "$VPC_CIDR" --query "Vpc.VpcId" --output text)
    echo '>>>' $VPC_ID 'vpc created'

    # TODO consider http://docs.aws.amazon.com/cli/latest/reference/ec2/wait/vpc-available.html

    REGION=$(aws configure get region --output text)

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/create-subnet.html
    aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block "$NET1_CIDR" --availability-zone "$REGION""a"
    aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block "$NET2_CIDR" --availability-zone "$REGION""b"
    aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block "$NET3_CIDR" --availability-zone "$REGION""c"
    echo '>>> subnets created'

    # TODO consider http://docs.aws.amazon.com/cli/latest/reference/ec2/wait/subnet-available.html

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/create-internet-gateway.html
    IGW_ID=$(aws ec2 create-internet-gateway --query="InternetGateway.InternetGatewayId" --output text)
    echo '>>>' $IGW_ID 'internet gateway created'

    # http://docs.aws.amazon.com/cli/latest/reference/ec2/attach-internet-gateway.html
    aws ec2 attach-internet-gateway --internet-gateway-id "$IGW_ID" --vpc-id "$VPC_ID"
    echo '>>>' $IGW_ID 'internet gateway attached to vpc' $VPC_ID

    # TODO Check modify auto-assign public IP
    # TODO add tags

    echo '>>>' $VPC_CIDR 'vpc created'

else
    echo '>>>' $VPC_CIDR 'vpc already exists'
fi
```

to create a VPC, simply run ```create.sh "10.0.0.0/16" "10.0.0.0/20" "10.0.16.0/20" "10.0.32.0/20"``` and delete this VPC by running ```delete.sh "10.0.0.0/16"

These scripts have only been tested on Windows 8.1.

**Comment by kyleknap** [comment]
This would have to be a new feature. Fortunately, adding wait commands into the CLI is not difficult. All of the ``wait`` commands are generated from JSON models representing the waiters. Here is all of the various waiter from ec2: https://github.com/boto/botocore/blob/develop/botocore/data/ec2/2015-04-15/waiters-2.json

To get a wait command added for internet-gateway-deleted, it would need to be added to this model.

If you feel inclined, we do accept pull requests for adding to the waiter model. The format of the waiter models is pretty straight forward. However, there is not really any public documentation on how to write a waiter model and the best way to learn is to follow examples for other waiters. I can also help you out if you decide to try to write one.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by tim-finnigan** [comment]
Hi @jlchereau, thanks for your patience. Is this request still something that you need? There hasn’t been any community engagement on this issue so I just wanted to make sure. If so then I can bring this up with the service team to see if they would consider adding a waiter for internet-gateway-deleted.

**Comment by jlchereau** [comment]
@tim-finnigan, thanks but I have now switched to the cdk.

**Comment by tim-finnigan** [comment]
> @tim-finnigan, thanks but I have now switched to the cdk.

Ok thanks @jlchereau for letting me know, I'll go ahead and close this then.
