### ISSUE TITLE
Support for custom RoleSessionName when assuming a role

### ISSUE THREAD

**Issue by pgcp** [aws/aws-cli#1333]
**Short version:** I'd like to be able to have a fixed value for the RoleSessionName parameter when I'm running a command with an assumed role. Ideally I'd be able to configure what that fixed value is. The current implementation assigns the RoleSessionName with a built-in time: ` 'AWS-CLI-session-%s' % (int(time.time()))`

**The problem:** I have an S3 bucket policy containing a NotPrincipal section. I'm trying to block access to that bucket except for a specific role. In order to block access except for a specific role, I need to specify a fixed assumed-role ARN in the NotPrincipal. According to the [IAM Policy Documentation section on NotPrincipal](http://docs.aws.amazon.com/IAM/latest/UserGuide/AccessPolicyLanguage_ElementDescriptions.html#d0e17298), I need something like this:
```
"Effect": "Deny",
"NotPrincipal": {"AWS": [
  "arn:aws:sts::111122223333:assumed-role/HR-database-access-role/HR-database-app",
  "arn:aws:iam::111122223333:role/HR-database-access-role"
]}
```
In this example, 'HR-database-app' is the RoleSessionName which AWS-CLI will automatically assign to something like 'AWS-CLI-session-1431630707'. Since those two RoleSessionName values don't match, the policy won't be useful. The NotPrincipal section doesn't allow wildcards so unfortunately I can't use `arn:aws:sts::111122223333:assumed-role/HR-database-access-role/*`

I see the code that generates the RoleSessionName in awscli/customizations/assumerole.py. A couple lines look like this:
```
role_session_name = 'AWS-CLI-session-%s' % (int(time.time()))
```
I need the role_session_name to be customizable or at least a fixed value otherwise I can't put the appropriate assumed-role ARN in S3 bucket policy.

**To reproduce:**
 1\. Create an AWS bucket (e.g. test_bucket) and upload a file to it.
 2\. Create a cross-account role (e.g. test_role) with a policy that would let you do a GetObject from that bucket. The role can be a cross-account role even though the role is assumed from the same account it is in.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::test_bucket/*"
            ]
        }
  ]
}
```
 3\. Add an S3 policy to the bucket to exclude GetObject access except for the test_role. (Replace the account id 111122223333 with your own)
```
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Effect": "Deny",
			"NotPrincipal": {
				"AWS": [
					"arn:aws:iam::111122223333:role/test_role",
					"arn:aws:sts::111122223333:assumed-role/test_role/test_role_session_name"
				]
			},
			"Action": 	"s3:GetObject",
			"Resource": "arn:aws:s3:::test_bucket/*"
		}
	]
}
```
 4\. Grant an IAM user the STS:AssumeRole privilege so that user can assume the role.

 5\. Create an AWS CLI profile that will assume the test_role role from the IAM user from the last step. 

 6\. Use the AWS CLI to try to get the file in the bucket using the test_role role.
`aws  s3api get-object --profile test_role --bucket test_bucket --key test.txt /tmp/test.txt`

 7\. You should see an AccessDenied error.
`A client error (AccessDenied) occurred when calling the GetObject operation: Access Denied`

If you update the S3 bucket policy to replace `test_role_session_name` with RoleSessionName of the currently cached session credentials as found in `~/.aws/cli/cache/` then you can actually get the get-object command to succeed. As soon as the cached session credentials expire, the get-object command fails again.

**Comment by kyleknap** [comment]
Seems reasonable to me. Marking as a feature request.

**Comment by pgcp** [comment]
Thanks. I'm hoping to make the change myself and submit a pull request, but we'll see if I can pull it off.

**Comment by pgcp** [comment]
I created a pull request #1389 for this issue.

**Comment by quiver** [comment]
> I created a pull request #1389 for this issue.

@kyleknap #1389 is merged a few weeks back, so this issue can be closed now.
Nice work, @pgcp

**Comment by jamesls** [comment]
Closing out issue.  Thanks again @pgcp for the PR and thanks @quiver for mentioning this issue can be closed.
