### ISSUE TITLE
aws ecs delete-service cannot delete DRAINING service

### ISSUE THREAD

**Issue by jlchereau** [aws/aws-cli#1334]
I have been stuck for a couple of days with a DRAINING ecs service that I cannot delete either using the console (not listed) or the AWS CLI:

```
aws ecs delete-service --service my-service
````

returns

```
{
    "service": {
        "status": "DRAINING",
        "taskDefinition": "arn:aws:ecs:eu-west-1:123456489012:task-definition/my-task-definition:1",
        "pendingCount": 0,
        "loadBalancers": [
            {
                "containerName": "Kidoju-Blog",
                "containerPort": 3000,
                "loadBalancerName": "my-old-elb"
            }
        ],
        "roleArn": "arn:aws:iam::123456489012:role/ecsServiceRole",
        "desiredCount": 0,
        "serviceName": "my-service",
        "clusterArn": "arn:aws:ecs:eu-west-1:123456489012:cluster/default",
        "serviceArn": "arn:aws:ecs:eu-west-1:123456489012:service/my-service",
        "deployments": [
            {
                "status": "PRIMARY",
                "pendingCount": 0,
                "createdAt": 1431444514.347,
                "desiredCount": 0,
                "taskDefinition": "arn:aws:ecs:eu-west-1:123456489012:task-definition/my-task-definition:1",
                "updatedAt": 1431613057.05,
                "id": "ecs-svc/9223370605410261451",
                "runningCount": 0
            }
        ],
        "events": [
            {
                "message": "(service my-service) failed to describe instance health on (elb my-old-elb) with (error There is no ACTIVE Load Balancer named 'my-old-elb')",
                "id": "adec770c-271f-4300-a93f-b0a321f53579",
                "createdAt": 1431675697.659
            },
            {
                "message": "(service my-service) failed to describe instance health on (elb my-old-elb) with (error There is no ACTIVE Load Balancer named 'my-old-elb')",
                "id": "a0184820-00cb-42ad-92ec-8d46aa0f453e",
                "createdAt": 1431675604.033
            },

...

         ],
        "runningCount": 0
    }
}
```

This occured because in my script the ELB got deleted but the AutoScaling group and dependant services failed to delete up to the service.

**There should be a business rule: an ELB cannot be deleted if there is an ECS service relying on it** otherwise this leaves the system in a state which is difficult to recover

Any clue how I can sort this out?

**Comment by kyleknap** [comment]
We are looking into how this can be fixed. Let me know if you fix it before we get back to you.

**Comment by jhspaybar** [comment]
Sorry about the issue, a fix is going out soon.  From our forums 

"Is this service using ELB? If using ELB can you confirm if the ELB is still available and not deleted.

We discovered a bug in our system where services get stuck in 'DRAINING' state when ELB attached to service is deleted before deleting the service. We are actively working on fixing this issue."

https://forums.aws.amazon.com/thread.jspa?messageID=621911&#621911

A workaround for now would be to recreate the ELB the service was originally created with, this will allow the service to move from DRAINING to INACTIVE and then the ELB can be deleted again.

**Comment by jlchereau** [comment]
YES the service was using ELB.

**Comment by kyleknap** [comment]
@jlchereau 

Since the issue is server side, we would prefer that it is tracked in the forum thread. Let us know if there is anything else you need.

**Comment by jhspaybar** [comment]
Whoops, I should have closed the loop here as well.  The server side issue has been addressed and you should no longer encounter this situation.  If you do some across this or something else in the future with the ECS APIs, please come to our forums where we're best able to provide support.

**Comment by kyleknap** [comment]
Closing issue as the it has been resolved server side.

**Comment by syneafreen** [comment]
Hello, 

Below command is not working, 
aws ecs describe-services --service stackserver

I am getting result 
"services": [],
    "failures": [
        {
            "reason": "MISSING",

eventhough my service is running fine in the ECS console, why command not showing.

Please help urgent. I badly stuck.

**Comment by WishCow** [comment]
I am encountering this issue as of today. The service is stuck in the draining state, if I issue aws delete-service --cluster=x --service=y, it will return the same JSON result as the describe-service command does, and nothing happens.

**Comment by mrwilby** [comment]
Seeing the same issue - deletion of IAM role causes the service to be stuck in draining state.

ECS (AWS Console) UI says the cluster is ACTIVE

**Comment by Limess** [comment]
We also encountered this when terraform deleted things in a certain order, two services are stuck in DRAINING

aws ecs describe-services --services prod-analytics-airflow-worker-sensors
{
    "services": [],
    "failures": [
        {
            "arn": "arn:aws:ecs:eu-west-1:655100936961:service/prod-analytics-airflow-worker-sensors",
            "reason": "MISSING"
        }
    ]
}

**Comment by anton-demydov-zoral** [comment]
Having the same problem with deleting ecs service.
24h of DRAINING, then I deleted cluster, now I have MISSING.

I think it's related to circuit breaker somehow

**Comment by german-muzquiz** [comment]
I have the same problem of a ECS service stuck on `DRAINING` state forever, trying to delete from CLI using `--force` flag does nothing and the stuck container is locking a network interface.
The service is not shown on the console BTW, but trying to recreate it errors with service already exist.
Last error from events:
```
(service XXX) failed to deregister targets in (target-group arn:aws:elasticloadbalancing:XXX:targetgroup/XXX/YYY) with (error Target groups 'arn:aws:elasticloadbalancing:XXX:targetgroup/XXX/YYY' not found)
```

**Comment by annt2c98** [comment]
Having the same problem

**Comment by anton-demydov-zoral** [comment]
> Having the same problem with deleting ecs service. 24h of DRAINING, then I deleted cluster, now I have MISSING.
> 
> I think it's related to circuit breaker somehow

Was able to delete after removing ALB and target groups

**Comment by remiflament** [comment]
Service stuck because the IAM role used was delete before deleting the target group

```
"message": "(service xxxx) failed to deregister targets in (target-group arn:aws:elasticloadbalancing:eu-west-1:xxxx:targetgroup/xxxx-tg/xxxxx) with (error User: arn:aws:sts::xxxxx:assumed-role/service.s2/ecs
-ess-dub-s2-prod-2-12005.dub2.amazon.com is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxx:role/xxxxxx-ecs-service-role)"
```

**Comment by aekondratiev** [comment]
same problem with IAM role used was delete before deleting the target group, I just created IAM role manually and it deleted service now. 

go to IAM -> Roles -> Create role -> AWS Service + Elastic Container Service -> Next -> Put your missed role name (check it from aws ecs describe-services)

**Comment by mtbrobotanist** [comment]
> I needed to delete the ASG to fix the problem.

Also true for a dedicated EC2 instance

**Comment by mtbrobotanist** [comment]
> Service stuck because the IAM role used was delete before deleting the target group
> 
> ```
> "message": "(service xxxx) failed to deregister targets in (target-group arn:aws:elasticloadbalancing:eu-west-1:xxxx:targetgroup/xxxx-tg/xxxxx) with (error User: arn:aws:sts::xxxxx:assumed-role/service.s2/ecs
> -ess-dub-s2-prod-2-12005.dub2.amazon.com is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxx:role/xxxxxx-ecs-service-role)"
> ```
> 
> I needed to delete the ASG to fix the problem.

Also true for dedicated EC2 instance, if it was deleted before the ECS service

**Comment by ngocmanhha** [comment]
> same problem with IAM role used was delete before deleting the target group, I just created IAM role manually and it deleted service now.
> 
> go to IAM -> Roles -> Create role -> AWS Service + Elastic Container Service -> Next -> Put your missed role name (check it from aws ecs describe-services)

I had the same issue, check the Service `Events` tab to see which role is missing and add the corresponding role, the service that was `DRAINING` was gone.
