### ISSUE TITLE
running aws configure does not clear aws_session_token

### ISSUE THREAD

**Issue by joshunger** [aws/aws-cli#1341]
Running aws configure does not clear aws_session_token from the credentials file.  Is this expected behavior or should it clear aws_session_token?

Save the following to ~/.aws/credentials

```
[default]
aws_access_key_id = blah
aws_secret_access_key = blah
aws_session_token=blah
```

Run `aws configure` and enter a new access key and secret access key.

Inspect `~/.aws/credentials`

EXPECTING: I was thinking aws_session_token should be removed?

ACTUAL: aws_session_token exists.  Any future aws client calls fail since this security token is not invalid with the new access key.

**Comment by kyleknap** [comment]
This is expected behavior. There is not any special logic with the ``aws configure`` command. It just displays and sets the value for some of the possible config values.

If you want to set the session token value, you will have to do it manually.

Let me know if you have any follow up questions.

**Comment by kyleknap** [comment]
Closing. Please reopen if any updates come in or if you have any further questions.

**Comment by brianantonelli** [comment]
Why was this issue closed? If someone configures their default profile with STS creds and then later users `aws configure` to setup new creds it shouldn't just leave the old session token in there. The default block should be cleared out..

**Comment by theBull** [comment]
@kyleknap 
> If you want to set the session token value, you will have to do it manually.
How do we clear it manually?

**Comment by mpoppell** [comment]
Did you find an answer to this one?

**Comment by RichardTMiles** [comment]
https://stackoverflow.com/questions/39154544/aws-cli-invalid-security-token

^ this helped me

**Comment by axilis-marko** [comment]
Why doesn't `aws configure` include `aws_session_token` prompt? This would enable us to change it when renewing information for a profile.

**Comment by ashovlin** [comment]
As of [2.30.3](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#2303), via https://github.com/aws/aws-cli/pull/9590 `aws configure` will now:
1. Prompt for the session token, if you entered a short-lived access key (starting with `ASIA...`)
2. Clear the session token, if you've entered a long term access key (starting with `AKIA...`)
