### ISSUE TITLE
cloudfront create-distribution --generate-cli-skeleton json structure not accepted

### ISSUE THREAD

**Issue by cloudfountain** [aws/aws-cli#1342]
```aws cloudfront create-distribution --distribution-config```
takes different json object structure as is generated by
```aws cloudfront create-distribution  --generate-cli-sketelon.```

If using provided skeleton file, command 
```aws cloudfront create-distribution --distribution-config file://myconfig.json```
 throws an error

```
Parameter validation failed:
Missing required parameter in DistributionConfig: "CallerReference"
Missing required parameter in DistributionConfig: "Origins"
Missing required parameter in DistributionConfig: "DefaultCacheBehavior"
Missing required parameter in DistributionConfig: "Comment"
Missing required parameter in DistributionConfig: "Enabled"
Unknown parameter in DistributionConfig: "DistributionConfig", must be one of: CallerReference, Aliases, DefaultRootObject, Origins, DefaultCacheBehavior, CacheBehaviors, CustomErrorResponses, Comment, Logging, PriceClass, Enabled, ViewerCertificate, Restrictions
```

Json structure must not contain ```DistributionConfig``` key. 
After skeleton file is edited command works.

Generated skeleton:
```cat skeleton.json```

```javascript
    "DistributionConfig": {
        "CallerReference": "", 
        "Aliases": {
            "Quantity": 0, 
            "Items": [
                ""
            ]
        }, 
```

Working json structure
```cat myconfig.json```

```javascript
{

        "CallerReference": "43278", 
        "Aliases": {
            "Quantity": 1, 
            "Items": [
                "aws.cloudfountain.eu"
            ]
        }, 
```

**Comment by kyleknap** [comment]
@cloudfountain 

You cannot use the template from ``--generate-cli-skeleton`` with the ``--distribution-config`` parameter directly (you would need to modify the JSON like you did). You should be using the ``--cli-input-json`` argument instead with the JSON you generated from ``--generate-cli-skeleton``.

Let me know if you have anymore questions.

**Comment by cloudfountain** [comment]
Make sense. Format of --distribution-config input json structure was confusing as it was too similar to skeleton file.

**Comment by kyleknap** [comment]
Cool. Glad it makes sense. Closing issue.
