### ISSUE TITLE
Command line flag to change async commands to sync

### ISSUE THREAD

**Issue by lashex** [aws/aws-cli#1344]
It would be nice to have a ``--block <timeout>`` flag on some calls in order to turn the command into a synchronous invocation **instead** of asynchronous. 

First example: Change **``aws ec2 attach-volume``** into a blocking call **``aws ec2 attach-volume --block 30``** which would automatically wait for the ``State`` value to change from ``attaching``.
````
{
    "AttachTime": "YYYY-MM-DDTHH:MM:SS.000Z",
    "InstanceId": "i-abcd1234",
    "VolumeId": "vol-1234abcd",
    "State": "attaching",
    "Device": "/dev/sdf"
}
````
over to ``attached`` without having to manage the client polling for 30 seconds.

**Comment by mhart** [comment]
This already exists in the form of `wait`, eg `aws ec2 wait volume-available --volume-ids vol-1234abcd`

More options here: http://docs.aws.amazon.com/cli/latest/reference/ec2/wait/index.html

**Comment by mhart** [comment]
(it still polls behind the scenes, but there's no way you can get around that with the API)

**Comment by motely** [comment]
Aah thanks for that clarification and sorry I missed that in the docs. I'll definitely be using ``wait`` now that I know it exists.

**Comment by lashex** [comment]
Aah thanks for that clarification and sorry I missed that in the docs. I'll definitely be using ``wait`` now that I know it exists.
