### ISSUE TITLE
aws ec2 describe_security_groups  to yml

### ISSUE THREAD

**Issue by rainmanh** [aws/aws-cli#1353]
Hi

I am looking into getting the Json output into yml format as I am trying to get some ansible automation out of this based on my current infrastructure (obviously I cannot destroy what I got but to get some degree of management )
Any ideas/tips which can help on this?

thanks!!

**Comment by kyleknap** [comment]
The CLI does not have a yaml output. You should be able to pipe the json output from the command to another third-party tool that converts json to yaml. This website seemed to have a lot of solutions on how to do that: http://jsontoyaml.com

Let me know if you need anymore help.

**Comment by kyleknap** [comment]
Closing. Please reopen if you have any more questions or comments.
