### ISSUE TITLE
cloudformation create-stack : templateBody provided via --cli-input-json not working

### ISSUE THREAD

**Issue by vhartikainen** [aws/aws-cli#1360]
Seems like the "TemplateBody" given via --cli-input-json is not adhered to. When providing the same via command-line parameter there is no issues creating the stack. In addition the error message provided is very misleading.

*Version information*
aws-cli/1.7.13 Python/2.6.6 Linux/2.6.32-358.el6.x86_64

*client-input.json*
```
{
    "StackName": "teststack",
    "TemplateBody": "file:///home/user/engine.template", 
    "Parameters": [ {...
```

*When running this via CLI:*
```
$ aws cloudformation create-stack --cli-input-json file:///home/user/client-input.json --stack-name teststack

A client error (ValidationError) occurred when calling the CreateStack operation: Template format error: JSON not well-formed. (line 1, column 5)
```

*And with parameter given in command-line:*
```
$ aws cloudformation create-stack --cli-input-json file:///home/user/client-input.json --stack-name teststack --template-body file:///home/user/engine.template
{
    "StackId": "arn:aws:cloudformation:eu-west-1:xxxxxx:stack/teststack/af1xxxxx"
}
```

**Comment by kyleknap** [comment]
@vhartikainen 

The reason it does not work is that we do not accept the ``file://`` notation in the value passed to ``--cli-input-json``. If you want to specify a file in the JSON skeleton, you will have to do so as you did in your last example.

Let me know if you have any more questions.

**Comment by kyleknap** [comment]
Closing issue. Please reopen if you have any more questions or comments.

**Comment by lukemv** [comment]
Had this same issue, still don't understand how to specify a stack template file path within the cli-skeleton. A basic example that illustrates the correct format of the skeleton and how to call it would be extremely handy.

**Comment by biancachebet** [comment]
I want to launch instances from a JSON file using cloudformation template. How do I call the JSON file?

**Comment by biancachebet** [comment]
I converted excel sheet to JSON and I want tags reflecting in the respective systems on the AWS Console. My expectation is to be able to apply these tags when they are being migrated.
How can I automate tagging??
Here is the sample template:

[
{
"Server": "abe203-elwb.cfs.its.tld",
"dns-hostname": "abec203-elwb.cfs.its.tld",
"environment": "dev",
"name": "adc290",
"notification-team": "a@e.com",
"organization": "its",
"support-group": "ITS",
"tier": "web",
"university-service": "EDU"
},
{
"Server": "abe567-ewap.cfs.its.tld",
"dns-hostname": "abec567-ewap.cfs.its.tld",
"environment": "test",
"name": "adc567",
"notification-team": "a@e.com",
"organization": "its",
"support-group": "ITS",
"tier": "app",
"university-service": "EDU"
}
]
