### ISSUE TITLE
DOCUMENTATION discrepancy regarding aws ecs create-service

### ISSUE THREAD

**Issue by jlchereau** [aws/aws-cli#1362]
I wanted to connect a container consisting of an nginx reverse proxy exposing ports 80 and 443 with a permanent redirection from http to https to an ELB exposing the same ports.

The documentation at http://docs.aws.amazon.com/cli/latest/reference/ecs/create-service.html clearly states that this should be possible since one can pass several load balancers to the ```--load-balancers``` option.

When passing
loadBalancerName=my-elb,containerName=my-nginx,containerPort=80
loadBalancerName=my-elb,containerName=my-nginx,containerPort=443
I got the following error:

```
invalid literal for int() with base 10: '80 loadBalancerName=my-elb'
```

After changing the position of quotes, I got:
```
A client error (InvalidParameterException) occurred when calling the CreateService operation: load balancers can have at most 1 items.
```

The documentation at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-load-balancing.html says *"There is a limit of one load balancer per service."* but it is not clear whether the load balancer can be connected with several ports.

The AWS console only offers one load balancer + port combination:
![image](https://cloud.githubusercontent.com/assets/2556751/7940770/eebc08a8-094a-11e5-990e-47fb1c690edc.png)

Is it possible to create a service as I intended too: same load balancer, 2 ports (80 and 443) connected to the same nginx proxy container configured to forward all http traffic to https?

Is there a discrepancy in the documentation? In this case, how can I achieve the above?

**Comment by kyleknap** [comment]
@jlchereau 

I am not entirely sure how you would do this through the ECS API or if you can. I would suggest to post a question in the AWS Developer Forums for ECS: https://forums.aws.amazon.com/forum.jspa?forumID=187

As to the documentation, the ECS API represents that parameter as a list, which is why you can pass multiple load balancers to that argument. If they did not represent this as a list (say a structure), the ECS API would have to make a breaking change if they ever wanted to allow for more than one load balancer, and so the one load balancer per service restriction is imposed server side.

Let me know if you have any more questions.

**Comment by flowhamster** [comment]
@kyleknap  https://forums.aws.amazon.com/thread.jspa?messageID=596982&#596982 

```
If you leave out the host port, or specify it as being '0', in your task definition, then the port will be chosen automatically and reported back to the service. After the task is running, describing it should show what port(s) it bound to.

You cannot currently specify something like -P where all ports are mapped through, but simply specifying port mappings for all container ports with no host ports should give you similar behavior.

Finally, there is a known bug where a task with exposed ports (as specified in the image) that are not mapped will not work correctly (e.g. nginx if you only map 80 but not 443 since it exposes both). We're aware of this issue and are looking into it. 
```

If I understand that correctly if you specify 0 as the port then all ports mapped on the ELB will be passed through to the specified container. It would be very helpful to add that to the docs for many nginx setups

**Comment by kyleknap** [comment]
Noted. It would also be awesome if someone can request getting this message added to ECS's API docs in the opened forum thread as well.
