### ISSUE TITLE
other swift/objects services

### ISSUE THREAD

**Issue by ghost** [aws/aws-cli#1367]
Can we use with other swift / s3 like services, like dreamhost's dreamobjects ?

Maybe a configuration tool to specity the endpoint

**Comment by kyleknap** [comment]
We do not officially support other  s3-like, third-party services.

I suppose you could try by specifying the endpoint with ``--endpoint-url``, but I cannot say if it will work or not.

**Comment by kyleknap** [comment]
Closing issue. Please reopen if you have anymore questions.
