### ISSUE TITLE
[BUG] [aws deploy push] The Destination Bundle Type Does not Perform Compression (Zipping/Tarring)

### ISSUE THREAD

**Issue by virgofx** [aws/aws-cli#1371]
When specifying a destination with a suffix of ".zip" or ".tar" or ".tar.gz" for use with the `aws deploy push` command ... which are all allowed revisions ... the resulting bundle is not compressed.

Either the extension of the bundle could automatically determine the desired compression or an alternate flag could be specified which determines that the actual file should be compressed using that appropriate mechanism.

I noticed this testing large deployments that  were filling up S3 very fast --- when compressed it would have been not noticeable.

Additionally, directories with no files in them do not appear in the resulting bundle.

**Comment by kyleknap** [comment]
Thanks for reporting. We are looking into this.
