### ISSUE TITLE
aws s3 cp option to linearize writes

### ISSUE THREAD

**Issue by kislyuk** [aws/aws-cli#1373]
When downloading large files, `aws s3 cp` output can't be sent to a fifo pipe, and as such can't be pipelined with other commands for efficiency. This is because fifo pipes don't support seeking, and cp writes chunks out of order as they are downloaded simultaneously.

A preferable solution would be to have an option to write downloaded chunks to temporary files or hold them in memory until all chunks in front of them arrive, and never seek on the final output, writing all bytes in order.

**Comment by kislyuk** [comment]
By the way, the docs at https://github.com/aws/aws-cli/blob/develop/awscli/examples/s3/cp.rst imply that this should be possible with `aws s3 cp s3://... -`, but this doesn't actually work.

**Comment by kyleknap** [comment]
What version of the CLI are you using? You can figure it out by running: ``aws --version``. You may need to upgrade the CLI to be able to stream downloads to standard output.

**Comment by kislyuk** [comment]
You're right - upgrading from 1.3.9 to 1.7.32 helped. Thanks!
