### ISSUE TITLE
Pass a file as a parameter to create-stack?

### ISSUE THREAD

**Issue by ejholmes** [aws/aws-cli#1400]
Hey there!

I have a parameter in my CloudFormation stack called `DockerAuth` and I want to provide the value as the contents of `~/.dockercfg` (which is JSON) using the CLI. However, no matter how I try to escape the contents, the CLI will eventually complain with:

```console
--parameters ParameterKey=string,ParameterValue=string,UsePreviousValue=boolean ParameterKey=string,ParameterValue=string,UsePreviousValue=boolean
```

For example, this trivial value will result in the error above:

```console
$ aws cloudformation create-stack --stack-name foo \
  --template-body file:///$PWD/stack.json \
  --parameters ParameterKey=DockerAuth,ParameterValue=\{\"\":\"\"\}
```

This, however, does not fail:

```console
$ aws cloudformation create-stack --stack-name foo \
  --template-body file:///$PWD/stack.json \
  --parameters ParameterKey=DockerAuth,ParameterValue=\{\"\"\}
```

**Comment by kyleknap** [comment]
@ejholmes 

Are you just trying to provide an empty structure for the value?

Would something like this work?
```
$ aws cloudformation create-stack --stack-name foo \
  --template-body file:///$PWD/stack.json \
  --parameters ParameterKey=DockerAuth,ParameterValue={}
```

**Comment by ejholmes** [comment]
Hey @kyleknap. Actually, I want to pass a json string. I should be able to escape it with `$(printf '%q' $(cat ~/.dockercfg))`, but that results in the error I mentioned above.

**Comment by kyleknap** [comment]
Ahh, try using %s instead of %q for your printf command. The %q tries to escape the brackets, which is not correct for input to the CLI.

**Comment by jamesls** [comment]
Closing out old issue.  Please let us know if Kyle's suggestion does not work and we'll take another look.
