### ISSUE TITLE
aws ec2 run-instances Command - Doesn't Describe Use of "file://path/file.json" for --user-data

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-cli#1407]
Running `aws ec2 run-instances help` displays the following result:

`--user-data (string)`
`The Base64-encoded MIME user data for the instances.`

More valuable would be:
`--user-data (string)`
`The Base64-encoded MIME user data for the instances or a path to a file. If a file is used the file location should be given as file://path/to/user-data.file.`

**Comment by kyleknap** [comment]
@colinbjohnson 

Can you provide some insight on how you at first interpreted the documentation for the parameter (e.g. what value did you think you needed to provide)? Do you think adding an example of how to provide user data would help alleviate confusion?

**Comment by justnance** [comment]
@colinbjohnson - Thank you for reporting this issue unfortunately this issue will closing soon due to inactivity.  It also appears it somewhat related to #733.
