### ISSUE TITLE
Request - CLI for WorkMail

### ISSUE THREAD

**Issue by vikas027** [aws/aws-cli#1408]
Hello,

WorkMail is not listed in this list - http://docs.aws.amazon.com/cli/latest/reference/#available-services

Is it in the pipeline ? I am looking out a way to create users and set their password via command line. 

Regards.

**Comment by mtdowling** [comment]
Amazon WorkMail is currently only available in Preview. If you would like to sign up to use Amazon WorkMail, please fill in the form located at http://aws.amazon.com/workmail/preview/. After filling out the form, you will be contacted as soon as it is possible to add you to the preview with instructions on how to get started.

**Comment by vikas027** [comment]
I already have access to WorkMail, all I am looking a way out to manage WorkMail users via API/CLI.

**Comment by callmeradical** [comment]
This is out of preview now? How about some API/CLI access?

**Comment by vikas027** [comment]
@mtdowling Can you please reopen this case ? This shouldn't have been closed in the first place.

**Comment by dni** [comment]
is there an API/CLI yet?

**Comment by vikas027** [comment]
No, and the case has been closed :|
