### ISSUE TITLE
Name tag for a new instance

### ISSUE THREAD

**Issue by flypunk** [aws/aws-cli#141]
Hi,

Is it possible to specify a Name or other tags while creating an instance with 
"aws ec2 run-instances"?

Thanks!

**Comment by kanuparthyr** [comment]
Any update on this enhancement?

**Comment by kyleknap** [comment]
The underlying EC2 api still does not support it. I would recommend requesting it on the AWS Developer forums: https://forums.aws.amazon.com/forum.jspa?forumID=30
