### ISSUE TITLE
Exlude / Delete / Sync

### ISSUE THREAD

**Issue by elmic11111** [aws/aws-cli#1410]
When using Sync and the Exclude the command. The system doesn't seem to ignore the exude files on the remote server. Just the local server. 

The effect I was going was to have extra files of a certain pattern on the remove server that it didn't delete when it did the sync which doesn't existed on the local server.

**Comment by mtdowling** [comment]
Sync filters apply to both source and destination files. Can you provide a reproducible test case to illustrate the issue? What CLI command and arguments did you provide? What files were local and what files were remote?

**Comment by elmic11111** [comment]
It seems to work on. I realized I was using an old version, updated it and tried again and it works. sorry about the bad issue report.
