### ISSUE TITLE
UpLoading problem

### ISSUE THREAD

**Issue by ajay2c9** [aws/aws-cli#1420]
hai I am uploading the Videos and images to the s3 bucket the code i used is blow for upload.
for image uploading:

 self.tm = [S3TransferManager new];
    self.tm.s3 = self.s3;
  self.s3putObjectreq = [[S3PutObjectRequest alloc] initWithKey:imgname   inBucket:[Constants pictureBucket]] ;
    self.s3putObjectreq.contentType = @"image/jpeg";
    self.s3putObjectreq.data        = postimagedata;
    self.s3putObjectreq.cannedACL   = [S3CannedACL publicRead];
    
    self.s3putObjectreq.contentLength = [postimagedata length];
    self.s3putObjectreq.delegate = self;
    self.s3putObjectres=[self.s3 putObject:self.s3putObjectreq];

//For video

 NSString* filename = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:completeFileName];
    
    // ////NSLog(@"your movie data length~~~~~~~ %d",yourMovieData.length);
    [[NSFileManager defaultManager] createFileAtPath:filename contents:postvideoData attributes:nil];
    
    NSLog(@"the videoname name is %@",videoname);
    
    NSLog(@"the file name is %@",filename);
    
    
    self.tm = [S3TransferManager new];
    self.tm.s3 = self.s3;
    //    self.s3putObjectreq = [[S3PutObjectRequest alloc] initWithKey:videoname inBucket:[Constants videoBucket]];
     self.s3putObjectres=[self.tm uploadFile:filename bucket:[Constants videoBucket] key:videoname];
//
for the above code the didCompleteWithResponse:and request didReceiveResponse: delegate and methods are calling when the generated url are seeing in the browser it shows the error message.Please suggest how to identify and solve this problem . if error occur how to resend the same data.

**Comment by mtdowling** [comment]
It looks like you're using the IOS SDK and not the AWS CLI. You'll want to open this issue on the AWS Mobile SDK for IOS so that your issue can be handled by the appropriate team.

https://github.com/aws/aws-sdk-ios
