### ISSUE TITLE
How to delete an event of s3

### ISSUE THREAD

**Issue by zhiyelee** [aws/aws-cli#1421]
Throw `s3api put-bucket-notification-configuration`, we can create notification events, but can't find a way to delete the notification.

After I deleted the connected Lambda function, the s3 Event still links to the deleted function. It could be better, if  the event item could been deleted automatically, once the relative lambda function gets deleted.

**Comment by mtdowling** [comment]
You change a bucket's notification configuration using `s3api put-bucket-notification-configuration`. To clear out the configuration completely, try the following command:

```
aws s3api put-bucket-notification-configuration --bucket=mybucket --notification-configuration="{}"
```

Thanks for the feature request. A great place to get in touch with the Lambda team is through their forums at: https://forums.aws.amazon.com/forum.jspa?forumID=186

**Comment by zhiyelee** [comment]
Thank you @mtdowling  A little tricky, all similar api follow this pattern?

**Comment by mtdowling** [comment]
For S3, yes. Anything that you can pass an empty value to should accept "{}"

**Comment by zhiyelee** [comment]
Thank you @mtdowling  Sorry, I forgot to close it.
