### ISSUE TITLE
aws lambda -- add api endpoint when creating lambda function

### ISSUE THREAD

**Issue by ndrppnc** [aws/aws-cli#1424]
Is it possible to add an API endpoint when creating a lambda function? It seems like this is the only feature missing from the CLI as opposed to the web console. Thanks!

Updated: this is more a feature request. Sorry I just realized the service just launched!

**Comment by jamesls** [comment]
The AWS CLI now supports API gateway, so you should be able to use the `aws apigateway` commands to configure API endpoints that are associated with lambda functions.
