### ISSUE TITLE
multipart-uploads still exist after failed partial upload

### ISSUE THREAD

**Issue by keturn** [aws/aws-cli#1428]
My `aws s3 sync` failed:

```
upload failed: foo.ova to s3://my-bucket/foo.ova
('Connection aborted.', error(32, 'Broken pipe'))
upload failed: foo.ova to s3://my-bucket/foo.ova
('Connection aborted.', error(32, 'Broken pipe'))
upload failed: bar.ova to s3://my-bucket/bar.ova
Could not connect to the endpoint URL: "https://my-bucket.s3-us-west-2.amazonaws.com/bar.ova?partNumber=208&uploadId=secr1ts”
Completed 832 of 3307 part(s) with -1 file(s) remaining
```

It seems this is expected to remove all the multipart-uploads it's created, but when I `s3api list-multipart-uploads` it still has entries for these files:

``` javascript
{
    "Uploads": [
        {
            "Initiator": {
                "DisplayName": "keturn", 
                "ID": "arn:aws:iam::783___:user/keturn"
            }, 
            "Initiated": "2015-07-17T19:07:35.000Z", 
            "UploadId": “h1dd3n”, 
            "StorageClass": "STANDARD", 
            "Key": "foo.ova", 
            "Owner": {
                "DisplayName": "s3owner", 
                "ID": "357___”
            }
        }, 
        {
            "Initiator": {
                "DisplayName": "keturn", 
                "ID": "arn:aws:iam::783___:user/keturn"
            }, 
            "Initiated": "2015-07-17T20:05:01.000Z", 
            "UploadId": "secr1ts", 
            "StorageClass": "STANDARD", 
            "Key": “bar.ova", 
            "Owner": {
                "DisplayName": "s3owner", 
                "ID": "357___”
            }
        }
    ], 
    "CommonPrefixes": []
}
```

**Comment by rayluo** [comment]
It really depends on how your upload session is broken. If it is caused by a physical broken network connection (BTW, is that the way you generate this test case?), there is no way the aws-cli can try to clean up the mess for you. Does that make sense?

Your another feature request about resuming the previous upload is still a valid point.

**Comment by hanpeter** [comment]
Looks like I am running into a similar issue. According to the [documentation](http://docs.aws.amazon.com/cli/latest/userguide/using-s3-commands.html), aws cli should abort multipart upload upon receiving SIGINT signal. I also see the code to make that happen in [s3handler.py](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/s3handler.py#L126). However, I am still seeing the multipart upload entries hanging around after the termination.

Looking at the debug log, I think one or more threads that were spun off to handle the multipart upload is not terminated before aborting the upload, causing the entries to re-appear.

Let me know if you need any more information from me.

**Comment by damiandennis** [comment]
Same issue here, its happening with anything large. small transfers work just fine.

**Comment by JordonPhillips** [comment]
We now clean these up on the latest versions of the CLI!
