### ISSUE TITLE
Return output on put-role-policy

### ISSUE THREAD

**Issue by thephilwells** [aws/aws-cli#1434]
It would be comforting if this command presented the output for `aws iam --role-name [role-just-affected] --policy-name [policy-just-put]` after its successful completion.

**Comment by kyleknap** [comment]
Based on IAM's API docs: http://docs.aws.amazon.com/IAM/latest/APIReference/API_PutRolePolicy.html, the service's response does not have any output parameters other than the request id. The CLI only generates requests and displays the response from the service. So if you want that operation to have an output I would suggest sending a feature request to the AWS Developer Forums: https://forums.aws.amazon.com/forum.jspa?forumID=76.

Let me know if you have any more questions.

**Comment by thephilwells** [comment]
Works for me. Thanks!
