### ISSUE TITLE
doc request: expand put-log-events

### ISSUE THREAD

**Issue by agordon** [aws/aws-cli#1443]
Hello,

In the documentation for `put-log events`, please mention that the parameter `timestamp` should be milliseconds since epoch (1970-01-01- 00:00:00 UTC).
That tiny bit of information (i.e. milliseconds instead of seconds) can prevent lots of frustrations with 'too old' log message rejection.

Thanks!

**Comment by jamesls** [comment]
Thanks for the feedback, we're looking into getting that updated.

**Comment by justnance** [comment]
@agordon - Thank you again for reporting this issue. Our documentation has been updated.  

https://docs.aws.amazon.com/cli/latest/reference/logs/put-log-events.html
https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html
