### ISSUE TITLE
Incorrect error message for duplicate "values".

### ISSUE THREAD

**Issue by adamv** [aws/aws-cli#1448]
I created a template definition with objects, values, and parameters, and tried to put the definition while also supplying a values file.

The error message said "Only parameter-values or parameter-values-uri is allowed".

But I had only passed a parameter-values-uri option. The values in the pipeline definition itself triggered this error message, and I had to debug for a while before I realized what the actual cause was.

Suggest the error message either handle both error cases, or better, two different error messages are used for the different error cases.

**Comment by jamesls** [comment]
Do you have example commands you can share that demonstrate the problem?

**Comment by adamv** [comment]
On Monday I'll isolate a minimal example and verify my version of awscli.
