### ISSUE TITLE
Unable to use dash in option value

### ISSUE THREAD

**Issue by kimh** [aws/aws-cli#1470]
Version: 1.8.0

The same command used to work at least in 1.7.42 but not in 1.8.0.

```
$ aws s3api create-multipart-upload --metadata "uncompressed-length=111" --bucket my-bucket --key my-key
Error parsing parameter '--metadata': Expected: '=', received: '-' for input:
uncompressed-length=111
```

Looks it complains `-` in uncompressed-length. Is this an expected change?

**Comment by jamesls** [comment]
Not intended, this is a regression.  We'll get this fixed.  Thanks for reporting.

**Comment by henrjk** [comment]
I think I am seeing the same issue. I observed this in a build which used to work. The builds were off for 2 or 3 months. The error showed for me with this version:

```console
aws --version
aws-cli/1.8.2 Python/2.7.3 Linux/3.13.0-57-generic
```

The command that fails is this:
```console
aws s3api put-object --bucket builds-shippables-doggie.example.net --key henkr/doggie/doggie-228.1.tar.gz.gpg --content-md5 +A+JCM/D88l35LqcQQl5aw== --metadata SHIPPABLE_BUILD_ID=55eeb529b2ed760b00cfe732,BUILD_URL=https://app.shippable.com/builds/55eeb529b2ed760b00cfe732,BRANCH=master,COMPARE_URL=https://bitbucket.org/henkr/doggie/branches/compare/bdca26b53565fbc08e52e7a2915c192cd4002dae..e4e4a14374bb#diff --body shippable/shippable.tar.gz.gpg

Error parsing parameter '--metadata': Expected: '=', received: '_' for input:
SHIPPABLE_BUILD_ID=55eeb529b2ed760b00cfe732,BUILD_URL=https://app.shippable.com/builds/55eeb529b2ed760b00cfe732,BRANCH=master,COMPARE_URL=https://bitbucket.org/henkr/doggie/branches/compare/bdca26b53565fbc08e52e7a2915c192cd4002dae..e4e4a14374bb#diff
         ^
```

Can you comment on:

1. what is the most recent release which does not have the issue?  

2. when do you project that the fix might be released? 

Thank you!

**Comment by henrjk** [comment]
Just tried it with `aws-cli/1.8.3 Python/2.7.3 Linux/3.13.0-57-generic`. It was still failing for me.

**Comment by jamesls** [comment]
@henrjk Looks like there's a regression with the `_` char as well.  I'll get that updated.  Thanks for reporting.

**Comment by ltagliamonte** [comment]
I have the same issue creating an ES domain:
```
--advanced-options 'est.action.multi.allow_explicit_index'='true','indices.fielddata.cache.size'='40'
```
i'm using the latest awscli:
```
aws-cli/1.9.7 Python/2.7.5 Darwin/13.4.0 botocore/1.3.7
```
any ETA about this issue solved?

**Comment by BobertForever** [comment]
I'm getting the same issues doing an elasticbeanstalk update.
```
aws elasticbeanstalk update-environment --environment-name beek --option-settings elb-acm.json
```
using the latest aws-cli as well. I believe this issue should be reopened because this seems to have regressed.

**Comment by kyleknap** [comment]
@BobertForever 
I do not think it is still an issue. If you are going to use the file ``elb-acm.json`` for ``--option-settings`` you will need to prefix it with ``file://``. So something like this:
```
aws elasticbeanstalk update-environment --environment-name tmp --option-settings file://elb-acm.json
```

**Comment by BobertForever** [comment]
oh, I didn't realize you had to actually type out that `file://. That's... bizarre syntax for a command line tool. I suppose it's working in that case, though the error message was a bit less than helpful.

**Comment by spyderdyne** [comment]
Requested:
`--iam-instance-profile=aws-ca-gateway`

Returned:
`Error parsing parameter '--iam-instance-profile': Expected: '=', received: 'EOF' for input:
aws-ca-gateway`

**Comment by itonics-tbeauvais** [comment]
I was able to resolve this with a fully qualified path.  Why on earth do I need to use a fully qualified path?  These are scripts checked into a repo.  I need to be able to use the PWD.

**Comment by akotranza** [comment]
Agreed, using absolute file:/// paths is a major pain when you are running all of these commands in a job in your CI tool. (Which you should be doing, infrastructure-as-code, and all that)
