### ISSUE TITLE
Filter do not support spaces

### ISSUE THREAD

**Issue by andibadu** [aws/aws-cli#1471]
I updated the aws client to 1.8.0. Now, the script for creating an instance does not work any more.

aws --profile default --region us-west-1 ec2 describe-subnets --filters 'Name=subnet-id,Values=Private A' Name=vpc-id,Values=vpc-MYVPC --query 'Subnets[*].SubnetId' --output=text

The error message is:
Error parsing parameter '--filters': Expected: ',', received: 'A' for input:
Name=subnet-id,Values=Private A
                              ^

So there is a space in the subnet-id and I cannot filter it any more. 
The command worked with 1.7.x

**Comment by jamesls** [comment]
Thanks for reporting.  We'll get this fixed.

**Comment by jamesls** [comment]
Just want to mention that while we will fix the current behavior, the workaround for now is to double quote the value with spaces:


```
 --filters 'Name=subnet-id,Values="Private A"' Name=vpc-id,Values=vpc-MYVPC 
```
