### ISSUE TITLE
'unicode' object has no attribute 'append'

### ISSUE THREAD

**Issue by ttback** [aws/aws-cli#1472]
Getting an `'unicode' object has no attribute 'append'` when trying to do `aws emr` create-cluster with options.

There is no line number or any hint on what that error might be triggered, any tip on how I could debug this?

**Comment by ttback** [comment]
nvm, this was only happening to aws-cli/1.7.18 Python/2.7.9 Darwin/14.4.0
after upgrading to aws-cli/1.8.0 Python/2.7.9 Darwin/14.4.0, it's gone.

**Comment by kyleknap** [comment]
Interesting. Well glad to hear it is fixed in the latest version of the CLI. Closing.
