### ISSUE TITLE
Unintended consequences of s3  Head Bucket request

### ISSUE THREAD

**Issue by andrewgoodchild** [aws/aws-cli#1480]
Hi

I have been building instructions to allow our users  to script uploads to folders we hold in a s3 bucket using the AWS CLI and temporary credentials issued by the AWS STS API.

I have since found that when you can use STS to issue a temporary credential to access a specific folder in a S3 bukcet, you also need to grant users access to the ListBucket operation on the whole S3 bucket as well,.  This is because AWS CLI when doing an 'ls' and 'sync'  first validates the existence of a bucket by doing a get 'HEAD Bucket Request' before permitting the user to list the contents of a folder.

here is an example policy: 

"Policy":"{"Version": "2012-10-17","Statement": [
{"Effect": "Allow\","Action": ["s3:ListBucket", "s3:GetBucketLocation", "s3:ListBucketMultipartUploads" ], "Resource": ["arn:aws:s3:::my-bucket-name"] },
{"Effect": "Allow","Action": ["s3:Get*", "s3:PutObject", "s3:AbortMultipartUpload" ], "Resource": ["arn:aws:s3:::my-bucket-name/my-folder-name/*"] }]}"}
}"}

As a result the unintended consequence is the user can now view the filenames in other folders and not just the contents of the folders they have been granted access to.

I asked the AWS support team what we should do, and they recommended we raise an issue here..

I would like a feature that allows me to work around this problem by having a setting in the AWS CLI  that switches off get HEAD Bucket  validation requests to test for bucket existence (i.e. it forces s3.get_bucket('mybucket', validate=False)).

thanks, Andrew

**Comment by kyleknap** [comment]
What version of the CLI are you using? I do not think the current version of the CLI uses the ``HeadBucket`` operation anymore for validation of bucket existance.

**Comment by andrewgoodchild** [comment]
Hi,

I was running 1.7.42.  I upgraded to 1.8.1 

Even under 1.8.1, if I create a temporary credential using STS assumeRole() that only permits access to the folder and not the bucket, such as:

"Policy":"{"Version": "2012-10-17","Statement": [
{"Effect": "Allow","Action": ["s3:Get", "s3:PutObject", "s3:AbortMultipartUpload" ], "Resource": ["arn:aws:s3:::my-bucket-name/my-folder-name/"] }]}"}
}"}

And then do a:

aws --profile TEMP_CRED s3 ls s3://my-bucket-name/my-folder-name/

I get:

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied

To make the problem go away, I still need to generate a temporary credential with STS using a policy that allows listbucket access as above, which has the unintended consequence of permitting list bucket access on any folder.

I suspect the issue is not a CLI issue.  I think the problem is with S3 policies as there is no way of granting listObject access for a specific folder and you can only grant listBucket access on the whole bucket.

**Comment by garnaat** [comment]
If you want to be able to list the contents of the bucket, even for only a part of the bucket, you need to provide the ``s3:ListBucket`` action in the policy.

However, you can restrict that so that you can only list a part of the bucket by using a Condition.  For example:

        {
          "Effect": "Allow",
          "Action": ["s3:ListBucket"],
          "Resource": ["arn:aws:s3:::my-bucket-name"],
          "Condition": {"StringLike": {"s3:prefix": ["my-folder-name/"]}}
        },

Should only allow the listing of objects that have a ``prefix`` that matches your "folder" name.

Does that work for you?

**Comment by andrewgoodchild** [comment]
:+1: 

Works like a dream.  Many thanks. Andrew
