### ISSUE TITLE
aws s3 sync --delete behaves differently if source is <LocalPath> rather than <S3Path>

### ISSUE THREAD

**Issue by jrotenstein** [aws/aws-cli#1481]
This issue was raised on: https://stackoverflow.com/questions/32304326/amazon-s3-sync-deleting-excluded-files

Basically, doing `aws s3 sync . s3://bucket2 --delete` behaves differently to `aws s3 sync s3://bucket1 s3://bucket2 --delete` even if the two source directories are identical.

It would appear that the logic for `--delete` behaves differently between Local and S3. An example is well-documented in the stackoverflow issue.

**Comment by kyleknap** [comment]
I can confirm the file being unexpectedly deleted. The files being copied over from the s3 bucket to other s3 bucket is as expected because the objects in the origin bucket are newer than the objects in the destination bucket.

**Comment by JordonPhillips** [comment]
Confirmed on both OSX and Linux, investigating
