### ISSUE TITLE
AWS s3 ls error Handling through unix script

### ISSUE THREAD

**Issue by RamPatel58** [aws/aws-cli#1492]
I am  connecting aws from ec2 using unix shell script and using  below code find is there files are present in bucket or not ....
In  case if any error occurs during connecting to aws I want to handle with proper massage.. 
In below code if error occur aws s3  the $?  in not changing  it will only zero...
How can I capture from aws s3 and how to do the error handling in this case ..
For testing purpose I have modified aws configure file and given wrong credentials after that I am getting below error   
A client error (InvalidAccessKeyId) occurred when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
But it is not goving inside my error block.Please provide me any update
 
new-file_count =`aws s3 ls <buckket_path> | wc -l`

if [ $? -ne 0 ]
then
    echo -e "`date` : Error  occurs while connecting  aws s3.. "    	
fi
    	
if [ $new_file_count  -eq 0 ]
 then
    		echo -e "`date` : There are no new files present @bucket/ for $table_name"
error_exit "no_source_file"
fi

A client error (InvalidAccessKeyId) occurred when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by rayluo** [comment]
I think the key is how to get the error code of the previous command in pipe. And there is some useful information here. http://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another

Let me know if you need more help. Thanks.

**Comment by RamPatel58** [comment]
Thanks for update,
But it is not working I am looking for if any error written by aws s3 ls that should be capture like error code

**Comment by rayluo** [comment]
There may be other ways to do this too, but at least the follow code snippet works for me.

    aws s3 ls > /tmp/temp.txt

    if [ $? -ne 0 ]
    then
    echo -e "date : Error occurs while connecting aws s3.. "
    fi

    new_file_count=`wc -l</tmp/temp.txt`
    if [ $new_file_count -eq 0 ]
    then
    echo -e "date : There are no new files present @bucket/ for $table_name"
    error_exit "no_source_file"
    fi

**Comment by RamPatel58** [comment]
Thanks rayluo

This is solution is working for me ..
Once again thank you for giving your time....

**Comment by RamPatel58** [comment]
Thanks,

This is solved my problem..

thank you for giving your time

On Wed, Sep 9, 2015 at 11:56 PM, Ray Luo <notifications@github.com> wrote:

> There may be other ways to do this too, but at least the follow code
> snippet works for me.
>
> aws s3 ls > /tmp/temp.txt
>
> if [ $? -ne 0 ]
> then
> echo -e "date : Error occurs while connecting aws s3.. "
> fi
>
> new_file_count=`wc -l</tmp/temp.txt`
> if [ $new_file_count -eq 0 ]
> then
> echo -e "date : There are no new files present @bucket/ for $table_name"
> error_exit "no_source_file"
> fi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-cli/issues/1492#issuecomment-138998331>.
>



-- 




Thank You,
Regards
Ram Narayan Patel
contact No.8197879468

**Comment by hoihoi8** [comment]
Now the question is, why did one work but the other didn't?
