### ISSUE TITLE
aws schedule-run documentation --test parameters

### ISSUE THREAD

**Issue by jrejaud** [aws/aws-cli#1497]
Can the [schedule-run documentation](http://docs.aws.amazon.com/cli/latest/reference/devicefarm/schedule-run.html) be more explicit about what needs to be provided to --test parameters? I don't see an equivalent in the GUI.

**Comment by rayluo** [comment]
Thanks for pointing out. There is definitely room for improvement here. I'll mark this one as a feature request in terms of documentation improvement. Before that, you can try to read the [document of the API Reference of this service](http://docs.aws.amazon.com/devicefarm/latest/APIReference/API_ScheduleRun.html) to know more.

Hope that helps.

**Comment by jrejaud** [comment]
Hi rayluo, thanks for your comment.

I read over the link you provided (very helpful), but I'm still getting a 
```
A client error (ArgumentException) occurred when calling the ScheduleRun operation: Missing or unprocessed resources.
```

error when trying to use schedule-run via the following line of code:
```
aws devicefarm schedule-run --project-arn $PROJECT_ARN --app-arn $APP_UPLOAD_ARN --device-pool-arn $DEVICE_POOL_ARN --test type=INSTRUMENTATION,testPackageArn=$TESTS_UPLOAD_ARN
```

Could you provide me some more info as to what parameters I could be missing please?

**Comment by rayluo** [comment]
As a generic hint, you can append ``--debug`` at the end of your aws cli, and then you will have lots of output, which may reveal more detail.

On the other hand, I would like to suggest you to repost your question in the [AWS Device Farm Forum](https://forums.aws.amazon.com/forum.jspa?forumID=193). I believe there are more Device Farm users and experts there to help you more efficiently.

**Comment by dylanmcintyre** [comment]
@rayluo 
Can you post an example usage of the cli schedule-run command --test parameters?  I've tried many combinations and all yield the same error as @jrejaud. Appending `--debug` gives an unhelpful Python stack trace which I've investigated and is altogether not useful.

**Comment by nishanthvallambatla** [comment]
I am facing the same problem. Could you please tell me whether this is resolved?
Thank You.

**Comment by rjatling** [comment]
Is this issue resolved yet? I am facing the same problem. After uploading the files, i was able to successfully run the test from UI but not able to run through CLI. Please help.
Thanks

**Comment by jrejaud** [comment]
I never resolved it
Cheers, Jordan Rejaud, EIT San Francisco, CA M.S. Carnegie Mellon University jrejaud@gmail.com jordanrejaud.com





On Mon, Jul 25, 2016 6:57 PM, rjatling notifications@github.com wrote:
Is this issue resolved yet? I am facing the same problem. After uploading the
files, i was able to successfully run the test from UI but not able to run
through CLI. Please help.
Thanks

**Comment by dwillmc** [comment]
I was able to resolve my issues with the CLI a while back. It looks like this is how I ended up using the `--test` parameter and scheduling the run:

```
TEST_INFO="{\"type\":\"INSTRUMENTATION\",\"testPackageArn\":\"$TESTS_ARN\"}";
TEST_RESULT=`aws devicefarm schedule-run --project-arn "$AWS_PROJECT_ARN" --app-arn "$APK_ARN" --device-pool-arn "$AWS_DEVICE_POOL_ARN" --name "$RUN_NAME" --test "$TEST_INFO"`
```

Hope it helps

**Comment by rjatling** [comment]
Thanks dwillmc ! This helped.

**Comment by techvedikasolutions** [comment]
aws devicefarm schedule-run --project-arn "$proarn" --app-arn "$apparn" --device-pool-arn "$devicePoolarn" --name "Automated script" --test '{"type":"APPIUM_JAVA_TESTNG","testPackageArn":"$testPackageArn"}'
now also getting same error
An error occurred (ArgumentException) when calling the ScheduleRun operation: Missing or unprocessed resources.
Is it anything i am missing to include

**Comment by Sabesna** [comment]
Hello 
I am trying to create schedule  run in the aws devicefarm after doing the following steps.

1. Created a Project and got the project arn also as a response.
2. Created a maven .zip package for a simple APPIUM_JAVA_TESTNG execution that will open chrome browser in the mobile device and load google.com.
3. Uploaded the package to the aws using the 'create-upload' command and also using 'curl' have uploaded the package to the URL received. Also using 'get-upload' command have got the upload arn as response with 'SUCCEEDED' status.
4. Using the 'schedule-run' command when i try to run the test by providing the upload arn got from the server I am getting error stating 
"An error occurred (ArgumentException) when calling the ScheduleRun operation: Invalid Upload arn: null"

This is the complete command that I am providing

`aws devicefarm schedule-run --project-arn "arn:aws:devicefarm:us-west-2:410979834468:project:79179ec4-7865-4d1f-8550-102f55e574be" --device-pool-arn "arn:aws:devicefarm:us-west-2::devicepool:082d10e5-d7d7-48a5-ba5c-b33d66efa1f5" --name "LoadGoogle_06202017_1" --test "{\"type\":\"APPIUM_JAVA_TESTNG\",\"testPackageArn\":\"arn:aws:devicefarm:us-west-2:410979834468:upload:79179ec4-7865-4d1f-8550-102f55e574be/5ceccdcb-b529-4200-9cca-241f942b4ed4\"}"`

Please help me solve this error. I am trying to do this for quite a long time.

If you need any other information I may provide. Please help.

Thanks in Advance



>

**Comment by techvedikasolutions** [comment]
Hi i was using this command for android and iOS. Just try this format
schedule-run –project-arn ${PROJECT_ARN} –app-arn ${APP_ARN} –device-pool-arn ${DEVICEPOOL_ARN} –name ${TESTRUN_NAME} –test ‘{“type”:”APPIUM_JAVA_TESTNG”,”testPackageArn”:”‘${TESTSCRIPT_ARN}'”}’

Regards
Rijo

**Comment by Sabesna** [comment]
Hi @techvedikasolutions 

Thanks for the response. It worked and was also able to run the sample test script in the CURATED device pool.

Can anyone help me with following doubt.

I have some test datas that has to be provided to the test case during run time. How to do that in AWS?
How can we upload the excel file to AWS and run the script?

Please help me. I am stuck in this.

Thanks in advance.

**Comment by Sabesna** [comment]
Hi All,

About the issue

> I have some test data that has to be provided to the test case during run time.
> How to do that in AWS?
> How can we upload the excel file to AWS and fetch the data from it in the run time?
> What path do i have to mention in the script for retrieving the values from the sheet?
> 
> Please help me. I am stuck in this.

 I have uploaded the excel files in a zip, that i need for the test to the AWS using 'create-upload' in type 'EXTERNAL_DATA' (the response is below). 

{
    "status": "SUCCEEDED",
    "type": "EXTERNAL_DATA",
    "name": "External Files",
    "arn": "arn:aws:devicefarm:us-west-2:410979834468:upload:79179ec4-7865-4d1f-8550-102f55e574be/afee24ca-84dc-4d1d-87ad-f337f5ca7735",
    "created": 1498127930.865
}

Now how i can access that files from the java code in the maven of my project in AWS. If any one did this already please help with a small example.

Thanks in Advance
M. Sabesan

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by kdaily** [comment]
It looks like this issue has been resolved and the documentation has been updated. @sab-sv if you are still having trouble, please open a [new issue](https://github.com/aws/aws-cli/issues/new/choose). Thanks!
