### ISSUE TITLE
Downgrading rsa package

### ISSUE THREAD

**Issue by orome** [aws/aws-cli#1498]
The awscli install or update (`pip install -U awscli `) is downgrading rsa (to 3.1.4).

**Comment by rayluo** [comment]
Yes this is the real reason causing your issue in botocore. Again, we will need to test the new version rsa before we can upgrade.

**Comment by orome** [comment]
Sorry to ask here but perhaps you can direct me to the right issues list for this (similar) issue:

The awsebcli package installation is again downgrading other packages:

    cement to 2.40
    docker-py to1.1.0
    pathspec to 0.3.3
    requests to 2.6.2

**Comment by jamesls** [comment]
Diff looks fine, let's bump the version up to `<3.3`: https://bitbucket.org/sybren/python-rsa/branches/compare/version-3.2%0Dversion-3.1.4#diff

@orome For ebcli the best place to reach out would be the [AWS Elastic Beanstalk forums](https://forums.aws.amazon.com/forum.jspa?forumID=86).

**Comment by jamesls** [comment]
This has now been fixed.
