### ISSUE TITLE
aws s3

### ISSUE THREAD

**Issue by rakeshpb90** [aws/aws-cli#1500]
Is aws s3 command line support server side encryption using KMS encryption.

**Comment by rayluo** [comment]
Sorry the "aws s3" does not support SSE-KMS at this moment. This is a [popular topic](https://github.com/aws/aws-cli/search?q=kms&type=Issues&utf8=%E2%9C%93) though, and the [most recent PR is here](https://github.com/aws/aws-cli/pull/1487).

I will close this question here and let's keep track in that PR. Thanks.
