### ISSUE TITLE
ec2.authorizeSecurityGroupIngress case wrong on error message

### ISSUE THREAD

**Issue by rainabba** [aws/aws-cli#1503]
"The request must contain the parameter groupName or groupId" but these should be "GroupName or GroupID" per http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#authorizeSecurityGroupIngress-property

**Comment by rayluo** [comment]
Sounds like an error on error message, per this backend service [api doc](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AuthorizeSecurityGroupIngress.html).

Are you using CLI or JavaScript SDK (you mentioned JavaScript SDK document in your question)? If you can provide the steps to reproduce this, that would be very helpful for us to locate the problem (which is likely not in the CLI code base).

**Comment by rainabba** [comment]
I was using the AWS SDK for JS (node.js) at https://github.com/aws/aws-sdk-js

The error isn't the issue per-se. Just try to make a call without "GroupName" and "GroupID" and you'll get it. 

The case in the error is the issue (albeit minor) and it's coming from the back-end so I didn't know a more appropriate place to create this issue.

I was having trouble with the API and that inconsistency case to my attention as it made matters worse.

**Comment by joguSD** [comment]
The ec2 service team would have to fix this.
