### ISSUE TITLE
No ability to change workspace creation options

### ISSUE THREAD

**Issue by elerch** [aws/aws-cli#1509]
aws workspaces describe-workspace-directories provides json output that includes an object "WorkspaceCreationProperties". For example:

            "WorkspaceCreationProperties": {
                "EnableInternetAccess": true,
                "EnableWorkDocs": true,
                "CustomSecurityGroupId": "sg-2d70fd49",
                "UserEnabledAsLocalAdministrator": true
            }

However, there does not appear to be a subcommand in the workspaces command nor the ds command that allows manipulation of these values. Without this feature it's impossible to fully script the creation of workspaces that allow internet access or otherwise deviate from the default workspace values.

**Comment by jamesls** [comment]
These commands are just mapped to the underlying API commands for Amazon WorkSpaces (http://docs.aws.amazon.com/workspaces/latest/devguide/API_Operations.html).

I would suggest reaching out on the [Amazon WorkSpaces forum](https://forums.aws.amazon.com/forum.jspa?forumID=164) to see if the workspaces team have any suggestions for you.  If it's not possible to do this with the service's API, then the AWS CLI won't be able to do this.
