### ISSUE TITLE
STANDARD_IA is an invalid storage class option

### ISSUE THREAD

**Issue by thejusme** [aws/aws-cli#1513]
The release notes on the main AWS site mention that CLI 1.8.5 was released to support the new STANDARD_IA storage class, but apparently support is not yet built into the CLI:

aws s3 cp --storage-class=STANDARD_IA file_to_be_copied s3://some-bucket/

Yields "Invalid choice: 'STANDARD_IA'" and suggests either STANDARD or REDUCED_REDUNDANCY. I also cannot find any instances of STANDARD_IA in the codebase here on GitHub. Was support for STANDARD_IA simply missed, and is it forthcoming in the next release? My guess is that it might simply be a matter of allowing it as a valid storage-class option since it's just an option sent with the request to the server.

**Comment by jamesls** [comment]
1.8.5 added this option to the low level `s3api` commands.  [1.8.6](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#186) added this option to the `s3` commands.
