### ISSUE TITLE
S3API put-object operations fails to find KMS key when bucket and key are in different regions

### ISSUE THREAD

**Issue by ischoonover** [aws/aws-cli#1517]
Hi

I'm trying to put a key to a bucket in us-west-1, but KMS keys are stored Global (US Standard). --region seems to be applying to the KMS ARN, and this results in the key not being found. I was unsuccessful in specifying the entire ARN to --ssekms-key-id to circumvent this. I'm using the latest version of aws-cli (1.8.6).

```
[ec2-user@ip-172-31-21-162 ~]$ aws s3api put-object --server-side-encryption aws:kms --ssekms-key-id <hex string snip> --storage-class STANDARD_IA --region us-west-1 --bucket bucketname --key subdir/keyname --body backups/keyname

A client error (KMS.NotFoundException) occurred when calling the PutObject operation: Key 'arn:aws:kms:us-west-1:accountnumber:key/hex-string-snip' does not exist

[ec2-user@ip-172-31-21-162 ~]$ aws kms describe-key --key-id hex-key-snip --region us-east-1
{
    "KeyMetadata": {
        "KeyId": "hex-key-snip", 
        "Description": "encryption key for ec2 instance backups to s3", 
        "Enabled": true, 
        "KeyUsage": "ENCRYPT_DECRYPT", 
        "CreationDate": 1442767507.222, 
        "Arn": "arn:aws:kms:us-east-1:accountnumber:key/hex-string-snip", 
        "AWSAccountId": "accountnumber"
    }
}

[ec2-user@ip-172-31-21-162 ~]$ aws s3api put-object --server-side-encryption aws:kms --ssekms-key-id arn:aws:kms:us-east-1:accountnumber:key/hex-key-snip --storage-class STANDARD_IA --region us-west-1 --bucket bucketname --key subdir/keyname --body backups/keyname

A client error (KMS.NotFoundException) occurred when calling the PutObject operation: Invalid arn
```

Should --ssekms-key-id be defaulting to craft us-east-1 into the ARN? I see no way to create a KMS key in another region than that.

**Comment by kyleknap** [comment]
So in the first example, the service is constructing the arn from the hex string snippet you are providing. The CLI is not doing any customizations there, and it looks like the service is constructing the arn based on what region you sent the request.

I tried out the other two scenarios as well. The only way it looks like you can get to this to work is if you use a KMS key that is located in us-west-1. You can create a KMS key in a specific region by specifying the region. So something like this:
```
$ aws kms create-key --region us-west-1
```
Then you can use that key when uploading and kms encrypting objects to a bucket located in us-west-1.

Let me know if you have any more questions.

**Comment by JordonPhillips** [comment]
This issue is being closed due to inactivity
