### ISSUE TITLE
Sudden issues with S3

### ISSUE THREAD

**Issue by nikolay** [aws/aws-cli#1519]
The command below used to work without issues eaerlier today. Suddenly, during the second half of the day, I keep getting this:
```bash
$ aws s3 cp path/test.template.json s3://bucket/path/test.json
upload failed: path/test.template.json to s3://bucket/path/test.json ('Connection aborted.', OSError(64, 'Host is down'))
```
Any idea?

**Comment by nikolay** [comment]
I issue fixed by itself without me doing anything.

**Comment by kyleknap** [comment]
Yeah I am not sure what would have caused this. If you hit this issue again, please include debug logs and reopen this issue.

**Comment by nikolay** [comment]
I will. Thanks!
