### ISSUE TITLE
ec2 run-instances ignores count in its json input

### ISSUE THREAD

**Issue by michipili** [aws/aws-cli#1524]
When preparing a reservation with `aws ec2 run-instances --cli-input-json JSONBLOB` the `MinCount` and `MaxCount` parameters are ignored and overwritten by the value 1. The equivalent reservation using command line options and esp. the `--count` option functions as expected.

How to reproduce:

```shell
jsonblob()
{
   cat <<'EOF'
{
  "DryRun": false,
  "ImageId": "ami-XXXXXXXX",
  "MinCount": 3,
  "MaxCount": 3,
  "SubnetId": "subnet-XXXXXXXX",
  "UserData": "IyEvYmluL3NoCnNodXRkb3duIC1QICsyCg==",
  "InstanceInitiatedShutdownBehavior": "terminate",
  "InstanceType": "t2.small"
}
EOF
}
aws --debug ec2 run-instances --cli-input-json "$(jsonblob)"
```
(The user data is a script terminating the instance after a few minutes.)

The output contains the line
```
2015-09-23 16:49:09,762 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0xXXXXXXXXXX> (verify_ssl=True) with params: {'body': {u'UserData': u'SXlFdlltbHVMM05vQ25Ob2RYUmtiM2R1SUMxUUlDc3lDZz09', u'DryRun': 'false', u'InstanceInitiatedShutdownBehavior': u'terminate', u'ImageId': u'ami-XXXXXXXX', u'SubnetId': u'subnet-XXXXXXXX', 'Version': u'2015-04-15', 'MaxCount': 1, 'Action': u'RunInstances', 'MinCount': 1, u'InstanceType': u't2.small'}, 'url': u'https://ec2.us-east-1.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.7.32 Python/2.7.10 Darwin/14.5.0'}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
```

This demonstrates that the parameters `MaxCount` and `MinCount` in the JSON input are ignored.

----

```console
% pip show awscli
---
Metadata-Version: 1.1
Name: awscli
Version: 1.7.32
Summary: Universal Command Line Environment for AWS.
Home-page: http://aws.amazon.com/cli/
Author: Mitch Garnaat
Author-email: garnaat@amazon.com
License: Apache License 2.0
Location: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: botocore, bcdoc, colorama, docutils, rsa
```

**Comment by michipili** [comment]
The bug is still in the latest version available throug PIP

```
%  pip show awscli        
---
Metadata-Version: 2.0
Name: awscli
Version: 1.8.6
Summary: Universal Command Line Environment for AWS.
Home-page: http://aws.amazon.com/cli/
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requires: colorama, botocore, rsa, docutils
```

**Comment by michipili** [comment]
And quite interestingly the `--count` option can be used together with the JSON blob to set these parameters, just append the `--count 3` option to the command line in the example above to demonstrate it.

**Comment by kyleknap** [comment]
Yeah that is unfortunate. The workaround that you mentioned is what I would have suggested. The reason why it happens is the ``--count`` parameter is a custom parameter that has a default of 1 if it is missing from the command line. However, with the ``--cli-input-json`` parameter we allow users to override values in there by specifying it on the command line. However, what is happening here is that even though the parameter is missing, a default value is provided and thus clobbers the value in the JSON skeleton provided. We will look to see how we can fix this.
