### ISSUE TITLE
API Gateway support on the roadmap?

### ISSUE THREAD

**Issue by doapp-ryanp** [aws/aws-cli#1525]
Would be really cool if it was.  Very handy to do things like [flush cache](http://docs.aws.amazon.com/apigateway/api-reference/link-relation/stage-flush-cache/)

**Comment by kyleknap** [comment]
API Gateway is something we want to support. We are looking to add commands for it.

**Comment by mijndert** [comment]
+1

**Comment by mijndert** [comment]
Is there an ETA for this?

**Comment by danielrmeyer** [comment]
+1

**Comment by pauldtong** [comment]
+1

**Comment by BetaGrumm** [comment]
Do want. +1

**Comment by quiver** [comment]
+1

**Comment by bradmurray** [comment]
+1

**Comment by JordonPhillips** [comment]
API Gateway is supported as of today's release (1.9.1)
