### ISSUE TITLE
Config file reveals credentials

### ISSUE THREAD

**Issue by cgsmith** [aws/aws-cli#1527]
The aws secret and access keys are stored in plain text in the config file.  This poses a security risk, albeit not an immediate threat.

I'd like to see if the file could be encrypted in a new version if possible.  Perhaps even an option to encrypt it?

**Comment by garnaat** [comment]
Have you seen https://github.com/sj26/awscli-keyring?

**Comment by cgsmith** [comment]
Thanks @garnaat 

Exactly what I was looking for.

**Comment by kyleknap** [comment]
Yep that is one library that adds support for it. We also have have an existing issue open for key ring support: https://github.com/aws/aws-cli/issues/547. We would prefer to track this feature there.
