### ISSUE TITLE
aws iam get-user-policy docs are out of sync

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cli#153]
The docs for this command as well as several other IAM commands that return a Policy document state that the policy document will be returned as URL-encoded.  However, we have added a handler to decode the policy document.  We also need to add a handler to update the documentation.

**Comment by JordonPhillips** [comment]
This is actually a botocore thing, which is being addressed in https://github.com/boto/botocore/pull/664
A more relevant issue is also in boto/botocore#664
