### ISSUE TITLE
Upgrading the awscli tool from 1.8.11 to 1.8.12 breaks the add-permission call

### ISSUE THREAD

**Issue by lewisd32** [aws/aws-cli#1552]
Running:
`aws lambda add-permission --function-name <arn> --region us-east-1 --statement-id Test --action "lambda:InvokeFunction" --principal s3.amazonaws.com --source-arn arn:aws:s3:::<bucketname> --source-account <accountId>`

With awscli 1.8.11 works, but with 1.8.12 it gives the following error:
`A client error (AccessDeniedException) occurred when calling the AddPermission operation: Unable to determine service/operation name to be authorized`

**Comment by lewisd32** [comment]
This may actually be due to botocore changes, so I've also reported this here: https://github.com/boto/botocore/issues/678

**Comment by rayluo** [comment]
Yes, let's close this one and keep track of this issue on that botocore issue.
