### ISSUE TITLE
zsh autocomplete script removes already defined completions

### ISSUE THREAD

**Issue by jwhitley** [aws/aws-cli#1557]
**Repro steps**

1.  Install aws-cli, e.g. via Homebrew
2.  Load it via `.zshrc`, e.g. using:

     ```
aws_cli_completion='/usr/local/share/zsh/site-functions/_aws'
[[ -r $aws_cli_completion ]] && source $aws_cli_completion
    ```
3.  Attempt to use a completion defined in `.zshrc` before the aws-cli completions are loaded.

**Actual results**

No completions loaded prior to the aws-cli completions work.  They were removed when the `_aws` script ran `compinit`.  Scripts that are intended to just establish a completion should not *ever* run `compinit`, for this very reason.  This is unexpected and rather bad behavior for a completion loader script.

**Expected results**

The zsh completions for `aws` are loaded, other completions remain as previously defined.

**Comment by jamesls** [comment]
Thanks for reporting, looks like our zsh completer needs some updates.

**Comment by mtdowling** [comment]
Fixed in https://github.com/aws/aws-cli/issues/1626
