### ISSUE TITLE
put-metric-data dimensions inconsistent with get-metric-statistics dimensions

### ISSUE THREAD

**Issue by JohnBloom** [aws/aws-cli#1559]
I have been having an issue that ate up most of my day and I think it is an issue with the cli but it could also just be a documentation issue. Since I have it working now, someone else will have to say if this is intended. 

I was playing around with `put-metric-data` using the cli. I was trying to get some sample data for a C# app we are writing. I was running the following command (new lines added for readability):

```
aws cloudwatch put-metric-data --metric-name SampleMetric 
--namespace DemoNamespace --timestamp 2015-10-14T07:55:00.000Z 
--dimensions Name=InstanceId,Value=i-123abc --profile productdev --value 2
```

Then I was trying to pull that metric data back out:

```
aws cloudwatch get-metric-statistics --metric-name SampleMetric 
--namespace DemoNamespace --start-time 2015-10-12T01:00:00.000Z 
--end-time 2015-10-15T14:00:00.000Z 
--period 1440 --statistics "Sum" --dimensions Name=InstanceId,Value=i-123abc
```

This is the recommended way as far as I can tell from [here](http://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-data.html) and [here](http://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html)

No matter what I did the `get-metric-statistics` call always returned:
```
{
    "Datapoints": [], 
    "Label": "SampleMetric"
}
```

But I was able to see the metric in the aws web console so I knew it was there. 

After some investigation I ended up calling `list-metrics --namespace DemoNamespace` and saw this:

```
"Metrics": [
        {
            "Namespace": "DemoNamespace", 
            "Dimensions": [
                {
                    "Name": "Name", 
                    "Value": "InstanceId"
                }, 
                {
                    "Name": "Value", 
                    "Value": "i-123abc"
                }
            ], 
            "MetricName": "SampleMetric"
        }
    ]

```

Notice that there are two dimensions! One for the name and one for the value. This gave me an ah-ha moment and I went back and reran my `put-metric-data` call like this:

```
aws cloudwatch put-metric-data --metric-name SampleMetric --namespace DemoNamespace 
--timestamp 2015-10-14T07:55:00.000Z --dimensions InstanceId=i-123abc --value 2 
```

Notice that I changed the dimensions call to `--dimensions InstanceId=i-123abc`. 

And low and behold I was able to see my new data point. I can also see the original data point if I format my dimension like this `--dimensions Name=Name,Value=InstanceId Name=Value,Value=i-123abc` but that doesnt seem intuitive.

My main issue is that this seems to go against what the documentation was telling me to do. Now that I know it is not hard to work around but it was very tricky to figure out in the first place. 

_All of the included code snippets can be run to repo this issue, they are not unique to my project._

**Comment by JordonPhillips** [comment]
@JohnBloom it looks like you got a little confused on the input format of `--dimensions`. You don't need to specify which part is the name and which is the value explicitly, it is implied by the equality operator. So it would look like `--dimensions InstanceId=i-123abc`. The [documentation](http://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-data.html#options) gives a similar example.

**Comment by JohnBloom** [comment]
Ah I see, I was looking at this part of the documentation:
```
MetricName=string,Dimensions=[{Name=string,Value=string},{Name=string,Value=string}],Timestamp=timestamp,Value=double,StatisticValues={SampleCount=double,Sum=double,Minimum=double,Maximum=double},Unit=string ...
```

Where is seems to indicate using the other format.

**Comment by JordonPhillips** [comment]
On second look, it looks like you were correct in that they are inconsistent. One page lists what I put down and one lists the way you initially tried. Curious. We'll look into the issue, thanks for bringing it to our attention!

**Comment by mtdowling** [comment]
The problem here is that we added a customization to move some of the nested parameters under `--metric-data` up to top-level argument for the put-metric-data command. Unfortunately, this argument treats --dimensions as a map, when it's actually a list of structs (which would match get-metric-statistics). While inconsistent, removing this behavior without a major version bump in the CLI would be a breaking change as users are relying on the current behavior.

An alternative, but much more verbose, way to use put-metric-data is using

```
aws cloudwatch put-metric-data --namespace DemoNamespace --metric-data 'MetricName=SampleMetric,Timestamp=2015-11-20T07:55:00.000Z,Value=2,Dimensions=[{Name=InstanceId,Value=i-123abc}]'
```

We'll add this to our "change this if we ever do a CLI v2" list.
