### ISSUE TITLE
Add --metadata to s3 sync / cp

### ISSUE THREAD

**Issue by chainlink** [aws/aws-cli#1561]
I'd like to be able to set custom metadata on all objects involved in a sync or copy.

**Comment by mtdowling** [comment]
Thanks for the feature request

**Comment by davidpatters0n** [comment]
+1

**Comment by kyleknap** [comment]
Related issue: https://github.com/aws/aws-cli/issues/1218. Wants the feature for ``cp`` and ``mv``. If we were to implement this feature, it would be added to all transfer related command (i.e. ``cp``, ``mv``, ``sync``).

**Comment by tim-kos** [comment]
+1

**Comment by JordonPhillips** [comment]
Whoops! Look like we added this but forgot to close out the issue.

**Comment by chainlink** [comment]
Nice!
