### ISSUE TITLE
Pattern for attaching Policy inconsistent across services

### ISSUE THREAD

**Issue by nand0p** [aws/aws-cli#1563]
for example, SQS and SNS policy attachment pattern inconsistencies:
```
aws sns set-topic-attributes --topic-arn arn:aws:sns:{{ region }}:{{ aws_account }}:{{ sns_name }} --attribute-name Policy --attribute-value {{ sns_policy }}
```
```
aws sqs set-queue-attributes  --queue-url {{ queue_url }} --attributes '{"Policy":"{{ sqs_policy }}"}'
```

**Comment by mtdowling** [comment]
These APIs are actually significantly different: one allows you to set multiple attributes (sqs) while the other allows you to set a single attribute (sns). This is simply how these services chose to expose their APIs. I don't see much that the CLI could do to work around this.
