### ISSUE TITLE
Feature Request: "system" alias to use the system cert bundle

### ISSUE THREAD

**Issue by lorengordon** [aws/aws-cli#1569]
Please consider adding a "system" alias for the `ca_bundle` configuration option. The intent would be to detect and use the system ca cert bundle (rather than relying on the bundle distributed with requests or requiring that the user specify the path to the bundle with the the `ca_bundle` setting). Here is a diff with my initial (naive) implementation:

``` diff
diff --git a/awscli/customizations/globalargs.py b/awscli/customizations/globalargs.py
index e582cea..44cad51 100644
--- a/awscli/customizations/globalargs.py
+++ b/awscli/customizations/globalargs.py
@@ -16,7 +16,7 @@ import os
 from botocore.handlers import disable_signing
 import jmespath

-from awscli.compat import urlparse
+from awscli.compat import urlparse, six


 def register_parse_global_args(cli):
@@ -58,6 +58,7 @@ def _resolve_endpoint_url(value):


 def resolve_verify_ssl(parsed_args, session, **kwargs):
+    SYSTEM_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
     arg_name = 'verify_ssl'
     arg_value = getattr(parsed_args, arg_name, None)
     if arg_value is not None:
@@ -67,6 +68,9 @@ def resolve_verify_ssl(parsed_args, session, **kwargs):
         else:
             verify = getattr(parsed_args, 'ca_bundle', None) or \
                         session.get_config_variable('ca_bundle')
+            if isinstance(verify, six.string_types):
+                if u'system' == verify.lower():
+                    verify = SYSTEM_CA_BUNDLE
         setattr(parsed_args, arg_name, verify)


diff --git a/awscli/data/cli.json b/awscli/data/cli.json
index 5837d0d..66a36fe 100644
--- a/awscli/data/cli.json
+++ b/awscli/data/cli.json
@@ -53,7 +53,7 @@
         },
         "ca-bundle": {
                 "dest": "ca_bundle",
-                "help": "<p>The CA certificate bundle to use when verifying SSL certificates. Overrides config/env settings.</p>"
+                "help": "<p>The CA certificate bundle to use when verifying SSL certificates. Keyword 'System' is an alias for '/etc/pki/tls/certs/ca-bundle.crt'. Overrides config/env settings.</p>"
         }
     }
 }
```

**Comment by lorengordon** [comment]
For more context, see the discussion in PR https://github.com/aws/aws-cli/pull/1379.

**Comment by mtdowling** [comment]
Thanks for the feature request. We'll take a look and see if and how this can best be supported.

**Comment by jamesls** [comment]
FWIW, playing around with [`ssl.get_default_verify_paths()`](https://docs.python.org/2/library/ssl.html#ssl.get_default_verify_paths) seems to do what we want.  Haven't looked at how this is actually implemented, but might be worth exploring.

**Comment by lorengordon** [comment]
Nice. I want to say I started down that path...but it was long enough ago that I honestly don't remember what rabbit holes I explored. Does that work on Windows, as well? I think trying to figure out Windows support is where I broke down and copped out...

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (155/150 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:47212 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0P3-001aWE-Cj
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:06 -0700
Date: Tue, 06 Feb 2018 02:22:40 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912560;
	bh=EOdrUpVAWB+Sgude5KLErpTihCpSA2AGNkKRwaIELH0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JpkzKelT+2i/G26eDnhL64UgWZ5UHrn3sdbQy5KQkHStqT9ZAOiljrd3AketGejAr
	 h5V08fHM6gL8OV+ggXRDtTdOBdoselEw8IXw++GpojasJWobWBErLVKyzHRF/hpRFq
	 WI3G0ybNlSPQ30JUbv+0YXuB522ublA2G52cNXOI=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (154/150 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:47046 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0P2-001aWA-4n
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:23:05 -0700
Date: Tue, 06 Feb 2018 02:22:40 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912560;
	bh=9rCURBn36JZQQ/n6SqL+p8+oDTcfCQLvCPxpatcnl3Q=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rgJVy0M5IUCc9GxjD83FHprkLjfRPsYOB5+aij28Ofz6LtcLlQ9+Lv3+vX5/lDmf1
	 HHxq02NCV/96FBxN2DJT4Og6R8q5JVYtBhIoasY9LBLExakQM1jHAXPKb1Ta9qsod5
	 QZrPxapErHfWVlfN0eI3RlqLawtjx8/hmkXNzos8=

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.
