### ISSUE TITLE
AWS CLI 1.8.6 Alarmingly High CPU Utilization

### ISSUE THREAD

**Issue by anthony-battaglia** [aws/aws-cli#1573]
I'm using the AWS CLI to recursively copy files from an S3 bucket to an EC2 c3.xlarge instance, all within us-east-1 region.  There are 16 files, each approximately 180 MB in size.  I'm trying to copy them to root EBS partition.  The command appears as: aws s3 cp --recursive s3://path.to.bucket/folderX/ /home/ubuntu

While this command is running, monitoring via top shows %CPU of the AWS process anywhere from 180%-210%.  While this is running, the server becomes completely unresponsive and unreachable from the increased load.

Some machine data:

`$ aws --version`
aws-cli/1.8.6 Python/2.7.6 Linux/3.13.0-40-generic

`$ uname -a`
Linux ip-xx-x-x-xx 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

`$ lsb_release -a | grep Description`
Description:	Ubuntu 14.04.2 LTS

**Comment by mtdowling** [comment]
We'll take a look and see if we can reproduce the issue. In the meantime, it would be worth a shot to see if using `nice` helps to lower the CPU utilization. Have you tried running the the command with `--debug` to see if there's anything strange going on like excessive retries?

**Comment by anthony-battaglia** [comment]
Thanks for your response @mtdowling.  Regarding the previous issue logged about the aws-cli, the instance I was using was also experiencing additional issues outside of aws-cli abnormalities (inconsistent NIC availability, inconsistent EBS throughput).  The issues were problematic enough where I ended up stopping and starting the EC2 instance.  Once the instance came back up, I'm no longer seeing this issue.  It's possible faulty hardware was a contributing factor here.

**Comment by mtdowling** [comment]
Ah interesting. Thanks for letting us know. I suppose this issue is no longer necessary. Please follow up with us if you have any more problems.
