### ISSUE TITLE
--recursive is now "Unknown option" in aws cli under Ubuntu 14.04

### ISSUE THREAD

**Issue by vigliensoni** [aws/aws-cli#1580]
I just installed awscli using apt-get in an Ubuntu 14.04 AMI image. When I ask for listing recursively my bucket:
```
aws s3 ls --recursive s3://my-bucket
```
Now I get
```
Unknown options: --recursive
```
Any clues?

**Comment by mtdowling** [comment]
I think you may have picked up an older version of the CLI. Can you provide the output of `--version`?

**Comment by vigliensoni** [comment]
I got the one that apt-get gave me after doing the apt-get update. It should be the last one.

Anyway, the version is:
```
aws-cli/1.6.2 Python/2.7.6 Linux/3.13.0-48-generic
```

**Comment by mtdowling** [comment]
That version of the CLI is about a year out of date (distros aren't always up to date), but I should also note that the `--recursive` option was added to the `aws s3 ls` command in version [1.2.11](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1211).

When I launched an Ubuntu AMI running `ubuntu-trusty-14.04-amd64-server-20150325 (ami-d05e75b8)`, I ran the following commands:

```
apt-get update
apt-get install awscli
aws --version
> aws-cli/1.2.9 Python/3.4.0 Linux/3.13.0-48-generic
```

I think you'll need to update your version of the CLI to pull in the `--recursive` argument. I suggest installing the CLI using one of the methods listed in the documentation: http://docs.aws.amazon.com/cli/latest/userguide/installing.html

**Comment by mtdowling** [comment]
I think this issue is resolved and the solution is to update the CLI. I'll go ahead and close this, but let me know if this is still an issue and we'll reopen.

**Comment by IvRRimum** [comment]
I followed the http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os it installed even older version, that i got from the apt-get install..

also --recursive doesn't work.

**Comment by b44p** [comment]
Yes same here. Please advise
`Unknown options: --recursive`
`aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-40-generic`
