### ISSUE TITLE
aws s3 dowload small files

### ISSUE THREAD

**Issue by dduleep** [aws/aws-cli#1591]
This is not issues in aws cli but i can't find solution. Please kindly suggest

1. Is there way to download small files as zip
exm:
aws zip s3://bucket/files1/* s3://bucket/image/image1.png --download C:\backup 

2. if i versioning is enable for bucket how to download all versions of single file/folder?

**Comment by JordonPhillips** [comment]
As far as I am aware, there is no way to download a file / group of files from S3 as a zip unless you put them there zipped in the first place. If you want it zipped, you'll have to do that locally. It looks like you're doing a local backup, for which you might use `aws s3 sync` which has the advantage of only downloading changed files.

There is also no command to download all versions of a file. You would need to either chain the [`list-object-versions`](http://docs.aws.amazon.com/cli/latest/reference/s3api/list-object-versions.html) command with the [`get-object`](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-object.html) command with a shell script or use one of the SDKs / the API to do the same thing with code. Here's what it might look like in `boto3`:

```python
import boto3

bucket = 'bucket-name'
key = 'object-key'
s3 = boto3.resource('s3')
versions = s3.Bucket(bucket).object_versions.filter(Prefix=key)

for version in versions:
    objekt = version.get()
    # save files somewhere
```

**Comment by dduleep** [comment]
I try with above code for download all version of the files but i can't find download files

```
{'LastModified': datetime.datetime(2015, 11, 3, 14, 35, 9, tzinfo=tzutc()), 'ResponseMetadata': {'HostId': 'XO3mrqbox3+M6ZpWCrj51+S+kUoigiwVVeMuS/mkps8NAeNe38I1OroLU3R2uqwlFcZdNTJn1iU=', 'RequestId': 'C2CCB2DE0F12776E', 'HTTPStatusCode': 200}, 'ETag': '"52f5d2ce9cd024e6aec9b1ad0b1b33ed"', 'ContentLength': 10, 'VersionId': 'v5EcT3F2mAR4E_XkEhH1f0Ikjpe5jQTb', 'AcceptRanges': 'bytes', 'Body': <botocore.response.StreamingBody object at 0x02F91870>, 'ContentType': 'text/plain', 'Metadata': {}}
{'LastModified': datetime.datetime(2015, 11, 3, 7, 16, 12, tzinfo=tzutc()), 'ResponseMetadata': {'HostId': 'hy3drf9Ap5/0BR8j0IimejbaXo6ymAn/S4yBxhWhV9VC12+Nh44IufLpTuIv0TRjUd97usqamm8=', 'RequestId': '759D1E9A7F7C8FBA', 'HTTPStatusCode': 200}, 'ETag': '"ef86dfc8a37b0348ea2431ab55e1428c"', 'ContentLength': 213, 'VersionId': 'BWyEZxm7j3H1YvdIEpcP4RJbgdfjUG7Y', 'AcceptRanges': 'bytes', 'Body': <botocore.response.StreamingBody object at 0x02FB5E30>, 'ContentType': 'text/plain', 'Metadata': {}}

```

**Comment by JordonPhillips** [comment]
You would need to then save the result as a file, which I didn't include in that code. There are several python ways to do that, but we provide a convenience method:

```python
version.download_file('local-filename')
```

**Comment by dduleep** [comment]
Thanks for your feed back
using bellow code i can download all the version of given  file

```
client = boto3.client('s3')
transfesr = S3Transfer(client)

def downloadFilesAllVersion(bucket, key):
    versions = s3.Bucket(bucket).object_versions.filter(Prefix=key)
    
    dir_path = os.path.dirname(key)
    file_name = os.path.basename(key)
    
    # if directory not exit create
    os.makedirs(dir_path, exist_ok=True)
    
    for version in versions:
        obj = version.get()
        print(obj)
        
        transfesr.download_file(bucket, key, obj['LastModified'].strftime("%Y%m%d%H%M%S")+ "_" + file_name,
                                 extra_args={'VersionId': obj['VersionId'] })
```

The advantage of the above code is download file as datetime_filename so that is every easy for user to find files

I can't create directory structure relative to current directory use in transfesr.download_file method(ex s3://mybucket/directory1/file.txt should be save as currentdirectory/directory1/file.txt) if you have any suggestion really appropriate

**Comment by JordonPhillips** [comment]
To get the current working directory in python, you can use [`os.getcwd()`](https://docs.python.org/2/library/os.html#os.getcwd) which you would then append with the key. 

Other notes:
* you can call `obj.file_download(filename)` so you don't need to use `transfer` directly.
* `makedirs` will throw an error if the directory exists, so you may want to catch it
