### ISSUE TITLE
Better handle documentation of ContentMD5 for S3

### ISSUE THREAD

**Issue by kyleknap** [aws/aws-cli#1607]
We have customizations in botocore/boto3 to hide the ContentMD5 parameters. We should hide or document them as auto-populated in the CLI as well because it has created some confusion. Was brought up in this [comment](https://github.com/aws/aws-cli/issues/860#issuecomment-152279496).

**Comment by justnance** [comment]
Adding other Content MD5 related GitHub issues and submitting an internal ticket to the documentation team.

**Comment by tim-finnigan** [comment]
This documentation page has since been added to expand on the usage of the Content-MD5 header in the AWS CLI: https://docs.aws.amazon.com/cli/latest/topic/s3-faq.html#q-does-the-aws-cli-validate-checksums
