### ISSUE TITLE
aws apigateway put-integration: Always returns u'http_method'

### ISSUE THREAD

**Issue by ehammond** [aws/aws-cli#1609]
I'm trying to figure out what parameters to pass to `apigateway put-integration` and am getting back the same `u'http_method'` response no matter what I pass in. For example:

    $ aws apigateway put-integration --region us-east-1 --rest-api-id BOGUS --resource-id BOGUS --http-method BOGUS --type BOGUS 
    
    u'http_method'
    $ echo $?
    255

The same thing happens when I put in what I think are reasonable values.

**Comment by ehammond** [comment]
It never fails: I just pulled the latest version and get much different (and better) results with aws-cli 1.9.2.

**Comment by JordonPhillips** [comment]
That was related to a bug we had to fix, glad everything's working out now though!
