### ISSUE TITLE
Elasticsearch Service `--advanced-options` Parsing Broken

### ISSUE THREAD

**Issue by bsandrow** [aws/aws-cli#1615]
Per the documentation, I should be able to run this:

```console
$ aws es update-elasticsearch-domain-config --domain-name mylogs --region us-east-1 --advanced-options indices.fielddata.cache.size=35
```
What I get is this:

```console
$ aws es update-elasticsearch-domain-config --domain-name mylogs --region us-east-1 --advanced-options indices.fielddata.cache.size=35
Error parsing parameter '--advanced-options': Expected: '=', received: '.' for input:
indices.fielddata.cache.size=35
```

Right now, setting Advanced Options via the CLI only works if you use the `--cli-input-json` option (e.g.):

```console
$ aws es update-elasticsearch-domain-config --domain-name mylogs --region us-east-1 --cli-input-json '{"AdvancedOptions": {"indices.fielddata.cache.size": "35"}}'
```

Also, the documentation says that I should be pass `--advanced-options` like so:

```
--advanced-options indices.fielddata.cache.size=35 rest.action.multi.allow_explicit=false
```

But adding the second option (separated by a space) results in this error:

```
Unknown options: rest.action.multi.allow_explicit=false
```

(Running Version: `aws-cli/1.8.12 Python/2.7.10 Darwin/15.0.0`)

**Comment by kyleknap** [comment]
Yeah looks like a bug in our shorthand syntax parsing. We recently redid it and at one point we considered making ``.`` meaningful way for expressing nested structures and members, but in the end, we decided against it.

**Comment by tc-turner** [comment]
I was having this issue and was able to resolve it by removing leading spaces from `network.host: ` and `cluster.name:`
