### ISSUE TITLE
Shorthand parsing error for cloudformation

### ISSUE THREAD

**Issue by kyleknap** [aws/aws-cli#1629]
Brought up by this [comment on Boto3](https://github.com/aws/aws-cli/issues/1529#issuecomment-154238704). So for the ``--parameters`` parameter of ``create-stack``, we need to interpret the ``ParameterValue`` as a string but it gets parsed as a list causing a botocore validation error:
```
--parameters ParameterKey=SecurityGroups,ParameterValue=sg-11111111,sg-22222222
```
```
Invalid type for parameter Parameters[1].ParameterValue, value: [u'sg-11111111', u'sg-22222222'], type: <type 'list'>, valid types: <type 'basestring'>
```
The only workaround would be to use JSON instead of shorthand or paramfiles.

**Comment by gene1wood** [comment]
A workaround to this is described [in this comment](https://github.com/aws/aws-cli/issues/1529#issuecomment-154403007)
