### ISSUE TITLE
Cannot get information of Distributions (Behaviors, Error Pages, Restrictions, Invalidations)

### ISSUE THREAD

**Issue by rolandovillca** [aws/aws-cli#1633]
It is not possible, to get cloudfront information of following distributions using aws-cli tool:
CloudFront Behaviors:
      \* Precedence
      \* Path Pattern
      \* Origin
      \* Viewer Protocol Policy
      \* Forwarded Query Strings
CloudFront Error Pages:
      \* HTTP Error Code
      \* Error Catching Minimum TTL
      \* Response Page Path
      \* HTTP Response Code
CloudFront Restrictions:
      \* Restriction
      \* Status
      \* Type
CloudFront Invalidations:
      \* Invalidation ID -> Get successfully
      \* Status -> Get successfully
      \* Date

note: I have tried using aws-cli tool without success, Do you know another way or how to get above information via aws-cli tool?

**Comment by JordonPhillips** [comment]
Could you give us an example of one or more of the commands you're trying to run?

**Comment by rolandovillca** [comment]
I have ran following commands, and it is returned in json format (coz i configured that):

$ aws cloudfront get-distribution --id MYID
$ aws cloudfront get-distribution-config --id MYID

I reviewed JSON result and some information are missed:
For example for "CloudFront Restriction", I cannot see information for Restriction, Status and Type fields.
For example for "CloudFront Error Pages", I cannot see information for HTTP Error code,Error Caching Minimum TTL, Response Page Path and HTTP Response Code fields.

**Comment by kdaily** [comment]
Hi @rolandovillca,

Is this still an issue for you? Thanks!
