### ISSUE TITLE
Access to AWS CLI from a Lambda function

### ISSUE THREAD

**Issue by JAForbes** [aws/aws-cli#1636]
I know this isn't really within the control of this project.  

It would be fantastic to be able to use `aws s3 cp` instead of the NodeJS SDK.  One of the provided examples for a Node JS lambda is executing terminal commands, yet you can't execute the cli itself.

**Comment by rayluo** [comment]
I like the idea. AFAIK, lambda already bundles Boto 3, but perhaps not (yet?) AWS CLI. Anyway, I would suggest you reach out to the [Lambda Forum](https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0) for this. Closing this issue here.
