### ISSUE TITLE
RDS: sharing snapshot not available in CLI?

### ISSUE THREAD

**Issue by pbudzon** [aws/aws-cli#1637]
Hello,

According to this post: https://aws.amazon.com/blogs/aws/amazon-rds-update-cross-account-snapshot-sharing/ sharing of the RDS snapshot is available in the CLI tool:

> Here’s how a snapshot appears in the accounts that it is shared with (again, this functionality is also accessible from the command line and the RDS API)

But I cannot see this option documented anywhere, not online not on the man page. Is this option actually available in the CLI or will it be available soon?

**Comment by rayluo** [comment]
Duplicated to boto/botocore#716

**Comment by rayluo** [comment]
It is now released in latest AWS CLI 1.9.7 (which contains botocore 1.3.7).
