### ISSUE TITLE
Allow s3n and s3a URLs to make life easier to Hadoop users

### ISSUE THREAD

**Issue by navado** [aws/aws-cli#1641]
For Hadoop users, (for example verifying results) it may be more convenient to allow re-use of s3 URLs as used in Hadoop. 
Hadoop (and derivatives) allows s3, s3n and s3a schemes in S3 URLs.

**Comment by jamesls** [comment]
Could you share your use case here?  I see the different types of S3 URLs documented [here](http://wiki.apache.org/hadoop/AmazonS3), but I'm not quite following what we'd do in the CLI to support this.  Could you clarify?

**Comment by navado** [comment]
Yes

**Comment by jamesls** [comment]
I think this would be confusing to CLI users, especially to S3 users of the CLI that don't also use hadoop.  I don't think is something we'd be be able to support.

**Comment by navado** [comment]
Don't think so..
If user unaware about this the feature will be transparent and just work for that part of users, who has such URLs
