### ISSUE TITLE
RPM's built from awscli with setup.py lack dependencies

### ISSUE THREAD

**Issue by nkadel** [aws/aws-cli#1643]
I do a great deal of RPM rebundling of open source tools,  especially to lock down dependencies and versions for consistency across an environment. Doing this with "pip" can be problematic, and RPMs are most useful to me in my RHEL or CentOS or Amazon Linux or Fedora  work. I can build RPM's using the Pythons setuptools, with "python setup.py bdist_rpm", but the resulting packages don't include critical dependencies.

I've published a .spec file at https://github.com/nkadel/nkadel-aws-cli/blob/develop/python-awscli.spec, and would be happy to toss in a merge requiest so that "rpmbuild -ta" could be used to build RPM's from the published tarbals. It takes a bit more work for RHEL 5, which requires the optional "python26" and a locally built "pythons25-setuptools" to compile the RPM. but I'd be happy to work with anyone with a good, secuire, public yum repository to help make those available..

**Comment by nkadel** [comment]
I've updated the spec file to handle RHEL 5, and to compile "python-awscli" on RHEL 6 or greater, and "python26-awscli" on RHEL 5. I don't know if there's a graceful way to help Amazon compile and publish these directly, but it would help stabilize versions for RPM based operating system users.

**Comment by nkadel** [comment]
It's reasonable for downstream to include, especially with the reasonable Apache licensing you've published. I've had some difficulty getting through the intricate procedures to get new RPM's into Fedora and EPEL, and RHEL especially tends to insist on consistency of interface over leading edge releases. I've especially had problems getting "koji" to work the way Fedora and EPEL want right now, so I couldn't promise any success, and having a template .spec file could be really useful to distos I don't work with, such as SuSE.

**Comment by jamesls** [comment]
I think having these RPMs live upstream makes the most sense right now.  Maintaining these spec files is something that would be best handled by the package maintainers for the various distros.  We can help out these upstream maintainers in whatever way they might need.
