### ISSUE TITLE
Problems with s3 sync with --ssekms-key-id

### ISSUE THREAD

**Issue by ArneWeise** [aws/aws-cli#1660]
Using the new --ssekms-key-id parameter throws the following error

> A client error (InvalidArgument) occurred when calling the CreateMultipartUpload operation:
> Server Side Encryption with AWS KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms

Same error while syncing both from local disk to s3 as well as between s3-buckets. 
Destination bucket is eu-central-1and specified with --region eu-central-1 

Am I missing something or is it a bug?

**Comment by mtdowling** [comment]
You'll need to specify the type of server side encryption using `--sse=aws:kms`.

> --sse (string) Specifies server-side encryption of the  object  in  S3.
>       Valid  values are AES256 and aws:kms. If the parameter is specified but
>       no value is provided, AES256 is used.

**Comment by JSkeets** [comment]
It should be noted that the flag has been updated and is now
``` 
--server-side-encryption (string)

The Server-side encryption algorithm used when storing this object in S3 (e.g., AES256, aws:kms).

Possible values:

AES256
aws:kms

**Comment by morufevari** [comment]
@JSkeets As of today, it is still `--sse=aws:kms` on https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by bisdavid** [comment]
@morufevari - I just saw this.  I'll get the correction submitted this afternoon.  Thanks for reporting this.
