### ISSUE TITLE
aws s3 cp broken in 1.9.11

### ISSUE THREAD

**Issue by CamJN** [aws/aws-cli#1670]
`aws s3 cp s3://aws-logs-777423221348-us-east-1/elasticmapreduce/j-2WTZ7AWUMJ0K2/node/i-a7fdd917/bootstrap-actions/2/controller.gz /tmp/`

'Session' object has no attribute 'get_default_client_config'

**Comment by CamJN** [comment]
Probably has to do with the changes to awscli/clidriver.py https://github.com/aws/aws-cli/commit/33a68f9d4c0581339cfd20e75a66166a205a016f#diff-63f67c748224f51280a660105cbea98d

**Comment by kyleknap** [comment]
What installation method are you using to the install the CLI? I have a feeling that the botocore version you are using is out of sync with the version of the CLI. You can tell by using ``--version``.
```
$ aws --version
aws-cli/1.9.11 Python/2.7.5 Darwin/13.4.0 botocore/1.3.11
```
If you are not using 1.3.11 of botocore, you will get the error that you pointed out. Let me know.

**Comment by CamJN** [comment]
Yeah it's aws-cli/1.9.11 Python/2.7.10 Darwin/15.0.0 botocore/1.3.6, I installed via homebrew.

**Comment by kyleknap** [comment]
Ah. I would recommend not installing with brew as we do not maintain nor officially support brew as an installation method. You may need to contact whoever maintains the brew package of the CLI to get this fixed if you are set on using brew. I would recommend using ``pip`` to install the CLI or through the bundled installer as those are both something that we maintain and officially support as installation methods.

I also noticed that you are using El Capitan. Some people have ran into issues when installing with pip and no virtualenv, but it looks like users have figured out how to get it to work: https://github.com/aws/aws-cli/issues/1522.

Let me know if you have any more questions or need any more help

**Comment by CamJN** [comment]
Yeah I'm not normally a python developer so when I ran into this problem I didn't think to look in the system python site-packages dir. Turns out that there was a bunch of outdated stuff in there that was screwing with this tool.

**Comment by kyleknap** [comment]
Cool. Glad to here you got it working then. Closing issue.
