### ISSUE TITLE
Support new NAT Gateway

### ISSUE THREAD

**Issue by conorgil** [aws/aws-cli#1683]
Just announced [NAT Gateway](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html).

Any idea when support will be included in the AWS CLI? Thanks!

**Comment by rayluo** [comment]
Thanks for your interest. We will support this in a new release. Stay tuned. ;-)

**Comment by rayluo** [comment]
It is released now http://aws.amazon.com/releasenotes/CLI/3232693073660098

Enjoy!

**Comment by conorgil** [comment]
Excellent! Thanks!

**Comment by JamesMGreene** [comment]
A big thank you for the quick turnaround on this long-needed new feature! :+1:
