### ISSUE TITLE
ec2 describe-instances returns error parsing parameter when using the --filter option

### ISSUE THREAD

**Issue by VladVladVladVlad** [aws/aws-cli#1690]
I am trying an example from this whitepaper:
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-DescribeInstances.html

The command is:
`ec2 describe-instances --filter tag:Purpose=Test`

I receive:
 
`Error parsing parameter '--filters': Expected: '=', received: ':' for input:
tag:Purpose=Test
   ^`

The version of CLI is 1.9.15, i suppose.

Thanks,
Vlad

**Comment by jamesls** [comment]
That link is to the EC2 command line interface, which is a different product than the AWS CLI.  Here's our examples from our reference docs that show how to do this in the AWS CLI: http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#examples


**To describe all instances with a Purpose=test tag**

Command:
```
aws ec2 describe-instances --filters "Name=tag:Purpose,Values=test"
```

Let us know if you have any more questions.
