### ISSUE TITLE
AWS CLI list-group-policies does not show groups, but web console does 

### ISSUE THREAD

**Issue by mslinn** [aws/aws-cli#1694]
The following does not show the expected policies for group devops:

````
$ aws iam create-group --group-name devops
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::aws:policy/CloudFrontFullAccess
$ aws iam list-group-policies --group-name devops
{
    "PolicyNames": []
}
````

However, if I use the web console at this point I can see that group devops has all the expected policies associated with it

**Comment by jamesls** [comment]
The `list-group-policies` is used for inline policies.  When you attach a managed policy via `attach-group-policy` you need to use the `list-attached-group-policies` command:

```
$ aws iam list-attached-group-policies --group-name devops
```

For more info:


http://docs.aws.amazon.com/cli/latest/reference/iam/list-group-policies.html
http://docs.aws.amazon.com/cli/latest/reference/iam/list-attached-group-policies.html

**Comment by mslinn** [comment]
Thank you! Output is as expected:

````
{
    "AttachedPolicies": [
        {
            "PolicyName": "AmazonEC2FullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
        },
        {
            "PolicyName": "AmazonS3FullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        },
        {
            "PolicyName": "AmazonRoute53DomainsFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonRoute53DomainsFullAccess"
        },
        {
            "PolicyName": "CloudFrontFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/CloudFrontFullAccess"
        },
        {
            "PolicyName": "AmazonRoute53FullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonRoute53FullAccess"
        }
    ],
    "IsTruncated": false
}
````

Perhaps the docs might be updated to incorporate this information.

**Comment by mslinn** [comment]
I cannot list a managed policy, however:

````
$ read -r -d '' POLICY_JSON <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1451158079000",
            "Effect": "Allow",
            "Action": [
                "ec2:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1451158106000",
            "Effect": "Allow",
            "Action": [
                "route53:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1451158123000",
            "Effect": "Allow",
            "Action": [
                "route53domains:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1451158159000",
            "Effect": "Allow",
            "Action": [
                "cloudfront:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Stmt1451158173000",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
EOF
$ aws iam create-policy --policy-name devops-policy \
--description "Complete access to S3, CloudFront, Route 53 and Route 53 Domains" \
--policy-document "$POLICY_JSON"
{
    "Policy": {
        "PolicyName": "devops-policy",
        "CreateDate": "2015-12-28T19:06:26.644Z",
        "AttachmentCount": 0,
        "IsAttachable": true,
        "PolicyId": "ANPAIZQTDBIPSKQHIVWCE",
        "DefaultVersionId": "v1",
        "Path": "/",
        "Arn": "arn:aws:iam::031372724784:policy/devops-policy",
        "UpdateDate": "2015-12-28T19:06:26.644Z"
    }
}
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::031372724784:policy/devops-policy
$ aws iam list-group-policies --group-name devops
{
    "PolicyNames": []
}
````

What am I doing wrong?

**Comment by quiver** [comment]
@mslinn 
> I cannot list a user managed policy, however:
> What am I doing wrong?

`list-group-policies` lists inline policies that are attached via `put-group-policy` API calls.

You attached managed policies via an `attach-group-policy` API call, that are listed via `list-attached-group-policies` API.

* http://docs.aws.amazon.com/cli/latest/reference/iam/put-group-policy.html
* http://docs.aws.amazon.com/cli/latest/reference/iam/attach-group-policy.html
* http://docs.aws.amazon.com/cli/latest/reference/iam/list-attached-group-policies.html
* http://docs.aws.amazon.com/cli/latest/reference/iam/list-group-policies.html

**Comment by mslinn** [comment]
Sorry, your last comment does not connect with me. After this command runs:

$ aws iam attach-group-policy --group-name devops --policy-arn 
arn:aws:iam::031372724784:policy/devops-policy

The web console shows that I have associated the user managed policy 
"devops-policy" with group devops.



However neither the |list-group-policies| nor the 
|list-attached-group-policies| commands shows me the association. What 
AWS CLI command will show the association depicted in the image?

Thanks,

Mike

**Comment by quiver** [comment]
@mslinn 
Are you sure you're running the commands correctly? Is the specified group name correct? 

I can confirm that ` list-attached-group-policies` lists both AWS managed and customer managed policies as displayed in the management console.

```
$ aws iam create-policy --policy-name devops-policy \
--description "Complete access to S3, CloudFront, Route 53 and Route 53 Domains" \
--policy-document "$POLICY_JSON"
{
    "Policy": {
        "PolicyName": "devops-policy",
        "CreateDate": "2015-12-29T05:47:24.236Z",
        "AttachmentCount": 0,
        "IsAttachable": true,
        "PolicyId": "ANPAIMB6E5KTSXFEBNF56",
        "DefaultVersionId": "v1",
        "Path": "/",
        "Arn": "arn:aws:iam::123456789012:policy/devops-policy",
        "UpdateDate": "2015-12-29T05:47:24.236Z"
    }
}

# attach customer managed policy
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::123456789012:policy/devops-policy

# attach aws managed policy
$ aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess

# list managed policies
$ aws iam list-attached-group-policies --group-name devops
{
    "AttachedPolicies": [
        {
            "PolicyName": "AmazonS3FullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        },
        {
            "PolicyName": "devops-policy",
            "PolicyArn": "arn:aws:iam::123456789012:policy/devops-policy"
        }
    ]
}
```

**Comment by mslinn** [comment]
I believe the image that I provided shows that the group name is correct.
I also provided the commands and the results.
Perhaps there is a bug?

Mike

**Comment by quiver** [comment]
@mslinn 
> I believe the image that I provided shows that the group name is correct.
I don't get the image you're referring to. Is it attached to github?

Anyway, you're reporting two problems:

Problem 1. `list-attached-group-policies` only lists aws managed policies and does not list customer managed policys 

To confirm that,  please attach both AWS and customer attached policies and run `list-attached-group-policies` as I did at the comment https://github.com/aws/aws-cli/issues/1694#issuecomment-167723668
This should isolate the problem.

You've only attached only AWS managed or customer managed policies. 

Problem 2.  What you see from web console and what you get from API calls are different.

One possibility is that

* AWS account you're logged in at the management console
* AWS account you're calling API

is different.

**Comment by mslinn** [comment]
I only have one AWS account.

This script worked:

POLICY_NAME=test-policy
GROUP_NAME=test-group
aws iam create-group --group-name $GROUP_NAME
read -r -d '' POLICY_JSON <<EOF
{
     "Version": "2012-10-17",
     "Statement": [
         {
             "Sid": "Stmt1451158079000",
             "Effect": "Allow",
             "Action": [
                 "ec2:*"
             ],
             "Resource": [
                 "*"
             ]
         },
         {
             "Sid": "Stmt1451158106000",
             "Effect": "Allow",
             "Action": [
                 "route53:*"
             ],
             "Resource": [
                 "*"
             ]
         },
         {
             "Sid": "Stmt1451158123000",
             "Effect": "Allow",
             "Action": [
                 "route53domains:*"
             ],
             "Resource": [
                 "*"
             ]
         },
         {
             "Sid": "Stmt1451158159000",
             "Effect": "Allow",
             "Action": [
                 "cloudfront:*"
             ],
             "Resource": [
                 "*"
             ]
         },
         {
             "Sid": "Stmt1451158173000",
             "Effect": "Allow",
             "Action": [
                 "s3:*"
             ],
             "Resource": [
                 "*"
             ]
         }
     ]
}
EOF
aws iam create-policy --policy-name $POLICY_NAME \
--description "Complete access to S3, CloudFront, Route 53 and Route 53 
Domains" \
--policy-document "$POLICY_JSON"
aws iam attach-group-policy --group-name $GROUP_NAME --policy-arn 
arn:aws:iam::031372724784:policy/$POLICY_NAME
aws iam list-attached-group-policies --group-name $GROUP_NAME


Thanks,

Mike
