### ISSUE TITLE
sync command for download files after restore from Glacier

### ISSUE THREAD

**Issue by dduleep** [aws/aws-cli#1699]
As my bucket policy every upload object moving to Glacier within one day.
when i need to download folder, i restore all objects inside folder using boto3. 
After that wait 5 hour and tried to download folder using aws sync command in aws cli 

once i try to download that give me bellow error
```
Object is of storage class GLACIER. Unable to perform download operations on GLACIER objects. You must restore the object to be able to the perform operation.
```

**Comment by JordonPhillips** [comment]
The reason for this is that we call [`GetObjects`](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) to determine the objects in the bucket, and unfortunately this does not include information about whether the file is restored or not. To get that information we would need to perform a `HeadObject` on every object in the bucket, resulting in as much as 1000x more requests. That's significant enough that we don't want to hide it behind a single command. If you know the object keys, you can download them individually with `cp` or `s3api get-object`.

**Comment by dduleep** [comment]
Thanks for your honest replay.
 I was trying run bellow command
```aws s3 sp s3://mybucket/myfolder/ localfolder --recursive```
unfortunately that gave to me same error as bellow

```
warning: Skipping file s3://mybucket/myfolder/file.sql. Object
is of storage class GLACIER. Unable to perform download operations on GLACIER ob
jects. You must restore the object to be able to the perform operation. 
```

but if i give object key that possible to download key.

aws sync and cp --recursive command support for directory concept. that was very simple and effective command for folder download.

Is there any command(aws cli command or boto3 method) available for download folder after restore object glacier to S3.

**Comment by JordonPhillips** [comment]
A recursive copy has the same issues as a sync. As of now there isn't any command that will try to download glacier objects regardless.

**Comment by DzamoNorton** [comment]
It's unfortunate.  For now I am using the following workaround

`aws s3 ls --recursive s3://my-bucket/path | awk '{print "s3://mybucket/"$4}' | xargs -L 1 -I % aws s3 cp % /my-local-dir`

**Comment by JordonPhillips** [comment]
We now have an argument, `--force-glacier-transfer` that will attempt a transfer on every glacier object.

**Comment by pleegor** [comment]
how about --ignore-glacier-warnings option? Is that feature working at all? I am trying to run
`aws s3 sync <bucket-a> --profile a <bucket-b> --profile b --ignore-glacier-warnings` and nothing happens

**Comment by JordonPhillips** [comment]
`--ignore-glacier-warnings` only ignores the problems, allowing the rest of the transfer to proceed. `--force-glacier-transfer` will actually attempt them.

**Comment by orblivion** [comment]
From a usability standpoint:

"You must restore the object to be able to the perform operation" implied to me that your tool had awareness of the restored state of the object. Amazon is telling me that the objects are restored. I have no idea why your tool seems to disagree.

Could you put something in the error message that makes it clear that your awareness, as you've explained here, is limited to requests for individual items? Secondly, perhaps add suggestion to use the new `--force-glacier-transfer` option if the user feels confident that all the objects are already restored?

**Comment by mjdellwo** [comment]
Concerning --force-glacier-transfer, what will be the consequence of doing so on an object that is in fact GLACIER class?  If it still fails, what is the difference between using and not using that flag?

Concerning --ignore-glacier-warnings, I presume this would be useful in a sync when you know you've initiated the restore, but perhaps not all objects are restored yet.  What happens if we do this in batch, and we've previously synced a file that was restored for, let's say, 2 days, but now 2 days have passed and that particular object is back in GLACIER class?  Will it throw an error again, or would it be skipped since it was already synced and considered unchanged ?

**Comment by NettSite** [comment]
I have just installed the AWS cli application, so am a brand new user - so far, I have to say the documentation is more cryptic and more difficult to understand and use than most I have come across, and I have seen some really bad documentation. I also had to search on Google to find this page to find out how to download objects which have been restored from Glacier.

**Comment by JordonPhillips** [comment]
@mjdellwo If you try to download something with `--force-glacier-transfer` that isn't restored, you'll get a hard failure rather than a warning.

@NettSite Sorry about the issues you're having with our docs. I've just [updated the warning](https://github.com/aws/aws-cli/pull/2476) that gets printed out to guide people to the correct doc page which includes this parameter.

**Comment by mjdellwo** [comment]
this seems consistent with 'get[ting] a hard error rather than a warning'.  Have you verified that all objects  under that prefix are in fact in a restored state?

**Comment by mdanish-ilsainteractive** [comment]
--force-glacier-transfer are there any charges for this flag ?

aws s3 sync s3://bucketname1 s3://bucketname2 --force-glacier-transfer --storage-class STANDARD
