### ISSUE TITLE
aws sqs get-queue attributes - no result

### ISSUE THREAD

**Issue by maanbsat** [aws/aws-cli#17]
Hello,

When using "aws sqs get-queue-attributes", the result always comes up blank:

```
$ aws sqs get-queue-attributes --queue-url https://queue.amazonaws.com/1234/sample_queue
{
    "ResponseMetadata": {
        "RequestId": "edfaceaa-a8a6-59b6-9e75-87f13e5d1da6"
    }
}
```

And if I try to specify a specific attribute (e.g. All or ApproximateNumberOfMessagesNotVisible), I get an error:

```
$ aws sqs get-queue-attributes --queue-url https://queue.amazonaws.com/1234/sample_queue --attribute-names ApproximateNumberOfMessagesNotVisible
{
    "ErrorResponse": {
        "RequestId": "7e742e72-b760-5881-a799-672920ab7f3b", 
        "Error": {
            "Message": "Top level element may not be treated as a list", 
            "Code": "MalformedInput", 
            "Type": "Sender", 
            "Detail": ""
        }
    }
}
A client error (Unknown) occurred: Unknown
```

Let me know if I can help. Thanks for the great tool!

Maan

**Comment by ryancastle** [comment]
It seems that `--attribute-names` is optional, but without it you get nothing.

Try `--attributes-names All`

**Comment by rodnaph** [comment]
> It seems that `--attribute-names` is optional, but without it you get nothing.
> 
> Try `--attributes-names All`

Minor correction: `--attribute-names`

Thanks so much!
