### ISSUE TITLE
lambda update-function-code --zip-file option inconsistent with create-function --zip-file option

### ISSUE THREAD

**Issue by mslinn** [aws/aws-cli#1704]
The `aws lambda create-function --zip-file` option help says:

````
--zip-file  (blob) The path to the zip file of the code you are upload-
       ing. Example: fileb://code.zip
````

Not sure what the (blob) pertains to.

Anyway, the `aws lambda update-function-code --zip-file` option docs say:

````
--zip-file (blob)
          Based64-encoded .zip file containing your packaged source code.
````

... which is confusing and inconsistent. The `--zip-file` option for the `update-function` command should work the same as for the `create-function` command. Instead, I understand this documentation to mean that instead of providing the path to the zip file as the value of this option, the contents of the zip file need to be provided as a base64-encoded string, which seems horrible. It would be much better to provide a value like `fileb://code.zip`.

**Comment by mslinn** [comment]
I went ahead and assumed the documentation was in error, and provided a value like `fileb://code.zip` and the`update-function-code` command appeared to work. Looks like the docs need tweaking.

**Comment by JordonPhillips** [comment]
Yes, that does seem to be a bit confusing. Thanks for letting us know!
