### ISSUE TITLE
Improve get-console-output in event of permissions failure

### ISSUE THREAD

**Issue by alexjs** [aws/aws-cli#1713]
[Edited: originally tested against 1.7.19 which just gives a single 'Output' line and no feedback , it's handled a *lot* better in 1.9, sorry! Nonetheless, it would be nice to add further debug info]

Currently get-console-output doesn't specifically indicate missing/incorrect credentials, just stating that the instance ID is invalid

```
» aws ec2 get-console-output --instance-id i-<id>
i-<id>	[    0.000000] Initializing cgroup subsys cpuset
» rm ~/.aws/credentials
» aws ec2 get-console-output --instance-id i-<id>

A client error (InvalidInstanceID.NotFound) occurred when calling the GetConsoleOutput operation: The instance ID 'i-<id>' does not exist
```

It may be beneficial to expand the error message to indicate that this could be caused by insufficient/incorrect credentials.

**Comment by JordonPhillips** [comment]
Following the same process, I get:
`Unable to locate credentials. You can configure credentials by running "aws configure".`

It seems to me that the error is that you have some other credential provider set up that does not have access to the relevant instance (or maybe even account). EC2 will try not to give you information about instances you don't have access to.
