### ISSUE TITLE
'aws s3 cp' crash server (With big files)

### ISSUE THREAD

**Issue by Trufelli** [aws/aws-cli#1723]
Hi!

I have a server running Amazon Linux AMI 2015.09 with aws-cli/1.9.18 and Python/2.7.10. If I use the 'aws s3 cp' with small size files (10MB) all are fine! I got the files and nothing anormal ocours. But if I try with bigger files (500MB), the server just crashes!

I've updated the aws cli to the latest version and so did with my SO, but I still have the same crashes!

I have attached the debug log downloading a bigger file and freezing my server.

[awsLog.txt](https://github.com/aws/aws-cli/files/89199/awsLog.txt)

Thanks for your help!

**Comment by JordonPhillips** [comment]
How much space do you have on your storage volume? I wouldn't think that would cause a crash, but who knows. Additionally, I notice you're writing to `/root`, maybe that has something to do with it? Amazon Linux doesn't allow root login, so I imagine you're running `sudo aws` to try getting write permissions. If that's the case, could you try downloading to the `ec2-user` home directory?

**Comment by Trufelli** [comment]
JordonPhillips

Thanks for your reply! We did more testing and we got the same issue with wget... So, its not an issue with AWS cli!
