### ISSUE TITLE
Able to delete s3 objects even when the policy doesn't allow it

### ISSUE THREAD

**Issue by 0xmohit** [aws/aws-cli#1737]
Output of `aws --version`:

```
aws-cli/1.9.21 Python/3.4.3+ Linux/4.2.0-23-generic botocore/1.3.21
```

Created a new IAM user with the following policy attached:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1453276235000",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::EXAMPLE-BUCKET/test"
            ]
        }
    ]
}
```

The file `$HOME/.aws/credentials` specifies `aws_access_key_id` and `aws_secret_access_key` for the IAM user.

Try uploading an object to the bucket:

```
$ aws s3 cp foo.txt s3://EXAMPLE-BUCKET/test/
upload: ./foo.txt to s3://EXAMPLE-BUCKET/test/foo.txt
```

So far so good.  Now try deleting the object:

```
$ aws s3 rm s3://EXAMPLE-BUCKET/test/foo.txt
delete: s3://EXAMPLE-BUCKET/test/foo.txt
```

This works too!  Shouldn't the `s3:DeleteObject` action be required in order to be able to delete objects from s3?

**Comment by 0xmohit** [comment]
Adding the following to the policy seems to work as intended:

```
        {
            "Effect": "Deny",
            "Action": [
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:PutLifeCycleConfiguration"
            ],
            "Resource": [
                "*"
            ]
        }
```

Somewhat counter-intuitive.

Apologies for the noise.

**Comment by JordonPhillips** [comment]
@0xmohit It is likely that your bucket policy allows you to perform the delete. A public-write bucket won't deny write access to anyone unless their policy explicitly forbids it, for instance.

**Comment by 0xmohit** [comment]
@JordonPhillips Thanks.  The default bucket permissions were too broad.  Fixing that causes the API to work as intended.
