### ISSUE TITLE
Update colorama version

### ISSUE THREAD

**Issue by Fale** [aws/aws-cli#1742]
It seems like the current aws-cli requires colorama >=0.2.5 and <=0.3.3, but the current colorama stable version in 0.3.6.
From tickets #1698 and #1700 I guess some fix will have to be executed before it's possible to update

PS: From colorama [changelog](https://github.com/tartley/colorama/blob/master/CHANGELOG.rst), it seems like from v0.3.3 they just fixed bugs, so it should not create any problem for the update (unless awscli was using a colorama bug as if it was a feature)

**Comment by Fale** [comment]
Any update on this? In the mean time, colorama 0.3.7 has been released

**Comment by Knio** [comment]
Hi,

Can you please mention what release on PyPI has this fix?

**Comment by Fale** [comment]
@Knio not really sure which fix you are speaking about. If you mean accepting colorama <= 0.3.7, I guess 1.11.28, since https://github.com/aws/aws-cli/commit/e28212cfde9525781d9c5d2bc548ba4d03242ce1 was  part of that release

**Comment by Knio** [comment]
That's what I was looking for, thanks!
