### ISSUE TITLE
file permissions of "iot create-keys-and-certificate" are too open

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#1745]
`aws iot create-keys-and-certificate` command supports saving command outputs of RSA key pair and an X.509 certificate with this commit https://github.com/aws/aws-cli/commit/1f99104b52f044d697a1ce391e77f5cf6535e4ca .

These files contain sensitive data but their permissions are `644` and they are accessible by other users.
It would be great if permissions are `600`.

```
$ aws iot create-keys-and-certificate \
  --set-as-active \
  --certificate-pem-outfile cert.pem \
  --public-key-outfile publicKey.pem \
  --private-key-outfile privateKey.pem
...
$ ls -l privateKey.pem publicKey.pem cert.pem
-rw-r--r--  1 jsmith  staff  1224  1 23 11:50 cert.pem
-rw-r--r--  1 jsmith  staff  1679  1 23 11:50 privateKey.pem
-rw-r--r--  1 jsmith  staff   451  1 23 11:50 publicKey.pem
```

**Comment by rekhajoshm** [comment]
Fix PR: https://github.com/aws/aws-cli/pull/1746

**Comment by mtdowling** [comment]
That sounds like a good idea. I'll take a look.

**Comment by mtdowling** [comment]
Addressed in https://github.com/aws/aws-cli/pull/1746  Thanks  @rekhajoshm!
