### ISSUE TITLE
Bug while sync'ing from S3 to local server using awscli

### ISSUE THREAD

**Issue by alanjohnmiller** [aws/aws-cli#1752]
I have an s3 bucket with hundreds of folders, and thousands of files. It is also a static website.

I sync the bucket to a local CentOS 6.7 server which is also a running the same website. 
The server is installed with:
aws-cli/1.10.0 Python/2.7.9 Linux/2.6.32-573.8.1.el6.x86_64 botocore/1.3.22

I run the following command:

aws s3 sync s3://www.website.com/ /home/website/public_html/ --delete --exact-timestamps

Which seems to correctly sync the entire website, but outputs the following errors:

download failed: s3://www.website.com/www/ to ../../../home/website/public_html/www/ [Errno 21] Is a directory: u'/home/website/public_html/www/'
download failed: s3://www.website.com/www/en/html/ to ../../../home/website/public_html/www/en/html/ [Errno 21] Is a directory: u'/home/website/public_html/www/en/html/'
Completed 2 part(s) with ... file(s) remaining

It does not report the same problem on any other local folder, even though it is syncing hundreds of folders.

I am trying to work out why this happens, and what the error means. 

/home/website/public_html/www/
/home/website/public_html/www/en/html/
are local folders. So the error message makes no sense at all.

The local permissions of these folders are the same as all other folders that are processed correctly without errors.
The S3 permissions of these folders are the same as all other folders processed correctly from S3 without errors.

This appears to be a bug, and I do not know why it reports an error when all other folders are correctly processed.

Any help would be appreciated.

**Comment by kyleknap** [comment]
So I have a feeling an issue is that the CLI is treating the s3 objects ``s3://www.website.com/www/`` and ``s3://www.website.com/www/en/html/`` as files to download as opposed to a directories. The error is caused because it is trying to write the contents of the objects to the same location as their corresponding directories, which should error out saying that you can write to the directory.

The CLI treats an s3 object as a directory only if it ends with ``/`` and has zero size. Could you determine if this file is of size zero? If that is the case I would either delete the object or upload an empty object to those keys.

**Comment by alanjohnmiller** [comment]
Hi Kyle

I have already checked the s3 objects s3://www.website.com/www/ and s3://
www.website.com/www/en/html/ and they appear in S3 with / on the end, and
zero size. I have checked this using both Amazon services, and S3 Browser
(a product I use on Windows).

I am not sure how to delete and reload these objects without also deleting
everything underneath them. If you have a method for doing this it would be
appreciated. I have more than 12G of data in the www/ folder. I don't
really want to go through uploading another 12G to amazon if I can help it,
since I have very little bandwidth availability from my main source of the
files (in rural Australia).

Is it possible that the problem is related to how CLI handles the
modification date/time of the folder, rather than the two issues you
mentioned?

Cheers


On Fri, Jan 29, 2016 at 11:04 AM, Kyle Knapp <notifications@github.com>
wrote:

> So I have a feeling an issue is that the CLI is treating the s3 objects
> s3://www.website.com/www/ and s3://www.website.com/www/en/html/ as files
> to download as opposed to a directories. The error is caused because it is
> trying to write the contents of the objects to the same location as their
> corresponding directories, which should error out saying that you can write
> to the directory.
>
> The CLI treats an s3 object as a directory only if it ends with / and has
> zero size. Could you determine if this file is of size zero? If that is the
> case I would either delete the object or upload an empty object to those
> keys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-cli/issues/1752#issuecomment-176504721>.
>



-- 

*AJ*

*Alan John Miller*
*aj@divinetruth.com <aj@divinetruth.com>*

**Comment by lbrownell-gpsw** [comment]
I'm having the same sort of problem. We have a bucket with a collection of files and directories; this has all been sync'ing just fine to Mac, Windows and Linux systems.  Until today.

Today, using S3 Browser, I added some new subfolders, and trying to sync I now get Errno 21 for the new folders.  The new folders show in in the S3 console as "Folders", storage class, size and last modified are all shown as "-", consistent with all the pre-existing folders that are syncing without issue.

On Linux and Windows, all appears to be synced; on the Mac, the folders are there, but the files within aren't.

Command, somewhat abstracted:
aws s3 sync s3://mybucket/synced/testcases /Users/me/testcases  --exclude "Exports/*" --delete

Any guidance?

**Comment by alanjohnmiller** [comment]
I have resolved my original issue.

Even though Amazon itself, and S3 Browser (a windows product for checking permissions on S3 objects) reported 0 bytes, and / on the end of each sub-folder, I found that for the two problem folders, there actually was 1 byte stored in each S3 object.

I used another product for windows (S3 Express) to upload folders only if they have changed, and the two folders with errors were uploaded correctly and corrected to 0 byte entries.

If anyone is using S3 Express in Windows, the command that fixed the folders was:

put D:\local\top\of\tree\folder\ s3bucket/top/of/tree/folder/ -include:"*.htm|*.html" -exclude:"*.*" -meta:"cache-control:max-age=43200" -s -onlynewer -purge -showdelete -showfiles -t:16 -optimize

Basically this command re-uploads my html, while excluding uploading everything else (which means I did not have to upload 12GB of data again), getting rid of any folder on S3 that does not match. If you use the -sim option in S3 Express, it will simulate so that you can see what will happen.

It appears that sometimes during an upload to S3, a single byte entry is made to some folders (I don't know why this happens yet), which turns the object on S3 into a file, which then causes the error described in the beginning of this issue while downloading to another location. However, these 1 byte entries are not correctly reported in Amazon itself or most other tools. Once these single byte objects are corrected, awscli then also operates correctly.

However, I could not fix the problem using awscli. I had to fix the problem with S3 Express. Perhaps in a future enhancement to awscli, there could be some kind of command which finds S3 objects that have / after them, and are 1 byte, and reports them as potential folder errors, and/or fixes them?
