### ISSUE TITLE
Feature request: consider adding short options

### ISSUE THREAD

**Issue by 0xmohit** [aws/aws-cli#1753]
Currently the CLI supports only long options.  While it might not make sense to provide short options in every case, those could be supported in certain cases.  For example, `aws s3 ls help` states:

            ls
          <S3Uri> or NONE
          [--recursive]
          [--page-size <value>]
          [--human-readable]
          [--summarize]

Short options, such as `-r`, `-n`, `-h`, `-s` could be provided in this case.  Those would be somewhat intuitive to someone familiar with `ls` and `du` on *nix systems.

**Comment by JordonPhillips** [comment]
Duplicate of #1602
