### ISSUE TITLE
unable to use --storage-class STANDARD_IA when using python 2

### ISSUE THREAD

**Issue by JumpingSpottedTiger** [aws/aws-cli#1764]
Running `aws s3 cp --sse --storage-class STANDARD_IA <file> s3://<file>` on Debian 8 with aws-cli/1.10.1 Python/2.7.9 Linux/3.16.0-4-amd64 botocore/1.3.23 results in:

```
Invalid choice: 'STANDARD_IA', maybe you meant: 
* STANDARD
```

I'm able to upload with STANDARD.

On Archlinux with aws-cli/1.10.1 Python/3.5.1 Linux/4.3.3-3-ARCH botocore/1.3.23 I can use STANDARD_IA.

**Comment by jamesls** [comment]
The error message would suggest you're using an old version of the CLI and not 1.10.1.  Just to be sure, can you post the `--debug` output?   I'm not able to repro the issue:

```
$ aws s3 cp --sse --storage-class STANDARD_IA foo.txt s3://bucket/stdia/
upload: ./foo.txt to s3://bucket/stdia/foo.txt
$
```

**Comment by JumpingSpottedTiger** [comment]
Terribly sorry to inconvenience, it was indeed an installation error on my side.

**Comment by Samuel-Raj-Sukumaran** [comment]
> Terribly sorry to inconvenience, it was indeed an installation error on my side.

Hi, could you please share what was the installation issue? I am facing the same error.
