### ISSUE TITLE
Elastic Beanstalk CLI keeps throwing error no matter how i install it

### ISSUE THREAD

**Issue by devotox** [aws/aws-cli#1768]
Running EB Init gives me this

https://www.dropbox.com/s/ymr05rldh761w2i/Screenshot%202016-02-02%2017.46.58.png?dl=0

**Comment by JordonPhillips** [comment]
The EB CLI is a separate product from the more general AWS CLI. I would recommend directing any questions regarding the EB CLI to the [elasticbeanstalk developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).
