### ISSUE TITLE
'aws s3 rb --force' should refuse to delete anything when objects within bucket are specified

### ISSUE THREAD

**Issue by dtenenba** [aws/aws-cli#1773]
A command like

    aws s3 rb s3://bucketname/foo/bar/baz --force

should probably return an error and refuse to do anything (with an error message explaining why), because it is probably a mistake on the user's part.

The `rb` subcommand removes an entire bucket, so there would be no reason to specify objects within the bucket. Doing so probably means the user is making a mistake (they should be using `rm` instead of `rb`) and should be saved from doing so. 

The `rb` subcommand with the `--force` flag (or even without it) should only work when no objects in the bucket are specified, for example:

    aws s3 rb s3://bucketname --force

**Comment by jamesls** [comment]
This should be fixed in: https://github.com/aws/aws-cli/pull/1477, which was first available in 1.8.3.  I believe if you upgrade to the latest version of the AWS CLI you should be all set.

Let me know if you're still seeing this issue in version 1.8.3 or later and I'll reopen and take a look.

**Comment by dtenenba** [comment]
I confirm the issue is solved with the latest version. Thanks.
