### ISSUE TITLE
How to describe instances from all regions?

### ISSUE THREAD

**Issue by ApproximateIdentity** [aws/aws-cli#1777]
I'm trying to switch my workflow over to the cli from the aws control panel, but I've run into a very odd issue. I know how to describe instances within a region, but how do I describe all of my instances irrespective of regions? Or at least get an output of all ec2 regions so I can do this programmatically one by one (i.e. something like `aws ec2 list-regions`).

It's very odd because the cli seems to use different names for regions than the control panel. For one, apparently all of my instances are being started in region "us-west-2" (at least so far), but I cannot find that string anywhere in the control panel. In fact, I can't seem to find anywhere listing my default region at all.

Is there a command inside of aws that does this?

**Comment by JordonPhillips** [comment]
The console doesn't allow you to list all instances irrespective of region, but it does hide the region identifiers with more descriptive text. `us-west-2` is the datacenter located in Oregon, for instance. There's a drop-down in the top right of the console page that lets you select a region (pictured below).

For most services, there is not currently a programmatic way of discovering which regions are available, and so you will need to refer to [this list](http://docs.aws.amazon.com/general/latest/gr/rande.html). EC2 is one of the exceptions, however, as it provides the [`describe-regions`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html) function. Since the CLI is a wrapper over service APIs, we can't do multi-region searches unless the service supports it (S3, for instance, is mostly region-agnostic). You will have to provide the region with the `--region` argument to query in a different region.

Your default region is located in your configuration file (`~/.aws/config` on UNIX systems), and can be both shown and set with the `aws configure` command.

![regions](https://cloud.githubusercontent.com/assets/2643092/12893940/e1212322-ce48-11e5-8636-e738bd337e7a.png)

**Comment by nonbeing** [comment]
For people arriving here from Google, here's one way to list all your instances across all regions with the AWS CLI (based on the discussion above):

```
for region in `aws ec2 describe-regions --output text | cut -f3`
do
     echo -e "\nListing Instances in region:'$region'..."
     aws ec2 describe-instances --region $region
done
```

**Comment by Fitblip** [comment]
For those of you who also don't want to parse JSON with your eyeballs, here's an appended version that uses [jq](https://stedolan.github.io/jq/) to give you a bit more-to-the-point summary. 

```bash
for region in `aws ec2 describe-regions --output text | cut -f3`
do
     echo -e "\nListing Instances in region:'$region'..."
     aws ec2 describe-instances --region $region | jq '.Reservations[] | ( .Instances[] | {state: .State.Name, name: .KeyName, type: .InstanceType, key: .KeyName})'
done
```

Example output: 
```json
Listing Instances in region:'us-west-1'...
{
  "state": "stopped",
  "name": "scanner-1",
  "type": "t2.micro",
  "key": "scan1"
}
{
  "state": "stopped",
  "name": "cors",
  "type": "t2.micro",
  "key": "cors"
}
{
  "state": "stopped",
  "name": "scanner-2",
  "type": "t2.medium",
  "key": "scan2"
}
```

**Comment by JordonPhillips** [comment]
@nonbeing Nice! If you use that often, you should consider making it an [alias](https://github.com/awslabs/awscli-aliases).

**Comment by pcgeek86** [comment]
Another option would be to use the AWS PowerShell .NET Core module, which runs natively on Linux, Mac, and Windows.

```powershell
foreach ($Region in (Get-AWSRegion)) {
  Get-EC2Instance -Region $Region.Region
}
```

### Results

```
GroupNames    : {}
Groups        : {}
Instances     : {asdf}
OwnerId       : 123
RequesterId   : 123
ReservationId : r-asdf

GroupNames    : {}
Groups        : {}
Instances     : {asdf}
OwnerId       : 123
RequesterId   : 123
ReservationId : r-asdf

GroupNames    : {}
Groups        : {}
Instances     : {asdf}
OwnerId       : 123
RequesterId   : 123
ReservationId : r-asdf
```

### Output using Format-Table

By default, in the current version of the AWS PowerShell module, the EC2 instances are returned in the PowerShell "list" format. However, this is easily changed to tabular formatting, using the `Format-Table` command.

```powershell
$InstanceList = @()
foreach ($Region in (Get-AWSRegion)) {
  $InstanceList += Get-EC2Instance -Region $Region.Region -ProfileName CIDBTest
}
$InstanceList | Format-Table
```

### Results

```
GroupNames Groups Instances   OwnerId      RequesterId  ReservationId       RunningInstance
---------- ------ ---------   -------      -----------  -------------       ---------------
{}         {}     {asdf222}   123          123                  r-123               {asdf222}
{}         {}     {asdf222}   123          123                  r-123               {asdf222}
{}         {}     {asdf222}   123          123                  r-123               {asdf222}
```

**Comment by jimdigriz** [comment]
You could use `jq`, if you like adding more dependencies, or just use the built in `--query` in AWS CLI:
````
aws --profile whatever ec2 describe-instances --query 'Reservations[].Instances[].[State.Name,InstanceType]'
[
    [
        "running", 
        "t2.small"
    ], 
    [
        "running", 
        "t2.small"
    ], 
    [
        "running", 
        "m3.medium"
    ]
]
````

For those wanting to integration with shell scripts, use `env AWS_DEFAULT_OUTPUT=text aws ...`

**Comment by ygeo** [comment]
while read -r r ; echo start region : $r ; do while read -r i ; do echo instance-id: $i 2>&1 ; done < <(aws ec2 describe-instances --query "Reservations[].Instances[].InstanceId" --region $r --profile prd|perl -nl -e 's/\s+/\n/g;print'); echo "stop  region: $r" ;  done < <(aws ec2 describe-regions --output text --profile prd| cut -f 3)

**Comment by Selimcse98** [comment]
Include tags value to better understand your EC2 instances

for region in `aws ec2 describe-regions --output text | cut -f3`
do
     echo -e "\nListing Instances in region:'$region'..."
     aws ec2 describe-instances --region $region | jq '.Reservations[] | ( .Instances[] | {state: .State.Name, name: .KeyName, Tag_Name: .Tags[].Value,type: .InstanceType, key: .KeyName})'
done

**Comment by AhmedAG80** [comment]
Just another solution I just wrote!
This small script can execute commands across all regions
Usage examples: 
sudo ./aws-x.sh ec2 describe-instances
sudo ./aws-x.sh ec2 describe-instances | grep PrivateDnsName

#!/bin/bash

echo "Getting AWS Avaiable Regions:"
sudo aws ec2 describe-regions --region eu-west-2 |grep RegionName |cut -d '"' -f 4 > /tmp/regions.txt
cat /tmp/regions.txt

#Start executing
while read region; do
	echo "Executing " $@ " on "  $region ":"
	aws --region $region $@ 
done</tmp/regions.txt

#cleanup
rm /tmp/regions.txt

**Comment by nlsko** [comment]
#!/bin/bash
echo Grabbing running instances in all regions, please wait..
for region in `aws ec2 describe-regions --output text | cut -f3`
do
aws ec2 describe-instances --region $region --query 'Reservations[].Instances[].[State.Name,InstanceType,PublicIpAddress,Placement.AvailabilityZone]' --output table
done

**Comment by obijan42** [comment]
> For those of you who also don't want to parse JSON with your eyeballs, here's an appended version that uses [jq](https://stedolan.github.io/jq/) to give you a bit more-to-the-point summary.

[aws cli supports the "query" parameter](https://docs.aws.amazon.com/cli/latest/userguide/controlling-output.html#controlling-output-filter), which does this stuff as a build-in.

**Comment by AhmedAG80** [comment]
Thanks obijan! I I started using jq few months back and it changed my life :)

**Comment by ajorpheus** [comment]
Note that the [AWS Cli Docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-json) do still recommend JQ for more advanced usage: 

> If you need more advanced features that might not be possible with --query, you can check out jq, a command line JSON processor. You can download it and find the official tutorial at http://stedolan.github.io/jq/

So if you are already used to the JQ query language, there might not be a good reason to switch to or learn yet another query language/syntax.

If you prefer to use the `--query` param, note that it uses [JMESPath](http://jmespath.org/) as its query language.

**Comment by PatMyron** [comment]
If `opt-in-not-required` is the 3rd column of output  when you run `aws ec2 describe-regions --output text`, you can change `cut -f3` to `cut -f4` like so:

```shell
for region in `aws ec2 describe-regions --output text | cut -f4`
do

done
```

**Comment by coltoncat** [comment]
Probably a more robust way is to use a JMESPath query as follows:

```
for region in $(aws ec2 describe-regions --query "Regions[*].RegionName" --output text)
do

done
```

**Comment by genyrosk** [comment]
You could also do some further parsing to filter to the regions that you want with `grep`. 
For instance, after installing [awscli-aliases](https://github.com/awslabs/awscli-aliases), add the following to `~/.aws/cli/alias` to list your instances:

```shell
list-instances =
  !f() {
    echo "Filtering by \`$1\`"
    for region in $(aws ec2 describe-regions --query "Regions[*].RegionName" --output text | tr "\t" "\n" | grep "$1")
      do
        echo "\nListing Instances in region:'$region'..."
        aws ec2 describe-instances --region $region \
          --output table \
          --query "Reservations[*].Instances[*].{
                    Instance:InstanceId,
                    Type:InstanceType,
                    AZ:Placement.AvailabilityZone,
                    KeyName:KeyName,
                    Name:Tags[?Key==\`Name\`]|[0].Value,
                    Project:Tags[?Key==\`project\`]|[0].Value,
                    IP:PublicIpAddress,
                    State:State.Name,
                    CPUcores:CpuOptions.CoreCount,
                    CPUThreads:CpuOptions.ThreadsPerCore
                }"
      done
  }; f
```

Usage:

```shell
$ aws list-instances
```

Apply a filter to the region code, e.g. `us` for US regions:
 
```shell
$ aws list-instances 'us'
```

**Comment by Johnjosh11** [comment]
for region in `aws ec2 describe-regions --output text | cut -f3`
do
     echo -e "\nListing Instances in region:'$region'..."
     aws ec2 describe-instances --region $region  | grep running > file.txt
     cat file.txt | wc -l
done



![image](https://user-images.githubusercontent.com/14269112/82467550-67517e80-9adf-11ea-83b0-214ed1c68f49.png)

**Comment by laidig** [comment]
The output format from `aws ec2 describe-regions` has changed slightly. If it doesn't work for you, try `cut -f4`.

```
for region in `aws ec2 describe-regions --output text | cut -f4`;
  do 
     echo -e "\nListing Instances in region:'$region'...";
      aws ec2 describe-instances --region $region | jq '.Reservations[] | ( .Instances[] | {state: .State.Name, name: .KeyName, type: .InstanceType, key: .KeyName})' > all_instances ;
done
```

**Comment by bugb** [comment]
@laidig worked on Jul 2021, thank you for that!!

**Comment by tomekit** [comment]
In my case I had to use: `aws ec2 describe-regions --output text | cut -f2` 
AWS cli version: `aws-cli/2.1.38 Python/3.8.8 Linux/5.11.0-38-generic exe/x86_64.ubuntu.21 prompt/off`

**Comment by N0B0T-cedric** [comment]
Yet another iteration on this theme:
```
for region in `aws ec2 describe-regions --output text | awk '{split($0,a," "); print a[2]}' | awk '{split($0,a,"."); print a[2]}'`;
  do 
      aws ec2 describe-instances --region $region > ec2-${region}.json
done
````

**Comment by ddigitalplus** [comment]
hi @N0B0T-cedric when I try your code and that of @bugb AWS comes back with an error saying "you must specify a region. You can also configure your region by running "aws configure"." 
I do not have local configs, I am logged to AWS through AAD SAML and I choose the account with --profile , please assist

**Comment by jujhars13** [comment]
> For people arriving here from Google, here's one way to list all your instances across all regions with the AWS CLI (based on the discussion above):
> 
> ```shell
> for region in `aws ec2 describe-regions --output text | cut -f3`
> do
>      echo -e "\nListing Instances in region:'$region'..."
>      aws ec2 describe-instances --region $region
> done
> ```

Thanks for this.  I had to use `cut -f4`  to get this to work as the region is in the 4th column on zsh:
```bash
AWS_DEFAULT_REGION=eu-west-1 aws ec2 describe-regions --output text
REGIONS	ec2.ap-south-1.amazonaws.com	opt-in-not-required	ap-south-1
REGIONS	ec2.eu-north-1.amazonaws.com	opt-in-not-required	eu-north-1
REGIONS	ec2.eu-west-3.amazonaws.com	opt-in-not-required	eu-west-3
REGIONS	ec2.eu-west-2.amazonaws.com	opt-in-not-required	eu-west-2
REGIONS	ec2.eu-west-1.amazonaws.com	opt-in-not-required	eu-west-1
REGIONS	ec2.ap-northeast-3.amazonaws.com	opt-in-not-required	ap-northeast-3
REGIONS	ec2.ap-northeast-2.amazonaws.com	opt-in-not-required	ap-northeast-2
REGIONS	ec2.ap-northeast-1.amazonaws.com	opt-in-not-required	ap-northeast-1
REGIONS	ec2.ca-central-1.amazonaws.com	opt-in-not-required	ca-central-1
REGIONS	ec2.sa-east-1.amazonaws.com	opt-in-not-required	sa-east-1
REGIONS	ec2.ap-southeast-1.amazonaws.com	opt-in-not-required	ap-southeast-1
REGIONS	ec2.ap-southeast-2.amazonaws.com	opt-in-not-required	ap-southeast-2
REGIONS	ec2.eu-central-1.amazonaws.com	opt-in-not-required	eu-central-1
REGIONS	ec2.us-east-1.amazonaws.com	opt-in-not-required	us-east-1
REGIONS	ec2.us-east-2.amazonaws.com	opt-in-not-required	us-east-2
REGIONS	ec2.us-west-1.amazonaws.com	opt-in-not-required	us-west-1
REGIONS	ec2.us-west-2.amazonaws.com	opt-in-not-required	us-west-2     
```

```bash
for region in $(AWS_DEFAULT_REGION=eu-west-1 aws ec2 describe-regions --output text | cut -f4)
do
     echo -e "\nListing deprecated lambdas in region:'${region}'..."
     aws lambda list-functions --region="${region}" --query "Functions[?Runtime=='nodejs16.x'].FunctionArn"
done
```

**Comment by CristianPrundeanu** [comment]
There are multiple ways to parse the output of `describe-regions`, the most stable being `jq` probably.
But assuming the last field will always be the region name and not relying on knowing the field number (it used to be 3, now it's 4 at least in some cases), one of the shortest ways to find it is this:
```
aws ec2 describe-regions --output text | sed 's/.*\t//'
```
