### ISSUE TITLE
Add .python-version to gitignore

### ISSUE THREAD

**Issue by kaizensoze** [aws/aws-cli#1783]
Using pyenv with tox is convenient but it generates a .python-version file which should be git-ignored.
e.g.
```zsh
pyenv install 2.6.9
pyenv install 2.7.11
pyenv install 3.3.6
pyenv install 3.4.4
pyenv install 3.5.1
pyenv rehash
pyenv local system 2.6.9 2.7.11 3.3.6 3.4.4 3.5.1
tox
```

**Comment by JordonPhillips** [comment]
This seems very tool specific, is there any reason you don't just add it to your global .gitignore?

**Comment by kaizensoze** [comment]
True. I just saw other non-project-specific-but-related things in the gitignore like emacs, Eclipse, IDEA, and figured why not.

**Comment by jamesls** [comment]
Interesting, I don't use pyenv.  Would anyone else find this useful?  I think if there's enough demand, I don't mind pulling #1784 in.

**Comment by kaizensoze** [comment]
It might make sense to have an `others-chime-in` tag since, from the perspective of someone looking at the issues list, `closing-soon-if-no-response` implies a reply is requested from the author of the issue.

**Comment by jamesls** [comment]
Good point, I like the idea of having something like "others-chime-in".  We can probably tag a couple other issues with this.

Any objections? cc @kyleknap @rayluo @JordonPhillips

**Comment by kyleknap** [comment]
I have no objections with adding it to the .gitignore. ``others-chime-in`` is also fine with me
