### ISSUE TITLE
`aws support` should always use correct region

### ISSUE THREAD

**Issue by mfischer-zd** [aws/aws-cli#1793]
The `aws support` subcommand should always use the correct region (us-east-1) and service endpoint regardless of what the region context is otherwise set to.  Otherwise the user will get confusing error messages such as failures to connect to service endpoints that don't exist.

**Comment by jamesls** [comment]
While the current set of regions for `aws support`  is `us-east-1`, we don't know if `support` will be added to other regions in the future.  There's a good explanation for a similar request (except with opsworks) here: https://github.com/boto/boto3/issues/301#issuecomment-159409325

That being said, we can try to improve the error messages when this happens.  There's also a tracking feature request to allow customers to provide default regions for different services which I think would help with this issue.  Let's track that progress over in https://github.com/aws/aws-cli/issues/1047

**Comment by mfischer-zd** [comment]
> we don't know if support will be added to other regions in the future

Understood, but can't you address that in a later version?  Users have to update the CLI from time to time to keep up with service changes anyway.

I'd appreciate it if you would not close this issue without a full discussion first.

**Comment by jamesls** [comment]
> I'd appreciate it if you would not close this issue without a full discussion first.

No problem, let's discuss.

> ...can't you address that in a later version?

There's a couple of points that the AWS SDKs including the AWS CLI are moving towards:

* We want customers to be aware of which regions they're using.  As we continue to launch more regions this becomes even more important for customers.
* We don't want to prefer one region over another.  If there's multiple regions available we should *not* be defaulting to a specific region.  We want customers to explicitly pick the region that makes the most sense for their use case, geographic location, etc.

If a service launches with only a single region today and we default to that region, we can never remove that default later.  This would be a backwards incompatible change.  As soon as a service launches into another region, we're now preferring a specific region over another.

What I propose, that I think accommodates all these constraints, is to make this as painless as possible.  Part of the problem we have now, which you mentioned, is that the error messages are confusing and not obvious.

What I envision as ideal:

```
# If we have our default region set to us-west-2:
$ export AWS_DEFAULT_REGION=us-west-2

# When you run a command, you get this error message:

$ aws support describe-cases

This service is not available in "us-west-2".  The available regions for this service are:

* us-east-1

To make this the default region for this service you can run:
    aws configure set support.region us-east-1
```

Does that seem reasonable?

**Comment by mfischer-zd** [comment]
> If a service launches with only a single region today and we default to that region, we can never remove that default later. This would be a backwards incompatible change.

It would not entail a backward-compatible change if the region was only ignored for those services for which there is a single endpoint.  (This assumes, of course, that an API exists that can tell the client what endpoints are available for a given service.)  If other endpoints later become available, then issuing your error message would be an appropriate way to fail in the face of ambiguity.

On the other hand, for those services that are endpoint-neutral or are global/single-region, there is no ambiguity resolve, and so I think it's a better user experience to handle those cases automatically.

**Comment by jamesls** [comment]
I want to make sure I understand your first point.

Let's say I have no region configured at all.  The proposed logic would be:

* User wants to run "aws support ...".    Did they provide a region for us to use?  No
* What regions is the service available in?  Is it only one region?  ["us-east-1"] -> True
* Because there's only one region for this service, we're automatically injecting "us-east-1" as the region to use.
* End result: **successful API call to us-east-1**

Then, let's say support launches in "us-west-2".  I upgrade the AWS CLI to the newest version.  I still have no region configured.  Now I rerun my script and the logic now becomes:

* User wants to run "aws support ...".    Did they provide a region for us to use?  No
* What regions is the service available in?  Is it only one region?  ["us-east-1", "us-west-2"] -> False
* There's multiple regions available, they didn't provide us a region so let's provide an error message letting them know that they need to explicitly pick a region for us to use.
* End result: **Error message to customer that they need to pick a region**

Did I understand correctly?

**Comment by mfischer-zd** [comment]
Yes, that's correct. 

I sense an issue that this might cause a problem for fledgling services being rolled out in a single region.  Is there a way we can have our cake and eat it too here?

**Comment by jamesls** [comment]
We're certainly open to suggestions.  The best suggestion I've heard so far was the customer's suggestion in #1047, which allows the user to configure a default set of regions per service.  Yes, it's a one time configuration step they need to perform, but from that point forward everything will work how they'd like.

I'd like to hear your thoughts on that approach.  I know it's not 100% automatic, but it seems reasonable.

**Comment by mfischer-zd** [comment]
OK, thanks.  Feel free to close out this issue.

**Comment by jamesls** [comment]
Cool, closing issue.
