### ISSUE TITLE
source_profiles are not chained

### ISSUE THREAD

**Issue by mfischer-zd** [aws/aws-cli#1794]
Configuration profiles do not chain properly to follow the source profiles to the root.

For example, if I configure the following:

```
[profile default]
aws_access_key_id = xxxxx
aws_secret_access_key = xxxxx

[profile tokyo]
source_profile = default
region = ap-northeast-1
role_arn = arn:aws:iam::123456789012:role/PowerUser

[profile tokyo-support]
source_profile = tokyo
region = us-east-1
```

I expect the "tokyo-support" profile to inherit the values from the "tokyo" profile first, and if not defined therein, from the "default" profile. 

Instead, I receive an error when using the "tokyo-support" profile that my credentials cannot be located.

**Comment by jamesls** [comment]
I agree this would be useful.  There's an existing future request for this here, consolidating issues: https://github.com/aws/aws-cli/issues/1086
