### ISSUE TITLE
groff 1.22.3 on smartos won't parse help text

### ISSUE THREAD

**Issue by jblachly** [aws/aws-cli#1798]
Due to the way the latest groff 1.22.3 is installed on smartos (through pkgsrc), the traditional

`groff -man` will not parse man format pages correctly. I think this may be related to groff 1.22.3 in general, not the particular installation on smartos (illumos), but I do not have latest groff on either my mac or linux machines to test. In any case, as a result, there is empty help text when using `aws help`.

The fix, which should not interfere with other platforms, is to run `groff -m man`; you can change the line setting up the groff command in `help.py` to:

`cmdline = ['groff', '-m', 'man', '-T', 'ascii']`

In case someone has groff 1.22.3 installed on another platform it would be worth testing to see if the help pages are rendered correctly.

**Comment by jblachly** [comment]
Upon closer inspection, this may be a problem with *any* platform using **pkgsrc** installation of groff 1.22.3, wherein installation of `an.tmac` is commented out.

It would be helpful if someone with NetBSD or another platform using pkgsrc installation of groff could test this out.

**Comment by JordonPhillips** [comment]
I've run `aws help` with groff 1.22.3 installed via homebrew and also pkgsrc. Both installations worked. It looks like `-man` and `-m man` are identical, so I don't know why that would make a difference. This definitely seems like a bug with groff on smartos.

**Comment by jblachly** [comment]
That's a huge help in terms of narrowing down the problem. 

I recognize -man and -m man should be identical, but the legacy (i.e. `-man`) behavior is implemented using a macro package called `an` which should redirect to mandoc but it is not. I note that in both smartos and NetBSD's pkgsrc installers the an.tmac file is not installed.

On what platform did you test a pkgsrc installed version of groff?

**Comment by JordonPhillips** [comment]
OSX. SmartOS is not available as an instance type on EC2 (no surprise since it is maintained by a competitor), so I wasn't able to test there. This definitely looks like a change we could pull in, but I'd rather see the root cause fixed. Have you tried raising an issue with the SmartOS maintainers?

**Comment by jblachly** [comment]
I will as soon as I can narrow it down to SmartOS. 

pkgsrc is also used by NetBSD and I noticed in the NetBSD version of the package that `an.tmac` is also commented out, so I need to track the error to the appropriate upstream source.

Thanks for your patience; will report back.
