### ISSUE TITLE
as put-metric-alarm does not warn user when using period inappropriate to namespace

### ISSUE THREAD

**Issue by y-p** [aws/aws-cli#180]
Debugging an issue led me to [this AWS forum thread](https://forums.aws.amazon.com/thread.jspa?threadID=99679)
It appears that 60 seconds is a lower bound on mertic periods across 
all services, but some services has a higher minimum of 5 minutes,
SQS being an example. 
aws-cli warns you when you set a value to lower then 60, but will allow
a settings of 60 when referencing a namespace in which it is not invalid,
and this causes the alarm to remain in an "INSUFFICIANT_DATA" state.

Since the namespace argument must be specified, it should be possible
to warn the user when he is about to shoot himself in the foot.

(partial) Command example:
```
 put-metric-alarm --alarm-name AddCapacityToProcessQueue  --metric-name ApproximateNumberOfMessagesVisible --namespace "AWS/SQS" --statistic Average --period 300 <...>
```

**Comment by JordonPhillips** [comment]
Less than 5 minutes is still a valid period, you just will need to wait on new metrics before the alarm goes into the ALARM state.

http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/as-using-sqs-queue.html#create-sqs-cw-alarms-cli
