### ISSUE TITLE
Ability to include external file contents in cli parameters json

### ISSUE THREAD

**Issue by tpakula-fender** [aws/aws-cli#1803]
For instance, to create a new CloudFormation stack, I would like to do something like

`aws cloudformation create-stack --cli-input-json file://mystack.cliparameters`

where the contents of `mystack.cliparameters` is

`{
  "TemplateBody": "file://mystack.cloudformationtemplate",
  "Parameters": [
    {
      "ParameterKey": "UserDataParam",
      "ParameterValue": "file://userdata.sh",
      "UsePreviousValue": false
    }
}`

`mystack.cloudformationtemplate` then contains the actual CloudFormation template, and `userdata.sh` contains the script used to bootstrap the instance at launch time.

Currently, I have to do 

`aws cloudformation create-stack --cli-input-json file://mystack.cliparameters --template-body file://mystack.cloudformationtemplate`

...and specify the userdata explicitly within `mystack.cliparameters` which can get very messy with newlines if the userdata script is more than just a few lines.

**Comment by jamesls** [comment]
There was a similar request a while back here: https://github.com/aws/aws-cli/issues/1097

In that scenario, they wanted to be able to specify binary contents as a value, which isn't possible in a JSON document.  The most reasonable way to do this would be to reference a file in the JSON document.

We've explored several options, but the main constraint we're running into is that we'd need this to be backwards compatible.

The solution you've proposed could work.  However, if there's existing users that want to specify the *literal* string value of `file://mystack.cloudformationtemplate` and we change this behavior to now interpret this as mean "insert the contents of this file", this will be a breaking change.

Another solution proposed was to support something besides JSON.  YAML would allow for custom tags (i.e `!file`), one of which could be a "file" tag.  Another option would be to extend JSON to support something like:

```
{"foo": file:///path/to/file}     # Note there's no quotes around the file path
{"foo": File("/path/to/file")}
```

If we can come up with something that's backwards compatible, I think this is something we should do.
I'm interested to hear what others have to say.

**Comment by tpakula-fender** [comment]
Ahh, I see where my suggestion might break things. CloudFormation itself does something like the JSON extension you've proposed, so maybe similar to the following in the CLI parameters JSON:


`{ "ParameterKey": "UserDataParam", "ParameterValue": { "Fn::ExtFile": "/path/to/file" }`

Bonus: the door is then open to adding other functions without breaking backwards compatibility by introducing new.

**Comment by jamesls** [comment]
Very interesting idea.  If we only apply this for scalar values (strings, integers, booleans, floats), then it should be entirely backwards compatible.  Previously the value had to be a string, so providing a dictionary type would cause a validation error, so all we would do now is pre-process the data, look for the `{"Fn::ExtFile" ....}` where a string type was previously used and replace that value with a string.

**Comment by tridays** [comment]
Could this bug be fixed soon? It has exists for one year.

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (172/150 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:60133 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0Qr-001bk7-It
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:24:57 -0700
Date: Tue, 06 Feb 2018 02:24:43 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912683;
	bh=tqTIm5tCw5vaBvyleO8ZJxQTcNGh4HuAA3sOn2llpwA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hMpxoYpDt4cgnoBejHY3pY4mrkFoLmlyk6l+RGnKPtbFoGAfukLkXSmQCldlWz74g
	 qIlJIva5Xwv6n8/explqarzvDjmm1cWzyOtgGt9+pJ1BwxT2QiPU3wCMUE/oKC8g2l
	 +7AGVY6bd4EyC6lysaEJc2TwIi7SBm7AKJsmD304=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (173/150 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6164 characters long; only the first
------ 5000 or so are included here.
Received: from o3.sgmail.github.com ([192.254.112.98]:56835)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Qr-001bk0-GS
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:24:58 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=AsGNIcF4FLj6IL3v+J9+hO3nHUQ=; b=sy2sSGt4dWRI2+5X
	B7ZO/mvLaAtJi1ZHPy4Rl2k+rZoB9ocBgtX5JkP6IDosqBFvEnEw5a4cVTEWZI7u
	M9N6W4JUQkKpuLVmKqXlVFPLoOo2Q+uAl851lBHka118XQkHlyGbFBMWtzYkvaE0
	b2FJIIO5ZOeYtRcLuekuKUPd0R4=
Received: by filter0953p1mdw1.sendgrid.net with SMTP id filter0953p1mdw1-24171-5A79826B-5
        2018-02-06 10:24:43.174478305 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id HdDB_aMjTxueywQ5RzTgpw
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:24:43.135 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:24:43 +0000 (UTC)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by TRT-GruffM** [comment]
This is still an issue 2 years on. Perhaps your backlog management needs looking at.
