### ISSUE TITLE
Don't url-encode S3 paths

### ISSUE THREAD

**Issue by boosh** [aws/aws-cli#1805]
Working with spark, parquet partitions data with key-value pairs separated by an equals sign. Currently, aws cli is URL encoding returned paths which makes copying and pasting paths difficult. E.g. the path `/my/data/date=2016-01-01` is printed as `/my/data/date%3D2016-01-01`.

Please can we have an option to not URL encode S3 paths. Thanks.

**Comment by jamesls** [comment]
Can you clarify which s3 commands are returning url encoded paths?

```
$ aws s3 ls bucket/foo/
2016-02-24 14:34:59          0 data=2016-01-01
```

**Comment by boosh** [comment]
`aws s3 ls` is:

```
aws s3 ls s3://my/path/data_source=account/
                           PRE date%3D2015-03-13/
                           PRE date%3D2015-03-15/
                           PRE date%3D2015-03-17/
```
This is aws-cli/1.9.11.

**Comment by jamesls** [comment]
The CLI should already be handling this.

I believe that's because the actual object in s3 is stored urlencoded.

Here's a full example that shows what I tried.  Could you run this example for me and show we your output?

```
$ mkdir /tmp/noencode
$ cd /tmp/noencode/
$ touch date=2016-01-01
$ touch date=2016-01-02
$ touch date=2016-01-03
$ aws s3 cp . s3://your-bucket-name/data_source=account/ --recursive
upload: ./date=2016-01-02 to s3://your-bucket-name/data_source=account/date=2016-01-02
upload: ./date=2016-01-03 to s3://your-bucket-name/data_source=account/date=2016-01-03
upload: ./date=2016-01-01 to s3://your-bucket-name/data_source=account/date=2016-01-01
$ aws s3 ls s3://your-bucket-name/data_source=account/
2016-02-25 10:31:09          0 date=2016-01-01
2016-02-25 10:31:09          0 date=2016-01-02
2016-02-25 10:31:09          0 date=2016-01-03
```

**Comment by boosh** [comment]
Ah yeah it does work. Must be spark urlencoding the equals sign. Thanks.
