### ISSUE TITLE
sync replaces identical fils if hardlinked locally

### ISSUE THREAD

**Issue by nkadel-skyhook** [aws/aws-cli#1808]
If I am testing some complex and bulky environments, such as 100 Gig OS image stored in S3, and I hardlink my locally synced file to another location, the hardlink seems to tell the "aws s3 sync" commands that the local file is no longer identical with upstream and will need to be deleted and resynced. This is seriously inefficient if one is working with quite bulky sync'ed files and wants to save local disk space.

Is this intended? If not, is it feasible to tweak the "aws s3 sync" command to ignore hardlinks as a relevant reason to update a local file?

**Comment by jamesls** [comment]
The first thing we'd need to check is why the CLI thinks the file is being synced.  You can run:

```
aws s3 sync s3://bucket/ . --dryrun --debug 2>&1 | grep comparator
```

To see why the CLI is syncing the file.

My guess as to what's happening is that hardlinking will change the mtime, which we use to determine if a file has changed.

If that is the case, you can try using `--size-only` which will only sync the file is the file size changes.

Let me know if that works for you.
