### ISSUE TITLE
global name 'ssl' is not defined

### ISSUE THREAD

**Issue by liangjiaxing** [aws/aws-cli#1817]
When I run `aws s3 ls`. I got an error `global name 'ssl' is not defined`.

**Comment by kyleknap** [comment]
Can you run the command with ``--debug`` and show us the output? I am not seeing this issue with the latest version of the CLI.

**Comment by liangjiaxing** [comment]
My machine was looking for the wrong directory of the ssl directory.
The issue was fixed by running the command:  `unset DYLD_LIBRARY_PATH`

**Comment by liangjiaxing** [comment]
Thanks for looking at it @kyleknap
