### ISSUE TITLE
Support for extended file attributes in S3 commands

### ISSUE THREAD

**Issue by KrzysiekJ** [aws/aws-cli#1833]
It would be a handy feature for the `sync`/`cp`/`mv` commands to support synchronizing extended file attributes from the `user` namespace with user-defined metadata. To preserve backwards compatibility, this behaviour could be triggered by a command line flag.

Keywords: attr, xattr

**Comment by jamesls** [comment]
I think this is similar to https://github.com/aws/aws-cli/issues/1585, except instead of POSIX ACLs this is the `attr/xattr` values.

I'd like to consolidate issues and make #1585 a general purpose "additional file metadata/attributes" feature request.  Let me know if you see any issues with that.

**Comment by KrzysiekJ** [comment]
No issues for me. However I guess it may be easier to handle this case, as extended attributes from the `user` namespace already have their counterpart (user-defined metadata), while I don’t see where to store filesystem ACLs.

**Comment by kyleknap** [comment]
Closing in favor of the feature request that James linked to consolidate feature requests.
