### ISSUE TITLE
Pull request for fix formating and indentation issues for autoscaling documentation

### ISSUE THREAD

**Issue by tuxinaut** [aws/aws-cli#1834]
Hello,

Are you interested in a **bigger** pull request for fixing the formatting and indentation issues for the ```autoscaling``` documentation? Because I looked over these **rst** files and saw a lot of indentation and mixed indentation errors.

I think that the rest of the documentation also needs a check.

**Comment by jamesls** [comment]
Can you clarify which autoscaling files you're referring to?

If it's `awscli/examples/autoscaling`, then we'd be happy to accept pull requests for that.

If it's in `doc/source/reference/`, then those files are autogenerated and we won't be able to accept pull requests to those files.  We would however accept pull requests for our doc generator code that creates those `.rst` files.  If that's too big of a task, let us know which parts of the autoscaling docs have formatting issues and we can take a look at updating our doc generator.

**Comment by tuxinaut** [comment]
Ah good to know. I'm referring to files under `awscli/examples` that mean we're good to go?

**Comment by jamesls** [comment]
Yep, feel free :)

**Comment by kyleknap** [comment]
Thanks for the PR. Just merged it.
