### ISSUE TITLE
Exception thrown if uploaded file size > 5TB

### ISSUE THREAD

**Issue by Diggs** [aws/aws-cli#1842]
We recently hit an exception when uploading a large file that by the looks of it should instead be reported to the user as a helpful message. The exception is being raised attempting to create that helpful message.

Version: aws-cli/1.10.11 Python/2.7.9 Windows/2012Server botocore/1.4.2

on: create_warning() got an unexpected keyword argument 'message' 
Traceback (most recent call last): 
File "awscli\customizations\s3\s3handler.pyc", line 99, in call 
File "awscli\customizations\s3\s3handler.pyc", line 186, in _enqueue_tasks 
TypeError: create_warning() got an unexpected keyword argument 'message'

Looks like it is happening here:

https://github.com/aws/aws-cli/blob/c5fb60e1b49667d6f689bb8f8670ed4a1c01791a/awscli/customizations/s3/s3handler.py#L185

I think message= should be error_message= (although I don't know Python, so could be reading it wrong.

**Comment by jamesls** [comment]
Thanks for letting us know, we'll get that updated.
