### ISSUE TITLE
Running `s3 cp` download to local file where you don't have write permissions results in hang

### ISSUE THREAD

**Issue by paultyng** [aws/aws-cli#1845]
The CLI just hangs if i try to run a command similar to `aws s3 cp s3://remote/path local-path` with no error messaging, but if I run with `sudo`, executes fine.  The CLI should probably test write access and fail quickly instead of hanging or waiting on a download first.

This was on the most recent Ubuntu AMI with the most recent awscli package installed.

The file was 2 GB, so it may be something having to do with the progress output.

`Ubuntu 14.04.3 LTS`
`aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-74-generic`

**Comment by jamesls** [comment]
I can confirm similar behavior.  I can't get it to hang, but I do get a significant delay proportional to the size of the file.

For small files, it works as expected:

```
/tmp/repro $ aws s3 cp s3://bucket/key foo
download failed: s3://bucket/key to ./foo [Errno 13] Permission denied: u'/private/tmp/repro/foo'
```

But for large files I see:

```
 $ time aws s3 cp s3://bucket/key foo
download failed: s3://bucket/key to ./foo
[Errno 13] Permission denied: u'/private/tmp/repro/foo'
Completed 1 part(s) with ... file(s) remaining

real	0m39.957s
user	0m42.945s
sys	0m4.073s
```

Is this similar to what you're seeing?

I believe what's going on here is that the CLI marks the create file task as failed but the task threads still need to cycle through all the download parts tasks, see that they're marked as failed, and move on.  For a large file this can take a while.

We can fix this for the single file case, but I think we'll still have this problem for a `cp --recursive` and a  ``sync``.

**Comment by paultyng** [comment]
Yeah, I imagine it has something to do with the size.  I didn't wait for completion though so I can't fully confirm.

**Comment by kyleknap** [comment]
Going over older issues. Resolving this as fixed. We made numerous improvements to the S3 commands a few years back which included faster fail times. I tried the following and it exited significantly faster that times posted in the issue:
```
$ time aws s3 cp s3://mybucketfoo/50GB /tmp/sudo-access/
download failed: s3://mybucketfoo/50GB to ../../tmp/sudo-access/50GB [Errno 13] Permission denied: '/tmp/sudo-access/50GB.d191F50c'

real	0m4.354s
user 0m1.680s
sys	0m0.323s
```
To get this behavior, please upgrade to the [AWS CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html)
