### ISSUE TITLE
shorthand does not allow hash(#) in key, used by dynamodb, regression from 1.7.47

### ISSUE THREAD

**Issue by crowe1** [aws/aws-cli#1848]
note: this is a regression from (v1.7.47 to v1.8.0+)

dynamodb placeholders have a hash(#) in their name:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ExpressionPlaceholders.html

this comes into play when passing in the --expression-attribute-names argument:
http://docs.aws.amazon.com/cli/latest/reference/dynamodb/put-item.html

previously (v1.7.47 and earlier), this was allowed:
`   --expression-attribute-names='#k=version'`

now (v1.8.0 through v.1.10.12), it is not.
the error message is:
> Error parsing parameter '--expression-attribute-names': Expected: '=', received: '#' for input:
> #k=version
> ^

it appears due to the code in shorthand.py (lines 164-166):
```
    def _key(self):
        # key = 1*(alpha / %x30-39 / %x5f / %x2e)  ; [a-zA-Z0-9\-_.]
        valid_chars = string.ascii_letters + string.digits + '-_.'

```
the valid_chars does not allow for '#'

passing in the argument via json works:
`  --expression-attribute-names='{"#k":"id"}'`

steps to reproduce:
```
## create a table
aws dynamodb create-table --table-name table --key-schema AttributeName=id,KeyType=HASH --attribute-definitions AttributeName=id,AttributeType=S --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --output json

## add an item
aws dynamodb put-item --table-name table --item '{"id":{"S":"x"},"version":{"S":"0"}}' --output json

## conditionally update the item using shorthand (fails)
aws dynamodb put-item --table-name table --item '{"id":{"S":"x"},"version":{"S":"1"}}' --condition-expression '#k <= :k' --expression-attribute-name '#k=version' --expression-attribute-values '{":k":{"S":"0"}}' --output json

## conditionally update the item using json (works)
aws dynamodb put-item --table-name table --item '{"id":{"S":"x"},"version":{"S":"1"}}' --condition-expression '#k <= :k' --expression-attribute-name '{"#k":"version"}' --expression-attribute-values '{":k":{"S":"0"}}' --output json
```
the simplest fix would be to add '#' to the valid_chars, however it seems that maybe it is only a valid_char for dynamodb and only when it is the first char, so i'll leave it to you to decide what is appropriate.

**Comment by kyleknap** [comment]
Can confirm. Should be easy to fix.
