### ISSUE TITLE
Change output of get-bucket-policy

### ISSUE THREAD

**Issue by SpoonBoy** [aws/aws-cli#1851]
The current output of `get-bucket-policy` is a JSON with a single `Policy` key containing a string value.

```
aws s3api get-bucket-policy --bucket my-bucket
{
    "Policy": "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::my-bucket/*\"},{\"Sid\":\"\",\"Effect\":\"Deny\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::my-bucket/secret/*\"}]}"
}
```

Actually, that string is JSON formated, so it would make sens to have the output as follow : 

```
aws s3api get-bucket-policy --bucket my-bucket
{
    "Policy": {
        "Version": "2008-10-17",
        "Statement": [
            {
                "Sid": "",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::my-bucket/*"
            },
            {
                "Sid": "",
                "Effect": "Deny",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::my-bucket/secret/*"
            }
        ]
    }
}
```

it would also make the API more consistent, since all other `get-bucket-*` API return a valid JSON structure

This was tested with `aws-cli/1.10.1 Python/2.7.9 Linux/4.0.0-kali1-amd64 botocore/1.3.23`

**Comment by JordonPhillips** [comment]
While we wouldn't be able to change this in botocore for backwards compatibility reasons, we may be able to alter the CLI output. Thanks for letting us know!

**Comment by morkot** [comment]
@SpoonBoy  as far as I understood the issue appears when output is ```json```, so aws-cli have to output json inside json. If you use ```--output text``` then it will output it correctly:
```bash
❯ aws --version
aws-cli/1.11.148 Python/2.7.10 Darwin/15.6.0 botocore/1.7.6

~
❯ aws s3api get-bucket-policy --bucket my-bucket --output text | jq .
```

**Comment by ASayre** [comment]
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (176/150 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 6170 characters long; only the first
------ 5000 or so are included here.
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:34656 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1ej0Qx-001blV-47
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:03 -0700
Date: Tue, 06 Feb 2018 02:24:52 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1517912692;
	bh=S0lhwfPsFysmGa1sYiAa4Imd7m+VyFuWj9LvfM4y6Sw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MrNGaYNyVGdQBAuvnXK36HOthfGT+QyldRyITHnw3XcQNV6p/Yb9vN0GGYi/SoVeT
	 3QEfTe2oSr0F6ruQIsmgUzk6RdBrYukSkl3JJ3mqu/6npMmvc4BO2+5CobRPkNBSjT
	 grlrPLfkII02X5HiRzmrTNM0quUZZYJaOIUgIAys=

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (177/150 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:17561)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1ej0Qy-001bmO-4r
	for hello@salmanwaheed.info; Tue, 06 Feb 2018 03:25:04 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=efHMkHVSTeVtEpZ2N2CD5PaapYQ=; b=KVrKtZhXNYxS391I
	8aG92mqxi4n2pBWJMqcHu4y6JqIAD/CUtPYsoRh8qmaKSeS2porPUYdG3vwo4wJ0
	sH4hD7/6H+CiEcJErmaQ25F13+N/vZXT1IHuvnWmALjY4wIQyRJf1OYfVZaVExnG
	PIe/2sOx+P6mEDAZibrMu/NVi3k=
Received: by filter0605p1mdw1.sendgrid.net with SMTP id filter0605p1mdw1-30577-5A798275-9
        2018-02-06 10:24:53.105112722 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id nRgqFU98SyiAwvUKLjkjeA
	for <hello@salmanwaheed.info>; Tue, 06 Feb 2018 10:24:53.050 +0000 (UTC)
Date: Tue, 06 Feb 2018 10:24:53 +0000 (UTC)

**Comment by jamesls** [comment]
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by chadasapp** [comment]
The workaround I ended up with was piping to `jq` like this:
`aws s3api get-bucket-policy --bucket=foo | jq '.Policy | fromjson'`
