### ISSUE TITLE
Add config option to enable sse on all s3 cp commands

### ISSUE THREAD

**Issue by tylerprete** [aws/aws-cli#1853]
My company is going to start requiring sse on all s3 uploads soon. Would be nice to set this once rather than adding --sse on every single cp command.

**Comment by JordonPhillips** [comment]
Thanks for the feature request! We'll add this to the backlog.

**Comment by alexlo03** [comment]
+1
possible dupe https://github.com/aws/aws-cli/issues/1080

**Comment by JordonPhillips** [comment]
@alexlo03 Nice catch, lets keep tracking there.

**Comment by echan5** [comment]
Was this ever added as a feature, or is there to specify a default `--sse`?
