### ISSUE TITLE
aws kms has 'utf8' codec can't decode byte error

### ISSUE THREAD

**Issue by jimmy0x52** [aws/aws-cli#1855]
This appeared in earlier issue #1001 and was closed as fixed. Noticed today the same error occurs -- so this may have been reintroduced.

```
mooney:~ jimmymooney$ aws --version
aws-cli/1.6.2 Python/2.7.10 Darwin/15.3.0
mooney:~ jimmymooney$ aws kms generate-random --number-of-bytes 128 
{
    "Plaintext": 
'utf8' codec can't decode byte 0xc3 in position 5: invalid continuation byte
mooney:~ jimmymooney$ aws kms encrypt --key-id alias/REDACTED --plaintext "bar"
{
    "KeyId": "REDACTED", 
    "CiphertextBlob": 
'utf8' codec can't decode byte 0xc6 in position 2: invalid continuation byte
mooney:~ jimmymooney$
```

**Comment by JordonPhillips** [comment]
Your CLI version is very close to the version reported as being affected. Have you tried updating to the latest version (1.10.13 at time of writing)?

**Comment by jimmy0x52** [comment]
Apologies - I was relying on `homebrew` to update me to the latest `awscli`. I hadn't realized that I hadn't updated `homebrew` itself in a while and it wasn't aware of the newer versions of the `awscli`. After running `brew update` and then `brew upgrade awscli` again, I now have version 1.10.12 and it seems to be resolved.

Please close. Sorry for the alarm!
