### ISSUE TITLE
tagging resources: value gets interpreted and its not possible to use quotes

### ISSUE THREAD

**Issue by femans** [aws/aws-cli#1856]
I can't put any data into the value of a tag. I tried using quotes because this is how the data should be stored, but the code doesn't accept anything of the sort. I can't escape or anything. Then if I remove all the quotes, it does this:
```
aws ec2 create-tags --resources ami-b13983c2 --tags Key=environment,Value=development Key=projects,Value="{panda=>2.0.3}"

Parameter validation failed:
Invalid type for parameter Tags[3].Value, value: {u'panda': u'>2.0.3'}, type: \<type 'dict'\>, valid types: \<type 'basestring'\>
```

clearly does not handle it as a string.

**Comment by JordonPhillips** [comment]
The trick here is that the shell is taking those quotes and passing along a string literal, which is what we'd expect to see for a dict value. To get your shell to pass a quoted string to the CLI, you'll need to double quote it like so `"'{panda=>2.0.3'"`

**Comment by femans** [comment]
thank you very much. That works :)
