### ISSUE TITLE
Different config file between 

### ISSUE THREAD

**Issue by zzreader** [aws/aws-cli#1877]
The aws-ruby-sdk is mentioning (at this page http://docs.aws.amazon.com/sdkforruby/api/index.html)  this

The shared credentials ini file at ~/.aws/credentials (more information)

But your doc is mentioning saving to the ~/.aws/config

Shouldn't you use the same default? Also this article was published in 2014 http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs

Seems that credentials should be the default name or am I missing something?

**Comment by zzreader** [comment]
Even more, the aws configure help seems to refer to the credentials, yet doing a aws configure list
shows

% aws --profile 'profile test' configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile             profile test           manual    --profile
access_key     ****************Y35Q shared-credentials-file    
secret_key     ****************lozd shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config

My file is called credentials in my .aws folder.... and not config..

**Comment by jamesls** [comment]
The `~/.aws/config` is primarily for backwards compatibility as well as configuration values that aren't credentials.  This is discussed in the config var topic guide (http://docs.aws.amazon.com/cli/latest/topic/config-vars.html).  You can also run `aws help config-vars` for more info.  

Could you let us know which doc you're referring to that mentions saving vars to `~/.aws/config`?  We'll get it updated.

**Comment by epinault** [comment]
yes on the README of this repo. See line that says

and place it in ~/.aws/config (or in %UserProfile%\.aws\config on Windows).


Also the "aws --profile 'profile test' configure list" is showing the incorrect file . (might be hardcoded or something because I don t have an .aws/config

**Comment by jamesls** [comment]
Thanks, we'll get the README updated.
