### ISSUE TITLE
cloud formations script and AWS CLI problem

### ISSUE THREAD

**Issue by aktarali** [aws/aws-cli#1881]
Hi;

I've got a cloud formation script. Using this json file I use the CLI tool to provide the values like so:

```
for nodes in mesos-master2;do 

/usr/bin/aws cloudformation create-stack --stack-name $nodes --template-body file:///home/centos/instance.json --parameters ParameterKey=DefaultChefServerValidatorName,ParameterValue=testlab-validator ParameterKey=DefaultAlarmSNSArn,ParameterValue=interKube ParameterKey=SecurityGroupIds,ParameterValue='sg-cc4b60a8\,sg-cc4b60a8' ParameterKey=DefaultDiskType,ParameterValue=standard ParameterKey=DefaultKeypair,ParameterValue=aws ParameterKey=DefaultRootDiskSize,ParameterValue=20 ParameterKey=DefaultVpcId,ParameterValue=vpc-f5f4cf90 ParameterKey=RoleEC2Ami,ParameterValue=ami-fb8c0888 ParameterKey=DefaultSIID,ParameterValue=iq000-$nodes ParameterKey=RoleInstanceType,ParameterValue=t2.medium ParameterKey=RoleSubnetId,ParameterValue=subnet-71bc9e28 --capabilities CAPABILITY_IAM; done
```
The problem I'm having is with this line: ParameterKey=SecurityGroupIds,ParameterValue='sg-cc4b60a8\,sg-cc4b60a8'

I cannot specify more than 1 security group. If I specify one, it works, but more than one it does not. In my json CF script, I've tried using the following ways:
method 1:

```
    "SecurityGroupIds": {
      "Description": "SG ID's for the default security group",
      "Type": "String",
      "ConstraintDescription": "must be list of EC2 security group ids"

```
Using this method, I've tried listing sg-xxxx,sgxxxx but it hasnt worked.

method 2:
      "Type": "List<AWS::EC2::SecurityGroup::Id>",
This doesn't work either.

PLEASE HELP. If someone can tell me what the json file should have and how the params should be called in the CLI that would be a great help.

**Comment by jamesls** [comment]
From what I can tell we're sending the parameters are being passed as expected when I try it:

```
  "Parameters.member.3.ParameterKey": "SecurityGroupIds",
  "Parameters.member.3.ParameterValue": "sg-cc4b60a8,sg-cc4b60a8",
```

From the CLI perspective it appears that the values are being sent as expected for `List<AWS::EC2::SecurityGroup::Id>`.  I would suggest asking on the [cloudformation forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) for more information.  There the cloudformation service team would be able to give you better guidance about why this isn't working.
