### ISSUE TITLE
Unable to describe network interface attribute

### ISSUE THREAD

**Issue by aaratn** [aws/aws-cli#1888]
I followed [this](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-network-interface-attribute.html) article to describe the network interface attribute for my ec2 instance from ec2 instance running ubuntu 14.04.

I ran below command:
`aws ec2 describe-network-interface-attribute --network-interface-id eni-686ea200 --attribute attachment`

and got this exception

> Unknown options: --attribute, attachment

I also tried to run below command

`aws ec2 describe-network-interface-attribute --network-interface-id eni-686ea200 --attachment`

and got below exception

>aws: error: argument --attachment: expected one argument`

This is my AWS CLI Version

>aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-48-generic

This is my operating system version

> Distributor ID: Ubuntu
>Description:    Ubuntu 14.04.4 LTS
>Release:        14.04
>Codename:       trusty

**Comment by JordonPhillips** [comment]
That CLI version is out of date, you'll need to update it. I imagine you're using the ubuntu repository version, which we don't maintain. [See here](http://docs.aws.amazon.com/cli/latest/userguide/installing.html). The current version of the CLI is 1.10.17
