### ISSUE TITLE
aws elasticbeanstalk create-environment allows creation of environments longer than allowed limit

### ISSUE THREAD

**Issue by moosamus** [aws/aws-cli#1891]
Version info: aws-cli 1.10.6, python 2.7.10

For example, the following succeeds:  

`aws elasticbeanstalk create-environment --environment-name somenamelongerthantwentythreecharacters --application-name my-app  `

**Comment by JordonPhillips** [comment]
What's the result when you run that? We don't validate length constraints locally, that's left up to the service.

**Comment by moosamus** [comment]
It returns an expected response: 

```
{
    "ApplicationName": "my-application", 
    "EnvironmentName": "an-incredibly-long-environment-name", 
    "Status": "Launching", 
    "EnvironmentId": "e-abcdefghij", 
    "SolutionStackName": "64bit Amazon Linux 2015.09 v2.0.7 running Docker 1.9.1", 
    "Health": "Grey", 
    "Tier": {
        "Version": " ", 
        "Type": "Standard", 
        "Name": "WebServer"
    }, 
    "DateUpdated": "2016-04-04T17:39:24.964Z", 
    "DateCreated": "2016-04-04T17:39:24.964Z"
}
```

Interestingly, however, when pushing my luck, I stumbled upon a client limit: 

`A client error (ValidationError) occurred when calling the CreateEnvironment operation: 1 validation error detected: Value 'this-is-an-incredibly-long-environment-name' at 'environmentName' failed to satisfy constraint: Member must have length less than or equal to 40`

**Comment by JordonPhillips** [comment]
Looks like a service documentation model issue, I'll make sure that gets updated. Thanks for reporting!
