### ISSUE TITLE
Piping to text: TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by rpbaptist** [aws/aws-cli#1898]
I was piping the output of `aws s3 ls` to a file and received this message:

`TypeError: encode() argument 1 must be string, not None`

After a search I solved it by setting `export PYTHONIOENCODING='utf-8'`

**Comment by jamesls** [comment]
The underlying issue has also been fixed via https://github.com/aws/aws-cli/pull/1844.  You'll no longer get the `TypeError` even when `PYTHONIOENCODING` is set.
