### ISSUE TITLE
How to add a new command?

### ISSUE THREAD

**Issue by amosshapira** [aws/aws-cli#190]
Hi,

I'd like to add a new command ("s3 sync" or just "sync") and found "examples/new_command.py" but don't understand how to follow it in order to add the new command.

Can you give me some pointers on where can I learn to add such a command?

Thanks.

**Comment by jamesls** [comment]
Sorry for the delay.  This isn't a publicly documented interface yet, but I'd check out the [commands.py](https://github.com/aws/aws-cli/blob/develop/awscli/customizations/commands.py) module.  There's several custom commands added in the `customizations/` folder with examples of custom commands.
