### ISSUE TITLE
list-alias for lambda version returns empty list

### ISSUE THREAD

**Issue by Lknechtli** [aws/aws-cli#1904]
Running `aws lambda list-aliases --function-name [name]` returns the list of all aliases for a given function [name], but specifying a version number a la `aws lambda list-aliases --function-name [name] --function-version [version]` always returns an empty list of aliases.  

This appears to be an issue with the endpoint, but I'm not sure what the right place to report this is.

**Comment by JordonPhillips** [comment]
The best place to report service-specific issues is the service forum. [Here](https://forums.aws.amazon.com/forum.jspa?forumID=186) is the link to the Lambda forum specifically.

**Comment by JordonPhillips** [comment]
Does it look like the CLI is passing the values along correctly? You can inspect the request if you add `--debug` to the end of your command.

**Comment by Lknechtli** [comment]
it does appear to be passing the values along correctly - I get the same error when making the request using boto3 in a python script. I'll see if I can get a solution at the forum you linked

**Comment by JordonPhillips** [comment]
Since it doesn't look like a CLI issue, I'm going to close out this issue. Feel free to update here with your findings!
