### ISSUE TITLE
What does pip install require sudo permissions?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#1923]
http://s.natalian.org/2016-04-18/pip-install.txt

Why is it trying to install into /usr/lib/python2.7 ? Isn't there some $USER local construct?

When I try sudo (which I really don't want to do), it still wants to put things into ~/.pip/cache. That is crazy.

**Comment by JordonPhillips** [comment]
pip may require sudo if you're trying to install on the system python. I would recommend asking about this on the [pip repository](https://github.com/pypa/pip), as this doesn't seem to be a CLI specific issue.

**Comment by kaihendry** [comment]
I think you should perhaps document the alternative of

    pip2 install --user awscli
