### ISSUE TITLE
Not properly outputting in MINGW

### ISSUE THREAD

**Issue by stramel** [aws/aws-cli#1925]
System: Windows 7 64bit

steps to reproduce:

1. Open mingw64 (git bash) 
2. Run `aws configure`
3. Observe no output
4. Hit enter 4 times
5. Observe output

It looks as if AWS CLI is thinking it is outputting text however it actually isn't.

![image](https://cloud.githubusercontent.com/assets/855184/14644114/86f4eb30-0616-11e6-835c-21cb94db9eb4.png)

**Comment by JordonPhillips** [comment]
Looks like the issue here is that MINGW doesn't refresh until stdout is flushed explicitly, whereas most terminal emulators will opt to display text as soon as possible. This shouldn't be too hard to fix.

**Comment by JordonPhillips** [comment]
In the meantime, you should be able to work around the issue by providing the environment variable `PYTHONUNBUFFERED=1`.

**Comment by stramel** [comment]
@JordonPhillips I put in my environment variables `PYTHONUNBUFFERED=1` and even tried exporting it `export PYTHONUNBUFFERED=1`. Checked with `echo $PYTHONUNBUFFERED` and got output of `1`. 

Still same issue. Not that my mingw64 was installed via GIT as the Git Bash terminal.

**Comment by JordonPhillips** [comment]
@stramel The fix will be out in the next release
