### ISSUE TITLE
key-pair from CLI doesn't appear in dashboard

### ISSUE THREAD

**Issue by SamuelMarks** [aws/aws-cli#1934]
```
$ aws --version
aws-cli/1.10.22 Python/2.7.11+ Linux/4.4.0-18-generic botocore/1.4.13
$ aws configure
AWS Access Key ID [****************OOOO]: 
AWS Secret Access Key [****************OOOO]: 
Default region name [ap-southeast-2]: 
Default output format [json]: 
$ aws ec2 create-key-pair --key-name foo
{
    "KeyMaterial": "<omitted>", 
    "KeyName": "foo", 
    "KeyFingerprint": "<omitted>"
}
```

But it doesn't appear here: https://ap-southeast-2.console.aws.amazon.com/ec2/v2/home?region=ap-southeast-2

**Comment by JordonPhillips** [comment]
Hmmm.... I am having difficulty reproducing. Can you still use that key from the CLI, or is it just not available in the console? Does it show up in `aws ec2 describe-key-pairs`?

**Comment by SamuelMarks** [comment]
There are different key-pairs shown in `aws ec2 describe-key-pairs` than in the web-interface.

Maybe they're associated with every region or something like that?

**Comment by JordonPhillips** [comment]
They are associated on a region by region basis. Are you logging into the console with the same credentials on the same account? I've had issues myself where I've left the console logged into my personal account, causing confusion when my instances aren't there.

**Comment by SamuelMarks** [comment]
Yes, same account in web-console as in CLI

**Comment by JordonPhillips** [comment]
If that's the case, I'm not sure what's happening. It could be permissions issues if you're using different roles for the cli vs the console, but it is not often that the CLI has a more permissive role than the console login. Right now it seems like the CLI is interacting properly with the service, so I think it might be a service/console issue. You can reach the service team via [their forum](). I'm going to close out the issue on this repo, but please feel free to come back to leave a comment if the service team is able solve your issue.
