### ISSUE TITLE
pip install awsebcli error

### ISSUE THREAD

**Issue by anubhaw2091** [aws/aws-cli#1936]
I am currently using python 3.4.3

When am trying `pip install awsebcli` am getting below error.

```
Command "C:\Python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\
\Users\\Anubhaw\\AppData\\Local\\Temp\\pip-build-8kpzrs_v\\pyyaml\\setup.py';exe
c(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n')
, __file__, 'exec'))" install --record C:\Users\Anubhaw\AppData\Local\Temp\pip-_
9x2n5hi-record\install-record.txt --single-version-externally-managed --compile"

failed with error code 1 in C:\Users\Anubhaw\AppData\Local\Temp\pip-build-8kpzrs_v\pyyaml\
```

I don't understand what's the problem. I even changed the permission of the python folder.

**Comment by JordonPhillips** [comment]
This is the repository for the generalized aws-cli, not the elasticbeanstalk cli. I recommend you ask in the [elasticbeanstalk forums](https://forums.aws.amazon.com/forum.jspa?forumID=86). That said, it looks like you may need to run the command with elevated permissions.
