### ISSUE TITLE
Support --help, and maybe -h, for fetching help on commands

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-cli#1937]
I've typed `aws something something --help` like a hundred times and been frustrated that I've had to recall that it's without the `--` every time. Nearly every CLI program supports `--help` so it's surprising that `aws` doesn't.

**Comment by JordonPhillips** [comment]
Duplicate of #303 / #576

**Comment by adamchainz** [comment]
Thanks, I couldn't find those after a five minute search
