### ISSUE TITLE
A client error (InvalidAccessKeyId): Uploading failing

### ISSUE THREAD

**Issue by mokshpooja** [aws/aws-cli#1946]
Hi Guys, 
I am new with this. Have big data that I need to periodically upload to s3. I am not using IAM roles yet, just using master. Wanted to get it working before changing to IAM roles.
I have both %userDir%/.aws/credentials and %userDir%/.aws/config files as below-
%userDir%/.aws/credentials-
```
[default]
aws_access_key_id=key1
aws_secret_access_key=pass1

```
%userDir%/.aws/config-
```
[default]
aws_access_key_id=key1
aws_secret_access_key=pass1
region=us-west-2
output=json
```
```
export AWS_CREDENTIALS_FILE=%userDir%/.aws/credentials
export AWS_CONFIG_FILE=%userDir%/.aws/config
```
I tried uploading only 1 file but I get-
`A client error (InvalidAccessKeyId) occurred when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.`

versions I am using- 
aws-cli/1.10.24 
Python/2.7.9 
Linux/3.13.0-48-generic botocore/1.4.15

**Comment by kyleknap** [comment]
A quick way to figure out what credentials are being used is by running: ``aws configure list``. That will show where the credentials are being pulled from in the CLI. Let us know if that helps you figure out your credentials issue.
