### ISSUE TITLE
No way to change S3 storage types with awscli

### ISSUE THREAD

**Issue by nkadel-skyhook** [aws/aws-cli#1949]
I've been re-arranging content, and would love to be able take content out of glaciered storage, and put other content into glaciered storage, from the aws cli. Unfortunately, I seem unable to do so.

I'm not comfortable writing this feature myself, but would be happy to help test it.

**Comment by kyleknap** [comment]
To take an object out of glacier storage class, you need to call S3's restore API: http://docs.aws.amazon.com/cli/latest/reference/s3api/restore-object.html. 

To put content as glacier storage class, there is no direct way to do it. You need to setup a policy on your bucket with the ``put-bucket-lifecycle-policy`` command: http://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-lifecycle-configuration.html using a rule that transitions objects to glacier (such as in its example).

**Comment by nkadel-skyhook** [comment]
Thanks, I was having some difficulty understanding that the documentation meant "use this command"

* aws s3api restore-object

rather than "s3api is a description of a category.
