### ISSUE TITLE
s3 sync command between buckets don't override cache-control headers

### ISSUE THREAD

**Issue by codename-** [aws/aws-cli#1953]
```sh
$ aws s3 sync ./local/files s3://remove/bucket/1 --cache-control "public, max-age=3600"
$ aws s3 sync s3://remote/bucket/1 s3://remove/bucket/2 --cache-control "private, no-cache"
```

After running above script, cache headers for files in bucket `remote/bucket/2` are equal to:
`public, max-age=3600`

Is this a know issue? Is there a way to fix it? Any workarounds?

**Comment by kyleknap** [comment]
So the ``sync`` command does not sync based on metadata like cache control. It only syncs based on the content of files by checking last modified and size of the file. Do the files that actually got copied over in the second sync have the correct cache control? I would only expect that the files that got copied over during the second sync would have this new cache control value. If that is not the case, could I get debug logs from the second sync you ran? You can do this by appending ``--debug`` to the command you ran.

**Comment by codename-** [comment]
Sorry for late reply... I'm sending logs for first and second upload, as well as screen shots. I hope it helps.

<img width="1421" alt="file 1" src="https://cloud.githubusercontent.com/assets/1577416/15475986/b29e5d3a-2104-11e6-9cbc-2dcdc2a93e7d.png">

<img width="1424" alt="file 2" src="https://cloud.githubusercontent.com/assets/1577416/15475987/b2a6d8b6-2104-11e6-8b26-ac216999c8b7.png">

[first.txt](https://github.com/aws/aws-cli/files/277753/first.txt)
[second.txt](https://github.com/aws/aws-cli/files/277755/second.txt)

**Comment by codename-** [comment]
@kyleknap, @jamesls - have someone looked at my post above?  Or you are not notified by posts in closed issues?

**Comment by agrawaltarun** [comment]
I also face similar issue, I believe aws cli need this functionality as we do not want to force copy all teh assets everytime to s3 just to update object metadata.
