### ISSUE TITLE
getting upgrades working on mac

### ISSUE THREAD

**Issue by foobar8675** [aws/aws-cli#1954]
To upgrade the awscli on my mac, an AWS support person pointed me to the commands

````
sudo pip install --upgrade pip
sudo pip install --upgrade --ignore-installed awscli
````

can the read me be updated to reflect that?

**Comment by kyleknap** [comment]
Does ``pip install --upgrade awscli`` not perform the upgrade for you because that works just fine for me on my mac and that is what is in the [README](https://github.com/aws/aws-cli/blob/develop/README.rst#installation)? Here is what I did:
```
$ aws --version
aws-cli/1.7.25 Python/2.7.10 Darwin/15.4.0

$ pip install --upgrade awscli

$ aws --version
aws-cli/1.10.26 Python/2.7.10 Darwin/15.4.0 botocore/1.4.17

```

**Comment by foobar8675** [comment]
no it did not work. i either got
```` 
OSError: [Errno 1] Operation not permitted: '/var/folders/dn/p7t_db8x7tx4d5ztwyfhlfl40000gn/T/pip-_Kl_sw-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
````

or after adding --ignore-installed

````
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.11-intel-2.7/check_libyaml.c -o build/temp.macosx-10.11-intel-2.7/check_libyaml.o
    build/temp.macosx-10.11-intel-2.7/check_libyaml.c:2:10: fatal error: 'yaml.h' file not found
    #include <yaml.h>
             ^
    1 error generated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    running install_lib
    copying build/lib.macosx-10.11-intel-2.7/yaml/__init__.py -> /Library/Python/2.7/site-packages/yaml
    error: could not delete '/Library/Python/2.7/site-packages/yaml/__init__.py': Permission denied
````

but after doing a sudo on it, it was fine.

**Comment by JordonPhillips** [comment]
Sounds like you're installing it on the system python, which requires sudo to use pip.

**Comment by kyleknap** [comment]
This looks like the same issue as this [larger thread](https://github.com/aws/aws-cli/issues/1522). In [our user guide](http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-with-pip), we have a snippet for this scenario with OSX that is similar that users have been doing in the other GitHub issue that I linked:
```
$ sudo pip install awscli --ignore-installed six
```
@foobar8675 Can you confirm the line above works for you?

I would be inclined to mention this line in our README given it is already in our user guide.

**Comment by foobar8675** [comment]
yes it did work. thanks! I was mainly focusing on the github readme page. maybe link to the user guide in the github readme?
