### ISSUE TITLE
Need "no quotes" string option for JMESPAth output

### ISSUE THREAD

**Issue by SteveALee** [aws/aws-cli#1961]
Is there a way to lose the quotes in returned string values?

In order to use output such as the ```IdentityPoolId``` from ```cognito-identity create-identity-pool``` on the command line the quotes need to me removed.

[JMSEPath jp](https://github.com/jmespath/jp) includes an ```-u/--unquoted``` option or we can set ```export JP_UNQUOTED=true```

neither work with AWS. Can you please implement?

**Comment by SteveALee** [comment]
For now I'm using

``` IDENTITY_POOL_ID="${IDENTITY_POOL_ID%\"}";IDENTITY_POOL_ID="${IDENTITY_POOL_ID#\"}" ```

**Comment by kyleknap** [comment]
You can do this now with the ``--output text`` option. For example, try something like this:
```
$ aws cognito-identity create-identity-pool --identity-pool-name foo --allow-unauthenticated-identities --query IdentityPoolId --output text
us-east-1:96339a84-0d20-4e67-9b87-fe1f1f854f00
```
It should output the id that you want without the quotes. Let us know if that helps.

**Comment by SteveALee** [comment]
AH, OK thanks will give it a go. I had assume the text output would be ALL the same info as in the json. Ie more than just the ID.

**Comment by JordonPhillips** [comment]
@SteveALee Correct, it shows all the same information.

**Comment by SteveALee** [comment]
Gotit --query IdentityPoolId filters even if not JSON output. Effectively -output text reformats the json output.

**Comment by SteveALee** [comment]
@JordonPhillips @kyleknap 

Yes ```--output text``` is perfect. I obviously made invalid assumptions about output formats and relation to the ```--query``` option. My bad. It turns out I even forgot to specify the output format at all. I don't see the default specified. I guessed JSON.

**Comment by nitrocode** [comment]
I know this is an old thread but it popped up on google so I thought I'd add to the conversation.

The `--output text` works for most use-cases but if any of the output contains multi line string data with `\n` chars, if you use `--output text`, you lose the new lines.

I use the following for multi line information.

- `sed` to remove the quotations
- `echo` to turn the `\n` chars into new lines

```sh
echo $(aws secretsmanager get-secret-value --secret-id my-client-pem --query SecretString | sed 's,",,g') > client.pem
```

with `jq` and its flag `-r` for raw, we can drop the `echo` and the `sed` command

```sh
aws secretsmanager get-secret-value --secret-id my-client-pem | jq -r '.SecretString' > client.pem
```

It would be nice if the awscli supported a native `-r` raw output like `jq` does.

**Comment by lvkins** [comment]
Be careful using `--output text` as it changes how `--query` operates, see: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side

> Important
> The output type you specify changes how the --query option operates:
> 
> If you specify --output text, the output is paginated before the --query filter is applied, and the AWS CLI runs the query once on each page of the output. Due to this, the query includes the first matching element on each page which can result in unexpected extra output. To additionally filter the output, you can use other command line tools such as head or tail.
> 
> If you specify --output json, --output yaml, or --output yaml-stream the output is completely processed as a single, native structure before the --query filter is applied. The AWS CLI runs the query only once against the entire structure, producing a filtered result that is then output.

You can can combine AWS cli command with `jq` in order to strip the double quotes:

`aws [...] --query 'yourItem' | jr -r`
