### ISSUE TITLE
doc/README.rst is inaccurate

### ISSUE THREAD

**Issue by elee** [aws/aws-cli#1964]
Fixed an inaccuracy in the doc README

https://github.com/aws/aws-cli/pull/1963

**Comment by kyleknap** [comment]
Thanks for the contribution. Just looked at the PR. Had a small comment but change looks good to me.

**Comment by elee** [comment]
fixed and rebased 🚀

**Comment by kyleknap** [comment]
Thanks again. Just merged it.
