### ISSUE TITLE
Unexpected behaviour: s3api put-bucket-notification-configuration deletes existing events

### ISSUE THREAD

**Issue by prad9** [aws/aws-cli#1974]
Hi there,

Trying to add new event notification to invoke lambda function for mybucket using cli commands. Event gets added to s3 successfully but removes all existing events which were configured before.

**Lambda permission: To allow s3 to invoke lambda**
command: `aws lambda add-permission --function-name MyTestLambda --statement-id 123--action "lambda:InvokeFunction" --principal s3.amazonaws.com --source-arn arn:aws:s3:::mytestbucket --source-account xxxxx --qualifier Dev`

Above adds permission policy successfully

**S3 event: Add event notification**
command: `aws --debug --color on s3api  put-bucket-notification-configuration --bucket mytestbucket --notification-configuration file://C:\testnotification.json`

testnofication.json:
```json
{
  "LambdaFunctionConfigurations": [
    {      
      "Id": "Notify_Test",
      "LambdaFunctionArn": "arn:aws:lambda:us-west-2:xxxxx:function:MyTestLambda:Dev",
      "Events": ["s3:ObjectCreated:*"],
      "Filter": {
        "Key": {
          "FilterRules": [
            {
              "Name": "prefix",
              "Value": "dev/test/"
            }
          ]
        }
      }
    }
  ]
}
```

Above command adds event successfully but deletes all existing events

I've updated my cli to latest version: aws-cli/1.10.28

It looks like similar issue: https://github.com/serverless/serverless/issues/652 but not clear whether serverless project is related to AWS CLI?

**Comment by JordonPhillips** [comment]
The [s3 docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html) are somewhat more clear on this point, but that is expected behavior. The PUT replaces the configuration, it does not PATCH it. You will need to retrieve the existing configuration, update it, and then send the new configuration.

**Comment by prad9** [comment]
Hi @JordonPhillips sorry for getting back on this bit late.

Problem with above approach is we will have to add permissions again from the script for the existing ones which would be tricky as we have hundreds of them. Is it possible to add PATCH command for S3 notifications? Thanks

**Comment by JordonPhillips** [comment]
@prad9 That would be something to ask for on the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24), so it could be made available to all S3 customers.

**Comment by aneeskA** [comment]
Hi

I am looking to do the same thing. Were you able to get clarity on this?

Thanks

**Comment by flybd5** [comment]
Kinda late but there is still no way to patch a notification event configuration. I'm not sure you can get the existing one either. You can only overwrite it, or you can delete it by specifying an empty configuration.

**Comment by liveHarshit** [comment]
Is patch available now?
