### ISSUE TITLE
Returned spot price history is limited to 1000 rows if the actual result set contains a little bit more

### ISSUE THREAD

**Issue by storozhilov-dnanexus** [aws/aws-cli#1978]
Hello to all,

if the actual amount of items in the spot price history is slightly greater than 1000 rows `aws ec2 describe-spot-price-history` returns only 1000 of them.

To reproduce the issue use [attached](https://github.com/aws/aws-cli/files/270785/test-aws-cli-spot-price-history-1000-rows-limit-issue.zip) Python script. It tries to fetch an extra items by issuing an additional `aws ec2 describe-spot-price-history` command with adjusted timeframe. Screenshot of the output is attached as well.

Attached script moves particular timeframe by some step to the past and calls `aws ec2 describe-spot-price-history` iteratively to find a suspicious result set having exactly 1000 rows. Then script checks that result set for correctness by trying to fetch an extra items (see above).

To accelerate testing adjust the value of `timeframe_minutes` variable to get approximately 1000 rows returned on each `aws ec2 describe-spot-price-history` call - you can check script's output first, then adjust value and run script again.

All the best,
Ilya

**Comment by JordonPhillips** [comment]
What version of the CLI are you using? Could you post the `--debug` logs from your command?

**Comment by storozhilov-dnanexus** [comment]
Hi Jordon,

thank you very much for fast response!

I've amended a testing script, which is in [attachment](https://github.com/aws/aws-cli/files/273157/test-aws-cli-spot-price-history-1000-rows-limit-issue.v2.zip) - it plays with the timeframe's width to identify a suspicious result set, so it should work faster. I've added a `--debug` param to `aws ec2 describe-spot-price-history` command. Script prints a result items CSV to `stdout`, where the last integer field is a flag, which is set to **1** if it's an extra item (fetched using an extra call to `aws ec2 describe-spot-price-history` command).

> What version of the CLI are you using?

I'm using **aws-cli/1.10.28 Python/2.7.3 Linux/3.2.0-98-virtual botocore/1.4.20** version of aws-cli.

> Could you post the `--debug` logs from your command?

`stdout` and `stderr` of my script are in the [attachment](https://github.com/aws/aws-cli/files/273157/test-aws-cli-spot-price-history-1000-rows-limit-issue.v2.zip) as well. Result items CSV looks good - extra items seems to be correct, so they should be in the primary result set.

Note, that extra items (but not **only** extra items) has a timestamp, which does not belong to the requested timeframe - it's earlier than a start date, but the price was actual for the beginning of the timeframe so it's correct to have that in the result set.

All the best,
Ilya

**Comment by jamesls** [comment]
Thanks for the debug scripts/output.  I've gone through the code and see the issue you're talking about.  The CLI appears to be passing the correct arguments (in terms of start/end time) to the EC2 API, and the results are what's returned from the EC2 service.

At this point, I don't think there's anything the CLI can do on our end.  I'd suggest contacting the EC2 team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) and see if they can add any additional insight as to why they're API's returning the data you're seeing.

Let's move this over to the AWS forums.  I'm going to go and close out this issue here, let me know if I've missed anything.

**Comment by storozhilov-dnanexus** [comment]
Hi @jamesls ,

thank you very much for your participation and effort! I will send my findings to the EC2 team using forums.

All the best,
Ilya
