### ISSUE TITLE
create-user-pool command missing

### ISSUE THREAD

**Issue by mikedizon** [aws/aws-cli#1979]
Seems that the create-user-pool command referenced in this blog post is missing.

http://docs.aws.amazon.com/cognito/latest/developerguide/setting-up-cognito-user-identity-pools.html

Am I looking in the wrong place?

**Comment by JordonPhillips** [comment]
I believe the correct command is `create-identity-pool`. I'll let the service team know to update their docs.

**Comment by JordonPhillips** [comment]
The service docs have been fixed. Thanks again!
