### ISSUE TITLE
[doc]route53 create-health-check API doc bug

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#1986]
The CLI doc's description says

```
To create a new health check, send a POST request to the /*Route 53 API version* /healthcheck resource.
```

http://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHealthCheck.html

But the `/*Route 53 API version* / ` part should read `/2013-04-01/` as in the API reference doc

```
To create a new health check, send a POST request to the /2013-04-01/healthcheck resource. 
```
http://docs.aws.amazon.com/cli/latest/reference/route53/create-health-check.html

It might be a rendering bug.

**Comment by JordonPhillips** [comment]
It's not a rendering bug, that's how it is presented in the [doc model](https://github.com/boto/botocore/blob/develop/botocore/data/route53/2013-04-01/service-2.json#L94). I think the intent is that it applies to any given api version. That said, we currently only ship [one api version](https://github.com/boto/botocore/tree/develop/botocore/data/route53), so I think it would make more sense to be more precise. Thanks for reporting!

**Comment by JordonPhillips** [comment]
So I talked to the service team about this. While we only ship one version in boto/CLI, there are multiple extant versions. They would rather not blow that bit away if customers using older versions see it. The service docs being different is a problem they are going to work on.

With that in mind, I'm going to close out this issue. I'll re-open if the service team changes their mind.

Thanks for the report!
