### ISSUE TITLE
support for ModifyDBClusterSnapshotAttribute

### ISSUE THREAD

**Issue by zactimeinc** [aws/aws-cli#1987]
As directed on http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ShareSnapshot.html, need to use ModifyDBClusterSnapshotAttribute action to share a db cluster snapshot.  Can support for it be added to aws-cli?

**Comment by jamesls** [comment]
Marking as api-update.  We should be able to get that updated.  Thanks for letting us know.

**Comment by zactimeinc** [comment]
I think this API endpoint (http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBClusterSnapshotAttribute.html)
is missing in the JSON blueprint for RDS, as suggested here (aws/aws-sdk-go#694).
Could updating to the latest JSON blueprint for RDS solve this issue?

**Comment by jamesls** [comment]
Now available in the latest version of the CLI: http://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-cluster-snapshot-attribute.html
