### ISSUE TITLE
feature request: it would be nice to have the ability to sync buckets between aws regions where the bucket owners are different accounts

### ISSUE THREAD

**Issue by JoeNunnelley** [aws/aws-cli#1989]
aws-cli/1.10.33 Python/2.7.10 Darwin/15.5.0 botocore/1.4.23

problem:  I need to be able to backup file assets from S3 to a second environment for a variety of reasons.  I want assetA in an environment 1 bucket to be synched to an environment 2 bucket and I want to use the aws cli to do it.  This does not appear possible when each environment I use has different credentials (segmented due to security requirements).  

what I see:
aws s3 sync s3://bucketA/file s3://bucketB/file --source-region us-west-2 --region us-east-1 --profile company-production
A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
Completed 1 part(s) with ... file(s) remaining

seems like we should be able to do the following:
aws s3 sync s3://bucketA/file s3://bucketB/file --source-region us-west-2 --region us-east-1 --source-profile company-production --profile company-rc

we use credentials files in /.aws that contain multiple accounts (1 for each environment).  It makes it hard for me to move assets between environments with the CLI.  As long as I have the correct credentials for both environments, I should be able to do this.

**Comment by kyleknap** [comment]
Makes sense. Labeling it as a feature request. Also have you considered setting up a bucket policy to grant the account for ``company-production`` to list objects owned by profile ``company-rc``?

**Comment by JoeNunnelley** [comment]
I have. However, that would be a change to our infrastructure that would allow other services that live in environment ```company-production``` to have access to that ```company-rc``` bucket which is something we wish to avoid managing and/or regulating. Having the CLI be able to discretely access both resources using existing user/service credentials mechanisms without having to modify the bucket access security settings seems preferable.

**Comment by nkadel-skyhook** [comment]
I don't see how this could possibly work without an intermediate transfer location, somewhere that the first set of credentials could write to, and the second set of credentials could read from.

**Comment by kyleknap** [comment]
It would work because under the hood we would create a new client to list the object for cross region bucket transfers and in this client we would just use a different profile to create the client.

**Comment by kyleknap** [comment]
Actually now that I think of it specifically for the copy object. The creds for the destination must have permissions to copy objects from the source. I am not sure if this is feasible to do this. There is no notion of granting temporary permissions to copy from a source to a destination. Permissions need to be granted.
