### ISSUE TITLE
ec2 request returns [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by seattledeveloper** [aws/aws-cli#1991]
Hello,

When attempting to execute the following command (note that I have obfuscated real volume id and description):

`aws ec2 create-snapshot --volume-id vol-99999999 --description "description"`

I receive the following error:

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

Interestingly, I am able to execute this with no issues on a different client account within AWS.

I have compared the 2 servers, and the version information and installed packages are virtually identical:

```
[root@admin .aws]# aws --version
aws-cli/1.10.8 Python/2.7.10 Linux/4.4.10-22.54.amzn1.x86_64 botocore/1.3.30

[root@admin .aws]# uname -a
Linux admin.xxxxxxxxxxx.com 4.4.10-22.54.amzn1.x86_64 #1 SMP Tue May 17 22:45:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@admin .aws]# yum list *certifi*
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
ca-certificates.noarch                                     2015.2.6-65.0.1.15.amzn1                                    @amzn-updates
Available Packages
python26-certifi.noarch                                    0.0.8-3.7.amzn1                                             amzn-main
python27-certifi.noarch                                    0.0.8-3.7.amzn1                                             amzn-main
```

I have verified that if I use the --no-verify-ssl flag that I am able to successfully create a snapshot, so I believe all the authentication has been set up correctly.

Attached is the full debug output.

[aws ec2 error.txt](https://github.com/aws/aws-cli/files/284898/aws.ec2.error.txt)

Thanks in advance!

**Comment by jamesls** [comment]
Does this work if you uninstall `python27-certifi`?  Botocore will fall back to its bundled certs if certifi is not installed, so it'd be helpful to know if the issue is with certifi.

**Comment by seattledeveloper** [comment]
`python27-certifi` is not installed -- it's listed under 'Available Packages'

**Comment by jamesls** [comment]
Sorry, I missed that.  There's a couple of other values that can influence which CA bundle is chosen.  I want to make sure that the issue isn't due to using different CA bundles than what's in botocore.  Do you have:

a) the AWS_CA_BUNDLE environment variable set?
b) A `ca_bundle` value set in your `~/.aws/config` file?

**Comment by seattledeveloper** [comment]
Neither of these items is set on the server with the issue.  But the interesting thing is that neither of these are set on the server where everything is working fine.

That's been the tough part for me to try to track this down.  Working fine on a server with (seemingly) all the same settings as the one that is failing.  The only difference I have found so far is that `aws-apitools.rds` is installed on the server _without_ the issue, and on the server _with_ the issue.

**Comment by jamesls** [comment]
Are the two systems running the same AMI as well?

It could be a difference in the OS system certs.

**Comment by seattledeveloper** [comment]
If you mean does the version match (with `uname -a`), then yes, they are identical.

However, one thing I just thought of is that the one with the issue was launched in Feb 2015. The one without the issue was lauched earlier this month.  Both servers are fully patched.

**Comment by jamesls** [comment]
I think that could influence things.  In particular, if any of the files from the output of running `python -c "import ssl; print ssl.get_default_verify_paths()"` are different between the two systems, that could explain why there's a difference in ssl cert behavior.

**Comment by seattledeveloper** [comment]
That's the issue!

Output from "good" server:

`DefaultVerifyPaths(cafile='/etc/pki/tls/cert.pem', capath='/etc/pki/tls/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/etc/pki/tls/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/etc/pki/tls/certs')`

Output from "bad" server:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_default_verify_paths'
```

My only remaining question is how to "fix" it.

**Comment by jamesls** [comment]
That would seem to suggest that they're actually running different versions of python.  Would you mind double checking that the python version is the same on each machine?

**Comment by seattledeveloper** [comment]
Different.  Working machine is 2.7.10.  Non-working machine is 2.6.9.  What's the best practice for upgrading?  There are a lot of different approaches mentioned on the web.  What the "easiest" in your opinion.  We pretty much exclusively use yum for installs and updates.

**Comment by seattledeveloper** [comment]
OK.  So this seems deeper than it originally appeared.

I change the symlinks in /etc/alternative from:

```
lrwxrwxrwx 1 root root 18 Mar  7 19:05 python -> /usr/bin/python2.6
lrwxrwxrwx 1 root root 34 Mar  7 19:05 python.1.gz -> /usr/share/man/man1/python2.6.1.gz
```

To:

```
lrwxrwxrwx 1 root root 18 Apr 29 16:58 python -> /usr/bin/python2.7
lrwxrwxrwx 1 root root 34 Apr 29 16:58 python.1.gz -> /usr/share/man/man1/python2.7.1.gz
lrwxrwxrwx 1 root root 25 Apr 29 16:58 python-config -> /usr/bin/python2.7-config
```

And rebooted the server just for good measure.  Python version now showing 2.7.10.  Still getting same error:

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

Thoughts?

**Comment by jamesls** [comment]
2.7.1 or 2.7.10?  I'm basing this just on your output that has the line:

```
lrwxrwxrwx 1 root root 34 Apr 29 16:58 python.1.gz -> /usr/share/man/man1/python2.7.1.gz
```

**Comment by seattledeveloper** [comment]
I just mimicked the setup that was on the working server.  When I do `python -V`, I get `Python 2.7.10`.

**Comment by seattledeveloper** [comment]
I found the issue.  The ca-bundle.crt file was outdated.  I updated to the latest and now all is working great.  Thanks for all your assistance in leading me in the right direction.  I am hopeful that others with this same issue will be able to find this page.  Cheers1
