### ISSUE TITLE
SNS invoke lambda doesnt invoke lambda when subscribed from cli

### ISSUE THREAD

**Issue by prad9** [aws/aws-cli#1996]
Hi there. 

Trying to invoke lambda from SNS. When i add subscription from console it works fine but when i do from cli commands nothing happens. 

Here are my setup commands:
**Add permission to lambda:**
aws lambda add-permission --function-name TestLambda --qualifier Dev --statement-id 123Test --action lambda:invokefunction --principal sns.amazonaws.com --source-arn arn:aws:sns:us-west-2:222333444:TestTopic --source-account 222333444
**Add lambda subscription**
aws sns subscribe --topic-arn arn:aws:sns:us-west-2:222333444:TestTopic --protocol lambda --notification-endpoint arn:aws:lambda:us-west-2:222333444:function:TestLambda:Dev

Also tried adding SNS permission (refer below) but no luck

aws sns add-permission --topic-arn "arn:aws:sns:us-west-2:222333444:TestTopic" --label "Testlabel" --aws-account-id "222333444" --action-name "Receive" "Subscribe"

Once executed i can see subscription added to SNS properly and eventsource added to lambda but lambda doesnt get triggered when topic is sent?

Order executed:
1. Added SNS permission
2. Added lambda permission
3. Added subscription to SNS

AWS CLI version: aws-cli/1.10.34 Python/3.4.3 Windows/7 botocore/1.4.24

**Comment by prad9** [comment]
Also tried adding SNS permission (refer below) but no luck

aws sns add-permission --topic-arn "arn:aws:sns:us-west-2:222333444:TestTopic" --label "Testlabel" --aws-account-id "222333444" --action-name "Receive" "Subscribe"

**Comment by kyleknap** [comment]
Yeah I am not sure why that may be happening. Your logic seems to be on the right page to me. I have you tried asking on the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) to see if you are missing anything? That would probably be better to figure what steps need to be taken and what parameters need to be passed to get it to work.

Also, one trick I sometimes do to figure out what I may be doing differently than the console is: First, set up everything in the console and then use the CLI to describe those resources to see how they are configured and work from there in terms of what parameters I need to pass to the CLI.

**Comment by prad9** [comment]
Thanks for feedback @kyleknap. I will recheck the configuration and will get back to you.

**Comment by prad9** [comment]
Hi @kyleknap. I did make sure that there is no difference in what i see after configuring from console vs configuring from CLI. They look same but cli configuration seems to have no effect (Topic doesnt invoke lambda)

**Comment by prad9** [comment]
@kyleknap: Found the problem. Once SNS is subscribed to lambda from cli the state of event source under lambda is setting as Disabled. I assume when it is subscribed the default state should be Enabled. After updating state to Enabled from lambda console it is working as expected.

New question: Is there a way to set this state of event source to enabled from CLI? I've tried to use update-event-source-mapping command but one of the parameter is UUID which i'm not sure how to get it? My attempt to get the UUID was to run the command  list-event-source-mappings which returns me empty array
{
    "EventSourceMappings": []
}

So what is the alternative for this? I know we can achieve this by updating from console manually but it would be long time job as we use AWS for all integration projects

**Comment by jamesls** [comment]
Not sure, I would expect `list-event-source-mappings` to return this information.  The CLI is just exposing the APIs provided by the lambda service.

For API questions like this, the service team are the best people to answer these questions.  Let's move this question over to the [AWS Lambda forums](https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0).

**Comment by prad9** [comment]
Thanks James.

Added to forum. Been waiting for so long seems service team is so busy?
https://forums.aws.amazon.com/thread.jspa?threadID=233425&tstart=0
https://forums.aws.amazon.com/thread.jspa?threadID=233042&tstart=0

**Comment by kalpatel01** [comment]
[with-sns-create-x-account-permissions](https://docs.aws.amazon.com/lambda/latest/dg/with-sns-create-x-account-permissions.html)

"Do not use the --source-account parameter to add a source account to the Lambda policy when adding the policy. Source account is not supported for Amazon SNS event sources and will result in access being denied. This has no security impact as the source account is included in the source ARN."
