### ISSUE TITLE
rds describe-reserved-db-instances-offerings --product-description fails for postgresql

### ISSUE THREAD

**Issue by lphilps** [aws/aws-cli#1997]
Using the latest version of the aws command line API:

````
aws-cli/1.10.34 Python/2.7.10 Darwin/15.5.0 botocore/1.4.24
````

The following command returns no offerings even though offerings exist:

````
aws rds describe-reserved-db-instances-offerings --product-description postgresql
````

the command works just fine, and returns offerings, if you replace postgresql with mysql, and if the --product-description argument is removed entirely,

````
aws rds describe-reserved-db-instances-offerings
````

lots of offerings are returned, many of them that contain "postgresql" in the ProductDescription field.

**Comment by kyleknap** [comment]
Yeah I am seeing that as well. I am not sure why that would be happening. I wonder if a different value is needed to get the postgresql instance offerings. I would recommend asking the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=60) about this.

The other option that you could do is client side filtering with the ``--query`` argument. So something like this:
```
$ aws rds describe-reserved-db-instances-offerings --query 'ReservedDBInstancesOfferings[?ProductDescription==`postgresql`]'
```
The downside with this though is that the CLI is still receiving all of the offerings it is just only showing the ones that match postgresql. Let us know if you have anymore questions.

**Comment by lphilps** [comment]
Thanks for the response Kyle.  Good to know it's not just me seeing this. :-)  I took your advice and just opened a forum thread regarding this:

https://forums.aws.amazon.com/thread.jspa?threadID=232902

**Comment by jamesls** [comment]
Sounds good, closing out issue.
