### ISSUE TITLE
Feature: Support for prefix in s3 sync command.

### ISSUE THREAD

**Issue by zerthimon** [aws/aws-cli#1999]
It would be nice to have an option to specify a remote directory prefix when doing sync with s3 bucket, so the source tree ends up in the bucket under bucket/[prefix]/ instead of bucket/

In my use case, I want to mirror (sync with --delete) local backup directories from several hosts to s3 using aws s3 sync command.
Currently, I have to create a bucket for each host. This feature will allow me to have one bucket for all backups from all hosts with hostnames as prefixes eg:
backup-bucket/hostname1-prefix/backuptree
backup-bucket/hostname2-prefix/backuptree
backup-bucket/hostname3-prefix/backuptree
...

**Comment by nkadel-skyhook** [comment]
Why doesn't it work to do:
    aws s3 sync --exact-timestamps dirname/ s3://bucket/dirname1/
    aws s3 sync --exact-timestamps dirname2/ s3://bucket/dirname2/
    aws s3 sync --exact-timestamps dirname3/ s3://bucket/dirname3/

**Comment by zerthimon** [comment]
@nkadel-skyhook yeah, that works for me. Thanks.

Closing as irrelevant.
