### ISSUE TITLE
Query Kinesis stream ARN in text mode

### ISSUE THREAD

**Issue by majidfn** [aws/aws-cli#2001]
Hi,

The following command gives back the Stream ARN: 

```
$ aws kinesis describe-stream --stream-name $STREAM_NAME --query "StreamDescription.StreamARN"
"arn:aws:kinesis:us-east-1:44444444444:stream/something_something-something"
```

But if you specify output to be `text` (to avoid the double quoted returned result), it gives back nothing.

```
$ aws kinesis describe-stream --stream-name $STREAM_NAME --query "StreamDescription.StreamARN" --output text
None
```

**Comment by jamesls** [comment]
Looks like a pagination bug to me.  In the meantime, to workaround the issue, you can add `--no-paginate`, which returns the stream arn without quotes when using `--output text`.

**Comment by andreineculau** [comment]
Bumped into the same problem! Bump

**Comment by stobrien89** [comment]
Tested in v1 `1.18.213` and v2 `2.1.34` and it appears this bug has been fixed in recent releases.  Let us know if you're still having an issue!
