### ISSUE TITLE
s3 sync > add a sync strategy to compare etags instead of timestamp / filesize

### ISSUE THREAD

**Issue by oodavid** [aws/aws-cli#2006]
== Use-Case

Static-Site-Generators _(jekyll, hugo etc.)_ have a tendency to rebuild **every** file even if there's no change. As such the timestamp is updated. This makes the `s3 sync` badly optimised to synchronise sites generated in this way.

== Proposal

Add a new sync strategy that compares etags.

**Comment by JordonPhillips** [comment]
This potential feature is discussed in #599. We would need to cache etags since we can't reliably generate them ourselves.
