### ISSUE TITLE
Unable to download complete RDS log files

### ISSUE THREAD

**Issue by jlintz** [aws/aws-cli#2008]
`aws rds download-db-log-file-portion --db-instance-identifier DB --log-file-name error/postgresql.log.2016-06-08-14 --starting-token 0 --output text > postgresql.log.2016-06-08-14`

Only ends up with a 14MB file when `describe-db-log-files` shows `209037009` bytes.

I've tried with `--max-items 999999`.

Output from version
```
aws --version
aws-cli/1.10.36 Python/2.7.11 Darwin/15.5.0 botocore/1.4.26
```

The last few lines when running with `--debug`

```
</LogFileData>
    <Marker>17:13387550</Marker>
  </DownloadDBLogFilePortionResult>
  <ResponseMetadata>
    <RequestId>d770ea91-2d94-11e6-8f7b-b370c9692eb4</RequestId>
  </ResponseMetadata>
</DownloadDBLogFilePortionResponse>

2016-06-08 12:19:59,227 - MainThread - botocore.hooks - DEBUG - Event needs-retry.rds.DownloadDBLogFilePortion: calling handler <botocore.retryhandler.RetryHandler object at 0x106b97d90>
2016-06-08 12:19:59,227 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-06-08 12:19:59,227 - MainThread - botocore.hooks - DEBUG - Event after-call.rds.DownloadDBLogFilePortion: calling handler <awscli.errorhandler.ErrorHandler object at 0x106571650>
2016-06-08 12:19:59,227 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 200
```

I've been able to reproduce this fairly reliably with all our RDS log files, getting vary success on how far into the file the download finishes.  I'm able to download the file fine from the AWS console.

**Comment by JordonPhillips** [comment]
Could you post a more complete debug log? That shows one successful response, but I bet there's something else going on.

**Comment by jlintz** [comment]
@JordonPhillips got a response from support, apparently there's currently an issue on Amazon's side of things

```
After doing some research on our internal knowledge base, I am actually seeing some similar issues regarding the log files were downloaded incomplete. There is a fix on the way but at this time I cannot give an ETA for it. I apologize for the inconvenience caused. For now, a possible workaround is to specify another variable in the command --max-items 99999999....
```

**Comment by JordonPhillips** [comment]
@jlintz Thanks for updating! I'm gonna close out the issue here since it doesn't seem to be our issue. Feel free to update here if another issue arises, or you get confirmation that the bug is fixed.
