### ISSUE TITLE
aws api / aws cli to get list of instances

### ISSUE THREAD

**Issue by amy201988** [aws/aws-cli#2012]
I have a below task to do . Can anyone suggest me is it doable?

1) Use the AWS API to gather information about the env
2) E-mail the tagged account the following information
stack name, state, age 
instances state, age, size
DB state, age, size
3) run weekly 
4) Must be able to work on multiple AWS accounts

**Comment by JordonPhillips** [comment]
You can absolutely query EC2 instances. If you have an email address tagged, you can use SES to send an arbitrary message. Lambda functions can be run at regular intervals, or you could setup crontab on EC2. Nothing about that should be tied to an account so long as you have permission configured properly.

**Comment by amy201988** [comment]
can you please give me a sample code for above as i am new to this aws

**Comment by JordonPhillips** [comment]
Unfortunately, I'm not a service expert, so I would suggest you go have a look at their docs to see how you might accomplish a particular task.

**Comment by jamesls** [comment]
Here's an example to get you started.  It lists all of your instances, their states, and their launch times:

```
aws ec2 describe-instances --query 'Reservations[].Instances[].[State.Name, LaunchTime]'
```

I'd suggest either reaching to specific service teams on their forums, or reaching out on [gitter](https://gitter.im/aws/aws-cli) if you have any additional questions.
