### ISSUE TITLE
Where to find "aws efs"?

### ISSUE THREAD

**Issue by MasterJames** [aws/aws-cli#2020]
I'm looking at this...
http://docs.aws.amazon.com/cli/latest/reference/efs/index.html
and wondering where is this located in github? aws aws-cli?

**Comment by JordonPhillips** [comment]
The CLI wraps [botocore](https://github.com/boto/botocore), which generates service clients based on service json definitions that we generate upstream. So there is no code specific to EFS, if that's what you're looking for.

**Comment by JordonPhillips** [comment]
Let's continue this discussion on [gitter](https://gitter.im/aws/aws-cli).

**Comment by MasterJames** [comment]
gitter? oh okay cool much better. I'll check it out.
