### ISSUE TITLE
Problem with --recursive and protected subpaths

### ISSUE THREAD

**Issue by vide** [aws/aws-cli#2025]
Hello

I have a bucket my-bucket with an IAM access policy like this:
```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::000000000000:user/my_user"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my-bucket"
        },
        {
            "Sid": "AllowPublicReadOfSecretFolfer",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::my-bucket/SECRET-PATH/*"
        },
        {
            "Sid": "AllowListingOfSecretFolder",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my-bucket",
            "Condition": {
                "StringLike": {
                    "s3:prefix": "SECRET-PATH/*",
                    "s3:delimiter": "/"
                }
            }
        },
        {
            "Sid": "PermitWriteAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::000000000000:user/my_user"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}
```

and when I try to recursively list (or copy, or remove) a path behind the protected SECRET-PATH token, I always get an access denied error. Other S3 clients like for example CyberDuck have no problem listing the contents behind the secret token without authentication (given that you know the secret token, obviously)

Here is the command line I'm using:
```
$ aws --no-sign-request s3 ls --recursive  s3://my-bucket/SECRET-PATH/

A client error (AccessDenied) occurred when calling the ListObjects operation: Access Denied
```

Is this a bug or is it something wrong in my IAM code? If so, why other clients work as expected (by me, at least)?
Thanks!

**Comment by vide** [comment]
Forgot to mention that  I'm using Ubuntu 16.04 with this awscli: `aws-cli/1.10.1 Python/3.5.1+ Linux/4.7.0-040700rc3-generic botocore/1.3.23` and that copying/listing single files behind SECRET_PATH works smoothly.

**Comment by JordonPhillips** [comment]
You are using `--no-sign-request`, but your policy specifies that requests must be signed (`"Principle": {"AWS": "*"}`)

**Comment by jamesls** [comment]
Closing out issue.  Let us know if you're still seeing issues.  You can also chat with us on [gitter](https://gitter.im/aws/aws-cli) and we can try to help troubleshoot.
