### ISSUE TITLE
Spot Block for EMR?

### ISSUE THREAD

**Issue by sjlee86** [aws/aws-cli#2032]
Hi, is spot instance with defined-duration available on EMR?
If so it would be nice to have an option in aws-cli to bring them up when creating-cluster.

**Comment by kyleknap** [comment]
I would recommend asking if the feature is available in the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=52) as they will be more knowledgeable about EMR's capabilities.

If it is available through EMR's API, We could possibly add it to the high level ``create-cluster`` command if it makes sense.

Closing for now. If it is available through the API, we can reopen this as a feature request.
