### ISSUE TITLE
Lambda - update-function-code -- Can't Publish Description

### ISSUE THREAD

**Issue by mark-keaton** [aws/aws-cli#2033]
It would be nice when publishing a new version of a Lambda to be able to set the description (much like a Git commit message).

It's already a functionality on the website.

**Comment by JordonPhillips** [comment]
Modifying the description is done with `update-function-configuration`. If you would like the ability to do both at once, your best bet is to request this feature on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=186).

**Comment by mark-keaton** [comment]
I'll ask on the forums then. Thanks. This seems like a feature that should be available during update-function-code.

**Comment by jamesls** [comment]
Closing, marking as move-to-forums.
