### ISSUE TITLE
[aws deploy push] Destination bundle type does not match extension

### ISSUE THREAD

**Issue by pulkitjalan** [aws/aws-cli#2036]
When specifying a destination with a suffix of ".zip" or ".tar" or ".tar.gz" for use with the `aws deploy push` command the resulting bundle is always only zipped.

```
$ aws deploy push --application-name test --s3-location s3://$AWS_DEPLOY_BUCKET/test/latest.tar --no-ignore-hidden-files --source .
To deploy with this revision, run:
aws deploy create-deployment --application-name test --s3-location bucket=BUCKET_NAME,key=test/latest.tar,bundleType=zip,eTag=... --deployment-group-name <deployment-group-name> --deployment-config-name <deployment-config-name> --description <description>
```

I downloaded and check the file it come back as a zip file.

```
$ file latest.tar 
latest.tar: Zip archive data, at least v2.0 to extract
```

**Comment by pulkitjalan** [comment]
Thanks for making the docs clearer on this. However CodeDeploy supports zip and tar, shouldn't the cli?

**Comment by bgupta** [comment]
@JordonPhillips Would it be out of line to support bundleType as an option for push since it seems create-deployment already supports it? (Default to zip is fine.)
