### ISSUE TITLE
No ssl? 

### ISSUE THREAD

**Issue by dbrb2** [aws/aws-cli#2054]
Is there a way to upload a file to S3 using aws-cli entirely over http - without any SSL...?

**Comment by jamesls** [comment]
You have to specify the `--endpoint-url` explicitly with `http://` instead of `https://`.  For example `aws s3 cp s3://bucket/key --endpoint-url http://s3.amazonaws.com/`.  Of if your bucket is in us-west-2: `--endpoint-url http://s3-us-west-2.amazonaws.com/`.
