### ISSUE TITLE
Using via ntlm proxy? 

### ISSUE THREAD

**Issue by dbrb2** [aws/aws-cli#2058]
This might be expected behaviour rather than an issue - since I see that here: 

http://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html

It states that NTLM proxies are not supported - however it's not clear why this would be, since as far as I can tell, by using cntlmn:

http://cntlm.sourceforge.net/

then the proxy should appear as a basic http proxy. It would be interestinf to understand either way...

When uploading to S3 using a standard HTTP proxy, tshark shows me something similar to:

-> HTTP 638 PUT http://s3-eu-west-xxxxxx.jpg HTTP/1.1 
-> HTTP 115 HTTP/1.1 100 Continue 
-> HTTP 600 HTTP/1.1 200 OK

And all works fine

When I do the same thing via an http proxy using cntlm proxy (which itself uses NTLM), I get:

-> HTTP 727 PUT http://s3-eu-west-xxxxxx.jpg HTTP/1.1 , NTLMSSP_NEGOTIATE
-> HTTP 1052 HTTP/1.1 407 Proxy Authorization Required , NTLMSSP_CHALLENGE (text/html)
-> HTTP 907 PUT http://s3-eu-west-xxxxxx.jpg HTTP/1.1 , NTLMSSP_AUTH, User: 
-> HTTP 128 HTTP/1.1 100 Continue 
-> HTTP 509 HTTP/1.1 200 OK

On the face of it, from that trace, all looks good - however in this second case, although the upload appears to succeed, aws returns:

upload failed: xxxx.jpg to s3://xxxx Connection was closed before we received a valid response from endpoint URL

It looks from the above that a response is received...
Any ideas as to why this is failing...?

**Comment by kyleknap** [comment]
Looks like a similar issue the one you opened in [boto3](https://github.com/boto/boto3/issues/709). Let's track the issue there as the logic that is being used is in botocore which is the same library that the CLI and boto3 uses and the causes for your issue would be the same for both libraries.
