### ISSUE TITLE
Lots of wasted whitespace in aws help

### ISSUE THREAD

**Issue by pcgeek86** [aws/aws-cli#2061]
The AWS CLI uses up a lot of whitespace, which makes it challenging to read the built-in help. Any chance of improving this?

![image](https://cloud.githubusercontent.com/assets/466713/16745713/4de119dc-4774-11e6-89cc-b30fb1c2f1b3.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by kyleknap** [comment]
Is the whitespace you are referring to the newlines used in the list of commands? Or is it something else?

**Comment by pcgeek86** [comment]
@kyleknap yeah, I'm referring to the new lines used in between commands. It doesn't read very well in the console. Requires a lot of scrolling. Maybe it could detect the console's horizontal size and display multiple columns? I don't have a particular preference, but I think there's some opportunity for display improvement. Any thoughts?

**Comment by pcgeek86** [comment]
Maybe consider modeling it after the Azure command line built-in help. They space things out at the beginning, to make it easy for beginners, but then when they dive into the platform features, they compress it down to single lines. Here's a screenshot.

![image](https://cloud.githubusercontent.com/assets/466713/16784845/010402a8-4848-11e6-81dc-6d30677bbd23.png)

**Comment by kyleknap** [comment]
I think we are going to stick with using newlines between options/parameters. With the number of AWS services and APIs the CLI supports, I feel like it would be harder to read if they were not separated by newlines and clumped together instead. Furthermore, it is pretty common in other command line utility man pages to use newlines between commands (i.e. ``git``, ``brew``). Closing issue.
