### ISSUE TITLE
output text with query, unable to retrieve full information

### ISSUE THREAD

**Issue by ikrabbe** [aws/aws-cli#2068]
How can I retrieve the full set of parseable information, for example through a `aws --output text ec2 describe-images --query ...`? What I do I miss some things or they are in a strange structured order?
- By the way: Where is the reference documentation of the record structure, for example for the ec2-describe-images IMAGES type?

When I select `--output text` without a query I get a Record Type in front of a line, for example `aws --output text ec2 describe-images --image-id ami-0030d96f` gives

```
IMAGES  x86_64  2016-06-15T07:16:33.000Z    xen ami-0030d96f    amazon/aws-elasticbeanstalk-amzn-2016.05.11.x86_64-WindowsServer2012-hvm-201606150603   amazon  machine aws-elasticbeanstalk-amzn-2016.05.11.x86_64-WindowsServer2012-hvm-201606150603  102837901569    windows True    /dev/sda1   ebs available   hvm
BLOCKDEVICEMAPPINGS /dev/sda1   
EBS True    False   snap-a79222ac   30  gp2
BLOCKDEVICEMAPPINGS xvdca   ephemeral0
BLOCKDEVICEMAPPINGS xvdcb   ephemeral1
BLOCKDEVICEMAPPINGS xvdcc   ephemeral2
BLOCKDEVICEMAPPINGS xvdcd   ephemeral3
BLOCKDEVICEMAPPINGS xvdce   ephemeral4
BLOCKDEVICEMAPPINGS xvdcf   ephemeral5
BLOCKDEVICEMAPPINGS xvdcg   ephemeral6
BLOCKDEVICEMAPPINGS xvdch   ephemeral7
BLOCKDEVICEMAPPINGS xvdci   ephemeral8
BLOCKDEVICEMAPPINGS xvdcj   ephemeral9
BLOCKDEVICEMAPPINGS xvdck   ephemeral10
BLOCKDEVICEMAPPINGS xvdcl   ephemeral11
BLOCKDEVICEMAPPINGS xvdcm   ephemeral12
BLOCKDEVICEMAPPINGS xvdcn   ephemeral13
BLOCKDEVICEMAPPINGS xvdco   ephemeral14
BLOCKDEVICEMAPPINGS xvdcp   ephemeral15
BLOCKDEVICEMAPPINGS xvdcq   ephemeral16
BLOCKDEVICEMAPPINGS xvdcr   ephemeral17
BLOCKDEVICEMAPPINGS xvdcs   ephemeral18
BLOCKDEVICEMAPPINGS xvdct   ephemeral19
BLOCKDEVICEMAPPINGS xvdcu   ephemeral20
BLOCKDEVICEMAPPINGS xvdcv   ephemeral21
BLOCKDEVICEMAPPINGS xvdcw   ephemeral22
BLOCKDEVICEMAPPINGS xvdcx   ephemeral23
BLOCKDEVICEMAPPINGS xvdcy   ephemeral24
BLOCKDEVICEMAPPINGS xvdcz   ephemeral25
```

Now, if I want to get a parseable list of output I need a query, as sometimes in Images records some fields are silently missing, that can be forced with query `aws --output text ec2 describe-images --image-id ami-0030d96f --query Images[*].[Architecture,CreationDate,Description,Hypervisor,ImageId,ImageLocation,ImageOwnerAlias,ImageType,Name,OwnerId,Public,RootDeviceType,State,VirtualizationType,BlockDeviceMappings[*],Images[*]]
` gives

```
x86_64  2016-06-15T07:16:33.000Z    None    xen ami-0030d96f    amazon/aws-elasticbeanstalk-amzn-2016.05.11.x86_64-WindowsServer2012-hvm-201606150603   amazon  machine aws-elasticbeanstalk-amzn-2016.05.11.x86_64-WindowsServer2012-hvm-201606150603  102837901569    True    ebs available   hvm None
/dev/sda1   
EBS True    False   snap-a79222ac   30  gp2
xvdca   ephemeral0
xvdcb   ephemeral1
xvdcc   ephemeral2
xvdcd   ephemeral3
xvdce   ephemeral4
xvdcf   ephemeral5
xvdcg   ephemeral6
xvdch   ephemeral7
xvdci   ephemeral8
xvdcj   ephemeral9
xvdck   ephemeral10
xvdcl   ephemeral11
xvdcm   ephemeral12
xvdcn   ephemeral13
xvdco   ephemeral14
xvdcp   ephemeral15
xvdcq   ephemeral16
xvdcr   ephemeral17
xvdcs   ephemeral18
xvdct   ephemeral19
xvdcu   ephemeral20
xvdcv   ephemeral21
xvdcw   ephemeral22
xvdcx   ephemeral23
xvdcy   ephemeral24
xvdcz   ephemeral25
```

You see here that the Recordtype _sometimes_ misses! EBS has a record type in front of the line.

So either I get some tab separated fields with record types in front, but I cannot rely on the order of the fields of incomplete records or I get tab separated fields of a selected record type, where I can rely on the line structure, but if I want to read substructures I'm lost again with the query.

**Comment by kyleknap** [comment]
I usually would not recommend text output if you are trying to get **all** possible information because that output format is somewhat limited especially when there is bunch of nested structures. Usually I only use it if there is a small slice of response properties that I want to pipe to another command. If you do not mind me asking what are you trying to do with all of the information once you have it in the text format?

**Comment by ikrabbe** [comment]
When writing scripts for aws-cli, it's far more simple to parse text output, if you know the structure of the output. But I agree that I can reach most if not any information through a `--query` parameter. My basic problem with that approach is, that the output, even with a `--query` is not consistent with the output of the default, __all__ query. It it isn't even consistent with sibling lines of the same `--query` result, as sometimes (in the example the EBS line) the record will get prefixed with the record type, while other lines are written without this prefix (here IMAGES and BLOCKDEVICEMAPPINGS).

**Comment by stealthycoin** [comment]
Generally the text output is for human readability. The JSON output is designed for scripting, we would suggest using either `--query` or pipe the JSON output to some other JSON parsing utility.
