### ISSUE TITLE
"aws ec2 create-subnet" rc=0 for invalid availability zone

### ISSUE THREAD

**Issue by ralfbergs** [aws/aws-cli#2074]
In my script to create my environment I execute the following command:
`aws ec2 create-subnet --output text --vpc-id ${VpcId} --cidr-block 10.3.0.0/24 --availability-zone ${AZ1} --query 'Subnet.SubnetId'`
`AZ1` was set to a non-existent value, `eu-central-ERROR`. Still the return code of the above command is `0`.

However, I received a reasonable error message:
`An error occurred (InvalidParameterValue) when calling the CreateSubnet operation: Value (eu-central-ERROR) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: eu-central-1b, eu-central-1a.`

This is about the following AWS CLI version:
`aws-cli/1.10.47 Python/2.7.10 Darwin/15.6.0 botocore/1.4.37`

**Comment by JordonPhillips** [comment]
I'm not able to reproduce. Could you provide a scrubbed out --debug log?

**Comment by ralfbergs** [comment]
The strange thing is -- I can't reproduce it any longer. :-/

(It was reproducible earlier, or else I wouldn't have opened a ticket!)

Thanks for checking, and sorry for bothering. Should I see the issue again (unlikely, as it was due to a typo, and now I have all the constants I need defined), I will update this issue.

Kind regards!
