### ISSUE TITLE
No option to set Elasticsearch version from CLI

### ISSUE THREAD

**Issue by ajcrites** [aws/aws-cli#2081]
When creating a domain with AWS managed Elasticsearch service `es` in the console you can set the version with the domain and it defaults to 2.3

On the CLI, there is no way to set the version and it defaults to 1.5

There should be an option to set the Elasticsearch version and it should probably match the default in the console, 2.3

**Comment by JordonPhillips** [comment]
Looks like this was a feature that was released yesterday. We'll need to update our models accordingly.

**Comment by JordonPhillips** [comment]
We've updated to support the new parameter: http://docs.aws.amazon.com/cli/latest/reference/es/create-elasticsearch-domain.html
