### ISSUE TITLE
Return code

### ISSUE THREAD

**Issue by NoUseFreak** [aws/aws-cli#2083]
Hi,

I am trying to verify the available aws-cli version is correct. I do this by running the version command and parsing it using a grep regex.

The issue I am having is that `aws --version; echo $?` returns 0 witch is good. However if I run `aws --version | grep a; echo $?` it returns 1. I am depending on the return codes of grep `0` for success and `1` for no results found.

Do I need to do anything special to get this to work?

Kind regards.

**Comment by jamesls** [comment]
`--version` info is written to stderr.  Something like this should work for you:

```
$ aws --version
aws-cli/1.10.46 Python/2.7.11 Darwin/15.6.0 botocore/1.4.36
$ aws --version 2>&1 | fgrep '1.10.46'; echo $?
aws-cli/1.10.46 Python/2.7.11 Darwin/15.6.0 botocore/1.4.36
0
$ aws --version 2>&1 | fgrep '1.10.47'; echo $?
1
```

Let me know if that doesn't work and I'll reopen and take another look.

**Comment by NoUseFreak** [comment]
@jamesls It works! Thank for the help!
