### ISSUE TITLE
Windows MSI installer uses incorrect path

### ISSUE THREAD

**Issue by truedat101** [aws/aws-cli#2087]
Using Windows 10, awscli build: 

```
$ aws.exe --version
aws-cli/1.10.52 Python/2.7.9 Windows/8 botocore/1.4.42
```

User environment gets path:

C:\Program Files\Amazon\AWSCLI\

Should be:

C:\Program Files\Amazon\AWSCLI

Trailing slash breaks the path.

**Comment by jamesls** [comment]
I can confirm this issue.  Thanks for reporting.

**Comment by kyleknap** [comment]
Just going over old issues. Is this still an issue? Can you clarify how a trailing slash breaks the path. When running the Python2-base CLI MSI on Windows, it does not seem that having a trailing slash or omitting a trailing slash affects the ability to find the `aws` executable on the path.
