### ISSUE TITLE
The pip package name should be aws-cli, not awscli

### ISSUE THREAD

**Issue by mattdipasquale** [aws/aws-cli#2090]
The pip package name should be the same as the git repository name because consistency is good and AWS & CLI are separate acronyms.

**Comment by kyleknap** [comment]
This is something that we would not probably want to change. It would be a huge breaking change for everyone relying on ``awscli`` as a dependency because we would have to remove that package and create a new ``aws-cli`` package in PyPI.

To avoid a breaking change, we would have to create an alias package but that would lead to confusion if there was an ``awscli`` and ``aws-cli`` package in PyPI as users may be confused on which one to install when there is not really a difference.

Closing issue.

**Comment by mattdipasquale** [comment]
Why avoid a breaking change?

Boy: Slavery is wrong. The laws should be changed.
Man: No, they shouldn't because that would require slaveowners to make changes.

**Comment by lorengordon** [comment]
Could also rename the github project to `awscli`. :)

**Comment by mattdipasquale** [comment]
Yeah, that would make sense if it were called AWSCLI, but it's called [AWS CLI](http://docs.aws.amazon.com/general/latest/gr/GetTheTools.html), which makes sense because AWS & CLI are separate acronyms, and so, they should be separated by a space, or by a hyphen in a URL.

**Comment by lorengordon** [comment]
And the tool is just `aws`. They're even less likely to change that than the python package name. So let's not get so caught up in semantics that we ignore practical, less-breaking options that achieve the same desired effect. Changing documentation to AWSCLI is not particularly hard, either.

**Comment by mattdipasquale** [comment]
> Perfection is not attainable, but if we chase perfection we can catch excellence.

— Vince Lombardi

Great point. Then, maybe the GitHub repository, pip package, and Homebrew forumla should all have the same name: `aws`.

Consistency is nice. But, a foolish consistency (in order to avoid a breaking change)?

> A foolish consistency is the hobgoblin of little minds, adored by little statesmen and philosophers and divines. With consistency a great soul has simply nothing to do. He may as well concern himself with his shadow on the wall. Speak what you think now in hard words, and to-morrow speak what to-morrow thinks in hard words again, though it contradict every thing you said to-day. — 'Ah, so you shall be sure to be misunderstood.' — Is it so bad, then, to be misunderstood? Pythagoras was misunderstood, and Socrates, and Jesus, and Luther, and Copernicus, and Galileo, and Newton, and every pure and wise spirit that ever took flesh. To be great is to be misunderstood.

— Ralph Waldo Emerson
