### ISSUE TITLE
CodeCommit credential helper does not work on Python 3 in Windows

### ISSUE THREAD

**Issue by JordonPhillips** [aws/aws-cli#2092]
Git wants unix style line endings from its credential helpers, but Python converts unix style line endings to windows-style line endings when writing strings to stdout. There is currently a fix for that behavior for python 2, which is to use `msvcrt.setmode` to set the line ending translation mode to `O_Binary`. That fix no longer works in python 3, so the cli will need to write to `stdout.buffer`.

**Comment by jamesls** [comment]
Remind me again, what's the error look like when this happens?

**Comment by KaibaLopez** [comment]
Hi @JordonPhillips,
I'm going through old issues and bugs, and this one in particular seems to have been resolved. At least I was not able to reproduce it and so I'll mark it for closure, if you don't think that's the case please comment, and if it gets closed before you get a chance to do so feel free to open a new one, it would help us reprioritize it better.
