### ISSUE TITLE
Sort Objects In Amazon S3 by last Date

### ISSUE THREAD

**Issue by hacheme** [aws/aws-cli#2095]
I use Amazon to upload object and S3bubble plugin to display video. They're sorted alphabetically by key In Amazon S3.

How to solve this problem. Please help me

**Comment by kyleknap** [comment]
There is not really a way to do this server side. I would recommend asking the forums for this feature request: https://forums.aws.amazon.com/forum.jspa?forumID=24

The best you can do is use client-side filtering that the CLI provides with ``--query``.

So to list from oldest to latest, you can do:
```
aws s3api list-objects --bucket mybucketfoo --query "sort_by(Contents,&LastModified)"
```

Or if you want to do in the reverse order do:
```
aws s3api list-objects --bucket mybucketfoo --query "reverse(sort_by(Contents,&LastModified))"
```

If you have any further questions, lets keep the conversation onto [gitter](https://gitter.im/aws/aws-cli)

**Comment by jimiwal** [comment]
the workaround for your problem is to:
1) Add x-amz-timestamp-desc to your bucket
2) Whenever you create object, please attach metadata value calculated as 1000000000 -  CurrentDateTime
What you achive is that your date time will not grow but decrease.
