### ISSUE TITLE
support: Could not connect to the endpoint URL

### ISSUE THREAD

**Issue by andreineculau** [aws/aws-cli#2102]
When I try to use the `aws support describe-cases` command, all I get is
`Could not connect to the endpoint URL: "https://support.eu-west-1.amazonaws.com/"`

**Comment by kyleknap** [comment]
So support is only available in ``us-east-1`` right now: http://docs.aws.amazon.com/general/latest/gr/rande.html#awssupport_region. So you will have to specify ``us-east-1`` through ``--region`` or the config file.

If you have any more follow up questions, let's continue the conversation on [gitter](https://gitter.im/aws/aws-cli).

**Comment by awsdevopro** [comment]
To create any services through command line, you need to specify the region. I have faced the issue as stated and got the solution as following command and it worked. 

root@aws-pc:~# aws ec2 create-security-group --group-name my-sg --description "My security group"

Could not connect to the endpoint URL: "https://ec2.us-east-1.amazonaws.com/"
root@aws-pc:~# aws configure
AWS Access Key ID [****************3P5A]: 
AWS Secret Access Key [****************uHLJ]: 
Default region name [us-east-1]: 
root@aws-pc:~# aws ec2 create-security-group --group-name my-sg --description "My security group" --region=us-east-1
{
    "GroupId": "sg-b9d581cc"
}

**Comment by jalbstmeijer** [comment]
Hi,

Had an old internal ticket pointing to this behavior.
Just revisited it and tested again against aws-cli version 1.16.183, it is still the same.

Would it not be nicer if the aws cli  just outputs, in case you supply a wrong --region, that this service is only available through the us-east-1 region? or just overrules the region?
It does that at least in case you set the env AWS_DEFAULT_REGION to an other region than us-east-1 and not use --region

in both cases with env AWS_DEFAULT_REGION=eu-west1 set:

aws iam get-role --role-name XXXX_role --output text --region eu-west1
Could not connect to the endpoint

aws iam get-role --role-name XXXX_role --output text
works

Gr, J

**Comment by justnance** [comment]
We are tracking a feature request under #2266 to improve region validation.

**Comment by Allow-tap** [comment]
> 

Is this still the case? We can only access the AWS support API through us-east-1?
