### ISSUE TITLE
Install codedeploy agent on Centos 7

### ISSUE THREAD

**Issue by davividal** [aws/aws-cli#2107]
Whenever I try to install AWS CodeDeploy agent on a on-premise server, I got a System.UNSUPORTED_SYSTEM_MSG.
I was able to get it up and running with the following:

```diff
diff --git a/awscli/customizations/codedeploy/utils.py b/awscli/customizations/codedeploy/utils.py
index 7aee4bb..e343cf0 100644
--- a/awscli/customizations/codedeploy/utils.py
+++ b/awscli/customizations/codedeploy/utils.py
@@ -101,7 +101,8 @@ def validate_instance(params):
     if platform.system() == 'Linux':
         if 'Ubuntu' in platform.linux_distribution()[0]:
             params.system = Ubuntu(params)
-        if 'Red Hat Enterprise Linux Server' in platform.linux_distribution()[0]:
+        if 'Red Hat Enterprise Linux Server' in platform.linux_distribution()[0]
+            or 'CentOS Linux' in platform.linux_distribution()[0]:
             params.system = RHEL(params)
     elif platform.system() == 'Windows':
         params.system = Windows(params)
```

`platform.linux_distribution` outputs `('CentOS Linux', '7.2.1511', 'Core')`.

Is there a reason as to not allow install on CentOS? How can I test it to check if it is properly working?

**Comment by davividal** [comment]
Update: I'm using codedeploy-agent on a premise CentOS 7 server without any noticeable issue.
My build files are .tar.gz stored in a S3 bucket.

**Comment by jamesls** [comment]
Let me follow up with the codedeploy team and see if they have any issues with this.

**Comment by davividal** [comment]
Hi. Any updates on this?

**Comment by jamesls** [comment]
Sorry for the delay, I'm following up again with codedeploy.  I'll update this as soon as I have information to share.

**Comment by davividal** [comment]
Hey @jamesls , any update?

**Comment by davividal** [comment]
Any update on this?
I'm on the verge to give up on using codedeploy on my on-premise instances.

Unless there is some MAJOR issue with CentOS 7, I don't think it should take more than a month to review a ONE LINE patch...

**Comment by ambareesha** [comment]
Apologies for the delay in getting back on this. We don't officially support CentOS since we haven't tested our agent on the OS. Unfortunately, our host-agent release process is a bit time consuming and we are focusing all our efforts right now on updating the host agent to work with all versions of Ruby 2.x. The next item in our roadmap after that is to support Ubuntu 16. We can consider adding tests for CentOS too at that point, so we can release support both the OSes at the same time.

Having said that, several of our customers are running the CodeDeploy host agent on CentOS without any problems. While it will take us some time to pull in your patch and test it, you can build your own custom host agent and run it on CentOS.

However, please be aware that this has not been tested officially and you could run into problems.

**Comment by jamesls** [comment]
Given the response from the code deploy team above ^ I think we'll need to hold off on merging this PR for the time being until CentOS is officially supported.

I'm going to go ahead and close out this issue for now, but we can revisit this again when CodeDeploy adds official support.

Thanks again for the pull request.

**Comment by kyalamanchi** [comment]
Any update on when Centos will be supported ?

**Comment by enricopesce** [comment]
A N Y   U P D A T E ? ? ? ?

**Comment by CosmicCatnap** [comment]
This is a one line fix that has been outstanding for 5 years now. Its currently being maintained by one of the largest and well funded companies in the world and is part of their most profitable division. Its pathetic to be honest.

**Comment by davividal** [comment]
@CosmicCatnap it is not 5 years.
It will turn 4 years old in 1 day and 41 minutes. :birthday:

**Comment by davividal** [comment]
Congrats #2107 ! 4 years old!! 🎂

**Comment by SlaySayto** [comment]
its 5 years now. I can believe that a small task like this is taking 5 years. This is so annoying !!

**Comment by SlaySayto** [comment]
@davividal  can you tell me the steps to install the CLI manually with the modified file

**Comment by davividal** [comment]
> @davividal can you tell me the steps to install the CLI manually with the modified file

Nope.
I did this 5 years ago, I can't remember how I did it.

Since I made a PR with this change, I had a cloned repo with the patch applied. I probably installed this package using pip and my clone. But this is a guess.

**Comment by rsiw2000** [comment]
Well, I'm interested too.
I need to run  codedeploy agent on a Centos 7.
At this point, I'm sure AWS won't officially support this.

**Comment by trevor-burbidge-iiq** [comment]
After trying to figure out how to make this code change work to install on CentOS I finally realized that I don't need to use the aws-cli to install the agent, it can just be installed directly by following the instructions here: [Install the CodeDeploy agent for Amazon Linux or RHEL](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-linux.html)

**Comment by rsiw2000** [comment]
Yes, thanks for reminding me to take a minute to write a feedback here.
It's working fine on CentOS 7 that I've installed using this installation guide.
