### ISSUE TITLE
aws s3api with encoding-type=url - "Error during pagination" on special characters

### ISSUE THREAD

**Issue by rjamestaylor** [aws/aws-cli#2115]
When executing s3api list-object-versions --encoding-type=url I receive the following error:

> Error during pagination: The same next token was received twice: {u'VersionIdMarker': '****_Kki7vmzz**__uf5y2lN6Bkz_***', u'KeyMarker': '999999999999999/[GUID-redacted]/article/charencoding001/size%3A72/TitleSubject/image+L.jpg'}

Redacted the GUID & changed a bit of the plain ASCII text

When executing the same command without the --encoding-type=url, I receive no errors. Bucket has ~26m objects.

I have the --debug log for the command but would like to upload it in a private setting - should I create a support case for this?

$ aws --version
aws-cli/1.10.56 Python/2.7.10 Linux/4.4.11-23.53.amzn1.x86_64 botocore/1.4.46

**Comment by jamesls** [comment]
I'm not sure if this is documented, but we automatically inject the EncodingType=url param for you whenever we invoke `list-objects`, you shouldn't need to specify this param.

Out of curiosity, was there a specific you were running into where you needed to specify `--encoding-type url`?

**Comment by rjamestaylor** [comment]
Interesting! So, not specifically a need for that, however, reading the documentation indicated that some special characters would need --encoding-type=url to be added to be processed. I am working with large buckets and ways to quickly gather a list of all object versions for the purpose of a point in time recovery operation (on a versioned bucket, obviously). On a 26M object bucket, without specifying a prefix and parallelizing the API calls, I can retrieve the version info into a 16G file in 3.5 hours (on an m4.10xlarge in us-east-1). By sharding the calls with a forked process for each ascii character between 32 and 126, I can pull the info down in 23 mins. But! I don't get the same number of objects and was trying to change ways of calling the API to see why. In one of those attempts I added the --encoding-type=url parameter and discover this issue.
