### ISSUE TITLE
Generate S3 Pre-signed URLs

### ISSUE THREAD

**Issue by ajorg** [aws/aws-cli#2118]
boto3 knows how to generate S3 pre-signed URLs. It would be handy if the AWS CLI could also do this.

**Comment by lorengordon** [comment]
Stay tuned for an upcoming release ;)

https://github.com/aws/aws-cli/pull/2113

**Comment by ajorg** [comment]
Nice!

**Comment by JordonPhillips** [comment]
I'm gonna go ahead and close this out, the feature will be available in our next release. We release pretty often, so you won't have long to wait :)

**Comment by lorengordon** [comment]
"release pretty often" he says! :joy: the bulk of the software world still struggles even with quarterly releases, and it's rare for this project to go without a few a week!
