### ISSUE TITLE
typo in documentation - "PutBucketNotificationConfiguraiton"

### ISSUE THREAD

**Issue by hakanson** [aws/aws-cli#2127]
Looking at the online documentation for put-bucket-notification, I saw a typo in the word "PutBucketNotificationConfiguraiton" (see http://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-notification.html)

> Deprecated, see the PutBucketNotificationConfiguraiton operation.

Searching this repo, I could not find that string, but a search across the AWS org found 12 matches from various repos.

https://github.com/search?p=1&q=org%3Aaws+PutBucketNotificationConfiguraiton&type=Code

Not sure if these were all copy/paste or sourced from a common string, so creating an issue.

**Comment by jamesls** [comment]
Thanks. These are sourced from the same underlying source.  For the AWS CLI, this docstring comes from botocore.

I'll get this updated upstream.

**Comment by hakanson** [comment]
Is there a related issue in botocore to reference?

**Comment by adamchainz** [comment]
botocore only copies them in from AWS, this needs updating somewhere on AWS

The typo is in this file: https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json

**Comment by justnance** [comment]
@hakanson - Thanks for reporting this issue.  This issue has been escalated internally.  Thanks for your patience.

**Comment by justnance** [comment]
@hakanson - Typo has been corrected.  Thanks for your patience.

**Comment by adamchainz** [comment]
👌
