### ISSUE TITLE
aws-cli not working in Mumbai region

### ISSUE THREAD

**Issue by rolindroy** [aws/aws-cli#2128]
Hi, I am getting error while running aws-cli ec2 describe command.

Error : "_Service ec2 not available in region ap-south-1_"

Command : 

`aws ec2 describe-instances \
  --filters "Name=tag:Name, Values=Website" \
  --query 'Reservations[*].Instances[*].[InstanceId]' \
  --output text`

Please advice me on this.

**Comment by jamesls** [comment]
Not seeing that issue:

```
$ aws ec2 describe-instances --region ap-south-1
{
    "Reservations": []
}
```

Please post the a `--debug` log so we can see what's going on.

**Comment by rolindroy** [comment]
Hi, Thank you for  getting back to me.
Plesae see the attached log.

![aws-cli](https://cloud.githubusercontent.com/assets/5978607/17918506/285b06dc-69e3-11e6-8aa5-1290f1912259.JPG)

**Comment by rolindroy** [comment]
Please look into it.
```
$aws configure
AWS Access Key ID [****************XXXX]: 
AWS Secret Access Key [****************yyyy]: 
Default region name [ap-south-1]: 
Default output format [None]:
```

```
$aws ec2 describe-instances

Service ec2 not available in region ap-south-1

```

```
$aws ec2 describe-instances --region us-west-1
{
    "Reservations": []
}
```
```
$aws ec2 describe-instances --region ap-south-1
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --region: Invalid choice, valid choices are:

sa-east-1                                | us-gov-west-1                           
us-east-1                                | us-west-2                               
ap-southeast-2                           | ap-southeast-1                          
ap-northeast-1                           | eu-west-1                               
cn-north-1                               | us-west-1                               
fips-us-gov-west-1                      

Invalid choice: 'ap-south-1', maybe you meant:

  * ap-southeast-1
```

**Comment by lorengordon** [comment]
The region is fairly new, right? What version is your awscli? If not latest, try upgrading...

**Comment by rolindroy** [comment]
Thank you @lorengordon . I have upgraded awscli to latest version (1.10.14). Everything seems working fine.

**Comment by shreejayp95** [comment]
Hello,
I am getting same error
I tried to upgrade aws cli but still getting same msg

To install awscli I used the command
`$ sudo apt-get install awscli`

Agter installing I checked version
`$ aws --version`
    aws-cli/1.2.9 Python/3.4.3 Linux/4.4.0-62-generic

Then I Configured aws cli
`$ aws configure`
    AWS Access Key ID [****************JSDA]: 
    AWS Secret Access Key [****************okSI]:
    Default region name [ap-south-1b]: ap-south-1b
    Default output format [text]: text

`$ aws ec2 describe-instances --instance-ids i-0ba78a65sw45s1012sa`
    Service ec2 not available in region ap-south-1b


Then I tried to upgrade by using following command. But still getting same version and same OUTPUT
`$ sudo pip install --upgrade awscli`
`$ aws --version`
    aws-cli/1.2.9 Python/3.4.3 Linux/4.4.0-62-generic

Then again I tried to upgrade by using following command, still getting same version and same OUTPUT

`$ git clone https://github.com/aws/aws-cli.git`
`$ cd ~/aws-cli`
`$ sudo python setup.py install`
`$ aws --version`
    aws-cli/1.2.9 Python/3.4.3 Linux/4.4.0-62-generic

`$ aws ec2 describe-instances --instance-ids i-0ba78a65sw45s1012sa`
    Service ec2 not available in region ap-south-1b

`$ aws ec2 describe-instances --region ap-south-1`
    usage: aws [options] <command> <subcommand> [parameters]
    aws: error: argument --region: Invalid choice, valid choices are:
    
    ap-northeast-1                           | us-gov-west-1                           
    eu-west-1                                | sa-east-1                               
    fips-us-gov-west-1                       | cn-north-1                              
    us-west-2                                | ap-southeast-2                          
    ap-southeast-1                           | us-east-1                               
    us-west-1                               
    
    Invalid choice: 'ap-south-1', maybe you meant:
    
      * ap-southeast-1

How to solve the issue....??

**Comment by rolindroy** [comment]
@shreejayp95 
http://stackoverflow.com/questions/36969391/how-to-upgrade-aws-cli-to-the-latest-version
