### ISSUE TITLE
Error while doing deploy push

### ISSUE THREAD

**Issue by kamililyas** [aws/aws-cli#2135]
Hello, hope you guys are doing good, thank you for the tool. I have a problem while using the tool which I can' t seem to get around. I keep trying to deploy push through my CLI but keep getting this error: 

Command:
> aws deploy push --application-name <app_name> --description "This is first deployment" --s3-location s3://<bucket_name>/example_1.zip

Error:
[Errno 6] No such device or address: u'/home/alien/.config/google-chrome/SingletonSocket'

It seems like it looks for something in my local config files, but i have a hunch that this issue is related to python(install or upgrade maybe, currently i'm using the default ubuntu 14.04 version of python). I recently upgraded my awscli version as the previous one didn't have deploy and push commands, here are the details for it after running the following command:

> aws --version

aws-cli/1.10.59 Python/2.7.6 Linux/3.13.0-32-generic botocore/1.4.49

Any help would be greatly appreciated, thank you in advance.

Regards,
Kamil

**Comment by jamesls** [comment]
If you don't provide a `--source` location, it will default to your current working directory.  What happens if you try to specify `--source /path/to/your/app`?

**Comment by kamililyas** [comment]
Hello again, thank you so much for pointing that out, i didn't notice it at first, yes we should run it from the source location or mention the source explicitly as u stated, thank you again.
