### ISSUE TITLE
Error parsing parameter '--test': Expected: '=', received: ''' for input:

### ISSUE THREAD

**Issue by hoda0013** [aws/aws-cli#2142]
This is the command and error response from running a aws cli for the device farm:

`$ aws devicefarm schedule-run --project-arn $AWS_PROJECT_ARN --app-arn $APP_UPLOAD_ARN --device-pool-arn $AWS_TOP_DEVICES_POOL_ARN --name myTest --test "'""{\"type\":\"INSTRUMENTATION\",\"testPackageArn\":\"$TEST_APP_UPLOAD_ARN\"}""'"

Error parsing parameter '--test': Expected: '=', received: ''' for input:
'{"type":"INSTRUMENTATION","testPackageArn":"arn:aws:devicefarm:us-west-X:XXXXXXXX:upload:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"}'`

`Version information:
# aws --version
aws-cli/1.10.60 Python/2.7.5 Linux/4.4.15-moby botocore/1.4.50`

**Comment by kyleknap** [comment]
I think you can simplify a lot of this by using the shorthand syntax instead of the JSON syntax:
```
$ aws devicefarm schedule-run --project-arn AWS_PROJECT_ARN \
  --app-arn APP_UPLOAD_ARN --device-pool-arn AWS_TOP_DEVICES_POOL_ARN \
  --name myTest --test type=$INSTRUMENTATION,testPackageArn=$TEST_APP_UPLOAD_ARN
```

That works for me. Let us know if it works for you.

**Comment by hoda0013** [comment]
Oh snap. I had no idea I could do it that way. That's so much easier. Thanks.
