### ISSUE TITLE
How to restore Aurora cluster from snapshot of cluster with DB cluster member?

### ISSUE THREAD

**Issue by rluisr** [aws/aws-cli#2144]
Hi.

I want to restore Aurora cluster from snapshot of cluster which includes DB instance member with AWS CLI.
The cluster is backed up automatically but when I restore cluster from it, New cluster does't includes DB instance member.

What Should I do?

**Comment by kyleknap** [comment]
I am not too familiar with how you would do this in the RDS API. I would recommend asking on the [AWS developer forums](https://forums.aws.amazon.com/forum.jspa?forumID=60) about this. They should be much more knowledgeable on how to do this.
