### ISSUE TITLE
aws ecs register-task-definition (--task-role-arn Unknown option)

### ISSUE THREAD

**Issue by kgcmd** [aws/aws-cli#2156]
Every time I create a revision to a task and and register it using the aws cli, my task role arn gets wiped. The documentation states that I can specify --task-role-arn as an option, but this throws the error:  

Unknown options: --task-role-arn, arn:aws:iam::XXXXXXXXX:role/ecsTaskRole

This is a huge pain, as we use CI to deploy updates, and it is very inconvenient to have to go in and manually create another revision with the proper role set.

**Comment by kgcmd** [comment]
Also when i try to type "aws ecs register-task-definition help" I get the error:
<string>:414: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.

I'm running version:
aws-cli/1.10.35 Python/2.7.10 Darwin/15.5.0 botocore/1.4.25

**Comment by JordonPhillips** [comment]
That particular argument was added in `1.10.47`, so you'll need to update to at least that version.
