### ISSUE TITLE
mv of large files always fails with AccessDenied

### ISSUE THREAD

**Issue by Kent-H** [aws/aws-cli#2158]
When trying to `mv` large files within a single bucket, the `mv` will always fail, with:

    An error occurred (AccessDenied) when calling the UploadPartCopy operation: Access Denied

This only appears to fail when UploadPartCopy is used.

----

Possibly related/more documentation: https://forums.aws.amazon.com/thread.jspa?messageID=739813

**Comment by Kent-H** [comment]
This also occurs when using copy/cut --> paste on the aws web ui.  

(Is it possible to submit a bug report for a core S3 service?)

**Comment by JordonPhillips** [comment]
Normally I would assume this is a policy issue, but if it PutObject works then I'm not sure. You can ask for service specific assistance on the forums (as you linked), and that's what I recommend here.

**Comment by jumping** [comment]
I encounter the similar problem: "occurred when calling the UploadPartCopy operation: Access Denied"

**Comment by mnagen** [comment]
any solution had been facing the similar issue
