### ISSUE TITLE
determine multiple acls for object being pushed by awscli

### ISSUE THREAD

**Issue by gkiar** [aws/aws-cli#2162]
Hi,

In a script, I am pushing data to a publicly writeable directory of my s3 bucket without using a certificate. I wish to, however, do two things upon pushing this data:
- make it publicly available; and,
- give bucket owner full control.

Using the `--acl` flag I find that i am able to do either of these things, with the `public-read-write` and `bucket-owner-full-control` options, respectively, but not both. Is this possible? Or even if in two commands, could I achieve both from the cli without using a certificate?

My perfect command (though this doesn't seem to produce desired behaviour) would be something like: 
```
aws s3 cp ./mydata s3://mybucket --no-sign-request --acl public-read-write bucket-owner-full-control
```

Thanks!
Greg

**Comment by JordonPhillips** [comment]
The ACL is a predefined set of grants. For something that doesn't fall within the canned ACLs, you'll need to supply your own grants. You can see an example of this at the bottom of the [cp reference page](http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html). You can find more information about grants [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html).

**Comment by gkiar** [comment]
That helped, thank you!! 👍
