### ISSUE TITLE
aws s3 sync doesn't guess mimetype for .properties files

### ISSUE THREAD

**Issue by mblakele** [aws/aws-cli#2163]
```
aws-cli/1.10.56 Python/2.7.10 Darwin/15.6.0 botocore/1.4.46
```

When using `aws s3 sync` on `*.properties` files, the metadata content-type ends up with a value suitable for binary. It would be nice to have `text/x-java-properties` or another `text/*` type.

Workaround: use `--content-type text/x-java-properties`. However the sync origin may have more than one file type.

**Comment by JordonPhillips** [comment]
We use the python `mimetypes` library to guess the type, if it can't guess then there's not much we can do. You might be able to make that request on python itself, but it will necessarily require updating python versions.

**Comment by mblakele** [comment]
Consider falling back on python-magic in `guess_content_type` if `mimetypes.guess_type` returns `None`.

```
>>> import magic
>>> mime = magic.Magic(mime=True)
>>> mime.from_filename("/tmp/test.properties")
>>> mime.from_file("/tmp/test.properties")
'text/plain'
```

That would be an improvement on the current behavior.
