### ISSUE TITLE
Manpage should contain an example for put-item

### ISSUE THREAD

**Issue by stapelberg** [aws/aws-cli#217]
Being a new user to aws-cli, I looked at aws dynamodb put-item help, but that manpage does not contain an example or at least a reference to https://github.com/aws/aws-cli/blob/develop/doc/source/tutorial/getting_started.rst which explains how to do complex parameter passing.

It would be great if you could add an example so that it’s easier to pinpoint the particular problem new users are having :). Thanks.

**Comment by JordonPhillips** [comment]
Leaving references to the [basic usage guide](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-using.html) everywhere would be messy and, IMHO, unnecessary.
