### ISSUE TITLE
how to list stopped instances and email to admin

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2176]
how to list stopped instances and email to admin

**Comment by mkaja** [comment]
i got it
aws --output table  ec2 describe-instances --query 'Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value,InstanceId,InstanceType,State.Name,VpcId,Placement.AvailabilityZone]' --filters "Name=instance-state-name,Values=stopped"

**Comment by jamesls** [comment]
Awesome, glad you were able to get it working.
