### ISSUE TITLE
ec2 describe-security-groups + filters (ip-permission.from-port / ip-permission.to-port) does not work with --group-ids

### ISSUE THREAD

**Issue by lifeofguenter** [aws/aws-cli#2186]
The example from: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html

```
aws ec2 describe-security-groups --filters Name=ip-permission.from-port,Values=22 Name=ip-permission.to-port,Values=22 Name=ip-permission.cidr,Values='0.0.0.0/0' --query 'SecurityGroups[*].{Name:GroupName}'
```

Works.

However:

```
aws ec2 describe-security-groups --group-ids sg-xxxx --filters Name=ip-permission.from-port,Values=22 Name=ip-permission.to-port,Values=22 Name=ip-permission.cidr,Values='0.0.0.0/0'
```

Does not.

**Comment by JordonPhillips** [comment]
If you leave out the `--group-ids` parameter, is that security group id returned as part of the response? That's the only thing that seems off. I was able to successfully run the second request using my own security groups.

If you're still having issues, you can get api specific help on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
