### ISSUE TITLE
AWS devicefarm create-upload requires a .ipa name

### ISSUE THREAD

**Issue by otusweb** [aws/aws-cli#2193]
Running 
`aws devicefarm create-upload --name appTest --type IOS_APP --project-arn arn:aws:devicefarm:xxx` 

will cause the upload to fail with an invalid file error:

`{
    "upload": {
        "status": "FAILED", 
        "name": "appTest", 
        "created": 1474632694.157, 
        "type": "IOS_APP", 
        "arn": "arn:aws:devicefarm:us-west-2:xxxx", 
        "metadata": "{\"errorMessage\":\"Invalid file uploaded.\"}"
    }
}`

where running 
`aws devicefarm create-upload --name evaneosAppTest.ipa --type IOS_APP --project-arn arn:aws:devicefarm:us-west-2:xxxxxx`
will create an upload that can successfully complete. 

Note the added extension in the name parameter. I did not see anything in the doc stating that the name parameter needed to end in .ipa

**Comment by JordonPhillips** [comment]
Is the name the only thing that has changed? I think it's reasonable to expect an `ipa` file, but I agree the docs could be more explicit.

**Comment by otusweb** [comment]
yes, that was the only thing I changed from what i can remember

**Comment by jschwarzwalder** [comment]
Resolved.

**Comment by justnance** [comment]
@jschwarzwalder - Thanks for the update.  Our API reference documentation now shows:

[**name**](https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_CreateUpload.html)

> The upload's file name. The name should not contain the '/' character. If uploading an iOS app, the file name needs to end with the .ipa extension. If uploading an Android app, the file name needs to end with the .apk extension. For all others, the file name must end with the .zip file extension.
> 
> Type: String
> 
> Length Constraints: Minimum length of 0. Maximum length of 256.
> 
> Required: Yes

Closing issue.
