### ISSUE TITLE
Downloading MariaDB audit log often results in errors

### ISSUE THREAD

**Issue by matsev** [aws/aws-cli#2197]
Attempting to download MariaDB audit logs using the `aws rds download-db-log-file-portion` command often results in error:

> An error occurred (InvalidParameterValue) when calling the DownloadDBLogFilePortion operation: This file contains binary data and should be downloaded instead of viewed.

I have created a script that will download the RDS audit logs from a MariaDB instance (see the script file in the [attachment.zip](https://github.com/aws/aws-cli/files/492473/attachment.zip) file).

- The script calls `describe-db-log-files` to list all file name containing `audit/server_audit.log`, i.e. including file names such as `audit/server_audit.log.5`.
- A timestamp (stored on disk) is used so only files that have been modified since the last download are downloaded, c.f. "Last Written" timestamp in the RDS console.
- [jq](https://stedolan.github.io/jq/) is used to extract the log file names.
- The files are downloaded by executing the `aws rds download-db-log-file-portion` command and they are stored to the `/var/log/rds-audit-logs` folder.
- To avoid problems with file concatenation, paging, etc the audit log files are downloaded in their entireties. Any existing files will be overwritten.

Observations:
- Selecting the "view" option the very same RDS instance using the AWS Console -> RDS -> Instances -> Logs sometimes succeeds, sometimes fail with a similar error, e.g.
> This file contains binary data and should be downloaded instead of viewed. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: ########)
- Selecting the "download" option on the very same RDS instance from the RDS console successfully downloads the log, despite that the `describe-db-log-files` command and the "view" option from the RDS section in the AWS Console fails.

Debug log (created by executing `download-rds-audit-logs.sh eu-west-1 ibes-test-rds-ppe-mdb >>debug.log 2>&1` can be found in the [attachment.zip](https://github.com/aws/aws-cli/files/492474/attachment.zip). 

```
$ aws --version
aws-cli/1.10.66 Python/2.7.10 Darwin/15.6.0 botocore/1.4.56
```

**Comment by JordonPhillips** [comment]
I notice two things. First, you're using `--no-paginate` when downloading the logs. This means you will only ever download 1MB of logs since that is what RDS caps for that operation. This also applies to your list call, you'll only ever see a subset of the results when you provide that parameter and don't handle pagination yourself. Second, you need to specify `--starting-token 0` to download the whole log because by default RDS grabs the latest chunks so to download the whole thing you need to start at the beginning.

**Comment by matsev** [comment]
@JordonPhillips Thanks for the feedback. 

Do I need to handle paging when I use `--starting-token 0`? In the [documentation](http://docs.aws.amazon.com/cli/latest/reference/rds/download-db-log-file-portion.html) it is stated that `Multiple API calls may be issued in order to retrieve the entire data set of results.`, however in the [example](http://docs.aws.amazon.com/cli/latest/reference/rds/download-db-log-file-portion.html#examples) it seems like just specifying `--starting-token 0` and execute a single call would suffice.

The bash script has been modified like you suggested (see below), but the main problem still remains. Calling `download-db-log-file-portion` results in `An error occurred (InvalidParameterValue) when calling the DownloadDBLogFilePortion operation: This file contains binary data and should be downloaded instead of viewed.` For details, please see the attached [debug.log.zip](https://github.com/aws/aws-cli/files/494669/debug.log.zip). Sometimes I get a similar error when choosing `view` log in the RDS instances part of the AWS Console, but not always.

```
function fetchAuditLogFileNames() {
    describeAuditLogs=$(aws rds describe-db-log-files \
        --region "$awsRegion" \
        --db-instance-identifier "$rdsInstanceId" \
        --filename-contains audit/server_audit.log \
        --starting-token 0 \
        --file-last-written="$latestAuditLogTimestamp"
    )
    auditFiles=$(echo $describeAuditLogs | jq -r '.DescribeDBLogFiles[].LogFileName')
}
```

```
function downloadAuditLogs() {
    if [ -n "$auditFiles" ];
    then
        # TODO global error handling should be used, but we frequently get InvalidParameterError here.
        set +e

        while read -r auditFile; do
            echo "Downloading: $auditFile"
            local fileName=$(echo "$auditFile" | cut -d '/' -f 2)
            aws rds download-db-log-file-portion \
                --region "$awsRegion" \
                --db-instance-identifier "$rdsInstanceId" \
                --log-file-name "$auditFile" \
                --starting-token 0 \
                --output text \
                > "$auditLogDir/$fileName"
        done <<< "$auditFiles"

        # Restore global error handling
        set -e
    else
        echo "No audit logs created since: $latestAuditLogTimestamp"
    fi
}
```

Side note, I found the `rds:DownloadCompleteDBLogFile` privilege in IAM. However, I have not found a corresponding AWS CLI command. Are there any plans to add that to AWS CLI?

**Comment by JordonPhillips** [comment]
@matsev The CLI will handle pagination for you unless you specify `--no-paginate` or one of the hidden service paging params. Regarding the permission, the names of permissions do not always map 1-1 to api calls.

Beyond what I've already suggested, I'm not sure. I recommend you ask on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=60). They should be able to help better with api specifics.

I'm going to close out the issue here, but if you discover any issues caused by the CLI please feel free to reopen. And for the sake of future google searchers, it would also be great if you post any solution you discover.
