### ISSUE TITLE
describe-vpcs prints "IsDefault" in JSON output but correct one is lowercase 'i'

### ISSUE THREAD

**Issue by rajeshr264** [aws/aws-cli#2198]
**Issue Noticed:**
$ aws ec2 describe-vpcs 
...
 "IsDefault": true
...

Note the capital 'I' in "IsDefault". 

**Expected outcome**
The correct syntax is 'isDefault'. 

Reference:
http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-vpcs.html

**Info**
$ aws --version
aws-cli/1.10.66 Python/2.7.10 Darwin/15.0.0 botocore/1.4.56

**Comment by JordonPhillips** [comment]
The referenced doc page shows the response casing as `IsDefault`.

**Comment by jamesls** [comment]
The response does show `IsDefault`.  However keep in mind that the `--filters` uses `isDefault`.  I confirmed that this is documented correctly and everything is working as expected.  I'm going to go ahead and close out the issue.
