### ISSUE TITLE
Uploads to s3 fail when run from cron

### ISSUE THREAD

**Issue by gjanz** [aws/aws-cli#2199]
I'm having trouble with uploads of bz2 files (backups), but it only seems to occur when run from the cron daemon. When running from a prompt (via ssh) they complete without an issue. I believe this to be the same problem from #1411.

There doesn't seem to be an error, or a error status returned to the bash script.

A debug log is at https://gist.github.com/gjanz/115adbf6f126a66e20d9f1e25ff46bff

I've also tried using s3api put-object, and I'm getting the same effect.

**Comment by JordonPhillips** [comment]
I'm not seeing any failure in those logs. What's happening when it fails?

**Comment by gjanz** [comment]
The resulting files are not intact; bunzip2 gives an error and no data is usable, and the files themselves are significantly smaller than they should be (i.e. 4Mb instead of 8.8Mb).

I thought it was a multi-part upload thing, but when attempting to use s3api put-object (which I understand won't use multi-part upload for files up to gig range in size) still gives similar results.

The files themselves are all smaller than 25Mb.

It baffles me how it runs perfectly if I ssh into the virtual machine and run it from a command line - either using s3 cp or s3api put-object.

**Comment by JordonPhillips** [comment]
Can you reproduce it if you try to replicate the cron environment like [this](https://serverfault.com/questions/85893/running-a-cron-job-manually-and-immediately/85906)? Also, are you modifying the file in any way while this process is happening?

**Comment by gjanz** [comment]
Thank you. Apologies for the wasted time; file modification will be the problem. Looking at the time stamps on the files, the cron job to create the archives isn't finishing before the s3 upload occurs. The timing wasn't allowing for a low cpu virtual machine, and this is why it always works when I run it. Off to integrate and rewrite the backup scripts so this isn't possible.

**Comment by JordonPhillips** [comment]
Glad to help!
