### ISSUE TITLE
aws codecommit list-branches --cli-input-json nextToken doesn't work

### ISSUE THREAD

**Issue by hprudent** [aws/aws-cli#2207]
I'm studying this CLI, and has a part that simply doesn't work.

Looking into --generate-cli-skeleton I should be able to use nextToken.

```
aws codecommit list-branches --generate-cli-skeleton 
{
    "repositoryName": "", 
    "nextToken": ""
}
```

So I retrieve a next-token limiting the output.

```
aws codecommit list-branches --repository-name study-101.01 --max-items 2 --region us-east-1                                                                                                                                           master
{
    "NextToken": "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAyfQ==", 
    "branches": [
        "master", 
        "cli-dev-json"
    ]
}
```

And  try to use into the --cli-input-json and the output is not limited.

```
aws codecommit list-branches --cli-input-json '{"repositoryName":"study-101.01","nextToken":"eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAyfQ=="}' --region us-east-1                                                    master
{
    "branches": [
        "master", 
        "cli-dev-json", 
        "dev", 
        "cli-dev"
    ]
}
```

**Comment by hugoprudente** [comment]
Looks like the list-repositories has a similar problem, may or may not be related, in this case, the token was unable to be parsed.

**Comment by jamesls** [comment]
The output of the `NextToken` needs to be paired with the `--starting-token` arg.  The CLI adds additional metadata into the next token that needs to be transformed before sending to the service.  If you use the `nextToken` argument directly, then the CLI will pass that value directly to the service which won't understand the CLI specific next token.

The only caveat is you have to use `--starting-token`.  There's no support for `--starting-token` being specified in the CLI input json file.

If you do want to manually paginate, you'll need to turn off pagination entirely in the CLI: `aws service command --max-items 1 --no-paginate`.  The token that comes back can then be used with CLI input json.  Note that this won't be possible until the bugfix https://github.com/aws/aws-cli/pull/2223 is merged.

Let me know if you're still having issues with this.

**Comment by hugoprudente** [comment]
So only for understanding the CLI input json has a parameter that is useless till bugfix #2223.

And will be not the best solution as I see, because using a command without json I only need to provide the NextToken from a previous command to the --starting-token and will work as I charm.

Example:

```bash
~ ❯❯❯ aws codecommit list-branches --region us-east-1 --max-items 1  --cli-input-json '{"repositoryName":"study-101.01"}'
{
    "NextToken": "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAxfQ==",
    "branches": [
        "master"
    ]
}
~ ❯❯❯ aws codecommit list-branches --region us-east-1 --max-items 1  --cli-input-json '{"repositoryName":"study-101.01"}' --starting-token "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAxfQ=="

{
    "NextToken": "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAyfQ==",
    "branches": [
        "cli-dev-json"
    ]
}
~ ❯❯❯ aws codecommit list-branches --region us-east-1 --max-items 1  --cli-input-json '{"repositoryName":"study-101.01"}' --starting-token "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAyfQ=="

{
    "NextToken": "eyJuZXh0VG9rZW4iOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAzfQ==",
    "branches": [
        "00-first"
    ]
}

```
Why doesn't change the json to work with starting-token instead next-token?

**Comment by jamesls** [comment]
> Why doesn't change the json to work with starting-token instead next-token?

We'd still want to support next-token, it is a valid thing to specify if you're manually paginating without the CLI's help.

We could look into *also* supporting starting token, but the basic reason we don't know is that the cli input json only works with parameters that map directly to the API calls for the service.  Any CLI specific arguments aren't supported in that JSON file.  Similar to how you can't specify `--endpoint-url, --debug, --query, --no-verify-ssl, etc` in the CLI input json file, you also can't provide `--starting-token`.

It is an interesting idea though, especially when you consider things like supporting `--query` in the CLI input json.  It would serve as a more complete and self contained specification of how to invoke the CLI.

In the meantime, #2223 has been merged and will go out in the next CLI release.

**Comment by hugoprudente** [comment]
OK Thanks!
