### ISSUE TITLE
Documentation: Warning about ec2 move-address-to-vpc

### ISSUE THREAD

**Issue by sleemanj** [aws/aws-cli#2210]
The documentation does not mention about move-address-to-vpc that the move can take a long time (currently I have an IP address still in MovingToVpc status for more than 24 hours), during which the IP can not be managed.

A simple warning in the documentation that moving an IP may take a long period of time would be of use to users.

**Comment by jamesls** [comment]
Thanks for the feedback.  Was the elastic IP already allocated to your account for more than 24 hours?  Just want to double check that wasn't the condition you were hitting.

**Comment by sleemanj** [comment]
Yes I had that elastic IP for... 2 or maybe 3 years I think.

**Comment by jschwarzwalder** [comment]
Resolved

**Comment by justnance** [comment]
@jschwarzwalder - Thanks for the update.  Our documentation now shows: 

>[The Elastic IP address must be allocated to your account for more than 24 hours, and it must not be associated with an instance. After the Elastic IP](https://docs.aws.amazon.com/cli/latest/reference/ec2/move-address-to-vpc.html)

Closing issue.
