### ISSUE TITLE
unable to set credentials 

### ISSUE THREAD

**Issue by pranshu1992** [aws/aws-cli#2212]
$ sudo aws configure

AWS Access Key ID [None]: ####
AWS Secret Access Key [None]: #####
Default region name [None]: ####
Default output format [None]: ####

 $ aws configure list

      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None

Tried it many times still doesn't work for me. Please help. Any suggestion is helpful.

**Comment by igmar** [comment]
AWS credentials set with aws configure are per user. The sudo makes it a config for root, while the list is done as a non-root user.

**Comment by pranshu1992** [comment]
@igmar - Thanks you for your comment I see what happened here. When i do a sudo I do see the credentials set. Just curious should I actually set it as a root user or do it normally ? When I do it normally i get an permission denied message.

**Comment by jamesls** [comment]
It will depend on your use case.  It will use `$HOME/.aws/credentials` so if you run it as a non-root user it will create the credentials file in `~/.aws/config`.

Sounds like there's no issues with the CLI so I'm going to go ahead and close this issue.  If you still have questions about how to configure the CLI, feel free to stop by our [gitter channel](https://gitter.im/aws/aws-cli).
