### ISSUE TITLE
changed behavior: aws s3 cp --recursive yields error status code even when all files were copied

### ISSUE THREAD

**Issue by npeer2004** [aws/aws-cli#2214]
Recursive copying yields exit code 1, even when all files have been copied successfully. This is a change from earlier versions.

Example:
```
$ aws s3 cp s3://my_bucket/ . --recursive
$ echo $?
1
```

**Comment by mariotacke** [comment]
I posted a related issue about this yesterday: #2213

**Comment by kyleknap** [comment]
@npeer2004 I was not able to reproduce. I was getting a rc of 0 everytime I did a recursive download.

Could you do the following to help us debug:
1) Provide debug logs for the command you ran. You can do so by appending ``--debug`` to the command you ran.
2) Try running the command ``--only-show-errors`` and see if there is any output from that.

**Comment by npeer2004** [comment]
Thanks for looking into this. I also can't reproduce now, although it happened numerous times with 1.11.0.
If this happens again, I'll reopen with the debug output.
