### ISSUE TITLE
how to find a s3 bucket is having sse enabled or not ? 

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2215]
how to find a s3 bucket is having sse enabled or not ?

**Comment by igmar** [comment]
You need to look at the bucket policy for that.

**Comment by jamesls** [comment]
Specifically `s3api get-bucket-policy`.  For individual objects, you can use `s3api head-object`.

**Comment by mkaja** [comment]
thanks James
i see in some buckets its having , output 2 is clear that bucket is not having sse enabled.
from output 1 and 3 is quite confusing to conclude which is having sse enabled.

output 1 : 
{
    "Policy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"AllowAll\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::acc:user/buck-name\"},\"Action\":[\"s3:Put*\",\"s3:Get*\",\"s3:Restore*\",\"s3:Delete*\",\"s3:List*\"],\"Resource\":[\"arn:aws:s3:::buck-name\",\"arn:aws:s3:::buck-name/*\"]}]}"
}

output 2 :
A client error (NoSuchBucketPolicy) occurred when calling the GetBucketPolicy operation: The bucket policy does not exist

output 3 ;

{
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"S3PolicyId1\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedObjectUploads\",\"Effect\":\"Deny\",\"Principal\":\"*\",\"Action\":\"s3:PutObject\",\"Resource\":\"arn:aws:s3:::buck-name/*\",\"Condition\":{\"StringNotEquals\":{\"s3:x-amz-server-side-encryption\":\"AES256\"}}}]}"
}
