### ISSUE TITLE
pipe output of aws s3 cp fails

### ISSUE THREAD

**Issue by daanemanz** [aws/aws-cli#2217]
When trying to pipe a file to `openssl` we encountered the following issue when using `awscli 1.11.0`

```
aws s3 cp s3://path/to/encrypted/file >(openssl aes-256-cbc -a -d -out decrypted_file -pass file:/path/to/password/file )
download failed: s3://path/to/encrypted/file to ../dev/fd/63 [Errno 29] Illegal seek
error reading input file
```

On version `1.10.67` we did not encounter this failure, and the encrypted file was decrypted just fine.

Relevant system info:
```
# uname -a
Linux ip-10-10-5-219 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
# openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

```
# aws --version
aws-cli/1.11.0 Python/2.7.6 Linux/3.13.0-36-generic botocore/1.4.58
```

**Workaround**: downgrade `awscli` to `1.10.67`.

**Comment by JordonPhillips** [comment]
I notice you're omitting the "-" that signals to send the output to stdout. Is that a direct copy of what you were using?

**Comment by daanemanz** [comment]
@JordonPhillips this is indeed a direct copy of what we're using -- note that it works fine with `awscli==1.10.67`.

**Comment by JordonPhillips** [comment]
Ah, maybe there's some confusion on my part so let me clarify. Is that openssl command returning a file path to be written to? If not, the format for streaming output is `aws s3 cp s3://some/key -` emphasis on the `-`.

**Comment by daanemanz** [comment]
It is -- I added the `-out decrypted_file` part in the `openssl` command which reflects what we do in our case.

I just confirmed that the command is successful by rewriting it to
```
aws s3 cp s3://path/to/encrypted/file - | openssl aes-256-cbc -a -d -out decrypted_file -pass file:/path/to/password/file```

However the previous version -- using ` >( openssl etc)` instead of `- | openssl etc` -- used to work on `1.10.67`, so I'm wondering what changed so that that doesn't work anymore.

**Comment by JordonPhillips** [comment]
We changed the back end of the `cp` command pretty thoroughly, but if what is returned looks like a normal file I'm not sure why it would break. Could you post the `--debug` output (or at least the full traceback)?

**Comment by JordonPhillips** [comment]
I get a slightly different error when reproducing the issue: 

```
download failed: s3://some/key to ../dev/fd/12 File or stream is not seekable.
```

So it seems like the file is presenting itself as a seekable file, but actually isn't

**Comment by daanemanz** [comment]
Here's what I got by switching on `--debug`:

```
2016-10-03 16:42:36,566 - Thread-5 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=0, {'offset': 0}) done waiting for dependent futures
2016-10-03 16:42:36,566 - Thread-5 - s3transfer.tasks - DEBUG - Executing task IOWriteTask(transfer_id=0, {'offset': 0}) with kwargs {'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7fd2197f2550>, 'offset': 0}
2016-10-03 16:42:36,567 - Thread-5 - s3transfer.tasks - DEBUG - Exception raised.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/download.py", line 563, in _main
    fileobj.seek(offset)
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/utils.py", line 323, in seek
    self._open_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/utils.py", line 308, in _open_if_needed
    self._fileobj.seek(self._start_byte)
IOError: [Errno 29] Illegal seek
```

Hope that helps!

**Comment by JordonPhillips** [comment]
Looks like this applies generally to FIFO files

**Comment by srinicreddy** [comment]
Wondering if I can send data from named pipe to S3 using CLI? Noticing it was done as output from S3 I was looking other way round.
