### ISSUE TITLE
`aws elb describe-load-balancers` does not list `application` type load balancers

### ISSUE THREAD

**Issue by ShahBinoy** [aws/aws-cli#2224]
`aws elb describe-load-balancers` command only lists the classic type load balancers.

**Comment by ShahBinoy** [comment]
Found out that there is an `aws elbv2` for ALBs

**Comment by saikojosh** [comment]
Well I'm glad I found this issue. I couldn't figure out why my only load balancer was not showing up. For anyone who comes after me, the documentation for `elbv2` is here: http://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-load-balancers.html

**Comment by keltonkowalchuk** [comment]
I'm trying to describe load balancers for types "application" and "classic", but it seems that you can only list "classic" using `elb`, and "application" using `elbv2`. Is there not a way to retrieve both from `elbv2`?

**Comment by saikojosh** [comment]
Nope. Doesn’t appear to be possible.

**Comment by prensoni0143** [comment]
can we list ELB and ALB together?

**Comment by dannykansas** [comment]
Adding my +1 to the pile. 

We ran into this issue while trying to audit our TLS policy versions; it'd be great to not have two separate APIs that contain this information.

**Comment by darrenoc3** [comment]
+1... Its absurd that you have to query two different endpoints, with two different response types, to get all the ELBs.

**Comment by ElijahLynn** [comment]
Wowzers, thanks for this issue! I couldn't figure this out, I was messing with the --no-paginate option etc. Couldn't get it working. Then found this and tried `aws elbv2 describe-load-balancers` and POW, the missing children have been found!

**Comment by boompig** [comment]
In the year 2023, I don't think classic load balancers can even be created. But there's so much documentation and resources online describing how to perform tasks with `aws elb`. Can the AWS devs at least add a warning in the CLI that this API is deprecated, or lists only classic load balancers, or something to indicate that this will not do what you expect it to do?

**Comment by leroylim20** [comment]
> In the year 2023, I don't think classic load balancers can even be created. 


FYI, as of 24 Jul 2023, you still can create classic load balancers
