### ISSUE TITLE
Unknown options: --no-follow-symlinks

### ISSUE THREAD

**Issue by chadhobson** [aws/aws-cli#2228]
Trying to do an "aws s3 cp" with a --no-follow-symlinks option and getting this error below. Also including every other thing I can think of. What am I missing here?

`Unknown options: --no-follow-symlinks`

aws --version  ...

`aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-98-generic`

aws s3 cp help ... **nothing about --no-follow-symlinks**

`SYNOPSIS
            cp <LocalPath> <S3Path> or <S3Path> <LocalPath> or <S3Path> <S3Path>
          [--exclude <value>]
          [--content-encoding <value>]
          [--sse]
          [--storage-class <value>]
          [--expires <value>]
          [--no-guess-mime-type]
          [--recursive]
          [--website-redirect <value>]
          [--grants <value> [<value>...]]
          [--content-language <value>]
          [--content-disposition <value>]
          [--quiet]
          [--cache-control <value>]
          [--content-type <value>]
          [--include <value>]
          [--acl <value>]
          [--dryrun]`

Web docs for version latest version (showing an older version 1.11.2 but we'll go with it) definitely show --no-follow-symlinks as an option...

http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

`cp
<LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
[--dryrun]
[--quiet]
[--include <value>]
[--exclude <value>]
[--acl <value>]
[--follow-symlinks | --no-follow-symlinks]
[--no-guess-mime-type]
[--sse <value>]
[--sse-c <value>]
[--sse-c-key <value>]
[--sse-kms-key-id <value>]
[--sse-c-copy-source <value>]
[--sse-c-copy-source-key <value>]
[--storage-class <value>]
[--grants <value> [<value>...]]
[--website-redirect <value>]
[--content-type <value>]
[--cache-control <value>]
[--content-disposition <value>]
[--content-encoding <value>]
[--content-language <value>]
[--expires <value>]
[--source-region <value>]
[--only-show-errors]
[--page-size <value>]
[--ignore-glacier-warnings]
[--force-glacier-transfer]
[--metadata <value>]
[--metadata-directive <value>]
[--expected-size <value>]
[--recursive]`

**Comment by kyleknap** [comment]
1.11.2 is not an older version. It is the latest version of the CLI. You will need to upgrade your version of the CLI to be able to access ``--no-follow-symlinks``. How did you install the CLI previously? Here is a guide about the installation process for the CLI: http://docs.aws.amazon.com/cli/latest/userguide/installing.html. It has some information about upgrading.

**Comment by chadhobson** [comment]
Too early in the AM. My brain was evaluating the version number as a decimal. All sorted out now. Thanks!

**Comment by kyleknap** [comment]
No worries. Glad it works now. Closing.
