### ISSUE TITLE
Setting up CodeCommit for eb init is not optional

### ISSUE THREAD

**Issue by hayd** [aws/aws-cli#2232]
Previously (in awsebcli=3.7.8), I could create a directory, `eb init`, and start using the tool without having to install any source (or set anything up).

It seems that in the update to 3.8.0 has made this no longer work, I now see the following error:

```
$ mkdir foo
$ cd foo
$ eb init
# select the options e.g. region, application, platform, platform version
# note: in my usecase these are pre-existing applications
...
Cannot setup CodeCommit because there is no Source Control setup
$ 
```

This used to work in 3.7.8.
Note: if I init on 3.7.8, then upgrade `awsebcli` then the `eb` commands work fine.

**Comment by kyleknap** [comment]
I would recommend asking your question on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=86). This repository is for the AWS CLI and I think your question is about the EB CLI, which is a completely different tool.

**Comment by hayd** [comment]
Okay... there's no link on the pypi for where that AWS product should have issues reported.

**Comment by truonghuy** [comment]
The error returned with version 3.8.7. The 2nd eb init displays the error "Cannot setup CodeCommit because there is no Source Control setup, continuing with initialization".

**Comment by JuanjoSalvador** [comment]
With EB CLI 3.9.0, when I run `eb init` I get the same message.

**Comment by RSid** [comment]
The above workaround worked for me...sometimes. If I select IIS as a platform, it requires CodeCommit again when I try to select a version.

**Comment by inspiralpatterns** [comment]
it worked really nice, but I can see that the message still is here. Any explanation about this?
![screen shot 2017-08-08 at 09 35 44](https://user-images.githubusercontent.com/8710333/29061175-09b76f02-7c1d-11e7-92d9-c7b2f5638d3b.png)

**Comment by carmenalbu** [comment]
I have the exact same problem as @inspiralpatterns. Can anyone help us? 

Immediately after I enter "y" on the last question it returns "ERROR: API Call unsuccessful. Status code returned 401"

Thanks

**Comment by kmturley** [comment]
If you read the source code from the tool at:
https://pypi.python.org/packages/2c/77/9ade0e1455d9b55cb1a48cdf7f789fe14c19a7f2548edee4af47495bda5d/awsebcli-3.12.1.tar.gz#md5=c5c48038e2b80484b1841d420698a992

You see if you set the platform then it forces interactive mode to be disabled:

```
        if self.app.pargs.platform:
            self.force_non_interactive = True
```

So try using:
`eb init my-project-name --region us-east-1 --platform "64bit Amazon Linux 2017.09 v2.8.3 running Docker 17.06.2-ce"`
