### ISSUE TITLE
S3 signature_version setting does not work outside of default profile

### ISSUE THREAD

**Issue by jhalterman** [aws/aws-cli#2236]
When attempting to use the s3.signature_version setting in anything but the default profile, it does not work:

```
[aws-foo]
s3 =
    signature_version = s3v4
```
..
```
aws s3 --profile aws-foo ...
```

V2 auth is used when it should be V4, even when setting signature_version in the [default] profile as well.

**Comment by JordonPhillips** [comment]
In the config file, non-default profiles are denoted with `[profile profilename]`. So for instance if you had an empty configuration for your profile and ran `aws configure --profile aws-foo` or `aws configure set s3.signature_version s3v4` it would set it up that way.

**Comment by scottw-finao** [comment]
if I try "aws configure set s3.signature_version s3v4" I get an error saying the valid choices are 'list'
