### ISSUE TITLE
aws s3 access with email

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2238]
is it possible to give access to s3 buckets for users not in an aws account to give access with their email ids ? 

aws s3api put-bucket-acl --bucket bucket-name and email address ?

**Comment by JordonPhillips** [comment]
There is no way to do this, aside from having them set up an aws account. If you would like that ability, you can ask for it on the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=24)
