### ISSUE TITLE
'aws ec2 describe-instances --query' doesn't work in ZSH

### ISSUE THREAD

**Issue by hbarcelos-revmob** [aws/aws-cli#2242]
The following command works just fine in bash:

```
aws ec2 describe-instances \
  --filters "Name=tag:Name,Values=XXXXXXX" "Name=instance-state-code,Values=16" \
  --query 'Reservations[0].Instances[0].PublicDnsName'
```

However, if I try to run it in zsh, it gives me:

```
(eval):1: no matches found: Reservations[0].Instances[0].PublicDnsName
```

I'm running:
`aws-cli/1.11.5 Python/2.7.6 Linux/4.4.0-45-generic botocore/1.4.62`

**Comment by JordonPhillips** [comment]
I'm not able to reproduce - are you using this as part of a larger command? It seems to be trying to evaluate that query as if it were itself a command. Some searching points to inverted quotes causing issues, is what you've provided here exactly what you're using?

**Comment by hbarcelos-revmob** [comment]
No, I'm using it standalone.

**Comment by hbarcelos-revmob** [comment]
You are right, I have no control of this environment and I didn't realise there was a user-defined function shadowing the `aws` command.
