### ISSUE TITLE
Invalid S3 v4 signed request when using non-AWS endpoint

### ISSUE THREAD

**Issue by jhalterman** [aws/aws-cli#2243]
As best i can tell, when using an AWS endpoint, `aws s3` commands default to v2 request signing. But when using a non-AWS endpoint (Eucalyptus in my case), `aws s3` attempts to use v4 request signing, except that the request is missing an `x-amz-content-sha256` header which makes it invalid. 

Here's an example command that does this:

```
aws --endpoint-url http://s3.d-23.autoqa.qa1.eucalyptus-systems.com:8773/ s3 cp ExampleObject.txt s3://examples-test/
```

And here's the corresponding server-side ngrep packet capture for that command:

```
  PUT /examples-test/ExampleObject.txt HTTP/1.1..Host: s3.d-23.autoqa.qa1.eucalyptus-systems.com:8773..Accept-Encoding: identity..Content-Length: 857..Content-MD5: WZurPtLGl/HSaEJydWH9lA==..Expect: 100-continue..X-Amz-Date: 20161021T
  001844Z..User-Agent: aws-cli/1.11.6 Python/2.7.10 Darwin/14.5.0 botocore/1.4.63..Content-Type: text/plain..Authorization: AWS4-HMAC-SHA256 Credential=REDACTED, SignedHeaders=content-m
  d5;content-type;host;x-amz-date, Signature=aa2c93b491918a742a53d4fdff03c8fb75aa776269ec625a48c0a089f63d069c....    
```

The Content-MD5 header makes it look somewhat like a v2 request, but the Authorization header is that of a v4 request.

The current workaround is to explicitly configure:

```
s3 =
    signature_version = s3v4
```

...in my profile, which causes a valid v4 request that includes a `x-amz-content-sha256` to be created as expected.

Currently using awscli 1.11.6

**Comment by JordonPhillips** [comment]
Could you capture the debug logs for that? Specifically there will be a section that starts with:

`2016-10-26 10:59:50,685 - Thread-3 - botocore.auth - DEBUG - CanonicalRequest:`

What do you see there?

**Comment by jhalterman** [comment]
@JordonPhillips Here's some debug output:

```
2016-10-27 14:21:07,917 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:s3.d-23.autoqa.qa1.eucalyptus-systems.com:8773
x-amz-date:20161027T212107Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2016-10-27 14:21:07,917 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20161027T212107Z
20161027/eucalyptus/s3/aws4_request
097d018269379dbd475f8cde1acfc930b5f4bbbaeb70abe388ee2c20bfad5f31
2016-10-27 14:21:07,917 - MainThread - botocore.auth - DEBUG - Signature:
cc409c8208778fd4c437f0596774357a503b2aa9d1019463fba6c5d05f7454e6
```

**Comment by jhalterman** [comment]
> S3 does allow optional body signing

@JordonPhillips I read the docs to mean that while body signing is optional, the `x-amz-content-sha256` header is mandatory for V4. Is that not correct? From [the docs](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html):

> x-amz-content-sha256	
This header is required for all AWS Signature Version 4 requests.

**Comment by JordonPhillips** [comment]
@jhalterman yes, the header should still be present, it would just be set to `UNSIGNED-PAYLOAD`.

**Comment by subhadipghoshal** [comment]
@jhalterman I tried out your work around, but doesn't seem to work for me. I am using AWS version 1.2.9.

Is there perhaps a version barrier too?

**Comment by tbeckham** [comment]
I've hit the same issue and found this workaround. There have been no updates in a while. @JordonPhillips is this on any sort of radar to be fixed?

**Comment by udf2457** [comment]
@JordonPhillips any news on this one ?  I hit it today !

```
foo@bar:~> aws s3 presign s3://foobar/barfoo --expires-in 604800 --profile foobar
Enter MFA code for arn:aws:iam::123456789:mfa/foobar: 
```

Putting the generated URL into a web browser yields:

```
<Error>
<Code>InvalidRequest</Code>
<Message>
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
</Message>
<RequestId>9BE9B2D7C03C783C</RequestId>
<HostId>
azWoLwviEY9slSpW6bxJgWE65VddsZENyPpC6Xkf55S+pr0hg3tkm8vdBgp7L+7P0tIFyNasbhU=
</HostId>
</Error>
```

**Comment by kdaily** [comment]
@jhalterman @tbeckham @udf2457 @subhadipghoshal 

Are you still encountering this error with newer versions of the CLI?
