### ISSUE TITLE
AWS s3 cp failes when copying nearly 200 backup files

### ISSUE THREAD

**Issue by blade1989** [aws/aws-cli#2245]
We have 182 backup files, which totals to `175G`. While copying to a bucket, AWS fails with the following message:

> 2016-10-20 08:45:10,158 - Thread-10 - s3transfer.utils - DEBUG - Releasing acquire 0/None
> 2016-10-20 08:45:10,159 - Thread-3 - awscli.customizations.s3.results - DEBUG - Error processing result SuccessResult(transfer_type='upload', src=u'../backup/USER.tar.gz', dest=u's3://BUCKETNAME/backups/2016-10-20/users/USER.tar.gz') with handler <awscli.customizations.s3.results.ResultPrinter object at 0x2a7ea90>: [Errno 32] Broken pipe
> Traceback (most recent call last):
>   File "/usr/local/aws/lib/python2.6/site-packages/awscli/customizations/s3/results.py", line 576, in _process_result
>     result_handler(result)
>   File "/usr/local/aws/lib/python2.6/site-packages/awscli/customizations/s3/results.py", line 387, in __call__
>     result=result)
>   File "/usr/local/aws/lib/python2.6/site-packages/awscli/customizations/s3/results.py", line 407, in _print_success
>     self._print_to_out_file(success_statement)
>   File "/usr/local/aws/lib/python2.6/site-packages/awscli/customizations/s3/results.py", line 516, in _print_to_out_file
>     uni_print(statement, self._out_file)
>   File "/usr/local/aws/lib/python2.6/site-packages/awscli/customizations/s3/utils.py", line 410, in uni_print
>     out_file.flush()
> IOError: [Errno 32] Broken pipe
> 2016-10-20 08:45:10,191 - Thread-3 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.

This are customer backups, that need to be backup-ed ASAP. Any help is greatly appreciated.

**Comment by blade1989** [comment]
Nope. It lasted longer. But script still fails. As a work around, starting the script twice via cron.

**Comment by mattgrahamdevops** [comment]
I too am getting this with a large amount of files (and heavily nested) when using the sync command . I cant find an error when I turn debug on. I checked to see if the OOM function killed it off, but found nothing in the logs. Though, when I switched to s3cmd, it did get a OOM kill by the kernel. 

Im just using a good old fashion bash script to run the aws s3 sync command. 

aws-cli/1.11.101
Python/2.7.3
botocore/1.5.65
boto Version: 2.47.0
```
Releasing acquire 1upload: ../../../../home/jjjunearthed/prod/sites/default/files/users/public/3/8/6/9/6/5/1/2e6ce7a2-46f4-465a-9b1a-44e271b33ff1.jpg to s3://acquia-backups-for-unearthed-and-double-j/jjjunearthed/prod/sites/users/public/3/8/6/9/6/5/1/2e6ce7a2-46f4-465a-9b1a-44e271b33ff1.jpg

2017-06-13 18:48:53,715 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
```

**Comment by wilyru** [comment]
We are getting the same error. Suddenly it appeared in almost all our customers when syncing files from Windows Servers to S3 buckets.

Did you solve the problem? any clue?
Thanks!

**Comment by kdaily** [comment]
@blade1989 @wilyru @mattgrahamdevops - 

Is this still an issue? Thanks!

**Comment by blade1989** [comment]
I don't remember what I did to actually get this working... I **think** it was a networking issue. Unrelated to the `aws` cli.

**Comment by bshrinidhi** [comment]
> I too am getting this with a large amount of files (and heavily nested) when using the sync command . I cant find an error when I turn debug on. I checked to see if the OOM function killed it off, but found nothing in the logs. Though, when I switched to s3cmd, it did get a OOM kill by the kernel.
> 
> Im just using a good old fashion bash script to run the aws s3 sync command.
> 
> aws-cli/1.11.101 Python/2.7.3 botocore/1.5.65 boto Version: 2.47.0
> 
> ```
> Releasing acquire 1upload: ../../../../home/jjjunearthed/prod/sites/default/files/users/public/3/8/6/9/6/5/1/2e6ce7a2-46f4-465a-9b1a-44e271b33ff1.jpg to s3://acquia-backups-for-unearthed-and-double-j/jjjunearthed/prod/sites/users/public/3/8/6/9/6/5/1/2e6ce7a2-46f4-465a-9b1a-44e271b33ff1.jpg
> 
> 2017-06-13 18:48:53,715 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
> awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
> ```

@mattgrahamdevops How did you manage to overcome this?
