### ISSUE TITLE
s3 cli issue

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2246]
hello there,
I am planning to give a vendor s3 bucket access - he dont have his aws(iam) id in our aws account and he is not going to use anything in our acc apart from one s3 bucket. so i ran

aws s3api put-bucket-acl --bucket bucket-name --grant-full-control 'emailaddress="user@example.com"' --grant-read 'uri="http://acs.amazonaws.com/groups/global/AllUsers"'

An error occurred (UnresolvableGrantByEmailAddress) when calling the PutBucketAcl operation: The e-mail address you provided does not match any account on record.

if the user is having an aws account with his email id - user@example.com - is that enough ? or he / i need to add some more steps ?

**Comment by JordonPhillips** [comment]
The other user needs a valid aws account. If that email does reflect a valid aws account and you're still having issues, I would recommend asking about it on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).
