### ISSUE TITLE
aws ec2 import-image getting an python error -- I think so

### ISSUE THREAD

**Issue by simon-india** [aws/aws-cli#2249]
`aws ec2 import-image --cli-input-json "{  \"Description\": \”Slackware\", \"DiskContainers\": [ { \"Description\": \”Disk Description\", \"UserBucket\": { \"S3Bucket\": \”bucketname\", \"S3Key\" : \”filename\" } } ]}"
`

> Traceback (most recent call last):
>   File "/usr/local/bin/aws", line 27, in <module>
>     sys.exit(main())
>   File "/usr/local/bin/aws", line 23, in main
>     return awscli.clidriver.main()
>   File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 50, in main
>     return driver.main()
>   File "/usr/local/aws/local/lib/python2.7/site-packages/awscli/clidriver.py", line 212, in main
>     sys.stderr.write("%s\n" % e)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 122: ordinal not in range(128)

**Comment by JordonPhillips** [comment]
You've got a few unicode forward quotes in there, which is messing up all of your escaping. This should work:

```
aws ec2 import-image --cli-input-json "{  \"Description\": \"Slackware\", \"DiskContainers\": [ { \"Description\": \"Disk Description\", \"UserBucket\": { \"S3Bucket\": \"bucketname\", \"S3Key\" : \"filename\" } } ]}"
```
