### ISSUE TITLE
AWS CLI S3 Sync "warning: File has an invalid timestamp. Passing epoch time as timestamp"

### ISSUE THREAD

**Issue by NK74** [aws/aws-cli#2254]
i've got a problem with AWS CLI,

**S3 SYNC** 
aws s3 sync ~/mnt/FOLDER/ s3://bucket --delete --storage-class STANDARD_IA > LOG-bucket.txt

and cli return me "warning: File has an invalid timestamp. Passing epoch time as timestamp"

**Comment by JordonPhillips** [comment]
Some file you have has invalid timestamps. This could happen for a number of reasons, for instance Windows allows timestamps that can't be converted to unix time. You will need to find the file and fix it's timestamp.

**Comment by tracer888** [comment]
I actually started to have the same issue... how do you see the error for which one is having issues?  There are millions of files in the bucket.  How do you see which one it is flaming out on?
