### ISSUE TITLE
Unable to enforce Subnet list type in cfn template

### ISSUE THREAD

**Issue by jbenoit2011** [aws/aws-cli#2255]
Hello,

I'm writing a cloudformation template taking a subnet list as a parameter (`List<AWS::EC2::Subnet::Id>`).
Then I need to use this list as value of option `Subnets`, in namespace `aws:ec2:vpc`, to create an Elasticbeanstalk environment.
But I got this error: `Value of property Value must be of type String`
So I found out this property only accepts string. This is ok if you specify only one subnet but does not work when you specify more than 1.

As a workaround, I have to use `string` type which prevents to enforce parameter type to Subnet list. But this goes against the best practices you specify:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best-practices.html#parmtypes

So I think this property should accept list of strings instead of just string since you can specify one or more subnets.

Thanks for your help.

Julien BENOIT.

**Comment by JordonPhillips** [comment]
I'm not a cloudfront expert, I think you'll have better luck in the [cloudfront forums](https://forums.aws.amazon.com/forum.jspa?forumID=46). Feel free to reopen here if you find it's an issue with the CLI specifically or if you find the answer on the forums!

**Comment by jbenoit2011** [comment]
Okay thanks. You're right I will ask in the forums or through AWS Support.
By the way, you put the wrong tag. Problem is about Cloudformation and not Cloudfront.

**Comment by ishug86** [comment]
Did you ever get an answer of this?
