### ISSUE TITLE
Documentation bad link: Route 53 Traffic Policy

### ISSUE THREAD

**Issue by jrotenstein** [aws/aws-cli#2258]
Page:

http://docs.aws.amazon.com/cli/latest/reference/route53/create-traffic-policy.html

Bad link:

http://docs.aws.amazon.com/Route53/latest/api-reference/api-policies-traffic-policy-document-format.html

Should be:

http://docs.aws.amazon.com/Route53/latest/APIReference/api-policies-traffic-policy-document-format.html

(Sorry, I'd submit an update request but it wasn't obvious how to do this for the documentation.)

**Comment by JordonPhillips** [comment]
This looks like it came from the service model, I'll make sure it gets updated. Thanks for pointing it out!

**Comment by jschwarzwalder** [comment]
Resolved

**Comment by justnance** [comment]
@jschwarzwalder - Thanks for the update.  All the links are working as expected.  Closing issue.
