### ISSUE TITLE
more aws-cli parsing errors

### ISSUE THREAD

**Issue by johncleveland** [aws/aws-cli#2261]
I have run this aws-cli code at the command prompt and in windows powershell. 
Also **aws configure** will not run in Powershell but it will run in the command terminal. I dont know if that will be of help, but I have included screenshots of the error messages.
Here is the command:
`  aws emr create-cluster –-ami-version 3.2.1 -–instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.2xlarge InstanceGroupType=CORE,InstanceCount=5,InstanceType=m3.2xlarge -–no-auto-terminate -–ec2-attributes KeyName=MyKeyPair,AvailabilityZone=us-east-1a, InstanceProfile=EMR_EC2_DefaultRole -–bootstrap-actions Path= "s3://johnclevelandbucket/emR_bootstrap.sh", Name=CustomAction, Args=[-–rstudio,-–rexamples,-–plyrmr,–-rhdfs] -–steps Name=HDFS_tmp_permission,Jar="s3://elasticmapreduce/libs/script-runner/script-runner.jar",Args= "s3://johnclevelandbucket/hdfs_permission.sh" -–name "emR-example"
![aws-cli-cmd](https://cloud.githubusercontent.com/assets/18667146/19791711/4ede34d6-9c89-11e6-857a-5a0c74b62b88.png)
![aws-cli-powershell](https://cloud.githubusercontent.com/assets/18667146/19791723/5de584ac-9c89-11e6-9fc3-f861f31ed0ba.png)
   `

**Comment by johncleveland** [comment]
![aws-cli-cmd](https://cloud.githubusercontent.com/assets/18667146/19791752/958fa716-9c89-11e6-971e-ac40f4c620f9.png)
![aws-cli-powershell](https://cloud.githubusercontent.com/assets/18667146/19791757/99d7f7ec-9c89-11e6-887d-5d506c9f64b6.png)

**Comment by JordonPhillips** [comment]
You have several en-dashes in your command (en: `–`, em: `-`), which are not supported by ascii. You also have some extra spaces thrown in that could be confusing the parser. Give this a try:

```
aws emr create-cluster --ami-version 3.2.1 --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.2xlarge InstanceGroupType=CORE,InstanceCount=5,InstanceType=m3.2xlarge --no-auto-terminate --ec2-attributes KeyName=MyKeyPair,AvailabilityZone=us-east-1a,InstanceProfile=EMR_EC2_DefaultRole --bootstrap-actions "Path=s3://johnclevelandbucket/emR_bootstrap.sh,Name=CustomAction,Args=[--rstudio,--rexamples,--plyrmr,--rhdfs]" --steps Name=HDFS_tmp_permission,Jar="s3://elasticmapreduce/libs/script-runner/script-runner.jar",Args="s3://johnclevelandbucket/hdfs_permission.sh" --name "emR-example"
```

**Comment by johncleveland** [comment]
Thanks, I tried the above and aws told me that I needed to have a service role So I added 
--service-role EMR_DefaultRole 
` The final code is: aws emr create-cluster --ami-version 3.2.1 --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.2xlarge InstanceGroupType=CORE,InstanceCount=5,InstanceType=m3.2xlarge --no-auto-terminate --service-role EMR_DefaultRole --ec2-attributes KeyName=MyKeyPair,AvailabilityZone=us-east-1a,InstanceProfile=EMR_EC2_DefaultRole --bootstrap-actions "Path=s3://johnclevelandbucket/emR_bootstrap.sh,Name=CustomAction,Args=[--rstudio,--rexamples,--plyrmr,--rhdfs]" --steps Name=HDFS_tmp_permission,Jar="s3://elasticmapreduce/libs/script-runner/script-runner.jar",Args="s3://johnclevelandbucket/hdfs_permission.sh" --name "emR-example"`
 but then it just returns 
`{
    "ClusterId": "j-31FVCBHN97YSJ"
} `

but no cluster is created? Does anyone know what the latter means?

**Comment by JordonPhillips** [comment]
It can take a while for the cluster to spin up, my guess is that it just doesn't show up immediately. You might try asking in the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=52) if it continues to be absent.
