### ISSUE TITLE
Update output for admin-create-user 

### ISSUE THREAD

**Issue by ghost** [aws/aws-cli#2262]
`UserStatus` are not up to date on `admin-create-user` command as there is missing `FORCE_CHANGE_PASSWORD`.

> Here is the current content for **Output**:
> 
> ```
> UserStatus -> (string)
>  The user status. Can be one of the following:
> - UNCONFIRMED - User has been created but not confirmed.
> - CONFIRMED - User has been confirmed.
> - ARCHIVED - User is no longer active.
> - COMPROMISED - User is disabled due to a potential security threat.
> - UNKNOWN - User status is not known.
> ```

**Comment by JordonPhillips** [comment]
Thanks for pointing this out, I'll make sure it gets updated.

**Comment by justnance** [comment]
@ghost - Thanks for reporting where our documentation needs improvements.  This has been re-escalated with our documentation writers.

**Comment by justnance** [comment]
The [documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserType.html) has been corrected.  closing issue.
