### ISSUE TITLE
Add command to change user status FORCE_CHANGE_PASSWORD

### ISSUE THREAD

**Issue by Domsware** [aws/aws-cli#2263]
When creating user using CLI, UserStatus is set to FORCE_CHANGE_PASSWORD.

```
{
    "User": {
        "Username": "PibeDeOro", 
        "Enabled": true, 
        "UserStatus": "FORCE_CHANGE_PASSWORD", 
        "UserCreateDate": 1477662772.246, 
        "UserLastModifiedDate": 1477662772.246, 
        "Attributes": [
            {
                "Name": "sub", 
                "Value": "XXXX"
            }, 
            {
                "Name": "email", 
                "Value": "XXXX"
            }
        ]
    }
}
```

This is a blocking state as nothing can be achieve by/with this user until password is changed. If I am not mistaking administrator do not have any action in CLI to change this UserStatus.
This is really annoying when administrator want/need to create user only for testing purposes. 

Adding a command to change this state to the next one solve this issue.

**Comment by JordonPhillips** [comment]
[You can change the password fairly simply](http://docs.aws.amazon.com/cli/latest/reference/iam/change-password.html).

**Comment by JordonPhillips** [comment]
If you have any more questions, I would recommend asking on the [iam service forums](https://forums.aws.amazon.com/forum.jspa?forumID=76). They should be able to give you more details.

**Comment by Domsware** [comment]
There is a misunderstanding as the need is not to change the password but to change UserStatus.

**Comment by JordonPhillips** [comment]
Since you opened a new issue with clarifications, lets just keep this one closed and keep discussion over there.

**Comment by Domsware** [comment]
OK!
