### ISSUE TITLE
aws-cli has problems in Powerwhell

### ISSUE THREAD

**Issue by johncleveland** [aws/aws-cli#2265]
I have a Windows 10 acer laptop. I am  having trouble with aws-cli in Powershell. 

aws configure works in the command prompt but not with the Powershell

Also if I run _aws --version_ I get code that I do not understand on Powershell. It could be the en dash and em dash, but I do not know how to control them on my machine. As far as I can tell there is a - (hyphen) key and a - (minus) key. No others.
![aws-cli_version](https://cloud.githubusercontent.com/assets/18667146/19825383/0fb5db28-9d3e-11e6-94a9-074b6aecee16.png)

**Comment by stealthycoin** [comment]
Any additional info on replicating this? I started from a fresh windows machine and installed python 2.7.12 from the msi on python.org, then did `pip install awscli`and copy/pasted your command, everything works as expected.

**Comment by johncleveland** [comment]
aws-cli/1.11.10 Python/2.7.9 Windows/8 botocore/1.4.67

this is what I get now... I do not know what has transpired since I last tried this command...thanks
