### ISSUE TITLE
Code deploy changing app name?

### ISSUE THREAD

**Issue by protometa** [aws/aws-cli#2270]
When I issue a code deploy command like so

    aws --region us-west-2 deploy register-application-revision --application-name my-notification-svc --s3-location bucket=my-bkt,bundleType=zip,key=my-notification-svc.zip

I'm getting

    An error occurred (ApplicationDoesNotExistException) when calling the RegisterApplicationRevision operation: No application found for name: my-Trigger-svc

A `my-notification-svc` app does exist, but the command appears to have swapped out `notification` in the name for `Trigger` somehow. What could possibly be causing this?

**Comment by protometa** [comment]
OK the `my-notification-svc` app had a slightly different name and didn't actually exist. This appears to be a case of an erroneous error message.

**Comment by stealthycoin** [comment]
Just to be clear it does work now that you corrected the name of the app?

**Comment by protometa** [comment]
Yes, it worked with the correct app name.
