### ISSUE TITLE
list aws users inactive for 30 days

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2271]
how to list aws users who are inactive for 30 days using aws cli ?

**Comment by JordonPhillips** [comment]
I'm not sure you can. [`list-users`](http://docs.aws.amazon.com/cli/latest/reference/iam/list-users.html) will return the last date the user logged into an aws website, but that doesn't seem to count using credentials to access the api. There also appears to be no way to filter based on that date in the api, so you would need to transform the output via some other command line tool.

For api assistance, I recommend asking on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=76).
