### ISSUE TITLE
aws ec2 for finding linux distro

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2272]
how can we check whether the linux ec2 are running ubuntu , centos,amazon using cli ?

**Comment by JordonPhillips** [comment]
The easiest way is to tag the instance with the operating system / version. You could also ssh into the instance to check. You could also get the image id for the instance and check it using [`describe-images`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html), though the detail in that response is dependent on who created the image and what information they decided to put in.

For api questions, I recommend asking on the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).

**Comment by brian-lamb-software-engineer** [comment]
its interesting that this is the only ways to pull the distro. i thought about script an ssh into it based on  the ips in the describe-instances for filter `instance-state-name` `running` results, but i really only wanted a way to get the list of distros using the cli, i wasnt ready to start scripting up stuff.   

Well thats probably what ill do anyway.
