### ISSUE TITLE
attachment.status is never "detached"

### ISSUE THREAD

**Issue by qfissler** [aws/aws-cli#2273]
A detached attachment is not an attachment.
so
`aws ec2 describe-volumes --filters "Name=attachment.status,Values=detached"`
will never return results.

**Comment by qfissler** [comment]
I see that https://github.com/aws/aws-cli/issues/1221 might help if I can get an inverse search to work.

**Comment by JordonPhillips** [comment]
That seems to be a service bug, I would recommend asking about it on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30). If you have specific volumes you're wondering about you can use [`describe-volume-status`](http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-volume-status.html), but I have a feeling that's not what you're going for.

**Comment by repl-satish-kumar** [comment]
This is what you need to try to fetch what you need. 

aws ec2 describe-volumes --filter "Name=status,Values=available"
