### ISSUE TITLE
aws ec2 us-east-2 is an invalid region choice

### ISSUE THREAD

**Issue by XXChester** [aws/aws-cli#2277]
I have created a new instance on us-east-2, configured the security groups, policies and access rules and I can see it running and access it via the browser. However, when I attempt to connect to it via the aws-cli, it tells me us-east-2 is an invalid choice for the region.

What am I missing here? 

I am running Ubuntu and aws --version results in: aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-100-generic

I am trying to connect to the instance via aws ec2 get-console-output --instance-id XXXXXXXX --region us-east-2

**Comment by JordonPhillips** [comment]
The versions of the CLI in the various linux distributions are wildly out of date. If you want to have an up-to-date CLI, you should use one of our [recommended installation methods](http://docs.aws.amazon.com/cli/latest/userguide/installing.html).

That aside, we don't hard-code regions so you shouldn't have any issues connecting to it. What errors are you getting exactly?

**Comment by XXChester** [comment]
Thanks, I realise my version is wildly out of date, I am purging the package managers version and installing via pip now. Thank you.
