### ISSUE TITLE
ssm describe-instance-information doesn't return IamRole nor Name fields

### ISSUE THREAD

**Issue by mtougeron** [aws/aws-cli#2278]
The `aws ssm describe-instance-information help` says that the `InstanceInformationList` list output will include `IamRole` and `Name` fields. I'm not sure if this is a bug in the docs or in the returned data.

```
$> aws --version
aws-cli/1.11.13 Python/2.7.12 Darwin/15.6.0 botocore/1.4.70
```

Example `aws ssm describe-instance-information` output:

```
{
    "InstanceInformationList": [
        {
            "IsLatestVersion": true, 
            "ComputerName": "REDACTED", 
            "PingStatus": "Online", 
            "InstanceId": "i-REDACTED", 
            "IPAddress": "REDACTED", 
            "ResourceType": "EC2Instance", 
            "AgentVersion": "1.2.298.0", 
            "PlatformVersion": "12.04", 
            "PlatformName": "Ubuntu", 
            "PlatformType": "Linux", 
            "LastPingDateTime": 1478651372.67
        }
    ], 
    "NextToken": "REDACTED"
}
```

**Comment by JordonPhillips** [comment]
The response information shown in the docs is only what could be returned. Generally things that don't exist just aren't in the response. If your resource has no role, no role is returned. As to why exactly different things aren't returned I can't comment. Those sorts of questions are better asked on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).

**Comment by mtougeron** [comment]
Okay, I will check with them to make sure it is an API issue and not a cli issue. If it is cli, I'll reopen.
