### ISSUE TITLE
feature required - filter option should be available for all describe-XXXX commands 

### ISSUE THREAD

**Issue by SydOps** [aws/aws-cli#2280]
Recently I am looking for a aws cli command to filter the load balancer out, but I found it doesn's have `--filter` option. 

I have no chance to check all of describe-XXXX commands.  My understand is, `--filter` option should be available for any of them.

Don't say we have `--query` option, that's not same at all.

**Comment by JordonPhillips** [comment]
Unfortunately `--query` is your only other option right now. If you would like server-side filtering, I would recommend asking for it on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
