### ISSUE TITLE
aws cli to get the list of terminated instances.

### ISSUE THREAD

**Issue by svuppala01** [aws/aws-cli#2284]
i was googling for something i'm trying to do and found this forum and thought it was helpful.i'm very new to aws and mostly use it via console.one of the things i have to do is to go in to the console and see if there are any instances that are stopped for more than a week and terminate them.i normally do it from the console manually.i've never used cli before and just started reading it.is there a way that can be done.

list the availability zone,instance ID,size,state=stopped,name of the instance,date when stopped and if it is equal to 7 then terminate it.

any help/advice will be gratly appreciated.

thanks in advance,

svuppala01.

**Comment by JordonPhillips** [comment]
I don't think there's a simple way to do it. The `StateTransitionReason` returned from a `describe-instances` but it's a string that doesn't necessarily contain a timestamp. I would recommend asking about this on the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).
