### ISSUE TITLE
Adding tags to volume/snapshot creation commands

### ISSUE THREAD

**Issue by mrabe142** [aws/aws-cli#2286]
It would be helpful to be able to specify tags for commands like "create volume", "block device mapping", and "create snapshot".  These already return tags as part of their output but there seems to be no way to set the tags when creating volumes/snapshots.

I generally use infrastructure automation tools like Vagrant and Terraform to manage instances in AWS.  If I want to tag volumes/snapshot, it is currently either a manually process or requires an involved post-processing script.

**Comment by JordonPhillips** [comment]
Creating tags is a separate operation. If you would like for the service team to allow setting them upon creation, I would recommend asking for that in the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
