### ISSUE TITLE
UnicodeEncodeError when uploading document to Amazon CloudSearch

### ISSUE THREAD

**Issue by iron59** [aws/aws-cli#2288]
Good day. I'm uploading documents to my search endpoint but one of my json files have a unicode character and it seems to be causing the CLI to throw a UnicodeEncodeError. Here's the debug log of the command:

> $ aws cloudsearchdomain --endpoint-url http://doc-twitch-data-search-7qmgdcs43ob54lkmjtet7xnj54.us-west-2.cloudsearch.amazonaws.com upload-documents --content-type application/json --documents game_json_data12000.json --debug
> 2016-11-19 09:40:06,095 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.19 Python/2.7.12 Linux/4.4.19-29.55.amzn1.x86_64 botocore/1.4.76
> 2016-11-19 09:40:06,095 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['cloudsearchdomain', '--endpoint-url', 'http://doc-twitch-data-search-7qmgdcs43ob54lkmjtet7xnj54.us-west-2.cloudsearch.amazonaws.com', 'upload-documents', '--content-type', 'application/json', '--documents', 'game_json_data12000.json', '--debug']
> 2016-11-19 09:40:06,096 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fc6afabc8c0>
> 2016-11-19 09:40:06,096 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fc6b0376578>
> 2016-11-19 09:40:06,096 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
> 2016-11-19 09:40:06,097 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/site-packages/botocore/data/cloudsearchdomain/2013-01-01/service-2.json
> 2016-11-19 09:40:06,099 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.cloudsearchdomain: calling handler <function register_retries_for_service at 0x7fc6b0c611b8>
> 2016-11-19 09:40:06,100 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: cloudsearchdomain
> 2016-11-19 09:40:06,100 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudsearchdomain: calling handler <function add_waiters at 0x7fc6afac1c80>
> 2016-11-19 09:40:06,103 - MainThread - awscli.clidriver - DEBUG - OrderedDict([(u'documents', <awscli.arguments.CLIArgument object at 0x7fc6af7c5d10>), (u'content-type', <awscli.arguments.CLIArgument object at 0x7fc6af7c5d50>)])
> 2016-11-19 09:40:06,103 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_streaming_output_arg at 0x7fc6afabced8>
> 2016-11-19 09:40:06,103 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_cli_input_json at 0x7fc6b037c488>
> 2016-11-19 09:40:06,104 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function unify_paging_params at 0x7fc6afb43aa0>
> 2016-11-19 09:40:06,106 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudsearchdomain.upload-documents: calling handler <function add_generate_skeleton at 0x7fc6afb36050>
> 2016-11-19 09:40:06,106 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudsearchdomain.upload-documents: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fc6af7c5d90>>
> 2016-11-19 09:40:06,106 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudsearchdomain.upload-documents: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fc6af7c5e10>>
> 2016-11-19 09:40:06,107 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.documents: calling handler <function uri_param at 0x7fc6b0411e60>
> 2016-11-19 09:40:06,107 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudsearchdomain.upload-documents: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fc6b03d56d0>
> 2016-11-19 09:40:06,107 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'game_json_data12000.json' for parameter "documents": <open file u'game_json_data12000.json', mode 'rb' at 0x7fc6b0430f60>
> 2016-11-19 09:40:06,107 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.content-type: calling handler <function uri_param at 0x7fc6b0411e60>
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.cloudsearchdomain.upload-documents: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fc6b03d56d0>
> 2016-11-19 09:40:06,108 - MainThread - awscli.arguments - DEBUG - Unpacked value of u'application/json' for parameter "content_type": u'application/json'
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.cli-input-json: calling handler <function uri_param at 0x7fc6b0411e60>
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.cloudsearchdomain.upload-documents.generate-cli-skeleton: calling handler <function uri_param at 0x7fc6b0411e60>
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fc6af7c5e10>>
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <function validate_endpoint_url at 0x7fc6afbddd70>
> 2016-11-19 09:40:06,108 - MainThread - botocore.hooks - DEBUG - Event calling-command.cloudsearchdomain.upload-documents: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fc6af7c5d90>>
> 2016-11-19 09:40:06,109 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
> 2016-11-19 09:40:06,109 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
> 2016-11-19 09:40:06,109 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
> 2016-11-19 09:40:06,109 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
> 2016-11-19 09:40:06,110 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python2.7/site-packages/botocore/data/endpoints.json
> 2016-11-19 09:40:06,121 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: cloudsearchdomain
> 2016-11-19 09:40:06,121 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.cloudsearchdomain: calling handler <function add_generate_presigned_url at 0x7fc6b0cb1668>
> 2016-11-19 09:40:06,122 - MainThread - botocore.regions - DEBUG - Creating a regex based endpoint for cloudsearchdomain, us-west-2
> 2016-11-19 09:40:06,122 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
> 2016-11-19 09:40:06,125 - MainThread - botocore.endpoint - DEBUG - Setting cloudsearchdomain timeout as (60, 60)
> 2016-11-19 09:40:06,125 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=UploadDocuments) (verify_ssl=True) with params: {'body': <open file u'game_json_data12000.json', mode 'rb' at 0x7fc6b0430f60>, 'url': u'http://doc-twitch-data-search-7qmgdcs43ob54lkmjtet7xnj54.us-west-2.cloudsearch.amazonaws.com/2013-01-01/documents/batch?format=sdk', 'headers': {u'Content-Type': 'application/json', 'User-Agent': 'aws-cli/1.11.19 Python/2.7.12 Linux/4.4.19-29.55.amzn1.x86_64 botocore/1.4.76'}, 'context': {'client_region': 'us-west-2', 'has_streaming_input': True, 'client_config': <botocore.config.Config object at 0x7fc6af6cffd0>}, 'query_string': {}, 'url_path': u'/2013-01-01/documents/batch?format=sdk', 'method': u'POST'}
> 2016-11-19 09:40:06,126 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudsearchdomain.UploadDocuments: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fc6af6cfed0>>
> 2016-11-19 09:40:06,128 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
> 2016-11-19 09:40:06,128 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
> POST
> /2013-01-01/documents/batch
> format=sdk
> content-type:application/json
> host:doc-twitch-data-search-7qmgdcs43ob54lkmjtet7xnj54.us-west-2.cloudsearch.amazonaws.com
> x-amz-date:20161119T094006Z
> content-type;host;x-amz-date
> 091c18fe39f0e77147b0db6d5ff15d449f3af7a602f011a4b737e031e35d7c91
> 2016-11-19 09:40:06,128 - MainThread - botocore.auth - DEBUG - StringToSign:
> AWS4-HMAC-SHA256
> 20161119T094006Z
> 20161119/us-west-2/cloudsearch/aws4_request
> d3c709b467e346745444a4d483c81416c909231bd1ec4e75eedba5281decd0a6
> 2016-11-19 09:40:06,128 - MainThread - botocore.auth - DEBUG - Signature:
> 12f9a0960d6c0009af59dd2af930edd43113ec6a6de40dd74f5c1f1076ddadab
> 2016-11-19 09:40:06,130 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
> 2016-11-19 09:40:06,131 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): doc-twitch-data-search-7qmgdcs43ob54lkmjtet7xnj54.us-west-2.cloudsearch.amazonaws.com
> 2016-11-19 09:40:07,331 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST /2013-01-01/documents/batch?format=sdk HTTP/1.1" 400 647
> 2016-11-19 09:40:07,332 - MainThread - botocore.parsers - DEBUG - Response headers: {'date': 'Sat, 19 Nov 2016 09:40:06 GMT', 'x-amzn-requestid': '274a7328-ae3c-11e6-9888-a1ae03fdeb68', 'content-length': '647', 'content-type': 'application/json; charset=utf-8', 'connection': 'keep-alive'}
> 2016-11-19 09:40:07,332 - MainThread - botocore.parsers - DEBUG - Response body:
> {"status": "error", "errors": [{"message": "[Deprecated: Use the outer message field] lexical error: invalid character inside string.\n \t"name": "Pok\u00e9mon Seek & Find\t", \t\t\t"giantbomb_id": "47767"\n (right here) ------^\n (near operation with index 566; document_id 488105)"}], "adds": 0, "__type": "#DocumentServiceException", "message": "{ ["lexical error: invalid character inside string.\n \t"name": "Pok\u00e9mon Seek & Find\t", \t\t\t"giantbomb_id": "47767"\n (right here) ------^\n (near operation with index 566; document_id 488105)"] }", "deletes": 0}
> 2016-11-19 09:40:07,332 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudsearchdomain.UploadDocuments: calling handler <botocore.retryhandler.RetryHandler object at 0x7fc6af7c5590>
> 2016-11-19 09:40:07,332 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
> 2016-11-19 09:40:07,332 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
> Traceback (most recent call last):
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 186, in main
> return command_table[parsed_args.command](remaining, parsed_args)
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 381, in call
> return command_table[parsed_args.operation](remaining, parsed_globals)
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 551, in call
> call_parameters, parsed_globals)
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 675, in invoke
> **parameters)
> File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
> return self._make_api_call(operation_name, kwargs)
> File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
> raise ClientError(parsed_response, operation_name)
> ClientError: An error occurred (DocumentServiceException) when calling the UploadDocuments operation: { ["lexical error: invalid character inside string.
> "name": "Pok\xe9mon Seek & Find ", "giantbomb_id": "47767"
> (right here) ------^
> (near operation with index 566; document_id 488105)"] }
> 2016-11-19 09:40:07,333 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
> 
> Traceback (most recent call last):
> File "/usr/bin/aws", line 27, in 
> sys.exit(main())
> File "/usr/bin/aws", line 23, in main
> return awscli.clidriver.main()
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 50, in main
> return driver.main()
> File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 212, in main
> sys.stderr.write("%s\n" % e)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 164: ordinal not in range(128)

For what it's worth, here's my locale:

> $ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Any suggestions on how to fix this? Thank you very much.

**Comment by JordonPhillips** [comment]
Looks like the source of the issue is this:

```
ClientError: An error occurred (DocumentServiceException) when calling the UploadDocuments operation: { ["lexical error: invalid character inside string.
"name": "Pok\xe9mon Seek & Find ", "giantbomb_id": "47767"
(right here) ------^
(near operation with index 566; document_id 488105)"] }
```

We then have an issue printing that error out as normal, so I'll have to look into that.

**Comment by iron59** [comment]
Any progress on this? Thank you. :)

**Comment by kdaily** [comment]
Hi @iron59,

Are you still experiencing this with a newer version of the client using Python 3, which has much better Unicode support? Thanks!
