### ISSUE TITLE
RDS add-option-to-option-group - can't add sqlserver_backup_restore

### ISSUE THREAD

**Issue by wesseljt** [aws/aws-cli#2301]
I am having an issue with adding an RDS option group (sqlserver_backup_restore) using the rds add-option-to-option-group cli command. 

See example below:

Command: aws rds add-option-to-option-group --option-group-name sql-webdb1 --apply-immediately --options OptionName=SQLSERVER_BACKUP_RESTORE,OptionSettings=[Name=IAM_ROLE_ARN,Value=t]

Error:
Invalid type for parameter OptionsToInclude[0].OptionSettings[0], value: Name=IAM_ROLE_ARN, type: <type 'unicode'>, valid types: <type 'dict'>
Invalid type for parameter OptionsToInclude[0].OptionSettings[1], value: Value=1, type: <type 'unicode'>, valid types: <type 'dict'>

Any ideas? i also tried: 
OptionSettings=[{Name=IAM_ROLE_ARN,Value=t}]

**Comment by wesseljt** [comment]
**note - works fine through the GUI

**Comment by JordonPhillips** [comment]
Try surrounding the options with quotes, like so:

```
aws rds add-option-to-option-group --option-group-name sql-webdb1 --apply-immediately --options "OptionName=SQLSERVER_BACKUP_RESTORE,OptionSettings=[{Name=IAM_ROLE_ARN,Value=t}]"
```

**Comment by wesseljt** [comment]
Perfect, that worked. Thanks!
