### ISSUE TITLE
Error when using the "aws opsworks register" command

### ISSUE THREAD

**Issue by ramesh4046** [aws/aws-cli#2309]
When trying to register an instance using the CLI, it failed with a message as
 "the JSON object must be str, not 'bytes'". 

The command that was ran:

aws opsworks register --region $REGION --infrastructure-class ec2 --stack-id $STACK_ID --local --override-hostname $INSTANCE_NAME

the JSON object must be str, not 'bytes'

aws --version
aws-cli/1.10.12 Python/3.4.3 Linux/3.13.0-101-generic botocore/1.4.3

echo $REGION
us-east-1

echo $STACK_ID
xx-xx-xx (removed the stack ID)

$ echo $INSTANCE_NAME
xxx (removed the instance name)

uname -a
Linux ip-172-16-7-149 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Additionally after further testing it had been figured out the issue is on this ( https://github.com/aws/aws-cli/blob/develop/awscli/customizations/opsworks.py ) and the suggested fix is as in the attached file. 
[opsworks.txt](https://github.com/aws/aws-cli/files/634993/opsworks.txt)

**Comment by Choms** [comment]
following this, plus the patch actually works, can someone please apply that little change?
