### ISSUE TITLE
Invalid JSON output from 'aws ec2 describe-instances'

### ISSUE THREAD

**Issue by richard-scott** [aws/aws-cli#2313]
AWS Cli version:
```
$ aws --version
aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-53-generic botocore/1.3.23
```

With the above installed, I'm running this command:
```
aws --debug ec2 describe-instances \
--filters "Name=instance-state-name,Values=running"
```

and I get this text at the top of my output:
```
ESC[3;JESC[HESC[2J{
    "Reservations": [
        {
```

When I run the same command with --debug, I don't and I can jq query the output as follows just fine:

```
aws --debug ec2 describe-instances \
--filters "Name=instance-state-name,Values=running" \
| jq -r '.Reservations[].Instances[]|.PrivateIpAddress + " " + (.Tags[]|select(.["Key"] == "Name")|.Value)'
```

With --debug mode on, I eventually get a list of IP's and Name Tags.

**Comment by kyleknap** [comment]
Interesting. I am not too sure what could be causing this. To help debug, could you provide the following information:

* Could you provide how often does this occur? Does it occur for other commands as well?
* Could you provide the debug logs that you collected?
* What operating system are you using?
* What terminal/shell are you using (i.e. bash, zsh)?

Thanks!

**Comment by richard-scott** [comment]
Answers: 

- It happens every time I run the command detailed above...  I will test for other commands and report back soon.
- I will also post more info (debug logs).
- I'm running Ubuntu Mate 16.04.
- Using the default Bash shell.

**Comment by richard-scott** [comment]
Hmm, how odd. its not doing it today. same filter, same AWS account same everything... just different output from AWS... odd.
