### ISSUE TITLE
BodyS3Location from CloudFormation

### ISSUE THREAD

**Issue by kyledecot** [aws/aws-cli#2317]
When looking at the CloudFormation documentation I see there is an option for providing an openapi (Swagger) definition but I don't see that there is an mention of it when doing `aws cloudformation create-rest-api help`. 

Is there a way of building an API using the cli while providing a openapi definition?

**Comment by jamesls** [comment]
Are you talking about creating an API gateway rest api?  If so you can use the `import-rest-api` to provide a swagger definition: http://docs.aws.amazon.com/cli/latest/reference/apigateway/import-rest-api.html

**Comment by kyledecot** [comment]
@jamesiri Yes, that's exactly what I'm talking about.
