### ISSUE TITLE
aws ec2 describe-reserved-instances / region scope

### ISSUE THREAD

**Issue by tylerbartlett** [aws/aws-cli#2319]
I am having success with pulling in any of my reservations with an az scope, but when the scope is region 'aws ec2 describe-reserved-instances' isn't pulling in data. Is this just me or is this happening for anyone else? Is there another command I should be running?

**Comment by kyleknap** [comment]
@tylerbartlett 
Could you provide what specific command (with its parameters) you are running for the success case and the failure case? Also could you provide the actual output and the expected output for those commands?

**Comment by tylerbartlett** [comment]
for instance i am using

```aws ec2 describe-reserved-instances --filters "Name=instance-type,Values=c3.2xlarge"```

and this is returned:
```
RESERVEDINSTANCES	us-east-1b	USD	X	X	8	default	c3.2xlarge	Heavy Utilization	Linux/UNIX	X	X	retired	0.0
RECURRINGCHARGES	0.0855	Hourly
RESERVEDINSTANCES	us-east-1a	USD	X	X	10	default	c3.2xlarge	Heavy Utilization	Linux/UNIX	X	X	retired	0.0
RECURRINGCHARGES	0.0855	Hourly
RESERVEDINSTANCES	us-east-1c	USD	X	X	5	default	c3.2xlarge	Heavy Utilization	Linux/UNIX	X	X	retired	0.0
RECURRINGCHARGES	0.0855	Hourly
```
I am missing data from the highlighted reservation in the picture below. It looks like the call is only missing data when the scope is region.

![screen shot 2016-12-13 at 2 21 22 pm](https://cloud.githubusercontent.com/assets/19858909/21155169/09e5f96a-c13f-11e6-97c5-96dc83bdd67f.png)

**Comment by riegel** [comment]
I am having a similar issue using the API, this is the specific API request that should return 2 reserved instances that have a scope of region.

     https://ec2.us-west-2.amazonaws.com/?Action=DescribeReservedInstances
     This Fails, scope=region

I have other accounts that have Reserved Instances with a scope of "Availability Zone" and the API works as expected with those.

     https://ec2.us-east-1.amazonaws.com/?Action=DescribeReservedInstances
     This suceeds, scope=Availability Zone

**Comment by riegel** [comment]
When I said it fails I should have been more clear the call succeeds but does not return the two reserved instance that have scope=region

**Comment by patrickvalenzuela** [comment]
I was just seeing this same exact issue, but then I noticed I was on awscli version 1.10.0. After upgrading awscli (to 1.11.32), all is well.

Region-scoped RIs were introduced very recently, so upgrading to fix this makes sense.

**Comment by SumitKumar1985** [comment]
Hi,

I am using Elastic Beanstalk and want to provide a user read only access but want to restrict that he can see only his application and only Health and Monitoring tab how can can i create such policy because read only policy shows everything but i want that user can see health and monitor tab.

**Comment by riegel** [comment]
I am using the API. I updated my version string to Version=2015-10-01 but still no region scoped reserved instances being returned.

**Comment by riegel** [comment]
just noticed this little string near the top of the documentation...

API Reference (API Version 2016-11-15)

I changed my version to 2016-11-15 an Viola they are now showing up.

**Comment by upbeta01** [comment]
Bump into this. Upgrading `awscli` solved the problem.

```
 User$ aws --version
aws-cli/1.11.49 Python/2.7.10 Darwin/14.5.0 botocore/1.5.12
```

**Comment by JordonPhillips** [comment]
It looks like this is a simple case of updating the cli to the latest version.
