### ISSUE TITLE
Allow aws cloudformation deploy to take tags

### ISSUE THREAD

**Issue by joekiller** [aws/aws-cli#2324]
A CloudFormation [CreateChangeSet][1] supports Tags however the `aws cloudformation deploy` command does not. Please update the CLI to support `--tags` while doing a `deploy`.

[1]: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateChangeSet.html

**Comment by kyleknap** [comment]
Marking as a feature request. We will need to figure out what to do in general on what to do (if anything) about the various parameters that are in ``create-change-set`` that are not in the ``deploy`` command. In the meantime, are you able to use ``create-change-set`` command instead for your use case?

**Comment by joekiller** [comment]
I'm tagging on a `create` and deploying updates using `deploy` for the update but tagging would be nice for lamda deploys.

**Comment by zodeus** [comment]
Any update on this?

**Comment by ShaunEgan** [comment]
I would also like this feature.

**Comment by aripalo** [comment]
Yes, this would be really useful, especially for Lambda deploys.

**Comment by davidrdark** [comment]
+1

**Comment by joshm91** [comment]
+1

**Comment by nlenz** [comment]
+1

**Comment by c2xbrhdj6u4qs15** [comment]
+1

**Comment by oleyka** [comment]
+1...

**Comment by absynthe** [comment]
+1

**Comment by noelmccrory** [comment]
+1

**Comment by samgurtman** [comment]
Has this been rejected? Some communication would be appreciated.

https://github.com/aws/aws-cli/pull/2620

**Comment by xu-lei-richard** [comment]
+1

**Comment by quintonm** [comment]
+1

**Comment by corrjo** [comment]
This feature would be great, can we get #2620 merged?

**Comment by davidrdark** [comment]
:shipit:

**Comment by joekiller** [comment]
:tada: @sanathkr with the follow-up!

**Comment by sanathkr** [comment]
Just followed up with AWS CLI folks. We are reeaaally close to merging this. There are no blockers at this point.

**Comment by estheban** [comment]
👍

**Comment by sanathkr** [comment]
This got merged with #3106. It should be available in the next release

**Comment by kyleknap** [comment]
Looks like the PR was merged. Closing out issue.
