### ISSUE TITLE
aws efs size cli

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2328]
can we monitor the aws efs fs size using aws cli ?

**Comment by jamesls** [comment]
Looking at their API docs, the only thing that looks like it might do this is the `describe-file-systems` operation which has the a `SizeInBytes` output: http://docs.aws.amazon.com/cli/latest/reference/efs/describe-file-systems.html

In general though, asking on the AWS forums for a given service is the best way to get a definitive answer for service related questions.  The CLI exposes a 1-1 mapping of the APIs provided from the service.
