### ISSUE TITLE
run linux command on multiple ec2 

### ISSUE THREAD

**Issue by mkaja** [aws/aws-cli#2329]
we need to run a single linux command ( ex : uptime) on 100+ ec2 servers - i read about ssm agent can do the work if the role is enabled while creating the ec2 instance . how can we do the same for servers which dont have the ssm role enabled?https://aws.amazon.com/blogs/aws/new-ec2-run-command-remote-instance-management-at-scale/

**Comment by jamesls** [comment]
Not sure, I think the best place to ask would be the AWS forums.  The SSM service team would be able to help you out there: https://forums.aws.amazon.com/forum.jspa?forumID=30&start=0
