### ISSUE TITLE
get cloudformation parameters from .txt file/s3 bucket

### ISSUE THREAD

**Issue by jk1510karti** [aws/aws-cli#2336]
Hi,

I want to pass input parameter to cloudformation properties from text file or save the text file in s3 bucket and point the s3 URL in CF properties.
Please let me know if this is possible? If yes, how to do?.  

Actually we have front end as java, the users will provide inputs from front end portal/website, we need to capture those inputs values and assign them to CF properties.

**Comment by dtimberlake** [comment]
I don't think there is currently a way of doing this.

How I would handle this situation is by creating a Lambda function that triggers on updates to either an s3 bucket or DynamoDB stream that holds the customers parameter settings.

**Comment by jk1510karti** [comment]
Hi @dtimberlake  appreciate your response. Could you please be more specific. ? can you provide some examples please ?

Let say an example. I need following inputs from user
-Instancetype 
-StackName
-Number of instance (We will use AutoscalingGroup for this).
-ProjectName
..etc. 

So the user will provide these inputs in the frontend portal which is developed in Java. And it will be passed as a parameters to the CF templates. 

Please add your comments on the above scenario.

**Comment by dtimberlake** [comment]
I created a quick [gist](https://gist.github.com/dtimberlake/8a2b47a281c8a2143ddb5d9fc412d387) to kind of show you what I meant.

My suggestion is that we carry this conversation over there, since this is really a CLI issue.

**Comment by jamesls** [comment]
Thanks @dtimberlake.

Closing in favor of the gist.
