### ISSUE TITLE
AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by SumitKumar1985** [aws/aws-cli#2339]
Hi,

I am using Elastic Beanstalk and want to provide a user read only access but want to restrict that he can see only his application and only Health and Monitoring tab how can can i create such policy because read only policy shows everything but i want that user can see health and monitor tab.

**Comment by jamesls** [comment]
Hi, these types of questions are best asked on the service teams forums (https://forums.aws.amazon.com/forum.jspa?forumID=86).  A service expert over there will be able to answer your question.
