### ISSUE TITLE
elb set-load-balancer-listener-ssl-certificate hangs, does not set

### ISSUE THREAD

**Issue by msllcm0753** [aws/aws-cli#2341]
Example from AWS documentation:
"aws elb set-load-balancer-listener-ssl-certificate --load-balancer-name my-load-balancer --load-balancer-port 443 --ssl-certificate-id arn:aws:iam::123456789012:server-certificate/my-new-certificate;"
(cli commands listed below truncated , save space, but all required options were given including the --profile {PROFILE_NAME} )

Upload ssl cert via cli:  
   "aws iam upload-server-certificate .....;"
Do verification upload of certificate, to gather required ARN:  
   "aws iam list-server-certificates ....;"
Gather details of LB for LoadBalancerName, LoadBalancerPort from output of cli and ARN ( above from list of cert ): 
   "aws elb describe-load-balancers ....;"

The aws cli for the elb  set-load-balancer-listener-ssl-certificate  hangs and does not complete. 
Work around is AWS Console Web UI, And change is immediate. 
CLI does not complete.

**Comment by jamesls** [comment]
Can you share a sanitized `--debug` log for us?  Without that I'm not really sure what went wrong . I'd double check that you've set the correct region value, but the debug logs would help confirm what went wrong.

**Comment by msllcm0753** [comment]
Please Tell Me how to Turn on Debug Logging , or Where to Find them.
I will Recreate the Process. I am having one of my SA’s under my document the Process also for internal purposes.

Noel Morrison
Sr. Systems Administrator
Operations Team
MedicaSoft LLC
Remote: Bunker Hill, WV
Phone: (304) 261-1216
noel.morrison@medicasoftllc.com<mailto:noel.morrison@medicasoftllc.com>

MOTD: My therapist says I have a preoccupation with vengeance. We'll see about that.

[cid:EB41BBEA-AD55-4167-A622-A128100670A1]

Creating Smarter Healthcare
(http://www.medicasoft.us)
[cid:DA59FBA5-B1EB-4C09-A2C4-433D6BE4EE19][cid:7A15551E-201A-4587-AB50-79625231E3DF][cid:1881FE0E-3C3C-4D61-9BC3-7C17B67C1A8E]

On Dec 22, 2016, at 14:54, James Saryerwinnie <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share a sanitized --debug log for us? Without that I'm not really sure what went wrong . I'd double check that you've set the correct region value, but the debug logs would help confirm what went wrong.

**Comment by msllcm0753** [comment]
I see the Problem. The person I was working with did not include the --profile {BLAH} to the end of his commands. it was attempting to use the default profile. When I recreated it on my machine I always use the --profile . Low and Behold it works.
