### ISSUE TITLE
CreateVpc operation: The parameter amazon-provided-ipv6-cidr-block is not recognized

### ISSUE THREAD

**Issue by jhazelwo** [aws/aws-cli#2343]
The error should indicate this is because ipv6 is not available in the specified region (not that the param is invalid).

```
$ aws ec2 create-vpc --region us-west-2 --cidr-block 10.0.0.0/16 --amazon-provided-ipv6-cidr-block

An error occurred (InvalidParameter) when calling the CreateVpc operation: The parameter amazon-provided-ipv6-cidr-block is not recognized
```

```
$ aws --version
aws-cli/1.11.34 Python/3.5.2+ Linux/4.4.0-57-generic botocore/1.4.91
```

**Comment by JordonPhillips** [comment]
Yeah, that does seem a bit unintuitive. Since that's a service error, you'll need to contact the service team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) to get it changed.
