### ISSUE TITLE
Support eb local run --volumesFrom docker image

### ISSUE THREAD

**Issue by JIoJIaJIu** [aws/aws-cli#2345]
```
$ eb --version
EB CLI 3.9.0 (Python 2.7.5)
```

`volumesFrom` Dockerrun.aws.json v2 directive don't mapped in `docker-compose.yml` locally without any warning.

It would be great if this feature will be included in next releases or maybe missed features were added in the warning message

**Comment by JordonPhillips** [comment]
The eb cli is a different tool, to get help with that you'll need to ask on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=86).
