### ISSUE TITLE
cloudformation list-stacks to return tags

### ISSUE THREAD

**Issue by stephenchu** [aws/aws-cli#2348]
According to the AWS CloudFormation API doc [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Stack.html), the `Stack` data type does have `Tags.member.N` as an attribute (among a couple other ones). However, this seems currently [not returned](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/list-stacks.html) by awscli `cloudformation list-stacks`.

The tags are also shown as a tab in the AWS web console.

Would love to have this enhancement done. Thanks!

**Comment by JordonPhillips** [comment]
The [`list-stacks`](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/list-stacks.html) operation returns a minimal description of the stack. To get more detailed information on a stack (including the tags), you'll need to use [`describe-stacks`](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stacks.html). If you have any other questions about the cloudformation api, I recommend asking on their [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=92).
