### ISSUE TITLE
[bug]decrease-stream-retention-period client APIs not matching documentation

### ISSUE THREAD

**Issue by spy-tech** [aws/aws-cli#2357]
The Amazon SDK (http://docs.aws.amazon.com/kinesis/latest/APIReference/API_DecreaseStreamRetentionPeriod.html) supports a value of `1`. 

![image](https://cloud.githubusercontent.com/assets/23215674/21609195/5acbcc64-d1c1-11e6-8ce5-247639d9b794.png)

`aws-cli` doesn't support `1` because the Python interface doesn't (see: 

https://boto3.readthedocs.io/en/latest/reference/services/kinesis.html#Kinesis.Client.decrease_stream_retention_period.)

I run:
```
aws kinesis decrease-stream-retention-period --stream-name test --retention-period-hours 1
```
I get:
```
An error occurred (InvalidArgumentException) when calling the DecreaseStreamRetentionPeriod operation: Minimum allowed retention period is 24 hours. Requested retention period (1 hours) is too short.
```
I tried this with `aws-cli/1.11.35 Python/2.7.13 Linux/4.8.15 botocore/1.4.92`.

It actually appears that none of Amazon client API (I looked at Python, Go, and Python) implementations implement the Amazon API correctly.

**Comment by JordonPhillips** [comment]
That looks like a documentation error on the service side. You can see up at the top of that linked doc page that they mention the minimum value is 24 hours.

**Comment by JordonPhillips** [comment]
I just sent a message to the service team, closing out the issue here.
