### ISSUE TITLE
Add ability to tag an Elastic Beanstalk environment when rebuilding it

### ISSUE THREAD

**Issue by lucke84** [aws/aws-cli#2363]
Sometimes it is necessary to add a newly created tag to an existing environment. 

At the moment, it seems to be only possible to tag environments at creation time. 

I'm assuming "rebuilding" an environment would trigger the same (or a very close) set of instructions as per its creation, so it'd be nice to have a `--tags` option there too.

**Comment by stealthycoin** [comment]
The cli just wraps the service teams API we aren't in control of which api calls take what arguments. You should make a feature request with the elastic beanstalk team in their
[forums](https://forums.aws.amazon.com/forum.jspa?forumID=86).
