### ISSUE TITLE
CLI doesn't work on windows with unicode profile names

### ISSUE THREAD

**Issue by soukicz** [aws/aws-cli#2366]
Hello,
CLI is using credentials from home directory but it doesn't work if this directory has unicode characters:

```
C:\Users\René Winkler>aws --version
Traceback (most recent call last):
File "aws", line 27, in <module>
File "aws", line 23, in main
File "awscli\clidriver.pyc", line 49, in main
File "awscli\clidriver.pyc", line 57, in create_clidriver
File "botocore\session.pyc", line 368, in full_config
File "botocore\configloader.pyc", line 105, in load_config
File "botocore\configloader.pyc", line 126, in raw_config_parse
File "botocore\exceptions.pyc", line 27, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 12:   ordinal not in range(128)
```
https://stackoverflow.com/questions/37904689/unicodedecodeerror-when-calling-aws-cli

**Comment by dstufft** [comment]
Are you able to see what version of botocore you have installed? If you've installed using pip then you should be able to see that information using ``pip list``. I believe that this should have been fixed by boto/botocore#861 so if you have a version older than 1.4.9 then upgrading should solve it. If you have a version of botocore >= 1.4.9 then it must be another issue.

**Comment by soukicz** [comment]
It was installed from MSI package (https://s3.amazonaws.com/aws-cli/AWSCLI64.msi). I will try to uninstall and install it from pip.

**Comment by NK74** [comment]
Same issue on Windows Server 2012 R2 with AWSCLI x64 (https://s3.amazonaws.com/aws-cli/AWSCLI64.msi).

> aws-cli/1.11.35 Python/2.7.9 Windows/2012Server botocore/1.4.92

> Traceback (most recent call last):
>   File "aws", line 27, in <module>
>   File "aws", line 23, in main
>   File "awscli\clidriver.pyc", line 54, in main
>   File "awscli\clidriver.pyc", line 223, in main
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xde' in position 58: ordinal not in range(128)

![image](https://cloud.githubusercontent.com/assets/17825769/21882780/54a70ea6-d8ac-11e6-9a05-5a4b47a91fd7.png)

But AWS CLI work perfectly with unicode characters

**Comment by dstufft** [comment]
I believe this should be fixed now with https://github.com/aws/aws-cli/pull/2374.
