### ISSUE TITLE
DynamoDB batch-write-item UnicodeEncodeError

### ISSUE THREAD

**Issue by floschliep** [aws/aws-cli#2370]
I'm trying to import a JSON file in DynamoDB using the following command:
`aws dynamodb batch-write-item --request-items file:///path/to/json/file.json`

Here's the error:
```
ParamError: Error parsing parameter '--request-items': Invalid JSON:
...
2017-01-08 15:31:55,068 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 54, in main
    return driver.main()
  File "/Library/Python/2.7/site-packages/awscli/clidriver.py", line 223, in main
    sys.stderr.write("%s\n" % e)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1751-1755: ordinal not in range(128)
```

The error seems to be caused by Chinese characters, e.g. `针织品批发`.

How would I go about importing such a file? Can DynamoDB store those characters or only as unicode? Will I need to decode them after reading them from the database (assuming I stored them encoded)?

**Comment by dstufft** [comment]
There appear to be two errors here. The first error is that your JSON is invalid, which unfortunately the error message is being obscured because when it tries to write out the exception message it fails with an encoding error. I've solved the exception that is masking the real exception in #2374, but perhaps trying to load the json file using:

```python
import json

json.loads(open("FILENAME").read())
```

Might indicate what the underlying issue is.

**Comment by floschliep** [comment]
I can successfully load the JSON file without an error.
Though I noticed every string is prefixed with a `u` (as the file contains unicode), might this be an issue?

**Comment by JordonPhillips** [comment]
I was able to put in the provided characters, so I'm inclined to think your json didn't match the dynamodb schema. That said, the printing bug should be dealt with.

**Comment by JordonPhillips** [comment]
To be clear, does your file look like this?

```json
{
    "testing-table": [{
        "PutRequest": {
            "Item": {
                "numbah": {"N": "34322321231354354325342532452345"},
                "strnum": {"S": "针织品批发"}
            }
        }
    }]
}
```

or like this:

```json
{
    u"testing-table": [{
        u"PutRequest": {
            u"Item": {
                u"numbah": {u"N": u"34322321231354354325342532452345"},
                u"strnum": {u"S": u"针织品批发"}
            }
        }
    }]
}
```

If the former, it should work. If the latter, then it wouldn't.

**Comment by floschliep** [comment]
It looked like neither of those, I got the syntax wrong. Sorry for the confusion!

**Comment by JordonPhillips** [comment]
Cool. We'll make sure to fix that error printing issue. Let us know if you have any other issues.
