### ISSUE TITLE
Why default VPC does not require Elastic IP to connect in internet

### ISSUE THREAD

**Issue by rajasekaran07** [aws/aws-cli#2371]
Hello,

I have one small query in default VPC. Why default VPC does not require Elastic IP to connect in internet. As per VPC concept even through we are running our instance in VPC public subnet without attaching elaticIP or ELB we can't connect that in internet then how it is working in default VPC.

Regards,
Raja

**Comment by dstufft** [comment]
Hello! This repository is specifically for the CLI and we don't control the various services. You'll have better luck asking your question over on the [VPC forums](https://forums.aws.amazon.com/forum.jspa?forumID=58).

**Comment by rajasekaran07** [comment]
@dstufft Thanks for your response  I am unable to create new topic in forum. Can you share github link for AWS VPC.

--Raja
