### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED for all aws commands

### ISSUE THREAD

**Issue by rguerra** [aws/aws-cli#2373]
Hi,

I am aware of the ticket:
https://github.com/aws/aws-cli/issues/1499

But the proposed solutions have not helped me solve my problem.

However I do not have certifi. Running simple commands on a Mac like
```
$aws s3 ls
```
Give me:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

I have:
OpenSSL 0.9.8zh 14 Jan 2016

I have tried updating using brew, but the problem remains.

**Comment by dstufft** [comment]
What version of Python are you using and where did you get it from? (macOS, Homebrew, Python.org installers, something else?)

**Comment by rguerra** [comment]
The version I am using is: Python 2.7.12
I got it from Homebrew.

**Comment by kyleknap** [comment]
How did you install the CLI? Was it with brew? Because if it was with brew, you may want to an official installation method such as ``pip`` or the bundled-installer as we do not manage how the brew installation methods.

**Comment by rguerra** [comment]
I reinstalled the Anaconda python version and it worked.
