### ISSUE TITLE
Tags not supported by s3api *-bucket-lifecycle

### ISSUE THREAD

**Issue by j0hnsmith** [aws/aws-cli#2376]
I'm creating lifecycle rules to delete objects based on tags, I want to use `aws s3api get/put-bucket-lifecycle` to set the rules but tags don't appear to be supported. 

Here's screenshot of a rule that uses a tag

![rule with tag](https://dl.dropboxusercontent.com/spa/jgk3u4877oqwibf/0iam_oik.png)

Here's the output of `aws s3api get-bucket-lifecycle --bucket mybucket`

![output json](https://dl.dropboxusercontent.com/spa/jgk3u4877oqwibf/nefonpsb.png)

The output doesn't show the tag.

**Comment by dstufft** [comment]
I can confirm this is the case, marking as a feature request.

**Comment by kyleknap** [comment]
@j0hnsmith I would recommend using [get-bucket-lifecycle-configuration](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-bucket-lifecycle-configuration.html) command instead. That command has support for getting the tags.

I would recommend not using ``get-bucket-lifecycle`` in general. As you can see in the help [documentation](http://docs.aws.amazon.com/cli/latest/reference/s3api/get-bucket-lifecycle.html), it is deprecated in favor of ``get-bucket-lifecycle-configuration``.

Let us know if that helps.

**Comment by j0hnsmith** [comment]
Yes it does! I was using an old version of `awscli` that didn't have that. Thanks
