### ISSUE TITLE
aws autoscaling describe-auto-scaling-instances

### ISSUE THREAD

**Issue by star3am** [aws/aws-cli#2382]
Hi I am using your latest version: https://github.com/aws/aws-cli/releases released 9 days ago 1.11.36

`# aws --version
aws-cli/1.11.36 Python/2.7.6 Linux/3.13.0-83-generic botocore/1.4.93
`

According to this API documentation: http://docs.aws.amazon.com/cli/latest/reference/autoscaling/describe-auto-scaling-instances.html

I should get returned in the results: "LaunchConfigurationName": "my-launch-config"

However, I don't get that: 

`
#aws autoscaling describe-auto-scaling-instances --instance-ids i-47cb21c8 --region eu-west-1
{
    "AutoScalingInstances": [
        {
            "ProtectedFromScaleIn": false, 
            "AvailabilityZone": "eu-west-1c", 
            "InstanceId": "i-47cb21c8", 
            "AutoScalingGroupName": "xxxxx-InvStack-16HUAN9O4UJ43-InvAutoScalingGroup-3DU235SA74I2", 
            "HealthStatus": "HEALTHY", 
            "LifecycleState": "InService"
        }
    ]
}`

Any pointers?

**Comment by kyleknap** [comment]
Could you provide debug logs from running this command? You can do so by appending ``--debug`` to the command you ran. My hunch is that the ``LaunchConfigurationName`` is not actually in the response from the service. Then as a result, the CLI will not include ``LaunchConfigurationName`` in the returned JSON structure as it does not exist in the service response.

**Comment by tchia04** [comment]
It works for me. I was able to see the LaunchConfigurationName

Here is what I am using

aws --version
aws-cli/1.11.41 Python/2.7.10 Darwin/16.3.0 botocore/1.5.4

**Comment by star3am** [comment]
Hello there, sorry for the late reply, it seems there is some edge case, if you remove an instance from an Autoscaling group and re-attach it. I am not sure if this is a bug or not, you can decide. 

i have as a work around: 
aws ec2 describe-instances (to get the instance id)
aws autoscaling describe-auto-scaling-instances --instance-ids (to get the autoscaling group name)
aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names (to get the launch configuration)
I use this to create AMI snapshots 

From the AWS Support case: 
Hello Riaan,

Thank you for contacting AWS Premium Support. My name is Bhanu and I would be assisting you on the case.

I understand you tried to find the launch configuration of an AutoScaled Instance using the "describe-auto-scaling-instances" CLI command, but the "LaunchConfigurationName" section is missing.

I used the command to describe instances in my autoscaling group was able to get the Launch Configuration Name, however if I detach the instance from the AutoScalingGroup(ASG) and attach it back, the Launch Configuration name disappears. Below is the output:

Before Detaching the Instance from the ASG:

[admin@ip-192-168-1-38 ~]$ aws autoscaling describe-auto-scaling-instances --instance-ids i-02dbxxxxxxxxxxxxx
{
    "AutoScalingInstances": [
        {
            "ProtectedFromScaleIn": false,
            "AvailabilityZone": "ap-south-1a",
            "InstanceId": "i-02dbxxxxxxxxxxxxx",
            "AutoScalingGroupName": "NetBootASG",
            "HealthStatus": "HEALTHY",
            "LifecycleState": "InService",
            "LaunchConfigurationName": "NewLCBoot"
        }
    ]
}

Instance detached and attached again to the same ASG:

[admin@ip-192-168-1-38 ~]$ aws autoscaling describe-auto-scaling-instances --instance-ids i-02dbxxxxxxxxxxxxx
{
    "AutoScalingInstances": [
        {
            "ProtectedFromScaleIn": false,
            "AvailabilityZone": "ap-south-1b",
            "InstanceId": "i-02dbxxxxxxxxxxxxx",
            "AutoScalingGroupName": "NetBootASG",
            "HealthStatus": "HEALTHY",
            "LifecycleState": "InService"
        }
    ]
}

I checked your AutoScalingGroup "mukuru-InvStack-16HUAN9O4UJ43-InvAutoScalingGroup-3DU235SA74I2" and it is associated with the LaunchConfiguration "mukuru-InvStack-16HUAN9O4UJ43-InvLaunchConfig-1EZRXASLH799Q". So, if you try the following CLI command, the Launch Configuration name should be visible.

 aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names mukuru-InvStack-16HUAN9O4UJ43-InvAutoScalingGroup-3DU235SA74I2
 
Please confirm if you had detached and re-attached the instance "i-47cb21c8" back to the AutoScalingGroup or any other changes performed on the EC2 instance.

I look forward to your response and if there's anything else I can help you with, Please let me know.

Best regards,

Bhanu Pratap P.
Amazon Web Services
