### ISSUE TITLE
aws cloudformation package generates improper s3 url for AWS::CloudFormation::Stack

### ISSUE THREAD

**Issue by justengland** [aws/aws-cli#2384]
It seems when using the package command, with a AWS::CloudFormation::Stack resource and TemplateURL with a local path. The template output generates s3 short hand rather than a url. 

Command: ``````aws cloudformation package --template-file master.yaml --s3-bucket my bucket```
Generates:
TemplateURL:
s3://lambda-build-store/aws-deploy/f94558b8c73c07eacc3ec32cd7328113.template

Needs to generate
TemplateURL:
https: //s3.amazonaws.com/lambda-build-store/aws-deploy/f94558b8c73c07eacc3ec32cd7328113.template

Code Repo
https://github.com/justengland/aws-deploy

**Comment by dtimberlake** [comment]
This fix is in develop. See #2360.

**Comment by justengland** [comment]
Sorry about the dupe
