### ISSUE TITLE
aws tokens

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-cli#2386]
is there  a equivalent of awstokens.py with aws configure?

I want to be able to generate AWS Tokens via SAML , how can I do this via aws configure?

**Comment by kyleknap** [comment]
Do you plan to use the AWS token with use of the AWS CLI?

While the AWS CLI does currently does not have built-in support for assuming a role with SAML, here is a [blog post](https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/) on how to get  the AWS CLI working with SAML.

**Comment by JordonPhillips** [comment]
Closing due to inacitivy
