### ISSUE TITLE
aws ec2 modify-instance-attribute does not work for instances created by EMR. 

### ISSUE THREAD

**Issue by abelsonlive** [aws/aws-cli#2389]
When using `aws ec2 modify-instance-attribute`, I get the following error when attempting to modify EMR instances:

```
$ aws ec2 modify-instance-attribute --instance-id 'ig-XXXXXXXXXXXXXXX'
>>> An error occurred (InvalidParameterValue) when calling the ModifyInstanceAttribute operation: Value (ig-XXXXXXXXXXXXXXX) for parameter instanceId is invalid. Expected: 'i-...'.
```

The problem seems to be that the parameter check for the `instance-id` flag in `aws ec2 modify-instance-attribute` is too strict to allow for EMR instance ids, which start with `ig-`.

**Comment by kyleknap** [comment]
I would recommend opening up an issue on the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) about this. This validation logic is happening service side so if the service team starts permitting/accounting for these instance ids, the CLI will automatically start working.

Closing issue in favor of the forums.

**Comment by abelsonlive** [comment]
Lol... it's almost like you don't work at the same company.
