### ISSUE TITLE
glacier abort-multipart-upload incorrect arguments parsing

### ISSUE THREAD

**Issue by josser** [aws/aws-cli#2399]
Hi! 
For some reason I'm getting error for some upload-id's when trying to abort-multipart-upload. 

i.e: 
```
 aws glacier abort-multipart-upload --account-id - --vault-name mongo_backup --upload-id "-Pr17goV5R6ov-zxoJShfU_6-fpuCm-YVLy1XqfQnGRjXpdFhzITWfkD_bgik8m2tSnvfEqEaqJdXFxgWEFjhBAKVVvF"
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --upload-id: expected one argument
```

Same command but with different upload-id executes without any errors. 

aws-cli version: 1.11.40
uname -a
Linux ip-172-31-18-164 3.13.0-105-generic #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.6

Thank you and sorry for bad english

**Comment by kyleknap** [comment]
@josser 

It looks like it because the value for upload-id starts with a dash. The CLI sometimes has problems identifying values that start with a dash and instead tries to treat it as a separate parameter. Try putting an equal sign between to be more explicit about parameter/value assignment:
```
aws glacier abort-multipart-upload --account-id - --vault-name mongo_backup --upload-id="-Pr17goV5R6ov-zxoJShfU_6-fpuCm-YVLy1XqfQnGRjXpdFhzITWfkD_bgik8m2tSnvfEqEaqJdXFxgWEFjhBAKVVvF"
```
That worked for me. Let me know if this helps.

**Comment by josser** [comment]
@kyleknap As you can see in my example in first comment I'm already using quotes and it's doesn't help. I think the possible reason for this may be that I'm using zsh.

**Comment by josser** [comment]
@kyleknap Yeah, working with "=". Thank you!
