### ISSUE TITLE
aws sync download failed: Max Retries Exceeded

### ISSUE THREAD

**Issue by squish102** [aws/aws-cli#2401]
I am trying to sync a 7.4TB bucket to local storage and get lots of download failed: Max Retries Exceeded.

I am using the following command line:

aws s3 sync  s3://mybucket-s3backup ./ --page-size 25 --cli-read-timeout 600 --cli-connect-timeout 600 --size-only

Version I'm running:

aws --version
aws-cli/1.11.40 Python/2.6.6 Linux/2.6.32-642.4.2.el6.x86_64 botocore/1.5.3

Thanks

download failed: s3://mybucket-s3backup/FSR-01/CA/One Offs/R12.2/MSD/p20774933_R12.MSD.C_R12_LINUX_3of5.zip to FSR-01/CA/One Offs/R12.2/MSD/p20774933_R12.MSD.C_R12_LINUX_3of5.zip Max Retries Exceeded

**Comment by kyleknap** [comment]
Could I get information on what exactly is causing the retries? The best way would be to provide a snippet of the debug logs. You can do this be appending ``--debug`` to the command that you ran.

**Comment by squish102** [comment]
I have managed to complete the download. I extended the --cli-read-timeout and --cli-connect-timeout to 1200 and that was based on the error message in the --debug. I have since lost the debug file.

Closing.
