### ISSUE TITLE
Issue with parsing SSM parameters

### ISSUE THREAD

**Issue by omahonyb** [aws/aws-cli#2405]
I was recently trying SSM, and found the following two issues with aws-cli when I copied the command from the AWS webpage:

> aws ssm send-command --document-name "AWS-UpdateLinuxAmi" --document-description "Update a Linux AMI. By default this will update distribution packages and Amazon software." --instance-ids "i-0123456789" --parameters '{"TargetAmiName":["UpdateLinuxAmi_from_{{SourceAmiId}}_on_{{global:DATE_TIME}}"],"InstanceType":["t2.micro"],"PreUpdateScript":["none"],"PostUpdateScript":["none"],"IncludePackages":["all"],"ExcludePackages":["none"],"SourceAmiId":["ami-c51e3eb6"],"InstanceIamRole":["SystemsManagerEC2Role"],"AutomationAssumeRole":["SystemsManagerAutomationRole"]}' --timeout-seconds 600 --region eu-west-1
> usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

If I leave in the --document-description I get:

> Unknown options: --document-description, Update a Linux AMI. By default this will update distribution packages and Amazon software.

If I remove this, it seems to fall apart parsing the parameters:

> "Error parsing parameter '--parameters': Expected: '=', received: ''' for input:
> '{TargetAmiName:[UpdateLinuxAmi_from_{{SourceAmiId}}_on_{{global:DATE_TIME}}],InstanceType:[t2.micro],PreUpdateScript:[none],PostUpdateScript:[none],IncludePackages:[all],ExcludePackages:[none],SourceAmiId:[ami-c51e3eb6],InstanceIamRole:[SystemsManagerEC2Role],AutomationAssumeRole:[SystemsManagerAutomationRole]}'
> ^"

Any ideas what could be wrong? New to AWS CLI to be honest.

**Comment by kyleknap** [comment]
Can you add a link to the command that you found on the website?

**Comment by omahonyb** [comment]
The command was generated on the "Run a Command" section of the Systems Manager

**Comment by jamesonwilliams** [comment]
Hi omahony, thanks for reporting this. AWS-UpdateLinuxAmi is actually an Automation document, not a Command document. AWS-UpdateLinuxAmi would be used with ssm start-automation-execution command/API. All the same, this is an interesting test case and it appears that the behavior should be improved, to provide a descriptive error message.

**Comment by stefansundin** [comment]
I have issues with spaces inside `--comment`, even if it's quoted properly. Not sure if it's related to this.

Example:

```
$ aws ssm send-command --instance-ids $INSTANCE_IDS --document-name RestartServices --comment "Restart services"
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: services
```

If I remove the space, it works.
