### ISSUE TITLE
[Question] Is there a docker image available of the cli itself?

### ISSUE THREAD

**Issue by jason-riddle** [aws/aws-cli#2416]
I couldn't find an official aws cli docker image so I came here to ask if such a thing exists?

**Comment by JordonPhillips** [comment]
We don't maintain an official docker image, no.

**Comment by mrjgreen** [comment]
Is there any reason why it wouldn't be possible to publish an image to dockerhub for the aws-cli? It would be great to have this re-opened for discussion.

I often require the aws-cli in build pipelines - with more and more build tools relying purely on docker to run the stages (circle, bitbucket, drone etc..), it would be handy to be able to pull in an official image for this.
