### ISSUE TITLE
commands create-vpc-association-authorization and delete-vpc-association-authorization are missing.

### ISSUE THREAD

**Issue by dahu33** [aws/aws-cli#2417]
The commands referenced in the documentation below are missing in the CLI...
http://docs.aws.amazon.com/cli/latest/reference/route53/create-vpc-association-authorization.html
http://docs.aws.amazon.com/cli/latest/reference/route53/delete-vpc-association-authorization.html

**Comment by stealthycoin** [comment]
You probably have an out of date version of botocore. They were added in [this commit](https://github.com/boto/botocore/commit/2e5599d3d40c42483e47f4b599bbe19f6f5fa84a#diff-af83374e99ae590b293d70198f3333e9).

Run:
`pip install --update awscli`
to update your cli version.

**Comment by dahu33** [comment]
Indeed, thanks!
