### ISSUE TITLE
Error while syncing local data to S3

### ISSUE THREAD

**Issue by Nataliya1** [aws/aws-cli#2419]
Getting the error below while trying to sync local data to s3.  The script has been in place for a couple of months and have been working great and it failed today. Appreciate any help. 
The aws -- version is
aws-cli/1.11.44 Python/2.7.9 Windows/7 botocore/1.5.7

fatal error: HTTPSConnectionPool(host='dcgis-documents.s3.amazonaws.com', port=4
43): Max retries exceeded with url: /?prefix=Septic_scans%2F&encoding-type=url (
Caused by ProxyError('Cannot connect to proxy.', error(10061, 'No connection cou
ld be made because the target machine actively refused it')))

Thanks,
Nataliya

**Comment by stealthycoin** [comment]
Can you give me more information? Can you provide the output of the cli command when the `--debug` flag is added?

**Comment by Nataliya1** [comment]
@stealthycoin Thanks for reply. The issue got resolved. The problem was that our IT department made some changes to the proxy server. Thanks, again.

**Comment by stealthycoin** [comment]
Awesome glad you got everything working.
