### ISSUE TITLE
glacier upload-archive:  default archive description should be value of --body

### ISSUE THREAD

**Issue by ghost** [aws/aws-cli#2421]
Observed on at least one version of aws-cli <= 1.11.44

If --archive-description is omitted, the actual description for that archive will be empty (according to vault inventory).  This can be a nasty surprise when attempting to restore from a multi-archive vault.

**Comment by stealthycoin** [comment]
What command/version of cli (`aws --version`) exactly are you running and how does the result differ from your expectations based on the documentation?

**Comment by mpalandra** [comment]
I don't recall exactly the version that was used for uploading; all I can say for sure is <= 1.11.44.

According to documentation (`aws glacier upload-archive help`), description is optional, and there is no mention of a default value.

How does one easily differentiate between multiple archives in a vault if all descriptions are empty?  The archive basename seems like a reasonable default to me.  At least one other uploader follows that convention:  https://github.com/MoriTanosuke/glacieruploader

**Comment by kdaily** [comment]
The documentation for [uploading an archive](https://docs.aws.amazon.com/amazonglacier/latest/dev/api-archive-post.html) describes it as such:

> When uploading an archive, you can optionally specify an archive description of up to 1,024 printable ASCII characters. S3 Glacier returns the archive description when you either retrieve the archive or get the vault inventory. S3 Glacier does not interpret the description in any way. An archive description does not need to be unique. You cannot use the description to retrieve or sort the archive list.

I agree that archives lacking a description makes it difficult to identify. The flexibility is left up to the user to come up with a scheme for managing the archives. A number of documentation pages indicate that metadata about archives is left on the client side - the main glacier documentation page suggests maintaining an index using DynamoDB.

Given the age of this and lack of activity, I'm going to close this.
