### ISSUE TITLE
Documentation: opsworks describe-elastic-load-balancers example

### ISSUE THREAD

**Issue by dumityty** [aws/aws-cli#2422]
Looks like the example output for the opsworks describe-elastic-load-balancers command (https://github.com/aws/aws-cli/blob/develop/awscli/examples/opsworks/describe-elastic-load-balancers.rst) is the same as that of the opsworks describe-apps command (https://github.com/aws/aws-cli/blob/develop/awscli/examples/opsworks/describe-apps.rst)

**Comment by stealthycoin** [comment]
Thanks for finding that. Opened #2434
