### ISSUE TITLE
presign URL results in redirect, us-west-2

### ISSUE THREAD

**Issue by devinrsmith** [aws/aws-cli#2424]
I've got a bucket in us-west-2 and have the aws cli setup for us-west-2.

Using presign

`aws s3 presign s3://bucket-name/directory/file`

it generates a URL of the form

`https://bucket-name.s3.amazonaws.com/directory/file?...&Signature=the-signature`

When uploading to the URL, it returns a 307 w/ a redirect location of

`https://bucket-name.s3-us-west-2.amazonaws.com/directory/file?...&Signature=the-signature`

The upload to this new URL fails b/c the signature doesn't match.

Am I invoking presign incorrectly? Or is presign doing something wrong?

**Comment by stealthycoin** [comment]
Can you `GET` the object using the presigned url? Does the AWS user that generates the presigned url have permission to write the object?

**Comment by devinrsmith** [comment]
In this specific case, the object doesn't exist yet. It's just a location that I'm wanting to pass off and have a client upload to. (I've successfully done this workflow w/ the java client.)

Using `aws s3 presign` with an existing object in us-west-2 and `GET` seems to work (no redirect).

The user is permissioned to write.

**Comment by stealthycoin** [comment]
How exactly are you trying to upload them?

**Comment by devinrsmith** [comment]
`curl -XPUT --upload-file file "SIGNED_URL"`

**Comment by stealthycoin** [comment]
My guess is that your CORS configuration is not correct. Given that a PUT request will issue a preflight OPTIONS request which if the bucket is not configured to handle will cause the upload to fail. Check out http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html

**Comment by JordonPhillips** [comment]
You should also make sure that your region is configured correctly. You can configure this in several ways, such as specifying it on the command line like so: `--region us-west-2`
