### ISSUE TITLE
rds describe-db-instances querying or filtering by tag

### ISSUE THREAD

**Issue by lancelakey** [aws/aws-cli#2427]
$ aws --version
aws-cli/1.11.44 Python/2.7.10 Darwin/16.4.0 botocore/1.5.7

It appears that the output of `describe-db-instances` doesn't list tags and that it's not possible to query or filter by tags. What's the simplest way to list rds instances, so I can get their instance id's and arn's, which match specific tags?

**Comment by jerm** [comment]
This seems to be a limitation within boto2 and 3.... I haven't looked at the API yet, but I imagine it's an issue therein.

**Comment by stealthycoin** [comment]
There is no way to do this with the current API, [RDS only exposes three](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Tagging.html) api calls to interact with tags.
[AddTagsToResource](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference//API_AddTagsToResource.html)
[ListTagsForResource](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference//API_ListTagsForResource.html)
[RemoveTagsFromResource](http://docs.aws.amazon.com/AmazonRDS/latest/APIReference//API_RemoveTagsFromResource.html)

You could make a feature request at the [RDS forums](https://forums.aws.amazon.com/forum.jspa?forumID=60)

Barring that you can cobble something together your self such as:
```bash
#!/bin/bash
ARNS=$(aws rds describe-db-instances --query "DBInstances[].DBInstanceArn" --output text)
for line in $ARNS; do
    TAGS=$(aws rds list-tags-for-resource --resource-name "$line" --query "TagList[]")
    MATCHES=$(echo $TAGS | python -c "import sys, json; tags = json.loads('$1'); remote = {t['Key']: t['Value'] for t in json.load(sys.stdin)}; print('$line') if len({'$line' for k, v in tags.items() if k in remote and v == remote[k]}) > 0 else ''")
    if [[ ! -z $MATCHES ]]; then
        echo $MATCHES
    fi
done
```


Which an be used like this:
I have two databases both with the tag `test: tag` and one with `name: test-1` and the other with `name: test-2`
```
(cli) ➜ ./db-by-tags.sh '{"test": "none have this"}'
(cli) ➜ ./db-by-tags.sh '{"test": "tag"}'
arn:aws:rds:us-west-2:001499081322:db:test-1
arn:aws:rds:us-west-2:001499081322:db:test-2
(cli) ➜ ./db-by-tags.sh '{"name": "test-1"}'
arn:aws:rds:us-west-2:001499081322:db:test-1
(cli) ➜ ./db-by-tags.sh '{"name": "test-2"}'
arn:aws:rds:us-west-2:001499081322:db:test-2
```

**Comment by lancelakey** [comment]
Sounds good. I'll make a feature request.

Thanks for the script too!

**Comment by umitseremet** [comment]
Hi,

Is that featured merged? When I try I still can not still tag of RDS

**Comment by nsushkin** [comment]
So, why is this closed? Has it been re-filed somewhere else or not going to be implemented?

**Comment by phils** [comment]
If anyone stumbles upon this, there's a new tagging API now, so you can do this:

aws resourcegroupstaggingapi get-resources --resource-type-filters rds:snapshot --tag-filters Key=blah

**Comment by JohnPreston** [comment]
@phils  thanks for this. Made my day <3

**Comment by CharlesLuttos** [comment]
There is some chance for this to be implemented?

**Comment by jerm** [comment]
@CharlesLuttos Yes and no. Not as a part of describe instances, because this capability literally doesn't exist in the rds API. 

However, as someone noted a couple of messages up, this can effectively be accomplished through the tagging api

to query DBs:

`aws resourcegroupstaggingapi get-resources --resource-type-filters rds:db --tag-filters Key=Level`

**Comment by CharlesLuttos** [comment]
@jerm mmm, right, i'm using boto3, needing some more information than resourcegroupstaggingapi returns.

I'll need to make two requests anyway..
