### ISSUE TITLE
Issues when revoking security rule for ::/0 IPv6

### ISSUE THREAD

**Issue by jasongfr** [aws/aws-cli#2428]
When trying to revoke a security group rule for the Anywhere ::/0 IPv6 CIDR I get a a malformed error. Here are the steps to reproduce:

 `$ aws ec2 revoke-security-group-ingress --group-id sg-123456789 --protocol tcp --port 443 --cidr "::/0"`

The error I get is:

> An error occurred (InvalidParameterValue) when calling the RevokeSecurityGroupIngress operation: CIDR block ::/0 is malformed

**Comment by stealthycoin** [comment]
It looks like you can use `--ip-permissions` which has some CidrIpv6 specific parameters.

http://docs.aws.amazon.com/cli/latest/reference/ec2/revoke-security-group-ingress.html

**Comment by jasongfr** [comment]
Thank you very much, I was able to get it to work with your suggestion.
