### ISSUE TITLE
"aws s3 cp" silently fails if local storage exhausted

### ISSUE THREAD

**Issue by cswarth** [aws/aws-cli#2430]
Copying a large file from S3 will SILENTLY fail when the local storage is insufficient to contain the file.   After the failure, the exit code indicates success and no error message is produced.

```
$ aws s3 cp s3://somebucket/largefile.iso largefile.iso
Completed 186 of 490 part(s) with 1 file(s) remaining
$ echo $?
0
$ df .
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1       8115168 6333960   1345932  83% /
```

Don't be fooled by the fact that there is still space left on the device.  `aws` is downloading the file to a temporary filename which it will rename upon success.  Upon failure, it cleans up the temporary file, but the local disk was full while the temp file was in place.

Just to be clear:
I expect an error if the copy fails.  The failure that occurred is undetectable.

**Comment by stealthycoin** [comment]
Seems reasonable to me. Marking as feature request.

**Comment by stealthycoin** [comment]
Actually, try upgrading and see what you get, it should already do this.

`pip install --upgrade awscli`

**Comment by cswarth** [comment]
Yay!  It does work in a recent version (aws-cli/1.11.44).

Previously I was running old crud from `apt-get install awscli`

**Comment by stealthycoin** [comment]
Glad it works for you!.

Yea `apt-get` we have no control over, it's quite out of date, stick with `pip` we maintain those packages.
