### ISSUE TITLE
1.11.26 - lambda outfile

### ISSUE THREAD

**Issue by itopiacloud** [aws/aws-cli#2436]
Hi - got x64 installer from https://s3.amazonaws.com/aws-cli/AWSCLI64.msi (1.11.26)

When running aws lambda invoke --outfile regardless of format used, cli reports "aws.cmd: error: the following arguments are required: outfile"

**Comment by stealthycoin** [comment]
As of right now we are on `1.11.45` so I would suggest you start with upgrading. If that does not solve your problem show us the exact command you ran, as well as adding the `--debug` flag and giving us the output of that.

**Comment by JordonPhillips** [comment]
`outfile` is a positional argument referring to a file location on disk, so for example:

`aws lambda invoke --function-name my-function /tmp/output.log`

**Comment by itopiacloud** [comment]
@stealthycoin Thanks John - now on 1.11.45 - same error:

lambda invoke --function-name greetingsOnDemand --payload "{"""name"":""John""}" c:\mnt\output.txt

lambda invoke --function-name greetingsOnDemand --payload "{"""name"":""John""}" --outfile output.txt

both come back with the same outfile message

**Comment by kyleknap** [comment]
@itopiacloud Can you share debug logs for running those commands? The first command you listed looks like it should work.

**Comment by itopiacloud** [comment]
Hiya @kyleknap - I've tried running a few lambda commands but essentially, after I include the "--payload "{"""name"":""John""}"" entry, it'll then bomb out and not let me run debug (see attached)
[lambda-error.txt](https://github.com/aws/aws-cli/files/798711/lambda-error.txt)

**Comment by stealthycoin** [comment]
Hmm which shell are you using? This works for me:
`aws lambda invoke --function-name greetingsOnDemand --payload "{\"name\":\"John\"}" output.txt`

**Comment by itopiacloud** [comment]
Windows 10, using CLI via command line or aws-shell

**Comment by JordonPhillips** [comment]
I'm still unable to reproduce this on Windows (bash, powershell, cygwin, and git bash), Linux, or macOS. If this is still an issue for you can you provide debug logs for a command where you are specifying the outfile?

**Comment by itopiacloud** [comment]
Hiya,

Since last flurry of posts, I've had to reinstall win10 with Creators Update. The suggestion by @stealthycoin 
'''

aws lambda invoke --function-name greetingsOnDemand --payload "{\"name\":\"John\"}" output.txt
```
now works when using aws-shell but not from the cli --version: aws-cli/1.11.122 Python/3.6.2 Windows/10 botocore/1.5.85

**Comment by JordonPhillips** [comment]
Powershell will require different quoting than cmd, so something like this should work:

```
aws lambda invoke --function-name greetingsOnDemand --payload '{"name":"John"}' output.txt
```

**Comment by itopiacloud** [comment]
Thanks @JordonPhillips - that works a treat.

Death to Powershell eh.

**Comment by JordonPhillips** [comment]
Awesome, glad we got it all sorted out

**Comment by aviralvishnoi** [comment]
Is it possible to achieve outfile using boto3?

**Comment by aviralvishnoi** [comment]
response = lambda_client.invoke(
        FunctionName=datalake_lambda_function,
        InvocationType='RequestResponse',
        LogType='Tail',
        Payload=create_payload_for_lambda(data, glue_iam_user_arn, bi_account_id)
    )

    result = response['Payload'].read()

Result is equivalent to outfile.
