### ISSUE TITLE
Escaping Powershell commands in UserData Property for Windows Stack

### ISSUE THREAD

**Issue by BenMitchell1979** [aws/aws-cli#2437]
I'm having a difficult time passing powershell into the build process via UserData. When I try to reference a parameter in the UserData stream - powershell tries to execute the parameter reference vs YAML replacing it as string.. 

The Parameter it calls from is generated with:
Parameters:
  BucketName:
    Type: String
    Description: 'Name of bucket for shared assets.'
    Default: 'SomeUniqueBucketName'

Build Instance!
BuildMyVM:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 'myKeySet'
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: 'ami-21414f36'
      InstanceType: t2.medium
      NetworkInterfaces:
      - DeviceIndex: '0'
        AssociatePublicIpAddress: 'true'
        SubnetId: 'subnet-#######'
        GroupSet:
        - "sg-######"
      Tags:
      - Key: Name
        Value: xxxxxxx
      - Key: SN Owner
        Value: xxxxxxx #change for your use
      UserData:
        Fn::Base64:
          !Sub |
            <powershell>
            Set-ExecutionPolicy unrestricted -Force
            New-Item c:/chef/tmp -ItemType Directory -Force
            Copy-S3Object -BucketName ${BucketName} -Key "chef-client-12.17.44-1-x64.msi" -LocalFile "c:/chef/tmp/chef-client-12.17.44-1-x64.msi"
            Start-Process c:/chef/tmp/chef-client-12.17.44-1-x64.msi /qn -Wait
            Set-Location c:/chef
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
            chef-client -z -j c:/chef/attributes.json -o mybuild::windows_node -L c:/chef/chef-client.log -l info
            </powershell>

**Comment by stealthycoin** [comment]
Are you sure you are using the awscli and not powershell? You can check in at the [dotnet sdk](https://github.com/aws/aws-sdk-net) for powershell questions.

**Comment by BenMitchell1979** [comment]
I am.. Figured out my issue - typo in the attributes file that I was pulling down via Posh was generating the error..

**Comment by stealthycoin** [comment]
Ah ok, glad you got it all sorted out!
