### ISSUE TITLE
aws s3 cp with metadata issue

### ISSUE THREAD

**Issue by animeshmod** [aws/aws-cli#2440]
`aws s3 cp /home/test.txt s3://bucketname/test.txt  --metadata "name=test.txt,destination=abc"` works from the command line on ec2 however the same being used in shell script exporting `"name=test.txt,destination=abc"` as parameter for metadata fails with below error.

```
Error parsing parameter '\''--metadata'\'': Expected: '\''='\'', received: '\''"'\'' for input:
```

The double quote along with the key=value pair is requirement for the metadata.

**Comment by dstufft** [comment]
Could you include a minimal shell script that reproduces the problem?

**Comment by animeshmod** [comment]
**Script Option 1 (Executed as script.sh -m name=test.txt,destination=abc)**

#!/bin/sh

while getopts :m: option
do
case "$option" in
  m) metadata=\"$OPTARG\";;
esac
done

AWSOUTPUT="$(/usr/bin/aws s3 cp /home/test.txt s3://bucketname/test.txt --metadata ${metadata} 2>&1)"

Script Option 2 (Executed as script.sh -m name=test.txt,destination=abc)

#!/bin/sh

while getopts :m: option
do
case "$option" in
  m) metadata="$OPTARG";;
esac
done

AWSOUTPUT="$(/usr/bin/aws s3 cp /home/test.txt s3://bucketname/test.txt --metadata \"${metadata}\" 2>&1)"


The only difference between 1 and 2 is that in option 1 using quotes while passing the parameter while in 2 passing the same in command line.

**Comment by JordonPhillips** [comment]
This looks like a side effect of how your shell works. You can see exactly what the CLI is getting by using `--debug` and checking the output for a line that looks like this (should be the second line printed):

```
2017-03-06 15:43:39,066 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug']
```
