### ISSUE TITLE
modify-volume not available

### ISSUE THREAD

**Issue by fernandohonig** [aws/aws-cli#2442]
Hi Guys,
I've just installed the latest aws-cli/1.11.47 Python/2.7.10 Darwin/16.3.0 botocore/1.5.10.
I can't find a way to run modify-volume as the command is not available.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-expand-volume.html#cli-modify

Can you please indicate when is that going to be there?

Thanks!
FH

**Comment by dstufft** [comment]
I believe this command is new in aws-cli 1.11.48, try upgrading to the latest version.

**Comment by fernandohonig** [comment]
Thanks! Working now.
