### ISSUE TITLE
Valid filters for searching service catalog record history

### ISSUE THREAD

**Issue by dhorbach** [aws/aws-cli#2445]
Documentation doesn't provide any examples on search filters for the following command
`aws servicecatalog  list-record-history --access-level-filter Key=Account,Value=self --search-filter Key=status,Value=COMPLETE`

Result:

> An error occurred (ValidationException) when calling the ListRecordHistory operation: status is an invalid filter.

We want to filter events by record id  ( for provisioned product) but having difficulties to find appropriate filter

**Comment by kyleknap** [comment]
Yeah I am not too sure either how you would do this through the Service Catalog API. As detailed in our [README](https://github.com/aws/aws-cli/blob/develop/README.rst#getting-help), I would recommend the following:
* Ask StackOverflow for that specific usage question
* To get the documentation updated to make it more helpful, I would recommend submitting documentation feedback in the [API documentation](http://docs.aws.amazon.com/servicecatalog/latest/dg/API_ListRecordHistory.html) for Service Catalog. We pull our documentation from an upstream source so if it gets updated there, it will get updated the AWS CLI documentation as well.
