### ISSUE TITLE
Consistency between s3api and s3 options

### ISSUE THREAD

**Issue by slagelwa** [aws/aws-cli#2446]
Noticed today that service side encryption is enabled in the 's3' commands with the option `--sse`.  However for the 's3api' commands, e.g. put-object, it's the full name `--server-side-encryption AES256`.  It's a minor quibble I know but it is however annoying.

**Comment by dstufft** [comment]
Marking this as a feature request.

**Comment by JordonPhillips** [comment]
@slagelwa `s3api` exposes the low level s3 interface, unchanged as much as possible. While I agree that it isn't ideal, I wouldn't be in favor of changing it as that would make it inconsistent with the service api and all the other sdks. The high level command `s3` is where we can provide those conveniences.

**Comment by slagelwa** [comment]
Makes sense I guess.
