### ISSUE TITLE
The eb cli help message for setenv is wrong

### ISSUE THREAD

**Issue by jasonkarns** [aws/aws-cli#2447]
```
$ eb setenv my-env SOMEVAR=VALUE
ERROR: This branch does not have a default environment. You must either specify an environment by typing "eb setenv my-env-name" or set a default environment by typing "eb use my-env-name".
```

Help output indicates that the environment option must be passed with the `-e` flag, but the error message indicates that it should _not_.

```
$ eb setenv --help
usage: eb setenv [VAR_NAME=KEY ...] [-e environment] [options ...]
...
```

**Comment by dstufft** [comment]
This repository is for the aws cli, you're using the elastic beanstalk cli. You best bet is going to be posting to the [AWS Elastic Beanstalk Forums](https://forums.aws.amazon.com/forum.jspa?forumID=86).

**Comment by jasonkarns** [comment]
Yep, looked for eb-cli on github. no dice. This was the extent of the effort I am willing to expend (for free) on behalf of a multi billion dollar corporation.

**Comment by mpreisinger** [comment]
@jasonkarns , Thanks!  I encountered this confusing message and your issue report at least helped me figure out how to get it working and that I wasn't crazy.

**Comment by dennisvang** [comment]
Thanks @jasonkarns , the `-e` flag is not mentioned in the [online documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-setenv.html) either, but it does the job.

**Comment by tres-caras** [comment]
I was having the same message error because I was trying to eb setenv FOO=bar before eb create. If you create the environment before setting the environment variables it will work. Hope this helps!
