### ISSUE TITLE
parameter groupName cannot be used with the parameter subnet

### ISSUE THREAD

**Issue by elrod-johnson** [aws/aws-cli#2453]
`::aws --version`
aws-cli/1.10.22 Python/2.7.9 Windows/8 botocore/1.4.13

### entering this in ap-southeast-1 Asia Pacific (Singapore):
`aws ec2 run-instances --image-id "ami-xxxxxxxx" --count 1 --instance-type "t2.large" --key-name "xxxxxxxxxxxxxxxxxxxxxxxxxxx" --security-groups "sg-xxxxxxxx" --subnet-id "subnet-xxxxxxxx" --enable-api-termination`

### results in this:
A client error (InvalidParameterCombination) occurred when calling the RunInstances operation: The parameter groupName cannot be used with the parameter subnet

i've seen several posts like this over the past year, but no resolutions.
any ideas on what's wrong or how to debug?

thanks
elrod

**Comment by kyleknap** [comment]
@elrod-johnson I would recommend using ``--security-group-ids`` instead of ``--security-groups``. When you are trying to spin up an instance in a VPC, you cannot use ``--security-group`` which entails to use its name. You need to use its id instead.

**Comment by elrod-johnson** [comment]
@kyleknap `--security-group-ids` was the right answer. 
i didn't notice that parameter in in the `run-instances` doc.
i think i tried `--security-group` with the sg name (not the id) earlier, but that didn't work.
many thanks.

**Comment by oliversalzburg** [comment]
Wow. I had the same error and thought it related to the `GroupName` in the `--placement` argument. This was the solution though.

**Comment by losDaniel** [comment]
If you're having trouble checking the status of any given spot-instance or spot-fleet request. In the console, in section that appears the dashboard showing the instances, the section containing the instance details. Select the pane marked **History** and you will be able to see the last state of any request
