### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by danieljimenez** [aws/aws-cli#2455]
Would AWS consider supporting adding aliases? I was thinking something like how git handles their aliases.  

For example I find myself running these so frequently I've created shell scripts for them:

grab the instance id from the name:
```aws ec2 describe-instances --filter Name=tag:Name,Values=${INSTANCE_NAME} --query Reservations[].Instances[].InstanceId --output text```

grab the private IP so I can SSH to the machine:
```aws ec2 describe-instances --instance-ids ${INSTANCE_ID} --query Reservations[].Instances[].PrivateIpAddress --output text```

grab the health of a specific server on an Elastic Load Balancer:
```/usr/local/bin/aws elb describe-instance-health --load-balancer-name ${ELB_NAME} --instances ${INSTANCE_ID} --query InstanceStates[].State --output text```

**Comment by JordonPhillips** [comment]
This is actually a feature we already support! See [here](https://github.com/awslabs/awscli-aliases) for more details.

**Comment by danieljimenez** [comment]
Wow, I kind had a feeling I couldn't be the only one! Thanks Jordon!!
