### ISSUE TITLE
Feature request: Support CloudWatch dashboards

### ISSUE THREAD

**Issue by repptilia** [aws/aws-cli#2457]
Having a setup with CodeDeploy, which creates a new auto-scaling group at each deployment, I want to be able to update my CloudWatch dashboards automatically with the details of the new auto-scaling groups.

Can we have a CloudWatch dashboard integration?

**Comment by kyleknap** [comment]
@repptilia I am having trouble understanding how the AWS CLI integrates would integrate with the CloudWatch dashboard, especially since it is a command-line utility and it is integrating with a dashboard. Could you elaborate more on how you would envision this integration?

**Comment by repptilia** [comment]
Hello,

I would envision an interface allowing to list dashboards, and at the dashboard level to position and then manage the widgets?

Basically replicating the UI to command line, like I'd manage other AWS components.

Does this seem achievable?

**Comment by foragerr** [comment]
1. Create dashboards
2. List dashboards
3. Add 
4. Widget to dashboards
4. List metrics in dashboard
5. Delete metric from dashboards
6. Delete dashboards

**Comment by JordonPhillips** [comment]
There isn't currently an API for managing widgets, though I can see how that might be useful. This would be feedback to give to the cloudwatch team on [their forums](https://forums.aws.amazon.com/forum.jspa?forumID=138).

**Comment by tomislacker** [comment]
If nobody else has made a feature request post on the forums, I'll do so. Just need to remember which account I have that has already cleared the [ridiculous anti-spam measures](https://aws.amazon.com/premiumsupport/knowledge-center/error-forum-post/).

**Comment by ErikThorsson** [comment]
This would be seriously useful. In order to replicate a dashboard template from one API to another it's extremely time consuming to replace all 40 metrics with different endpoints each time. On top of this, we routinely create new clusters of instances so the old dashboards have to be reconfigured.
