### ISSUE TITLE
CloudFormation deploy does not use previous value as expected

### ISSUE THREAD

**Issue by mbp** [aws/aws-cli#2466]
I already got this confirmed as a bug in AWS Support Case, but I don't see any issue here.

For the parameter overrides, the documentation state the following:

> If you're updating a stack and you don't specify a parameter, the command uses the stack's exisiting value. For new stacks, you must specify parameters that don't have a default value"

However, when you don't provide a value, it will go back to the default value.

It can be reproduced with this CloudFormation template:

```
{
    "AWSTemplateFormatVersion" : "2010-09-09",
    "Description"              : "Test stack",
    "Parameters"               : {
        "TestParam1" : {
            "Description" : "Test param 1",
            "Type"        : "String"
        },
        "TestParam2" : {
            "Description" : "Test param 2",
            "Type"        : "String",
            "Default": "exampledefault"
        }
    },
    "Resources" : {
        "examplebucket" : {
            "Type" : "AWS::S3::Bucket",
            "Properties": {
                "BucketName": { "Ref" : "TestParam2" }
            }
        }
    }
}
```

First call:

    aws cloudformation deploy --template-file test.template --stack-name example --parameter-overrides TestParam1=valueOnCreate

Bucket 'exampledefault' was created

Then go to CloudFormation console and change the value of `TestParam2` to some other value. The bucket name now changed.

Finally call:

    aws cloudformation deploy --template-file test.template --stack-name example --parameter-overrides TestParam1=valueOnUpdate

Now the bucket is (mistakenly) renamed back to "exampledefault".

**Comment by mbp** [comment]
This is probably the same issue as #2460

**Comment by jamesls** [comment]
Thanks for reporting.  I agree that it looks like the same issue as #2460.  I'd suggest we consolidate this over in #2460.

**Comment by stealthycoin** [comment]
Closing in favor of #2460
