### ISSUE TITLE
Starting from release 1.9.19, aws sync progress log does not display non ASSIC issue

### ISSUE THREAD

**Issue by shallker** [aws/aws-cli#2470]
Starting from release 1.9.19, `$ aws sync` progress does not show the log line on terminal if the file name or folder name contains non ASSIC character, like Chinese etc.

`aws-cli/1.9.18 Python/2.7.13 Linux/3.10.0-514.el7.x86_64 botocore/1.3.18` is fine.
`aws-cli/1.9.19 Python/2.7.13 Linux/3.10.0-514.el7.x86_64 botocore/1.3.19` is not.

**Comment by JordonPhillips** [comment]
[This pr](https://github.com/aws/aws-cli/pull/1719) is the source. So what we're doing is we're encoding with your terminal's set encoding with a fallback to ascii. How you resolve that will depend on your os and terminal. On unix systems you should be looking at the `LANG` and `LC_CTYPES` environment variables to start.

**Comment by shallker** [comment]
Thanks
