### ISSUE TITLE
's3 mv' does not persist WebsiteRedirectLocation metadata

### ISSUE THREAD

**Issue by alexjs** [aws/aws-cli#2483]
Based on http://docs.aws.amazon.com/cli/latest/reference/s3/mv.html, specifically:

> When copying between two s3 locations, the metadata-directive argument will default to 'REPLACE' unless otherwise specified

> --metadata-directive (string) Specifies whether the metadata is copied from the source object or replaced with metadata provided when copying S3 objects.

I expected s3 mv to result in metadata being copied over -- however:

```
alexjs@laptop ~ » daws s3api head-object --bucket alexjs-s3-shortener --key u/uazi5cs
{
    "AcceptRanges": "bytes",
    "ContentType": "text/plain",
    "LastModified": "Thu, 09 Mar 2017 03:50:12 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "WebsiteRedirectLocation": "https://speakerdeck.com/miccheng/the-magic-behind-engineers-dot-sg",
    "Metadata": {}
}
alexjs@laptop ~ » daws s3 mv s3://alexjs-s3-shortener/u/uazi5cs s3://alexjs-s3-shortener/u/engineers2
move: s3://alexjs-s3-shortener/u/uazi5cs to s3://alexjs-s3-shortener/u/engineers2
alexjs@laptop ~ » daws s3api head-object --bucket alexjs-s3-shortener --key u/engineers2
{
    "AcceptRanges": "bytes",
    "ContentType": "text/plain",
    "LastModified": "Thu, 09 Mar 2017 04:39:25 GMT",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "Metadata": {}
}
```

Makes it look like it's removed. I'd expect that 'mv' should always maintain all metadata - but I could be wrong. 

I'm unsure whether this is a documentation issue, a PEBKAC issue, or a bug in the behaviour of 's3 mv'.

**Comment by kyleknap** [comment]
So for the ``--metadata-directive`` parameter corresponds directly to the S3's API parameter. Based on the docs: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html, it states that redirect location is not copied over when the metadata directive is set to true. If you want to add the website redirect, you would need to add it with ``--website-redirect`` parameter when moving the object over.

**Comment by alexjs** [comment]
Makes sense - I think then it's a documentation fix (as one wouldn't naturally go to the REST API page when looking at the behaviour of mv) to clarify it. Or, it might just be me being stupid :)

**Comment by kyleknap** [comment]
That would makes sense. I will mark as a documentation update.

**Comment by justnance** [comment]
@alexjs - Our [CLI reference](https://docs.aws.amazon.com/cli/latest/reference/s3/mv.html) and [API reference ](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html)has been updated information on using the `--website-redirect` parameter.   Please let us know if this documentation does not provide clarification.
