### ISSUE TITLE
No way to create Dashboards into Cloudformation

### ISSUE THREAD

**Issue by AmitThakkar** [aws/aws-cli#2484]
Hello,

I am creating all the resource with cloud formation, but not finding any way to create dashboard for those resource. Please correct me If I am wrong.

**Comment by stealthycoin** [comment]
There is no way in the CLI to create a cloud formation dashboard.

**Comment by JordonPhillips** [comment]
To be more specific, there is no service api to do this, so the CLI has no way of doing it.
