### ISSUE TITLE
Add cli option to create default EMR-managed security groups

### ISSUE THREAD

**Issue by matthewadams** [aws/aws-cli#2485]
http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-man-sec-groups.html, in section "To specify Amazon EMR–managed security groups using the AWS CLI", says:

> Note
Amazon EMR–managed security groups are not supported in the Amazon EMR CLI.

However, the cli supports the subcommand `aws emr create-default-roles`.  According to the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), I expected a subcommand like `aws emr create-default-emr-managed-security-groups`, or similar.

Without it, I can't fully script the creation of an EMR cluster with default EMR-managed default security groups.  When I examine them after creating via the web console, they look too complicated for me to derive what they're doing & script whatever that is.

In the meantime, what's the workaround?

FYI, also asked [here](https://forums.aws.amazon.com/thread.jspa?threadID=251127&tstart=0) & [here](http://stackoverflow.com/questions/42706724/whats-the-aws-cli-command-to-create-the-default-emr-managed-security-groups).

**Comment by JordonPhillips** [comment]
My impression from reading the docs is that if you don't specify security groups then the defaults are created for you. Is this not the case?

**Comment by matthewadams** [comment]
@JordonPhillips (sorry for delay -- was on vacation) It is *not* the case that the default EMR-managed security groups are created for you.  Here is what you get when you don't specify them:
```
no existing EMR-managed ElasticMapReduce-master security group found in vpc vpc-1832627e; aborting
you must use the AWS EMR web console once to create an EMR cluster in order to automatically create the default EMR-managed security groups in vpc vpc-1832627e
```

**Comment by matthewadams** [comment]
While I didn't have the same impression from reading the docs, you are indeed correct.  I tried it and the default EMR-managed security groups were created automatically.  Can you point me which part of the docs led you to that conclusion?  I'd pored over those docs, including the note cited above.

While the impetus behind this issue is no longer valid, I'd still like to see the command `aws emr create-default-emr-managed-security-groups` added to the CLI, if possible.  As such, I'll leave the issue open.

**Comment by skilbjo** [comment]
I am surprised that from the docs

   To specify Amazon EMR–managed security groups using the AWS CLI

    Use the create-cluster command with the --emr-managed-master-security-group and --emr-
    managed-slave-security-group parameters.

I run: 
    aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Tez \
      --emr-managed-master-security-group \
      --emr-managed-slave-security-group \
      --some-more-flags

but I get back: `Unknown options: --emr-managed-master-security-group,--emr-managed-slave-security-group`
