### ISSUE TITLE
aws elasticache create-replication-group ends in empty cache clusters

### ISSUE THREAD

**Issue by fishercoder1534** [aws/aws-cli#2491]
I'm using aws-cli to create an ElastiCache cluster from snapshots stored in S3, but upon successful creating new clusters, the cache is empty!

1. why is this happening? 
2. anything wrong in my usage of this command?

Here's my command:

    aws elasticache create-replication-group --replication-group-id ${NEW_REDIS_CLUSTER_ID} --num-node-groups ${NUM_NODE_GROUPS} \
    ${snapshot_arns_arg} --cache-node-type ${EC2_TYPE} --cache-parameter-group abc-default-redis32-cluster --engine redis --engine-version 3.2.4 \
    --replication-group-description ${NEW_CACHE_CLUSTER_DESCRIPTION} --cache-subnet-group-name abc-cache-prod --security-group-ids sg-abcd1234 sg-abcd4321 \
    --node-group-configuration "ReplicaCount=2,Slots=0-5461,PrimaryAvailabilityZone='ap-northeast-2a',ReplicaAvailabilityZones='ap-northeast-2a','ap-northeast-2c'" \
    "ReplicaCount=2,Slots=5462-10924,PrimaryAvailabilityZone='ap-northeast-2a',ReplicaAvailabilityZones='ap-northeast-2a','ap-northeast-2c'" \
    "ReplicaCount=2,Slots=10925-16383,PrimaryAvailabilityZone='ap-northeast-2a',ReplicaAvailabilityZones='ap-northeast-2a','ap-northeast-2c'"

I used `aws elasticache describe-replication-groups --replication-group-id ${NEW_REDIS_CLUSTER_ID}` to get a description of the new cluster, its status is `available`.
Also, it's all OK when you see it on AWS console.

Then I used [Keylord](https://protonail.com/products/keylord) to access my cache tables, it's able to establish the connection to the new cache endpoint, but the cache is empty: `Loaded 0 keys`.

**Comment by stealthycoin** [comment]
I don't know too much about the specific services and how their commands work. The CLI just maps api calls to the service and relays the answers back so we are not. 

I see you opened a [stackoverflow question](http://stackoverflow.com/questions/42793238/aws-elasticache-create-replication-group-ends-in-empty-cache-clusters) as well, you're likely to get better answers there, you could also ask on the [service specific forums](https://forums.aws.amazon.com/forum.jspa?forumID=127).
