### ISSUE TITLE
Cannot delete s3 object with custom sse encryption

### ISSUE THREAD

**Issue by omencl** [aws/aws-cli#2494]
When using command `aws --profile some_profile s3 cp /some_file s3://bucket/some_file --sse-c AES256 --sse-c-key XXX` file is successfully uploaded to server. Also copy back from bucket to local server works.
But this command `aws --profile some_profile s3 rm s3://bucket/some_file` returns
>  fatal error: An error occurred (400) when calling the HeadObject operation: Bad Request

Same object uploaded without sse-c can be deleted normally.

**Comment by stealthycoin** [comment]
Can you add `--debug` to the command and give us the logs here?

**Comment by omencl** [comment]
Here it is. I replace original bucket name with some foo name in logs.
[log.TXT](https://github.com/aws/aws-cli/files/850947/log.TXT)

Thank you!

**Comment by omencl** [comment]
Note: now I am using s3api delete-object as a workaround

**Comment by neelay-shah** [comment]
I am having the exact same issue.

**Comment by stealthycoin** [comment]
Interesting, can yuo give the working debug logs for `s3api delete-object` and also @ mention me when you post them?

**Comment by lvnyan05** [comment]
I had a same issue, too ! and I could avoid it as follows. 
```
$ aws s3 cp file s3://backet/test/ --sse-c AES256 --sse-c-key xxx
upload: ./file to s3://backet/test

$ aws s3 rm s3://backet/test/file
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

$ aws s3 rm s3://backet/test/ --recursive
delete: s3://backet/test/file
```
Best Regards.

**Comment by neelay-shah** [comment]
Hi @stealthycoin 
Sorry for the delay, find the log in attachment. 
[aws-s3-rm-log.txt](https://github.com/aws/aws-cli/files/1022833/aws-s3-rm-log.txt)

**Comment by stealthycoin** [comment]
Yep so this definitely looks like a bug to me.
