### ISSUE TITLE
s3 sync summary text?

### ISSUE THREAD

**Issue by ixodie** [aws/aws-cli#2500]
Is there anyway to email myself when the aws s3 sync completes?  I tried this:

aws s3 sync --size-only --exclude "log.txt" /mnt/xxx-2 2>&1 | mail -s "Image Backups" -aFrom:Admin\<admin@xxx.com\> joe@aol.com

But this has way too much output from the sync.  I see there is no summary in the output, is there a way to dial down the verbosity a bit and simply return some summary information via email?

**Comment by dstufft** [comment]
There's no built in support for sending an email, but you can reduce the verbosity using the ``--quiet`` flag.
