### ISSUE TITLE
aws elasticache create-replication-group doesn't support repartition

### ISSUE THREAD

**Issue by tchia04** [aws/aws-cli#2503]
The enhanced redis backup and restore with cluster resizing has been announced at https://aws.amazon.com/about-aws/whats-new/2017/03/amazon-elasticache-launches-enhanced-redis-backup-and-restore-with-cluster-resizing/

However using the latest version of awscli which as of today is 1.11.63 still doesn't support using different number of RDB file than the number of shards.

I still see this in the help file. 

       --snapshot-arns (list)
          A  list  of  Amazon  Resource Names (ARN) that uniquely identify the
          Redis RDB snapshot files stored in Amazon S3. The snapshot files are
          used to populate the replication group. The Amazon S3 object name in
          the ARN cannot contain any commas. The list must match the number of
          node  groups (shards) in the replication group, which means you can-
          not repartition.

          NOTE:
              This parameter is only valid if the Engine parameter is redis  .

          Example of an Amazon S3 ARN: arn:aws:s3:::my_bucket/snapshot1.rdb

Also how do I do "Equal distribution" that I can do from the console UI?

**Comment by stealthycoin** [comment]
This kind of question specific to the usage of a service is better asked on the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=127) or on [stackoverflow](https://stackoverflow.com/questions/tagged/amazon-elasticache). There are too many new services and features coming out for us on the CLI team to be experts in their usage.
