### ISSUE TITLE
change-resource-record-sets example lists TTL which doesn't work with AliasTarget

### ISSUE THREAD

**Issue by volker-fr** [aws/aws-cli#2508]
The change-resource-record-sets example lists TTL which doesn't work with at least the AliasTarget. I didn't test other use cases.
```
  $ aws route53 change-resource-record-sets --hosted-zone-id MYZONEID --change-batch '
  {
      "Comment": "Update DNS record to the new Loadbalancer Endpoint",
      "Changes": [
          {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                  "Type": "A",
                  "AliasTarget": {
                      "EvaluateTargetHealth": false,
                      "HostedZoneId": "Z35SXDOTRQ7X7K",
                      "DNSName": "name-ElasticL-xxxx-xxx.us-east-1.elb.amazonaws.com"
                  },
                  "Name": "my.hostname.domain.tld",
                  "TTL": 60
              }
          }
      ]
  }
  '
An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request
```

If you remove the TTL it works.

The issue can be found here: https://github.com/aws/aws-cli/blame/develop/awscli/examples/route53/change-resource-record-sets.rst#L42

**Comment by kyleknap** [comment]
Yeah so for doing for a ``change-resource-record-sets`` command using alias record sets, you should follow the alias syntax: https://github.com/aws/aws-cli/blame/develop/awscli/examples/route53/change-resource-record-sets.rst#L83 from the example. Note that in that example syntax, it does not show you can use TTL.

**Comment by volker-fr** [comment]
I personally find it highly confusing having basic syntax that doesn't work in the advanced syntax which should be more detailed but not strip basic features.

**Comment by jamesls** [comment]
Is there anything we can do in the examples we provide that would help?  It sounds like the service itself does not accept `TTL` with `AliasTarget`.

**Comment by piersf** [comment]
You can't provide a TTL value for Alias records. When you use an alias resource record with a load balancer, the TTL will be 60 seconds.
