### ISSUE TITLE
aws help commands hang on osx 10.11.6 with python2.7

### ISSUE THREAD

**Issue by ptoal** [aws/aws-cli#2509]
I have been experiencing a problem with some of the aws cli help pages.  For example, `aws dynamodb help` works fine, however `aws dynamodb put-item help` just hangs indefinitely.

I have tried to trace this, but the closest I can narrow it down is something happening in the _convert_doc_content function in the PosixHelpRenderer class in help.py.  I think it may be a threading related issue similar to the one noted here:

[os.write and os.close on pipe from separate threads hangs on Mac OS X](http://grokbase.com/t/python/python-bugs-list/09c1r9n7as/issue7401-os-write-and-os-close-on-pipe-from-separate-threads-hangs-on-mac-os-x)

A brief snippet of the tail end of `python -m trace --trace ./aws dynamodb put-item help` is included below.  The process hangs after `os.dup2(a, b)`

```
threading.py(1216):         for thread in _enumerate():
threading.py(1231):         _limbo.clear()
threading.py(1232):         _active.clear()
threading.py(1233):         _active.update(new_active)
threading.py(1234):         assert len(_active) == 1
subprocess.py(921):                     self._child_created = True
subprocess.py(922):                     if self.pid == 0:
subprocess.py(924):                         try:
subprocess.py(926):                             if p2cwrite is not None:
subprocess.py(927):                                 os.close(p2cwrite)
subprocess.py(928):                             if c2pread is not None:
subprocess.py(929):                                 os.close(c2pread)
subprocess.py(930):                             if errread is not None:
subprocess.py(931):                                 os.close(errread)
subprocess.py(932):                             os.close(errpipe_read)
subprocess.py(937):                             if c2pwrite == 0:
subprocess.py(939):                             if errwrite == 0 or errwrite == 1:
subprocess.py(943):                             def _dup2(a, b):
subprocess.py(951):                             _dup2(p2cread, 0)
 --- modulename: subprocess, funcname: _dup2
subprocess.py(947):                                 if a == b:
subprocess.py(949):                                 elif a is not None:
subprocess.py(950):                                     os.dup2(a, b)
subprocess.py(952):                             _dup2(c2pwrite, 1)
 --- modulename: subprocess, funcname: _dup2
subprocess.py(947):                                 if a == b:
subprocess.py(949):                                 elif a is not None:
subprocess.py(950):                                     os.dup2(a, b)
```

**Comment by kyleknap** [comment]
Yeah that's really strange. Running on osx 10.11.6 with python 2.7, I have never seen that happen. Could you provide a minimal amount of steps required to reproduce this? Does ``aws dynamodb put-item help`` always hang indefinitely or is it only after running ``aws dynamodb help``?

**Comment by ptoal** [comment]
The hang always happens every time I run the `aws dynamodb put-item help` command, and never for the `aws dynamodb help` command.  It does not matter the order they are run.

I will do a bit more digging, and try to step through things with PyCharm's debugger to see if I can get more data.

**Comment by ptoal** [comment]
Here's a bit more info, after some debugging.  The problem code is most definitely:
```
        p3 = self._popen(cmdline, stdin=PIPE, stdout=PIPE, stderr=PIPE)
        groff_output = p3.communicate(input=man_contents)[0]  
```
in the help.py code.  This happens for any help page of any significant length, not just the put-item page.

The call to p3.communicate() consumes the first 16k or so of the file, and then deadlocks.

After quite a bit of digging, I found that my system's pipe size is limited to 512 bytes.  I haven't figured out exactly why that is, but I have been using this machine for a number of years without wiping it, and I presume I did SomethingBad(tm) to it at some point in the past which has made it "non-standard"

```
> sudo ulimit -a | grep pipe
pipe size            (512 bytes, -p) 1
```
From what I can tell, this is probably a block buffering issue that is being exacerbated by my tiny pipe buffer.  I don't know for certain, but I suspect that other systems could be impacted by this, too.  I guess it just depends on whether or not there is too little input on the pipe to trigger a buffer flush.

At any rate, the following modification to help.py removes the issue for me:
```
17a18
> import tempfile
114,116c115,119
<         p3 = self._popen(cmdline, stdin=PIPE, stdout=PIPE, stderr=PIPE)
<         groff_output = p3.communicate(input=man_contents)[0]
<         return groff_output
---
>         groff_output = tempfile.TemporaryFile()
>         p3 = self._popen(cmdline, stdin=PIPE, stdout=groff_output, stderr=PIPE)
>         p3.communicate(input=man_contents)
>         groff_output.seek(0)
>         return groff_output.read()
```

I am not knowledgeable enough to know if this is the "right" fix for this issue.  With any luck, someone smarter than I am will know. :)

Some of the resources I used when researching this:
https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/
https://qnalist.com/questions/7201670/passing-file-objects-into-subprocess-popen

**Comment by ptoal** [comment]
This has been idle for a bit.  Should I submit a PR, or is this too much of a corner-case to worry about?

**Comment by stealthycoin** [comment]
My guess would be too corner-casey.  I don't want to be writing to disk to read a helpfile that I just read from disk.

**Comment by edmundcraske-bjss** [comment]
I'm hitting the same issue, my pipe size is the same on a pretty new build of Catalina, and I can't explain why it would have changed. Have raised #5118 about this, as there's not an open issue covering it.
