### ISSUE TITLE
"aws s3 cp" uses 100% CPU on Bash for Windows

### ISSUE THREAD

**Issue by laurent22** [aws/aws-cli#2517]
I'm using `aws s3 cp` on Bash for Windows (WSL) and it makes the Python process use 100% CPU, which makes my laptop freeze frequently during the copying process:

![](https://i.imgur.com/qkJgQMt.png)

The network stack on Windows is a bit rubbish especially with WSL, which might be where the problem comes from. However would it be possible to prevent it from doing this? If it's a tight poling loop in the Python code that's causing this, maybe a simple `sleep(1)` statement would help?

**Comment by kyleknap** [comment]
So one suggestion that may help is to turn down the maximum number of threads making requests to S3. You can do that through the [max_concurrent_requests](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html#max-concurrent-requests) configuration option. Right now the default is 10 so try lowering that to see if it uses less CPU.

**Comment by laurent22** [comment]
Thanks, I have set it to 1. It's a bit better but it still uses 25%, which is a lot just to transfer one file over one connection. I see that the progress bar is updated quite frequently (at least more than once per second) - is it possible that it's what's causing the issue. If so, wouldn't updating it only once per second for example improve the situation?

**Comment by laurent22** [comment]
I don't know if it was an update to WSL or to aws-cli but it's no longer taking 100% CPU when doing `aws cp` so I guess the issue can be closed.

**Comment by JordonPhillips** [comment]
Cool. It could possibly just be an inefficiency in the Windows Subsystem for Linux that they addressed.
