### ISSUE TITLE
aws ec2 describe-images doesn't work with --filters, when used with a --profile

### ISSUE THREAD

**Issue by chamindg** [aws/aws-cli#2529]
#### aws --version
`aws-cli/1.10.15 Python/2.7.11 Darwin/16.5.0 botocore/1.4.6`

I'm trying to list AMIs inside one AWS account (say Account A), from a different AWS account (say Account B). ID of Account B is added in AMI permissions. I use --profile option to assume a role inside Account B. AMI listing works fine without --filters. But returns empty list with --filters. Verified the same filters actually exist, by invoking the same command from Account A itself (i.e. without --profile). Here's the commands to reproduce:

NOTE: I have masked the account ID in the commands below.

Command 1:  *With --filters*, from Account A where the AMIs reside (i.e. *without --profile*); Lists the jenkins_master AMI as expected. This shows that the tag actually exists.

##### aws ec2 describe-images --owners 308885xxxxxx --filters Name=tag:role,Values=jenkins_master|grep jenkins_master

`
            "Name": "jenkins_master-1491344967", 
                    "Value": "jenkins_master", 
            "ImageLocation": "308885xxxxxx/jenkins_master-1491344967", 
`

Command 2: *Without --filters*, from Account B (i.e. *with --profile*); Lists the AMI as expected. This shows that the AMI has correct permissions to allow Account B to access it.

##### aws ec2 describe-images --owners 308885xxxxxx  --profile test_admin|grep jenkins_master
`
            "Name": "jenkins_master-1491344967", 
            "ImageLocation": "308885xxxxxx/jenkins_master-1491344967", 
`

Command 3: *With same --filters as command 1*, from Account B (i.e. *with --profile*); Doesn't list the AMI.

#####  aws ec2 describe-images --owners 308885xxxxxx --filters Name=tag:role,Values=jenkins_master --profile test_admin
`{
    "Images": []
}
`

**Comment by stealthycoin** [comment]
Interesting. Looks like a service issue to me, the CLI just forwards the parameters to the service and parrots the response, all the logic for this is with the service. You should ask this on the [ec2 service forums](https://forums.aws.amazon.com/forum.jspa?forumID=187)

**Comment by chamindg** [comment]
Thanks @stealthycoin. Posted the question on [ec2 service forum](https://forums.aws.amazon.com/thread.jspa?threadID=253245)
