### ISSUE TITLE
Make s3 client signed urls accept expiry greater than 1 week in v4 (this a regression from earlier API's)

### ISSUE THREAD

**Issue by alexmnyc** [aws/aws-cli#2532]
In V4, S3 signed urls no longer accept `Expiry`/`X-AMZ-Expiry` query string parameter greater than 1 week. 

This a regression from earlier version of the API, where we could create a signed url for ten years or more if needed. We have a polling configuration sources configured via this mechanism, v4 is breaking that backwards compatibility. Please address this in Amazon API layer. Thanks!

**Comment by stealthycoin** [comment]
This would be a feature request for s3, not the cli. You should bring this up in the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).
