### ISSUE TITLE
s3 sync w/ --delete option not deleting folders

### ISSUE THREAD

**Issue by Shattoww** [aws/aws-cli#2533]
Seems like the --delete flag with s3 sync isn't removing empty directories from destination despite them being gone from the source. It seems to handle files fine, just not directories.

**Comment by stealthycoin** [comment]
By destination do you mean the local or s3? Because it can be either. Can you show what changed and how you expected that to change in the destination?

**Comment by jardakotesovec** [comment]
Just ran into the same issue. Using aws-cli on OS X to sync bucket to local folder. So if there is file within folder, it gets synced properly. Issue is when file gets deleted - empty folder locally remains, which overtime can result in many empty folders.

```
aws s3 sync --delete s3://bucket/folder .
```
