### ISSUE TITLE
Support custom path for credential file

### ISSUE THREAD

**Issue by pauldraper** [aws/aws-cli#2541]
Just as it is possible to specify a config file other than ~/.aws/config with AWS_CONFIG_FILE, it would be nice to specify a credential file other than ~/.aws/credentials.

I suggest an environment variable like AWS_CREDENTIAL_FILE.

**Comment by JordonPhillips** [comment]
There is an environment variable you can use, `AWS_SHARED_CREDENTIALS_FILE`

**Comment by pauldraper** [comment]
Ah, excellent.

**Comment by jcrben** [comment]
Is this documented? Seems to be missing from the list at https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
