### ISSUE TITLE
AWSCLI Installation Error on AIX 7.1 - OSError: Command /usr/local/aws/bin/python - setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by vallapur** [aws/aws-cli#2543]
We are getting the below error message when trying to install AWSCLI on AIX version 7.1
Can you please provide a fix or work around on the below issue.
OSError: Command /usr/local/aws/bin/python - setuptools pip wheel failed with error code 1

Few more details below shows the step by step process we followed.
Python is already installed on AIX version 7.1

```
/usr/local/bin> uname -a
AIX ckd37nn 1 7 00F9C1C54C00
[ckd37nn]tempa
/usr/local/bin> python
Python 2.7.5 (default, Aug 16 2013, 14:02:06) [C] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> [7] + Stopped (SIGTSTP)        python
[ckd37nn]tempa
/usr/local/bin> which python
/usr/bin/python
[ckd37nn]tempa
/usr/local/bin> whereis python
python: /usr/bin/python /usr/bin/python2.7 /usr/bin/python2.7-config /usr/bin/python2.7_64 /usr/bin/python2.7_64-config /usr/lib/python2.7 /usr/include/python2.7
[ckd37nn]tempa
/usr/local/bin>
```

===================================================================
We are following below link
http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html

Here is what is says in a nutshell:

Install the AWS CLI Using the Bundled Installer
Follow these steps from the command line to install the AWS CLI using the bundled installer.
To install the AWS CLI using the bundled installer
1.	Download the AWS CLI Bundled Installer.
$ curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
2.	Unzip the package.
$ unzip awscli-bundle.zip
Note
If you don't have unzip, use your Linux distribution's built in package manager to install it.
3.	Run the install executable.
$ sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

=====================================================================

Essentially, download the bundle, unzip it and run the installer.  We did that and we get this:

```
Running cmd: /usr/bin/python virtualenv.py --python /usr/bin/python /usr/local/aws
Traceback (most recent call last):
  File "awscli-bundle/install", line 138, in <module>
    main()
  File "awscli-bundle/install", line 128, in main
    create_install_structure(working_dir, opts.install_dir)
  File "awscli-bundle/install", line 64, in create_install_structure
    _create_virtualenv(location=install_dir, working_dir=working_dir)
  File "awscli-bundle/install", line 81, in _create_virtualenv
    location))
  File "awscli-bundle/install", line 44, in run
    p.returncode, cmd, stdout + stderr))
__main__.BadRCError: Bad rc (1) for cmd '/usr/bin/python virtualenv.py --python /usr/bin/python /usr/local/aws': Already using interpreter /usr/bin/python
New python executable in /usr/local/aws/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /usr/local/aws/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/tmp/tmpte9x42/virtualenv-15.1.0/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 28, in <module>
  File "/tmp/tmpte9x42/virtualenv-15.1.0/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpte9x42/virtualenv-15.1.0/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/tmp/tmpte9x42/virtualenv-15.1.0/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/utils/glibc.py", line 4, in <module>
  File "/opt/freeware/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2328, in <module>
    main()
  File "virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "virtualenv.py", line 945, in create_environment
    download=download,
  File "virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  ****File "virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /usr/local/aws/bin/python - setuptools pip wheel failed with error code 1****
```

We are using python version 2.7.5.

Could you please help us to fix this issue.It would be great if you provide us workaround or fix as soon as possible.

**Comment by vallapur** [comment]
Any update Jordon, really appreciated if you could get some answer for us.

**Comment by JordonPhillips** [comment]
I had @dstufft take a look, and here was his response:

> pip's manylinux1 support requires ctypes to be installed and it looks like they don't have it. They could either get ctypes or open a pip issue to ask for us to not depend on ctypes or use a pre manylinux1 pip

**Comment by vallapur** [comment]
After speaking to our AIX admins, we don't know how pip will be working on our side, we can't get pip to work.
Can you please confirm on the below items.
1) Is it supported on AIX
2) Can you send us instructions to install on AIX

**Comment by JordonPhillips** [comment]
You may be able to install it using your system pip (`pip install awscli`), since it seems that the ctypes dependency is for virtualenv. If you don't have pip installed, you can try to find it in your os package manager or otherwise you can use the instructions [here](https://pip.pypa.io/en/stable/installing/).
