### ISSUE TITLE
Command is stuck

### ISSUE THREAD

**Issue by gopalganu** [aws/aws-cli#2547]
Hello

I am transferring a large file of about 10GB to s3. (aws s3 cp )
The transfer seems to work as I can see with "ls", same file size on s3 and locally. But the command never returns and my calling process waits forever. ps shows that the aws process is still running.
For smaller files this seems to work. Is there a limit or some setting to work with large files?

Also a different question but related to cp, if my transfer fails halfway, will s3 delete the partially transferred file?

regards
Gopal

I am using 
Ubuntu 14.04.3 LTS
awscli 1.11.76
python 2.7.6

**Comment by JordonPhillips** [comment]
possible duplicate of #1775 

Do you have full permissions for the file and the bucket?
