### ISSUE TITLE
Authentication required! in AWS IP

### ISSUE THREAD

**Issue by bswscube** [aws/aws-cli#2553]
Hello there,

I have recently create a instance using ec2 in aws. When i run my IP address at browser, it give me Authentication required! error and asking for Username and Password.

| URL: http://54.148.62.84/xampp/

I want to remove this authentication. Please help me out for that as soon as possible.

Thanks.

**Comment by JordonPhillips** [comment]
This is configuration you'll need to do in your application code. From the AWS side of things as long as you can access it you should be good to go.
