### ISSUE TITLE
`--no-paginate` is backwards on `route53 list-health-checks`

### ISSUE THREAD

**Issue by tjsingleton** [aws/aws-cli#2554]
```
> aws --version
aws-cli/1.11.76 Python/2.7.10 Darwin/15.6.0 botocore/1.5.39
> aws route53 list-health-checks --no-paginate | grep 'HealthCheckConfig' | wc -l
     100
> aws route53 list-health-checks | grep 'HealthCheckConfig' | wc -l 
     716
```

**Comment by tjsingleton** [comment]
Also, `aws cloudwatch describe-alarms` seems to be reversed

**Comment by jamesls** [comment]
Could you clarify the expected behavior you're looking for?  The CLI will paginate by default, so in your first command with `--no-paginate` we'll only receive the max page size of results, which for this operation is 100.  With no arguments we'll auto page which will retrieve all your healthchecks.

**Comment by tjsingleton** [comment]
I misunderstood this when I read the following and thought it was the pattern for all the commands. I read it as it's paginated by default, and that --no-paginate enables auto paging. 

> describe-instances is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument.

I do think that maybe the `ec2 describe-instances` behaved differently at some point in time, but can't say with 100% certainty. I know I started using it in scripts for some reason, but it doesn't appear to have an effect now. Now I'm not seeing any difference with or without it, but I'm guessing that the 467 instances I have is left that the default page size.

Thanks for the clarification and apologies for not reading the docs better.
