### ISSUE TITLE
Database creation using AWS CLI

### ISSUE THREAD

**Issue by fdrgiit** [aws/aws-cli#2560]
Hello,

As per the current RDS documentation for CLI, it seems using CLI database cannot be created in a particular database engine in AWS RDS.

Requesting you to please let me know if that will be possible in the near the future.

Thanks

**Comment by dstufft** [comment]
I believe you're looking for the ``--engine`` flag, assuming you're looking at the ``aws rds create-db-instance`` command.

**Comment by fdrgiit** [comment]
Hello,

Nope.. `--engine` flag is used to select appropriate database engine like mysql, postgres, etc. I am looking for a cli command that can help me create database as well as how `create-db-instance` helps in initializing the instance itself.

**Comment by dstufft** [comment]
Is there an RDS API to do what you're looking to do?

**Comment by fdrgiit** [comment]
I am sorry, but not sure what are you intending to say.....

**Comment by dstufft** [comment]
Do any of the API operations listed on https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Operations.html do what you're asking for? I'm having a bit of trouble understanding what specifically you're asking for here.

**Comment by fdrgiit** [comment]
I am sorry to be sounding here confused..but wanted to ask is how using cli command `create-db-instance` you can spin up and aws rds instantly with the storage and other configs as per requirements. R there cli commands available to operate at database level?? Like is there a cli command `create-db` using which i can create a database on the instance i just spin up using the above the command. I hope i am clear

**Comment by dstufft** [comment]
OH! I see, you're looking for something that would do something like ``CREATE DB foobar;`` via SQL?

**Comment by fdrgiit** [comment]
correct sir...but not using sql but instead using cli itself in the `create-db-instance` command itself or if there are any other alternatives..

**Comment by lorengordon** [comment]
I'd be highly interested in this as well!

**Comment by mahesh-raghunandanan** [comment]
I am also highly interested in this feature. We are focusing on much automation of creation of numerous databases in existing RDS instances (SQL server). Is this feature planned in roadmap of AWS RDS or is there any temporary workaround for this. Will be really helpful.
