### ISSUE TITLE
CodeBuild Command missing

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [aws/aws-cli#2561]
Hi,

It looks like the "aws codebuild .." command is missing in awscli. Has it been added yet? 

`aws codebuild help`
`usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]`

Regards

**Comment by dstufft** [comment]
This command is working for me with:

```
$ aws --version
aws-cli/1.11.80 Python/3.6.0 Darwin/16.5.0 botocore/1.5.43
```

I believe all you'll need to do is upgrade your aws-cli and botocore.
