### ISSUE TITLE
Cloudformation Package does not work with already uploaded templates in nested stacks

### ISSUE THREAD

**Issue by jrstarke** [aws/aws-cli#2564]
I'm using Cloudformation Stacks and SubStacks to deploy large parts of our infrastructural components, in combination with `aws cloudformation package` to package up the SubStack resources for deployment. 

Recently, we've started pushing AWS WAF out with our CloudFront distributions. To this, the stack for these distributions has a `AWS::CloudFormation::Stack` resource, which deploys the AWS WAF Preconfigured Protections (https://aws.amazon.com/answers/security/aws-waf-security-automations/). These protections include a CloudFormation template available at https://s3.amazonaws.com/solutions-reference/aws-waf-security-automations/latest/aws-waf-security-automations.template for creating the WAF WebACL and the associated rules.

The problem is, when I run `cloudformation package` on my top level stack, I get the error 

`TemplateURL parameter of AppFirewall resource is invalid. It must be a S3 URL or path to CloudFormation template file. Actual: /Users/jstarke/<redacted>/https:/s3.amazonaws.com/solutions-reference/aws-waf-security-automations/latest/aws-waf-security-automations.template`

Looking into this specific command, it appears that it checks if the template_path in the `TemplateURL` is an s3 url (https://github.com/aws/aws-cli/blob/develop/awscli/customizations/cloudformation/artifact_exporter.py#L64), but it only considers urls starting with `s3://`, where as the Cloudformation Stack documentation specifically requires TemplateURLs for existing resources to start with `https://s3.amazonaws.com/` (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-templateurl).

**Comment by jrstarke** [comment]
I've come up with what I think is the simplest reproduction of this. It involves a top level stack with a substack that uses the AWS WAF Preconfigured protections (So Stack -> Child Stack -> Grandchild Stack). I've made a gist here: https://gist.github.com/jrstarke/ab60f3713675c69d9377fbd1b5017459

When you run these templates with the following (replacing `<bucket_to_upload_to>` with a bucket you have access to):
`aws cloudformation package --template-file template1.yaml --s3-bucket <bucket_to_upload_to>`

**Comment by dstufft** [comment]
Confirmed, thanks for the reproduction steps.

**Comment by matheusmaximo** [comment]
I know this is a closed issue but just a point here, the docs say:
https://s3.region.amazonaws.com/bucket-name/sam-template-object

When in fact, the code expects to be:
https://s3.amazonaws.com/bucket-name/sam-template-object

And if you hit on S3 object Url from Console Management, you get back:
https://s3-region.amazonaws.com/bucket-name/sam-template-object

Source:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template.html#serverless-sam-template-application
