### ISSUE TITLE
files end up in 'hidden' buckets / folders on aws.amazon.com

### ISSUE THREAD

**Issue by thewhowhatwhere** [aws/aws-cli#2571]
problem with extra slash in bucket path:

`aws s3 mv localfile s3://bucket_name/sub/remotefile` will put file in 'sub', however...
`aws s3 mv localfile s3://bucket_name//sub/remotefile` runs just fine, but puts the file in a "hidden" directory on the aws s3 dashboard.

other than not showing up in the dashboard, the file is perfectly accessible.

**Comment by RJTK** [comment]
I've just run into this as well.  In the s3 dashboard I get a folder with a blank name and it shows up just as '____'.  But, the data is still accessible.  I'm not sure it's really a problem, but simply how blank names are handled?

**Comment by kyleknap** [comment]
This looks like an issue with the S3 console. Could you open a thread in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) about this? Typically we reserve the GitHub repository for issues specific to the CLI.
