### ISSUE TITLE
aws s3 cp from local to s3 fails for empty files

### ISSUE THREAD

**Issue by alekdimi** [aws/aws-cli#2583]
I had a simple script on a spot instance that uploads an empty file "success.txt" to S3, which fails, it seems, if the file is empty:

aws s3 cp success.txt s3://bucket/folder/

`upload failed: ./success.txt to s3://bucket/folder/ seek() takes 2 positional arguments but 3 were given`

Note that if I add a line to the file the command works.

Similar to https://github.com/aws/aws-cli/issues/2403

**Comment by kyleknap** [comment]
How did you install the CLI? Was it through the ubuntu package manager like the other linked issue? If so, I would prefer we keep all of the conversations to just that thread as it is probably for the similar reason that the maintainers of the Ubuntu package repository did not properly package up the CLI.

**Comment by alekdimi** [comment]
Yes, I did apt-get on the default ubuntu 16.04 spot instance image from aws.

**Comment by chetankapoor** [comment]
Hi 

I am also getting the same issue if i put something in file then it works perfectly..

**Comment by stealthycoin** [comment]
Try installing awscli from pip which is the suggested/supported way of doing so: http://docs.aws.amazon.com/cli/latest/userguide/installing.html
