### ISSUE TITLE
describe-images is not able to filter on tags

### ISSUE THREAD

**Issue by thomaslarsen** [aws/aws-cli#2584]
I am trying to filter images based on a tag (Name), and I consistently get no images returned. 

I am running the following command:
`aws ec2 describe-images --filters "Name=tag:Name,Values=aws-eu-west-1-CENTOS-6.8-64"`

Through the console I can confirm that a number of images with this tag exists.

I have tried various combinations of using `"` and globs when specifying the filters and they all fail.

I have further noticed, that the `describe-images` command don't return any tag information either, so maybe there is a general issue with it accessing the image tag information.

**Comment by kyleknap** [comment]
Running the same command, these are the debug logs I am getting:
```
2017-05-05 09:55:55,970 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeImages) (verify_ssl=True) with params: {'body': {'Action': u'DescribeImages', u'Filter.1.Value.1': u'aws-eu-west-1-CENTOS-6.8-64', 'Version': u'2016-11-15', u'Filter.1.Name': u'tag:Name'}, 'url': u'https://ec2.eu-west-1.amazonaws.com/', 'headers': {'User-Agent': 'aws-cli/1.11.82 Python/2.7.10 Darwin/15.6.0 botocore/1.5.41'}, 'context': {'auth_type': None, 'client_region': u'eu-west-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x1124a2710>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
```
So it looks like the request is getting formatted correctly. So I don't think it is an issue with how you are specifying the command.

Are you able to see the AMI in general when you run the ``describe-images`` command without any filters? Could you potentially include debug logs from the command you ran by appending ``--debug`` to the command you ran? That will help with debugging this.

**Comment by thomaslarsen** [comment]
Hi Kyle,

I think I have gotten a bit further in figuring this out.

First, I have resolved the issue below. The problem I had was, that my environment variables AWS_xxx was pointing to a different account. When I fixed that, I got the expected result.

However I do need to run this query from a different account (we are using Terraform to copy come AMIs across). When I run the following (same query) with my environment variables set to a different account I get an empty result:

aws --region=eu-west-1 ec2 describe-images --owners="232969XXXXX" --filters "Name=tag:Name,Values=aws-eu-west-1-CENTOS-6.8-64*"
{
    "Images": []
}

Where the owners setting is set to the account that holds the AMIs. When I do the above, filtering on the AMI name, it does work - for example:

aws --region=eu-west-1 ec2 describe-images --owners="232969XXXXX" --filters "Name=name,Values=aws-eu-west-1-CENTOS-6.8-64*"

So it seems to be when I am filtering on a tag, it fails.

Kind regards,
Thomas

**Comment by kyleknap** [comment]
@thomaslarsen I am not sure why that would not work? Can you confirm that the AMI's have a Name tag associated? So when you run:
```
 aws --region=eu-west-1 ec2 describe-images --owners="232969XXXXX" --filters "Name=name,Values=aws-eu-west-1-CENTOS-6.8-64*"
```
What are the tags in that response?

**Comment by qantasloyalty-techops** [comment]
@kyleknap fyi i encountered this myself today.

The issue is cross-account.

To replicate...

1. Create an AMI
2. Share the AMI with another account
3. Tag the AMI with MyTag: MyValue
3. Use the describe-image cli command with the tag filter to get info in the account you created.
E.g.
aws ec2 describe-images --filters Name="tag:MyTag",Values=MyValue
4. Now use the credentials of the account you shared the AMI to to perform the describe-image command again.
E.g.
aws ec2 describe-images --filters Name="tag:MyTag",Values=MyValue

You will get back a result for step 3 but an empty result for step 4.

**Comment by studees** [comment]
I've just hit this also - I believe it's due to account B not having permission to read tags of account B.

You can share the AMI and the EBS snapshots that backs it but not the values it is tagged with...

**Comment by rquadling** [comment]
I fell foul of this restriction: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

    You can tag public or shared resources, but the tags you assign are available only to your AWS account and not to the other accounts sharing the resource.
