### ISSUE TITLE
Specify an IAM Role in a CloudWatch Alarm

### ISSUE THREAD

**Issue by vikas027** [aws/aws-cli#2586]
I have created a custom CloudWatch Alarm through user data something similar to what is shown [here](http://johnhunsley.blogspot.com.au/2016/03/custom-cloudwatch-tomcat-jvm-metrics.html).

```bash
aws cloudwatch put-metric-alarm \
  --region ${region} \
  --alarm-name ${cw_namespace}_$${INSTANCE_ID} \
  --namespace ${cw_namespace} \
  --metric-name ${cw_namespace}_$${INSTANCE_ID} \
  --comparison-operator LessThanThreshold \
  --threshold ${cw_threshold} \
  --evaluation-periods ${cw_evaulation_periods} \
  --period ${cw_period} \
  --statistic ${cw_statistic} \
  --insufficient-data-actions "arn:aws:swf:${region}:${account_id}:action/actions/AWS_EC2.InstanceId.Terminate/1.0" \
  --alarm-actions "arn:aws:swf:${region}:${account_id}:action/actions/AWS_EC2.InstanceId.Terminate/1.0" \
  --dimensions "Name=InstanceId,Value=$${INSTANCE_ID}
```

This works perfectly fine, but the only thing I have to do is choose the IAM Role **EC2ActionAccess** and click _Save Changes_.
![2017-05-08_11-14-00](https://cloud.githubusercontent.com/assets/6998650/25800680/a5df5206-342d-11e7-9857-4e4de20a7eca.png)

Interestingly, I have to do this for just one alarm. All future alarms in the same namespace don't require me to choose the IAM Role.

How can I choose the role in the first place in an automated way?

**Comment by JordonPhillips** [comment]
Looks like this is documented behavior:

> Note that you must create at least one stop, terminate, or reboot alarm using the Amazon EC2 or CloudWatch console to create the EC2ActionsAccess IAM role. After this IAM role is created, you can create stop, terminate, or reboot alarms using a command-line interface or an API.

Still, that's not a great experience. I would recommend making this feature request on the [CloudWatch forums](https://forums.aws.amazon.com/forum.jspa?forumID=138).

**Comment by vikas027** [comment]
Thanks @JordonPhillips, I am closing this issue.
