### ISSUE TITLE
Problem Downloading files from S3 Bucket 

### ISSUE THREAD

**Issue by raghav20** [aws/aws-cli#2588]
I am downloading files from S3 bucket with hierarchy of folder structure. 
BucketName -> A -> B 
and then one of the folder has space and single quote

So it is somewhat like 
Bucket/A/B/DEF KLM  N'Q 

I tried to use CLI 
aws s3 sync path .
it fails how should I download the data from S3 ?

-pR

**Comment by JordonPhillips** [comment]
What error are you seeing? What OS are you using? Could you please run `aws --version`?

**Comment by raghav20** [comment]
I am using GPU instance from ubuntu g22x

**Comment by raghav20** [comment]
and latest version of cli downloaded today

**Comment by raghav20** [comment]
Any update on this ?

**Comment by JordonPhillips** [comment]
Can you please run `aws --version` and pate the output here?

**Comment by raghav20** [comment]
sorry the output is 
aws-cli/1.11.83 Python/2.7.12 Linux/4.4.0-1016-aws botocore/1.5.46

**Comment by JordonPhillips** [comment]
I'm not able to reproduce. Could you share a debug log? You can do this by appending `--debug` to the command.

**Comment by raghav20** [comment]
checking it now
