### ISSUE TITLE
Environment variables for assume role

### ISSUE THREAD

**Issue by vikas027** [aws/aws-cli#2590]
Hey,

Currently, I have this in my `~/.aws/credentials` file.

```
[account_B]
role_arn = arn:aws:iam::<account_ID>:role/<IAM_ROLE>
source_profile = <some_profile>
```

And I am using below CLI commands to assume role
```
aws --profile account_B <other arguments>
```

Is there a way to use `role_arn` and `source_profile` as environment variables? I am looking out a way to not have these saved in `~/.aws/credentials` file and use environment variables.

Cheers.

**Comment by JordonPhillips** [comment]
We don't currently have a way to use assume role via environment variables. Marking as a feature request.

**Comment by vikas027** [comment]
Thanks @JordonPhillips 👍

**Comment by mmeany** [comment]
Would be useful where Docker containers are being used as part of a build pipeline that is configured with environment variables.

**Comment by vikas027** [comment]
@mmeany that is exactly my use case
