### ISSUE TITLE
Add soft memory limit in ECS Task definition json

### ISSUE THREAD

**Issue by Chintanvpatel** [aws/aws-cli#2591]
Hi, I'm using AWS Cli version 1.10.7. When i do "aws ecs describe-task-definition" It gave me hard limit memory in response. If i have assigned only soft limit, I can not get memory in response of describe-task-definition.

Is there any way to get soft limit or still it's not implemented ?

Thanks & Regards,
Chintan Patel

**Comment by JordonPhillips** [comment]
You are using an old version of the CLI, you will need to update. For reference, the current version is 1.11.83

**Comment by Chintanvpatel** [comment]
@JordonPhillips I installed latest version of cli & I'm getting "memoryReservation" for soft limit. Thanks.
Closing the issue.
