### ISSUE TITLE
aws dynamodb put-item and batch-write-item failure for examples in the reference documentation

### ISSUE THREAD

**Issue by shruthb** [aws/aws-cli#2609]
I am trying to run the examples given in the http://docs.aws.amazon.com/cli/latest/reference/dynamodb/batch-write-item.html#examples
I get the following errors with this
1) Error parsing parameter '--request-items': Expected: '=', received: 'EOF' for input:
request-items.json
*
When I add a = to the end of the file name in the command, I no longer get this error but I get the following error instead.

2) Parameter validation failed:
Invalid type for parameter RequestItems.request-items.json[0], value: , type: <type 'str'>, valid types: <type 'dict'>

I haven't made any changes to the file given in the example and I have created the table being used here to for trying out the example.

aws cli version being used:
aws-cli/1.11.86 Python/2.7.8 Linux/3.2.45-0.6.wd.865.49.315.metal1.x86_64 botocore/1.5.49

**Comment by stealthycoin** [comment]
You didn't put `file://` before the name of the file.

**Comment by shruthb** [comment]
oops yes, file:/// fixed it
