### ISSUE TITLE
aws cli has pinned colorama 0.3.7 which is not the latest

### ISSUE THREAD

**Issue by edrozenberg** [aws/aws-cli#2610]
My scripting updates all pip packages which gets me colorama 0.3.9, but then the awscli install/update downgrades it to 0.3.7 each time.

````
Installing collected packages: colorama
  Found existing installation: colorama 0.3.9
    Uninstalling colorama-0.3.9:
      Successfully uninstalled colorama-0.3.9
Successfully installed colorama-0.3.7
````

**Comment by stealthycoin** [comment]
Colorama has a history of breaking us. What do you need in `colorama >=0.3.7`?

**Comment by edrozenberg** [comment]
We don't need anything in colorama - it's just our automation scripting updates all pip packages and then aws cli downgrades colorama, and this upgrade/downgrade happens every time we run the automation scripts. But various software does need to pin versions sometimes, so we'll have to work out something on our end or just ignore this version oscillation.

**Comment by rth** [comment]
> Colorama has a history of breaking us. What do you need in colorama >=0.3.7?

The problem is other packages depending on `colorama >=0.3.7`: for instance `docker-compose` [pins the version of colorama to `0.3.8`](https://github.com/docker/compose/blob/master/requirements.txt#L5) meaning that awscli and docker-compose cannot be installed in the same Python environment which is not ideal. Would it be possible to upgrade maximal supported version to 0.3.8  at least (the latest being 0.3.9) ?

**Comment by ambakshi** [comment]
This is still an issue and conflicting with other packages now that require >= 0.3.9, any chance to modify the requirement?

**Comment by simformsolutions** [comment]
We are having the same issue: below is the error description

C:\Windows\System32>eb --version
Traceback (most recent call last):
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (colorama 0.3.7 (c:\users\dharmraj.mangukiya\appdata\roaming\python\python36\site-packages), Requirement.parse('colorama<0.4,>=0.3.9; sys_platform == "win32"'), {'docker-compose'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dharmraj.Mangukiya\AppData\Roaming\Python\Python36\Scripts\eb-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3095, in <module>
    @_call_aside
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\dharmraj.mangukiya\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (colorama 0.3.7 (c:\users\dharmraj.mangukiya\appdata\roaming\python\python36\site-packages), Requirement.parse('colorama<0.4,>=0.3.9; sys_platform == "win32"'), {'docker-compose'})

**Comment by mrday86** [comment]
pip install git+git://github.com/aws/aws-cli

**Comment by rth** [comment]
> pip install git+git://github.com/aws/aws-cli

There was a recent release on PyPi: https://pypi.org/project/awscli/#history so I don't think that installing the dev version will help...

**Comment by mrday86** [comment]
well I must say that I ended here because I was searching for a similar issue (mine was about awsebcli and I solved it by instaling the previous version), maybe I replied too fast without reading well everything (if this is the case: I'm sorry about it), but I see a confict with cororama (colorama<0.4,>=0.3.9), the version I linked have different dependencies (as you can check them here: https://github.com/aws/aws-cli/blob/develop/requirements.txt): colorama>=0.2.5,<=0.3.9

**Comment by Naotamon** [comment]
１、
Copy USER\AppData\Local\Programs\Python\Python36\Lib\site-packages\colorama-0.3.9.dist-info to  USER\AppData\Roaming\Python\Python36\site-packages\

And delete USER\AppData\Roaming\Python\Python36\site-packages\colorama-0.3.7.dist-info

２、
USER\AppData\Roaming\Python\Python36\site-packages\awsebcli-3.14.0-py3.6.egg-info
Overwrite the version.
colorama==0.3.7　→　colorama==0.3.9

３、
Try again.

**Comment by simformsolutions** [comment]
@Naotamon ,
this solution is not working for me, I uninstalled everything including AWS cli, EB cli, PIP, Python, deleted all the directories, and re install all and not it works for me.

**Comment by wanjugu** [comment]
I am getting Colorama version conflic when I run 'eb --version'. Anyone got a solution to this.
![image](https://user-images.githubusercontent.com/7904323/41145897-32ed87f8-6b0a-11e8-88e8-9e387361cae4.png)

**Comment by kd9951** [comment]
@Naotamon 
Thank you. I have same problem. but fixed.

**Comment by glyph** [comment]
Having just manually updated our dependencies again, I was reminded of this today.  It would be great to let this float and keep more current with new colorama versions.

Also, this seems related: https://github.com/pypa/pip/issues/988

**Comment by diraven** [comment]
Yes, it's still pretty much an issue when you try to install something that uses more recent versions of colorama.

**Comment by dacarlin** [comment]
Why is this issue closed? It's still an issue as of 2019-08-21

**Comment by nbcsteveb** [comment]
Doing regular pip updates on my machine, awscli is always an issue.

```
ERROR: awscli 1.16.224 has requirement colorama<=0.3.9,>=0.2.5, but you'll have colorama 0.4.1 which is incompatible.
ERROR: awscli 1.16.224 has requirement rsa<=3.5.0,>=3.1.2, but you'll have rsa 4.0 which is incompatible.
```

**Comment by DanLipsitt** [comment]
> We don't need anything in colorama - it's just our automation scripting updates all pip packages and then aws cli downgrades colorama, and this upgrade/downgrade happens every time we run the automation scripts.

@edrozenberg Can you point us at the automation scripts you're talking about so that somebody can attempt a fix? I agree that this issue definitely isn't resolved and it's puzzling that it's closed.
