### ISSUE TITLE
aws cli version going backward? 

### ISSUE THREAD

**Issue by tchia04** [aws/aws-cli#2613]
Before updating aws cli version

tonychia@blueapple ~ $ aws --version
aws-cli/1.11.79 Python/2.7.10 Darwin/16.6.0 botocore/1.5.42

tonychia@blueapple ~ $ audo
tonychia@blueapple ~ $ sudo pip install -U aws
Password:

After updating aws cli to the latest version.
tonychia@blueapple ~ $ aws --version
0.2.5
tonychia@blueapple ~ $

Why the version number change from "aws-cli/1.11.79" to "0.2.5" ? 

This was done on a Mac

**Comment by stealthycoin** [comment]
The package name in pip is `awscli`. I don't know offhand what `aws` is but you installed something else.

**Comment by tchia04** [comment]
Thanks

**Comment by zachliu** [comment]
i had the same issue. i installed `aws` by mistake, then i installed `awscli` without uninstalling `aws` first.
all hell broke loose ... long store short, i had to uninstall both of them and reinstall `awscli` for it to find itself
