### ISSUE TITLE
attach-role-policy

### ISSUE THREAD

**Issue by PomegranateApps** [aws/aws-cli#2631]
When I try to run the "attach-role-policy" command I get the following error.

`aws: error: argument operation: Invalid choice, valid choices are:`

http://docs.aws.amazon.com/cli/latest/reference/iam/attach-role-policy.html

**Comment by JordonPhillips** [comment]
That doesn't look like our error format. Are you sure you installed the correct package? There is a package in pypi that we don't own called `aws-cli` which can trip people up. `awscli` is the correct package name.
