### ISSUE TITLE
ECR get-login does not support alternate output formats

### ISSUE THREAD

**Issue by patrickf55places** [aws/aws-cli#2632]
Running `aws --output=json ecr get-login` does not format the output in JSON. The `table` format is also not supported.

```
$ aws --version
aws-cli/1.11.96 Python/2.7.10 Darwin/16.6.0 botocore/1.5.59
```

**Comment by JordonPhillips** [comment]
Right. This command is intended to print off a command that you can run to login to docker. The json / table output doesn't make sense for it.

**Comment by patrickf55places** [comment]
Those credentials are useful outside of direct use in a docker command. In my case, I want to use them with a library that takes the docker username/password and has its own authentication flow.

**Comment by JordonPhillips** [comment]
You can use [`get-authorization-token`](http://docs.aws.amazon.com/cli/latest/reference/ecr/get-authorization-token.html) to get that information for use in other applications.

**Comment by patrickf55places** [comment]
Didn't see that command. Thanks.
