### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by sdeshpande** [aws/aws-cli#2641]
Hi,

We recently implemented Palo Alto firewall in our network. The firewall does SSL decryption with the cert provided by the firewall itself. Since then, we can no longer use aws cli or aws web page to interact with aws services such as S3.
When working with CLI we get following error 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
If I pass --no-verify-ssl,  cli works. 

I want to know if there is a way to specify our own ssl cert with aws cli or with web interface ?

Regards,
Saurabh

**Comment by JordonPhillips** [comment]
Sounds a bit suspicious that it's decrypting your https traffic. Regardless, you can provide your own cert bundles using `ca_bundle` in addition to environment variable and command line options. See [the docs](https://github.com/aws/aws-cli#other-configurable-variables) for more details. Your web browsers probably also allow this sort of configuration, but I can't help you out there.

**Comment by sdeshpande** [comment]
Thank you. I will try this and confirm once completed.

**Comment by sdeshpande** [comment]
Thank you. This worked on scripts that makes use of aws cli.
I just need to figure out how to get s3 web pages to respond to this. 

Regards,
Saurabh

**Comment by JordonPhillips** [comment]
Well it should just be configuration for your browsers. I'm pretty sure most of the big ones allow you to do this. Glad you got the CLI working though!
