### ISSUE TITLE
--iam-instance-profile not being parsed correctly

### ISSUE THREAD

**Issue by utterlyforked** [aws/aws-cli#2643]
I know this issue has been raised previously in a few similar issues (https://github.com/aws/aws-cli/issues/1470 and https://github.com/aws/aws-cli/issues/2392) but I'm still seeing a simliar behaviour in a very recent release

```
Andrews-MacBook:~ andrewtaylor$ aws --version
aws-cli/1.11.97 Python/2.7.10 Darwin/16.6.0 botocore/1.5.60
```

--iam-instance-profile parameter causes error 

```
Andrews-MacBook:~ andrewtaylor$ aws ec2 run-instances --image-id ami-01ccc867 --key-name systemmanager --instance-type m3.medium --iam-instance-profile systemmanager-instancerole

Error parsing parameter '--iam-instance-profile': Expected: '=', received: 'EOF' for input:
systemmanager-instancerole
```

I tried with the same parameter but removing the hyphen from the argument value in case it was just the value being passed.  Same result:

```
Andrews-MacBook:~ andrewtaylor$ aws ec2 run-instances --image-id ami-01ccc867 --key-name systemmanager --instance-type m3.medium --iam-instance-profile systemmanager

Error parsing parameter '--iam-instance-profile': Expected: '=', received: 'EOF' for input:
systemmanager
```

When I remove the --iam-instance-profile argument the command is successful. 

Here's the debug output which looks as if the params are correct.

```
Andrews-MacBook:~ andrewtaylor$ aws ec2 run-instances --image-id ami-01ccc867 --key-name systemmanager --instance-type m3.medium --iam-instance-profile systemmanager --debug 2>&1 | grep "Arguments entered"
2017-06-06 09:42:17,498 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['ec2', 'run-instances', '--image-id', 'ami-01ccc867', '--key-name', 'systemmanager', '--instance-type', 'm3.medium', '--iam-instance-profile', 'systemmanager', '--debug']
```

Is this a regression?

Andrew

**Comment by JordonPhillips** [comment]
You need to specify whether you're providing a name or an arn (or both), like so: `Name=systemmanager-instancerole`. There are examples in the [docs](http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html#examples) which demonstrate this.

**Comment by utterlyforked** [comment]
Oh well now I feel foolish!

Thanks for the heads-up. Perhaps a pull request for a change in the error message would be accepted?

**Comment by kdaily** [comment]
The original issue was resolved and documentation shows expected parameter. Since the error returned notes which parameter is at fault, we wouldn't try to parse this particular specification as incorrect.

**Comment by dota247** [comment]
Its been 4 years and i literally ran into the same issue, its almost like were all treading down the same path, running into the same mistakes.

**Comment by saraswat40** [comment]
This stuff is not documented. This is how the the parameter needs to be passed:
`# aws ec2 associate-iam-instance-profile --iam-instance-profile '{"Name": "name of the profile" }'`
OR
`# aws ec2 associate-iam-instance-profile --iam-instance-profile '{"arn": "arn of the profile" }'`
