### ISSUE TITLE
aws iot create-keys-and-certificate: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013'

### ISSUE THREAD

**Issue by theunreal** [aws/aws-cli#2649]
I'm trying to follow the "[How to Configure the Bridge to AWS IoT](https://aws.amazon.com/blogs/iot/how-to-bridge-mosquitto-mqtt-broker-to-aws-iot/)" guide for EC2, and I need run the following command: 

`sudo aws iot create-keys-and-certificate --set-as-active --certificate-pem-outfile cert.crt --private-key-outfile private.key --public-key-outfile public.key –region eu-central-1`

But running this command outputs the following error without creating a ceriticate:

```
$ sudo aws iot create-keys-and-certificate --set-as-active --certificate-pem-outfile cert.crt --private-key-outfile private.key --public-key-outfile public.key –region eu-central-1
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 56, in main
    return driver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 203, in main
    sys.stderr.write(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 31: ordinal not in range(128)
```

Any workaround?

**Comment by tgore03** [comment]
@theunreal I am facing the same problem. Did you find a solution for it?

**Comment by rkim-ias** [comment]
I'm not sure if this will help you guys, but i've found that the /u2013 is an english dash (got it from copying and pasting code), so i replaced the dashes in my command with dashes from the keyboard, and my commands went through.

**Comment by KennyKu** [comment]
–region shoud be –-region
