### ISSUE TITLE
Cannot grant access to s3 object with id

### ISSUE THREAD

**Issue by robbymckilliam** [aws/aws-cli#2651]
```
aws s3 cp somefile s3://somebucket --grants read=id=123456789012
```
Returns
```
upload failed: ./somefile to s3://somebucket An error occurred (InvalidArgument) when calling the PutObject operation: Invalid id
```
I've confirmed the Id I'm using is valid. The documentation ``aws s3 cp help`` under ``--grants`` states
```
            o id - The account's canonical ID
```
Am I interpreting this incorrectly?

**Comment by JordonPhillips** [comment]
That looks like the actual id you passed is invalid. Can you confirm that it is correct? You can get it by running:

`aws sts get-caller-identity --query Account --output text`

from the account in question.

**Comment by robbymckilliam** [comment]
I'm using the same number as obtained from 
```
aws sts get-caller-identity --output text --query 'Account'
```

**Comment by jamesls** [comment]
Hi, sorry for the confusion here.  To use grants with S3 you need to use the canonical user id, which is different from the account id.  More info here: http://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html#FindingCanonicalId .  The canonical user id will be longer than the account id and is usually ~65 chars or so.

Let me know if that doesn't work for you.

cc @JordonPhillips

**Comment by sachinerosnow** [comment]
How do i grant permission by using group_uri

**Comment by ElijaxApps** [comment]
I got the same question:

How to grant access for a Bucket to a Group? What is exactly the property "Group.Uri", and where can I find it in AWS?

I wrote this portion of code

```
const bucket = new aws.s3.Bucket(bucketName, {
	grants: [{
         type: "Group",
         permissions: ["FULL_CONTROL"],
		 uri: "*",
	}],
});

```

And I got the following error:

```
 aws:s3:Bucket (bucket-full):
    error: 1 error occurred:
        * updating urn:pulumi:dev::fulleu::aws:s3/bucket:Bucket::bucket-full: 1 error occurred:
        * Error putting S3 Grants: InvalidArgument: Invalid group uri
        status code: 400, ...
```

Help very appreciated.
