### ISSUE TITLE
Standalone binary for MacOS

### ISSUE THREAD

**Issue by divyenduz** [aws/aws-cli#2652]
Hey all, I am not entirely sure if this is the right place to ask this question but I will explain the issue I am facing. 

I am working on a MacOS app that provides a GUI interface on top of `aws s3 sync` command. 

The app does not make any assumptions on whether `aws` command is present and tries to install both `brew` and `aws` command via brew in the setup. 

I am using `Process` class from swift 3 and relying on `which` command to detect `brew` and `aws` command and if that is not available, try to install it. Roughly, the script interfaced by swift 3 looks like this 

```
#!/bin/sh

export PATH=$PATH:/usr/local/bin

if ! [ -x "$(command -v $1)" ]; then
    echo $2
    if [ $1 == "brew" ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &>/dev/null
    fi
    if [ $1 == "aws" ]; then
        brew install awscli &>/dev/null
    fi
fi
```

But on different MacOS versions, I am running into issues with managing the automatic installation. 

I was wondering if it is possible to ship a specific version of the "awscli" with the app. I am looking at something like 

`cp /usr/local/bin/aws <project folder>` and then removing all the auto install scripts. Would something like this be possible ?

Thanks

**Comment by JordonPhillips** [comment]
You could try using the [bundled installer](http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html). It does have a requirement on Python, but MacOS comes with python by default so you should be good.

**Comment by divyenduz** [comment]
I think this solves it for me, thanks.
