### ISSUE TITLE
Create tags while running create-snapshot

### ISSUE THREAD

**Issue by ethicalmohit** [aws/aws-cli#2662]
I am not sure why they have mentioned tags in the output when they are not allowing to use "--tags" with the "create-snapshot". 

Command:

`aws ec2 create-snapshot --volume-id vol-1234567890abcdef0 --description "This is my root volume snapshot."`

Output:

```
{
    "Description": "This is my root volume snapshot.",
    "Tags": [],
    "VolumeId": "vol-1234567890abcdef0",
    "State": "pending",
    "VolumeSize": 8,
    "StartTime": "2014-02-28T21:06:01.000Z",
    "OwnerId": "012345678910",
    "SnapshotId": "snap-066877671789bd71b"
}
```

Any idea ?

**Comment by jamesls** [comment]
Not sure about that.   This is how the response is returned from the EC2 service API itself: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html

I'd suggest reaching out on the [EC2 Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) to see if someone can shed some light on this issue.  But I don't think there's anything we'd be able to do client side.
