### ISSUE TITLE
A client error (SignatureDoesNotMatch) occurred when calling the CreateBucket operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by dschinkel** [aws/aws-cli#2665]
I have been able to run my s3 commands just fine.  But today when I try from my local PC (OSX, command-line cli calls) as I always have when testing, I get:

`aws s3api create-bucket --bucket our-bucket-name --region us-west-2 --create-bucket-configuration LocationConstraint=us-west-22
`

and it is bombing today out of the blue with `A client error (SignatureDoesNotMatch) occurred when calling the CreateBucket operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.`

what could cause this all of a sudden?  I rebuilt a previous Travis build using some AWS credentials I had addd as enviornment variables in Travis and that build still works with the asw credentials I specified, but I've **not** had to specify my AWS credentials locally for aws cli calls or if I did, then I don't remember but regardless this was working fine yesterday.

Here's another call that was working just fine up till now 

`aws s3api head-bucket --bucket mayfield-gizmo-react-web-admin-wa-19`

```
A client error (403) occurred when calling the HeadBucket operation: Forbidden
So why was I able to make calls fine without specifying credentials locally, but now it's complaining all of a sudden?
```

So why was I able to make calls fine without specifying credentials locally, but now it's complaining all of a sudden?

**Comment by dschinkel** [comment]
I don't know what it was but I reset my credentials locally and it's working.  No idea why the hell it would just stop using the credentials that are already set locally which I guess I did do at some point:

<img width="533" alt="screen shot 2017-06-14 at 12 47 19 pm" src="https://user-images.githubusercontent.com/338798/27146716-e0c6fdda-50ff-11e7-9f52-1a9da76d2de4.png">

**Comment by Genaker** [comment]
This error occurred when you AWS credential set using environment variables And  key has special characters in my case "/"

**Comment by nicovigil1** [comment]
^-- This solved my problem

**Comment by mckadesorensen** [comment]
Thank you, worked like a charm!

**Comment by gomezjesus** [comment]
I got a special character too a "+" plus symbol. Generated other key without special charactes and it is working again!
Thanks

**Comment by continuum-dev-chaudhary** [comment]
Worked for me :D
TRY THIS:
Just had this happening to me and was a result of my system time being off by too much even though it did not report that. Ran ntpdate against pool.ntp.org and fixed this problem for me.

**Comment by negeek** [comment]
> 

show me how you did it

**Comment by elixapesa** [comment]
My AWS credentials are from STS assume role. How do I make sure it does not generate a special character?

**Comment by DPubliweb** [comment]
> This error occurred when you AWS credential set using environment variables And the key has special characters in my case "/" Related issue: #602

Well done

**Comment by seekatekode** [comment]
I ran into this issue a few weeks ago and finally found this post! Resetting the      AWS SECRET ACCESS KEY     helped with this issue and I am now able to successfully run     ./bin/db/update_cognito_user_ids
THANK YOU!🙏🏾

**Comment by l-alfaro** [comment]
> Worked for me :D TRY THIS: Just had this happening to me and was a result of my system time being off by too much even though it did not report that. Ran ntpdate against pool.ntp.org and fixed this problem for me.

`sudo ntpdate pool.ntp.org`

**Comment by pritamedge** [comment]
create ramdom number in python
