### ISSUE TITLE
s3 cp asterisk expansion is broken on msys2

### ISSUE THREAD

**Issue by iongion** [aws/aws-cli#2673]
Windows 10

```
bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
```

In msys2, running this command:

```
 aws s3 cp './build/release/2.0.5/' s3://my-nice-bucket/2.0.5 --recursive --exclude "*" --include 'MyLambda-1.0.3.zip' 
```

Outputs this:

```
 aws s3 cp './build/release/2.0.5/' s3://my-nice-bucket/2.0.5 --recursive --exclude "*" --include 'MyLambda-1.0.3.zip' --profile admin@prod --region eu-west-1

Unknown options: .editorconfig,.git,.gitignore,.jscsrc,.jshintrc,...
```

This means, something badly expands the asterisk. The same command works in cygwin:
```
bash --version
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
```

So on cygwin `4.4.12(3)`, on msys `4.4.12(1)`

**Comment by kyleknap** [comment]
Unfortunately, I was not able to reproduce it.

So the way the CLI works in terms of wildcard use is that it will pass the literal `*` value into the CLI executable. It does not do any expanding prior to that. Here is an example of the debug logs I was seeing when I added ``--debug`` to the command:
```
2017-06-21 16:46:41,509 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', 'docs', 's3://my-nice-bucket/2.0.5', '--recursive', '--exclude', '*', '--include', 'MyLambda-1.0.3.zip', '--debug']
```
If arguments are being expanded, it is because of the shell being used. However, I am not entirely sure why it would be expanding the wildcard, especially since you quoted. If you can figure out a way to ensure bash does not expand the wildcard you should be able to get to this to work. Does the asterisk get expanded for other commands (not AWS CLI commands) installed?

**Comment by iongion** [comment]
Here is what I get as output from Linux(Ubuntu/WSL)

![image](https://user-images.githubusercontent.com/867609/27424822-acdbd238-5736-11e7-81a0-fe9e846a2aa8.png)
![image](https://user-images.githubusercontent.com/867609/27424898-f1bc6a8e-5736-11e7-896e-8c7e7a4f29aa.png)

And here is what I get as output from msys:

![image](https://user-images.githubusercontent.com/867609/27424846-beb4c046-5736-11e7-9b14-2569fd9ffebc.png)
![image](https://user-images.githubusercontent.com/867609/27424888-e6a74a06-5736-11e7-867a-2d9592a38e56.png)

[awscli.zip](https://github.com/aws/aws-cli/files/1094130/awscli.zip)

This will help you reproduce it, the test.sh inside the zip must be adjusted to your env:

```bash
#!/bin/bash
S3_ARN=s3://...
AWS_PROFILE=...
AWS_REGION=eu-west-1

aws s3 cp ./test/ $S3_ARN --recursive --exclude "*" --include f2.txt --profile $AWS_PROFILE --region $AWS_REGION
```

**Comment by iongion** [comment]
$ uname -a
MINGW64_NT-10.0 ws1-pc 2.7.0(0.306/5/3) 2017-02-14 08:57 x86_64 Msys

**Comment by iongion** [comment]
I just tested with this other command:

```
#!/bin/bash
S3_ARN=s3://...
AWS_PROFILE=...
AWS_REGION=eu-west-1

aws s3 cp ./test/ $S3_ARN --recursive --exclude="*" --include="f2.txt" --profile $AWS_PROFILE --region $AWS_REGION
```

And now it works on `msys` too! It really does upload only `f2.txt` and does not get stuck.

You should still try to see why it doesn't work on with the first shape, without the `=` between args and the values, almost all of the online examples on `cli` usage are with that shape.
Feel free to close this ticket whenever you want if you consider it a non-issue.
Thank you very much for paying attention to this!
