### ISSUE TITLE
ECR doesn't create repository and returns false response

### ISSUE THREAD

**Issue by jaipradeesh** [aws/aws-cli#2675]
```
2017/06/21 13:40:43 bake.go:222: {
    "repository": {
        "repositoryArn": "arn:aws:ecr:ap-southeast-1:000:repository/django-postgresql-63e6930f9ef4434c9e017c8821c17b-165381",
        "registryId": "000",
        "repositoryName": "django-postgresql-63e6930f9ef4434c9e017c8821c17b-165381",
        "repositoryUri": "000.dkr.ecr.ap-southeast-1.amazonaws.com/django-postgresql-63e6930f9ef4434c9e017c8821c17b-165381",
        "createdAt": 1498032633.0
    }
}
```

Command
```
"aws", "ecr", "create-repository", "--repository-name", "django-postgresql-63e6930f9ef4434c9e017c8821c17b-165381"
```

Repository isn't created. It isn't issue with auth because it works at times. It doesn't at times.

```
➜  ~ aws --version
aws-cli/1.11.105 Python/3.6.1 Linux/4.11.3-1-ARCH botocore/1.5.68
```

**Comment by dolftax** [comment]
https://dpaste.de/oWmY/raw

Could be related.

**Comment by kyleknap** [comment]
Does the repository eventually show up ever for the ones that fail out? It may be an eventual consistency issue where you may just have to wait a little longer for the repository to be available. In general if the CLI is not returning an error on the command, it was able to successfully make the request and the service responded back with a successful HTTP status code.

**Comment by dolftax** [comment]
- The repository did not eventually show up
- What do you mean `little longer`?

**Comment by justnance** [comment]
@jaipradeesh - Just checking in to see if this is still an issue and if the CLI returned any errors.  If it is still an issue, how long is it taking for the repository to become available?

**Comment by jaipradeesh** [comment]
@justnance I don't use ECR anymore. I'm not sure if this still exists (or) fixed.

**Comment by justnance** [comment]
@jaipradeesh - Thanks for the feedback. I'm going to close this issue.

**Comment by oluwatosinobembe** [comment]
Can anyone help please? I'm getting the same error.
Trying to build, tag and push my docker image to Amazon ECR but it fails at the point of pushing it with the error: "name unknown: The repository with name '<reponame>' does not exist in the registry with id '***'
"
