### ISSUE TITLE
aws ecr get-login broken in latest rc build

### ISSUE THREAD

**Issue by sixcorners** [aws/aws-cli#2676]
$ `aws ecr get-login`
    unknown shorthand flag: 'e' in -e
    See 'docker login --help'.

    $ docker --version
    Docker version 17.06.0-ce-rc4, build 29fcd5d

**Comment by JordonPhillips** [comment]
You will need to supply the `--no-email` flag

**Comment by rpnguyen** [comment]
Also, please see this forum post for more context about this https://forums.aws.amazon.com/ann.jspa?annID=4656

**Comment by ottumm** [comment]
Why is this marked as "closing-soon-if-no-response"? The `aws` commandline tool is generating the incorrect `docker login` command, so this seems like a bug with `aws`, not a question. This is currently breaking deployment scripts for me.

**Comment by ottumm** [comment]
> You will need to supply the --no-email flag

The flag is `--no-include-email`, not `--no-email`.

**Comment by JordonPhillips** [comment]
@ottumm We can't change our current behavior or we'll break customers locked to older versions of docker. The compromise is to have the flag which will allow customers who upgrade to unblock themselves.

**Comment by Clecompt** [comment]
Rather than adding a flag why not detect the docker version.  It seems that the AWS client has enough information to decide whether or not to include the -e in the login command rather than generating an invalid command.

**Comment by ottumm** [comment]
Absolutely agree with @Clecompt. There are environments (e.g. Travis) where the Docker version is not under the user's control. Detecting the Docker version and emitting the appropriate command seems like the right thing to do here.

**Comment by stealthycoin** [comment]
Because detecting the docker version and testing that on every possible system configuration people are using in the CLI in is not feasible and very brittle even if we could get it to work. Even if we could get this to work that makes the assumption that the login command is being run on the same machine in the environment where we detected the docker version. People have very complicated build systems spread out over multiple machines/images/environments so that is not an acceptable assumption to make.

You can control the docker version in travis by the way using the before_install key.

**Comment by paistipoikka** [comment]
@stealthycoin Has this issue been fixed?

Agreed that detecting the docker version is no good.

The email option has been removed from Docker so having some sort of `--no-include-email flag` is required.

**Comment by vanaparth** [comment]
@JordonPhillips  I am adding --no-include-email it gives me Unknown Options. According aws docs, Updated to latest version still I get the same Unknown Options.

**Comment by igarcez** [comment]
@vanaparth had the same issue, updating aws cli tools with `sudo pip install --upgrade awscli` fixed the problem

**Comment by vanaparth** [comment]
I tried the command which you mentioned still getting the same problem. Is there any other way we can clear this issue. @igarcez

**Comment by vanaparth** [comment]
@igarcez Here is the other way  to login. I have a workaround 
sudo docker login -u AWS -p $(aws ecr get-authorization-token --output text --query authorizationData[].authorizationToken | base64 -d | cut -d: -f2) ${ECR_URL}.

**Comment by sfertman** [comment]
Still broken. Installed the latest version of AWS CLI. 
Running this command:
```bash
aws ecr get-login --region <my-region> --no-include-email
```
returns
```bash
Unknown options: --no-include-email
```

**Comment by zeg-io** [comment]
Still an issue!

`aws ecr get-login --region us-west-2 --no-include-email`

yields:

`Unknown options: --no-include-email`

```sh
$ aws --version

aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1022-aws botocore/1.4.70
```

**Comment by bbakersmith** [comment]
@sfertman @zeg-io you're not using the latest. i'm on 1.11.120 and the following works for me

    aws ecr get-login --region us-east-2 --no-include-email

looks like it was added in 1.11.91: https://github.com/aws/aws-cli/commit/4b3e8d0b21532d8a0e29c3a817978ca7f213d501

**Comment by mmas** [comment]
@zeg-io you are actually using version `1.11.130` (`aws-cli/1.11.13`), I just downgraded to `1.11.120` and it works fine

**Comment by bbakersmith** [comment]
@mmas why do you say he's using version `1.11.130` when it says `aws-cli/1.11.13`? I'm running `1.11.120` and it doesn't get truncated when I run --version, it shows `aws-cli/1.11.120`. Wouldn't @zeg-io be running 1.11.13?

**Comment by mmas** [comment]
@bbakersmith I had version `1.11.130` (checked with pip) and it was showing truncated for me with `awscli --version`

**Comment by bbakersmith** [comment]
@mmas odd. it doesn't for me. I just upgraded and get `was-cli/1.11.130` as expected.

**Comment by bbakersmith** [comment]
And the `--no-include-email` flag does work in `1.11.130` for me.

**Comment by ChrisRyuGS** [comment]
aws-cli/1.11.42 Python/2.7.10 Darwin/16.7.0 botocore/1.5.5
I've got still "Unknown options: --no-include-email"

**Comment by bbakersmith** [comment]
@ChrisRyuGS You need to upgrade. As I said a few comments up, it was added in 1.11.91 
https://github.com/aws/aws-cli/issues/2676#issuecomment-320051215

**Comment by ChrisRyuGS** [comment]
@bbakersmith How to upgrade awscli?
I've already upgrade awscli by pip install -U awscli
Ryu-rMBP:~ test$ pip install -U awscli
Requirement already up-to-date: awscli in ./.local/lib/python3.6/site-packages
Requirement already up-to-date: botocore==1.6.3 in ./.local/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: colorama<=0.3.7,>=0.2.5 in ./.local/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.9 in ./.local/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: PyYAML<=3.12,>=3.10 in ./anaconda/envs/ipykernel_py3/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: docutils>=0.10 in ./.local/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: rsa<=3.5.0,>=3.1.2 in ./.local/lib/python3.6/site-packages (from awscli)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in ./.local/lib/python3.6/site-packages (from botocore==1.6.3->awscli)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.1 in ./.local/lib/python3.6/site-packages (from botocore==1.6.3->awscli)
Requirement already up-to-date: pyasn1>=0.1.3 in ./.local/lib/python3.6/site-packages (from rsa<=3.5.0,>=3.1.2->awscli)
Requirement already up-to-date: six>=1.5 in ./anaconda/envs/ipykernel_py3/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.6.3->awscli)

**Comment by Denvious** [comment]
Hopefully this helps someone, as my aws --version was not changing (Ubuntu 16.04).

Managed to resolve by using pip3 instead:

```
pip3 install --upgrade awscli
```

This may require you to install 
```
apt-get install python3-pip
```

```
Before pip3
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1038-aws botocore/1.4.70

After pip3
aws-cli/1.14.2 Python/3.5.2 Linux/4.4.0-1041-aws botocore/1.8.6
```

**Comment by altitude** [comment]
For people coming from Google stuck here on old environments, there's an easy solution :

```SHELL
eval $(aws ecr get-login --region eu-west-1 | sed 's/ \-e none//')
```

**Comment by branflake2267** [comment]
The workaround for aws docker login error I use.

* Run `aws ecr get-login` 
* Run the output of get-login. (Remove the flag `-e none` in the comand). Look for successful login output.
* Run `cat ~/.docker/config.json` to verify.

**Comment by ricardojohnny** [comment]
This status code usually indicates an unauthorized user. To fix this, we need to let our Code Build role be able to talk to ECR. To do this: Go to IAM and then attach a AmazonEC2ContainerRegistryPowerUser policy to your CodeBuild role.
