### ISSUE TITLE
Parameter Store 'put-parameter' doesn't allow global KMS key

### ISSUE THREAD

**Issue by schmohlio** [aws/aws-cli#2682]
the `--key-id` in `aws ssm put-parameter` doesn't allow you to specify the full ARN of the kms key or an alias (`alias/<aliasName`). This means that I can't create a secure string in a region other than `us-east-1` where my KMS key is located (KMS keys are global, unlike AWS Parameter Store).

**Comment by stealthycoin** [comment]
The CLI is just a wrapper around the KMS API and this is a service-specific feature request so this is best directed to the KMS [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=182).
