### ISSUE TITLE
ECR docker login w/out AWS CLI

### ISSUE THREAD

**Issue by ichekrygin** [aws/aws-cli#2687]
This is a feature request.

While AWS CLI is a great and at times indispensable tool, most if not all functionality is also available via AWS WEB UI. Well, at least for me, and I am not a "power user". 

When comes down to AWS ECR it appears **the only ** way to obtain `docker login` information is via `aws ecr get-login ...` command.  

I know it says right [here](http://docs.aws.amazon.com/AmazonECR/latest/userguide/get-set-up-for-amazon-ecr.html)
```
1. Sign Up for AWS
2. Create an IAM User
3. Install the AWS CLI
```

Still, I and (in my observation) many of my fellow engineers find it at very least a little inconvenient having to install AWS CLI just for the sake of one command. And, until recently, install and keep it (AWS CLI) up to date, to keep up with changing flags.

**Comment by stealthycoin** [comment]
This is the repo for the AWS CLI only so i'm not sure this is a feature request for us. We already support that command as mentioned.

**Comment by ichekrygin** [comment]
@stealthycoin you are absolutely correct. If you know could you please suggest the repo for this issue?

**Comment by caboteria** [comment]
@ichekrygin it sounds as if you need to open a support ticket with AWS asking them to add this feature to the web UI.  The AWS web UI is proprietary so there's no public git repo.

**Comment by JordonPhillips** [comment]
@caboteria correct, I believe support is the way to go here.

**Comment by ichekrygin** [comment]
Just FYI: https://hub.docker.com/r/illya/aws-cli/

**Comment by toshke** [comment]
@ichekrygin AWS Labs released ECR Credentials helper (written in Go) which does the ecr login  under the hub for you - https://github.com/awslabs/amazon-ecr-credential-helper
