### ISSUE TITLE
`ecr get-login` should probably default to `--no-include-email` now.

### ISSUE THREAD

**Issue by rofinn** [aws/aws-cli#2691]
The deprecated `-e` flag (to `docker login`) has been completely removed as of docker-ce 17.06, so `aws ecr get-login` should probably default to `--no-include-email` now.

**Comment by stealthycoin** [comment]
That would break existing customers upgrading the CLI version so we cannot do that.

**Comment by rofinn** [comment]
Couldn't this be solved with a deprecation cycle (using semantic versioning and a warning message)? Alternatively, awscli could check the installed docker version (`docker -v`), but that seems unnecessary.

**Comment by JordonPhillips** [comment]
We have some data on how many customers are using old versions of docker. If that number drops to acceptable levels then we can change the default. That might be a while though :(
