### ISSUE TITLE
cloudformation package does not support pipeline s3 source action

### ISSUE THREAD

**Issue by winmillwill** [aws/aws-cli#2692]
If you try to use awslabs/ecs-refarch-continuous-deployment and change the TemplateUrl references to paths in the repo, you still end up using the original refarch bucket for the Source action in the pipeline that eventually yields the ECS Service.

Ideally, the S3Bucket and S3ObjectKey properties of Configuration for the Source action, and also later references to the artifact, could be updated by the package command. This seems like a bear to "just do it" automatically, so what would make sense to me is to populate some Refs for the package bucket and paths that are being transformed. I'm totally waving my hands here, but I would be fine with maintaining a template like:

```
...
              Configuration:
                S3Bucket: !Ref CloudformationPackageBucket
                S3ObjectKey: !GetAttr CloudformationPackageBucket.Templates
...
                TemplatePath: Template::service.yaml
...
```

**Comment by JordonPhillips** [comment]
This seems more like a feature request for CloudFormation itself. I recommend submitting this feature request to the service team more directly either via their forums or support.
