### ISSUE TITLE
Data required in JSON format		

### ISSUE THREAD

**Issue by ricky1988** [aws/aws-cli#2693]
I have number of instances running in my aws account. I want to following information in JSON format or any other format
1) Number of EC2 Instances running	
2) Number of RDS	
3) Number of EBS Volumes
4) Number of S3 / Glacier Buckets	

In each I want detailed information. I have been trying this for 3 days. Please someone help me out.

**Comment by JordonPhillips** [comment]
For service usage questions I'd recommend making use of one of our [community resources](https://github.com/aws/aws-cli#getting-help). In this case you'll want to look at the describe* and list* operations.
