### ISSUE TITLE
AWS console page size persistence

### ISSUE THREAD

**Issue by jch254** [aws/aws-cli#2695]
Hello,

I have searched far and wide for a place to report AWS console related issues but couldn't find anything - could someone please can direct my request appropriately.

I am using AWS CodeCommit, CodePipeline and CodeBuild heavily and have a large number of repositories and projects. The page size selector defaults to 10 and does not persist on refresh. Is it possible to either persist page size on refresh or increase the default page size? ECR page size selector defaults to 100.

Thanks for any help

**Comment by dstufft** [comment]
Hmm, I think the best location for this would be to open a thread on the AWS developer forums. Unfortunately there isn't one specific to the console, but I think the best place would be for the service you're looking to have this done for. Like https://forums.aws.amazon.com/forum.jspa?forumID=189 for CodeCommit.

**Comment by jch254** [comment]
Champion thanks @dstufft 👍
