### ISSUE TITLE
put-notification-configuration internal error

### ISSUE THREAD

**Issue by kakusco** [aws/aws-cli#2699]
Hello,

we are using this command since a while:
`aws autoscaling put-notification-configuration --auto-scaling-group-name xyz-asg --region eu-west-1 --topic-arn arn:aws:sns:xyz --notification-types autoscaling:EC2_INSTANCE_LAUNCH autoscaling:EC2_INSTANCE_LAUNCH_ERROR autoscaling:EC2_INSTANCE_LAUNCH autoscaling:EC2_INSTANCE_TERMINATE autoscaling:EC2_INSTANCE_TERMINATE_ERROR`

On July, 4th it stopped working. This is the error feedback:
`A server error (InternalFailure) occurred when calling the PutNotificationConfiguration operation: The service has encountered an internal error. We apologize for the inconvenience.`
The result is, there are no notifications set and we got endless Test-Notification-Mails.

The last time, we used it, on June 20th, it worked.
We are using aws-cli 1.9.1

Does anyone has an hint, what we can do?

**Comment by JordonPhillips** [comment]
This is a service side error, I would recommend contacting support about this issue.

**Comment by kakusco** [comment]
We finally found it!
The problem was the double option EC2_INSTANCE_LAUNCH. Removed one and the script is working without any problems.
