### ISSUE TITLE
Multiple Values in EB Create-environment option-settings

### ISSUE THREAD

**Issue by mkaws** [aws/aws-cli#270]
Is there a way to specify multiple VPC or ELB subnets in the option-settings commands for EB create-environment?    Namespace=aws:ec2:vpc,OptionName=Subnets,Value=subnet-xyz subnet-abc or subnet-xyz,subnet-abc

**Comment by JordonPhillips** [comment]
According to the [elastic beanstalk api](http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_ConfigurationOptionSetting.html) this does not seem to be possible.
