### ISSUE TITLE
AWS Route53 malformed response 

### ISSUE THREAD

**Issue by ideahitme** [aws/aws-cli#2701]
#### How to reproduce: 
Create a wildcard record (e.g. `*.mycompany.com -> my-loadbalancer.elb.com`), then try to retrieve it back with aws-cli (or any other SDK):

```bash
aws route53 list-resource-record-sets --hosted-zone-id=my-zone-id | jq '.ResourceRecordSets|map(select(.Name=="\\052.*.mycompany.com."))'
[
  {
    "TTL": 300,
    "ResourceRecords": [
      {
        "Value": "my-loadbalancer.elb.com"
      }
    ],
    "Type": "CNAME",
    "Name": "\\052.mycompany.com."
  }
]
```
The response comes malformed with a additional escape backslash. This will fail any string matching, because obviously 

`*.mycompany.com. != \\052.mycompany.com.`

More information here: https://github.com/kubernetes-incubator/external-dns/issues/264

**Comment by JordonPhillips** [comment]
How are you creating the record? Could you post a --debug log showing what's coming back over the wire?

**Comment by ideahitme** [comment]
The records are creating using [aws-sdk-go](https://github.com/aws/aws-sdk-go/), as follows:

```go
	change := &route53.Change{
		Action: aws.String(action),
		ResourceRecordSet: &route53.ResourceRecordSet{
			Name: aws.String(endpoint.DNSName), // it is "*.mycompany.com"
		},
	}
```

Which part of the debug output u are interested in ?

**Comment by ideahitme** [comment]
any updates?

**Comment by JordonPhillips** [comment]
You should be checking out the raw `Response body` (grep for that string) in the debug logs so that we can see if it's an issue with us or with the service.

**Comment by ideahitme** [comment]
@JordonPhillips 
here is it ( I changed some info and removed other records from the list) 
```xml
<?xml version="1.0"?>\n

<ListResourceRecordSetsResponse
    xmlns="https://route53.amazonaws.com/doc/2013-04-01/">
    <ResourceRecordSets>
        <ResourceRecordSet>
            <Name>\\052.wildcard.mycompany.com.</Name>
            <Type>A</Type>
            <AliasTarget>
                <HostedZoneId>ZMOD1F1ED2BY7OV</HostedZoneId>
                <DNSName>catwatch.mycompany.com.</DNSName>
                <EvaluateTargetHealth>false</EvaluateTargetHealth>
            </AliasTarget>
        </ResourceRecordSet>
    </ResourceRecordSets>
    <IsTruncated>false</IsTruncated>
    <MaxItems>100</MaxItems>
</ListResourceRecordSetsResponse>
```

**Comment by JordonPhillips** [comment]
Interesting, so it looks like this is behavior from the service and not some mangling on our part. Unfortunately that means that there isn't anything that we can do about it. I would recommend opening a ticket with [support](https://console.aws.amazon.com/support/home#/) asking for a change, such as a flag to request it not be converted that way.

**Comment by ideahitme** [comment]
Okay, I will create a support ticket, thanks. I think this issue can be closed then

**Comment by redbaron** [comment]
@JordonPhillips ,this is an annoying, but documented behaviour: http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html?shortFooter=true#domain-name-format-asterisk

so if aws-cli did do something about it, it would be very helpful :)
