### ISSUE TITLE
Amazon Connect CLI & Amazon WorkSpaces Application Manager CLI

### ISSUE THREAD

**Issue by lmenaolivares** [aws/aws-cli#2703]
Add support to work with Amazon Connect and Amazon WorkSpaces Application Manager using the command line interface

**Comment by JordonPhillips** [comment]
Unfortunately it looks like neither of those services have public api's that we can make use of, so we won't be able to support them.

**Comment by lmenaolivares** [comment]
Sorry to hear that.
Thanks anyway.
