### ISSUE TITLE
lex-models is not available?

### ISSUE THREAD

**Issue by GomuGomuMan** [aws/aws-cli#2704]
I want to manipulate the model for my chatbot on the CLI. I tried executing on bash: 

`aws lex-models`

However, it gives me:

> aws: error: argument command: Invalid choice, valid choices are: ...

I thought this option is supported since it is mentioned in the [documentation](http://docs.aws.amazon.com/cli/latest/reference/lex-models/index.html)

**Comment by JordonPhillips** [comment]
You will need to update your version of the CLI. The latest version is 1.11.117
