### ISSUE TITLE
AWS s3 uploads empty (0Kb) file

### ISSUE THREAD

**Issue by MarcoPorracin** [aws/aws-cli#2707]
Im trying to make my ec2 upload files on startup to my s3 bucket using crontab. I used the following lines in *crontab -e* 

```
@rebbot > s3log
@reboot aws s3 cp /path/localfile.csv s3://bucketname >> s3log 2>&1
```

The first line clears the log file, and the second make the upload and logs it on a file named 's3log'. After this everything that appears on the s3log is:

> upload: ./data_xxxxxxx.csv to s3://bucket-name/data_xxxxxxx.csv

So far everything ok, the file was meaning to copy is on the ec2

![kj4il](https://user-images.githubusercontent.com/22181136/28133116-4a43cf06-6715-11e7-8a3c-5e851ae04272.png)

But when i try to access the file from the s3 bucket it is empty:

![nzahi](https://user-images.githubusercontent.com/22181136/28133127-523472ba-6715-11e7-8fcf-29b4b42dad70.png)

When i do this task manually it works just fine.
Any ideas why this could be happening?

Since the .csv is generated just before the upload with a python script i tried delaying the upload with a sleep 30 but i keep having the same problem.

**Comment by JordonPhillips** [comment]
Not sure what's going on. Could you provide `--debug` logs to help out?

**Comment by MarcoPorracin** [comment]
This is the debug log:

[s3log.zip](https://github.com/aws/aws-cli/files/1145145/s3log.zip)

**Comment by MarcoPorracin** [comment]
I worked around it using boto3 and uploading the file directly from it.
