### ISSUE TITLE
aws cloudformation package re-uploads the same file when used with SAM

### ISSUE THREAD

**Issue by dinvlad** [aws/aws-cli#2712]
Hi Team,

Using `aws cloudformation package` with a SAM template, this command doesn't seem to recognize when the directory specified through the `CodeUri` property is shared between multiple functions. So it ends up uploading the same package over and over again (once for each function that uses the same  `CodeUri`). It would seem that it should keep the hash of the `CodeUri` property and only upload corresponding package once for each hash.

Thanks

**Comment by dinvlad** [comment]
Somewhat related, #2582

**Comment by stealthycoin** [comment]
I would prefer you add a comment in that issue #2582 since this is more or less the same feature request.
