### ISSUE TITLE
Environment variables in README and User Guide out of sync

### ISSUE THREAD

**Issue by jcrben** [aws/aws-cli#2716]
It looks like the User Guide describes 6 environment variables (https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) while the README describes 10 (https://github.com/aws/aws-cli#other-configurable-variables). There's also https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#cli-aws-help-config-vars which covers the same general topic.

I imagine they may be out of sync in other more subtle ways and I'm not sure 3 discussions of the same general topic is a great iea, but at the least the AWS_SHARED_CREDENTIALS_FILE variable should be added to the User Guide so that people who find AWS_CONFIG_FILE there can quickly see how to relocate both files.

**Comment by stealthycoin** [comment]
Thanks for reporting this.

**Comment by justnance** [comment]
@jcrben - Thanks again for reporting this anomaly.  An internal ticket has been submitted to our documentation writers for review.

**Comment by justnance** [comment]
@jcrben - This issue is being closed as our documentation has been updated and in sync now.  I'm closing this issue.
