### ISSUE TITLE
Allow cloudformation deploy to complete successfully if there are no changes

### ISSUE THREAD

**Issue by rtimush** [aws/aws-cli#2717]
`aws cloudformation deploy` fails if there are no changes. However, when it is used as a part of CI/CD pipeline, we usually want to treat this case as a success. It would be nice if there was an option like `--allow-empty-changeset`, or at least the process exit code was different for "nothing to do" and "failed to do" cases.

**Comment by stealthycoin** [comment]
This would be a feature request for the cloudformation team, we just wrap their API in a command line utility we don't actually make the APIs themselves.

Best way to do this would be to open a [support ticket](https://console.aws.amazon.com/support/home#/) with your feature request.

**Comment by rtimush** [comment]
If anyone comes across this closed issue, there is a `--no-fail-on-empty-changeset` option now.

**Comment by niklasastrom** [comment]
I am running into the same issue, and the `--no-fail-on-empty-changeset` flag doesn't make a difference. The flag is recognised by the CLI (at least it does not say `Unknown option`), but it still fails with the error message `FAILED. Reason: No updates are to be performed.`. @rtimush , are you successfully using this flag?

**Comment by tmaior** [comment]
I have the same issue. --no-fail-on-empty-changeset does not work. Any planning on fixing that?
