### ISSUE TITLE
Unknown options for AWS Cli export 

### ISSUE THREAD

**Issue by richardxin** [aws/aws-cli#2725]
Steps to reproduce:
1. Create an EMR cluster on aws console
2. AWS Cli export  to get aws commandline
3. run the command from step 2

got error: 
Unknown options: --ebs-root-volume-size,10

**Comment by joguSD** [comment]
I believe this option was added quite recently.
Try updating your aws cli and see if you still have the issue.
It should work in `aws-cli/1.11.123`.

**Comment by smhillin** [comment]
This issue is still occuring in 1.11.55

**Comment by joguSD** [comment]
This flag was added in `1.11.123`. You need to update to at least this version for it to work.

**Comment by smhillin** [comment]
@joguSD I have the latest version. 1.11.55

**Comment by joguSD** [comment]
What platform are you on? What method did you use to install the cli?

**Comment by smhillin** [comment]
pip install --upgrade --user awscli
on iterm2 on IOS Sierra 10.12.6

[image: Inline image 1]



SHAUN HILLIN // Managing Partner

512.761.7653 // xmm.io
Twitter <https://twitter.com/XtraMileMedia> | Facebook
<https://www.facebook.com/XtraMileMedia> | Linkedin
<http://www.linkedin.com/company/xtra-mile-media>




This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by joguSD** [comment]
Hmm. Not sure why that wouldn't update to the latest version. Perhaps a version of another library is causing this. You could try `pip install -I --user awscli` to ignore any previously installed versions.
