### ISSUE TITLE
DynamoDB Duplicate Key-Value Insertion

### ISSUE THREAD

**Issue by danielschnoll** [aws/aws-cli#2727]
This is a cross post from my reddit thread on [r/aws](https://www.reddit.com/r/aws/comments/6p9nii/dynamodb_duplicate_keyvalue_pair_insertion_will/). Also I recognize this is for aws CLI, but there's no repo for Python, so I figured this is the next most appropriate repo to ask in. Additionally if there is a more appropriate place to ask this question, can you please direct me to it? Thanks. Anyway...

I'm currently trying to use DynamoDB to create a database for an event store. I'm new to using Dynamo, but from what I gather, Dynamo uses key-value pairs for hashing purposes. The table I'm constructing needs attributes like `event_type`, `event_details`, `user_id`, some other ids, and an `event_timestamp`.

I currently have `user_id` as my hash and `event_type` as my range. From what I've read on Stackoverflow and in the Dynamo docs, this is my key-value lookup for hashing purposes.

My question, however, is what happens to the table when there are multiple entries with the same `user_id` and `event_type`? Since the key-value pair would hash to the same location in the table, would it overwrite the existing entry? Or would the table look to other attributes for insertion? I read something about global/local secondary indexes, but what I found doesn't really answer my question nor are the docs very clear, especially for a beginner.

So for example, lets say a record already exists in the table with `user_id` 10239 and `event_type` 4. This happened at, say, `event_timestamp` 2017-07-22 12:10:04.123123. Now user 10239 triggers the `event_store` again with `event_type` 4. The key-value lookup is going to hash to the same location in the table, but `event_timestamp` is different, say 2017-07-24 11:30:34.589822.

Even though there are subtle differences between other table properties, would user 10239's entry in the table be overwritten by the new one, or does Dynamo look to other attributes, such as the `event_timestamp`, to determine where to place the new record? If it does in fact overwrite a preexisting entry because it was hashed to the same location, what can I do to prevent this from happening? 

**Update**: I just found stuff on another [Stackoverflow](https://stackoverflow.com/questions/12457130/what-will-happen-if-we-insert-into-dynamo-db-with-a-duplicate-hash-key) post where it links do a doc describing the conditional `attribute_not_exists`. However I can't find any documentation or SOF posts on using it. Can anyone please help?

**Comment by joguSD** [comment]
This is definitely a question for one of the community resources.
For links to various resources on getting help check [here](https://github.com/aws/aws-cli#getting-help).
