### ISSUE TITLE
Uploading data from Amazon S3 to Amazon Cloudsearch error.  

### ISSUE THREAD

**Issue by varun1993** [aws/aws-cli#2729]
I am trying to upload the data from Amazon S3 Bucket to Amazon CloudSearch domain using AWS CLI. When I try to execute the command 

cs-import-documents -d mydomain --source s3://mybucket/myobject.json

I get the following error : 
AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied)

When I try to use the command 

aws cloudsearchdomain upload-documents and pass in the s3 bucket url (https://s3-us-west-1.amazonaws.com/mybucket/myobject.json) 

I get the following error:

Error parsing parameter '--documents': Blob values must be a path to a file.

I have also gone through the error log file and the documentation for Amazon CloudSearch but I am not able to resolve the issue.  

I have given all read write permissions access in Amazon S3 bucket and Amazon CloudSearch Domain. I am also using the latest version of AWS CLI . 

I would really appreciate it if someone can help me regarding this.

**Comment by kyleknap** [comment]
Unfortunately, the tool you are using is not the AWS CLI. Instead, it appears to be a standalone [CloudSearch command line tool](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/cloudsearch-command-line-tools.html) so there is not much help that we can provide here as this repository is specifically for AWS CLI related issues. We do not have really any knowledge about the tool you are using. Instead, I would recommend opening a thread in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=137) to get help with that command line tool.
