### ISSUE TITLE
aws s3api can be used to create multipart uploads with tags

### ISSUE THREAD

**Issue by dheerajsangamkar** [aws/aws-cli#2735]
The AWS S3 documentation mentions that tags cannot be specified when creating an object using multipart upload operations.  (See http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html)

However, AWS CLI version - "aws-cli/1.11.117 Python/2.7.9 Windows/8 botocore/1.5.80" supports creation of objects using multipart uploads with tags specified during initiation of the multipart upload.

For example(with bucket name changed):
H:\>aws s3api create-multipart-upload --bucket mybucket --key 'multipart/01' --tagging "key=value"
...
H:\>aws s3api complete-multipart-upload --bucket mybucket --key 'multipart/01' --multipart-upload file://parts.txt --upload-id "<uploadid>"
...
H:\>aws s3api get-object-tagging --bucket mybucket--key 'multipart/01'
{
    "VersionId": "someversionid",
    "TagSet": [
        {
            "Value": "value",
            "Key": "key"
        }
    ]
}

Is this intended or a bug?

**Comment by kyleknap** [comment]
This is intentional. Just looks like the S3 API docs have not been updated. I would recommend opening up a thread on [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) or open up a case with support to get this fixed. Let us know if you have an further questions.

**Comment by cwgem** [comment]
Didn't see any action on this so I went ahead and put up a thread for it on the forums:

https://forums.aws.amazon.com/thread.jspa?threadID=261132

And also pinged AWS Support about it.

**Comment by kyleknap** [comment]
Closing GitHub issue as there is no action item with respect to the AWS CLI. The changes need to happen in the upstream documentation.
