### ISSUE TITLE
Feature - Specify the AWS_SESSION_DURATION for MFA session tokens

### ISSUE THREAD

**Issue by ajohnstone** [aws/aws-cli#2748]
Similar to #2177, however would like to specify the session duration to a configurable period, so can specify a longer period.

Expose environment variable of AWS_SESSION_DURATION and session-duration in the ~/.aws/config.

---
aws-cli/1.11.127 Python/2.7.12 Linux/4.4.0-81-generic botocore/1.5.90

**Comment by jamesls** [comment]
The session duration would be useful if we supported the `sts get-session-token` as a credential provider, but the assume-role provider we currently support only lets you shorten the duration.  Did you want to use this for the assume role provider with MFA?  If so, we'd have to get the service to support specifying longer durations first.

**Comment by ajohnstone** [comment]
Hi,

Yes using with mfa e.g. 
```
[profile photobox]
role_arn = arn:aws:iam::xxxx:role/<REPLACE-ME-ROLE>
source_profile = photobox-jump
mfa_serial = arn:aws:iam::xxx:mfa/<REPLACE-ME-EMAIL>
```

Thanks

Andy

**Comment by drAlberT** [comment]
this is still so actual .. please consider :) tnx

**Comment by justnance** [comment]
@ajohnstone and @drAlberT - Thanks for your feedback.  Currently the service does not use the assume role provider with MFA.  This feature would be a request for the IAM Service team.  It is recommended to reach out on the [AWS IAM forums](https://forums.aws.amazon.com/forum.jspa?forumID=76) or contact [AWS Support](https://console.aws.amazon.com/support/home#/).  If the service team approves and adds this feature it will be exposed from the API to the CLI.
