### ISSUE TITLE
Documentation of code layout

### ISSUE THREAD

**Issue by cwgem** [aws/aws-cli#2751]
When looking over the code I thought it would be nice to have a document that describes the overall layout. Currently I have an in-progress preview available in my local fork:

https://github.com/cwgem/aws-cli/blob/65f04a1cc581163051ad8cf05a58d688ade1cd0f/ARCHITECTURE.rst

As the next step is documentation of the `awscli` subdirectory I'd like to get your thoughts on this before I devote more time to it. My thoughts on going with a local document instead of a Wiki entry is that I can see someone wanting to inspect the code in a non-network environment (a plane that does not offer Wifi for example).  Another potential benefit is helping to ease the hurdle of contribution. Thanks ahead of time for your thoughts!

**Comment by kyleknap** [comment]
As it is now, I am not too sure how much value there is in documenting the top level files such as the `requirements.txt`, `CHANGELOG.rst`, and `tests` directory etc. Many of these files are common for an open source project or a Python library in general.

Documenting the `awscli` subdirectory would be more interesting as it will help users that are new to the codebase and want to understand it better. However, I would like to avoid it being overly specific in the case where the code base starts to easily drift away from this document when we make updates.  So I am curious how do you plan to document the `awscli` subdirectory?

**Comment by cwgem** [comment]
@kyleknap 
With regards to the toplevel files, maybe it would be best to keep around the unusual parts such as scripts, `MANIFEST.in` (potentially? Projects having that seems a hit or miss), `.coveragerc` (I don't see too many projects doing code coverage analysis), and `.changes` (almost curious if those are used to generate the `CHANGELOG.rst` file through an automated process).

The basic idea on the documentation of the `awscli` directory would be a high level overview. Realistically I'd like to have a basic explanation of top level files in that directory (save maybe `__init__.py` and `__main__.py`) as anything more detailed might as well be auto generated API docs at that point. The other subdirectories in `awscli` would simply explain the purpose of files in that directory without drilling down into individual files. 

In addition one thing I noticed is that the documentation of individual python files seems a bit hit or miss. `clidocs.py` has it in some places and not in others. Is there a documentation policy at all regarding docstrings?

**Comment by kdaily** [comment]
Bumping this, I think there are still areas for improvement here. We could update our contributing guide with more of this information as well, especially some things like:

> Is there a documentation policy at all regarding docstrings?

Great for a contributing guide, possibly linting for new code.

> The other subdirectories in awscli would simply explain the purpose of files in that directory without drilling down into individual files.

This would be useful for the customization directory especially.
