### ISSUE TITLE
Add container overrides to put-targets for ECS tasks

### ISSUE THREAD

**Issue by gregeinfrank** [aws/aws-cli#2760]
Hi, 

According to http://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html, you can now pass in `EcsParameters` in `put-targets` and pass in a `TaskDefinitionArn` and `TaskCount`, but there is no option for container overrides, which seems to be supported in the AWS Console (see screenshot below):

![image](https://user-images.githubusercontent.com/3170441/29253678-d278f176-8038-11e7-8324-4cb6edea9f65.png)

Is there any plan to support this?
Thank you!

**Comment by joguSD** [comment]
The CLI supports whatever the public API for the service is, so if it's not supported now we would need to wait for the CloudWatch Events service team to add this functionality to their API. You can try contacting [AWS Support](https://console.aws.amazon.com/support/home#/) to see if the service team has any insight on this feature.

**Comment by highbass** [comment]
Has there been any updates made on this or any plans to release functionality to support this?

**Comment by sdesalas** [comment]
Hey guys, 

Pretty poorly documented but this is working by the way:

Its just that you have to use the `Input` parameter and pass in "containerOverrides", ie:

```
ecs events put-target --rule my-daily-batch --targets "[{ \"Id\": \"$TARGET_ID\", \"Arn\": \"$CLUSTER_ARN\", \"RoleArn\": \"$ROLE_ARN\", \"EcsParameters\": { \"TaskDefinitionArn\": \"$TASK_DEFINITION_ARN\", \"TaskCount\": 1 }, \"Input\": "{ \\\"containerOverrides\\\": [{ \\\"name\\\": \\\"$CONTAINER_NAME\\\", \\\"command\\\": [\\\"echo hello override\\\"] }] }" }]"
```

**Comment by alexanderdavidpan** [comment]
@sdesalas, the command in the array has to be comma separated strings, right? Not just a single string? Can you provide an example of how to do so?

**Comment by renperez** [comment]
@sdesalas i'm getting invalid json when running this. 

aws events put-targets \
   --rule my-daily-batch \
   --targets "[{ \
      \"Id\": \"$TARGET_ID\", \
      \"Arn\": \"$CLUSTER_ARN\", \
      \"RoleArn\": \"$ROLE_ARN\", \
      \"EcsParameters\": { \"TaskDefinitionArn\": \"$TASK_DEFINITION_ARN\", \"TaskCount\": 1 }, \
      \"Input\": \"{ \\\"containerOverrides\\\": [{ \\\"name\\\": \\\"$CONTAINER_NAME\\\", \\\"command\\\": [\\\"echo\\\", \\\"hello\\\", \\\"override\\\"] }] }\" \
  }]"

**Comment by sdesalas** [comment]
@renperez please double check your escape characters inside `"Input":`, (ie `containerOverrides` etc. The quotation marks should be using TRIPLE backslashes (`\\\`) as per my comment above.

**Comment by nwsparks** [comment]
It can be simplified a bit further than the example above by wrapping the json in a single quote and some escaping inside the input block.

```
aws events put-targets \
--rule "dev-referrals-timeliness-4am-gmt" \
--targets '[
  {
      "Id": "dev-referrals-timeliness",
      "Arn": "arn:aws:ecs:us-east-1:667646328794:cluster/qio-dev-ecs",
      "RoleArn": "arn:aws:iam::667646328794:role/ECS_Run_Task_Role",
      "Input": "{ \"containerOverrides\": [{ \"name\": \"dev-data-services\", \"command\": [\"echo\", \"hello\", \"override2\"] }] }",
      "EcsParameters": {
          "TaskDefinitionArn": "arn:aws:ecs:us-east-1:667646328794:task-definition/dev-data-services:115",
          "TaskCount": 1
      }
  }
]'
```

**Comment by sterichards** [comment]
I wish CloudFormation would add container overrides...

This becomes a whole lot simpler and less of a hack job when/if they do

**Comment by whereisaaron** [comment]
Woah, this is badly documented for CloudFormation `AWS::Events::Rule` too. Nowhere does it mention you can use `Inputs` in this way. I read the documentation multiple times as I was confused that the console could do overrides but it seemed like CloudFormation could not (nor the CLI). Now I realize it all hinged around `Inputs`. In the `AWS::Events::Rule` there is not a single example of using `Inputs` - for any purpose.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html

Neither does the EventBridge dicumentation bring it up or have even a single example. It covers inputs only in the context of something else generating it. And in the context of transforming an input something else generated.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

@sdesalas [saves the day](https://github.com/aws/aws-cli/issues/2760#issuecomment-364837638) 👍

**Comment by alexisdray** [comment]
My issue for this is that you can not both specify inputs and leave the revision empty. 

We are using an empty revision specification, which ensures that the tasks TaskDefinitionArn is updated to the latest revision. However it then ignores input overrides and uses whatever is specified in the original task definition. Does anyone know a workaround to this?

**Comment by spezam** [comment]
Since I found this discussion useful to solve the integration EventBridge -> Fargate, I can tell that it's also possible to use the `InputTransformer:` in order to pass for example information about the event to the container via `containerOverrides`.

An example, using Cloudformation (which can be easily translated into cli):
```yaml
  SomeEventListener:
    Type: AWS::Events::Rule
    Properties:
      ...
      Targets:
        - Id: some-target
           ...
          InputTransformer:
            InputPathsMap:
              source: $.source
            InputTemplate: |
            {
                "containerOverrides": [
                  {
                    "name": "some-container",
                    "environment": [
                      {
                        "name": "EVENT_SOURCE",
                        "value": <source>
                      },
                    ]
                  }
                ]
              }
```

According to the documentation about transforming target input:

https://docs.aws.amazon.com/eventbridge/latest/userguide/transform-input.html

it's possible to use some reserved variables:
aws.events.rule-arn — The Amazon Resource Name (ARN) of the EventBridge rule.
aws.events.rule-name — The Name of the EventBridge rule.
aws.events.event — A copy of the original event.

I was interested in particular about `aws.events.event`, to be able to pass the whole event as env variable. But it seems there's something missing there, as the container is not starting (possibly because the override JSON object is malformed.

Hope this extra information will come useful to someone.

**Comment by rams3sh** [comment]
While trial and testing with Eventbridge and ECS Fargate Task , I found some more possible reasons on failure.  Below my short experimentation story for others to take up from here in case they are trying anything. 

The possible way to inject values during runtime are through two ways as already mentioned above :- 

i. Using `InputPathsMap` where one can use a JSON path to map a dynamic value from the event JSON to a variable and then use that variable in `InputTemplate` string to interpolate the value which can be injected into the runtask configurtion triggered by event bridge.

ii. Use the [reserved variables](https://docs.aws.amazon.com/eventbridge/latest/userguide/transform-input.html) directly in the `InputTemplate` 


**It is to be noted that the interpolated variable needs to be non-object or non-array to be interpolated as part of  `InputTemplate` string.**  

I understood this only after one full  day of trial and error. I could'nt find any explicit documentation which tells about this constraint of interpolation process. 

I had a requirement to pass the complete event json to the fargate task for further processing. So I had only one choice to rely on which is `aws.events.event.json` which is a raw string version of the complete event json as per the documentation and is supposed to be logically interpolated as given in the below snippet. :- 

```
aws events put-targets --rule <some_rule> --targets ' [
        {
            "Id": <Rule Id>,
            "Arn": <Task_Role_Arn>,
            "RoleArn": <Task_Execution_Role_Arn_For_EventBridge>,
            "EcsParameters": {
                "TaskDefinitionArn": <Task_Definition_Arn>,
                "TaskCount": 1,
                "LaunchType": "FARGATE",
                "NetworkConfiguration": {
                    "awsvpcConfiguration": {
                        "Subnets": [
                            <Subnet_Id>
                        ],
                        "SecurityGroups": [
                            <Security_Group_Id>
                        ],
                        "AssignPublicIp": "ENABLED"
                    }
                }
            },
            
            "InputTransformer": {
              "InputTemplate": "{ \"containerOverrides\": [ { \"name\": \"FargateContainer\", \"environment\": [ {\"name\": \"EVENT\", \"value\": <aws.events.event.json> }]}]}"
              }
        }
    ]'
```

However the variable does not work as per the documentation. 

Just to ensure that my structure of target is rite, I experimented with other variables such as `aws.events.rule-arn `, `aws.events.rule-name`  and `aws.events.ingestion-time ` and the first two worked. However `aws.events.ingestion-time ` didnt work and I changed the variable to `aws.events.event.ingestion-time` and it worked. 

There was a typo in that variable (possibly a documentation error) 

@spezam 
There is apparently something fishy with  `aws.events.event.json`  and these overrides are not clearly documented.  I have reached out to support team , will update here if I find any information regarding it.

In the interim, I am using an intermediate Lambda which gets triggered by the EventBridge and  pushes the raw event  to SQS queue and triggers the Fargate task and the Fargate task consumes the event from this SQS queue for processing.

**Comment by rams3sh** [comment]
Received response from AWS Support team. They have reproduced the bug and confirmed that it would require a fix. No ETA has been provided.

Until then , one cannot interpolate `aws.events.event.json` as environment variable for an ECS task.

**Comment by spezam** [comment]
Thanks @rams3sh for the update! Goona be great to get it fixed.
