### ISSUE TITLE
Can't filter route53 resource recordsets

### ISSUE THREAD

**Issue by andrewmyhre** [aws/aws-cli#2766]
In my script I want to check whether a specific route53 recordset exists and act on whether it does or not. I would like to be able to do:
`aws route53 list-resource-record-sets --hosted-zone-id xyz --filter some-record-set-name`

or even

`aws route53 describe-resource-record-set --hosted-zone-id xyz --record-set-name some-record-set-name`

In our organisation our hosted zone has around 2400 record sets so paging is necessary without some kind of filtering.

**Comment by joguSD** [comment]
The upstream service needs to support this. Open a ticket with [AWS Support](https://console.aws.amazon.com/support/home#/) to suggest this feature to them.
