### ISSUE TITLE
aws s3 ls --page-size does not work

### ISSUE THREAD

**Issue by sharms** [aws/aws-cli#2769]
`aws s3 ls --page-size 10` returns more than 10 results.  This can be repeated with any arbitrary integer.

**Comment by joguSD** [comment]
Setting the `--page-size` defines the number of results asked for in each request and does not limit total number of results ultimately displayed. For example if there is 100 files, setting a `page-size` of 50 will make 2 requests and display all 100 files.

**Comment by sharms** [comment]
joguSD is correct, and this resolves the issue.
