### ISSUE TITLE
CLI doesn't support Postgres v9.6.3

### ISSUE THREAD

**Issue by robinjoseph08** [aws/aws-cli#2771]
When running `aws rds create-db-instance help`, it says the valid versions of Postgres v9.6 are:

```
Version 9.6.x:  9.6.1 | 9.6.2
```

even though [it is supported](https://aws.amazon.com/about-aws/whats-new/2017/07/amazon-rds-for-postgresql-supports-new-minor-versions-9-6-3-and-9-5-7-and-9-4-12-and-9-3-17/).

**Comment by joguSD** [comment]
It seems that the documentation is outdated, but the newer version will work if you try them. I'll forward this along to the service team so they can update these docs.

**Comment by ranman** [comment]
I think this is resolved.

**Comment by joguSD** [comment]
I can confirm the relevant documentation has been updated.
