### ISSUE TITLE
describe-snapshots --filters errors

### ISSUE THREAD

**Issue by jdzialo** [aws/aws-cli#278]
I have seen similar issues reported here but have an additional issue running on Ubuntu 12.04.  Purpose of command is to describe the snapshots that have a tag with key:value Volume:vol-xxxxxx.

Original command based on aws ec2 describe-snapshots help:

aws ec2 describe-snapshots --filters "Volume:vol-xxxxxxx"

Gave error:

Structure option value must be json or path to file.

After looking at this site I tried to format my filter as json.

aws ec2 describe-snapshots --filters '{"name":""Volume","values":["vol-xxxxxxx"]}'

Gave error:

{
      "Errors": {},
      "ResponseMetadata": {},
      "Snapshots": [],
      "RequestID": "1a74d9dd-b00a-46ed-8238-4341767d7222"
}A client error (Unknown) occurred:  Unknown

Any help with my syntax would be greatly appreciated.  I am trying to script this in bash

**Comment by sachinvgaikwad** [comment]
hi how do i get only the list of names and timing of snapshots
