### ISSUE TITLE
Documentation of file:// protocol able parameters

### ISSUE THREAD

**Issue by cwgem** [aws/aws-cli#2781]
After looking into Issue #2779 as well as the KMS docs for another issue I found that there are a number of API calls where the core API parameter accepts a string but a `file://` protocol can be accepted as well. Here are some examples:

* `--policy (string) The bucket policy as a JSON document` [put-bucket-policy](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-policy.html)
* `--plaintext (blob) Data to be encrypted` [encrypt](http://docs.aws.amazon.com/cli/latest/reference/kms/encrypt.html)
* `--policy-document (string) The JSON policy document that you want to use as the content for the new policy` [create-policy](http://docs.aws.amazon.com/cli/latest/reference/iam/create-policy.html) 

The core reason for this is that most documentation is derived from botocore:

https://github.com/boto/botocore/blob/develop/botocore/data/kms/2014-11-01/service-2.json#L965 ( For the plaintext parameter to encode )

Since the expectation for botocore is to be used for scripts, API calls which accept string content don't strictly accept file handlers unless such code is provided. With this in mind:

* I'm not sure if there's a reliable way to get api parameters which can accept `file://` save looking up every single parameter and testing it
* Should usage of `file://` protocol be an Examples section only deal? I've noticed that most examples cover `file://` usage
* Assuming the decision is to document parameters which accept it, I think a boilerplate helper function that outputs something like this may work:

> This method is able to accept a filename as input using the `file://` protocol

to reduce typos in individual cases.

Let me know what your thoughts are on this

**Comment by kyleknap** [comment]
I think we can improve the documentation of the file parameter feature in general. The only place where we really document it is in the separate user guide: http://docs.aws.amazon.com/cli/latest/userguide/cli-using-param.html#cli-using-param-file. In general, most parameters accept the use of `file://`. It is just only practical to use for a smaller subset of those parameters like the ones you listed above.

We could programmatically determine what parameters accept file parameters like`file://`. So adding a general "This parameter supports file:// notation..." would not be difficult. I think that would be probably the route we would go down if we try to document it for each command.

As to it being only documented in the examples section, I do not think it should be just limited to the examples section. Along with the lack of a general programmatically generated statement about file parameter support, the reason it is only really used in the examples section is that for some commands, it really only makes sense to use the command with `file://`.

Hope this helps. In the meantime, marking issue as a documentation update.

**Comment by mjpost** [comment]
+1 on improving the documentation here. This also exists for the argument to `--service-model` (when adding a model using `aws configure add-model`). Providing a path without the URI prefix produces the following error:

    No JSON object could be decoded

It took me quite a while to figure out that the problem wasn't an invalid JSON object in the file, but the fact that it was trying to parse the file path itself as a JSON object.

**Comment by justnance** [comment]
@cwgem - Thanks again for reporting this issue and @mjpost, thanks for adding feedback.  This issue has been escalated to our documentation writers for review.
