### ISSUE TITLE
aws cli stopped working on mingw out of the blue

### ISSUE THREAD

**Issue by iongion** [aws/aws-cli#2785]
The output:

```
An error occurred (ValidationError) when calling the AssumeRole operation: 2 validation errors detected: Value '\''?O?P?R?P'\'' at '\''tokenCode'\'' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*; Value '\''?O?P?R?P'\'' at '\''tokenCode'\'' failed to satisfy constraint: Member must have length less than or equal to 6'
```

Using msys:
```
$ uname -a
MINGW64_NT-10.0 ws1-pc 2.8.2(0.313/5/3) 2017-07-14 08:19 x86_64 Msys
```

Using aws cli:
```
aws-cli/1.11.137 Python/2.7.13 Windows/10 botocore/1.6.4
```

Even deleted my credentials cli cache, always shouting that error, what can I do to get it back working ?

**Comment by cwgem** [comment]
Is the token value exactly as you've given or are you masking it out for security? I'm wondering if it's an encoding issue. What's the output of `locale` look like?

**Comment by iongion** [comment]
locale response is:
```
istoica@ws1-pc MINGW64 /W/Workspace
$ locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
```

That is the exact output, no masking

**Comment by cwgem** [comment]
What is the specific command you're running btw? I'm trying to see what the source of the token value is (of course mask out any sensitive data). I first want to rule out weird encoding issues so try putting `LANG=UTF-8 LC_ALL=UTF-8` before your `aws` command run to see if anything changes.

**Comment by iongion** [comment]
Was running:
```
      aws s3 cp \
        --acl public-read \
        $PROJECT_DIR/build/ffmpeg.zip \
        s3://my-bucket/binaries/ffmpeg.zip \
```
I have retried and now it works, but I got something alike before in the msys env, maybe it is time for me to move away from it, use UOW or alike. My previous issue reported was also due to msys weird behavior.
Thank you for all the involvement!

**Comment by moalexmonk** [comment]
FWIW in case anyone else runs into this, a colleague just found that this can happen due to num lock. I typed 123456 both times with different num lock settings (getpass is what boto will be using behind the scenes):

$ winpty py -3 -c 'import getpass; print(getpass.getpass("test: "))'
test:
àOàPàQàKàM

$ winpty py -3 -c 'import getpass; print(getpass.getpass("test: "))'
test:
123456
