### ISSUE TITLE
aws rds describe-db-snapshots --max-items weird behaviour

### ISSUE THREAD

**Issue by cs-mahmoud-khateeb** [aws/aws-cli#2788]
I am trying to get only one snapshot based on this query, so I have used `--max-items 1` which is causing the following behaviour, there are items that match my criteria, but they only start to appear when I increased the value of `max-items` to more than 32, I thought it might be a paging issue, so I have tried to use the highest page-size which changed nothing.

```
15:51 $ aws rds describe-db-snapshots --db-instance-identifier production-db-r3 --max-items 1 --query "DBSnapshots[?SnapshotCreateTime>='2017-08-20'].DBSnapshotIdentifier" --output=json
[]
15:52 $ aws rds describe-db-snapshots --db-instance-identifier production-db-r3 --max-items 30 --query "DBSnapshots[?SnapshotCreateTime>='2017-08-20'].DBSnapshotIdentifier" --output=json
[]
15:53 $ aws rds describe-db-snapshots --db-instance-identifier production-db-r3 --max-items 33 --query "DBSnapshots[?SnapshotCreateTime>='2017-08-20'].DBSnapshotIdentifier" --output=json
[
    "rds:production-db-r3-2017-08-20-03-23"
]
15:57 $ aws rds describe-db-snapshots --db-instance-identifier production-db-r3 --max-items 34 --query "DBSnapshots[?SnapshotCreateTime>='2017-08-20'].DBSnapshotIdentifier" --output=json
[
    "rds:production-db-r3-2017-08-20-03-23",
    "rds:production-db-r3-2017-08-21-03-23"
]
```

**Comment by joguSD** [comment]
If you apply `--max-items 1` you will only get one item in the response which is then applied against the query which (probably) doesn't match the query. The `--max-items` argument affects the input to the query rather than the output.

**Comment by cs-mahmoud-khateeb** [comment]
In the AWS documentation, `--max-items` is:

> The total number of items to return in the command's output.

**Comment by joguSD** [comment]
Yeah the documentation is unclear and I can see how this is confusing.

**Comment by cs-mahmoud-khateeb** [comment]
I am not sure that should be the case, this will make this flag almost useless when used with a query.
