### ISSUE TITLE
System-wide configuration/models directory?

### ISSUE THREAD

**Issue by lorengordon** [aws/aws-cli#2790]
Hello, not sure if this belongs here or in botocore, but is there a system-wide configuration directory?

Specifically, I know that botocore will read from `~/.aws/models`. I would like to have to ability to place models in a single location on a system, rather than putting them in every home directory. Something like say `/etc/aws/models` or `/etc/botocore/models` on Linux, or under `%PROGRAMFILES%` or `%PROGRAMDATA%` on Windows.

**Comment by kyleknap** [comment]
Yep! That is possible. If you set the `AWS_DATA_PATH` to point to the directory you want to place the models, the CLI should start picking up the models. I don't think this is in the CLI reference, but it should be. Marking as a documentation update.

**Comment by joguSD** [comment]
The in-code documentation for the loaders in botocore is pretty good so in the meantime you can see those [here](https://github.com/boto/botocore/blob/cac78632cabddbc7b64f63d99d419fe16917e09b/botocore/loaders.py#L33).

**Comment by lorengordon** [comment]
Oh, shoot, I totally didn't see this reply! Very nice, thanks @kyleknap and @joguSD!

**Comment by lorengordon** [comment]
@joguSD Something not mentioned in the in-code docs is how models are merged (what is the evaluation order, or what overrides what? if merged, how deep is the merging?), or that the data path is also used to resolve endpoints.json.

**Comment by joguSD** [comment]
The current behavior is to evaluate paths in this order:
1) The paths in order as described in `AWS_DATA_PATH`
2) The `~/.aws/models` path
3) The models included in `botocore/data`

Models are not merged, first result found in a path using the above order is used.

**Comment by lorengordon** [comment]
@joguSD @kyleknap Do you know if other AWS SDKs expose an option/env similar to `AWS_DATA_PATH` for evaluating models and endpoints? The aws go sdk, in particular... I searched but didn't turn anything up... :/

**Comment by joguSD** [comment]
The Go SDK definitely cannot dynamically load the models like we do in Python as it's a statically compiled language. If you want to dig further the Go SDK is [here](https://github.com/aws/aws-sdk-go).
