### ISSUE TITLE
The vpc none does not exist. - AWS CloudFormation

### ISSUE THREAD

**Issue by aravindvasu** [aws/aws-cli#2795]
When I try to launch my AWS cloudformation stack in new region. Am getting error "The vpc none does not exist" when creating RDS service. Can anyone help me to fix this issue?

```javascript
    "dbsgdefault": {
      "Type": "AWS::RDS::DBSecurityGroup",
      "Properties": {
        "GroupDescription": "default"
      }
    },
```

**Comment by cwgem** [comment]
You really shouldn't be using `DBSecurityGroup`. Instead, create an [AWS::EC2::SecurityGroup](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html) and attach it to your RDS instance using the [VPCSecurityGroups](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-vpcsecuritygroups) property. 

[DBSecurityGroups are meant for EC2-Classic](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithSecurityGroups.html), which is essentially a way to help AWS users who were on EC2 before VPCs were a thing migrate over to the newer VPC setup. Also please note that this is meant as a place to file issues for `aws-cli`, and you'll be better off asking such questions on [StackOverflow](https://stackoverflow.com/) where there's a lot more users able to assist in answering such questions.

**Comment by jamesls** [comment]
Thanks @cwgem for the help!
