### ISSUE TITLE
[kinesis] [cloud-formation] Unable to override ShardCount from aws-cli during deploy

### ISSUE THREAD

**Issue by srmelody-rally** [aws/aws-cli#2798]
Hi,

I am trying to override the ShardCount parameter for my cloud formation template that creates a Kinesis stream.

````json
{
  "AWSTemplateFormatVersion": "2010-09-09",
 
  "Resources": {
      "OutgoingStream": {
          "Type": "AWS::Kinesis::Stream",
          "Properties": {
            "RetentionPeriodHours": 24,
            "ShardCount": 3
          }
      }
  }
}
````

Neither this:
````
aws cloudformation deploy --stack-name test-kinesis-streams --template kinesis/outgoing-messages-stream.json --parameter-overrides ShardCount=1
````

nor this:

````
aws cloudformation deploy --stack-name test-kinesis-streams --template kinesis/outgoing-messages-stream.json --parameter-overrides ParameterKey=ShardCount ParameterValue=1
````

work for me.  They will create streams with 3 shards.  Is this a feature supported by the aws-cli to override the property in this manner?

**Comment by jamesls** [comment]
You'll need to make sure you have this mapped in your `Parameters` section of your template: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/gettingstarted.templatebasics.html#gettingstarted.templatebasics.parameters

If you'd like help with cloudformation templates I'd suggest asking on [their forums](https://forums.aws.amazon.com/forum.jspa?forumID=92).  Someone there will be able to answer any cfn questions you have.
