### ISSUE TITLE
awscli-cwlogs does not work with FIPS encryption mode

### ISSUE THREAD

**Issue by mgresko** [aws/aws-cli#2799]
Not sure this is the correct project for this but can't find anything specific for awscli-cwlogs.

When running cwlogs on an EL7  STIGS hardened instance I am seeing log lines with errors like:

```
2017-08-30 16:37:43,843 - cwlogs.push.watcher - ERROR - 1124 - Thread-1 - Failed to refresh stream: {'datetime_format': None, 'log_group_name': 'messages', 'log_stream_name': 'ip-x-x-x-x.us-gov-west-1.compute.internal', 'encoding': 'utf_8', 'time_zone': 'UTC', 'queue': 0, 'source_id': None, 'init_pos': 'end_of_file', 'file': '/var/log/messages', 'buffer_duration': 5000}, reason: ValueError('error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips',).
```

I suspect it has to do with how the log files are getting fingerprinted:
```return hashlib.md5(source_id_val).hexdigest()```

Perhaps sha could be used in its place in order to support FIPS

**Comment by jamesls** [comment]
This package is owned by the cloudwatch logs team so the best place to get help with that would be on [their forums](https://forums.aws.amazon.com/forum.jspa?forumID=138).  Sorry I can't be of much help here.

**Comment by mgresko** [comment]
Thought i was in the wrong place... thanks for the direction! :)

**Comment by lorengordon** [comment]
@mgresko I'm interested in this as well... once you post to the forum, would you mind posting the link here to make it easier to find?

**Comment by mgresko** [comment]
@lorengordon I opened an AWS support request hoping that will be a little faster... I will let you know.

**Comment by lorengordon** [comment]
@mgresko, it's not any faster, it seems to me, with these projects that aren't managed through github. we opened a ticket regarding FIPS compliance for the aws cfn bootstrap utility back in march (iirc). still not resolved. 😢

**Comment by mgresko** [comment]
@lorengordon I received the response that you expected.  No timeline.  +1 to the feature request.  :(

**Comment by lorengordon** [comment]
Yeah, I wish they'd just host these somewhere we could submit a patch. This stuff is seriously easy to fix.

**Comment by mgresko** [comment]
@lorengordon FYI i patched the md5 reference in push.py to sha256 and works fine.  Just going to patch in AMI until it is fixed upstream.

**Comment by lorengordon** [comment]
@mgresko good to know, appreciate the update!

**Comment by ferrx** [comment]
@mgresko What is the procedure exactly? Where is push.py located?

**Comment by tdillan** [comment]
@ferrx You might have discovered this already, but push.py is found under the awslogs installation directory (/var/awslogs/).  You can find the exact path by navigating to that directory and running `find -wholename *cwlogs/push.py`.  In that file, you need to replace `hashlib.md5` with `hashlib.sha256`.

**Comment by ferrx** [comment]
@tdillan Yes- I did find it. Turned out there's a different version of CloudWatch Agent Logs now that is FIPS compliant. It works great. https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/UseCloudWatchUnifiedAgent.html
