### ISSUE TITLE
run-instances  does not assign an IamInstanceProfile when specified in cli-input-json file 

### ISSUE THREAD

**Issue by edgreenberg** [aws/aws-cli#2802]
When I run an instance in the cli using the flag --iam-instance-profile Arn=arn:aws:iam::999999999999:instance-profile/ec2_describe_tags  I get the profile and roles properly attached BEFORE the user-data is run, just as I need. 

On the other hand, when I leave that flag off, and add this json block:
```
            "IamInstanceProfile": {
                "Arn": "arn:aws:iam::999999999999:instance-profile/ec2_describe_tags"
            },
```
the profile and role are not attached. 

No error message is returned, and the run-instance proceeds otherwise properly.

**Comment by joguSD** [comment]
Can you provide the debug logs by adding `--debug` to your command?

**Comment by edgreenberg** [comment]
It seems to have worked now. Embarrassed. Closing.
