### ISSUE TITLE
Profile does not return region or output format if it contains a SPACE character

### ISSUE THREAD

**Issue by CliveJL** [aws/aws-cli#2806]
The AWS CLI tool allows you to create a profile name with a space character in it, and writes the values to the credentials and config file as expected. However when getting that config using the quoted profile name, it doesn't return the region or default output format.

Setting the profile credentials and config:

    $ aws configure --profile 'Foo Bar'
    AWS Access Key ID [None]: foo
    AWS Secret Access Key [None]: bar
    Default region name [None]: eu-west-1
    Default output format [None]: json

    $ cat .aws/config
    [profile Foo Bar]
    output = json
    region = eu-west-1

    $ cat .aws/credentials
    [Foo Bar]
    aws_access_key_id = foo
    aws_secret_access_key = bar

Checking the profile credentials and config:

    $ aws configure --profile 'Foo Bar'
    AWS Access Key ID [****************foo]:
    AWS Secret Access Key [****************bar]:
    Default region name [None]:
    Default output format [None]:

CLI commands then prompt for a region when using the profile name. The **credentials** do still work, and are retrieved from the profile, but the **config** ,e.g. the region, has to be specified on the command line still:

    $ aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names group_name --profile 'Foo Bar'
    You must specify a region. You can also configure your region by running "aws configure".

When performing the same steps above with a profile name without a space character (Foo_Bar), everything works as expected.

**Comment by cwgem** [comment]
So after some debugging. Essentially the `configure` function for profile needs to check if the profile name has spaces and if so add single quotes around them. First off actual config loading happens in botocore and uses `shlex.split` on the profile section name:

https://github.com/boto/botocore/blob/develop/botocore/configloader.py#L254

To get the name of the profile. Unfortunately, this splits on whitespace which leads to your issue:

```
>>> import shlex
>>> test = 'profile Foo Bar'
>>> shlex.split(test)
['profile', 'Foo', 'Bar']
```

 Now given the following profile:

```
[profile 'Foo Bar']
output = json
region = eu-west-1
```

If I run this through the python interactive shell (botocore parses config files through `configparser`):

```
>>> config = configparser.RawConfigParser()
>>> config.read('config.ini')
['config.ini']
>>> config.sections()
["profile 'Foo Bar'"]
>>> shlex.split(config.sections()[0])
['profile', 'Foo Bar']
```

The quoting ensure that the profile name even with spaces comes up properly.

**Comment by jamesls** [comment]
Thanks for looking into this.  So I think a fix for this would be when the CLI is writing out a new profile, check if the profile name has spaces and if so, surround the name in quotes.

I suppose we could always quote the profile name, but I'd prefer a smaller change.

**Comment by cwgem** [comment]
@jamesls I'm thinking of doing the quoting route. It's a mostly small fix with the main part to deal with being testing. This week might end up a bit busy, but at the worst case I might be able to pull together a pull request over the weekend if no one gets to it by then.

**Comment by gtseres** [comment]
I have sent out a PR for that. Actually there is a bunch of unit tests for the configuration, that cover the change as well. Please let me know if you want me to run any other kind of test.
