### ISSUE TITLE
Wheel 0.30.0 dropped Python 2.6, 3.2, and 3.3 (SyntaxError: invalid syntax bdist_wheel.py", line 407)

### ISSUE THREAD

**Issue by montaguethomas** [aws/aws-cli#2818]
Looks like wheel just released a new version which drops support for several python versions, including 2.6: https://github.com/pypa/wheel/blob/7ca7b3552e55030b5d78cd90d53f1d99c9139f16/CHANGES.txt#L15.

I get the following error when trying to run the `install -i` script on a host with python 2.6.6:
```
Collecting PyYAML<=3.12,>=3.10 (from awscli==1.11.149)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UmW85f/PyYAML/setup.py", line 83, in <module>
        from wheel.bdist_wheel import bdist_wheel
      File "/opt/srx/bundle-install/awscli-bundle/aws/lib/python2.6/site-packages/wheel/bdist_wheel.py", line 407
        ignore=lambda x, y: {'PKG-INFO', 'requires.txt', 'SOURCES.txt',
                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
```

**Comment by djve** [comment]
I'm not sure this is the correct package. bdist_wheel.py isn't part of this project. However it's broken lots of calls.

**Comment by sethgrid** [comment]
we have broken packages too. Any suggestions on a fix?

**Comment by montaguethomas** [comment]
@sethgrid I ended switching from using the [awscli bundle installer](http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html) to just manually installing to a local user path:

```
mkdir './.awscli'
curl 'https://bootstrap.pypa.io/get-pip.py' -o './.awscli/get-pip.py'
export PYTHONUSERBASE="$(pwd)/.awscli/"
python './.awscli/get-pip.py' --user
'./.awscli/bin/pip' install wheel==0.29.0 --user
'./.awscli/bin/pip' install awscli --user
AWSCLI="$(pwd)/bundle-install/.awscli/bin/aws"
```

**Comment by stonefury** [comment]
pip install wheel==0.29.0

Then retry the install

**Comment by babineaum** [comment]
if you are using virtualenv

`virtualenv --system-site-packages --no-download ENV`

This will make sure to NOT go out to the internet and use the local installation of 0.29.0 of wheel.

**Comment by IpassAnil** [comment]
@stonefury. Thanks! this worked for me.
install wheel==0.29.0
