### ISSUE TITLE
List all the dynamodb tables with their throughput

### ISSUE THREAD

**Issue by asvarshn** [aws/aws-cli#2832]
I am looking to list  all the dynamodb tables with their throughput and also the number of decrement has happened.
Is there any automated solution for dynamodb autoscaling?

**Comment by cwgem** [comment]
DynamoDB has [autoscaling functionality](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html) assuming the information you're requesting is related to your own custom autoscale solution.

**Comment by jamesls** [comment]
Thanks @cwgem.

@asvarshn  If you still have questions I suggest moving this issue over to stackoverflow as mentioned in our [README](https://github.com/aws/aws-cli#getting-help).
