### ISSUE TITLE
s3api put-object --tagging option is not working

### ISSUE THREAD

**Issue by Cicatrice** [aws/aws-cli#2841]
There is a `--tagging` option for `s3api put-object` command (like explained in this documentation http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html), but it seems not working and throw the following errors: 
```
aws s3api put-object [...] --tagging 'TagSet%3D%5B%7BKey%3Dstring%2CValue%3Dstring%7D%5D'
An error occurred (InvalidTag) when calling the PutObject operation: The TagKey you have provided is invalid
```

or:
```
aws s3api put-object [...] --tagging 'TagSet=[{Key=string,Value=string}]'
An error occurred (InvalidArgument) when calling the PutObject operation: The header 'x-amz-tagging' shall be encoded as UTF-8 then URLEncoded URL query parameters without tag name duplicates
```

I'm using an AWS key with AdministratorAccess on target bucket.
```
aws --version
aws-cli/1.11.154 Python/2.7.13 Linux/4.12.11-300.fc26.x86_64 botocore/1.7.12
```

Any idea ? Many thanks !

**Comment by dstufft** [comment]
You want to use ``'testing=Moo'`` as the value of ``--tagging``. It is encoding the key values as a query string.

**Comment by rtvlad** [comment]
That's not true. This worked for me: `aws s3api put-object-tagging --bucket my_bucket --key my.file --tagging 'TagSet=[{Key=mykey,Value=myvalue},{Key=yourkey,Value=yourvalue}]'`

**Comment by ccayg-sainsburys** [comment]
@rtvlad You've quoted `put-object-tagging` rather than `put-object`. The commands seem to have different behaviour

**Comment by ccayg-sainsburys** [comment]
@dstufft Any ideas when you want to give multiple tags? `'testing=Moo,testing2=Baa'` does not seem to work

**Comment by rolecram** [comment]
Ayyyyyyyy AWS!!!!!!!!!. The value format for the parameter **--tagging** is completely different in **put-object** **and put-object-tagging** commands.

IN **put-object-tagging** command, the format is as follows (example):

**aws s3api put-object-tagging --region us-east-1 --bucket test-devops-curso --key code/index.js --tagging 'TagSet = [{Key=action,Value=create}]'**

IN **put-object** command the parameter --tagging follows the URL format (the same example as above):

 **aws s3api put-object --region us-east-1 --bucket test-devops-curso --key code/index.js --body c:\projects\aws\aws.smalltowns\code\camiri\s3-list.mjs --tagging 'action=create'**

In case you need to add more parameters, separate them by an ampersand symbol as follow:

 **aws s3api put-object --region us-east-1 --bucket test-devops-curso --key code/index.js --body c:\projects\aws\aws.smalltowns\code\camiri\s3-list.mjs --tagging 'action=create&name=Myfunction'**

Anyway, I do not know why, but I can not use the JSON format in the put-object-tagging, i.e:

**aws s3api put-object-tagging --region us-east-1 --bucket test-devops-curso --key code/index.js --tagging '{"TagSet": [{ "Key": "action", "Value": "create"}]}'**
