### ISSUE TITLE
Invalid Syntax Error when running any AWS command. 

### ISSUE THREAD

**Issue by gill-0** [aws/aws-cli#2843]
After installing with awscli with pip and  running aws --version, or any other aws command, I receive this error:

/Users/<user>/anaconda/lib/python3.6/site-packages/aws/main.py", line 23
    print '%(name)s: %(endpoint)s' % {
                                 ^
SyntaxError: invalid syntax

The entire function from that error is as follows:

def list_regions(service):
    """
    List regions for the service
    """
    for region in service.regions():
        print '%(name)s: %(endpoint)s' % {
            'name': region.name,
            'endpoint': region.endpoint,
        }

I am using an anaconda environment, with python 2.7. However it appears main.py is running under python 3.6 from the error. I also tried installing and running in my regular environment with 3.6 and had the same error as well.

**Comment by cwgem** [comment]
I don't see this `list_regions` function in the codebase. This seems to be custom code of some sort.

If you're hitting python 3, `print` needs to have parens. Some details can be found in this [SO answer](https://stackoverflow.com/questions/6182964/why-is-parenthesis-in-print-voluntary-in-python-2-7).

**Comment by dstufft** [comment]
This appears to be an issue with something other than this code base. The importable name for this tool is ``awscli`` not ``aws``

**Comment by HUU** [comment]
Leaving this here in case someone comes across this via google like me:

I had the same issue with the same environment (anaconda environment with python 3.6).  This is actually a different package, confusingly named "aws" which is throwing the error: https://github.com/eofs/aws

Make sure you run `pip install awscli`,  NOT `pip install aws`.  You may want to confirm which "aws" package you are calling via `which aws`.

**Comment by eze1981** [comment]
Remove the aws package wiith `pip uninstall aws`. Then install awscli, `pip install awscli`.

**Comment by PronomitaDey** [comment]
eze1981, that worked. Thanks pal :)

**Comment by shankarraj** [comment]
I installed AWSCLI using pip install awscli command but still got this error. It got resolved after upgrading the aws with the command pip install --upgrade awscli

**Comment by billywatson** [comment]
I had to do a `--force-reinstall` after forgetting that I already had `awscli` installed, installing `aws` and then uninstalling `aws`. This removed the `aws` binary, hence the need for the `--force-reinstall`

**Comment by sfdc-ajith** [comment]
In my case, I tried all the options highlighted and it still resulted in the same error until I did the following:

1. Find the `aws` binary installed `which aws` and rm the file.
2. Follow steps from @HUU  and @eze1981

**Comment by irfanalef2060** [comment]
@HUU Thanks dude, you saved my day 👍

**Comment by oedeleon** [comment]
'aws' is the package name for version 2 of the cli. If you install 'awscli' you'll be using version 1 ... not that there's anything wrong with that. 

I have the same error on 'aws' too.

**Comment by sblinz** [comment]
> Leaving this here in case someone comes across this via google like me:
> 
> I had the same issue with the same environment (anaconda environment with python 3.6). This is actually a different package, confusingly named "aws" which is throwing the error: https://github.com/eofs/aws
> 
> Make sure you run `pip install awscli`, NOT `pip install aws`. You may want to confirm which "aws" package you are calling via `which aws`.

Is it just me or is it crazy that a `pip install aws` on Python 3.8.10 installs a package which has print function syntax errors?

**Comment by Abhi-lash19** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/home/vagrant/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/home/vagrant/.local/lib/python2.7/site-packages/botocore/__init__.py", line 96
    name = f"{name[: -len(matched)]}{sep}{matched.lower()}"
                                                          ^
SyntaxError: invalid syntax
 I am still getting the above error I mentioned. I tried all the ways mentioned above. please help if possible

**Comment by Nokodoko** [comment]
> In my case, I tried all the options highlighted and it still resulted in the same error until I did the following:
> 
> 1. Find the `aws` binary installed `which aws` and rm the file.
> 2. Follow steps from @HUU  and @eze1981



> 

TY!! :+1:

**Comment by aurolive-shseo** [comment]
This is an old post, but I think it will be helpful to someone, so I'm leaving this post.

I'm using Anaconda 3, and I'm using python 3.9.13 as the base (ROOT).

The 'pip uninstall aws' and 'pip uninstall awscli' commands that you told me here didn't work properly,
and even after running 'pip upgrade awscli', the awscli version didn't upgrade to 2 and stayed at version 1.3.

After looking into it, I found that awscli v2 is not officially supported by pip,
and I was able to solve it with the command 'pip install awscliv2'.

Instead, if you use this command, you have to change the existing aws command to v2, so you have to use the command below.
$ alias aws='awsv2'
