### ISSUE TITLE
aws-cli trying to add ipv6 to sg 

### ISSUE THREAD

**Issue by golimer** [aws/aws-cli#2846]
`aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --protocol tcp --port 80 --cidr 2c0f:f248::/32`

and error 
An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block 2c0f:f248::/32 is malformed

**Comment by dstufft** [comment]
From ``aws ec2 authorize-securitygroup-ingress`` the way to add this rule would be:

``aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "Ipv6Ranges": [{"CidrIpv6": "2001:db8:1234:1a00::/64"}]}]'``

**Comment by golimer** [comment]
thanks i'll try

**Comment by campanellaf** [comment]
> From `aws ec2 authorize-securitygroup-ingress` the way to add this rule would be:
> 
> `aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "Ipv6Ranges": [{"CidrIpv6": "2001:db8:1234:1a00::/64"}]}]'`

This does not work:
Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

Is there a way to work with ipv6 addresses without using this --ip-permissions parameter?

**Comment by darioxz** [comment]
@campanellaf Try this:

```
aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions "[{\"IpProtocol\": \"tcp\", \"FromPort\": 22, \"ToPort\": 22, \"Ipv6Ranges\": [{\"CidrIpv6\": \"2001:db8:1234:1a00::/64\"}]}]"
```

**Comment by oadam** [comment]
Even simpler :

    aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,Ipv6Ranges=[{CidrIpv6=2001:db8:1234:1a00::/64}]

**Comment by Abhijets** [comment]
aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions IpProtocol=tcp,FromPort=80,ToPort=80,Ipv6Ranges="[{CidrIpv6=::/0}]"

**Comment by Abhijets** [comment]
Inbound rule to allow IPV6 traffic on port 80 and its output:-
$ aws ec2 authorize-security-group-ingress --group-id sg-aee513c4 --ip-permissions IpProtocol=tcp,FromPort=80,ToPort=80,Ipv6Ranges="[{CidrIpv6=::/0}]"
Output: 
```
{
    "Return": true,
    "SecurityGroupRules": [
        {
            "SecurityGroupRuleId": "sgr-03xxxxxxe2a47",
            "GroupId": "sg-080axxxxxxaafd",
            "GroupOwnerId": "302xxxxxx86",
            "IsEgress": false,
            "IpProtocol": "tcp",
            "FromPort": 80,
            "ToPort": 80,
            "CidrIpv6": "::/0"
        }
    ]
}
```
