### ISSUE TITLE
update-function-code silently fails for large payload

### ISSUE THREAD

**Issue by eyaler** [aws/aws-cli#2847]
i am doing:
aws lambda update-function-code --function-name myfunc --zip-file fileb://payload.zip

when payload is small this works.
when payload is large (but smaller than lambda limit) e.g. 49MB it silently fails.
I am still able to manually upload the 49MB file via web interface.

**Comment by eyaler** [comment]
updating awscli to latest version seems to fix it

**Comment by dstufft** [comment]
Are you able to run this command with ``--debug`` and share the debug logs? You would want to redact any information in them that is private.

**Comment by eyaler** [comment]
i could not reproduce so closing. thanks for the --debug tip
