### ISSUE TITLE
aws s3 --quiet should not suppress errors

### ISSUE THREAD

**Issue by tlycken** [aws/aws-cli#2848]
This command runs silently:

```
$ aws s3 cp foo.zip s3://bar-bucket/foo.zip --quiet
$
```

while this one doesn't:

```
$ aws s3 cp foo.zip s3://bar-bucket/foo.zip
upload failed: foo.zip to s3://bar-bucket/foo.zip An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
$
```

The only difference is the `--quiet` option, which I use to suppress undesired progress output (related to #519?) when using this in a script, but it's obviously quite unhelpful that the output about errors is suppressed - it took me quite some troubleshooting to realize this is why things that happened after, relying on this upload, did not work.

**Comment by cwgem** [comment]
Given your use case `--only-show-errors` might work better for you:

`--only-show-errors (boolean) Only errors and warnings are displayed. All other output is suppressed`

**Comment by tlycken** [comment]
@cwgem thanks, that seems to be exactly what i'm looking for!

**Comment by abdennour** [comment]
As per today, `Unknown options: --only-show-errors`

**Comment by dennisvang** [comment]
there's also `--no-progress`:

>File transfer progress is not displayed. This flag is only applied when the quiet and only-show-errors flags are not provided.

see [docs][1]

[1]: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html
