### ISSUE TITLE
aws s3 sync is not reliable

### ISSUE THREAD

**Issue by jamestwebber** [aws/aws-cli#2854]
As was described in #2297: `aws s3 sync` has been consistently failing to upload all of the files asked of it, without saying anything about failures. We're doing this from an EC2 instance (from an attached st1 volume), trying to uploading ~16000 files to s3. In some cases only a few thousand of those are uploaded. As these files were the product of hours of computation on EC2 this is quite aggravating.

aws-cli version:
```
~$ aws --version
aws-cli/1.11.157 Python/2.7.12 Linux/4.4.0-89-generic botocore/1.7.15
```

**Comment by jamestwebber** [comment]
For what it's worth I think we were having the same issues with `aws s3 cp` so this is probably not a sync-specific issue. Copies are failing silently and reporting success.

**Comment by nkadel-skyhook** [comment]
The "aws s3 sync" command is not the best integrated or supported of the awscli components. This is a situation where the lighter weight "s3cmd" tool may work better for you. Barring that, I've had good success with doing a "aws s3 sync --exact-timestamps --dryrun", running "aws s3 sync --exact-timestamps --quiet" in a loop to reduce the progress spew, and re-running "aws s3 sync --exact-timestamps --dryrun" to verify successful delivery afterwards.

It's a lot of extra work, but I've had too many deliveries fail partway through or be interrupted by local network issues to consider "aws s3 sync" reliable without a verification step.

**Comment by kyleknap** [comment]
Interesting, I wonder if it is related to the fact that you are reading from EBS volumes. In the past, I have seen scenarios where the read throughput is exceeded on the EBS volume and you get throttled in reading in the data to upload it to S3. Do you happen to have any debug logs that can help us dive into this? You can get debug logs by appending `--debug` to the command you ran.

**Comment by jamestwebber** [comment]
I started adding --debug to our commands and added a bunch of logging, which of course guarantees that we haven't seen these errors recently.

When the next big bolus of data processing comes down the pipe we should have more diagnostic information available.

**Comment by kyleknap** [comment]
Closing this issue for now. @jamestwebber if you are able to run into this issue again and have debug logs, please open a new issue.

**Comment by glarrain** [comment]
I just got bit by this, while trying to copy all the contents of a bucket to a new one. This a *severe bug*

**Comment by jrthorne** [comment]
I find the aws tools inconsistent. All of them. Sometimes they work, and sometimes they don't. They don't report errors, and the web interface takes a while to update often reporting incorrectly the existence of files. Sorry, this is not a solution, but just a verification to anyone experiencing the same problem that the technical reputation of Amazon does not reflect their performance.

**Comment by benhannel** [comment]
I am also experience this issue @kyleknap. Please fix it as soon as possible.
