### ISSUE TITLE
Unable to create rds instance read replica with a tag that has space

### ISSUE THREAD

**Issue by chnaveens** [aws/aws-cli#2860]
aws rds create-db-instance-read-replica --db-instance-identifier "some-name" --region us-west-2 --source-db-instance-identifier "arn:aws:rds:us-east-1:1234567778:db:some-name" --source-region "us-east-1" --storage-type "gp2" --db-instance-class "db.r3.large" --tags "Key"="Stream","Value"="something with space" --profile <profile>

getting following error ..

An error occurred (InvalidParameterValue) when calling the CreateDBInstanceReadReplica operation: PreSignedUrl could not be authenticated.

Please help me with a work around or a fix.

Note:
aws --version
aws-cli/1.11.158 Python/2.7.10 Darwin/16.7.0 botocore/1.7.16

**Comment by joguSD** [comment]
Can you post debug logs for this by adding `--debug` to the command?

**Comment by chnaveens** [comment]
Give sometime, i will get you the log..!

**Comment by chnaveens** [comment]
I got the complete log, but i can't post the log in public domain..plz let me know what portion of the log you are interested in.. that scrap company data and can post it..! Sorry for the inconvenience

**Comment by chnaveens** [comment]
One difference i found is, when terraform created canonical request.. it created &Tags.Tag.4.Value=SOME+THING... but where as aws cli created &Tags.Tag.8.Value=SOME%20THING .. as per aws documentation % is not allowed. So, as this tag element is part of presignedul.. aws api is throwing 
<ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>PreSignedUrl could not be authenticated.</Message>
  </Error>
  <RequestId>223e319e-a599-11e7-af8d-f5e6264a1d2a</RequestId>
</ErrorResponse>

**Comment by chnaveens** [comment]
```<ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>PreSignedUrl could not be authenticated.</Message>
  </Error>
  <RequestId>223e319e-a599-11e7-af8d-f5e6264a1d2a</RequestId>
</ErrorResponse>```

**Comment by joguSD** [comment]
Where in the documentation did you see that `%` is invalid? 
As far as I know `%20` for space is the correct behavior according to the [documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html).
```
The space character is a reserved character and must be encoded as "%20" (and not as "+").
```
Still looking into exactly what might be causing this.

**Comment by chnaveens** [comment]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

Tag restrictions are common for all resources.

**Comment by joguSD** [comment]
I think that's in reference to the actual contents of the tag, not the encoded form when it's being sent to the service via a URI. 

I've looked into the source for terraform and found they use the Go SDK which actually fails in a similar manner to the CLI / Python SDK when passed a tag value with a space. I'm fairly certain this is unrelated to whether or not a space is encoded as `+` or `%20`.

Are the tags that you're applying to the read replica the same as the source instance? If so you might be able to supply `--copy-tags-to-snapshot` to copy them over. Another workaround for now might be to just call `aws rds add-tags-to-resource` after the instance has been created.
