### ISSUE TITLE
ec2 run-instances Tag 'network-interface' is not a valid

### ISSUE THREAD

**Issue by koooge** [aws/aws-cli#2865]
hello aws-team.
I found error when I ran `aws ec2 run-instances --cli-input-json file://test.json`

test.json
```
...
"TagSpecifications": [
    {
        "ResourceType": "network-interface",
        "Tags": [
            {
                "Key": "Name",
                "Value": "awesome-name"
            }
        ]
    }
]
...
```

output
```
An error occurred (InvalidParameterValue) when calling the RunInstances operation: 'network-interface' is not a valid taggable resource type for this operation.
```

see http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html
(--tag-specifications JSON syntax)

related? #1274

**Comment by joguSD** [comment]
This is expected as noted in the [documentation](http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html) that you linked.
You can only supply `instance` or `volume` for `run-instances`.

If you need help with the usage of a service you should see the links here:
https://github.com/aws/aws-cli#getting-help
