### ISSUE TITLE
aws configure set profile.... does not add "aws_" prefix to credentials

### ISSUE THREAD

**Issue by tecromatica** [aws/aws-cli#2878]
I have the following version:
aws-cli/1.11.21 Python/2.7.12 Linux/4.4.0-96-generic botocore/1.7.14
Linux myhost 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

aws configure set profile.testProfile.aws_access_key_id "$access_key_id"

Does not add an entry, however if I remove "aws_", it adds the entry incorrectly as:
access_key_id = [access key id hash]
It's missing the 'aws_" prefix.

**Comment by jamesls** [comment]
The credential values (`aws_access_key_id`, `aws_secret_access_key`, `aws_session_token`) are written to the `~/.aws/credentials` file not the `~/.aws/config` file.  It looks like you might be checking the `~/.aws/config` file for these values.  While both files are supported in the CLI, the CLI will always write out config values to `~/.aws/config` and credential values to `~/.aws/credentials`.

**Comment by tecromatica** [comment]
Oh man, you're right. I goofed... must have needed sleep.

**Comment by kyleknap** [comment]
Closing out issue. Glad that helped.
