### ISSUE TITLE
`aws apigateway put-gateway-response` does not work with --response-parameters option

### ISSUE THREAD

**Issue by robertomoreno** [aws/aws-cli#2879]
This is related to this question in [stackoverflow](https://stackoverflow.com/questions/46567484/put-gateway-response-fails-when-response-parameters-option-is-set).

Trying to modify the response parameters on API Gateway Responses with the following command:
`aws apigateway put-gateway-response --rest-api-id w1s3nc4dxd --response-type UNAUTHORIZED --status-code 401 --response-parameters method.response.header.Access-Control-Allow-Origin='"'"'*'"'"' --response-templates '{ "application/json": "{\"errorcode\":401,\"message\":$context.error.messageString}" }' --region eu-west-1` 

and fails with:

> An error occurred (BadRequestException) when calling the PutGatewayResponse operation: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: method.response.header.Access-Control-Allow-Origin]

I have also tried with JSON format and other kind of params and still fails. If the `--response-parameters` option is removed all works as expected.

**Comment by robertomoreno** [comment]
Seems like it is not an error related to the cli but the entire functionality. I have tried to do this using the node.js sdk:

        const AWS = require('aws-sdk');
        var apigateway = new AWS.APIGateway({region:'eu-west-1'});

        const params = {
            responseType: 'ACCESS_DENIED',
            restApiId: '1lycalqfrl',
            responseParameters: {"method.response.header.Accept-Charset":"'utf-8'" },
            responseTemplates: {"application/json":"{\"errorcode\":403,\"message\":\$context.error.messageString}}"},
            statusCode: '403'
        };
        apigateway.putGatewayResponse(params, function(err, data) {
            if (err) console.log(err, err.stack); // an error occurred
            else     console.log(data);           // successful response
        });

The result is the same: 

> BadRequestException: Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: method.response.header.Accept-Charset]

**Comment by jamesls** [comment]
Hi,  I would suggest asking on the [API Gateway forums](https://forums.aws.amazon.com/forum.jspa?forumID=199), as the service team would be able to give you a definitive answer on how to use the `responseParameters` parameter.  That would be the quickest way to get this question answered.

**Comment by MEGApixel23** [comment]
Try using `--response-parameters '{"gatewayresponse.header.Access-Control-Allow-Origin":"'"'*'"'"}'`, it worked for me

**Comment by anagai** [comment]
That works. Don't see gatewayresponse.header documented in cli documentation or anywhere else.

**Comment by whatadayday** [comment]
+1
Very intrigued to know what this kind of quoting is named though :)
