### ISSUE TITLE
elbv2 describe-load-balancers not displaying "LoadBalancerAddresses" section for network load balancer

### ISSUE THREAD

**Issue by sandidgm** [aws/aws-cli#2881]
I have created network load balancers assigning EIPs to the AZs the load balancers are in. I can view the EIPs (one per AZ) in the console when looking at the load balancer but the describe load balancers does not display these details.

**Comment by jamesls** [comment]
Can you please provide sanitized `--debug` logs?  We would need more information to help troubleshoot.

**Comment by sandidgm** [comment]
I was initially thrown by the debug output listing the EIPs but the final output not having them. After upgrading the awscli from 1.11.80 to 1.11.168 it now works as expected - sorry about that
