### ISSUE TITLE
Error parsing CLI - input - JSON (running inside terraform) . Running terraform via powershell 

### ISSUE THREAD

**Issue by ravneet05** [aws/aws-cli#2891]
Below is my code to run json with aws-cli (inside terraform) but getting a parsing error. I tried file:\filename.json, but it is not working.I am running my terraform via powershell.It works fine on linux but I am running the same code in terraform via powershell then its throwing parsing errors.

resource "null_resource" "Scaling_Policy_write" {
provisioner "local-exec" {
command = "aws application-autoscaling put-scaling-policy --service-namespace dynamodb --resource-id 'table/${var.tablename}' --scalable-dimension 'dynamodb:table:WriteCapacityUnits' --policy-name 'MyScalingPolicy' --policy-type 'TargetTrackingScaling' --target-tracking-scaling-policy-configuration '{"PredefinedMetricSpecification":{"PredefinedMetricType":"DynamoDBWriteCapacityUtilization"},"ScaleOutCooldown":60,"ScaleInCooldown":60,"TargetValue":50}'"
}
}

error:
Error parsing parameter '--target-tracking-scaling-policy-configuration': Expected: '=', received: ''' for input:
'{"PredefinedMetricSpecification":{"PredefinedMetricType":"DynamoDBWriteCapacityUtilization"},"ScaleOutCooldown":60,"Sca
leInCooldown":60,"TargetValue":50}'

**Comment by jamesls** [comment]
It it works fine on linux but not on windows that suggests that powershell might be stripping off quotes before the command line args gets passed to the CLI.  Can you add a `--debug` arg to the end of that command and show the first couple of lines?  You'll see a line that says "Arguments entered to CLI" which will show the exact values we're seeing.  That will help narrow down the issue.

**Comment by kyleknap** [comment]
Closing issue for now. If you are able to get debug logs, please open up another issue.

**Comment by lu-liu-rft** [comment]
> Below is my code to run json with aws-cli (inside terraform) but getting a parsing error. I tried file:\filename.json, but it is not working.I am running my terraform via powershell.It works fine on linux but I am running the same code in terraform via powershell then its throwing parsing errors.
> 
> resource "null_resource" "Scaling_Policy_write" {
> provisioner "local-exec" {
> command = "aws application-autoscaling put-scaling-policy --service-namespace dynamodb --resource-id 'table/${var.tablename}' --scalable-dimension 'dynamodb:table:WriteCapacityUnits' --policy-name 'MyScalingPolicy' --policy-type 'TargetTrackingScaling' --target-tracking-scaling-policy-configuration '{"PredefinedMetricSpecification":{"PredefinedMetricType":"DynamoDBWriteCapacityUtilization"},"ScaleOutCooldown":60,"ScaleInCooldown":60,"TargetValue":50}'"
> }
> }
> 
> error:
> Error parsing parameter '--target-tracking-scaling-policy-configuration': Expected: '=', received: ''' for input:
> '{"PredefinedMetricSpecification":{"PredefinedMetricType":"DynamoDBWriteCapacityUtilization"},"ScaleOutCooldown":60,"Sca
> leInCooldown":60,"TargetValue":50}'

Hi I encountered the same error, just wondering if you have resolved it?
