### ISSUE TITLE
update metadata

### ISSUE THREAD

**Issue by eepstein** [aws/aws-cli#2895]
I want to just update SOME of the metadata on an existing object in S3.

I do not want to replace the entire object.

Nor do I want to replace all the other metadata.

The S3 console lets me do this.

Seems the CLI still doesn't offer this feature.

Can it be added?

**Comment by JordonPhillips** [comment]
Unfortunately this is a limitation of the S3 public api. You might consider using [tags](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object-tagging.html) instead, which are very similar but don't have that limitation.

**Comment by andyexeter** [comment]
Is this still a limitation of the public API? I have a collection of images with the wrong Content-Type which I'd like to update in bulk.

**Comment by mordka** [comment]
@JordonPhillips is this on the roadmap? Should we raise a feature request? Why would a Web Console be superior to programmatic API? https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-object-metadata.html#add-object-metadata-user-defined
