### ISSUE TITLE
Add support for high resolution metrics in CloudWatch

### ISSUE THREAD

**Issue by michalgasek** [aws/aws-cli#2898]
Cloudwatch API supports high-resolution metrics, AWS CLI does not.

https://aws.amazon.com/blogs/aws/new-high-resolution-custom-metrics-and-alarms-for-amazon-cloudwatch/

**Comment by JordonPhillips** [comment]
It does via `--metric-data`, but we haven't pulled it out to the top like we do with most of the other bits in there.

**Comment by michalgasek** [comment]
Thanks @JordonPhillips !
