### ISSUE TITLE
AWS console client functionality as static library

### ISSUE THREAD

**Issue by andre2007** [aws/aws-cli#2908]
For the D Programming Language I wrote a AWS SDK which does not directly calling the AWS rest apis but calls the AWS console client with a serialized JSON and deseralizes the AWS console client JSON output.

Thats working quite fine and creating the SDK for all AWS services was a matter of few hours. I wonder whether you could provide the same functionality like the aws console client also as static / dynamic library. 
A lot of programming languages would benefit of just calling methods of the AWS static library instead of reinventing the wheel.

**Comment by JordonPhillips** [comment]
I'm -1 on reverse engineering the console requests to make an SDK. If you have a particular feature you would like, we are of course open to feature requests.

**Comment by andre2007** [comment]
From your reply I think there is a misunderstanding what I am doing. There is no reverse engineering of the console requests at all. I try to rephrase it:

I want to provide an AWS SDK for the D Programming Language. Instead of inventing the wheel, the AWS SDK for D is rather thin. It only has the structures generated from the AWS JS SDK and for each service a class with methods for each operation. The methods forwarding the actual call to the AWS console client and parsing the output of the console client. 
I am not wrong, this is the purpose of the AWS console JSON functionality. That is working fine but the AWS console client needs to be installed on the operation system.

My enhancement request is about providing a C library which can also be called like the console client:
"ec2 run-instances --cli-input-json "{...}" 

By providing such a library it is easy for most development languages just to provide simple wrapper about this library.

**Comment by JordonPhillips** [comment]
@andre2007 I'm not clear what you mean by "console client".  To be clear, my definition of "console" is the AWS Console, the web interface that you access via `https://console.aws.amazon.com`. I don't support anything that tries to reverse-engineer any call that console javascript is making because that is undocumented and more or less guaranteed to be broken eventually.

We do provide a [c++ sdk](https://aws.amazon.com/sdk-for-cpp/) that you could wrap if that's what you're looking for.

**Comment by pchaganti** [comment]
@andre2007 Are you maybe referring to the aws-cli as the 'console client' ?

**Comment by andre2007** [comment]
Now it is clear what caused the confusion. I was not talking about the web interface but about the AWS Command Line interface (http://docs.aws.amazon.com/en_en/cli/latest/userguide/cli-chap-welcome.html)

What I meant with Javascript: I use the definitions from here (https://github.com/aws/aws-sdk-js/tree/master/apis) to generate the classes and structures for the AWS SDK for D Programming Language. The AWS SDK for DLang executes the application "aws" installed on the local pc to access AWS.

My enhancement request is: Please provide a C static library which has 1 function. This function gets a string and returns a string. The input string is the same like you would call the command line interface:

"ec2 run-instances --cli-input-json "{...}"

The return of the function is JSON like the command line interface would return (format set to JSON).

The major benefit of this:
- A lot of programming languages are able to work with C libraries directly
- The AWS SDKs for the various languages will become rather small, just wrapper which will forward the calls to the C library provided by AWS
- Generating the AWS SDKs for the various languages is easy, just parse the JS Api definitions and create the artefacts accordingly
