### ISSUE TITLE
Waiter ClusterRunning failed: Waiter encountered a terminal failure state

### ISSUE THREAD

**Issue by ranjankumar03** [aws/aws-cli#2918]
Getting this error on ec2 instance cluster start up out of sudden. Any workaround?

Now waiting for the cluster to startup

****************************************

/anaconda/lib/python2.7/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Waiter ClusterRunning failed: Waiter encountered a terminal failure state

**Comment by JordonPhillips** [comment]
That generally means that the cluster failed to start, though the specific reasons may vary.

**Comment by JordonPhillips** [comment]
Closing out here. If you're still having issues, feel free to open a new issue!
