### ISSUE TITLE
BUG: aws s3 cp fails silently when uploading CSS files when @supports and }} is present

### ISSUE THREAD

**Issue by timothyasp** [aws/aws-cli#2920]
### s3 version
```
▶ aws --version
aws-cli/1.11.177 Python/2.7.10 Darwin/16.7.0 botocore/1.7.35
```

### Steps to reproduce

```
@supports (-webkit-appearance:none) {.foo {color: black}}.baz{color:white;}
```

* Save the valid CSS pasted above to both`test.txt` and `test.css` files
* Run `aws s3 cp path/to/test.css s3://example.bucket/test.css`
* Run `aws s3 cp path/to/test.txt s3://example.bucket/test.txt`

Notice the file contents at s3://example.bucket/test.css are as follows:

```
@supports (-webkit-appearance:none) {.foo {color: black
```

while the content of s3://example.bucket/test.txt is as expected.

If you modify the content of the css file and add a newline between the curly braces `}}`, like so:

```
@supports (-webkit-appearance:none) {.foo {color: black}
}.baz{color:white;}
```

and then reupload the file, Everything works as expected.

No idea why that would be happening, but I found this when trying to upload minified CSS files, which happen to have a lot of `}}` characters in them.  

I should note, that the bug seems to be specific to the `@supports` rule, because when you replace the CSS content with something like:

```
@media screen and (max-width: 200px) {.foo{color:black}}.baz{color:white;}
```

it uploads the file fully.

**Comment by JordonPhillips** [comment]
The CLI doesn't look at the contents of a file, so I'm not sure why this would be happening. I was unable to reproduce it myself. Could you try the following steps to see if you get the same results as me (substituting your own bucket name)?

```bash
$ export MYBUCKET=my-bucket
$ echo '@supports (-webkit-appearance:none) {.foo {color: black}}.baz{color:white;}' > test.css
$ aws s3 cp test.css s3://$MYBUCKET/test.css
upload: ./test.css to s3://my-bucket/test.css
$ aws s3 cp s3://$MYBUCKET/test.css
@supports (-webkit-appearance:none) {.foo {color: black}}.baz{color:white;}%
$ cp test.css test.txt
$ aws s3 cp test.txt s3://$MYBUCKET/test.txt
upload: ./test.txt to s3://my-bucket/test.txt
$ aws s3 cp s3://$MYBUCKET/test.txt -
@supports (-webkit-appearance:none) {.foo {color: black}}.baz{color:white;}%
```

**Comment by timothyasp** [comment]
It's strange - following your steps, I got the same results you got.  But when viewing the file in the browser, it's cut off and incomplete.  

https://files.grizly.com/test.css

**Comment by timothyasp** [comment]
vs https://files.grizly.com/test.txt
