### ISSUE TITLE
Ubuntu Snaps autocomplete won't work

### ISSUE THREAD

**Issue by RockOnHero** [aws/aws-cli#2928]
I couldn't find any better place to post the issue and couldn't find any other Ubuntu snap related issue in this repo. The Problem is, the snap version of the aws-cli can't use autocomplete.
When i follow the instructions on Ubuntu 16.04.3 i get an error:
```bash
$ sudo snap install aws-cli --classic
aws-cli 1.11.160 from 'aws' installed
$ complete -C '/snap/aws-cli/29/bin/aws_completer' aws
# aws <Tab press> results in
$ aws Traceback (most recent call last):
  File "/snap/aws-cli/29/bin/aws_completer", line 18, in <module>
    import awscli.completer
ImportError: No module named 'awscli'
```
The bash completion tries to use the system python instead of the snap build in python.
Therefore it can't found the awscli module. This can be fixed by installing it via pip.
But then i don't need the snap anymore. The snap was covered at [insights.ubuntu](https://insights.ubuntu.com/2017/07/12/top-10-snaps-in-june/) in june with Author Amazon Web Services. Maybe you can help me.

Thank you for the efforts.

**Comment by dstufft** [comment]
Unfortunately we're not going to be able to help with this, we don't ship that Snap and I'm not entirely sure where it's even coming from. My best suggestion is to try to determine who is actually publishing that Snap and following up with them.

Sorry!

**Comment by julian-alarcon** [comment]
Same issue here, as the snap info show the author/publisher as aws, is that right? Or should we ask to another place/person?

```
darkhole@devolo:~$ snap info aws-cli
name:      aws-cli
summary:   Universal Command Line Interface for Amazon Web Services
publisher: aws
description: |
  Universal Command Line Interface for Amazon Web Services
snap-id: CRrJViJiSuDcCkU31G0xpNRVNaj4P960
commands:
  - aws-cli.aws
tracking:    stable
installed:   1.12.1 (41) 14MB classic
refreshed:   2017-11-26 13:43:16 -0500 -05
channels:                
  stable:    1.12.1 (41) 14MB classic
  candidate: 1.12.1 (41) 14MB classic
  beta:      1.12.1 (41) 14MB classic
  edge:      1.12.1 (41) 14MB classic
```

**Comment by nickbreen** [comment]
The web page for this snap (of course) also claims that the developer is AWS: https://snapcraft.io/aws-cli/

**Comment by julian-alarcon** [comment]
Maybe @popey can help us with this. I know that this is not a AWS issue, but somebody should build it and maintain it.

**Comment by popey** [comment]
The aws-cli is indeed owned by the AWS team, not Canonical. The registered email address for the account which uploaded the snap is within the Amazon domain. The post on G+ is just our internal advocacy team promoting interesting snaps that are in the store. Do let me know if there's anything else I can help with.

**Comment by benyanke** [comment]
This is still an issue - just bubbling it up again.

**Comment by smarnach** [comment]
For what it's worth, you can make bash completion for the snap work by using this in your `.bashrc`:

    complete -C 'SNAP=/snap/aws-cli/current /snap/aws-cli/current/usr/bin/python3 /snap/aws-cli/current/bin/aws_completer' aws

The completion is rather slow for me, but I believe this is becasue the Python script is slow to load, and not due to the snap packaging.

**Comment by shawnoster** [comment]
This issue was never solved, it only confirmed that AWS owns the snap, which is clear from the documentation. Given that the instructions have made their way into the official docs I vote to re-open the issue.

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

![image](https://github.com/user-attachments/assets/e03797df-1278-40c6-a116-0f61574254d4)

**Comment by miporto** [comment]
I managed to make it work with a slightly modified version of the one offered by @smarnach:
```
complete -C '/snap/aws-cli/current/bin/aws_completer' aws
```

**Comment by zepplen** [comment]
Can we please get clarification from AWS about if this Snap is owned by AWS?

It's strongly implied by the documentation that this is a first party distribution of the software.
Docs: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

If this is really not an AWS Snap, AWS needs to be getting the snap removed, or at least not claiming to be published by AWS (verified)

**Comment by popey** [comment]
The last time (June 2019) this was [asked](https://forum.snapcraft.io/t/is-aws-cli-legit/11654/4?u=popey) on the [snapcraft forum](https://forum.snapcraft.io/?u=popey], the answer was yes. 

> The AWS CLI packaging is currently supported by the AWS operating system partners team at AWS. While it is not maintained at this time by the AWS SDK team, it is supported and you can file a support case with AWS support or customer service if you require assistance.
> You can also reach out to me directly on #snappy on freenode (davdunc)

I note on #6010 @marrek-az (who appears (from their GH profile)) to work at aws, may know more.

**Comment by marrek-az** [comment]
We encountered difficulty in getting the autocomplete to work, and the work was deprioritized so we could complete the publication. At present, it remains unsolved. I hope to be able to resolve this eventually.

**Comment by gregorydulin** [comment]
I got completion working system-wide with this symlink:
`sudo ln -s /snap/aws-cli/current/bin/aws_completer /usr/local/bin/aws_completer`

I suppose it could _also_ work if you added `/snap/aws-cli/current/bin` to $PATH.
