### ISSUE TITLE
cloudformation validate-template cryptic error message

### ISSUE THREAD

**Issue by ChastinaLi** [aws/aws-cli#2936]
While running `aws cloudformation validate-template --template-body file://cft.json`,  I got: 
```
{
    "Description": "Multiple Environments",
    "Parameters": []
}
```

"Multiple Environments" is the `Description` field value of my CFT.
What does that mean? The error messages are very cryptic.
Does that mean the CFT is good???

**Comment by dstufft** [comment]
I'm not familiar enough with cloud formation to help out. I would recommend engaging with [community resources](https://github.com/aws/aws-cli#getting-help) or support to get help with service issues.
