### ISSUE TITLE
Add command line flag for passing in template configuration file for create-stack

### ISSUE THREAD

**Issue by vigbk** [aws/aws-cli#2937]
I use code pipeline to run the stack and that uses the template configuration file with the parameters specified. It would be great if the create stack cli command could utilize the same file as well. As of now, I need to create a separate JSON file with a different format specifying the values.

**Comment by dstufft** [comment]
Could you be more specific about which ``create-stack`` command you're talking about?

**Comment by vigbk** [comment]
Sorry about that. The cloud formation one http://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html.

**Comment by dstufft** [comment]
I believe that CodePipeline supports the same template file that this command does (CodePipeline supports two different types of templates, but if you look at the documentation you linked to it says that it supports a "Stack Template File" in addition to the "Template Configuration File". My recommendation if you want to use the same file for both, is to utilize the stack template file for both.

I'm going to close this for now, but if using that file for both doesn't work for you, feel free to reopen and we can discuss it further.

**Comment by vigbk** [comment]
The idea was to put the parameters in a separate file. Right now to make it work with the stack template file in both use cases(CodePipeline and CLI), I will need to create two files for the different formats that each supports. It would great if they supported the same format for passing parameters from a file.
