### ISSUE TITLE
AWS CLI has an unclosed socket upon exit

### ISSUE THREAD

**Issue by konklone** [aws/aws-cli#2942]
When running a command (it happened to be `aws lambda create-function`) using a version of Python 3.6 built in debug mode, I got this warning after it was done:

```
/path/to/lib/python3.6/site-packages/awscli/clidriver.py:508: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('XX.XX.XX.XX', 53512), raddr=('XX.XX.XX.XX', 443)>
```

That's the end of this `__call__` function (which I verified are in the same state as the one on my machine):

https://github.com/aws/aws-cli/blob/c032775b00248cd62b2366e2bea649c4943fed93/awscli/clidriver.py#L456-L508

May not be a big deal, as I expect Python cleans it up upon exit, but wanted to file it in case it's worthy of cleanup, especially for novel deployments of aws-cli which may not get cleaned up in this way.

**Comment by joguSD** [comment]
Would it be possible to get the full debug logs from this? You can turn them on by providing `--debug`. In the meantime I'll try reproducing this on our end.

**Comment by joguSD** [comment]
I was able to confirm this. This happens for both the CLI and a simple botocore script that makes a client call.

**Comment by rjuengling-hf** [comment]
> This is still true. Is there a plan the address this? It's quite annoying to get the warning messages for each CLI command

Agree, this adds annoying noise to logs. Please prioritize.
