### ISSUE TITLE
ec2 run-instances command prepends image-id with a 0 causing command to fail

### ISSUE THREAD

**Issue by waldnzwrld** [aws/aws-cli#2945]
Example

`aws ec2 run-instances --image-id ami-c636c6b --count 1 --instance-type r3.large --key-name obfuscated  --block-device-mappings '[{ "DeviceName": "/dev/sdb","Ebs": {"VolumeSize": 10,"DeleteOnTermination": true} }]' --query 'Instances[0].InstanceId' `

and the error it causes.

`An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-0c636c6b]' does not exist`

You can see that it is adding a 0 to ami-c636c6b (ami-0636c6b)

awscli version `aws-cli/1.11.180 Python/3.6.3 Darwin/17.0.0 botocore/1.7.38`
(although checking against versions 1.11.160 + returns the same)
region is set to `us-west-2` 

This is causing problems with automations.

**Comment by joguSD** [comment]
The added 0 is coming back from EC2, possibly because a character is missing from the id. I'm assuming you want `ami-c636c6be` instead of `ami-c636c6b`?

**Comment by waldnzwrld** [comment]
Thank you so much. 

I overlooked it in my troubleshooting. 🤦‍♂️ 

CHeers
