### ISSUE TITLE
Incorrect completions when using 'menu-complete' in Bash

### ISSUE THREAD

**Issue by d13r** [aws/aws-cli#2947]
Hi there,

I use [`menu-complete`](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Completion.html) rather than the default `complete` in Bash. It can be enabled, e.g. by adding these lines in `~/.inputrc`:

```bash
# Tab & shift-tab to run through all options instead of showing a list
TAB: menu-complete
"\e[Z": "\e-1\C-i"
```

The `aws_completer` command currently (`aws-cli/1.11.185 Python/2.7.12 Linux/4.4.0-98-generic botocore/1.7.43`) has two issues that prevent this working correctly.

**Issue 1**

The first issue is if you enter a valid command (e.g. `s3`) and press tab, it overwrites the command that was entered with its own subcommands. For example (assume `|` represents the cursor):

```bash
$ aws s3|
# Press Tab
$ aws cp  |
# Press Tab again
$ aws ls  |
# etc.
```

Whereas if the command name is incomplete when you press tab it works correctly:

```bash
$ aws s|
# Press Tab
$ aws s3  |
# Press Tab again
$ aws s3api  |
# etc.
```

This is because if the last word is a valid command, `aws_completer` returns the subcommands, whereas Bash expects you to return the matching commands *unless* there's a space at the end.

Here's what it currently looks like if you run the `aws_completer` command directly:

```bash
# Incomplete command (correct)
$ COMP_LINE='aws s' aws_completer
sdb
servicecatalog
ses
shield
sms
snowball
sns
sqs
ssm
stepfunctions
storagegateway
sts
support
swf
s3api
s3

# Valid command with no space at the end (wrong)
$ COMP_LINE='aws s3' aws_completer
website
mb
sync
mv
ls
rb
rm
cp
presign
```

Whereas it should output this to work consistently with other tab completions (Bash, Git, etc.):

```bash
# Valid command with no space at the end
$ COMP_LINE='aws s3' aws_completer
s3api
s3

# Command with a space at the end
$ COMP_LINE='aws s3 ' aws_completer
website
mb
sync
mv
ls
rb
rm
cp
presign
```

This would result in the following:

```bash
$ aws s3|
# Press Tab
$ aws s3 |
# Press Tab again
$ aws s3api |
# etc.
```

And:

```bash
$ aws s3 |
# Press Tab
$ aws s3 cp |
# Press Tab again
$ aws s3 ls |
# etc.
```

Which would be consistent with how other commands are completed.

**Issue 2**

The second issue is more of an annoyance than a problem, but it's also easier to fix: `aws_completer` outputs an extra space at the end of each line (except the last), which causes Bash to output two spaces instead of one. For example (again `|` represents the cursor):

```bash
$ aws b|
# Press Tab
$ aws batch  |
#          ^^ Two spaces
# Press Tab again
$ aws budgets |
#            ^ One space because this is the last line
```

This can be seen in the command output by adding an end of line marker:

```bash
$ COMP_LINE='aws b' aws_completer | sed s/$/$/
batch $
budgets$
```

I believe the cause is [this line](https://github.com/aws/aws-cli/blob/e28e2fa0905dd37530404db4f0e67469fe39aaaa/awscli/completer.py#L134):

```python
print(' \n'.join(choices))
```

Which should be:

```python
print('\n'.join(choices))
```

I can make a PR for this if you like.

Thanks!

**Comment by joguSD** [comment]
Confirmed.

Feel free to open up a PR for this.

**Comment by tim-finnigan** [comment]
Hi @d13r thanks for your patience - I wanted to check in after bringing this up with the team. Is this also an issue in v2 of the AWS CLI? If so then we can continue tracking the issue, but if this is limited to v1 then addressing it is unlikely to get prioritized.
