### ISSUE TITLE
Alternative to .aws credentials file

### ISSUE THREAD

**Issue by kaustubh93** [aws/aws-cli#2951]
Is there a way to feed the credentials to the "aws " CLI tool itself. I basically want to pass them in a function so that it can be used modularly. 

Currently we have to save them in config or credentials. Is there a way we can feed it directly to the CLI ?

**Comment by lorengordon** [comment]
You can pass them as [environment variables](https://github.com/aws/aws-cli#other-configurable-variables).

E.g.: `AWS_ACCESS_KEY_ID=xxxxxxx AWS_SECRET_ACCESS_KEY=yyyyyyyyy aws <command>`

**Comment by kaustubh93** [comment]
Thanks a lot @lorengordon . It worked,
