### ISSUE TITLE
"fatal error: Unable to parse response" should be verbose about the content by default

### ISSUE THREAD

**Issue by andreineculau** [aws/aws-cli#2952]
I'm not going to reference them one by one, but both this repo and the boto repos have plenty of issues related to some AWS commands failing with "Unable to parse response". The web/AWS forum has plenty more. All spread out over many years, meaning this issue has not been fixed properly. In many cases, the first reply is to run the aws command with `--debug` and post the trace, which gets more granular results about where, internally, the error is triggered BUT not what caused the error in the first place. At times, it is not even reproducible.

aws-cli/boto/etc are all clients of the AWS HTTP API. Some times the error is on the client side, but some times the error is on the server side. But in this case, the error *is* on the server side. Whatever the server responds with, it's something that cannot be parsed by the HTTP client.

The point that I'm making is that aws-cli should be transparent about what it tried to parse and failed. I'm happy putting `--debug` on all my team's CI scripts, in order to always get trace when an error happens, but in these "Unable to parse response" situations, it should also tell me what the HTTP API returned including status code, headers, and content. Knowing that a failure is caused on `429 Too Many Requests` or `504 Gateway Timeout` or `200 OK` is extremely important.

**Comment by joguSD** [comment]
I agree that it would be nice to have more information even in situations where debug is not on. Labeling as an enhancement.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity on this issue in a long time. Boto3 does seem to offer more flexibility with [logging](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/boto3.html#boto3.set_stream_logger). I think this issue a bit too general though and I'm not sure what the best path forward is. Is the request essentially for some level of logging similar to `--debug` but not as verbose? I could see how that might be useful but I think some further discussion is needed to define specifically what to include/exclude in those logs.
