### ISSUE TITLE
elbv2 create-target-group --matcher does not work with comma separated HttpCode

### ISSUE THREAD

**Issue by vsalvino** [aws/aws-cli#2963]
For example (working):
`aws elbv2 create-target-group --matcher HttpCode=200-300`

produces expected results. But when specifying individual HttpCodes using a comma, it appears that this is parsed as a Python list when expecting a string. Tried various forms of single quotes, double quotes, all producing same results.

To reproduce:

`aws elbv2 create-target-group --matcher HttpCode=200,301`

Also tried:
```
aws elbv2 create-target-group --matcher HttpCode="200,301"
aws elbv2 create-target-group --matcher HttpCode='200,301'
aws elbv2 create-target-group --matcher "HttpCode=200,HttpCode=301"
aws elbv2 create-target-group --matcher HttpCode=200 --matcher HttpCode=301  # works but only uses final arg of --matcher (301 in this case)
```

Using version `aws-cli/1.11.177 Python/2.7.9 Linux/3.16.0-4-amd64 botocore/1.7.35` on Debian 9

**Comment by kyleknap** [comment]
Looks like a limitation of our shorthand parser. In general if it sees commas, it is going to parse it as a list. The good news is that you do not need to use the shorthand notation to get this working. You can use a JSON format that passes the literal value into the Python SDK:
```
--matcher '{"HttpCode": "200,301"}'
```
This was working for me. Let us know if that works for you.

**Comment by jamesls** [comment]
Also, the shorthand parser supports quoting values but bash will remove the double quotes in certain cases.  An easy to check this is with the `echo` command:

```
$ echo aws elbv2 create-target-group --matcher HttpCode="200,301"
aws elbv2 create-target-group --matcher HttpCode=200,301
```

Notice how the double quotes are removed.  You can either escape the quotes, or surround the entire value with single quotes:

```
$ echo aws elbv2 create-target-group --matcher 'HttpCode="200,301"'
aws elbv2 create-target-group --matcher HttpCode="200,301"
```

Let me know if you have any issues with that.

**Comment by vsalvino** [comment]
Great feedback and suggestions. Thank you. Would be helpful to document this in the AWS CLI docs, or possibly leave a note linking to this thread.

**Comment by mrazvan91** [comment]
It works with:
**aws elbv2 create-target-group --matcher HttpCode='"200,303"'**
