### ISSUE TITLE
AWS CLI configuration does not respect profile variable

### ISSUE THREAD

**Issue by Dimpl** [aws/aws-cli#2970]
I tried to use the command aws ec2 describe-spot-price-history in the CLI and received the error 'You must specify a region. You can also configure your region by running "aws configure".' When I first installed the CLI, I configured my credentials and region.

Running 'aws configure', I try to re-enter my details (they are listed as blank), but they do not save. I assume this is because I am using a profile. I have the environment variable AWS_DEFAULT_PROFILE set to 'internal', and have attached my configuration files (with .txt extension added and sensitive data redacted).

[config.txt](https://github.com/aws/aws-cli/files/1486174/config.txt)
[credentials.txt](https://github.com/aws/aws-cli/files/1486175/credentials.txt)

**Comment by joguSD** [comment]
Thanks for the report, there's a PR open to fix this issue here: https://github.com/aws/aws-cli/pull/2972

As a workaround for now you'll need to run `aws configure --profile name` where name matches what's in `AWS_DEFAULT_PROFILE`.
