### ISSUE TITLE
ruby-2.0 won't work for recent ubuntu

### ISSUE THREAD

**Issue by dictcp** [aws/aws-cli#2976]
https://github.com/aws/aws-cli/blob/59e30779bc290a2f4f4d124c79144b8b77464700/awscli/customizations/codedeploy/systems.py#L216

we should not hardcode to install a ruby 2.0 while ignoring ruby >2.0, eg ruby2.3

Ref: 
https://github.com/aws/aws-codedeploy-agent/issues/61

**Comment by joguSD** [comment]
@ravirajataws @feverLu

**Comment by tim-finnigan** [comment]
Checking in, here is a related issue: https://github.com/aws/aws-codedeploy-agent/issues/174. After discussing this with a member of the CodeDeploy team I was told that the issue has now been addressed. For more guidance please refer to this comment: https://github.com/aws/aws-codedeploy-agent/issues/174#issuecomment-1116378405
