### ISSUE TITLE
Cannot use assume role after update to version 1.12

### ISSUE THREAD

**Issue by migueljoao** [aws/aws-cli#2978]
Hello,

After updating aws cli to version 1.12 in a Windows 10, my assume role credentials with MFA no longer work, generating the following error on any aws cli command

> [Errno 2] No such file or directory: 'D:\\<user_profile>\\.aws\\cli\\cache\\arn_aws_iam__08888888888_role/Administrator--56
cdeaiu23he8723de87h23e22f47b0fec7ab51e9daf458bfb530292f0eeb1fee.json'

The release notes refers to added features for credentials with assume role. Do I need to change the aws configuration for assume role with MFA?

Here's a sample of by profile

> role_arn = arn:aws:iam::08888888888:role/Administrator
> source_profile = default
> mfa_serial = arn:aws:iam::0666666666666:mfa/user

The aws cli version

> aws-cli/1.12.0 Python/2.7.9 Windows/2012Server botocore/1.8.0

Thanks

Cheers

**Comment by JordonPhillips** [comment]
Thanks for reporting! Looks like we need to strip out that `/` in those cache file names.
