### ISSUE TITLE
awslog installation of awscli does not respect existing awscli.conf in /etc/awslogs/

### ISSUE THREAD

**Issue by vschurink** [aws/aws-cli#2981]
Hi all,

I have experienced an issue when trying to log ECS instance logging to cloudwatch. 

When you specify in a cloud-init file that awslogs needs to be installed an awscli.conf file gets created in the /etc/awslogs/ directory. 
This awscli.conf however has the wrong default region specified, namely us-east-1 while we're running on eu-central-1.

Trying to fix this issue by writing an awscli.conf file using cloud-init write_files directive fails however as it appears that the install of awscli called during the awslogs installation does not repect an existing file and just overwrites the existing awscli.conf file with the 'default' configuration which does not work as it contains the incorrect region for our usecase.

I am currently bypassing this by creating a temp file and moving that during the runcmd phase of the cloud-init file, but it would be great if awscli installation respects the existance of an existing config file and just like awslogs installation renames the to be installed configuration file awscli.conf.rpmnew
 
you can replicate this behaviour by deploying an ECS instance via cloudformation file where you're using an cloud-init file to install awslogs. We're using the latest public AWS AMII for ecs.

**Comment by joguSD** [comment]
The CLI doesn't manage the `/etc/awslogs/awscli.conf` file at all. Can you provide a little more information on how you're specifying that awslogs should be installed in your cloud-init file? It might be possible for me to track down who does own this.

**Comment by vschurink** [comment]
Hi JoguSD, 

thanks for responding. attached 
[cloud-init.zip](https://github.com/aws/aws-cli/files/1506044/cloud-init.zip)
is my cloudinit file that deals with writing the file(s) and installing bootstrap and awslogs. during this fase the awscli.log file in /etc/awslogs/ gets overwritten (hence the mv hack in the runcmd part).

We call this init script during the cloudformation run of the ECS deployment.

Let me know if you need more information.

**Comment by joguSD** [comment]
I think you should ask over on the [awslogs repo](https://github.com/jorgebastida/awslogs). Closing out here as there's no actionable task for the CLI.
