### ISSUE TITLE
PowerShell Core 6 fires exceptions on most of the commands

### ISSUE THREAD

**Issue by Braza** [aws/aws-cli#2986]
PowerShell v6.0.0-rc is set up
AWSCLI module imported 
> PS C:\Program Files\PowerShell\6.0.0-rc> Import-Module "C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPow
erShell.psd1"
> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Binary     3.3.196.0  AWSPowerShell                       {Add-AASScalableTarget, Add-ACMCertificateTag, Add-ADSConf...

Although most of the commads result in exceptions

![image](https://user-images.githubusercontent.com/5665515/33239935-2454510c-d2be-11e7-8024-bda02db28529.png)

Set-AWSCredential seems to work fine

**Comment by steveataws** [comment]
This isn't an issue with the AWS CLI; you are using the wrong version of the AWS PowerShell tools (a separate CLI) inside PowerShell Core.

The AWSPowerShell module is for the 'traditional' Windows version of PowerShell. PowerShell Core is based on .NET Core - you need to be installing and importing the module named [AWSPowerShell.NetCore](https://www.powershellgallery.com/packages/AWSPowerShell.NetCore/3.3.196.0).

**Comment by Braza** [comment]
@steveataws thanks, I'll close then.
