### ISSUE TITLE
DynamoDB batch-write-item incorrectly encodes non-ASCII characters

### ISSUE THREAD

**Issue by markuspelnens** [aws/aws-cli#2987]
I am using batch-write-item (aws-cli/1.12.1 Python/3.6.0 Windows/10 botocore/1.8.1) to upload a json that contains words with German diacritics like this:

aws dynamodb batch-write-item --request-items file://C:/users/public/data.json

The data.json looks like this:

```
{
	"products": [{
			"PutRequest": {
				"Item": {
					"content": {
						"S": "Ölperlen Pfirsich"
					},
					"requestId": {
						"S": "a94b879d-5bd3-4081-a672-f72d3465a4cb"
					},
					"userId": {
						"S": "eu-central-1:someid"
					}
				}
			}
		}
	]
}

```

The command succeeds; however, when the "content" attribute arrives in DynamoDb, it looks like this: 

> `Ã–lperlen Pfirsich`

When debugging the command, I can see that something goes wrong in the unpacking stage:

`2017-11-27 08:31:17,216 - MainThread - awscli.arguments - DEBUG - Unpacked value of '{\n\t"products": [{\n\t\t\t"PutRequest": {\n\t\t\t\t"Item": {\n\t\t\t\t\t"content": {\n\t\t\t\t\t\t"S": "Ã–lperlen Pfirsich"\n\t\t\t\t\t},\n\t\t\t\t\t"requestId": {\n\t\t\t\t\t\t"S": "a94b879d-5bd3-4081-a672-f72d3465a4cb"\n\t\t\t\t\t},\n\t\t\t\t\t"userId": {\n\t\t\t\t\t\t"S": "eu-central-1:someid"\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t]\n}' for parameter "request_items": OrderedDict([('requests', [OrderedDict([('PutRequest', OrderedDict([('Item', OrderedDict([('content', OrderedDict([('S', 'Ã–lperlen Pfirsich')])), ('requestId', OrderedDict([('S', 'a94b879d-5bd3-4081-a672-f72d3465a4cb')])), ('userId', OrderedDict([('S', 'eu-central-1:someid')]))]))]))])])])`

**Comment by joguSD** [comment]
What is the encoding of the json file?
Would it be possible for you to run the following in Python and tell me the output?
```python
import locale
locale.getpreferredencoding()
```

**Comment by markuspelnens** [comment]
The json is UTF-8 encoded, and locale.getpreferredencoding() returns "cp1252".

I opened the same json in Pyhon, and unless I explicitly passed an "encoding=UTF-8" argument to the open function, it defaulted to the "preferred encoding", which in my case is cp1252. This resulted in the same incorrect character encoding as I observed with the aws cli. I am assuming the aws cli uses the same function to open files. If my understanding is correct, I would either need to change the default OS encoding (which appears to be tricky to do in Windows) or the aws cli explicitly passes a "encoding=UTF-8" argument to the file open function.

As a workaround, I am now pre-processing the json and encoding the German letters in Unicode using  ASCII characters.

**Comment by joguSD** [comment]
We do use the preferred encoding to open the file. There is a PR that would attempt to use UTF-8 first and fallback to preferred locale [here](https://github.com/aws/aws-cli/pull/2674). But we're a little hesitant to pull this in as there's still a chance for mangled characters.

**Comment by markuspelnens** [comment]
I understand the hesitation, but it seems a very reasonable PR to me. Perhaps you can default to UTF-8 for the time being and make it configurable later.

**Comment by stealthycoin** [comment]
Can you +1 that PR and give your feedback there so we can keep this conversation in the same place as much as possible? I think that would be more useful when reviewing the PR.

**Comment by Cobertos** [comment]
Can someone link this PR? I had a json file I was trying to upload and I'm getting this exact same issue when '”' type characters are in the string.

**Comment by nahtajainsurbhi** [comment]
The Germans have their place in the history of time, and when it comes to the vocabulary, it follows exactly the exact same heritage. Germany is the country that frightens the planet with innovations in automation, cars, and other technologies. One way to get into this world is through languages. The [German language Training in Pune](https://www.sevenmentor.com/german-language-classes-in-pune.php) has led to dive deep into.
