### ISSUE TITLE
Reopen #2518: Prevent AttributeError when invoking awscli from python3 daemon

### ISSUE THREAD

**Issue by emurphy** [aws/aws-cli#2990]
This is to reopen #2518. Details are there and will be submitting a new PR with an otherwise harmless, one-line fix.

**Comment by emurphy** [comment]
#2991 fixes

**Comment by joguSD** [comment]
I'm not 100% sure why we closed the previous issue but just basing off the discussion it seems like we strayed away from merging this as it doesn't fully resolve the problem. In general it might resolve the issue but will lead to errors later on when you actually try to use a feature that relies on this. To be fair, I'm not sure how common this will be in a daemon context where there is no stdin anyways. 

This will also fail if a different IO object that doesn't have a buffer, such as `io.StringIO`, is used.

**Comment by emurphy** [comment]
This fully resolves the problem. Right now among the python3 daemon users who invoke aws-cli, 100% error on the line in question. We have at least two users (myself and another on the previous issue), who have demonstrated that when the line in question is fixed, the aws-cli works through to completion. In other words, we go from 100% of this user group failing to less than 100% failing.  And keep in mind that as a rule of thumb, for every one user who complains there are a hundred more who work around the problem without notifying you. That alone is enough to justify fixing this line of code. By inspecting it, you can see that it does no harm. 

I suspect that it will actually fix it for all users in this group, as the python3 authors chose for the daemon to act this way for a reason--it has no need of providing binary input.  As mentioned on the previous issue, the offending line of code violates the spec:

The python docs are clear that a library should not rely on `sys.stdin.buffer`: 

from https://docs.python.org/3/library/sys.html:
> Note To write or read binary data from/to the standard streams, use the underlying binary buffer object. For example, to write bytes to stdout, use sys.stdout.buffer.write(b'abc').
However, if you are writing a library (and do not control in which context its code will be executed), be aware that the standard streams may be replaced with file-like objects like io.StringIO which do not support the buffer attribute.

**Comment by JordonPhillips** [comment]
Thanks for submitting the PR and bringing the issue up. We've decided to implement the fix in a slightly different way in order to improve our error messages for customers who aren't familiar with how the underlying python code works.
