### ISSUE TITLE
https_proxy / http_proxy  ipv6 does not work

### ISSUE THREAD

**Issue by limbo127** [aws/aws-cli#2994]
Hello, 
using ipv6 http/s proxy seems to not work.

Test with http(s)_proxy on localhost ipv4 : aws cli is working
Test with http(s)_proxy with ipv6 adddress : export https_proxy="http://[xxxx:xxxx:xxxx]:8080" does not work.
 (Caused by ProxyError('Cannot connect to proxy.', gaierror(-2, 'Name or service not known')))

[WSO-ROSAPARKS-3b714fa2-f497-ce7d-eb15-b8aeedea2f3c]aws --version
aws-cli/1.12.2 Python/2.7.9 Linux/4.9.23 botocore/1.8.2

Regards, 
Nicolas Prochazka

**Comment by joguSD** [comment]
We need to update urllib3 to handle this.
More info:
https://github.com/boto/botocore/issues/1325
https://github.com/boto/botocore/issues/1248

**Comment by joguSD** [comment]
We have un-vendored requests/urllib3 and are now using urllib3 directly as of `botocore` v1.11.0.
This should work as of cli version v1.16.0.
