### ISSUE TITLE
S3.upload multipart request is getting cancelled after 2min 

### ISSUE THREAD

**Issue by chaitanyasai508** [aws/aws-cli#3000]
Hi,

I'm using below code to upload my video blob data to S3

        s3.upload({
        Bucket: 'name',
        Key: key,
        Body: player.recordedData.video
      }, function(err, data){
        console.log(err, data);
      }).on('httpUploadProgress', function(evt) {
        console.log('Progress:', evt.loaded, '/', evt.total); 
  }). send(function(err, data) { console.log(err, data); });

But at times the request is getting cancelled in 2mins_(from chrome network panel)_ .Thought it is re attempting the upload, request is not successful.

> Note: This is happening when i'm trying to upload file in slower network

**Comment by joguSD** [comment]
I think you meant to open this against the [javascript sdk](https://github.com/aws/aws-sdk-js).

**Comment by daluu** [comment]
Did the OP ever post an issue to the JS SDK?
