### ISSUE TITLE
AWS CLI - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by nareshkhatri81** [aws/aws-cli#3009]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is null.
At line:1 char:28
+ ... on -Command (aws ecr get-login --no-include-email --region us-east-2) ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

we have Below version installed.
aws-cli/1.14.2 Python/2.7.9 Windows/2012Server botocore/1.8.6

As we don't have internet connectivity on server, we install it via MSI by following these instructions.
-- http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#install-msi-on-windows

**Comment by stealthycoin** [comment]
This command makes a network request so it won't work if you don't have internet access, it needs to make a POST to `ecr.us-east-2.amazonaws.com` in order to succeed.

**Comment by nareshkhatri81** [comment]
With --no-verify as argument
We are able to connect but i would like to fix it without using -no-verify.
We have internet connectivity.

**Comment by jamesls** [comment]
Do you know if you might be overriding the SSL cert bundle?  The AWS CLI bundles a cacert.pem file used to validate SSL connections, so the only reason I can think you might be getting this is either:

1. You're overriding our bundled cacerts
2. You're connecting via some proxy that's not correctly handling SSL certs.

Any other debug info you can provide us would be really helpful

**Comment by nareshkhatri81** [comment]
we moved from using proxy and we are able to connect now.

**Comment by NarasimhaChinimilly** [comment]
For me also with --no-verify worked like a charm

**Comment by Manowarsk** [comment]
Use this command at end of the command, --no-verify-ssl
ex- aws ec2 run-instances --image-id ami-00e782930f1c3dbc7 --count 1 --instance-type t2.micro --key-name efskey --security-groups Linux --no-verify-ssl

**Comment by shubhamsawantsjsu** [comment]
I have got the solution for this.

Don't install boto3 using pip/pip3.

Use following steps::

$ git clone https://github.com/boto/boto3.git
$ cd boto3
$ virtualenv venv
...
$ . venv/bin/activate
$ pip install -r requirements.txt
$ pip install -e .

It worked for me. Initially I was facing the same SSL Validation Exception problem. Then I uninstalled the boto3 (pip3 uninstall boto3) and re-installed it using virtualenv as stated above. Now, it is working fine.

**Comment by ViralAgency** [comment]
Hi, i am a MAC user (Mojave). I have the same error.

When i launch:

    repo init <repository url>

I get this error:

    Downloading Repo source from https://gerrit.googlesource.com/git-repo
    fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle
    fatal: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
    fatal: cloning the git-repo repository failed, will remove '.repo/repo'

The problem seems due to Python 3.6 on MacOS that comes with its own private copy of OpenSSL. That means the trust certificates in the system are no longer used as defaults by the Python ssl module. To fix that, you need to install a certifi package in your system.

Solved with:
 

    open /Applications/Python\ 3.6/Install\ Certificates.command
