### ISSUE TITLE
aws ssm create-document - converts YAML to JSON

### ISSUE THREAD

**Issue by ashishrajbar** [aws/aws-cli#3013]
We are unable to create YAML formatted ssm documents.

Below command
>aws ssm create-document --content "file://MF-TestYAML.yml" --name MF-TestYAML --document-type "Command" --document-format YAML

converts and creates document in JSON instead of YAML.

P.S. it seems the web console does not support YAML yet.

**Comment by stealthycoin** [comment]
This is just the service itself, all we do is call it and show you the response. I would suggest bringing this up with the service team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).

**Comment by ashishrajbar** [comment]
ok
