### ISSUE TITLE
Apply s3 lifecycle policy across buckets to clear up failed multi-part uploads

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#3014]
Might be related to https://github.com/aws/aws-cli/issues/1076

    aws-cli/1.14.2 Python/3.6.3 Linux/4.14.3-1-ARCH botocore/1.8.6

When getting a life cycle policy from one bucket, and applying it to another, I expect it to work:

```
~/s3$ aws --profile mine s3api get-bucket-lifecycle --bucket archive.webconverger.com > multipart.json
~/s3$ cat multipart.json
{
    "Rules": [
        {
            "Expiration": {
                "ExpiredObjectDeleteMarker": true
            },
            "ID": "Multipart",
            "Status": "Enabled",
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 1
            }
        }
    ]
}
~/s3$ aws --profile mine s3api put-bucket-lifecycle --bucket vueaws.dabase.com --lifecycle-configuration file://multipart.json

Parameter validation failed:
Missing required parameter in LifecycleConfiguration.Rules[0]: "Prefix"
```
As you can see it fails because it's missing a prefix. Why didn't the "get-bucket-lifecycle" receive that element in response or why does "put-bucket-lifecycle" require it?

My use case is that I am trying to ensure I don't get charged for **failed multi-part uploads**. RE case id 4704659031 upon my account 407461997746. If there is a better way of doing this let me know.

I'm also worried that if there is an existing life cycle policy on a bucket, that I will effectively overwrite it with this API. I guess there is no way to merge policies?

**Comment by stealthycoin** [comment]
This looks like a service question to me, we only send the requests and show the responses, any service usage related questions should be directed to either [support](https://console.aws.amazon.com/support/home#/) or the [service forums](https://forums.aws.amazon.com/forum.jspa?forumID=24). There are too many services these days for us SDK maintainers to be experts in all of them.

**Comment by kaihendry** [comment]
It's not a service issue. It's a policy mapping issue where a fetched policy won't apply to another policy, which it should. Please re-open.
