### ISSUE TITLE
Credentials file does not override credentials in config

### ISSUE THREAD

**Issue by SamCyanide** [aws/aws-cli#3015]
`$ aws --version`
`aws-cli/1.2.9 Python/3.4.3 Linux/3.13.0-55-generic` (Ubuntu 14.04.5 LTS)

On [this page](http://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html) of the documentation, under the "Storing Credentials in Config" section, it is stated that the `~/.aws/credentials` file overrides any credentials stores in the `~/.aws/config` file. I rotated IAM keys recently and updated the `credentials` file. However, all `aws` commands are failing because of invalid credentials. I took a look and there were the old credentials in the `config` file. After commenting them out, all `aws` service commands (ec2, s3, etc.) are failing due to having no credentials. When I run an `aws configure` it shows "none" for previous credentials. 

The documentation specifically states that the credentials file is supposed to override those in config, but this does not seem to happen. However, it does note that having an SDK installed will require the #credentials file. On another server, with `boto` installed (botocore 1.4.39) running `aws-cli/1.10.49` on kernel `3.14.48-33.39.amzn1.x86_64` (Amazon Linux 2015.03) having no credentials in the `config` file, and just using the `credentials` file works just fine. With no boto installed, however, it will fail if you do not have the credentials in the `config` file.

**Comment by stealthycoin** [comment]
Looks like you have a very old version of the cli and it also looks like it comes from a linux distro package manager which is not supported by us. Try installing the newest version from `pip` which is the distribution method we support. Let me know if that fixes it for you or if you still have the same issue on a newer version.

**Comment by SamCyanide** [comment]
Perhaps this was patched. Unfortunately due to versioning requirements (ugh) and validation procedures (dobule ugh) I can't update packages and I'd like to make sure of this before I do. I'll do some testing, but likely won't have a chance to for a few months so I will close this and re-open in a few months if it is not fixed.
