### ISSUE TITLE
Question: Why does 'cloudformation package' require '--s3-bucket' 

### ISSUE THREAD

**Issue by frob** [aws/aws-cli#3024]
I apologize in advance if this isn't the place to ask this question. There was nothing in CONTRIBUTING.rst about asking general questions.

I am running through the [SAM how-to documentation](https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md) and started experimenting with ```aws cloudformation package``` when I noticed that it requires ```--s3-bucket``` but doesn't seem to do anything with it.

Why is this argument required?

**Comment by frob** [comment]
Nevermind.

> Packages the local artifacts (local paths) that your AWS CloudFormation template references. The command uploads local artifacts, such as source code for an AWS Lambda function or a Swagger file for an AWS API Gateway REST API, to an S3 bucket.

**Comment by phongn17** [comment]
I am running aws cloudformation package ... and received a message 'aws.exe: error: argument operation: Invalid choice, valid choice are: cancel-update-stack ...' It does not list package as an operator. Is it replaced by other operation?

**Comment by frob** [comment]
@phongn17 can you post your yaml? It is likely you are missing a parameter. Also, this is a closed issue, you might consider opening a new issue.
