### ISSUE TITLE
Option to add T2 Unlimited using a launchconfiguration

### ISSUE THREAD

**Issue by bjornbak** [aws/aws-cli#3029]
According to the examples on how to add T2 Unlimited while creating EC2 instances using an autoscaling group it is done using a launchtemplate: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html#t2-auto-scaling-grp

But as launchtemplate and launchconfiguration is mutual exclusive please add the option to add T2 Unlimited using a launchconfiguration like a 
--credit-specification=cpucredits-unlimited
to aws autoscaling create-launch-configuration

**Comment by bjornbak** [comment]
Realizing launchtemplate is a complete replacement of launchconfiguration.

**Comment by bjornbak** [comment]
After 7 hours of rewritten my code to use a launchtemplate instead of a launchconfiguration I realize that a launchtemplate do not replace a launchconfiguration!

A launchtemplate is tight to a single subnet I need a launchconfiguration where the autoscalinggroup places in new instances in multiple AZs.

Please add the T2 unlimited feature to launchconfigurations too!

**Comment by dstufft** [comment]
The AWS CLI just exposes the APIs provided by the individual services, and in this case the LaunchTemplate API does not provide this feature. Your best option is to raise a request with the [EC2 Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).
