### ISSUE TITLE
review security-group settings of AMI prior to deployment?

### ISSUE THREAD

**Issue by n0x08** [aws/aws-cli#3036]
Is there a way to review the vendor supplied security-group config of AMI's before they're deployed? I see the rest of the details with a 'aws ec2 describe-images' command, however there's nothing in this data which shows the SG config the image will deploy with.

When going through the Launch Instance Wizard in the AWS Website these settings are immediately available under 'Step 6: Configure Security Group' but I can't find it in aws-cli.

**Comment by dstufft** [comment]
The AWS CLI can only expose the values returned by the service API, and in this case the [DescribeImages](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html) API does not expose this information. You can ask for that feature to be added on the [EC2 Forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).
