### ISSUE TITLE
Stop skipping FIFOs now that streams with STDIN/OUT are working with s3 cp.

### ISSUE THREAD

**Issue by bmcgough** [aws/aws-cli#3037]
We would very much like to use named pipes in AWS Batch to set up data streams from S3 for user jobs. It is exciting that AWS CLI supports STDIN/OUT at this time, but not all command line tools our users want can work with STDIN/OUT. Named pipes would let us use data streams with tools that do not directly support STDIN/OUT.

It looks like is_special_file() in filegenerator.py checks stat.S_ISFIFO. That made sense when streams were not supported, but now that they are, I think it is just that check that is stopping us from uploading to S3 from our AWS Batch containers (download works, which makes sense as no local file would need to be stated).

**Comment by dstufft** [comment]
Marking as an enhancement request, thanks.
