### ISSUE TITLE
Possible issue with assume-role not respecting source_profile

### ISSUE THREAD

**Issue by hussfelt** [aws/aws-cli#3039]
I'm contributing to a tool for assuming roles and setting credentials to the environment. Doing this I found a case where - with having multiple profiles using the same source_profile - not being able to assume role, specifying a profile.

Issue affected:
https://github.com/hybby/aws-switchrole/issues/11

Command executed:

```
aws sts assume-role --role-arn arn:aws:iam:: 123456789:role/Implementation --role-session-name dr-account1-141217074137 --profile dr-account1
```

Error:

```
An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole
```

Solved by:

```
aws sts assume-role --role-arn arn:aws:iam:: 123456789:role/Implementation --role-session-name dr-account1-141217074137
```

Config:

```
[default]
region = eu-west-1
output = json
[preview]
cloudfront = true

[profile dr-account3]
role_arn = arn:aws:iam::1234567899:role/Administrator
source_profile = default
region = eu-west-1

[profile dr-account2]
source_profile = dr-otherprofile
region = eu-west-1

[profile dr-account1]
role_arn = arn:aws:iam::123456789:role/Implementation
source_profile = default
region = eu-west-1
```

Credentials:

```
[default]
aws_access_key_id = AKIASOMKEY
aws_secret_access_key = SOMESECRET
```

Quote from the other thread:

I can assume all these roles in the AWS console and through the ```aws sts``` command.

I can call the command without specifying the profile and assume the role. But not specifying the profile - even though the source_profile points to the default one.

**EDIT: Fixed references to profile**

**Comment by joguSD** [comment]
It seems like you're trying to use a profile to assume the role `arn:aws:iam::123456789:role/Implementation` then use an `aws sts assume-role` operation call to assume `arn:aws:iam::123456789:role/Implementation` again (while already acting under that role). I'm not sure this use case makes sense, furthermore that error is coming back from the service.

The source profile is used to specify which credentials to use when making an assume role call to assume the `role_arn` in the profile.

**Comment by hussfelt** [comment]
@joguSD yes, this is what I narrowed it down to as well. I am unsure though why ```--profile``` in this case (```aws sts assume-role```) would respect the role_arn here. Is it possible to assume a role with a role, is it not the IAM user that is the key there? Setting up profiles with specific ```source_configuration``` seems like best practice, configuring different setups and accounts.

If this behaviour is still considered correct, please do close this case.
