### ISSUE TITLE
S3 prefix is not obvious

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#304]
The experience is again jarring. The UX doesn't guide you to use `s3://`

    $ aws s3 ls

           CreationTime Bucket
           ------------ ------
    2013-08-30 13:57:23 bbackup
    $ aws s3 ls bbackup
    usage: aws s3 ls <S3Path> or NONE
    Error: Invalid argument type
    sg:~/btsync$ aws s3 ls s3://bbackup

    Bucket: bbackup
    Prefix: 

          LastWriteTime     Length Name
          -------------     ------ ----

**Comment by RichardBronosky** [comment]
@jamesls,
This seems to be resolved with `aws s3 ls` but is still an issue with `aws s3 cp`. For the former, the s3 [URI scheme] is optional. For the later it is not. I suggest putting `<S3Path>` in the usage statements where it is optional and `<S3Uri>` where the scheme is required.

Also, THANK YOU for https://www.youtube.com/watch?v=qiPt1NoyZm0 I go back and rewatch it every few weeks. There is SO MUCH to learn in there.

[URI scheme]: http://en.wikipedia.org/wiki/URI_scheme

**Comment by RichardBronosky** [comment]
I don't know if https://github.com/aws/aws-cli/pull/1232 is too extreme of a change for you. Before grepping the source for s3path I didn't even know that `awscli/examples/s3/_concepts.rst` existed. If this change messes up a bunch of other documentation, let me know and I'll consider a different way to improve the UX.

The main thing you get from this is to go from:

    aws s3 cp mybucket/test.txt test2.txt

    usage: aws s3 cp <LocalPath> <S3Path> or <S3Path> <LocalPath> or <S3Path> <S3Path>
    Error: Invalid argument type

To:

    aws s3 cp mybucket/test.txt test2.txt

    usage: aws s3 cp <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
    Error: Invalid argument type

I think that better communicates what is invalid about the arguments.

**Comment by mtdowling** [comment]
`aws s3 ls` now allows the `s3://` scheme to be optional. I've taken a look at your PR, @RichardBronosky. It looks great. I'm going to rebase it and merge it in.

**Comment by SirR4T** [comment]
`aws s3 ls` now indeed allows the `s3://` scheme to be optional, but `aws s3 rm` doesn't yet. Should that be raised as a different issue?
