### ISSUE TITLE
SNS protocols description shows only one supported protocol

### ISSUE THREAD

**Issue by reddy-v** [aws/aws-cli#3046]
Description of sns protocols attribute doesn't show all supported protocols. It shows only http.. other email, lamda etc are not shown
![snsprototype](https://user-images.githubusercontent.com/20856583/34075298-1b9a1abc-e2e8-11e7-93ad-70e132cc2a86.JPG)

**Comment by joguSD** [comment]
This seems like an issue with the `aws-shell` could you open up an issue against [this repo](https://github.com/awslabs/aws-shell)?
