### ISSUE TITLE
aws cloudtrail put-event-selectors returns TrailNotFoundException

### ISSUE THREAD

**Issue by smarshal-Quest** [aws/aws-cli#3048]
receiving error:

An error occurred (TrailNotFoundException) when calling the PutEventSelectors operation: Unknown trail: xxxx .  

Trail does exist 

aws-cli/1.11.181 Python/3.6.3 Darwin/17.3.0 botocore/1.7.39

**Comment by joguSD** [comment]
Does the trail exist in the region that you're trying to use?
Does the trail name appear when you call `aws cloudtrail describe-trails`?

**Comment by smarshal-Quest** [comment]
:( school boy error  taill was in another region than my default --region  resolved my issue
