### ISSUE TITLE
high sierra can not install 

### ISSUE THREAD

**Issue by WinLinKer** [aws/aws-cli#3051]
can u give us a best way to install awscli  on high sierra,i tried a lot of method,all failed,i install python 2.7. and python 3.7

pip install awscli
sudo pip install awscli

hope you can test on your system,if success,let us know

thanks .

**Comment by joguSD** [comment]
Without more information on what failed I'm afraid I can't help much. Have you tried installing using a [bundled installer](http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html#install-bundle-other)?

**Comment by WinLinKer** [comment]
thanks for your reply,i use source tar.gz,successed.
