### ISSUE TITLE
S3 Copy - Bad Substitution Tail: Write Error: Broken Pipe

### ISSUE THREAD

**Issue by varun2327** [aws/aws-cli#3056]
Hello,
I have a use case where I need to read the file from one S3 bucket in memory, remove the first line of the file and then put the output back to another S3 bucket. I ran the below command from terminal without parameters and it worked perfectly fine but when I run the same command with parameters(like below) inside the script it is throwing the broken pipe error. I searched for answers and nothing seem to work. Please guide me if you have ran in to the similar issue before and how it can be resolved.

**Command:**
aws s3 cp s3://${srcBucketName}/${InputFolderName}/${srcFileName} - | tail -n +2 | aws s3 cp - s3://${destBucketName}/${DestFolderName}/${srcFileName}.dat --sse

**Error:**
/opt/nifi/current/lib/app/remove_header.ksh: line 19: s3://${destBucketName}/${DestFolderName}/${srcFileName}.dat: bad substitution tail: write error: Broken pipe

**Comment by joguSD** [comment]
The important part is `bad substitution`. It sounds like the shell you're using (ksh?) doesn't like your variable expansion syntax. I would double check to make sure that the command being generated after performing the substitution is correct.

Also closing this out as it is not an issue with the CLI.

**Comment by varun2327** [comment]
Thanks joguSD, you are right. The variables were not resolving properly in Nifi flow. I was able to change them and it worked fine.
