### ISSUE TITLE
Update the snap package to the latest release

### ISSUE THREAD

**Issue by ghisvail** [aws/aws-cli#3065]
Please consider upgrading the Ubuntu snap package to the latest upstream release (version `1.14.16` at the time of writing). The current version available in the snap store is `1.14.11`. It might be worth to push future updates automatically to the snap store alongside the upload to PyPI.

**Comment by joguSD** [comment]
We don't maintain the Ubuntu snap package, not sure who does either.

Closing out here as there is no actionable item for us.

**Comment by tunix** [comment]
Would you consider owning it? It'd be great if there's an up-to-date version available as a snap.
