### ISSUE TITLE
aws s3 cp error:  __init__() got an unexpected keyword argument 'max_bandwidth'

### ISSUE THREAD

**Issue by bosveld** [aws/aws-cli#3075]
When running ‘aws s3 cp s3_file.txt s3://mybucketname/

I get this error
__init__() got an unexpected keyword argument 'max_bandwidth'

$ aws —version
aws-cli/1.14.18 Python/2.7.14 Darwin/17.3.0 botocore/1.8.23

$ pip install --upgrade s3transfer
Requirement already up-to-date: ….. 

Still get same error after pip install --upgrade

Any ideas what I am missing?
Thanks

**Comment by kyleknap** [comment]
How did you originally install the AWS CLI? Was it using `pip`? Also could you run `which aws` to see where it points to? I have a feeling that even though `s3transfer` is getting upgraded with `pip`, there is a separate installation of `s3transfer` that is being used when the CLI is ran, and thus why upgrading is not helping.

**Comment by bosveld** [comment]
I am using Python 2.7 as per Anaconda package
awscli was installed with `conda install -c conda-forge awscli`

I tried following.  Uninstalling awscli with `conda uninstall awscli`

When running `aws` now I get command not found (as expected)
	
Then install awscli again but this time with 
`pip install awscli --upgrade --user`

Typing `show pip awscli` I see:

	Name: awscli
	Version: 1.14.20
	Location: /Users/<userid>/anaconda/lib/python2.7/site-packages

Look if it should be available but still not working. Get command not found.

`which python` shows:
/Users/<userid>/anaconda/bin/python

Add tried adding any of following to .bash_profile

	export PATH="/Users/<userid>/Library/Python/2.7/bin:$PATH"
	export PATH =“/Users/<userid>/anaconda/bin:$PATH”
	export PATH="~/.local/bin:$PATH"

Still not working

**Comment by bosveld** [comment]
Problem now resolved.  
I rather used `brew install awscli` to install cli.

**Comment by diplodata** [comment]
`pip install awscli --upgrade --user` worked for me. Thanks.
