### ISSUE TITLE
aws ec2 describe-snapshots filter by volume-size

### ISSUE THREAD

**Issue by aw-huit** [aws/aws-cli#3077]
Maybe I'm doing something wrong but one cannot filter for volume-size greater or less than a number:

```
$ aws ec2 describe-snapshots --owner-id 593028750997 --filter Name=volume-size,Values>100

Parameter validation failed:
Invalid type for parameter Filters[0].Name, value: [u'volume-size', u'Value'], type: <type 'list'>, valid types: <type 'basestring'>

$ aws --version
aws-cli/1.14.20 Python/2.7.12 Darwin/16.7.0 botocore/1.8.24
```

I tried various quoting schemes and none of them had any effect.  FYI if I use Values=100 command works.  Filtering for less or greater than a number works in the web GUI.

**Comment by kyleknap** [comment]
So the `--filter` parameter corresponds to EC2's filter API and it looks like it only supports filtering if it is equal to a value. So instead the console is probably doing client side filtering to achieve the greater/less than filter. Fortunately, you can do this with the CLI as well by using the `--query` parameter. So something like:
```
$ aws ec2 describe-snapshots --query 'Snapshots[?VolumeSize>`100`]'
```
should return all of the snapshots whose size is greater than a 100 GB.

Let us know if that helps.
