### ISSUE TITLE
aws cloudwatch put-metric CPU

### ISSUE THREAD

**Issue by jkotrlik** [aws/aws-cli#3081]
Hi there,
we started monitoring about 50 metrics every minute and we had to bump up the EC2 machine, because CPU was 100% full time and metrics weren't getting pushed in time or at all, which caused our alarms not to have enough data. So we wonder, is it suppose to eat up that much CPU? We had to make separate monitoring machine and it's stronger than our production machines. It also happened to us that we couldn't ssh into machine under such load and had to reboot.
We're pushing to the cloudwatch in the same region as the EC2 which pushes is, so slow network should not be the culprit. We suspect that doing HMAC for every command takes that much time and eats that much CPU.
So one option would be to optimize calculations.
The other (and we believe better) option would be to make it possible to push not just one, but unlimited metrics with their dimensions, data and units in one `aws` command. We're still expanding and we might be looking at 200+ API calls every minute (which would require a huge machine).

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
```
aws --version
aws-cli/1.14.4 Python/3.5.2 Linux/4.4.0-1044-aws botocore/1.8.8
```

Thanks, Jan

**Comment by joguSD** [comment]
It sounds like you're calling `aws` for each metric you send, is that correct? It's possible to batch the calls a bit as `--metric-data` is a list. If I recall correctly you can send up to 20 metrics per api call. We can't support unlimited metrics as this is an API limitation. The largest performance hit here is likely having to start a new Python process every time you call `aws`. It might be worthwhile to use an AWS SDK directly to improve performance, for example [boto3](https://github.com/boto/boto3/).

Let me know if this helps.

**Comment by jkotrlik** [comment]
Yes, that is correct, we're calling `aws` command each time we push. I was looking at `--metric-data`, but that let's you push only to one namespace, do I get that right?

Thanks, Jan

**Comment by joguSD** [comment]
Yep, you can only publish to one namespace per API call.

**Comment by jkotrlik** [comment]
Ok, thanks, we went with `--metric-data` per namespace and it's working pretty good. Too bad there is 20 metrics limitation per API call.

I consider this resolved.
Thanks, Jan.
