### ISSUE TITLE
No --user-data flag for spot fleet requests

### ISSUE THREAD

**Issue by rterwedo** [aws/aws-cli#3084]
It seems there is no standard --user-data flag for spot requests as there are for ec2 instances?  Is this by design or a miss?

We noticed in json structure of spot fleet request there is a "UserData" string option, but for complicated scripts this is less than ideal (2 different versions of user data scripts based on whether they are launched on ec2 or spot)

**Comment by stealthycoin** [comment]
This is a part of the EC2 API so its not really anything the CLI specifically could do here. This would be a feature request for EC2 which you can do through [support](https://console.aws.amazon.com/support/home#/) or the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=30).
