### ISSUE TITLE
Rekognition detect-labels "--min-confidence" values below 50 not working

### ISSUE THREAD

**Issue by dcnoren** [aws/aws-cli#3098]
aws-cli/1.14.29 Python/2.7.12 Linux/4.4.0-109-generic botocore/1.8.33

Attempting to specify a minimum confidence does not work with values below 50 (default). Setting to, for example, 90, does limit the confidence values returned to those only higher than 90. Setting to 0-50 seems to have no impact (unless of course, magically there are no values being returned below 50 confidence, but given how many are 50.0xxxx I doubt that to be the case).

https://docs.aws.amazon.com/rekognition/latest/dg/API_DetectLabels.html states that 0 - 100 are possible values for the API.

**Comment by dstufft** [comment]
Unfortunately this is going to be controlled by the service itself and this isn't something that the CLI is going to be able to affect. I would suggest asking on the [Rekognition forums](https://forums.aws.amazon.com/forum.jspa?forumID=234) so that the service team itself can answer your question.
