### ISSUE TITLE
AWS EMR Cluster exists and is ready but describe-cluster doesn't work

### ISSUE THREAD

**Issue by md-software** [aws/aws-cli#3099]
Hello.

I've started an AWS EMR cluster. I cannot log into using ssh but from my local machine where I try to execute $aws emr describe-cluster --cluster-id j-XXXXXXXXX
I get:
An error occurred (InvalidRequestException) when calling the DescribeCluster operation: Cluster id 'j-XXXXXXXXX' is not valid.

I've the same problem with add-steps

My cluster is set to visible by all.

Any idea ?

EDIT: if I run the describe command from an ssh session on the cluster, it works. So is it possible to run the command from my local computer ?

**Comment by dstufft** [comment]
Unfortunately this error comes from the service API itself, and isn't something the CLI has any control over. If you're still getting this issue I would suggest using one of the help resources linked from the [Getting Help](https://github.com/aws/aws-cli#getting-help) section of the readme.
