### ISSUE TITLE
cloudformation --generate-cli-skeleton fails

### ISSUE THREAD

**Issue by davidham** [aws/aws-cli#3100]
I am trying to get the output of `aws cloudformation wait stack-update-complete`. I ran the following:

```
aws cloudformation wait stack-update-complete --generate-cli-skeleton output
```

**Expected result**: I expected to see an example of the JSON that this command will output, [as described in the docs](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/wait/stack-update-complete.html). 

**Actual result**:
```
$ aws cloudformation wait stack-update-complete --generate-cli-skeleton output

Parameter validation failed:
Invalid range for parameter Stacks[0].TimeoutInMinutes, value: 0, valid range: 1-inf
Invalid length for parameter Stacks[0].RoleARN, value: 7, valid range: 20-inf
```

May be related to #2337?

**Comment by dstufft** [comment]
I can produce it, marking it as a bug, thanks!

**Comment by stobrien89** [comment]
Closing, as this is a duplicate of #2337.
