### ISSUE TITLE
Subcommand help broken

### ISSUE THREAD

**Issue by Dunedan** [aws/aws-cli#3101]
In 1.14.29 the subcommand help is broken, so commands such as e.g. `aws ec2 describe-images help` don't work anymore. Instead the following error message is shown:
```
'ReSTStyle' object has no attribute 'internal_link'
```

Up to 1.14.28 it worked fine.

**Comment by stealthycoin** [comment]
What version of botocore do you have?

You need botocore>=1.8.33 and version CLI version 1.14.29 is pinned to 1.8.33 so you should be able to upgrade with pip `pip install -U awscli`.

**Comment by Dunedan** [comment]
I have `botocore==1.8.33` installed.

**Comment by Dunedan** [comment]
Found another local installation of `botocore` with an older version. Upgrading that as well solved it.
