### ISSUE TITLE
[Feature request] Option to preserve existing tag values when using aws ec2 create-tags

### ISSUE THREAD

**Issue by aw-huit** [aws/aws-cli#3107]
I know I can script around it but it's really a pain when you need to create tags on multiple resources, it means I can no longer give multiple values to --resources, instead I'll have to check the resources one by one.

**Comment by joguSD** [comment]
This sounds like a feature request for the service side of things and isn't something we're likely to implement in the CLI. I would suggest reaching out to [AWS Support](https://console.aws.amazon.com/support/home#/) or the service team at their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=30).
