### ISSUE TITLE
ssm put-parameter prompt for value

### ISSUE THREAD

**Issue by rofinn** [aws/aws-cli#3109]
It'd be nice if `aws ssm put-parameter` provided a secure prompt (e.g., `getpass`) when `--value` isn't provided.

**Comment by dstufft** [comment]
I can see a use case for this, but I'm not sure if it's something we'd be willing to implement or not. I'm flagging it as needing further discussion, thanks!

**Comment by rofinn** [comment]
Just noticed that the command arguments table is generated from a botocore session, which is largely generated from the JSON API. I can see why you might not want to special case this particular option then.

**Comment by stobrien89** [comment]
Reviewed—closing due to lack of traction and staleness.  Please feel free to @ me with any questions!
