### ISSUE TITLE
Distinguish between SI and IEC prefixes

### ISSUE THREAD

**Issue by ben4ever** [aws/aws-cli#3117]
Currently, sizes prefixed with SI prefixes like `k`, `M`, `G`, and so on, are treated as IEC prefixes:
https://github.com/aws/aws-cli/blob/6403926407f5502e6820764bca154a5be58ed25c/awscli/customizations/s3/utils.py#L36-L39

As you can read [here](https://en.wikipedia.org/wiki/Binary_prefix#Adoption_by_IEC,_NIST_and_ISO) though, this is strictly discouraged today. I therefore suggest to change the code quoted above to:
```python
    'kb': 1e3,
    'mb': 1e6,
    'gb': 1e9,
    'tb': 1e12,
```

**Comment by joguSD** [comment]
Thanks for the feedback! While it is technically correct we don't have any plans this update these. 
We added the IEC versions after having the (incorrect) SI versions and decided that it wasn't worth modifying the behavior of existing commands to be technically correct.

Perhaps this is something we can revisit if were ever to major version bump the CLI.
