### ISSUE TITLE
aws CLI UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 17: ordinal not in range(128)

### ISSUE THREAD

**Issue by melvudin** [aws/aws-cli#3125]
I have uploaded an image into my AWS S3 bucket. And I am trying to use the AWS Rekognition Detect labels feature on my Ubuntu 16.04. After configuring the AWS CLI, I tried: 

> aws rekognition detect-labels --image “{\"S3Object\":{\"Bucket\":\"myBucketName\",\"Name\":\"myImageName.jpg\"}}” --region eu-west-1

And this is the response: UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 17: ordinal not in range(128)

I have seen some answers regarding the aws configure non-ascii copy mistake solutions, but that is not the solution in my case!
Any suggestions on what this error might be?

**Comment by kyleknap** [comment]
I believe the main issue is because you are trying to quote with the character ``“``. Instead, I would recommend using single quotes to preserve the double quotes in your CLI command. So something like this:
```
aws rekognition detect-labels --image '{"S3Object":{"Bucket":"myBucketName","Name":"myImageName.jpg"}}' --region eu-west-1
```
That worked just fine for me. Let us know if that helps.

**Comment by melvudin** [comment]
@kyleknap It worked like a charm! Thank you!

**Comment by joguSD** [comment]
Glad that worked for you! Closing this out.
