### ISSUE TITLE
EC2 Run Command option

### ISSUE THREAD

**Issue by pmartindev** [aws/aws-cli#3126]
In the following AWS blog post from October 2015, it is mentioned (3 times to be exact) that the _EC2 Run Command_ can be be executed via the AWS cli. However, I have searched through the docs, release notes, examples, and briefly through the code and cannot find an any reference to this particular CLI command.  I think this should be supported if it is not already, and if it is, there should be an example placed in the examples/ec2/  directory 

https://aws.amazon.com/blogs/aws/new-ec2-run-command-remote-instance-management-at-scale/

**Comment by kyleknap** [comment]
@pmartindev Have you tried taking a look at the ``ssm`` commands? Specifically, I believe it is the [send-command](https://docs.aws.amazon.com/cli/latest/reference/ssm/send-command.html) CLI command is what you are looking for. The console occasionally combines multiple services onto a single service console page so it is sometimes misleading that a functionality that you are looking for actually exists in a separate service API (which is how the SDKs and Tools are partitioned).

**Comment by kenorb** [comment]
Yep, it works.

Example:

```
cmdid=$(aws ssm send-command --instance-ids "i-ch3ng3th1s" --document-name "AWS-RunPowerShellScript" --parameters commands=ipconfig --query "Command.CommandId" --output text)
aws ssm list-command-invocations --command-id "$cmdid" --details --query "CommandInvocations[*].CommandPlugins[*].Output[]" --output text
```

**Comment by joguSD** [comment]
Closing out due to inactivity.
