### ISSUE TITLE
--dry-run gives client error

### ISSUE THREAD

**Issue by binkocd** [aws/aws-cli#3127]
The following results in a "client error", but states it would have worked. 

```
# aws ec2 run-instances \
>     --instance-type "c3.4xlarge" \
>     --user-data "<removed>" \
>     --image-id  ami-<removed> \
>     --placement AvailabilityZone=us-west-2c \
>     --iam-instance-profile Name=<removed> \
>     --key-name <removed> \
>     --network-interfaces '[{ "DeviceIndex": 0, "SubnetId": "subnet-<removed>", "Groups": [ "sg-<removed>" ], "AssociatePublicIpAddress": true }]' \
>     --dry-run

A client error (DryRunOperation) occurred when calling the RunInstances operation: Request would have succeeded, but DryRun flag is set.
```
and
```
# echo $?
255
```
When running a malformed --dry-run, it gives the same 255 exit code. 

It would be great to have this return a success and different exit code on a well formed --dry-run and a failure or error on malformed --dry-run requests. This message, at first glance, is confusing and could be problematic.

**Comment by kyleknap** [comment]
So unfortunately I do not think there really is not much we can do here. The EC2 API returns any dryrun operation as an error, and in the CLI, we always surface the API errors to the end user as errors. To do the one off customization to change the `--dry-run` parameter related errors be surfaced as successful is likely something we would not change and would also be backwards incompatible if we did change. Out of curiosity how are you currently scripting this to handle unsuccessful dryruns versus successful dryruns? One thing that I could imagine us doing is adding the ability to parse exceptions into a format that easy to script around (i.e. `json` or `text) as right now to script you would need to run a regex on the error message.

**Comment by binkocd** [comment]
So it's something on the AWS side of things and not the CLI tool, if I'm reading that correctly? I'll reach out to AWS and see if I can get some clarification on that decision.

But to answer your question, I haven't put any dry-run into and scripts yet, but I was toying around with it for a new build out.
