### ISSUE TITLE
Route table missing in 'ec2 describe-vpcs'

### ISSUE THREAD

**Issue by kenorb** [aws/aws-cli#3136]
I'm running `aws ec2 describe-vpcs` command, however the output is missing route tables. It's displayed fine on AWS Console. My goal is to find the route table id based on the instance.

My commands are:
```
vpcs=$(aws ec2 describe-instances --instance-id $id --query 'Reservations[].Instances[].NetworkInterfaces[].VpcId' --output text)
aws ec2 describe-vpcs --vpc-ids $vpcs
```

I'm using:

    aws-cli/1.11.13 Python/3.5.4 Linux/4.12.7-64 botocore/1.4.70

**Comment by kyleknap** [comment]
It looks like you figured it out in the issue you opened up a little later: https://github.com/aws/aws-cli/issues/3138. That is was what I was going to suggest. Is that working for you now?

**Comment by kenorb** [comment]
So I assume it's not a bug? It's quite confusing since the internet gateway (`igw`) is present in VPC on the AWS Console.

----

Although, as [suggested here](https://github.com/aws/aws-cli/issues/3138#issuecomment-363957362), the following workaround worked for me to load the route tables for the given instance:

```
id=i-0xyzxyz
vpcs=$(aws ec2 describe-instances --instance-id $id --query 'Reservations[].Instances[].NetworkInterfaces[].VpcId' --output text)
igw=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$vpcs" --query "InternetGateways[].InternetGatewayId" --output text)
aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$vpcs" --query "RouteTables[].Routes[]"
```

**Comment by kyleknap** [comment]
Yeah it is not a bug. EC2 would have to add it to its `DescribeVpc` API. The console often times makes multiple different API calls when it is renders its view. There is a strong possibility that it is making more API calls than `DescribeVpc` when it is rendering the VPC view.
