### ISSUE TITLE
Feature Request: Support "--datapoints-to-alarm" on CloudWatch Alarms

### ISSUE THREAD

**Issue by sirosen** [aws/aws-cli#3140]
One of the `aws cloudwatch put-metric-alarm` parameters supported by Boto3 and the underlying API is missing from the CLI.

`--datapoints-to-alarm` lets you set alarms based on the number of breaching datapoints (default is all).

This lets you have a much wider class of alarm conditions, for example,

> alarm if Average CPUUtilization per Minute > 50% more than 75% of the time for an hour

can be done with `--datapoints-to-alarm=45 --period=60 --evaluation-periods=60`

In the current version of the CLI, you can't create such alarms.

---

Also, this might be unrelated, but I don't see this value coming back from `describe-alarms` or `describe-alarms-for-metric` ? Is that a bug, or related to this feature?

**Comment by kyleknap** [comment]
What version of the CLI are you using? I suspect you need to upgrade your version of the CLI as the latest versions of the `boto3` and the CLI share the same core library for API updates. You can read more about it in the [documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html). Furthermore, if you upgrade I suspect that you will start seeing the values come back from `describe-alarms` and `describe-alarms-for-metric` as if you are using the latest CLI version it will be modeled and thus parsed into the response printed back.

**Comment by sirosen** [comment]
Ach! I confused my systemwide install of awscli with an install I did with `pip install --user`.

All of this happened with `aws-cli/1.11.181 Python/2.7.13 Linux/4.9.0-5-amd64 botocore/1.7.48`, NOT with the latest version.

Fixed my local setup and everything works fine. Sorry for the noise, and thanks for the quick response.
