### ISSUE TITLE
aws s3 sync fails for bad soft links

### ISSUE THREAD

**Issue by babunatarajan** [aws/aws-cli#3150]
aws-cli/1.14.29 Python/2.7.10 Darwin/17.2.0 botocore/1.8.33

Babus-Mac:test babunatarajan$ aws s3 sync . s3://babunatarajantest/ --profile aws-admin
warning: Skipping file /Users/babunatarajan/Desktop/test/b/c/d/test. File does not exist.

Babus-Mac:test babunatarajan$ aws s3 ls s3://babunatarajantest/ --profile aws-admin
Babus-Mac:test babunatarajan$ touch testfile && aws s3 cp testfile s3://babunatarajantest/ --profile aws-admin
upload: ./testfile to s3://modetwotest/testfile

Babus-Mac:test babunatarajan$ aws s3 ls s3://babunatarajantest/ --profile aws-admin
2018-02-15 15:34:28 0 testfile

Babus-Mac:test babunatarajan$ aws s3 sync /Users/babunatarajan/Desktop/test/ s3://babunatarajantest/ --profile aws-admin
warning: Skipping file /Users/babunatarajan/Desktop/test/b/c/d/test. File does not exist.

Babus-Mac:test babunatarajan$ aws s3 ls s3://babunatarajantest/ --profile aws-admin
2018-02-15 15:34:28 0 testfile

Babus-Mac:test babunatarajan$ tree
.
├── a
│   └── b
│   ├── c
│   └── d
├── b
│   └── c
│   └── d
│   └── test -> ../../../a/b/test
├── testfile
└── z
└── a

9 directories, 2 files

**Comment by jamesls** [comment]
Can you clarify what you're suggesting the behavior to be?  If you have a bad symlink, the expected behavior is to warn you about the bad link, continue syncing, and exit with a non zero RC.  Is that different from the behavior you're seeing?

**Comment by babunatarajan** [comment]
The sync fails when it hits broken soft link.
