### ISSUE TITLE
servicediscovery register-instance help is broken

### ISSUE THREAD

**Issue by wnkz** [aws/aws-cli#3152]
It looks like the help page of the `servicediscovery register-instance` subcommand is making docutils fail.

```
> aws servicediscovery register-instance help
<string>:148: (SEVERE/4) Unexpected section title or transition.

****

<string>:148: (SEVERE/4) Unexpected section title or transition.

****
```

Furthermore, this makes `aws-shell` fail badly (see https://github.com/awslabs/aws-shell/issues/195)

```
> aws --version
aws-cli/1.14.41 Python/3.6.4 Darwin/17.4.0 botocore/1.8.45
```
[debug logs](https://github.com/aws/aws-cli/files/1736675/awscli.log)

**Comment by JordonPhillips** [comment]
Looks like it's struggling with `attributes` for some reason. You can see [in the boto3 docs](http://boto3.readthedocs.io/en/latest/reference/services/servicediscovery.html#ServiceDiscovery.Client.register_instance) that it's messed up there too, though it does render.

**Comment by JordonPhillips** [comment]
Found the issue. The [docs for attributes](https://github.com/boto/botocore/blob/develop/botocore/data/servicediscovery/2017-03-14/service-2.json#L1209) has a weird bit in it: `<p> <b/> </p>`. That section gets translated to rst like so:

```rst
  Supported attribute keys include the following:



   **AWS_ALIAS_DNS_NAME**



   ****



  If you want Route 53 to create an alias record...
```

That empty bolding is the problem. The rst parser doesn't know what to make of it.
