### ISSUE TITLE
'describe-image-attribute --attribute blockDeviceMapping' results in "Unauthorized attempt to access restricted resource" REOPEN #1083

### ISSUE THREAD

**Issue by colin-lyman** [aws/aws-cli#3155]
As Per https://github.com/aws/aws-cli/issues/1083 - this issue is not fixed.

On latest CLI and getting the same issue as previously identified.

**Comment by JordonPhillips** [comment]
As mentioned in the previous issue, there isn't anything the CLI can do about this. This is a server-side error that we can't modify.
