### ISSUE TITLE
preSignedUrl is added when not required on rds create-db-instance-read-replica

### ISSUE THREAD

**Issue by msh100** [aws/aws-cli#3156]
When calling:

```
aws rds create-db-instance-read-replica --db-instance-identifier pro-${IDENTIFIER}-mysql-ro --source-db-instance-identifier pro-${IDENTIFIER}-mysql --db-instance-class db.t2.medium --port 3306 --no-multi-az --option-group-name "default:mysql-5-5" --no-publicly-accessible --storage-type gp2 --monitoring-interval 60 --monitoring-role-arn "arn:aws:iam::${AWSID}:role/rds-monitoring-role" --no-enable-iam-database-authentication --source-region ${REGION}
```

Presents the following:
```
An error occurred (InvalidParameterCombination) when calling the CreateDBInstanceReadReplica operation: Your request does not require the preSignedUrl parameter. Please remove the preSignedUrl parameter and try your request again.
```

This issue is resolved by adding `--pre-signed-url ""` to the end of the command, but it's quite clearly a bug.

Similar issue to https://github.com/aws/aws-sdk-php/issues/1415

**Comment by JordonPhillips** [comment]
That parameter is added when you provide `--source-region`, all you need to do is not specify that parameter. I'll get the docs updated to be more clear on that point.

**Comment by msh100** [comment]
Thanks for the information, although I agree that adding that information to the documentation is a positive and means I won’t need to define the source region, I disagree that this is a solution.

Defining the source region feels like you’re just being more specific with your call, doing so surely shouldn’t break the procedure? Especially when there’s nothing logically wrong with the definition.

**Comment by stobrien89** [comment]
After review of API errors and testing in v1 and v2, it appears the initial reported issue has been resolved.  Documentation has been updated to provide notice of the `--source-region` flag generating a pre-signed url.  Closing for now, but let us know if you have any questions!
