### ISSUE TITLE
#1522 still isn't resolved

### ISSUE THREAD

**Issue by amsheehan** [aws/aws-cli#3161]
See #1522 for a description. It never works on a fresh install of macOS to install aws cli. In the past, the answer has been _shrug_ "sounds like a quirk of the platform."

Well, it's been two years since the last reply to 1522 and it still doesn't work. At some point, I feel aws-cli has to work around the quirks. Please re-open and fix the issue. I shouldn't have to search for 20 minutes to find some random sudo command to cut and paste to install aws cli.

**Comment by JordonPhillips** [comment]
This is not something that any client tool can solve. You can find more details [here](https://github.com/pypa/pip/issues/3165), but the short of it is that System Integrity Protection on some versions of macOS prevents pip from updating the built-in six which is too out of date. This should be fixed as of Sierra.

**Comment by JordonPhillips** [comment]
Another solution, which I generally recommend, is to avoid using the system python where possible. I highly recommend using a more up to date python version, such as what you'll get from homebrew.
