### ISSUE TITLE
output is empty, help to fix it?

### ISSUE THREAD

**Issue by prensoni0143** [aws/aws-cli#3164]
Hi All,

I would like to get the output of below cmd, but it's empty, would you please help?

aws ec2 describe-security-groups | grep "GroupName|FromPort|IpRanges|CidrIp"

My purpose is to get as follow:
1) Get all security groups which has CIDR: 0.0.0.0/0 or/and 10.0.0.0/8

2) Filter the groups out which are pointing to ELB/ALB

3) Get all EC2 instances which has these Security Groups assigned in nice format

**Comment by samx18** [comment]
This not really an issue. 
AWS CLI has the --filter option specifically for this purpose

`aws ec2 describe-security-groups --filters Name=ip-permission.cidr,Values='0.0.0.0/0'`
`aws ec2 describe-instances --filters Name=network-interface.group-name,Values='myDemoSG'`

**Comment by stealthycoin** [comment]
Thanks @samx18 for answering correctly!

**Comment by prensoni0143** [comment]
Thanks. I posted here because I didn't know where else to post and I am new to this form
