### ISSUE TITLE
Registering dynamodb autoscaling target does not set correct ARN

### ISSUE THREAD

**Issue by evanstachowiak** [aws/aws-cli#3165]
aws cli version: 1.14.40

I ran this command: `aws application-autoscaling register-scalable-target --service-namespace dynamodb --resource-id table/dynamodb-table --scalable-dimension dynamodb:table:ReadCapacityUnits --min-capacity 5 --max-capacity 100 --role-arn arn:aws:iam::account:role/custom-role`

However, when I describe the targets I get this:
```
{
            "ServiceNamespace": "dynamodb",
            "ResourceId": "table/dynamodb-table",
            "ScalableDimension": "dynamodb:table:ReadCapacityUnits",
            "MinCapacity": 5,
            "MaxCapacity": 100,
            "RoleARN": "arn:aws:iam::$account_id:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable",
            "CreationTime": 1519647613.21
        },
```

**Comment by stealthycoin** [comment]
This would be a report for the service team since this is a problem with the API. The CLI just calls the APIs we don't have anything to do with the functioning of the service. I would suggest opening a ticket with [AWS Support](https://console.aws.amazon.com/support/home#/).
