### ISSUE TITLE
opsworks update-instance removes EC2 tags

### ISSUE THREAD

**Issue by daisieh** [aws/aws-cli#3166]
When I run `aws opsworks update-instance` to assign an instance to a layer, it seems to overwrite that instance's EC2 tags, like `Name`, if it was set before.

**Comment by stealthycoin** [comment]
This looks like an issue for the Service API, the CLI just calls the service APIs so I don't have any special knowledge about how the service acts. I would suggest contacting [AWS Support](https://console.aws.amazon.com/support/home#/).
