### ISSUE TITLE
Make s3 sync support client-side encryption

### ISSUE THREAD

**Issue by perost-l14** [aws/aws-cli#3168]
Hi. s3 sync is really great. However, I want to use it for backup and for that I need client-side encryption. If I had that, s3 sync would cover my needs and I did not have to complicate matters involving other software. Furthermore, I would know how to restore data from any platform; I.E. not be dependent upon the lifecycle of the backup software.

I envision --cse-c AES256 and --cse-c-key <value> similar to --sse-c and --sse-c-key.

For completeness, I guess --cse-c-copy-source and --cse-c-copy-source-key should be added as well.

**Comment by stealthycoin** [comment]
This is already a feature request for this so I am going to close this issue:
https://github.com/aws/aws-cli/issues/1686 
[uservoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface/suggestions/33168418-supporting-client-side-encryption-when-uploading-d)

**Comment by perost-l14** [comment]
This seem to be back-and-forth between github and uservoice.
Anyone that can provide a status on this?
