### ISSUE TITLE
`aws cloudformation package`  fails with awscli version 1.14.48

### ISSUE THREAD

**Issue by seza443** [aws/aws-cli#3169]
Hello,

I am using CodeBuild to package a cloudformation template.
Since the commit https://github.com/aws/aws-cli/commit/53f650442f9f5d20d479c644f6d31700863d7b31
the command

    aws cloudformation package --template-file API.yml --s3-bucket $TEMPLATE_BUCKET --output-template-file new_API.yml

fails with the following error

    Unable to upload artifact None referenced by CodeUri parameter of GetPolicyUsersFunction resource.
    ZIP does not support timestamps before 1980

I do not have any `CodeUri` anywhere in my template.
`GetPolicyUsersFunction` is a serverless lambda function.

Codebuild use awscli version:

    aws-cli/1.14.48 Python/2.7.6 Linux/4.9.77-31.58.amzn1.x86_64 botocore/1.9.1

On my local machine, running the same command succeed. awscli version is

    aws-cli/1.14.5 Python/2.7.12 Linux/4.4.0-116-generic botocore/1.8.9

Is there a regression of some kind included with the version 1.14.48 of awscli ?

Best regards

**Comment by seza443** [comment]
I solved this issue by upgrading the version of NPM.
On Codebuild, the version was `3.10.3`
upgrading to version `5.6.0` solved this issue.

**Comment by avinashg08** [comment]
I was also getting the error : "Unable to upload artifact None referenced by CodeUri parameter of GetPolicyUsersFunction resource. ZIP does not support timestamps before 1980." 
I also got the same when  using cloud9 ide for deployment. Resolved it by upgrading aws cli:
~$: sudo pip install --upgrade awscli

**Comment by axlrommel** [comment]
I was getting the same errors as above: "Unable to upload artifact None referenced by CodeUri parameter of GetPolicyUsersFunction resource. ZIP does not support timestamps before 1980."

I solved it by upgrading my build environment (node version, CPU and memory)
Upgraded to:
Image . aws/codebuild/nodejs:8.11.0
Environment .  typeLinux
Compute .  7 GB memory, 4 vCPU

**Comment by ShardulKhodankar** [comment]
Hi,

My builds were running fine until now and they suddenly started failing with the same error. I tried using 'aws/codebuild/standard:4.0' and 'aws/codebuild/standard:3.0' but it fails with the same error. I am manually setting the node version to 12 in my buildspec.
