### ISSUE TITLE
ECR get-login produces invalid docker login command [email flag]

### ISSUE THREAD

**Issue by pgrzesik** [aws/aws-cli#3173]
Hello,
today I noticed a problem with `aws ecr get-login` call. Email flag (-e) was deprecated for a while in `docker-login` command, but as of now, it's totally removed and it causes command produced by `aws ecr get-login` to fail with the following:
```
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```
Removing -e flag from produced commands solves the issue. 

awscli version: 1.14.49
docker version: 17.12.0-ce, build c97c6d6

I would love to resolve this issue, so if no one is working on that, let me know and I'll gladly take it.

Regards,
Piotr

**Comment by joguSD** [comment]
We have the `--no-include-email` flag which will remove this from the `-e` flag from the output. However, we can't change the default as we can't make assumptions on what version of docker customers are using and we need to preserve backwards compatibility. 

Let me know if this helps!

**Comment by pgrzesik** [comment]
Thanks a lot for your response @joguSD , seems reasonable to keep it for people that still depend on it, I'm closing the issue. 

Have a good day!
