### ISSUE TITLE
Question: create-identity-provider and provider type cannot be of type Google.

### ISSUE THREAD

**Issue by pawelsocha** [aws/aws-cli#3179]
I want to create Cognito identity provider and I got an error: 

An error occurred (InvalidParameterException) when calling the CreateIdentityProvider operation: Provider NameOfGP cannot be of type Google.

```
aws cognito-idp  create-identity-provider  --user-pool-id id_of_my_user_pool --provider-name NameOfGP --provider-type Google  --provider-details token_url=https://www.googleapis.com/oauth2/v4/token
```

Question is why? Is it related to user pool somehow? Do I miss something?

**Comment by pawelsocha** [comment]
Hi @traviswimer, 

yes, I found a good way ;-)
Name and type must have the same value 'Google'

**Comment by traviswimer** [comment]
Haha thanks. This was driving me crazy. I guess maybe that's their hackish way of preventing you from creating multiple ID providers of the same type.

I wonder if they have a repo for the documentation. Would be nice if they at least documented their ridiculous hacks. haha
