### ISSUE TITLE
aws-cli installation doesnt work using pip on windows

### ISSUE THREAD

**Issue by vasuse7en** [aws/aws-cli#3181]
I have tried installing awscli using pip, anyways with msi installer its working, but i just want to inform you, pip would be convienient for me if people want to write batch files for windows

```
C:\Users\vasubabu.k>python --version
Python 3.6.4

C:\Users\vasubabu.k>pip --version
pip 9.0.1 from c:\users\vasubabu.k\appdata\local\programs\python\python36\lib\site-packages (python 3.6)

C:\Users\vasubabu.k>pip install awscli
Requirement already satisfied: awscli in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages
Requirement already satisfied: colorama<=0.3.7,>=0.2.5 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: botocore==1.9.3 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: docutils>=0.10 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.12 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: PyYAML<=3.12,>=3.10 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from awscli)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from rsa<=3.5.0,>=3.1.2->awscli)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from botocore==1.9.3->awscli)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from botocore==1.9.3->awscli)
Requirement already satisfied: six>=1.5 in c:\users\vasubabu.k\appdata\roaming\python\python36\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.9.3->awscli)
```
later i added aws cli executable to system path

C:\Users\vasubabu.k\AppData\Local\Programs\Python\Python36\Scripts

then i checked for aws command 

```
C:\Users\vasubabu.k>aws
'aws' is not recognized as an internal or external command,
operable program or batch file.
'''

**Comment by dstufft** [comment]
Adding the ``Scripts`` directory to the path is part of the setup of using pip and Python on Windows and there isn't a whole lot AWS CLI can do about it. However, not having `aws` after you added it to the path I believe is wrong. Did you try closing your command prompt after adding to the path and perhaps logging in and out? I forget what Windows requires to update the working``$PATH`` after a change.

**Comment by vasuse7en** [comment]
hello mr donald i have done whatever ever i have mentioned in you docs. Even re opening the command  prompt windows. I wouldnr have raised this issue on github without atleast knowing restarting cli on windows after new installation. anyway you are always welcome to connect to my system to verify. sorry if i troubled you!

**Comment by vasuse7en** [comment]
![image](https://user-images.githubusercontent.com/16218127/37178113-83623ad6-2347-11e8-9983-2be3f083163b.png)
i remember the 6th point

**Comment by matyasforian** [comment]
The issue is that %USERPROFILE%\AppData\Local\Programs\Python\Python36\Scripts points to C:\Users\[USER]\AppData\Local\Programs\Python\Python36\Scripts whereas aws.cmd is at C:\Users\[USER]\AppData\Roaming\Python\Python36\Scripts\aws.cmd So the documentation is wrong, you should add %APPDATA%\Python\Python36\Scripts\aws.cmd (or the PIP installer installs it in the wrong place.)

**Comment by replaysMike** [comment]
I too have this issue on Windows. I have the path set as indicated, C:\Users\{USERNAME}\AppData\Roaming\Python\Python34\site-packages\awscli which is where it was installed. But there is no AWS.cmd on the drive.

I also tried installing using the windows installer MSI package, and it installs AWS.cmd to program files, however the json template handling throws errors and I know there's no issue with the json. Some definite wonkyness going on here.

**Comment by rfschroeder** [comment]
Thansk @replaysMike, it works for me!

**Comment by vikaspro90** [comment]
I used pip for Python 3.4. aws.cmd was found in C:\Users\Vikas\AppData\Roaming\Python\Scripts.
How did I find it? I ran 'pip uninstall awscli' and it showed me all the files it will delete along with the confirmation.

**Comment by drevie** [comment]
@replaysMike same issue for me! weird

**Comment by perfenginner0321** [comment]
Yes, as mentioned by @matyasforian , add the path C:\Users\[user]\AppData\Roaming\Python\Scripts to environment variables and then it works. Worked for me. Thanks

**Comment by ianm4cm** [comment]
I did something similar to perfenginner0321. I found that awsebcli installed in the C:\.....\AppData\Roaming\... while my $PATH for python was C:\.....\AppData\Local\...
I copied the Scripts and site-packages folders from the ...\Roaming\Python\Python37 to the local version and it all is working well now.

**Comment by kdaily** [comment]
Is this still an issue for anyone? Thanks!

**Comment by MrAliMohsin** [comment]
thanks @replaysMike, you saved my life man
