### ISSUE TITLE
describe-instance-status only returns instances with "running" status 

### ISSUE THREAD

**Issue by MattPuzey** [aws/aws-cli#3182]
We are not able to return any instances using `aws ec2 describe-instance-status` other than those which have an instance state of running (code 16). For monitoring purposes we need to retrieve all instances in order to display their status.

The Options described in the docs for `describe-instance-status` state that there are numerous ways to filter on a state (e.g. `stopped`, 80) but we have not been able to retrieve any instances other than those which have a `running` status.
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-status.html

We have not been able to filter on state code:
```
aws ec2 describe-instance-status --filters Name=instance-state-code,Values=80
{
    "InstanceStatuses": []
}
```

We have not been able to filter on state name:
```
$ aws ec2 describe-instance-status --filters Name=instance-state-name,Values=stopped
{
    "InstanceStatuses": []
}
```

We have tested all of the above in scenarios where `stopped` and `terminated` states are present and retrievable via `describe-instances`.

**Comment by joguSD** [comment]
I think you need to provide the `--include-all-instances` flag.
Let me know if that helps!

**Comment by MattPuzey** [comment]
Thanks! that works, it's a shame to have not spotted that in the reference as it's quite clear. Apologies. Out of curiosity, I appreciate the API has to support more use cases than just our own but do you happen to know what the motivation was for this default behaviour? I've seen a couple of threads where others are running into the same problem. I would expect that if you wanted to see the running instances only that you'd just use a filter. Either way you can mark this one as resolved.

**Comment by joguSD** [comment]
@MattPuzey No worries! It caught me up for a second too. Unfortunately, I don't know why the API was designed this way (the APIs themselves are maintained by separate teams). Sorry for not being able to provide anymore context!

**Comment by nkrishne** [comment]
As a newbie struggled for sometime to find the solution for this issue through API.
Thanks @joguSD for giving an hint and i used below Query Parameter in my API call and it worked.
Just posting it here for other newbies like me which may help.
Add Query Parameter:-
"IncludeAllInstances" : "true"

Sample Request:-
https://ec2.amazonaws.com/?Action=DescribeInstanceStatus&Version=2016-11-15&InstanceId=i-0a0123456789az0az&IncludeAllInstances=true
