### ISSUE TITLE
AWS Logs "No Pagination" parameter returns first page only

### ISSUE THREAD

**Issue by ayehia2000** [aws/aws-cli#3184]
Using parameter `-no-paginate` with logs `filter-log-events `, returns only first page, while expecting to return all pages.

example: 

`aws logs filter-log-events     --start-time 1520515827000     --end-time 1520519427000     --log-group-name /aws/lambda/mylambda     --filter-pattern COPYed     --output text    >  logs.txt`

**Comment by dstufft** [comment]
The ``-no-paginate`` flag doesn't control what the service sends back, the service is paginated and there's no way for the CLI to change that. The ``-no-paginate`` flag simply disables the CLI's automatic handling of pagination, so you only get 1 page at a time and you're responsible for manually paginating through the results.
