### ISSUE TITLE
aws s3 cp error with no copy

### ISSUE THREAD

**Issue by yeniugo** [aws/aws-cli#3185]
when i want to copy files from one bullet to other bullet,there with no error,but i can not find the copy file.
this is my commod
`aws s3 mb s3://bucket-name s3://bucket-name`
copy all to another one.and i use the root key,and i dont know why.

**Comment by dstufft** [comment]
I'm sorry but I'm not exactly following what you're asking here. Could you perhaps provide some more detail about what you're doing, what you expected it to do, and what it actually did? If there is a traceback that was generated, please include that as well.

**Comment by yeniugo** [comment]
i want copy all the files from one bucket to another one,and i use the command there.but i dont know why it can not work here.

**Comment by v-sukt** [comment]
hi did you try sync? 
` aws s3 sync s3://bucket-name s3://bucket-name`
`aws mb` is to create buckets. Please try this and share if you get any errors or any traceback

**Comment by yeniugo** [comment]
i have set sync the two bucket,but the first one have some files,and the second one is empty.and i need to copy the file from the first to the second.

**Comment by yeniugo** [comment]
thank you very much,and i copy all the file.and i only have a litte file.

**Comment by justnance** [comment]
@yeniugo - please advise if the copy worked as expected or if there were any any errors.  Thanks.
