### ISSUE TITLE
cannot add alarmidentifier using cli

### ISSUE THREAD

**Issue by DuckDagobert** [aws/aws-cli#3188]
in route53 
https://docs.aws.amazon.com/cli/latest/reference/route53/create-health-check.html
my json:
{
"Port": 443,
"Type": "HTTPS_STR_MATCH",
"ResourcePath": "blabla",
"FullyQualifiedDomainName": "test.example.com",
"SearchString": "healthcheck",
"RequestInterval": 30,
"FailureThreshold": 3,
"MeasureLatency": false,
"Inverted": false,
"EnableSNI": true,
"Regions": ,
"AlarmIdentifier": {
"Region": "us-east-1",
"Name": "Route53 Server Offline Alert"
},
"InsufficientDataHealthStatus": "Healthy"
}

I get this error:
An error occurred (InvalidInput) when calling the CreateHealthCheck operation: Invalid parameter : Basic health checks must not have an metric region specified.
when I leave the AlarmIdentifier away it works without issue. I can manually (GUI) create this exact health check without any issues.

What's wrong here?

**Comment by dstufft** [comment]
The CLI is forwarding the CreateHealthCheck command to the Route53 service.  The response you're seeing is just what the Route 53 service is returning back to us. I'd suggest moving this to stackoverflow, as suggested in our ["Getting Help" section](https://github.com/aws/aws-cli#getting-help) of our README.  It will reach a wider audience of people that may be able to answer your question.
