### ISSUE TITLE
S3 sync does not allow specification of file metadata headers e.g content-encoding

### ISSUE THREAD

**Issue by ratpik** [aws/aws-cli#319]
Uploading to S3 by using the aws s3 sync should have an option to specify the headers for that request. Right now there doesn't seem to be any way to upload gzipped content and expect it to have the appropriate metadata

--add-header='Content-Encoding: gzip'

**Comment by revolunet** [comment]
Where is the "interactive help page" please ?
Can someone confirm we can set Cache-Control headers using sync ? (i need to set Expiration headers)

**Comment by revolunet** [comment]
ok using sync : `aws s3 sync --acl public-read --cache-control "max-age=3600" --expires 2100-01-01T00:00:00Z  /path/to/images s3://bucket/images`

**Comment by makmanalp** [comment]
Note for posterity, if you have issues with metadata headers not updating on sync, see #1145 and potentially #319

**Comment by bruno-rossi-movile** [comment]
How can I download a file that is in Content-Encoding = gzip ?  
# cat test.json 
��zl��i�4fv�����s�|6�C>����+�ݺ>�EDh�0��0�s�mU��R��]�B66Ļ�)�T��}�>@
is impossible to read, because has Content-Encoding = gzip.
I need make a sync from bucket to local , but all filies in bucket is in gzip, can I download with unzip ?

**Comment by AlexeyPanda** [comment]
Hi, how I can find the object to metadata  in aws CLI.

**Comment by ptsteadman** [comment]
I have the same problem as Bruno, `aws s3 sp s3://<bucket>/<file> .` results in a gzipped file.  Unzipping the file confirms that the file is not corrupt.  I tried added `--content-encoding 'gzip'` but it did not help.

**Comment by monty241** [comment]
It is great that content-encoding can be set, but transparant on the fly zip/unzip would even be better. Now you always have to pre-process the files, whereas in many scenarios it could be done during the sync (and with twice the threads maybe even as fast).

**Comment by yvele** [comment]
That's why I created https://github.com/yvele/poosh which allow a metadata configuration file based on glob patterns:

```js
{
  plugins : ["s3"],
  baseDir : "./deploy",
  remote  : "s3-us-west-2.amazonaws.com/my-bucket",

  each: [{
    headers   : { "cache-control": { cacheable: "public" } }
  }, {
    match     : "**/*.{html,css,js}",
    gzip      : true,
    headers   : { "cache-control": { maxAge: "48 hours" } }
  }, {
    match     : "**/*.{jpg,png,gif,ico}",
    gzip      : false,
    headers   : { "cache-control": { maxAge: "1 year" } }
  }, {
    match     : "**/*.html",
    priority  : -1
  }]
}
```

I wish AWS add more control over headers while using `aws s3 sync`

**Comment by akotranza** [comment]
WholeFoods later this is still an unmitigated disaster. When using the CLI to COPY or SYNC from an s3 source to an s3 destination it *should* (with no extra parameters or caveats about multipart uploads) copy the metadata. How is this too much to ask?
