### ISSUE TITLE
Bundle install is broken with python 2.6 due to dateutil

### ISSUE THREAD

**Issue by thebearmayor** [aws/aws-cli#3196]
Installing from the bundle per [these docs](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html) is currently broken with python 2.6. [awscli-bundle.zip](https://s3.amazonaws.com/aws-cli/awscli-bundle.zip) contains python-dateutil-2.7.0.tar.gz which is not compatible with python 2.6. See [here](https://pypi.python.org/pypi/python-dateutil/2.7.0).

**Comment by joguSD** [comment]
I've confirmed this.
I've opened up a pull request to make the versioning requirements more strict here:
https://github.com/boto/botocore/pull/1402

**Comment by thebearmayor** [comment]
Thanks for the link to the previous version!

**Comment by b-dean** [comment]
Also, it seems to work fine if you replace the `packages/python-dateutil-2.7.0.tar.gz` with [python-dateutil-2.6.1.tar.gz](https://pypi.python.org/packages/54/bb/f1db86504f7a49e1d9b9301531181b00a1c7325dc85a29160ee3eaa73a54/python-dateutil-2.6.1.tar.gz)

**Comment by joguSD** [comment]
This should be fixed as of version 1.14.55.

**Comment by b-dean** [comment]
Just curious, what in 1.14.55 makes this not a problem? I was looking at [the diff between 1.14.55 and 1.14.53](https://github.com/aws/aws-cli/compare/1.14.53...1.14.55), expecting to see something about python-dateutil, but I didn't.

**Comment by thebearmayor** [comment]
@b-dean the change was in botocore, see the PR joguSD referred to, boto/botocore#1402, and other related PR's.
