### ISSUE TITLE
aws lambda invoke filter outfile

### ISSUE THREAD

**Issue by 141984** [aws/aws-cli#3198]
Hi,
Is it possible to filter the contents being written to the outfile? If possible, how :)

**Comment by joguSD** [comment]
Could you provide a little more detail on specifically what kind of filtering you're trying to do?

**Comment by 141984** [comment]
The outfile file being written as a  result of the aws lambda invoke command has  quite a lot of fields in it. It would be nice to be able to filter out what gets written in the outfile, like --query option

**Comment by stealthycoin** [comment]
This is currently not possible. I can mark it as a feature request.

**Comment by 141984** [comment]
thank you, that would be great
