### ISSUE TITLE
Repositories for AWS tools

### ISSUE THREAD

**Issue by mhalano** [aws/aws-cli#3201]
Sorry if I asking this question again. I searched on past issues but didn't find anything. The idea is create repositories for Debian/Ubuntu and RHEL/Fedora/Centos. Google alrady did this for it's 'gcloud' tool. Would be nice has the latest release of the tool automatically.

**Comment by kyleknap** [comment]
I could not find an open issue related to this, but it seems reasonable to me. Marking as a feature request.

**Comment by mhalano** [comment]
Any news about that? Azure and Google seem to have repositories with very updated versions of the tools. I checked for aws-cli in the Ubuntu repository and in Snap repository and they are quite old versions.

**Comment by stobrien89** [comment]
Hi @mhalano, 

Thanks for reaching out!  I don't believe we'll be creating repositories (but don't hold me to that), but we are actively working on a [source distribution](https://github.com/aws/aws-cli/pull/6352), which should alleviate some issues with packaging by helping distribution maintainers make the AWS CLI v2 available through standard package managers.  We want to condense our issues related to packaging so we have a single place to track this, so please keep an eye on #5282 for any updates!

**Comment by mhalano** [comment]
There is any evolution about this issue?
