### ISSUE TITLE
aws cloudformation list-exports should accept a filter --export-names

### ISSUE THREAD

**Issue by yangmillstheory** [aws/aws-cli#3206]
A useful feature in CloudFormation is the ability for Stacks to export values: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html. These values can be named so other stacks can consume them via the `!ImportValue` directive in their templates.

The [`list-exports`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/list-exports.html) subcommand of `aws cloudformation` lists all exported values that you can import into other stacks (i.e. "named" exports), and is a paginated operation. 

**Currently it's onerous for the caller to get a finite number of exports by name**. I believe getting a single export by name can possibly be done with `--query`, but for multiple exports I usually have to write a Python script to walk the paginated API and manually gather the exports by name.

Instead of putting this burden on the user, we should provide an option `--export-names` that spits out the information for the given export names.

Note that I've filed a ticket with AWS support to provide a filter for the ListExports API; if that ever happens, we can change the implementation, but it'd be one place to change (here), and users wouldn't be affected.

***

If maintainers agree that we should have this in the tool, I'm happy to do the work.

**Comment by JordonPhillips** [comment]
While that does sound useful, I would prefer that we keep this command as close to the api as possible. Getting the feature on the service side will let all customers use it, not just CLI customers. I'll forward this feedback along to the service team. Thanks!

**Comment by garretwilson** [comment]
For those stumbling into this ticket, indeed the `--query` to retrieve an exported value is not so onerous; it looks like this:

```bash
aws cloudformation list-exports [--profile <profile>] [--region <region>] --query 'Exports[?Name==`<export-name>`].Value' --output text --no-cli-pager
```

This uses a [JMESPath](https://jmespath.org/) expression. Just substitute the export name in place of `<export-name>`. The profile and region are optional. I added `--no-cli-pager` out of an abundance of correctness; hopefully the CLI won't be paging a single line anyway.

I agree that the AWS CloudFormation team likely has an immense number of new features in the queue, and that there is only a tiny relative value in spending time on implementing this shortcut, as the functionality can be replicated by a query. However if might be of benefit to add the specific query to the CLI documentation as an example.
