### ISSUE TITLE
datapipeline error when 3 params with same id in CLI args, PR included

### ISSUE THREAD

**Issue by fffergal** [aws/aws-cli#3217]
Hello,

When using the datapipeline commands, if you pass a list parameter value by specifying the same parameter id 3 times with different values, there is an error. 1 or 2 values with the same id work fine.

Example:
```
aws datapipeline activate-pipeline --pipeline-id df-0864740YN3DQ8BJXV0R --parameter-values myConversionsDates=2018-01-01 myConversionsDates=2018-01-02 myConversionDates=2018-01-03
```

A workaround is to use a file to pass parameters instead.

I made a PR to fix and test the problem #3177.

If there is anything else I can do to help, please let me know.

**Comment by stealthycoin** [comment]
I took a quick look at the PR and flagged it as needing another reviewer. I'll close this in favor of the PR.

**Comment by fffergal** [comment]
Sounds good. Thank you.
