### ISSUE TITLE
Feature Request: S3 Sync to provide a dryrun / live-run output in addition to stdout

### ISSUE THREAD

**Issue by rmmeans** [aws/aws-cli#3220]
It would be ideal if the `s3 sync` command followed the other library conventions for output (text, table, json). The command appears to only be printing to stdout saying what it did during the run and doesn't provide any output at all (which is still very useful, especially when running syncs that take hours!)

Ideally, everything it printed to the stdout would also be available in an output form as well instead of not outputting anything. This would allow you to write programs around the CLI to capture what it did (or will do, if using dry run) and work with those sync results in your own script.

Workaround for now would be to pipe the stdout to a file and then parse that, but since it not a defined contract (just text strings), it's not a very ideal thing to build logic off of vs something like a JSON output.

**Comment by kyleknap** [comment]
Seems reasonable to me. Marking as a feature request.
