### ISSUE TITLE
AWS cli not updated to use serviceRegistries

### ISSUE THREAD

**Issue by dileep-p** [aws/aws-cli#3222]
#aws ecs create-service --service-name ecs-service-discovery --launch-type FARGATE --platform-version 1.1.0 --cli-input-json file://test.json

Parameter validation failed:
Unknown parameter in input: "serviceRegistries", must be one of: cluster, serviceName, taskDefinition, loadBalancers, desiredCount, clientToken, launchType, platformVersion, role, deploymentConfiguration, placementConstraints, placementStrategy, networkConfiguration, healthCheckGracePeriodSeconds

**Comment by naydencho** [comment]
The same happens in `aws ecs update-service --cluster my_cluster --service my_service --region us-east-1 --cli-input-json file://service-definition.json`

Parameter validation failed:
Unknown parameter in input: "serviceRegistries", must be one of: cluster, service, desiredCount, taskDefinition, deploymentConfiguration, networkConfiguration, platformVersion, forceNewDeployment, healthCheckGracePeriodSeconds

version 1.14.64

**Comment by jamesls** [comment]
I believe you just need to upgrade to the latest version of the CLI.  I'm seeing that parameter in version 1.14.59:

```
$ aws ecs create-service help  | grep 'service\-registries'
          [--service-registries <value>]
```
