### ISSUE TITLE
non-reproducible sync errors between s3 buckets

### ISSUE THREAD

**Issue by jhoblitt** [aws/aws-cli#3227]
I have a daily job that makes point in time copy of an s3 bucket into another s3bucket with a timestamp prepended to the object keys.  The source bucket has a total size of around 700GiB and a sync takes ~2 hours to run.

Eg.
```
aws s3 sync s3://mybucket s3://mybucket-backup/daily/YYYY/MM/DD...
```

The `sync` occasionally produces random, non-repeatable, errors -- which has been persisting for months across multiple different versions of `awcli``.  This error message from yesterday is from `1.14.61`:

```
copy failed: s3://****/stack/redhat/el7/devtoolset-6/miniconda3-4.3.21-10a4fa6/log4cxx-0.10.0.lsst7@Linux64.tar.gz to s3://****/daily/2018/03/29/2018-03-29T11:52:05Z/stack/redhat/el7/devtoolset-6/miniconda3-4.3.21-10a4fa6/log4cxx-0.10.0.lsst7@Linux64.tar.gz An error occurred (InvalidArgument) when calling the UploadPartCopy operation: Range specified is not valid for source object of size: 17601350
```

I'm at a bit of a loss as to how to debug this further due to the random nature and inability to reproduce the failures.  I don't even know if this is a bug in `awscli` or a s3 service side problem.

Has anyone else seen this failure mode?

**Comment by kyleknap** [comment]
@jhoblitt Seems like a concurrency problem to me. Specifically, do you know if there are any other processes changing the objects in your source bucket as you are preforming the `sync`? If that is the case, I would guess that is the problem. The `s3` commands in general cannot handle mutation of the source objects during a transfer command.

**Comment by jhoblitt** [comment]
@kyleknap Hmm -- that hadn't occurred to me but I suppose it is possible that the object being copied might be in the process of being written. I'll see if some external locking makes the errors go away.  Thank you for the suggestion!

**Comment by stealthycoin** [comment]
Let us know if there is anything else needed from us.

**Comment by jhoblitt** [comment]
I'm about 90% convinced that the problem was being caused by objects being written during a sync, as suggested by @kyleknap, so I'm going to close this out.  Thanks again.

**Comment by stealthycoin** [comment]
Glad that worked for you.
