### ISSUE TITLE
Error message is missing go1.x

### ISSUE THREAD

**Issue by markusvanlaak** [aws/aws-cli#3229]
Hi, I try to create a lambda function and mad typo on --runtime g1.x.
The error message was saying:

An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value 'g1.x' at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, nodejs, nodejs4.3, nodejs6.10, python2.7, python3.6, dotnetcore1.0]

I was confused as go1.x was mssing in the message. 
Only a very small thing but would help to complete the message with all runtimes.

Regards,
Markus

**Comment by jamesls** [comment]
Hi, those specific error messages come from lambda service itself, we're just echoing them back to you.  I would recommend letting the service team know about this on their forums https://forums.aws.amazon.com/forum.jspa?forumID=186.

Let me know if you have any other questions.
