### ISSUE TITLE
aws batch submit-job double quotes escape character not working

### ISSUE THREAD

**Issue by nithinvenugopal** [aws/aws-cli#3230]
Hi,
I am trying to run the batch submit job api with command as below. I am getting parsing error.

aws batch submit-job --job-name xxx --job-queue xxx --job-definition xxxx:1 --retry-strategy attempts=1 --container-overrides vcpus=2,memory="4000",command=["/bin/sh","-c","mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-xxxxx.efs.us-xxxx-1.amazonaws.com:/ efs && runuser -l user -c \"csh /efs/program.csh\""]

Error: Error parsing parameter '--container-overrides': Expected: ',', received: '"' for input:

So commands like runuser and su need to have command within " or '. But I am not able to escape this with backslash(\) in this case.

Thanks,
Nithin

**Comment by jamesls** [comment]
For cases like this, especially when you start needing to escape quotes within a string, I would recommend switching to the JSON input, either via `--generate-cli-skeleton` or just as a JSON parameter for `--container-overrides`.  This should version should work:

```
aws batch submit-job --job-name xxx --job-queue xxx --job-definition xxxx:1 --retry-strategy attempts=1 \
  --container-overrides '{"vcpus": 2, "memory": 4000, "command": ["/bin/sh","-c","mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-xxxxx.efs.us-xxxx-1.amazonaws.com:/ efs && runuser -l user -c \"csh /efs/program.csh\""]}'
```

Let me know if you're still having issues.

**Comment by nithinvenugopal** [comment]
Yes, as JSON parameter works! Thanks James.
