### ISSUE TITLE
aws ecs dumps the complete JSON with malformed JSON

### ISSUE THREAD

**Issue by vikasrohit** [aws/aws-cli#3234]
If we pass malformed JSON in following command
`aws ecs register-task-definition --cli-input-json "$task_def"`
it would dump the complete JSON on console which is actually a security issue, if the task definition contains sensitive information configured via env variables specially when command is run in a build hosted in public cloud.

**Comment by vikasrohit** [comment]
Thanks for the response @kyleknap. Yes, that is possible, I guess. However, I think as task definition always contains environment variables so aws ecs command should not dump the actual JSON in any case. By default it should hide the JSON in error and may be a flag/switch can allow users to view the JSON when there is an error.

**Comment by justnance** [comment]
@vikasrohit - Thanks for your feedback.  I am marking this issue as a feature request pending further review.

**Comment by vikasrohit** [comment]
@justnance just curious if this has been fixed.
