### ISSUE TITLE
Unable to install on Mac

### ISSUE THREAD

**Issue by rahul003** [aws/aws-cli#3237]
Hi,

I've spent a lot of time towards installing awscli for mac and failed. How do I go about doing this?
This is the error I get when I try to run it.
```
huilgolr$ aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 58, in main
    driver = create_clidriver()
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/clidriver.py", line 69, in create_clidriver
    event_hooks=emitter)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/aws/lib/python2.7/site-packages/awscli/plugin.py", line 58, in _import_plugins
    plugins.append(__import__(path))
ImportError: No module named botocore_amazon
```

**Comment by JordonPhillips** [comment]
How did you install? Do you have a `[plugins]` section in your `~/.aws/config` file?

**Comment by rahul003** [comment]
I did `pip install awscli` 
Then I tried the awscku bundle. `sudo /usr/local/bin/python2.7 awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws` like this. I tried with python2 as well as python3. I installed python3 with brew. 

Even when I install it for python3 it shows me the above error whose trace has python2.7 for some reason.

Yes I have a plugins section
```
[plugins]
amazon = botocore_amazon
```

**Comment by rhcarvalho** [comment]
This is similar to #2159.

As a workaround, if the plugin is not installed on the same Python where aws-cli is installed, you can either:

- Update you ~/.aws/config to remove the reference to the plugin; or
- Apply the patch from: https://github.com/aws/aws-cli/pull/3242

I've been using the patch for some time to allow me to have a plugin referenced in my config without breaking `aws-cli` when the plugin is not installed.
