### ISSUE TITLE
A CloudFormation stack that can be deployed, but not validated

### ISSUE THREAD

**Issue by galaxy4public** [aws/aws-cli#3238]
There is some kind of an issue with AWS CLI (cloudformation validate-template) which fails to validate a [valid CloudFormation YAML stack](https://gist.github.com/galaxy4public/2bded4c2235bee2a0cea0a7ed4072479):
```
$ aws cloudformation validate-template --template-body badges.template 

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: unsupported structure.
Exited with: 255
```
At the same time you can successfully deploy that stack with `deploy`:
```
$ aws cloudformation deploy --template-file badges.template --stack-name badges1 --capabilities CAPABILITY_IAM

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - badges1
```
I believe the validation logic is in the wrong here :)  The offending template is in the Gist linked in the first line of this issue.

**Comment by JordonPhillips** [comment]
The difference here is between the parameters. `--template-file` takes a file name while `--template-body` expects the file contents. You would need to use `file://` to load the file contents like so:

```
$ aws cloudformation validate-template --template-body file://badges.template
```

**Comment by galaxy4public** [comment]
I feel so dumb :-/ .  Thank you for pointing out my mistake!
