### ISSUE TITLE
aws acm-pca list-certificates

### ISSUE THREAD

**Issue by firedbeer** [aws/aws-cli#3243]
In acm, we can use list-certificates to get a full list of all certificates. It seems this feature is not supported yet in the new Private CA support.  My aws cli version is 1.15.1

**Comment by JordonPhillips** [comment]
Thanks for the feedback, I've forwarded it on to the service team. I'll update this issue when I hear back.

**Comment by JordonPhillips** [comment]
Sounds like the intent is for customers to fully manage the certs with acm-pca. You can gather a list of certificates issues by creating an audit report, which will include every cert issued by the ca. I've passed on the feedback that this is a bit of a sharp edge. I would recommend either opening support cases or posting on their forum if you would like to see this feature, as every reported use case adds weight to the request.

**Comment by joaco-espinosa** [comment]
> Thanks for the feedback, I've forwarded it on to the service team. I'll update this issue when I hear back.

I'm guessing you still haven't heard back from the service team. Can you provide any additional information regarding this request?

**Comment by omahn** [comment]
@JordonPhillips What was the response from the service team? This remains an issue today several years ago. Our use case involves applications in isolated (no outbound access) subnets. ACM doesn't provide a VPC endpoint so there's no way to list the available certificates from this application. The only remaining option is the audit report, but that is unsuitable for provisoning certificates on-demand as it runs in the background and dumps the output to S3.
