### ISSUE TITLE
cloudformation describe  stacks report different response depending on if stack name is supplied

### ISSUE THREAD

**Issue by etsangsplk** [aws/aws-cli#3247]
Log issue for @kapil
i'm starting to see at least one of the testing issues here is due to the api, the aws api is a bit broken wrt to its own documentation, per the docs, stack protection status should be reported by describe stacks, but i've created a protected stack, and it doesn't report the status unless one describes a single stack in isolation.

$ aws cloudformation describe-stacks
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-2:11112222:stack/mytopic/7efb2d40-3a5d-11e8-8c44-500cef930ce6",
            "StackName": "mytopic",
            "CreationTime": "2018-04-07T12:16:27.160Z",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Tags": []
        }
    ]
}
$ aws cloudformation describe-stacks --stack-name mytopic
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-2:11112222:stack/mytopic/7efb2d40-3a5d-11e8-8c44-500cef930ce6",
            "StackName": "mytopic",
            "CreationTime": "2018-04-07T12:16:27.160Z",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Tags": [],
            "EnableTerminationProtection": true
        }
    ]
}

**Comment by stealthycoin** [comment]
This looks like it would be an issue to open with[AWS Suppport](https://console.aws.amazon.com/support/home#/). This repo is for the CLI, we don't have any special knowledge about CloudFormation or influence with them so this isn't the correct place for this issue.
