### ISSUE TITLE
ONEZONE_IA should be an allowed parameter to --storage-class

### ISSUE THREAD

**Issue by jmillerdesign** [aws/aws-cli#3252]
I'm using CLI v1.15.2 and according to the [docs](https://docs.aws.amazon.com/cli/latest/reference/s3api/copy-object.html), `ONEZONE_IA` is one of the allowed parameters to `--storage-class`, yet when I use it, I get the error:

```
aws: error: argument --storage-class: Invalid choice, valid choices are:

STANDARD                                 | REDUCED_REDUNDANCY
STANDARD_IA
```

**Comment by liltechdude** [comment]
I am also seeing this issue with v1.15.4
```
$ aws --version
aws-cli/1.15.4 Python/2.7.12 Linux/4.4.0-43-Microsoft botocore/1.10.4

$ aws s3 mv s3://s3-*** s3://s3-*** --storage-class ONEZONE_IA

aws: error: argument --storage-class: Invalid choice, valid choices are:

STANDARD                                 | REDUCED_REDUNDANCY
STANDARD_IA
```

**Comment by stealthycoin** [comment]
Ah looks like a new storage class came out. I'll take a look and see if it works with all the `s3` subcommands.

**Comment by t4ec** [comment]
Hello,

Any updates? Just came across it and it is dissapointing to have no ability to just set ONEZONE_IA on upload instead of setting up bucket policies which probably makes it even more expensive.
