### ISSUE TITLE
docker login doesn't work. Error message is "The user name or passphrase you entered is not correct."

### ISSUE THREAD

**Issue by 99** [aws/aws-cli#3264]
Hi,

I'm running command eval $(aws ecr get-login --region <my-region> --no-include-email) and I'm receiving below error: 
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `The user name or passphrase you entered is not correct.`
```

**aws --version**: aws-cli/1.14.60 Python/3.6.5 Darwin/17.4.0 botocore/1.9.13
**docker --version**: Docker version 18.03.0-ce, build 0520e24
MacOS High Sierra (10.13.3)

Would like to know why this error is occurring and how do I fix it? I tried to research here in aws docs, it but no luck 

Thank you,
99

**Comment by dennislky** [comment]
Try opening Keychain Access
Right-click on the login keychain 
Lock it and then unlock it again

**Comment by 99** [comment]
thank you @dennislky but that didn't help :( . I don't use keychain access

**Comment by mfornasa** [comment]
Well, it worked for me! What is the reasoning behind that?

**Comment by JordonPhillips** [comment]
Looks like there may be a bug in the osx keychain credential helper in docker on newer versions of osx: https://github.com/docker/docker-credential-helpers/issues/65

Some have said that rebooting solves the problem. Some have said that removing that credential helper fixes it, though I would highly suggest trying other avenues before you do that.

It doesn't appear that this is a CLI issue though. If you find more info then let us know.

**Comment by 99** [comment]
@JordonPhillips made it work after reboots, restarts, reinstall, etc . Have no idea what fixed it. So not much here to share.( But I have 2 more co-worker who just got their laptops and hit the same problem) 
I think we can close this ticket not much here

**Comment by dinamic** [comment]
@99 feel free to close it then :)

**Comment by wahengchang** [comment]
Edited:
Removing "credsStore": "osxkeychain" from ~/.docker/config.json instead.

**Comment by rdonkin** [comment]
@dennislky comment at https://github.com/aws/aws-cli/issues/3264#issuecomment-381478869 worked for me on macOS 10.13 with Docker 19.03.8.  Simplest solution I've seen, tried various other options including editing ~/.docker/config.json

**Comment by jfortier** [comment]
I ran into this issue, and no matter amount unlocking/locking of the keychain, or deleting lines from ~/.docker/config.json worked for me. Apparently if you're using a terminal remotely (which I do between my macs) you need to run `$ security unlock-keychain` which is the equivalent of opening your keychain (but it works remotely). Helpful for anyone who runs into this issue and would like to script around it!

Hope that helps someone in the future!

**Comment by punitpandey** [comment]
For those who are not on mac and/or changes with keychain did not helped. 
**Removing "credsStore" and "credHelpers" nodes from docker config file will do the magic. You can delete the .docker/config.json file as well.**
