### ISSUE TITLE
Feature Request: support List V2 in the AWS S3 high level commands

### ISSUE THREAD

**Issue by AndrewAWS** [aws/aws-cli#3266]
The high level S3 commands (sync, cp) use the [GET Bucket (List Objects) Version 1](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) API. 
This was revised to [GET Bucket (List Objects) Version 2](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html)

While the low level S3api commands can use List V1 and V2 the high level commands only support List V1.

**Comment by skwslide** [comment]
+1 As a heavy user of S3, I can attest that the V2 API is much faster and robust than V1.

**Comment by kyleknap** [comment]
Closing this issue. It was updated with this PR: https://github.com/aws/aws-cli/pull/3549
