### ISSUE TITLE
EOF occurred in violation of protocol (_ssl.c:661)

### ISSUE THREAD

**Issue by anijmlt** [aws/aws-cli#3268]
On using any aws cli commands I get this message.
> aws ec2 describe-instances --filter "Name=tag:Billing by Role,Values=*"
EOF occurred in violation of protocol (_ssl.c:661)

I have already completed aws configure. Here my software and OS versions:
_$ aws --version_
aws-cli/1.15.4 Python/2.7.14 Linux/4.13.0-36-generic botocore/1.10.4
_$ python -c "import ssl; print ssl.OPENSSL_VERSION"_
OpenSSL 1.0.2n  7 Dec 2017
OS : 16.04.1-Ubuntu

This has never worked for me before this, unlike[ this issue.](https://github.com/aws/aws-cli/issues/3254)

**Comment by JordonPhillips** [comment]
Do you have proxies configured? How about a custom ca bundle?

**Comment by anijmlt** [comment]
Hello,
I found the solution to my issue. Default region name in aws configure was set to "us-east-1b". When changed to "us-east-1", I have no more issues.
When running awscli commands in --debug mode when using the wrong region name, I see that the host that was being contacted was iam.us-east-1a.amazonaws.com, whereas with region name = us-east-1 host being contacted is iam.amazonaws.com.
I am closing the issue.
