### ISSUE TITLE
Please add AWS::StepFunctions::StateMachine DefinitionString to cloudformation package supported artifacts

### ISSUE THREAD

**Issue by vombor** [aws/aws-cli#3270]
https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

Please allow externalizing of DefinitionString property in a StepFunction resource the same way CodeUri works for lambda. I would like to maintain a states.json file outside of the template and have 'aws cloudformation package' upload it to s3 as an artifact and transform the template to use an s3 file include for the value of that property.

**Comment by aliniacobv** [comment]
One possible solution could be to use [AWS::Include Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html). Example:
```
 DefinitionString:     
   Fn::Transform:
     Name: AWS::Include
     Parameters:
       Location: 
         Fn::Sub: 's3://yourbucket/stepfunctiondefinition.json'
```
However, there's still something I'm missing, as CF returns error - 'Property validation failure: [Value of property {/DefinitionString} does not match type {String}]'.

I've seen the example with using the intrinsic function Join:
```
DefinitionString: |-
   {
     "StartAt": "HelloWorld",
     "States": {
       "HelloWorld": {
         "Type": "Task",
         "Resource": "arn:aws:lambda:us-east-1:111122223333:function:HelloFunction",
         "End": true
       }
     }
   }
```
and that works. 
But how does one combine the two, to make it both reference an external definition, but also interpret that as a String?
Is there someone ar AWS that can give a statement on this?
Thank you.

**Comment by vombor** [comment]
Thanks for the reply. I've been able to successfully load the definition string externally using cloudformation custom resources, and I have a functioning workaround.

To be clear, this request is for DefinitionString to be supported for the specific cli method "aws cloudformation package" so the source json file can be published automatically to S3 and an artifact and the template transformed to automatically use that artifact, the same as CodeUri does for Lambda functions via the Serverless transform.

**Comment by aliniacobv** [comment]
I was a bit off topic, indeed, sorry for that. 
Are you saying you're using a lambda custom resource for the workaround you mentioned? Can you please give more details about the setup?
Thank you.

**Comment by JordonPhillips** [comment]
This would be a feature request for [awslabs/serverless-application-model](https://github.com/awslabs/serverless-application-model). Since `package` follows that spec, we would need to have it supported there first.

**Comment by bpg** [comment]
Hi @vombor , could you please share an example of your workaround?

**Comment by bpg** [comment]
Actually, got it from https://github.com/aws-samples/lambda-refarch-imagerecognition/blob/master/cloudformation/image-processing.serverless.yaml.
You'll need to run a python pre-processor to build the final template file.

**Comment by akanshajain1** [comment]
> Thanks for the reply. I've been able to successfully load the definition string externally using cloudformation custom resources, and I have a functioning workaround.
> 
> To be clear, this request is for DefinitionString to be supported for the specific cli method "aws cloudformation package" so the source json file can be published automatically to S3 and an artifact and the template transformed to automatically use that artifact, the same as CodeUri does for Lambda functions via the Serverless transform.


Hi @vombor, could you please share an example of this?
