### ISSUE TITLE
[Feature Request] Renaming Files in S3 Buckets

### ISSUE THREAD

**Issue by kushagrasahni93** [aws/aws-cli#3275]
Currently as per AWS S3 docs, in order to rename an object, we have to use two API Calls, copyObject, and deleteObject.

It would be great if we could achieve the same in one API Call itself.Thereby saving Network Transactions to S3 too.

**Comment by dstufft** [comment]
Hi there, thanks for reaching out.

Unfortunately this repository is for the CLI, which can only consume the existing APIs not add new ones to the services themselves. The best way to ask for features for the S3 service is to post on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).
