### ISSUE TITLE
Support T2 "Unlimited" in AutoScaling::LaunchConfiguration

### ISSUE THREAD

**Issue by kastork** [aws/aws-cli#3276]
This is a feature request to provide a way to ask for T2-Unlimited in a Cloud Formation  LaunchConfiguration.

When launching a T class instance directly from the CLI, you can get the "Unlimited" cpu credit model by mentioning it in a `CreditSpecification` field.

```
"CreditSpecification": {
    "CpuCredits": "unlimited"
}
```

But when using Cloud Formation you can't.  `AWS::AutoScaling::LaunchConfiguration` has no direct way to ask for an Unlimited instance.

**Comment by dstufft** [comment]
Hey there, this isn't something that the CLI actually has any control over. This would be a feature request for the AWS Auto Scaling team, which yo can file over at the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=291). Thanks!

**Comment by nathanwebsterdotme** [comment]
For anyone else looking at this, you need to use AWS::EC2::LaunchTemplate instead of AWS::EC2::LaunchConfiguration

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html

**Comment by pierrefevrier** [comment]
Have a look to the new EC2 T3 instances, unlimited CPU is activated by default at price a little less expensive than T2 instances: https://aws.amazon.com/fr/ec2/instance-types/t3/

**Comment by brainframe-me** [comment]
You could also just add this to the UserData (yml cloudformation syntax here):

      UserData: 
        'Fn::Base64': !Sub |
          #!/bin/bash
          yum install -y aws-cli
          instanceid=`curl http://169.254.169.254/latest/meta-data/instance-id`
          aws ec2 modify-instance-credit-specification --region eu-central-1 --instance-credit-specification '[{"InstanceId": "'"$instanceid"'","CpuCredits": "unlimited"}]'
