### ISSUE TITLE
aws ec2 create-tags throws a false positive error

### ISSUE THREAD

**Issue by tejasvi5** [aws/aws-cli#3283]
`aws ec2 create-tags --resources $INSTANCE_ID --tags Key="Name",Value=$TAG_Name`

An error occurred (InvalidParameterValue) when calling the CreateTags operation: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty._

_"Name" is not null and non-empty. Both variables $INSTANCE_ID and $TAG_Name are valid; and not null and non-empty_

**Comment by dstufft** [comment]
I believe if you do ``--tags "Key=Name,Value=$TAG_NAME"`` this will likely work.

**Comment by tejasvi5** [comment]
Thanks, that worked.

**Comment by sandygvs** [comment]
@dstufft Would be great  if there is a way to pass tag key as empty string(""). i tried with different options as below but not getting expected result. Ideally am looking for the command or script to get the AWS resources which are untagged

**aws ec2 describe-addresses --filters Name=tag:"",Values="" --query 'Addresses[*].PublicIp'
aws ec2 describe-addresses --filters Name=tag:NULL,Values="" --query 'Addresses[*].PublicIp'
aws ec2 describe-addresses --filters Name=tag:null,Values="" --query 'Addresses[*].PublicIp'
aws ec2 describe-addresses --filters Name=tag:,Values="" --query 'Addresses[*].PublicIp'**

Appreciate you help!!!
