### ISSUE TITLE
aws route53 associate-vpc-with-hosted-zone error parsing parameter

### ISSUE THREAD

**Issue by damdr** [aws/aws-cli#3299]
Hello 

i think there is a problem with the 'associate-vpc-with-hosted-zone' api.  I get this error :
```
$ aws --version
aws-cli/1.15.8 Python/3.6.5 Darwin/17.5.0 botocore/1.10.8
$ aws route53 associate-vpc-with-hosted-zone --hosted-zone-id XXXXXXXXXXXXXX --vpc vpc-xxxxxxx --profile xxxxxxxxxxxxxxx

Error parsing parameter '--vpc': Expected: '=', received: 'EOF' for input:
vpc-xxxxxxx
```

**Comment by kyleknap** [comment]
I think the error message could be a little more helpful here, but if you look at the [reference page](https://docs.aws.amazon.com/cli/latest/reference/route53/associate-vpc-with-hosted-zone.html) for the command, the command needs to be:
```
aws route53 associate-vpc-with-hosted-zone --hosted-zone-id XXXXXXXXXXXXXX --vpc VPCId=vpc-xxxxxxx
```
Let us know if that helps or if you have anymore questions/comments.

**Comment by damdr** [comment]
thank's my bad .
