### ISSUE TITLE
Document of ACM update-certificate-options with wrong example 

### ISSUE THREAD

**Issue by 4ndersonLin** [aws/aws-cli#3300]
CLI version:
`aws-cli/1.15.11 Python/3.6.3 Darwin/17.4.0 botocore/1.10.11`

Command:
`aws acm update-certificate-options`

Description:
The ACM update-certificate-options command example[1] not work because “update-certificate” command doesn’t exist. And the option “--certificate-options” also doesn’t exist. So, this example is not workable when I change the certificate-arn from example to my real certificate arn.
The document example as follows:
`aws acm update-certificate --certificate-arn arn:aws:acm:region:account:certificate/12345678-1234-1234-1234-123456789012 --certificate-options CertificateTransparencyLoggingPreference=DISABLED`

This example should be fixed to
`aws acm update-certificate-options --certificate-arn arn:aws:acm:region:account:certificate/12345678-1234-1234-1234-123456789012 --options CertificateTransparencyLoggingPreference=DISABLED`

Reference:
[1]https://github.com/aws/aws-cli/blob/develop/awscli/examples/acm/update-certificate-options.rst

Thanks

**Comment by joguSD** [comment]
Opened up a PR to get this fixed.
