### ISSUE TITLE
Add support for DefinitionS3Location property on AWS::AppSync::GraphQLSchema to cloudformation package

### ISSUE THREAD

**Issue by gregoryfabry** [aws/aws-cli#3301]
Currently `cloudformation package` does not support the DefinitionS3Location property for an AppSync GraphQL schema, which means that schemas must be embedded in the template file.

See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlschema.html#aws-resource-appsync-graphqlschema-properties

**Comment by TimoVink** [comment]
I believe this should be resolved now that #3297 is merged. I think it was released with v1.15.23
