### ISSUE TITLE
cognito-idp update-user-pool resets pool configuration when optional arguments are not passed

### ISSUE THREAD

**Issue by tarciosaraiva** [aws/aws-cli#3302]
## Background
- User pool created with a certain configuration
- A lambda is created separately
- Using aws cli to associate the Lambda with the User pool

## Command executed
```
aws cognito-idp update-user-pool \
    --user-pool-id $COGNITO_USER_POOL \
    --lambda-config UserMigration="$MIGRATION_LAMBDA" \
    --region ap-southeast-2
```

## Expectation
Only the UserMigration lambda trigger is updated, everything else is kept as is.

## What actually happens
The entire pool is reset to default values but the lambda is setup
- Tags are removed
- Password complexity is reset to default
- Verifications are reset

### BEFORE
![screenshot-2018-5-3 user pools - amazon cognito](https://user-images.githubusercontent.com/893428/39556747-f36f4338-4ec5-11e8-9940-7b3daa1804e6.png)

### AFTER
![screenshot-2018-5-3 user pools - amazon cognito 1](https://user-images.githubusercontent.com/893428/39556756-fd99fa1a-4ec5-11e8-994e-a6a63e4dce4c.png)

**Comment by joguSD** [comment]
The CLI is only responsible for creating and sending the request, the actual result is determined by the service so we won't be able to help you much here. I would try asking on the [cognito forums](https://forums.aws.amazon.com/forum.jspa?forumID=173&start=0) or opening a [support ticket](https://console.aws.amazon.com/support/home#/).

**Comment by adrai** [comment]
@tarciosaraiva I'm having the same issue... did you solve the problem?

**Comment by adrai** [comment]
https://forums.aws.amazon.com/message.jspa?messageID=828232#828232

**Comment by mpvosseller** [comment]
This is a total hack, not recommended, and will probably break for you but here is a fragile workaround via bash script and using jq. It fetches the current cognito configuration, massages it, and then passes it back into `update-user-pool` as the `--cli-input-json` arg. This allows you to update a subset of config values with command line args while (hopefully!) keeping the rest of the configuration which is passed with `--cli-input-json` 

```bash
# get allowed config keys
config_keys=$(aws cognito-idp update-user-pool --generate-cli-skeleton | jq 'keys')

# get the current cognito configuration and reformat it for use with update-user-pool
# note: we delete AdminCreateUserConfig.UnusedAccountValidityDays because it is not supported when using Policies.PasswordPolicy.TemporaryPasswordValidityDays
current_config=$(aws cognito-idp describe-user-pool --user-pool-id "${user_pool_id}" | jq --argjson whitelist "${config_keys}" '.UserPool | . + {UserPoolId:.Id} | with_entries(select(.key as $a | any($whitelist[]; . == $a))) | del(.AdminCreateUserConfig.UnusedAccountValidityDays)')

# update the cognito config. In this case I update only the lambda config and keep the rest unmodified
aws cognito-idp update-user-pool --lambda-config "PostConfirmation=${api_function_arn},PostAuthentication=${api_function_arn}" --cli-input-json "${current_config}"
```
