### ISSUE TITLE
How to sync with content type only for some extensions?

### ISSUE THREAD

**Issue by jleclanche** [aws/aws-cli#3303]
I have several folders containing tens of thousands of files named "12345.png", "12345.jpg" and "12345.webp".

I run `aws s3 sync` on those folders to sync up the local fs with s3 on a regular basis. Problem is, webp files are not correctly detected by s3 as `image/webp` and instead end up with the mime type `binary/octet-stream`, making it impossible to view the files directly on Chrome. [Example](http://art.hearthstonejson.com.s3-website-us-east-1.amazonaws.com/v1/tiles/EX1_001.webp).

There is a feature request from 2015 about this: https://forums.aws.amazon.com/thread.jspa?threadID=219708

I know how I can individually upload the files with a content type, or modify them after-the-fact, but both of those options are very impractical for me. Is there an option to either:

1. Have `s3 sync` *map* the webp extension to `image/webp`, without causing all the JPG and PNG files to have the same content-type; or
2. Have s3 correctly autodetect image/webp?

**Comment by joguSD** [comment]
I wasn't able to reproduce this. I started with an empty bucket and did the following:
```
$ ls
a.jpg  a.png  a.webp
$ aws --version
aws-cli/1.15.10 Python/3.6.2 Darwin/16.7.0 botocore/1.10.12
$ aws s3 sync . s3://bucketname
...
$ aws s3api get-object --bucket bucketname --key a.webp tmp
{
    "AcceptRanges": "bytes",
    "LastModified": "Fri, 04 May 2018 22:21:12 GMT",
    "ContentLength": 4088,
    "ETag": "\"a568b5497b2bfd90d75055a12e4655e3\"",
    "ContentType": "image/webp",
    "Metadata": {}
}
```
When you run `aws s3 sync` we attempt to guess the content type using Python's `mimetypes` library. This module will look at your systems environment in addition to some well known file types to try and guess the content type. I'm assuming my system has a mapping for `webp` and yours doesn't (are you on windows by any chance?). It should be possible to extend `mimetypes` known list of mappings, for windows this would be the MIME types database in the registry.

You might also try using filters and a manual content type on your `sync` command like this: `--exclude "*" --include "*.webp" --content-type "image/webp"`

Let me know if this helps!

**Comment by jleclanche** [comment]
Oh interesting. No, I'm on linux. So you're saying awscli will look at mime types to determine the default content type? Where's the code for that?

**Comment by joguSD** [comment]
https://github.com/aws/aws-cli/blob/5d349108c974d80b5b1a634e8a7433556a31e605/awscli/customizations/s3/utils.py#L288-L307

**Comment by jleclanche** [comment]
Ah, but using the builtin `mimetypes` library doesn't look at the OS's configued mime types actually, it's a hardcoded list in python.

https://github.com/python/cpython/blob/cedc9b74202d8c1ae39bca261cbb45d42ed54d45/Lib/mimetypes.py#L402-L530

And they don't take in anything not registered by IANA (which webp doesn't seem to be, though that's a bit surprising).

**Comment by joguSD** [comment]
It also has a list of files to check:
https://github.com/python/cpython/blob/cedc9b74202d8c1ae39bca261cbb45d42ed54d45/Lib/mimetypes.py#L42-L52
That when the module initializes it reads and adds any mappings:
https://github.com/python/cpython/blob/cedc9b74202d8c1ae39bca261cbb45d42ed54d45/Lib/mimetypes.py#L352-L355

**Comment by jleclanche** [comment]
@joguSD You're totally right! Adding image/webp mapping to `/etc/mime.types` fixed my issue after a re-upload.

https://art.hearthstonejson.com/v1/256x/FP1_012.webp

Yay. :)

I don't know what you want to do with this issue then. I believe s3 itself should still autodetect webp rather than not but that's out of scope of awscli.

**Comment by joguSD** [comment]
Awesome, glad to hear you found a solution! To be entirely honest I'm not sure what level of content type detection S3 does on the service side. I suppose you could try asking on the [S3 forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) or opening a [support ticket](https://console.aws.amazon.com/support/home#/) to get in touch with the service team.

As we can't do much here and we at least have a client side work around I'm going to close this issue.

**Comment by fitcwill** [comment]
I would second that the CLI should be mapping correctly .webp to image/webp.  I'm not sure why you wouldn't want this but please feel free to point out some good reasoning that might help my understanding.
