### ISSUE TITLE
aws cli cloudformation deploy exit code

### ISSUE THREAD

**Issue by papiveron** [aws/aws-cli#3308]
Hello,

This is more like an update/bug suggestion than an issue.

In fact the **cli**  `aws  cloudformation deploy` command creates or updates a **cloudformation** stack.

Actually when the stack is up to date, the command displays the message 

> "No changes to deploy. Stack cfn-XXX is up to date"

 and exists.

However the exit code in that case is **255**, which for me is not a good choice, as stack beeing up to date is not an error, it's just that there is nothing to do like the above message says.
So when you use this command in a POSIX program like for example implementing a CI/CD with **codebuild**, replaying the stage invoking the command exits with the code **255** and then halts the build as the code is different from **ZERO**.
While one would like the pipeline/build to continue to next stages as the stack created in the previous stage is already up to date.

I will do a workaround to avoid running deploy command when the related stack is up to date, but I don't if for yoi it's normal to return **255** instead of **ZERO**, and if this can me modified in future releases.

Regards,
Eugène NG

**Comment by papiveron** [comment]
```
function awsCF {
    STDERR=$(( aws cloudformation "$@" ) 2>&1)
    ERROR_CODE=$?
    echo ${STDERR} 1>&2
    if [[ "${ERROR_CODE}" -eq "255" && "${STDERR}" =~ "No changes to deploy" ]]; then
        exit 0;
    fi
    exit ${ERROR_CODE}
}

awsCF --region eu-west-1 deploy --template-file template_file.yaml --stack-name my_stack [--capabilities CAPABILITY_NAMED_IAM]
~                                                                                                                                                                               
```

**Comment by joguSD** [comment]
You can pass the `--no-fail-on-empty-changeset` to get a 0 RC when the change set is empty.

**Comment by papiveron** [comment]
Yes you're rigth, the flag works

**Comment by ajinkyatakle** [comment]
Great. Flag --no-fail-on-empty-changeset works great.
