### ISSUE TITLE
Athena Query error

### ISSUE THREAD

**Issue by prathamesh1122** [aws/aws-cli#3313]
Hello,
I am getting below error on Athena when I try to run my Query-
User: arn:aws:sts::545566666:assumed-role/ADFS-MASTERDATA-DEVELOPER/pk79901 is not authorized to perform: athena:StartQueryExecution (Service: AmazonAthena; Status Code: 400; Error Code: AccessDeniedException; Request ID: 49eee8d6-52a7-11e8-964f-c3a8fb8f6ffc)

I have checked that IAM policy has been correctly defined to have required Athena access and it is mapped to correct role.
Can anyone please help me what is going wrong here?

Thanks,
Prathamesh

**Comment by joguSD** [comment]
This sounds like a service usage issue which unfortunately we won't be able to help with much here. I would try asking on another resource like the [athena forums](https://forums.aws.amazon.com/forum.jspa?forumID=242&start=0).
