### ISSUE TITLE
aws configure get and aws configure set with multiword profile names are inconsistent

### ISSUE THREAD

**Issue by atbentley** [aws/aws-cli#3314]
It seems that `aws configure set --profile "two words"` will add single quotes around the profile name, but `aws configure get --profile "two words"` will search for a profile name that does not have single quotes around the profile name.

These two methods should behave in a similar manner.

To reproduce:

```
$ aws --version
aws-cli/1.15.10 Python/3.6.5 Darwin/17.4.0 botocore/1.10.10
$ aws configure set aws_access_key_id test --profile "test profile"
$ aws configure get aws_access_key_id --profile "test profile"
The config profile (test profile) could not be found
$ aws configure get aws_access_key_id --profile "'test profile'"
test
```

**Comment by joguSD** [comment]
Confirmed. Looks like this is only an issue for configurations that end up being written to credentials file as the section name format for the profile is different.
