### ISSUE TITLE
How to set SMS attributes when using SNS publish

### ISSUE THREAD

**Issue by starkshaw** [aws/aws-cli#3320]
Hi all,

I am confused when trying to set the sender ID using the AWS CLI SNS publish. How can I achieve this?

I used command like this:

```
$ aws sns publish --message "Hello world." --phone-number +1xxxxxxxxx --message-attributes "file:///home/ec2-user/sms.json"
```

And in the `sms.json` I have something like,

```
{"entry":{
        "N":{
            "DefaultSenderID": "HelloWorld",
            "DefaultSMSType": "Promotional"
        }
    }
}
```

Actually I am not sure about the format of the JSON or shorthand syntax stated here: https://docs.aws.amazon.com/cli/latest/reference/sns/publish.html

I am trying to implement the attributes here: https://docs.aws.amazon.com/cli/latest/reference/sns/set-sms-attributes.html

The error I received from the previous command is
```
Parameter validation failed:
Missing required parameter in MessageAttributes.entry: "DataType"
Unknown parameter in MessageAttributes.entry: "N", must be one of: DataType, StringValue, BinaryValue
```

It seems it only accept these three types.

**Comment by joguSD** [comment]
The format for that parameter should look like this:
```json
{
  "any_string": {
    "DataType": "String",
    "StringValue": "example_corp"
  }
}
```
or if you could set `DataType` to `Binary` and provide a `BinaryValue` instead of `StringValue`.

**Comment by starkshaw** [comment]
Hey joguSD

I attempted this
```
{
  "DefaultSenderID": {
    "DataType": "String",
    "StringValue": "HelloWorld"
  },
  "DefaultSMSType": {
    "DataType": "String",
    "StringValue": "Promotional"
  }
}
```
But the sender ID is still the default value "NOTICE".

If I add `MessageAttributes.entry.N` or `attributes.entry.N` as prefix of these two attributes, still no visible difference.

**Comment by ClemontX** [comment]
Same problem here.

**Comment by kdaily** [comment]
Hi @Cle

**Comment by ClemontX** [comment]
@kdaily Hey, i experienced a new thing, i set the Sender-ID to 404MG and i got a Message from +49404

In Germany, i think, you can't use a hyphen in the Sender-ID.

I'm using this version: `aws-cli/2.2.8 Python/3.8.8`

**Comment by kdaily** [comment]
Thanks @ClemontX. So, it is working for you now? According to the documentation, the sender ID is 1-11 alphanumeric digits, one of which needs to be a character, so a hyphen would not work.

I think the previous comments on the format of the JSON are still correct regarding the required formatting.

**Comment by starkshaw** [comment]
I'm going to response the question I asked few years ago.

In AWS CLI (v1 and v2), you can set the sender ID in this fashion:

```
$ aws sns publish --phone-number +1234567890 --message "Hello World" --message-attributes '{"AWS.SNS.SMS.SenderID":{"DataType":"String","StringValue":"JohnDoe"}}'
```

Ref: https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html#sms_publish_sdk

**Comment by ClemontX** [comment]
Thank you, i think this is a problem with my phone.
You can close this issue, if you want. :)
