### ISSUE TITLE
aws cli update-function-configuration 'ascii' codec can't encode character u'\xef' in position 26: ordinal not in range(128)

### ISSUE THREAD

**Issue by Moudybasha** [aws/aws-cli#3321]
Hi,
I was trying to update my lambda function configuration using the below CLI command 

`aws lambda update-function-configuration --function-name ARM-ATDReader --handler=Syngenta.OBBC.ATDReader.Function::Syngenta.OBBC.ATDReader.Function.Function::FunctionHandler --environment file://E:\Projects\Spikes\Syngenta.OBBC.ATDReader.Spike\Syngenta.OBBC.ATDReader.Function\publish\environment.json --runtime dotnetcore2.0 --timeout 300 --memory-size 1024`

But, I'm facing the below error message:

`'ascii' codec can't encode character u'\xef' in position 26: ordinal not in range(128)`

Attached `envrionment.json` 
[environment.zip](https://github.com/aws/aws-cli/files/2000347/environment.zip)

Could you please help.

**Comment by joguSD** [comment]
This sounds like a unicode issue, and you're on windows it seems. Can you try installing the AWS CLI using the Python 3 MSIs? 

https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#python3-msis
