### ISSUE TITLE
Does --no-include-email have an ENV equivalent?

### ISSUE THREAD

**Issue by wenlock** [aws/aws-cli#3328]
This might be a feature request, but as the title ask, I'm looking for an environment equivalent that we can include as an option in our automated builds that used `aws ecr get-login`. When we move to newer versions of docker we'd like to have the environments with newer versions pickup the `--no-include-email` option by simply having an environment variable that lets the `aws` command know it should have that option turned on.  Our current workaround is to write a wrapper script for the aws cli that adds the option when the version of docker requires this new option.

Any suggestions for automatically setting this option would be great.  Thanks!

**Comment by joguSD** [comment]
There is not an environment variable equivalent. Marking as a feature request.

**Comment by stubblyhead** [comment]
The -e flag was removed from `docker login` almost a year and a half ago, and had been deprecated for some time before that.  Perhaps it's time to just make `--no-include-email` the default behavior?

**Comment by rpnguyen** [comment]
`ecr get-login` is now deprecated, please see aws/containers-roadmap#735 for guidance on using the new command [`ecr get-login-password`](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html) which will remove the need to conditionally include the `--no-include-email` parameter

**Comment by stealthycoin** [comment]
Closing since its resolved.
