### ISSUE TITLE
aws s3 sync fails to upload big files (error 10054: An existing connection was forcibly closed by the remote host)

### ISSUE THREAD

**Issue by vmitec** [aws/aws-cli#3329]
I am trying to use aws s3 sync to backup my documents from a server (not in AWS).

`aws s3 sync D:\Documents s3://mybucket --storage-class STANDARD_IA --sse --delete --no-follow-symlinks --exclude "*.git\*" --exclude "*Html\*" --exclude "*VirtualBox VMs\*"`

It works fine for small files but fails systematically for big files (60 MB-200MB), e.g. java development kits:

`upload failed: D:\Documents\infrastructure\software\Java\jdk-6u45-windows-x64.exe to s3://mybucket/infrastructure/software/Java/jdk-6u45-windows-x64.exe ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`

`upload: D:\Documents\infrastructure\software\Java\jdk-6u17-windows-x64.exe to s3://mybucket/infrastructure/software/Java/jdk-6u17-windows-x64.exe`

`upload failed: D:\Documents\infrastructure\software\Java\jdk-7u60-windows-x64.exe to s3://mybucket/infrastructure/software/Java/jdk-7u60-windows-x64.exe ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`

`upload failed: D:\Documents\infrastructure\software\Java\jdk-7u80-windows-x64.exe to s3://mybucket/infrastructure/software/Java/jdk-7u80-windows-x64.exe ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`

I tried multiple times but it does not work. I am uploading these files over a slow and unreliable DSL line. But I would expect  aws s3 sync to work reliably, even with large files/network glitches..

I am using the latest windows version of the AWS CLI available for download on the AWS website:

`aws --version
aws-cli/1.15.21 Python/2.7.9 Windows/8 botocore/1.10.21`

Thanks for your support

**Comment by joguSD** [comment]
One thing you could try is lowering the [`multipart_chunksize`](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#configuration-values) to something smaller (the default is 8MB) which should reduce the chance of this happening.

Let me know if that helps.

**Comment by vmitec** [comment]
Thanks. I tried again by lowering multipart_chunksize to 2MB: 

`aws configure set default.s3.multipart_chunksize 2MB`

Unfortunately, I still get error messages for "large" files:
`upload failed: ('Connection aborted.', error(10053, 'An established connection was aborted by the software in your host machine'))
upload failed: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))`
