### ISSUE TITLE
aws s3 sync is very processor intensive

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#333]
My i7-2620M X220 is overheating at 92C with a sync. :(

![1378695940_1366x768](https://f.cloud.github.com/assets/765871/1104519/f95982da-18fc-11e3-8625-58334739c7ed.png)

**Comment by eknath-iyer** [comment]
Both my cores are up to 100% utilization when I use `aws s3 cp` on ~100mB files. I am using version 1.7.36 on ec2 (ec2 and the bucket reside in the same region). Are there better SDKs/strategies to achieve this?

**Comment by kaihendry** [comment]
Have you tired s3cmd @eknath-iyer ? http://s3tools.org/s3cmd
