### ISSUE TITLE
Date format not specified in documentation

### ISSUE THREAD

**Issue by gcbw** [aws/aws-cli#3332]
on https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

all the mentions to `--expire` only say:
```
[--expires <value>]
```
or
```
--expires (string) The date and time at which the object is no longer cacheable.
```
which is rather unhelpful as the date format is never mentioned. Also it never shows up on any example.

**Comment by joguSD** [comment]
It's expecting an ISO 8601 formatted timestamp. You can see descriptions of common inputs [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-using-param.html#parameter-types).

Some examples from the docs:
```
YYYY-MM-DDThh:mm:ss.sssTZD (UTC), e.g., 2014-10-01T20:30:00.000Z

YYYY-MM-DDThh:mm:ss.sssTZD (with offset), e.g., 2014-10-01T12:30:00.000-08:00

YYYY-MM-DD, e.g., 2014-10-01

Unix time in seconds, e.g. 1412195400
```

I've also opened up a PR to add an example of this: https://github.com/aws/aws-cli/pull/3335
