### ISSUE TITLE
Ambiguous documentation for inspector create-assessment-template --duration-in-seconds"

### ISSUE THREAD

**Issue by fabdouglas** [aws/aws-cli#3368]
For `aws inspector create-assessment-template --duration-in-seconds` argument, the documentation states:

> The duration of the assessment run in seconds. The default value is 3600 seconds (one hour).

But the CLI requires this argument. `3600` (`1 Hour`) is only optional when the template is created from the console and since it is selected by default.

**Comment by stealthycoin** [comment]
Thanks for pointing this out. We consume those docs from the service team. I informed them of the doc mistake but since there is no action we can take I will close this issue.
