### ISSUE TITLE
Issues with double slash '//'

### ISSUE THREAD

**Issue by leezu** [aws/aws-cli#3370]
If a path on s3 contains '//', `aws s3 sync` will re-download all files "below" that path on every invocation.

E.g. consider the following path: `s3://path/to//somewhere/`. In this case all files `s3://path/to//somewhere/a`, `s3://path/to//somewhere/b` etc will be re-downloaded by the sync command even if they have not changed.

**Comment by kyleknap** [comment]
Hmm. I'm not sure if there is really any great options here. The problem boils down to the commands are trying to map a key-value store to a file system. Specifically, the `//` would indicate there is a directory with an empty name which is not allowed on file systems. To help with that, we collapse the path separators to a single separator when downloading the file. However with`sync`, it is ambiguous with regards to if local file had the path separators collapsed or not. Unfortunately, I think the only option to get the ideal behavior to work would be to see if you can remove the double slashes from object key name itself. Let us know if you have anymore comments or questions.

**Comment by leezu** [comment]
Thanks for your analysis @kyleknap . I wonder if it would make sense to perform the collapsion of path separators (`//` to `/`) already during the check if the file was downloaded already? After all the collapsion is deterministic and will always result in the same local filename. I'm not sure if the ambiguity from mapping file-names to object names matters, given that the check can be performed the other way round (ie. mapping object names to file names). `aws-cli` is inconsistent in that it performs the normalization during `download` but not during checking which files to download. 

For my case, I solved the issue by renaming the objects as you suggested.
Maybe a warning should be generated when files are downloaded and path collapsion had to be performed?

**Comment by justnance** [comment]
@leezu - Thank you for your feedback.  In regards to the following question, I am leaving this issue open and labeled as feature request pending further review and 👍 .  

> Maybe a warning should be generated when files are downloaded and path collapsion had to be performed?

**Comment by misterhayman** [comment]
This appears to still be an issue. Would love if this could be fixed.  It's typical for bash to collapse a `//` down to a `/`
