### ISSUE TITLE
First Deploy Works, Second Deploy Fails

### ISSUE THREAD

**Issue by cikpis** [aws/aws-cli#3371]
Hello,

I am facing a weird issue. The first deploy works but sadly, subsequent deploys fail.

I found the same issue [here](https://github.com/aws/aws-vsts-tools/issues/26) Is it related?

**Comment by cikpis** [comment]
I've already a t2.micro :)

**Comment by stealthycoin** [comment]
Deploy of what? I need some more details about what it is you are trying to do that fails. If its a service error then there probably isn't much we can do here and you would have better luck contacting the service team through customer support or through the forums.

[AWS Support](https://console.aws.amazon.com/support/home#/)
