### ISSUE TITLE
Blocker: ImportError: No module named s3transfer.exceptions

### ISSUE THREAD

**Issue by rbuck** [aws/aws-cli#3372]
We're running a python client that launches a CFT after checking current state in S3. It immediately fails with the following issue:

```ImportError: No module named s3transfer.exceptions```

Has anyone an understanding of what is going on here?

Our pip list is:

```
aws-cfn-bootstrap==1.4
awscli==1.14.9
Babel==0.9.4
backports.ssl-match-hostname==3.4.0.2
boto==2.48.0
boto3==1.7.35
botocore==1.10.31
chardet==2.0.1
cloud-init==0.7.6
colorama==0.2.5
configobj==4.7.2
docutils==0.11
ecdsa==0.11
futures==3.0.3
hibagent==1.0.0
iniparse==0.3.1
Jinja2==2.7.2
jmespath==0.9.2
jsonpatch==1.2
jsonpointer==1.0
kitchen==1.1.1
List==1.3.0
lockfile==0.8
MarkupSafe==0.11
paramiko==1.15.1
PIL==1.1.6
ply==3.4
pyasn1==0.1.7
pycrypto==2.6.1
pycurl==7.19.0
pygpgme==0.3
pyliblzma==0.5.3
pystache==0.5.3
python-daemon==1.5.2
python-dateutil==2.1
pyxattr==0.5.0
PyYAML==3.10
requests==1.2.3
rsa==3.4.1
simplejson==3.6.5
six==1.8.0
urlgrabber==3.10
urllib3==1.8.2
virtualenv==15.1.0
yum-metadata-parser==1.1.4
```
And the stack trace is:

```Traceback (most recent call last):
  File "./bin/cluster", line 561, in <module>
    main()
  File "./bin/cluster", line 553, in main
    if args.function(session, args):
  File "./bin/cluster", line 350, in create_clusters
    create_cluster(name, session, args)
  File "./bin/cluster", line 444, in create_cluster
    sync_to_s3(session, aws_region, bucket_name, name)
  File "./bin/cluster", line 48, in wrapper
    result = f(*args)
  File "./bin/cluster", line 304, in sync_to_s3
    s3 = session.resource('s3')
  File "/usr/local/lib/python2.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 70, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 95, in _create_client_class
    base_classes=bases)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/usr/local/lib/python2.7/site-packages/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \
ImportError: No module named s3transfer.exceptions```

**Comment by kyleknap** [comment]
Interesting. Based on your `pip freeze`, you do not have `s3transfer` installed which is a direct requirement of the CLI: https://github.com/aws/aws-cli/blob/develop/setup.py#L30. `s3transfer` must be installed to run the CLI. Out of curiosity, how did you originally install the CLI?

**Comment by rbuck** [comment]
To install it I used Packer to create an AMI (Jenkins Slave) per the following:

```  "provisioners": [{
    "type": "shell",
    "inline" : [
      "sudo yum -y update",
      "sudo yum install -y java-1.8.0-openjdk.x86_64",
      "sudo yum remove -y java-1.7*",
      "sudo yum install -y git",
      "sudo pip install awscli --upgrade --user",
      "sudo /usr/sbin/alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java"
    ]
  }, {
```

That's on a Jenkins Slave, on the Master we run:

```sudo yum install -y git nginx aws-cli```

What I found does work, is that after all this, if instead I run this sort of thing (not cleaned up, a bit rough):

```
sudo apt-get install -y python-pip
sudo pip install awscli boto boto3 --force-reinstall --upgrade
sudo pip install awscli --force-reinstall --upgrade
aws --version
```

The force-reinstall for some reasons masks some other issue and resolves this. So the question I'd have is, why would force-reinstall fix things? What could have happened?

Net-net, on either RH or Ubuntu I'd like a rinse-and-repeat recipe that works. But I'd like to also understand, from a Python perspective, how could this have occurred, so I can understand this better, and know how to avoid the issue in the future? Is it the use of yum to install the `aws-cli` vs using `pip` that is at issue, e.g.?

**Comment by jamesls** [comment]
> Is it the use of yum to install the aws-cli vs using pip that is at issue, e.g.?

Essentially yes.  Both the `sudo apt-get install ...` and `sudo pip install` are both installing the CLI globally which means they're both updating the same files.  It's likely that installing some python packages globally through `apt-get/yum` and some through `pip` can create these types of issues.

If you want a truly isolated install mechanism you can use our bundled installer (https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html#install-bundle-user) which will still the entirety of the CLI in a single directory and doesn't require sudo.

**Comment by mxc19912008** [comment]
I had the same problem when I use IBM openwhisk to connect aws s3. I added s3transfer to the package list that needs to be installed, then it's fixed. The following code equals to include the corresponding packages. Hope it helps!

```
package:
  exclude:
    - virtualenv/**
    - '!virtualenv/bin/activate_this.py'
    - '!virtualenv/lib/python2.7/site-packages/boto3/**'
    - '!virtualenv/lib/python2.7/site-packages/botocore/**'
    - '!virtualenv/lib/python2.7/site-packages/jmespath/**'
    - '!virtualenv/lib/python2.7/site-packages/s3transfer/**'
    - '!virtualenv/lib/python2.7/site-packages/concurrent/**'
```

**Comment by clarkkarenl** [comment]
I had the same problem on Mac OS X with aws-cli 1.16.79 using Python 2.7 (our codebase is locked to the old version due to backwards compatibility demands). The steps in @rbuck 's June 14th [post](https://github.com/aws/aws-cli/issues/3372#issuecomment-397338410) fixed it for me. 
Resulting versions:
$ aws --version
aws-cli/1.16.81 Python/2.7.10 Darwin/17.7.0 botocore/1.12.71)
