### ISSUE TITLE
How to automatically retry if `aws glacier upload-archive` fails for RequestTimeoutException

### ISSUE THREAD

**Issue by paologf** [aws/aws-cli#3373]
Hello,

I have big file of 6/7GB that I upload to Glacier splitting in 1GB file and then uploading the single file with `aws glacier upload-archive`. I do this every day, but sometimes one of this 6/7 files fail to be uploaded and I got the `An error occurred (RequestTimeoutException) when calling the UploadArchive operation: Request timed out.` error. 
Is there a way to automatically retry to send the file without waiting for the output message? What is the correct way to manage this kind of error?

Thanks

Paolo

**Comment by justnance** [comment]
Thanks for reaching out @paologf.  Currently the CLI does not have this functionality.  It would a good feature.  I'm labeling this as a feature request pending further review and 👍 .
