### ISSUE TITLE
[Feature Request] Give more obvious warning when using an invalid profile

### ISSUE THREAD

**Issue by tyhunt99** [aws/aws-cli#3375]
I was testing permissions with another user and set up another profile. I did not realize at first you could specify ```--profile``` for the configure command, so I wen and manually created the profile in ```.aws/credentials```:

```
[default]
aws_access_key_id = ***********
aws_secret_access_key = ***************************************

[thuntupdate]
aws_access_key = ***********  # made a typo here and forgot _id
aws_secret_access_key = ***************************************
```
Whenever I was trying to do anything it simply gave me ```Access Denied``` errors. It would be nice if instead of simply returning a forbidden response for everything, it could return an unauthorized response when the credentials were unauthorized and not just denied access. 

It would also be nice if it could throw errors when the specified profile being used is invalid.

**Comment by kyleknap** [comment]
@tyhunt99 What version of the AWS CLI are using? When I do something similar in my `~/.aws/credentials` file, I get the following:
```
$ aws s3 ls --profile invalid
Unable to locate credentials. You can configure credentials by running "aws configure".
```
Sure it may make sense to be more helpful for detecting why it could not locate credentials, but it is definitely better than `Access Denied`. I am running this version of the CLI:
```
$ aws --version
aws-cli/1.15.35 Python/2.7.10 Darwin/15.6.0 botocore/1.10.35
```

**Comment by tyhunt99** [comment]
@kyleknap Now that I am trying to verify this I am getting more strange behavior. It seems to always be falling through to my default user. And I am not sure where it is getting it from. I have removed it from my ~/.aws/credentials and have no environment variables set. 

Where else could it be getting this from?

```
$ aws --version
aws-cli/1.15.36 Python/3.4.3 Linux/3.19.0-78-generic botocore/1.10.36
```

**Comment by jamesls** [comment]
If you run `aws configure list` it will tell you where it's getting credentials from.  Additionally, running `--debug` will tell you where we're checking for credentials and in what order.

As to your other question:

>  It would be nice if instead of simply returning a forbidden response for everything, it could return an unauthorized response when the credentials were unauthorized and not just denied access.

While I agree it would be nice, we have no way of knowing this.  From the CLI's perspective we just sign the request with whatever credentials you give us, and we surface any errors that the AWS service returns.  It wouldn't be possible for us to know if you're credentials are valid or not.

**Comment by tyhunt99** [comment]
Ah okay I was hoping it would actually return an actual 401 unauthorized but if it is just a generic response then there is not much you can do.

After using debug it shows it is finding an iam-role with credentials. How and where are those configured?
