### ISSUE TITLE
No config file lookup if credentials are set as environment variables

### ISSUE THREAD

**Issue by jvguillen** [aws/aws-cli#3390]
I realized that if i set my credentials as environment variables the cli does not go through the config file unless specified as command option `--profile default`. Keep in mind that I'm working with a unique profile.

The issue became evident when I tried to assume role from the config file and keep my credentials as environment variables. My first instinct was set `AWS_PROFILE` but that didn't have any effect.

Ideally, there is always a config file lookup based on command option or `AWS_PROFILE` variable (in that order), otherwise assume default behaviour.

**Comment by jamesls** [comment]
> Ideally, there is always a config file lookup based on command option

Can you clarify if the `--profile ` option didn't work for you?  If you have `AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY` set in env vars, you can specify the profile with the role configuration via `--profile my-profile-with-role` which will override whatever you've set in env vars.

**Comment by JordonPhillips** [comment]
We do have that option documented [here](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#cli-aws-help-config-vars), but I agree we should also have it in the user guide. I'll make sure it gets added. Thanks for the feedback!
