### ISSUE TITLE
Elastic Beanstalk deploy

### ISSUE THREAD

**Issue by smoi** [aws/aws-cli#3395]
I'm using eb cli to deploy a Magento app to EB but when I run the deploy command it gives me this error

> LargeZipFile: Files count would require ZIP64 extensions

However the directory is only around 500mb but it has something around 75k files inside.
Is there a workaround to fix this?

**Comment by jamesls** [comment]
Hi this repository for the AWS CLI.  For questions about the eb cli please ask on the elasticbeanstalk forums (https://forums.aws.amazon.com/forum.jspa?forumID=86) and someone on that team should be able to help you
