### ISSUE TITLE
Documentation: Range of `ec2 describe-launch-template-versions` --max-results param is incorrect

### ISSUE THREAD

**Issue by tdmalone** [aws/aws-cli#3397]
_I couldn't find the documentation in this repo... hence submitting an issue rather than a pull request. If I've missed an obvious place for it please accept my apologies!_

The documentation at https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-launch-template-versions.html states:

> `--max-results (integer)`
>
> The maximum number of results to return in a single call. To retrieve the remaining results, make another call with the returned NextToken value. This value can be between 5 and 1000.

However using this command states:

```bash
$ aws ec2 describe-launch-template-versions --launch-template-name ci_e0 --max-results 1000

An error occurred (InvalidParameterValue) when calling the DescribeLaunchTemplateVersions operation: Maximum results allowed are between 1 and 200
```

It would appear that the documentation needs to be updated to specify the max range is 200, not 1000.

**Comment by joguSD** [comment]
This documentation comes from the upstream [service documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeLaunchTemplateVersions.html). I've sent them an issue to let them know of this error. Closing out here as there's no actionable item on our side.
