### ISSUE TITLE
https:// and http:// argument expansion

### ISSUE THREAD

**Issue by stealthycoin** [aws/aws-cli#3398]
This is a tracking feature to discuss the deprecation path of the automatic `https://` and `http://` following.

Work has been done (#3384) to add a configuration option to disable this feature by setting `cli_follow_urlparam = false` in the config file.

Previous discussion: #2507 #3076 #2577.

**Comment by jamesls** [comment]
https://github.com/aws/aws-cli/pull/3384 has been implemented, closing issue.
