### ISSUE TITLE
s3 command masks ClientError

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cli#340]
The s3 command seems to be masking ClientError's that are raised and failing silently.

For example, if I have a bucket named `foo.bar.fie.baz` in the `us-east-1` region and I have my default region set to `us-west-2` in my config file:

```
$ aws s3 ls s3://foo.bar.fie.baz

Bucket: foo.bar.fie.baz
Prefix: 

      LastWriteTime     Length Name
      -------------     ------ ----
```

However, if I run with the `--debug` flag, I can see that a `ClientError` is being raised:

```
$ aws s3 ls s3://foo.bar.fie.baz --debug
...
ClientError: A client error (PermanentRedirect) occurred: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

And if I run it with the correct region, I do see the actual contents of the bucket.

Originally reported in the [forum](https://forums.aws.amazon.com/thread.jspa?threadID=134602&tstart=0).

**Comment by rlgomes** [comment]
I'm seeing the `aws s3 cp s3:///validbuck/invalidpath` returning a 0 exit code when it downloaded absolutely nothing on version `aws-cli/1.2.9 Python/2.6.9 Linux/3.10.37-47.135.amzn1.x86_64` shall we reopen the issue ?

**Comment by rlgomes** [comment]
The above failure happens when you use `--recursive` without the recursive option the exit codes are correct.
