### ISSUE TITLE
Glacier upload-archive fails with Invalid Content-Length error

### ISSUE THREAD

**Issue by elvetemedve** [aws/aws-cli#3413]
### The problem

When I run the command
```
aws glacier upload-archive --vault-name Photos --account-id - --body photos.tar
```
then I get an error like
> An error occurred (InvalidParameterValueException) when calling the UploadArchive operation: Invalid Content-Length: 38505164800

### Details
The **photos.tar** file is a 36 GB tar archive, more precisely

```
file photos.tar
photos.tar: POSIX tar archive (GNU)

du --bytes photos.tar
38505164800     photos.tar
```

### Expected Result

According to the API documentation the [file size is limited to 4GB](https://docs.aws.amazon.com/amazonglacier/latest/dev/uploading-an-archive.html#uploading-an-archive-overview). I would expect get an error message saying that. Alternatively it could offer to split the data into multiple chunks and do upload after that.

### Environment
**AWS CLI version**: aws-cli/1.15.42 Python/3.6.5 Linux/4.17.2-1-ARCH botocore/1.10.42

**Comment by JordonPhillips** [comment]
That error is a service-side error, so unfortunately we have no way to change it. I would recommend asking the service team via support or their forums.

As far as multipart uploading is concerned, that isn't something we offer for glacier directly at the moment. However, you can upload the objects to an S3 bucket and then simply set a lifecycle policy to put them into glacier immediately. This would allow you to use our fairly robust uploader for S3 while still getting the benefits of glacier storage.

**Comment by elvetemedve** [comment]
Alright. Thank you.

**Comment by RyanHCCSI** [comment]
When I run the same command on a 30GB database backup it'll take 6.5 hours to upload it then finally spits out the error:

> An error occurred (InvalidParameterValueException) when calling the UploadArchive operation: Invalid Content-Length: 31401009664
