### ISSUE TITLE
Cloudformation package support adding metadata to artifacts uploaded to S3

### ISSUE THREAD

**Issue by gate2022keeper** [aws/aws-cli#3417]
It would be useful if we can attach additional information to **ALL** artifacts to be uploaded to S3 by `aws cloudformation package`.

This will enable us to tag all the artifacts to be packaged with additional information. This will help us know the nature of the artifacts by simply inspecting them via S3, in scenarios where we are having problems with them.

A typical example: I built and packaged all the artifacts(Lambda Function source, API Gateway OpenAPI file etc) using a TravisCI/Jekins build and later found CloudFormation complained with failure when it tried deploying them. I would like to find out which build produced them.

**Comment by stealthycoin** [comment]
Marking as a feature request specifically for cloudformation.
