### ISSUE TITLE
Ignoring VCS related files when make deploy bundle

### ISSUE THREAD

**Issue by HatsuneMiku3939** [aws/aws-cli#3428]
```
$ aws --version
aws-cli/1.15.51 Python/3.6.5 Linux/4.15.0-24-generic botocore/1.10.50
```

In some PHP frameworks, hidden file such as `.env` should be deployed. In this case, `--ignore-hidden-files` flag of `aws deploy push` can't helpful  prevent bundle VCS related files. (.git, .svn ...etc)

Is there any other flags to solve this problem? If not, I suggest a new flag `--ignore-vcs-files`.

* my implementation
  * https://github.com/HatsuneMiku3939/aws-cli/commit/ba424bb64a27ad489b0d6a5fd689a47fceac4e20  (modified, add some testcase)

**Comment by justnance** [comment]
@HatsuneMiku3939 - thank you for reaching out.  We do not maintain or control aws deploy.  I am cc: @sanathkr as an FYI.
