### ISSUE TITLE
Can't Force Payload Signing for S3

### ISSUE THREAD

**Issue by fribeiro1** [aws/aws-cli#3429]
When using the CLI with non-AWS S3 endpoints, I need to force payload signing like with the "payload_signing_enabled" configuration in the Python SDK (https://botocore.readthedocs.io/en/latest/reference/config.html).

**Comment by justnance** [comment]
@fribeiro1 - thanks for your post and your patience.  As per the [AWS CLI reference ](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html), 

> payload_signing_enabled - Refers to whether or not to SHA256 sign sigv4 payloads. By default, this is disabled for streaming uploads (UploadPart and PutObject) when using https.

It should work the same way.  Please advise if this did not answer your question.  Thanks.
