### ISSUE TITLE
put-bucket-cors docs indicate JSON payload, but error says malformed XML

### ISSUE THREAD

**Issue by unbracketed** [aws/aws-cli#343]
I tried passing a JSON structure as per the API docs, but the error I get is:

```
A client error (MalformedXML) occurred: The XML you provided was not well-formed     or did not validate against our published schema
```

**Comment by ggmartins** [comment]
aws s3api put-bucket-cors  --bucket somebucket   --profile someprofile --cors-configuration '{"CORSRules": [{"AllowedOrigins": ["*"], "AllowedMethods":["GET"]}]}'
