### ISSUE TITLE
Double quoted tags cause update rollback failed when using deploy

### ISSUE THREAD

**Issue by samgurtman** [aws/aws-cli#3433]
When using double quoted tags with cloudformation deploy, any rollback due to stack update failure results in `UPDATE_ROLLBACK_FAILED` due to 

```
1 validation error detected: Value '["environment, "role]' at 'tagKeys' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 128, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$] (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: ****)
```

or on S3 bucket:
`One or more tags are not valid`

The documentation seems to support `aws cloudformation deploy ... --tags "a=b" "c=d"` yet deploy does not seem to pass them on correctly to downstream components. To be clear deploy does not complain about the tags on a successful deployment, only on rollback.

**Comment by andytl6** [comment]
Do you have an example of how this issue is consistently recreated in the latest version of the CLI that you'd be able to share? Perhaps a template as a demo?

**Comment by justnance** [comment]
@samgurtman - Thank you for reporting this behavior.  I am including @sanathkr to loop him in on this thread to see if he has any feedback.

**Comment by stwendl** [comment]
thank you for providing this package,  my first foray into was reporting.  Allow me to alert you to an issue.  When successfully deployed to aws, it does not seem to be possible to change the cron controlled frequency.  AWS complains about the ANS string exceeding 100 characters.  But I can delete aws structures, edit the saml definitions with a new schedule and redeploy.  Thought you might want to know
