### ISSUE TITLE
Query "Max session duration" parameter on a role?

### ISSUE THREAD

**Issue by max-allan-surevine** [aws/aws-cli#3437]
Using `iam get-role` or `iam list-roles` I cannot see any "Max Session Duration" values despite having set them in the console.
I also can't get boto3 to return any session durations, probably using the same underlying mechanism as the AWS CLI...
(Version : awscli-1.15.55)

**Comment by max-allan-surevine** [comment]
--debug output from a get-role shows the value in the response but it is missing from the CLI output :

    2018-07-10 11:50:33,277 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-requestid': '11d0ff8d-842f-11e8-afff-7d877bba4808', 'date': 'Tue, 10 Jul 2018 10:50:32 GMT', 'content-length': '1032', 'content-type': 'text/xml'}
    2018-07-10 11:50:33,277 - MainThread - botocore.parsers - DEBUG - Response body:
    <GetRoleResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
      <GetRoleResult>
        <Role>
          <Path>/</Path>
          <AssumeRolePolicyDocument>%7B%22Version%22%3A%2...</AssumeRolePolicyDocument>
          <MaxSessionDuration>28800</MaxSessionDuration>
          <RoleId>AROAJRTXXXXX5KEP4GM</RoleId>
          <RoleName>Infrastructure</RoleName>
          <Description>Infrastructure GOD permissions.</Description>
          <Arn>arn:aws:iam::999996123770:role/Infrastructure</Arn>
          <CreateDate>2017-11-06T12:01:23Z</CreateDate>
        </Role>
      </GetRoleResult>
      <ResponseMetadata>
        <RequestId>11d0408d-842f-4cf-7d877bba4808</RequestId>
      </ResponseMetadata>
    </GetRoleResponse>

    2018-07-10 11:50:33,278 - MainThread - botocore.hooks - DEBUG - Event needs-retry.iam.GetRole: calling handler <botocore.retryhandler.RetryHandler object at 0x10596a090>
    2018-07-10 11:50:33,278 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
    2018-07-10 11:50:33,278 - MainThread - botocore.hooks - DEBUG - Event after-call.iam.GetRole: calling handler <function json_decode_policies at 0x104a291b8>
    2018-07-10 11:50:33,279 - MainThread - botocore.session - DEBUG - Loading variable profile from environment with value 'max.allan@surevine.com'.
    2018-07-10 11:50:33,279 - MainThread - botocore.session - DEBUG - Loading variable output from defaults.
    2018-07-10 11:50:33,279 - MainThread - awscli.formatter - DEBUG - RequestId: 11d0408d-842f-11e8-a4cf-7d877bba4808
    {
        "Role": {
            "Description": "Infrastructure GOD permissions.", 
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17", 
                "Statement": [
                    {
                        "Action": "sts:AssumeRoleWithSAML", 
                        "Effect": "Allow", 
                        "Condition": {
                            "StringEquals": {
                                "SAML:aud": "https://signin.aws.amazon.com/saml"
                            }
                        }, 
                        "Principal": {
                            "Federated": "arn:aws:iam::999996123770:saml-provider/Foo"
                        }
                    }
                ]
            }, 
            "RoleId": "AROAJRTXXXXX5KEP4GM", 
            "CreateDate": "2017-11-06T12:01:23Z", 
            "RoleName": "Infrastructure", 
            "Path": "/", 
            "Arn": "arn:aws:iam::999996123770:role/Infrastructure"
        }
    }

**Comment by jamesls** [comment]
Can you double check you're using v1.15.55?  When I install that version I'm able to see the `MaxSessionDuration` value returned:

```
$ pip install awscli==1.15.55
$ aws --version
aws-cli/1.15.55 Python/2.7.14 Darwin/16.7.0 botocore/1.10.54
$ aws iam get-role --role-name TestMFA
{
    "Role": {
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Effect": "Allow",
                    "Condition": {
                        "Bool": {
                            "aws:MultiFactorAuthPresent": "true"
                        }
                    },
                    "Principal": {
                        "AWS": "arn:aws:iam::123:root"
                    }
                }
            ]
        },
        "MaxSessionDuration": 3600,
        "RoleId": "roleid",
        "CreateDate": "2018-08-08T19:16:03+00:00",
        "RoleName": "TestMFA",
        "Path": "/",
        "Arn": "arn:aws:iam::123:role/TestMFA"
    }
}
```

**Comment by max-allan-surevine** [comment]
So, I'm guessing awscli relies on boto. I found this same issue with boto. Someone suggested checking the botocore version from within python, and I found I had an old version of botocore in my path before the system version. So even after updating everything, said it was latest, but actually used the old version. Now I've removed the old version, I can see the max_session_duration.

**Comment by justnance** [comment]
@max-allan-surevine - thanks for your reply.  Yes the CLI relies on botocore so it is understandable updating botocore to the latest version resolved the problem.
