### ISSUE TITLE
Cloudwatch metric NetworkIn is not returning any value when unit is set as Kilobytes or Megabytes

### ISSUE THREAD

**Issue by LogeshGovi** [aws/aws-cli#3442]
Hi,
I am using the following command to get the NetworkIn metric for a specific instance:
`aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name NetworkIn --period 123   --statistics Maximum --unit Kilobytes --dimensions Name=InstanceId,Value=i-xxx --start-time yyyy-mm-ddTHH:MM:SS --end-time yyyy-mm-ddTHH:MM:SS`
if I set the **unit** as **Bytes** it's returning all the results, however if the **unit** is changed to **Megabytes** or **Kilobytes** it returns an empty list of Datapoints.

**Comment by LogeshGovi** [comment]
Hi, 
I have tried to do the same with Boto3 cloudwatch client.
``client.get_metric_statistics(
Namespace='AWS/EC2',
    MetricName='NetworkIn',
    Dimensions=[
        {
            'Name': 'InstanceId',
            'Value': 'i-xxxx'
        },
    ],
    StartTime=datetime.datetime(2018,1,1),
    EndTime=datetime.datetime(2018,7,1),
    Period=3600000,
    Statistics=[
        'Maximum'
    ],
    Unit='Kilobytes')
``
Resulting Json: 
``
{u'Datapoints': [], 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '9fe91b68-8a9e-11e8-ab2a-038496ed1a78', 'HTTPHeaders': {'x-amzn-requestid': '9fe91b68-8a9e-11e8-ab2a-038496ed1a78', 'date': 'Wed, 18 Jul 2018 15:24:11 GMT', 'content-length': '332', 'content-type': 'text/xml'}}, u'Label': 'NetworkIn'}
``

But when the same is done with unit as Bytes:
``{u'Datapoints': [{u'Timestamp': datetime.datetime(2018, 3, 25, 8, 0, tzinfo=tzutc()), u'Maximum': 60455587.0, u'Unit': 'Bytes'}, {u'Timestamp': datetime.datetime(2018, 2, 11, 16, 0, tzinfo=tzutc()), u'Maximum': 76000502.0, u'Unit': 'Bytes'}, {u'Timestamp': datetime.datetime(2018, 5, 6, 0, 0, tzinfo=tzutc()), u'Maximum': 187740565.0, u'Unit': 'Bytes'}, {u'Timestamp': datetime.datetime(2018, 6, 16, 16, 0, tzinfo=tzutc()), u'Maximum': 23716544.0, u'Unit': 'Bytes'}, {u'Timestamp': datetime.datetime(2018, 1, 1, 0, 0, tzinfo=tzutc()), u'Maximum': 64906817.0, u'Unit': 'Bytes'}], 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '33d5e96a-8a9f-11e8-bfd2-c116a6d55bfd', 'HTTPHeaders': {'x-amzn-requestid': '33d5e96a-8a9f-11e8-bfd2-c116a6d55bfd', 'date': 'Wed, 18 Jul 2018 15:28:20 GMT', 'content-length': '1095', 'content-type': 'text/xml'}}, u'Label': 'NetworkIn'}
``
When I tried it with an invalid unit "Seconds" the result was:
``{u'Datapoints': [], 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '604aad62-8a9f-11e8-b8bb-677cb599c87b', 'HTTPHeaders': {'x-amzn-requestid': '604aad62-8a9f-11e8-b8bb-677cb599c87b', 'date': 'Wed, 18 Jul 2018 15:29:35 GMT', 'content-length': '332', 'content-type': 'text/xml'}}, u'Label': 'NetworkIn'}
``
There  is no error message if wrong units are used but the JSON contains empty array of Datapoints. I think it would be nice if an error message is shown  when an invalid unit is used. However Bytes and Kilobytes should work as they belong to the same unit category.

**Comment by justnance** [comment]
@LogeshGovi - thank you for reaching out.  We do not control results from change in parameter to the API.  It is recommended to reach out to [AWS Support](https://console.aws.amazon.com/support/home#/) or the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=138)

**Comment by LogeshGovi** [comment]
@justnance -- thank you. I will reach out to AWS Developer Forums and see if a solution can be found. For now we can close this ticket I think.
