### ISSUE TITLE
Support in parameter files in --parameter-overrides

### ISSUE THREAD

**Issue by digitalfiz** [aws/aws-cli#3445]
As requested by @sanathkr over a year ago in https://github.com/awslabs/serverless-application-model/issues/111 I am submitted a request to support parameter files in the --parameter-overrides flag.

*Sorry I never got any notifications for some reason...*

**Comment by justnance** [comment]
@digitalfiz, Thank you for following up.  We are investigating this request and so far it appears to be a reasonable feature request and have changed the label as such.  Thanks.

**Comment by atkretsch** [comment]
Don't know if this should be a separate feature request, but it would be great if `--parameter-overrides` supported YAML-formatted files.

**Comment by linusguan** [comment]
This feature would be awesome, we are still hacking it using a file with `key=value`

**Comment by adamfortuno** [comment]
It's Agree. Feature would be helpful.

**Comment by anabadce** [comment]
This is how I solved this for now:

```
STACK=myStack
TEMPLATE=stack.yaml
PARAMETERS=config1.json

PROPERTIES=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' ./$PARAMETERS)

aws cloudformation deploy \
--stack-name $STACK \
--template-file "./$TEMPLATE" \
--parameter-overrides $(echo $PROPERTIES)
```

- Using `jq` to easy convert from json to key=value
- Config file is json because that is what `aws cloudformation create-change-set` uses for example
- Config looks like this:

```
[
  {
    "ParameterKey": "Environment",
    "ParameterValue": "dev"
  }
]
```

**Comment by kenlju** [comment]
We had some problem when one of the parameter values contained a cron expression cron(0 * * * ? *). Then the shell would expand the * to the filenames in the directory.
```
bash-3.2$ ls 
testfile
bash-3.2$ CR="cron(0 * * * ? *)"
bash-3.2$ echo $CR
cron(0 testfile testfile testfile ? *)
bash-3.2$ echo "$CR"
cron(0 * * * ? *)
```

**Comment by tim-finnigan** [comment]
In CLI v2 there is documented support for using a JSON file with `--parameter-overrides`: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html#examples

But there is another open feature request to use a parameter file in YAML format (as @atkretsch requested in [this comment](https://github.com/aws/aws-cli/issues/3445#issuecomment-423399038)): https://github.com/aws/aws-cli/issues/5473

Closing this issue as the JSON file option is available. Please refer to https://github.com/aws/aws-cli/issues/5473 for updates on the request for YAML file support.
