### ISSUE TITLE
aws s3api get-bucket-location doesnt return anything

### ISSUE THREAD

**Issue by AlexanderThaller** [aws/aws-cli#345]
When I run `aws s3api get-bucket-location --bucket mytestbucket` I don't get anything back (but the return value is 0).

I'm using the following version:

> `aws-cli/1.0.0 Python/2.7.3 Linux/3.2.0-53-generic-pae`

**Comment by bennlich** [comment]
I'm still having this issue with `aws-cli/1.2.9 Python/3.4.0 Linux/3.13.0-44-generic`
