### ISSUE TITLE
How to restore The RDS DB instance through its latest snapshot ?

### ISSUE THREAD

**Issue by palakbadgujar** [aws/aws-cli#3453]
Here i have created the snapshot and whenever i am executing the the restoring command for instance its taking the old snapshot it should take the latest snapshot .
 
what i have to mention to restore the RDS DB instance through the most latest snapshot.

Please help.

Regards
palak

**Comment by justnance** [comment]
As stated in our [README](https://github.com/aws/aws-cli#getting-help), I would recommend reaching out to AWS Support, StackOverflow, or the AWS Developer Forums with this question. We try to reserve GitHub issues to CLI bugs and feature requests and you should be able to find someone at one of the resources with the knowledge to help you troubleshoot this issue.

[AWS RDS forums](https://forums.aws.amazon.com/forum.jspa?forumID=60)
