### ISSUE TITLE
cloudformaiton CLI wait command timeout 3600sec

### ISSUE THREAD

**Issue by i-sangyu** [aws/aws-cli#3457]
Hey there,

I have a some trouble of cloudformation **wait** command. It seems to be timeout 3600sec.
https://github.com/aws/aws-cli/blob/f4d2dcd6b2205644da75a25e30631d6486b3fa22/awscli/customizations/cloudformation/deployer.py#L208

It's timeout value as a command options flag should to be more helpful, i think. 
for example, create RDS aurora from snapshot as a over 1 hour. 
So I suggest a new flag. **--timeout**

**Comment by justnance** [comment]
@i-sangyu - thanks for reaching out.  Sounds like a reasonable feature request.  I'm marking it as such.

**Comment by i-sangyu** [comment]
@justnance I would appreciate for your attention. I hope it will be released in the near future, before long. ;)

**Comment by tim-finnigan** [comment]
Hi @i-sangyu, thanks for your patience. This looks like a duplicate of the existing feature request to expose parameters for max-attempts and delay when using waiters. I think we should close this in favor of that issue (https://github.com/aws/aws-cli/issues/1295).
