### ISSUE TITLE
Make cloudformation create-stack --parameters support codepipeline-style configuration

### ISSUE THREAD

**Issue by iron-s** [aws/aws-cli#3461]
`--parameters file://params.json` expects json to be in the following format:
```
[
  {
    "ParameterKey": "key name",
    "ParameterValue": "value"
  },
...
]
```

But CodePipeline accepts parameters in following format:
```
{
  "Parameters" : {
    "NameOfTemplateParameter" : "ValueOfParameter",
    ...
  },
  "Tags" : {
    "TagKey" : "TagValue",
    ...
  }, 
  "StackPolicy" : {
    "Statement" : [
      StackPolicyStatement
    ]
  }
}
```
see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html#w2ab2c13c15c15

This is inconvenient and error-prone in case you deploy the same cloudformation template both using cli and from the CodePipeline.
If cli additionally supported CodePipeline format for --parameters we could keep just one file without any additional processing.

**Comment by justnance** [comment]
@iron-s - thanks for reaching out and your patience.  I understand the behavior described here however to add a feature for this would cause an backwards incompatibility.
