### ISSUE TITLE
update-security-group-rule-descriptions-ingress not showing as valid parameter for updating security group

### ISSUE THREAD

**Issue by boodera** [aws/aws-cli#3463]
I ran -
`$ aws ec2 update-security-group-rule-descriptions-ingress --group-id sg-aabbccdd --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "123.123.123.123/32", "Description": "SSH access from ABC Office"}]}]'` 
but the result shows -

aws: error: argument operation: Invalid choice, valid choices are:

activate-license                         | allocate-address
assign-private-ip-addresses              | associate-address
associate-dhcp-options                   | associate-route-table
attach-internet-gateway                  | attach-network-interface
attach-volume                            | attach-vpn-gateway
authorize-security-group-egress          | authorize-security-group-ingress
bundle-instance                          | cancel-bundle-task
cancel-conversion-task                   | cancel-export-task
cancel-reserved-instances-listing        | cancel-spot-instance-requests
confirm-product-instance                 | copy-image
copy-snapshot                            | create-customer-gateway
create-dhcp-options                      | create-image
create-instance-export-task              | create-internet-gateway
create-key-pair                          | create-network-acl
create-network-acl-entry                 | create-network-interface
create-placement-group                   | create-reserved-instances-listing
create-route                             | create-route-table
create-security-group                    | create-snapshot
create-spot-datafeed-subscription        | create-subnet
create-tags                              | create-volume
create-vpc                               | create-vpn-connection
create-vpn-connection-route              | create-vpn-gateway
deactivate-license                       | delete-customer-gateway
delete-dhcp-options                      | delete-internet-gateway
delete-key-pair                          | delete-network-acl
delete-network-acl-entry                 | delete-network-interface
delete-placement-group                   | delete-route
delete-route-table                       | delete-security-group
delete-snapshot                          | delete-spot-datafeed-subscription
delete-subnet                            | delete-tags
delete-volume                            | delete-vpc
delete-vpn-connection                    | delete-vpn-connection-route
delete-vpn-gateway                       | deregister-image
describe-account-attributes              | describe-addresses
describe-availability-zones              | describe-bundle-tasks
describe-conversion-tasks                | describe-customer-gateways
describe-dhcp-options                    | describe-export-tasks
describe-image-attribute                 | describe-images
describe-instance-attribute              | describe-instance-status
describe-instances                       | describe-internet-gateways
describe-key-pairs                       | describe-licenses
describe-network-acls                    | describe-network-interface-attribute
describe-network-interfaces              | describe-placement-groups
describe-regions                         | describe-reserved-instances
describe-reserved-instances-listings     | describe-reserved-instances-modifications
describe-reserved-instances-offerings    | describe-route-tables
describe-security-groups                 | describe-snapshot-attribute
describe-snapshots                       | describe-spot-datafeed-subscription
describe-spot-instance-requests          | describe-spot-price-history
describe-subnets                         | describe-tags
describe-volume-attribute                | describe-volume-status
describe-volumes                         | describe-vpc-attribute
describe-vpcs                            | describe-vpn-connections
describe-vpn-gateways                    | detach-internet-gateway
detach-network-interface                 | detach-volume
detach-vpn-gateway                       | disable-vgw-route-propagation
disassociate-address                     | disassociate-route-table
enable-vgw-route-propagation             | enable-volume-io
get-console-output                       | get-password-data
import-key-pair                          | modify-image-attribute
modify-instance-attribute                | modify-network-interface-attribute
modify-reserved-instances                | modify-snapshot-attribute
modify-volume-attribute                  | modify-vpc-attribute
monitor-instances                        | purchase-reserved-instances-offering
reboot-instances                         | register-image
release-address                          | replace-network-acl-association
replace-network-acl-entry                | replace-route
replace-route-table-association          | report-instance-status
request-spot-instances                   | reset-image-attribute
reset-instance-attribute                 | reset-network-interface-attribute
reset-snapshot-attribute                 | revoke-security-group-egress
revoke-security-group-ingress            | run-instances
start-instances                          | stop-instances
terminate-instances                      | unassign-private-ip-addresses
unmonitor-instances                      | help

Are these parameters are not valid for my aws cli version [aws-cli/1.2.9] ?

**Comment by justnance** [comment]
@boodera, thank you for reaching out. I was not able to reproduce this issue.   Please add the --debug option to get more info about issue.  If you can post a sanitized debug log, we can take a look at what's going on.

**Comment by arundevops16** [comment]
aws ec2 authorize-security-group-ingress --group-id sg-abcdef2 --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "10.0.0.54/32"}]}]'

**Comment by justnance** [comment]
@arundevops16 - Thanks for your post.  Initially I was not able to reproduce the same results as @boodera but I was able to use both `aws ec2 authorize-security-group-ingress` and `aws ec2 update-security-group-rule-descriptions-ingress` successfully using the latest version of the CLI.
