### ISSUE TITLE
cloudformation package - add support to S3 location for AWS::AppSync::Resolver

### ISSUE THREAD

**Issue by lsuss** [aws/aws-cli#3464]
Hi there,

I think it would be a cool feature to see [AWS::AppSync::Resolver](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html)'s S3 locations
```
{
  "ResponseMappingTemplateS3Location" : String,
  ...
  "RequestMappingTemplateS3Location" : String,
}
```
to support upload to an S3 bucket like [AWS::AppSync::GraphQLSchema](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-graphqlschema.html)'s `DefinitionS3Location` does.

Thanks :kissing:

**Comment by DanielLaberge** [comment]
We would love this as well! Right now we have to use aws s3 sync to manage the files ourselves, and it makes for templates that are easy to break.

The referenced #3487 would be even more flexible, of course.

**Comment by justnance** [comment]
Seems like a reasonable feature request. @sanathkr - what are your thoughts?

**Comment by wnkz** [comment]
Hey, any idea on when #3559 will be merged? I really need this 🙏
