### ISSUE TITLE
'aws lambda invoke' doesn't fail if lambda fails

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-cli#3470]
It would be nice for scripts to be able invoke lambdas and then succeed only if the lambda function succeeds, at least for `RequestResponse` invocation type. Currently this requires checking the outfile for json and if it contains `errorMessage`, which isn't easy nor 100% reliable.

**Comment by jamesls** [comment]
I agree this would be nice, marking as a feature request.  Not sure if we can change the behavior of the existing command but perhaps we could add another `aws lambda ...` command that had this extra behavior.

FWIW, not sure if this meets your use case, but [AWS Chalice](https://github.com/aws/chalice) supports lambda functions and also has a `chalice invoke` command that's a wrapper around `aws lambda invoke` that has a lot of this behavior (https://github.com/aws/chalice/issues/900).

**Comment by kishaningithub** [comment]
Still an issue

**Comment by majkel-hyggio** [comment]
Any recommended substitute ?
