### ISSUE TITLE
Creating new rule for fixed response to specified listener

### ISSUE THREAD

**Issue by Gujarats** [aws/aws-cli#3479]
I have tried command below : 

```shell
aws elbv2 create-rule --listener-arn arn:aws:elasticloadbalancing:**** --priority 1 --conditions Field=path-pattern,Values='/img/*','more/path/*' --actions Type='fixed-response',FixedResponseConfig={MessageBody=string,StatusCode=503,ContentType=JSON}  --profile my-profile
```
Above command is creating new rule with `fixed-response` to return 503 response to specified path request.

but I got this as the response : 
```
Parameter validation failed:
Invalid type for parameter Actions[0].FixedResponseConfig, value: MessageBody=string, type: <type 'unicode'>, valid types: <type 'dict'>
Invalid type for parameter Actions[1].FixedResponseConfig, value: StatusCode=503, type: <type 'unicode'>, valid types: <type 'dict'>
Invalid type for parameter Actions[2].FixedResponseConfig, value: ContentType=JSON, type: <type 'unicode'>, valid types: <type 'dict'>
```

Any Idea where did I go wrong ? 

changing the `FixedResponseConfig={MessageBody=string,StatusCode=503,ContentType=JSON}` using `"` or `'` not working as the values.

**Comment by Gujarats** [comment]
Never mind I need to use `"` as a whole for `FixedResponseConfig={MessageBody=string,StatusCode=503,ContentType=JSON}` so the correct command is : 
```
aws elbv2 create-rule --listener-arn arn:aws:elasticloadbalancing:**** --priority 1 --conditions Field=path-pattern,Values='/img/*','more/path/*' --actions Type='fixed-response',FixedResponseConfig="{MessageBody=string,StatusCode=503,ContentType=JSON}"  --profile my-profile
```

**Comment by ecout** [comment]
This doesn't work in default config and modify-listener although the documentation for the syntax s the same. Why?

**Comment by rayman-g** [comment]
aws --region us-east-1 elbv2 modify-rule --rule-arn $RULE_ARN --actions \
'[{
  "Type": "fixed-response",
  "FixedResponseConfig": {
       "MessageBody": "string",
       "StatusCode": "503",
       "ContentType": "text/plain"
   }
}]'
