### ISSUE TITLE
AWS Code Build Error 255

### ISSUE THREAD

**Issue by swathirudra9** [aws/aws-cli#3489]
Hi,

I am getting the following error while executing the pipeline.

Error while executing command: aws cloudformation package --template template.yml --s3-bucket mycicdbucket --output-template template-expt.yml. Reason: exit status 255

If i am changing the CodeUri in cloud formation template.yml, it is working but while execution it is getting failed

**Comment by justnance** [comment]
@swathirudra9 - thank you for reaching out.  Without knowing the CLI version or seeing a —debug log, it's hard to tell why that's happening. I would say try first upgrading to the latest version of the CLI and re-test. If there is still an issue, please use the —debug option and post a sanitized debug log so we can look into this issue further. Thanks.
