### ISSUE TITLE
Feature Req: Support Authentication For Third-Party Commands

### ISSUE THREAD

**Issue by hikerspath** [aws/aws-cli#3490]
Going out on a limb here that I'm not the only one who has to login to multiple AWS accounts and every setup is different.  Some work on the older style access key/secret combination, while others are now enforcing MFA.  The hard part is getting the appropriate environment variables set in order to run other commands that use AWS libraries and default environment variables to function.

## Feature Request
I would like to have the option to authenticate and populate these environment variables inline with running a third-party command so that I don't have to manage STS tokens and could run something similar to:

```
$ aws --profile <my_profile> run <command> <command_options>
```

Effectively producing the following desired output if run against ``env``:
```
$ aws --profile development run env | grep '^AWS'
AWS_ACCESS_KEY_ID=AKSHHDUTYQ23TJBEBAB
AWS_DEFAULT_REGION=us-east-1
AWS_SECRET_ACCESS_KEY=LKF8hsjhe9sw728tGHDgj26523gauhgdggyfqffd+1
AWS_SESSION_TOKEN=AOIh92hsfs+kjh2876yqhj/sj8276yhbaggh2jghfja7u2hg+kjhfjahgdnqytdgzg276ehjsgaGHSDUYHjhff

$ env | grep '^AWS'
AWS_DEFAULT_REGION=us-east-1
```

## Goal
Place control of these environment variables in the hands of the people who are best at managing them while allowing rapid integration and use of AWS libraries and executables.

## Details
> aws-cli/1.15.59 
> Python/2.7.10 
> Darwin/17.7.0 
> botocore/1.10.58

**Comment by jamesls** [comment]
I agree this would be a good feature to have.  Out of curiosity what third party commands are you using that don't support the assume role configuration options used in `~/.aws/config`?

One of the issues that you'll run into with exporting these credentials in env vars is that these are temporary credentials, so they're eventually expire.  The nice thing about having built in support for temporary credentials in the AWS CLIs/SDKs is that we automatically handle refresh so if the credentials are about to expire we'll handle the refreshing details.

If you export env vars, the credentials could expire mid execution.  For example, if there was a third party command that did something similar to `s3 sync`, that command could take hours to run.  If your temporary creds expired mid-sync you'd get errors about expired credentials.

**Comment by hikerspath** [comment]
Totally missed this req, I am aware of the limitations, but for services like terraform which my team uses both in a CI/CD solution as well as local workstations, it becomes super useful option that (to-date) only `awsudo` does well.

**Comment by hikerspath** [comment]
Wierd, I don't remember unassigning anyone, isn't really my place to do that....

**Comment by tim-finnigan** [comment]
Hi @hikerspath, it looks like Terraform provides a few options for authenticating through AWS: https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication

Do those help you accomplish what you need to? Or did you have any updates you wanted to add to this feature request?
