### ISSUE TITLE
aws ec2 describe instance is not giving output,.. why it is happening ?

### ISSUE THREAD

**Issue by palakbadgujar** [aws/aws-cli#3496]
Hii Aws Team,
    
    Please help its an urgent call from my side...... i have wrote the following command :- 

aws ec2  describe-instances --filters "Name=launch-time,Values=August 8, 2018 at 4:15:54 P"
 And Following output is coming:-
{
    "Reservations": []
}

Please help to make it happen.

Thanks & Regards
    Palak

**Comment by jamesls** [comment]
Looks like the date format is wrong which is why you're not getting any data.  The date format needs to be iso8601, eg. "2018-08-08T16:15:54".

**Comment by palakbadgujar** [comment]
No this same problem occurring with different scenarios as :- 

Command:-  aws ec2 describe-instances

Response output:-

{
    "Reservations": []
}

Issue is that why it is giving empty response to me and the same code i am applying in the different users account so it is happly working for them is it my account problem or something else.

**Comment by justnance** [comment]
@palakbadgujar - thanks for your response.  is it possible you can check and compare the IAM policy attached to both user accounts?  and are you able to provide a screen shot of both scenarios so we can compare?  thanks!

**Comment by justnance** [comment]
@palakbadgujar - please see my response on #3988.
