### ISSUE TITLE
Feature Request: Default Region to "here" on EC2 when using IAM Role

### ISSUE THREAD

**Issue by rrehbein** [aws/aws-cli#3498]
Add defaulting the region to the EC2 instance's region, especially when using IAM Role.

```
aws sqs list-queues 
You must specify a region. You can also configure your region by running "aws configure".
```

In theory, this would reduce the need to add code to scripts such as `get_instance_region` in [AWS CodeDeploy Sample: common_functions.sh](https://github.com/aws-samples/aws-codedeploy-samples/blob/master/load-balancing/elb/common_functions.sh) if the defaulting was baked into the cli.

**Comment by jamesls** [comment]
I agree this would be useful.  There's a tracking issue over at https://github.com/aws/aws-cli/issues/486.  Initially there wasn't a whole lot of interest in the feature but it appears to be gaining momentum.  I'd suggest +1'ing the feature.
