### ISSUE TITLE
AWS CLI session timeout - aws ecr get-login - security concern

### ISSUE THREAD

**Issue by agerro** [aws/aws-cli#3500]
Background:
We are using AWS ECR for storage of our Docker images. In order for us to authenticate with each repository, we have "ecr-access" IAM users that also has an active access key. We use this access key for both human interaction and our CI systems. 
To authenticate, we run the command "aws ecr get-login" command in order to use the "docker ush command". Nothing special here.
But we notcied a "security concern" when we rotated the access keys connected to this user. After we had rotated the keys, we were still able to push images, using the old access key. I'm guessing this has to do with sessions connected to the CLI, but should't a rotated access key also mean that session connected to the old key should be revoked in some way?
Our intention with rotating the keys, are so that the old ones is not supposed to be used, not even for a shortperiod of time after they have been rotated.

We tested it by later on re-run "aws ecr get-login" with the new access key, and tried to push (which worked) then switching back to the old ones again (which then prompted us with the error "The security token included in the request is invalid.")

Scenario:
1. Obtain working credentials for a user being allowed to push images to an ECR repository, and store them in ~/.aws/credentials
2. aws ecr get-login (and run the outputted docker login command)
3. push image to repository and verify it being successfully pushed
4. rotate access key for this user, and verify it has been rotated
5. DON'T update credentials file with the new access key and secret
6. push new image to the same repository 
7. verify that the new image is in the repository (UNEXPECTED since it was possible to push with the old access key and secret).

Maybe this is/should be as it is, but I see it as a problem since a rotated access key shouldnt be able to be used at all, even if there is a session since before using the key and secret. 

Could anyone try this to verify that this is the same?
Should this really be how it works?

Ps. We are using both Docker and Docker-machine. But even if it is docker that keeps the session somehow, AWS should somehow enforce user to not be able to use an old session and/or access key/secret after they have been rotated.

Docker version: 18.03.0-ce
AWS CLI version: 1.11.86

**Comment by agerro** [comment]
Yes, it is an older version of aws cli so I'll try to reproduce it with the newest

**Comment by agerro** [comment]
The issue goes for aws-cli 1.15.75 too

**Comment by justnance** [comment]
@agerro - Thank you for reporting this and providing the details explanation.  This behavior is control by the service team and not the CLI.  I am notify our Service Team with an internal ticket but recommend reaching out to Premium Support or the AWS Forums for follow up.
