### ISSUE TITLE
Bad InvokeUrl Returned by `aws apigateway get-sdk`

### ISSUE THREAD

**Issue by marty-sullivan** [aws/aws-cli#3503]
I have an API gateway stage with a Custom Domain Basepath mapping. I am using IAM_AUTH on several methods and so I need to generate the SigV4 SDK for the API. When I run the following command:

    aws apigateway get-sdk \
        --rest-api-id 123456 \
        --stage-name prod \
        --sdk-type javascript \
        api-js-sdk.zip

I get back the JavaScript SDK zip file as expected. However, there is a small problem in the SDK code that is returned. in the file `apiGateway-js-sdk/apigClient.js` there is a variable defined that is named `invokeUrl` that points to my API stage's Invoke URL. However, it has been generated incorrectly. 

It should read:

    var invokeUrl = 'https://example.com';

But instead it reads:

    var invokeUrl = 'https://example.comnull';

I believe it is due to the fact that the BasePathMapping for the Custom API Domain does not include the stage name. Something internal to the AWS API is messing this up when generating the code.

If I remove the "null" from the invokeUrl, everything works fine. This is an extra step of automation that I have to write though, and it would be nice if this was fixed.

I imagine this is not directly related to the aws-cli but I felt this was the best place I could find to report the bug. Feel free to let me know if it should be submitted somewhere else.

**Comment by justnance** [comment]
@marty-sullivan - Thank you for reaching out.  I understand the point you have made here but was unable to reproduce the problem.  Please run the following and post the sanitized logs so we can look into what is happening:

```
aws apigateway get-sdk --rest-api-id 123456 --stage-name prod --sdk-type javascript api-js-sdk.zip --debug
```

**Comment by justnance** [comment]
@marty-sullivan - After a second look, I think the `--debug` is not going to provide much information to debug this issue.  We do not have control of the behavior of the API Gateway returned by the SDK.  I suggest reaching out to the [API Gateway forum](https://forums.aws.amazon.com/forum.jspa?forumID=199)s or to  [AWS Support](https://console.aws.amazon.com/support/home#/).
