### ISSUE TITLE
aws cli SSL certificate issue

### ISSUE THREAD

**Issue by palanibsm** [aws/aws-cli#3504]
I tried to setup aws s3 ls at my corporate who has proxy configured. I followed below:
1)  ~/.aws/config
[default]
region = ap-southeast-2
ca_bundle = cabundle-2018aug13.pem

2) cat ~/.bashrc
AWS_CA_BUNDLE=c/dev/apps/ca-certs/cabundle-2018aug13.pem
export HTTP_PROXY=http://proxy.companyname.com:12345
export HTTPS_PROXY=http://proxy.companyname.com:12345
export http_proxy=http://proxy.companyname.com:12345
export https_proxy=http://proxy.companyname.com:12345
export NO_PROXY=localhost,127.0.0.0/32,com.company.com

3) When I run 'aws s3 ls' I am getting this error I : [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
3.1) I got this cabundle-2018aug13.pem file from my corporate security team who has my company certificate which is valid. Just to know ca-bundle.pem will have only one certificate or multiple certificate. Do I have to get this from Aws or anyother source?
3.2) If my certificate seems valid, what else needs to be done?

Thanks 
Senthil

**Comment by justnance** [comment]
@palanibsm -  Thank you for reaching out and for your patience.  By default, the CLI uses SSL when communicating with AWS services.  For each SSL connection, the CLI will verify SSL certificates.  The CLI bundles a cacert.pem file used to validate SSL connections.  

Have you tried using the [`--no-verify-ssl (boolean)` option](https://docs.aws.amazon.com/cli/latest/reference/) to override the default behavior of verifying SSL certificates? 

Are there any sanitized debug logs you can share using the `--debug` option?

**Comment by justnance** [comment]
referencing #1545 and #864
