### ISSUE TITLE
aws S3 cp high CPU usage

### ISSUE THREAD

**Issue by alexbowers** [aws/aws-cli#3505]
![image](https://user-images.githubusercontent.com/842974/44091470-6c32db9a-9fc5-11e8-84c3-fc806dce20a2.png)

The CPU fluctuates hugely from ~ 10% to > 70% 

We are piping a large tar file to S3.

Below is the command we are using:

```
tar c files/ | aws s3 cp - "s3://.../file.tar"
```

Is there anything we can do to lower CPU usage, or is there anything the library can do to change how it uses the CPU?

I don't think memory is much of an issue, it seems to raise to ~ 18% then drop back to 16% and repeat. Never seems to increase above ~ 18%.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

```
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
stepping	: 1
microcode	: 0x1
cpu MHz		: 2199.998
cache size	: 30720 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
```

Aws version:

```
aws-cli/1.15.76 Python/2.7.12 Linux/4.4.0-130-generic botocore/1.10.75
```

**Comment by alexbowers** [comment]
The tar file we're transferring is being created on the fly - it does not exist on the disk, and the directory size we're tarring is ~ 160GB, so a large tar file is created too (note. no gzip is happening).

**Comment by alexbowers** [comment]
If you run with the debug flag on, it maxes out the CPU.

![image](https://user-images.githubusercontent.com/842974/44140953-9f996e0a-a073-11e8-878d-b3d70b518005.png)

**Comment by justnance** [comment]
@alexbowers - Thanks for reaching out and sorry for the delayed response.  I've been investigating this issue and trying to reproduce it.  I found this is issue is related to a few other GitHub threads: #2791, #2463, #2791, #333 and #355.  

I'm curious if this is still an issue when using the latest CLI version.

**Comment by justnance** [comment]
@alexbowers - Thank you again for reporting this behavior.  We need additional information to debug this issue further as I was unable to reproduce the same behavior.   

When the CPU spikes, is there any unusual network activity? i.e does the download speed drastically drop or does it completely stop transferring data entirely?

When the CPU spikes, does it appear the system 'hangs'?  See #1845

If an EC2 instance is in use, can you increase the Instance size with more CPU so the debug logs can be collected and then revert the EC2 Instance size after?  We're specifically looking for anything with ERROR that will indicate any errors that occurred during transfer. This will give us an idea of where to start looking.

To continue investigating this issue, please [upgrade to the latest version of the CLI](https://docs.aws.amazon.com/codedeploy/latest/userguide/getting-started-configure-cli.html) and let us know if there is any new information.

**Comment by alexbowers** [comment]
Sorry for the late response.

We no longer use aws-cli so I will be unable to test this further.

**Comment by Dabbrivia** [comment]
I am doing a simple sync of smallish (a few KB) files and I see consistent 90+% CPU utilization on the free tier Ubuntu instance with 621 Bytes/s reported on average. The files are transferred successfully. I'm happy to work with you to debug this.
