### ISSUE TITLE
feature-request: if credentials are passed as a profile argument to the command-line, override EC2 role settings

### ISSUE THREAD

**Issue by sallen42** [aws/aws-cli#3506]
I've got a use case where a box which has the CLI tools installed temporarily needs additional privs. It currently has a role assigned and is in production.

Security has asked me not to modify the role itself, and we cannot change the machine's role (production).

I don't want to have to stand up yet another aws cli tools instance (without a role), because I only need to do a minute's worth of work. I'd take more time to create the instance and ensure that it is secure/compliant with company policies than it would to make the changes on the CLI. Instead, I wanted to create a temporary API key on my account and use it to authenticate from the machine which has the CLI tools using MFA, which is within my company's security requirements.

I have been unable to make the CLI honor my credentials. It appears that since the machine has a role the requests are always using the role even when I specify a profile which has my API keys set. I'd like a way to ignore the role in the CLI tools if possible. Potentially this could be a change to precedence (use Role if nothing else is present, otherwise use specified credentials), or maybe it could be through a flag like --ignore-instance-role.

Thanks!

**Comment by diehlaws** [comment]
Thanks for reaching out about this @sallen42. The AWS CLI uses a provider chain to look for credentials in [different places](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence) - the instance profile is the final credential set the AWS CLI uses when it cannot find any other credentials in the provider chain. Can you give us some more details on how you're setting these temporary credentials on the instance and calling them from the CLI?

You should be able to specify your temporary API key either as the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, or by setting up a non-default profile with these API keys by running `aws configure --profile PROFILENAME` and then specifying that profile name when you're running the commands you want to run as this user.

If neither of the above suggestions work, can you provide the output for an `aws configure list` call from the instance on which you're seeing this behavior? Seeing the output for the same call using the profile configured with your temporary API keys would be helpful as well.

**Comment by sallen42** [comment]
Based on your notes we were able to figure out what we were doing wrong.

I think documentation improvement might be able to help here, but I don't at this point know what change I'd recommend, so I'll close this off. If I can come up with what I feel is a useful contribution on clarifying the documentation, I'll submit it as a separate issue.

Thanks a lot for your support!
