### ISSUE TITLE
Broken array access in query result for "aws iam list-roles" with "--output text"

### ISSUE THREAD

**Issue by alexfrere** [aws/aws-cli#3507]
This aws cli query to return an AuthorizedRole ARN started returning incorrect data on Aug 14-15, 2018:

QUERY: 
```
aws iam list-roles --output text --query 'Roles[?contains(RoleName, `'$our_role_name_var'`) == `true`]|[0].Arn'
```

EXPECTED RESULT: `arn:aws:iam::xxx:role/the-role-name-123`
ACTUAL RESULT: `arn:aws:iam::xxx:role/the-role-name-123 None`

Notes:
- Specifying `--output json` works as expected. 
- Specifying `--output text` and `...|[*].Arn` works as expected.

**Comment by justnance** [comment]
@peternann, Thanks for reaching out and for your patience.  Please provide additional details and explain what you are trying to do.  The query looks a little off and may be the reason it is returning 'None' which typically points out the use of query, text format, and [pagination](https://docs.aws.amazon.com/cli/latest/userguide/pagination.html). 

If you wanted to query for a specific name, try this query instead:  
`--query 'Roles[?RoleName==`Administrator`].Arn'`

Or if you wanted to see if contained a specific name you could do instead: 
'aws iam list-roles --query 'Roles[?contains(RoleName, `Admin`) == `true`]'.Arn --output text`

**Comment by peternann** [comment]
Ahhhh, why the random tag @justnance ?

**Comment by alexfrere** [comment]
Thanks @justnance - as you've suggested, removing the array pipe `|[0]` when using `--output text` does return just the ARN. I will update our query to this format.

**For some context:**

We use this query to iterate over the collection of AuthorizedRoles and return the ARN of the one that matches the the given name.

The reason for reaching out was that previously this query with the `|[0]` (as list-roles returns a list, so we pipe to access the single expected result from the array) returned just the ARN:
```
<ARN>
```
... however after Aug 14-15 it started returning:
```
<ARN>
None
```
... causing our deploy script to fail.

We found that the query with `|[0]` but using `--output json` returned just the ARN:
```
"<ARN>"
```
... however dropping the `|[0]` returns the list:
```
[
    "<ARN>"
]
```

So, with the change suggested this issue is resolved, however we did notice the behaviour of this query change as described above.

**Comment by justnance** [comment]
@alexfrere - Thank you for your feedback.  I have tested [pagination](https://docs.aws.amazon.com/cli/latest/userguide/pagination.html) options with query and text format to which I could reproduce with and without the 'None' result. 

Understanding pagination would be helpful for the type of querying being done here.  I would guess the query result hit a page or item limit around Aug 14-15 after which 'None' started to show up in the results.  I understand this issue is resolved however I wanted suggest trying out the ```aws iam get-role``` command as it might be more efficient.
