### ISSUE TITLE
delete amazon ses template from cli

### ISSUE THREAD

**Issue by igortas** [aws/aws-cli#3509]
Hi,

I'm following this link on amazon doc for deleting amazon ses email template, but when I hit amazon help to see all avail. options I don't see the flag delete-template:

https://docs.aws.amazon.com/cli/latest/reference/ses/delete-template.html

Can someone help me how to delete template from the cli?

BR,

**Comment by justnance** [comment]
@igortas - Thank you for your post.  Try the following CLI command and replace `<value>` with the name of the template:

`aws ses delete-template --template-name <value>`

**Comment by justnance** [comment]
great to hear
