### ISSUE TITLE
awscli rpm in Amazon Linux heavily outdated

### ISSUE THREAD

**Issue by webratz** [aws/aws-cli#3525]
Hi there,

I'm aware that you are probably not responsible for building the rpm for awscli within Amazon Linux but I wanted to bring this issue to attention.

Within the current Amazon Linux 2 the version of the awscli provided is 1.14.8-1.amzn2.0.3. This dates back to December 2017 and therefore misses many features and services.
Is there a way to trigger a release to get a more recent version?

(I know that there is always the virtualenv / pip method of installing, but if there is a package provided it should be up to date)

**Comment by justnance** [comment]
@webratz - thanks for reaching.  You are correct.  We do not have control over the rpm for awscli within Amazon Linux.  We also only support the virtualenv, pip or bundled [installation](https://docs.aws.amazon.com/cli/latest/userguide/installing.html).  

The version of the awscli on the Amazon Linux 2 is controlled by the AWS EC2 Linux team.  I would suggest contacting [AWS Support](https://console.aws.amazon.com/support/home#/) for additional follow up.  As stated in our [README](https://github.com/aws/aws-cli#getting-help), We try to reserve GitHub issues to CLI bugs and feature requests.

**Comment by webratz** [comment]
Also checked with AWS support they told me  that the service team is in the process of updating the awscli to the most recent version and we can expect a fix in the near future.
Therefore closing it.
