### ISSUE TITLE
Warn if `aws logs` calls are given timestamps very close to the epoch -- likely indicating someone calling with seconds since epoch, not milliseconds

### ISSUE THREAD

**Issue by sirosen** [aws/aws-cli#3526]
When we query our logs with `aws logs filter-log-events`, it's quite common to pass `--start-time` in the wrong units.
For example, we often see both new and experienced developers writing commands like this:
```
$ aws logs filter-log-events --log-group-name 'mygroup' \
    --start-time "$(($(date +%s) - 60))" --filter-pattern '"ERROR"'
```
and then being confused as the command is slow to return a result. And when it does come through, it will have all matching log events, not just those from "60 seconds ago".

I think it would be great if `aws logs` could shout a quick warning to stderr if `--start-time` or `--end-time` is really close to the epoch.
e.g.
```
$ aws logs filter-log-events --log-group-name 'mygroup' \
    --start-time "$(($(date +%s) - 60))" --filter-pattern '"ERROR"'

WARNING: `--start-time=1535571453` looks like an epoch time in seconds!
         `--start-time` should be in milliseconds.
```

This would need to be a customization for `aws logs` usage specifically, but it should be an easy enhancement.

**Comment by joguSD** [comment]
In general we don't do customizations like this on specific service parameters unless the parameter is significantly hindered without the customization. Considering the documentation is quite clear that the parameter is in milliseconds and passing seconds behaves similarly to just not passing the parameter at all, I don't think we would ever implement this.

**Comment by sirosen** [comment]
Thanks for the clear answer, at least. 👍
