### ISSUE TITLE
Add ability to register/deregister a directory for workspaces

### ISSUE THREAD

**Issue by farhank3389** [aws/aws-cli#3527]
There is no way to register a directory to be used with workspaces. This is the only manual step in the creating workspaces.

Manual method:
https://docs.aws.amazon.com/workspaces/latest/adminguide/register-deregister-directory.html

**Comment by justnance** [comment]
@farhank3389, Thank you for reaching out.  I understand your request and the registration and deregistration process of directory services.  The CLI is just exposing the APIs provided by the Directory Services and WorkSpace services.  For API issues and questions like this, the service team are the best people to respond. Let's move this question over to the [AWS Directory Service forums](https://forums.aws.amazon.com/forum.jspa?forumID=180) or you can contact [AWS Support](https://console.aws.amazon.com/support/home#/).

**Comment by farhank3389** [comment]
@justnance Thanks, I'll have a look at the forums
