### ISSUE TITLE
Please provide an official Docker Image with the AWS CLI for use in CI/CD scenarios

### ISSUE THREAD

**Issue by bert-laverman** [aws/aws-cli#3529]
I read Issue #3291 and saw it was closed, with the only reaction hinting it was 'not that complicated'. However, the comment also acknowledged that doing this yourself would run the risk of being out of date. Apart from exactly that point, I would also like to point out that, for commercial users, having an official Amazon image is hugely preferential to "<some-random-docker-hub-user>/aws-cli:latest".

In my case, I would be using this in a Kubernetes-based Jenkins setup, not with CodeBuild or the Beanstalk.

**Comment by justnance** [comment]
@bert-laverman - Thanks for reaching out.  Unfortunately, we are currently not looking to create docker images at this time.

**Comment by Rabadash8820** [comment]
All, this Issue is now being tracked at #3553. You should like that one to show your support and leave comments in that thread.
