### ISSUE TITLE
Requiring a 32 byte ascii key is a bug, it cannot have 256 bits of entropy of a real key.

### ISSUE THREAD

**Issue by rfielding** [aws/aws-cli#3533]
At this spot here, the AWS CLI requires a 32 byte string as a key.  A true, correctly-generated AES256 key has a one in 18 quintillion chance of being valid base64 (and a similar chance of being ascii).  This is because a true random AES key has each character take on a random value `0..255` uniformly, with 32 such bytes to make 256 bits.  If a true 32 bytes of randomness is converted to base64 to get printable ASCII characters, then truncating the (44) bytes of base64 of the real key to 32 bytes, then 64 bits of the key have effectively been chopped off.  In effect, you have a 192-bit AES key inefficiently represented in 256-bits; not an AES-256 key.

https://github.com/aws/aws-cli/blob/4ff0cbacbac69a21d4dd701921fe0759cf7852ed/awscli/customizations/s3/subcommands.py#L199

The current workaround is to supply a binary argument to `--sse-customer-key=fileb://theKey` to reference a key on disk.  Writing the key to disk may be worse than having a key that is effectively shortened to 192 bits.

In detail, I had started writing about it here:

https://github.com/aws/aws-sdk-go/issues/1726

The real, and backwards compatible, fix is to just look at the length of the key. 
- If it's length 32, then assume that it will be cast to a literal byte array.  In this case, even though an AES256 cipher is used, the key only has 192 bits of entropy.
- If it's 64 bytes and looks like hex, then it is hex (because it will decode to an arbitrary array of 32 bytes.  
- If it looks like base64, then decode it as base64 and verify that it's 32 bytes at that point.  It might be 44 bytes.  Some encoders include spurious `==` on the end.  What is important is that the base64 decode is 32 bytes.

The key is NOT a valid "string" in most languages.  It is a byte array.  In Golang, embedded null chars in strings are ok.  In other languages they are not.  But from Go, Java, etc, it is possible to generate keys with zeroes in them.  It should be possible to use all valid AES keys from the command-line; because real AES keys are completely random, with almost no chance that they will ever be printable ASCII.

Being printable ASCII, be warned that it's an approximately 192-bit key in reality.  ie: No high bit (low ASCII), no embedded nulls in string, no spaces, no tabs, no bell chars, etc.  Base64 is effectively `0..64` per character, rather than `0..255` of full bytes.

> 2^64 is 18quintillion.  Using an AES256 key that is known to be valid printable ASCII speeds up a brute-force search for the key by 18quintillion.  Also, if a user generated a real AES key, there is only a one in 18quintillion chance that it can be represented as valid base64.  So, keys properly generated cannot even be passed in unless they can be base64, or base16 (hexadecimal).  If the key is not length 32, we know unambiguously that we need to decode it.

**Comment by JordonPhillips** [comment]
Yeah, this should be modeled as a bytes type not a string. Thankfully this is only a problem for the high level s3 commands in the CLI.

**Comment by justnance** [comment]
@rfielding - Thank you for reaching out.  This issue has been fixed with #3612.  Please let us know if there are any questions.
