### ISSUE TITLE
cli get-media-for-fragment-list  aws: error: too few arguments

### ISSUE THREAD

**Issue by texano00** [aws/aws-cli#3536]
Hi everyone,

i've tried to use get-media-for-fragment-list command for many days but i always get `aws: error: too few argument`

Output of `aws --version`
`aws-cli/1.16.1 Python/2.7.15rc1 Linux/4.15.0-33-generic botocore/1.11.1`

The command that i'm tring to execute is 
`aws kinesis-video-archived-media get-media-for-fragment-list --stream-name hub --fragments "123" "1234" outfile a`

as described on https://docs.aws.amazon.com/ja_jp/cli/latest/reference/kinesis-video-archived-media/get-media-for-fragment-list.html#synopsis

Waiting for a fix,
Thanks

**Comment by justnance** [comment]
@texano00 - thanks for reaching out.  I was able to reproduce the issue and found a workaround:

```
aws kinesis-video-archived-media get-media-for-fragment-list --stream-name hub --fragments='["123","1234"]' outfile
```
It appears our documentation could be more clear.  Please test the command and advise if it worked.

**Comment by texano00** [comment]
Thanks @justnance 

Now, i receive 
`An error occurred (403) when calling the GetMediaForFragmentList operation: <AccessDeniedException>`

What policy do you have attached to your IAM user? AmazonKinesisVideoStreamsFullAccess seems not enough.

**Comment by justnance** [comment]
@texano00 - thanks for your feedback.  I agree this appears to related to an issue with IAM AWS Service policy.  Looks like Kinesis service may require [admin access](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/gs-account.htmll).   Typically when an http error returns, there is not an issue or bug with the CLI so you might want to reach out to [AWS Support](https://console.aws.amazon.com/support/home#/) to do a deeper understanding of the service.

Thanks.

**Comment by texano00** [comment]
@justnance  i've tried also to use root iam user but i get the same error from CLI.
It seems bugged `get-media-for-fragment-list`.

Waiting news.

**Comment by texano00** [comment]
Finally i've found the solution, we must pass the `--endpoint-url`.
 
In order to retrieve this endpoint the service to call is
`aws kinesisvideo get-data-endpoint --stream-name MY_STREAM_NAME --api-name GET_MEDIA_FOR_FRAGMENT_LIST`.

The output will be 
`{
    "DataEndpoint": "https://xxxx.kinesisvideo.eu-west-1.amazonaws.com"
}`.

Finally we can call the get-media-for-fragment-list passing the DATA_ENDPOINT as a new parameter.
 
`aws kinesis-video-archived-media get-media-for-fragment-list --stream-name hub --fragments='["1234"]' out.webm --endpoint-url DATA_ENDPOINT`
