### ISSUE TITLE
s3 cp stdout data corruption

### ISSUE THREAD

**Issue by gfody** [aws/aws-cli#3551]
**note: I am not using Powershell, these commands were run in cmd.exe**

```
>aws --version
aws-cli/1.16.10 Python/2.7.9 Windows/2012Server botocore/1.12.0

>aws s3 cp s3://my-bucket/file.dat.xz - | xzdec > file.dat
xzdec: (stdin): File is corrupt
download failed: s3://my-bucket/file.dat.xz to - [Errno 0] Error
fatal error:

>aws s3 cp s3://my-bucket/file.dat.xz - | 7z e -txz -si -so > file.dat
ERROR: Data Error : ~
download failed: s3://my-bucket/file.dat.xz to - [Errno 0] Error
```

if I use this simple program instead then it works fine
```
>s3p s3://my-bucket/file.dat.xz | xzdec > file.dat
(success)
```

comparing the output between the two programs it looks like the aws s3 cp command replaced every occurrence of `0A` with `0D0A` - is there a way to disable this behavior?

source code for s3p (AWSSDK 3.3.23.1)
```
using Amazon.S3;
using System;

class Program
{
    static void Main(string[] args)
    {
        using (var s3 = new AmazonS3Client())
        using (var stdout = Console.OpenStandardOutput())
        {
            var url = new Uri(args[0]);
            s3.GetObjectAsync(url.Host, url.PathAndQuery.TrimStart('/')).Result.ResponseStream.CopyToAsync(stdout).Wait();
        }
    }
}
```

**Comment by gfody** [comment]
FWIW in this case s3://my-bucket/file.dat.xz was uploaded via the multi-part upload api and so far I haven't seen this reproduced with files not uploaded in that way.

**Comment by fedir** [comment]
Could You compare the source of Your files ? https://superuser.com/questions/125376/how-do-i-compare-binary-files-in-linux

Probably, You will find some artefacts and it will help to understand the problem.

**Comment by gfody** [comment]
this I did, the differences were that line endings were converted (`0A` became `0D0A`) which corrupted the file as it is not text

```
>aws s3api head-object --bucket my-bucket --key file.dat.xz
{
    "AcceptRanges": "bytes",
    "ContentType": "binary/octet-stream",
    "LastModified": "Mon, 10 Sep 2018 01:32:51 GMT",
    "ContentLength": 128641484344,
    "ETag": "\"077882d4ddd6becfa99c3750d6e268d3-3834\"",
    "Metadata": {}
}
```

**Comment by gfody** [comment]
this only repro'd with aws.cmd not aws.exe, closing
