### ISSUE TITLE
Unable to set metadata on S3 objects

### ISSUE THREAD

**Issue by garnaat** [aws/aws-cli#356]
Setting metadata when putting a new object with the low-level `s3api` command, fails.  Trying to do so using the shorthand syntax results in:

```
'StringParameter' object has no attribute 'enum' 
```

and trying to use the JSON syntax gives:

```
AttributeError: 'dict' object has no attribute 'strip'
```

**Comment by tim-kos** [comment]
+1 for @rmatt to add the ability to insert meta data with `aws s3 cp`. We need this, too. What is the status on this?

**Comment by timvisher** [comment]
@rmatt @tim-kos Given that the OP was regarding the `s3api` subcommand, it might be best to open a new issue if you're looking to add support for arbitrary metadata to `s3 cp`.

The way I've done this in the past is to `s3 cp` the file to a staging bucket/key and then `s3api copy-object` it from there to where it should actually go with the correct metadata, and then `s3 rm` the temporary object. It's a little more work than a single `cp` operation but ¯\_(ツ)_/¯
