### ISSUE TITLE
No module named customizations

### ISSUE THREAD

**Issue by CaseyPeters** [aws/aws-cli#3565]
Using the `https://github.com/aws-samples/aws-codedeploy-samples/blob/master/load-balancing/elb/deregister_from_elb.sh` script for a few years now and all of a sudden when deploying to our staging instance we are running into this issue.

aws --v
`aws-cli/1.15.2 Python/2.7.13 Linux/4.9.91-40.57.amzn1.x86_64 botocore/1.10.2`

```
[stderr]ImportError: No module named customizations
[stderr]aws --region us-east-1 elbv2 describe-target-groups --names staging-http --query 'TargetGroups[*].[TargetGroupArn]' --output text
[stderr] * 3 failure(s), retrying in 9 second(s)
[stderr]Traceback (most recent call last):
[stderr]  File "/usr/bin/aws", line 27, in <module>
[stderr]    sys.exit(main())
[stderr]  File "/usr/bin/aws", line 23, in main
[stderr]    return awscli.clidriver.main()
[stderr]  File "/root/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 58, in main
[stderr]    driver = create_clidriver()
[stderr]  File "/root/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 68, in create_clidriver
[stderr]    event_hooks=session.get_component('event_emitter'))
[stderr]  File "/root/.local/lib/python2.7/site-packages/awscli/plugin.py", line 44, in load_plugins
[stderr]    modules = _import_plugins(plugin_mapping)
[stderr]  File "/root/.local/lib/python2.7/site-packages/awscli/plugin.py", line 61, in _import_plugins
[stderr]    module = __import__(path, fromlist=[module])
[stderr]  File "/root/.local/lib/python2.7/site-packages/awscli/handlers.py", line 21, in <module>
[stderr]    from awscli.customizations import datapipeline
```

**Comment by CaseyPeters** [comment]
Found out that running `sudo aws --v` was throwing the same exception. I manually uninstalled the aws cli and reinstalled it via
`sudo pip uninstall awscli` & `sudo pip install awscli` and that resolved my issue for now. I would still like to know why I had to do this but for me the :fire: is over.

**Comment by justnance** [comment]
@CaseyPeters - Thanks for reaching out and glad to hear the re-install resolved the problem.  It is hard to tell what caused the issue and what might have been wrong with the previous CLI installation.  Were there any changes to your CLI installation?
