### ISSUE TITLE
upload-part-copy --copy-source-range incorrect limit

### ISSUE THREAD

**Issue by gaul** [aws/aws-cli#3577]
`upload-part-copy --copy-source-range ` has incorrect documentation:

> You can copy a range only if the source object is greater than 5 GB.

This should be 5 MB.  I believe this comes from some AWS code generation so I cannot submit a pull request.

**Comment by kunallillaney** [comment]
@diehlaws Can you verify if this is indeed an issue or not? I still cannot get it to work for sizes <5GB

**Comment by diehlaws** [comment]
@kunallillaney This is purely a typo in the AWSCLI documentation for this command. You should be able to issue this command with a given `copy-source-range` value for an object that is larger than 5MB as shown below.

```
$ aws --version
aws-cli/1.16.93 Python/3.6.5 Darwin/16.7.0 botocore/1.12.83
$ aws s3api head-object --bucket kirby-footage --key aFolder/19mb.2.mp4
{
    "AcceptRanges": "bytes",
    "LastModified": "Tue, 21 Mar 2017 20:31:55 GMT",
    "ContentLength": 19425334,
    "ETag": "\"8883c95f6fd154513ea797dc4f40167e-3\"",
    "ContentType": "video/mp4",
    "Metadata": {}
}
$ aws s3api create-multipart-upload --bucket alex-crr --key 19mb.2.mp4
{
    "Bucket": "alex-crr",
    "Key": "19mb.2.mp4",
    "UploadId": "Wq0SbEFZK66dNIUsYquoV9V95eNkgGdnFjDGs2BS7z7vjMo0MxkEuM_49aQuhqscHHeERLMUFrnci47nfGp4iFZz2TYXLPSsXrvSqRsbe8hjCVAUwSZxTGFTQLmuLW6D"
}
$ aws s3api upload-part-copy --bucket alex-crr --key 19mb.2.mp4 --part-number 1 --upload-id "Wq0SbEFZK66dNIUsYquoV9V95eNkgGdnFjDGs2BS7z7vjMo0MxkEuM_49aQuhqscHHeERLMUFrnci47nfGp4iFZz2TYXLPSsXrvSqRsbe8hjCVAUwSZxTGFTQLmuLW6D" --copy-source kirby-footage/aFolder/19mb.2.mp4 --copy-source-range bytes=0-500
{
    "CopyPartResult": {
        "ETag": "\"460df1f042241d2336ed408d8cd54c69\"",
        "LastModified": "2019-01-23T19:00:08.000Z"
    }
}
```

**Comment by justnance** [comment]
adding a related AWS forum link:  [Unable to copy file more then 5GB in size](https://forums.aws.amazon.com/thread.jspa?threadID=58449)

**Comment by justnance** [comment]
@gaul - Thanks again for reporting this issue.  The [documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/upload-part-copy.html) has been updated with the corrected information:

> You can copy a range only if the source object is greater than 5 MB.
