### ISSUE TITLE
Read-only permission to log-group 

### ISSUE THREAD

**Issue by GieForce** [aws/aws-cli#3578]
Hello,

I'm currently struggling to setup to only have access on specified log groups, but I can only get access to them when I set my resource to "*". This is not possible when I setup this dedicated to predefined log groups. Does someone have a good practice or solution? When I try this solution beneath I only get 

> Not authorized to perform: logs:FilterLogEvents

when I try to access it via an user which is part of the IAM group "logs". Also when I try to perform this via the aws-cli I get a access denied on reading the log events of the cloudwatch log groups.

```{
{
        "Version": "2012-10-17",
        "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                    "logs:Get*",
                    "logs:List*",
                    "logs:FilterLogEvents"
                ],
                "Resource": [
                    "${aws_cloudwatch_log_group.web.arn}",
                    "${aws_cloudwatch_log_group.redis.arn}",
                    "${aws_cloudwatch_log_group.sidekiq.arn}"
                ]
            },
            {
                "Effect": "Allow",
                "Action": [
                    "logs:DescribeLogGroups",
                    "logs:DescribeDestinations"
                ],
                "Resource": "*"
            }
        ]
}

**Comment by justnance** [comment]
@GieForce, Thanks for reaching out.  [AWS Support](https://console.aws.amazon.com/support/home#/) would be the best resource for setup questions and best practices for AWS Services as we try to reserve GitHub issues to CLI bugs and feature requests.  After a quick review of the snippet, it appears there might be an issue with the ARN format:

```
                "Resource": [
                    "${aws_cloudwatch_log_group.web.arn}",
                    "${aws_cloudwatch_log_group.redis.arn}",
                    "${aws_cloudwatch_log_group.sidekiq.arn}"
```

Online documentation for an [Overview of Managing Access Permissions to Your CloudWatch Logs Resources ](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.htmll) has CloudWatch Logs Resources and Operations guidelines that might help.

**Comment by GieForce** [comment]
This is not working on every resource I try to fill in, also the same arn as in the AWS documentation is not working. Trying to configure it via the cli or amazon web UI gives the same error “Not authorized to perform logs: FilterLogEvents. Hopefully you can investigate this problem.

**Comment by justnance** [comment]
@GieForce - Thanks for the feedback.  This error and behavior is something that is controlled by the service API and not the CLI.  The CLI just calls the APIs we don't have anything to do with the functioning of the service. I would suggest opening a case with [AWS Support](https://console.aws.amazon.com/support/home#/) or reach out to the [.](url)

It is recommended to reach out to the Scaling team, which yo can file over at the [forums](
https://forums.aws.amazon.com/forum.jspa?forumID=138). Thanks!
