### ISSUE TITLE
aws cloudformation delete-stack fails when deleting a kinesis stream with registered consumers

### ISSUE THREAD

**Issue by prascuna** [aws/aws-cli#3580]
Hi there,
I'm using KCL 2, with Enhanced Fan Out enabled.
That means that, at startup, KCL will register a consumer into my kinesis stream.
Unfortunately, if I attempt to delete the stack, the operation fails because the stream still has a consumer attached.
Would it be possible to have an option to force the deregistration of consumers whenever a delete-stack is requested?

Here it is the error I get in the Events Log:
```
DeleteStream can?t delete ***** because there are consumers associated with this data stream. To delete ***** anyway, set the EnforceConsumerDeletion parameter to true to force the deletion of all the consumers that are associated with it. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceInUseException; Request ID: *****)
--
```

**Comment by itaimalek** [comment]
Is there any way to pass the --EnforceConsumerDeletion flag to cloudFormation ?
