### ISSUE TITLE
improvement - attempt to re-read credentials upon token expiration

### ISSUE THREAD

**Issue by fightingtexasaggie** [aws/aws-cli#3586]
I'm using a federated adfs account for access to AWS resources, as a hard requirement of my institution. As such, I generate temporary IAM credentials for use by the CLI tools, but they have a maximum validity of 12 hours. I have s3 file copy operations that take longer than 12 hours. The s3 copy utility fails if the credentials read at the beginning of the operation expire during the operation. Having the CLI tools re-read the credentials for any changes made during a running operation would allow me to keep the credentials updated and keep a long running process authorized.

**Comment by justnance** [comment]
@fightingtexasaggie - Thanks for reaching out. I understand the [12 hour](https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/) limit.  [AWS process creds](https://github.com/awslabs/awsprocesscreds) might be a good solution for your use-case.  What are your thoughts?
