### ISSUE TITLE
Is Windows CLI broken?

### ISSUE THREAD

**Issue by timwins** [aws/aws-cli#3591]
I looks like the Windows CMD CLI is returning the key instead of the value for queries. Same result for multiple commands. Works as advertised on Linux.
![clibroken](https://user-images.githubusercontent.com/43424282/45784779-e6155a80-bc1e-11e8-8883-824994a90a04.png)

**Comment by JordonPhillips** [comment]
CMD has different quoting rules than bash or powershell. If you replace those single quotes with double quotes it will work.
