### ISSUE TITLE
describe-subnets vpc-id wildcard filter not working

### ISSUE THREAD

**Issue by stilettk** [aws/aws-cli#3600]
Run the following command, no results are returned:
```
> aws ec2 describe-subnets --filters "Name=vpc-id,Values=*"
{
    "Subnets": []
}
```
However, the following command returns correct results:
```
> aws ec2 describe-subnets --filters "Name=subnet-id,Values=*"
```
Version info:
```
> aws --version
aws-cli/1.14.26 Python/2.7.9 Windows/8 botocore/1.8.30
```

**Comment by justnance** [comment]
@stilettk - Thanks for reaching out.  Please advise what the expected results were suppose to be for your first command.
```
aws ec2 describe-subnets --filters "Name=vpc-id,Values=*"
```

**Comment by stilettk** [comment]
@justnance Expected results are all subnets, because I query for all "vpc- id" values. If you are wondering why anyone would apply such filter, this is just an example of wildcards not working.

**Comment by justnance** [comment]
@stilettk - Thank you for your feedback.  After a deeper dive, it appears the [API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSubnets.html) is currently not passing wildcards to the CLI.  The CLI is only displaying the output returned by the service and does not have any control over this behavior.  This feature would be a request for the EC2 Service team.  It is recommended to reach out on the [AWS EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) or contact [AWS Support](https://console.aws.amazon.com/support/home#/).  Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.

**Comment by TiloGit** [comment]
fyi worked for me in tags: 

`aws ec2 describe-subnets --filters "Name=tag:Name,Values=MainDev-P*" --output text`

**Comment by synth** [comment]
Ha, luckily found this, it was all about the quotes!. Without quotes, doesn't work, with quotes it does. This does not seem to be documented and the documentation always shows without quotes form. 

![Screen Shot 2020-11-23 at 7 48 20 PM](https://user-images.githubusercontent.com/10546/100045500-daa4b780-2dc4-11eb-9b6f-f5d3aa7065b7.png)
