### ISSUE TITLE
Expose `hlsDiscSequence` parameter to mediatailor put-playback-configuration

### ISSUE THREAD

**Issue by thomas91310** [aws/aws-cli#3603]
We currently send HTTP requests to register and update our configurations to `mediatailor`.

The only thing preventing us from using the CLI to manage the configurations is because we don't have the ability to set `hlsDiscSequence` on the client side.

We usually set `hlsDiscSequence` parameter to `true` when calling [put-playback-configuration](https://docs.aws.amazon.com/cli/latest/reference/mediatailor/put-playback-configuration.html).
Unfortunately, this parameter is defaulted to `null` on the server side.

We can see the `hlsDiscSequence` parameter is set to `null` in the response when creating a configuration in the console:
#### Request payload:
```
{method: "PUT", path: "/v1/config/account/test", region: "us-east-1", operation: "PutConfig",…}
contentString: "{"originId":"test","originPrefix":"http://test.com","adDecisionServer":"http://test.com","slateURL":"","cdnContentSegmentURL":"","cdnAdSegmentURL":"","hlsManifestPrefix":"","dashManifestPrefix":"","sessionInitializationPrefix":""}"
headers: {Content-Type: "application/json; charset=utf-8",…}
method: "PUT"
operation: "PutConfig"
path: "/v1/config/account/test"
region: "us-east-1"
```

#### Response:
```json
{
    "adDecisionServer": "http://test.com",
...
    "hlsDiscSequence": null,
...
    "originId": "test", 
    "originPrefix": "http://test.com",
    "cdnAdSegmentURL": null,
    "dashManifestPrefix": "https://...", 
    "cdnContentSegmentURL": null,
    "awsAccountId": "..."
}
```

Would it be possible to:
- **if not sent from the CLI**, then `hlsDiscSequence` is set to `null`.
- **if sent from the CLI**, then `hlsDiscSequence` is set to the value passed (`true` & `false` being the only two possible values?)

**Comment by justnance** [comment]
@thomas91310 - Thanks for reaching out.  The CLI will only displaying the results returned by the service and does not have any control over this behavior.   It is recommended to reach out on the [Mediatailor forums](https://forums.aws.amazon.com/forum.jspa?forumID=270) or contact [AWS Support](https://console.aws.amazon.com/support/home#/) to submit a formal feature request to the service team.  Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.

**Comment by thomas91310** [comment]
It's worth mentioning here that the service **does** accept `hlsDiscSequence` as a parameter in the payload. The service does what we expect it to (if not set, default to `null`, otherwise assign to the value passed). The service also exposes the `hlsDiscSequence` parameter in the response, it just looks the aws-cli and the sdks ignore this parameter and don't return it to the users.
The cli and sdks don't expose this parameter either (when creating/updating configs) which results in the default value being assigned on the server side (which is `null` and in my case problematic).

I will ask my question on the mediatailor forums when I get approved to post a message.
However, I don't know if this is the right place either since the service already supports what we need it to support. It's just that the cli/sdks that don't leverage the ability to set this parameter (on the request side) and the ability to parse the parameter and return it to the users (on the response side).

**Comment by thomas91310** [comment]
just created https://forums.aws.amazon.com/thread.jspa?threadID=290523

**Comment by justnance** [comment]
@thomas91310 - Thank you for the feedback and reaching out to the forums.  You are correct about the service exposing the `hlsDiscSequence` parameter in the response.  What the service does not allow is the 'hlsDiscSequence` as an input parameter.  This feature would be a request for the service team.  Please note, the [API reference](https://docs.aws.amazon.com/mediatailor/latest/apireference) compared to the [CLI reference](https://docs.aws.amazon.com/cli/latest/reference/mediatailor/index.html#cli-aws-mediatailor):

Example PUT from the [API reference](https://docs.aws.amazon.com/mediatailor/latest/apireference/playbackconfiguration.html) also display how the API does not allow is the 'hlsDiscSequence` as an input parameter:
```JSON
{
  "AdDecisionServerUrl": "string",
  "CdnConfiguration": {
    "AdSegmentUrlPrefix": "string",
    "ContentSegmentUrlPrefix": "string"
  },
  "SlateAdUrl": "string",
  "VideoContentSourceUrl": "string",
  "Name": "string"
}
```

**Comment by thomas91310** [comment]
@justnance what you said wasn't exactly right but this has been answered by Alex here: https://forums.aws.amazon.com/thread.jspa?threadID=290523&tstart=0 
Thanks both and looking forward to a future release to make things easier on our end
