### ISSUE TITLE
Clear Instructions for ContainerService Permissions

### ISSUE THREAD

**Issue by vsoch** [aws/aws-cli#3604]
hey Amazon! 

We are trying to reproduce the [example shown here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth_http) in [this issue](https://github.com/singularityhub/sregistry-cli/issues/145#issuecomment-423769918) and my colleage is able to reproduce the 200 response (giving full permissions I believe to a user role) but I am trying to create an IAM profile and have tried many things, but have been unable to thus far. You can see the full response in the linked issue - can you provide guidance? I am writing a full instruction guide, the start of which you can [see here](https://github.com/singularityhub/sregistry-cli/blob/fix/aws/docs/clients/aws.md). I'd like to be able to walk the user from zero to working, including steps to:

 - create the new IAM user
 - assign the least number of required permissions
 - give the user a command (with curl) to ensure permissions are working properly (this is where it doesn't work for me yet)
 - then walk through the call via the client (likely with some updated code I will need to write to adjust any headers / expected challenges.)

Thanks in advance!

**Comment by justnance** [comment]
@vsoch - Thank you for reaching out and sorry for the delayed response.  I have reviewed GitHub issue [#145](https://github.com/singularityhub/sregistry-cli/issues/145) and pull request [#146](https://github.com/singularityhub/sregistry-cli/pull/146).  It appears the following documentation was used throughout the process of troubleshooting:

https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly
https://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicyExamples.html
https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_BatchGetImage.html

It appears you were able to find what was needed after this GitHub issue was generated which resulted in PR [#146](https://github.com/singularityhub/sregistry-cli/pull/146) resolving the issue.  I have also reviewed this GitHub issue with one of our documentation writers and would like to know if there are any specific gaps in our documentation that we can improve.  

To confirm, yes the CLI uses boto3 under the hood.

**Comment by vsoch** [comment]
Yep thanks muchly! Apologies for the lack of response, I didn't see the label as I should have.

**Comment by vsoch** [comment]
No robot, it's okay! We're good :)
