### ISSUE TITLE
Windows error handling broken

### ISSUE THREAD

**Issue by vishghelani** [aws/aws-cli#3608]
It looks like the newer versions of AWS cli do not seem to return errors correctly when running within a loop under the context of delayedexpansion enabled. 

To reproduce this issue, create a cmd file with the following contents and execute:

setlocal enabledelayedexpansion
if 1==1 (
aws s3 ls
echo !errorlevel!
)
The errorlevel should be displayed as 0

This is how it should work (aws cli 1.6.9)
![inkederrorhandlingworking_li](https://user-images.githubusercontent.com/43608244/46090439-9b5c8b00-c1a8-11e8-8ade-4c5434424b0b.jpg)

This is what happens with the latest version 1.16.21 (running the same test script):
![inkederrorhandlingnotworking_li](https://user-images.githubusercontent.com/43608244/46090447-a0213f00-c1a8-11e8-992c-15daaf2f80c7.jpg)

**Comment by justnance** [comment]
@vishghelani - Thanks for reaching out and for your patience.  I have reproduced this error based on the information provided.  In my second attempt, I was able to modify the `test2.cmd` file with the following:

```
aws s3 ls --debug
```

This provided CLI debug logs which shows the request send and response body.  It appears the CLI does not have control over the error returning from the test2.cmd.  If this is still an issue, please reply with the output using the [--debug option](https://docs.aws.amazon.com/cli/latest/reference/) so I can dig deeper into what is happening.

**Comment by vishghelani** [comment]
@justnance, its no longer an issue.
It seems seems using the call command in windows shell scripts against aws commands seems to resolve the error handling in newer versions of aws cli.

**Comment by justnance** [comment]
@vishghelani - Thank you for your feedback and glad it is resolved.  Closing issue.
