### ISSUE TITLE
put-bucket-inventory-configuration inconsistent with console

### ISSUE THREAD

**Issue by bmcgough** [aws/aws-cli#3611]
I am trying to configure a bucket to be inventoried and the inventory placed in a bucket in another account. This appears to be possible from the console, as when I apply this inventory configuration, I am given a policy to apply to the destination bucket and the inventory configuration is saved.

When I try to put this inventory configuration onto the bucket using aws cli, I am getting an error:
```
aws s3api put-bucket-inventory-configuration --bucket inv-test-bucket --id inv-test-id --inventory-configuration file://inventory_configuration.json 

An error occurred (InvalidS3DestinationBucket) when calling the PutBucketInventoryConfiguration operation: Bucket ARN should not specify a namespace.
```
inventory_configuration.json looks like (note that 'accountid' below is not the same account as owns the source bucket):
```
{
  "Destination": {
    "S3BucketDestination": {
      "Bucket": "arn:aws:s3::<accountid>:<destination-bucket>", 
      "Format": "CSV", 
      "Prefix": "inv", 
      "Encryption": {
        "SSES3": {} 
      }
    }
  }, 
  "IsEnabled": true, 
  "Id": "inv-test-id", 
  "IncludedObjectVersions": "Current", 
  "OptionalFields": [
    "LastModifiedDate",
    "StorageClass", 
    "Size", 
    "ETag", 
    "ReplicationStatus", 
    "IsMultipartUploaded", 
    "EncryptionStatus"
  ], 
  "Schedule": {
    "Frequency": "Daily"
  }
}
```
I guess it is also possible the console is wrong, and S3 inventory does not support cross-account destination buckets?

**Comment by justnance** [comment]
@bmcgough - Thank you for reaching out.  Can you check if the bucket policy has been [added to the destination bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html)?

**Comment by bmcgough** [comment]
No, the inventory configuration does not get applied to the bucket.

**Comment by justnance** [comment]
@bmcgough - Thank you for your feedback.  The (InvalidS3DestinationBucket) error in your first reply is an error that returns from the service to which the CLI does not have control over this behavior.   I suggest the following [practices for the destination bucket are in use:](https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-inventory.html)

- Contains the inventory file lists.
- Contains the manifest files that list all the file inventory lists that are stored in the destination bucket. For more information, see What Is an Inventory Manifest?
- Must have a bucket policy to give Amazon S3 permission to verify ownership of the bucket and permission to write files to the bucket.
- Must be in the same AWS Region as the source bucket.
- Can be the same as the source bucket.
- Can be owned by a different AWS account than the account that owns the source bucket.

Also, the [ARN format](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namespaces) appears to be correct as S3 does not require an account number or region in ARNs.  If this does not help solve the issue, I recommend reaching out to [S3 Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) or submitting a case to [AWS Support](https://console.aws.amazon.com/support/home#/).
