### ISSUE TITLE
awscli does not works with botocore 1.12.12 / boto3

### ISSUE THREAD

**Issue by yasra002** [aws/aws-cli#3614]
When i install boto3, it breaks awscli and it throws the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 17, in <module>
```

I suspect that it is because of botocore's version. When boto3 is installed, it upgrades `botocore-1.12.12` and after that awscli stops working. However after installing boto3, if I try to install awscli again, it downgrades the botocore to `botocore-1.10.82` and awscli starts to work again.

**Comment by justnance** [comment]
@yasra002 - Thanks for reaching out.  It sounds like using [virtual environments](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-virtualenv.html) might be a better practice if you are switching between versions.

Please show us the output of `PIP freeze` so we can get a better idea what is going on and can review the version of `urllib3`.  

What installation method used?  
Have you tried to do a complete uninstall and reinstall using PIP as per our [online documentation](https://docs.aws.amazon.com)?
