### ISSUE TITLE
Creating Iot rule to SQS Queue

### ISSUE THREAD

**Issue by toughthomas** [aws/aws-cli#3615]
`aws-cli/1.16.22 Python/2.7.15rc1 Linux/4.15.0-23-generic botocore/1.12.12`

When creating an iot rule to send mqtt messages to a sqs queue with aws cli, the rule does not work. I have to edit the sqs action manually and save it (without changing any settings) to make it work

**Comment by justnance** [comment]
@toughthomas - Thank you for reaching out.  It is hard to tell what is happening here.  Please reply with the specific command and arguments in use but add the --debug at the end.  If you can reply with the sanitized logs we can look into what is happening.  Thanks.
