### ISSUE TITLE
S3 cp from AWS to another compatible S3 Storage system

### ISSUE THREAD

**Issue by zoomphoto** [aws/aws-cli#3616]
With so many S3 compatible storage systems online, it would be nice to be able to cp or sync from S3 direct.  For example, I have three copies of each file.  1 each in S3, Wasabi and a local Minio installation.

Rather than copying the files from a local filesystem syncing to each, it would be nice to copy from S3 direct to Wasabi, or local Minio direct to S3 for example.

So:

# aws s3 sync /files/inventory/123 --profile local s3://files/inventory/123 --profile S3

Sort of like how on rclone you can specify the profile for source and destination.

Thanks,

**Comment by dstufft** [comment]
This direct copying isn't really possible without pulling the entire object down locally given the S3 API. I suppose this could be viewed at as a feature request for a flag that'll force the use of buffering files locally instead of using the copy API.
