### ISSUE TITLE
Issue a presigned URL and enforce tagging of the uploaded object

### ISSUE THREAD

**Issue by deceze** [aws/aws-cli#3617]
It doesn't seem to be possible to create a presigned URL, and ensure that the uploaded object is tagged a certain way?!

1. Creating an empty object first, tagging it, issuing a presigned URL and then uploading an object without tags erases the previously added tags.
2. Issuing a presigned URL with tagging parameters *allows* the uploader to tag the object, but it doesn't *require* it. It would be helpful if tags could be treated the same way as, say, the `Content-Type` header, which *can* be enforced when presigning.
3. Presigning POST URLs doesn't seem to support tagging at all.

I would like to use tags to organise certain lifecycles (filtering by tag), but let clients upload files directly, so I need to ensure those clients tag the files correctly or otherwise ensure those objects have the correct tags.

**Comment by dstufft** [comment]
Unfortunately there are too many AWS services for the individual SDK teams to be experts on all of them. Questions about the individual services are best asked on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) or usage questions can be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/aws-cli).

More information on getting help can be found [here](https://github.com/aws/aws-cli#getting-help).
