### ISSUE TITLE
aws cloudformation prints S3 upload progress to STDOUT

### ISSUE THREAD

**Issue by dnagir** [aws/aws-cli#3618]
When running `aws cloudformation package`, the output must not include the S3 upload progress.

It currently includes the combined output of the S3 file upload as well as packaged CloudFormation itself making it impossible to use via STDOUT.

See the full repro at https://github.com/dnagir/cf-package-stdout-messed-up

Workaround - use `--output-template-file` option.

**Comment by sanathkr** [comment]
Agreed. Progress should print to stderr. Care to submit a PR? Should be a quick one. 

I don’t consider this a breaking change because the progress bar was not something someone would take a dependency on.
