### ISSUE TITLE
cloudformation package does not resolve local files against the specified parent directory when FORCE_ZIP=true

### ISSUE THREAD

**Issue by rianwouters** [aws/aws-cli#3632]
If a template uses a local file in a lambda function or serverless function, 'cloudformation package replaces it by a temporary directory containing a copy of that file ('Resource.export''').

However, it considers that file to be located relatively to os.cwd(), i.e. it is not resolved against the Resource's parent path by is_local_file and copy_to_temp_dir, as - for example - upload_local_artifacts is doing (by make_abs_path)

Putting it differently: currently the parent_path can only be os.pwd()

**Comment by dstufft** [comment]
@sanathkr thoughts?

**Comment by sanathkr** [comment]
Yeah this is a general problem we are running with a command in SAM CLI as well. How do you resolve relative paths:

- relative to cwd
- relative to template
- relative to user specified directory 

We need to provide a extra arg to support third option. I am not opposed to this idea, but if someone was to implement this, we need to make sure the UX clearly distinguishes these three cases

**Comment by rianwouters** [comment]
See https://github.com/rianwouters/cfn-cli-plugin for a plugin-fix for this issue;

The simple fix is basically in this file:
https://github.com/rianwouters/cfn-cli-plugin/blob/master/package/search_path.py
