### ISSUE TITLE
Blob values must be a path to a file.

### ISSUE THREAD

**Issue by 80kk** [aws/aws-cli#3633]
I am trying to copy data to the Glacier Vault. This is my script:
```
#!/bin/bash
VAULT="vault-name"
NOW=$(date +%s)
IDFILE="archive-ids-vault-name-${NOW}.json"

for glacier_backup in /s3/*; do
  echo $'\n'"# $glacier_backup" >> $IDFILE
  aws glacier upload-archive --vault-name "$VAULT" --account-id - --archive-description "${NOW}/$glacier_backup" --body "$glacier_backup" >> $IDFILE
done
```

Source directory /s3 is a mounted s3 bucket I am copying from. The problem here is that the data structure in the bucket looks like:
first_dir/sub_dir/files.*
second_dir/files*
files*
Files have sometimes single extension, sometimes double and sometimes don't have extension at all.
Is there any option to override --body requirement?

**Comment by 80kk** [comment]
As a temporary workaround I have changed:
```
for glacier_backup in /s3/*; do
```
to:
```
for glacier_backup in /s3/* /s3/*/* ; do
```
However it adds some garbage ("# $glacier_backup") to the log file.

**Comment by justnance** [comment]
@80kk - Thank you for reaching out.  First to answer your question, "Is there any option to override --body requirement?" - not if it is required.  The `--body` requirement supports files and not directories.  It appears `"$glacier_backup"' is a directory and the CLI is working as expected.
