### ISSUE TITLE
aws s3 cp --recursive hangs on the last file on a large transfer to an instance

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [aws/aws-cli#3636]
aws s3 cp --recursive hangs on the last file on a large transfer to an instance and also the transfer speed is around half of the mbs that it normally is

I have confirmed that this works normally and as expected on version Linux/4.15.0-1021-aws

aws cli version where it doesn't work (Also the same with python3)
aws-cli/1.16.23 Python/2.7.15rc1 Linux/4.15.0-1023-aws botocore/1.12.13

Ubuntu version
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
eu-west-1 - ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180912 - ami-00035f41c82244dab

Package version
linux-aws:
  Installed: 4.15.0.1023.23
  Candidate: 4.15.0.1023.23
  Version table:
 *** 4.15.0.1023.23 500
        500 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     4.15.0.1007.7 500
        500 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by JoshuaEdwards1991** [comment]
This is still an issue - is anyone able to advise?

**Comment by justnance** [comment]
@JoshuaEdwards1991 - Thanks for reaching out.  It appears this issue might be related to #1775 and #1845.  Are you able to use the --debug option and post a sanitized debug log so we can look into this issue further?  Errors in the debug logs will indicate any errors that occurred during the transfer.

**Comment by JoshuaEdwards1991** [comment]
Sure I'll get that now

**Comment by JoshuaEdwards1991** [comment]
for anyone using ansible, this is how I rolled back to 21 version 

` - name: Removing awscli
   pip:
     name: awscli
     state: absent
 
 - name: Wait for sudo
   become: yes
   shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
 
 - name: remove aws kernel version
   become: yes
   apt:
     name: "{{ item }}"
     state: absent
   with_items:
     - linux-aws
     - linux-image-aws
     - linux-headers-aws
 
 - name: Wait for sudo
   become: yes
   shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
 
 - name: Pin aws kernel
   become: yes
   apt:
     deb: http://launchpadlibrarian.net/385721541/linux-image-aws_4.15.0.1021.21_amd64.deb
 
 - name: Wait for sudo
   become: yes
   shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
 
 - name: Pin aws kernel dependency
   become: yes
   apt:
     deb: http://launchpadlibrarian.net/385721540/linux-headers-aws_4.15.0.1021.21_amd64.deb
 
 - name: Wait for sudo
   become: yes
   shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
 
 - name: Pin aws kernel version
   become: yes
   apt:
     deb: http://launchpadlibrarian.net/385721538/linux-aws_4.15.0.1021.21_amd64.deb

 - name: Installing awscli
   pip:
     name: awscli`

**Comment by bendog** [comment]
I'm having this issue too.

**Comment by bendog** [comment]
large files are not working with cp or sync.
it seems to download the entire file but fails when it comes to completion.
could this be some form of checksum timeout on the AWS end?

**Comment by bendog** [comment]
I've resolved the issue by installing the ubuntu package for awscli rather than the python package.

**Comment by mrvisser** [comment]
Experiencing something like this on version:

`aws-cli/1.16.38 Python/2.7.15rc1 Linux/4.15.0-1023-aws botocore/1.12.28`

**Comment by JoshuaEdwards1991** [comment]
Something else to look at - https://bugs.launchpad.net/ubuntu/+source/linux-aws/+bug/1796469

**Comment by justnance** [comment]
@JoshuaEdwards1991 - Thank you for your feedback and patience.  This issue has been resolved with CLI version (aws-cli/1.16.38).  The problem was reproduced under CLI version 1.16.23 and 1.16.27 but has been fix under 1.16.38.  Please upgrade to the latest version.

**Comment by JoshuaEdwards1991** [comment]
Closing issue. You can track this bug here - https://bugs.launchpad.net/ubuntu/+source/linux-aws/+bug/1796469
