### ISSUE TITLE
template url support cloudformation deploy command

### ISSUE THREAD

**Issue by Guslington** [aws/aws-cli#3643]
In my scenario i am using a SAM template to package and deploy cloudformation to dev/staging/prod environments. When using the command `cloudformation package` i supply a s3 location to push my artefact to, and it generates a compiled cloudformation template which outputs as a local file. I then run `cloudformation deploy` to each environment providing the local file as well as a s3 location incase the local file is too large.

What i would like to happen is for `cloudformation package` to push the compile template to the same s3 location as the artefact and then in the `cloudformation deploy` step reference that s3 location to deploy that template to each environment. That way i'm not relying on the existence of a local file to update each environment.

**Comment by justnance** [comment]
Thank you for reaching out @Guslington.  @sanathkr , What are your thoughts?

**Comment by hauboldj** [comment]
Why not just add a `--template-url` parameter that can be an S3 object. This would be the same as `cloudformation update-stack` or `cloudformation create-stack` This wouldn't break anything currently.

**Comment by alekspickle** [comment]
It would be a great change to just have `--template-url` to a preuploaded template on a public bucket. Right now Im struggling with how do I even do this without having my template be named like a `bunch_of_random_numbers.json`

**Comment by timharris777** [comment]
I just submitted a PR with working code that accepts either a local path or s3 url to the cloudformation template with the `--template-file` option.

https://github.com/aws/aws-cli/pull/6409

**Comment by tim-finnigan** [comment]
Per [this comment](https://github.com/aws/aws-cli/pull/6409#issuecomment-1088579416) on that PR linked above, there is an `--s3-bucket` and `--s3-prefix` attribute that seems to address the use case for this issue. We have also been advised to start referring users to the [AWS SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) and [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html) command going forward for these types of use cases. Based on the above I think this issue can be closed but please let us know if there's anything further you would like to discuss here.
