### ISSUE TITLE
ECS waiter duration should be configurable

### ISSUE THREAD

**Issue by Puneeth-n** [aws/aws-cli#3644]
I was wondering if the `aws ecs wait ...` wait duration could be configurable.

**Comment by Puneeth-n** [comment]
A duplicate of https://github.com/aws/aws-cli/issues/2237

**Comment by justnance** [comment]
@Puneeth-n - Thank you for your feedback.  Let's use #2237 to track this feature request. The issue will be closed as a duplicate.
