### ISSUE TITLE
marketplace-entitlement endpoint does not exist in my region (us-west-2)

### ISSUE THREAD

**Issue by taylorjacklespriggs** [aws/aws-cli#3647]
I am trying to determine if I am subscribed to a product programmatically, but I run into the following issue when running `aws marketplace-entitlement get-entitlements`:
```
Could not connect to the endpoint URL: "https://entitlement.marketplace.us-west-2.amazonaws.com/"
```
I see that this endpoint exists in other regions (like us-east-1) so I will just be switching my region for now.

**Comment by justnance** [comment]
@taylorjacklespriggs - Thank you for reaching out.  I have confirmed the [CLI is not blocking the us-west-2 endpoint](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L930-L939).  It appears the service is not supported in the us-west-2 region.  If you would like this feature recommend reaching out to contact [AWS Support](https://console.aws.amazon.com/support/home#/).  If the service team approves and adds this feature it will be exposed from the API to the CLI.

**Comment by dvaldivia** [comment]
@justnance will `us-west-2` ever be supported?
