### ISSUE TITLE
s3api put-bucket-notification-configuration causes random failures

### ISSUE THREAD

**Issue by flybd5** [aws/aws-cli#3654]
I have an Ansible playbook that makes a shell call to the aws cli:

```
aws s3api put-bucket-notification-configuration --bucket {{ lambda_s3_bucket }} \
        --profile {{ lambda_profile }} --region {{ lambda_region }} \
        --notification-configuration file://ntemplate.json
```
The params are all correct, but I get totally random failures:

`fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": "aws s3api put-bucket-notification-configuration --bucket flaconi-testing-common-logs --profile testing --region eu-central-1 --notification-configuration file://ntemplate.json", "delta": "0:00:00.795407", "end": "2018-10-16 10:46:25.489599", "msg": "non-zero return code", "rc": 255, "start": "2018-10-16 10:46:24.694192", "stderr": "\nAn error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations", "stderr_lines": ["", "An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations"], "stdout": "", "stdout_lines": []}`

I don't understand what is causing this. 

```
$aws --version
aws-cli/1.16.30 Python/3.7.0 Darwin/18.0.0 botocore/1.12.20
```

**Comment by justnance** [comment]
Hello @flybd5 - Thank you for reaching out.  It is a bit difficult to understand what is happening here.  Please share a sanitized version of the contents in the ntemplate.json file.

**Comment by flybd5** [comment]
What is happening is that the call to the CLI succeeds about 80% of the time and fails 20% of the time. When it fails, Ansible retries 10 times and all 10 times the call fails.

```
"LambdaFunctionConfigurations": [{
"Id": "myESEvent",
"LambdaFunctionArn": "arn:aws:lambda:eu-central-1:123456789012:function:testing_s3_logging_to_es",
"Events": [ "s3:ObjectCreated:*" ]}]}
```

**Comment by flybd5** [comment]
Ok, so I've narrowed it down. My playbook creates a Lambda:

```
  lambda:
        name: "{{ lambda_name }}"
        region: "{{ lambda_region }}"
        profile: "{{ lambda_profile }}"
        role: "{{ lambda_role }}"
        handler: "{{ lambda_handler }}"
        runtime: python2.7
        zip_file: dist/Archive.zip
        state: present
        timeout: 180
        environment_variables: "{{ lambda_environment_vars }}"
      register: create_lambda_result
```

From create_lambda_result I get the ARN:

`create_lambda_result.configuration.function_arn`

I then use that to create the event in S3 that calls the Lambda:

```
- name: Setup the lambda event template for the S3 bucket
      shell: |
        echo '{"LambdaFunctionConfigurations": [{
                 "Id": "myESEvent",
                 "LambdaFunctionArn": "{{create_lambda_result.configuration.function_arn}}",
                 "Events": [ "s3:ObjectCreated:*" ]}]}' > ntemplate.json
      register: result
      failed_when: result.rc != 0
```
When I then use that to crete the S3 notification event here:

```
- name: Set the Lambda S3 notification to the bucket
      shell: aws s3api put-bucket-notification-configuration --bucket {{ lambda_s3_bucket }} \
        --profile {{ lambda_profile }} --region {{ lambda_region }} \
        --notification-configuration file://ntemplate.json --debug 2>>log.txt
      retries: 10
      delay: 1
      register: result
      until: result.rc == 0
```

...the call to the s3api fails, saying it cannot interpret the destination (the lambda ARN). That does't happen all the time, only intermittently, and the reason it happens is that when it fails, it's because for some weird reason the call to the lambda role has returned an ARN with a **version number** at the end of the ARN. That is not supposed to happen. Instead of getting this:

`arn:aws:lambda:eu-central-1:123456789012:function:testing_s3_logging_to_es`

I get this, for example:

`arn:aws:lambda:eu-central-1:123456789012:function:testing_s3_logging_to_es:6`

AWS Mikey don't like it, and barfs at me.

????

**Comment by justnance** [comment]
@flybd5 - Thank you for your feedback.  I am not able to reproduce this issue as we do not support Ansible.  The `ARN with a version number at the end of the ARN` is a [valid format](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-arns) however I understand it is not expected.  Please provide the sanitized contents of the `--debug 2>>log.txt` so we can dig a little deeper into what the CLI is doing and determine if there is a bug in the CLI.

**Comment by flybd5** [comment]
I need to clarify. What was happening is that the CLI was returning a version number of the lambda that did not exist. It's not an Ansible issue, I just mentioned it because I am calling the API with Ansible. All Ansible is doing is telling me what the call to the API returned. It happens very intermittently. I put the playbook in a loop and let it run for a full hour. Sometimes it returns one failure, sometimes it repeats until the session timer runs out.

**Comment by justnance** [comment]
@flybd5 - Thanks for your feedback and clarification.  The CLI will only displaying the results returned by the service and does not have any control over this behavior.  The CLI just calls the APIs we don't have anything to do with the functioning of the service.  I would suggest reaching out to the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) or contacting [AWS Support](https://console.aws.amazon.com/support/home#/).

**Comment by flybd5** [comment]
I have already spent hours with AWS support. They have no idea why this happens.

**Comment by justnance** [comment]
@flybd5 - Thanks for your feedback and patience.  I generated an internal ticket to our service team for a deeper dive into this issue.  Since I do not have access to your support case, I would suggest replying to your case to automatically reopen it and reference this GitHub issue.

**Comment by justnance** [comment]
@flybd5 - I've been collaborating with our internal service team about this issue.  Please reopen your support case and attached the debug logs so they can do a deeper dive into what is happening.  Thanks.

**Comment by flybd5** [comment]
Unfortunately, I have finished the contract with the company for whom I was doing the Ansible work and do not have access to the email or AWS accounts anymore. I still have the Ansible playbooks I wrote. best i can do is try them with my personal AWS account and see if I can replicate the issue. I will try this weekend and let you know how it goes.
