### ISSUE TITLE
aws_zsh_completer.sh uses an outdated version of _bash_complete

### ISSUE THREAD

**Issue by sblask** [aws/aws-cli#3655]
I just ran into a problem that I traced back to aws_zsh_completer.sh - see https://github.com/kislyuk/argcomplete/issues/258 - aws_zsh_completer.sh uses an outdated version of _bash_complete and there is an important fix in the upstream version - see discussion and fix here: https://github.com/kislyuk/argcomplete/issues/228#issuecomment-346003195 It would be great if that fix would be applied to aws_zsh_completer.sh as well. Or even better the copy paste be removed to be resilient against possible future changes. Otherwise maybe a switch on the ZSH version could be added if the copy paste is indeed necessary.

**Comment by joguSD** [comment]
@sblask Looking at the reasoning for re-defining that function I'm tempted to say we should just remove it. Not sure if it's worth having future versions of the CLI working around a bug in ZSH that was fixed five years ago, but I guess we'll have to do some research into how likely someone is using a really old version of zsh.

**Comment by sblask** [comment]
If I see this right, the line `complete -C aws_completer aws` does all the magic, doesn't it? So an alternative could also be to just change the README to say "if you are using ZSH version XYZ or below use aws_zsh_completer.sh otherwise just add `complete -C aws_completer aws` to your ~/.zshrc"
