### ISSUE TITLE
ec2 run-instance incorrect description for --user-data

### ISSUE THREAD

**Issue by epinault** [aws/aws-cli#366]
I am using aws cli 1.0.   Clearly the doc is incorrect. 

whatever is specified after --user-data is passed straight. If I encoded base64, they show base64 encoded on the server metadata as well . So if  I wanted to pass a file, I had to do the folllowing in order to get it to work

--user-data file:///path/to/the/file

It would be nice also to add an example to it

**Comment by poshest** [comment]
Seems like this is still a problem [here](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-RunInstances.html)

> -d, --user-data user_data
> The base64-encoded MIME user data for the instances....
