### ISSUE TITLE
Streaming uploads to Glacier

### ISSUE THREAD

**Issue by DemiMarie** [aws/aws-cli#3663]
I have an application (QubesOS system backups, in case anyone is wondering) that requires uploading **large** (tens of GB) encrypted files.

QubesOS executes a command in a specific VM to do the backup.  The command receives the data to be uploaded on standard input, and is not given the size of the data.  I would like to do a *streaming* upload to Glacier (cheap) that does not require buffering unlimited amounts of data.

If this is not currently supported, then this is a feature request to add support.  Otherwise, this is a feature request for documentation of how to do this.

**Comment by justnance** [comment]
@DemiMarie - Thank you for reaching out.  Have you worked with the `[upload-multipart-part](https://docs.aws.amazon.com/cli/latest/reference/glacier/upload-multipart-part.html)` with the `--range` option or does it not meet your use case?  

If not, your requirement would be a feature request for the service team as the CLI only displays results returned by the service.  It is recommended to reach out on the [Glacier forums](https://forums.aws.amazon.com/forum.jspa?forumID=140) or if you want to submit a formal feature request to the service team please contact [AWS Support](https://console.aws.amazon.com/support/home#/).  If the service team approves and adds this feature it will be exposed from the API to the CLI.

**Comment by DemiMarie** [comment]
I don't think it meets my needs.  Does it support reading from standard
input?

I don't know the size of my file in advance.  What I was looking for is a
command that automatically splits the stream into parts and uploads each
part separately.  That is, I want the CLI to submit multiple API requests
for each request on the command line.

On Oct 21, 2018 2:11 AM, "Nancy Alvine" <notifications@github.com> wrote:

@DemiMarie <https://github.com/DemiMarie> - Thank you for reaching out.
Have you worked with the [upload-multipart-part](
https://docs.aws.amazon.com/cli/latest/reference/glacier/upload-multipart-part.html
) with the --range option or does it not meet your use case?

If not, your requirement would be a feature request for the service team as
the CLI only displays results returned by the service. It is recommended to
reach out on the Glacier forums
<https://forums.aws.amazon.com/forum.jspa?forumID=140> or if you want to
submit a formal feature request to the service team please contact AWS
Support <https://console.aws.amazon.com/support/home#/>. If the service
team approves and adds this feature it will be exposed from the API to the
CLI.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aws/aws-cli/issues/3663#issuecomment-431641855>, or mute
the thread

**Comment by justnance** [comment]
Thank you for your feedback @DemiMarie.  I understand your use case better.  We already have a feature request for streaming standard input under #1280.  It would be better to track the progress under #1280 and close this issue.
