### ISSUE TITLE
How can I exit automatically when "eb deploy" reaches "(safe to Ctrl+C)"?

### ISSUE THREAD

**Issue by IsaiahJTurner** [aws/aws-cli#3667]
I am using the elasticbeanstalk cli to deploy my app and was wondering if there is a command line flag to automatically exit when the deploy process reaches "(safe to Ctrl+C)". I'm using the tool within a CI server and can not use the eb cli interactively. If not, can this feature be added? I have looked into patching `def stream_event(self, message, safe_to_quit=True)` so that it exits the process whenever that's called but not entirely sure how. Would love to have `eb deploy --quit-when-safe` or something.

I posted on this forum but nobody responded:
https://forums.aws.amazon.com/thread.jspa?threadID=291750&tstart=0

**Comment by justnance** [comment]
@IsaiahJTurner - Thanks for reaching out.  This repository for the AWS CLI.  The EB CLI is for a different project, please reach out to the elasticbeanstalk forums (https://forums.aws.amazon.com/forum.jspa?forumID=86) with your questions.

**Comment by IsaiahJTurner** [comment]
@justnance I did that but nobody replies.
