### ISSUE TITLE
Prompt out command from Get Login doesn't work

### ISSUE THREAD

**Issue by zhucebuliaolongchuan** [aws/aws-cli#3669]
https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html

`docker login` has already deprecated the `-e` shorthand config. But the command from `get login` prompt out still has it. This command would not work if you simply copy and paste them.

Suggestion: simple remove `-e none` might fix the problem

**Comment by justnance** [comment]
@zhucebuliaolongchuan - Thank you for reporting this.  I am labeling this issue as a feature request pending further testing and investigation.

**Comment by zhucebuliaolongchuan** [comment]
Thanks for the update!

**Comment by justnance** [comment]
@zhucebuliaolongchuan - After a second look, I found this request is referenced in #3374 which also references a workaround.  Currently we are _we are keeping it for backwards compatibility reasons as users may still be using an old version of docker that use it._

**Comment by zhucebuliaolongchuan** [comment]
I hear you and thanks for the update!

But would that be better if aws-cli team could make two versions of the prompt out commands, add some hints, prompt out proper command by detecting the version of docker or something like that. To make sure people who are using a newer version of Docker do not need to spend their time to figure out why the command is not working?

Thanks!

**Comment by justnance** [comment]
@zhucebuliaolongchuan - Thanks for your feedback.  There are some changes in the works under CLI v2 which we are tracking under issue #3587.
