### ISSUE TITLE
S3 Sync : Warning about skipping socket file despite --exclude that socket file

### ISSUE THREAD

**Issue by plittlefield** [aws/aws-cli#3671]
Why do I receive a warning message about a BackupPC socket file when I have specifically excluded it from the command line?

Command...

`/usr/local/bin/aws s3 sync --exclude "/home/backuppc/log/BackupPC.sock" --only-show-errors --storage-class STANDARD_IA /home/backuppc/ s3://myserver/home/backuppc/`

Output...

`warning: Skipping file /home/backuppc/log/BackupPC.sock. File is character special device, block special device, FIFO, or socket.`

Paul

**Comment by davido-bs** [comment]
Still an issue with 1.16.123.

**Comment by swetashre** [comment]
@plittlefield - Thank you for reporting the behavior. I was able to reproduce the issue and confirmed it as a bug.  This bug is being tracked under #1588. So closing this issue as a duplicate .
