### ISSUE TITLE
awscli breaks requests

### ISSUE THREAD

**Issue by laurence-hubbard** [aws/aws-cli#3672]
I installed the latest version of awscli using `sudo pip install awscli --upgrade` and it has caused my scripts to fail when attempting to import the `requests` library.

Steps to reproduce:
```
$ aws --version
aws-cli/1.16.39 Python/2.7.6 Linux/3.13.0-160-generic botocore/1.12.29

$ pip freeze | grep requests
requests==2.2.1

$ echo "import requests" | python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 92, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict
```

**Comment by joguSD** [comment]
When you did the upgrade you pulled in a version of `urllib3` that isn't compatible with the version of `requests` that you have installed.

See: https://github.com/urllib3/urllib3/issues/1456
https://github.com/requests/requests/blob/master/HISTORY.md#2200-2018-10-18

You'll need to either upgrade your version of `requests` to the latest (> v2.20.0) or install a lower version of `urllib3`. I don't think `urllib3==1.23` will have this issue.
