### ISSUE TITLE
aws ecr get-login --no-include-email doesn't work

### ISSUE THREAD

**Issue by icastilho** [aws/aws-cli#3675]
I'm getting erro when I try to loggin

AWS CLI commands:
`aws ecr get-login --no-include-email --region sa-east-1 --debug`

Error:
`An HTTP Client raised and unhandled exception: unhashable type: 'list'`

aws --version
`aws-cli/1.16.39 Python/2.7.15 Linux/4.15.0-36-generic botocore/1.12.29`

OS
Ubuntu 18.04.1 

Debug log

> 2018-10-23 15:25:50,134 - MainThread - botocore.httpsession - DEBUG - Exception received when sending urllib3 HTTP request
> Traceback (most recent call last):
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/httpsession.py", line 246, in send
>     conn = manager.connection_from_url(request.url)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/urllib3/poolmanager.py", line 271, in connection_from_url
>     pool_kwargs=pool_kwargs)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/urllib3/poolmanager.py", line 219, in connection_from_host
>     return self.connection_from_context(request_context)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/urllib3/poolmanager.py", line 232, in connection_from_context
>     return self.connection_from_pool_key(pool_key, request_context=request_context)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/urllib3/poolmanager.py", line 245, in connection_from_pool_key
>     pool = self.pools.get(pool_key)
>   File "/home/icastilho/miniconda2/lib/python2.7/_abcoll.py", line 382, in get
>     return self[key]
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/urllib3/_collections.py", line 53, in __getitem__
>     item = self._container.pop(key)
>   File "/home/icastilho/miniconda2/lib/python2.7/collections.py", line 155, in pop
>     if key in self:
> TypeError: unhashable type: 'list'
> 2018-10-23 15:25:50,135 - MainThread - botocore.hooks - DEBUG - Event needs-retry.ecr.GetAuthorizationToken: calling handler <botocore.retryhandler.RetryHandler object at 0x7fad7c26a0d0>
> 2018-10-23 15:25:50,135 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
> Traceback (most recent call last):
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/awscli/clidriver.py", line 207, in main
>     return command_table[parsed_args.command](remaining, parsed_args)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/awscli/clidriver.py", line 344, in __call__
>     return command_table[parsed_args.operation](remaining, parsed_globals)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
>     return self._run_main(parsed_args, parsed_globals)
>   File "/home/icastilho/miniconda2/lib/python2.7/site-packages/awscli/customizations/ecr.py", line 72, in _run_main
>     result = ecr_client.get_authorization_token()
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/client.py", line 610, in _make_api_call
>     operation_model, request_dict)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
>     return self._send_request(request_dict, operation_model)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 136, in _send_request
>     success_response, exception):
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
>     caught_exception=caught_exception, request_dict=request_dict)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
>     if self._checker(attempts, response, caught_exception):
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
>     caught_exception)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
>     return self._checker(attempt_number, response, caught_exception)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
>     caught_exception)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
>     attempt_number, caught_exception)
>   File "/home/icastilho/.local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
>     raise caught_exception
> HTTPClientError: An HTTP Client raised and unhandled exception: unhashable type: 'list'
> 2018-10-23 15:25:50,136 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

**Comment by justnance** [comment]
@icastilho - Thanks for reaching out and providing the `--debug` output.  I'm trying to reproduce this issue.  What docker version are you using?
