### ISSUE TITLE
apigateway update-api-key is only changing the name in the console but not internally ?

### ISSUE THREAD

**Issue by Private-SO** [aws/aws-cli#3677]
Steps to reproduce 

1. Create a apigateway API key with aws console with a NAME(i.e.Version1).
2. Update the API key name with below command

 aws apigateway update-api-key --api-key sNvjQDMReA1eEQPNAW8r37XsU2rDD7fc7m2SiMnu --patch-operations op='replace',path='/name',value='Version2'

After running this command we can see the NAME of the API Name is changed in the console. But the API Id and API key remains the same. 

3. Run the same thing using CFN template 

```
     ApiKey: 
   Type: AWS::ApiGateway::ApiKey
   Properties: 
    Name: "Version1"
    Description: "CloudFormation API Key V1"
    Enabled: true
```
4. Which will create a API key with name `Version1` and update the Name to `Version2` and again deploy the template. As soon as you deploy the template we can see the API ID and API Key got changed. 

Why is the difference ? Both aws-cli and CFN are doing same things , i even deploy the API after aws-cli command .

Thanks
Any help is appreciated

**Comment by diehlaws** [comment]
Hi @Private-SO, thanks for reaching out to us. The behavior you are describing is expected from API Gateway's [`apikey:update`](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/apikey-update/) API call. Using the `update-api-key` command in the CLI to only update the name of the API key as shown in the provided command will keep the key's ID and Value as is, and will only change the name of the key in question. 

By contrast, when you create a CloudFormation stack with the provided template and deploy it, then modify the template to update the key's name and deploy it again, CloudFormation is not updating the API key's name but rather replacing the API key altogether. You can see this behavior take place in the Events tab of your CloudFormation stack after deploying it a second time - there is an 'update' event that actually creates a new API Key with a different ID from the key created in the first deployment, then a delete event that removes that first API Key with the original ID. This is why you see a different ID and Value for the API Key when redeploying your CloudFormation stack.

**Comment by justnance** [comment]
@Private-SO - Unfortunately we have not heard back from you. This issue may close this week due to inactivity.  Please review the last response from @diehlaws and let us know if there new questions or concerns.

**Comment by Private-SO** [comment]
Sorry for very late response @diehlaws  and @justnance . 

Thanks for detailed explanation on this issue.
