### ISSUE TITLE
aws ec2 describe-instances --filters tag: seems to be not working (or docs is missing/misleading)

### ISSUE THREAD

**Issue by zasran** [aws/aws-cli#368]
Trying to use aws ec2 describe-instance (version 1.1.0) with tag: filter which is mentioned in docs at http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html but it doesn't seem to be working.

Quote from documentation: "tag: --filters the response based on a specific tag/value combination."

Tried several formats (just guessing, trying format used by http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-DescribeInstances.html) but no luck.

This does not complain but returns no instances:

aws ec2 describe-instances --filters Name=tag:,Values=Name=ADS-prod-ads

This one fails:

aws ec2 describe-instances --filters tag:Name=ADS-prod-ads
Unknown key 'tag:Name' for parameter --filters, valid choices are: Values, Name

Just for reference, using tag-value works (just to show that tag Name=ADS-prod-ads exists):

aws ec2 describe-instances --filters Name=tag-value,Values=ADS-prod-ads | jq '.Reservations[].Instances[].Tags[]'
{
  "Key": "Name",
  "Value": "ADS-prod-ads"
}

**Comment by jbehl** [comment]
Alright, this wasn't obvious, from the above, so hopefully it'll help somebody.  This lists in a nice table format some useful fields including the Name tag (if you use that).

aws ec2 describe-instances --query 'Reservations[].Instances[].[ InstanceId,[Tags[?Key==`Name`].Value][0][0],State.Name,InstanceType,Placement.AvailabilityZone ]' --output table

**Comment by myoung34** [comment]
``$ aws ec2 describe-instances --filter Name=tag:Role,Values=cache`` for those who stumble here

**Comment by samizzo** [comment]
The help is still super confusing about the tag filter. It says:

`o tag :key =*value* - The key/value combination of a tag assigned to the resource.`

which seems to suggest that you can do:

`--filters Name=tag:SomeKey=SomeValue`

which of course is not correct.

**Comment by flipy** [comment]
If anyone has a hard time figuring it out how to sort tags, following command works for me:
`aws ec2 describe-instances --output json --query "Reservations[*].Instances[*].{ID:InstanceId,Type:InstanceType,Name:Tags[?Key=='Name'].Value}"`

**Comment by dfroberg** [comment]
If you need to include tags with a : in them you need to quote, i.e.
`aws ec2 describe-instances --region us-west-2 --filters Name=tag:"aws:autoscaling:groupName",Values=yourautoscalegroupname`

**Comment by BarthesSimpson** [comment]
I too was stymied by the impenetrable and misleading documentation on this.

**Comment by brandonowings** [comment]
I was trying to figure out how to get the IP address of an instance based on a tag (in this case, "Name"). I tried a few different things with --query and --filters, but it seems that getting from one nested parameter to another is complicated, or maybe not possible just using one or the other approach. Combining --query and --filters did the trick:
```
aws ec2 describe-instances --filters Name=tag:Name,Values="Instance Name" --query 'Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddresses[].PrivateIpAddress' --output text
```

**Comment by adeelx** [comment]
This comes up at the top when I search for `ec2.instances.filter()`, to filter instances programmatically.

---

Here's how you would achieve this:
(Find all instances that have tag `Name` and the tag value starts with `api-`)

```python
import boto3

ec2 = boto3.resource('ec2')

for instance in ec2.instances.filter(Filters=[{'Name': 'tag:Name', 'Values': ['api-*']}]):
    print instance
```

**Comment by myoung34** [comment]
@adeelx for Python sure but the issue is with the bash awscli usage

**Comment by sharand** [comment]
Below command works for me
```
aws --version
aws-cli/1.11.81 Python/3.4.3 Linux/3.13.0-74-generic botocore/1.5.44
aws ec2 describe-instances --filters Name=tag:App,Values="value" --query 'Reservations[].Instances[].[Placement.AvailabilityZone, State.Name, InstanceId,InstanceType,Platform,Tags.Value,State.Code,Tags.Values]' --output table
```

**Comment by kiyanwang** [comment]
I wanted to filter my instances to those that had a specific prefix in the Name tag, and then ensure that in the output table the Name was listed, the only way to achieve that seems to be to use a `join()` to flatten the list into a string:

```
aws ec2 describe-instances --filters "Name=tag:Name,Values=talis*" --query 'Reservations[].Instances[].[InstanceId,PublicDnsName,State.Name,InstanceType,join(`,`,Tags[?Key==`Name`].Value)]' --output table
```

**Comment by benofben** [comment]
I had similar issues and it was quite a struggle to get to this:
`aws ec2 describe-tags --region ${region}  --filter "Name=tag:Name,Values=*Rally" "Name=resource-id,Values=$instanceID"
`

**Comment by tolidano** [comment]
5 years later, and that same terrible example is still in the documentation, and a better example still doesn't exist.

**Comment by jonathanwcrane** [comment]
My Google search for how to use filters with the describe_* API calls has led me here, and I can't help but shake my head after reading @tolidano 's last comment.

**Comment by thalesac** [comment]
In case you need to filter by the tag key only, you can do something like `ec2-describe-tags --filter "resource-type=instance" --filter "key=hostname" --filter "resource-id=$(ec2metadata --instance-id)" | awk '{print $5}'`

Or simply use the `--filter "key=<KEY>"`

**Comment by Sureshhm** [comment]
I'm looking to get ec2 platform type i.e. (Windows or Linux) using the lambda function filters. In case if anyone has done it could you please share the same

**Comment by sebsto** [comment]
'Windows' is returned by the "Platform" field for Windows instances.  None is returned for Linux instances.  The query at the top of this thread still works today.

`aws ec2 describe-instances --query 'Reservations[].Instances[].[Placement.AvailabilityZone, State.Name, InstanceId,InstanceType,Platform,Tags.Value,State.Code,Tags.Values]' --output table`

**Comment by cjyothi** [comment]
> To filter on all instances that have a tag with a name or key of `Name` AND a value of `ADS-prod-ads`, you would do this:
> 
> ```
> aws ec2 describe-instances --filter Name=tag:Name,Values=ADS-prod-ads
> ```

if need exactly instance name 
aws ec2 describe-instances --filter Name=tag:Name,Values=devschemareg01 --output text | sort | grep Name | awk '{print $3}'

**Comment by aksgithub** [comment]
Sharing what i have used:
```instance-id = curl --silent http://169.254.169.254/latest/meta-data/instance-id 2>&1
aws ec2 describe-tags --region us-west-1 --filters Name=resource-id,Values=[instance-id] Name=tag:aws:cloudformation:stack-name,Values=[“my_stack_name"]```

**Comment by javapapo** [comment]
```bash
aws -ec2 describe-instances --filters Name=tag:<YOUR_TAG>,Values="<YOUR_VALUE>" --query 'Reservations[].Instances[].[Placement.AvailabilityZone, State.Name, InstanceId,InstanceType,InstanceLifecycle,Tags[?Key==`<YOUR_RAG`]|[0].Value]'  --output table
```

**Comment by chalamchala-od** [comment]
> Trying to use aws ec2 describe-instance (version 1.1.0) with tag: filter which is mentioned in docs at http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html but it doesn't seem to be working.
> 
> Quote from documentation: "tag: --filters the response based on a specific tag/value combination."
> 
> Tried several formats (just guessing, trying format used by http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-DescribeInstances.html) but no luck.
> 
> This does not complain but returns no instances:
> 
> aws ec2 describe-instances --filters Name=tag:,Values=Name=ADS-prod-ads
> 
> This one fails:
> 
> aws ec2 describe-instances --filters tag:Name=ADS-prod-ads
> Unknown key 'tag:Name' for parameter --filters, valid choices are: Values, Name
> 
> Just for reference, using tag-value works (just to show that tag Name=ADS-prod-ads exists):
> 
> aws ec2 describe-instances --filters Name=tag-value,Values=ADS-prod-ads | jq '.Reservations[].Instances[].Tags[]'
> {
> "Key": "Name",
> "Value": "ADS-prod-ads"
> }

aws ec2 describe-instances --filter Name=tag:costcenter,Values=30056 --query 'Reservations[*].Instances[*].BlockDeviceMappings[*].Ebs' | grep VolumeId

**Comment by altif227** [comment]
I've used below filters to get the list of instances with public IP and their respective name usign --filter options and it works fine.

aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" "Name=tag:OS,Values=AMAZON/LINUX2" --query "Reservations[].Instances[].[PublicIpAddress, Tags[?Key=='Name'].Value|[0]]" --output table

**Comment by vaibhavg2510** [comment]
I have used below query to get AZ, InstanceType, Name, PrivateIpAddress, PublicIpAddress and state of the running ec2 instances:

aws ec2 describe-instances --query 'Reservations[*].Instances[*].{State:State.Name,PublicIpAddress:PublicIpAddress,InstanceType:InstanceType,PrivateIP:PrivateIpAddress,AZ:Placement.AvailabilityZone,Name:Tags[?Key==`Name`]**|**[0].Value}' --output table **| grep -i "ignoredCaseNameOfEc2Instance"**

To filter the details by name, i am using grep with -i option to have case-insensitive search.

P.S. : While writing command, i was mostly struggling with the pipe operator highlighted. (might be helpful for someone struggling with the command)

**Comment by tripleee** [comment]
Bump. The `--filter "Name = tag:Name, Values = ..."` syntax is still not obvious from the documentation. I literally googled for 15 minutes until I found this issue which finally showed how to do this.

**Comment by bisdavid** [comment]
I spoke with the EC2 writers about this.  They told me that they would work on an example to clarify this.  In the interim, the syntax is documented in the EC2 User Guide here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#Using_Tags_CLI

I hope this helps!

**Comment by henderjm** [comment]
I'm the latest victim I think that had to come here to get my answer. Are the plans to consolidate the docs still existing?

Even a link from the API page to the above comments link (or maybe at this stage this repo) would be beneficial.

**Comment by bisdavid** [comment]
I'm sorry, I've moved to a new role and no longer work in this space.  I'll pass your comments on, however.

**Comment by john-aws** [comment]
Please also add documentation for how you can filter on absence of a value, for example:

    aws ec2 describe-addresses --filters "Name=association-id,Values=xxx"

What should you indicate in place of `xxx` for 'absence of association ID'? It's not any spelling of null, none, undefined, or empty string. Or is the only option here to use a `--query` client-side?
