### ISSUE TITLE
error launching EMR cluster with configs on S3

### ISSUE THREAD

**Issue by dmenin** [aws/aws-cli#3686]
Running the command below (example from the [aws ](https://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html#examples) page)

> aws emr create-cluster --release-label emr-5.9.0 --service-role EMR_DefaultRole --ec2-attributes InstanceProfile=EMR_EC2_DefaultRole --instance-groups s3://mybucket/instancegroupconfig.json

issues the error:
```
Error parsing parameter '--instance-groups': Expected: '=', received: ':' for input:
s3://mybucket/instancegroupconfig.json
```

tried on windows cmd and on the Cygwin Terminal
also tried quotes around the parameter and "=" as the message indicates

**Comment by justnance** [comment]
@dmenin - Thanks for reaching out.  There is a feature request for this issue under #3228.  The work around is to use https:// or file:// to get the contents of the file.   I will label this issue as a duplicate so we can track the work under #3228 and avoid confusion or duplicate efforts.
