### ISSUE TITLE
S3 sync download fails for *.xls files with size greater than 8MB.

### ISSUE THREAD

**Issue by M-S-Saurabh** [aws/aws-cli#3690]
I am using AWS S3 cli's sync utility to download file from S3 bucket. I have a profile defined in config file. The sync function downloads all files (of types .xlsm, .xlsx etc.) but it fails on .xls files and that too on files exceeding a certain size.
Then I came across this [issue](https://github.com/aws/aws-cli/issues/3329). So I experimented with the configuration options listed [here](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html). 
The issue was resolved once I set the `multipart_threshold` option to more than the files' size.(25MB).
The command I was using is 
`aws s3 sync --no-verify-ssl "s3://<bucket-name>/data/<folder-name>" .  --profile <profile-name>`

I think the error occurs when the utility tries to chunk XLS files.

**Comment by JordonPhillips** [comment]
So you're seeing closed connections when using small chunk sizes, but not large ones? What specific errors are you seeing?
