### ISSUE TITLE
aws ec2 describe-instances randomly returns key-value or value key

### ISSUE THREAD

**Issue by dywanik** [aws/aws-cli#3691]
I'm performing the following query:

`$ AWS_DEFAULT_REGION=eu-west-2 aws ec2 describe-instances --filter "Name=private-ip-address,Values=10.44.10.166" | grep Environment -C 2`

sometimes I receive
                        `{
                            "Value": "production",
                            "Key": "Environment"
                        },`
and sometimes
                      `{
                            "Key": "Environment",
                            "Value": "production"
                        },`
Probably the issue occurs for other key/value pairs as well. Also, it seems it's completely random.

My OS: `Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1038-aws x86_64)`
`$ aws --version
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1038-aws botocore/1.4.70`

Note: for Amazon Linux everything works fine
`$ aws --version
aws-cli/1.11.132 Python/2.7.12 Linux/4.9.51-10.52.amzn1.x86_64 botocore/1.5.95`

**Comment by dywanik** [comment]
More clues. The whole returned sequence is mismatched from time to time. It is correctly returned but in random order.

**Comment by JordonPhillips** [comment]
As those are are JSON, either of those are equally valid since order is not semantically important.
