### ISSUE TITLE
Parameter validation failed: Invalid type for parameter patchOperations[0].value

### ISSUE THREAD

**Issue by Ch3ck** [aws/aws-cli#3692]
I'm working on updating a REST API policy via `aws-cli` with the following command
```
aws apigateway update-rest-api --cli-input-json file://basic_rest_api.json
```

I get the following error after passing the policy json file.
`Error: type: <class 'dict'>, valid types: <class 'str'>`

Below is my input json file
```
{
    "restApiId": ...,
    "patchOperations": [
        {
            "op": "replace",
            "path": "/policy",
            "value": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": [
                            ...
                        ],
                        "Action": "execute-api:Invoke",
                        "Resource": [
                            ...
                        ],
                        "Condition": {
                            "IpAddress": {
                                "aws:SourceIp": [
                                    ...
                                ]
                            }
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by JordonPhillips** [comment]
Yep, the policy is accepted as a string in the api. This is a relatively common pattern - and one we'd like to solve in a cross-service manner. For now though you would need to pass that as a json string.

**Comment by Ch3ck** [comment]
@JordonPhillips thanks for the information. I've done that, however I get this strange error:

```
An error occurred (BadRequestException) when calling the UpdateRestApi operation: Invalid policy document. Please check the policy syntax and ensure that Principals are valid.
```

I configured my principal to `"*"` and later on switched to my aws account profile still doesn't work. However when I try using this same policy it seems to attach perfectly, but fails on the CLI?

**Comment by JordonPhillips** [comment]
If you're having trouble putting together a policy, I highly recommend using the [policy simulator](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_testing-policies.html).

**Comment by Ch3ck** [comment]
Thanks.
