### ISSUE TITLE
How can I get "aws s3 sync" to encrypt using --sse-c-key

### ISSUE THREAD

**Issue by satyajeet-poradia** [aws/aws-cli#3693]
I'm trying to sync two buckets, but I need data to be encrypted in the destination bucket. I looked at the https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html and found that it provides [--sse-c <value>] [--sse-c-key <value>] for the data to be encrypted.

I have --sse-c-key in the form of '\xd4G\xdfS\xa2\x1b...'. But I don't know how to provide --sse-c-key(File or text)

Is there a example that I can look at?

**Comment by JordonPhillips** [comment]
If you want to pass a file as a parameter in the CLI you generally will do `file://path/to/file`, or if you want to load the file as bytes instead of a string `fileb://path/to/file`.

**Comment by satyajeet-poradia** [comment]
https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html, says that --sse-c-key is of the blob format and https://docs.aws.amazon.com/cli/latest/userguide/cli-using-param.html says that "Blob – Binary object. Blob parameters take a path to a local file that contains binary data. The path should not contain any protocol identifier such as http:// or file://" that's why I'm confused. 
Any ways I tried storing my key in a file and pass fileb://key.bin but that throws me "(InvalidArgument) when calling the PutObject operation: The secret key was invalid for the specified algorithm"

**Comment by JordonPhillips** [comment]
The key must be AES256
