### ISSUE TITLE
Windows aws help, cannot quit by pressing q

### ISSUE THREAD

**Issue by john-aws** [aws/aws-cli#3694]
It does not seem to be possible to quit `aws help` or `aws help | more` by pressing q. Pressing ctrl+c is not a good alternative because aws is a CMD file and you are prompted "Terminate batch job (Y/N)?"

aws-cli/1.16.30 Python/3.6.0 Windows/10 botocore/1.12.20

**Comment by JordonPhillips** [comment]
If you're not able to exit `more` even outside of the CLI invoking it the it seems like there's some other problem on your end.

**Comment by john-aws** [comment]
I launched an EC2 Windows instance and I can indeed quit `aws help` by pressing `q`. I'll investigate the original Windows machine for why it's not working there. And thank-you for the quick response.
