### ISSUE TITLE
Missleading README about profiles

### ISSUE THREAD

**Issue by marverix** [aws/aws-cli#3696]
Hi,

README is currently very missleading. In one place one can read:

> In the config file, except for the default profile, you *must* prefix each config section of a profile group with `profile`. For example, if you have a profile named "testing" the section header would be `[profile testing]`.

And in one example there is:
```
[default]
aws_access_key_id=foo
aws_secret_access_key=bar

[testing]
aws_access_key_id=foo
aws_secret_access_key=bar
```

And in another:
```
[default]
aws_access_key_id=<default access key>
aws_secret_access_key=<default secret key>
# Optional, to define default region for this profile.
region=us-west-1

[profile testing]
aws_access_key_id=<testing access key>
aws_secret_access_key=<testing secret key>
region=us-west-2
```

When I have changed my config and credentials files to have `profile` prefix then everything stopped working. I *must be without* `profile` prefix is seems. We need to decide if we should fix README and/or CLI itself. It's very frustrating.

**Comment by JordonPhillips** [comment]
There are two different configuration files - the `credentials` file and the `config` file. The `config` file requires the profile prefix, the config file does not. By default we'll split up your configuration and credentials into those different files, but they can be placed in either.

**Comment by marverix** [comment]
Yes, I found that, but still I found it very confusing. Especially that here you mention only `config` file and here https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html one can read:
> The AWS credentials file uses a different naming format than the CLI config file for named profiles. Do not include the 'profile ' prefix when configuring a named profile in the AWS credentials file.
In my opinion this should be fixed in one of two ways:
1. (From my POV better) Unify both files. I don't see any good reason why `credentials` file has different syntax then `config`. If both files would use the same `[profile ...]` definition then it would be much less confusing. For backward capability you can make `profile` word optional, but at least it should be marked as preferred.
2. (Lazy "fix") Copy-paste notice from AWS to this README.

**Comment by justnance** [comment]
@marverix - Thank you for pointing out the confusion in our documentation.  I'm going to forward your findings over to our documentation team for review.
