### ISSUE TITLE
aws cloudformation package - allow taking the file from STDIN

### ISSUE THREAD

**Issue by dnagir** [aws/aws-cli#3700]
Currently, if we generate a CloudFormation template, we have to store it in a temporary location so that the `aws cloudformation package --template-file=path/to/tempfile`.

Can we please add an option to accept the `template-file` from STDIN to allow this flow:

`generate_cloudformation | aws cloudformation package`

**Comment by JordonPhillips** [comment]
Seems reasonable, marking as a feature request

**Comment by wknapik** [comment]
This is a general problem with aws cli. `file://` is required in many places and there's no way to make it work without an actual file.

E.g. when you're creating secrets in secrets manager, you need to save them to files in plain text, reference those files when calling aws cli and then shred them. If you run `aws secretsmanager create-secret --name foo --secret-string <(echo bar)` you will get a secret value like `/proc/self/fd/11`.

Related pull request #3209.

**Comment by rianwouters** [comment]
See also https://github.com/aws/aws-cli/pull/3209#issuecomment-439608003

**Comment by rianwouters** [comment]
@wknapik totally agree with you.
To solve this, why not implement a simple fallback in get_paramfile

replacing ```return data```

by 

```
if data is None:
    prefix = 'file://'
    function, kwargs = cases[prefix]
    data = function(prefix, prefix + path, **kwargs)
return data
```

**Comment by oshriPP** [comment]
@justnance any update for this features?

**Comment by tim-finnigan** [comment]
I think we should resolve this in favor of https://github.com/aws/aws-cli/issues/5982 as that issue refers to supporting stdin more broadly than just the cloudformation command referenced here. The [PR](https://github.com/aws/aws-cli/pull/3209) someone mentioned here earlier is linked there as well and it looks like there is still some ongoing discussion there as far as next steps.
