### ISSUE TITLE
aws ec2 describe-images raises exception with unicode

### ISSUE THREAD

**Issue by youngfeldt** [aws/aws-cli#3703]
aws ec2 describe-images —-owners aws-marketplace
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Traceback (most recent call last):
  File "/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 60, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 212, in main
    sys.stderr.write(str(e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 34: ordinal not in range(128)

**Comment by justnance** [comment]
@youngfeldt - Thanks for reaching out and providing the output details.  This looks like a unicode issue.  I'm not able to reproduce this issue.  Please the output for `locale`.

**Comment by justnance** [comment]
@youngfeldt - is this an issue?

**Comment by youngfeldt** [comment]
Apologies for the delayed response.   I was not aware an email filter was blocking these notificaitons.
I do still have an issue. 
My locale is as follows:
╰─  ○ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

I did some digging and it seems this is related to an issue I found in 2015
https://github.com/aws/aws-cli/issues/945
However, with something that old, I'm guessing there must be an adjustment i can/should make on my system.
