### ISSUE TITLE
Feature Request: session duration with role profiles

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [aws/aws-cli#3710]
We can specify a role to assume in the config and underneath the facade of
```bash
aws --profile "${role_profile}" "${foo}"
```
the CLI does something like this:
```bash
aws sts assume-role --role-arn "${role_arn}" --role-session-name "${session_name}"
# now with the temporary credentials fetched (and cached) , it does the actual command:
aws "${foo}"
```

What I am wondering is whether there's any possibility of adding a `--duration-seconds 7200` parameter to the `sts assume-role` call. I couldn't find anything related in the description of the CLI config or in command line params.

I would wish for something like:
```
aws --profile "${role_profile}" --session-duration-seconds 7200 "${foo}"
```

**Comment by hubertgrzeskowiak** [comment]
Ah, I think this is a duplicate of #3307

**Comment by justnance** [comment]
@hubertgrzeskowiak - Thanks for reaching out about `sts assume-role'.  Yes this feature is a duplicate of #3307.  It would be best to close this issue and track the feature request under #3307.
