### ISSUE TITLE
Add --rollback-configuration to cloudformation deploy

### ISSUE THREAD

**Issue by jaakkotuosa** [aws/aws-cli#3712]
I think cloudformation deploy should have --rollback-configuration just like create-stack and update-stack.

**Comment by max-allan-surevine** [comment]
I think it needs --disable-rollback as well as --rollback-configuration !

**Comment by justnance** [comment]
@max-allan-surevine - Thanks adding feedback.  Both are good ideas.

**Comment by dnascimento** [comment]
@justnance Could AWS prioritise it?

**Comment by ozbillwang** [comment]
@justnance 

I am waiting for this feature as well, it should be three options:

[--disable-rollback | --no-disable-rollback]
[--rollback-configuration <value>]

The reason why we need this option is, with two commands `create-stack` and `update-stack`, we can manage the cloudformation stack, but it is not convenience. 

With only one command `deploy`, we can deploy a new stack or update an exist stack. 

Any progress on this feature?

By the way, could you give some hints on which files will be updated in this feature? I did search the sample about `create-stack`, but no luck.

**Comment by justnance** [comment]
There is no ETA or update yet.  PRs are welcome.

**Comment by citrusoft** [comment]
another vote for this feature as it facilitates root-cause-analysis of failed pipelines of failed stacks.

**Comment by emmajhyde** [comment]
I attempted to create a PR for this, but it appears the create_change_set API client functionality does not support this. What can we do, as a community, to encourage that this be included in the API?

**Comment by max-allan-surevine** [comment]
> I attempted to create a PR for this, but it appears the create_change_set API client functionality does not support this. What can we do, as a community, to encourage that this be included in the API?

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateChangeSet.html
 Says : 
> RollbackConfiguration
The rollback triggers for AWS CloudFormation to monitor during stack creation and updating operations, and for the specified monitoring period afterwards.
Type: RollbackConfiguration object
Required: No

Same as on create stack :
> RollbackConfiguration
The rollback triggers for AWS CloudFormation to monitor during stack creation and updating operations, and for the specified monitoring period afterwards.
Type: RollbackConfiguration object
Required: No

The change set does lack disable-rollback though. On creation and execution, which is weird!

**Comment by brosaaj** [comment]
Any updates on that? Need this feature badly

**Comment by ezeev** [comment]
+1 - what is the status of this?

**Comment by NickTheSecurityDude** [comment]
+1

**Comment by mjacobsson** [comment]
+1

**Comment by martini631** [comment]
+1

**Comment by cdion3537** [comment]
Guys, what's the update here? Over two years and nothing? No wonder everyone is going to Terraform.

**Comment by alrawas** [comment]
:(

**Comment by atheiman** [comment]
To simplify this issue and match other cloudformation cli commands, I think the option could just be `-–disable-rollback`. This option already exists in [`create-stack`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html), [`update-stack`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack.html), and [`execute-change-set`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/execute-change-set.html)

**Comment by atheiman** [comment]
I've started a PR for this which adds `--disable-rollback | --no-disable-rollback` to `aws cloudformation deploy`. This option is already on `create-stack`, `update-stack`, and `execute-change-set`, so I think it makes sense to have on `deploy`. Its a simpler interface to disabling rollback, which is what I think most people would use `--rollback-configuration` for. Need to test it locally / polish it up and get a review from a maintainer still.

**Comment by tim-finnigan** [comment]
Since https://github.com/aws/aws-cli/pull/6453 was merged I think we can close this issue. As mentioned in the [comment above](https://github.com/aws/aws-cli/issues/3712#issuecomment-936304880), that PR didn't add `--rollback-configuration` but added a disable rollback option which is likely what most people needed. If anyone has additional feedback to share please let us know, otherwise I will set this to close if we don't get any responses.

**Comment by ozbillwang** [comment]
Good job, which aws cli version I can run a test with?

**Comment by atheiman** [comment]
If I remember right, `—disable-rollback` has been released, so you can just pull the latest aws cli v2. You can confirm you have it by running `aws cloudformation deploy help` and see if the flag is in the help output.

**Comment by tim-finnigan** [comment]
Thanks @atheiman! I'll go ahead and close this. If further enhancements beyond that PR are requested then I think it would be better to track those in a new issue.
