### ISSUE TITLE
aws ec2 wait nat-gateway-available does not work

### ISSUE THREAD

**Issue by MaxCCC** [aws/aws-cli#3716]
```
aws --version
aws-cli/1.16.50 Python/3.7.1 Darwin/18.2.0 botocore/1.12.40
```

I'm able to describe my NAT using `aws ec2 describe-nat-gateways ` but I'm not able to use the wait fucion:

```
$ aws ec2 wait nat-gateway-available
Waiter NatGatewayAvailable failed: Waiter encountered a terminal failure state 
```

**Comment by justnance** [comment]
@MaxCCC - Thanks for reaching out.  This error is expected when a particular condition or state is not satisfied after polling every 15 seconds and 40 failed checks which is approximately a 10 minute [wait](https://docs.aws.amazon.com/cli/latest/reference/ec2/wait/nat-gateway-available.html).  What is/was the initial condition or state? 
What was the expected results if the command was successful?
