### ISSUE TITLE
Feature Request: Add Availability Zone to EFS describe-mount-targets

### ISSUE THREAD

**Issue by nritholtz** [aws/aws-cli#3718]
My current use case is that there is a mount target within the same AZ but not the same subnet as the EC2 mounting the EFS. There are issues beyond the scope of this that prevents me from using the EFS DNS.

In order to find the EFS mount target to use for my EC2, I currently need to do the following:
1) Get Instance's mac using metadata
2) Use mac to get instance's VPC ID using metadata
3) Get instance's AZ using metadata
4) Get subnets using `aws ec2 describe-subnets` with filters on same AZ and VPC ID as the instance
5) Use subnets from 4 as a query on `aws efs describe-mount-targets`, where subnet is in the list of subnets from 4, to find mount target IP

My request is have `aws ec2 describe-subnets` support availability zone for each Mount Target structure in the response (the same way it currently shows within the AWS console EFS page). This would greatly shorten the amount of steps required above to:
1) Get instance's AZ from metadata
2) Use instance's AZ as a a query on `aws efs describe-mount-targets` to find mount target IP

**Comment by nritholtz** [comment]
I just noted that this is not currently supported by the EFS API. I will open up a support ticket for them to take a look.

**Comment by justnance** [comment]
@nritholtz - Thanks for reaching out and providing feedback when it was closed.
