### ISSUE TITLE
Setup requires for colorama needs to be bumped

### ISSUE THREAD

**Issue by glaubitz** [aws/aws-cli#3724]
Upstream ```colorama``` was updated to version 0.4.0 around a month ago. This version was just uploaded to openSUSE Factory which means that ```aws-cli``` is no longer installable in openSUSE Tumbleweed.

I just fetched the latest upstream version of ```aws-cli``` to update it in openSUSE Factory but noticed that even the latest version of ```aws-cli``` requires ```colorama``` has still a maximum version of ```0.3.9```.

Would it be possible to update the ```colorama``` version in ```aws-cli``` so it's compatible with the latest ```colorama``` versions found in rolling release distributions?

CC @rjschwei

**Comment by justnance** [comment]
@glaubitz - Thank you for reaching out.  This seems like a reasonable request.  I have labeled it as a feature request + dependency.

**Comment by glaubitz** [comment]
Ok, I guess we can just increase the version dependency on openSUSE. It shouldn't make any difference.

I wasn't aware that ```colorama``` is required for Windows only:

> ANSI escape character sequences have long been used to produce colored terminal text and cursor positioning on Unix and Macs. Colorama makes this work on Windows, too, by wrapping stdout, stripping ANSI sequences it finds (which would appear as gobbledygook in the output), and converting them into the appropriate win32 calls to modify the state of the terminal. **On other platforms, Colorama does nothing.**

From: https://pypi.org/project/colorama/

**Comment by hugovk** [comment]
PR https://github.com/aws/aws-cli/pull/4179 should fix this too.

**Comment by stealthycoin** [comment]
This got udpated recently.
