### ISSUE TITLE
An error occurred (InternalFailure) when calling the RestoreDBClusterFromSnapshot operation

### ISSUE THREAD

**Issue by travis-webb** [aws/aws-cli#3732]
This is all I did: 

aws rds restore-db-cluster-from-snapshot --db-cluster-identifier staging-5-nov15 --snapshot-identifier arn:aws:rds:us-east-1:ACCOUNT_NUMBER:cluster-snapshot:staging-5-nov15 --engine aurora-postgresql --db-subnet-group-name private-subnets --kms-key-id arn:aws:kms:us-east-1:ACCOUNT_NUMBER:key/KEY_ID

And I get this:

An error occurred (InternalFailure) when calling the RestoreDBClusterFromSnapshot operation (reached max retries: 4): An internal error has occurred. Please try your query again at a later time.

**Comment by travis-webb** [comment]
Note that if I take off the "--kms-key-id" part, it works. I want to restore this snapshot to be encrypted, so I cannot take this part off.

**Comment by justnance** [comment]
@travis-webb - Thank you for reaching out and reporting this issue.  It is possible this error is being returned from the service.  If you could provide the sanitized output after using the [`--debug` option ](https://docs.aws.amazon.com/cli/latest/reference/)we can dig a little deeper into the problem.

**Comment by travis-webb** [comment]
After researching this I'm fairly sure that restoring a non-encrypted aurora postgres snapshot to become an encrypted database isn't possible on this date (Jan 11, 2019). 

If you'd like to pursue this issue you could just create an Aurora Postgres DB, take a snapshot of it, then try to restore that snapshot using the '--kms-key-id' option. You'll get the same errors. 

You also can't restore that snapshot to be encrypted via AWS Console UI, either. I think the ability to restore snapshots to encrypted databases for Aurora Postgres hasn't been added yet, although this took a lot of searching to realize and the Console UI and documentations are often misleading or lack information. 

We've moved on to using third party tools to clone our Aurora Postgres databases. 

To anyone who happens to be reading this searching for a solution: we created a brand new Aurora Postgres database with encryption selected at creation, then used bucardo (bucardo.org) to copy/sync the data from the unencrypted database to the encrypted database.
