### ISSUE TITLE
Guidance Requested: Packaging AWSCLI

### ISSUE THREAD

**Issue by agamzn** [aws/aws-cli#3736]
https://github.com/aws/aws-cli/blob/5c1d807431ce4dcac2aa8c97c05dc0a1a88841c4/requirements.txt#L3-L8

What's the recommend guidance for packaging AWSCLI ?  Pulling from the develop branch means that I can't tie my awscli package (rpm, apk, etc) to a specific tag of these dependencies.  I'm all for pulling from latest development for development purposes, but IMO these should be tagged to specific versions in the production release. To me, the path forward would be a `requirements.txt` that's tailored for the development of `awscli`

Arbitrary example: 

AWSCLI (version number here), should define in the requirements.txt file:
- dependency on botocore 1.12.47
- dependency on s3transfer 0.13
- dependency on jmespath 0.9

Instead of the HEAD pointer in each respective develop branch. 

In a more practical example, the current workflow leads itself to the following gotcha.

- Monday, 10:00am: I start building my package on my package-builder-1 box, located in my DC1 datacenter.
- Monday, 1:00pm: commits are pushed to one of the three libraries develop branch.
- Monday 3:00pm: I start building my package on my package-builder-2 box, located in my DC2 datacenter.

In my current understanding, both package builds would tie to the same version of AWSCLI (`master` branch), but have different upstream commits of, say, `jmespath`.

**Comment by joguSD** [comment]
Look at the [setup.py](https://github.com/aws/aws-cli/blob/9c4381fc821ac410fdd0d27b94fda79e6773ce92/setup.py#L26-L31) for more concrete versioning numbers.

While ideally a particular CLI version would have very specific versions for every dependency, it's currently not possible to list it this way as that rigidness will potentially cause issues for customers that are potentially installing this via `pip` into a shared or global environment. 

This is something we're looking at improving in CLI v2 however.

**Comment by agamzn** [comment]
@joguSD 
- Why does the setup.py differ from requirements.txt?
- Is there a roadmap for CLI v2?

**Comment by lorengordon** [comment]
Definitely feels like the aws-cli has diverged from the broader python community on how to manage python packages. I'd expect setup.py to have no or very broad ranges on dependency versions, and requirements.txt to contain pinned dependencies updated for each version of the aws-cli.

The current situation is quite unfortunate, and leads to a lot of issues.

**Comment by joguSD** [comment]
@agazmn
The `setup.py` defines the actual ranges we support and is enforced when installing the package via tooling in the python ecosystem (setuptools, pip, etc.). The `requirements.txt` is only used when explicitly given to `pip install -r`. We primarily use the `requirements.txt` in development / CI.

We have a tracking issue for v2 [here](https://github.com/aws/aws-cli/issues/3587). And anything labeled as `v2`. 

@lorengordon 
Our `setup.py` is more or less what you describe, we have the broadest version ranges possible. I think I would agree on how we're treating `requirements.txt` though. Right now it's more of a `requirements-dev.txt` or `requirements-ci.txt`. Perhaps we can provide another file (or shuffle some files around) to have a requirements file that describes concrete versions for dependencies.
