### ISSUE TITLE
Guidance: Custom Model in Lambda

### ISSUE THREAD

**Issue by coingraham** [aws/aws-cli#3738]
I'm using the custom AMS (amazon managed service) cli model that is installed in ~/.aws/models by default.  It looks like the addmodel.py command is hard coded to look there.  Issue is that I'd like to use lambda to call some AMSCM functions and lambda functions don't have access to ~/.aws for custom models.

Is there an easy way to allow the aws cli instantiate custom models from somewhere else?

**Comment by lorengordon** [comment]
Try exporting `AWS_DATA_PATH` to include a path where you have your custom models... For more info see this issue, https://github.com/aws/aws-cli/issues/2790...

**Comment by coingraham** [comment]
That worked spectactularly.  Thank you!

**Comment by babunatarajan** [comment]
Hi, I would like to create a custom AMS cli model in Lambda/shell can you help me with sample code?
