### ISSUE TITLE
Update-kubeconfig exit with 255 code

### ISSUE THREAD

**Issue by sakomws** [aws/aws-cli#3744]
Cannot update kubeconfig for EKS cluster:
```
aws-okta  exec development-admin -- aws eks update-kubeconfig --name eks-development-xx

'name'
exit status 255
```
Awscli version:
```
aws --version
aws-cli/1.16.60 Python/3.7.1 Darwin/17.7.0 botocore/1.12.50
```
Can successfully list clusters:
```
aws-okta  exec development-admin -- aws eks list-clusters
{
    "clusters": [
        "bhavin-cluster-dev",
        "eks-development-xx",
        "eks-development-xxx"
    ]
}
```
Solution: After recreating new .kube/config file, issue was solved. 
Problem: The error was given is not descriptive.

**Comment by justnance** [comment]
@sakomws - Thanks for reaching out and reporting this.  [AWS CLI Return Codes](https://docs.aws.amazon.com/cli/latest/topic/return-codes.html) are listed online with some guidance on how to proceed.  The `255 indicates the command failed and there were errors thrown by either the CLI or by the service the request was made to.`  Given this new information, do you still think the error was not descriptive enough?

**Comment by sakomws** [comment]
The issue was in syntax error in kubeconfig file.

**Comment by justnance** [comment]
@sakomws - Thank you for your feedback and confirming the fix.  closing issue.

**Comment by justnance** [comment]
@sakomws - Thanks for reporting the confusing error.  I reopened this issue pending further review.

**Comment by bpetit** [comment]
Hi,

This is still happening with aws-cli/1.18.37 Python/3.7.3 botocore/1.15.0
When the kubeconfig file is messy, I get the output:

'name'

And the exit code 255
