### ISSUE TITLE
javascript file will be set wrong content type as 'text-plain'

### ISSUE THREAD

**Issue by stevenruizhang** [aws/aws-cli#3758]
Hi Team,
  I am use aws cli to update file into s3 bucket like below, but after that, some JS files has wrong content type as 'text-plain', should be 'application/javascript', this will cause web application issue when set the header x-content-type-options to nosniff value.
  I try to delete the original js file and manually upload file and set 'application/javascript', sometimes the js file content-type is 'application/javascript', but sometimes show 'text-plain' in chrome, but sure this is browse or s3 or other issue.

`aws s3 cp ./dist s3://%s3_bucket%/ --recursive`

![capture](https://user-images.githubusercontent.com/13114985/49019905-06870580-f1ca-11e8-891b-8f451ca2a200.PNG)

**Comment by klaytaybai** [comment]
Hi @stevenruizhang, are you seeing the content-type change if you don't make any changes to the object through the CLI, console, or something else?  If changing browsers or refreshing the page is changing the content-type, this is something we'll probably want to look into.

To set a self-determined content-type via your CLI command, add the `[--content-type <value>] ` option.  You can find more options at the [aws s3 cp documentation](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html).

**Comment by justnance** [comment]
related to #3886

**Comment by bradisbell** [comment]
Please re-open this issue.

**Comment by schbz** [comment]
I second the motion to re-open

**Comment by kdaily** [comment]
Hi @bradisbell and @schbz,

I think this is the same as the open issue here and is not specific to `application/javascript` files: #1249

If you can comment on that issue with information about your environment, version, and debug logs, that would be appreciated. Thank you!
