### ISSUE TITLE
Filters require brackets on Values field when only one value passed

### ISSUE THREAD

**Issue by rdonahoe-placed** [aws/aws-cli#3760]
In 2.0.0.dev0

When passing a filter like so:
`
aws ec2 describe-instances --region us-east-1 --filters "Name=instance-state-name,Values=running"
`

An error is kicked back, claiming
`
Parameter validation failed:
Invalid type for parameter Filters[0].Values, value: running, type: <type 'unicode'>, valid types: <type 'list'>, <type 'tuple'>
`

This can be solved by putting brackets around the singular value in the Values field
`
aws ec2 describe-instances --region us-east-1 --filters "Name=instance-state-name,Values=[running]"
`

but this behavior didn't exist in V1 and non-brackets syntax still works as described in doc when using multiple values
`
aws ec2 describe-instances --region us-east-1 --filters "Name=instance-state-name,Values=running,terminated"
`

seems to be a regression.

**Comment by justnance** [comment]
@rdonahoe-placed - Thanks for reporting this issue.  I recently worked on another issue related to this command.  Please provide an example of the expected output when using multiple values.  Are you trying to filter some but not all of the Instance states:

[The valid values are: 0 (pending), 16 (running), 32 (shutting-down), 48 (terminated), 64 (stopping), and 80 (stopped).](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html)

**Comment by rdonahoe-placed** [comment]
@justnance the expected output is to not have an error thrown when following the documented request syntax. Having to add [] around the Values sometimes but not all the time is pretty sloppy and makes automation frustrating

**Comment by kdaily** [comment]
Hi @rdonahoe-placed, I cannot reproduce on a more recent version of the v2 CLI. Is this still an issue for you? Thanks!
