### ISSUE TITLE
aws s3 sync: "warning: Skipping file ... File/Directory is not readable."

### ISSUE THREAD

**Issue by yuha0** [aws/aws-cli#3767]
I have a bash script that attempts to sync some files on NFS to S3 daily. It looks like this:

```bash
# some logic here to generate a "folders" array
for src in "${folders[@]}"; do
    dst="s3://my_bucket$src"
    /path/to/aws s3 sync --only-show-errors --follow-symlinks $src $dst
done
```

Usually, there are around 60 folders in that array and about 20 of the commands that will return this error:

> warning: Skipping file /path/to/a/folder/. File/Directory is not readable.

I have confirmed that those folders **are** readable. And if I put a retry logic in my script, the number of such error is significantly reduced. Some of the folders need to be retried another 2-3 times to be successful.

OS: Ubuntu 18.04
NFS mount options:
`nfs_hostname:/my/nfs/export/path /mount/point nfs rw,soft,timeo=25,retrans=2,noacl,intr,tcp,rsize=32768,wsize=32768 0 0`

`aws --version`: 
```
aws-cli/1.16.60 Python/2.7.15rc1 Linux/4.15.0-33-generic botocore/1.12.50
```

**Comment by yuha0** [comment]
Turned out there was some issue with NFS lookups.

**Comment by chefren** [comment]
I have seen this issue on Windows OS, both `icacls` and `Get-NTFSAccess` don't show different permissions on files that are able to upload and others that aren't.
