### ISSUE TITLE
Cloudwatch Insights `describe-queries` fails to respect --status opt 

### ISSUE THREAD

**Issue by Igrom** [aws/aws-cli#3771]
Writing a command-line tool to streamline CLI log querying, I noticed that the AWS CLI (aws-cli/1.16.65 Python/2.7.15rc1 Linux/4.15.0-36-generic botocore/1.12.55) fails to respect an opt to `describe-queries`.

Excerpt from the terminal:
```bash
igrom@Touchstone:~$ aws logs describe-queries --status NotARealStatus | grep status | head -10

An error occurred (InvalidParameterException) when calling the DescribeQueries operation: 1 validation error detected: Value 'NotARealStatus' at 'status' failed to satisfy constraint: Member must satisfy enum value set: [Scheduled, Cancelled, Complete, Failed, Running]
igrom@Touchstone:~$ aws logs describe-queries --status Cancelled | grep status | head -10
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
            "status": "Complete", 
```

**Comment by sayboras** [comment]
@Igrom I got the same issue some time back, but it is fixed as per latest version.

> aws --version
aws-cli/1.16.81 Python/3.7.1 Darwin/18.2.0 botocore/1.12.71

**Comment by kyleknap** [comment]
I'm unable to reproduce the service not respecting the `--status`. I was able to successfully filter on `Cancelled`. If you are still seeing issues with it, can you rerun the command with `--debug` to help get more insight on what may be going on?
