### ISSUE TITLE
Requesting support for lambda layers in cloudformation package command

### ISSUE THREAD

**Issue by tqhoughton** [aws/aws-cli#3773]
With the release of Lambda function layers I would appreciate it if the package command supported local definitions of Lambda function layers. Right now it just skips over Lambda layers as a whole.

**Comment by dehli** [comment]
Looks like this was added already: https://github.com/aws/aws-cli/commit/7149c43d94a929b9b7550b40500c79ecb52e24c8! :fireworks: :smile:

**Comment by tqhoughton** [comment]
Oh nice, so do I just need to update my version of the AWS CLI then?

**Comment by dehli** [comment]
Yep! Since the latest version hasn't been publish on pip yet, you'll need to install it via source. The readme outlines how to do that.

**Comment by justnance** [comment]
@tqhoughton - Thanks for reaching out and @dehli for your response.

**Comment by mearns** [comment]
Based on the name, this looks like it's only for SAM Layers, not raw "AWS::Lambda::LayerVersion" resources. Can anyone verify?

**Comment by dehli** [comment]
It works for the raw resource (that's how I'm using it).

**Comment by mearns** [comment]
Cool, would you mind sharing a snippet of how this is used? I tried setting the `Content` property on an `AWS::Lambda::LayerVersion` resource to a local file path and running the cloudformation package command; it didn't change the property to an S3 path as I expected it to.

**Comment by mearns** [comment]
Oops, nevermind, I did not have the latest version of awscli. It looks like support for LambdaLayerVersion resources was added in [1.16.172](https://github.com/aws/aws-cli/commit/80c472e2fc90e5f9ec0ab52f945baeb00fc87be3)

**Comment by LarsFronius** [comment]
In case someone is still looking for a usage guide as this is not documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-layerversion-content.html

```
  ImageServiceLibs:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibelRuntimes:
        - go1.x
      Content: ../dist/libs/
```

`aws cloudformation package` will then take care of uploading the folder as a zip to use with Lambda.
