### ISSUE TITLE
Aws s3 cp takes ages to exit on Windows

### ISSUE THREAD

**Issue by Kodiakkb** [aws/aws-cli#3774]
I use an aws s3 cp command with 68 --include rules. 
When run on MacOS, once every file is copied the command returns immediately and the rest of my bash can execute.
When run on Windows (64 bits), once every file is downloaded, I'm stuck with a
`Completed 354.4 MiB/~354.4 MiB (3.7 MiB/s) with ~0 file(s) remaining (calculating...)`
and it takes forever to stop (12 minutes). During this time a whole CPU core is used.
When downloading 3 files it exits successfully within seconds.

**Comment by kyleknap** [comment]
Hmm I have a few follow up questions. Does this hang happen for every time you use the cp command on Windows? Could you provide debug logs for running it on windows? You can get debug logs by appending the command you ran with `--debug`. This will give us a little more insight on what may be happening.
