### ISSUE TITLE
Backslashes in windows package.json cant be used to run invalidation command for cloudfront

### ISSUE THREAD

**Issue by 11fishem** [aws/aws-cli#3775]
In my package.json for a React App, I wanted to run a command to create an invalidation in a node script like so:

`aws cloudfront create-invalidation --distribution-id {distributionid}--paths /\*`

However, having the backslash \* invalidated the JSON.

This command can also accept the following path

`aws cloudfront create-invalidation --distribution-id {distributionid}--paths '/*'`

but again, within a node command like below, this was rejected

`"start": "aws cloudfront create-invalidation --distribution-id {distributionid}--paths '/*'"`

Finally, I was able to use the following, and it WORKED:

`aws cloudfront create-invalidation --distribution-id {distributionid}--paths \/*`

I'm not sure why, so if anyone wants to comment that'd be great. If this is inactive for a while, you can mark it as closed, I mostly made it to help someone else out who may run into this problem.

**Comment by 11fishem** [comment]
For clarity, this method will work for invalidating an entire cloudfront distribution as part of an NPM command, just make sure you use your own id
package.json

`"start": "aws cloudfront create-invalidation --distribution-id {distributionid} --paths \/*"`

**Comment by stealthycoin** [comment]
Closing, in general this doesn't have to do with the CLI, its all happening at the layer above before the cli is called.
