### ISSUE TITLE
AWS S3 ls wildcard support

### ISSUE THREAD

**Issue by Bongani** [aws/aws-cli#3784]
Currently it seems there is no way to search for file(s) using ls and a wild card. For example:

`aws s3 ls s3://bucket/folder/2018*.txt`

This would return nothing, even if the file is present.

I have done some [searching online,](http://bigdatums.net/2015/11/30/using-unix-wildcards-with-aws-s3-cli/) it seems the wildcard is supported for rm, mv & cp but not ls. The common solution to getting this done is to ls the entire directory then grep for the files you are searching for

`aws s3 ls s3://bucket/folder/ | grep 2018*.txt`

But come across this, I also found warnings that this won't work effectively if there are over a 1000 objects in a bucket.

To me, it appears it would be nice to have the aws s3 ls command to work with wildcards instead of trying to handle with a grep & also having to deal with the 1000 object limit.

**Comment by justnance** [comment]
@Bongani - Thank you for reaching out and reporting this feature.  This would be a feature requests for our service team.  If the service team approves and adds this feature it will be exposed from the API to the CLI.   I have submitted an internal request to our service team but would recommend any follow up via a case with [AWS Support](https://console.aws.amazon.com/support/home#/) or reach out to the [AWS Forum for S3](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by Bongani** [comment]
@justnance Thanks for submitting the request.

**Comment by justnance** [comment]
no problem at all.

**Comment by justnance** [comment]
As per our S3 Service team, "Thanks for the feedback, your feature request will be prioritized with other features planned for S3."

**Comment by Bongani** [comment]
Thanks for the update. It's greatly appreciated.

**Comment by dhalliday-shotspotter** [comment]
I would love this also.

**Comment by dhalliday-shotspotter** [comment]
In my case I have lots of files in S3 under date folders of the form

bucket/name/YYYY-MM/YYYY-MM-DD/filename.ext

I would love to say "aws s3 ls s3://mybucket/*/2016-03/*/" and list all files from all root prefixed for march 2016.

**Comment by kalihman** [comment]
So how this is going now? Is there any roadmap include this feature?

**Comment by justnance** [comment]
Hi All.  This was escalated internally and there is no update at this time.

**Comment by rjurney** [comment]
This is really essential. You can grep, but man... really?

**Comment by nickorka** [comment]
Python implementation of s3 wildcard search:

```
import boto3
import re

def search_s3_regex(results, bucket, prefix, regex_path):
    s3_client = boto3.client('s3')
    wc_parts = regex_path.split('/')
    if len(wc_parts) == 1 and len(wc_parts[0]) == 0:
        results.append(prefix)
        return
    else:
        regex = re.compile(wc_parts[0])
        next_regex_path = '/'.join(wc_parts[1:])
        paginator = s3_client.get_paginator('list_objects')
        result = paginator.paginate(Bucket=bucket, Delimiter='/', Prefix=prefix)
        for pref in result.search('CommonPrefixes'):
            if pref is None:
                # check files
                for k in result.search('Contents'):
                    res = k.get('Key')
                    search_prefix = res if len(prefix) == 0 else res.split(prefix)[1]
                    if re.match(regex, search_prefix):
                        results.append(res)
            else:
                # check paths
                res = pref.get('Prefix')
                search_prefix = res if len(prefix) == 0 else res.split(prefix)[1]
                if re.match(regex, search_prefix):
                    search_s3_regex(results, bucket, res, next_regex_path)
```
After that you can call the function like this:

```
res =[]
search_s3_wildcard(res, 'my_bucket', 'initial_prefix/blah/', 'b.{2}h/[0-9]{2}-.*-2019/.*')
for p in res:
     print(p)
```

**Comment by kelek** [comment]
Just curious, about a year later, is there plan for native support?  The scripts are nice, but it doesn't help in cases where there are tons of files in the directory that still have to be traversed on the client side.

**Comment by felipe1982** [comment]
You can use `sync` with `--dryrun` option:

```bash
aws s3 sync --dryrun --exclude '*' --include '*/.DS_Store' s3://mybucket ./
```

**Comment by alukach** [comment]
> You can use `sync` with `--dryrun` option:
> 
> ```shell
> aws s3 sync --dryrun --exclude '*' --include '*/.DS_Store' s3://mybucket ./
> ```

This solution is such a great hack.  You can distill it into single S3 urls by piping to `awk`:
```
aws s3 sync --dryrun --exclude '*' --include '*/.DS_Store' s3://mybucket ./ | awk '/s3:\/\//{print $3}'
```

**Comment by teaguexiao** [comment]
> | awk '/s3:\/\//{print $3}'

This works well for me!
