### ISSUE TITLE
AWS Cognitor Pool Trigger is not saved properly

### ISSUE THREAD

**Issue by vijigit** [aws/aws-cli#3797]
Hi All, 
I am facing a strange problem while configuring the triggers in cognito pool using AWS CLI

I have an angular UI that authenticates using cognito pool, and the pool calls a lambda configured under PRE Token generator. I am creating the pool using AWS CLI. Below the command used. 

 aws cognito-idp  create-user-pool --pool-name "${CLIENT}-app" --admin-create-user-config AllowAdminCreateUserOnly=true --policies "$PASSWORD_POLICY" --email-verification-subject "$EMAIL_VERIFICATION_SUBJECT" --auto-verified-attributes email --lambda-config PreTokenGeneration="$PRE_TOKEN_LAMBDA_REF" --schema "$CUSOM_ATTR_VALUES"

I see the trigger is created properly. I verified in aws console (UI) and I queried the pool using aws list-pools, Both cases the lambda is referenced properly in Pre token generator.

But using the Angular UI while accessing the pool , i am getting Access Denied exception. I am able to resolve the problem by manually visiting the pool and simply press "Save Changes" under Triggers. I am not updating any information in the pool. After this step the UI is able to work without any issues.

Kindly provide your suggestions.

Regards Viji

**Comment by justnance** [comment]
@vijigit - Thank you for reaching out and reporting this issue.  The CLI does not have control over this behavior as the CLI is only displaying `Access denied exception errors` returned from the service.  Any chance you can run the [--debug option](https://docs.aws.amazon.com/cli/latest/reference/) and upload a sanitize output ?  The debug will show the request and the response body that might provide more information into the problem. 

Another suggestion is to reach out to the [IAM or the Lambda AWS Support team](https://console.aws.amazon.com/support/home#/) or [AWS Forums for IAM](https://forums.aws.amazon.com/forum.jspa?forumID=76).

**Comment by lenarmazitov** [comment]
I have same problem.
I'm trying to update user pool with new triggers, but triggers.
In AWS console I see that new triggers are selected, but triggers did not work.
If I just press Save button on "triggers" page in AWS console, everything works fine.

**Comment by ezalorsara** [comment]
> I have same problem.
> I'm trying to update user pool with new triggers, but triggers.
> In AWS console I see that new triggers are selected, but triggers did not work.
> If I just press Save button on "triggers" page in AWS console, everything works fine.

Hi @lenarmazitov ,did you find the solution. I'm currently having this problem same with you. Thanks

**Comment by lenarmazitov** [comment]
@ezalorsara 
Just go to AWS Console (Cognito User Pools) see that all lambdas on own place and press Save.
