### ISSUE TITLE
Windows AWSCLI64PY3 MSI not working with git-bash or mingw: command not found (despite being on path)

### ISSUE THREAD

**Issue by veqryn** [aws/aws-cli#3815]
On Windows 10, 1809, and I've installed AWS CLI 64-bit for windows, version `aws-cli/1.16.80 Python/3.6.0 Windows/10 botocore/1.12.70` from https://aws.amazon.com/cli/

I've added the directory to my path.

When using with `git-bash` or with `mingw`, the command `aws` can not be found:
```
MinGW 11:44:22 ~$ aws
bash: aws: command not found
```

However, `aws.cmd` can be found just fine
```
MinGW 11:45:41 ~$ aws.cmd
usage:  aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
```

If I try renaming `aws.cmd` to just `aws`, I get errors running it:
```
MinGW 11:46:06 ~$ aws
/c/Users/foobar/workspace/programs/awscli/bin/aws: line 2: @rem: command not found
/c/Users/foobar/workspace/programs/awscli/bin/aws: line 3: @echo: command not found
/c/Users/foobar/workspace/programs/awscli/bin/aws: line 5: setlocal: command not found
/c/Users/foobar/workspace/programs/awscli/bin/aws: line 7: fg: no job control
```

This is certainly not the end of the world, as I can `alias aws='aws.cmd'` to get things working again.
But it would be a nice quality of life fix, if you all could get this working again.

Edit:
When using `winpty`, the alias doesn't work, forcing me to type aws.cmd everywhere and breaking scripts.  Please fix.

**Comment by marczis** [comment]
"I've installed AWS CLI 64-bit for windows" <-- I think that's the source of the problem, tried to install with pip inside git-bash ?

Never used the windows version, but sounds like it uses the python for windows and so on, which is not the python inside the git-bash... or is it?

**Comment by veqryn** [comment]
Git-Bash doesn't come with python.

**Comment by justnance** [comment]
@veqryn - Thank you for reporting this issue.  I appears this might be related to #3662.  

There are two versions of the AWS CLI MSIs. The one that has an issue (#3662) which is built against [python 3.6](https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi). We still publish the [older MSIs](https://s3.amazonaws.com/aws-cli/AWSCLI64.msi), which does not have an issue and is the recommended workaround while we are working on a solution.  

Please advise if the problem with `git-bash` or with `mingw` exists when using the [older MSIs](https://s3.amazonaws.com/aws-cli/AWSCLI64.msi)

**Comment by veqryn** [comment]
Thanks, I do believe #3662 is related.

I don't remember having this issue a long time ago, before I updated my AWS cli install, so the older MSI probably does fix it.

However, I would prefer to keep using the Python 3 version, as that solves a lot of problems with unicode that the python 2 version has.

**Comment by justnance** [comment]
@veqryn - Thanks for the feedback. Let's track this issue on #3662 to avoid duplicate efforts as we work on resolving this issue so you can keep using the Python 3 version.

**Comment by justnance** [comment]
Work has been done to resolve this issue. Please install the latest version of the CLI and let us know if it is working as expected now. Thanks for your patience.
