### ISSUE TITLE
aws s3 ls versions

### ISSUE THREAD

**Issue by vviswaroop** [aws/aws-cli#3818]
Currently, aws s3api supports listing object versions and  aws s3 cli doesn't support listing the object versions.
Is there a reason why there is no extended support for aws s3 cli ?

**Comment by JordonPhillips** [comment]
The high level interface is there to support common operations in a more simple, unix-like way. Listing versions isn't common enough to have driven much demand. Beyond that, for an even moderately used bucket that's going to be a BIG list that will probably be hard to see on terminal.

How would you imagine this working / looking?

**Comment by vviswaroop** [comment]
Why not!

**Comment by vviswaroop** [comment]
Why not ! As an end user, if i would like to get the size of a bucket, aws s3 ls with human readable size filter will provide you the size of the bucket excluding versions.

**Comment by justnance** [comment]
@vviswaroop - Thank you for your feedback.  We'd like to dig a little deeper.  Please reply back with a few details on how you'd imagine this working / looking.  An example of the ideal output is welcome too.  
Thanks!

**Comment by vviswaroop** [comment]
The size of the bucket in the S3 metrics will provide us the output with total size including versions and standards (correct me if am wrong). At the same time, when am trying to get the size of the bucket via CLI -- it will return partial size (like excluding versions and returning only certain standard format types). In our environment most of the end users were comfortable with using AWS CLI rather than Console. This is how the current API structure with available filters looks like . **aws s3 ls --summarize --human-readable s3://bucket-name | tail -2**. and the it would be better, if this has more filters to include versions also when user is trying to get the size of the bucket via AWS CLI. Please let me know, if there is a work around to do this. Thanks!!

**Comment by justnance** [comment]
@vviswaroop - Thank you for the feedback.  I have marked this as a feature request pending further review and 👍 from the GitHub community.
