### ISSUE TITLE
'AWSHTTPSConnection' object has no attribute 'server_hostname'

### ISSUE THREAD

**Issue by kp625544** [aws/aws-cli#3820]
Hello, I m getting the above issue while running all aws commands. Is it a bug or there is any fix available for it? I tried reinstalling awscli as well but still the issue persists

'AWSHTTPSConnection' object has no attribute 'server_hostname'

**Comment by sayboras** [comment]
@kp625544 can you share output of `aws --version`, I was having kind of similar issue before (for different attribute), then found out that my `botocore` version was kind of old.

**Comment by kp625544** [comment]
Solved.
I removed the package from linux 
sudo apt-get remove awscli

and the reinstalled with pip

sudo python -m pip install --upgrade awscli

**Comment by pbaughman** [comment]
Maybe this will be helpful to someone else, but I encountered this problem on someone else's computer and it was related to the version of `requests` that was installed.  I'm not sure what version they had before, but they removed it and reinstalled it along with `urllib3` and the problem went away
