### ISSUE TITLE
no escape characters implemented in session-manager plugin

### ISSUE THREAD

**Issue by JayDoubleu** [aws/aws-cli#3863]
session-manager plugin does not seem to support ssh escape characters ex. "  ~.      Disconnect.". 
  This would be a very useful feature as the only way to exit shell (if there was an issue with the session) is to kill the pid corresponding to session-manager.

**Comment by justnance** [comment]
@JayDoubleu - Thank you for reaching out.  The CLI does not have control over this behavior.  This would be a great feature request for the service team.  I can notify the service team but for a quicker response and followup, I recommend reaching to the service team [forum](https://forums.aws.amazon.com/forum.jspa?forumID=185) or directly to [AWS Premium Support](https://console.aws.amazon.com/support/home#/).
