### ISSUE TITLE
list-identity-providers documentation is showing wrong parameters 

### ISSUE THREAD

**Issue by qalshakhoori** [aws/aws-cli#3866]
When running [list-identity-providers](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/list-identity-providers.html) command, you get maxResults failed to satisfy
```
 aws cognito-idp list-identity-providers --user-pool-id YOUR-USER-POOL-ID --max-items 5

An error occurred (InvalidParameterException) when calling the ListIdentityProviders operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy
constraint: Member must have value greater than or equal to 1
```
To fix this you need to use the parameter "--max-results" instead

`aws cognito-idp list-identity-providers --user-pool-id YOUR-USER-POOL-ID --max-results 5`

Please fix this to reflect the correct parameters.

**Comment by justnance** [comment]
@qalshakhoori - Thanks for reporting this issue.  I will reach out to our documentation team to get this corrected.

**Comment by justnance** [comment]
@qalshakhoori - An internal ticket is in progress to resolve this issue.

**Comment by TDA** [comment]
@justnance It also needs be to marked as a required field, as not passing it results in 
```
Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1
```

**Comment by justnance** [comment]
@TDA - Thank you for the feedback.  I am reopening the issue and updating our doc writer team.

**Comment by justnance** [comment]
@TDA and @qalshakhoori - After some internal collaboration, this issue has been escalated to the service team.  The CLI does not have control over this behavior because it is only echoing what is returned by the service.  I'm leaving this GitHub issue opening pending more (internal) feedback.  Thanks for your patience.

**Comment by TDA** [comment]
@justnance Thanks for the update.

**Comment by stobrien89** [comment]
Confirmed that `--max-items` now appears to work in later versions— tested in `2.1.27` and `1.18.213`. Please let us know if you're still having issues!

**Comment by abjavaprof** [comment]
Issue still exists with `aws-cli/2.13.14 Python/3.11.4 Darwin/22.6.0 exe/x86_64 prompt/off`. --max-results parameter works but the following ways do not work:

- `aws cognito-idp list-resource-servers --region <REGION> --max-items 2 --user-pool-id <USER_POOL_ID>`

- `aws cognito-idp list-resource-servers --region <REGION> --user-pool-id <USER_POOL_ID>`

As per [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/list-resource-servers.html) --max-items is optional parameter also --max-results should not be even needed.

**Comment by cgddrd-gardin** [comment]
> Issue still exists with `aws-cli/2.13.14 Python/3.11.4 Darwin/22.6.0 exe/x86_64 prompt/off`. --max-results parameter works but the following ways do not work:
> 
> * `aws cognito-idp list-resource-servers --region <REGION> --max-items 2 --user-pool-id <USER_POOL_ID>`
> * `aws cognito-idp list-resource-servers --region <REGION> --user-pool-id <USER_POOL_ID>`
> 
> As per [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-idp/list-resource-servers.html) --max-items is optional parameter also --max-results should not be even needed.

I am still experiencing the same thing.
