### ISSUE TITLE
aws transfer create-user does not accept policy ARN

### ISSUE THREAD

**Issue by amcquade** [aws/aws-cli#3867]
When supplying the `--role` argument with an ARN, the role policy is applied as expected. When supplying the `--policy` argument with an ARN, the policy for that user becomes the string you supplied, instead of appling the actual policy. 

Is this a bug or does the policy need to be supplied as JSON?

**Comment by justnance** [comment]
@amcquade - Thanks for reaching out.  [The request accepts the data in JSON format](https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html).  Providing the output from adding `--debug` to the command will help us understand if there is another issue or bug in the CLI.

**Comment by amcquade** [comment]
@justnance this does not really answer my question.  I understand the request can be process entirely in JSON, however no where in the documentation does it specify that for the `--policy ` argument.  For example, if i run `aws transfer create-user --debug --home-directory /sftp.hostname.com/policytest --policy arn:aws:iam::xxxxxxxxxxxx:policy/SFTPScopeDown --role arn:aws:iam::xxxxxxxxxxxx:role/SFTPRole --server-id s-12345xxx --user-name policytest --ssh-public-key-body "$(< key.pub)"` the command will add this user successfully, but set the policy as "arn:aws:iam::xxxxxxxxxxxx:policy/SFTPScopeDown", instead of setting the policy attached to the ARN, like the screenshot attached below. 
![policy-arn-fail](https://user-images.githubusercontent.com/16789125/51186607-fe814300-18a7-11e9-972b-48c76b758b49.png)

**Comment by justnance** [comment]
@amcquade - Thank you for your feedback and additional information.  I am investigating this issue and trying to reproduce the issue.  I respond again shortly.

**Comment by citrocity** [comment]
Same issue. 
No where in the documentation it says clearly how --policy will work. even in the sample example it is left out. Policy name and arn doesnt work.

**Comment by bisdavid** [comment]
You are correct - the --policy instructions are not clear for this command.  I will contact the writer for the Transfer service to add more information about that.

The parameter takes the actual policy text as a JSON string.  It does not take the ARN of an existing policy. Because including a JSON string on a command line is awkward at best (you have to escape all the double-quotes, for example), you can instead store the policy text in a file on disk and then reference that file using the **file://_mypolicyfilename_.json** syntax.  It works identically to the "policy-document" parameter on the IAM create-policy command.  You can see that command here: https://docs.aws.amazon.com/cli/latest/reference/iam/create-policy.html.  That page has much more information about how to use that parameter successfully.  

I hope this helps!
Dave

**Comment by justnance** [comment]
Thanks for the feedback @bisdavid !

**Comment by citrocity** [comment]
Thanks @bisdavid That worked.

Could you also shed some light on using 

> Variables you can use inside this policy include ${Transfer:UserName} , ${Transfer:HomeDirectory} , and ${Transfer:HomeBucket} .

i have tried it but didnt work for me. the policy has it literally intead of the value

**Comment by amcquade** [comment]
Thanks @bisdavid! I think some more guidance in the documentation will go a long way, but it would be a really nice feature to be able to just pass the ARN. 

@citrocity the variables wont be replaced with the actual values when you view the policy in the SFTP console, but they will work whenever you are actually connecting to the service as that user.

**Comment by bisdavid** [comment]
Sorry, but we're now beyond my area of expertise. I sent an email to the Transfer owner. If he replies to me, I'll post his answer here.

**Comment by citrocity** [comment]
> Thanks @bisdavid! I think some more guidance in the documentation will go a long way, but it would be a really nice feature to be able to just pass the ARN.
> 
> @citrocity the variables wont be replaced with the actual values when you view the policy in the SFTP console, but they will work whenever you are actually connecting to the service as that user.

I tried but found that it doesn't work.
On AWS CLI i am:

- creating a bucket named userA
- creating a policy named sftp-userA with list access and read/write access to bucket UserA (this is where i am using: Resource:  "arn:aws:s3:::${Transfer:UserName}"
- Attaching the above policy to assume transfer role
- creating transfer user called userA and adding the above policy and adding user home directory.

The user can login but no access.

If i replace ${Transfer:UserName} in the policy with the name userA, the user can read/write but with the variable it doesnt work.

**Comment by ajay-kickdrum** [comment]
Failed to create user (${transfer:Home*} variable used in policy for a user with a logical home directory)
