### ISSUE TITLE
Is a reboot required after pip install --upgrade awscli ?

### ISSUE THREAD

**Issue by mattvend** [aws/aws-cli#3869]
According to this thread, https://stackoverflow.com/questions/36969391/how-to-upgrade-aws-cli-to-the-latest-version
and the comment made by Joe Tidee, a reboot is required after a pip install --upgrade awscli

I could not find the reboot mentioned in the documentation. Is it really required?

**Comment by justnance** [comment]
@mattvend - Thank you for your feedback.  Closing issue.
