### ISSUE TITLE
Confusing Execution Condition of DynamoDB Local

### ISSUE THREAD

**Issue by byeonggukgong** [aws/aws-cli#3871]
In [DynamoDB Usage Notes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html)

> The AWS SDKs for DynamoDB require that your application configuration specify an **access key value and an AWS Region value**. Unless you're using the -sharedDb or the -inMemory option, DynamoDB uses these values to name the local database file. **These values don't have to be valid AWS values to run locally.** However, you might find it convenient to use valid values so that you can run your code in the cloud later simply by changing the endpoint you're using.

I ran DynamoDB Local on the Docker using [amazon/dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local) that applied `-inMemory` option basically. In this condition, it didn't worked when input invalid access key or region. I wonder if the official document is correct.

**Comment by justnance** [comment]
Hi @byeonggukgong - Thanks for posting your questions and your patience.  I started to reproduce this issue to understand if there was a bug or if our documentation needs clarification.  I need a little more information:

-- Do you have a sample command I can use for testing?
-- Is there a specific error message returning so I can confirm if I've reproduced the problem correctly?
-- are both -dbPath and -inMemory in use at the same time?
-- is a specific local endpoint (such as `http://localhost:8000`) in use?
-- are you specifying an --endpoint-url with each CLI command?

[The AWS CLI can't use the downloadable version of DynamoDB as a default endpoint. Therefore, you must specify --endpoint-url with each AWS CLI command.](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html)  Example:

```
aws dynamodb list-tables --endpoint-url http://localhost:8000
```
