### ISSUE TITLE
Misleading "Failed to connect to proxy URL:" error message using awscli support functions

### ISSUE THREAD

**Issue by Holger1968** [aws/aws-cli#3872]
I have my region set to eu-central-1 and I am using a proxy (by setting HTTP[S]_PROXY in my environment).
When using support or organizations with awscli I got the following error:

PS C:\Users\holger> aws support describe-trusted-advisor-checks --language en
Failed to connect to proxy URL: "https://proxy.localdomain.net:8079"

This is issue #2102 and you can avoid this by specifying the region us-east-1.

PS C:\Users\holger> aws support describe-trusted-advisor-checks --language en --region us-east-1
An error occurred (SubscriptionRequiredException) when calling the DescribeTrustedAdvisorChecks operation: AWS Premium Support Subscription is required to use this service.
PS C:\Users\holger>

The error message "Failed to connect to proxy URL:" that you get is wrong and misleading. The problem has nothing to do with the proxy. The error message that you get in #2102 is 'Could not connect to the endpoint URL: "https://support.eu-west-1.amazonaws.com/"' and is correct.

When using a proxy there should not be another (misleading) error message as the problem has nothing to do with the proxy.

**Comment by tstibbs** [comment]
This isn't only for the support functions. I think it happens for anything where there isn't an endpoint for that service in the specified region, because it also happens if you typo the region. E.g. running `aws --region eu-wes-2 ecs list-tasks` gives the same error (note the typo in the region name).

**Comment by justnance** [comment]
@Holger1968 and @tstibbs - Thanks for posting on this issue.  We are tracking a feature request and confusing errors related to region validation under #2266.  Sounds like it would be ideal to have regions validated for spelling and if it is supported by the service.  Please 👍 #2266 or add any additional information.  

As such, I am closing this issue as a duplicate so we can continue to track the progress under #2266.

**Comment by MarkHerhold** [comment]
I hit this error as well because I forgot to specify my profile argument.

What a terrible error message 🤦‍♂️

**Comment by dkolepp** [comment]
I had this problem as well, with cli `v2.12.1`.  I attempted to execute: `aws s3 cp ./<somefile> s3://<bucket> --sse AES256`
and got a proxy error message.   After lots of fiddling with the proxy, I added a `--region us-east-1`, and the command executed without error.

**Comment by csecker** [comment]
Had the same issue when accessing an s3 bucket with `aws s3 ls s3://...`
Works when using `aws s3 ls --region us-east-2 s3://...`

Thanks @Holger1968 for reporting this!
