### ISSUE TITLE
querying Organizations by Id is broken

### ISSUE THREAD

**Issue by chizou** [aws/aws-cli#3873]
In my organization, this always returns an empty list, not matter which account I query for: ``aws organizations list-accounts --query 'Accounts[?Id==`1234567890`]'``

Querying for any of the other fields in the account works

```
$ aws --version
aws-cli/1.16.91 Python/3.7.1 Linux/4.14.77-86.82.amzn2.x86_64 botocore/1.12.62
```

**Comment by chizou** [comment]
This returned a bunch of empty arrays:
``for i in $(aws organizations list-accounts --query 'Accounts[].Id' --output text); do echo $i; aws organizations list-accounts --query 'Accounts[?Id==`$i`].Id'; done;``

**Comment by shabeebk** [comment]
@chizou Please try **aws organizations list-accounts --query "Accounts[?Id=='<YOUR_ACCOUNT_ID>']"**

This is working as expected.

**Comment by chizou** [comment]
Querying with double and single quotes does work. Why does the querying with single quotes and backticks not work then? 

Is parsing broken then?

**Comment by chizou** [comment]
Yep, that worked. Thanks for explaining that to me

**Comment by srchase** [comment]
You're welcome!
