### ISSUE TITLE
ECR get-login produces an invalid parameter for ECR get-login

### ISSUE THREAD

**Issue by combusean** [aws/aws-cli#3881]
I noticed this standard behavior using the aws ECR cli and found it unusual.  

Anything I'm missing in this?  This seems widespread.

```
$ aws ecr get-login
docker login -u AWS -p eyJw....= -e none https://....ecr.us-west-2.amazonaws.com

$(aws ecr get-login)
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```

Leaving out the -e in the docker command fixes this.

**Comment by justnance** [comment]
@combusean - Thanks for reaching out.  [The '-e' option has been deprecated and is removed in docker version 17.06 and later. You must specify --no-include-email if you're using docker version 17.06 or later. The default behavior is to include the '-e' flag in the 'docker login' output.](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login.html)  Basically, using the `--no-include-email` option will remove the -e flag from the output.   Currently we are we are keeping the `-e` for backwards compatibility reasons as users may be using an old version of docker that still uses it.

Reference:  #3669 and #3374
