### ISSUE TITLE
Allow naming change set when calling aws cloudformation deploy with --no-execute-changeset

### ISSUE THREAD

**Issue by hauboldj** [aws/aws-cli#3882]
I'm using `aws cloudformation deploy` in a ci pipeline to create a changeset before deployment so someone can review the changes before they are deployed. It's cumbersome to get the change set name from the output text of the `aws cloudformation deploy` command. I would like to be able to provide the change set name so I don't have to parse the output to know what the change set name was.

**Comment by klaytaybai** [comment]
Hi @hauboldj, I think the best solution for your use case would likely be to use alternative commands to 
[aws cloudformation deploy](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html).

If you broke it up into the steps of creating, reviewing, and executing the change set, you could use methods built for this purpose that would allow you to specify the change set name and do an intermediate review step.

To create a change set, you can use 
`aws cloudformation create-change-set --stack-name <value>
 --change-set-name <value> ... other arguments including template` 
[create-change-set documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-change-set.html).

After doing your review, you can then execute with:
 `aws cloudformation execute-change-set --change-set-name <value>` 
[execute-change-set documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/execute-change-set.html).

Please let me know if you think this would work for you.  If you would still like to see an option to name the change set with the deploy command, let me know.  We can certainly change this issue to a feature-request.

**Comment by hauboldj** [comment]
There are a couple additional steps that `aws cloudformation deploy` provides. It determines if the stack exists and sets the `change-set-type` parameter appropriately. It also waits for the change set to complete creating and differentiates between a failure due to no changes and a failure due to other reasons, e.g. invalid template or parameters. So I would need several more steps than what is listed above.

**Comment by justnance** [comment]
Hauboldj- Thank you for your feedback.  @sanathkr - What are your thoughts?

**Comment by mixja** [comment]
+1 - this would be very useful if you want to control which change sets someone can execute as per the cloudformation:ChangeSetName condition key here https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awscloudformation.html#awscloudformation-policy-keys

**Comment by y3ti** [comment]
I have the same problem, so I have created a pull request with this feature https://github.com/aws/aws-cli/pull/5453
