### ISSUE TITLE
s3api put-bucket-lifecycle, depreciated implementation

### ISSUE THREAD

**Issue by Happy2C0de** [aws/aws-cli#3885]
aws-cli uses the depreciated version of "put-bucket-lifecycle"
I observed the issue when I tried to set a lifecycle config using the new "Filter" parameter to set up a prefix filter. In the new implementation prefix has "Filter" or "And" as an ancestor. See more detail:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTlifecycle.html
E.g.
```
{
  "Rules": [
  ...
  "Prefix": "",
  ...
  ]
}
```

Should become:

```
{
"Rules": [
  ... 
  "Filter": {
    "Prefix": ""
  },
  ...
  ]
}
```

There might be other changes as well.

**Comment by justnance** [comment]
@Happy2C0de - Thanks for reaching out.  What version of the CLI are you using?  Please provide the output of:

`aws --version`

**Comment by Happy2C0de** [comment]
I use:
```
aws-cli/1.16.89 Python/2.7.5
```

**Comment by Happy2C0de** [comment]
@justnance Thank you for the advice. With your help, I figured out what I was doing wrong. Now, it seems to work with the updated lifecycle configuration command. Thank you a lot for your help!!

**Comment by justnance** [comment]
@Happy2C0de - Thank you again for your feedback. Glad it is working for you.
