### ISSUE TITLE
aws cli: invalid security token on my local windows

### ISSUE THREAD

**Issue by navid1981** [aws/aws-cli#3891]

**Comment by justnance** [comment]
@navid1981 - Thanks for reaching out.  Please clarify if 

>  IAM on root use several times 

is it suppose to be 

>IAM on root `user` several times

In regards to using the [root user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html), it is [best practice not to use the access keys for the root user](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html).

Generally, we see this error when the IAM user is not set up with programmatic access or the user is missing the correct IAM permissions for the particular service which in this case is [Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html).  

Are you able to run other AWS commands without it returning the same error?

**Comment by navid1981** [comment]
@justnance Thanks for reply. I fixed the error. system variable override credential on aws config. I removed aws_access_key system variable and restart windows
Thanks

**Comment by aman353** [comment]
@navid1981 Actually when i am running command aws lambda list-functions, i am getting An error occurred (UnrecognizedClientException) when calling the ListFunctions operation: The security token included in the request is invalid.
