### ISSUE TITLE
InvalidParameterValue: not a valid identifier because it is longer than 20 characters.

### ISSUE THREAD

**Issue by paulkossler** [aws/aws-cli#3893]
Named IDs such as ReplicationGroupId when passed through the CLI will throw this "Error" for various ID parameters; however, the ID is defined by the GUI service and is a valid ID
This leads to many situations where the CLI becomes useless to seek information about services created through the CLI that automatically get IDs that are greater than 20 characters.
Please note in February 2018 Long IDs were adopted so the rules have changed
Please commonly address the ID length issue and provide a patch

**Comment by klaytaybai** [comment]
Hi @paulkossler, are you specifically referring to ElasticCache replication group IDs or other IDs?  Can you provide some examples of commands that you are struggling with and the outputs of running them with the `--debug` option?
