### ISSUE TITLE
Incorrect install instructions on aws-cli homepage

### ISSUE THREAD

**Issue by Almad** [aws/aws-cli#39]
One should do pip install awscli, not aws-cli. 

```
almad@namtar ~/program_files/aws-cli $ pip install aws-cli
```

   Downloading/unpacking aws-cli
     Could not find any downloads that satisfy the requirement aws-cli
    No distributions at all found for aws-cli
    Storing complete log in /home/almad/.pip/pip.log

**Comment by ccemeraldeyes** [comment]
This issue is still a problem.
