### ISSUE TITLE
Slow transfer speed from s3

### ISSUE THREAD

**Issue by russ0519** [aws/aws-cli#3910]
#aws s3 cp s3://bucketname/filename.ext .
Completed 7.5 GiB/1.0 TiB (109.2 MiB/s) with 1 file(s) remaining

That speed is less than half of what the local disks can handle.  

looking at top, it's using about 300% of the CPU.  

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
15763 root      20   0 2041904 479160   5388 S 300.0  0.8   9:29.45 aws

Is there any way to get it to go faster?   It seems to be CPU bound,  It's using less than 5% of the total CPU on the box.

**Comment by justnance** [comment]
@russ0519 - Thank you for reaching out and reporting this issue.  It appears the file size is below the max limit so I'm ruling that out.  Any chance you are able to capture the `--debug` output which returns standard errors that help us understand what might be the problem?  The output will also show the CLI version in use. 

Also, what OS is in use and is it an EC2 instance?

Something that might help is lowering the maximum number of threads making requests to S3. The default is 10 but it can by lower using the [max_concurrent_requests](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html#max-concurrent-requests) configuration option.

**Comment by russ0519** [comment]
Attached is the debug log (I canceled after a few seconds).  
[debug.zip](https://github.com/aws/aws-cli/files/2847172/debug.zip)

**Comment by kdaily** [comment]
Hi @russ0519, is this issue persisting for you? Thanks!
