### ISSUE TITLE
EKS update-config not working when updating cluster

### ISSUE THREAD

**Issue by ktugan** [aws/aws-cli#3914]
I am not sure if by design. In case it isnt, executing:

```
aws eks update-kubeconfig --name dev-tools --kubeconfig ~/.kube/dev-tools
```

Yields into following the error message:
```
Cluster status not active
```
When the cluster is updating: `"status": "UPDATING",`.

**Steps:**
1. create cluster with older version
2. update-cluster to newer version
3. execute `aws eks update-kubeconfig`
4. error

------
After looking into the source code it looks like this is because it only checks for the status "Active". Everything else is not allowed.

**Comment by ktugan** [comment]
https://github.com/aws/aws-cli/blob/bbeb9a1bc72982b00d974bf35424f6f3bce26e63/awscli/customizations/eks/update_kubeconfig.py#L290

Here the line of code causing this.

**Comment by justnance** [comment]
@ktugan - Thank you for reaching out.  Just so I understand your ask here.  Are you looking for us to add a feature to improve the error messages?

**Comment by ktugan** [comment]
I should have stated my intentions clearer. From what I see there is two options to go forward:

1. kubectl works normal and as intended when the cluster is in `UPDATING`
-> I would change the code as following:
```
if self._cluster_description["status"] != "ACTIVE":
-->
if self._cluster_description["status"] not in ["ACTIVE", "UPDATING"]:
```

2. kubectl doesn't work properly while the cluster is updating: keep it as it is

Hope that makes it clearer. Sorry for not taking the time to writing it properly the first time.

**Comment by justnance** [comment]
@ktugan - Thank you for your feedback and for pointing this out.  I'm labeling this as a feature request and confusing error pending further review.

**Comment by coryflucas** [comment]
I opened PR #4036 to address this.  I confirmed all the data from the describe cluster response is available during an upgrade so there doesn't appear to be any real reason this is not currently supported this other than the `UPDATING` status did not exist when the `update-kubeconfig` functionality was added.

**Comment by coryflucas** [comment]
@justnance wondering if there is something I can do to get some review on the PR opened for this?  Thanks!

**Comment by chadlwilson** [comment]
Any chance of getting the associated PR merged @justnance and team? This is highly unexpected behaviour.

We pipeline use of `aws eks update-kubeconfig` to assume an appropriate deployment role for use with `kubectl` and `helm` deploys in ephemeral deployment agents before triggering a deployment. it's really unexpected to have inability to do this for the N minutes a cluster is upgrading.
