### ISSUE TITLE
Wrong URL returned for SQS queue when using create-queue

### ISSUE THREAD

**Issue by gshiftlabs-dburke** [aws/aws-cli#3915]
When using the aws cli to create an SYS queue (successfully) it returns the QueueUrl.  
The value returned does not match the URL of the Queue in the AWS Console.

aws --profile sca sqs create-queue --queue-name abc  --attributes "VisibilityTimeout=60"

{
    "QueueUrl": "https://us-west-2.queue.amazonaws.com/757002957923/abc"
}

If you go into the AWS console the URL will be shown as 

https://sqs.us-west-2.amazonaws.com/757002957923/abc

**Comment by justnance** [comment]
@gshiftlabs-dburke - Thank you for reaching out.  This issue looks similar to #1715.  Please review and advise if there are more questions.
