### ISSUE TITLE
S3 LS: Error during pagination: The same next token was received twice

### ISSUE THREAD

**Issue by HyperDevil** [aws/aws-cli#3917]
**AWS Version:**
aws-cli/1.16.101 Python/3.7.2 Linux/4.20.5-200.fc29.x86_64 botocore/1.12.91

**Command:** 
aws s3 ls s3://test-test/ --profile wasabi --endpoint-url=https://s3.wasabisys.com

**Error:** 
Error during pagination: The same next token was received twice: {'ContinuationToken': 'urn%3Aoid%3A9071'}

Bucket has > 100.000 objects.

This seems to have come up suddenly, also tried running version 1.16.62 and 1.16.80 but i get the same error.
I tried to look for duplicate filenames in the bucket but found none.

```
2019-02-09 12:55:14,471 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/s3/subcommands.py", line 485, in _run_main
    bucket, key, parsed_args.page_size, parsed_args.request_payer)
  File "/usr/local/lib/python3.7/site-packages/awscli/customizations/s3/subcommands.py", line 512, in _list_all_objects
    for response_data in iterator:
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 301, in __iter__
    raise PaginationError(message=message)
botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: {'ContinuationToken': 'urn%3Aoid%3A10922'}
2019-02-09 12:55:14,471 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

**Comment by justnance** [comment]
#3191 
#3022
[boto issue #1584](https://github.com/boto/boto3/issues/1584)

**Comment by HyperDevil** [comment]
Could be related although this is a regular "s3 ls" command and not (i assume) used for filter-log-events? 
Wasabi (my S3 provider) is now also looking at the server logs in the meantime.

**Comment by justnance** [comment]
@HyperDevil - Thanks for the feedback. Correct the commands are different but the issue related to pagination is similar.  I'm still investigating this issue but wanted to collect additional information to analyze the problem more.  

Is this an intermittent issue or does this happen all of the time?  
Are you able to run it multiple times with the same results?

**Comment by justnance** [comment]
@HyperDevil - I have tried to reproduce this issue with different versions of the CLI using AWS endpoints.  It worked as expected.  It appears the problem might be isolated to the `--endpoint-url=https://s3.wasabisys.com`.  It appears you might be using [their documentation](https://wasabi-support.zendesk.com/hc/en-us/articles/115001910791-How-do-I-use-AWS-CLI-with-Wasabi-) as guidance.

When you said "This seems to have come up suddenly" does the mean it worked as expected under a lower version of the CLI?  
Are the 100,000 items stored at the root of the bucket?

**Comment by HyperDevil** [comment]
Yes i am using a different S3 storage target, although in this case i don't think it matters.
I have made case with Wasabi to check their servers logs, but i don't expect anything on the server side to be broken. ( i will update this case when i get feedback from them)

I happened suddenly without any change in version number, i suspect it has to do with the amount of files. The amount of files in my bucket always increases. The files are names: urn:oid:<increasing number> 

At this moment thid problem is a permanent one, it completely stopped working.
Also tried version 1.16.62 and 1.16.80, but it fails with the same error.
I checked the bucket and did not find duplicate objects.

**Comment by justnance** [comment]
@HyperDevil - Thank you for your feedback.  It is possible information retrieved from using the `aws history show` command will provide more details to help isolate the problem.  It will have to be enabled first, the problem reproduce, and then run the command.  

https://docs.aws.amazon.com/cli/latest/reference/history/index.html
https://docs.aws.amazon.com/cli/latest/reference/history/show.html

**Comment by HyperDevil** [comment]
```
AWS CLI command entered
at time: 2019-02-14 19:39:51.466
with AWS CLI version: aws-cli/1.16.101 Python/3.7.2 Linux/4.20.5-200.fc29.x86_64 botocore/1.12.91
with arguments: ['s3', 'ls', 's3://xxxxxxxx/', '--profile', 'wasabi', '--endpoint-url=https://s3.wasabisys.com']

[0] API call made
at time: 2019-02-14 19:39:51.713
to service: s3
using operation: ListObjectsV2
with parameters: {
    "Bucket": "xxxxxxxxx",
    "Delimiter": "/",
    "Prefix": ""
}
[0] HTTP request sent
at time: 2019-02-14 19:39:51.759
to URL: https://s3.wasabisys.com/xxxxxxx?list-type=2&prefix=&delimiter=%2F&encoding-type=url
with method: GET
with headers: {
    "Authorization": "AWS4-HMAC-SHA256 Credential=xxxxx/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4abd...",
    "User-Agent": "aws-cli/1.16.101 Python/3.7.2 Linux/4.20.5-200.fc29.x86_64 botocore/1.12.91",
    "X-Amz-Content-SHA256": "xxxxxx",
    "X-Amz-Date": "20190214T183951Z"
}
[0] HTTP response received
at time: 2019-02-14 19:39:52.905
with status code: 200
with headers: {
    "Content-Type": "application/xml",
    "Date": "Thu, 14 Feb 2019 18:39:52 GMT",
    "Server": "WasabiS3/3.3.791-2019-02-06-b50720e (head05)",
    "Transfer-Encoding": "chunked",
    "x-amz-bucket-region": "us-east-1",
    "x-amz-id-2": "xxxxxx",
    "x-amz-request-id": "xxxxxxx"
}
with body: <?xml version="1.0" ?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>xxxxxxxx</Name>
    <Prefix/>
    <NextContinuationToken>urn%3Aoid%3A1092</NextContinuationToken>
    <KeyCount>1000</KeyCount>
    <MaxKeys>1000</MaxKeys>
    <Delimiter>/</Delimiter>
    <EncodingType>url</EncodingType>
    <IsTruncated>true</IsTruncated>
    <Contents>
        <Key>.s3cmd.rc1t7trk.tmp</Key>
        <LastModified>2018-12-02T11:18:21.000Z</LastModified>
        <ETag>&quot;xxxxxx&quot;</ETag>
        <Size>0</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
     etc.
[1] HTTP response parsed
at time: 2019-02-14 19:39:53.785
parsed to: {
    "Contents": [
        {
            "ETag": "\"xxxx\"",
            "Key": "urn%3Aoid%3A1000",
            "LastModified": "2018-12-02T11:18:22.000Z",
            "Size": 1270,
            "StorageClass": "STANDARD"
        },
    ],
    "ContinuationToken": "urn%253Aoid%253A1092",
    "Delimiter": "/",
    "EncodingType": "url",
    "IsTruncated": true,
    "KeyCount": 1000,
    "MaxKeys": 1000,
    "Name": "xxxxxx",
    "NextContinuationToken": "urn%3Aoid%3A10922",
    "Prefix": "",
    "ResponseMetadata": {
        "HTTPHeaders": {
            "content-type": "application/xml",
            "date": "Thu, 14 Feb 2019 18:39:53 GMT",
            "server": "WasabiS3/3.3.791-2019-02-06-b50720e (head05)",
            "transfer-encoding": "chunked",
            "x-amz-bucket-region": "us-east-1",
            "x-amz-id-2": "xxxxx//",
            "x-amz-request-id": "xxxx"
        },
        "HTTPStatusCode": 200,
        "HostId": "xxxxx//",
        "RequestId": "xxxxx"
    }
}
[2] API call made
at time: 2019-02-14 19:39:53.999
to service: s3
using operation: ListObjectsV2
with parameters: {
    "Bucket": "xxxxx",
    "ContinuationToken": "urn%3Aoid%3A10922",
    "Delimiter": "/",
    "Prefix": ""
}

[2] HTTP request sent
at time: 2019-02-14 19:39:54.048
to URL: https://s3.wasabisys.com/xxxxxxx?list-type=2&prefix=&delimiter=%2F&continuation-token=urn%253Aoid%253A10922&encoding-t
ype=url
with method: GET
with headers: {
    "Authorization": "AWS4-HMAC-SHA256 Credential=xxxxxxxxx/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-
content-sha256;x-amz-date, Signature=7ffb...",
    "User-Agent": "aws-cli/1.16.101 Python/3.7.2 Linux/4.20.5-200.fc29.x86_64 botocore/1.12.91",
    "X-Amz-Content-SHA256": "xxxxxxx",
    "X-Amz-Date": "20190214T183954Z"
}
with body: There is no associated body

[2] HTTP response received
at time: 2019-02-14 19:39:54.469
with status code: 200
with headers: {
    "Content-Type": "application/xml",
    "Date": "Thu, 14 Feb 2019 18:39:54 GMT",
    "Server": "WasabiS3/3.3.791-2019-02-06-b50720e (head05)",
    "Transfer-Encoding": "chunked",
    "x-amz-bucket-region": "us-east-1",
    "x-amz-id-2": "xxxxx",
    "x-amz-request-id": "xxxxx"
}
with body: <?xml version="1.0" ?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>xxxxxx</Name>
    <Prefix/>
    <ContinuationToken>urn%253Aoid%253A10922</ContinuationToken>
    <NextContinuationToken>urn%3Aoid%3A10922</NextContinuationToken>
    <KeyCount>1000</KeyCount>
    <MaxKeys>1000</MaxKeys>
    <Delimiter>/</Delimiter>
    <EncodingType>url</EncodingType>
    <IsTruncated>true</IsTruncated>
    <Contents>
        <Key>urn%3Aoid%3A1000</Key>
        <LastModified>2018-12-02T11:18:22.000Z</LastModified>
        <ETag>&quot;xxxxxxxxxa&quot;</ETag>
        <Size>1270</Size>
        <StorageClass>STANDARD</StorageClass>
    </Contents>
     etc.

AWS CLI command exited
at time: 2019-02-14 19:39:54.795
with return code: 255

```
The output has of course been cut down since it's too long.
There are no appearant errors, it just doesnt continue with the next API call.

**Comment by HyperDevil** [comment]
Response above @justnance

**Comment by AdrianChungie** [comment]
@HyperDevil I had the same issue when I was uploading to wasabi endpoint. I manage to fix it by making the page-size bigger (the default is 1000). You would add `--page-size 10000` or whatever size you want. In your case it would be `aws s3 ls s3://test-test/ --profile wasabi --endpoint-url=https://s3.wasabisys.com --page-size 10000`. I hope this helps.

**Comment by HyperDevil** [comment]
@AdrianChungie thank you for the tip! unfortunately when using 10 ,100 or 1000 i did not help in my case.

**Comment by AdrianChungie** [comment]
@HyperDevil hmm try using 100,000 page size and see if that works

**Comment by HyperDevil** [comment]
@AdrianChungie  fatal error: Error during pagination: The same next token was received twice: {'ContinuationToken': 'urn%3Aoid%3A808'}  with a pagesize of 100000

**Comment by HyperDevil** [comment]
The issue has suddenly resolved itself.
Wasabi had an issue on the server side.

**Comment by justnance** [comment]
@HyperDevil - Thanks for the update. Glad to hear it is working.

**Comment by crummy** [comment]
FYI we are experiencing the same thing as of today with the following command:

```
aws --endpoint-url https://cos.na-ashburn.myqcloud.com s3 sync s3://ourbucket/ourpath /tmp/repro
```

This has worked for about a year, so I suspect a change in Tencent's backend. No need to re-open this, just FYI in case anyone else googles this term.

`aws-cli/2.4.4 Python/3.9.9 Darwin/21.1.0 source/x86_64 prompt/off`

**Comment by yabetsu1993** [comment]
Experiencing the same issue, added page-size 10k for now kindly no need to open this issue am using the following cli version with 10k page-size it has the same issue trying 100k page-size, still exists in this version 
```
aws --version
aws-cli/2.25.5 Python/3.12.9 Darwin/24.1.0 source/arm64
```
