### ISSUE TITLE
Enable a parameter on the installer to control where the files are installed

### ISSUE THREAD

**Issue by bisdavid** [aws/aws-cli#3922]
A customer provided this feedback about the current bundled installer:

The current installer presents NO option for controlling the target folder of the installed files.  
I certainly thing it makes sense to support control of where the tools are installed.  

Please consider a parameter that accepts a folder path to override the default installation location.

**Comment by justnance** [comment]
@bisdavid - This seems reasonable and a good idea.  I'm labeling this as a feature request.

**Comment by kdaily** [comment]
This feature has been implemented, closing! Thanks.
