### ISSUE TITLE
output table mode reports error when I try to list tags of ec2 instance

### ISSUE THREAD

**Issue by PSLLSP** [aws/aws-cli#3925]
aws-cli reports error when I try to list tags and request to output in TABLE mode. When I run the same query and output is JSON or TEXT, it work OK.

```
$ aws --version
aws-cli/1.16.101 Python/3.6.7 Linux/4.4.0-17134-Microsoft botocore/1.12.91
```

`$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[InstanceId,PrivateIpAddress,State.Name,Tags[*]]" --output text`
some text output, ok

`$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[InstanceId,PrivateIpAddress,State.Name,Tags[*]]" --output json`
some json output, ok

**ERROR:**
```
$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[InstanceId,PrivateIpAddress,State.Name,Tags[*]]" --output table

list index out of range
```

```
$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[InstanceId,PrivateIpAddress,State.Name,Tags[?Key=`Team`]]" --output table

list index out of range
```

There should be at least one instance in the filter output. When filter returns no instances than there is no error...

**Comment by klaytaybai** [comment]
Hi @PSLLSP, your issue seems to be due to issues structuring the array into the table format.  I'm not yet aware of a solution for how to create a table that includes columns for all of your tags across all of your instances, but we can help you out with creating a table looking for a single tag. 

To get a single tag try this:
```aws ec2 describe-instances --query 'Reservations[].Instances[].[Placement.AvailabilityZone,InstanceId,InstanceType,Platform,State.Name,Tags[?Key==`Team`] | [0].Value' --output table```

You can also find all tags for a particular instance by using the [describe-tags](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-tags.html) command.

**Comment by klaytaybai** [comment]
This is also pretty closely related to https://github.com/aws/aws-cli/issues/1567,  https://github.com/aws/aws-cli/issues/621, and others

**Comment by PSLLSP** [comment]
This works (print all instance details, no query option):

`$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --output table`

This works (print only tags):

`$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].Tags[]" --output table`

This works too (print only tags):

`$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[Tags[]]" --output table`

This reports error (print instance Id and tags):

```
$ aws ec2 describe-instances --filters "Name=tag:Team,Values=MyTeam" --query "Reservations[].Instances[].[InstanceId,Tags[]]" --output table

list index out of range
```

**Comment by justnance** [comment]
@PSLLSP - Thank you for your feedback.  See if the table output works with the following sample:


```
aws ec2 describe-instances --filter "Name=tag:Version,Values=3.0.0" --query 'Reservations[].Instances[].{InstanceId:InstanceId,Tags:Tags[?Key==`Service`]|[0].Value}|[]' --output table
```

Results:

```
-----------------------------------------
|           DescribeInstances           |
+----------------------+----------------+
|      InstanceId      |     Tags       |
+----------------------+----------------+
|  i-04cadd976f759b401 |  ServiceTest   |
|  i-055344fc6aae20fdf |  ServiceTest2  |
|  i-0e2eac8a6289398d7 |  ServiceTest   |
|  i-095a25f8a1e233e04 |                |
|  i-01407ae48fa5b5e39 |  ServiceTest   |
+----------------------+----------------+
```
