### ISSUE TITLE
EFS put-lifecycle-configuration missing

### ISSUE THREAD

**Issue by waynerobinson** [aws/aws-cli#3927]
The command as per the docs https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html to update the lifecycle configuration for EFS doesn't appear to be available.

For example:

`aws efs put-lifecycle-configuration --file-system-id fs-7e0ae847 --lifecyclepolicies Key=TransitionToIA,Value=AFTER_30_DAYS`

Results in:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:

create-file-system                       | create-mount-target
create-tags                              | delete-file-system
delete-mount-target                      | delete-tags
describe-file-systems                    | describe-mount-target-security-groups
describe-mount-targets                   | describe-tags
modify-mount-target-security-groups      | update-file-system
help
```

AWS CLI version:

`aws-cli/1.16.103 Python/2.7.13 Darwin/18.2.0 botocore/1.12.93`

**Comment by justnance** [comment]
@waynerobinson - Thank you for reporting this issue.  The CLI does not control this behavior as it just echoing what is returned by the service.  This issue was discovered while running some tests internally and it was escalated to the service team.   If you'd like an update on the progress then it is recommended to the service team on their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=222).

**Comment by justnance** [comment]
@waynerobinson - Thanks for your patience.  I was able to reproduce these results.  Please try to use the following [syntax](https://docs.aws.amazon.com/cli/latest/reference/efs/put-lifecycle-configuration.html):

```
aws efs put-lifecycle-configuration --file-system-id <value> --lifecycle-policies <value>
```
Example:
```
aws efs put-lifecycle-configuration --file-system-id fs-7e0ae847 --lifecycle-policies Key=TransitionToIA,Value=AFTER_30_DAYS
```
