### ISSUE TITLE
Please add support for python-rsa 4.0

### ISSUE THREAD

**Issue by glaubitz** [aws/aws-cli#3947]
```python-rsa``` 4.0 was released on September 16, 2018 [1] and has now been uploaded to openSUSE Tumbleweed meaning that ```aws-cli``` is no longer installable on Tumbleweed due to the version constraint for ```python-rsa <= 3.5.0```.

Could you add support for ```python-rsa``` 4.0?

> [1] https://pypi.org/project/rsa/#history

**Comment by justnance** [comment]
@glaubitz - Thanks for requesting this feature.  There is already a request under #3660 which is labeled as a feature request.  To avoid duplicate efforts I'm going to close this issue so we can track the work under #3660.
