### ISSUE TITLE
"Parameter validation failed: Unknown parameter in LaunchSpecification: "IamFleetRole", must be one of:" issue

### ISSUE THREAD

**Issue by youngminpark2559** [aws/aws-cli#3955]
I executed following command to make a request for a spot instance:
```
(py36aws) young@young-desktop:~$ aws ec2 request-spot-instances --launch-specification file:///home/young/config.json
```

I got follownig erros:
```
Parameter validation failed:
Unknown parameter in LaunchSpecification: "IamFleetRole", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "AllocationStrategy", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "TargetCapacity", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "SpotPrice", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "ValidFrom", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "ValidUntil", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "TerminateInstancesWithExpiration", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "LaunchSpecifications", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "Type", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
Unknown parameter in LaunchSpecification: "InstancePoolsToUseCount", must be one of: SecurityGroupIds, SecurityGroups, AddressingType, BlockDeviceMappings, EbsOptimized, IamInstanceProfile, ImageId, InstanceType, KernelId, KeyName, Monitoring, NetworkInterfaces, Placement, RamdiskId, SubnetId, UserData
```

I searched relevant posts and those said I would need to update versions of boto3, aws cli

But I guess my versions on them are up to date
```
(py36aws) young@young-desktop:~$ aws --version
aws-cli/1.16.107 Python/3.6.8 Linux/4.14.41 botocore/1.12.97
```

I downloaded config.json from the web EC2 console page where I manually configured a spot request setting
and it's like this:
```
{
  "IamFleetRole": "arn:aws:iam::numbers_here:role/aws-ec2-spot-fleet-tagging-role",
  "AllocationStrategy": "lowestPrice",
  "TargetCapacity": 1,
  "SpotPrice": "0.0255",
  "ValidFrom": "2019-02-19T09:38:05Z",
  "ValidUntil": "2020-02-19T09:38:05Z",
  "TerminateInstancesWithExpiration": true,
  "LaunchSpecifications": [
    {
      "ImageId": "ami-0f9e8c4a1305ecd22",
      "InstanceType": "a1.medium",
      "KeyName": "deep_learning_training",
      "SpotPrice": "0.0255",
      "IamInstanceProfile": {
        "Arn": "arn:aws:iam::numbers_here:instance-profile/EC2DeepBucketAccess"
      },
      "BlockDeviceMappings": [
        {
          "DeviceName": "/dev/sda1",
          "Ebs": {
            "DeleteOnTermination": true,
            "VolumeType": "gp2",
            "VolumeSize": 75,
            "SnapshotId": "snap-03929c7df7ae45011"
          }
        }
      ],
      "SecurityGroups": [
        {
          "GroupId": "sg-0bdada3e98fc1a2ad"
        }
      ]
    }
  ],
  "Type": "request",
  "InstancePoolsToUseCount": 11
}
```

**Comment by justnance** [comment]
@youngminpark2559 - Thank you for posting this issue on the CLI repo.  I have seen this error before and usually shows up when there is a lack of required IAM permissions.  The CLI does not have control over this behavior as the error is returning from the service.  There is another post on  the [AWS forums](https://forums.aws.amazon.com/thread.jspa?threadID=236972) about parameter validation errors related to IAM permissions that might help.  It is recommended to review the [Spot Fleet Prerequisites](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-prerequisites) and [related IAM permissions](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-iam-users).  You can also reach out to the service on the [AWS EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) or contact [AWS Support](https://console.aws.amazon.com/support/home#/).

**Comment by youngminpark2559** [comment]
@justnance Thanks for the reply. To clarify, my question is that is the IAM permission for a spot instance request via web console or via AWS CLI different?

Because I could launch a spot instance (including on demand instance) via AWS web console.
I couldn't launch a spot instance via AWS CLI as posted from above.

**Comment by justnance** [comment]
@youngminpark2559 - It depends on the [configuration of the CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).  

The AWS Access Key ID and AWS Secret Access Key are the credentials used by the CLI and used to sign programmatic requests that you make to AWS.  They are associated with an IAM user or role and can be configured in a different place, such as the system or user environment variables, local AWS configuration files, or explicitly declared on the command line as a parameter.  

Your JSON output indicates you might be [assuming an IAM role](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html) called `IamFleetRole`.  This looks like the CLI is explicitly using a different IAM than what is logged into the AWS console.  I'd check the setup specifically to [permissions and trust relationship](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-role-prepare) and then review the review the [Spot Fleet Prerequisites](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-requests.html#spot-fleet-prerequisites) again.  I think the IAM role `IamFleetRole` might be missing permissions or a trusted relationship.

**Comment by youngminpark2559** [comment]
I got a pair of Access Key ID and Secret Access Key
And I configured on AWS CLI when I was installing aws cli via pip.

I'll try to see on the permission in conjunction with AWS CLI.

But if it's issue of permission, 
error message seems misleading cause it seems like saying an issue on the structure of JSON configuration file.

**Comment by akrasnov-drv** [comment]
I also have this issue (or a similar one).
It's not a permissions issue as I tested it with admin account. The same user is able to create spot request via GUI.
The json really has parameters not specified as allowed in error message (check the error messages, it's not about permissions, it's about unrecognized "strings"): IamFleetRole, AllocationStrategy, AllocationStrategy, TargetCapacity, TargetCapacity, etc.

The problem appeared when I tried using json generated by AWS console (left bottom corner of "Request Spot Instances" screen)
Is AWS console json incompatible with aws-cli? If so, for what tool is this json intended?

**Comment by ZordoC** [comment]
Hello I know this is closed but I've ran into the same problem, and found a solution that worked for me unrelated to permissions and IAM roles.

So what worked for me was actually instead of using the config.json file I just used the subset array of  "LaunchSpecifications" and remove SpotPrice. So in your case specifications.json would be:


```
   {
      "ImageId": "ami-0f9e8c4a1305ecd22",
      "InstanceType": "a1.medium",
      "KeyName": "deep_learning_training",
      "IamInstanceProfile": {
        "Arn": "arn:aws:iam::numbers_here:instance-profile/EC2DeepBucketAccess"
      },
      "BlockDeviceMappings": [
        {
          "DeviceName": "/dev/sda1",
          "Ebs": {
            "DeleteOnTermination": true,
            "VolumeType": "gp2",
            "VolumeSize": 75,
            "SnapshotId": "snap-03929c7df7ae45011"
          }
        }
```

This is what worked in the end for me! 

Then you can set up the spot price like:
`
aws ec2 request-spot-instances --spot-price "0.0255" --instance-count 1 --type "one-time" --launch-specification file://specification.json
`

The thing here was that we were using the config.json as specifications.json which is incorrect and even if you have all the roles and permissions defined it will not help.

These answer was given by my AWS Architect ! 


Hope this helps!
