### ISSUE TITLE
AWS CLI Does not sanity check region names

### ISSUE THREAD

**Issue by Sanitys** [aws/aws-cli#3959]
Hello,

I noticed that when you set a fake region or make a mistake setting the region in the AWS CLI it wont be rejected. The CLI will accept the bad region name and then try to make requests using said bad region name. Can we add logic to filter against known region names?

aws s3 ls --region bad

Could not connect to the endpoint URL: "https://s3.bad.amazonaws.com/"

Is there anything the CLI team can do to prevent this from happening?

**Comment by justnance** [comment]
@Sanitys - Thank you for posting this idea.  It seems reasonable.  I'm going to mark this as a feature request pending further review and 👍 from the GitHub Community.

**Comment by lorengordon** [comment]
If you do decide to do this, please lean on botocore and its models/endpoints.json, and not a hard-coded list of regions. I've seen many projects do the latter, and it only leads to heartache. :D

**Comment by pletnes** [comment]
I had the same issue recently. I took the "Region name" from the web UI, and got no error message. Later on, I got hit by the same error message. Suggest to run the sanity check during `aws configure`. E.g. try pinging `check.eu-central-1.aws.com` or whatever.

**Comment by justnance** [comment]
@Sanitys, @lorengordon, & @pletnes - I'm closing this issue as a duplicate as we are tracking the same feature request under #2266.  Thanks!
