### ISSUE TITLE
awscli s3 sync recursive loop on symlink handling

### ISSUE THREAD

**Issue by hholst80** [aws/aws-cli#3961]
`awscli s3 sync` gets stuck in self-recursive directory loops.

```
/usr/bin/aws --version
aws-cli/1.16.104 Python/3.7.2 Linux/4.20.8-arch1-1-ARCH botocore/1.12.94
```

Source directory:

```
holst@puff ~/awscli-s3-syncbug
$ tree -al
.
├── subdir
│   ├── problematic-link -> ../subdir/  [recursive, not followed]
│   └── welcome+again
└── welcome

2 directories, 2 files
```

Repro

```
$ aws s3 sync ~/awscli-s3-syncbug s3://<bucket>/<remotedir>
```

`awscli` will follow the self-recursive link infinitely. Or until the PATH limitation or upload limitation kicks in.

**Comment by kyleknap** [comment]
This is similar to this issue: https://github.com/aws/aws-cli/issues/3709. Let's track the conversation in that issue.
