### ISSUE TITLE
--output text results in "None" while --output json gives correct result on cloudformation changesets

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cli#3962]
Hi,

the following gives "CREATE_COMPLETE" which is correct

`aws cloudformation describe-change-set --change-set-name website-production-alb-a-1-0-7 --stack-name website-production-alb-a`

while this gives "None" which is incorrect

`aws cloudformation describe-change-set --change-set-name website-production-alb-a-1-0-7 --stack-name website-production-alb-a --output text`

`aws --version`
`aws-cli/1.16.110 Python/3.7.2 Darwin/18.2.0 botocore/1.12.100`

colleague has aws-cli/1.16.1 which also gives correct result on text.

**Comment by mivtachyahu** [comment]
I have also noticed this problem, same version, but linux. 
Iterating through versions using pip --user installs, I can see that this regression was introduced in release version 1.16.108

**Comment by sriramho** [comment]
Try using --no-paginate switch to the command and see if it resolves the issue.

**Comment by konstantinj** [comment]
@sriramho 
it does, thanks!

But y?!

**Comment by swetashre** [comment]
@konstantinj - Thank you for reporting the behavior. I was able to reproduce the issue and confirmed it as a bug. We are looking into getting this resolved. 

Followings are the commands were used to reproduce the problem:
```
$ aws cloudformation describe-change-set --change-set-name mychangeset --stack-name mystack --output text

$ aws cloudformation describe-change-set --change-set-name mychangeset --stack-name mystack --output text --no-paginate
```
I found CLI version 1.16.100 gives correct result but returns ```none``` with version 1.16.110.  If the option ```--no-paginate``` is used with  version 1.16.110 it returns the correct result.

**Comment by DenisBY** [comment]
It seems this bug is still valid:
```
aws codepipeline list-pipeline-executions --pipeline-name $1 --max-items 1 --query "pipelineExecutionSummaries[?lastUpdateTime>=\`$today\`].status | [0]"
```
returns `"Succeeded"` however with `--output text` it returns `Succeeded None`

```
$ aws --version
aws-cli/2.9.18 Python/3.10.9
```

**Comment by nickamon** [comment]
This still seems to be an issue with:
`aws-cli/2.15.16 Python/3.11.6 Linux/3.10.0-1160.105.1.el7.x86_64 exe/x86_64.rhel.7 prompt/off` 

Running the following command returns an additional `None`:
`aws ecs list-task-definitions --max-items=1 --sort=desc --query='taskDefinitionArns[0]' --output text`

Adding `--no-paginate` returns an error:
`Cannot specify --no-paginate along with pagination arguments: --max-items`

**Comment by sairohith-vanna** [comment]
I've run into this issue while listing Amplify Jobs, and looks like it's by design (as described under note in the [docs' text output section](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output-format.html#text-output). 
Removing `--max-items` and using `--no-paginate` may work but in use cases like mine where we'd need just the top slice, `grep`-ing the output seemed like a better option to filter out and exclude `None`:

`aws amplify list-jobs --app-id <app-id> --branch-name develop --max-items 1 --query 'jobSummaries[0].status' --output text | grep -v -i 'none'`
