### ISSUE TITLE
lambda invoked with log-type Tail to stdout creates null "-" file

### ISSUE THREAD

**Issue by sadams** [aws/aws-cli#3963]
```aws lambda invoke --function-name [lambdaarn] --log-type Tail -```
Correctly sends output to stdout, but also creates a file called "-" with `null` as contents.
```aws lambda invoke --function-name [lambdaarn] --log-type Tail /dev/stdout``` is incorrect differently:
```text
null{
    "StatusCode": 200,
    ...
}
```
Running on mac 10.14.3 with aws cli version 1.16.110 (via homebrew)

**Comment by swetashre** [comment]
@sadams - Thank you for your post . According to our [documentation](https://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html) when a lambda function is invoked,content of that function will be saved to the specified file . If the function response is null or there is no value set in the callback parameter then null be returned .The optional callback parameter can be used to return any data back to caller, or else return value is null.

**Comment by sadams** [comment]
Hi, thanks for the reply. 
That solves `--log-type Tail /dev/stdout`, but doesn't explain the different behaviour with `--log-type Tail -`. 
if `-` means stdout, then it should produce same result in both cases: 
```
null{
    "StatusCode": 200,
    ...
}
```. 
If `-` doesn't mean stdout, then the contents of the file `-` (or whatever path we give it) should be: 
```
null{
    "StatusCode": 200,
    ...
}
```
rather than the file `-` just containing "null" and stdout receiving 
```
{
    "StatusCode": 200,
    ...
}
```

**Comment by swetashre** [comment]
@sadams - Thanks for the reply. For this command 
```
aws lambda invoke --function-name [lambdaarn] --log-type Tail -
```
```-``` is treated as a outfile where only the function response or the value that is set in callback parameter will be saved . And if stdout is specified as outfile then that value will be displayed along with the output.

Irrespective of the outfile and function response when a lambda function is invoked it returns immediate response containing ExecutedVersion and StatusCode.

For this function
```
exports.handler = async (event) => {
    const response = {
        statusCode: 200,
       
    };
    return response;
};
```
SatusCode:200 will be saved in outfile as this parameter is set as function response .

But for this function 
```
exports.handler = function(event, context, callback) {
    console.log('value1 =', event.key1);
    console.log('value2 =', event.key2);
   
};
```
only null will be saved in outfile as the function response does not contain any value.

In both cases the ```invoke``` returns StatusCode and ExecutedVersion immediately.
Let me know it helps.

**Comment by sadams** [comment]
Thanks, makes sense. I understand that ‘-‘ has no special meaning and if i only wanted the console.log output send to stdout i should supply /dev/null as the argument, or for everything, stdout as the argument.
