### ISSUE TITLE
cp replace command is changing the content type

### ISSUE THREAD

**Issue by g-guth** [aws/aws-cli#3967]
Hi,

I have a release task on my CI/CD environment which uses the AWS CLI. 
I use a task to execute a `cp` command to change the `--cache-control` metadata from the files I have hosted on AWS S3. The command is: 
`cp s3://sourceFolder/ s3://sourceFolder/ --exclude "*" --include "*.js" --include "*.png" --include "*.css" --include "*.jpg" --include "*.gif" --include "*.eot" --include "*.ttf" --include "*.svg" --include "*.woff" --include "*.woff2" --recursive --metadata-directive REPLACE --cache-control max-age=2592000,private`

Before this command is executed I checked that all the Javascript files were with the correct content-type metadata that is `application/x-javascript`, but after the command the content-type changes to `text/plain`. 

My problem is, I would like to replace only the `--cache-control` metadata without touching the other ones. Is there a solution to this?

**Comment by swetashre** [comment]
Hi **@g-guth** - Thanks for reporting this behavior.  When an object is replaced with itself s3 will ignore the object properties or reset the values to default.  To avoid this, read all properties of the object you want to maintain and re-apply them when you replace the object.  S3 treats a object-copy the same way that it treats a fresh upload so you must explicitly set the properties that you want on the new copy and/or updated object. S3 doesn't maintain any state in this case. 

First verify the content type of object before running the command

```
$ aws s3api head-object --bucket mybucket --key test2.json --query ContentType
"application/json"

```
Now replace —cache-control metadata without changing the content type

```
aws s3 cp s3://mybucket s3://mybucket --recursive --metadata-directive REPLACE --content-type application/json --cache-control max-age=2592000,private

copy: s3://mybucket/test2.json to s3://mybucket/test2.json
copy: s3://mybucket/test3 to s3://mybucket/test3 

```
And finally verify the content type has not changed 

```
aws s3api head-object --bucket mybucket --key test2.json --query ContentType
"application/json"
```
Let me know if you have questions .
