### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by yufengshizhe** [aws/aws-cli#3969]
Can you add a speed limit parameter?
We have a broadband upload data to many accounts.
Therefore, scheduling optimization is required to increase a speed limit parameter.

**Comment by klaytaybai** [comment]
Hi @yufengshizhe, can you please provide some more details about what you are looking for?  What services and commands are you using?

**Comment by yufengshizhe** [comment]
> Hi @yufengshizhe, can you please provide some more details about what you are looking for? What services and commands are you using?

I have a lot of customers who use s3, I need to upload data to s3
But I only have one bandwidth, but there are a lot of customer accounts. I need to schedule the task, so I hope s3 can add a speed limit parameter.

**Comment by JordonPhillips** [comment]
There is a `max_bandwidth` configuration you can set. See the [config docs](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) for more details.

**Comment by yufengshizhe** [comment]
> There is a `max_bandwidth` configuration you can set. See the [config docs](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) for more details.

thanks

**Comment by bisdavid** [comment]
Just as an FYI, all of the configuration settings, environment variables, and command line options are now also documented in the CLI User Guide.  This particular setting is in the S3 specific section: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-s3
