### ISSUE TITLE
cloudformation package feature - store md5sum in s3 as metadata of the uploaded file

### ISSUE THREAD

**Issue by sdole** [aws/aws-cli#3970]
Cloudformation Package command for packaging lambda functions replaces the "Code" property with S3Bucket and S3Key properties. It would be nice if it added the "S3ObjectVersion" property. Further, it would be great if the package command could check whether the existing lambda package artifact at the desired S3 location already has the same MD5SUM and not upload new package if does. Lastly, when doing so, it should not pick a random name for the S3Key property and instead use the Logical ResourceName of the function. This way, we can achieve the following: Let's say we are deploying one or more functions and a few other things (such as SNS, SQS) in a single template... in this case, let's say we changed only the SNS topic or just one of many functions. aws cloudformation package will see that the md5sum of an unchanged function is the same as that in S3 and hence, it will not update the package in S3 and will result in a transformed template that is the same as the one deployed in cloudformation last time. This way, when a changeset is created, it will omit the unchanged lambda function. This will be great from a change management standpoint where change management is important. In this case, the md5sum can be stored in s3 as metadata of the uploaded file. 

Thanks!

**Comment by debora-ito** [comment]
Hi @sdole, marking this as a feature request, pending review.

Pinging @sanathkr for thoughts.
