### ISSUE TITLE
Unable to get the cost type of instance

### ISSUE THREAD

**Issue by xmubeta** [aws/aws-cli#3974]
There are a few different price of instance type, for example: Windows, Windows with SQL, Amazon Linux, RedHat, etc. However we cannot get this information from 'aws ec2 describe-instances'. Is there a way to get that? So that I can use this info to buy RI easily. 

Thank you.

**Comment by debora-ito** [comment]
Hi @xmubeta, if you're looking specifically for Reserved Instances available for purchase, maybe 
```
aws ec2 describe-reserved-instances-offerings
``` 
 is what you need. Take a look at the CLI Reference [docs](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-reserved-instances-offerings.html) and let us know if that helps.

If you're looking for pricing of AWS services in general, please check the [AWS Price List API](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html). This blog post provides an overview and examples of use: [AWS Price List API Update – New Query and Metadata Functions](https://aws.amazon.com/blogs/aws/aws-price-list-api-update-new-query-and-metadata-functions/).

**Comment by xmubeta** [comment]
Hi @debora-ito, thank you for your reply.

I am not looking for what you mentioned. I am looking for the true instance type which AWS is charging. For example, I am running an EC2 with OS RedHat. I know it has different price with Amazon Linux. 

Here is the example of 'aws ec2 describe-instances':
`{
    "Reservations": [
        {
            "Instances": [
                {
                    "Monitoring": {
                        "State": "disabled"
                    },
                    "PublicDnsName": "ec2-52-81-xxx-xxx.cn-north-1.compute.amazonaws.com.cn",
                    "State": {
                        "Code": 16,
                        "Name": "running"
                    },
                    "EbsOptimized": false,
                    "LaunchTime": "2019-03-05T05:29:37.000Z",
                    "PublicIpAddress": "52.81.xxx.xxx",
                    "PrivateIpAddress": "172.31.16.69",
                    "ProductCodes": [],
                    "VpcId": "vpc-29cdaf4d",
                    "CpuOptions": {
                        "CoreCount": 1,
                        "ThreadsPerCore": 1
                    },
                    "StateTransitionReason": "",
                    "InstanceId": "i-0b51d407f670e5a56",
                    "EnaSupport": true,
                    "ImageId": "ami-0aec480c46b22c341",
                    "PrivateDnsName": "ip-172-31-16-69.cn-north-1.compute.internal",
                    "KeyName": "null",
                    "SecurityGroups": [
                        {
                            "GroupName": "launch-wizard-8",
                            "GroupId": "sg-058764ab7eb11767c"
                        }
                    ],
                    "ClientToken": "",
                    "SubnetId": "subnet-85cd7ce1",
                    "InstanceType": "t2.micro",
                    "NetworkInterfaces": [
                        {
                            "Status": "in-use",
                            "MacAddress": "02:1d:d5:2d:d6:d8",
                            "SourceDestCheck": true,
                            "VpcId": "vpc-29cdaf4d",
                            "Description": "",
                            "NetworkInterfaceId": "eni-0ddd7b352eaa6c436",
                            "PrivateIpAddresses": [
                                {
                                    "PrivateDnsName": "ip-172-31-16-69.cn-north-1.compute.internal",
                                    "PrivateIpAddress": "172.31.16.69",
                                    "Primary": true,
                                    "Association": {
                                        "PublicIp": "52.81.27.137",
                                        "PublicDnsName": "ec2-52-81-27-137.cn-north-1.compute.amazonaws.com.cn",
                                        "IpOwnerId": "amazon"
                                    }
                                }
                            ],
                            "PrivateDnsName": "ip-172-31-16-69.cn-north-1.compute.internal",
                            "Attachment": {
                                "Status": "attached",
                                "DeviceIndex": 0,
                                "DeleteOnTermination": true,
                                "AttachmentId": "eni-attach-0ed5afb6755b4461e",
                                "AttachTime": "2019-03-05T05:29:37.000Z"
                            },
                            "Groups": [
                                {
                                    "GroupName": "launch-wizard-8",
                                    "GroupId": "sg-058764ab7eb11767c"
                                }
                            ],
                            "SubnetId": "subnet-85cd7ce1",
                            "OwnerId": "096647135601",
                            "PrivateIpAddress": "172.31.16.69",
                            "Association": {
                                "PublicIp": "52.81.27.137",
                                "PublicDnsName": "ec2-52-81-27-137.cn-north-1.compute.amazonaws.com.cn",
                                "IpOwnerId": "amazon"
                            }
                        }
                    ],
                    "SourceDestCheck": true,
                    "Placement": {
                        "Tenancy": "default",
                        "GroupName": "",
                        "AvailabilityZone": "cn-north-1a"
                    },
                    "Hypervisor": "xen",
                    "BlockDeviceMappings": [
                        {
                            "DeviceName": "/dev/sda1",
                            "Ebs": {
                                "Status": "attached",
                                "DeleteOnTermination": true,
                                "VolumeId": "vol-0e3175b159633c9d1",
                                "AttachTime": "2019-03-05T05:29:38.000Z"
                            }
                        }
                    ],
                    "Architecture": "x86_64",
                    "RootDeviceType": "ebs",
                    "RootDeviceName": "/dev/sda1",
                    "VirtualizationType": "hvm",
                    "AmiLaunchIndex": 0
                }
            ],
            "ReservationId": "r-099c96c8f52f05386",
            "Groups": [],
            "OwnerId": "096647135601"
        }
    ]
}
`

There is no entry for the OS type of the instance. I cannot know what instance type I should buy RI for this instance. 

I hope you can understand my request now. Thank you.


--Beta

**Comment by debora-ito** [comment]
You can use the `ImageId` returned in `describe-instances` to run 
```
aws ec2 describe-images --image-id <ImageId_value>
```

The [`aws ec2 describe-images`](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html) output provides more detailed information on the platform.

**Comment by xmubeta** [comment]
Yep. That does give a clue. Thank you.

**Comment by debora-ito** [comment]
Glad to help! Closing.
