### ISSUE TITLE
[Question] what is the AND operator?

### ISSUE THREAD

**Issue by saidmasoud** [aws/aws-cli#3975]
On the [`resourcegroupstaggingapi:get-resources`](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html) page, the docs for the `--tag-filters` flag state:

> If you specify multiple filters connected by an AND operator in a single request, the response returns only those resources that are associated with every specified filter.

However, I an unable to determine what the AND operator is in this case, and how to utilize it. I Googled around and couldn't find anything. Any ideas?

**Comment by JordonPhillips** [comment]
It looks like this documentation is out of date: https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html

I'll let upstream know so that the confusion can be resolved. Thanks!

**Comment by saidmasoud** [comment]
Hi @JordonPhillips , it's still unclear to me how the AND operator should be used when running the `get-resources` CLI command. Could you show me an example?
