### ISSUE TITLE
Elasticsearch documentation incorrectly states a domain can start with a letter or number

### ISSUE THREAD

**Issue by DaveHewy** [aws/aws-cli#3976]
When infact only the former is true. It fails the regex if a passed domain_name does not start with a letter.

```
Domain names must start with a letter or number and can contain the following characters: a-z (lowercase), 0-9, and - (hyphen).
```

**Comment by klaytaybai** [comment]
@DaveHewy, thanks for pointing this out.  I've confirmed that it is an issue.

**Comment by DaveHewy** [comment]
@klaytaybai np. how does one contribute the fix?

**Comment by klaytaybai** [comment]
I have already asked our documentation team to make the correction, so there is nothing you need to do on your end.  If you see other areas for improvement in the documentation, you can give feedback via the link in the Feedback section of each CLI reference page.
