### ISSUE TITLE
ComputeServerLaunchTemplate does not belong to resourceCostCalculator map

### ISSUE THREAD

**Issue by radaniba** [aws/aws-cli#3978]
Hello everyone,

I am trying to use aws estimate-template-cost for a cluster that I launched using CfnCluster.
I am running through this issue

```
An error occurred (ValidationError) when calling the EstimateTemplateCost operation: Resource Type AWS::EC2::LaunchTemplate (Logical ID: ComputeServerLaunchTemplate) does not belong to resourceCostCalculator map.
```

Any idea why this Logical ID is not supported?
Thanks

**Comment by justnance** [comment]
@radaniba - Thank you for reporting this behavior.  This error looks like it is returning from the service which the CLI does not control.  I'd like to reproduce the issue.  Please provide the command you ran and/or a minimal set of steps to follow so I can reproduce the issue.

**Comment by radaniba** [comment]
Hi @justnance 

I created a CfnCluster and was trying to get the cost estimate using the s3 bucket URL to the json template.

The command I used is 

```
aws cloudformation estimate-template-cost --template-url S3_PATH_TO_A_CLASSIC_CFNCLUSTER_JSON_TEMPLATE --parameters '[{"ParameterKey":"MasterSubnetId","ParameterValue":"subnet-xxxx"},{"ParameterKey":"VPCId","ParameterValue":"vpc-xxxxx"}, {"ParameterKey":"AvailabilityZone", "ParameterValue":"us-west-2"},{"ParameterKey":"KeyName", "ParameterValue":"xxxx"}]'

```

You can replace the S3 link to a classic CfnCluster json template
I hope this helps

Rad

**Comment by jonesbe** [comment]
i get the same error when stack contains a custom resource.

**Comment by justnance** [comment]
@radaniba - Thanks again for the feedback.  I was able to reproduce the issue and confirmed the results returned the same error. The Resource Type `AWS::EC2::LaunchTemplate` is not supported by the [Simple Cost Calculator](https://calculator.s3.amazonaws.com/index.html) which is what CloudFormation is using.  To add this Resource Type, it is recommended to reach out to the [CloudFormation Service team](https://forums.aws.amazon.com/forum.jspa?forumID=92) on their forums.  If you post the forum link on this issue I can escalate it internally.

**Comment by PatMyron** [comment]
`estimate-template-cost` coverage tracking here:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/217

**Comment by jpolania** [comment]
I have same problem with AWS::FSx::FileSystem resourceCostCalculator and recorded on CloudTrail
The issue was I was having duplicate tagging, make sure your tagging have a unique Key name
