### ISSUE TITLE
[WINDOWS]Unable to upload artifact

### ISSUE THREAD

**Issue by therepo90** [aws/aws-cli#3980]
aws cloudformation package not working on Windows when installing node moduels that creates .bin directory. I guess its about python double backslash paths.
I've already created issue in aws-sam-cli: https://github.com/awslabs/aws-sam-cli/issues/1033
The error is the same in this command

**Comment by swetashre** [comment]
@therepo90 - Thank you for reporting the behavior. I was not able to reproduce the same results with the latest version of CLI. I recommend updating to the latest version and let us know if you are getting the same error. It would be better if you can provide the output from ```--debug``` .

**Comment by therepo90** [comment]
This is happening when i try to package using sam build --use-container flag.
If I dont use it its okay.
with --debug  flag:

package command is called

Unable to upload artifact MyArtifact referenced by CodeUri parameter of MyArtifact resource.
[WinError 123] The filename, directory name, or volume label syntax is incorrect
'C:\\projects\\my-project\\.aws-sam\\build\\MyArtifact\\node_modules\\.bin\\sshpk-conv'
Exception: Command '['aws.cmd', 'cloudformation', 'package', '--profile', 'mfauser', '--output-template-file', 'packaged-dev.yaml', '--region', 'us-east-1', '--s3-bucket', 'my.bucket', '--template-file', 'C:\
\projects\\my-project\\.aws-sam\\build\\template.yaml']' returned non-zero exit status 255.

**Comment by swetashre** [comment]
Thank you for the --debug log . Followings were the command used to reproduce the problem 
```
C:\Users\sweta\test>sam init
```
```
C:\Users\sweta\test>cd sam-app
```
```
C:\Users\sweta\test\sam-app>cd hello-world
```
```
C:\Users\sweta\test\sam-app\hello-world>npm install request
```
```
C:\Users\sweta\test\sam-app\hello-world>cd ..
```
```
C:\Users\sweta\test\sam-app>sam build —use-container
```
```
C:\Users\sweta\test\sam-app>sam package --s3-bucket my.bucket2 --output-template-file packaged-dev.yaml --template-file .\.aws-sam\build\template.yaml

```
I found that AWS CLI is working as expected. I would recommend you to update the SAM CLI issue[#1033](https://github.com/awslabs/aws-sam-cli/issues/1033) with the full ```--debug``` log and track the progress of this issue in the SAM CLI repo.
