### ISSUE TITLE
Provide option to ignore noop in cloudformation update-stack

### ISSUE THREAD

**Issue by dustin-rcg** [aws/aws-cli#3989]
I'd like to request adding a switch `--ignore-noop` to `aws cloudformation update-stack`.

In orchestrating deployments involving cloudformation using AWS CLI in scripts, when I call `aws cloudformation update-stack` using the existing stack template, the CLI exits with exit code 255 and prints to stderr: "An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed." Let's call this a noop.

This is undesirable behavior in the common case where other actions will follow that one in the script, which depend on the stack, may have changed and need to be updated, and do not care if `update-stack` was a noop. In fact, I'd expect `update-stack` to be idempotent already.  

Currently, I'm not sure how to handle this. I really don't want to have to

- create a change set;
- inspect the change set for the noop condition; and
- delete the change set

just to detect a noop.

Given that `update-stack` is not idempotent, and rather than adding so much complexity to handle this condition in every script, it would be quite useful to just add a `--ignore-noop` switch to `aws cloudformation update-stack` that will cause it to exit with exit code 0 in this case. Specifically, I guess that would be an enhancement of the validation step returning more than just pass/fail -- another value indicating to shortcircuit the update and exit immediately with exit code 0.

**Comment by swetashre** [comment]
@dustin-rcg - Thank you for reaching out. It looks like the same feature request as this one :[#3625](https://github.com/aws/aws-cli/issues/3625) . Let's track the progress on the linked GitHub issue.  Closing this feature request as a duplicate.

**Comment by jghaines** [comment]
Well, #3625 was closed due to inactivity, :-(
