### ISSUE TITLE
aws apigateway put-method 

### ISSUE THREAD

**Issue by jpdik** [aws/aws-cli#3992]
I can't make changes into a endpoint using `aws apigateway put-method`. Always return the error:

> An error occurred (ConflictException) when calling the PutMethod operation: Method already exists for this resource

**Comment by swetashre** [comment]
@jpdik - Thank you for reporting the behavior. This error looks like it is returning from the service which CLI does not control.  I reproduced the issue using the following command:
```
aws apigateway put-method --rest-api-id oc9q3412bd --resource-id agrxceton2 --http-method POST --authorization-type NONE
```
The [put-method](https://docs.aws.amazon.com/cli/latest/reference/apigateway/put-method.html) command adds a method to an existing resource but the same error will return if the method already exists. To find out if the resource already exists, use the following:
```
aws apigateway get-resources --rest-api-id oc9q3412bd
```
Let me know if it helps.

**Comment by jpdik** [comment]
I was able to resolve it in another way, using `update-method`. Like this:

`aws apigateway update-method --rest-api-id oc9q3412bd --resource-id agrxceton2 --http-method POST --patch-operations op="replace",path="/apiKeyRequired",value="true"'`
