### ISSUE TITLE
aws iam list-users not return map which in documentation

### ISSUE THREAD

**Issue by nborisenko** [aws/aws-cli#4003]
aws iam list-users
User object should have Tags array which are not returned according doc:
https://docs.aws.amazon.com/cli/latest/reference/iam/list-users.html

**Comment by klaytaybai** [comment]
Hi @nborisenko, thank you for reporting this.  I was able to reproduce the problem.  The IAM's team documentation does say that tags should be returned in the User object, so I'll work with them to see if we can get the results fixed.  It appears to be an issue with their API and not the CLI.  In the meantime, you should be able to use [list-user-tags](https://docs.aws.amazon.com/cli/latest/reference/iam/list-user-tags.html) to get a particular user's tags via the CLI.
