### ISSUE TITLE
Incorrect documentation for DMS - Create Event Subscriptions

### ISSUE THREAD

**Issue by nick-woodward** [aws/aws-cli#4007]
### Description

The documentation for `dms create-event-subscription` claims the valid `source-type` values are:

`replication-instance | migration-task`

**This should be the following:**

`replication-instance | replication-task`

### References

https://docs.aws.amazon.com/cli/latest/reference/dms/create-event-subscription.html

**Comment by justnance** [comment]
@nick-woodward - Thanks for reporting this issue. We're looking into get this corrected.

**Comment by swetashre** [comment]
The issue has been resolved with the ```source-type``` value has been updated with valid values.
