### ISSUE TITLE
`aws deploy` can't find 'appspec.yml' if the file is in the root directory of a drive

### ISSUE THREAD

**Issue by netjordanlee** [aws/aws-cli#4011]
### Environment
`aws-cli/1.16.124 Python/3.6.0 Windows/10 botocore/1.12.114`

### Steps to reproduce
1. Create an empty drive location (can also be a network mapped drive or NTFS folder mapped drive)
2. Create a simple application with associated appspec.yml
3. Run `aws deploy` in the root directory of the drive (ex. `Z:\>aws deploy --application-name issue-4011 --s3-location s3://issue-4011/deployment.zip`)

### Actual Result
1. The error `X:\\appspec.xml was not found` is shown

Note that the path is showing two backslashes, this indicates to me that there is some issue with the path not being properly constructed.

### Expected Result
1. The application should deploy successfully

**Comment by dstufft** [comment]
What command are you using exactly? ``aws deploy`` needs an operation, like ``aws deploy push`` or similar.
