### ISSUE TITLE
Ability to pass multiple service endpoints

### ISSUE THREAD

**Issue by dpeek** [aws/aws-cli#4012]
There doesn't seem to be a way to configure more than one service endpoint. I'm using localstack for local development, and while `--endpoint-url` works great for commands that work with one service, it doesn't for "utility" commands like `cloudformation package` (which actually uploads to s3).

Would you be interested in a PR to support configuring multiple endpoints in some way? If so, how would like to see it implemented?

**Comment by dstufft** [comment]
I'm flagging this as needs discussion to get some discussion on what exactly we would want this to look like or if we even want it. Thanks!

**Comment by justnance** [comment]
@dpeek - Adding feature request pending further review and discussion.

**Comment by kellertk** [comment]
Thank you for posting your feedback here, and our apologies that we’ve been thinking this over for a long time without much forward motion. There are similar requests to implement this feature in a few of the AWS SDKs and the AWS CLI, so in order to coordinate those teams - and hopefully make the discussions a little easier to follow - we’ve created a new issue in aws/aws-sdk here: https://github.com/aws/aws-sdk/issues/229

**Comment by kdaily** [comment]
Hi all,

We recently added a pull request (https://github.com/aws/aws-sdk/pull/230) that contains a proposal based on community comments and suggestions and our own discussions. This document proposes to extend the options for configuring the endpoint to allow users to provide an endpoint URL independently for each AWS service via an environment variable or a profile subsection in the shared configuration file.

You can [read the proposal here](https://github.com/kdaily/aws-sdk/blob/endpoint-url-configuration-proposal/proposals/configure-endpoint-url.md).

For more information on how to give feedback, please see this comment on the `aws/aws-sdk` repository:

https://github.com/aws/aws-sdk/issues/229#issuecomment-1118725725

Thanks!

**Comment by kdaily** [comment]
I'm happy to announce that the ability to configure the endpoint URL via the shared configuration file and environment variables is now available in the AWS CLI v1 and v2! You can now specify the endpoint to use for all service requests through the shared configuration file and environment variables, as well as specify the endpoint URL for individual AWS services.

To start using this feature, install the AWS CLI `>=1.29.0` or `>=2.13.0`.

To read more about this feature, see the documentation page "Service-specific Endpoints" in the AWS SDKs and Tools Reference Guide:

https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html

Look forward to a blog post demonstrating the use of this feature with the AWS CLI on the [AWS Developer Tools Blog](https://aws.amazon.com/blogs/developer/)!

**Comment by kdaily** [comment]
I'm excited to announce that we have published an AWS Developer Blog post about this feature. Let us know in the feedback links on the post what you think!

https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/
