### ISSUE TITLE
SSL validation failed for https//: xxxxxxxxxx [SSL verify failed] certificate verify failed

### ISSUE THREAD

**Issue by karthikreddybaddam09** [aws/aws-cli#4017]
Can someone please help me out how to resolve this issue

**Comment by dstufft** [comment]
Can you provide some more information on what's happening here? The command you tried to run, along with the entire traceback would be very useful. In addiiton what OS are you running on and what version of Python?

**Comment by karthikreddybaddam09** [comment]
Hi, Please see below. aws-cli/1.16.114 Python/3.6.0 Windows/10 botocore/1.12.104 OS: Windows 10
--

**Comment by justnance** [comment]
@karthikreddybaddam09 - Thanks for your feedback.  We'd like to help you with this issue but need the [CLI command you're using and the output from using the '--debug' at the end of the command.>>https://docs.aws.amazon.com/cli/latest/reference/]

**Comment by karthikreddybaddam09** [comment]
aws iam list-server-certificates

**Comment by justnance** [comment]
@karthikreddybaddam09 - Thanks for your reply.  I am not able to reproduce this exact error.  Can you please run the following and post the sanitized output:

`aws iam list-server-certificates --debug` 

The output may help us understand what is happening.
