### ISSUE TITLE
ssm put parameter tags

### ISSUE THREAD

**Issue by MrAtheist** [aws/aws-cli#4020]
Would anyone advice on the correct syntax for `tags`? Here's the [doc](https://docs.aws.amazon.com/cli/latest/reference/ssm/put-parameter.html) and I always find it very cryptic with regards to `tags` section with little to no examples on how to append the tags (pretty much applies to all the api I have looked at on tagging). Also, what would be the syntax for multiple tags?

```
aws ssm put-parameter --name "KEY" --value "VALUE" --overwrite --type SecureString --key-id 1234567890 --tags Key=Env,Value=Staging

Unknown options: --tags, Key=Env,Value=Staging
```

```
$ aws --version
aws-cli/1.16.82 Python/3.7.2 Darwin/18.2.0 botocore/1.12.72
```

**Comment by swetashre** [comment]
@MrAtheist - Thank you for posting your question. Command to create a parameter with tag :
```
aws ssm put-parameter --name='test3' --value='testing3' --type='String' --tags Key=All,Value=Mytest 
```
Command to apply multiple tags :
```
aws ssm put-parameter --name='test4' --value='testing4' --type='String' --tags Key=All,Value=Mytest Key=All2,Value=Mytest2
```

And to add tags to an existing Systems Manager parameter, use the [AddTagsToResource](https://docs.aws.amazon.com/cli/latest/reference/ssm/add-tags-to-resource.html) action.

**Comment by MrAtheist** [comment]
Thanks for the quick follow up. It turns out that the cli version I have doesnt support `tags` yet. I found out while i followed the cmd prompted by the error.

`aws ssm put-parameter help`

**Comment by jagibson** [comment]
We're seeing something that may be related.

The documentation says, "if you don't want the tag to have a value, specify the parameter with no value, and we set the value to an empty string."  However this doesn't seem to work

aws ssm add-tags-to-resource --resource-type Parameter --resource-id  /mystuff/unwieldy/long/test --tags "Key=dns,Value=" help  

Error parsing parameter '--tags': Expected: '=', received: 'EOF' for input:
help
    ^

Anyone else getting this?  Using awscli 1.16.140
