### ISSUE TITLE
Sagemaker Model, EndpointConfig and Endpoint resource names not generated properly

### ISSUE THREAD

**Issue by stefnovabasiq** [aws/aws-cli#4021]
Sagemaker::Model resource does not generate proper name when part of a stack but model name is not provided. Example:

```
(Stack name = TestStack)

ModelA:
  Type: "AWS::Sagemaker::Model"
```
In this case name of the model will be (name that appears in sagemaker console): ModelA
**Expected:** TestStack-ModelA

Sagemaker::EndpointConfig resource does not generate proper name when part of a stack but model name is not provided. Example:

```
(Stack name = TestStack)

EndpointConfigA:
  Type: "AWS::Sagemaker::EndpointConfig"
```
In this case name of the model will be (name that appears in sagemaker console): EndpointConfigA
**Expected:** TestStack-EndpointConfigA

Sagemaker::Endpoint resource does not generate proper name when part of a stack but model name is not provided. Example:

```
(Stack name = TestStack)

EndpointA:
  Type: "AWS::Sagemaker::Endpoint"
```
In this case name of the model will be (name that appears in sagemaker console): EndpointA
Expected: TestStack-EndpointA

This behavior is inconsistent with other cloudformation resources naming (AWS::Lambda, AWS::Dynamodb, AWS::SQS ...)  when name property is left out.

**Comment by swetashre** [comment]
@stefnovabasiq - Thanks for your post. Please provide the CLI commands in use or a minimal set of steps to follow so i can reproduce the issue. This is the link for CLI Sagemaker Documentation.
https://docs.aws.amazon.com/cli/latest/reference/sagemaker/index.html
