### ISSUE TITLE
aws sts get-federation-token ignores --duration-seconds

### ISSUE THREAD

**Issue by Mibou** [aws/aws-cli#4022]
When I call sts for a get-federation-token, always returns expired credential whatever the duration-seconds is.

Test with duration-seconds at 4600
triggered at 14:26:23
returns expiration at 14:26:23

```
~ $ date ; aws sts get-federation-token --name test5 --duration-seconds 4600 --policy '{"Version":"2012-10-17","Statement":[the_policy_here]}' --region eu-west-1 

jeudi 21 mars 2019, 14:26:23 (UTC+0100)

{
    "FederatedUser": {
        "FederatedUserId": "xxxxxxx", 
        "Arn": "xxxxx"
    }, 
    "Credentials": {
        "SecretAccessKey": "the_secret_here", 
        "SessionToken": "the_token_here", 
        "Expiration": "2019-03-21T14:26:23Z", 
        "AccessKeyId": "the_access_key_here"
    }, 
    "PackedPolicySize": 17
}
```

Test with duration-seconds at 5600
triggered at 14:26:52
returns expiration at 14:26:53

```
~ $ date ; aws sts get-federation-token --name test5 --duration-seconds 5600 --policy '{"Version":"2012-10-17","Statement":[the_policy_here]}' --region eu-west-1 

jeudi 21 mars 2019, 14:26:52 (UTC+0100)

{
    "FederatedUser": {
        "FederatedUserId": "xxxxxx", 
        "Arn": "xxxxx"
    }, 
    "Credentials": {
        "SecretAccessKey": "the_secret_here", 
        "SessionToken": "the_token_here", 
        "Expiration": "2019-03-21T14:26:53Z", 
        "AccessKeyId": "the_access_key_here"
    }, 
    "PackedPolicySize": 17
}
```

**Comment by swetashre** [comment]
@Mibou - Thank you for reporting the behavior. 

According to our [documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetFederationToken.html) temporary credentials that are obtained by using AWS root account credentials have a maximum duration of 3600 seconds (1 hour) and if the specified duration is longer than one hour, the session obtained by using root user credentials defaults to one hour. The temporary security credentials that are obtained by using the long-term credentials of an IAM user are valid for the specified duration, from 900 seconds (15 minutes) up to a maximium of 129600 seconds (36 hours).

Please check if you are running the command with root user credential.

Please note that the Expiration date in the response is in UTC time zone and the date command output is in a timezone 1 hour ahead of UTC. Considering the timezone difference, the expiration duration is being set in your case is 3600 sec.

**Comment by Mibou** [comment]
Ok, this is correct. Thank you, I apologize, didn't see this part of the documentation.
