### ISSUE TITLE
Add ability to create roles and databases for aws_db_instance

### ISSUE THREAD

**Issue by throwable-one** [aws/aws-cli#4023]
I need to create several databases and users in rds postgres.
I can do that with postgres client or terraform provider for postgres, but my instance does not have public IP (``map_public_ip_on_launch`` is not set for subnet).

It would be convenient to have this ability for aws client tool and/or terraform aws provider, but if I understand it correctly, it can't be done unless AWS provides appropriate REST API (which, I believe, used both by aws tool and terfaform provider)

**Comment by justnance** [comment]
@throwable-one - Thanks for your post.  This feature would need to be implemented with the Service team so it could be exposed to the CLI.  I suggest reaching out to the RDS Service team via their [forums>>https://forums.aws.amazon.com/forum.jspa?forumID=60] or contacting [Premium Support>>(https://console.aws.amazon.com/support/home#/)].
