### ISSUE TITLE
Allow passing user on update-kubeconfig cli

### ISSUE THREAD

**Issue by crhuber** [aws/aws-cli#4027]
Currently running `aws eks update-kubeconfig` on version `1.16.10` generates a context with a `users: name:` defaulting to the name of the cluster arn.  We would like to switch contexts with different `AWS_PROFILES` authenticating to the same cluster.  However, `aws eks update-kubeconfig` does not allow passing different users

**Comment by crhuber** [comment]
fix title

**Comment by justnance** [comment]
@crhuber - Thanks for the great idea.  This a feature our EKS service team would have to review and implement before it would show up in the CLI.  I have submitted an internal request but would suggest following up with either a case with [AWS Support](https://console.aws.amazon.com/support/home#/) or posting the idea on the [forums for the EKS service team ](https://forums.aws.amazon.com/forum.jspa?forumID=3038).
