### ISSUE TITLE
Check if S3 objects exists using Python

### ISSUE THREAD

**Issue by girish-kamble** [aws/aws-cli#4028]
I am having some objects in S3 whose folders are named with the date they have been created on.
 like
 ```
s3bucket/SampleTest/20180110
s3bucket/SampleTest/20180111
s3bucket/SampleTest/20180112
``` 
and so on.
Inside each of these folders contains a file name "done".
 ```
s3bucket/SampleTest/20180110/done
s3bucket/SampleTest/20180111/done
s3bucket/SampleTest/20180112/done
``` 

I want to check using the date parameter(also if `done file` exists/not ) if an s3 object has been created for the day. Want to use this trigger in lambdas using Python. (new to Python)
Is there any way I can do this.

Little detailed explanation would be much helpful for me. Appreciate the help .
Thanks

**Comment by JordonPhillips** [comment]
If you want to trigger a lambda function based on object creation you can do this with S3 events. See here for more details: https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html

**Comment by girish-kamble** [comment]
> If you want to trigger a lambda function based on object creation you can do this with S3 events. See here for more details: https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html

Great.. Will check into that. Thanks.
