### ISSUE TITLE
aws s3 sync and glacier deep archive - InvalidObjectState

### ISSUE THREAD

**Issue by nokiomanz** [aws/aws-cli#4039]
Hi,

Following the announcement of glacier deep archives. I modified my lifecycle policy to first move to glacier and then move to deep archives. On the following day. Object older than x days had been moved to deep archive.

I have a script that run on that bucket that rsync file back locally for double backup. For object that were glacier I added to my command --ignore-glacier-warnings which made my script run fine and return without error. Like this
aws s3 sync --delete --ignore-glacier-warnings s3://mybucket/myfolder/ /localbackup/

With the addition of deep archive, I get the following message.
An error occurred (InvalidObjectState) when calling the GetObject operation: The operation is not valid for the object's storage class
My script still runs fine. But I get a bunch of this error for each object in glacier deep arvice.

I tried updating my awscli to latest version following this
https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html
Still with the same result.

If I run my rsync command on a specific object that is under glacier deep archives I don't get any message and it does nothing since it just can't.

**Comment by swetashre** [comment]
@nokiomanz - Thank you for reporting the behavior. I am able to reproduce the issue and marking it as a bug . The sync command does not currently works with Deep Archive class storage objects. You are getting the error because Deep Archive objects stored in s3 cannot be downloaded/copied without restoring them.

**Comment by vz10** [comment]
Hi @nokiomanz ,

In AWS CLI version 2.0.15 this issue has been fixed.

Could you please try it out and confirm that it resolved your issue.
