### ISSUE TITLE
OpenId connect support  to generate temporary credentials

### ISSUE THREAD

**Issue by forty** [aws/aws-cli#4045]
Hello,
I feel a feature like https://github.com/openstandia/aws-cli-oidc would be a great addition to AWS cli (I haven't tried this project yet but we do something similar, and the code looks good).
It allows the generation of temporary AWS credential by simply opening an URL in the browser using oidc. This is a great feature, and as this is security sensitive, I would rather have it in the official client than on a random client on GitHub.
Syntax idea:
`aws oidc get-temporary-credentials --config=configfile.json` (this opens the browser and output the result of AssumeRoleXXXX)
What do you think?

**Comment by justnance** [comment]
@forty - Thanks for your post.  Looks like you might be interested in checking out [AWS Security Token Service (STS)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html).  There is a command you can use that [returns a set of temporary credentials for an AWS account or IAM user.](https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html):

`aws sts get-session-token`

You can also [control the output from the CLI ](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html)to json or text: 

```
$ aws sts get-session-token --output json > output.json

```
```
$ aws sts get-session-token --output text > output.txt
```

Please let us know if this would work for your use case.

**Comment by forty** [comment]
@justnance Sorry for the late answer. No, that would not work for me, my goal is to login using oidc/saml, which get-session-token doesn't allow.
Thanks

**Comment by justnance** [comment]
@forty - Thanks for the feedback.  We are discussing [a similar feature for CLI V2](https://github.com/aws/aws-cli/issues/3587#issuecomment-442442317) which we are tracking  under #3587.  I'm going to close this issue so we can centralize the discussion and avoid duplicate efforts.  Please 👍 or comment on #3587.
