### ISSUE TITLE
Get Lambda version for $LATEST

### ISSUE THREAD

**Issue by pjarts** [aws/aws-cli#4051]
We use Lambda aliases to manage versions in our environments. The _dev_ alias always points to $LATEST, while _test_ and _prod_ points to a specific version number. When I've made a new deploy to dev and made sure that it works as intended I need to up the _test_ alias to the latest version number, but I find it quite hard to retrieve. It seems the only way to get it via aws-cli is to loop over the `lambda list-versions-by-function` command until I reach the last page and then echo out the last item in the list. Is there an easier way? I would be nice if the version number was listed in the `list-aliases` command. Currenty it gives me version numbers for _test_ and _prod_, but only $LATEST for _dev_.

**Comment by klaytaybai** [comment]
Hi @pjarts, [$LATEST is a version](https://docs.aws.amazon.com/lambda/latest/dg/versioning-intro.html), so it is expected that list-aliases would return that for your "dev" alias.  If you want to test a specific snapshot while continuing to change $LATEST, publish a new version first (and maybe give it a description indicating that you plan to test something).  If you do this by running the [publish-version command](https://docs.aws.amazon.com/cli/latest/reference/lambda/publish-version.html) in the CLI, the output should contain the new version number that you can then use to set your test alias.

**Comment by pjarts** [comment]
Thank @klaytaybai. Our problem was that publishing new versions and changing the alias pointer was done in two different places, but thanks to your guidance with the publish-version command I could tweak the publish system to display the latest published version. However, I do think it's inconvenient to get the lambda version in ascending order when running the list-versions-by-function command. In the console, they are listed in descending order.. A `--sort` option would be handy 👍

**Comment by klaytaybai** [comment]
Hi @pjarts, sorry for a delay in follow-up.  You can get the max version by utilizing the query options and JMESPath.  See [CLI global options](https://docs.aws.amazon.com/cli/latest/reference/index.html) and [JMESPath Specification](http://jmespath.org/specification.html#func-max-by).

`aws lambda list-versions-by-function --function-name <value> --query "max_by(Versions, &Version).{Version:Version}"`

FYI, there is also a sort_by and reverse function.

**Comment by pjarts** [comment]
Hi @klaytaybai, thanks for your response and I'm sorry for this late reply. Just wanted to add that jmespath queries will only operate on the result of the current page. If there is more than one page of results the `--query` option with the query you provided won't return the correct version until you reach the last page.

**Comment by smatsumoto78** [comment]
Hi @klaytaybai, I'm also interested in getting the newest of published version efficiently. And I guess @pjarts is right. JMESPath solution is only getting the max value within the pagenated result.

**Comment by smatsumoto78** [comment]
After commenting that, I tried `aws lambda publish-version` several times, and when the code is not changed, the version is not incremented and get the up-to-date version number. 

So, we can get the latest version invoking `aws lambda publish-version` even if the lambda code is not changed.

**Comment by carnesen** [comment]
The solution `aws lambda list-versions-by-function --function-name <value> --query "max_by(Versions, &Version).{Version:Version}"` provided by @klaytaybai is incorrect if you have more than 9 versions because it sorts alphabetically, e.g. "10" is LESS THAN "9".

**Comment by klaytaybai** [comment]
Thanks for the corrections.  I'm going to reopen this and see it resolved to a simple solution.

**Comment by mokoaki** [comment]
Is this solution effective?

```
aws lambda list-versions-by-function --function-name <value> --query "Versions[-1].[Version]"
```

As you know, the "query" CLI option is only formatted at the time of output, so there will be a limit.

**Comment by carnesen** [comment]
@mokoaki Yes that works for me!

**Comment by xc938** [comment]
@mokoaki THANK YOU!

**Comment by pjarts** [comment]
It looks like you can add the option `--no-paginate` in order to get the entire result set in one request.

**Comment by kdaily** [comment]
Looks like this is resolved. Thanks everyone for your contributions!

**Comment by eliskovets** [comment]
When you have 1000+ versions for a lambda, it's still a pain to get a latest published. I would prefer to have a proper solution on the AWS side.  
@kdaily would you mind to reopen the issue or should I create a new one? 
My issue is specific to boto3, but I believe it's the API limitation, right?

**Comment by jacoor** [comment]
I did it like so
`aws lambda list-versions-by-function --function-name {name} --max-items 10000 --page-size 10000 --query "reverse(Versions)[:1].{Version:Version}"`
I have 635 versions.
AWS CLI v2.
