### ISSUE TITLE
Periodic progress output

### ISSUE THREAD

**Issue by ucjonathan** [aws/aws-cli#4054]
Could we have an option to output progress like one a second or every X seconds?  Right now if you run a high speed aws s3 sync with Systems Managers Session you are going to basically overload the text throughput of that window.   Possibly a --period-progress parameter?

**Comment by jamesls** [comment]
Thanks for reporting, I think we should probably just automatically handle this for you.  We can track how often we're updating the terminal and ensure we're not printing too fast.
