### ISSUE TITLE
unable to list content in aws s3 bucket

### ISSUE THREAD

**Issue by ghorpade84** [aws/aws-cli#4056]
Hello, 

Below are the things i have tried but no luck.

my s3 bucket name: narayan5656

aws s3 ls

SSL validation failed for https://s3.ap-south-1a.amazonaws.com/ hostname 's3.ap-south-1a.amazonaws.com' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'
[root@narayan ~]# curl https://s3.ap-south-1.amazonaws.com/narayan5656

aws s3 ls narayan5656

SSL validation failed for https://narayan5656.s3.ap-south-1a.amazonaws.com/?list-type=2&delimiter=%2F&prefix=&encoding-type=url hostname u'narayan5656.s3.ap-south-1a.amazonaws.com' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'
ws s3 ls http://s3.ap-south-1.amazonaws.com

Error parsing parameter 'paths': Unable to retrieve http://s3.ap-south-1.amazonaws.com: received non 200 status code of 307

**Comment by swetashre** [comment]
@ghorpade84 - Thank you for reporting the behavior. I was not able to reproduce the issue. Please provide me the ```--debug``` log.
