### ISSUE TITLE
rds describe-reserved-db-instances-offerings help output returns errors

### ISSUE THREAD

**Issue by nathan333** [aws/aws-cli#4064]
Running 
`aws rds describe-reserved-db-instance-offerings help`  returns information regarding the command, however in the `Examples` section, it seems the output returned is not the expected output. 

`EXAMPLES
       To describe reserved DB instance offerings

       This example describes reserved DB instance options for oracle:

          aws rds describe-reserved-db-instances-offerings \
          --product-description oracle

       Output:

          {

       System Message: ERROR/3 (<string>:, line 208)
              Unexpected indentation.

          ReservedDBInstancesOfferings : [

                 {      "CurrencyCode": "USD", "UsagePrice": 0.0,  "ProductDe-
                        scription":  "oracle-se2(li)", "ReservedDBInstancesOf-
                        feringId":     "005bdee3-9ef4-4182-aa0c-58ef7cb6c2f8",
                        "MultiAZ":  true,  "DBInstanceClass":  "db.m4.xlarge",
                        "OfferingType": "Partial Upfront", "RecurringCharges":
                        [

                 System Message: ERROR/3 (<string>:, line 218)
                        Unexpected indentation.

                            {      "RecurringChargeAmount":   0.594,   "Recur-
                                   ringChargeFrequency": "Hourly"

                            System Message: WARNING/2 (<string>:, line 221)
                                   Definition list ends without a blank  line;
                                   unexpected unindent.

                                   }

                 System Message: WARNING/2 (<string>:, line 222)
                        Block  quote  ends  without  a  blank line; unexpected
                        unindent.

                        ], "FixedPrice": 4089.0, "Duration": 31536000

          System Message: WARNING/2 (<string>:, line 225)
                 Definition list ends without a blank line;  unexpected  unin-
                 dent.

                 },

       System Message: WARNING/2 (<string>:, line 226)
              Block quote ends without a blank line; unexpected unindent.

              <...output omitted...>

              }
`

in turn, this returns the following help command itself: 
`<string>:208: (ERROR/3) Unexpected indentation.
<string>:218: (ERROR/3) Unexpected indentation.
<string>:221: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
<string>:222: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:225: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
<string>:226: (WARNING/2) Block quote ends without a blank line; unexpected unindent.`

CLI version is `aws-cli/1.16.140`

**Comment by swetashre** [comment]
@nathan333 - Thank you for reporting the behavior. There was a indentation problem in the .rst file for command rds describe-reserved-db-instances-offerings that's why you were getting those error. 

I fixed it and submitted a PR #4098 for it.

**Comment by swetashre** [comment]
PR #4098 has been merged. Closing issue.
