### ISSUE TITLE
aws rds-data execute-sql fails, urging to use ExecuteStatement API

### ISSUE THREAD

**Issue by domcorvasce** [aws/aws-cli#4086]
I first got this error when I was using AWS SDK in Node, but then I tried replicating it with the AWS CLI. 

I got the same result:

```
An error occurred (BadRequestException) when calling the ExecuteSql operation: This API is deprecated and not available. Use ExecuteStatement API instead
```
I know **Data API** are beta, but I couldn't find any reference of _Execute Statement API_ in the "AWS SDK for Node" documentation, nor in the `rds-data` _man_ page.

**Region**: `eu-west-1`

**Comment by colbenkharrl** [comment]
I am getting the same behavior. Any known workarounds? I am trying to set up a Lambda API which uses serverless Aurora but all of my `executeSql` calls throw this error.

**Comment by justnance** [comment]
@domcorvasce and @colbenkharrl - Thank you for reporting this issue.  We are aware of this issue and working on it internally.  As soon as there is more information to share, I will post another comment.

**Comment by srchase** [comment]
@colbenkharrl 

Which region are you using?

Per the documentation [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html), the data-api is only available in us-east-1.

**Comment by gladosguru911** [comment]
Apologies for the inconvenience. Please reach out to rds-data-api-feedback@amazon.com for the latest preview documentation.

**Comment by nitesmeh** [comment]
Here is the latest preview documentation,

https://s3-us-west-2.amazonaws.com/rds-data-preview/Amazon+Aurora+Serverless+Data+API_Preview-05-01.pdf

**Comment by pmd30011991** [comment]
I also getting the error with rds-data 

My cloudformation stack has building on ap-southeast-1 then I’m trying to connect rds aurora serverless on us-east-1 side. Getting 403 rds-data:ExecuteStatement

**Comment by benkeil** [comment]
Had the same issues, solved it adding the `--database` param
