### ISSUE TITLE
Simple use errors result in excessive stack trace

### ISSUE THREAD

**Issue by john-aws** [aws/aws-cli#4088]
A simple user error such as a mis-spelled credentials profile in the following invocation:

`AWS_PROFILE=prod1 aws s3 ls`

results in excessive output, such as:

> Traceback (most recent call last):
>   File "/usr/local/bin/aws", line 27, in <module>
>     sys.exit(main())
>   File "/usr/local/bin/aws", line 23, in main
>     return awscli.clidriver.main()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 59, in main
>     rc = driver.main()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 193, in main
>     command_table = self._get_command_table()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 102, in _get_command_table
>     self._command_table = self._build_command_table()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 122, in _build_command_table
>     command_object=self)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/session.py", line 671, in emit
>     return self._events.emit(event_name, **kwargs)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/hooks.py", line 356, in emit
>     return self._emitter.emit(aliased_event_name, **kwargs)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/hooks.py", line 228, in emit
>     return self._emit(event_name, kwargs)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/hooks.py", line 211, in _emit
>     response = handler(**kwargs)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
>     service_name=original_command.service_model.service_name,
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 318, in service_model
>     return self._get_service_model()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/awscli/clidriver.py", line 335, in _get_service_model
>     api_version = self.session.get_config_variable('api_versions').get(
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/session.py", line 233, in get_config_variable
>     logical_name)
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/configprovider.py", line 226, in get_config_variable
>     return provider.provide()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/configprovider.py", line 323, in provide
>     value = provider.provide()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/configprovider.py", line 382, in provide
>     config = self._session.get_scoped_config()
>   File "/Users/john/Library/Python/3.7/lib/python/site-packages/botocore/session.py", line 334, in get_scoped_config
>     raise ProfileNotFound(profile=profile_name)
> botocore.exceptions.ProfileNotFound: The config profile (prod1) could not be found

It might be cleaner to emit:

> botocore.exceptions.ProfileNotFound: The config profile (prod1) could not be found

or simply:

> Error: The config profile (prod1) could not be found

And possibly emit the full stack trace if, and only, if `--verbose` is present.

**Comment by justnance** [comment]
@john-aws - Thank you for pointing this out.  I've marked this has confusing error and enhancement pending further review.

**Comment by tim-finnigan** [comment]
Running this command: `AWS_PROFILE=prod1 aws s3 ls`

Now results in just: `The config profile (prod1) could not be found`
