### ISSUE TITLE
apigatewayv2 get-api-mappings empty response

### ISSUE THREAD

**Issue by pavel-ignatiev** [aws/aws-cli#4095]
I'm trying to create or update an api mapping using apigatewayv2 cli (same with SDK) and would like to check existing mappings first for this purpose.
Both CLI and SDK equivalents of **aws apigatewayv2 get-api-mappings** return an empty response even though an api mapping was successfully created before.

Here's the api mapping creation command and the correspondent output log:

`aws --debug --region eu-central-1 MYDOMAIN create-api-mapping --api-id emoqsa6plf --domain-name MYDOMAIN --stage dev &> create-api.log`

[create-api.log](https://github.com/aws/aws-cli/files/3108041/create-api.log)

I don't provide an ApiMappingKey here since this parameter is not required (an empty string '' when using SDK).

Then the get-api-mappings command and log:

`aws --region eu-central-1 apigatewayv2 get-api-mappings --domain-name MYDOMAIN --debug &> get-api-mappings.log`

[get-api-mappings.log](https://github.com/aws/aws-cli/files/3108043/get-api-mappings.log)

Am I doing something wrong here (ApiMappingKey must be non-empty?) or is it a legit bug?

**Comment by swetashre** [comment]
@pavel-ignatiev - Thank you for your post. I executed the command using latest version of CLI(1.16.144) and it is working as expected. 
```
$ aws apigatewayv2 get-api-mappings --domain-name mydomain --region us-west-2 
{
    "Items": [
        {
            "ApiId": "y3jbq7qhp4", 
            "ApiMappingKey": "", 
            "ApiMappingId": "bvayc8", 
            "Stage": "dev"
        }
    ]
}
```
I would recommend updating your CLI version. Here is the link https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

**Comment by pavel-ignatiev** [comment]
@swetashre - Thank you for your quick response! The version of AWS CLI was indeed the issue here, get-api-mappings is working fine in v1.16.144 as well as in AWS SDK for Javascript v2.441.0
