### ISSUE TITLE
Fix ec2 import-key-pair

### ISSUE THREAD

**Issue by boosh** [aws/aws-cli#41]
On Ubuntu 12.04 I ran ssh-keygen and wrote the output to particular (non-default) file.

When I try to use the 'aws ec2 import-key-pair' command it fails, complaining the .pub file isn't in OpenSSH format. However the same key works fine with the java CLI tools.

**Comment by ssbarnea** [comment]
The fact that we are required to write `--public-key-material file://~/.ssh/id_rsa.pub` instead of just specifying the filepath is really a bad UX.

**Comment by jtheuer** [comment]
+1
I also think that the file:// is really not intuitive, in fact I don't know any other cli using it. And at least the shell I use (fish) can't do auto-completion for filenames.

**Comment by rayluo** [comment]
I would agree that `file://` (or sometimes even more-unintuitive `fileb://`) is not obvious. Yet the reason of introducing such syntax in the first place is that, many AWS parameters can accept input either as a literal string in command line, or read it from a file (or from a URL). So we need a special syntax to differentiate the two scenarios. Is there any other syntax which is more intuitive? Possibly. Any new suggestion is welcome.

**Comment by k00754** [comment]
Why not just check if the parameter meets the format for a ssh private key and if not, open it as a file?  AWS is already pretty restrictive on what it will take as a public key. (No DSA, no non-standard lengths, etc.)

Also, it doesn't help that the --help option in command line tools says:

> "--public-key-material" (blob)
> 
>   The public key. You must base64 encode the public key material
>   before sending it to AWS.

This indicates that the user has to base64 encode the public key, when in fact it's being done by the client and the user should NOT base64 encode it.

**Comment by k00754** [comment]
Or if you want less ambiguity and corner case coding, consider adding a --public-key-file to specify a filename.

**Comment by so0k** [comment]
this is still not documented on the [ec2 key pair user guide](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws) nor in the [ec2 import-key-pair](http://docs.aws.amazon.com/cli/latest/reference/ec2/import-key-pair.html) guidelines...

**Comment by o6uoq** [comment]
+1

**Comment by jcheroske** [comment]
Good lord! The pain!

**Comment by pcgeek86** [comment]
Had the same issue with the `Import-EC2KeyPair` command in PowerShell. Here's how I fixed it:

```powershell
# Get file contents as a single string
$RawKey = Get-Content -Raw -Path /path/to/key

# Cast string to char array
# Cast char array to byte array
# Call ToBase64String() method on result
$KeyMaterial = [System.Convert]::ToBase64String([byte[]][char[]]$RawKey)

# Import the Base64-encoded key material
Import-EC2KeyPair -PublicKeyMaterial $KeyMaterial -KeyName trevor
```
