### ISSUE TITLE
Feature Request : Cancel pending restore jobs

### ISSUE THREAD

**Issue by baptiste-mnh** [aws/aws-cli#4100]
Hi,
It looks like there is no way for now to cancel pending job.
Is it in the roadmap? Otherwise it could be great to have it.

Thanks!

**Comment by justnance** [comment]
@baptiste-mnh - Thank you for your post.  I have confirmed with our storage team that [canceling a job is not included the job operations](https://docs.aws.amazon.com/amazonglacier/latest/dev/job-operations.html).  Once the call is made and service returns a successful response, the job starts processing and can not be canceled.  Adding a feature to cancel the job would need to come from the service team first before it can be added to the CLI.   

Please reach out to the service team on their AWS developer forums ([S3](https://forums.aws.amazon.com/forum.jspa?forumID=24) or [Glacier](https://forums.aws.amazon.com/forum.jspa?forumID=140)).
