### ISSUE TITLE
aws ec2 delete-tags --resources does not function as documented

### ISSUE THREAD

**Issue by thanatos** [aws/aws-cli#4109]
The following command fails:

```
» aws ec2 delete-tags --resources 'i-1234abcd i-9876dcba' --tags "Key=role,Value=test"

An error occurred (InvalidID) when calling the DeleteTags operation: The ID 'i-1234abcd i-9876dcba' is not valid
```
(Fake IDs have been substituted.)

According to the documentation, the supplied syntax is correct:
```
 --resources (list)
    The IDs of one or more resources, separated by spaces.
```

That is the value supplied. However, the docs go on,

```
Syntax:

   "string" "string" ...
```

This example is different from the prose: this includes quotes around the identifiers. If we actually attempt that syntax, escaping properly for the shell,

```
» aws ec2 delete-tags --resources '"i-1234abcd" "i-9876dcba"' --tags "Key=role,Value=test"

An error occurred (InvalidID) when calling the DeleteTags operation: The ID '"i-1234abcd" "i-9876dcba"' is not valid
```

The syntax that appears to be the correct one is to specify the list in JSON:
```
» aws ec2 delete-tags --resources '["i-1234abcd", "i-9876dcba"]' --tags "Key=role,Value=test"

An error occurred (UnauthorizedOperation) when calling the DeleteTags operation: You are not authorized to perform this operation.
```
(The permission error is insignificant. I'm replicating this w/ my local account, which lacks perms, but the original issue occurs in a context where I have permissions.)

Can the docs match the actual parser?

**Comment by swetashre** [comment]
@thanatos - Thank you for your post. 
```
» aws ec2 delete-tags --resources 'i-1234abcd i-9876dcba' --tags "Key=role,Value=test"
```
For this command  CLI will take both resource ids as one id and that's why it will give invalid id error.
Here is the command for deleting a tag from multiple resources:
```
$  aws ec2 delete-tags --resources i-1234abcd i-9876dcba --tags "Key=role,Value=test"
```
