### ISSUE TITLE
Validate swagger file before upload to server 

### ISSUE THREAD

**Issue by hendrixroa** [aws/aws-cli#4110]
Would be great if we can do:
```bash
aws apigateway validate-swagger --file file://mypath/swagger.json
// Return
{ valid: true | false, warnings: [ list of warnings similar to failOnWarnings params ] }
```
Before upload to server. I know that exist the param `failOnWarnings` for importRestApi and PutRestapi.

**Comment by justnance** [comment]
@hendrixroa - Thank you for submitting this idea.  Would you say it is similar to having a `--dry-run` option?

**Comment by hendrixroa** [comment]
Exactly, having a cmd to validate x-apigateway-* integrations before upload to server.

**Comment by justnance** [comment]
@hendrixroa - Thanks again for the feedback.  To consolidate and avoid duplicate efforts I'm going to close this issue as a duplicate as we are tracking this feature request under issue #1965.
