### ISSUE TITLE
aws ecr list-tags-for-resource always returns null

### ISSUE THREAD

**Issue by jth08527** [aws/aws-cli#4111]
When trying to get a list of tags, null is always returned, even if there are tags set.

Steps to repro:
    1. Create a new ECR repo
    2. Add 1 or more tags to repo
    3. Run aws ecr list-tags-for-resource to list out the tags

Expected behavior:
A JSON array of objects containing the tags(or empty JSON array if no tags) should be returned, as described in the [documentation](https://docs.aws.amazon.com/cli/latest/reference/ecr/list-tags-for-resource.html).

Actual behavior:
null is returned

Tested on several older versions, including the latest(as of writing this):
aws-cli/1.16.146 Python/3.6.0 Windows/10 botocore/1.12.136

**Comment by justnance** [comment]
@jth08527 - I tried to reproduce the `null` output using CLI version 1.16.146 but it returned the expected results: 

```
aws ecr list-tags-for-resource --resource-arn arn:aws:ecr:us-west-2:0123456789123:repository/foobar
```

```
{
    "tags": [
        {
            "Key": "name01",
            "Value": "foo1"
        }
    ]
}
```

Test with multiple tags

```
{
    "tags": [
        {
            "Key": "Name03",
            "Value": "foo3"
        },
        {
            "Key": "Name02",
            "Value": "foo2"
        },
        {
            "Key": "Name01",
            "Value": "foo1"
        }
    ]
}
```

Test with zero tags

```
{
    "tags": []
}

```

Please reply with a sample of the syntax in step 3 of your repro steps. 

Thanks.

**Comment by jth08527** [comment]
@justnance Thank you for your reply. Looking at your output, I see my mistake. I had a --query of Tags, but I should be querying tags. It would appear that not all AWS resources share the same capitalization. Either way, I am closing this. Thanks again.
