### ISSUE TITLE
Batch Handling of HITs with MTurk CLI

### ISSUE THREAD

**Issue by rachel-1** [aws/aws-cli#4112]
It'd be very handy to be able to pass a `HITGroupID` or something to `mturk delete-hit` to be able to delete multiple HITs at once. It's a little silly that I have to write a wrapper to achieve this. 

There are a bunch of doc pages and forum posts about getting this functionality with the original MTurk CLI, but my understanding is that was deprecated in favor of putting everything under the AWS CLI. 

If I'm missing something and there is a better way for me to be doing, please this let me know.

**Comment by justnance** [comment]
@rachel-1 - Thanks for your feedback about improving MTurk.  At this time, the [MTurk API](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/Welcome.html) only support deleting on HIT at a time.  This is also true with [botocore](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mturk.html#MTurk.Client.delete_hit) and the [CLI](https://docs.aws.amazon.com/cli/latest/reference/mturk/delete-hit.html).  It is recommended to reach out to the Amazon Mechanical Turk service team via [their forums](https://forums.aws.amazon.com/forum.jspa?forumID=11) to request this feature.  As such, I did a search and found [one forum post](https://forums.aws.amazon.com/thread.jspa?messageID=195267&#195267) that matched the problem you are trying to solve but it is rather old.  If you can reply back with a more recent AWS forum post, I will escalate this feature request to the service team.  

I also want to point out that AWS generally uses [Tags](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/tag-editor.html) to group like objects which might be ideal but the service team would need to add this feature first.

**Comment by rachel-1** [comment]
[Here](https://forums.aws.amazon.com/thread.jspa?threadID=303012) is the thread. Thanks for the prompt response.

**Comment by justnance** [comment]
@rachel-1 - Thanks for your feedback back.  It looks like an AWS agent has acknowledge the feature request for the service.  The CLI will be updated once the service team implements the feature.
