### ISSUE TITLE
aws s3 sync - could have better parameter checking :-)

### ISSUE THREAD

**Issue by aleks-mariusz** [aws/aws-cli#4126]
This is as much of a feature request, as an embarrassing confession of me fat-fingering a command - which at least hopefully is amusing to whoever reads this..  But, in all seriousness, leads me to wonder if the aws s3 functionality could do a better job of parameter validation:

Yesterday evening I was trying to manually sync two buckets between regions, and wrote out the following:

```aws s3 sync s3://source-bucket-name s://destination-bucket-name --source-region us-east-1 --region eu-west-1```

Unfortunately, what I failed to realize is that the _destination_ parameter i had written was just *s://*... instead of s3:// and so the tool dutifully created a local folder named "s:" with a subfolder named after the destination-bucket.. not _really_ what i had hoped for :-( especially since i had left for the day, and found the next morning that i had inadvertently transfered 230gb out of S3 (ouch) and filled up my root volume.. 

so, after I was done shaking my head, I would like to request that `aws s3 sync` perhaps does a better of validating parameters, and maybe realize that "s:" isn't a typical folder name, or that two forward slashes shouldn't be treated as simply a subfolder?

**Comment by justnance** [comment]
@aleks-mariusz - Thanks for the amusing read and being curious about the functionality of the CLI and parameter validation.  To clarify, the CLI has a configuration setting called parameter_validation which [specifies whether the CLI client attempts to validate parameters before sending them to the AWS service endpoint](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).  This configuration is enable or set to true by default but can disabled or set to false:

> • true: This is the default value. When configured, the CLI performs local validation of command
line parameters.
• false: When configured, the CLI does not validate command line parameters before sending them
to the AWS service endpoint.

The parameter validation does not validate the value of the parameter which appears to be what you are pointing out.   As such, I found we are tracking a feature request under issue #1965 for adding `dry-run option` that might be ideal for what you are requesting.  Please let us know if you agree and 👍 issue #1965.
