### ISSUE TITLE
feature: cloudformation deploy --tags should accept a file

### ISSUE THREAD

**Issue by neilhwatson** [aws/aws-cli#4127]
The deploy command should operate as create or update-stack does, including --tags taking a file:// option

**Comment by justnance** [comment]
@neilhwatson - Thanks for your idea.  I think we might be tracking this feature request under #2828.  Please advise if you think it is different.  

@sanathkr - what are your thoughts?

**Comment by neilhwatson** [comment]
#2828 is for parameters, this issue is for tags. But they are similar.

**Comment by justnance** [comment]
@neilhwatson - Thanks for your feedback.  I'm going leave this issue open and labeled as a duplicate and needs discussion pending feedback from @sanathkr.

**Comment by hsnopi** [comment]
I'd add to this. In addition it would be nice if the deploy, create-tags and update-tags could all use the same format. Specifically if it could use the same format at the TemplateConfiguration in the pipeline cfn.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity in a while. We have been advised to refer uses to the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) and the [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html) command going forward. Have you tried using the SAM CLI? It doesn't look like you can pass a file with tags there either but it's something you could also consider requesting in their repository: https://github.com/aws/aws-sam-cli.
