### ISSUE TITLE
list-command-invocations --command-id "xxx" shows "Failed" status only if the last command of the list was failed

### ISSUE THREAD

**Issue by gitrahul9** [aws/aws-cli#4132]
Run the following on an ec2 where aws cli and ssm client is configured: 
`aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "i-xxxxx" --parameters commands=["ech HelloWorld","ls","ech HelloWorld"]`

take the command id from above output and use it in the below command

```aws ssm list-command-invocations --command-id "xxxxxxxx"```

You will see that the status shown is "Failed" because the last command in the list would fail

Now run this: 

```aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "i-xxxxx" --parameters commands=["ech HelloWorld","ls"]```

check the output status again using command-id of the above command
> ```aws ssm list-command-invocations --command-id "xxxxxxxx"```

Although the first command fails but the last command passes, the status this time would be "Success".

It should have been something like this  ```if all(output_statuses_of_all_commands): return True```
or at least return status of each command in some way.

**Comment by justnance** [comment]
@gitrahul9 - Thank you for reporting this issue and providing the details steps.  I was reproduce the same results showing the "Failed" status.   I understand you would like the status to show more information.  The CLI does not have control over the this behavior as it is echoing what is returning from the service for the [`list-command-invocations` API operation](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListCommandInvocations.html).  This feature request would need to be implement in the API first.   Please reach out to the service via the [SSM forums](https://forums.aws.amazon.com/forum.jspa?forumID=185).
