### ISSUE TITLE
AWS IOT text output not consistent

### ISSUE THREAD

**Issue by sbertrand-witekio** [aws/aws-cli#4157]
I have observed an inconsistent behavior of aws cli with iot using text output.

```
aws iot list-things --query 'things[0].[thingName]' --output text
D01905160003
D01905140012
S01904040011
S01904020008
ST0312142750
S0190219D003
XDCQA1
```
There should be only 1 name shown, there are multiple. The JSON output is correct.
```
 aws iot list-things --query 'things[0].[thingName]'
[
    "D01905160003"
]
```

**Comment by JordonPhillips** [comment]
Yeah the text output is streaming output whereas the json output is buffered. This means that for text the query is applied to every page, so if you just want the first thing you need to say `--no-paginate`. In v2 we plan on making this consistent and explicit, so you could say `--output text-streaming` or `--output text-buffered` or something like that.
