### ISSUE TITLE
aws eks get-token doesn't work with --profile

### ISSUE THREAD

**Issue by streetmapp** [aws/aws-cli#4163]
When going to use `aws --profile profilename eks get-token --cluster-name eksClusterName` I receive the following error `Unable to locate credentials. You can configure credentials by running "aws configure".`. However, when I set the ENVVAR of AWS_DEFAULT_PROFILE to the profile I want, the command works fine.

I verified other eks commands work fine with the --profile option. For example: `aws --profile profilename eks describe-cluster --name eksClusterName` works as expected.

aws --version                                             
aws-cli/1.16.160 Python/3.7.0 Darwin/18.2.0 botocore/1.12.150

**Comment by oarmstrong** [comment]
Adding on to this, using the `AWS_PROFILE` environment variable doesn't utilise the CLI cache when MFA is enabled.

A quick look at the code makes me think that this isn't using the standard authentication chain, which would also explain (IMO) your issue.

I'm having a play around and will push a PR if I get anywhere.

**Comment by oarmstrong** [comment]
I've just tested PR #4159. That PR resolves this issue as well as mine that I just filed (and thus closed).

**Comment by blagerweij** [comment]
It seems that the latest versions of the CLI have support for the --profile, however it's not working as expected:
When running `aws eks update-kubeconfig --profile xxx`, it correctly updates the kube config with env AWS_PROFILE. However, the `aws eks get-token` does not work, at least not until I manually add the `--role-arn` parameter. I was hoping for a solution where we would not have to hack the config file

**Comment by justnance** [comment]
@streetmapp, @oarmstrong, & @blagerweij - Thanks for reporting this issue and testing the PR.  We are reviewing this issue and PR.  Thanks for your patience.

**Comment by blagerweij** [comment]
I've just tested the latest 1.16.185 build, and am still having issues:
When i run `aws eks update-kubeconfig --profile xxx --name yyy`, the kube config-file *does* have a the AWS_PROFILE environment variable, but the `aws eks get-token` commandline is missing `--role-arn`, and it's not able to authenticate to the cluster using an assumed role. Our AWS profile looks like this:

```
[profile deploy_prod]
role_arn = arn:aws:iam::123123123123:role/my_role
region = eu-west-1
credential_source = Environment
```

**Comment by nicolasbelanger** [comment]
@blagerweij I think I'm facing what you experienced.  What I can say for sure is that it used to work properly on:
```aws-cli/1.16.240 Python/3.7.2 Linux/4.14.177-139.254.amzn2.x86_64 botocore/1.12.230```

but not anymore on:
``` aws-cli/1.18.81 Python/3.8.3 Linux/4.14.177-139.254.amzn2.x86_64 botocore/1.17.4```

Did you get around it somehow?

**Comment by blagerweij** [comment]
@nicolasbelanger yes update the aws cli. Currently I'm using v2, which does not have this issue (and supports SSO)
