### ISSUE TITLE
aws rds create-db-instance: no endpoint returned

### ISSUE THREAD

**Issue by MaxHoefl** [aws/aws-cli#4165]
I am creating an RDS database instance (e.g. mysql db) using

```
aws rds create-db-instance \
          --db-name $dbname \
          --port $dbport \
          --db-instance-identifier $dbname \
          --db-instance-class db.t2.micro \
          --engine $engine \
          --engine-version $dbversion \
          --allocated-storage 20 \
          --master-username <masterusername> \
          --master-user-password <password> \
          --backup-retention-period 0 \
          --availability-zone=eu-west-2a \
          --publicly-accessible
```

The output json is missing the Endpoint structure.

```
{
    "DBInstance": {
        "DBInstanceIdentifier": "dbinstancename",
        "DBInstanceClass": "db.t2.micro",
        "Engine": "enginename",
        "DBInstanceStatus": "creating",
        "MasterUsername": "masterusername",
        "DBName": "dbname",
        "AllocatedStorage": 20, <--- after DBName there should be an Endpoint structure
        "PreferredBackupWindow": "05:17-05:47",
        "BackupRetentionPeriod": 0,
        "DBSecurityGroups": [],
      ....
```

Accoding to the [documentation](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html) there should be an Endpoint structure after the field "DBName"

cli version: `aws-cli/1.16.161 Python/3.6.1 Darwin/18.2.0 botocore/1.12.151`

**Comment by JordonPhillips** [comment]
The CLI can only show what the service teams actually return. In this case they probably haven't set up the endpoint yet, which is why nothing is returned there.

**Comment by almercier** [comment]
For those that are experiencing this, you have to wait for the DB to become available before the database's endpoint is created. I feel like this needs to be documented in the cli documentation because it definitely is misleading to show "Endpoint" as an available property in the output of `create-db-instance`

```
aws rds create-db-instance --db-instance-identifier $dbname ...
aws rds wait db-instance-available --db-instance-identifier $dbname
```

The results of wait is an array of DBInstances, and they should have the Endpoint in them.
