### ISSUE TITLE
Permissions for CLI User Don't Update

### ISSUE THREAD

**Issue by JimTheMan** [aws/aws-cli#4166]
To reproduce:

1) I create a role in IAM with no permissions.

2) get keys from aws console and run `aws configure`

3) Add Administrator Access role to user or user's group.

4) try to run `aws cloudformation list-stacks`

5) See Error: ____ is not authorized to perform: iam:ListRoles on resource: _____

**Comment by klaytaybai** [comment]
Hi @JimTheMan, I have a couple questions.  

In step 1, do you mean create a user with no permission policies?  I'm not sure where you are using this role in the following steps.  

In step 3, are you assuming an Administrator Access role or adding an AdministratorAccess policy?  If you're assuming a role, please check to see the permissions inside.  How are you adding the policy:  via CLI or Console?  

I tried following your steps as best as I understood them, but it did work for me.  Could you please add the results of `aws --version`
