### ISSUE TITLE
`get-resources` api is returning deleted volumes in results

### ISSUE THREAD

**Issue by dhawal55** [aws/aws-cli#4173]
I'm using the `get-resources` api to filter volumes by tag as shown below:
` aws resourcegroupstaggingapi get-resources --tag-filters=Key=foo,Values=bar --resource-type-filters=ec2:volume`

It shows me volumes that were deleted and no longer exists. 

I see no values for the below query:
`aws ec2 describe-volumes --filters=Name=tag:foo,Values=bar` 

aws --version
`aws-cli/1.16.50 Python/3.7.1 Darwin/18.6.0 botocore/1.12.40`

**Comment by JordonPhillips** [comment]
This seems like it's just eventual consistency, I imagine they'll go away after some period of time. For more details, or if they don't go away, I would recommend asking about the issue on their service forum: https://forums.aws.amazon.com/forum.jspa?forumID=218

**Comment by dhawal55** [comment]
Ya, I hope it's just eventual consistency but I waited for 20 mins and was still getting inconsistent results. It shouldn't be taking that long.
