### ISSUE TITLE
Wrong Health endpoint when using `--region` parameter

### ISSUE THREAD

**Issue by varunchandak** [aws/aws-cli#4183]
Since `health` has a single endpoint for all regions, it should not change the endpoint URL to include the `region` in the `config` file. For example,
```
$ aws --profile XXXX --region ap-southeast-1 health describe-events --output json

Could not connect to the endpoint URL: "https://health.ap-southeast-1.amazonaws.com/"
```
whereas the intended behaviour should be:
```
$ aws --profile XXXX --region ap-southeast-1 health describe-events

{
    "events": [
    {
        "arn": "arn:aws:health:ap-southeast-1::event/EC2/AWS_EC2_PERSISTENT_INSTANCE_RETIREMENT_SCHEDULED/XXXX",
        "service": "EC2",
        "eventTypeCode": "AWS_EC2_PERSISTENT_INSTANCE_RETIREMENT_SCHEDULED",
        "eventTypeCategory": "scheduledChange",
        "region": "ap-southeast-1",
        "startTime": 1234.0,
        "endTime": 5678.0,
        "lastUpdatedTime": 0123.0,
        "statusCode": "upcoming"
    }
  ]
}
```

**Comment by justnance** [comment]
@varunchandak - Thank you for reporting this behavior.  I was able to reproduce the same results.  The endpoints are listed in [botocore](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L1549). Here's an excerpt from a sample debug output for quick reference:

```
2019-06-20 22:18:38,389 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/janedoe/Library/Python/3.7/lib/python/site-packages/botocore/data/endpoints.json
```

According to our [documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html#awshealth_region), AWS Health has a single (regional) endpoint: health.us-east-1.amazonaws.com (HTTPS).   The issue with defaulting to a single endpoint is that if the service attempted to expand into a new region, the new endpoint would be ignored.  

It appears this issue may be similar to a feature requests we are tracking under #2266 to improve region validation and under #1270 for Ability to specify endpoint-url in profile.  Please 👍 either issue to let us know if you agree.

**Comment by varunchandak** [comment]
Done. Thanks for the update.
