### ISSUE TITLE
list-roles and list-users api call does not display permission-boundary policy of the role / user as stated in official  api docs

### ISSUE THREAD

**Issue by rams3sh** [aws/aws-cli#4187]
I have enforced permission boundaries in one of my roles and one of my users in my AWS account. However , I do not get the permission boundary policy displayed as part of list-roles / list-users api call as documented as part of official API docs [here](https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html) and [here](https://docs.aws.amazon.com/cli/latest/reference/iam/list-users.html)

But the same policy is being displayed when get-role  / get-user is called for the specific role / user. 

My aws-cli version 

```
C:\>aws --version
aws-cli/1.16.166 Python/2.7.16 Windows/10 botocore/1.12.156
```
**_Roles_**

Given down the output of the aws cli command with jq to give out the keys of the output for clarity :- 

```
C:\>aws iam list-roles | jq ".Roles[] | keys"
[
  "Arn",
  "AssumeRolePolicyDocument",
  "CreateDate",
  "Description",
  "MaxSessionDuration",
  "Path",
  "RoleId",
  "RoleName"
]
[
  "Arn",
  "AssumeRolePolicyDocument",
  "CreateDate",
  "MaxSessionDuration",
  "Path",
  "RoleId",
  "RoleName"
]
[
  "Arn",
  "AssumeRolePolicyDocument",
  "CreateDate",
  "MaxSessionDuration",
  "Path",
  "RoleId",
  "RoleName"
]
```

Keys of json from output of get-role for the specific role with Permissions Boundary :- 

```
C:\>aws iam get-role --role-name "RoleWithPermissionBoundarySet" | jq ".Role  | keys"
[
  "Arn",
  "AssumeRolePolicyDocument",
  "CreateDate",
  "MaxSessionDuration",
  "Path",
  "PermissionsBoundary",
  "RoleId",
  "RoleName"
]
```

**_Users_**

In case of list-users :- 
```
C:\>aws iam list-users | jq ". | .Users[] | keys"
[
  "Arn",
  "CreateDate",
  "Path",
  "UserId",
  "UserName"
]
[
  "Arn",
  "CreateDate",
  "Path",
  "UserId",
  "UserName"
]
[
  "Arn",
  "CreateDate",
  "Path",
  "UserId",
  "UserName"
]
[
  "Arn",
  "CreateDate",
  "Path",
  "UserId",
  "UserName"
]
[
  "Arn",
  "CreateDate",
  "Path",
  "UserId",
  "UserName"
]
```

In case of get-user for a specific user with permission boundary policy set :- 

```
C:\>aws iam get-user --user-name "UserWithPermissionBoundarySet" | jq ".User | keys?"
[
  "Arn",
  "CreateDate",
  "Path",
  "PermissionsBoundary",
  "UserId",
  "UserName"
]

```
Is it an issue with aws-cli or AWS API gateway or the API official doc ? 
I was not sure about it. 

Hence raising the issue here .

**Comment by JordonPhillips** [comment]
This is a matter of what the service api returns. List calls often return truncated information, though usually the service teams will call out what gets returned when. I would recommend asking about this on the [service forum](https://forums.aws.amazon.com/forum.jspa?forumID=76), as there isn't anything the CLI can do about it directly.
