### ISSUE TITLE
port 22: Operation timed out

### ISSUE THREAD

**Issue by issnoejasso** [aws/aws-cli#4189]
`aws emr ssh --cluster-id j-XXXXX --key-pair-file ~/develop.pem`

`ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=10 -i ~/develop.pem hadoop@<EMR>.compute-1.amazonaws.com -t`

> response : port 22: Operation timed out

Please help me to connect by ssh

**Comment by justnance** [comment]
@issnoejasso - Thank you for reaching out about ssh connection issues.  This error is returned by the service and not controlled by the CLI.  Usually we see this error when the security group is not allowing traffic to port 22 or attempting an connection from a resource external to the VPC (without VPN) to a cluster that resides in private subnet. 

It is recommended to reach out to the [EMR service Forums](https://forums.aws.amazon.com/forum.jspa?forumID=52&start=0) for guidance or open a [support case with AWS premium support](https://console.aws.amazon.com/support/home#/).  It also appears there are threads on the forums that already have some additional guidance such as "[Timeout trying to ssh to my new EMR](https://forums.aws.amazon.com/thread.jspa?threadID=227430)".  Our online documentation may also provide additional guidance for [Allowing SSH Connections to the Cluster](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-gs-ssh.html) and [Troubleshooting Connecting to Your (EC2) Instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html).
