### ISSUE TITLE
No way to create advanced SSM Parameters from EC2 section the AWS Console (web page)

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-cli#4191]
There is currently no way of creating advanced SSM Parameters in the EC2 section of  the AWS Console (web page), (SYSTEMS MANAGER SERVICES) (SYSTEMS MANAGER SHARED RESOURCES) . If the development on this section of the AWS console has stopped , kindly add a banner notification that not all SSM features will be available in this section , and point customers to the new systems manager console instead .  

![AWSconsole](https://user-images.githubusercontent.com/50540203/58550661-8d1aaf00-820e-11e9-864c-512646a635a2.PNG)

**Comment by JordonPhillips** [comment]
This repo is for the CLI, not the web site. You would be better asking about this on the service forums: https://forums.aws.amazon.com/forum.jspa?forumID=185
