### ISSUE TITLE
aws s3 cp into bucket not copying metadata

### ISSUE THREAD

**Issue by jmukhtar** [aws/aws-cli#4197]
Summary:
s3 copy into the bucket doesn't copy the metadata into the destination bucket. 

Details
I am trying to copy files from one s3 bucket under account A into another s3 bucket under account B. The process i am trying to use is download bucket contents locally with all of the metadata and then upload them into the destination bucket with all the metadata. But the metadata is not getting copied over to the destination bucket

Below is the command i used to download the objects form s3

`aws s3 cp s3://bucket-in-aws/app/my-sample-pdf.pdf ../direc/ --profile=prod --debug --metadata-directive 'COPY'`

Below is the extract from the debug output which shows the metadata 'x-amz-meta-filename' being downloaded 

`2019-05-31 10:50:02,028 - ThreadPoolExecutor-0_0 - botocore.parsers - DEBUG - Response headers: {'Content-Length': '496775', 'x-amz-id-2': 'fFG4w1Z/fEx5Hek0YYhiFPvJ+gZ5BAiij7f94hQjhAbnyoiatyNi2x/u4tld/skrllU9fryZfT0=', 'Content-Type': 'application/pdf', 'Accept-Ranges': 'bytes', 'Server': 'AmazonS3', 'Last-Modified': 'Wed, 28 Nov 2018 11:44:51 GMT', 'x-amz-request-id': '1B351BB9E37C0A08', 'ETag': '"fce9348ae5e66f149a7249c95278c777"', 'Date': 'Fri, 31 May 2019 10:50:02 GMT', 'x-amz-meta-filename': 'my-filename.pdf'}`

Below is the command i used to upload to the destination S3

`aws s3 cp ../direc/my-sample-pdf.pdf s3://bucket-in-aws-test/app/ --profile=test --debug --metadata-directive 'COPY'`

and below is the extract of the PUT from the debug output

`2019-05-31 10:50:32,166 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - Executing task PutObjectTask(transfer_id=0, {'extra_args': {'ContentType': 'application/pdf'}, 'bucket': u'bucket-in-aws-test', 'key': u'app/my-sample-pdf.pdf'}) with kwargs {'extra_args': {'ContentType': 'application/pdf'}, 'client': <botocore.client.S3 object at 0x7f2260e7ac10>, 'bucket': u'bucket-in-aws-test', 'key': u'app/my-sample-pdf.pdf', 'fileobj': <s3transfer.utils.ReadFileChunk object at 0x7f226016d6d0>}`

I have set following to avoid multipart upload as well but didn't help

s3 =
  max_concurrent_requests = 20
  max_queue_size = 10000
  multipart_threshold = 256MB
  multipart_chunksize = 128MB
  max_bandwidth = 50MB/s
  addressing_style = path

**Comment by JordonPhillips** [comment]
Metadata only applies to objects in S3. You will lose that by downloading to disk. To properly copy you should grant read access to your source bucket to a role in your destination bucket and then use that role to perform the copy directly.
