### ISSUE TITLE
aws codebuild secondary sources

### ISSUE THREAD

**Issue by cumal** [aws/aws-cli#4201]
Last week I created some "--cli-input-json" templates with secondary sources and worked fine.
Today, the aws cli is returning several errors about the json :

- Unknown parameter in input: "secondarySources", ...
- Unknown parameter in input: "queuedTimeoutInMinutes", ...
- Unknown parameter in input: "logsConfig", ...
- Unknown parameter in source: "gitSubmodulesConfig", ...
- Unknown parameter in source: "reportBuildStatus", ..
- Unknown parameter in source: "sourceIdentifier", ...
- Unknown parameter in artifacts: "overrideArtifactName", ...
- Unknown parameter in artifacts: "artifactIdentifier", ...
- Unknown parameter in cache: "modes", ...
- Unknown parameter in environment: "imagePullCredentialsType", ...

The json have been updated?

Thanks.

**Comment by justnance** [comment]
@cumal - Thanks for reporting this behavior.  The json was not updated recently.   All secondary sources are installed in their own directory. This directory is stored in the built-in environment variable `CODEBUILD_SRC_DIR_sourceIdentifer`.  Are the environment variables for its directory path `CODEBUILD_SRC_DIR_sourceIdentifier`?

Related Link(s):  
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-multi-in-out.html
