### ISSUE TITLE
Error using search-resources Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by ketanbhut** [aws/aws-cli#4212]
I simply trying to follow the document https://docs.aws.amazon.com/cli/latest/reference/resource-groups/search-resources.html to search the resource with query as below:

If I run as below syntax, as per the cli-help-page it fails with 'Expecting property name enclosed in double quotes:

aws resource-groups search-resources --resource-query '{"Type":"TAG_FILTERS_1_0",\"Query\":"{\"ResourceTypeFilters\":[\"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"auto\",\"Values\":[\"no\"]}]}"}'
Error parsing parameter '--resource-query': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {Type:TAG_FILTERS_1_0,"Query":{"ResourceTypeFilters":["AWS::EC2::Instance"],"TagFilters":[{"Key":"auto","Values":["no"]}]}}

Assuming it is complaining about "Type":"TAG_FILTERS_1_0" not being escaped, I try below and it does not take it as a string

aws resource-groups search-resources --resource-query '{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":"{\"ResourceTypeFilters\":[\"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"auto\",\"Values\":[\"no\"]}]}"}'
Parameter validation failed:
Invalid type for parameter ResourceQuery.Query, value: OrderedDict([('ResourceTypeFilters', ['AWS::EC2::Instance']), ('TagFilters', [OrderedDict([('Key', 'auto'), ('Values', ['no'])])])]), type: <class 'collections.OrderedDict'>, valid types: <class 'str'>

**Comment by fh** [comment]
You need to escape the `Query` part of your command to make this work - see https://docs.aws.amazon.com/cli/latest/reference/resource-groups/create-group.html for a full example, the syntax for `search-resources` is the same.

So for your search, you have to do: 

`aws resource-groups search-resources --resource-query '{"Type":"TAG_FILTERS_1_0","Query":"{\"ResourceTypeFilters\":[\"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"auto\",\"Values\":[\"no\"]}]}"}'`

**Comment by ketanbhut** [comment]
Hi,
Thanks for the comments. The problem appears to reproduce on a windows machine. I could see same error from Powershell or Cmd.exe. 

It works as expected from Linux. I have attached a screenshot for your reference for three of those consoles. 
![image](https://user-images.githubusercontent.com/36862200/60262865-db4dcb80-98fc-11e9-9abb-6b3914fe832d.png)

**Comment by ketanbhut** [comment]
I can achieve this by PowerShell Cmdlet from the PowerShell console: 
```

$query = [Amazon.ResourceGroups.Model.ResourceQuery]::new()
$query.Query ="{`"ResourceTypeFilters`":[`"AWS::EC2::Instance`"],`"TagFilters`":[{`"Key`":`"auto`",`"Values`":[`"no`"]}]}"
$query.Type = [Amazon.ResourceGroups.QueryType]::TAG_FILTERS_1_0
Find-RGResource -ResourceQuery $query -MaxResult 50  | Select-Object -ExpandProperty ResourceIdentifiers

ResourceArn                                                     ResourceType
-----------                                                     ------------
arn:aws:ec2:eu-west-1:123456789012:instance/i-0123456b7cb89d12b AWS::EC2::Instance

```

**Comment by GitGaby** [comment]
Hi, ketanbhut,
Windows is weird about accepting JSON, and I didn't find a way to get the AWS CLI to accept the JSON string in either PowerShell on Windows or Command Prompt.  Didn't matter whether I used double quotes, escaping, single quotes, or any combination thereof.  A JSON string will probably be more acceptable to a CLI command running on Windows if it's passed in a file and not as a flat string.  However, Bash running on Windows accepts Florian's suggested command above without editing.  It just works.  If you're running Win10 you can enable Bash by enabling Windows Subsystem for Linux in "Turn Windows features on or off".  After that, just run Bash by typing "bash" into the Start menu.  [Reinstall the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html) after you get WSL/Bash up and running.

```
gabykap@TEST ~
$ aws resource-groups search-resources --resource-query '{"Type":"TAG_FILTERS_1_0","Query":"{\"ResourceTypeFilters\":[\
"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"InstanceType\",\"Values\":[\"t2.micro\"]}]}"}'
{
    "ResourceIdentifiers": [
        {
            "ResourceArn": "arn:aws:ec2:us-west-2:123456789000:instance/i-00EXAMPLEEXAMPLEX",
            "ResourceType": "AWS::EC2::Instance"
        },
        {
            "ResourceArn": "arn:aws:ec2:us-west-2:123456789000:instance/i-0cEXAMPLEEXAMPLEX",
            "ResourceType": "AWS::EC2::Instance"
        }
    ]
}
```
Hope that helps you.  I will add this example to the CLI topic for search-resources.
Gaby Kaplan
Technical writer, Resource Groups

**Comment by kyleknap** [comment]
@ketanbhut can you confirm if @GitGaby suggestion work?

**Comment by ketanbhut** [comment]
Hi, yes
I have been using WSL and awscli will accept the json input as above.

**Comment by winseros** [comment]
Any chance to get this working for `cmd` or `powershell`? I have no WSL on my windows machine.
