### ISSUE TITLE
Decrease EBS volume size

### ISSUE THREAD

**Issue by liorko87** [aws/aws-cli#4216]
Hello,
I'm trying to decrease the size of EBS volume using this command:
`aws ec2 modify-volume --volume-id {vol-id} --size {size}`

When I ran the command I got this error:
`An error occurred (InvalidParameterValue) when calling the ModifyVolume operation: New size cannot be smaller than existing size`

Is the `aws-cli` support this option?

**Comment by justnance** [comment]
@liorko87 - Thank you for reporting this issue.  This behavior is not control by the CLI as the error is returning from the service.  As per our online documentation, [decreasing the size of an EBS volume is not supported. However, you can create a smaller volume and then migrate your data to it](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/modify-volume-requirements.html).
