### ISSUE TITLE
Guardduty: get_available_regions

### ISSUE THREAD

**Issue by gabrielsoltz** [aws/aws-cli#4219]
There is no option to get_available_regions

With boto3: `session.get_available_regions('guardduty')`

**Comment by justnance** [comment]
@gabrielsoltz - Thanks for reporting this issue.   The CLI does not behave the same way as boto3.  For example, to get available regions under the EC2 service, you would use  [the `describe-regions` command](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html) which execute EC2 [DescribeRegions API call](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html).

The [Guardduty API](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_api_ref.html) does not have an API call to describe regions in the same way as EC2.  I would recommend posting in the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=288) or contacting AWS Support to request this feature from Guardduty service team.  Once this information is exposed from the API then it should be automatically picked up and displayed by the CLI.

Just a quick note, [if GuardDuty is not enabled in all supported regions, its ability to detect activity that involves global services is reduced.](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_regions.html)

**Comment by gabrielsoltz** [comment]
Hi, thanks for you answer. 

But using boto3, i can get that information using: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.get_available_regions

```
session = boto3.session.Session()

**Comment by justnance** [comment]
@gabrielsoltz - Thanks for your feedback.  [Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.get_available_regions) is actually loads a botocore session and returns a list from [botocore session store](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L1484
) and not from an API call. 

```
>>> guardduty_regions = session.get_available_regions('guardduty')
2019-06-07 09:39:14,625 botocore.loaders [DEBUG] Loading JSON file: /Users/username/Library/Python/3.7/lib/python/site-packages/botocore/data/endpoints.json
2019-06-07 09:39:14,674 botocore.loaders [DEBUG] Loading JSON file: /Users/username/Library/Python/3.7/lib/python/site-packages/botocore/data/guardduty/2017-11-28/service-2.json
>>> 
```

The CLI works differently as it uses API calls and current the Guardduty API is not exposing the `DescribeRegions` like it does with the EC2 API.  Here's an excerpt from the debug log showing the API call using the EC2 describe-regions command as an example of how Guardduty should work:

```
aws ec2 describe-regions --debug
```
> 2019-06-07 09:41:23,678 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeRegions) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.16.173 Python/3.7.0 Darwin/16.7.0 botocore/1.12.163'}, 'body': {'Action': 'DescribeRegions', 'Version': '2016-11-15'}, 'url': 'https://ec2.us-west-2.amazonaws.com/', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x10e67cba8>, 'has_streaming_input': False, 'auth_type': None}}

Again, the Guardduty service team will have to process this feature first so it can be exposed to the CLI.  If you submit a request on the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=288) and post the link here I will forward it onto the service team. 

Thanks.

**Comment by gabrielsoltz** [comment]
Thanks !

**Comment by justnance** [comment]
@gabrielsoltz - Thanks for the follow up but since feature requests for the service are requested via the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=288), I need a forum link before I can forward it onto the Guardduty service team.

**Comment by gabrielsoltz** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=904089&#904089

**Comment by justnance** [comment]
@gabrielsoltz - Thanks! This has been updated internally.  I will close this issue and follow the progress on the forums.
