### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Alaa-mansour** [aws/aws-cli#4222]
am trying to deploy my react django project to aws and am using webpack in the development phase it's all working well but when i try to deploy it it can't read my static files
 

**here is my webpack file** 
___________________________________________
module.exports = {
  entry: {
    app: "./src/index.js",
    vendors: ["react"]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "./backend/static/dist"),
    publicPath: "http://localhost:8080/backend/static/dist/"
  },
  resolve: {
    extensions: [".js", ".jsx"]
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        exclude: /node_modules/,
        query: {
          presets: ["@babel/react"]
        }
      },

      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"]
      },
      {
        test: /\.scss$/,
        use: [
          "style-loader", // creates style nodes from JS strings
          "css-loader", // translates CSS into CommonJS
          "sass-loader" // compiles Sass to CSS, using Node Sass by default
        ]
      },
      {
        test: /\.(png|svg|jpg|gif|jpe?g)$/,
        use: ["file-loader"]
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "fonts/"
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new BundleTracker({ filename: "./webpack-stats.json" }),
    new webpack.NoEmitOnErrorsPlugin(),
    new HtmlWebpackPlugin({
      title: "Production"
    })
  ]
};
_________________________________________________
**here is my settings.py** 

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'backend/static/'),
    os.path.join(BASE_DIR, 'backend/static', 'dist'),

]

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'dist/',  # must end with slash
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map']
    }
}
_____________________________________________________
here is the error am getting on aws 

GET http://localhost:8080/backend/static/dist/vendors.bundle.js  net::ERR_connection_refused

**Comment by justnance** [comment]
@Alaa-mansour - Thanks for posting this issue.  The error is not returning from the CLI.  As stated in our README, we try to reserve GitHub issues to CLI bugs and feature requests.  I would recommend reaching out to StackOverflow or the AWS Developer forums as there will probably be individuals that can provide further help.  It also appears there are a couple threads already discussing this issue:

https://forums.aws.amazon.com/thread.jspa?threadID=227341
https://forums.aws.amazon.com/tags/err_connection_refused
