### ISSUE TITLE
aws logs describe-log-streams filtering by timestamps not working

### ISSUE THREAD

**Issue by zebehringer** [aws/aws-cli#4227]
It seems that any jmespath expression for the *Timestamp attributes is not honored, although expressions on string attributes still are.

In the below query I would not expect to have the log stream returned since firstEventTimestamp is > 1560140000000

I wonder if the --order-by or --no-descending switches are somehow overriding the timestamp portions of the jmespath expression, or if long JSON literal numbers like these timestamps are not being parsed correctly.
FWIW, running the query on jmespath.org gives me the results I expect

`aws logs describe-log-streams --log-group-name /aws/my/log/group --order-by LastEventTime --no-descending --query "logStreams[?logStreamName == 'foo' && firstEventTimestamp <= '1560140000000']"`

```
[
    {
        "firstEventTimestamp": 1560178834382, 
        "lastEventTimestamp": 1560179496682, 
        "creationTime": 1560178832311, 
        "uploadSequenceToken": "49596366246143800516909869772940609709417414981251713954", 
        "logStreamName": "foo", 
        "lastIngestionTime": 1560180467350, 
        "arn": "arn:aws:logs:us-east-1:1234567890:log-group:/aws/my/log/group:foo", 
        "storedBytes": 0
    }
]
```

**Comment by joguSD** [comment]
The CLI does some coercion on the format of timestamps and I wonder if that's getting in the way somehow. Would it be possible to get debug logs for the command you're running by adding `--debug`?

**Comment by zebehringer** [comment]
[debug.log](https://github.com/aws/aws-cli/files/3683072/debug.log)

the attached log was run against a real log stream, not the fake one in the original description

**Comment by zebehringer** [comment]
I've since discovered that jmespath requires number literals in predicates be enclosed in back ticks. Using those instead of single quotes (the whole query now needs to be in single quotes instead of double quotes, though) seems to fix the issue.

here's the corrected query:
```aws logs describe-log-streams --log-group-name /aws/my/log/group --order-by LastEventTime --no-descending --query 'logStreams[?logStreamName == `foo` && firstEventTimestamp <= `1560140000000`]'```
