### ISSUE TITLE
Add support to generate cli skeleton in yaml format.

### ISSUE THREAD

**Issue by gautamkmr** [aws/aws-cli#4234]
Current option generates it in json format, however some of the standard tools like kubernetes accept the yaml format. It would be easier to convert the json to yaml from AWS cli itself.

**Comment by justnance** [comment]
@gautamkmr - Thanks for reporting this feature.  It sounds reasonable.  I am marking it as a feature request pending further review and community feedback.

**Comment by kyleknap** [comment]
Support for this was recently added via this PR: https://github.com/aws/aws-cli/pull/4700. This should be available in `2.0.0dev2` of the AWS CLI v2 developer preview. Closing issue.
