### ISSUE TITLE
aws sync truly different files (not based on size or mtime)

### ISSUE THREAD

**Issue by mmahut** [aws/aws-cli#4235]
```aws sync``` syncs right now based on the mtime or the size. Would it be possible to make it sync only if the file is truly different? This would probably required to compute hashes of the files before evaluation what is up for synchronization.

**Comment by mmahut** [comment]
Basically what I am looking for is MD5 based upload, as mentioned here https://github.com/bloomreach/s4cmd#additional-technical-notes

**Comment by justnance** [comment]
@mmahut - Thanks for your post.  I am labeling this type of feature and the MD5 features for S3 Sync under #599.  For now, I'm closing this issue as a duplicate.
