### ISSUE TITLE
aws s3 ls very high cpu usage

### ISSUE THREAD

**Issue by reinhrst** [aws/aws-cli#4239]
The `ls` command uses an extreme amount of CPU time, which I cannot understand why it would be necessary. See the run below:

```
> time aws s3 ls --recursive s3://xxxxx/xxxxx/ | wc -l
    7500
aws s3 ls --recursive s3://xxxxxxxx/xxxxx/  2.02s user 0.18s system 20% cpu 10.885 total
wc -l  0.01s user 0.03s system 0% cpu 10.884 total
```

As you can see, it's a simple recursive `ls` of 7500 items. As I understand the AWS api, this will take 8 calls, and then the result must be added together and printed.

This takes 2 seconds CPU time (and 10s wall-clock which is due to my crappy internet connection). Multiple runs always show between 1.5 and 2 seconds CPU time for this call.

This on MacOS, with the latest stable aws packages (awscli-1.16.178, botocore==1.12.168)

**Comment by kdaily** [comment]
Hi @reinhrst,

I tested this recently on an EC2 to minimize network latency issues. Here's what I see for a recursive listing of ~2500 files:

```
(aws-cli-1.18.79) ubuntu@ip-172-31-28-134:~$ time aws s3 ls --recursive s3://mybucket/ 1>/dev/null

real	0m1.178s
user	0m0.905s
sys	0m0.098s
```

On my Mac, it was substantially slower, but also on wireless:

```
$ time aws s3 ls --recursive s3://mybucket/ 1>/dev/null
aws s3 ls --recursive s3://mybucket/ > /dev/null  0.80s user 0.32s system 54% cpu 2.067 total
```

Does this still occur for you?

**Comment by reinhrst** [comment]
So don't you agree that 900 ms time to list 2500 items is a lot? I do understand why there may be network latency (and I'm not complaining about the total run time, just the cpu (=user+sys) time; since this is what counts if you were to do many of these requests in parallel), but as I would suspect, all the real (cpu) work is: construct a url, sign the url, parse the results (and do that 3 times, because it can only do 1000 items at a time). (To compare, the CPU time to do an `ls` of 2500 files is 20ms, and it seems that all that time is used to sort; an `ls -f` takes < 5ms); parsing a json array with 2500 items (in python) takes 1.1ms).

The problem is, I cannot imagine why any of the (construct url, sign url, parse results) should be more than a couple of ms max. So my hunch is that either the system is doing something else that is useful, or it's doing something else that is not useful -- but I have to admit, this is just a hunch.
