### ISSUE TITLE
GovCloud Route53 Support

### ISSUE THREAD

**Issue by spstratis** [aws/aws-cli#4241]
Just looking to see if the GovCloud Route53 api Url is supported in the aws-cli yet. When I attempt to create a private zone, I get the following error.

```
Could not connect to the endpoint URL: "https://route53.us-gov-west-1.amazonaws.com/2013-04-01/hostedzone"
```

My aws cli version is: 
aws-cli/1.16.79 Python/2.7.10 Darwin/18.6.0 botocore/1.12.69

Not sure if this is an issue due to Route53 support in GovCloud being so new, or an issue with me using my IAM role creds. It seems the Route53 calls are the only ones that are giving me an issue right now. 

Thanks!

**Comment by bflad** [comment]
After a little investigation, the seemingly undocumented Route 53 endpoint in AWS GovCloud (US) appears to be: https://route53.us-gov.amazonaws.com

```console
$ aws --endpoint https://route53.us-gov.amazonaws.com route53 list-hosted-zones
{
    "HostedZones": [
        {
            "Id": "/hostedzone/Z11RGLYS7OK8BK",
            "Name": "example.com.",
            "CallerReference": "D377CCA1-A554-1E80-9221-9BB1D357FA17",
            "Config": {
                "PrivateZone": true
            },
            "ResourceRecordSetCount": 2
        }
    ]
}
```

This endpoint information is also not available in the AWS Go SDK as of this writing, so my guess is that the Route 53 service team has not published this endpoint information yet.

**Comment by justnance** [comment]
@spstratis - Thanks for asking about GovCloud Route53 support in the CLI.  If append the `--debug` option to the command you will see from where the CLI loads the endpoints.  It looks something like:

```
MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/name/Library/Python/3.7/lib/python/site-packages/botocore/data/endpoints.json
```

The endpoints are loaded from botocore and according to the latest version of the CLI, [Route53](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L2249) is not supporting `us-gov-west-1` yet.  As a reference, you can also compare this to the endpoints for [ec2](https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L3863).

I've labeled this issue as a feature requesting pending further review.

**Comment by justnance** [comment]
@spstratis - After additional review, this has been relabeled as a bug.  We are working on getting this fixed.

**Comment by akdavenp** [comment]
@justnance Is there an update to this?  If it is still in progress, is this something that AWS support can add for us in the meantime?

We are interested in the private zone associations functionality since public zones are not available in GovCloud.

`HTTPSConnectionPool(host='route53.us-gov-east-1.amazonaws.com', port=443): Max retries exceeded with url: /2013-04-01/hostedzone/REDACTED/associatevpc (Caused by NewConnectionError('<botocore.awsrequest.AWSHTTPSConnection object at 0x7f997add9048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
`

**Comment by justnance** [comment]
@akdavenp - Thanks for asking about an update.  Work is still in progress as we are collaborating with the Route 53 service team to have endpoint, us-gov-west-1, exposed to the CLI.  Thanks for your patience.

**Comment by tedmiston** [comment]
Hi @justnance - I'm experiencing this bug in GovCloud as well.  Is it possible to get an ETA when the CLI will be patched?

**Comment by justnance** [comment]
@tedmiston - Thanks for the update.  At this time our service team is working on this issue and there is no eta yet.  This GitHub issues will be updated as soon as there is more information. 

Thanks for your patience.

**Comment by kyleknap** [comment]
I just tried the latest version of the CLI and it looks like it is correctly resolving to: `https://route53.us-gov.amazonaws.com/` when a gov cloud region is specified. Please let us know if you are still running into issues with it using the latest version of the CLI.

**Comment by weisjohn** [comment]
https://github.com/boto/botocore/blob/a59b85c5286aba787e90cab71ac1dc4d58a4d707/botocore/data/endpoints.json#L2972 is a more direct link to the route53 supports

**Comment by mgs4332** [comment]
As it turns out this is an AWS limitation. Having just gotten off with Amazon Support; they state Alias records are not supported in Gov Cloud at this time. 

We are currently looking into if we can augment the code to perform the same function with a CNAME record instead of an Alias record. I'm awaiting documentation on this from AWS to provide.

**Comment by harshaghub** [comment]
@kyleknap I still have this issue of route53 even with latest version of aws-cli version 2:

botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://route53.us-gov-west-1.amazonaws.com/2013-04-01/hostedzone"
