### ISSUE TITLE
awscli-bundle install on Python 2.6 fails at PyYAML (3.x dependency vs. 5.x bundled)

### ISSUE THREAD

**Issue by Trinition** [aws/aws-cli#4242]
As of awscli-bundle version 1.16.178 it is no longer installable with Python 2.6 (e.g. CentOS6 EC2 instance).

The failure is:
`Could not find a version that satisfies the requirement PyYAML<=3.13,>=3.10 (from awscli==1.16.178) (from versions: 5.1)`

The problem appears to be that the bundle includes the PyYAML 5.1 files, but the dependency is set to use PyYAML 3.10-3.13.  I can independently `pip install PyYAML==3.13` on such an instance just fine, but the `awscli-bundle/install` script seems to take special steps to leverage only the bundled items when installing itself, and can't find a 3.x PyYAML in the 5.1 artifact.

**Comment by Trinition** [comment]
By manually downloading the correct artifact for [PyYAML 3.13](https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz) and placing it alongside the incorrect version in the bundle's `packages` folder, it works.  This further confirms that the problem is the incorrect artifact version being included in the bundle.

**Comment by Trinition** [comment]
I believe the problem was indirectly introduced by [this PR](https://github.com/aws/aws-cli/pull/4231) submitted by @dstufft .  It properly makes the install script look for the correct version of PyYAML, but it can't be found because of the incorrect PyYAML artifact being bundled.

**Comment by JordonPhillips** [comment]
Confirmed that this is a bug, we'll get a fix out

**Comment by joguSD** [comment]
Merged a fix for this in https://github.com/aws/aws-cli/commit/aed297b19cf091c75445664787a177af413c5ad2

This should go out in the next release (today, 6/17/2019).

**Comment by joguSD** [comment]
This is fixed as of 1.16.180.
