### ISSUE TITLE
Documentation about initialization of Cloud-HSM is misleading

### ISSUE THREAD

**Issue by FKatenbrink** [aws/aws-cli#4246]
In my opinion, line 145 and 146 on [https://github.com/awsdocs/aws-cloudhsm-user-guide/blame/b571dce4bf1ad182a8bb9414206e94b1c0c6dbbd/doc_source/initialize-cluster.md](https://github.com/awsdocs/aws-cloudhsm-user-guide/blame/b571dce4bf1ad182a8bb9414206e94b1c0c6dbbd/doc_source/initialize-cluster.md#L145) lead to the assumption that we have to use the file path to the certificates.

However, aws-cli requires `--signed-cert` and `--trust-anchor` to be the content of the certificates, not the file path.

How about changing the documentation to the following on lines 144-146?

```
  $ aws cloudhsmv2 initialize-cluster --cluster-id <cluster ID> \
                                      --signed-cert "<content of file://<cluster ID>_CustomerHsmCertificate.crt>" \
                                      --trust-anchor "<content of file://customerCA.crt>"
```

**Comment by justnance** [comment]
@FKatenbrink - Thanks for reporting this issue with our documentation.  I have escalated this internally to our Cloud-HSM documentation writers.
