### ISSUE TITLE
Request: Nest buckets one DNS level deeper than blah.s3.amazonaws.com

### ISSUE THREAD

**Issue by mcandre** [aws/aws-cli#4252]
Not sure where else to post this, but I think as long as we are using DNS to differentiate storage buckets, then we should begin nesting each bucket under the bucket owner's organization name, like github-release-assets-12345.github.s3.amazonaws.com, instead of github-release-assets-12345.s3.amazon.com.

The difference is subtle: The former is more clearly managed by the controller of the github.s3.amazonaws.com domain. Versus github-release-assets-12345.s3.amazon.com, which could be a true GitHub, Inc. bucket, but could also be a fake bucket created by hackers attempting to fool people into downloading malicious artifacts. The current DNS scheme is cumbersome to write good access control lists for, for this very reason.

I realize this represents a breaking change to the DNS scheme currently used by all S3 customers; We would have to phase out the old bucket-to-DNS mapping over time, perhaps offering both of these DNS aliases until customers have time to switch over.

**Comment by justnance** [comment]
@mcandre - Thank you for submitting your request.  This is repo is for reporting bugs and feature requests for the CLI.  I recommend asking about this on the [s3 service team forums](https://forums.aws.amazon.com/forum.jspa?forumID=24) or reaching out to Premium Support.  It appears there are some [related discussion](https://forums.aws.amazon.com/search.jspa?mbtc=7872a2c03c71b3e2c8eb316d283342ba0d0535bf70e55d268936a2e471dffe6c&objID=f24&q=nested+dns&x=0&y=0) already posted on the forums.
