### ISSUE TITLE
ImportError: No module named connection

### ISSUE THREAD

**Issue by aShobhitSingh** [aws/aws-cli#4259]
I have uninstalled my old awscli and installed latest version via pip. After installing latest awscli
I am facing below error

> Traceback (most recent call last):
>   File "/usr/local/bin/aws", line 19, in <module>
>     import awscli.clidriver
>   File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 17, in <module>
>     import botocore.session
>   File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 30, in <module>
>     import botocore.credentials
>   File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 42, in <module>
>     from botocore.utils import InstanceMetadataFetcher, parse_key_val_file
>   File "/usr/local/lib/python2.7/dist-packages/botocore/utils.py", line 30, in <module>
>     import botocore.awsrequest
>   File "/usr/local/lib/python2.7/dist-packages/botocore/awsrequest.py", line 21, in <module>
>     from urllib3.connection import VerifiedHTTPSConnection
> ImportError: No module named connection

**OS version**: Ubuntu 14.04
**Python**: 2.7
pip freeze | grep urllib3
urllib3==1.23

From last year there is a similar thread but that doesn't help me as my urllib3 version is already the correct one. Really appreciate if someone can look into this

**Comment by pf22099** [comment]
Same here. This is a similar thread but I already got the correct urllib3 version: https://github.com/aws/aws-cli/issues/3606

**Comment by aShobhitSingh** [comment]
Hey Guys, anything on this. just to add installed pip via
python get-pip.py

**Comment by justnance** [comment]
@aShobhitSingh and @pf22099 - Thanks for reporting this issue, providing the traceback, and mentioning #3606.  With the details provided so far it appears this [maybe an issue with the `pip install` or how it installed `urllib3`](Related links:  https://stackoverflow.com/questions/27440060/how-to-fix-importerror-no-module-named-packages-urllib3).  The recommendation here is to install the CLI in a [virtual environment to isolate the tool and its dependencies](https://docs.aws.amazon.com/cli/latest/userguide/install-virtualenv.html).  

Let us know if this helps.
