### ISSUE TITLE
aws acm request-certificate --validation-method DNS  

### ISSUE THREAD

**Issue by Math1er** [aws/aws-cli#4261]
ISSUE TYPE
- Bug Report

COMPONENT NAME
- aws acm

AWS-CLI VERSION
aws-cli/1.16.102 Python/2.7.14 Linux/4.14.104-95.84.amzn2.x86_64 botocore/1.12.92

CONFIGURATION
Nothing specific to report on this.

OS / ENVIRONMENT
AMZ Linux 2

SUMMARY
When executing the command  `aws acm request-certificate --domain-name my-domain.com --validation-method DNS --region us-east-1`  I have an error message describe in ACTUAL RESULTS. the command work find without the `--validation-method DNS`

STEPS TO REPRODUCE
$ `aws acm request-certificate --domain-name my-domain.com --validation-method DNS --region us-east-1`

EXPECTED RESULTS
Docs return consistent to the output of all other modules, with no user-presented errors.

ACTUAL RESULTS
`Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 196, in main
    parsed_args, remaining = parser.parse_known_args(args)
  File "/usr/lib/python2.7/site-packages/awscli/argparser.py", line 91, in parse_known_args
    parsed, remaining = super(CLIArgParser, self).parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1774, in _parse_known_args
    option_tuple = self._parse_optional(arg_string)
  File "/usr/lib64/python2.7/argparse.py", line 2082, in _parse_optional
    option_tuples = self._get_option_tuples(arg_string)
  File "/usr/lib64/python2.7/argparse.py", line 2125, in _get_option_tuples
    if option_string.startswith(option_prefix):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 19: ordinal not in range(128)`

Can you help to resolve this issue?

**Comment by justnance** [comment]
@Math1er - Thank you for reporting this issue.  I unable to reproduce same results on an EC2 Instance running Amazon Linux 2 which is configured to use ASCII encoding and UTF-8 Locale by default.   I also tested with an older version of the CLI and the latest along with the following default configuration: 

```
[ec2-user@ip-172-31-41-244 ~]$ aws acm request-certificate --domain-name my-domain.com --validation-method DNS --region us-east-1
{
    "CertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/f76edd51-48b2-49d9-8889-f9fe7082c96a"
}
[ec2-user@ip-172-31-41-244 ~]$ aws --version
aws-cli/1.15.80 Python/2.7.14 Linux/4.14.72-73.55.amzn2.x86_64 botocore/1.10.79
```

```
[ec2-user@ip-172-31-41-244 ~]$ aws acm request-certificate --domain-name my-domain.com --validation-method DNS --region us-east-1                                                                                  
{
    "CertificateArn": "arn:aws:acm:us-east-1:839730217488:certificate/f76edd51-48b2-49d9-8889-f9fe7082c96a"
}
[ec2-user@ip-172-31-41-244 ~]$ aws --version
aws-cli/1.16.102 Python/2.7.14 Linux/4.14.72-73.55.amzn2.x86_64 botocore/1.12.92
```

```
[ec2-user@ip-172-31-41-244 ~]$ python
Python 2.7.14 (default, Jul 26 2018, 19:59:38) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'ascii'
```

```
[ec2-user@ip-172-31-41-244 ~]$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

```

It appears the CLI is working as expected.  The error in the traceback "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 19: ordinal not in range(128)" which is returning from `file "/usr/lib64/python2.7/argparse.py"` appears to point to an issue with the input.  This error is an indication that the character in position 19 of the CLI arguments has 0xc2 which translates to an [invisible control character](https://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=0x) that argparse can not handle.   

Does the sys module says Instance set to ASCII and the Locale set to UTF-8, as above?

Can you retype the command without using copy and paste to eliminate any transference of unknown characters? 

Let use know if this resolves the issue.

**Comment by Math1er** [comment]
@justnance  I just test without using copy and paste and it's working fine.
Thanks for your help
