### ISSUE TITLE
CLI does NOT honor china regions defined in .aws/config

### ISSUE THREAD

**Issue by zxkane** [aws/aws-cli#4264]
I have to explicitly specify China region in command.

See below example output,

```shell
➜  ~ cat ~/.aws/config
[default]
region = ap-southeast-1
[kane-bjs]
region = cn-northwest-1
[kane-global]
region = ap-east-1

➜  ~ aws iam list-users --profile kane-bjs

An error occurred (InvalidClientTokenId) when calling the ListUsers operation: The security token included in the request is invalid.
➜  ~ aws iam list-users --profile kane-bjs --region cn-northwest-1
{
    "Users": [
        {
            "Path": "/",
            "UserName": "kane",
            "UserId": "AIDAQP3VLCVWV6xxxxx",
            "Arn": "arn:aws-cn:iam::xxxx:user/kane",
            "CreateDate": "2019-06-21T05:51:08Z",
            "PasswordLastUsed": "2019-06-24T02:16:29Z"
        }
    ]
}
~ aws --version
aws-cli/1.16.180 Python/3.7.3 Darwin/18.6.0 botocore/1.12.170
```

**Comment by justnance** [comment]
@zxkane - Thank you for posting this issue.  I was able to reproduce the problem and the output returned the same error message.   I also added the `--debug` option to the command to understand the problem better:

```
aws iam list-users --profile kane-bjs --debug
```

This error will return when there a [named profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) in the `~/.aws/config` does not have credentials for the same named profile in the `~/.aws/credentials` file. 

Here's an example to use in your profiles using example keys:

```shell
➜  ~ cat ~/.aws/config
[default]
region = ap-southeast-1

[kane-bjs]
region = cn-northwest-1

[kane-global]
region = ap-east-1

```

```shell
➜  ~/.aws/credentials

[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[kane-bjs]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

[kane-global]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

```

I suggest updating the `~/.aws/credentials` file.  Let us know if this works.

**Comment by zxkane** [comment]
@justnance I don't think the error is caused by some credential missing for named profile. It still does not work though only leaving the named profile 'kane-bjs'.

```bash
➜  .aws cat config
[kane-bjs]
region = cn-north-1

➜  .aws cat credentials
[kane-bjs]
aws_access_key_id = AKIAQP3VLCVW3Lxxx
aws_secret_access_key = EVwDR5Pk2V/wRPmfnpKhoxxxxxxx

➜  .aws aws iam list-users --profile kane-bjs

An error occurred (InvalidClientTokenId) when calling the ListUsers operation: The security token included in the request is invalid.
```
After enabling the debug option, I found the aws-cli is using aws-global API server not the particular  China one. Not sure why aws-cli can not load the china region defined via named profile.

**Comment by justnance** [comment]
@zxkane - Thank you for your feedback.  If an option is specified as an environment variables, it override any value loaded from a profile in the configuration file.  If an option is specified by using a parameter, it overrides any value from either the corresponding environment variable or a profile in the configuration file.  The configuration values have the following precedence:

- Command line options
- Environment variables
- Configuration file

What value is stored in the Environment Variables?  I think it is overriding the Configuration File.  I was able to set the environment variables to the default and reproduce this behavior.  This explains why it works as expected with `--region`.  

Related links:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by zxkane** [comment]
Nancy, thanks for your feedback and documentations. I turned it out, the profile in config was incorrect. It should be,

```
[profile kane-bjs]
region = cn-north-1
```

**Comment by justnance** [comment]
@zxkane - Thanks for the feedback and updating the issue with the fix.
