### ISSUE TITLE
[Feature request] support route53 for China

### ISSUE THREAD

**Issue by hiscal2015** [aws/aws-cli#4266]
Please support automatically detect China region and endpoint for route53, actually terraform part is ready:
https://github.com/terraform-providers/terraform-provider-aws/commit/cd01ed513f8874b399300f546e3b1935ec113204#diff-4376ae0574029ea531860ba8678688a4

Thanks.

**Comment by justnance** [comment]
@hiscal2015 - Thanks for asking about this feature.  Currently the [China region is not supported in the Route53 service](https://www.amazonaws n/en/about-aws/regional-product-services/).  I recommended posting this feature request on the [service team forums](https://forums.aws.amazon.com/forum.jspa?forumID=87).
