### ISSUE TITLE
Configuring CloudWatch Agent using wizard

### ISSUE THREAD

**Issue by jasonbellack** [aws/aws-cli#4267]
Hello,

I am trying to configure the CloudWatch Agent on an Amazon Linux 2 EC2 instance. I have followed the procedure as described here:
 https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html

Here is the procedure I follow:

1) Provision EC2 Instance
2) Attach Role to Instance that will allow CloudWatch to create log groups and pull logs to the new log group.
3) Install CloudWatch Agent on EC2 instance
	wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
	 
	rpm -U ./amazon-cloudwatch-agent.rpm
4) Create the CloudWatch Agent configuration file: 
	/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard
5) While creating the CloudWatch Agent configuration file, choose which logs to send and the log trail name. AWS will create the log trail if using a new one.
6) Copy the filepath of the configuration file for the next step
7) Create the collectd directory and types.db file so the cloudwatch agent can be started properly
	mkdir /usr/share/collectd; touch /usr/share/collectd/types.db
8) Start the CloudWatchAgent:
	/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:configuration-file-path -s
Check AWS console and see if CloudWatch Agent is sending logs to the log group you created while setting up CloudWatch agent on the EC2 instance.

I am getting the following output:

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c /opt/aws/amazon-cloudwatch-agent/bin/config.json -s
/opt/aws/amazon-cloudwatch-agent/bin/config-downloader --output-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --download-source /opt/aws/amazon-cloudwatch-agent/bin/config.json --mode ec2 --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default
downloadLocation /opt/aws/amazon-cloudwatch-agent/bin/config.json is malformated.

Fail to fetch the config!

I have checked the format of the config.json file and do not see any issues. Can anyone please help?

**Comment by jasonbellack** [comment]
The config.json file is shown below
{
        "agent": {
                "metrics_collection_interval": 60,
                "run_as_user": "root"
        },
        "logs": {
                "logs_collected": {
                        "files": {
                                "collect_list": [
                                        {
                                                "file_path": "/var/log/messages",
                                                "log_group_name": "<LogGroup>",
                                                "log_stream_name": "{instance_id}"
                                        }
                                ]
                        }
                }
        },
        "metrics": {
                "append_dimensions": {
                        "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
                        "ImageId": "${aws:ImageId}",
                        "InstanceId": "${aws:InstanceId}",
                        "InstanceType": "${aws:InstanceType}"
                },
                "metrics_collected": {
                        "mem": {
                                "measurement": [
                                        "mem_used_percent"
                                ],
                                "metrics_collection_interval": 60
                        },
                        "swap": {
                                "measurement": [
                                        "swap_used_percent"
                                ],
                                "metrics_collection_interval": 60
                        }
                }
        }
}

**Comment by jasonbellack** [comment]
was missing "file:" before filepath when trying to start the CloudWatch Agent

**Comment by aknosis** [comment]
For posterity, the solution (using above example):

`/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s`

**Comment by lijoleeyuson** [comment]
> For posterity, the solution (using above example):
> 
> `/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s`

woked

**Comment by diamondhanddevOps** [comment]
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s

Worked
