### ISSUE TITLE
sync and cp does not work as expected

### ISSUE THREAD

**Issue by S0uLHun43r** [aws/aws-cli#4268]
The same problem here, awscli==1.16.186
`aws s3 cp` and `aws s3 sync` happen same .

I have 1217 files.but sync and cp all give 1000 files.

but when i use s3cmd,it works . @JordonPhillips please open this issue
![image](https://user-images.githubusercontent.com/17557425/60159083-fb11c080-9824-11e9-836e-c8d7aaf95ec2.png)

**Comment by justnance** [comment]
@S0uLHun43r - Thanks for reporting this issue.  It appears this is related to issue #3087.  I have been unable to reproduce the same problem after testing with both the `s3 cp` and `s3 sync` command, the latest version of the CLI, and with a bucket with 1200 items of various file types.  Please provide the command with the operations and example parameters I can use to retest.  Replying with the output of the `--debug` option would also be helpful.
