### ISSUE TITLE
[aws s3api list-object-versions] --max-items should be --max-keys

### ISSUE THREAD

**Issue by IanSavchenko** [aws/aws-cli#4269]
In the CLI and the [docs](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-object-versions.html) it says to use `--max-items` param, but it is ignored. At the same time `--max-keys` has to be used according to [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETVersion.html) and seems to be working. 

I wanted to submit a PR, but couldn't find either docs nor code for the change 😕

**Comment by justnance** [comment]
@IanSavchenko - Thanks for your post.  I worked with the commands to understand the problem better.  I used the `--max-items` and it worked as expected and was not ignored:

```
aws s3api list-object-versions --bucket mybucket --max-items 1
```
I also tested `--max-keys` and it worked as expected too.  Please reply with an example of the command, operation, and parameters when using `--max-items` so I can test how it is being ignored.  If you can reproduce the problem with the `--debug` that would be helpful.

**Comment by IanSavchenko** [comment]
Hi, @justnance. Thank you for your answer. The problem does not seem to happen anymore and now I can't understand what it was. I will close the issue.
