### ISSUE TITLE
enaSupport attribute not working

### ISSUE THREAD

**Issue by chanduusc** [aws/aws-cli#4273]
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore==1.12.178->awscli) (1.12.0)
testuser@ubuntu-amd64:~$ aws ec2 describe-instance-attribute --instance-id i-xxxxxxx --attribute enaSupport

An error occurred (InvalidParameterValue) when calling the DescribeInstanceAttribute operation: Value (enaSupport) for parameter attribute is invalid. Unknown attribute.
testuser@ubuntu-amd64:~$

**Comment by justnance** [comment]
@chanduusc - Thank you for reporting this issue.  According to the [CLI reference doc](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-attribute.html), the `enaSupport` attribute is not supported at this time.
