### ISSUE TITLE
aws cli returns wrong data when using text output

### ISSUE THREAD

**Issue by pmarques** [aws/aws-cli#4275]
# Summary

When I use aws cli get the latest Serverless Application version I get 2 versions instead of 1

# Details

## Version

```
$ aws --version
aws-cli/1.16.188 Python/3.7.2 Darwin/18.6.0 botocore/1.12.178
```

## How to reproduce

When I run (the default output is set to _**json**_):
```
$ aws serverlessrepo list-application-versions \
--application-id "arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app" \
--query 'Versions[-1]'
```

I get:
```
{
    "ApplicationId": "arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app",
    "CreationTime": "2019-06-26T16:37:45.241Z",
    "SemanticVersion": "0.0.2-rc10"
}
```

But if I run the same command with _**--output text**_
```
$ aws serverlessrepo list-application-versions \
--application-id "arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app" \
--query 'Versions[-1]' \
--output text
```

I get 2 lines instead:
```
arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app      2019-06-26T16:36:58.759Z        0.0.2-rc9
arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app      2019-06-26T16:37:45.241Z        0.0.2-rc10
```

This is working fine when the output is _**table**_.

# Expected

I would expect only one line like:

```
arn:aws:serverlessrepo:eu-west-2:<AWS::AccountId>:applications/my-app      2019-06-26T16:37:45.241Z        0.0.2-rc10
```

# Extra info

i just tested with different pagination sizes, for instance _**--page-size 100**_ and get only one line. Seems like that with text output the query is being applied per page instead of on the final result.

**Comment by bisdavid** [comment]
Indeed, you found one of the challenges of combining the **--query** parameter with output that is so long it is paginated.  This is documented here:
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter
When you use **--output text**, the output is paginated first and then the filter is run against each page of the output, resulting in (possibly) more rows than you expect. You've stumbled on the workaround, and that's to get all the output into a single set to filter.  To do that when there is an unknown number of results, you can use the **--no-paginate** option.

I hope this helps!

**Comment by pmarques** [comment]
I end up implementing this with **jq**.

I knew **query** was applied on client side and from what I read _--no-paginate_ just stops the CLI to do pagination since the API is paginated anyway and the CLI can't change that. So long story short cant I assume I get the right results with _--no-paginate_?

**Comment by bisdavid** [comment]
You should be able to get the correct and expected results with _--no-paginate_.  If you don't, please let us know.

**Comment by pmarques** [comment]
Well it works for a few dozens of versions at least 👍, although I'm still confused about the meaning of that option and why this edge case exists.
