### ISSUE TITLE
test_package_arn for built in tests

### ISSUE THREAD

**Issue by praneethkumar16** [aws/aws-cli#4282]
How to get test_package_arn for built in test like my test type is BUILTIN_FUZZ Or EXPLORER. 

I'm getting this error in console Unknown options: BUILTIN_FUZZ}’

**Comment by justnance** [comment]
@praneethkumar16 - Thanks for reporting this error.  Please provide the CLI command and any steps I can use to reproduce the problem.  The output from the `--debug` option would also be helpful. 

Thanks.
