### ISSUE TITLE
Add metadata-directive MERGE

### ISSUE THREAD

**Issue by frlinw** [aws/aws-cli#4283]
REPLACE: existing metadata are removed
`aws s3 cp s3://bucket s3://bucket--recursive --exclude "*" --include "*.woff2" --metadata-directive REPLACE --content-type font/woff2`
COPY: error
`aws s3 cp s3://bucket s3://bucket--recursive --exclude "*" --include "*.woff2" --metadata-directive COPY --content-type font/woff2`

Currently, there is no way to merge existing metadata with metadata in the command

**Comment by justnance** [comment]
@frlinw - Thanks for posting this feature request.  The  `COPY | REPLACE` are exposed to the CLI from the [S3 api from the PUT Object operation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html).  To have `MERGE` value added to this operation, I suggest requesting a feature on the [S3 Service Team on their forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).  If you can post the forum link here, I can escalate the feature request internally.

**Comment by frlinw** [comment]
@justnance https://forums.aws.amazon.com/thread.jspa?threadID=306154

**Comment by justnance** [comment]
Thanks @frlinw for the forum link.  I have escalated this request to our s3 service team.  Because this repo is for CLI feature request and bugs so we will continue to track this request on the forums.
