### ISSUE TITLE
cannot use environment vars

### ISSUE THREAD

**Issue by sergey-safarov** [aws/aws-cli#4287]
I preparing automation script and want use environment vars. Looks as `aws configure` ignores vars.
```
export AWS_ACCESS_KEY_ID=XXXXXXX
export AWS_SECRET_ACCESS_KEY=YYYYYYYYYY
export AWS_DEFAULT_REGION=us-west-2
export AWS_DEFAULT_OUTPUT=json

aws configure
```
I expect aws configure will get all data from environment vars but that is not.
```
AWS Access Key ID [None]: 
AWS Secret Access Key [None]: 
Default region name [None]: 
Default output format [None]: 
```

**Comment by bisdavid** [comment]
Environment variables are an ALTERNATIVE to those in the config file (as created by the aws configure command). 

CLI commands have a variety of places that they can get their config settings and credentials from. They are checked in a specific order and the command stops looking as soon as it finds a usable value.  The order for the CLI is:
1. Specified as an option on the command line.
2. Specified as an environment variable.
3. Found in a profile in the ~/.aws/config & ~/.aws/credentials files

Doing it this way enables you to use the settings in a profile to get most of your values, but you can (for example) override one or more individual settings with an environment variable, typically for the duration of that session.  You can override for an individual command with a command line option.

I hope that helps!

Dave
