### ISSUE TITLE
bucket-exists does not exist

### ISSUE THREAD

**Issue by henrytk** [aws/aws-cli#4294]
The [documentation for bucket-exists](https://docs.aws.amazon.com/cli/latest/reference/s3api/wait/bucket-exists.html) s3api call has the title "bucket-exists - AWS CLI 1.16.193 Command Reference", implying it is available with version 1.16.193.

When I run it it prints usage information because the subcommand does not exist.

```
$ aws --version
aws-cli/1.16.193 Python/2.7.10 Darwin/18.6.0 botocore/1.12.183

$ aws s3api bucket-exists --bucket bucket_name
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:
...

$ aws s3api help | grep bucket-exists
(prints nothing)
```

**Comment by justnance** [comment]
@henrytk - Thanks for reporting this behavior.  The command you are trying to use is actually:

```
aws s3api wait bucket-exists --bucket bucket_name
```

I tested this command with a bucket that exists and one that I had correct permission.  I also tested it with a bucket that did not exist and one that I did not have permissions which returned the following:

```

Waiter BucketExists failed: Max attempts exceeded
```

It appears to be working as expected.  Please let us know if there are more questions or concerns.

**Comment by henrytk** [comment]
Thanks @justnance. Documented examples would be sufficient. Didn't even know there was a wait subcommand!

**Comment by justnance** [comment]
@henrytk - Thanks for the feedback.
