### ISSUE TITLE
aws cloudformation deploy relies on order of params

### ISSUE THREAD

**Issue by stamhankar999** [aws/aws-cli#4302]
`aws cloudformation deploy --stack-name 'mystack' --template-file ./ec2.yaml` fails in argument parsing:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument subcommand: Invalid choice, valid choices are:

push                                     | register
deregister                               | install
uninstall
```

`aws cloudformation deploy --template-file ./ec2.yaml --stack-name 'mystack'` works properly.

My cli version:
```
$ aws --version
aws-cli/1.16.194 Python/3.7.3 Darwin/18.6.0 botocore/1.12.184
```

**Comment by justnance** [comment]
@stamhankar999 - Thank you for reporting this behavior.  I ran the commands and the output worked as expected.  If I add an unknown character such as a colon `:` then the same error returns.  Here's the repro:

```
$ aws cloudformation deploy --stack-name 'mystack' --template-file testcfn.yaml

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - mystack
$ aws cloudformation deploy --template-file testcfn.yaml --stack-name 'mystack'

Waiting for changeset to be created..

No changes to deploy. Stack mystack is up to date
$ aws cloudformation deploy --template-file testcfn.yaml --stack-name 'mystack' :
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument subcommand: Invalid choice, valid choices are:

push                                     | register
deregister                               | install
uninstall
$
```

Please check to see if you are copying and pasting the command which maybe including a extra or unknown character.  Could you try to re-type the command again?  If it returns the same error, then please provide the output of the `--debug` option so I can look into what is happening.

**Comment by stamhankar999** [comment]
You're absolutely right. I thought I'd eliminated that possibility and typed the whole command in, but it seems there was a hidden character in my command that threw things off. Not sure how that happened; will blame the person who sent me the command in the first place! ;)

**Comment by justnance** [comment]
Thanks for the feedback @stamhankar999 !
