### ISSUE TITLE
Support for AWS::CodeCommit::Repository in aws cloudformation package

### ISSUE THREAD

**Issue by nmoutschen** [aws/aws-cli#4316]
``AWS::CodeCommit::Repository`` now support the ability to specify a zip file in S3 to seed the repository. ``aws cloudformation package`` doesn't support it as a way to automatically package and send to s3 the seed files.

**Comment by justnance** [comment]
@nmoutschen - Thank you for posting this issue and submitting the PR.  I am labeling this as a feature request pending further review.  

@sanathkr - What are you thoughts?

**Comment by andrewgoss** [comment]
hi everyone, I am wondering how soon this could be released, as it would be a helpful addition

**Comment by nmoutschen** [comment]
Just checking here as it's been a long time. What's the status on this?
