### ISSUE TITLE
aws cp failed to download few larger files ~45 MB

### ISSUE THREAD

**Issue by ankitworld007** [aws/aws-cli#4320]

**Comment by ankitworld007** [comment]
I am seeing this strange issue since last week at first I thought was using the the wrong credentails but that's not true another file in same bucket size < 1MB can easily download to my local machine. For larger file gettig error "**An error occurred (SignatureDoesNotMatch) when calling the GetObject operation: The request signature we calculated match the signature you provided. Check your key and signing method.**"

copy command used
aws s3 cp s3://<bucket>/folder/filename.json . --profile test1

boto3 - 1.9.188
botocore - 1.12.188
Python 3.7.0

Please suggest if any there is any restriction in s3 to download bigger files

**Comment by justnance** [comment]
@ankitworld007 - Thank you for posting this issue.  To help us narrow down the root cause and understand what is happening, we would need the output from using the --debug option.

Related issue:  #1775

**Comment by justnance** [comment]
@ankitworld007 - Thank you for posting this issue.  To help us narrow down the root cause and understand what is happening, we would need the output from using the --debug option.

Related issue:  #1775
