### ISSUE TITLE
Documentation for describe-route-tables includes examples for a different API

### ISSUE THREAD

**Issue by tleonhardt** [aws/aws-cli#4331]
The [documentation for describe-route-tables](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-route-tables.html) is incorrect.

The examples show are for the `create-vpc-endpoint` API, not for `describe-route-tables`.

The offending commit appears to be the following: https://github.com/aws/aws-cli/commit/b4f312479f49a83194458a194426def9e9dd2342

**Comment by justnance** [comment]
@tleonhardt - Thank you for pointing this out.  I'm going to collaborate with our doc writers to get this fixed.

**Comment by justnance** [comment]
@tleonhardt - The fix is pending release.

**Comment by bisdavid** [comment]
This has been fixed.  The correct example is there now.  Thanks for finding this and bringing to our attention!

**Comment by tleonhardt** [comment]
The example looks good.  Thanks for the fix!
