### ISSUE TITLE
Public Hosted Zone support in GovCloud Route53

### ISSUE THREAD

**Issue by tedmiston** [aws/aws-cli#4333]
Base support for Route53 was [recently added](https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-route-53-launches-private-dns-and-health-checks-in-the-aws-govcloud-us-west-region/) to GovCloud, however attempting to use Route53 via the CLI is currently broken per the bug mentioned in #4241.

Once that issue is resolved, we'll be able to create *Private* hosted zones via the CLI.  What I'd like to inquire about is support for creating *Public* hosted zones in GovCloud via the CLI.

Currently the AWS Console itself seems to only support Private in GovCloud, whereas it supports Private and Public in other regions.

[Today this must be solved by creating a second (public) hosted zone in a separate Route53 in a non-GovCloud region with CNAME records pointing back to ELB addresses within GovCloud.]

It's possible this feature will never be added to GovCloud — I'm seeking clarity regarding if it is on the roadmap.

**Comment by justnance** [comment]
@tedmiston - Thanks for posting this issue and mentioning #4241.  This is a roadmap question and feature for the service team to review and approve.  The CLI only echoes what is returned by the service.   I suggest posting these questions and feature request on the [service team's forums](https://forums.aws.amazon.com/forum.jspa?forumID=87).  If you can post the forum link here I can escalate it internally.
