### ISSUE TITLE
aws s3 exclude / include commands ignored

### ISSUE THREAD

**Issue by paulsickling** [aws/aws-cli#434]
On Windows - when using aws s3 commands (cp or mv) with exclude and/or include parameters the parameters only seem to be honoured if the command is executed from the same drive as the source parameter. 

For instance if the source folder is d:\backup and the command is run anywhere from d:\ within cmd then exclude / include parameters are honoured. If the cmd drive is changed to c:\ then the exclude and include parameters appear to be ignored.

See output below

C:>aws s3 cp d:/backups/temp3/ s3://xxx/ --recursive --exclude \* --include *.zip
upload: d:\backups\temp3\2.zip to s3://xxx/test/2.zip
upload: d:\backups\temp3\readme.zip to s3://xxx/readme.zip
upload: d:\backups\temp3\readme.txt to s3://xxx/readme.txt (<<< EXTRA FILE PICKED UP)

C:>d:

D:>aws s3 cp d:/backups/temp3/ s3://xxx/ --recursive --exclude \* --include *.zip
upload: backups\temp3\readme.zip to s3:/xxx/readme.zip
upload: backups\temp3\2.zip to s3:/xxx/test/2.zip

I've tried various source path syntaxes including d:\backups... d://backups/... but all yield the same result.

The workaround for the time is to ensure cmd is started from the same drive as the source but I assume that isn't by design.

Love the tool in every other way!

**Comment by kilianc** [comment]
I still experience this with rm on `aws-cli/1.9.10 Python/2.7.10 Darwin/15.2.0 botocore/1.3.10`

**Comment by kilianc** [comment]
```
aws s3 rm "$S3_BUCKET/test/" --region ${S3_REGION:=us-east-1} --recursive --exclude "$S3_BUCKET/test/test1" --dryrun
```
```
(dryrun) delete: s3://my-bucket/test/
(dryrun) delete: s3://my-bucket/test/test1/
(dryrun) delete: s3://my-bucket/test/test1/pqatf4enkhxpfyuwkstq.jpg
(dryrun) delete: s3://my-bucket/test/test2/
(dryrun) delete: s3://my-bucket/test/test2/11870654_10207611827477332_7255026580168751425_n.jpg
```

**Comment by jingpengwu** [comment]
me too, only `exclude` works, `include` do not.

**Comment by 1adam** [comment]
Exclude doesn't seem to be working properly when attempting to sync from local to s3:

aws-cli/1.10.67 Python/2.7.6 Linux/3.13.0-79-generic botocore/1.4.57

`
$ tree static/
static/
├── valid
│   └── files
│       └── file.json
└── weather
    └── json
        └── file.json

4 directories, 2 files

$ aws s3 sync ./static/ s3://my-bucket/static/ --exclude "static/weather/*"
upload: static/valid/files/file.json to s3://my-bucket/static/valid/files/file.json
upload: static/weather/json/file.json to s3://my-bucket/static/weather/json/file.json

<delete 'static' from bucket>

$ aws s3 sync ./static/ s3://my-bucket/static/ --exclude "*static/weather/*"
upload: static/valid/files/file.json to s3://my-bucket/static/valid/files/file.json
upload: static/weather/json/file.json to s3://my-bucket/static/weather/json/file.json
`

**Comment by mtocci** [comment]
@1adam thanks! This worked for me for multiple directory excludes. I'm on Win10, so it looks like this:
`--exclude "*Windows10Upgrade\*"`

**Comment by chriszrc** [comment]
Seems like even though the files are at the top level, if you want include/exclude to work, you need the --recursive flag:

https://stackoverflow.com/questions/43370710/s3-cli-includes-not-working
