### ISSUE TITLE
codecommit: tag-resource does not permit `:` character in tag key

### ISSUE THREAD

**Issue by otterley** [aws/aws-cli#4348]
The following command incorrectly returns an error even though colon characters (`:`) in tag keys are legal:

```
aws codecommit tag-resource --resource-arn <arn> --tags namespace:KeyName=value
```

Expected behavior: a new tag is applied to the resource with the name `namespace:KeyName` and value `value`.

Actual behavior:

```
Error parsing parameter '--tags': Expected: '=', received: ':' for input:
namespace:KeyName=value
```

**Comment by justnance** [comment]
@otterley - Thanks for posting this issue.  Try the following syntax:

```
aws codecommit tag-resource --resource-arn <arn> --tags Key=namespace:KeyName,Value=value
```

There are some other examples of tagging resources under the [EC2 reference page](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-tags.html).

Let us know if this helps.

**Comment by otterley** [comment]
Hi @justnance!  Codecommit's tagging API is different from EC2's, and so the `Key=k,Value=v` syntax is not used by the `tag-resource` subcommand or its corresponding API.  See [the CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/codecommit/tag-resource.html) and [API documentation](https://docs.aws.amazon.com/codecommit/latest/APIReference/API_TagResource.html) for additional details.   

Using the syntax above, you would instead get two tags: one called `Key` whose value is `namespace:Keyname` and another called `Value` whose value is `value`.

**Comment by justnance** [comment]
@otterley - Thanks for the feedback and sorry about recommending the wrong syntax.  I reproduced and used the following:

```
aws codecommit tag-resource --resource-arn arn:aws:codecommit:us-west-2:123456789101112:clitags --tags name="namespace:KeyName",Value=Value5
```
```
aws codecommit list-tags-for-resource --resource-arn arn:aws:codecommit:us-west-2:123456789101112:clitags
```

```json
{
    "tags": {
        "Value": "Value5",
        "name": "namespace:KeyName",
    }
}
```

I also found an exampler [here](https://docs.aws.amazon.com/codecommit/latest/userguide/how-to-tag-repository-add.html#how-to-tag-repository-add-cli) but I looks like some of our other documentation could use some better examples.  I'm going to get this escalated internally.

**Comment by justnance** [comment]
@otterley - Thanks for the feedback and sorry about recommending the wrong syntax.  I reproduced and used the following:

```
aws codecommit tag-resource --resource-arn arn:aws:codecommit:us-west-2:123456789101112:clitags --tags name="namespace:KeyName",Value=Value5
```
```
aws codecommit list-tags-for-resource --resource-arn arn:aws:codecommit:us-west-2:123456789101112:clitags
```

```json
{
    "tags": {
        "Value": "Value5",
        "name": "namespace:KeyName",
    }
}
```

I also found an exampler [here](https://docs.aws.amazon.com/codecommit/latest/userguide/how-to-tag-repository-add.html#how-to-tag-repository-add-cli) but I looks like some of our other documentation could use some better examples.  I'm going to get this escalated internally.

**Comment by justnance** [comment]
@otterley - As discussed offline, I am reopening this issue as I was able to reproduce and confirm this issue with the following steps:

1.  Created a new tag using the AWS Management Console which includes a colon and then listed it with the CLI:

```

$ aws codecommit list-tags-for-resource --resource-arn arn:aws:codecommit:us-west-2:1234567890101112:clitagtest
{
    "tags": {
        "namespace:Keyname": "namespaceValue"
    }
}

```

This confirmed the service was allowing a tag name with a colon.  Next, I tried to create another new tag with a colon using the following the CLI command but it returned the same error reported in your first response:

```
$ aws codecommit list-tags-for-resource --resource-arn arn:aws:codecommit:us-west-2:1234567890101112:clitagtest
{
    "tags": {
        "namespace:Keyname": "namespaceValue"
    }
}

$ aws codecommit tag-resource --resource-arn arn:aws:codecommit:us-west-2:123456789101112:clitagtest --tags "namespace:KeyName2"=KeyNameValue

Error parsing parameter '--tags': Expected: '=', received: ':' for input:
namespace:KeyName2=KeyNameValue

```

I am escalating this internally and we are looking to get it resolved.

**Comment by jamesls** [comment]
Hi, just confirming, shorthand syntax doesn't support `:` for key names.  Should be ok to update the parser to support this, but you'll have to use the JSON syntax for now to specify tag keys with `:`chars:


```
aws codecommit tag-resource --resource-arn aws:codeommit:us-east-1:12345:sfasfadsf \
    --tags '{"namespace:KeyName": "value"}'
```
