### ISSUE TITLE
pyyaml<=5.1 runs into issues with serial install on Python 3.6

### ISSUE THREAD

**Issue by aviveve** [aws/aws-cli#4350]
I had an installed version of AWS CLI. But the pip install of serial failed since AWS CLI had a requirement that pyyaml <= 5.1. So I uninstalled awscli and reinstalled serial. It installed but installed PyYAML of 5.1.1.
Re-install of awscli now fails because of restrction yaml version.

Collecting serial
  Using cached https://files.pythonhosted.org/packages/1f/51/6a260c498162c37d0759f3759b7647a10d8d30caba1cfc9aa4b5b1f0d08b/serial-0.0.97-py2.py3-none-any.whl
Requirement already satisfied: iso8601>=0.1.12 in c:\programdata\anaconda3\lib\site-packages (from serial) (0.1.12)
Requirement already satisfied: future>=0.17.1 in c:\programdata\anaconda3\lib\site-packages (from serial) (0.17.1)
Requirement already satisfied: pyyaml>=3.13 in c:\programdata\anaconda3\lib\site-packages (from serial) (5.1.1)
Installing collected packages: serial
Successfully installed serial-0.0.97

C:\WINDOWS\system32>pip install awscli
Collecting awscli
  Using cached https://files.pythonhosted.org/packages/e3/56/398e5e1c1484b5e25da6eafbeca8ec2a69e25942485fe5c0aa6d3d173310/awscli-1.16.206-py2.py3-none-any.whl
Requirement already satisfied: botocore==1.12.196 in c:\programdata\anaconda3\lib\site-packages (from awscli) (1.12.196)
Requirement already satisfied: colorama<=0.3.9,>=0.2.5 in c:\programdata\anaconda3\lib\site-packages (from awscli) (0.3.7)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in c:\programdata\anaconda3\lib\site-packages (from awscli) (3.4.2)
Collecting PyYAML<=5.1,>=3.10; python_version != "2.6" (from awscli)
  Downloading https://files.pythonhosted.org/packages/72/da/386634cb17f33b12278af017ccb3314cede4806af70285f396b8f6af1203/PyYAML-5.1-cp36-cp36m-win_amd64.whl (214kB)
     |████████████████████████████████| 215kB 1.6MB/s
Requirement already satisfied: docutils<0.15,>=0.10 in c:\programdata\anaconda3\lib\site-packages (from awscli) (0.13.1)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\programdata\anaconda3\lib\site-packages (from awscli) (0.2.1)
Requirement already satisfied: urllib3<1.26,>=1.20; python_version >= "3.4" in c:\programdata\anaconda3\lib\site-packages (from botocore==1.12.196->awscli) (1.24.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from botocore==1.12.196->awscli) (0.9.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\programdata\anaconda3\lib\site-packages (from botocore==1.12.196->awscli) (2.6.0)
Requirement already satisfied: pyasn1>=0.1.3 in c:\programdata\anaconda3\lib\site-packages (from rsa<=3.5.0,>=3.1.2->awscli) (0.1.9)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore==1.12.196->awscli) (1.10.0)
Installing collected packages: PyYAML, awscli
  Found existing installation: PyYAML 5.1.1
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by justnance** [comment]
@aviveve - Thanks for posting this issue.  I've confirmed the behavior and labeled it has enhancement.  We are working on getting fixed under #4355.

**Comment by stealthycoin** [comment]
Merged
