### ISSUE TITLE
Bad interpreter. Python interpreter path longer than 128 characters

### ISSUE THREAD

**Issue by bdekksqula** [aws/aws-cli#4354]
I am running the awscli on our jenkins server in a virtualenvironment. This makes the path to the python interpreter more than 128 characters which results in a 'Bad Interpreter' error.

The first line of the aws executable is:

> #!/var/lib/jenkins-slave/workspace/xxx-xxxx-xxxx-xxx-xxx-xxx/v/bin/python3.7

The fix would be to generate the following:

> #!/bin/sh
> '''exec' /var/lib/jenkins-slave/workspace/xxx-xxxx-xxxx-xxx-xxx-xxx/v/bin/python3.7 "$0" "$@"
> ' '''

See: https://github.com/pypa/virtualenv/issues/596 for more information about the virtualenv issue.

**Comment by justnance** [comment]
@bdekksqula - Thanks for posting this issue.  The CLI does not control this behavior but it looks like it is a known issue and workarounds discussed in Python Packaging Authority's repos:

[Shebang length exceeded in pip executable - virtualenv #596](https://github.com/pypa/virtualenv/issues/596)

[Shebang length exceeded in pip executable - pip #1773](https://github.com/pypa/pip/issues/1773)
