### ISSUE TITLE
Permission denied when piping stdout

### ISSUE THREAD

**Issue by mal** [aws/aws-cli#4357]
When piping the `stdout` from `aws` with `nodejs`, `aws` throws an exception and crashes/exits. This used to work and has only surfaced since upgrading the version of `aws` being used.

Working in `1.10.1`, upgraded to and now broken in `1.16.148`.

---

Example shows the error when `stdio[1]` (`stdout`) is set to `pipe`, but OK when set to `inherit` (the `stdout` of the `nodejs` process).
```
$ aws --version                                                                                            
aws-cli/1.16.148 Python/3.6.7 Linux/4.18.0-25-generic botocore/1.12.138

$ node -v                                                                                                  
v11.15.0

$ node -e "require('child_process').spawn('aws', ['--version'], {stdio: ['ignore', 'pipe', 'inherit']})"
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
PermissionError: [Errno 13] Permission denied

$ node -e "require('child_process').spawn('aws', ['--version'], {stdio: ['ignore', 'inherit', 'inherit']})" 
aws-cli/1.16.148 Python/3.6.7 Linux/4.18.0-25-generic botocore/1.12.138
```

I understand there's a chance this could be down to `node` doing something weird, but since this was previously working and is now not and only the version of `aws` has changed I'm reporting here first.

Both `aws` and `node` are installed on Ubuntu 18.04 as snaps.

**Comment by klaytaybai** [comment]
Hi @mal, I'm working on getting an Ubuntu environment setup to test this, but I suspect that the issue is not on the AWS side.  We're wondering if it is potentially an error with your node setup.  I'll try investigating this more thoroughly tomorrow.  Please let us know if you have any updates as well.

Can I ask why you are using 1.16.148 if you are upgrading the CLI and not a newer version?

**Comment by mal** [comment]
I had a similar thought when I first encountered it and so verified the behaviour on a pristine OS install using a Live CD. Using the "Try Ubuntu" feature after booting from a Live CD image (I used 18.04.2) and opening a terminal, the issue can be reproduced as follows:

```
ubuntu@ubuntu:~$ sudo snap install node --channel=11/stable --classic
node (11/stable) 11.15.0 from NodeSource, Inc. (nodesource) installed

ubuntu@ubuntu:~$ sudo snap install aws-cli --classic
aws-cli 1.16.148 from Amazon Web Services (aws) installed

ubuntu@ubuntu:~$ node -e "require('child_process').spawn('aws', ['--version'], {stdio: ['ignore', 'pipe', 'inherit']})"
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
PermissionError: [Errno 13] Permission denied

ubuntu@ubuntu:~$ node -e "require('child_process').spawn('aws', ['--version'], {stdio: ['ignore', 'inherit', 'inherit']})" 
aws-cli/1.16.148 Python/3.6.7 Linux/4.18.0-25-generic botocore/1.12.138
```

The versions in use are determined by the latest published snaps, which can be found on snapcraft.io - [node](https://snapcraft.io/node) and [aws-cli](https://snapcraft.io/aws-cli).

**Comment by kdaily** [comment]
Hi @mal, is this still an issue? Also as a note, the snaps are not maintained by AWS, but by SnapCraft. I would try this with one of the official installation mechanisms for the AWS CLI. Thanks!

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

**Comment by mal** [comment]
The provenance of the `aws-cli` snap (https://snapcraft.io/aws-cli) is clearly indicated to be a verified publisher account representing AWS. If this is not, or is no longer the case then I'd recommend trying to either reclaim ownership or otherwise have it clearly marked as not an official source. Indeed looking at it now it seems to be seldom updated, and the edge channel non-functional. This is at the very least, confusing in it's own right.

As to the issue Itself, it remains reproducible, however with the version in the snap being so out of date, the reproduction means little. The "Exception ignored in" is typically as a result of an unhandled exception in a Python generator (or these days, perhaps an async method), and as the only Python part involved in the test case is on the `aws-cli` side, it would seem that at the very least there was (and I guess potentially still is) an unhandled exception capable of being thrown in the codebase, resulting in this fairly limited error message.

Given the lack of other reports of this, even if still legitimate it would seem to be an extreme edge case, and for our part we were forced to work around this over a year ago now, so it ends up of little consequence.

As a final thought I would encourage consideration being given to providing an up-to-date official snap package, it does provide a non-negligible benefit when getting new developers on-boarded and they already have five-hundred new things to learn, and a one liner installation that skips any requirement to know about Python versions, pip, or be constrained to an older version by the more slowly updating OS packaging systems is certainly convenient.

Thanks for your time!

**Comment by kdaily** [comment]
Hi @mal, thanks for the comment. I take that back - it seems that I mispoke, and someone at AWS did publish the AWS Snap. I will look into this further.

**Comment by kdaily** [comment]
@mal, thanks again for bringing attention to this. We'll look into getting the snap functional and current.
