### ISSUE TITLE
How do i remove credentials from ec2 when Creating an AMI?

### ISSUE THREAD

**Issue by Aoshokoya00** [aws/aws-cli#4359]
How do i remove credentials from ec2 when Creating an AMI? 

(Sysprep) AWS

**Comment by justnance** [comment]
@Aoshokoya00 - Thanks for posting your question.  It sounds like you are trying to [customize an AMI using sysprep](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ami-create-standard.html).     

[AMIs can be created with the CLI](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-image.html) but the CLI does not control the sysprep behavior.  It is recommended to reach out to the [EC2 forums](https://forums.aws.amazon.com/forum.jspa?forumID=30) as there will probably be individuals that can provide further help.
