### ISSUE TITLE
Command to reduce EBS volume size

### ISSUE THREAD

**Issue by binarykitchen** [aws/aws-cli#4376]
I know everyone says it's not possible. Only can increase.

There are unofficial manuals how to do this by detaching, new snapshot, multiple volumes, formatting, running rsync etc etc. but all of them few years old, outdated.

Not sure if this is ever implementable. Or if there are scripts meanwhile to semi-automate this. This awi-cli tool might help with that or at least output a link to a manual or so?

I am sure this is a wanted feature by many. Very much.

**Comment by justnance** [comment]
@binarykitchen - Thank you for your post.  This behavior is controlled by the service as the CLI is only echoing what is returned by the service.  As you already mentioned, [decreasing the size of an EBS volume is not supported.  I suggest reaching out to the service team on their [forums.](https://forums.aws.amazon.com/forum.jspa?forumID=30)

This is also related to issue #4216

**Comment by binarykitchen** [comment]
Thanks. But hmmm, searched through all their forums but not a single clue, tip, how to decrease an existing EBS volume. And Google search results neither. Most are outdated or not helpful.
