### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by stevemao** [aws/aws-cli#4377]
https://docs.aws.amazon.com/cli/latest/reference/s3api/select-object-content.html

In --input-serialization (structure):

```
CSV={FileHeaderInfo=string,Comments=string,QuoteEscapeCharacter=string,RecordDelimiter=string,FieldDelimiter=string,QuoteCharacter=string,AllowQuotedRecordDelimiter=boolean},CompressionType=string,JSON={Type=string},Parquet={}
```

`JSON={Type=string}` should be `JSON={Type= DOCUMENT}`

**Comment by bisdavid** [comment]
@stevemao, 

I think the docs are correct.  The shorthand CSV syntax is showing the data types that are expected for each value if you submit as a CSV. The shorthand syntax simply doesn't elaborate on the values of enums here.  The JSON syntax is simply more explicit, and does show that the string must be one of two specific values: DOCUMENT or LINES. But both of those are indeed strings.  Whether you submit as CSV or JSON, that value must be submitted as a string, and that string must be either "DOCUMENT" or "LINES".

**Comment by stevemao** [comment]
It's true. I knew it was just the type but when I saw string, I was expecting any arbitrary string not a enum. So the type is a bit too generic and seems confusing. Feel free to close it if you think a generic type is fine. Cheers!
