### ISSUE TITLE
send us a pull request on GitHub should link the source or docs file

### ISSUE THREAD

**Issue by stevemao** [aws/aws-cli#4378]
I can't find where the source code or the docs live. They should probably be linked on the website. EG: https://docs.aws.amazon.com/cli/latest/reference/s3api/select-object-content.html should link the source and docs of `select-object-content`

**Comment by bisdavid** [comment]
Steve,

Part of the content (such as the syntax blocks you referred to in another issue) is generated programmatically from the source code of the services involved, so we can't directly update it.  The descriptions for the APIs also are not directly editable by us (or you thru a pull request). Those descriptions come from the Service Writers who write the API Reference docs for their assigned services. We import that content into each of the SDKs, including the CLI.  If you find a bug with one of those, the best way to report it is to use the Feedback link that is available on every one of our documentation pages.  That generates a service ticket that is assigned directly to the correct writer who can fix the source content.

I hope this helps!

**Comment by justnance** [comment]
@stevemao and @bisdavid  - thanks for your post. I'm setting this issue to close soon.

**Comment by stevemao** [comment]
Thanks @bisdavid for the explanation. I think "or send us a pull request on GitHub." is a bit confusing then because in the context I read "send us a pull request on GitHub if you want to improve the page". Since the source code is open source, it'd be great to link to the source directly IMO.

**Comment by kdaily** [comment]
Hi @stevemao,

I agree with you that it's confusing! I'm working on improving our contribution guidelines. I think a link to our CONTRIBUTING file (with improvements) would be better suited here. I'd probably even move it to it's own line to separate the thoughts a bit more so others aren't parsing it as you are. What do you think?
