### ISSUE TITLE
un-pin docutils

### ISSUE THREAD

**Issue by glyph** [aws/aws-cli#4382]
Docutils was pinned as a result of https://github.com/aws/aws-cli/issues/4332 but almost immediately following that fix, 0.15.post1 was released, addressing the issue: https://github.com/aws/aws-cli/issues/4332#issuecomment-513774699

Please remove the docutils pin.

**Comment by glyph** [comment]
(Would a PR help to move this along?  Happy to write one if so...)

**Comment by swetashre** [comment]
@glyph - Thank you for your post. I would mark this as a feature request.

**Comment by glyph** [comment]
Thanks @swetashre !

**Comment by kdaily** [comment]
Closing this as it has been addressed. We will likely continue to pin to assure backwards compatibility and stability. We appreciate bringing these issues to our attention, and will be considering automation via Dependabot or the like to raise awareness of them. Thank you!
