### ISSUE TITLE
aws s3 ls got  an unexpected keyword argument - 'cert_file' or 'key_password' or 'key_file'

### ISSUE THREAD

**Issue by EpiqSty** [aws/aws-cli#4393]
aws s3 ls  gets random error on every run:
```
$ aws s3 ls

__init__() got an unexpected keyword argument 'cert_file'
$ aws s3 ls

__init__() got an unexpected keyword argument 'key_password'
$ aws s3 ls

__init__() got an unexpected keyword argument 'key_file'
$ aws s3 ls

__init__() got an unexpected keyword argument 'cert_file'
$
```

Meanwhile aws config proceeds fine without issues:
```
$ aws configure
AWS Access Key ID [****************6SZQ]:
AWS Secret Access Key [****************xr5g]:
Default region name [eu-central-1]:
Default output format [None]:
```

my version is:
```
$ aws --version
aws-cli/1.11.13 Python/3.5.3 Linux/4.4.0-17134-Microsoft botocore/1.4.70

```

Could you please advice, what could be wrong here?

**Comment by stealthycoin** [comment]
Can you try running `aws --version` and posting the output here.
Also the output of `aws s3 ls --debug` would be helpful, depending on how far its getting.

Likely some dependency in your environment is not at the correct version and its `init` interface has changed. Reinstalling should force compatible versions of everything to be installed.

**Comment by shreya1704** [comment]
I am getting similar errors while running s3 mv command
<img width="1242" alt="Screen Shot 2019-08-13 at 5 18 19 PM" src="https://user-images.githubusercontent.com/33744933/62978134-8dc6e880-bdee-11e9-8ac8-db79ef5bf536.png">

**Comment by EpiqSty** [comment]
`sudo apt-get purge awscli && sudo pip install awscli
`
fixed the issue in my case, thanks @stealthycoin

**Comment by stealthycoin** [comment]
Cool glad that worked. @shreya1704 try the same solution and if it doesn't work open a new issue if you still have trouble.

**Comment by shreya1704** [comment]
It worked for me as well. thank you.

**Comment by rafee** [comment]
It  worked for me as well

**Comment by surapuramakhil** [comment]
> `sudo apt-get purge awscli && sudo pip install awscli `
> fixed the issue in my case, thanks @stealthycoin

its a bit strange. seems unsupported is getting installed  from  apt-get ubuntu repo's and pip contains maintained one without issue

**Comment by razzinger** [comment]
sudo apt-get purge awscli && sudo pip3 install awscli

due to python2 is depricated

**Comment by nellshamrell** [comment]
Thank you thank you thank you! This just saved me!

**Comment by kotireddyaluri** [comment]
For Ubuntu
sudo apt update && sudo apt install awscli

**Comment by lcabral37** [comment]
I've traced this to having an incompatible version of urllibc3. I had another process that had installed a more recent urllibc3 in the user domain. once I reinstalled the right version awscli worked again

I would assume the installation might have fixed up the version potentially?
