### ISSUE TITLE
S3 Sync with "--delete" option is deleting files that have folders with the same name!

### ISSUE THREAD

**Issue by ddarbyson** [aws/aws-cli#440]
If you have a folder in your S3 bucket and a file name that contains the same starting characters as the folder name, the target files will be intermittently be deleted upon each run.

For example, create a folder in your S3 bucket:

s3://my-bucket/test/

Now create some txt files in the bucket with 'test' as the first 4 characters of the file name.. ie:

s3://my-bucket/test-123.txt
s3://my-bucket/test-321.txt
s3://my-bucket/test.txt

Run `aws s3 sync --delete s3://my-bucket /my/local/folder`.. Do this 3 or 4 times. You will see each file 'test-123.txt', 'test-321.txt', 'test.txt' will get intermittently be deleted and downloaded with each run. Each run produces different results.

Having files unexpectedly being deleting is a big concern as we use 's3 sync --delete' for daily backup's.

Please see AWS post for originating report https://forums.aws.amazon.com/message.jspa?messageID=497335#497335

**Comment by ClementWalter** [comment]
I had a similar issue with `aws-cli/1.15.10 Python/3.6.5 Darwin/15.6.0 botocore/1.10.45` but because of CAPITAL folders name. Basically I had data in my local computer within the `folder/` directory but they were stored as `s3://bucket-name/FOLDER/`.

Each call to `aws s3 sync s3://bucket-name/FOLDER folder --delete` would remove them and them again in the same `folder/` directory

**Comment by beckindesigns** [comment]
I know this is an older post but the resolution to perfectly sync what you have on your local machine to your bucket all you need to do is add the --delete option to the original sync from your local (source) to your bucket (destination).

`aws s3 sync /localfolder s3://bucket-name/localfolder --delete`

If the file/folder exists on local it will create it in your bucket and if it no longer exists on local then it will delete it in your bucket. This is the proper way to fully sync (upload) your local to the bucket.
