### ISSUE TITLE
Update task definition with new revision

### ISSUE THREAD

**Issue by ORESoftware** [aws/aws-cli#4401]
I am looking for this functionality:

```
aws ecs update-task-definition
```

without it, people are using this instead:

```
aws ecs register-task-definition
```

but that doesn't make sense, because we are not creating a new task def, but instead creating a revision for an existing task definition.

**Comment by stealthycoin** [comment]
This would be a request for the ecs team, which you can make either through 
[AWS Support](https://console.aws.amazon.com/support/home#/)
or their [Service Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187)

**Comment by ORESoftware** [comment]
@stealthycoin all due respect this seems like an aws-cli functionality feature request right?

**Comment by coolxeo** [comment]
aws-cli support, if you don't like us to discuss just don't use github, sorry, this is still valid and should be reopened
