### ISSUE TITLE
AWS cognito trigger after create app client in client credential flow

### ISSUE THREAD

**Issue by saiprateek** [aws/aws-cli#4405]
I'm trying to find a way to trigger a lambda function after creating an app client for client credential flow in AWS cognito but unfortunately I did not find any way to do it. Is there any to trigger a lambda after creating an app client from cognito UI?  and if not what options I have to trigger lambda when a new app client created?

**Comment by stealthycoin** [comment]
This looks like a service usage question. You should ask questions about service usage on either
[AWS Support](https://console.aws.amazon.com/support/home#/) or 
[stackoverflow](https://stackoverflow.com/). We don't have any particular knowledge about the services or their usage as there are so many of them, we can only answer questions about things specific to the AWS CLI.
