### ISSUE TITLE
AWS Glue 'WorkflowName' field is not present in get-triggers or get-trigger response

### ISSUE THREAD

**Issue by dmytro-bekuzarov** [aws/aws-cli#4406]
I have  several AWS Glue workflows with several triggers.
However, if you call get-triggers or get-trigger, `WorkflowName` field is not present in response.
Same behavior for boto3 client. 
I have the latest versions of both aws cli and boto3.
get-triggers or get-trigger returns all other fields properly, including actions on crawlers, not not a  `WorkflowName`.
Example:
```
aws glue get-trigger --name test_1
{
    "Trigger": {
        "Name": "test_1",
        "Type": "SCHEDULED",
        "State": "CREATED",
        "Schedule": "cron(0 0 * * ? *)",
        "Actions": [
            {
                "CrawlerName": "test_1_crawler"
            }
        ]
    }
}
```
It looks like this field is not returned from API at all, so not sure if this is related to AWS CLI.

Note: Triggers are created properly with `WorkflowName` field, but on get operations this field is absent

**Comment by stealthycoin** [comment]
I only can answer questions about the CLI specifically and this is a service question, I've never used glue myself so I can't help incidentally either. I'd suggest asking on either 
[AWS Support](https://console.aws.amazon.com/support/home#/)
[Glue service forums](https://forums.aws.amazon.com/forum.jspa?forumID=262)

Sorry I can't be of more help.
