### ISSUE TITLE
S3 and large files backup

### ISSUE THREAD

**Issue by martio** [aws/aws-cli#4417]
Hi,

I have large files and I am looking for a place where I could store files (databases dumps). AWS S3 is good for backups? I have already exceeded all limits. 

I have a few questions:

1. I am using API and CLI. Which solution is cheaper to send files via API? "aws s3api put-object" or "aws s3 cp"?
2. "2,000 Put, Copy, Post or List Requests of Amazon S3". How is consumption calculated? In HTTP requests or bytes? Ac Currently, Currently, I have level of consumption for 20 files per day: 2,000.00/2,000 Requests.
3. Are there any paid plans?

**Comment by kyleknap** [comment]
I would recommend reaching out to AWS Support for the last two questions. As stated in our [README](https://github.com/aws/aws-cli#getting-help), we try to reserve GitHub issues for feature requests and bugs.

For the first question, `s3api put-object` and `s3 cp` are running the same API call under the hood for small files. For larger files, the `s3 cp` command will start using multipart uploads if the file is larger than 8MB and do it in chunks of 8MB causing more requests to be sent. It is also important that you can [configure these values](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html#cli-aws-help-s3-config). The `s3api put-object` command will not do that and will always use a single put call. However, the maximum size that can be sent is 5GB and does not handle automatically switching to multipart uploads. In general, `s3 cp` command is more convenient to use and may send more requests by default than invoking a bunch of `s3api put-object` but you can configure the `s3 cp` commands to equate to the same API calls if you did it yourself with individual `s3api put-object` commands.
