### ISSUE TITLE
AWS ChatBot

### ISSUE THREAD

**Issue by ouadie-lahdioui** [aws/aws-cli#4418]
Hello guys,

Any plan to support the new AWS ChatBot service?

Thank you for the awesome work

**Comment by swetashre** [comment]
@ouadie-lahdioui - Thank you for your post. I would mark this as a feature request.

**Comment by QuinnyPig** [comment]
Now that Chatbot has gone GA, and there are some fascinating console bugs, it would be a prime time to revisit this issue.

**Comment by FSJRay** [comment]
I just wanted to revive this and see if there was any movement?

**Comment by tim-finnigan** [comment]
You can find documentation on using AWS CLI commands with ChatBot here: https://docs.aws.amazon.com/chatbot/latest/adminguide/chatbot-cli-commands.html. 

But there aren't any service API commands available for ChatBot in the AWS CLI [command reference](https://docs.aws.amazon.com/cli/latest/index.html) or for other SDKs. For tracking announcements involving new APIs your best bet is to follow the [AWS blog](https://aws.amazon.com/blogs/aws/category/post-types/announcements/) or [what's new page](https://aws.amazon.com/new). And for issues involving service APIs we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for further escalation. If there's any ChatBot issues directly related to the AWS CLI please create a new issue here in this repository. Thanks!
