### ISSUE TITLE
Get Role Permissions Boundary not returned in list-roles API call

### ISSUE THREAD

**Issue by devhulk** [aws/aws-cli#4421]
In the documentation it says you should get back the Permissions Boundaries per role under Outputs https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html. 

Is this a recent change? Right now we have to list all roles using list-roles then call get-role on every role.

**Comment by kyleknap** [comment]
Looking over the git history, it looks like it got added a year ago. Is the permission boundary information not being returned to you in `list-roles`?
