### ISSUE TITLE
need help to get day before yesterday terminated instances details like instance type, tags

### ISSUE THREAD

**Issue by AjithKumar-Raj** [aws/aws-cli#4426]
As per the [describe-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) doc, we can get terminated instance details within an hour. Is there any way I can do for getting a day before yesterday terminated instances details like instance type, tags.

**Comment by kyleknap** [comment]
As per our [README](https://github.com/aws/aws-cli#getting-help), we try to reserve issues to GitHub feature requests and bug specifically for the AWS CLI. I'd recommend reaching out to AWS Support on how to accomplish this.
