### ISSUE TITLE
Service Catalog --support-url not being passed as String but does a HTTP get

### ISSUE THREAD

**Issue by keagansc2** [aws/aws-cli#4427]
Hi,

While utilizing the service catalog CLI if the parameter of --support-url is used for the create-product, the CLI does an actual HTTP get request on the URL provided instead of just giving the parameter as a string. Since the URL would return the entire HTTP response it would go over the limit of 2083 characters. 

Even if the quotations are escaped a new error is retrieved, the only workaround I have found is to either have all the parameter values within a JSON file or to just have the support URL parameter within the JSON file.

Looking into the documentation of the behavior which could be causing this is here:
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters.html#cli-usage-parameters-file-remote

Stating that:
"
The AWS CLI also supports loading parameters from a file hosted on the internet with an http:// or https:// URL
"
therefore I believe that the support url parameter is not being validated by the create-product CLI command but rather by the underlying CLI behavior.

**Comment by joguSD** [comment]
You're correct in the root cause being remote fetching and that would be the suggested workaround. Considering these will always be URLs I've opened https://github.com/aws/aws-cli/pull/4458 which will disable this behavior by default.
