### ISSUE TITLE
Having issues in configuring kinesis firehose. 

### ISSUE THREAD

**Issue by Rattletech** [aws/aws-cli#4443]
After setting up AWS Kinesis, I tried to push the data to an S3 bucket through kinesis firehose stream. Here I have mentioned my details for your clear understanding.

**Kinesis data streams name: APP_STREAM
Kinesis Firehose delivery streams name: APP_DELIVERY_STREAM
S3 bucket name: APP-09-08-2019
Cognito role name: ### Cognito_APPdemoUnauth_Role**

**Scenario**

I have selected delivery stream source as "Direct PUT or other sources" there won't be any issues the device sending the data to S3 bucket.

Instead of Direct PUT or other sources, I have selected delivery stream source as Kinesis stream the device not sending data to s3 bucket and getting below error message.

**Error

Message: User: arn:aws:sts::XXXXXXXXX:assumed-role/Cognito_APPdemoUnauth_Role/ CognitoIdentityCredentials is not authorized to perform: firehose:PutRecordBatch on resource: arn:aws:firehose:us-east-1:XXXXXXXXXX:delivery streams/APP_DELIVERY_STREAM**

Here I'm using aws "root" user account.

**Cognito_APPdemoUnauth_Role role permission policy:**

```
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": [
"mobileanalytics:PutEvents",
"cognito-sync:*"
],
"Resource": "*"
},
{
"Sid": "",
"Effect": "Allow",
"Action": [
"sts:*"
],
"Resource": [
"*"
]
},
{
"Effect": "Allow",
"Action": "kinesis:*",
"Resource": "arn:aws:kinesis:us-east-1:76536XXXXX:stream/APP_STREAM"
},
{
"Effect": "Allow",
"Action": "firehose:*",
"Resource": "arn:aws:firehose:us-east-1:76536XXXXX:deliverystream/APP_DELIVERY_STREAM"
},
{
"Effect": "Allow",
"Action": [
"sts:AssumeRole"
],
"Resource": [
"arn:aws:iam::76536XXXXX:role/Cognito_APPdemoUnauth_Role"
]
},
{
"Sid": "",
"Effect": "Allow",
"Action": [
"s3:Get*",
"s3:List*",
"s3:Put*"
],
"Resource": [
"arn:aws:s3:::APP-09-08-2019/*"
]
}
]
}
```

**Cognito_APPdemoUnauth_Role TrustRelationship:**

```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Federated": "cognito-identity.amazonaws.com"
},
"Action": "sts:AssumeRoleWithWebIdentity",
"Condition": {
"StringEquals": {
"cognito-identity.amazonaws.com:aud": "us-east-1:6ff39f7d-33d3-4eb4-98fa-5c76330ffc3a"
},
"ForAnyValue:StringLike": {
"cognito-identity.amazonaws.com:amr": "unauthenticated"
}
}
},
{
"Effect": "Allow",
"Principal": {
"AWS": [
"arn:aws:iam::76536XXXXX:root",
"arn:aws:iam::76536XXXXX:role/Cognito_APPdemoUnauth_Role"
]
},
"Action": "sts:AssumeRole",
"Condition": {
"StringEquals": {
"sts:ExternalId": "76536XXXXX"
}
}
}
]
}
```
Can anyone please help me to resolve this issue?

**Comment by kyleknap** [comment]
As stated in our [README](https://github.com/aws/aws-cli#getting-help), we try to reserve GitHub issues for issues directly for the CLI. I would recommend reaching out to AWS Support to figure out why your IAM permissions are not working. They will be in a better position to help debug this.
