### ISSUE TITLE
register-task-definition requires 'memory' or 'memoryReservation' to be set for Fargate Task Definitions.

### ISSUE THREAD

**Issue by edwinwilson** [aws/aws-cli#4453]
We should be able to update the container for an existing Fargate compatible Task Definition without setting memory' or 'memoryReservation' in 'container-defninitions' via aws-cli.

aws ecs register-task-definition --family [...] --container-definitions [..]

An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Invalid setting for container 'xxxx'. At least one of 'memory' or 'memoryReservation' must be specified.

**Comment by joguSD** [comment]
Required parameters are handled by the service team for the particular API. This is not something we can fix within this repository. I would suggest raising your concerns to the service team through those support channels such as [AWS Support](https://console.aws.amazon.com/support/home#/)

**Comment by gnieutin** [comment]
@edwinwilson I had the same problem, if you don't want to set memory at container level, you must at least set it at task level: 
`aws ecs register-task-definition --family [...] --container-definitions [..] --memory 2048`
