### ISSUE TITLE
MFA code is not echoed

### ISSUE THREAD

**Issue by xehpuk** [aws/aws-cli#4461]
When asked for my MFA code, the CLI prevents me from seeing what I'm typing. I can't paste it either.

**Comment by kyleknap** [comment]
This is done on purpose. Under the hood, we are using Python's [getpass](https://docs.python.org/2/library/getpass.html) function which is the recommend way to securely get passwords from terminal. And as part of securely retrieving the password it will not echo the password back. That being said I do not feel comfortable changing the default to show the MFA code as some users actually don't want the MFA code echoed.

**Comment by xehpuk** [comment]
It's a TOTP and therefore doesn't need to be hidden. The login to the AWS console doesn't hide it either. Have those user never used the console?

**Comment by jamesls** [comment]
I agree with Kyle here, unless this is causing issues for people.  I'd prefer not to change it.
I've also confirmed that you can paste your MFA code (tested on mac/linux).
