### ISSUE TITLE
Dynamodb scan unable to handle tables larger than the ram of the local machine

### ISSUE THREAD

**Issue by temotodochi** [aws/aws-cli#4466]
aws dynamodb cli tools when performing filtering scanning try to download the whole table to local ram before filtering and outputting. Confirmed by AWS support. 

It should begin downloading and apply filter to each incoming item, discarding those which are not relevant and free up ram as it goes. 

This is particularly crippling on dynamodb tables with sizes over several terabytes. In my case the table i had to misuse and scan in an emergency to find misplaced data is over 3 terabytes with 4,6 billion items. That's just two months worth of data.

**Comment by kyleknap** [comment]
Can you provide the exact command you are running? If you are using `--filter`, it is doing client side filtering. It is likely you will want to use the `--filter-expression` which is a server side filter.
