### ISSUE TITLE
aws backup cli start-restore-job not working for EFS

### ISSUE THREAD

**Issue by manikjain** [aws/aws-cli#4467]
Hello,

I'm trying to create a restore point for an EFS backup from an existing recovery point to a new EFS file system using the following command:

```
$aws backup start-restore-job --recovery-point-arn arn:aws:backup:us-east-1:1234:recovery-point:xxxxx --metadata file-system-id=fs-xxxxx,Encrypted=false,PerformanceMode=generalPurpose,newFileSystem=true --iam-role-arn arn:aws:iam::1234/service-role/AWSBackupDefaultServiceRole --resource-type EFS
{
    "RestoreJobId": "xxxxxxxx"
}
```

The command above does create a restore job but that job fails after some time and doesn't proceed to create a new EFS file system. If I create a restore point using the console, it works fine.

I've tried working with boto3 as well to achieve this but noticing the same behaviour with that.

Here's what's passed to the API when I perform the same operation from the console:
```
contentString: "{"RecoveryPointArn":"arn:aws:backup:us-east-1:1234:recovery-point:xxxxxxxx","Metadata":{"aws:backup:request-id":"xxxxxx","file-system-id":"fs-xxxx","Encrypted":"false","PerformanceMode":"generalPurpose","CreationToken":"console-xxxx","newFileSystem":"true"},"IamRoleArn":"arn:aws:iam::1234:role/service-role/AWSBackupDefaultServiceRole","ResourceType":"EFS","IdempotencyToken":"xxxxxx"}"
```

Am I missing something or is this an issue with the API itself?

**Comment by jamesls** [comment]
If this isn't working in both the AWS CLI and boto3 it might be an issue with the API itself.  For those types of questions, the service team (Backup in this case) would be able to better help.  I'd suggest asking this question over in the AWS Backup forums: https://forums.aws.amazon.com/forum.jspa?forumID=324&start=0

**Comment by ManikJainOps** [comment]
Thanks for your response and sorry for responding late. It needed a `creationToken` in order for it to create a new file system. After I added a `creationToken` to the request, a new file system got created.
