### ISSUE TITLE
S3 PutBucketMetricsConfiguration Malformed XML

### ISSUE THREAD

**Issue by elefant90** [aws/aws-cli#4476]
I want to add metrics configuration over a bash or python script, but cli and boto3 all get me the same error.  Also added the filter manually and than read it over aws s3api get-bucket-metrics-configuration and the syntax is the same.

` aws s3api put-bucket-metrics-configuration --bucket "example-bucket-with-enabled-apid-metrics" --id "myid2" --metrics-configuration '{"Id":"avc", "Filter":{"Prefix":"testing/path=test1"}}' --debug`

> 2019-09-10 07:32:02,026 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/root/test/env/lib64/python3.6/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/root/test/env/lib64/python3.6/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/root/test/env/lib64/python3.6/site-packages/awscli/clidriver.py", line 530, in __call__
    call_parameters, parsed_globals)
  File "/root/test/env/lib64/python3.6/site-packages/awscli/clidriver.py", line 650, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/root/test/env/lib64/python3.6/site-packages/awscli/clidriver.py", line 662, in _make_client_call
    **parameters)
  File "/root/test/env/lib64/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/test/env/lib64/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the PutBucketMetricsConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema
2019-09-10 07:32:02,029 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

> An error occurred (MalformedXML) when calling the PutBucketMetricsConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema

**Comment by jamesls** [comment]
Interesting, I can confirm this:


```
$ aws s3api put-bucket-metrics-configuration --bucket "fgasdfadfhsdfgsa" --id "myid2" --metrics-configuration '{"Id":"avc", "Filter":{"Prefix":"testing/path=test1"}}' --debug

...
ClientError: An error occurred (MalformedXML) when calling the PutBucketMetricsConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema

# Serialized as XML (from the debug logs):

<?xml version="1.0"?>
<MetricsConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Id>avc</Id>
  <Filter>
    <Prefix>testing/path=test1</Prefix>
  </Filter>
</MetricsConfiguration>

```

If I create this in the console and then call `get-bucket-metrics-configuration` I see the raw xml coming back as:

```
$ aws s3api get-bucket-metrics-configuration --bucket fgasdfadfhsdfgsa --id TestFoo --debug
...
<?xml version="1.0" encoding="UTF-8"?>
<MetricsConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Id>TestFoo</Id>
  <Filter>
    <Prefix>testing/path=test1</Prefix>
  </Filter>
</MetricsConfiguration>
```

I'll follow up internally and see if I can get an answer to what's going on here.  Thanks for reporting.

**Comment by nuclearpidgeon** [comment]
duplicate of #2355 (just commenting to link the issues)
