### ISSUE TITLE
Feature Request: Allow exporting session credentials when assuming a role

### ISSUE THREAD

**Issue by timoguin** [aws/aws-cli#4479]
It would be nice it we could pass a flag to the `aws sts assume-role*` commands that would export the returned session credentials. This would be similar to the `ecr get-login` command that can be evaled to authenticate via the Docker CLI. It would remove the need to manually process the returned JSON.

Perhaps a flag like `--export` or `--export-credentials` would be good.

**Comment by jameswilsongrant** [comment]
Seconded this for use with required MFA.

If you turn on the policies listed here https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage.html you can use STS to punch in an arn/otp code and get back a key/secret/token but there's no easy way to export the ENV variables or populate a profile in ~/.aws/credentials.

We wrote a tool that does this for us but to me it should really be a feature of awscli.

**Comment by joguSD** [comment]
@timoguin While I'm not entirely against this type of feature, printing commands that can be eval'd has in general been a painpoint for us. It can be difficult to ensure the commands printed out will actually work in all cases (platform/shell differences, etc).

As a question, is there a particular reason you wouldn't want to configure this as a CLI profile?
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-mfa

**Comment by jameswilsongrant** [comment]
So I wasn’t aware of that feature, however it appears to require the user
to MFA every time.

I don’t want that, our users don’t want that, it’s a crap user experience.
I want them to have to do it once a day and then move on with their lives.
