### ISSUE TITLE
aws sync command is slow with multiple --exclude args 

### ISSUE THREAD

**Issue by clydebailey** [aws/aws-cli#4486]
This is what I am trying to do:
1. I download json files from an s3 prefix onto my server and use the data to populate a postgres db.
2. After the db populating is done, I delete the json files but maintain a file for indexing the files downloaded.
3. A cron job picks up the last downloaded files and uses the aws sync command with an --exclude argument to download only updated files. This means that I have an exclude arg for every file and I have 1000's of files.  
4. Aws cli sync works fine when I have a few exclude args, but my current command has many args which is hanging the system.
5. I am using an ec2 instance with 8gb mem
6. `aws s3 sync s3://bucket/TestOrg/TestPlace/2019-09-06/1560256729683-Cam1/    /data/s3_dashboard/download_projects/sync/clydebew/TestPlace/2019-09-06/1560256729683-Cam1/ --exclude "*.jpg"  --exclude "filename1.json" --exclude "filename2.json" .....`

Is there a limit on the exclude parameters? Any hack around this?

**Comment by jamesls** [comment]
There's no limit on exclude parameters.  There is a limit to how long a command can be, but that's a limitation of your OS:

```
$ getconf ARG_MAX
262144
```

There shouldn't be a huge degradation in performance with multiple exclude filters.  How much slower are you seeing `s3 sync` run with one vs. many exclude filters?

Your use case is fairly custom compared to what the high level s3 commands provide.  It might be worth using an AWS SDK to do this for you (e.g boto3).
