### ISSUE TITLE
put-dashboard brakes "log" widget source

### ISSUE THREAD

**Issue by skycremaschinin** [aws/aws-cli#4487]
Hi, 
using -put-dashboard command with console "view source" extracted json as --dashboard-body parameter value, "log" widget can't find source anymore. 
it's because json should be like this:
{"query":"SOURCE **'/**/my/log/source**'** | fields @timestamp\n| sort @timestamp desc\n ...

but is applied without single quote around source value
{"query":"SOURCE /my/log/source | fields @timestamp\n| sort @timestamp desc\n ...

**Comment by jamesls** [comment]
You'd need to escape the single quote, e.g `\'`.  This is an issue with your shell/bash stripping the characters before giving them to the CLI.
