### ISSUE TITLE
UpdateRolesWithIDPFunctionOutputs does not exist

### ISSUE THREAD

**Issue by AbirAbbas** [aws/aws-cli#4488]
I was cleaning up my AWS resources and I may have deleted something that is necessary for amplify, how do I go about reinitialize this specific function?

UPDATE_FAILED UpdateRolesWithIDPFunctionOutputs Custom::LambdaCallout Wed Sep 11 2019 13:57:08 GMT-0400 (Eastern Daylight Time) Template error: Function deliveryapp-dev-201908192-UpdateRolesWithIDPFuncti-1NEYMNMTD30CG doesn't exist

Reason: Template error: Function deliveryapp-dev-201908192-UpdateRolesWithIDPFuncti-1NEYMNMTD30CG doesn't exist

**Comment by jamesls** [comment]
You'd need to redeploy your lambda function the same way you initially deployed i.  This sounds like this might be a better question for the amplify team as it's not really related to the AWS CLI (unless you used the AWS CLI to initially create the lambda function).
