### ISSUE TITLE
Recent update broke tagging

### ISSUE THREAD

**Issue by Cyberax** [aws/aws-cli#4494]
Hi!

The recent AWS CLI update has broken tagging. Example command line:
`aws ecs tag-resource --resource-arn  arn:aws:ecs:us-east-1:123491197399:task/ApolloAlpha/5ea3f06df19d4e62ab2883994bcb1fdf --tags Key=MachineId,Value=mi-0644d95daf97ca45b`

Result is:
```
Parameter validation failed:
Unknown parameter in tags[0]: "Key", must be one of: key, value
Unknown parameter in tags[0]: "Value", must be one of: key, value
```
Using downcase values fixes this, but then it doesn't work on older versions of the CLI.

**Comment by Cyberax** [comment]
Sorry for the noise, the error is on my side.

**Comment by hemshankar** [comment]
what is the fix
