### ISSUE TITLE
CloudFormation Package Doesn't Zip Lambda Prerequisites For SAM Template

### ISSUE THREAD

**Issue by ckabalan** [aws/aws-cli#4497]
My SAM project has some prequisites which are maintained in a `requirements.txt`. `sam build` properly installs these to the `./.aws-sam/build/Lambda-Name` directory. When I attempt to package with `aws cloudformation package` the zip is successfully created and uploaded but contains no prerequisites.

Trying the same sequence with `sam package` exhibits the same missing-prereq behavior when using the `--template-file template.yaml` parameter, but does properly package prereqs when omiting the `--template-file` parameter. This is the workaround I'm temporarily using. The `--template-file` parameter is required for `aws cloudformation package` so I don't believe there to be a workaround with the native AWS CLI.

See my reproduction below. Unfortunately there is too much sensitive information using `--debug` to provide that for the numerous commands run. If providing debug output for a specific command is useful let me know and I can reproduce that. Note that the sequence below should be exactly reproducable since it checks out a specific commit id. Changing the S3 bucket name should be all that is required.

https://gist.github.com/ckabalan/84197739d839ff6c6cb42520331f717a

Apologies for the Gist, the GitHub markup was messing with the output formatting.

**Comment by jamesls** [comment]
In your template you specify the codeuri that contains the directory we should zip up and send to lambda.  I suspect you're pointing to your application code.  I'm not exactly sure what sam package is doing for you, but based on your debug output you'd need to point your code uri at `.aws-sam/build/CreateSecret`.
