### ISSUE TITLE
aws apigateway import-rest-api

### ISSUE THREAD

**Issue by Imagine-Jason** [aws/aws-cli#4511]
Firstly,I Read the documentation about aws cli apigateway import-rest-api ;
https://docs.aws.amazon.com/zh_cn/cli/latest/reference/apigateway/import-rest-api.html

When I Use the command like this:

aws apigateway import-rest-api  --body  'file://swagger.json' --parameters endpointConfigurationTypes=REGIONAL --region cn-north-1

It's Worked in Mac,But not Working in Windows;
So I Tried the parameter of "body" without "'" ,like this:

aws apigateway import-rest-api  --body  file://swagger.json --parameters endpointConfigurationTypes=REGIONAL --region cn-north-1

It's Also Worked in Window  and Mac.

Document seems to have some errors or cli problems?

**Comment by joguSD** [comment]
Not all of the examples in the CLI documentation works across all shells. Typically they're formated for *nix style shells, and occasionally there's a callout for a windows specific command.

In this case, the quoting rules for CMD/Powershell are different than say bash which is likely causing this discrepancy.
