### ISSUE TITLE
CloudFormation CLI parameters with space parsing.

### ISSUE THREAD

**Issue by kbyunAncile** [aws/aws-cli#4521]
I am trying to pass pass parameter with space to aws cloudformation create-stack aws cli.
The issue is that my parameter has space. I am using powershell for scripting.
Below is example of my parameter
```
 $JsonParameter = '[{"ParameterKey":"name","ParameterValue":"John"},{"ParameterKey":"Occupation","ParameterValue":"Test Engineer"}]'| ConvertTo-Json

aws cloudformation create-stack --stack-name "$stackName" --template-url "$templateUrl" --capabilities "$capabilityList" --parameters "$JsonParameter " --region "us-east-1"
```

It errors out because of space in ParameterValue
```
Error parsing parameter '--parameters': Invalid JSON:
[{"ParameterKey":"name","ParameterValue":"John"},{"ParameterKey":"Occupation","ParameterValue":"Test
```

I tried to escape the space with other characters but that doesn't really fix the issue.
Also tried to put single/double quot around the parameter value but same issue

The parameter's value is used for S3 key and the directory has space in it.

**Comment by joguSD** [comment]
Because you're using powershell I think you're going to have to quote the JSON body and then escape all of the double quotes.

Alternatively you could use the shorthand syntax and do something like:
```
ParameterKey=Occupation,ParameterValue='Test Engineer',...
```
