### ISSUE TITLE
s3 cp/sync bucket sub-folder, download error. Windows Federated Access.

### ISSUE THREAD

**Issue by Sir-HC** [aws/aws-cli#4527]
Environment: Windows 10
Issue on cmd and powershell
Using Federated AWS Access

when using s3 cp without specifying a output filename, cp --recursive, or sync command, files returned contain a hash/signature tacked on at the end (ie */test.csv returns as */test.csv.b49Ca03) which results in a [Errno 22] Invalid Argument, which I can only guess that the OS doesn't like the mismatch or invalid extension?

Following are commands used:
```
aws s3 cp s3://<bucketname>/tmp/test.csv .
aws s3 cp s3://<bucketname>/tmp/ . --recursive
aws s3 cp s3://<bucketname>/tmp/ C:/Dev/test/ --recursive
aws s3 sync s3://<bucketname>/tmp/ .
```

Returned error(s):
`download failed: s3://<bucketname>/tmp/test.csv to .\test.csv [Errno 22] Invalid argument: 'c:\\Dev\\test\\test.csv.6CBa3926'`

Also used absolute path name, attempted to utilize quotes with the same result. 

The added hash/signature extension changes each attempt to cp/sync.

Using s3 cp command that specifies the output file name, it downloads the file normally:
`aws s3 cp s3://<bucketname>/tmp/test.csv ./test.csv`
Result:
`download: s3//<bucketname>/tmp/test.csv to .\test.csv`

Found on SO, but only resolution was to use linux os, I don't have that option. https://stackoverflow.com/questions/57786113/errno-22-when-downloading-multiple-files-from-s3-bucket-sub-folder

**Comment by joguSD** [comment]
My hunch is that this is a similar issue to: https://github.com/aws/aws-cli/issues/4543

Could you provide debug logs for both the cp and sync command by adding `--debug`?

**Comment by Sir-HC** [comment]
Correct, I did have ":" in the file name. I'll correct and see if that fixes everything.

**Comment by Sir-HC** [comment]
Yup, everything is working now, was just the invalid characters <>:"/\|?*

**Comment by majiang** [comment]
Is there a way to recursively download by for example replacing invalid characters?  Do I have to rename one by one manually before downloading?

**Comment by potyt** [comment]
Is there really no automated way to substitute characters here? Seems a bit mad there's no option to do that with the cli command....
