### ISSUE TITLE
Ability to output S3 synced files

### ISSUE THREAD

**Issue by daveisfera** [aws/aws-cli#4535]
Currently, when running `aws s3 sync` it will output when it does something, but it would be nice to have an option like `--synced` or `--verbose` that would output all of the synced files.

**Comment by joguSD** [comment]
Could you clarify what you're looking for? 
Currently when the sync command takes an action it will print out something like:
```
download: s3://bucket/key to ./key  
```
For every key/file that it syncs, which sounds more or less like what you're describing.

**Comment by daveisfera** [comment]
If you run the same command a second time, then it will output nothing because nothing is downloaded. I'm asking for a flag that will output the files that are already synced where no action was taken.

**Comment by joguSD** [comment]
Gotcha, I could see how that would be useful. Marking this as an enhancement.

**Comment by domandinho** [comment]
PR: https://github.com/aws/aws-cli/pull/4669
