### ISSUE TITLE
ELBv2 should have the option to return all load balancers

### ISSUE THREAD

**Issue by darrenoc3** [aws/aws-cli#4537]
Its absurd that you need to query both ELB and ELBv2 endpoints (with different response types) to get all load balancers. It would be nice to have a wrapper that can return all ELBs

**Comment by joguSD** [comment]
I could see how this is annoying. My hunch is that this kind of customization/wrapper will be hard to pull off in a manner that doesn't constantly need to be updated as both the input and output to the two operations is different. 

In terms of output what would you expect?
