### ISSUE TITLE
Add ElasticSearch snapshot commands

### ISSUE THREAD

**Issue by aries1980** [aws/aws-cli#4538]
I was looking for commands to:

* Register a snapshot repository
* Take a manual snapshot
* Restore a manual snapshot

via the AWS CLI, but I didn't find it. I implemented in a Python script, I volunteer to create a PR for aws-cli with these features, just let me know if you think it is a good idea or there is an other way around it.

**Comment by joguSD** [comment]
Just to make sure I'm clear as I'm not very knowledgeable on ElasticSearch, these commands would be talking to the ElasticSearch cluster that AWS ElasticSearch hosts for you? If that is the case, I'm thinking it's probably out of scope for the AWS CLI.

Is something like [curator](https://github.com/elastic/curator) what you're looking for?

**Comment by aries1980** [comment]
I m not familiar with Curator, but the [AWS' Working with Amazon Elasticsearch Service Index Snapshots](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html) only mentions the SDK if I want to register a snapshot repository. According to this doc

> You must register a snapshot repository with Amazon Elasticsearch Service before you can take manual index snapshots.

I neither see the details of a [snapshot repo registration action](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/actions.html) nor as the [option of the snapshot action](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/option_repository.html). Boto3 can register a snapshot repo with S3 backend, utilising the [repository-s3](https://www.elastic.co/guide/en/elasticsearch/plugins/7.1/repository-s3.html) plugin, but I fail to find in Curator how to register such repo.

**Comment by joguSD** [comment]
@aries1980 Looks like that example is only using the Python SDK to resolve credentials. That being said, the example does also makes me wonder if there's a better approach. That being said, I definitely think these snapshot management calls are out of scope for the CLI.

Unfortunately, I don't think we'll be of much more help here. Perhaps poking around the curator repo for more help on a tool that can register / manage elasticsearch snapshots.
