### ISSUE TITLE
dynamodb create-table requires --provisioned-throughput with --billing-mode set to PAY_PER_REQUEST

### ISSUE THREAD

**Issue by JTunis** [aws/aws-cli#4540]
AWS CLI Version: 1.16.20

When trying to create a DynamoDB table with `--billing-mode PAY_PER_REQUEST`, I get an error saying `--provisioned-throughput` is required.

Input: 
```
aws dynamodb create-table \
         --region "${REGION}" \
         --table-name ${NAME} \
         --attribute-definitions AttributeName=rowID,AttributeType=S \
         --key-schema AttributeName=rowID,KeyType=HASH \
         --billing-mode PAY_PER_REQUEST \
         --sse-specification "{ \"Enabled\": true }"
```
Output:
```aws: error: argument --provisioned-throughput is required```

However, in the documentation [here](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/create-table.html) we see:

> If you set BillingMode as PROVISIONED , you must specify this property. If you set BillingMode as PAY_PER_REQUEST , you cannot specify this property.

I thought I'd entertain the error anyway by trying to set Read and Write capacity to zero, but got an error for invalid Read and Write capacity:

Input:
```
aws dynamodb create-table \
         --region "${REGION}" \
         --table-name ${NAME} \
         --attribute-definitions AttributeName=rowID,AttributeType=S \
         --key-schema AttributeName=rowID,KeyType=HASH \
         --provisioned-throughput ReadCapacityUnits=0,WriteCapacityUnits=0 \
         --sse-specification "{ \"Enabled\": true }"
```

Output:
```Unknown options: --billing-mode, PAY_PER_REQUEST```

I upgraded the CLI to this version hoping it would fix the problem, but before the upgrade I also got this error when setting `--provisioned-throughput`:
```error occured (ValidationException) when calling the CreateTable operation: One or more parameter values were invalid: Neither ReadCapacityUnits not WriteCapacityUnits can be specified when BillingMode is PAY_PER_REQUEST```

So I'm stumped as to how to create a table without provisioned throughput.

**Comment by sayboras** [comment]
Upgrading your aws cli version will work, I have quickly tried with mine.

```
aws --version
aws-cli/1.16.225 Python/3.7.4 Darwin/18.7.0 botocore/1.12.215

aws dynamodb create-table \
         --region "${REGION}" \
         --table-name ${NAME} \
         --attribute-definitions AttributeName=rowID,AttributeType=S \
         --key-schema AttributeName=rowID,KeyType=HASH \
         --billing-mode PAY_PER_REQUEST \
         --sse-specification "{ \"Enabled\": true }"
{
    "TableDescription": {
        "AttributeDefinitions": [
            {
                "AttributeName": "rowID",
                "AttributeType": "S"
            }
        ],
        "TableName": "testing-table",
        "KeySchema": [
            {
                "AttributeName": "rowID",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "CREATING",
        "CreationDateTime": 1569678047.415,
        "ProvisionedThroughput": {
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 0,
            "WriteCapacityUnits": 0
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableId": "93552d9a-2b61-496c-b2e4-b7113d3ad63d",
        "BillingModeSummary": {
            "BillingMode": "PAY_PER_REQUEST"
        },
        "SSEDescription": {
            "Status": "ENABLED",
            "SSEType": "KMS",
            ...
        }
    }
}
```

**Comment by joguSD** [comment]
As @sayboras mentioned updating your AWS CLI version should work as this parameter is no longer marked as required.
