### ISSUE TITLE
download failed | aws s3 cp 

### ISSUE THREAD

**Issue by palmtown** [aws/aws-cli#4543]
Hello,

There is a bug in aws-cli whereby when files are copied using the below command, files with particular names are generating an error and are not being downloaded, although, several other files download just fine.

I am able to reproduce the error every time and paste the log below with the --debug switch on.  Note that I am using: aws-cli/1.16.248 Python/3.7.4 Windows/10 botocore/1.12.238 in which the problem occurs.  However, note that it does not happen on a Linux server with version: aws-cli/1.16.248 Python/3.7.4 Windows/10 botocore/1.12.238

**Command**
`aws s3 cp s3://my-bucket/myfolder "C:\tmp\test" --recursive`

**Error**
`{ Error: Command failed: aws s3 cp s3://my-bucket/myfolder "C:\tmp\test" --recursive -
-only-show-errors --ignore-glacier-warnings
download failed: s3://my-bucket/myfolder/2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:
0:0.mp3 to ..\..\..\..\tmp\test\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3 [Errno 22] Invalid argument: 'C:\\t
mp\\test\\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3.c1fEfE2C'`

**Comment by h3ct0rjs** [comment]
Hi @palmtown it seems like the argument is invalid. I will try to reproduce this behavior and will confirm if I experiment the same.

**Comment by palmtown** [comment]
Hello @h3ct0rjs , note that I am merely performing a recursive s3 copy and I am not manually passing the filenames, s3 itself is getting all the filenames and performing the individual s3 copy.

**Comment by joguSD** [comment]
@palmtown It's hard to tell but it looks like there might be a space character in some of the key names? I'm curious if that's causing issues when being run on Windows. If possible, could you provide debug logs by adding `--debug`, removing any sensitive information from them?

**Comment by palmtown** [comment]
Hello @joguSD 

Please note that there are no spaces in the key name.  Th key is "2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3" 

`2019-10-01 20:11:19,233 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - Exception raised.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\download.py", line 573, in _main
    fileobj.seek(offset)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\utils.py", line 361, in seek
    self._open_if_needed()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\utils.py", line 344, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\s3transfer\utils.py", line 259, in open
    return open(filename, mode)
OSError: [Errno 22] Invalid argument: 'C:\\tmp\\test\\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3.0FD68d96'
2019-10-01 20:11:19,233 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': 'C:\\tmp\\test\\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3'}) about to wait for the fo
llowing futures []
2019-10-01 20:11:19,233 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': 'C:\\tmp\\test\\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3'}) done waiting for depende
nt futures
2019-10-01 20:11:19,233 - ThreadPoolExecutor-0_0 - s3transfer.utils - DEBUG - Releasing acquire 0/None
download failed: s3://files-circuitid-com/tmp/test/2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3 to ..\..\tmp\test\2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3 [Errno 22] Invalid argument: 'C:\\tmp\\test\\2701d
9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3.0FD68d96'
2019-10-01 20:11:19,233 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.`

**Comment by joguSD** [comment]
The following characters are reserved on NTFS file systems (almost certainly what your windows machine is using): `<>:"/\|?*`. Unfortunately, I don't think there's anything we can do on the CLI side of things to solve this.

**Comment by palmtown** [comment]
Hello @joguSD 
Yes, you are correct, I just tried renaming a filename to 2701d9068e6699be91be775bdd6b9045@0:0:0:0:0:0:0:0.mp3 and it gave me an error.  What it did was simply remove the characters from the filename.  Are you able to do the same with s3, simply remove the characters from the filename so that it doesn't download the file?

**Comment by joguSD** [comment]
@palmtown No, I don't think stripping characters like that is a solution for us. First it would require knowledge of what filesystem, host OS, etc we're on to even be able to determine the list of 'invalid' characters. Even if we could know that it could lead to conflicts as two keys might end up mapping to the same stripped value (for example: `00:0` and `0:00` would both end up as `000`).

**Comment by h3ct0rjs** [comment]
@joguSD I was checking the #4527  is the same problem ?

**Comment by h3ct0rjs** [comment]
So in other words  What was the right solution to this problem ?

**Comment by MeaningOfLights** [comment]
> So in other words What was the right solution to this problem ?

I posted a workaround here: https://stackoverflow.com/a/58576473/495455

Probably better to get AWS to change their file names not to use reserved windows charts, but since that isn't likely to happen we could do a powershell wrapper as a solution.

**Comment by h3ct0rjs** [comment]
it seems okay to me @MeaningOfLights I guess this is a temporal solution. Thanks
