### ISSUE TITLE
`aws s3 sync` command copies all files instead of just updated files

### ISSUE THREAD

**Issue by tomhrtly** [aws/aws-cli#4558]
Verison: aws-cli/1.16.251 Python/3.7.4 Linux/4.19.23-coreos-r1 botocore/1.12.241

I'm using the awscli package for GitLab CI/CD for my project. In my `deploy` job, I install the latest version of Python and install awscli using pip: `pip install awscli`.

After the package has successfully installed, I run the following command to sync the repository with my S3 bucket:

```
aws s3 sync htdocs s3://$S3_BUCKET_NAME
```

However, when this command is ran, regardless of whether there have been any file changes or just a few, the command will copy all files within the `htdocs` directory into my S3 bucket which takes almost 6 minutes.

When I run the same command on my local computer, I don't have a problem but when I run use it with GitLab CI/CD in a Docker container, it copies all of the files over instead of just the updated ones.

I'm unsure whether this is a bug with the awscli or a problem with GitLab CI/CD, I've opened the issue here because GitLab says CI/CD is out of the scope of their support.

Is this a problem with awscli or GitLab? Any help is appreciated.

**Comment by wtobi** [comment]
It seems to work now. I guess it was a problem with the awscli version.

I use `image: python:latest` and 
```
script:
    - pip install awscli
```

**Comment by wtobi** [comment]
Now it stopped working for me again, without any change to the CI/CD pipeline.

**Comment by tomhrtly** [comment]
I believe it's because during the CD process, the Git repo is cloned and therefore all the files are "new" even though one file may have been updated within the latest commit.

Does anyone know a way that this can be avoided so that AWS only recognises the actual updated file instead of the whole repo?

**Comment by martg0** [comment]
Hi guys, I've stumbled upon the same issue here. Any workaround to avoid uploading everything on each CI/CD trigger?

**Comment by shaoye** [comment]
I use the `--size-only` option to ignore file createtime changes

```
aws s3 sync local s3://remote --size-only
```

**Comment by 1d9akash** [comment]
@tomhrtly Did You Got The Solution For It?
