### ISSUE TITLE
(ExpiredToken) when calling the UploadPart

### ISSUE THREAD

**Issue by trevrobwhite** [aws/aws-cli#4562]
Our corporate policy only allows for an authentication session to last for 60 minutes, however we do have a script which will automatically authenticate every 55 minutes.

The problem is when uploading a large file using aws s3 cp the cli sees the session has ended and quits with (ExpiredToken) when calling the UploadPart, even though there are new session details in the credentials file.

Can the aws cli please check for updated credentials before failing with the above error.

Issue is on Windows 10 if it makes a difference, I realise the files can be uploaded in several chucks but to be honest it's really hard work to get a 150G file transferred manually especially on Windows where you need several tools to split, MD5 etc the file (and also double the disk space as you need to store the original and split file)

**Comment by joguSD** [comment]
How are you sourcing / providing the credentials? A lot of the credential providers built into the CLI can automatically refresh your credentials before they expire (an assume role profile, etc). If you're manually providing the explicit access key and secret key there's not much we can do to help as we have no way to refresh them for you.
