### ISSUE TITLE
Instance profile ignored when credentials file is present

### ISSUE THREAD

**Issue by esigoillot** [aws/aws-cli#4576]
Hi!

We have an EC2 instance with both a profile instance and specific credentials configured in the `~/.aws/credentials` file.
Old resources are still accessed through access keys, and we would like to use the instance profile to reach new resources.

Currently, it is not possible for AWS CLI to make use of the instance profile when a credentials file is present. The profiles and keys in the credential files will be used, and the instance profile will be ignored. Should the credentials file be missing, then the instance profile will be correctly taken into account and be used by AWS CLI.

There is no way in AWS CLI options to force it to use the instance profile. The _botocore_ library is checking credential providers in a specific order, and the instance profile provider is always checked last.

It could be a good idea to add a `--instance-profile` switch to force use of instance profile and ignore the credentials file.
For now, we have to call the meta-data endpoint, get the right profile name and associated credentials and populate environment variables before calling AWS CLI. Quite a burden :)

**Comment by thenets** [comment]
I have the same problem. I don't know why.

**Comment by justrp** [comment]
as of now this might be resolved by setting `AWS_SHARED_CREDENTIALS_FILE` env var to something that does not exist:

* default profile (from ~/.aws/config)
```
$ aws sts get-caller-identity
{
    "UserId": "...",
    "Account": "<my id>",
    "Arn": "arn:aws:iam::<my id>:user/alex"
}
```

* instance profile
```
$ AWS_SHARED_CREDENTIALS_FILE='' aws sts get-caller-identity
{
    "UserId": "...",
    "Account": "<my id>",
    "Arn": "arn:aws:sts::<my id>:assumed-role/blah/i-..."
}
```
