### ISSUE TITLE
S3 ls maximum 1000 objects with Snowball Edge

### ISSUE THREAD

**Issue by llamafilm** [aws/aws-cli#4579]
According to the documentation, **aws s3 ls** is limited to max 1000 objects per page.
```
$ aws s3 ls help
...
--page-size (integer) The number of results to return in each  response
       to  a  list operation. The default value is 1000 (the maximum allowed).
       Using a lower value may help if an operation times out.
```

I find this to be incorrect, since I can list buckets containing over 40000 objects and have never noticed a limit.
```
$ aws s3 ls s3://mybucket/ | wc
  42871  171484 2014937
```

However, when using a Snowball Edge, this limit of 1000 objects is enforced.  I would like to request removing the limit so the Snowball Edge works the same as a regular S3 bucket.  Or if not, we should at least update the documentation to explain the different behavior.

Example command:
```
$ aws --profile snowball --endpoint https://192.168.1.155:8443 s3 ls s3://snowball-bucket | wc
   1000    4000   47000
```

I'm using version 1.16.256.

**Comment by kdaily** [comment]
Hi @llamafilm,

The `--page-size` limit is per response. The list operation may require multiple responses, and `page-size` of these will be returned.

I'm not sure why a snowball endpoint would behave differently. Does this still occur with more recent versions of the AWS CLI?

**Comment by llamafilm** [comment]
I don't know; I no longer have a Snowball for testing.

**Comment by mc-meta** [comment]
Hello,

just to highlight that this seems to be happening in recent versions of the AWS CLI as well:

```
[root@xxx-xxxx ~]# aws s3 ls --recursive s3://xxxx-snowball2/xxxx/events/xxxx/year=2018/ --endpoint http://x.x.x.x:8080 --profile xxx|wc -l
1000
[root@xxx-xxxx ~]# aws --version
aws-cli/2.1.19 Python/3.7.3 Linux/3.10.0-1127.18.2.el7.x86_64 exe/x86_64.centos.7 prompt/off
```

This is a bit annoying since is preventing some quantitative cross verification on copied content.

We are planning to ship this snowball early/mid next week in case you want us to do any testing.

**Comment by gnieboer** [comment]
Can confirm this is occurring in most recent CLI v2.  This limit is NOT present in CLI v1 version 1.16.14 which we were using before attempting to upgrade to v2.

This prevents the discovery and handling of individual files that did not successfully transfer during a sync command (and for which also there is no log entry indicating failure... they show uploading but no error report and the file is not present on the device).  While these are literally one in a million, we must have 100% of data migrated.

**Comment by kdaily** [comment]
@gnieboer, you're correct in that, sorry that I missed that in my initial response! I will pass along the feedback to the Snowball team that this is still causing issues for users.

**Comment by botkillern** [comment]
Hello Guys!

This still happen for me on aws-cli/2.4.7
The limit of objects returned by "s3 ls" is 1000

Is a little hard to copy huge volume of data to Snowball when you can't validate the size or integrity of the data.

**Comment by dorn-olive** [comment]
@botkillern use AWS CLI v1.16.14. The snowball's S3 APIs haven't been updated to use the latest aws cli version (just addressed this with an aws support engineer and snow family SME)

**Comment by botkillern** [comment]
> 

Thank's for your reply, but now I already send snowball back to AWS.
This issue was a problem for me when trying to run "AWS SYNC" 😢 

I'm writing a post about "Snowball tips" and your reply will be there ;)
