### ISSUE TITLE
how to filter ec2 instances with tags starts with some string?

### ISSUE THREAD

**Issue by xjtustt** [aws/aws-cli#4582]
I want to filter the ec2 instances that with the tag like "my-tag-*", that may be my-tag-a, my-tag-b, etc.
I found that the parameters of --filters can only be specified string, below cmd cannot work for me.
```
aws ec2 describe-instances \
    --filters "Name=tag-key,Values=my-tag-*"
```

**Comment by kdaily** [comment]
Hi @xjtustt,

I think that you are missing a `.` in your regular expression to indicate 'any character'. See here:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html

Your command should be:

```
aws ec2 describe-instances \
    --filters "Name=tag-key,Values=my-tag-.*"
```
