### ISSUE TITLE
'We are having issues with colorma package with python 2.6 looking for <0.3.0'

### ISSUE THREAD

**Issue by mohsinaijaz** [aws/aws-cli#4583]
We are having issues with colorma package with python 2.6 looking for <0.3.0 adding greater than or equal to fixes this issue, could = be added. 
**Error:** 
```Could not find a version that satisfies the requirement colorama<0.3.9,>=0.2.5 (from awscli==1.16.257) (from versions: 0.3.9, 0.4.1) No matching distribution found for colorama<0.3.9,>=0.2.5 (from awscli==1.16.257)```

 Below two of the manual change fixed our issue temporary, can this be added in master?

**setup.cfg**
```colorama>=0.2.5,<=0.3.9; python_version=="2.6" or python_version=="3.3"```

**setup.py**
```install_requires.append('colorama>=0.2.5,<=0.3.9')```

**Comment by corybolar** [comment]
I have encountered the same issue.  The workaround seems to allow installation but long term it would be nice if this could be fixed.

**Comment by jamesls** [comment]
These issues should be resolved with https://github.com/aws/aws-cli/pull/4581, which was part of today's release (1.16.258).  Let me know if this is still failing on the latest CLI release.
