### ISSUE TITLE
describe-availability-zones returns wrong list

### ISSUE THREAD

**Issue by huseyinbabal** [aws/aws-cli#4594]
AWS SDK Version: `aws-cli/1.16.59 Python/2.7.16 Darwin/19.0.0 botocore/1.12.49`

When I execute `aws ec2 describe-availability-zones --region us-west-1`, it returns 

```
{
    "AvailabilityZones": [
        {
            "State": "available",
            "ZoneName": "us-west-1a",
            "Messages": [],
            "ZoneId": "usw1-az1",
            "RegionName": "us-west-1"
        },
        {
            "State": "available",
            "ZoneName": "us-west-1c",
            "Messages": [],
            "ZoneId": "usw1-az3",
            "RegionName": "us-west-1"
        }
    ]
}
```

However, in aws console it has `us-west-1a` and `us-west-1b`, not `us-west-1c`

<img width="865" alt="Screen Shot 2019-10-16 at 12 56 15" src="https://user-images.githubusercontent.com/1237982/66908800-5d7d0f80-f014-11e9-8876-b505442c1f57.png">

**Comment by kdaily** [comment]
Hi @huseyinbabal,

I'm not seeing this when do this. Can you confirm what you see using these instructions?

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#availability-zones-describe
