### ISSUE TITLE
bug:  --cli-input-json and command line parameters

### ISSUE THREAD

**Issue by mckraken** [aws/aws-cli#4595]
From PR #963, we have:
> --cli-input-json: This takes JSON (typically generated from --generate-cli-skeleton) from either a string or some file and uses that as the input to the command line operation. Additional arguments can be added to command line. If there are collisions between the two, the value from argument is used over the value from the input JSON

From my testing with `aws ssm start-automation-execution...` using the UpdateLinuxAMI document, the first level parameters (e.g. `DocumentName`) are kept, but if I put ANY `--parameters` on the command line (e.g. `SourceAmiId`), it overwrites ALL parameters in the passed JSON document.  

I would expect that I would be able to define default values for the needed parameters in the passed JSON document and override those default values passing in the `SourceAmiId` and `TargetAmiName` from the command line, but if I pass in any value on the command line, I have to pass in all values on the command line.

**Comment by bisdavid** [comment]
@mckraken,
Thanks for the feedback.  I'm sorry to say, but that is working as designed.  The "--parameters" value is actually a single parameter that takes a string (despite its ability to express several values in that string).  As the docs state, if you supply a parameter on the command line (even a compound one like "--parameters") then that overrides any "--parameters" string that you might have in the skeleton input file.

**Comment by mckraken** [comment]
@bisdavid Thank you for the response.  I was wondering if this was the case (only working one level deep on the overwrite/preserve for "collisions").  Can we put in a feature request to allow a second level working to allow specifying some values for compound parameters in the JSON and some on the command line?

**Comment by kdaily** [comment]
Hi @mckraken,

Sorry for the delay in getting back to this. I can understand what you're trying to do, but I think it adds more complexity than is necessary. This would be a kind of 'deep merge' that the client would have to manage. This would make order of precedence and debugging where specific parameter values came from very difficult.
