### ISSUE TITLE
Missing string substitution for --zip-file parameter in documentation for awscli update-function-code

### ISSUE THREAD

**Issue by copumpkin** [aws/aws-cli#4596]
Here's the code in question:

https://github.com/aws/aws-cli/blob/498ced29a46e2f1cddcb0edb9f5fe8f9fa754f56/awscli/customizations/awslambda.py#L27

And the text from [the doc page in question](https://docs.aws.amazon.com/cli/latest/reference/lambda/update-function-code.html):

> The path to the zip file of the {param_type} you are uploading. Example: fileb://{param_type}.zip

It seems like at some point someone intended to perform a splice but it got lost somewhere.

**Comment by kdaily** [comment]
Looks like this is the culprit:

https://github.com/aws/aws-cli/blob/develop/awscli/customizations/awslambda.py#L83

**Comment by kdaily** [comment]
That docstring is pulling double-duty. A new one needs to be created for use in the rendered documentation versus what is used for printing a better error message.

**Comment by kdaily** [comment]
Related PR: #1296
