### ISSUE TITLE
lambda get-policy function has inconsistent return value

### ISSUE THREAD

**Issue by scottgarcia11** [aws/aws-cli#4597]
aws version: `aws-cli/1.16.260`

All of the cli commands that I've used have return values that are structures/lists and allow for the use of the --query option to filter output as specified in the following documentation.

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html

The `lambda get-policy` method, however, returns its output as a String and makes it impossible to use --query in order to grab a specific field in the output, and one instead needs to pipe the output in order to replicate the typical --query behavior.

Minimum reproducible example:

`aws lambda get-policy --function-name lambda-function --output text --query Policy.Statement`

Returns `None`

**Comment by kdaily** [comment]
Hi @scottgarcia11,

I apologize for the delayed response. This change would require the Lambda service API to change their model from a string to a structure. I agree it would be much more useful to be able to parse the results using the familiar `--query` syntax, but there isn't anything that the AWS CLI can do. I will pass on your feedback to the Lambda team.

Of note, other resource based get operations also return strings of JSON back. For example:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ram/get-resource-policies.html

**Comment by LosAlamosAl** [comment]
For those landing here on search...

You may find this ugly, but the following will correctly format the string into readable JSON using `jq`. Don't think `--query` option on the CLI command will work though.

```sh
aws lambda get-policy --function-name fn | sed -e 's|\"{|{|g' | sed -e 's|}\"|}|g' | sed -e 's|\\"|"|g' | jq -r
```

@scottgarcia11
