### ISSUE TITLE
aws eks update-kubeconfig does not support `external_id`

### ISSUE THREAD

**Issue by benderillo** [aws/aws-cli#4598]
This is my second attempt to get this feature addressed in aws-cli.

Previous request was closed because there was no support for it in `aws-iam-authenticator`.
Now it seems the support was added per https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/228 

Original request, which is closed is here: https://github.com/aws/aws-cli/issues/4053 
It contains all the details.

Here is an excerpt:

>There is no way at the moment to specify external_id when calling aws eks update-kubeconfig.
>
>It supports specifying role-arn for the case when the cluster was created with assumed role.
However, if the role has an extra condition like: StringEquals | sts:ExternalId | test_account there is no way to supply aws eks update-kubeconfig this info.
>
>Basically, here is the use case:
>We use terraform with assumed role (that has external_id condition set) to bring up EKS cluster and worker nodes.
>
>In order to finish the setup, we need to do kubectl apply of the ConfigMap with AWS Auth to let nodes join the cluster.
>In order to do so, we first need to prepare .kubeconfig that will use the same role, that terraform assumed to create the cluster.
>
>Unfortunately, there is no way to specify external_id there and attempts to execute kubectl apply fail with
>
```
could not get token: AccessDenied: Access denied
	status code: 403, request id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx

```
>To sum up, this issue is a feature request to add ability to specify external_id when providing role-arn to aws eks update-kubeconfig.

I was not sure how to go about issues that were previously closed due to lack of support from another component. 
Since the support is now there, I thought it is a good time to resurrect this request.

**Comment by mailjunze** [comment]
I have multiple Cx's requesting for this feature. Any update when this will be released

**Comment by matt-palmer-tfs** [comment]
I think this is an issue on any `aws eks` command that will require the `external-id` one that comes to mind currently is the command

```
aws eks get-token --role <ARN> 
```
Which will also fail if expecting an external-id

**Comment by Progdrasil** [comment]
Is there any update on this?

**Comment by kdaily** [comment]
Hi @benderillo, I'm going to close this and re-open your original issue. Thanks!
