### ISSUE TITLE
InvalidSignatureException (expired) when using update-function-code

### ISSUE THREAD

**Issue by jacobweber** [aws/aws-cli#4600]
I'm upgrading my Lambda function from NodeJS 8.x to 10.x.

I installed NodeJS 10.16.3 and aws-cli 1.16.263 locally, removed my node_modules and ran "npm install", built my function, zipped it (about 6MB), then tried to run:

```
aws lambda update-function-code --function-name my-function-name --zip-file fileb:///path/to/archive.zip --publish
```

Sometimes it works, but sometimes after about five minutes, I get a 255 status code with this error:

```
An error occurred (InvalidSignatureException) when calling the UpdateFunctionCode operation: Signature expired: 20191018T223413Z is now earlier than 20191018T223507Z (20191018T224007Z - 5 min.)
```

This doesn't happen when I switch back to Node 8.12.0.

I'm guessing there's some sort of 5-minute timeout, but it always used to upload in under 5 minutes.

**Comment by kdaily** [comment]
Hi @jacobweber,

Is this still occurring for you? Are you able to update your function through the console? If you're still having trouble, please run this with `aws --debug` turned on and update here with sanitized output (remove account IDs, etc). Thanks!
