### ISSUE TITLE
Add support to configure single sign-on 

### ISSUE THREAD

**Issue by oscarmartinez-adl** [aws/aws-cli#4602]
We use single sign-on integrated with Organizations and the AWS Directory Service.

All configuration must be done from Web Console, and it would be great if it can be done from cli.

Tasks like:

List/create/delete permission sets
Assign/Unassign Users
List/Edit attribute mappings

And any other stuff you consider.

Is there anything in the roadmap to add this feature?

**Comment by valayDave** [comment]
The work I am doing at my organization requires this too. Is there anything in the AWS pipeline for this?

**Comment by joguSD** [comment]
This is actually a feature request for the SSO service team to expose APIs for these, so I can't comment on any plans or timelines for these. You should let the SSO team know that you would like for these functions to have APIs available via the SDKs and AWS CLI via [AWS Support](https://console.aws.amazon.com/support/home#/).
