### ISSUE TITLE
Add Tags - Update Stage - Api Gateway

### ISSUE THREAD

**Issue by rgleme** [aws/aws-cli#4614]
Hello

I need to add some tags to my api gateway stage.

I've tried this doc, but it seems there is not possible

https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-stage.html

Could you help me ?
Thank you

**Comment by joguSD** [comment]
You should be able to use `aws apigateway tag-resource` for this:

```
aws apigateway tag-resource --resource-arn <stage_arn> --tags tagName=tagValue
```
