### ISSUE TITLE
text output misbehaves with jmespath query when NextToken present

### ISSUE THREAD

**Issue by wryun** [aws/aws-cli#4617]
This seems related to https://github.com/aws/aws-cli/issues/3652, but I'm hitting the strange 'text' output behaviour in a different way.

If I run:

```
aws cloudformation describe-stack-events --max-items 2 --stack-name hostedprod-sentry-worker --query 'StackEvents'  --output text
```
I get None at the end. And if I run:
```
aws cloudformation describe-stack-events --max-items 2 --stack-name hostedprod-sentry-worker --query 'NextToken'  --output text
```
I get None at the start.

i.e. it seems like when you have paginated output, even if you don't use NextToken, the query is evaluated twice - once against StackEvents and once against NextToken. This causes type error messages with certain kinds of jmespath expressions, not to mention emitting essentially 'rubbish' data.

The ideal behaviour from my perspective would be to simply not evaluate against NextToken given that the text output is supposed to be streaming. I can't imagine the use case for the current behaviour.

**Comment by davespanton** [comment]
It's likely because this method (https://github.com/aws/aws-cli/blob/develop/awscli/formatter.py#L265) writes text to the output stream irrespective of what `response` contains, and it writes to it for every page of results. 
For certain JMESPath expressions, the result of `expression.search` is `None`, which then gets written to the output stream.
Some sort of None check in that method would likely fix it.

**Comment by joguSD** [comment]
@davespanton Is correct.

Here's a more detailed explanation: https://github.com/aws/aws-cli/issues/3652#issuecomment-530607404

Unfortunately, we won't be able to change the behavior of the `text` format. However I have marked down you other issue as a feature request for a `buffered-text` format that will behave more like `json` when it comes to pagination and `--query`.

**Comment by wryun** [comment]
@joguSD I believe, as I mentioned in the original post, that this is a subtly different issue to #3652 . I'm not trying to buffered the whole response, I just want the query to only apply to a response when the response exists. i.e. to actually use a streamed response.

As it is, I'm making a query that should only have one page to its response, but I'm getting two evaluations (the second with an empty response). This seems entirely like a bug to me, and as mentioned, I can't think what the use case would be.
