### ISSUE TITLE
Support buffered-text output format

### ISSUE THREAD

**Issue by wryun** [aws/aws-cli#4618]
I would like to be able to run a jmespath query that generates a single text string and have it emitted as such. This almost works with `--output text`, but fails if the output is paginated:

https://github.com/aws/aws-cli/issues/4617
https://github.com/aws/aws-cli/issues/3652

Would a PR for a new output format (rawtext?) be useful?

**Comment by joguSD** [comment]
I think given the amount of confusion around the behavior of the `text` format and how it combines with pagination and the `--query` parameter a `buffered-text` output format that will build the full result, apply the query once, and display the output makes sense to have. Marking this down as a feature request.

**Comment by grandopener** [comment]
Not sure if this should be a separate feature request, but the current situation left as-is will be an indefinitely ongoing source of bugs and confusion for users.  I recommend going farther: once the `buffered-text` output format exists, using `--query` with text should be forbidden, (or at the least carry large and obvious warnings with the output).  I'd wager that 9 times out of 10 someone who uses `--query` with `text` is doing so incorrectly and is just inviting hard-to-debug problems later when their scripts have more data in production.

**Comment by grandopener** [comment]
Personally I more or less gave up on using `text` with `--query` as just fundamentally broken, but as far as I'm aware this is still a problem.

**Comment by adlaika** [comment]
bump!
