### ISSUE TITLE
CloudWatch events list rules by target id

### ISSUE THREAD

**Issue by strahius** [aws/aws-cli#4620]
Using the CloudWatch events [cli](https://docs.aws.amazon.com/cli/latest/reference/events/index.html#cli-aws-events), there is no easy way to find the rule or a target, by a target id or target input.

Use case is:
1. Let's say I have 100 rules, each one having a few targets.
2. I want to get the info for a particular target, and I know the target id and the input.
3. The only way to do this now I think is to list all the rule names by a target arn, (list-rule-names-by-target) and then for each one of the 100 rules, do list-targets-by-rule, and parse the target id/input until I find the one I want.

**Comment by kdaily** [comment]
Thanks for the post, @strahius. This would be a new feature for the CloudWatch service. I will pass along this feedback to the team.
