### ISSUE TITLE
describe-association-executions displays multiple values using --output text

### ISSUE THREAD

**Issue by Luk3rson** [aws/aws-cli#4624]
Hi team,

using following command:
`aws ssm describe-association-executions --association-id f0a97a90-93d5-4a01-a880-x5dr854 --query 'AssociationExecutions[0].[Status]' --output text
`
You should obtain only the latest execution *Status*
But the output is following:

> Success
Success

Example without using --output text parameter:

`aws ssm describe-association-executions --association-id f0a97a90-93d5-4a01-a880-x5dr854 --query 'AssociationExecutions[0].[Status]'
`

> [
    "Success"
]

Please, would it be possible to adjust the *output text* paramater?

Query without using object *Status*:

`aws ssm describe-association-executions --association-id f0a97a90-93d5-4a01-a880-x5dr854 --query 'AssociationExecutions[0]'
`

> {
    "AssociationId": "f0a97a90-93d5-4a01-a880-x5dr854",
    "AssociationVersion": "15",
    "ExecutionId": "2e02283e-d752-47bb-9b31-a1b0ba8802c2",
    "Status": "Success",
    "DetailedStatus": "Success",
    "CreatedTime": 1573063535.711,
    "ResourceCountByStatus": "{Success=1}"
}

`aws ssm describe-association-executions --association-id f0a97a90-93d5-4a01-a880-x5dr854 --query 'AssociationExecutions[0]' --output text
`

> f0a97a90-93d5-4a01-a880-c43de962b80f    15      1573063535.711  Success 2e02283e-d752-47bb-9b31-a1b0ba8802c2    {Success=1}     Success
f0a97a90-93d5-4a01-a880-c43de962b80f    1       1572462684.419  Success 8ed544d5-3894-45f9-b345-524afea439ad    {}      Success

**Comment by kdaily** [comment]
Hi @Luk3rson,

Does this still occur for you with a more recent version of the AWS CLI? I tested with the most recent, 1.18.157, and this did not occur:

```
> aws ssm describe-association-executions --association-id a44c3b9d-69a6-4e99-aec8-23fdac63cff1 --output json --query 'AssociationExecutions[0]'
{
    "AssociationId": "a44c3b9d-69a6-4e99-aec8-23fdac63cff1",
    "AssociationVersion": "1",
    "ExecutionId": "a44c3b9d-69a6-4e99-aec8-23fdac63cff1",
    "Status": "Pending",
    "DetailedStatus": "Associated",
    "CreatedTime": 1602708481.481,
    "ResourceCountByStatus": "{Pending=1}"
}
> aws ssm describe-association-executions --association-id a44c3b9d-69a6-4e99-aec8-23fdac63cff1 --output json --query 'AssociationExecutions[0].[Status]'
[
    "Pending"
]
> aws ssm describe-association-executions --association-id a44c3b9d-69a6-4e99-aec8-23fdac63cff1 --output text --query 'AssociationExecutions[0].[Status]'
Pending
```
