### ISSUE TITLE
aws2 cli SSO Access Denied

### ISSUE THREAD

**Issue by mark-bixler** [aws/aws-cli#4631]
cli v2 doesn't seem to work when living along side v1. 

When running `aws2 sts get-caller-identity` the v1 credentials show and not the SSO credentials.

aws2 seems to write info to the `.aws/config` file, but when running a command it seems to check `.aws/credentials` file instead and therefore results in the access denied message since the newly created profile only exists in "config" not "credentials."

**Comment by joguSD** [comment]
When you configured your SSO profile, which profile name did you save it under?

If you have both static credentials and SSO configured under the same profile, the static credentials will win.

**Comment by mark-bixler** [comment]
a totally unique profile. Behavior seems to just be looking at creds file first and not config.

**Comment by joguSD** [comment]
When you run `aws2 sts get-caller-identity` are you providing the profile that you saved the SSO configuration to?

Something like: `aws2 sts get-caller-identity --profile <sso-profile-name>`
