### ISSUE TITLE
DescribeLogStreams causes ThrottlingException for large streams in log groups

### ISSUE THREAD

**Issue by fabiomatavelli** [aws/aws-cli#4635]
```
> aws --version
aws-cli/1.16.180 Python/3.7.4 Darwin/19.0.0 botocore/1.12.170
```
Trying to describe log streams of a log group with more than a million log streams, causes the CLI to raise the Throttling exception.

```
> aws logs describe-log-streams --log-group-name /aws/lambda/xxxx
An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded
```

**Comment by kdaily** [comment]
Hi @fabiomatavelli,

I apologize for the long delay. According to the [documentation](https://docs.aws.amazon.com/cli/latest/reference/logs/describe-log-streams.html):

> This operation has a limit of five transactions per second, after which transactions are throttled.

The AWS CLI should back off exponentially (by a factor of two up to 20 seconds) on retries to help mitigate this.

If this is still an issue for you, can you provide the output of this command with the retries it is making by adding the `--debug` flags?
