### ISSUE TITLE
aws2 sso configure error when authorizing request

### ISSUE THREAD

**Issue by cchd1** [aws/aws-cli#4639]
OS: MacOS
Terminal: Default Mac Terminal
Browser: Chrome
aws2 version: aws-cli/2.0.0dev0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev0

Following this blog post:
https://aws.amazon.com/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/

```
aws2 configure sso
SSO start URL [None]: https://d-1ab2c3d4.awsapps.com/start                                                                                                                      
SSO Region [None]: eu-west-1                                                                                                                                                      
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

ABCD-EFGH
```

The SSO Authorization page automatically opens in my browser with the URL `https://device.sso.eu-west-1.amazonaws.com/?user_code=ABCD-EFGH`, but there's an error message:
<img width="890" alt="Screenshot 2019-11-11 at 21 26 49" src="https://user-images.githubusercontent.com/44895210/68622568-5689d580-04ca-11ea-9017-7220dca9fd5a.png">

Note:
Our AWS SSO account has MFA enabled

**Comment by furikake** [comment]
CSP issues for me with CLI v2 too.  URL looks like https://device.sso.ap-southeast-2.amazonaws.com/?user_code=XXXX-XXXX

It's trying to load resource from https://oidc.ap-southeast-2.amazonaws.com/device_verification?user_code=XXXX-XXXX which isn't allowed by CSP. 

CSP has 

```
default-src 'self'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'; font-src data: https://*.console.aws.amazon.com/fonts/
```

This block in `login.js` seems to generate that hostname:

```
if(stage === "prod"){
    oidcServiceUrl = `https://oidc.${region}.amazonaws.com`;
} else {
    oidcServiceUrl = `https://${region}.${stage}.oidc.access.idaho.aws.a2z.com`;
}
```

Looks like you just need to add that different permutations of the OIDC URL into the CSP `script-src`.

**Comment by JohnVonNeumann** [comment]
I have also run up against this with a Control Tower deployed SSO in eu-west-1.

![image](https://user-images.githubusercontent.com/18162779/68633057-955c7180-0544-11ea-95f7-405c28be0638.png)

![image](https://user-images.githubusercontent.com/18162779/68633122-cccb1e00-0544-11ea-9250-d772d1ac13a8.png)

```
https://oidc.eu-west-1.amazonaws.com/device_verification?user_code=????-????
```

![image](https://user-images.githubusercontent.com/18162779/68633164-f1bf9100-0544-11ea-984d-8c223a4dc64d.png)

**Comment by michaeljfazio** [comment]
Hit this issue today also.

**Comment by joguSD** [comment]
Closing in favor of duplicate #4645
