### ISSUE TITLE
Add support for SSO integration with AzureAD

### ISSUE THREAD

**Issue by sstaffordestrat** [aws/aws-cli#4641]
Please extend the SSO support to include Azure AD as a SSO provider.  Majority of my customers are using AzureAD over AWS SSO at present and this would fix the biggest complaint I hear regarding the CLI.

**Comment by markaltmann** [comment]
+1

**Comment by danielsaibt** [comment]
+1

**Comment by ngander-amfam** [comment]
+1

**Comment by cervantek** [comment]
I've opened a ticket for a generic solution to this: #4647.

**Comment by jamesls** [comment]
We support it now, here's a blog post that walks through how to set this up: https://aws.amazon.com/blogs/aws/the-next-evolution-in-aws-single-sign-on/
