### ISSUE TITLE
OKTA SSO Integration

### ISSUE THREAD

**Issue by ado2p** [aws/aws-cli#4643]
Please introduce the Support for the Short term credentials management for customers using OKTA.

**Comment by ibareev-talend** [comment]
+1

**Comment by cervantek** [comment]
I've opened a ticket for a generic solution to this: #4647.

**Comment by kdaily** [comment]
Hi @ado2p,

Looks like this has been addressed:

https://github.com/aws/aws-cli/issues/4647#issuecomment-565263776
