### ISSUE TITLE
aws2 sso does not inherit ca_bundle from default profile

### ISSUE THREAD

**Issue by bondsbw** [aws/aws-cli#4646]
When using a profile with `aws2 sso` commands, the `ca_bundle` option is not inherited by the profile.  This configuration fails to verify my self-signed certificate when I attempt to run `aws2 sso login --profile myprofile`:

```
[default]
region = us-east-1
output = table
ca_bundle = .....\cert.cer

[profile myprofile]
sso_start_url = https://....awsapps.com/start
sso_region = us-east-1
sso_account_id = ...
sso_role_name = ...
region = us-east-1
output = table
```
But copying the `ca_bundle` line directly into the profile succeeds.

The profile code above is the default generated using `aws2 sso configure`.

---
aws-cli/2.0.0dev0 Python/3.7.5 Windows/10 botocore/2.0.0dev0

**Comment by bisdavid** [comment]
@bondsbw, that's because the default profile is a separate profile.  It's settings are not used when you specify a different one like "myprofile". There is no inheritance between profiles. 

You did, however, find the correct way to do this.  You need to add the "ca_bundle" value to each profile for which you want it available.  Just as you already have "region" and "output" value in each profile.

**Comment by bondsbw** [comment]
Odd, since I _do_ get inheritance from default to profile for `aws2 sts get-caller-identity --profile myprofile`.

**Comment by bondsbw** [comment]
I also can confirm that `aws s3 ls` and `aws ec2 describe-instances` seem to support default profile inheritance of `ca_bundle`.

**Comment by bisdavid** [comment]
There is something else going on then.  The values in the [default] profile are used only when you explicitly specify `--profile default` or don't specify a profile at all (and thus use "default" by default).  They are not inherited by other profiles.  I confirmed this with the engineering team.

**Comment by bondsbw** [comment]
Possibly.  I can test other scenarios if you can think of any that could help us narrow down the issue.

**Comment by bondsbw** [comment]
For clarity, I just ran a test of the 3 commands I previously mentioned with both the default profile and the `myprofile` profile:
```bash
aws2 sts get-caller-identity
aws2 sts get-caller-identity --profile myprofile
aws2 s3 ls
aws2 s3 ls --profile myprofile
aws2 ec2 describe-instances
aws2 ec2 describe-instances --profile myprofile
```

I did that with each of the following configurations:
- both the default profile and `myprofile` include the `ca_bundle` configuration
  - All commands succeeded
- neither the default profile nor `myprofile` include the `ca_bundle` configuration
  - All commands failed
- the default profile includes the `ca_bundle` configuration, `myprofile` does not
  - All commands succeeded
- `myprofile` includes the `ca_bundle` configuration, the default profile does not
  - Only the commands including `--profile myprofile` succeeded

These results are consistent with `ca_bundle` inheritance from default profile to `myprofile`.

**Comment by jamesls** [comment]
Just to clarify, we don't have support for profile inheritance, though I'd really like to add some type of support for it eventually.  Perhaps you're setting your ca bundle through an env var (e.g `AWS_CA_BUNDLE`)?

I tried a negative test case which has the behavior I expect:

```
# Set ca bundle to a bad value in the default profile:

$ head ~/.aws/config
[default]
ca_bundle=/tmp/badvalue

# Next verify that this fails because the file doesn't exist:

$ aws2 s3 ls --profile default --debug
... omitted ...
2019-12-12 17:35:04,019 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): s3.us-west-2.amazonaws.com:443
2019-12-12 17:35:04,047 - MainThread - botocore.endpoint - DEBUG - Exception received when sending HTTP request.
Traceback (most recent call last):
  File "site-packages/urllib3/util/ssl_.py", line 336, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

# Finally verify this works for a profile that doesn't have `ca_bundle` configured:

$ aws2 s3 ls --profile other-profile
2019-12-11 12:44:49 s3transfergr2su0iehc
2019-12-11 12:44:50 s3transferpagzlpai59
```

If you try the same test by pointing to a non-existing CA bundle file, do you see the same results?
