### ISSUE TITLE
Cloudformation - AWS::RDS::DBSubnetGroup Export Casing Error

### ISSUE THREAD

**Issue by Krobar** [aws/aws-cli#4652]
The documentation for DBSubnetGroup mentions the name of the DB Subnet Group will be stored in lower case which is fine but if you export the DBSubnetGroup object then it does not take this into account. 
For example; if you name the DBSubnetGroup as "myExampleGroup" it will be stored as "myexamplegroup" but the export will contain "myExampleGroup" and hence all dependant Cloudformation stacks will fail to find the DBSubnetGroup.

**Comment by kdaily** [comment]
Hi @Krobar, is this still an issue? Can you provide the location where the lower case restriction is mentioned, as well as the command you were running to encounter this? Thanks.
