### ISSUE TITLE
s3 cp: source object ACLs are not preserved

### ISSUE THREAD

**Issue by rbrinkman** [aws/aws-cli#4653]
Performing a recursive copy of objects in a bucket removes the ACL public read permissions from the original (source) objects.

Given an S3 bucket containing objects with ACLs that includes public read on each object, run the following command:
`aws s3 cp s3://bucket-name/prefix ./ --recursive`

Expected behavior:
1. The objects and directories in the bucket under the given prefix will be copied to the current run directory. The ACLs will not be preserved on the copies.
2. The source objects in the bucket will not be altered in any way.

Actual behavior:
1. The objects and directories are successfully copied, and do not have ACL permissions (expected).
2. The source objects in the S3 bucket no longer have any custom ACL public read permissions set (not expected).

aws-cli version:
1.16.263

**Comment by kdaily** [comment]
Hi @rbrinkman, is this still an issue for you?

If so, I want to confirm what you're encountering. You're indicating that if you run a recursive copy from a remote S3 bucket to a local file system, the ACL on the remote bucket is removed?

Can you provide a minimal reproducible example, specifically with the output of `aws s3api get-object-acl` before and after you perform a recursive copy?

**Comment by coriolinus** [comment]
Encountered a variant of this issue today. Attempted to copy a bucket to itself in order to set the `content-disposition` header, like:

```sh
aws \
  s3 cp \
  s3://my-bucket \
  s3://my-bucket \
  --recursive \
  --content-disposition attachment \
  --exclude "*" --include "*.pdf"
```

The expected behavior is that ACLs would be preserved. The actual behavior was that ACLs were clobbered, and documents could not be downloaded by the public anymore.

The fix was to re-run the command with one more flag:

```sh
aws \
  s3 cp \
  s3://my-bucket \
  s3://my-bucket \
  --recursive \
  --content-disposition attachment \
  --exclude "*" --include "*.pdf" \
  --acl public-read
```
