### ISSUE TITLE
create-state-machine --cli-input option should allow non-stringified JSON for State Functions definition

### ISSUE THREAD

**Issue by martineno** [aws/aws-cli#4655]
When using the `create-state-machine` with the `--cli-input` option, the `aws-cli` requires that the `definition` property that contains the Step Function definition is stringified.

For example:

```json
{
  "name": "example",
  "definition": "{\"StartAt\":\"Pass\",\"States\":{\"Pass\":{\"Type\":\"Pass\",\"End\":true}}}",
  "roleArn": "arn:aws:iam::012345678901:role/DummyRole"
}
```

It would be convenient if the definition property could be a non-stringified JSON object defining the Step Function. This makes the source file more readable and would require less additional processing. For example:

```json
{
    "name": "example",
    "definition": {
        "StartAt": "Pass",
        "States": {
            "Pass": {
                "Type": "Pass",
                "End": true
            }
        }
    },
    "roleArn": "arn:aws:iam::012345678901:role/DummyRole"
}
```

**Comment by joguSD** [comment]
The hard part of something like this is that the `definition` field is modeled as a string hence why you have to pass it as a JSON encoded string. We're generally hesitant to make these kind of one off changes for a particular service field as they tend to end up being problematic. That being said I can see how this would be useful so I'll mark this as a feature request.

**Comment by martineno** [comment]
Thank you @joguSD for considering this feature request.

If needed for the sake for consistency and compatibility, I think it would also make sense to have a separate `definition` field for non-stringified JSON.

For example,

```json
{
    "name": "example",
    "definition-json": {
        "StartAt": "Pass",
        "States": {
            "Pass": {
                "Type": "Pass",
                "End": true
            }
        }
    },
    "roleArn": "arn:aws:iam::012345678901:role/DummyRole"
}
```

would make sense to me. That way the input data type for `definition` is not overloaded and existing behavior is maintained.
