### ISSUE TITLE
aws2 sso configure error when signing in to use AWS CLI

### ISSUE THREAD

**Issue by cchd1** [aws/aws-cli#4657]
OS: MacOS
Terminal: Default Mac Terminal
Browser: Chrome
aws2 version: aws-cli/2.0.0dev0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev0
MFA Enabled on AWS SSO

Following this blog post:
https://aws.amazon.com/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/

```
aws2 configure sso
SSO start URL [None]: https://d-1ab2c3d4.awsapps.com/start                                                                                                                      
SSO Region [None]: eu-west-1                                                                                                                                                      
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

ABCD-EFGH
```

The SSO Authorization page automatically opens in my browser with the URL: `https://device.sso.eu-west-1.amazonaws.com/?user_code=ABCD-EFGH`

I am able to sign in now, after the fix was made in https://github.com/aws/aws-cli/issues/4645, but now there's an error message when trying to login to use the AWS CLI
<img width="1298" alt="Screenshot 2019-11-13 at 20 44 42" src="https://user-images.githubusercontent.com/44895210/68850606-3d507700-06cc-11ea-89dd-f7f87e983242.png">

This is after removing my cache/history in Chrome, as well as testing in Safari.

**Comment by cchd1** [comment]
@joguSD FYI

**Comment by mrdoro** [comment]
I got exact same error

**Comment by cchd1** [comment]
Tried again today, got this error instead now.
<img width="1297" alt="Screenshot 2019-11-18 at 14 45 05" src="https://user-images.githubusercontent.com/44895210/69100466-19fe3280-0a12-11ea-8dd4-bf1c5cf2be89.png">

**Comment by cchd1** [comment]
Updated the aws2 CLI and used the correct region (eu-west-2) where the AWS SSO directory was set up. Before updating, running `aws2 sso configure` would force me to use eu-west-1, hence the above error message.

**Comment by mrdoro** [comment]
I confirm what @cchd1 wrote.
It works well after the update.
