### ISSUE TITLE
large files have EOL terminators changed to OS EOL terminators

### ISSUE THREAD

**Issue by davidmoss75** [aws/aws-cli#4659]
Hi,
When large files are sent via aws cli and it uses the mulitpart upload it is replacing the EOL terminators with the OS specific ones and not keeping the ones specified in the file.

This is causing us issues as we are sending files up from a linux system but need <CR><LF> terminators to remain in place.  I would expect the content of my file to remain unchanged!

Is there a way around this if not is this a bug fix that can be put in the list.

Thanks

**Comment by joguSD** [comment]
Is this only happening for large files? 
I also think that this should be preserving line endings and not changing them based on the platform.

**Comment by kdaily** [comment]
Hi @davidmoss75, is this still occurring for you? If so, can you please let us know the version of the AWS CLI that you are experiencing this with (`aws --version`)? Thanks!
