### ISSUE TITLE
Change INSTALL_DIR default for aws2

### ISSUE THREAD

**Issue by lousyd** [aws/aws-cli#4660]
In the installer for aws2, the default `INSTALL_DIR` is /usr/local/aws-cli. I suggest changing it to /opt/aws-cli. The /usr/local hierarchy is not set up for installing whole packages in one subdirectory. It is split into different directories for bin files, source files, libraries, etc. Creating a new directory in /usr/local for aws2 breaks this convention.

Also, the Filesystem Hierarchy Standard, for Linux systems, says that no other directories should exist in /usr/local. It does however, specify a place for vendor package trees: /opt.

I suggest changing the default `INSTALL_DIR` for the aws2 installer to /opt/aws-cli. Nothing else needs to be changed to support changing that default. The /opt directory works exactly like the installer is expecting.

**Comment by kyleknap** [comment]
We would need to think about changing it to `/opt/aws-cli`. In the meantime though, you can control where the install dir lives using the `-i` parameter. So something like:
```
$ ./install -i /opt/aws-cli
```
Also, you can get a full list of the install options by running: `./install --help`
