### ISSUE TITLE
Please make aws2 respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by lousyd** [aws/aws-cli#4662]
aws2 currently defaults to storing configuration and credentials in a directory called "$HOME/.aws". Please modify it to default to "$HOME/.config/aws", per the XDG Base Directory Specification. This isn't just to follow a standard for standard's sake, but also to help keep hidden directories from proliferating in home directories. It would be sensible for aws2 to default to "$HOME/.config/aws" but fallback to "$HOME/.aws" if the former isn't available, so that backwards compatibility can be maintained.

I've set AWS_CONFIG_FILE and AWS_SHARED_CREDENTIALS_FILE, which does change where the config and credentials file are stored. But aws2 cli history still goes to .aws in my home directory.

*Please* please make aws2 respect XDG!

**Comment by z0rc** [comment]
Linking previous issues about this topic to signify that this isn't a new issue, but v2 would be prefect opportunity to finally make it happen.
https://github.com/aws/aws-cli/issues/2433
https://github.com/boto/botocore/issues/1839

**Comment by kdaily** [comment]
Given that this is relevant to AWS CLI v1 and v2, I'm going to close it in favor of #2433.

This change would need to be respected by all AWS SDKs and tools, so I'm going to be moving #2433 to the AWS SDK issue tracking repository, at https://github.com/aws/aws-sdk.

**Comment by Jolg42** [comment]
Note: I have found the issue (still open) at https://github.com/aws/aws-sdk/issues/30
