### ISSUE TITLE
CLI documentation for import-terminology doesn't match actual expected input

### ISSUE THREAD

**Issue by curtisgibby** [aws/aws-cli#4665]
When I run the following example command from the [documentation](https://docs.aws.amazon.com/cli/latest/reference/translate/import-terminology.html#examples)...

```bash
aws translate import-terminology \
    --name MyTestTerminology \
    --description "Creating a test terminology in AWS Translate" \
    --merge-strategy OVERWRITE \
    --data-file fileb://test-terminology.csv \
    --terminology-data Format=CSV
```

... I get this response:

```
Unknown options: --data-file, fileb://test-terminology.csv
```

It appears that the file has been moved to be part of the `--terminology-data` parameter. However, when I include it like this...

```bash
aws translate import-terminology \
    --name MyTestTerminology \
    --description "Creating a test terminology in AWS Translate" \
    --merge-strategy OVERWRITE \
    --terminology-data Format=CSV,File=test-terminology.csv
```

... I get back the following response...

```
An error occurred (InvalidParameterValueException) when calling the ImportTerminology operation: The provided terminology is not formatted correctly. Check the contents of your file to ensure that it follows the correct CSV format.
```

I'm using the same CSV file that I downloaded from `get-terminology`, so I know that the file itself is formatted correctly. The same result happens when I reference a CSV file that doesn't exist (`File=no-exist.csv`), so it appears that I'm not passing in the filename correctly. I've tried the following formats for referencing the file, with identical error results:

- `File=test-terminology.csv`
- `File=./test-terminology.csv`
- `File='test-terminology.csv'`
- `File=file://test-terminology.csv`
- `File=fileb://test-terminology.csv`

How should the CSV file be referenced from the CLI command to successfully upload to the AWS Translate service?

Similarly, when I try to import the TMX file from the [documentation](https://docs.aws.amazon.com/translate/latest/dg/creating-custom-terminology.html)...

```
aws translate import-terminology \
    --name MyTestTerminology \
    --description "Creating a test terminology in AWS Translate" \
    --merge-strategy OVERWRITE \
    --terminology-data Format=TMX,File=test-terminology.xml
```

... I get another error...

```
An error occurred (InvalidParameterValueException) when calling the ImportTerminology operation: Invalid TMX format.
```

**Comment by bisdavid** [comment]
@curtisgibby, I spoke with the Service writer for Amazon Translate, and he wasn't able to reproduce your problem.  He suggested that you check the version of the CLI that you're using, and if it's an older version, try upgrading.

The most recent version is 1.16.283.

Please let me know if that addresses your problem.

**Comment by curtisgibby** [comment]
@bisdavid thanks for the feedback. I updated my CLI client and was successfully able to create a new terminology with the command as documented. I appreciate your help with this!

**Comment by bisdavid** [comment]
@curtisgibby  I'm glad it worked for you!
