### ISSUE TITLE
RunInstances: InvalidParameterCombination: validUntil cannot be set with SpotRequestType 'one-time'

### ISSUE THREAD

**Issue by pwaller** [aws/aws-cli#4679]
# Reproducer

(Note: set ValidUntil to now + 6 hours `2019-11-19T16:13:16Z`)

```
aws --region=eu-west-1 ec2 run-instances \
  --instance-type c5.metal \
  --instance-market-options "MarketType=spot,SpotOptions={MaxPrice=0.2,SpotInstanceType=one-time,ValidUntil=2019-11-19T16:13:16Z,InstanceInterruptionBehavior=terminate}" \
  --instance-initiated-shutdown-behavior terminate \
  --image-id ami-04c58523038d79132
```

# Output

```
An error occurred (InvalidParameterCombination) when calling the RunInstances operation: The parameter validUntil cannot be specified when the SpotRequestType is set to 'one-time'.
```

# Expected behaviour

Possible successful creation of a spot instance with request valid until set to now + 6hours.

# Additional bug

A run with `--dry-run` claims success, where the actual run does not succeed.

# Documentation reference

This seems to contradict the documentation:

Link: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotMarketOptions.html

Quote (emphasis mine - it explicitly suggests one-time requests should allow specifying ValidUntil):

> #### ValidUntil
>
>    The end date of the request. For a **one-time request**, the request remains active until all instances launch, the request is canceled, **or this date is reached**. If the request is persistent, it remains active until it is canceled or this date and time is reached. The default end date is 7 days from the current date.

**Comment by kdaily** [comment]
This looks like a problem with the API or model, as that description (which is also present in the `run-instances` documentation) reads as you describe.

**Comment by kdaily** [comment]
Hi @pwaller, thanks again for filing this. The documentation is incorrect and will be adjusted: `validUntil` is not supported for one-time `requestType` in the `runInstances` call.

**Comment by kdaily** [comment]
Hi @pwaller, the documentation has been updated under the [`ValidUntil` section](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotMarketOptions.html):

> For a one-time request, ValidUntil is not supported. The request remains active until all instances launch or you cancel the request.
