### ISSUE TITLE
awscli unable to authenticate itself inside a container w/ bridge network

### ISSUE THREAD

**Issue by left4taco** [aws/aws-cli#4683]
We are running CI jobs inside a container, which uses `aws s3 cp` to upload things to S3. However, `aws` cannot authenticate itself using the EC2's IAM role if the container is started with docker0 bridge network. 

If the container is started with `--net=host`, then everything is fine. 

Any thought on that? Thanks.

**Comment by jcook793** [comment]
This exact thing happened to me today as well (Gitlab CI Runner). I pinned us to AWS CLI 1.16.282 (`pip install awscli==1.16.282`) to get us back up and running (last time I saw it work correctly), but yeah, this is a problem.

**Comment by dylanlive** [comment]
I believe this is a dup of https://github.com/aws/aws-cli/issues/4682

**Comment by left4taco** [comment]
@dylanlive Yes you are right. Just realized that. Closing this ticker now.
