### ISSUE TITLE
aws sts fails when home directory is updated in environment variable on windows

### ISSUE THREAD

**Issue by getsunil** [aws/aws-cli#4686]
i updated environment variable %Home% to c:\users\<user-name>\.aws
After update, my credentials were stored in c:\users\<user-name>\.aws\.aws folder on aws configure.
following commands started failing after this:
aws sts get-caller-identity
aws iam list-users

but other commands still worked
aws s3 ls

**Comment by klaytaybai** [comment]
I'll look into this.  May I ask why you set your Home path to the .aws folder?

**Comment by getsunil** [comment]
Actually if change my Home path in environment variable to anything other then the default one, sts and iam cli commands start failing.

**Comment by kdaily** [comment]
@getsunil - does this issue still occur for you?
