### ISSUE TITLE
not able to create change-resource-record-sets using cli

### ISSUE THREAD

**Issue by kalpeshims** [aws/aws-cli#4687]
Hello,

I am trying to create a new "record set" in route53 using cli,

i am using bash script.

and i want to do this in a single file,  

so, first i run the "aws apigateway create-domain-name.." command with --endpoint-configuration types=EDGE. and its working fine, and i am able to get the response with distributionDomainName.

then second i run the "aws apigateway create-base-path-mapping.." command and it is also working fine, i got the response properly.

and then finally run the "aws route53 change-resource-record-sets.." command with proper json file, but i am not able to create new record set.
JSON FILE :  {"Comment":"test using cli","Changes":[{"Action":"CREATE","ResourceRecordSet":{"Name":"test4.test.com","Type":"A","AliasTarget":{"HostedZoneId":"xxx","DNSName":"xxx.cloudfront.net","EvaluateTargetHealth":false}}}]}

 i am getting following error.

**An error occurred (InvalidChangeBatch) when calling the ChangeResourceRecordSets operation: [Tried to create an alias that targets d-xxxx.execute-api.us-east-1.amazonaws.com., type A in zone XXX, but the alias target name does not lie within the target zone, Tried to create an alias that targets d-w5i2u9amxa.execute-api.us-east-1.amazonaws.com., type A in zone XXX, but that target was not found]**

ref. link
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-regional-api-custom-domain-create.html

**My questions is  "IS IT POSSIBLE TO CREATE ALL THE THINGS SIMULTANEOUSLY ?"**  

thanks.

**Comment by kalpeshims** [comment]
my bash script file.

    ROUTE_NAME="test3.xx.com"
    echo "$ROUTE_NAME"

    NAME_CERTIFICATE="$ROUTE_NAME cert"
    echo "$NAME_CERTIFICATE"

    STAGE="dev"
    echo "STAGE = $STAGE"

    BASE_PATH="v1"
    echo "BASE_PATH = $BASE_PATH"

    API_ID="xxx"
    echo "API_ID = $API_ID"

    HOSTED_ZONE_ID="xxx"
    echo "$HOSTED_ZONE_ID"

    ARN_CERTIFICATE="arn certificate number"
    echo "$ARN_CERTIFICATE"

    CREATE_DOMAIN_NAME="aws apigateway create-domain-name --domain-name $ROUTE_NAME --certificate-name '$NAME_CERTIFICATE' --endpoint-configuration types=EDGE --certificate-arn $ARN_CERTIFICATE"
        echo "$CREATE_DOMAIN_NAME"
        # run aws command
        $CREATE_DOMAIN_NAME
        echo "###### NEW DOMAIN NAME CREATED"

    # code to get cloudfront.net string 
        delimiter=\"
        s=$CREATE_DOMAIN_NAME$delimiter
        array=();
        while [[ $s ]]; do
            array+=( "${s%%"$delimiter"*}" );
            s=${s#*"$delimiter"};
        done;
        declare -p array
        echo "${array[17]}"
        DNS_NAME="${array[17]}"
        echo "###### GETTING DNS NAME(CLOUDEFRONT-URL)"

    
    # code to mapping domain with apigateway
    CREATE_BASE_PATH_MAPPING="aws apigateway create-base-path-mapping --domain-name $ROUTE_NAME --base-path $BASE_PATH --rest-api-id $API_ID --stage $STAGE"
    echo "$CREATE_BASE_PATH_MAPPING"
    # run aws command
    $CREATE_BASE_PATH_MAPPING
    echo "###### NEW BASE MAPPING COMPLETE"

    # change-batch json file
    CHANGE_BATCH_JSON="{\"Comment\":\"test\",\"Changes\":[{\"Action\":\"UPSERT\",\"ResourceRecordSet\":{\"Name\":\"$ROUTE_NAME\",\"Type\":\"A\",\"AliasTarget\":{\"HostedZoneId\":\"$HOSTED_ZONE_ID\",\"DNSName\":\"$DNS_NAME\",\"EvaluateTargetHealth\":false}}}]}" 
    echo "$CHANGE_BATCH_JSON"
    # aws command for create record set
    RECORD_SET_COMMAND="aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch  $CHANGE_BATCH_JSON"
        
    echo "$RECORD_SET_COMMAND"
    # run aws command
    $RECORD_SET_COMMAND
    echo "###### ADD RECORD SET TO ROUTE53 COMPLETE"

**Comment by kdaily** [comment]
Hi @kalpeshims,

Is this still an issue for you? It looks like it might just be that you need to wait before you run the `change-resource-record-sets` call. Unfortunately it doesn't look like API Gateway V2 has any waiters defined for the create commands, so you'll have to manage that yourself.

**Comment by SalemNabeelSalem** [comment]
@kalpeshims how solve the problem ?
