### ISSUE TITLE
docdb describe commands return rds instances

### ISSUE THREAD

**Issue by joshmccleery** [aws/aws-cli#4688]
When I run:
`aws docdb describe-db-instances`
or
`aws docdb describe-db-clusters`
I get back all of my RDS and DocumentDB instances or clusters, respectively.

pip -V: pip 19.2.3
aws --version: aws-cli/1.16.285 Python/2.7.12 Linux/4.4.0-18362-Microsoft botocore/1.13.21

**Comment by klaytaybai** [comment]
Hi @joshmccleery, that does seem like very odd behavior.  Based on the documentation for the API and CLI calls, I assume that this is a bug.  However, changing the implementation would be a breaking change for customers who are using ALL db types.  If you want, we could change this issue to a feature request to add an option to filter by the database type easily.  I think you do this client side via the JMESPath queries, but an extra option might be simpler.  Let us know.

**Comment by PrivoSkadberg** [comment]
This seems like a rather poor reason to close a huge bug.  Just because you did return the wrong data and some people may be using it, does not mean you shouldn't fix the issue to return the correct data and have them fix their applications to do the right thing.

**Comment by fllaca** [comment]
Upvoting on reopening this. Today I deleted a RDS cluster with `aws docdb delete-db-cluster ...`, it was a dev environment but still not fun, this is a kinda serious bug.

**Comment by fdaugan** [comment]
Indeed, both the `docb` and `rds` APIs are based on the same IAM service `rds` permissions. Consequently, when partitioning docb and rds resources, it's imperative to account for these shared IAM permissions. If keeping the current behavior may seem poor, fixing it will lead to a significant regression.

**Comment by FilipSwiatczak** [comment]
As of aws-cli/2.13.28 the `aws docdb` completely ignores DocumentDb clusters and only returns instances of RDS. @klaytaybai 1) yes it's a bug 2) no it's not a feature request 3) it should ideally be re-opened

**Comment by trevorstr** [comment]
This is a pretty bad bug ... no one from AWS is going to fix this?

**Comment by mencnert** [comment]
I have found this in docs. Hope it helps.

```sh
aws docdb describe-db-clusters --filter Name=engine,Values=docdb
```

```sh
aws docdb describe-db-instances --filter Name=engine,Values=docdb
```

https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-view-details.html

https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-view-details.html

**Comment by FilipSwiatczak** [comment]
My experience on latest AWS CLI: 2.17.13 with Python 3.11.9. 

In same region, I have:
- 1 RDS instance called, for brevity, "A" and 
- 1 DocDB instance called "B"

Running:
`aws docdb describe-db-clusters --filter Name=engine,Values=docdb --profile my-profile --region ea-west-1`
I get null back:
```
{
"DBClusters": []
}
```

When I drop the Filter, I can the "A" instance back. 

Conclusion:
`aws docdb` returns same results as `aws rds` with same syntax, but crucially NEITHER return DocDB instance, with or without Engine filter. 

This must be a bug. For us it's a bummer as we're hoping to use Event Bridge to turn DocDB on and off for cost saving. Thanks!

**Comment by alancasagrande** [comment]
Same as the above, `aws docdb describe-db-clusters` return all the RDS clusters but not DocDB clusters.

🤷🏻‍♂️
