### ISSUE TITLE
[V2] After Login, resources doesn't available 

### ISSUE THREAD

**Issue by churtado-edrans** [aws/aws-cli#4696]
Hi all!

I'm trying with the aws2 login to get info about resources but always have the same output.

```
aws2 s3 ls --profile name-environment

Could not connect to the endpoint URL: "https://s3.qa-admin.amazonaws.com/"
```

Any ideas?

**Comment by jamesls** [comment]
Is that the value of your SSO start url?  Can you confirm that you can go to that page in your web browser?

**Comment by churtado-edrans** [comment]
I can login successful in the web browser, but when I run commands in terminal always respond with these message.

**Comment by kdaily** [comment]
Hi @churtado-edrans,

Are you still experiencing this issue?

**Comment by churtado-edrans** [comment]
Hi @kdaily , I didn't have this issue since last year, I think the issue must be closed

**Comment by stobrien89** [comment]
Closing due to staleness. If anyone is still experiencing an issue, please feel free to @ me!
