### ISSUE TITLE
aws firehose create-delivery-stream fails due to `TypeName`

### ISSUE THREAD

**Issue by PSChrisHinshaw** [aws/aws-cli#4697]
Here is the error I get when TypeName has a value:
`[chinshaw@build4 aws]$ grep TypeName p00000012.json 
        "TypeName": "document",
[chinshaw@build4 aws]$ aws firehose create-delivery-stream --delivery-stream-name p00000012 --delivery-stream-type DirectPut --cli-input-json file://$PWD/p00000012.json --profile psledeng
An error occurred (InvalidArgumentException) when calling the CreateDeliveryStream operation: Types are deprecated in Elasticsearch version 7.1. TypeName must be empty.`
Next is when TypeName is "":
`[chinshaw@build4 aws]$ grep TypeName p00000012.json 
        "TypeName": "",
[chinshaw@build4 aws]$ aws firehose create-delivery-stream --delivery-stream-name p00000012 --delivery-stream-type DirectPut --cli-input-json file://$PWD/p00000012.json --profile psledeng
Parameter validation failed:
Invalid length for parameter ElasticsearchDestinationConfiguration.TypeName, value: 0, valid range: 1-inf`
Here is when TypeName is removed:
`[chinshaw@build4 aws]$ grep TypeName p00000012.json 
[chinshaw@build4 aws]$ aws firehose create-delivery-stream --delivery-stream-name p00000012 --delivery-stream-type DirectPut --cli-input-json file://$PWD/p00000012.json --profile psledeng
Parameter validation failed:
Missing required parameter in ElasticsearchDestinationConfiguration: "TypeName"`

The beginning of the file in question....
`{
    "ElasticsearchDestinationConfiguration": {
        "RoleARN": "<redacted>",
        "DomainARN": "<redacted>",
        "IndexName": "p00000012-sensors",
        "TypeName": "document",
        "IndexRotationPeriod": "OneDay",
...
}`
aws --version 
aws-cli/1.11.133 Python/2.7.5 Linux/4.10.10-1.el7.elrepo.x86_64 botocore/1.9.2

Also confirmed failure occurs with:
aws-cli/1.16.250 Python/3.7.4 Darwin/19.0.0 botocore/1.12.240

Please let me know what text is required to create a firehose delivery stream using the CLI as this is impacting our customer deployment system.

**Comment by troydieter** [comment]
Also facing this issue when deploying through a CloudFormation stack - please advise.

**Comment by PSChrisHinshaw** [comment]
Try updating to the latest version of aws-cli.  I believe that fixed the problem I was running into.

**Comment by troydieter** [comment]
Hi,

We are deploying this through a serverless stack, in this case being a
cloudformation resource.

We opened a support case with AWS who recommended we downgrade to ES 6.8.

In my opinion, a cop-out for not supporting a handler for type not being
supported in 7.1.

**Comment by PSChrisHinshaw** [comment]
Copy/paste from our AWS support ticket:
Turns out the version of the aws cli tool was older.  Upgraded to the latest (1.16.304), and the error no longer occurs in our process

**Comment by jtmichelson** [comment]
@troydieter you can use CF for ES 7.1, on your Firehose delivery stream leave the TypeName field, CF will fail if it's missing, but set it to an empty string (`TypeName: ''`).

**Comment by kdaily** [comment]
Looks like this is resolved with a newer version of the AWS CLI. @PSChrisHinshaw please reopen if it reoccurs!
