### ISSUE TITLE
How to determine that a run would have succeeded with --dry-run option in bash script?

### ISSUE THREAD

**Issue by wfeng-fsde** [aws/aws-cli#4698]
In my bash script that will run in user data when a ec2 instance boots up, I need to parse the result of a `--dry-run` to determine that the command would hav succeeded if it were not a dry run. For now I can only tell that it errored out by the error message if I run it manually:

    $ a=$(aws --region us-west-2 --profile My-Profile ec2 create-volume --availability-zone us-west-2a --encrypted --size=8 --volume-type=gp2 --dry-run)
    
    An error occurred (DryRunOperation) when calling the CreateVolume operation: Request would have succeeded, but DryRun flag is set.
    $ echo $?                 
    255
    $ echo $a
    
with a return code of 255. In my bash script, I have no idea how to determine whether it would have succeeded or not.

**Comment by joguSD** [comment]
Considering this feature is implemented service side the exception that comes back is from the service. This also means that the RC is the same as any other exception from the service. You'll have to inspect the error message (which gets printed to stderr).
