### ISSUE TITLE
For autoscalling terminate-instance-in-auto-scaling-group --should-decrement-desired-capacity should be optional

### ISSUE THREAD

**Issue by sjones4** [aws/aws-cli#47]
There should be some way to use the terminate-instance-in-auto-scaling-group operation without decrementing the desired capacity of a group.

$ aws autoscaling terminate-instance-in-auto-scaling-group --instance-id i-C60243E1 
usage: aws autoscaling terminate-instance-in-auto-scaling-group
       --instance-id INSTANCE_ID --should-decrement-desired-capacity
aws autoscaling terminate-instance-in-auto-scaling-group: error: argument --should-decrement-desired-capacity is required

$ aws autoscaling terminate-instance-in-auto-scaling-group --instance-id i-C60243E1 --should-decrement-desired-capacity false
Something is wrong.  We have leftover options
['false']

**Comment by cewood** [comment]
Sorry to revisit such an old issue, but is this fix still valid? I'm currently experiencing this same issue with the following version of the cli: aws-cli/1.10.63 Python/2.7.12 Darwin/15.6.0 botocore/1.4.53.

> aws --region eu-west-1 autoscaling terminate-instance-in-auto-scaling-group --instance-id someinstancehere --should-decrement-desired-capacity
> 
> An error occurred (ValidationError) when calling the TerminateInstanceInAutoScalingGroup operation: Currently, desiredSize equals minSize (4). Terminating instance without replacement will violate group's min size constraint. Either set shouldDecrementDesiredCapacity flag to false or lower group's min size.

**Comment by zerolaser** [comment]
@garnaat I got the following error when trying to terminate an instance in asg which has min size = desired capacity. Should it also have an option of decreasing the min size as well?
>Currently, desiredSize equals minSize. Terminating instance without replacement will violate >group's min size constraint. Either set shouldDecrementDesiredCapacity flag to false or lower >group's min size
