### ISSUE TITLE
External Account Support

### ISSUE THREAD

**Issue by pb-clckwrk** [aws/aws-cli#4706]
I can see the accounts within my organisation listed when I login. 

But external AWS accounts that have been setup within AWS SSO are not appearing in my list of available accounts. Will external accounts also be available in v2?

**Comment by jamesls** [comment]
I think that would require support from the SSO service.  The API call we're making to get a list of accounts only accepts the access token as part of the call: https://docs.aws.amazon.com/cli/latest/reference/sso/list-accounts.html  There's no other parameters I can see where we can request other AWS accounts.  I'd suggest asking on the SSO forums to request this feature from the service: https://forums.aws.amazon.com/forum.jspa?forumID=277

Let me know if you have any other questions.
