### ISSUE TITLE
S3 Select doesn't support offset?

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-cli#4721]
I was querying a simple CSV file and it seems S3 Select doesn't support `offset`? 

```
SELECT * from s3object s limit 5, 10 
```
If that's true - It's not really useful feature for production if we can't query a large CSV file with offset/limit. Because let's say if I want to read the rows 5-10 then I'd need to read all rows...which will cost unnecessary read/scan and slow processing. 

![image](https://user-images.githubusercontent.com/6106479/69910787-f9cd6b00-1436-11ea-852c-0c4f31745532.png)

**Comment by joguSD** [comment]
The CLI doesn't have control over what clauses are support in the provided queries. You'll need to reach out to the S3 select service team by contacting [AWS Support](https://console.aws.amazon.com/support/home#/) or by creating a thread on the [S3 forums](https://forums.aws.amazon.com/forum.jspa?forumID=24).
