### ISSUE TITLE
Support `--s3-endpoint-url` argument to `cloudformation package`

### ISSUE THREAD

**Issue by miron4dev** [aws/aws-cli#4727]
I would like to deploy a SAM application to localstack.
I execute the command 
```
aws cloudformation package \
    --output-template-file packaged.yml \
    --endpoint-url http://localhost:4581 \ 
    --profile localstack \
    --s3-bucket my-bucket \
    --template-file template.yaml
```

but get 

> Unable to upload artifact XXX referenced by CodeUri parameter of XXX resource.
> An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

because it requests real S3 instead of using the local one.

I need an additional option like `--s3-endpoint-url` to solve this issue.

There is https://github.com/aws/aws-cli/pull/3309 PR, but it was not checked for a year.
See also https://github.com/localstack/localstack/issues/1783

**Comment by joguSD** [comment]
Marking this as a feature request. If you'd like to see this feature please thumbs up the opening comment so this request can be appropriately prioritized.

**Comment by whummer** [comment]
Thanks @joguSD , looks like we currently already have a significant number of thumbs ups (41 at this point). What is the threshold for getting this issue prioritized in one of the upcoming releases? 

In general, this is currently blocking a fairly large user base of LocalStack users from upgrading their AWS CLI to the latest version. Would be great to see this getting picked up.

Thanks a lot!

**Comment by whummer** [comment]
FYI - we integrated this change directly into the `awslocal` command line for now, as a temporary workaround until this PR is merged: https://github.com/aws/aws-cli/pull/3309 Thanks

**Comment by kdaily** [comment]
Hi everyone,

Thank you for your patience, and I apologize that it's taken so long to get this reviewed. We're making some changes to our community contribution process to provide more transparency and make community contributions successful.

The PR linked to this issue should be reviewed within the next couple weeks as we work through all open pull requests to see where they fall in our newly proposed contribution process.

You can read more about the changes to the contribution process [here](https://github.com/aws/aws-cli/pull/6828).

**Comment by tim-finnigan** [comment]
Hi all - thanks again for your patience. Per this [recent announcement](https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/) you can now specify the endpoint to use for all service requests through the shared configuration file and environment variables, as well as specify the endpoint URL for individual AWS services.

To start using this feature, install the AWS CLI >=1.29.0 or >=2.13.0. 

To read more about this feature, see the documentation page "Service-specific Endpoints" in the AWS SDKs and Tools Reference Guide:

https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html
