### ISSUE TITLE
cliV2 install process broken in MacOS Catalina

### ISSUE THREAD

**Issue by AntoniosHadji** [aws/aws-cli#4731]
Catalina's new security measures ask for permission for every library when trying to install aws cliV2.
I got about 5 in before it seemed like it was going to go through the entire python library file by file.

**Comment by jamesls** [comment]
This is a known issue that we plan on addressing before we GA CLI v2.  This is being tracked here: https://github.com/aws/aws-cli/issues/4737.  Let's track this over in that issue.
