### ISSUE TITLE
aws ebs subcommands missing

### ISSUE THREAD

**Issue by rplute** [aws/aws-cli#4733]
Per, https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html, and with the newest AWS CLI.

```bash
$ aws ebs list-snapshot-blocks --region us-west-2 --snapshot-id <SNAPSHOT_ID> --starting-block-index 1000 --max-results 100

Invalid choice: 'ebs', maybe you meant:

  * es
```

**Version:**

```bash
$ aws --version
aws-cli/1.16.295 Python/2.7.10 Darwin/18.6.0 botocore/1.13.31
```

**Comment by bisdavid** [comment]
These commands are VERY new.  I could repro your issue with 1.16.295, but the command is there with 1.16.296.  Please upgrade to latest build and then let us know if you're still having issues.

I hope this helps!

**Comment by rplute** [comment]
Hi, @bisdavid , pulled the newest release and validated. Thanks!
