### ISSUE TITLE
[V2]Using CLIv2 with Azure SSO

### ISSUE THREAD

**Issue by elmidwill** [aws/aws-cli#4734]
I attempted to use CLI2 with SSO for Azure AD, and I get the following error:

Hmmm… can't reach this pageIt looks like the webpage at https://d-0123456790.awsapps.com/start/?clientId=**(Removed The Client ID)** might be having issues, or it may have moved permanently to a new web address.

Is this suppose to work with Azure AD? It would be nice if it did, since our SecOps department won't allow us to use CLI without MFA.

**Comment by mattcharlton** [comment]
I'm also struggling with this.  I've got an azure tenant ID, an azure app ID, and at the moment I'm having to use a 3rd party tool for azure/aws login. 

We've got a unique setup in that our main org account isn't the one that has all the IAM config in it - that's off in a standalone user management account with trust back to the org account and trust from all of our project/team accounts back to both.  

I can't enable AWS SSO because it wants to use the main org account rather than my user management one.

**Comment by elmidwill** [comment]
Apparently CLIv2 now supports external SSO providers, but I don't see this option when running aws2 configure soo, or the aws2 configure wizard. How do I provide external SSO providers, and what information is needed.

**Comment by sethbacon** [comment]
Follow this: https://aws.amazon.com/blogs/aws/the-next-evolution-in-aws-single-sign-on/
And then this: https://aws.amazon.com/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/
Unfortunately, this has to be configured through AWS SSO in the master org account. However, you can assign permission sets to your other accounts and control access that way. Basically, this method does away with needing to manage IAM users in a separate account for anything but service accounts/service linked roles. All the IAM policies are managed as an SSO permission set that is assigned per group/user and per account. When you provision the permission set, the policy is magically deployed to the specified account. You can use other external idps also, the first article above just describes the steps for Azure.

**Comment by elmidwill** [comment]
@sethbacon The issue I am facing is not setting up SSO for Azure with AWS, as we already have that setup, and it has been working fine for months. The issue is getting CLI to use MFA via SSO. Neither of those document link address that issue

**Comment by elmidwill** [comment]
> I'm also struggling with this. I've got an azure tenant ID, an azure app ID, and at the moment I'm having to use a 3rd party tool for azure/aws login.
> 
> We've got a unique setup in that our main org account isn't the one that has all the IAM config in it - that's off in a standalone user management account with trust back to the org account and trust from all of our project/team accounts back to both.
> 
> I can't enable AWS SSO because it wants to use the main org account rather than my user management one.

What are you using for the SSO start URL? and where did you get it from?

**Comment by jamesls** [comment]
Which part of your workflow requires MFA?  MFA when logging in through your IdP or MFA required as part of the policy when assuming an IAM role?  If it's the latter, the SSO GetRoleCredentials API doesn't support an MFA token (https://docs.aws.amazon.com/cli/latest/reference/sso/get-role-credentials.html) so we're blocked on adding CLI support until the service supports it.

**Comment by elmidwill** [comment]
@jamesls MFA is required when logging into IdP provider, which in this case is Azure's myapp portal. Once I am there I have a link to Azure that does SSO to any of the various accounts I have access to. How would I go about setting up AWS CLIv2 to work with Azure.

**Comment by marcelboettcher** [comment]
Hey @elmidwill,

did you get it working? From this issue it seems possible if configured correctly: https://github.com/aws/aws-cli/issues/4738

I would expect the aws2 cli to direct you to the azure ad login in the browser and then redirect to aws sso to allow the cli to access sso on you behalf.

Thanks!
Marcel

**Comment by ntkach** [comment]
https://aws.amazon.com/blogs/developer/aws-cli-v2-now-supports-aws-single-sign-on/ isn't terribly helpful.  It only shows you how to use this v2 cli with plain aws sso.  In this case we're using Azure for sso.

**Comment by samtarplee** [comment]
I know this is an old issue, but has there been any progress on it, or can it be added as a feature request?

**Comment by kdaily** [comment]
Hi @samtarplee,

There has not been any work on this. Marking as a feature request.

**Comment by tim-finnigan** [comment]
AWS IAM Identity Center is now the successor to SSO per this documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html.

For Azure AD specifically I think this is the documentation you should refer to: https://docs.aws.amazon.com/singlesignon/latest/userguide/azure-ad-idp.html.

Please let us know if that addresses your use case or if there's anything you wanted to follow up on regarding this. Thanks!
