### ISSUE TITLE
how can i list all the snapshot with no tags in AWS and how to list snapshots using ami-id

### ISSUE THREAD

**Issue by durgalaxmi89** [aws/aws-cli#4735]
how can i list all the snapshot with no tags in AWS and how to list snapshots using ami-id

the following command is not working

aws ec2 describe-snapshots --query "Snapshots[*].{ID:SnapshotId,Time:StartTime,Name:Tags[?Key==`null`]}" --owner-ids <Account-id>

**Comment by kdaily** [comment]
I think this should workL

```aws ec2 describe-snapshots --query 'Snapshots[? ! not_null(Tags)].[ID:SnapshotId,Time:StartTime,Name:Tags]'```
