### ISSUE TITLE
Support for IdP plugins for browserless logons

### ISSUE THREAD

**Issue by deejvince** [aws/aws-cli#4736]
I would like to see support for 3rd party IdPs in SSO Logon, which will enable customers to select from a list / write their own plugins that integrate with IdPs to support browserless logon flows.
These plugins will simplify integration with the IdP authentication page and allow for programmatic access use cases.
The idea is to let the user securely store  their access credentials (i.e. secrets manager / parameter store) and the plugin will interact with the IdP authentication page and submit these on behalf of the user, then the SAML assertion will be attained from the IdP and forwarded to AWS SSO so that CLI will be able to seamlessly logon.

**Comment by jamesls** [comment]
We recently announced support for external IdPs for SSO: https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-your-identity-source-idp.html.

Let me know if you have any other questions.
