### ISSUE TITLE
[v2] “aws2” cannot be opened because the developer cannot be verified. MacOS Catalina

### ISSUE THREAD

**Issue by furikake** [aws/aws-cli#4737]
I work in an organisation that has Mac MDM.  The security policy doesn't allow unsigned apps to run.

The only way to get it running is to do a horrible hack (which gets remediated eventually by MDM)

```
sudo spctl --master-disable
```

Trying to allow the app via "System Preferences" -> "Security & Privacy" -> "Allow apps downloaded from" doesn't work as it seems every package/module needs an approval.

Example of what you see when you try to install `aws2` or run it.

<img width="454" alt="Screen Shot 2019-12-05 at 10 05 40 am" src="https://user-images.githubusercontent.com/304671/70189607-d9a7ef80-1747-11ea-84aa-e80ea7b5d6df.png">

Unlike other apps that only require one approval, we need to approve Python and all the packages/modules used.

<img width="672" alt="Screen Shot 2019-12-05 at 9 57 59 am" src="https://user-images.githubusercontent.com/304671/70189618-e0cefd80-1747-11ea-8294-e89028a22907.png">

<img width="479" alt="Screen Shot 2019-12-05 at 9 57 01 am" src="https://user-images.githubusercontent.com/304671/70189631-e75d7500-1747-11ea-9798-6c8f53646e37.png">

The error we see when your patience runs out or the approval doesn't stick for some reason

<img width="2035" alt="Screen Shot 2019-12-05 at 9 58 44 am" src="https://user-images.githubusercontent.com/304671/70189637-ed535600-1747-11ea-9516-cd1a241b23d9.png">

Can you please sign `aws2` so that we can run it without disabling security features?  I can't do this anyway due to company policies.

**Comment by jamesls** [comment]
Absolutely, we plan on addressing this before we go GA with CLI V2.

**Comment by furikake** [comment]
I just updated to and it runs successfully now.  Is this now signed?

```
❯ aws2 --version
aws-cli/2.0.0dev3 Python/3.7.4 Darwin/19.2.0 botocore/2.0.0dev2
```

**Comment by kyleknap** [comment]
The exe's in the mac executable installer are not signed still. I'm not sure why gatekeeper is not flagging them. However, we did recently launch a PKG and will be going forward with this installation mechanism for mac. This is both signed and notarized so you should not be getting the warning anymore. Here is the link for installation instructions: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html. Let us know how it works!

**Comment by furikake** [comment]
@kyleknap thanks for that. Installed and it's working. I can even delete my workarounds for EKS. 

```
❯ which aws
/usr/local/bin/aws

❯ aws --version
aws-cli/2.0.0dev5 Python/3.7.4 Darwin/19.2.0 botocore/2.0.0dev4
```
