### ISSUE TITLE
Issue signing in with SSO using Azure AD as external identity provider.

### ISSUE THREAD

**Issue by devopsdream** [aws/aws-cli#4738]
When using SSO with AzureAD as external identity provider I get the error below.
`An error occurred (InvalidRequestException) when calling the GetRoleCredentials operation: User attribute: ${user:email} is empty. Please check with your administrator`

**Comment by jamesls** [comment]
I don't have access to an Azure AD that I can test this with, but have you seen the blog post and setting up Azure AD with AWS SSO? https://aws.amazon.com/blogs/aws/the-next-evolution-in-aws-single-sign-on/.  

That error you're seeing is coming back from the SSO service itself so I'm not sure if there's anything we can do in the CLI.  I'd confirm in the "Users" tab on the SSO console that there's an email address associated with the user, but it sounds like the user identities aren't syncing.  There's also some info on confirugin AzureAD for SSO access here that might help: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/what-is-single-sign-on

**Comment by devopsdream** [comment]
I can confirm the email address field was not getting synced from azureAD

**Comment by marcelboettcher** [comment]
@devopsdream I want to use aws2 cli with Azure AD and AWS SSO as well.
If I setup the Azure AD and AWS SSO connection and sync correctly, does the aws2 cli direct me correctly to Azure AD Login and redirect to AWS SSO to allow AWS cli to access AWS SSO (clientToken and accessToken)?

From what I understood you just had a problem with missing e-mail adresses, but in general the aws2 cli was able to receive credentials, right?

I still wait for our Azure AD, so I cannot test it right now.

Thanks!
