### ISSUE TITLE
Cannot seem to get CloudFront metrics from CloudWatch

### ISSUE THREAD

**Issue by alexkeramidas** [aws/aws-cli#4740]
Not sure if this is general but for a couple of weeks now I cannot get CloudWatch metrics from the CLI (or any other AWS SDK). 

Example command:

```aws cloudwatch get-metric-statistics --start-time 2019-12-08T08:00:00Z --end-time 2019-12-08T18:00:00Z --namespace "AWS/CloudFront" --statistics Sum --period 300 --metric-name Requests --dimensions Name=DistributionId,Value=TheDistributionID```

I also tried the following:

- adding the dimension Name=Region,Value=Global
- adding --region us-east-1
- removing dimensions and region altogether

additionally the output of ```aws cli list-metrics``` while it produces a hefty 90000 line output, there is no sign of the "AWS/Cloudfront" namespace in it.

anyone with the same issue?

any ideas?

**Comment by alexkeramidas** [comment]
Ah bummer, Just occured to me, the list metrics command needs the --region us-east-1 for listing cloudfront stuff

suspecting that

` aws cloudwatch list-metrics --region us-east-1`

will list the distributions

**Comment by alexkeramidas** [comment]
However there seems to be something going wrong. Will investigate further and report. Sorry for the wrong spam.

**Comment by Dmitrii-I** [comment]
I struggled with same issue. Your tip of including `--region us-east-1` helped. It is annoying that one must have this AWS idiosyncratic knowledge that global region means us-east-1.

**Comment by psujit775** [comment]
Sharing in case someone needs it for telegraf cloudwatch exporter.

```yaml
[[inputs.cloudwatch]]
  region = "us-east-1"
  period = "1m"
  delay = "2m"
  interval = "1m"
  namespace = "AWS/CloudFront"
  [[inputs.cloudwatch.metrics]]
    names = [
      "TotalErrorRate", "Requests", "BytesUploaded", "BytesDownloaded",
      "5xxErrorRate", "4xxErrorRate"
    ]
    statistic_include = ["average", "minimum", "maximum", "sum"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "Region"
      value = "Global"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "DistributionId"
      value = "*"
```
