### ISSUE TITLE
Is there a way to do login programatically. We need to do this from a script to be able to connect to k8s cluster created in AWS control tower managed account.

### ISSUE THREAD

**Issue by danushkaf** [aws/aws-cli#4741]
Is there a way to do login programatically. We need to do this from a script to be able to connect to k8s cluster created in AWS control tower managed account.

_Originally posted by @danushkaf in https://github.com/aws/aws-cli/issues/3447#issuecomment-563168671_

**Comment by jamesls** [comment]
Not as far as I'm aware.  I'm not super familiar with AWS control tower but if you're using EKS for k8s, could you use IAM ROles with the OIDC integration?  All SDKs and the AWS CLI support this credential provider? https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

**Comment by danushkaf** [comment]
> Not as far as I'm aware. I'm not super familiar with AWS control tower but if you're using EKS for k8s, could you use IAM ROles with the OIDC integration? All SDKs and the AWS CLI support this credential provider? https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

Seems This is about accessing another accounts aws account via cli from a pod. But what I want to achieve is get access to kubectl from the master account's user. [1] works well if we are doing only aws things. But we need kubectl access and its not accessible from aws cli. For me it seems a bug of aws cli.

[1] https://controltower.aws-management.tools/required/cttasks/#1-2-programmatic-access

**Comment by alangford** [comment]
I'm currently wanting to do the same. I have a build terraform user in Active Directory that is hooked up to AWS SSO. I would like to programmatically login as that user using a bash script during build or deploy time. I could do this with IAM, But I'd rather not have to manage any user using IAM

**Comment by tarasrng** [comment]
I've implemented an app for automated login. It still uses CLI and browser, but at least no manual job is needed
https://github.com/tarasrng/aws-sso-credentials-fetcher

**Comment by alangford** [comment]
Any update on this?

**Comment by tim-finnigan** [comment]
Per [this comment](https://github.com/aws/aws-cli/issues/5301#issuecomment-1088075473) in a related issue a `--no-browser` parameter was added for `sso` commands. Does that address the use case here? If not then perhaps this should be combined with https://github.com/aws/aws-cli/issues/5061 going forward.
