### ISSUE TITLE
aws s3 ls - Grep and Wildcard Filtering is needed

### ISSUE THREAD

**Issue by animetauren** [aws/aws-cli#4743]
It is not possible to use **_aws s3 ls_** to filter results by either using Grep or any other form of wildcard filtering.

When using this command: `aws s3 ls s3://examplebucket/ --recursive | grep *.pdf` the result is always empty.

Can there please be support for Grep or wildcard support under the **_ls_** argument. 

This or add cross support for _**--exclude**_ or **_include_** commands that are available in `aws s3 mv` and `aws s3 cp`

**Comment by jamesls** [comment]
Can you elaborate on what you mean by not being able to filter the results using grep?  Keep in mind that with grep you'd need to use a regex, not the wildcard expansion from the shell, so if you wanted any file that ended in pdf you could use something like:

```
$ aws s3 ls s3://bucket/ --recursive | grep '\.pdf$'
```
