### ISSUE TITLE
External ID validation constraints are more restrictive than API

### ISSUE THREAD

**Issue by ixe-la** [aws/aws-cli#4745]
In trying to supply a single character External ID via the `external_id` parameter to a role parameter as described at [1], I got the following errors:

`An error occurred (ValidationError) when calling the AssumeRole operation: 1 validation error detected: Value '%20' at 'externalId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@:\/-]*`

and

`Parameter validation failed:
Invalid length for parameter ExternalId, value: 1, valid range: 2-inf`

These constraints (or the constraints described by the errors at least) are more restrictive than was is described in the API documentation at [2] which states `This value can be any string, such as a passphrase or account number.` 

Version: `aws-cli/1.16.102 Python/2.7.16 Linux/4.14.154-128.181.amzn2.x86_64 botocore/1.12.92`

[1] https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html
[2] https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html

**Comment by jamesls** [comment]
The first error you're getting is an error returned from the sts service, not from the CLI so the service is rejecting the request.

The API docs also state that the min length must be 2 (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html).  I don't think there's anything we can do in the CLI.  Have you been able to use an external ID of a single character in any other tools/sdks/console?

**Comment by paulgb** [comment]
There is also a mismatch between the AWS Console and the docs:

<img width="867" alt="image" src="https://github.com/aws/aws-cli/assets/46173/ac0e462a-29bb-48c0-99d7-ef47cc5403d4">

vs.

<img width="1184" alt="image" src="https://github.com/aws/aws-cli/assets/46173/1613594f-d3cc-4e59-8443-bb7a738e3ae8">
