### ISSUE TITLE
completion: NameError when only providing a single argument to awscli.completer

### ISSUE THREAD

**Issue by hoelzro** [aws/aws-cli#4750]
For example:

```
$ python -m awscli.completer 'aws '
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/awscli/completer.py", line 146, in <module>
    print(complete(cmdline, point))
NameError: name 'point' is not defined
```

I'm assuming that if only a single argument is provided, the module might want to default to the last index in the command line string?  If so, I'd be happy to whip up a PR to do that!

**Comment by jamesls** [comment]
Are you seeing that behavior when using the tab completion directly in the shell?  The completer wasn't really intended to called directly like that, but if you are getting a stack trace when configuring the completer via `complete -C aws_completer aws` then yes I'd say this is a bug.  However, I'm not seeing this behavior:

```
$ complete -C aws_completer aws
$ aws <TAB>
Display all 219 possibilities? (y or n)
```

**Comment by hoelzro** [comment]
It's only when I invoke `awscli.completer` directly - I'm interested in using the module for my own custom completion, and [this line](https://github.com/aws/aws-cli/blob/3dfbd7ee59a0ac008acbcc0164ea98feb33c9771/awscli/completer.py#L141) of code seemed to imply that _something_ should get assigned to `point` if you only provide a single argument.

**Comment by joguSD** [comment]
We don't really intend for this module (or any of the AWS CLI) to be used programmatically like this.

Could you expand on what you mean by 'my own custom completion'?

**Comment by hoelzro** [comment]
Well, I was wondering if I could improve upon the speed of zsh completions, so I wrote a custom completion function [here](https://github.com/hoelzro/zsh-config/blob/master/Completion/_aws) that uses the completer module to load services/method calls/options into zsh variables rather than shelling out to Python all of the time.

**Comment by kdaily** [comment]
Hi @hoelzro, is this still an issue for you?
