### ISSUE TITLE
synth and cloudformation parameters

### ISSUE THREAD

**Issue by nicl** [aws/aws-cli#4759]
Hey all, CDK is great so thanks!

This is more to document something that surprised me, but perhaps it is problem for others too.

I've been using `synth` to output cloudformation that I can then integrate with an internal build tool we have. This was working great until I added a `logRetention` property for my lambda - see https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html.

Turns out this requires a lambda behind the scenes, which CDK is happy to create but also introduces asset parameters like so:

```
AssetParameters03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1fS3BucketCAC9923E:
    Type: String
    Description: S3 bucket for asset "03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1f"
  AssetParameters03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1fS3VersionKey2FA48834:
    Type: String
    Description: S3 key for asset version "03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1f"
  AssetParameters03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1fArtifactHash6DF6DE44:
    Type: String
    Description: Artifact hash for asset "03918990104d8973acd2ad0abe022844192fcce618cf74f7734a7077f4111d1f"
```

Of course, our internal build tool has no idea about these parameters/what to do with them.

Are there any guidelines of what properties can safely be used with synth without introducing this kind of thing?

Thanks.

**Comment by jamesls** [comment]
Hi, thanks for the interest in the CDK!  This is the issue tracker for the AWS CLI, I'd suggest asking the team over at https://github.com/aws/aws-cdk.
