### ISSUE TITLE
Feature Request: QuickSight - create and view scheduled report email distribution.

### ISSUE THREAD

**Issue by rob-mckenzie** [aws/aws-cli#4762]
We have a growing number of dashboards that have scheduled report email distributions with more on the way.  It would be really helpful if the AWS CLI / API enabled programmatic way to create / update / view scheduled report email distributions.

**Comment by joguSD** [comment]
To support this in the AWS CLI we would need the QuickSight service team to provide APIs for these features. I would try reaching out via [AWS Support](https://console.aws.amazon.com/support/home#/) or opening a thread on the [QuickSight forums](https://forums.aws.amazon.com/forum.jspa?forumID=246).
