### ISSUE TITLE
Support resuming interrupted downloads in s3 sync

### ISSUE THREAD

**Issue by CMCDragonkai** [aws/aws-cli#4767]
Is there an option to enable resumed downloads after you interrupt or cancel the `aws s3 sync` command?

**Comment by joguSD** [comment]
Depending on what you mean, this is already more or less the behavior. For any particular object/file that has been downloaded completely it won't be re-downloaded (assuming no changes). 

If you mean resuming a downloaded of a particularly large object/file via `aws s3 sync` then no, there is no way to enable this.

**Comment by CMCDragonkai** [comment]
Yes I would like to be able to resume large downloads of single files. Are there any tools that can do this and also combine with directory sync?

On 18 December 2019 09:12:49 GMT+11:00, joguSD <notifications@github.com> wrote:
>Depending on what you mean, this is already more or less the behavior.
>For any particular object/file that has been downloaded completely it
>won't be re-downloaded (assuming no changes). 
>
>If you mean resuming a downloaded of a particularly large object/file
>via `aws s3 sync` then no, there is no way to enable this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/aws/aws-cli/issues/4767#issuecomment-566772644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joguSD** [comment]
I'm not aware if there are any other tools that can support pausing/resuming directory level syncs with per file granularity. I think it makes sense to mark this down as a feature request for `aws s3 sync`.

**Comment by nitrocode** [comment]
You can use `s3cmd sync --continue` using [s3cmd](https://github.com/s3tools/s3cmd)

**Comment by axelson** [comment]
This still is not possible
