### ISSUE TITLE
missing aws-cli iot commands

### ISSUE THREAD

**Issue by zuzana** [aws/aws-cli#4768]
Hi,

I was following official blog [Route data directly from IoT Core to your web services](https://aws.amazon.com/blogs/iot/route-data-directly-from-iot-core-to-your-web-services/#)

but all aws cli iot commands mentioned in that blog 

end up with following errors:

```
$ aws iot list-topic-rule-destinations --region us-east-1

aws: error: argument operation: Invalid choice, valid choices are:
```

```
$ aws iot create-topic-rule --rule-name test_http_action --topic-rule-payload file://payload.json --region us-east-1

Parameter validation failed:
Unknown parameter in topicRulePayload.actions[0]: "http", must be one of: dynamoDB, dynamoDBv2, lambda, sns, sqs, kinesis, republish, s3, firehose, cloudwatchMetric, cloudwatchAlarm, elasticsearch, salesforce, iotAnalytics, iotEvents, stepFunctions
````
Tried both:

```
aws-cli/1.16.230 
aws-cli/2.0.0dev2
```

Are these CLI commands not available yet? 

Thanks.

**Comment by joguSD** [comment]
`list-topic-rule-destinations` was added in v1.16.285 of the CLI.

V2 is lagging behind V1 of the AWS CLI in terms of API updates like these, we have a task to merge `develop` back into `v2` to get all of the API updates into v2.
