### ISSUE TITLE
[v2] Allow for storing credentials in system keychain a la aws-vault

### ISSUE THREAD

**Issue by mungoknotwise** [aws/aws-cli#4769]
Simply stated, the aws cli needs to natively support encrypted storage of access key/secret key credentials.

A similar feature request was created back in 2013 (https://github.com/aws/aws-cli/issues/547) and nothing ever got done. I find it incredulous that the cli doesn't support this natively by now. While the user community can rely on external tools like aws-vault, native support in the cli tool should be a given. v2 would be a great place to get this integrated.

**Comment by joguSD** [comment]
While there was a PR referenced in that issue that never got merged we have made some progress to open up credential sourcing. There's also a feature request for this over on botocore where I left a comment about the process provider feature:
https://github.com/boto/boto3/issues/629#issuecomment-350138980

Which can be used to get this functionality without it being directly baked into botocore or the CLI (via something like aws vault).

Seeing as the previous feature request is still open, let's keep this feature request consolidated to that issue so it's easier to track interest. If you would like to see this functionality directly in the CLI please thumbs up this issue: https://github.com/aws/aws-cli/issues/547
