### ISSUE TITLE
Enable to configure more accounts/roles after login with SSO

### ISSUE THREAD

**Issue by herbertgoto** [aws/aws-cli#4777]
After you login with SSO, you need to configure a profile associated to an account and a role. If you want to add another profile, you need to sign in SSO again. 

It would be nice that once you logged in wit SSO, you are able to configure more than one profile using accounts/roles of SSO.

**Comment by joguSD** [comment]
Could you expand on what you mean by add another profile? If you're attempting to configure additional profiles under the same SSO portal you've logged into you shouldn't need to login again when configuring additional profiles.

If you're attempting to configure many profiles from many different portals you'll need to log in once for each portal.

**Comment by herbertgoto** [comment]
using the same SSO Portal, I tried to configure 2 profiles and it send me to the portal to the login twice. 
I have tried to replicate twice and it constantly give the following error (screenshot at the end):

Failed to load resource: the server responded with a status of 400 ()

First time I replicate it, I manage to overcome the previous error. This time it did not happened.

Second time, I am stuck in the 'Failed to load resource' error. I did manage to access with roles I already have configure, but when trying to configure a new one, I get the following error: 

An error occurred (UnauthorizedException) when calling the ListAccounts operation: Session token not found or invalid

<img width="1268" alt="Screen Shot 2019-12-18 at 5 22 21 PM" src="https://user-images.githubusercontent.com/8704017/71128479-48129600-21bb-11ea-8e92-b91363bb564c.png">

**Comment by joguSD** [comment]
Just to be clear, are you using two different set of credentials (username/password) on the same portal? If so, unfortunately we only support logging into one user per portal.

Are you still seeing issues with this?

**Comment by herbertgoto** [comment]
I just downloaded the GA version and the problem remains. I just have one user and one portal. 
I am using SSO as idP. 
This is the version used:
aws-cli/2.0.0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev4

I used chrome and safari. 

![Screen Shot 2020-02-14 at 2 47 49 PM](https://user-images.githubusercontent.com/8704017/74563242-5de1d480-4f3a-11ea-9828-494fec0f91bb.png)

**Comment by pcChristopher** [comment]
I am also very eager to be able to configure 50 accounts and login to aws sso once.  This is my sole reason for wanting v2.  I was hoping to be able to run aws configure sso and have it populate my ~/aws/config with all 50 accounts.

**Comment by kdaily** [comment]
Hi @herbertgoto,

Is this still an issue for you? I could not reproduce it.

@pcChristopher,

Is this still an active feature request of interest for you? If so, I'll open a separate issue, but I'll need some more information on the use case and how this would work. As an example, how would you automate choosing profile names for 50 accounts?

**Comment by herbertgoto** [comment]
@kdaily Issue keeps happening. 
I upgraded to: aws-cli/2.2.4 Python/3.8.8 Darwin/20.4.0 exe/x86_64 prompt/off

**Comment by yannickmorel** [comment]
Any update on this issue? with latest aws cli this problem remains!

**Comment by pulberg** [comment]
Same, using awscli i logged into an acct via sso

`aws sso login --profile someprofilename`

I now need to configure sso access for a new account with a new profile

```
aws configure sso
SSO start URL [None]: https://xxx.awsapps.com/start
SSO Region [None]: us-east-2

An error occurred (UnauthorizedException) when calling the ListAccounts operation: Session token not found or invalid
```

**Comment by kdaily** [comment]
Hi @herbertgoto,

I still cannot reproduce. If you can provide debug logs and the command line steps to reproduce the issue, I can take a further look.

It might be correct what @truongtd6285 suggested. Depending on what you're trying to do (use a different portal, or different user, etc), you may also need to log out of your browser. As noted previously, the SSO configuration only supports one user per portal.

**Comment by kdaily** [comment]
Similar for @yannickmorel and @pulberg - if you can provide debug logs and the steps to reproduce, I'll take a closer look!

**Comment by AlbertMarashi** [comment]
> > aws sso login
> 
> you need to logout the current account first `aws sso logout` then run `aws configure sso` again, should be fine.

i owe you a cup of coffee mate

**Comment by truongtd6285** [comment]
> > > aws sso login
> > 
> > 
> > you need to logout the current account first `aws sso logout` then run `aws configure sso` again, should be fine.
> 
> i owe you a cup of coffee mate

Haha, no worries mate. I did not realized that my simple solution was liked that much until you tagged me in.

**Comment by toky0s** [comment]
> > aws sso login
> 
> you need to logout the current account first `aws sso logout` then run `aws configure sso` again, should be fine.

good solution
