### ISSUE TITLE
`aws codestar-connections` isn't available with the latest awscli

### ISSUE THREAD

**Issue by pranitr** [aws/aws-cli#4780]
According to the new release of CodePipeline with BitBucket as a source support ( https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-list.html ), we can list the connections to my 3rd party repositories by running the below command,

`aws codestar-connections list-connections --provider-type Bitbucket \
--max-results 5 --next-token: next-token` 

But however, I'm not able to get the command `aws codestar-connections` command itself with the latest version of awscli ( aws-cli/1.16.306 Python/3.7.5 Darwin/18.7.0 botocore/1.13.42 ).

**Comment by joguSD** [comment]
This was added in `1.16.307`, which was released earlier today.
