### ISSUE TITLE
ECS  create-capacity-provider does not accept 0 as minimumScalingStepSize

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cli#4781]
I've found a bug in `aws ecs create-capacity-provider`.

`aws ecs create-capacity-provider --name default --auto-scaling-group-provider autoScalingGroupArn="{}",managedScaling=\{status='ENABLED',targetCapacity=100,minimumScalingStepSize=0,maximumScalingStepSize=1\},managedTerminationProtection="DISABLED"`

leads to

```
Invalid range for parameter autoScalingGroupProvider.managedScaling.minimumScalingStepSize, value: 0, valid range: 1-inf
```

In the console it works to set 0 and it also scales to 0.

**Comment by kyleknap** [comment]
It appears that the service's API does not support setting `0` as a value for  `minimumScalingStepSize`. I first disabled our client-side validation:
```
$ aws configure set parameter_validation false
```
Then, I ran the command:
```
aws ecs create-capacity-provider --name default --auto-scaling-group-provider autoScalingGroupArn="arn:aws:autoscaling:us-west-2:0123456789012:autoScalingGroup:f6ed5396-a758-4ae0-ac4c-12264a212da5:autoScalingGroupName/TestGroup",managedScaling=\{status='ENABLED',targetCapacity=100,minimumScalingStepSize=0,maximumScalingStepSize=1\},managedTerminationProtection="DISABLED" --region us-west-2

An error occurred (ClientException) when calling the CreateCapacityProvider operation: The specified minimum scaling step size is invalid. Specify an integer between 1 and 10000 and try again.
```
The error from running that command is coming from the service. I'm not really sure what the console is doing when setting it from there, but the API itself does not permit `0` as a value. It may be worth running a [describe-capacity-providers](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-capacity-providers.html) on the provider created from the console to see what values the console is autopopulating the provider with.
