### ISSUE TITLE
ECS: It is not possible to add a capacity provider to an already existing cluster

### ISSUE THREAD

**Issue by konstantinj** [aws/aws-cli#4782]
I would have thought that works through `aws ecs update-cluster-settings` but obviously it does not. I seems it's only possible to use capacity providers when creating a new cluster.

**Comment by kyleknap** [comment]
@konstantinj Have you looked at the `put-cluster-capacity-providers` command? It looks like this is the command you need: https://docs.aws.amazon.com/cli/latest/reference/ecs/put-cluster-capacity-providers.html

**Comment by konstantinj** [comment]
I've updated awscli yesterday - now I also have this command. Don't know anymore which version I had before but usually I'm updating once a week. Anyway this works now. What's missing now is a command to delete the capacity group again. Also I can't see the created capacity group in the console as long as it's not connected to a cluster. Is that normal?

**Comment by kdaily** [comment]
Hi @konstantinj,

I think the delete command exists too:

https://docs.aws.amazon.com/cli/latest/reference/ecs/delete-capacity-provider.html

As for it's visibility in the console, I'm not sure. Given how it's described in the documentation, that might make sense that it's not visible without being associated with a cluster.

https://docs.aws.amazon.com/AmazonECS/latest/userguide/cluster-capacity-providers.html
