### ISSUE TITLE
S3 Operations and Endpoint URL

### ISSUE THREAD

**Issue by linceaerian** [aws/aws-cli#4783]
Hello,

Is there a problem with Authentication V4 and the use of endpoint_url or is it just me that missing something?

I cannot have a working setting the use S3 operation with a endpoint_url.
I use the following command fine:

```
/usr/local/bin/aws s3 ls s3://template.aerian.fr
2019-12-19 15:14:44     145659 toto
```

But once I set a endpoint url, 

`/usr/local/bin/aws --endpoint-url http://template.aerian.fr s3 ls s3://template.aerian.fr`   

```
An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
```

Also I need to specify the region as variable, AWS_DEFAULT_REGION=eu-west-1, else it default to a wrong one.

The endpoint URL is a CNAME from:

`template.aerian.fr -> template.aerian.fr.s3.amazonaws.com`

When I'm testing from boto3 I get the listing fine:

```python
import boto3

session = boto3.session.Session()

s3 = session.resource(
    service_name='s3',
    aws_access_key_id='AIA',
    aws_secret_access_key='s3kurecey',
    endpoint_url='https://template.aerian.fr',
    verify=False
)

bucket = s3.Bucket('template.aerian.fr')
for obj in bucket.objects.all():
    print(obj.key, obj.last_modified)

```

```bash
python test.py 
toto 2019-12-19 14:14:44+00:00
```

**Comment by kyleknap** [comment]
Would it be possible to include the debug logs from running your command? You can do so by appending `--debug` to the command you ran. Specifically, I want to figure out why you are getting the following error message:
```
An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
```
The ListObjectsV2 API does not generally return `NoSuchKey` exceptions. That is more common with GetObject or HeadObject. So I'm wondering if there is something going on with the serialization of the request.

**Comment by linceaerian** [comment]
Hello @kyleknap 

Thanks for your comment & time.
I already removed the python environment and the bucket configuration I had at that time and changed what I planned to do.

When recreating a venv and trying to reproduce it again, the comportment does not happen anymore, it work fine. (T.T Murphy's law)

/usr/local/bin/aws --endpoint-url http://template.aerian.fr s3 ls s3://template.aerian.fr                          
2020-01-03 13:49:08      91649 2020.gif

Not sure what was the cause.
I'll remove the env again and close the issue.

Regards

**Comment by Cauen** [comment]
I received this same error when I mistakenly set the bucket name in --endpoint-url. ie:

`aws --endpoint-url https://my-endpoint/bucket-name s3 ls s3://bucket-name/folder --recursive`

Error: `An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.`
