### ISSUE TITLE
[V2] Admin rights for Windows installer

### ISSUE THREAD

**Issue by kevin-slaney** [aws/aws-cli#4789]
The Windows msi installer currently requires admin rights on the PC its being installed on, however, I see the Linux installation instructions provide an alternative when the user doesn't have sudo rights. Would it be possible to get a version of the Windows installer that does not require admin rights?

**Comment by kyleknap** [comment]
Makes sense. Marking as a feature request. Another possibility we may explore is generating an executable installer (i.e. the current installers for MacOS and Linux), which would allow you to control the installation path and thus whether admin privileges would be needed.

**Comment by kevin-slaney** [comment]
Many thanks Kyle

**Comment by kdaily** [comment]
Hi @kevin-slaney, I'm going to close this as a duplicate. #4633 was opened just before this and has more activity. Thanks again for filing!

**Comment by dan-petty** [comment]
Still broken
