### ISSUE TITLE
 Could not connect to the endpoint URL: "https://eks.us-east-1.amazonaws.com/clusters/clustername"

### ISSUE THREAD

**Issue by veera2019** [aws/aws-cli#4790]
I am trying to connect my EKS cluster from ec2 instance AWS CLI i ma getting error like 
 **Could not connect to the endpoint URL: "https://eks.us-east-1.amazonaws.com/clusters/clustername"**
aws cli version: **aws-cli/1.16.308 Python/3.6.8 Linux/4.18.0-80.4.2.el8_0.x86_64 botocore/1.13.44**

i am giving below command to update kubeconfig
aws eks --region us-east-1 update-kubeconfig --name clustername

**Comment by veera2019** [comment]
it's urgent basis

**Comment by Loki-Afro** [comment]
@veera2019 Closing the issue without a solution or comment? **How did you resolve your issue?**
