### ISSUE TITLE
Feature Request: Support Cloud9 Connect and run in remote server (SSH)

### ISSUE THREAD

**Issue by tfolbrecht** [aws/aws-cli#4791]
![image](https://user-images.githubusercontent.com/6099765/71426041-075ec500-2672-11ea-9d07-3d47496e64b3.png)

This AWS Cloud9 feature (connect and run in remote server) is not present in the CLI while `create-environment-ec2` is. 

It would be useful, for example in a development workflow that lets you connect to a custom Linux environment.

It would need a different workflow like first returning a cloud9 instance ssh public key (not sure where the key come from, or if it's API accessible) which must then be added to the users box, then creating the actual instance.

Not sure if this is out of scope, this cloud9 feature doesn't seem to be apart of [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html) either

**Comment by kyleknap** [comment]
It would be out of scope from the CLI and CloudFormation perspective. Specifically, Cloud9 would need to support a public API that the CLI and Cloudformation can call out to. I would recommend reaching out to AWS Support of the [Cloud9 forums](https://forums.aws.amazon.com/forum.jspa?forumID=268) for that feature request.

**Comment by tfolbrecht** [comment]
Thanks Kyle!
I'll do that
