### ISSUE TITLE
Unknown Options: /root/elb-logs/  ...not able to sync the logs using bash script

### ISSUE THREAD

**Issue by krishnakaws** [aws/aws-cli#4795]
Hi there, 

I am using a bash script to download the elb logs for some specific date...but when I put the below-mentioned command in the script I seeing the "Unknown Option: /root/elb-logs/" 
**aws s3 sync s3://$log_bucket/AWSLogs/$account_id/elasticloadbalancing/$region/$y/$m/$d/ $dir/ --region $region**
assigned variable 
dir =`pwd`

fetching region, account_id bucket name all works fine but as destination $dir giving error "Unknown Option: /root/elb-logs/"

could anyone please let me know what I am doing wrong here.

**Comment by kyleknap** [comment]
@krishnakaws Could you post the debug logs from the command you ran? This will tell us the exact arguments that are being used on the command line after bash replacement. You can do so by appending `--debug` to the command you ran. If I were to guess, one the variables you have set includes a space, causing the `sync` command to think there is more than two positional arguments being provided.
