### ISSUE TITLE
feature req: --size=x filter

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-cli#4796]
Would be great if s3 cli would accept a size (bytes) filter argument. That way I could do a command like 's3 rm on files of 0 bytes only' without having to chain commands.etc (ie https://stackoverflow.com/questions/44687515/deleting-files-from-s3-of-0-bytes)

**Comment by kyleknap** [comment]
Seems reasonable. We'd probably want to expand on it to also include greater than, less than, and size ranges. Marking as a feature request.

**Comment by tooptoop4** [comment]
still issue
