### ISSUE TITLE
Support the use of aws-cli natively within Python

### ISSUE THREAD

**Issue by alanyee** [aws/aws-cli#4798]
Most of what `aws-cli` can do is present in `boto3` for Python, but features such as `aws configure` is not a feature of `boto3`. Using `subprocess` is an alternative in Python if one needs to automate processes of the cli, but based on my testing, using `import awscli` is significantly faster though undocumented and perhaps discouraged. 

Could we get documentation for using `aws-cli` for features that are not present in `boto3`?

**Comment by kyleknap** [comment]
Other than the `configure` command, are there any other features that you would like to use from the CLI codebase?

In general, we do not recommend importing directly from the CLI code as the Python interfaces are not intended to be used as a general library and thus would prefer not to document them. Instead, we have opted toward taking useful functionality and moving them to Python packages that can be consumed as a general library (i.e. `s3transfer`).

**Comment by alanyee** [comment]
For me, `configure` command is the only feature I use from the cli that I cannot emulate through `boto3`.

**Comment by alanyee** [comment]
Also, I would recommend following the PEP 8 style and use `_single_leading_underscore` as a weak "internal use" indicator.

**Comment by kyleknap** [comment]
In general, we try to use the leading underscore notation, but that is more from the perspective of developers of the codebase so we know what methods/classes we can change to make sure we do not break another module/class that may be using a particular class/method.

As of right now, we are not looking to publicly support importing and using abstractions directly from the CLI codebase. So for the `configure` command functionality, can you open a GitHub issue in the boto3 repository so we can track it as a feature request there?

**Comment by alanyee** [comment]
I opened a GitHub issue in the boto3 repo: https://github.com/boto/boto3/issues/2247
