### ISSUE TITLE
[v2] CLI compatibility with SSM/Session Manager?

### ISSUE THREAD

**Issue by pcolmer** [aws/aws-cli#4808]
I'll be honest up-front. I do not know if this is a CLI v2 issue or if that is just exposing something else.

We've started using SSH-over-SSM. Very occasionally, I'll type the `ssh <host>` command and nothing appears to happen. Today, I've been spending some time on looking into this and adding `--debug` to the `aws ssm` SSH ProxyCommand to try and figure out what is going on.

In a nutshell, the debug output from `aws` is identical between a working and non-working session. The only difference is that a working session carries on with the actual SSH output whereas the non-working session just stalls and nothing appears in the output to explain what it is waiting for or why it isn't working.

I thought I had found a way to reproduce it 100% reliably with `aws sso logout` then `aws sso login` but, in trying that again whilst writing this, it no longer seems to be 100% reliable after all.

So it may be a SSM issue instead. I'm not sure. Since `--debug` isn't giving me anything useful to show why it is stalling, I thought I'd still create an issue just in case anyone else has some insight that might help progress this.

**Comment by kdaily** [comment]
Hi @pcolmer,

I apologize for the delay in response.

Is this still an issue for you? I'm not able to reproduce it, so you may be correct that it's an SSM issue.

If it is still an issue, can you provide information about the versions/setup you are using of the AWS CLI?

**Comment by pcolmer** [comment]
@kdaily it is an issue that I experience occasionally but I cannot reliably reproduce it, I'm afraid. As a result, I'm OK with closing this issue.
