### ISSUE TITLE
describe-volumes filter if not contains tag.

### ISSUE THREAD

**Issue by komodin** [aws/aws-cli#4812]
When I try to get the volumes without the tag "noautosnap", I get all the volumes.

I'm currently using this command:
```
aws ec2 describe-volumes --profile backupEC2 --filters "Name=attachment.instance-id,Values=i-xxxxxxxxxxxxxxx" --query 'Volumes[].Tags[?Key!=`noautosnap`]' --output text
```

I get as result:

```
Name    instancename-volume1
Name    instancename-volume2
Name    instancename-volume3
```

And that are the tags of the volume

```
"Tags": [
                {
                    "Key": "Name",
                    "Value": "instancename-volume2"
                },
                {
                    "Key": "noautosnap",
                    "Value": "noautosnap"
                }
            ],
```
I can't found any suitable solution for "if not contains tag".
Any ideas?

Thanks in advance.

**Comment by jeking3** [comment]
This might help:

https://stackoverflow.com/a/42427654

I'd like the same functionality - a filter to match items that do not have a tag.

**Comment by kdaily** [comment]
Hi @komodin,

I think as @jeking3 hinted at, you want something like:

```
aws ec2 describe-volumes --output text --query 'Volumes[?not_null(Tags[?Value == `noautosnap`].Value)] | []'
```
