### ISSUE TITLE
aws elasticache describe-cache-clusters retrieves the nodes not the clusters

### ISSUE THREAD

**Issue by MohamedWaly** [aws/aws-cli#4816]
Hi,
I'm trying  to run the following command and to retrieve the clusters but it only retrieve the nodes. Also, if I specified the cluster name in `aws elasticache describe-cache-clusters --cache-cluster-id <cluster_name>`, it generates the following error:

> An error occurred (CacheClusterNotFound) when calling the DescribeCacheClusters operation: CacheCluster not found:cluster_name

However, it works properly if I replaced the clutser name with a node name.
Is it a misconfiguration in the cli itself, or I'm I doing something wrong?

**Comment by kyleknap** [comment]
This appears to be the error returned by the service. The CLI is only displaying this error from the service. I'd recommend reaching out to the AWS Support or the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=127) on why the service behaves in that particular fashion.

**Comment by prashankprince** [comment]
I am getting similar error while trying 
`aws elasticache modify-cache-cluster \
    --cache-cluster-id $ElasticCacheCluster \
    --engine-version $NewEngineVersion \
    --cache-parameter-group-name $parameter_group_name \
    --apply-immediately`
    
    Error msg - `An error occurred (CacheClusterNotFound) when calling the ModifyCacheCluster operation: CacheCluster not found: Cluster_name`

**Comment by prashankprince** [comment]
> I am getting similar error while trying
> 
> ```
> aws elasticache modify-cache-cluster \
>     --cache-cluster-id $ElasticCacheCluster \
>     --engine-version $NewEngineVersion \
>     --cache-parameter-group-name $parameter_group_name \
>     --apply-immediately
> ```
> 
> ```
> Error msg - `An error occurred (CacheClusterNotFound) when calling the ModifyCacheCluster operation: CacheCluster not found: Cluster_name`
> ```

Fix is to use `modify-replication-group` More details - https://docs.aws.amazon.com/cli/latest/reference/elasticache/modify-replication-group.html
