### ISSUE TITLE
New PyYaml version (py3.7) breaks installation

### ISSUE THREAD

**Issue by dtpryce** [aws/aws-cli#4828]
Newest version of PyYaml from a couple days ago (https://pypi.org/project/PyYAML/5.3/#history) is outside the required version for awscli and installing both causes pip._vendor.pkg_resources.ContextualVersionConflict

https://github.com/aws/aws-cli/blob/develop/setup.py#L48 is where an update might be needed

**Comment by danielhoherd** [comment]
This will require dropping support for python 3.4. The travis logs show:

```
PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.6
```

**Comment by wnkz** [comment]
Python 3.4 has reached end-of-life ; couldn't we drop support for it?
Having PyYaml version up-to-date would allow for awscli and sagemaker package to be installed together at the same time for example.

**Comment by danielhoherd** [comment]
Dropping 3.4 would be a great preparation exercise for [dropping 3.5 later this year when it too reaches EOL](https://devguide.python.org/#status-of-python-branches).

**Comment by dtpryce** [comment]
Looks like we all want it but the linked PR is failing :(
