### ISSUE TITLE
Clarification needed in Docs

### ISSUE THREAD

**Issue by JamieMcKernanKaizen** [aws/aws-cli#4830]
Not a big issue but I was following the [docs](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-resource.html) and I was struggling to rename an API Gateway Resource including the curly braces to pass through the query parameters.

I ended up finding this [answer](https://stackoverflow.com/questions/50416936/aws-apigateway-update-integration-cli-error) which gave me what I needed.

I was just thinking it would be nice to include an example where the user renames a resource including the query parameters in the docs.

**Comment by bisdavid** [comment]
I just updated the source files for that example to include the quotations.  As soon as it makes it thru our publication processes it will be live.  Thanks for finding, solving, and reporting this!

Dave Bishop
Senior Programming Writer

**Comment by JamieMcKernanKaizen** [comment]
Awesome stuff!
