### ISSUE TITLE
Amazon CloudFront additional real-time metrics in Amazon CloudWatch

### ISSUE THREAD

**Issue by piyushsonigra** [aws/aws-cli#4836]
AWS recently released feature in CloudFront to view additional cloudwatch metrics.
aws-cli doesn't have option to enable additional metrics in CloudFront distribution.

Rereferences:
https://aws.amazon.com/about-aws/whats-new/2019/12/cloudfront-realtime-metrics/
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html#monitoring-console.distributions-additional

**Comment by kdaily** [comment]
Hi @piyushsonigra, looking at the documentation it seems that this is now available:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html#monitoring-console.distributions-additional
