### ISSUE TITLE
New docutils 0.16 release goes past pin in awscli and botocore

### ISSUE THREAD

**Issue by ViktorHaag** [aws/aws-cli#4837]
Docutils latest release (0.16) has [dropped support for 2.6 and 3.4](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-16-2020-01-12), and has gone past the version pinned by awscli and boto3.

**Comment by swetashre** [comment]
@ViktorHaag - Thank you for your post. Marking this as enhancement. This issue is related to https://github.com/boto/botocore/issues/1942

**Comment by asford** [comment]
@swetashre Any potential prioritization on this issue? It appears that `docutils` was removed as a botocore dep, do you know if there is a breaking change in docutils `0.16` for `awscli`?

**Comment by nchepanov** [comment]
Interesting in having the ceiling updated too.

**Comment by limburgher** [comment]
This is still relevant.

**Comment by tim-finnigan** [comment]
Linking related tracking issue for updating pinned dependencies: https://github.com/aws/aws-cli/issues/5943

**Comment by tim-finnigan** [comment]
https://github.com/aws/aws-cli/pull/7384 was merged for v2, I don't think the team plans to prioritize increasing the docutils ceiling for v1. Using v2 is recommended and v1 will get deprecated at some point. For further discussion and tracking of issues related to pinned dependencies, I think those should move to https://github.com/aws/aws-cli/issues/5943.

**Comment by nanonyme** [comment]
Does this mean AWS has officially dropped support for awscli v1?

**Comment by tim-finnigan** [comment]
@nanonyme no there will be an official deprecation announcement and roadmap at some point in the future. We can't guarantee when that would be but still recommend using v2 if possible.
