### ISSUE TITLE
broken cfn validate with iam

### ISSUE THREAD

**Issue by dragonfly-net** [aws/aws-cli#4838]
When template creates iam resource, validate says
`aws cloudformation validate-template --template-body file://scriptlets/consul.yaml
    "CapabilitiesReason": "The following resource(s) require capabilities: [AWS::IAM::Role]"`

but capabilities broken
`aws cloudformation validate-template --template-body file://scriptlets/consul.yaml --capabilities CAPABILITY_IAM
Unknown options: --capabilities, CAPABILITY_IAM`

**Comment by swetashre** [comment]
@dragonfly-net - Thank you for your post. To fix the first issue "If your template contains IAM resources, you must specify the CAPABILITY_IAM or CAPABILITY_NAMED_IAM value for this parameter when you use the CreateStack or UpdateStack actions with your template"

And for the second question you are getting this error as ```--capabilities``` is not a supported parameter for validate-template command. 

For more information, see [Acknowledging IAM Resources in AWS CloudFormation Templates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#capabilities).

Hope it helps.
