### ISSUE TITLE
Changing to text output produces multiple results when selecting one element

### ISSUE THREAD

**Issue by kollektiv** [aws/aws-cli#4847]
Changing to text output produces multiple results when selecting one element. Why does changing to `--output text` produce multiple lines in the below command?

CLI Command Executed

```bash
$ aws ssm describe-instance-information --query 'InstanceInformationList[].InstanceId | [0]'
"i-3af18d8a26ab2272e"

$ aws ssm describe-instance-information --query 'InstanceInformationList[].InstanceId | [0]' --output text
i-3af18d8a26ab2272e
i-3496a17402c0a4963
i-3651771ee05d144f6

$ aws ssm describe-instance-information --query 'InstanceInformationList[0].InstanceId'
"i-3af18d8a26ab2272e"

$ aws ssm describe-instance-information --query 'InstanceInformationList[0].InstanceId' --output text
i-3af18d8a26ab2272e
i-3496a17402c0a4963
i-3651771ee05d144f6
```

# AWS CLI Version

```
aws-cli/1.17.0 Python/3.8.1 Darwin/18.7.0 botocore/1.14.0
```

**Comment by bisdavid** [comment]
@kollektiv, This is very likely due to the fact that when you use --output text AND --query, the output is paginated first, and then the query is run against EACH PAGE of the output.  For more information, see the first bullet in the Important note on this page: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter

The workaround is to also include the --no-paginate option on your command line to ensure that the query works on the entire output result set at one time instead of separately on each page of the output.

I hope this helps!

**Comment by grandopener** [comment]
The given workaround does not fix the issue, and the `text` output mode is basically unusable with any query that involves taking the first or last element of a sorted list.  I'll demonstrate below how `--query` with `--output text --no-paginate` still behaves incorrectly.  As of right now, the only usable workaround appears to be always using the `json` output type, and trimming off quotation marks etc. as necessary.

(I'm running through aws-shell on Windows, and verified before posting that I'm using the current most recent version.)  From debugging a session where I had this issue just a few minutes ago:
```
aws> ecr describe-images --repository-name xxx --query "sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]" --output json
"c07c72..."
```
The above, with json output, is the correct answer.
```
aws> ecr describe-images --repository-name xxx --query "sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]" --output text
779d25...
c07c72...
```
As expected, using `--output text` has queried each page of output and produced bogus results, but...
```
aws> ecr describe-images --repository-name xxx --query "sort_by(imageDetails,&imagePushedAt)[-1].imageTags[0]" --output text --no-paginate
779d25...
```
Even with the `--no-paginate` option, the `text` output method still applies the filters in an order that results in an incorrect result.

**Comment by joguSD** [comment]
@bisdavid Is correct. Here's another explanation: https://github.com/aws/aws-cli/issues/3652#issuecomment-530607404

We have another issue that I've marked down as a feature request to add another output format `buffered-text` that behaves like `json` in terms of pagination and query results. See: https://github.com/aws/aws-cli/issues/4618
