### ISSUE TITLE
Typo in CloudWatch help

### ISSUE THREAD

**Issue by tylerapplebaum** [aws/aws-cli#4848]
The example states that the example is for AWS/EC2, but the example shown is AWS/SNS.

Issue is present in at least this version: `aws-cli/1.16.291 Python/3.6.0 Windows/10 botocore/1.13.27`

https://github.com/aws/aws-cli/blob/4ff0cbacbac69a21d4dd701921fe0759cf7852ed/awscli/examples/cloudwatch/list-metrics.rst

```
aws cloudwatch list-metrics help

<output removed>

Examples
********

**To list the metrics for Amazon EC2**

The following example uses the "list-metrics" command to list the
metrics for Amazon SNS.:

   aws cloudwatch list-metrics --namespace "AWS/SNS"
```

**Comment by bisdavid** [comment]
Thanks for reporting this, @tylerapplebaum. I've fixed this in the source, and submitted the correction as a PR to the CLI team. It will be fixed in the first release after PR is merged.

**Comment by tylerapplebaum** [comment]
👍 thanks!
