### ISSUE TITLE
describe-sessions

### ISSUE THREAD

**Issue by oeresundsgruppen** [aws/aws-cli#4851]
Trying to get list of remote desktop sessinons:

aws2 ssm  describe-sessions --state "Active" --region eu-central-1  

returns no sessions  - any idea why ?

**Comment by klaytaybai** [comment]
Thanks for opening an issue.  We'll try to reproduce it.  

This only returns sessions from the past 30 days.  Maybe that is your problem?  Can you please verify that you actually have had active sessions over the past 30 days?

**Comment by oeresundsgruppen** [comment]
Have several sessions daily.
