### ISSUE TITLE
Feature request for ECS to login docker directly

### ISSUE THREAD

**Issue by shigemk2** [aws/aws-cli#4857]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_AWSCLI.html

Command:
```sh
aws ecr get-login --region region --no-include-email
```

Output:
```sh
docker login -u AWS -p password https://aws_account_id.dkr.ecr.us-east-1.amazonaws.com
```

We have docker login command output when executing ecr get-login and we have to execute the ecr get-login's output result. But it's a little troublesome for me because the output command is used only once but the command history remains in login shell.

I want to execute docker login directly when executing ecr get-login.

**Comment by joguSD** [comment]
The `ecr get-login` command has problematic as the docker's command line interface hasn't been particularly stable. Executing the docker command directly was considered, but we ultimately decided not to do this. We recently added `ecr get-login-password` which simply outputs the correctly formatted password for docker to try and decouple from docker's interface.
