### ISSUE TITLE
Lightsail --ca-certificate-identifier missing option

### ISSUE THREAD

**Issue by shivamgulati1991** [aws/aws-cli#4859]
Modification of Lightsail database works with AWS CLI1 to update SSL Certificate, but shows unknown options with CLI2

aws2 lightsail update-relational-database --relational-database-name test --ca-certificate-identifier rds-ca-2019 --apply-immediately
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --ca-certificate-identifier, rds-ca-2019

**Comment by naveenrpay** [comment]
upgrae the aws client

**Comment by klaytaybai** [comment]
Thanks for reporting this.  I have reproduced the problem using upgraded clients.

**Comment by ppshobi** [comment]
same problem repordusable

**Comment by ppshobi** [comment]
Actually, If you upgrade an existing awscli, its not working. But if you uninstall and install again the command works

**Comment by shivamgulati1991** [comment]
Thanks, that's strange.

**Comment by stobrien89** [comment]
It appears the `--ca-certificate-identifier` parameter was added to this operation (in botocore) on 1/2/2020— It's possible a CLI upgrade did not automatically upgrade your botocore version at the time this issue was opened.  Just tested and verified the parameter is working as expected.
