### ISSUE TITLE
ec2 describe-regions functionality doesn't match documentation

### ISSUE THREAD

**Issue by AndreyRainchik** [aws/aws-cli#4866]
From the ec2 describe-regions [documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html), in AWS CLI 1.17.7 the `--all-regions` or `--no-all-regions` flags should indicate whether to display all Regions. When running the command from the CLI in PowerShell, those flags do not exist.

```
PS C:\> aws --version
aws-cli/1.17.7 Python/3.6.0 Windows/10 botocore/1.14.7
PS C:\> aws ec2 describe-regions --all-regions
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --all-regions
```

**Comment by KaibaLopez** [comment]
Hi @AndreyRainchik, 
Thanks for pointing this out!

**Comment by swetashre** [comment]
@AndreyRainchik - Thank you for your post. I am not able to reproduce the issue in my windows machine with the cli version you specified. Please make sure your command is pulling the correct version of cli.
