### ISSUE TITLE
Profile not found error

### ISSUE THREAD

**Issue by kris-mlguy** [aws/aws-cli#4879]
Hi,

I'm trying to access S3 in my AWS account programmatically using Python.
> aws --version
> aws-cli/1.17.9 Python/3.6.9 Windows/10 botocore/1.14.9

An IAM user is created to have full access to S3 and to have access key ID and secret access key. 
There is also ~/.aws/credentials.ini file with contents 

[s3user1]
aws_access_key_id=foo
aws_secret_access_key=bar

and ~/.aws/config.ini file with contents

[s3user1]
region=us-east-1

However, ended up with below error for the code

import boto3
s3_res = boto3.resource('s3')

---------------------------------------------------------------------------
ProfileNotFound                           Traceback (most recent call last)
<ipython-input-3-33e76eea08e4> in <module>
----> 1 s3_res = boto3.resource('s3')

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\boto3\__init__.py in resource(*args, **kwargs)
     98     See :py:meth:`boto3.session.Session.resource`.
     99     """
--> 100     return _get_default_session().resource(*args, **kwargs)
    101 
    102 

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\boto3\__init__.py in _get_default_session()
     78     """
     79     if DEFAULT_SESSION is None:
---> 80         setup_default_session()
     81 
     82     return DEFAULT_SESSION

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\boto3\__init__.py in setup_default_session(**kwargs)
     32     """
     33     global DEFAULT_SESSION
---> 34     DEFAULT_SESSION = Session(**kwargs)
     35 
     36 

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\boto3\session.py in __init__(self, aws_access_key_id, aws_secret_access_key, aws_session_token, region_name, botocore_session, profile_name)
     78         self.resource_factory = ResourceFactory(
     79             self._session.get_component('event_emitter'))
---> 80         self._setup_loader()
     81         self._register_default_handlers()
     82 

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\boto3\session.py in _setup_loader(self)
    118         Setup loader paths so that we can load resources.
    119         """
--> 120         self._loader = self._session.get_component('data_loader')
    121         self._loader.search_paths.append(
    122             os.path.join(os.path.dirname(__file__), 'data'))

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\session.py in get_component(self, name)
    680     def get_component(self, name):
    681         try:
--> 682             return self._components.get_component(name)
    683         except ValueError:
    684             if name in ['endpoint_resolver', 'exceptions_factory']:

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\session.py in get_component(self, name)
    917         if name in self._deferred:
    918             factory = self._deferred[name]
--> 919             self._components[name] = factory()
    920             # Only delete the component from the deferred dict after
    921             # successfully creating the object from the factory as well as

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\session.py in <lambda>()
    153         self._components.lazy_register_component(
    154             'data_loader',
--> 155             lambda:  create_loader(self.get_config_variable('data_path')))
    156 
    157     def _register_endpoint_resolver(self):

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\session.py in get_config_variable(self, logical_name, methods)
    236                 logical_name, methods)
    237         return self.get_component('config_store').get_config_variable(
--> 238             logical_name)
    239 
    240     def _get_config_variable_with_custom_methods(self, logical_name, methods):

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\configprovider.py in get_config_variable(self, logical_name)
    288             return None
    289         provider = self._mapping[logical_name]
--> 290         return provider.provide()
    291 
    292     def set_config_variable(self, logical_name, value):

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\configprovider.py in provide(self)
    385         """
    386         for provider in self._providers:
--> 387             value = provider.provide()
    388             if value is not None:
    389                 return self._convert_type(value)

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\configprovider.py in provide(self)
    446     def provide(self):
    447         """Provide a value from a config file property."""
--> 448         scoped_config = self._session.get_scoped_config()
    449         if isinstance(self._config_var_name, tuple):
    450             section_config = scoped_config.get(self._config_var_name[0])

C:\Program Files\Anaconda3\envs\cloud_env\lib\site-packages\botocore\session.py in get_scoped_config(self)
    335             # exist (even if it's the default profile) otherwise
    336             # we complain.
--> 337             raise ProfileNotFound(profile=profile_name)
    338         else:
    339             return profile_map[profile_name]

ProfileNotFound: The config profile (username) could not be found

**Comment by bisdavid** [comment]
Hi, @kris-miguy, I suspect that the problem is because you gave the profile a specific name (s3user1), yet when you created your s3 client object (s3_res = boto3.resource('s3')) you didn't specify that profile name.  Because you don't specify a profile by name, the boto3.resource('s3') uses the [default] profile, which you might not have defined.  Also, when you specify a profile name other than [default] in the credentials file, it MUST begin with the word 'profile' as in [profile s3user1].

So, to fix this, you must do one of the following:

1. Create a default profile in the files as shown:
.aws/credentials:
```
[default]
aws_access_key_id=foo
aws_secret_access_key=bar

```
and ~/.aws/config
```
[default]
region=us-east-1
````
OR
2.  Invoke a specific profile when you instantiate the s3 client object, as follows:
```
import boto3
session = boto3.session.Session(profile_name='s3user1')
s3 = session.resource('s3')
```
I hope that helps!

**Comment by kris-mlguy** [comment]
Appreciate Dave @bisdavid for your response. I had tried option 1 with default profile with the same code earlier and somehow it didn't work but it's working now. Thanks!!
