### ISSUE TITLE
aws-cli installation v1 request command line developer tools

### ISSUE THREAD

**Issue by ArminDeeg** [aws/aws-cli#4883]
MacOS Catalina
I have the need to install the aws-cli for enduser S3 features.

Using the recommended installation with terminal:

```
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
./awscli-bundle/install -b ~/bin/aws
```

request for installing the command line developer tools.

For enduser which installs our software solutions with our installer is this irritating. Is the a solution to properly install the aws-cli without any user action from an signed and notarized Apple PKG installer ? 

![55C7B](https://user-images.githubusercontent.com/6436037/73267516-81d2b580-41d9-11ea-88b0-0578228a2616.png)

**Comment by KaibaLopez** [comment]
Hi @ArminDeeg ,
I may be misunderstanding the issue a bit here, but you're asking for a way to install the sdk without user interaction beyond the console lines, so you want the macos to not ask for permission to install?
And regarding Apple PKG, I'm afraid the only installation options we provide are listed in the [installation guide](https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html).

**Comment by ArminDeeg** [comment]
> Hi @ArminDeeg ,
> I may be misunderstanding the issue a bit here, but you're asking for a way to install the sdk without user interaction beyond the console lines, so you want the macos to not ask for permission to install?
> And regarding Apple PKG, I'm afraid the only installation options we provide are listed in the [installation guide](https://docs.aws.amazon.com/cli/latest/userguide/install-macos.html).

Hi @KaibaLopez,

I want to point to the developers of the aws-cli installer, that there seems a bug inside the installation process. Cause the AWS-CLI is not for xcode users only. So a normal enduser should not irritated with requests to install apple developer tools to use aws-cli.

The installation guide shows a sudo free installtion on macOS, but it does not work, it requests for apple command line tools, 

So what can I do to install aws-cli in a silent way ?

Armin

**Comment by KaibaLopez** [comment]
So I'm not able to replicate your problem, cli installation should not prompt apple developer tools, but if you're searching for another way to install the cli, I'd recommend doing it through pip.

**Comment by ArminDeeg** [comment]
> So I'm not able to replicate your problem, cli installation should not prompt apple developer tools, but if you're searching for another way to install the cli, I'd recommend doing it through pip.

Does PIP also request for xcode tools ? is it default on macOS ?

To replicate the problem, you have to install (not migrate) a fresh macOS catalina without any developer tools.

**Comment by Jaff** [comment]
I have a related problem, on Catalina I am getting this error following awscli-bundle/install script:
```
 sudo ./install -i /usr/local/aws -b /usr/local/bin/aws
Running cmd: /Users/mjaffe/.pyenv/versions/3.7.4/bin/python -m venv /usr/local/aws
Running cmd: /usr/local/aws/bin/pip install --no-binary :all: --no-cache-dir --no-index --find-links file://. setuptools_scm-3.3.3.tar.gz
Running cmd: /usr/local/aws/bin/pip install --no-binary :all: --no-cache-dir --no-index --find-links file://. wheel-0.33.6.tar.gz
Running cmd: /usr/local/aws/bin/pip install --no-binary :all: --no-build-isolation --no-cache-dir --no-index  --find-links file:///Users/mjaffe/Development/awscli-bundle/packages awscli-1.18.2.tar.gz
You can now run: /usr/local/bin/aws --version
[inception-builds]mjaffe@sjc-1mjaffe-m:~/Development/awscli-bundle $ /usr/local/bin/aws --version
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/aws/lib/python3.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/local/aws/lib/python3.7/site-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/aws/lib/python3.7/site-packages/urllib3/util/ssl_.py)
```

**Comment by kdaily** [comment]
@ArminDeeg - I am also not able to replicate. I'm running Catalina (10.15.6) and do not have XCode installed. I do not get prompted to install it with any installation mechanism. Does this still occur for you?

@Jaff, your issue looks distinct. Are you still encountering this? If so, can you open a separate issue and provide some more details about your environment? Thanks!

**Comment by ArminDeeg** [comment]
@kdaily 
Hi I've switched to the v2 CLI tools and my problem is fixed with v2

Armin

**Comment by kdaily** [comment]
Thanks @ArminDeeg, closing for now. Should you or someone else encounter it, please open another issue!
