### ISSUE TITLE
Feature Request: Update Alternate Contacts and Tax information

### ISSUE THREAD

**Issue by filipemcg** [aws/aws-cli#4884]
## Scenario

When in a big organization, we normally want to automate the account creation, configuration and delivery process to internal customers.

This often requires alternate contacts and tax information to be updated.

## Problem

Currently there is no API to change alternate contacts or tax information.

## Workaround

We end up developing HTML parsers or RPAs for this matter which is not the best solution for a proper account delivery pipeline.

## Solution

Expose an API for programmatic users with root credentials to update alternate contacts and tax information.

**Comment by klaytaybai** [comment]
Hi @filipemcg, can you please add more detail to your request.  Are you trying to use the [AWS Budgets](https://aws.amazon.com/aws-cost-management/aws-budgets/) or [AWS Cost Explorer](https://docs.aws.amazon.com/cli/latest/reference/ce/index.html#cli-aws-ce) APIs?  What features will this new API need?  I'm not very clear on the details and scope of your request.  However, it sounds like what you are asking for is likely something beyond the scope of the AWS CLI team.  If you provide more details and we determine this to be true, we'll send an internal feature request over to an appropriate team.

**Comment by filipemcg** [comment]
Hey @klaytaybai, thank you for reaching out.

Unfortunately I'm not referring to the AWS Budgets or AWS Cost Explorer.

I'm requesting an API to update the following information of an account:
- **My Account** -> **Tax Settings** -> **Manage Tax Registration Numbers**
- **My Account** -> **Account Settings**
- **My Account** -> **Contact Information**
- **My Account** -> **Alternate Contacts**

**Comment by klaytaybai** [comment]
Thanks for the clarification.

I'm adding a link to a [related Forums discussion](https://forums.aws.amazon.com/thread.jspa?threadID=256883).  If you have more to contribute there, I would suggest doing so.  I imagine that if this is going to be done, customer input is going to be valuable.

**Comment by klaytaybai** [comment]
In order to keep the open issues in this repo limited to the things that the CLI team has control over, I'm going to close this for now.  I've sent your feedback over to the AWS Organizations PM team for further review.  Thanks again.

**Comment by mustafa89** [comment]
Are there any updates on this?

**Comment by peter-beas** [comment]
i cannot find any update, but would also appreciate any solution

**Comment by banagevikas** [comment]
Is there is any update on this ?

**Comment by simonweil** [comment]
I need this too, wish there was something to automate it...

**Comment by bnh1** [comment]
Hi,

Adding another relevant forum feature request thread: [https://forums.aws.amazon.com/thread.jspa?threadID=307469](https://forums.aws.amazon.com/thread.jspa?threadID=307469)

**Comment by AjkayAlan** [comment]
FYI, per https://aws.amazon.com/blogs/mt/programmatically-managing-alternate-contacts-on-member-accounts-with-aws-organizations/, alternate contacts can now be managed via API.

It looks like this is available in newer versions of the CLI (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/account/index.html).

**Comment by TryTryAgain** [comment]
Yes, great that we can manage Alternate Contacts...still need to be able to audit/update Tax Settings as well as grab invoices...so crazy the finance side is living in the stone age.

**Comment by pawelfraczyk** [comment]
Is there any plan to add possibility to manage TRN in Tax Settings per account via aws cli?

We have multiple AWS Sellers in Organization and need to do it manually every time new account is created via our pipelines.

Thanks a lot!

**Comment by CpuID** [comment]
> Is there any plan to add possibility to manage TRN in Tax Settings per account via aws cli?

looks like this got implemented :) the public API was released in June 2024, and awscli support came somewhere after that

https://aws.amazon.com/about-aws/whats-new/2024/06/tax-settings-api-manage-tax-registration-information/

https://docs.aws.amazon.com/cli/latest/reference/taxsettings/

**Comment by TryTryAgain** [comment]
Thanks for sharing @CpuID .... invoices are next ;)
