### ISSUE TITLE
aws ec2 describe-fleets does not fetch instant type fleet

### ISSUE THREAD

**Issue by pragnesh** [aws/aws-cli#4889]
I have created ec2 fleet of type `maintain` and `instant` using example provided by [`https://github.com/awslabs/ec2-spot-labs/tree/master/ec2-fleet`](https://github.com/awslabs/ec2-spot-labs/tree/master/ec2-fleet)

If i use `aws ec2 describe-fleets --fleet-id $FLEETID` it can fetch both fleet data.

But if i use `aws ec2 describe-fleets` command, it only fetch information for `maintain` type fleet. It seems there is issue with [`describe-fleets`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFleets.html) api.

**Comment by kdaily** [comment]
Hello @pragnesh,

I was unable to run using the commands described here: https://github.com/awslabs/ec2-spot-labs

I received a number of errors with the provided demo files, including missing AMIs and missing subnets. Are you still able to use these examples?

**Comment by yeldiRium** [comment]
This is still an issue. Can this be reopened?
