### ISSUE TITLE
aws s3 cp doesn't indicate transfer rate

### ISSUE THREAD

**Issue by foresto** [aws/aws-cli#489]
It would be very helpful if the s3 cp command reported the overall transfer rate as it copies files to s3.  This would give me some idea of how long my transfer is likely to take, and whether I should wait for it or go home while it does its thing.

**Comment by jrmiller82** [comment]
+1

**Comment by kyleknap** [comment]
Feature implemented via: https://github.com/aws/aws-cli/pull/2296. Closing issue.
