### ISSUE TITLE
send-command is not honoring the executionTimeout for shell script

### ISSUE THREAD

**Issue by Pankajc123** [aws/aws-cli#4892]
I am trying to run SSM command below in windows command prompt.

```
aws ssm send-command --document-name "TestSample2" --document-version "2" --targets "Key=tag:arcgis:role2,Values=arcgis-enterprise-base" --parameters commands=["echo HelloWorld","sleep 3800s","echo Done"],executionTimeout=["7200"] --timeout-seconds 600
```

Above command is getting time out after 3600 seconds even though I have changed the execution time out to 7200 seconds.

My document object JSON is as below.
```
{
  "schemaVersion": "2.2",
  "description": "Test Time Out",
  "parameters": {
    "commands": {
      "type": "StringList"
    },
    "executionTimeout": {
      "type": "String",
      "description": "Execution Timeout",
      "default": "7200"
    }
  },
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "installArcGISEnterprise",
      "inputs": {
        "runCommand": "{{commands}}",
        "executionTimeout": "{{executionTimeout}}"
      }
    }
  ]
}
```
When command is running, in AWS console I checked command properties and it does shows execution timeout as 7200.

Any help in this case, will be very helpful.

Thanks.

**Comment by klaytaybai** [comment]
Thanks for the question.  Can you let me know if this [documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-doc-syntax.html) is helpful?  You may need to also specify a timeout in a runtime config section.

**Comment by Pankajc123** [comment]
@klaytaybai Thanks for your response. I have referred to that documentation.

If see JSON document Object, it pointing to schema version 2.2 

But if I change schema version to 1.2 and update schema appropriately, then above command works perfectly. In schema 1.2 under "runtimeConfig" properties I can add executionTimeout and send commands honor's that timeout.
Here is JSON document object with schema version 1.2
```
{
    "schemaVersion": "1.2",
    "description": "Run a shell script or specify the commands to run.",
	"parameters": {
		"commands":{
		    "type": "StringList",
			"description": "(Required) Specify a shell script or a command to run.",
			"minItems": 1			
		},
		"executionTimeout": {
			"type": "String",
			"description": "Execution Timeout",
			"default": "7200"
		}
	},
	"runtimeConfig": {
		"aws:runShellScript": {
		"properties": [
			{
			  "id": "0.aws:runShellScript",
			  "runCommand": "{{ commands }}",						
			  "timeoutSeconds": "{{ executionTimeout }}"
			}
		  ]
		}
	}
}
```

My revised question is why above command does not work with schema version 2.2?

I am under impression that we have move all our document objects from schema version 1.2 to 2.2

**Comment by kdaily** [comment]
Hi @Pankajc123,

Have you been able to resolve this issue and get the command working with the version 2.2 schema? If not, can you please provide the output of the command with the `--debug` flag turned on? Please remove any account identifiers or other sensitive information first. Thanks!

**Comment by bevinharris** [comment]
This is still an issue and is affecting our work processes.

**Comment by ChenLi0830** [comment]
This is still an issue for our system

**Comment by christianclarke** [comment]
This is also a problem that we have observed too.

**Comment by MrHash** [comment]
I see the correct execution timeout when `timeoutSeconds` is specified as a string number inside the `inputs` clause, like this.

```
{
  "schemaVersion": "2.2",
  "description": "Test Time Out",
  "parameters": {
    "commands": {
      "type": "StringList"
    }
  },
  "mainSteps": [
    {
      "action": "aws:runShellScript",
      "name": "DoSomething",
      "inputs": {
        "timeoutSeconds": "123"
        "runCommand": "{{ commands }}"
      }
    }
  ]
}
```
