### ISSUE TITLE
max_bandwidth doesn't work with sync

### ISSUE THREAD

**Issue by g3ntry** [aws/aws-cli#4894]
Setting max_bandwidth works fine with cp (probably as designed), but doesn't work with sync. This is a limitation when trying to use both features, ie using cp and sync concurrently. While this may be a subtle issue it sure can wreck some havoc.

**Comment by klaytaybai** [comment]
Thanks for reporting this.  Confirmed

**Comment by kdaily** [comment]
Hi @g3ntry,

I see that `aws s3 sync` does use the `max_bandwidth` parameter as intended. If you feel this is still an issue, could you please provide a `--debug` log and description of what you're uploading or downloading? What does the status transfer bar show for the bandwidth being used? Thanks!
