### ISSUE TITLE
API Gateway CLI put-integration-response [required field --response-templates] doc fix

### ISSUE THREAD

**Issue by sujituk** [aws/aws-cli#4905]
Per the documentation/synopsis at https://docs.aws.amazon.com/cli/latest/reference/apigateway/put-integration-response.html, the field [--response-templates <value>] is marked optional as shown below. However put-integration-response requires a value. Recommended snippet below could fix the issue. 

`put-integration-response
--rest-api-id <value>
--resource-id <value>
--http-method <value>
--status-code <value>
[--selection-pattern <value>]
[--response-parameters <value>]
[--response-templates <value>]
[--content-handling <value>]
[--cli-input-json <value>]
[--generate-cli-skeleton <value>]`

Recommended:
`put-integration-response
--rest-api-id <value>
--resource-id <value>
--http-method <value>
--status-code <value>
--response-templates <value>
[--selection-pattern <value>]
[--response-parameters <value>]
[--content-handling <value>]
[--cli-input-json <value>]
[--generate-cli-skeleton <value>]`

For the moment: passing has worked for default
`--response-templates '{}'`

**Comment by KaibaLopez** [comment]
Hi @sujituk,
Thanks for pointing this out!

**Comment by kdaily** [comment]
Hi @sujituk, I cannot reproduce this now, so the API Gateway team may have fixed this in the backend. If you are still receiving an error message, please let me know with some more details, including the output of running the command with the `--debug` flag. Thanks!
