### ISSUE TITLE
Please update behaviour or documentation

### ISSUE THREAD

**Issue by ikrabbe** [aws/aws-cli#4919]
When you expect a list of values on the command line, for example the document

aws ec2 describe-subnets help reads

...
       --subnet-ids (list)
          One or more subnet IDs.

          Default: Describes all your subnets.

       Syntax:
          "string" "string" ...

But the syntax is NOT "string" "string", but as in JSON '["string","string",....]', so either fix your documentation or prepare your tool to accept a string list as described, which would be much more reasonable for a CLI tool anyway.

**Comment by KaibaLopez** [comment]
Hi @ikrabbe ,
What version of the CLI are you using and what OS? 
Also I may be misunderstanding something but, I just tested on my side and I can use the list syntax as specified in the help message:
`aws ec2 describe-subnets --subnet-id "subnet-id1" "subnet-id2"`
Are you not able to do that or are you saying we should support the JSON format too?
