### ISSUE TITLE
 want to import json file into dynamoDB via AWS cli.

### ISSUE THREAD

**Issue by streetracer48** [aws/aws-cli#4921]
I have created a demo table music with partition key name.

I entered below command :

aws dynamodb put-item --table-name music --item file://0001.json --return-consumed-capacity TOTAL

I receive following error:

Parameter validation failed: Invalid type for parameter Item.Count, value: 503, type: , valid types: Invalid type for parameter Item.Items, value: [OrderedDict([('phoneNumber', OrderedDict([('S', 'GpDxxZRJIlUuoqlULj6h0w==')])),

my json file

{
  "Items": [
    {
      "phoneNumber": {
        "S": "GpDxxZRJIlUuoqlULj6h0w=="
      },
      "isfisheye": {
        "N": "0"
      },
      "isdeleted": {
        "N": "0"
      },
      "contactFEId": {
        "S": "FE160959275516"
      },
      "ismerged": {
        "N": "0"
      },
      "source": {
        "S": "fromPhone"
      },
      "secondaryPhoneNumbers": {
        "L": [
          {
            "S": "n/a"
          }
        ]
      },
      "email": {
        "S": "XVRb5DlaaC8yIfujKnLsUkV+yv0Ry9nPeWN2iv9OQPY="
      },
      "name": {
        "S": "Sankey Vaishali"
      },
      "isBlocked": {
        "N": "0"
      },
      "contactId": {
        "S": "1528891536"
      },
      "sharedData": {
        "N": "2"
      },
      "secondaryEmails": {
        "L": [
          {
            "S": "n/a"
          }
        ]
      },
      "userId": {
        "S": "FE1411544738781"
      },
      "privacyEnabled": {
        "N": "1"
      }
    },
  ],
  "ScannedCount": 503
}

**Comment by KaibaLopez** [comment]
Hi @streetracer48, 
I may be wrong and you are trying something else, but I think the problem is the format of your json (plus an extra coma before closing the final bracket).
Try:
```
{
    "phoneNumber": {"S": "GpDxxZRJIlUuoqlULj6h0w=="},
    "isfisheye": {"N": "0"},
    "isdeleted": {"N": "0"},
    "contactFEId": {"S": "FE160959275516"},
    "ismerged": {"N": "0"},
    "source": {"S": "fromPhone"},
    "secondaryPhoneNumbers": {"L": [{"S": "n/a"}] },
    "email": {"S": "XVRb5DlaaC8yIfujKnLsUkV+yv0Ry9nPeWN2iv9OQPY="},
    "name": {"S": "Sankey Vaishali"},
    "isBlocked": {"N": "0"},
    "contactId": {"S": "1528891536"},
    "sharedData": {"N": "2"},
    "secondaryEmails": {"L": [{"S": "n/a"}] },
    "userId": {"S": "FE1411544738781"},
    "privacyEnabled": {"N": "1"}
}
```
Let me know if that helps

**Comment by streetracer48** [comment]
Cool! I fixed the errors. Thanks
