### ISSUE TITLE
Access denied when uploading multipart that requires --acl bucket-owner-full-control

### ISSUE THREAD

**Issue by smenendez-verisk** [aws/aws-cli#4924]
I have a problem uploading  files on s3 to another account's s3 bucket using a lambda function with multi-part upload. Even though the acl flag is specified in the logic , the resulting object is not accessible when trying to download.

    # Initiate the multipart upload and send the part(s)
    mpu = s3.create_multipart_upload(Bucket=output_S3_Bucket, Key=Output_Location)
    s3 = boto3.client('s3')
    print("mpu:" + str(mpu))
    part_info = {'Parts': []}
    i = 1
    newcounter = 0
    temprecords=""
    for event in recordlist:
        #if 'Records' in event:
            newcounter = newcounter + 1
            #records = event['Records']['Payload'].decode('utf-8')
            records = event
            temprecords = temprecords + records
            recordslength = len(records.encode('utf-8'))
            #print("Records length in bytes: " + str(recordslength))
            temprecordslength = len(temprecords.encode('utf-8'))
            temprecordslengthinMB = round(temprecordslength)/1024/2014
            if(newcounter == counter):
                print("last MPU part")
                print("Concatenated records length in MB: " + str(temprecordslengthinMB))
                part = s3.upload_part(Bucket=output_S3_Bucket,
                Key=Output_Location,
                PartNumber=i,
                UploadId=mpu['UploadId'],
                Body=temprecords
                )
                print("part upload response:" + str(part))
                parts = {
                    'PartNumber': i,
                    'ETag': part['ETag']
                }
                part_info['Parts'].append(parts)
                i = i + 1

            if(temprecordslengthinMB < 5):
                continue
            else:
                print("Concatenated records length in MB: " + str(temprecordslengthinMB))
                part = s3.upload_part(Bucket=output_S3_Bucket,
                Key=Output_Location,
                PartNumber=i,
                UploadId=mpu['UploadId'],
                Body=temprecords,
                ExtraArgs={'ACL': 'bucket-owner-full-control'}
                )
                print("part upload response:" + str(part))
                parts = {
                    'PartNumber': i,
                    'ETag': part['ETag']
                }
                part_info['Parts'].append(parts)
                i = i + 1
                temprecords=""

**Comment by stealthycoin** [comment]
This is the ticket queue for the AWS CLI. It looks like you meant to open an issue with boto3?

https://github.com/boto/boto3/issues
