### ISSUE TITLE
[v2] Provide mac version in zip format, like linux

### ISSUE THREAD

**Issue by slimm609** [aws/aws-cli#4926]
The mac version only comes as a package but the linux version comes as a zip.    Please also provide the mac version as a zip of the binary.

**Comment by klaytaybai** [comment]
I'll check with the team to see if the package is their new preferred way of installation.  In the meantime, you can use the zip installation method found in our [blog post about V2 installers](https://aws.amazon.com/blogs/developer/aws-cli-v2-installers/).

**Comment by slimm609** [comment]
Thanks,  We have tools that stick specific versions of all our tools so that the teams are operating off the same version of tools across the board so the zip files are big benefit.

**Comment by stealthycoin** [comment]
What is the use case for them that you have? Is there a way we can make the pkg installer meet those needs as well?

**Comment by slimm609** [comment]
correct,  it gets installed to a specific directory via curl from a script.

**Comment by surajbarkale** [comment]
I have a similar use case and I can use https://awscli.amazonaws.com/awscli-exe-macos.zip link. However, it is not versioned like the Linux installer. For example, there is no https://awscli.amazonaws.com/awscli-exe-macos-2.0.4.zip similar to https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.4.zip url. Can you please provide the older macos zip versions as well?
