### ISSUE TITLE
PGP key is not on keyservers and the email address is invalid

### ISSUE THREAD

**Issue by stilvoid** [aws/aws-cli#4942]
To make package verification easier, the PGP key should be uploaded to a well-known keyserver (e.g. pgp.mit.edu).

Also, the email address associated with the PGP key does not exist (aws-cli@amazon.com). I know this because I first tried to raise this issue by email through that address :)

**Comment by kyleknap** [comment]
Thanks for reporting. Making sure the email alias exists and uploading the PGP key both make sense.

**Comment by stilvoid** [comment]
Looks like this is done now :+1:

http://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0xA6310ACC4672475C
