### ISSUE TITLE
-profile no longer works when using AWS CLI2 SSO as credentials file isn't updated

### ISSUE THREAD

**Issue by sethbacon** [aws/aws-cli#4944]
When using the AWS CLI v2 with SSO, the credentials file is no longer updated as it was using other utilities. Now a cached json file is created in a subdirectory of the .aws folder on windows. Powershell cmdlets that respect the -profile switch look at the credentials file instead of the new location for a session token and expiration.

**Expected Behavior**

-profile should look at both the credentials file and the new json cache to determine the correct behavior.

**Current Behavior**

Profiles updated by AWS SSO login don't update the credentials file, so cmdlets that look to that file fail.

**Possible Solution**

Look in both locations, respect either the latest expiration or the earliest, depending on how you think it should behave.

**Steps to Reproduce (for bugs)**

Use the new AWS CLI with SSO.
Login with a profile.
Try to run any cmdlet, passing the same profile.

**Context**

Annoying as can be. We finally get a non-third party SSO solution for the AWS CLI and it breaks the other important CLI for Windows

**Comment by hynynen** [comment]
I was sad to notice this too :( I'm trying to run Python scripts with boto3, but obviously it fails because it cannot find credentials. My platform is Ubuntu 18.04 in WSL.

I can see that there is command `aws sso get-role-credentials`, but it requires access-token and I don't know if or where I can find one after login in with SSO. It is also frustrating  to repeat account-id and role name.

**Comment by dayer4b** [comment]
I have run into this issue as well, I very much hope this is remedied ASAP!

I was able to find the credentials needed in the path `~/.aws/cli/cache/..` there are JSON files that are generated for various profiles when you use the `aws sso login` command.

I use this script for now:

```
#!/bin/bash

JSON_BASEPATH="${HOME}/.aws/cli/cache"
AWS_CREDENTIALS_PATH="${HOME}/.aws/credentials"

if [ -f ${AWS_CREDENTIALS_PATH} ]; then
        echo "backing up existing credentials"
	cp -rf ${AWS_CREDENTIALS_PATH} "${AWS_CREDENTIALS_PATH}-"$(date +"%s")
fi

# find the latest CLI JSON file

json_file=$(ls -tr "${JSON_BASEPATH}" | tail -n1)

# use jq to dump stuff in the right place

aws_access_key_id=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.AccessKeyId')
aws_secret_access_key=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.SecretAccessKey')
aws_session_token=$(cat ${JSON_BASEPATH}/${json_file} | jq -r '.Credentials.SessionToken')


echo "[default]" > ${AWS_CREDENTIALS_PATH}

echo "aws_access_key_id = ${aws_access_key_id}" >> ${AWS_CREDENTIALS_PATH}
echo "aws_secret_access_key = ${aws_secret_access_key}" >> ${AWS_CREDENTIALS_PATH}
echo "aws_session_token = ${aws_session_token}" >> ${AWS_CREDENTIALS_PATH}
```

**Comment by nateprewitt** [comment]
Hey @sethbacon,

Thanks for bringing this to our attention! We definitely want to help enable usage in external tools like cmdlets. To clarify the issue, are you experiencing this issue with the newly added SSO support in v2, or this is a workflow you were using in v1 that is now broken?

**Comment by nateprewitt** [comment]
I'm going to go ahead and mark as a feature request with the new SSO support. If I'm missing a previously supported breakage though, please let us know. Thanks!

**Comment by arvindkgs** [comment]
I have created a script to automate the web flow of 'aws sso login', so you do not need to switch to the browser for SSO authentication. It also updates the ~/.aws/credentials and inject env params AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN into current terminal. 

-  https://github.com/arvindkgs/aws_sso_login

**Comment by tim-finnigan** [comment]
I think this might be a duplicate of https://github.com/aws/aws-cli/issues/4676. Can anyone confirm that or help clarify any distinctions between these two issues?
