### ISSUE TITLE
Update ECR login command on the 'View Push Commands' popup in the console

### ISSUE THREAD

**Issue by edlevin6612** [aws/aws-cli#4960]
Not strictly an aws cli issue but ECR push commands popup in the AWS console (ECR > Repositories > <repo name>) still mentions:

```
Retrieve the login command to use to authenticate your Docker client to your registry.
Use the AWS CLI:
$(aws ecr get-login --no-include-email --region us-east-1)
```

This message needs to be augmented to account for aws cli 2 breaking change in regards to ECR login:
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-ecr-get-login

**Comment by joguSD** [comment]
Good catch. I'll forward this feedback along to the ECR team.

**Comment by mjsteinbaugh** [comment]
+1 I'm seeing the mismatch in my console.

The current Docker basics guide looks good though, with v2 instructions:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

**Comment by rpnguyen** [comment]
Thanks for letting us know!

This change has been deployed, you should now see an updated command in the "View Push Commands" popup.
