### ISSUE TITLE
V2 upgrade procedure and changelog ?

### ISSUE THREAD

**Issue by fmedery** [aws/aws-cli#4961]
What is the procedure to find the available updates and changelog ?
As an example V1 as been updated yesterday to add new ES features.
How can I know that 
* There is a new V2 version
* upgrade  without downloading the PKG package again and again

**Comment by KaibaLopez** [comment]
Hi @fmedery ,
for the latest development version updates you can check the [V2 branch](https://github.com/aws/aws-cli/tree/v2).
And to keep up with the latest version, at the moment the recommended way would be downloading the PKG... Or you could try installing from source by cloning from github, there are instructions for that in the V2 Branch Readme too.

**Comment by tmccombs** [comment]
> at the moment the recommended way would be downloading the PKG

that is far from ideal. It does look like it has an ETag header, and supports If-None-Modified on the request, and If-Modified-Since. But it would be nice for there to be a programmatic way to get the current version. 

Also, is there a way to download a specific version?

**Comment by kdaily** [comment]
Hi @tmccombs, the method for installing a specific version has been added to each install section in the installation guide. For example for [Linux](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html), it reads:

> For a specific version of the AWS CLI, append a hyphen and the version number to the filename. For this example the filename for version 2.0.30 would be awscli-exe-linux-x86_64-2.0.30.zip resulting in the following command: 
```
$ curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```

**Comment by kdaily** [comment]
I'm going to mark this as an enhancement around the distribution and versioning of the v2 client.

**Comment by tim-finnigan** [comment]
The v2 CHANGELOG can be found here: https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1

There's a related issue (https://github.com/aws/aws-cli/issues/5471) requested a "latest" release tag for this use case. (As well as several [installation issues](https://github.com/aws/aws-cli/issues?q=is%3Aissue+is%3Aopen+label%3Ainstallation) that are tracking work to improve source packaging/distribution). The current recommended installation steps can be found here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

@fmedery does the issue linked above or any other one you've seen address the original feature request here? Please let us know if there's anything you wanted to expand on or clarify. Thanks!
