### ISSUE TITLE
AWSCLI v2 preview not functional after windows msi install

### ISSUE THREAD

**Issue by danludwig** [aws/aws-cli#4963]
Hi,

I followed the instructions @ https://aws.amazon.com/blogs/developer/aws-cli-v2-installers/ to download and install the AWS CLI V2 preview installer on a windows machine. The installer appeared to succeed, and created contents @ C:\Program Files\Amazon\AWSCLIV2. This same path was also added to my system environment variables. However when I run `aws2 --version`, terminals are telling me they can't find it. For example cmd says

> 'aws2' is not recognized as an internal or external command, operable program, or batch file.

When I run `where aws`, the results seem to include the new aws v2 installation path.

> where aws
> C:\Program Files\Amazon\AWSCLI\bin\aws.cmd
> C:\Program Files\Amazon\AWSCLIV2\aws.exe
> C:\Users\Dan\AppData\Roaming\Python\Python35\Scripts\aws
> C:\Users\Dan\AppData\Roaming\Python\Python35\Scripts\aws.cmd

The results for `where aws2` turns up empty as well. 

When I run `aws --version`, it seems to be still mapped to my previous aws install.

> aws --version
> aws-cli/1.16.100 Python/3.6.0 Windows/10 botocore/1.12.90

Any advice, is this a known issue with workarounds or solutions?

**Comment by danludwig** [comment]
Follow up: If I `cd "C:\Program Files\Amazon\AWSCLIV2"`, then I can see the new version, but the docs said that the CLI should be available under the aws2 command name?

> cd "C:\Program Files\Amazon\AWSCLIV2"
> aws --version
> aws-cli/2.0.0 Python/3.7.5 Windows/10 botocore/2.0.0dev4

**Comment by joguSD** [comment]
@danludwig Earlier this week we announced that AWS CLI V2 is now generally available.

See this blog post:
https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/

As part of GA we've renamed the binary back to `aws`. I can definitely see how this could be confusing if you're looking at the preview blog post a while back. I'll see if we can get an update on that blog post to redirect to the GA announcement.

**Comment by danludwig** [comment]
That explains it. So @joguSD does this mean I should install from the general cli release download link? Currently, it looks like I have 2 side-by-side installations, should I remove the v2 version and update the v1 version? What's the recommended steps for those who had installed during the preview period?

**Comment by joguSD** [comment]
@danludwig It looks like your previous install of the AWS CLI V1 was installed via `pip`. I would suggest removing the `pip` version and using the MSIs for AWS CLI v2.
