### ISSUE TITLE
aws cp s3://x/file s3://x/file --cache-control foo fails

### ISSUE THREAD

**Issue by alexanderkjeldaas** [aws/aws-cli#4965]
I cannot change the cache-control header by copying a file onto itself.

copy failed: s3://x/file to s3://s/file An error occurred (InvalidRequest) when calling the CopyObject operation: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.

**Comment by KaibaLopez** [comment]
Hi @alexanderkjeldaas,
can you provide the command you used (not including your bucket names or cache control value)? 
If you are using literally the title then you are missing s3 and/or the cache-control value:
`aws s3 cp s3://mybucket/test.txt s3://mybucket/test2.txt --cache-control <some-value>`
