### ISSUE TITLE
v2 service side resource name completion not working

### ISSUE THREAD

**Issue by OskergMonReap** [aws/aws-cli#4970]
Command/parameter completion are working as expected, confirming I have the correct addition to my `.bashrc`, ie:
```
$ aws s3a<TAB>
$ aws s3api

$ aws s3api create-mu<TAB>
$ aws s3api create-multipart-upload

$ aws s3api create-multipart-upload --bu<TAB>
$ aws s3api create-multipart-upload --bucket 
```
The issue comes when I attempt completion of service side resource names, for example lets say I have a bucket named `aws-cli-v2-test-bucket`, the below never works:
```
$ aws s3api create-multipart-upload --bucket aws-cl<TAB>
```
I've attempted this across several services, including one mimicking the example in the release notes for aws-cli-v2 with DynamoDB Table names.. The service side resource name completion is not working.

---
aws-cli == 2.0.0
python == 3.7.3
botocore == 2.0.0dev4

**Comment by KaibaLopez** [comment]
Hi @OskergMonReap,
Thanks for pointing this out, at the moment we don't cover all resources, so yea the bucket name is not yet supported...
The example at the release notes works for me though: 
`aws dynamodb update-table --table-name m<TAB>`
 so just to make sure I label this correctly as a feature request... can you tell me what platform you're running this in?

**Comment by OskergMonReap** [comment]
@KaibaLopez 
Thanks for the quick response.
I'm experiencing this across all my Linux boxes.
To be specific: Ubuntu 19.10, Red Hat Enterprise Linux 8, Opensuse Leap 15.1 and Arch Linux (kernel 5.4.15)

**Comment by KaibaLopez** [comment]
@OskergMonReap, 
To be clear, the resource completer for s3 buckets is the feature request.

I've tested the dynamodb resource autocomplete on Mac linux and windows, and have no problems with it, so that at least should work... Only thing I can think for it to be giving you issues is, maybe credentials not set correctly? Can you try 
`aws dynamodb list-tables`
and tell me if it shows you a table?

**Comment by OskergMonReap** [comment]
@KaibaLopez 
I have the proper permissions, verified via `list-tables`
After some testing, it seems like it does not work properly when behind my VPN (odd, as aws-cli-v1 previously worked). Regardless, clearly a "me" problem and not a `aws-cli-v2` problem at this point :+1:
