### ISSUE TITLE
[v2] dynamodb restore-table-from-backup does not support --sse-specification-override option

### ISSUE THREAD

**Issue by michimani** [aws/aws-cli#4975]
AWS CLI v2 does not recognize the `--sse-specification-override` option when performing DynamoDB cross-region restore.

I tried restoring from the Tokyo (ap-northeast-1) region to the Northern Virginia (us-east-1) region.

```
$ aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev4

$ aws dynamodb restore-table-from-backup \
--backup-arn arn:aws:dynamodb:ap-northeast-1:XXXXXXXXXXXX \
--target-table-name TargetTable \
--sse-specification-override Enabled=false  \
--region us-east-1
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --sse-specification-override, Enabled=false
```

**Comment by kyleknap** [comment]
Looks like this was a recent API update that got updated in v1, but has not been updated yet for v2. We will make sure to pull this update in for our next release AWS CLI v2.

**Comment by michimani** [comment]
@kyleknap 
Thank you for your comment.  I want to wait for the next update.

**Comment by michimani** [comment]
@kyleknap 
I can see that the `--sse-specification-override` option is enabled in version `2.0.1` , and succeeded in cross-region restore.

Thank you for updating!
