### ISSUE TITLE
The event put-targets doesn't work as specified and doesn't support all Ecs parameters

### ISSUE THREAD

**Issue by mehric** [aws/aws-cli#4977]
**Problem**
The "aws events put-targets" command doesn't work as specified on the documentation here: https://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html

The json skeleton is different, but it is possible to figure it out. But still, even on the latest version, it is not possible to set all the EcsParameters.

For me it only shows these options on the skeleton:
`"EcsParameters": {
                "TaskDefinitionArn": "",
                "TaskCount": 0
            }
`

Using the "--cli-input-json" I am able to pass all parameter, but I still get errors as follows:

> Unknown parameter in Targets[0].EcsParameters: "NetworkConfiguration", must be one of: TaskDefinitionArn, TaskCount
> Unknown parameter in Targets[0].EcsParameters: "LaunchType", must be one of: TaskDefinitionArn, TaskCount
> Unknown parameter in Targets[0].EcsParameters: "Group", must be one of: TaskDefinitionArn, TaskCount
> Unknown parameter in Targets[0].EcsParameters: "PlatformVersion", must be one of: TaskDefinitionArn, TaskCount

**Comment by stealthycoin** [comment]
What version of the CLI do you have? Trying this on a current version I get all those parameters printed out. Try updating and trying again. Let us know if you're still runnnig into issues.

**Comment by mehric** [comment]
Hi, I checked again and I released it was some environment issue that was using the aws-cli/1.11.125.
When upgrading cli to the latest, it works perfectly fine now.
