### ISSUE TITLE
[v2] aws iam list-account-aliases does not work with SSO credentials

### ISSUE THREAD

**Issue by dayer4b** [aws/aws-cli#4980]
after setting up local credentials with an SSO login, `aws iam list-account-aliases` does not seem to function in the way it did with the v1 releases

example: 

```
$ aws sts get-caller-identity 
{
    "UserId": "REDACTED:username@example.com",
    "Account": "REDACTED",
    "Arn": "arn:aws:sts::REDACTED:assumed-role/AWSReservedSSO_AdministratorAccess_REDACTED/username@example.com"
}

$ aws iam list-account-aliases
{
    "AccountAliases": []
}
```
with the v1 CLI, I would get an actual alias here

**Comment by KaibaLopez** [comment]
Hi @dayer4b ,
Can you verify that you have aliases on your account? Or are you expecting the aliases to include the original account id?
I am able to replicate the empty output only when no aliases have been assigned, once one is created it is properly listed.

**Comment by granite-cloud** [comment]
No this does not seem to work properly as was mentioned. I can call to create an alias and you see by the error returned that it in fact does exist. However, the call to  list-account-aliases still returns empty. Something has changed as it did work.

aws-cli/2.0.42 Python/3.7.4 Darwin/19.6.0 exe/x86_64

```
aws iam  create-account-alias --account-alias playground

An error occurred (EntityAlreadyExists) when calling the CreateAccountAlias operation: The account alias playground already exists

aws iam list-account-aliases                            
{
    "AccountAliases": []
}
```
