### ISSUE TITLE
#aws #awscli Is it possible to fetch the name of the container in ecs through aws cli

### ISSUE THREAD

**Issue by nags28** [aws/aws-cli#4983]
hi i have created a cluster through manually and i want to fetch the ecs container name through aws cli 
is it possible if so how ?????

**Comment by KaibaLopez** [comment]
Hi @nags28 ,
It should be yea, I think you're looking for : 
`aws ecs describe-clusters --cluster "YOURCLUSTER"`
but if that isn't what you're looking for, you can check the[ Reference Guide](https://docs.aws.amazon.com/cli/latest/reference/ecs/index.html) you should be able to find the command you're looking for there.
