### ISSUE TITLE
make_bundle#verify_preconditions() fails for virtualenv 20+

### ISSUE THREAD

**Issue by jakub-bochenski** [aws/aws-cli#4984]
This comment no longer holds: https://github.com/aws/aws-cli/blob/develop/scripts/make-bundle#L142

The output is now something like
```
virtualenv 20.0.4 from /home/jenkins/.local/lib/python2.7/site-packages/virtualenv/__init__.pyc
```

I'm just running the script against virtualenv 16 for now.

**Comment by kyleknap** [comment]
I think the purpose of this comment is to give an example of what the virtualenv version string looks like in order to explain the logic for parsing the version number. That being said it does not matter too much that the version in the example does not match up with the minimum specified in the code. However, we'd accept a PR if you wanted to update the comment to make it consistent with the actual minimum version we use.

**Comment by jakub-bochenski** [comment]
I think you misunderstood me. The version parsing will fail because it will not extract a valid number

**Comment by jakub-bochenski** [comment]
This is the sample failure:
```

+ ./make-bundle
Running cmd: /usr/bin/python -m pip --version
Running cmd: /usr/bin/python -m virtualenv --version
Traceback (most recent call last):
  File "./make-bundle", line 186, in <module>
    main()
  File "./make-bundle", line 159, in main
    verify_preconditions()
  File "./make-bundle", line 143, in verify_preconditions
    _min_version_required('15.1.0', virtualenv_version, 'virtualenv')
  File "./make-bundle", line 152, in _min_version_required
    if int(actual_version_part) >= int(min_version_part):
ValueError: invalid literal for int() with base 10: ''
```

**Comment by mhart** [comment]
Yep, seeing the same thing – there appears to be no way to run `make-bundle` without removing this check. `virtualenv` 20.x was released 2020-02-10

**Comment by tim-finnigan** [comment]
Checking in as there haven't been any comments here in several years. Is this still an issue for folks?

**Comment by jakub-bochenski** [comment]
I'm not using aws-cli now, but I don't see how this issue would resolve itself without any action
