### ISSUE TITLE
ecr describe-repositories - filter by tag

### ISSUE THREAD

**Issue by dpolicastro** [aws/aws-cli#4985]
I want to get all the repository names for repositories that contains a specific tag, but I'm not seeing any option which I can pass it. Also, there is lack of documentation for the `--query` option, I could not found anywhere, any example using it.

What about adding the option `--filters` like in the command `aws ec2 describe-instances`?

Thanks.

**Comment by rpnguyen** [comment]
Please 👍this issue aws/containers-roadmap#418 to help prioritize this feature.

You could also use the resource groups tagging API to retrieve repositories by tag:

```
aws resourcegroupstaggingapi get-resources \
--tag-filters Key=Foo,Values=Bar \
--resource-type-filters ecr:repository
```

**Comment by nateprewitt** [comment]
Yep, it looks like we're waiting on the service team to implement the change linked above. Once that's in place, we should automatically pull in the functionality for the CLI.

Let's go ahead and track the progress in aws/containers-roadmap#418 to keep things consolidated. Thanks!
