### ISSUE TITLE
[V2] aws sso get-role-credentials fails one hour after authentication

### ISSUE THREAD

**Issue by pcolmer** [aws/aws-cli#4987]
After authenticating with `aws sso login --profile <blah>`, an `accessToken` is stored under `.aws/cli/cache` which, according to the file on my system, expires about 8 hours after that login process.

I'm then using that `accessToken` as a parameter to `get-role-credentials` in order to retrieve the temporary credentials for re-use by other tools like Terraform.

However, after just one hour after the login process, the access token is no longer accepted. Instead, I'm getting this error:

`An error occurred (UnauthorizedException) when calling the GetRoleCredentials operation: Session token not found or invalid`

Now, there was until recently a problem with AWS SSO in conjunction with the CLI in that SSO wasn't honouring the session duration when it was longer than an hour, so I'm not sure if this is revealing a bug that is still within AWS SSO itself or if there is a bug in AWS CLI. We have got an open AWS Support ticket regarding AWS SSO not honouring the session duration so I'm updating that just in case it is a problem at the back-end, but I'm reporting it here as well in case it is a problem with the CLI code.

**Comment by stealthycoin** [comment]
I would suggest following up with the SSO Service Team. The CLI doesn't do any logic on the tokens, we just write them to cache and read them for API calls. If the session token is expiring I think that would be something to do with the SSO service configuration.

**Comment by angusfz** [comment]
Same issue here. 
We're using awscliv2 SSO login with CDK. Because the CDK doesn't support the SSO profile yet. 
For working with CDK, we have to  export the credential which cached in `.aws/cli/cache`  
But the cached credential has expiration about 1 hr.
It's really annoying that we have to log in every hour to update the cached credentials.
Any suggestion will be appreciated

**Comment by pcolmer** [comment]
@stealthycoin The problem seems to be fixed now; it definitely did smack of the backend.

@angusfz You may want to try using a tool like https://github.com/linaro-its/aws2-wrap which allows you to get fresh credentials every time you run the tool with a secondary command it executes on your behalf. Also, have you set the session duration in the SAML response (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html#saml_role-session-duration) and/or the SSO web interface (https://docs.aws.amazon.com/singlesignon/latest/userguide/howtosessionduration.html)?
