### ISSUE TITLE
Potential Typo in code block (elb-listener-policy-cli)

### ISSUE THREAD

**Issue by KarlWebster97** [aws/aws-cli#4988]
TLDR/ 

* Should remove the `–-query` and replace with `--query` 

On this page: 
https://aws.amazon.com/premiumsupport/knowledge-center/elb-listener-policy-cli/

```
aws elb describe-load-balancer-policies --load-balancer-name TESTELB --policy-name AWSConsole-SSLNegotiationPolicy-TESTELB-1447102065672 –-query "PolicyDescriptions[0].{ReferenceSecurityPolicy:PolicyAttributeDescriptions[0].AttributeValue}" --output table
````

Should remove the `–-query` and replace with `--query` as they look similar and was relatively hard to troubleshoot consinding the trivial nature of the "mistake"

I am using Fedora so I cant confirm if `–-query` works on Windows & mac.

**Comment by KaibaLopez** [comment]
Thanks for pointing this out!
This is definitely a typo, and we'll look into it.

**Comment by KaibaLopez** [comment]
Hi @KarlWebster97, 
The typo has been fixed, thanks again for pointing this out to us!
