### ISSUE TITLE
[v2] Table output format broken in Windows

### ISSUE THREAD

**Issue by silverhero13** [aws/aws-cli#4989]
I was trying out AWS CLI v2 on my Windows machine. However when I choose `table` as the output format, the table displays what I suppose as escape sequences of the colours.

#### Sample output

```
-------------------------------------------------------------------------------------
|                                  DescribeImages                                   |
+-----------------------------------------------------------------------------------+
[2m[33m|[0m|                                     Images                                      |[2m[33m|[0m
[2m[33m|[0m+-----------------------------------+---------------------------------------------+[2m[33m|[0m
[2m[33m|[0m|  [1m[34mArchitecture[0m                     |  [1m[34mx86_64[0m                                     |[2m[33m|[0m
[2m[33m|[0m|  [1m[34mCreationDate[0m                     |  [1m[34m2020-02-19T10:23:45.000Z[0m                   |[2m[33m|[0m
```

#### AWS CLI Version

```
> aws --version
aws-cli/2.0.0 Python/3.7.5 Windows/10 botocore/2.0.0dev4
```

#### Related image

![Screenshot (5)_LI](https://user-images.githubusercontent.com/12245431/75044444-9d8d5b00-54fc-11ea-9043-8f2ef2af5ec7.jpg)

**Comment by KaibaLopez** [comment]
Hi @silverhero13 ,
Yea, it seems to work fine on linux style consoles but I can see the same problem on the windows command line.
Thanks for pointing it out!

**Comment by itamarka9** [comment]
Hi,
I have contacted AWS support and the suggested to add --color off at the end of the command.
It helped.
My os is  Windows 10 2004
He told me they are looking at the problem.

**Comment by cmonks119** [comment]
Is there any fix for this yet?

**Comment by jebbenbow** [comment]
I'm still using the --color off workaround.

**Comment by geragfg** [comment]
I agree the --color off workaround works for me too

**Comment by tim-finnigan** [comment]
Closing as this should be fixed in recent versions of Windows Terminal.
