### ISSUE TITLE
Glacier upload-archive fails with Invalid Content-Length error

### ISSUE THREAD

**Issue by nija-at** [aws/aws-cli#4991]
Opening a new issue with the same title, since I cannot see an option to re-open #3413.
Please see the #3413 for the details of the issue. 

I am getting the same error even with the verison `aws-cli/1.17.10 Python/3.8.1 Darwin/18.7.0 botocore/1.14.10`. I had to wait 1 hour to upload a 4GB file, eventually ending up with this error, with no clear path forward.

The [resolving comment on the issue](https://github.com/aws/aws-cli/issues/3413#issuecomment-401849012) states that this is not an issue of the CLI since this is a server side error. 
I disagree with this conclusion. The user has very little control over any of the server side parameters, and how the CLI integrates with the service. 

I am going to guess that the server-side API is working correctly (it can't be broken from Jul 2018 when the original issue was reported until today) and that there is an issue with how the CLI invokes this service.

I would urge the CLI team to investigate further.

Additionally, there is no progress reporting on the `glacier upload-archive` subcommand as is done with the `aws s3` subcommand. It would be great it that can be incorporated in as well.

**Comment by kyleknap** [comment]
For this workflow, I'd imagine we would add it for a higher level glacier command set (similar to the `s3` command set). For the `glacier upload-archive` command, it is considered a lower-level command that maps 1:1 to the API so we typically do not modify the behavior that is coming back from the service. I'd imagine if we added a higher-level glacier command, it would:

* Automatically convert to multipart uploads when it detects the payload is larger than 4GB. So you would not get that error in general
* Display progress similar to the `s3` commands. 

I'd suggest we track these features in the GitHub issue requesting it: https://github.com/aws/aws-cli/issues/1280. Let us know if you have any questions.

**Comment by nija-at** [comment]
This is not a request to add any higher level API or support multipart uploads (although you should totally do that). On the other hand, I'm reporting that the `upload-archive` command via the CLI is broken. 

Either that, or the API on the glacier service is broken, in which case, I would request you to open a high severity issue with them. 

The equivalence of this is the `s3api put-object` and I would guess that it doesn't generate the same error.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity in a while. Is there still an issue with the `upload-archive` command? As mentioned earlier that would likely be a service-side issue involving the underlying [Glacier API](https://docs.aws.amazon.com/amazonglacier/latest/dev/api-archive-post.html) rather than the CLI directly (in which case we recommend users to escalate those issues directly to [AWS Support](https://aws.amazon.com/contact-us/)). 

If this is something the CLI team should investigate further please share a reproducible example and debug logs by adding `--debug` to the command.
