### ISSUE TITLE
[v2] Command output redirected to vim by default

### ISSUE THREAD

**Issue by PatrykMilewski** [aws/aws-cli#4992]
Hello! 👋 

After upgrading AWS CLI to v2 using brew package manager, my AWS CLI is outputting everything to nano, which is my default text editor in console. Previously it was simply outputting to stdout.

How can I change this behaviour to the previous one? Due to this I have problems with running bash scripts, that use AWS CLI.

**Comment by KaibaLopez** [comment]
Hi @PatrykMilewski ,
Is this happening for every command or which ones specifically are doing this?

**Comment by PatrykMilewski** [comment]
@KaibaLopez thanks for the response.

I just confirmed, that I have this problem for Dynamo, Lambda, SSM, IAM and probably all other services. It actually outputs to `less` not `nano`, my bad.

**Comment by KaibaLopez** [comment]
Hmm, this seems to be a common issue on v2, but just so I can make sure it's not dependent on some local configuration or specific commands... Can you provide some examples  so I can try and reproduce this behavior? Just one or 2 are enough

Also, in case this is a blocking issue for you and you need a quick workaround, you could always pipe the commands to escape it `aws dynamodb list-tables | > /dev/null`

**Comment by KaibaLopez** [comment]
Hi @PatrykMilewski ,
Can you try following [this instructions](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager), and let me know if that solved your issue for you.

**Comment by PatrykMilewski** [comment]
@KaibaLopez It works, thanks!

To fix use this command:
```
export AWS_PAGER=""
```
Or in `~/.aws/config`:
```
[default]
cli_pager=
```

**Comment by intenics** [comment]
> [default]
> cli_page=
does not work for me.
Ubuntu 20.04.
cli version aws-cli/2.0.6

AWS_PAGER does the trick

**Comment by bobthearsonist** [comment]
i am also unable to set the pager using the config file

**Comment by chefhoobajoob** [comment]
fwiw, adding `cli_pager=` to the config file, at least on mac, result in `Unable to parse config file` errors when running any command
