### ISSUE TITLE
[v2] start-text-detection not available in aws cli rekognition api

### ISSUE THREAD

**Issue by thedewpoint** [aws/aws-cli#4995]
I'm trying to use rekognition api for start-text-detection on videos. It is documented here: https://docs.aws.amazon.com/cli/latest/reference/rekognition/start-text-detection.html
but when I try to use it on the cli, it's not an option.
$ aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/18.6.0 botocore/2.0.0dev4

$ aws rekognition start-text-detection --video "S3Object={Bucket=dewy-vods,Name=bans.mp4}"
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
**aws: error: argument operation: Invalid choice, valid choices are:**

**Comment by klaytaybai** [comment]
Hi @thedewpoint, start-text-detection was only added in the past 8 days.  Please update your AWS CLI to use it.

**Comment by thedewpoint** [comment]
@klaytaybai thats kind of crazy that i just decided to use it for the first time right after it was released. Weird timing. I installed the latest cli last night, has it been updated since then?

**Comment by thedewpoint** [comment]
@klaytaybai you're right i reinstalled it again, less than 24 hours later and now the option is there. Thank you!
