### ISSUE TITLE
aws ecr get-login error: argument operation: Invalid choice

### ISSUE THREAD

**Issue by arthurliebhardt** [aws/aws-cli#5014]
Hello,

$(aws ecr get-login --no-include-email --region eu-central-1)

gives me following:

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:

aws-cli/2.0.0 Python/3.8.1 Darwin/19.3.0 botocore/2.0.0dev4 are my versions.

**Comment by arthurliebhardt** [comment]
Ok the documentation states: "This command is deprecated. Use get-login-password instead."

**Comment by rpnguyen** [comment]
The [AWS CLI version 2 migration guide](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-ecr-get-login) has information about the ECR changes introduced in V2. [`ecr get-login-password`](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html) is now the recommended method for logging in to ECR. For more information, see [Registry Authentication](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth).

**Comment by mayordwells** [comment]
If you find yourself here, save yourself some time/headache by skipping the login step.

Using ECR credentials helper, referenced in this documentation - https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html 
With that helper, There is no need to use `docker login` or `docker logout`.

Find the installation instruction here - https://github.com/awslabs/amazon-ecr-credential-helper

**Comment by omerh** [comment]
You can use this: https://github.com/omerh/aws-docker-login

**Comment by yaireclipse** [comment]
If you still want to use cli (maybe for automation), this is the full command, [according to the official docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html#registry_auth), that worked for me:

```shell
aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
```

where:
- `<region>` - is the region name to which you want to push the image, e.g. `us-east-1`
- `<aws_account_id>` - [how to find your aws account ID](https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html)

Note that `--username` should remain set to `AWS`.

**Comment by alam0rt** [comment]
I alias this to ecr-login
```shell
 aws ecr get-login-password | docker login --username AWS --password-stdin "$(aws sts get-caller-identity | jq .Account -r).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
```

Requires jq to be installed.

**Comment by raxit65535** [comment]
I am getting error with  `aws ecr get-login-password | docker login --username AWS --password-stdin <>.dkr.ecr.<>.amazonaws.com`
`Error: Cannot perform an interactive login from a non TTY device`
What is the reason for that?

**Comment by danielmaartens-sovtech** [comment]
@raxit65535 I am also getting this error output with ```aws ecr get-login-password | docker login --username AWS --password-stdin <>.dkr.ecr.<>.amazonaws.com```

![image](https://user-images.githubusercontent.com/59686723/83734081-cd491480-a64e-11ea-9cbf-5cc6bb3809f0.png)

But as you can see from the following commands if I use ```get-login``` argument (which is deprecated) then no error is thrown for the command before the pipe and it tries the command after the pipe.

This tells me that maybe the cli we're using is out of date ? I don't know if that is even how it works. But maybe that is the issue.

I will update my cli and then try again and keep you posted.

**Comment by danielmaartens-sovtech** [comment]
@raxit65535 Yup as I suspected.

One of the breaking changes is:

![image](https://user-images.githubusercontent.com/59686723/83734897-e605fa00-a64f-11ea-8bae-070038fe9739.png)

**Comment by yaireclipse** [comment]
> I am getting error with `aws ecr get-login-password | docker login --username AWS --password-stdin <>.dkr.ecr.<>.amazonaws.com`
> `Error: Cannot perform an interactive login from a non TTY device`
> What is the reason for that?

@raxit65535 AFAIK this error (in this context) might occur due to not being logged in to AWS through the AWS CLI. Try running `aws configure`.

**Comment by danielmaartens-sovtech** [comment]
@yaireclipse  @raxit65535 

Confirmed. if you're still using aws cli v1 then upgrading aws cli to version 2 fixes that error (at least if yours is in the same context as the one I've been getting). Hopefully it solves your issue too @raxit65535 .

**Comment by yaireclipse** [comment]
@danielmaartens-sovtech I'm not sure if it's you or me that miss something, but it seems that @raxit65535 already uses the new CLI version (`get-login-password`) and yet get that error. Hence my suggestion for making sure he's logged in 😃 .

**Comment by danielmaartens-sovtech** [comment]
@yaireclipse @raxit65535  What cli version are you using ?

**Comment by someorganicmatter** [comment]
> I am getting error with `aws ecr get-login-password | docker login --username AWS --password-stdin <>.dkr.ecr.<>.amazonaws.com`
> `Error: Cannot perform an interactive login from a non TTY device`
> What is the reason for that?
@raxit65535 Are you executing this command from an EC2 instance by any chance?

**Comment by danielmaartens** [comment]
> @danielmaartens-sovtech I'm not sure if it's you or me that miss something, but it seems that @raxit65535 already uses the new CLI version (`get-login-password`) and yet get that error. Hence my suggestion for making sure he's logged in 😃 .

@yaireclipse He did not specify which version he is using.

@raxit65535 can you please confirm that `get-login-password` appears in the list of available commands when you execute `aws ecr help` ? If it does not, but instead has `get-password` then you are using CLI v1.

**Comment by someorganicmatter** [comment]
@danielmaartens-sovtech I am also facing the same issue. I have the setup on an EC2 instance (if that makes any difference). I just checked executing `aws ecr help`. Did you mean `get-login` instead of `get-password`?
The list of available commands shows `get-login` instead of `get-password` or `get-login-password` for me.

**Comment by thalesfc** [comment]
It is so non-sense that the comment is deprecated but still used in most of aws tutorials ==> https://github.com/aws/amazon-sagemaker-examples-community/blob/215215eb25b40eadaf126d055dbb718a245d7603/bring-your-own-container/fairseq_translation/fairseq_sagemaker_pretrained_en2fr.ipynb
