### ISSUE TITLE
awscli-cwlogs module is unable to parse timestamps on February 29 when the format does not contain a year (e.g. syslog format)

### ISSUE THREAD

**Issue by dmason-atlassian** [aws/aws-cli#5020]
As soon as the date ticked over to Feb 29 we noticed that the cwlogs module began failing to parse syslog messages, showing an error like this:

```Feb 29 00:00:02 ip-XXX-XXX-XXX-XXX aws[PID]: 2020-02-29 00:00:02,402 - cwlogs.push.reader - WARNING - PID - Thread-NN - Fall back to previous event time: {'timestamp': 1582934397000, 'start_position': NNNNNL, 'end_position': NNNNNL}, previousEventTime: 1582934397000, reason: timestamp could not be parsed from message.```

Digging into the code for this, it looks like the cwlogs module uses strptime, which will always fail to parse February 29 unless it's explicitly passed a leap year in the format. There is some handling for a missing year, but this does not occur until after the strptime call, so it would have already bailed out with a `ValueError: day is out of range for month` before reaching that point.

**Comment by kdaily** [comment]
Thanks for the report, @dmason-atlassian. Looks like a Python bug that the CLI is affected by too:

https://bugs.python.org/issue26460

**Comment by kdaily** [comment]
Hi @dmason-atlassian - Unfortunately this plugin is no longer supported and is part of a deprecation campaign. 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

You are encouraged to use the new Cloudwatch Agent, described here:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html

There is not an AWS CLI plugin. The new agent is written in Go and uses the API directly.

**Comment by zulk85** [comment]
thanks for the update mate...
