### ISSUE TITLE
IDEAS WANTED - CLI Example Scripts that illustrate common customer scenarios

### ISSUE THREAD

**Issue by bisdavid** [aws/aws-cli#5021]
Everyone,

What do **_you_** use the CLI for?  If you're trying to use more than simple one-line CLI commands and are writing full scripts to automate AWS tasks using the AWS CLI, then I'd love to hear from you! 

I'm looking for ideas for CLI example scripts that go beyond the common "one-liner".  For example, see the following in our new [AWS Code Example Repo](https://github.com/awsdocs/aws-doc-sdk-examples):

* [A collection of functions that perform C-R-U-D operations on Amazon S3 Buckets and objects](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/aws-cli/bash-linux/s3/bucket-lifecycle-operations).
* [A scenario-based example that shows how to change the Instance Type of a running EC2 instance](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/aws-cli/bash-linux/ec2/change-ec2-instance-type).

These scripts are both linted and tested (and include test scripts that show how to invoke them).

I want to create examples that'll help you complete your day-to-day ops automation tasks. I know that means more scenario focused examples like the second one above, not just spewing out lots of C-R-U-D examples (although I know those hold value as well).

What do you want to see?  If you have ideas for examples that you'd like to see, or want to submit your own examples, please contact us at [aws-cli-docs@amazon.com](aws-cli-docs@amazon.com).  **_I'm looking forward to hearing from you!_**

Thank you,
AWS Tools and SDKs Code Example Team

**Comment by abitrolly** [comment]
@bisdavid the most common scenario is to use S3 as a hosting for web app uploads. The algorithm.

1. Create AIM user for web app.
2. Create S3 bucket.
3. Let user write and read files in the bucket.
4. Make sure files are accessible from the web read-only.

Step 3 is especially hard, because there are too many ID types and ways of access controls that don't work.
