### ISSUE TITLE
Unable to logout/login, throws error "Missing the following required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id. To make sure this profile is properly configured to use SSO, please run: aws configure sso"

### ISSUE THREAD

**Issue by pcChristopher** [aws/aws-cli#5024]
Cannot successfully logout and then login.  Every time I run aws sso login it says

> [ubuntu] $ aws sso login
> Missing the following required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id. To make sure this profile is properly configured to use SSO, please run: aws configure sso

Easily reproducible.  If I run aws configure sso and go through it, then aws sso logout and aws sso login, it throws the error.  It forces me to run aws sso configure every time.  Login does work.  I can describe-instances with the profile.  It just doesn't login twice.

Installed following https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html by downloading and running sudo ./aws/install.

Here's a full walk through

> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $ rm -Rf ~/.aws
> 
> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $ aws configure sso
> SSO start URL [None]: https://1111.awsapps.com/start
> SSO Region [None]: us-east-1
> Attempting to automatically open the SSO authorization page in your default browser.
> If the browser does not open or you wish to use a different device to authorize this request, open the following URL:
> 
> https://device.sso.us-east-1.amazonaws.com/
> 
> Then enter the code:
> 
> FRKJ-HMNB
> There are 50 AWS accounts available to you.
> Using the account ID 111111111111
> There are 2 roles available to you.
> Using the role name "AdministratorAccess"
> CLI default client Region [None]: us-east-1
> CLI default output format [None]: text
> CLI profile name [AdministratorAccess-111111111111]:
> 
> To use this profile, specify the profile name using --profile, as shown:
> 
> aws s3 ls --profile AdministratorAccess-111111111111
> 
> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $ aws s3 ls --profile AdministratorAccess-111111111111
> 2020-01-13 10:17:09 111111111111toronctiociterciltan

> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $ aws sso logout
> 
> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $ aws sso login
> 
> Missing the following required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id. To make sure this profile is properly configured to use SSO, please run: aws configure sso
> 
> [/home/ubuntu]
> [ubuntu][L5CG84142B6] $

> [ubuntu]$ aws --version
> aws-cli/2.0.1 Python/3.7.3 Linux/4.4.0-19564-Microsoft botocore/2.0.0dev5

> [ubuntu] $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.4 LTS
> Release:        18.04
> Codename:       bionic

Immediately after aws sso configure, when it's working, filesystem looks like

> [/home/ubuntu/.aws]
> [ubuntu][L5CG84142B6] $ find .
> .
> ./cli
> ./cli/cache
> ./config
> ./sso
> ./sso/cache
> ./sso/cache/20d99b68cb9ccccb534521c3ff0376cbf7f39b4d.json
> ./sso/cache/botocore-client-id-us-east-1.json

After performing aws sso logout, one of the files is removed

> [ubuntu][L5CG84142B6] $ aws sso logout
> 
> [/home/ubuntu/.aws/sso/cache]
> [ubuntu][L5CG84142B6] $ ll
> total 4
> drwxr-xr-x 1 ubuntu ubuntu 4096 Mar  2 12:59 .
> drwxr-xr-x 1 ubuntu ubuntu 4096 Mar  2 12:48 ..
> -rw------- 1 ubuntu ubuntu  740 Mar  2 12:48 botocore-client-id-us-east-1.json
> 
> [/home/ubuntu/.aws/sso/cache]

**Comment by KaibaLopez** [comment]
Hi @pcChristopher ,
Can you try specifying your profile when you use the login command? 
`aws sso login --profile my-sso-profile`
And let me know if you get the same error?

**Comment by pcChristopher** [comment]
Hi @KaibaLopez Ah!  Yes, that worked.  The solution is to specify the profile with the login.  That was unintuitive to me.  My ability to "aws sso logout" without the profile lead me to believe that I could login without the profile.  Maybe echo a usage prompt for both of them telling me that it's missing the --profile parameter and force me to use profile during logout.

**Comment by KaibaLopez** [comment]
Hi @pcChristopher,
Glad that worked. 
So the thing is that the command without --profile is valid, it uses the environment variable AWS_PROFILE. So the error might be a bit confusing but it is not technically wrong.

**Comment by haxo5** [comment]
same problem and i also did specified my profile name.. and manually i added sso url, region, id into ~/aws/config that was the insrtuction and i did all that. but still it throws "Missing the following required SSO configuration values: sso_start_url, sso_region, sso_role_name, sso_account_id. To make sure this profile is properly configured to use SSO, please run: aws configure sso"

**Comment by kurtislamb** [comment]
Worth noting a few things with this.

 I added my SSO values manually so the ~/.aws/config file and kept getting the same error.

To resolve I ran aws configure sso, when prompted with `CLI profile name` I responded with sso. so now when I run ` aws sso login --profile sso` it finds the profile correctly

**Comment by lauradreith** [comment]
Having the same issue, when I manually added the values to the ~/.aws/config file I got a different error: Error loading SSO Token: Token for https://awsidentitycenterurl/start/ does not exist

**Comment by lauradreith** [comment]
this resolves the issue: https://www.reddit.com/r/aws/comments/zk456d/new_aws_cli_and_sso_sessions_profiles_and_legacy/

**Comment by dgdg-app** [comment]
This is so clunky

**Comment by Kevin8428** [comment]
I just ran into an issue like this and it turned out the AWS config file had bad white space formatting for a profile. The `sso_start_url` field had a mix of tab and spaces giving the message `Missing the following required SSO configuration values: sso_region`. Changing all fields to spaces fixed it.
