### ISSUE TITLE
Glacier upload-multipart content-length error for last part

### ISSUE THREAD

**Issue by Reuno92** [aws/aws-cli#5027]
Hello !

I have a trouble with command `glacier upload-multipart-part`.

I'm trying to upload a file sized more 14,3 Mo. I create a loop with a condition, if my chunk's size is equal at my part's size defined at 1Mo. 

The byte range begin at 0 to 1Mo - 1 and byte range following begin at byte's end previously to next 1Mo.

else my chunk begin by last byte's end previously and finish by the total of file's size.

My last chunk's size is less than 1Mo and when i send to AWS Glacier, I received and error `InvalidParameterValueException`.

```#bash
An error occurred (InvalidParameterValueException) when calling the UploadMultipartPart operation: Content-Range: bytes 13631488-14296893/* is incompatible with Content-Length: 665405
```

I counted my iterations like this for understand my errors:
```
ChunkName:  /Users/account/Desktop/INPUT/TO_PUBLISH/123/chunkal Chunk size:  1048576 sended
bytes range 11534336-12582911/* total chunk 1048576
total uploaded:  12582912

ChunkName:  /Users/account/Desktop/INPUT/TO_PUBLISH/123/chunkam Chunk size:  1048576 sended
bytes range 12582912-13631487/* total chunk 1048576
total uploaded:  13631488

ChunkName:  /Users/account/Desktop/INPUT/TO_PUBLISH/123/chunkan Chunk size:  665405 sended

An error occurred (InvalidParameterValueException) when calling the UploadMultipartPart operation: Content-Range: bytes 13631488-14296893/* is incompatible with Content-Length: 665405
bytes range 13631488-14296893/* total chunk 665405
total uploaded:  14296893
totalSize:  14296893
```

Do you have a solution for me ?

**Comment by kdaily** [comment]
Hi @Reuno92,

I think I'll need to see more of your logs in order to help debug. Can you run your command(s) with the `--debug` flag? Thanks.

**Comment by Reuno92** [comment]
> Hi @Reuno92,
> 
> I think I'll need to see more of your logs in order to help debug. Can you run your command(s) with the `--debug` flag? Thanks.

Hi @kdaily,

My issue was solve since any months.
I have add 1 byte in my last part and it's working.

I close this ticket, sorry for my non-return.
