### ISSUE TITLE
aws configure with --profile option credentials location

### ISSUE THREAD

**Issue by Arlington1985** [aws/aws-cli#5028]
I have set `AWS_SHARED_CREDENTIALS_FILE` to a custom location and it only contains the default profile. Additionally, I would like to set a new profile and specify credentials with 'aws configure --profile private' command. When I execute it this command, prompts new ACCESS_KEY, SECRET_KEY, REGION and FORMAT parameters to be filled and at the end 
- `ACCESS_KEY, SECRET_KEY` will be written to `AWS_SHARED_CREDENTIALS_FILE` without validating it already contains some access key or not. Because when I opened the file in the following format
```
[default]
aws_access_key_id = $default_access_key_id
aws_secret_access_key = $default_secret_access_key
aws_session_token = $default_session_token[private]
aws_access_key_id = $private_access_key_id
aws_secret_access_key = $private_secret_access_key
```
As you may already be spotted new profile was written to the file as if the file was empty before. And when you execute a command CLI throws an error

- The second problem is I think it's better to ask where you want to write new profile settings including access and secret key.

**Comment by KaibaLopez** [comment]
Hi @Arlington1985 ,
Just to be clear here, the first problem is that instead of overwriting the old [default] profile with the new credentials, it just appends the new values to it?

**Comment by Arlington1985** [comment]
It shouldn't overwrite, because I am setting up with new profile called `private`. It just adds to the file without appending new line before `[private]`

**Comment by KaibaLopez** [comment]
hmm odd, I can't seem to reproduce this behavior, when I run the command it adds the new profile normally both for custom locations and the default .aws/credentials. 

What version of the cli and what platform are you using? 
Also, any other info you got on how to reproduce would help a bunch.

**Comment by Arlington1985** [comment]
As I already wrote:

> I have set AWS_SHARED_CREDENTIALS_FILE to a custom location and it only contains the default profile.

When I manually add a new line to the end of this credentials file, the new profile also adding normally as expected.  

Here is the version of aws cli I use:

`aws-cli/1.16.306 Python/3.6.0 Windows/10 botocore/1.13.42`
--

**Comment by KaibaLopez** [comment]
Yea no I saw that, again I did try changing the location and still my cli works as expected.

The version you have is rather old though, so unless you have a reason why you can't I'll suggest you upgrade, hopefully this was a bug that has been fixed in recent versions.
But just to verify, are you using mac, windows or linux when running this?

**Comment by Arlington1985** [comment]
I upgraded and tested with newer version: `aws-cli/1.18.12 Python/3.6.0 Windows/10 botocore/1.15.12` . The result is same. My OS is Windows 10, it might make sense

**Comment by Arlington1985** [comment]
Also, do you consider in your test that at the end of the default profile is `aws_session_token`?

**Comment by KaibaLopez** [comment]
> My OS is Windows 10, it might make sense

You'd be surprised at what I've learned not to assume, the hard way. 
Anyways, I was able to reproduce this on version 1.18, specifically on windows, but if you update to V2 it no longer happens. 
So yea that'd be your best bet if you want to use configure this way.
