### ISSUE TITLE
v2: Helper utility to run commands across multiple accounts

### ISSUE THREAD

**Issue by joeydumont** [aws/aws-cli#5029]
When managing a AWS Organization with multiple accounts, it is difficult to have a list of all provisioned resources, say, for instance, a list of all S3 buckets in the organization. With v2, I would like to see a way to get credentials for multiple roles in multiple accounts at once, and run the specified command on all of these accounts.

The UI could be similar to `aws2 configure sso`, but it would let you select multiple roles and put their profile names in a list. This would probably work better as a temporary "mode" of operation that could be switched in and out of. In that mode, running  `aws2 s3api list-buckets` would return a list of S3 buckets that exist in all selected accounts, if the user's selected role had permission to run ListBuckets in that account.

Thank you for your consideration.

**Comment by kdaily** [comment]
Hi @joeydumont,

Thanks for the feature request. I think this kind of thing for your specific use case is beyond the scope of the AWS CLI. AWS has a service called AWS Config for tracking and managing all resources in an account. There is a section in there on how to aggregate resources across accounts for exactly the kind of auditing purposes you are describing. 

https://docs.aws.amazon.com/config/latest/developerguide/config-concepts.html#multi-account-multi-region-data-aggregation

You can already perform these actions via the AWS CLI:

- https://docs.aws.amazon.com/config/latest/developerguide/gs-cli.html
- https://docs.aws.amazon.com/config/latest/developerguide/set-up-aggregator-cli.html

I hope this helps you with your situation!

**Comment by joeydumont** [comment]
It makes sense to leverage AWS Config. I've actually written a small utility for myself to quickly list resources in all subaccounts, using the AWS SDK.

Thanks for the response!
