### ISSUE TITLE
secretsmanager default value for VersionStage is not AWSCURRENT, in spite of docs

### ISSUE THREAD

**Issue by oliverw1** [aws/aws-cli#5031]
In spite of the [documentation](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#SecretsManager-GetSecretValue-request-VersionStage), the default value for the VersionStage parameter is not AWSCURRENT when both VersionStage and VersionId are omitted.

I’ve experienced this on an AWS EMR cluster. Simple script (with some variables tweaked for security reasons):
```
[hadoop@ip-10-164-4-39 ~]$ export SECRET="arn:aws:secretsmanager:eu-west-1:<account>:secret:<name>"
[hadoop@ip-10-164-4-39 ~]$ aws secretsmanager get-secret-value --secret-id ${SECRET}  --version-stage AWSCURRENT --region eu-west-1
{
    "Name": "<name>",
    "VersionId": "some-hash,
    "SecretString": "foo",        
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1582641518.402,
    "ARN": "arn:aws:secretsmanager:eu-west-1:<account>:secret:<name>-ayDCQ2"
}
[hadoop@ip-10-164-4-39 ~]$ aws secretsmanager get-secret-value --secret-id ${SECRET} --region eu-west-1

An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::<different_account>:assumed-role/<some-role-with-permissions>/i-0abc46f15c8f04659 is not authorized to perform: secretsmanager:GetSecretValue on resource: arn:aws:secretsmanager:eu-west-1:<account>:secret:<name>-ayDCQ2
``` 
Note that in this particular situation, there’s a trust relationship set up between two accounts: the one from which I'm executing these commands is accessing the secrets in another account.

Not sure if this is an error in the documentation or only because of the situation where one account accesses details in another.

**Comment by kdaily** [comment]
Hi @oliverw1, I'll check with the API team to see if this is expected due to the situation you described. Thanks!

**Comment by kdaily** [comment]
I confirmed that if I perform this action on a secret in the same account, I do not encounter this issue:

```
$ aws secretsmanager get-secret-value --secret-id ${SECRET} --region us-west-2
{
    "ARN": "arn:aws:secretsmanager:us-west-2:account:secret:aws-cli-issue-5031-GmOZCQ",
    "Name": "aws-cli-issue-5031",
    "VersionId": "8901250c-69f9-4769-abb1-f5a31d5fe614",
    "SecretString": "hello there",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1601065193.281
}
```

**Comment by kdaily** [comment]
Can you also provide the version of the AWS CLI that you encountered this with, please? You can find this with `aws --version`, or attach debug logs with `aws --debug`. Thanks!

**Comment by kdaily** [comment]
I also note that this premium support knowledge base article uses the same example as you described (explicitly providing a version stage):

https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/

**Comment by pk864** [comment]
Hello Oliverw1,

What resource policy you have on your cross account secret? If the resource policy is using versionstage condition key, then you must pass the version stage flag with GetSecretValue API. Note, by default if no stage is supplied In GetSecretValue request then ASM will return CURRENT version but in case when resource policies are involved that too specifically looking for version stage parameter in the request then we have to supply the parameter.

**Comment by kdaily** [comment]
In order to follow up more, I would need to see what is in the IAM policy to be sure that there is nothing blocking it (as noted by @pk864).

**Comment by oliverw1** [comment]
I'll need to check with the client I was working with at that time to find out what the IAM policy was. Will come back to you in 2 weeks tops.

As for aws-cli version: it was the one that was installed by default on EMR6.0.0beta.

**Comment by oliverw1** [comment]
The client forwarded me these details: 

```sh
{
  "Version": "2012-10-17",
  "Statement": [
      {
        "Effect": "Allow",
        "Principal": {  "AWS": [ "arn:aws:iam::<account1>:root" ] },  
        "Action": "secretsmanager:GetSecretValue",
        "Resource": "arn:aws:secretsmanager:*:<account2>:secret:<some_prefix>-*",
        "Condition": {  "ForAnyValue:StringEquals": { "secretsmanager:VersionStage": "AWSCURRENT"  }  }
       }
     ]
   }
```

So if I understood @pk864 correctly, it's because of that last condition that I needed to explicitly add `--version-stage AWSCURRENT` to the CLI call?

If so, I'm wondering if I should've been able to spot this earlier. As mentioned, the [docs](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#SecretsManager-GetSecretValue-request-VersionStage) didn't highlight this, but I do understand it's a special case.

**Comment by kdaily** [comment]
Hi @oliverw1, I confirmed with the Secrets Manager team and the note from @pk864 is correct. I'll review the documentation to see if something should be updated. Thanks!

**Comment by pk864** [comment]
Hey @oliverw1 and @kdaily , this premium support knowledge center [document ](https://aws.amazon.com/premiumsupport/knowledge-center/secrets-manager-share-between-accounts/)regarding setting up cross account secrets does mention about supplying version stage parameter. @kdaily it would be great if the same information is also mentioned in this section of the public [doc ](https://docs.aws.amazon.com/secretsmanager/latest/userguide/tutorials_multiple_accounts.html) Thanks!

**Comment by kdaily** [comment]
Hi @oliverw1, I'm still working on providing a better example or documentation for this.

**Comment by kdaily** [comment]
Hi @oliverw1, 

As an update the team confirmed @pk864's statement above. It is a special case and isn't something that can be documented here as it's specifically related to the policy and not the standard behavior of the API. I appreciate you raising the issue and providing this feedback!
