### ISSUE TITLE
ebs-root-volume-size help text inconsistent with AWS docs

### ISSUE THREAD

**Issue by tekumara** [aws/aws-cli#5033]
ebs-root-volume-size help text applies to to versions of Amazon EMR earlier than 4.0:

https://github.com/aws/aws-cli/blob/637a04058bab0931f37e4f1b61a1641a9b954f89/awscli/customizations/emr/helptext.py#L337

but [Specifying the Amazon EBS Root Device Volume Size](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-custom-ami-boot-volume-size.html ) states

> This option is available only with Amazon EMR version 4.x and later

**Comment by KaibaLopez** [comment]
Hi @tekumara ,
Thanks for pointing this out, would you mind making a PR to change the error in the help text?

**Comment by tekumara** [comment]
@KaibaLopez I've created https://github.com/aws/aws-cli/pull/5043

**Comment by throwaway8787** [comment]
@KaibaLopez - this can be closed, the PR has been merged.
