### ISSUE TITLE
aws-cli requires 'less' be installed on linux

### ISSUE THREAD

**Issue by chrisgilmerproj** [aws/aws-cli#5038]
I'm using aws cli v2.0.1 and ran this command:

```sh
aws rds create-db-snapshot --db-instance-identifier "$db_instance_identifier" --db-snapshot-identifier "$db_snapshot_identifier" --tags "${tags[@]}"
```

This is the same command I was using in the aws cli v1. But now when I run it I get this error output:

```text
[Errno 2] No such file or directory: 'less': 'less'
Exited with code exit status 255
```

The solution for me was to run:

```sh
sudo apt-get update && sudo apt-get install -yy less
```

I didn't see `less` as a prerequisite in the docs. I also don't understand why its needed now. For additional context I'm running inside `docker` with the `circleci/python:3.8-buster` as my base image.

**Comment by chrisgilmerproj** [comment]
I should also identify that the snapshot was created, so the command was sent and did what I wanted. It failed when delivering output.

**Comment by chrisgilmerproj** [comment]
I just found https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager . On the one hand it's great that I can set `AWS_PAGER`. On the other hand I dislike having an opt-out feature where it ought to be opt-in. 

My only suggestion is that the doc for prereqs make this more clear.

**Comment by KaibaLopez** [comment]
Hi @chrisgilmerproj ,
Yea this sounds like "less" should at least be listed as a prerequisite if it's used by default on the cli.
Thanks for pointing this out to us, I'll see about updating the documentation.

**Comment by chrisgilmerproj** [comment]
@KaibaLopez - I appreciate it, thanks for the updates.

**Comment by jonrh** [comment]
Thank you @chrisgilmerproj. I ran into the same problem and was indeed surprised the dependency wasn't listed as a requirement. Specifically I was performing a CloudFront invalidation in a CircleCI container which didn't have the `less` command. I solved it by prefixing the command invocation with `AWS_PAGER=""` as the v2 migration guide stated:

```bash
AWS_PAGER="" aws cloudfront create-invalidation \
  --distribution-id ABCD1234 \
  --paths '/*'
```

**Comment by Jean-Baptiste-Lasselle** [comment]
omg you guys rock, I so really needed to fix this at 6:00am... :) :) :+1: :100:

**Comment by chrisgilmerproj** [comment]
Last activity on this was forever ago so I'm closing this out.

**Comment by mattolenik** [comment]
This bug did not go away just because people stopped talking about it! It's still present in the latest release!
