### ISSUE TITLE
aws cloudformation package fails when Code property of Lambda is a file

### ISSUE THREAD

**Issue by steadysupply** [aws/aws-cli#5040]
Granted, #4497, but this seems like an oversight. I take it that Lambda packages should always be Zip files, so the `package` subcommand should always render Zip files, no?

At least document the behaviour in https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

```
2020-03-05T08:14:46.950Z  CREATE_FAILED                                 AWS::Lambda::Function         Could not unzip uploaded file. Please check your file, then try to upload again. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; blah blah blah
```

**Comment by kdaily** [comment]
Hi @steadysupply, 

Can you provide the version of the CLI and the full command you're running with `--debug` turned on? Thanks!

**Comment by steadysupply** [comment]
@kdaily I'm afraid I have no idea what version of the Amazon CLI I happened to be using 6 months ago. I imagine it was whatever the latest version was when I posted this issue.

**Comment by kdaily** [comment]
Understood @steadysupply. I misunderstood your initial error. If an unzipped file is supplied I would expect a zipped file to be stored and it's location returned in the template, just as if a directory had been supplied (and zipped). I agree that it's not properly documented at least. Thanks!
