### ISSUE TITLE
[v2] aws cli v2 does not respect AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cli#5052]
There's a ton of various bugs regarding cli v2, but this is probably quite simple to fix:

If configured with sso credentials in a name profile, aws cli v2 disregards specifying that profile using the environment variable `AWS_PROFILE`.

this works:
`aws s3 ls --profile mytest`

this fails:
`AWS_PROFILE=mytest aws s3 ls`

Expected behaviour: both variants behave the same way.

**Comment by KaibaLopez** [comment]
Hi @trondhindenes ,
Yea, I'm also having trouble using the AWS_PROFILE env variable. 
Thanks for pointing this out to us.

**Comment by kyleknap** [comment]
Hmm. I'm not able to reproduce this. Specifically, I am using the SSO configured profile:
```
[profile view-cli-team]
sso_start_url = https://cli-reinvent.awsapps.com/start
sso_region = us-west-2
sso_account_id = 236300331245
sso_role_name = ViewOnlyAccess
```
and this is the version of the CLI v2 I'm using:
```
$ aws --version
aws-cli/2.0.3 Python/3.7.4 Darwin/17.7.0 botocore/2.0.0dev7
```

Then I called the following from the command line:
```
$ AWS_PROFILE=view-cli-team aws sts get-caller-identity
{
    "UserId": "AROATOBEY5DW6PVSW44OF:myuser@amazon.com",
    "Account": "236300331245",
    "Arn": "arn:aws:sts::236300331245:assumed-role/AWSReservedSSO_ViewOnlyAccess_81be674e157a82d0/myuser@amazon.com"
}
```
and its definitely using the SSO account for that profile.

@trondhindenes or @KaibaLopez can you provide a minimal set of steps for me to follow to help reproduce this?

**Comment by mattwillsher** [comment]
I'm running from homebrew version and upgrading to version 2.0.0_1 seems to have fixed the issue.

**Comment by trondhindenes** [comment]
yup, after updating to `aws-cli/2.0.2` the problem is gone. This issue can be closed.
