### ISSUE TITLE
Creating config file using awscli v2 works with AWS SSO. Feature request to enable it for Okta

### ISSUE THREAD

**Issue by rajesh-bachu** [aws/aws-cli#5060]
Creating config file using awscli v2 works with AWS SSO. Feature request to enable it for Okta

**Comment by KaibaLopez** [comment]
Hi @rajesh-bachu ,
Sorry to say, but this would not be the sdk's responsibility to make happen, I'd recommend asking Okta's support to handle it.

**Comment by yrsurya** [comment]
https://github.com/aws/aws-cli/issues/4647 - According to this it says also supports other SAML providers so can I know will it support Okta too ?
