### ISSUE TITLE
Package the AWS command-line as a "console script" entry point

### ISSUE THREAD

**Issue by danizen** [aws/aws-cli#5063]
**DESIRED BEHAVIOR**

The aws command on Windows should be an EXE rather than a batch file, because Python supports that well, and it is low-hanging fruit.

**CURRENT BEHAVIOR**

aws is a batch file, and this limits how it can be integrated with some build systems.

**AN EASY FIX?**

This could be addressed with changes to `setup.py`, depending on how this affects Python 2.7 support.  Python 2 is end of life, and on Windows, Python 2.7's install does not even include pip.

```python
    entry_points={'console_scripts': [
        'aws = awscli.clidriver:main',
    ]},
```

**MOTIVATING EXAMPLE**

This should work:

```xml
    <target name="deploy"
            description="--> Upload the S3 file to Amazon S3">        
        <exec failonerror="true" executable="aws">
            <arg value="s3" />
            <arg value="cp" />
            <arg value="${target.file}" />
            <arg value="${bucket.path}" />
        </exec>
    </target>
```

Since aws is a bat file rather than an executable, this fails on Windows.

**Comment by kdaily** [comment]
Hi @danizen, thanks. I looked at the installations via MSI for the AWS CLI v1 and v2, and both of these have an `exe`. By default, these are available at `C:\Program Files\Amazon\AWSCLI\aws.exe` and `C:\Program Files\Amazon\AWSCLIV2\aws.exe`, respectively for V1 and V2. Can you describe how you are installing? Can you provide a little more details as to which build systems you've encountered difficulty with?

**Comment by danizen** [comment]
@kdaily, the issue and suggestion is for the Python packaging, rather than the MSI packaging.  No one I know installs Python packages as MSIs, indeed most of my developers would be unable to do that, because they do not have administrative permissions. I, and my programmers, are installing it as follows:

```
pip install awscli
```

The code at https://github.com/aws/aws-cli/blob/8bb8c89500ac7772c746818a6049706218827d9c/setup.py#L51 is a very old way of setting up scripts that does not work properly on Windows.  The newer way is to use the console_scripts entry point.  The example below does this just for the main command-line - the other scripts, which are more specific to Linux shells such as bash and zsh, should remain as they are.

```python
    entry_points={'console_scripts': [
        'aws = awscli.clidriver:main',
    ]},
```

Here is the documentation, but what they do not say is that for Linux/Mac, pip installs an executable script, but for Windows, it creates an exe file that loads Python though DLLs and then executes the correct Python module.

**Comment by tomjakubowski** [comment]
+1. This would make it easier to use the aws cli from Bazel, using [py_console_script_binary](https://rules-python.readthedocs.io/en/stable/api/python/entry_points/py_console_script_binary.html#py_console_script_binary)
