### ISSUE TITLE
aws --version command on windows is showing older version of AWS CLI

### ISSUE THREAD

**Issue by vaishali-jain** [aws/aws-cli#5065]
I have installed newer version of aws cli but I still see the old version being returned after I run the command aws --version on command line in windows.

**Comment by aherzog-trx** [comment]
Did you follow the instructions under "Important" on the [installation page](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html)? You should remove v1, or create a symbolic link for v1 prior to installation of v2.

**Comment by ndrshrzg** [comment]
Did you follow the "Important" instructions on the [installation page](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html)? You need to remove v1, or create a  symlink to v1, prior to installing v2.
