### ISSUE TITLE
Lambda invoke doesn't pass --client-context correctly

### ISSUE THREAD

**Issue by K-JBoon** [aws/aws-cli#5069]
Hey,

Haven't had time to delve deeply into why this is happening yet, but something I observed when writing some tooling is that --client-context on `aws lambda invoke` isn't being passed properly somehow.

I'm using the Rust runtime (https://github.com/awslabs/aws-lambda-rust-runtime) and passing some client context data over the CLI as a method of adding some overrides for manual invocations like so:

`aws lambda invoke --function-name function-name --invocation-type Event --payload fileb:///tmp/tmp.LiPA8tlQnn --client-context eyJjbGllbnQiOnsiaW5zdGFsbGF0aW9uSWQiOiIxMjMiLCJhcHBUaXRsZSI6ImFwcHRpdGxlIiwiYXBwVmVyc2lvbk5hbWUiOiIxIiwiYXBwVmVyc2lvbkNvZGUiOiIxIiwiYXBwUGFja2FnZU5hbWUiOiJwYWNrYWdlIn0sImVudmlyb25tZW50Ijp7InBsYXRmb3JtIjoibGludXgifSwiY3VzdG9tIjp7InNvbWVfb3ZlcnJpZGUiOiJzb21lX3ZhbHVlIn19Cg== --log-type Tail --profile some-profile ./execution.log`

This fails the following check in Rust (where context is the default Context type):

```rust
    if let Some(client_context) = context.client_context {
        options = client_context.custom;
    }
```

Works with AWS CLI v1: `aws-cli/1.18.22 Python/3.6.9 Linux/5.3.0-40-generic botocore/1.15.22`
Fails with AWS CLI v2: `aws-cli/2.0.3 Python/3.7.3 Linux/5.3.0-40-generic botocore/2.0.0dev7`

**Comment by stealthycoin** [comment]
Is the payload being passed correctly? My first guess since this is a v1/v2 difference and you are passing a binary parameter would be this section of the cli migration guide: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam

If that doesn't resovle it for you can you post debug logs by adding `--debug`.
