### ISSUE TITLE
Preserve comments in CloudformationPackage command

### ISSUE THREAD

**Issue by stealthycoin** [aws/aws-cli#5070]
This feature request is to gauge interest in adding back the comment preservation feature of `cloudformation package`. We had to revert #5067 due to a regression and couldn't come up with a reasonable way to keep preserving comments, and make sure we were generating yaml that CloudFormation excepts.

Please mark this with a thumbs up reaction to show support.

**Comment by tim-finnigan** [comment]
Closing this issue as it has received no 👍 reactions or comments in over 2 years.
