### ISSUE TITLE
cloudformation create-stack's --template-body doesn't properly handle file URIs on Windows

### ISSUE THREAD

**Issue by bcj** [aws/aws-cli#5071]
`create-stack` fails with a parsing error when passed a windows file URI:
```
Error parsing parameter '--template-body': Unable to load paramfile file:///C:/Path/To/Template.yaml: [Errno 22] Invalid argument: '/C:/Path/To/Template.yaml'
```

The command succeeds if you omit one of the leading slashes (e.g., `file://C:/Path/To/Template.yaml`)

**Comment by KaibaLopez** [comment]
Hi @bcj ,
I might be missing something so sorry in advance if that's the case but, I believe that this is expected behavior, the command expects `file://`, having the extra slash causes the parsing error.
Is there any documentation that had 3 or why would you say this is a bug or problem?

**Comment by vijayopensource** [comment]
Hello All, 

I am trying to run cloud formation from within local stack on initiation, get the below error any suggestions? 

Error parsing parameter '--template-body': Unable to load paramfile file: [Errno 2] No such file or directory:

![image](https://user-images.githubusercontent.com/379195/177154677-347212cf-9e8f-4cb6-8e85-afd705a5f82a.png)
