### ISSUE TITLE
[cloud9] Membership enum does not support owner

### ISSUE THREAD

**Issue by nitrag** [aws/aws-cli#5073]
### Is this related to a problem?
No

### Feature description
According to the docs, `owner` enum is supported. https://docs.aws.amazon.com/cloud9/latest/APIReference/API_EnvironmentMember.html

### Describe alternatives you've considered
I have to give `read-write` access to users via the CLI instead of being able to set the owner and the owner sharing through Cloud9 dashboard.

### Additional context

https://docs.aws.amazon.com/cloud9/latest/APIReference/API_CreateEnvironmentMembership.html
```
An error occurred (ValidationException) when calling the CreateEnvironmentMembership operation: 1 validation error detected: Value 'owner' at 'permissions' failed to satisfy constraint: Member must satisfy enum value set: [read-only, read-write]
```

**Comment by KaibaLopez** [comment]
Hi @nitrag ,
I'm not understanding the problem here, your user does need read-write permissions to be able to set ownership this is correct behavior, plus this sounds like the cli side is working properly, if anything it's cloud9's dashboard that has the problem?

**Comment by nitrag** [comment]
The problem is I should be able to set permission to `owner`, right?

**Comment by KaibaLopez** [comment]
Hi @nitrag,
Not really, from cloud9's [documentation page](https://docs.aws.amazon.com/cloud9/latest/user-guide/share-environment.html#share-environment-member-roles) on Environment Member roles:

> An owner has full control over an environment. Each environment has one and only one owner, who is the environment creator.
