### ISSUE TITLE
s3 performance regression since v1.16.33

### ISSUE THREAD

**Issue by gfody** [aws/aws-cli#5074]
We have reduced download speed since updating aws-cli. Upgrading to v2.0.4 ~helped recover some but still significantly slower than v1.16.33~ fixed it:
| avg download | aws-cli version |
| --- | --- |
| `240.0 MiB/s` | `aws-cli/1.16.33 Python/3.6.0 Windows/10 botocore/1.12.23` |
| `130.0 MiB/s` | `aws-cli/1.18.25 Python/2.7.16 Windows/10 botocore/1.15.25` |
| `340.0 MiB/s` | `aws-cli/2.0.4 Python/3.7.5 Windows/10 botocore/2.0.0dev8` |

**edit**: v2.0.4 is only getting ~220MB/s on Server 2019 vs. 340MB/s on Server 2016, this seems to be a problem with Windows.

**Comment by ChrisAccsys** [comment]
We are also seeing slower speeds on Windows Server 2019 between v1 and v2 similar to the OP.

**Comment by kdaily** [comment]
Hi @gfody,

 Is this performance difference still occurring for you? If so, can you provide some more information as to what operations you are performing when you see reduced download speed? Thanks!

**Comment by gfody** [comment]
> 
> 
> Hi @gfody,
> 
> Is this performance difference still occurring for you? If so, can you provide some more information as to what operations you are performing when you see reduced download speed? Thanks!

I can retest later tonight. The command was `aws s3 cp s3://mybucket/test.dat .` where `.` is the local SSD on an m5dn.2xlarge

**Comment by kdaily** [comment]
Hi @gfody,

Looks like your slow speeds occur when you are using Python 2 instead of Python 3. Can you try with Python 3 using a newer version of the AWS CLI? Thanks!
