### ISSUE TITLE
Provide feedback when it is known that a presigned URL will expire before the requested timeout

### ISSUE THREAD

**Issue by TapdancingRodent** [aws/aws-cli#5076]
This is a feature request.

Pre-signed URLs must expire at the earliest of
- the requested timeout (if provided), and
- the lifetime of the (e.g.) session used to generate the URL.

This is fine from a design perspective, but can lead to some unexpected behaviour for a fleshy client. To avoid breaking changes, this could be signalled from the server through a response header.

**Comment by KaibaLopez** [comment]
hmm hard to say how hard this would be, and I have trouble testing some of these session/role dependent stuff, so may I ask for some help?
Usually presigned urls have the expiration in seconds as part of the url, can you check if the one you get is the same as the one you provide or does it change depending on the session's life time?

**Comment by TapdancingRodent** [comment]
Oh, good point. I just generated a new presigned URL using a 1 hour session created from aws-vault, and the Expires param has a UNIX timestamp 1 week from now i.e. the one I provided.
