### ISSUE TITLE
credential_process environment

### ISSUE THREAD

**Issue by karlw00t** [aws/aws-cli#5077]
I'd like to make decisions in my credential_provider based on the region or partition that is being used.  This could be done in a lot of different ways and I wanted to know what the supported method for doing this was. For example, this command:

```
aws sqs list-queue --region us-west-2 --profile my-profile
```
should get creds for the aws partition

```
aws sqs list-queue --region cn-north-1 --profile my-profile
```
While this one will work in aws-cn

the config file would look the same:

```
[profile my-profile]
credential_provider = my-custom-script
```

What would be the supported way to get this data from the running CLI inside the credential_provider process?

**Comment by KaibaLopez** [comment]
Hi @karlw00t ,
Hmm, sorry I'm not sure I understand what you're asking but... would something like this work for you?
```
[profile my-profile-west]
credential_provider = my-custom-script
region = us-west-2
[profile my-profile-cn]
credential_provider = my-custom-script
region = cn-north-1
```
And then do:
```
aws sqs list-queue --profile my-profile-west
--or--
aws sqs list-queue --profile my-profile-cn
```

**Comment by karlw00t** [comment]
Yes, this approach makes more sense. But can my script get the region passed to it without making it explicit? I don't think the above example would work, it would needs to look like this:

```
[profile my-profile-west]
credential_provider = my-custom-script --region us-west-2
region = us-west-2
[profile my-profile-cn]
credential_provider = my-custom-script --region cn-north-1
region = cn-north-1
```
