### ISSUE TITLE
Bug with "aws ec2 delete-security-group"

### ISSUE THREAD

**Issue by Julianxo** [aws/aws-cli#5082]
**My intention**
I just want to delete a security group via aws cli.

**When I run:**
`aws ec2 delete-security-group --region **YOUR_REGION** --group-name **YOUR_GROUP_NAME**`

It fails with this error message:
`An error occurred (VPCIdNotSpecified) when calling the DeleteSecurityGroup operation: No default VPC for this user`

**BUT when I run:**
`aws ec2 delete-security-group --region **YOUR_REGION** --group-id **YOUR_GROUP_ID**` 

It works like expected.

**Conclusion**
I think it should not matter whether I use a group name or a group id to specify the resource to be deleted.

**Further information:**
```
aws --version
aws-cli/1.16.290 Python/3.7.5 Darwin/18.7.0 botocore/1.13.26
```

**Comment by kdaily** [comment]
Hi @Julianxo,

I think you may be running into this, which is noted in the [examples and documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/delete-security-group.html#examples) if you are using an EC2-VPC environment.

>  Note that you can't reference a security group for EC2-VPC by name.

See this documentation page for the differences between EC2-Classic and EC2-VPC environments:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/vpc-migrate.html
