### ISSUE TITLE
SSM slow sessions.

### ISSUE THREAD

**Issue by phenri00** [aws/aws-cli#5083]
time aws --profile xx --region xx ssm start-session --target i-xxx

real	0m43.835s
user	0m1.559s
sys	0m1.427s

aws --version
aws-cli/1.18.0 Python/3.7.6 Darwin/18.7.0 botocore/1.15.0

aws2 --version
aws-cli/2.0.0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev4

python -V
Python 2.7.16

ssh tunnelling just hangs.

OS: macOS Mojave 10.14.6

**Comment by kdaily** [comment]
Hi @phenri00, does this still occur for you? If so, can you please provide output with `--debug` turned on? Thanks!
