### ISSUE TITLE
pip install fails because of ssh in requirements.txt

### ISSUE THREAD

**Issue by serverhorror** [aws/aws-cli#5087]
Hello,

I'm working in a corporate environment and the proxy doesnt' allow to connect via anything than HTTPS or HTTP.

`requirements.txt` defines the dependencies in a way that will involve pulling via SSH

**Comment by KaibaLopez** [comment]
Hi @serverhorror ,
Thanks for the pr!

**Comment by kdaily** [comment]
Bumping this to keep it open, as there is an open PR that needs review.

**Comment by nateprewitt** [comment]
Hi @serverhorror, we had a quick clarifying question that should have been asked here originally. Could you provide a little more info about your use case? Specifically you're trying to develop a new feature/code change with the CLI that's being inhibited?

If you're only trying to install the repo from source to use the CLI, `pip install -e .` will get all required dependencies. The requirements.txt file is intended for extras used in local development.

**Comment by serverhorror** [comment]
Let me start with this: I think you can close this, it has timed out and I honestly can't remember the context. We have worked around it. If memory served me correctly I reported this because it was quite unexpected that SSH connections were required to get the development dependencies installed.

I'll leave the decision whether to close this or not to you. I won't hold any grudges :)

> Specifically you're trying to develop a new feature/code change with the CLI that's being inhibited?

Yes that _was_ the case. 

> If you're only trying to install the repo from source to use the CLI, `pip install -e .` will get all required dependencies. The requirements.txt file is intended for extras used in local development.

Hello,

Yes this is about working _on_ the CLI not _with_ the CLI. So when trying to `pip install -r requirements.txt` this fails. This is due to a **local restriction at the organization** where SSH is not allowed.

The lines highlighted in https://github.com/aws/aws-cli/blob/09a752c5b4d35fbee7247cada9b8d9b9095bc4f7/requirements.txt#L4-L5 refer to an SSH checkout. And that makes it fail.

**Comment by nateprewitt** [comment]
I posted a quick update in the linked PR, but we're expecting this to be addressed in the next release of the CLI. Please let us know if you have any questions in the meantime, otherwise we'll resolve this after tomorrow's release.

**Comment by nateprewitt** [comment]
This change is now available in 1.21.10 and later. Please feel free to open a new issue if you have more feedback or concerns. Thanks!
