### ISSUE TITLE
[V2] AWSCLI v2 is reporting "aws2" in errors/messages to end-users

### ISSUE THREAD

**Issue by allenatdecisiv** [aws/aws-cli#5094]
"aws2" is in error/warning/notice messages to end-users:

```
$ aws --version
$ aws-cli/2.0.5 Python/3.7.7 CYGWIN_NT-10.0-18363/3.1.4-340.x86_64 botocore/2.0.0dev9
```

```
$ aws ssm start-session --target i-123457890abcdefg --profile my-sso-profile
```

returns:
> The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws2 sso login with the corresponding profile.

There is no `aws2` to run `aws2 sso login <..>`

**Comment by KaibaLopez** [comment]
Hi @allenatdecisiv ,
Thanks for bringing this up, it must have escaped us when releasing v2.

**Comment by kdaily** [comment]
Hi @allenatdecisiv,

Looks like this has been addressed:

https://github.com/boto/botocore/blob/v2/botocore/exceptions.py#L613
