### ISSUE TITLE
InvalidCloudWatchLogsLogGroupArnException

### ISSUE THREAD

**Issue by tretos53** [aws/aws-cli#5098]
I followed [this](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/send-cloudtrail-events-to-cloudwatch-logs.html) guide to send the CloudTrail logs to CloudWatch, so I can receive SNS alerts for ConsoleLogin event.

```
aws --version
aws-cli/1.16.131 Python/2.7.16 Darwin/19.3.0 botocore/1.12.121
```

I created a bucket, CloudWatch group log, a role and a policy.

When creating a new trail with below command I receive an error.

```
aws --region <REGION> cloudtrail create-trail \
    --name cloudtrail2cloudwatch \
    --cloud-watch-logs-log-group-arn arn:aws:logs:REGION:ACCOUNT_ID:log-group:cloudtrail2cloudwatch:* \
    --cloud-watch-logs-role-arn arn:aws:iam::ACCOUNT_ID:role/cloudtrail2cloudwatch \
    --s3-bucket-name cloudtrail2cloudwatch
```

ARN is from: `aws --region <REGION> logs describe-log-groups`

`An error occurred (InvalidCloudWatchLogsLogGroupArnException) when calling the CreateTrail operation: Access denied. Check the permissions for your role.
`

It says AccessDenied but according to AWS it means: This exception is thrown when the provided CloudWatch log group is not valid. Source: https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_UpdateTrail.html

**Comment by tretos53** [comment]
Somehow the CloudTrail is sending data to s3 even when I didn't get a `success` message. Something somehow worked.
It would be good to confirm what that error means anyway.

**Comment by kdaily** [comment]
Hi @tretos53, 

I could not reproduce, does this reliably reproduce for you?

I also want to confirm what you are reporting. After running the `create-trail`, you received the `InvalidCloudWatchLogsLogGroupArnException`. However, despite getting the error, it successfully created the cloudtrail.

The second question - why this reports an 'access denied' when it's really something about an invalid log group - that is a confusing error. I can report that to the Cloudwatch API team, but there isn't anything that we can do in the CLI about that.

I could get an `InvalidCloudWatchLogsLogGroupArnException` error, but by passing a malformed ARN, which returns a different error in the response body (and does not successfully create anything):

```
botocore.errorfactory.InvalidCloudWatchLogsLogGroupArnException: An error occurred (InvalidCloudWatchLogsLogGroupArnException) when calling the CreateTrail operation: Check the log group ARN: CloudTrail can't validate it.
```

**Comment by nibatandukar** [comment]
Hi @tretos53 how did you solve this issue. I am getting same issue.
```
Error: Error creating CloudTrail: InvalidCloudWatchLogsLogGroupArnException: Access denied. Check the permissions for your role.
```

**Comment by GhzTNFj2b19HRNAJBDKSGFYqIctv4** [comment]
@nibatandukar I honestly don't remember. I think despite the error the cloudtrail was created.

Is the trail created ? here https://console.aws.amazon.com/cloudtrail/home

Can you try creating using the UI? https://console.aws.amazon.com/cloudtrail/home/create

**Comment by tretos53** [comment]
@nibatandukar I honestly don't remember. I think despite the error the cloudtrail was created.

Is the trail created ? here https://console.aws.amazon.com/cloudtrail/home

Can you try creating using the UI? https://console.aws.amazon.com/cloudtrail/home/create
