### ISSUE TITLE
Use latest Python 3 runtime for the official Docker images

### ISSUE THREAD

**Issue by toricls** [aws/aws-cli#5100]
Thank you for the newly released official Docker images!

Regarding of the Python runtime version in the Docker images, it uses Python 2 as per followed output, but this blocks to run some in-house plugins for AWS CLI which requires Python 3.6 or above.

```shell
$ docker run -it --rm --entrypoint=bash amazon/aws-cli:latest
bash-4.2# python --version
Python 2.7.16
bash-4.2# python3 --version
bash: python3: command not found
```

I know I can create my own image based on the officials, but it could be very helpful if the images just use some latest Python 3 runtimes.

**Comment by KaibaLopez** [comment]
Hi @toricls ,
Just as a heads up, I'll be marking this as a feature request, but I'm pretty sure that the images are meant to be more for inside use and not something we particularly maintain or support, so the issue _may_ be closed...
I may also be wrong though, and it doesn't sound like the hardest of changes, which brings me to, would you be interested in making a PR for that?

**Comment by KaibaLopez** [comment]
Okay, my bad, we do support those, so this stays a feature request. 
Still would appreciate PR's on it.

**Comment by toricls** [comment]
@KaibaLopez Thanks for the quick response! I'd love to create a PR.

So in my understanding, [this Dockerfile](https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile) is to create the official container images on Docker Hub, and my idea here is as follows:

1. Use other base images instead of amazonlinux:2
2. Install Python 3 in the second stage in the Dockerfile

Any thoughts?

**Comment by kyleknap** [comment]
Chiming in as well. So the fact that Python2 is installed on the image is only by coincidence as it look like the Amazon Linux 2 base image comes with Python2 installed. The executable that we build into the image is not actually relying on the system python, but using a Python3 interpreter that is frozen in the executable.

That being said, I want to avoid pulling in a general purpose Python runtime into the Docker image. However if the interpreter can only be used for plugins, I can see a case being made, even though plugins in v2 are considered provisional: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-profile-plugins. I think I'd prefer to wait to make a decision once we have a stable plugin interface, but would like to hear any thoughts people have.

In terms of the in-house plugins, how are you pulling them into the container? I would have expected that you would have built your own image on top of the AWS CLI to house the plugins anyway. Or is it rather having the exact Python runtime needed for the plugins just makes your image easier to manage?

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't received any activity in a while. @toricls did you see the questions in the comment above? Regarding Amazon Linux 2 I saw this in their [documentation](https://aws.amazon.com/amazon-linux-2/faqs/):

> There are no plans to change the default Python interpreter. It is our intention to retain Python 2.7 as the default for the lifetime of Amazon Linux 2. We will backport security fixes to our Python 2.7 packages as needed.

**Comment by mstred** [comment]
Maybe changing the base image version to use `amazonlinux/amazonlinux:2022` instead of `amazonlinux/amazonlinux:2` would be a safe way to fix this. What do you guys think of that?

**Comment by ipleten** [comment]
So no plans to publish official docker image with python3?
