### ISSUE TITLE
SQL Server Transaction Log backup sync Issue with S3

### ISSUE THREAD

**Issue by shreikurao** [aws/aws-cli#5103]
I'm uploading SQL Server transaction log files to S3 using "aws s3 sync" command. Once in a while the file uploaded to S3 is malformed or incorrect. (not always)
To confirm this further, I compared the checksum of that file on S3 with the original file and they're indeed different. I'm suspecting that S3 sync coincided with SQL Server restore of the file. The file however was uploaded and sizes were same. Any more sync that we ran didn't fix the malformed file. 
I need help to resolve this issue.

**Comment by kdaily** [comment]
Hi @shreikurao,

Can you provide the output of your command where it fails with the `--debug` flag turned on? The output may be long, so you may need to attach the log. However you're right, if `aws s3 sync` and some other SQL Server operation were working on the same file, you might experience difficulties.
