### ISSUE TITLE
Default link to download 64-bit installer of AWSCLIV2 for Windows 10 points to 1.8.31 installer

### ISSUE THREAD

**Issue by pradeepvenkataraman** [aws/aws-cli#5110]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Default link to download 64-bit installer of AWSCLIV2 for Windows 10 points to 1.8.31 installer. Post installation when I check the version it shows "aws-cli/1.18.31 Python/3.8.2 Windows/10 botocore/1.15.31". There is no way to get the installer that shows "aws-cli/2.0.6 Python/3.7.4 Windows/10 botocore/2.0.0" as mentioned in the documentation **(https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html)**

**Platform/OS/Hardware/Device**
Windows 10 64-bit (Microsoft Windows [Version 10.0.17763.1098])

**To Reproduce (observed behavior)**
1. Download & install the AWSCLIV2 provided in the https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html

**Expected behavior**
The link should provide AWS CLI v2.0.x installer

**Comment by pradeepvenkataraman** [comment]
Please note that I do not have any other version of AWS CLI.

**Comment by KaibaLopez** [comment]
Hi @pradeepvenkataraman ,
that is odd, for me the link points me to CLIV2.msi and installs v2.

I see this link: https://awscli.amazonaws.com/AWSCLIV2.msi , does that install v1? Or is your link different?

**Comment by pradeepvenkataraman** [comment]
It was a mistake on my end. I had installed aws-cli using pip install (don't remember when). Since Python was ahead of AWSCLI in the PATH, the 1.8 version in python used to get picked ahead of 2.0 version. I have removed library from Python and moved AWSCLIV2 to first entry in PATH so that I'll not face this problem again.
