### ISSUE TITLE
Include filter not working as expected

### ISSUE THREAD

**Issue by cesarvarela** [aws/aws-cli#5112]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

 I'm guessing it's because the same string is twice in the path? I'm not sure though:

The log output shows:

`/web/public/page-data/index/page-data.json did not match include filter: /page-data/*`

**SDK version number**
`aws-cli/2.0.1 Python/3.7.4 Darwin/19.3.0 botocore/2.0.0dev5`

**Platform/OS/Hardware/Device**
Catalina

**To Reproduce (observed behavior)**
`aws s3 sync ./public s3://bucket --exclude "*" --include "/page-data/*"`

**Expected behavior**
Should sync everything inside 

**Logs/output**
```
2020-04-06 19:16:45,102 - MainThread - awscli.customizations.s3.filters - DEBUG - /web/public/page-data/index/page-data.json did not match include filter: /page-data/*
```

**Comment by KaibaLopez** [comment]
Hi @cesarvarela ,
So the debugger says it can't find the folder so I think this is a syntax problem
Can you try this?
* first verify that page-data folder is in the  ./public folder
* then try running:
     `aws s3 sync ./public s3://bucket --exclude "*" --include "*page-data/*"`
