### ISSUE TITLE
"aws-cli" snap package mismatch version

### ISSUE THREAD

**Issue by dsegurag** [aws/aws-cli#5115]
Hello there,

Seems that for any reason, the ["aws-cli" snap package](https://snapcraft.io/aws-cli) at this moment is the version `1.15.58` for `amd64` architecture, but not for `arm64` architecture  that is the version `1.18.35`.

![2020-04-07 11_34_42-](https://user-images.githubusercontent.com/21098646/78653831-fdc93800-78c3-11ea-9c5d-6f0b8747714d.png)
![2020-04-07 11_34_24-](https://user-images.githubusercontent.com/21098646/78653834-fe61ce80-78c3-11ea-9418-f4106d7f8d12.png)

Can you please review it?

Much appreciated.

**Comment by KaibaLopez** [comment]
Hi @dsegurag ,
sorry but we don't really support snap packages.
I'd recommend contacting snapcraft for this.
sorry again I can't be of much help here.

**Comment by kdaily** [comment]
Looking into this. Thanks for reporting!
