### ISSUE TITLE
pkg_resources.ResolutionError: Script 'scripts/aws' not found in metadata at '/home/user/.local/lib/python2.7/site-packages/awscli-1.18.39.dist-info'

### ISSUE THREAD

**Issue by vellangelus00** [aws/aws-cli#5121]
Hi I followed all the steps to install aws-cli but when I try to run it I get this message:

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 4, in <module>
    __import__('pkg_resources').run_script('awscli==1.18.39', 'aws')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/aws' not found in metadata at '/home/user/.local/lib/python2.7/site-packages/awscli-1.18.39.dist-info'

**Comment by OML72** [comment]
Hi,

I have a similar issue but cannot find the way to fix it:

pkg_resources.ResolutionError: Script 'scripts/pyFoamPlotRunner.py' not found in metadata at '/home/oml_400/.local/lib/python3.8/site-packages/PyFoam-2020.5.dist-info'

would you have any idea how to solve this ?

thank you
