### ISSUE TITLE
describe-snapshots change default behavior

### ISSUE THREAD

**Issue by P3GLEG** [aws/aws-cli#5128]
Hey there,

I was hoping to have an open discussion about changing the command `aws ec2 describe-snapshots` to show snapshots owned by self first. I.E `aws ec2 describe-snapshots --owner-ids self`

I messed up believing all these snapshots belonged to our environment only to find out down the line that was a lie and due to me not rtfm beforehand. 

On the AWS console for snapshots by default it only shows ones owned by self first.

**Comment by KaibaLopez** [comment]
Hi @P3GLEG ,
I think this makes sense as a feature request, but just to be clear on what this is, you'd want to have aws ec2 describe-snapshots --owner-ids as default behavior, and not having to use the filter option?

**Comment by P3GLEG** [comment]
I'd like the default behavior to only show snapshots that belong to **self** with no need for the filter.
