### ISSUE TITLE
Last point in time backup query using cli

### ISSUE THREAD

**Issue by leealexander** [aws/aws-cli#5137]
Is it possible to get the last point in time backup date/time of an rds sql server instance using the cli?  If so what would be the command... 

Regards 
Lee

**Comment by KaibaLopez** [comment]
hi @leealexander ,
I believe that information is part of the output for:
`aws rds describe-db-instance-automated-backups`

You can find more info [here](https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-instance-automated-backups.html)

**Comment by leealexander** [comment]
Thank you
