### ISSUE TITLE
aws-cli snap package broken for the latest release 1.18.43

### ISSUE THREAD

**Issue by anzap** [aws/aws-cli#5142]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
We are using aws-cli in travis builds using travis snapcraft support. Today our build started failing with the error after getting the latest released version 1.18.43:
```
/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory
```

**SDK version number**
1.18.43

**Platform/OS/Hardware/Device**
ubuntu through travis build.
```
$ sudo snap install aws-cli --classic --channel=latest/edge
aws-cli (edge) 1.18.43 from Amazon Web Services (aws*) installed

$ sudo snap list
Name     Version    Rev   Tracking       Publisher   Notes
aws-cli  1.18.43    161   latest/edge    aws*        classic
```

**To Reproduce (observed behavior)**
```
+aws ecr describe-images --region eu-central-1 --repository XXX --image-ids imageTag=XXX
/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory
```

**Comment by Kyocfe** [comment]
i have the same issue on the travis

**Comment by scnerd** [comment]
Confirming this on a bare metal ubuntu 18.04:

```
$ aws ecr get-login-password
/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory
```

The latest/stable branch is several years out of date and doesn't support this and, likely, many other modern commands. There don't seem to be any other versions available on snap, but I'd guess a workaround for now would be to install the CLI via pip instead of snap.

**Comment by ambigus9** [comment]
Same issue on Ubuntu 20.04

`/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory`

Any solution?

**Comment by marcindulak** [comment]
Do we know who is maintaining aws-cli snap? https://github.com/awsdocs/aws-cli-user-guide/issues/17

**Comment by marcindulak** [comment]
This is what the snap prints, but is this true @bisdavid  @flexiondotorg (looking at the post about aws-cli on https://forum.snapcraft.io/t/snapcraft-summit-montreal-2019-day-1-2-3/11763)?

```
snap info aws-cli | grep contact
contact:   https://console.aws.amazon.com/support
```

**Comment by jehos** [comment]
same++

```
/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory
2 jehos@GogunBuntu:/snap/aws-cli/current/bin$ tree /snap/aws-cli/161/bin/aws
/snap/aws-cli/161/bin/aws [error opening dir]

0 directories, 0 files
jehos@GogunBuntu:/snap/aws-cli/current/bin$ tree /snap/aws-cli/current/bin
/snap/aws-cli/current/bin

0 directories, 0 files
jehos@GogunBuntu:/snap/aws-cli/current/bin$ 
```

**Comment by unglaublicherdude** [comment]
Same issue here.

```
~$ aws-cli.aws 
/snap/aws-cli/161/usr/bin/python3: can't open file '/snap/aws-cli/161/bin/aws': [Errno 2] No such file or directory

~$ ls -lha /snap/aws-cli/161/bin/aws
ls: cannot access '/snap/aws-cli/161/bin/aws': No such file or directory

```

**Comment by joeky888** [comment]
In case someone is looking for a quick workaround.

```sh
sudo snap remove aws-cli

sudo snap install devoperator --classic
devoperator aliases | sudo bash -x
```

This will install the following packages

```
Ansible
AVH git flow
AWS CLI
aws-iam-authenticator
eksctl
istioctl
kubectl
Terraform
yq
```

**Comment by kdaily** [comment]
@marcindulak is correct, we do not support the Snap package, so you would need to contact SnapCraft for support on this. Thanks!

**Comment by sturfee-petrl** [comment]
Is there any progress?
 I remember I was on this issue page on May when I installed ubuntu 20.04
 Now I installed Ubuntu Budgie 20.04 and the issue is still here. 
 I see that snapcraft added to the repository "Verified account" Amazon Web Services. 
 Anyway I think it also true that snapcraft is going to be most comfortable way to install new applications on Ubuntu. So it would be weird if Canonical wouldn't support own Ubuntu images on dockerhub. 
 So I hope it will be supported any time soon
 Thank you!
 
 @kdaily

**Comment by sturfee-petrl** [comment]
Is there any progress? 
> Now I installed Ubuntu Budgie 20.04 and the issue is still here.
> I see that snapcraft added to the repository "Verified account" Amazon Web Services.
> Anyway I think it also true that snapcraft is going to be most comfortable way to install new applications on Ubuntu. So it would be weird if Canonical wouldn't support own Ubuntu images on dockerhub.
> So I hope it will be supported any time soon
> Thank you!
> 

So yes. I just created new machine to do experiment with some logic and I needed `aws-cli` . 
I went to the search bar and typed `ubuntu snap aws-cli` and I am again here

**Comment by sturfee-petrl** [comment]
Why does it tell that it **official Amazon Web Services account**? And **it's broken for more then a year**. 
![d](https://user-images.githubusercontent.com/28763635/116941206-1bcaae80-ac24-11eb-8b5f-81fe70615ceb.png)

**Comment by lazzarello** [comment]
> @marcindulak is correct, we do not support the Snap package, so you would need to contact SnapCraft for support on this. Thanks!

Can you clear up who is indicated in this "we do not support the Snap package"? The package has been published by a green checkmark publisher named "aws". If Amazon isn't supporting the snap, how did it get published?

```
name:      aws-cli
summary:   Universal Command Line Interface for Amazon Web Services
publisher: Amazon Web Services (aws✓)
store-url: https://snapcraft.io/aws-cli
contact:   https://console.aws.amazon.com/support
license:   Apache-2.0
description: |
  The AWS CLI is an open source tool built on top of the AWS SDK for Python (Boto) that provides
  commands for interacting with AWS services. With minimal configuration, you can start using all of
  the functionality provided by the AWS Management Console from your favorite terminal program.
snap-id: CRrJViJiSuDcCkU31G0xpNRVNaj4P960
channels:
  latest/stable:    1.15.58 2020-04-03 (130) 15MB classic
  latest/candidate: ↑                             
  latest/beta:      ↑                             
  latest/edge:      1.18.43 2020-04-22 (161) 10MB classic
```

**Comment by kdaily** [comment]
@anzap @sturfee-petrl, I apologize for the confusion. I was not aware at the time that the snap was authored by a separate AWS team than the AWS CLI team. I'm looking into what support can be provided.

While I realize that there is a verified account on Snapcraft for AWS publishing this package, at the current time the only officially supported installation mechanisms for the AWS CLI are detailed here:

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html

**Comment by 030** [comment]
Will you accept a PR?

**Comment by kdaily** [comment]
Hi @030,

This would not be a pull request for this repository, it would be to manage what is pushed to Snapcraft. With the recent source distribution proposal (#6352), we're looking into what it will take for the current owner to get the existing Snap up to date.

**Comment by nysasounds** [comment]
For what it's worth, I ended up creating an alternative snap of aws-cli.
There are a few subtle differences, and It's v2 only, but it's working fine for me, and is delivering the latest version.

Feel free to give it a try.

https://snapcraft.io/amz-aws-cli

**Comment by marrek-az** [comment]
I know this is an old issue, but if possible please check the current version in --channel v1/beta to see how it works for you. Thanks.

This is a **beta** version.
