### ISSUE TITLE
pager invoked even when there is no output

### ISSUE THREAD

**Issue by stickystyle** [aws/aws-cli#5144]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
PR https://github.com/aws/aws-cli/pull/4702 introduced a default pager for output, however this pager gets invoked even when there is no output, such as writing to a file. This results in the pager getting opened with empty content.

**SDK version number**
aws-cli/2.0.8 Python/3.8.2 Darwin/18.7.0 botocore/2.0.0dev12

**Platform/OS/Hardware/Device**
OS X 10.14.6

**To Reproduce (observed behavior)**
Run a command that supports writing to a file.
`$ aws appsync get-introspection-schema --api-id $API_ID --include-directives --format SDL .api.graphql`

**Expected behavior**
The pager should not start

**Additional context**
The pager can of course be disabled with `AWS_PAGER=""`, but it doesn't make sense to even call the pager when there is nothing to display.

**Comment by KaibaLopez** [comment]
Hi @stickystyle ,
Thanks for pointing this out!

**Comment by kdaily** [comment]
Hi @stickystyle,

I think this has been fixed. It can be an issue on Mac where the default `LESS` environment variable is not set correctly too. The documentation has been updated to describe this and how to remedy it, under the section "How to use pager flags":

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside

**Comment by kdaily** [comment]
@stickystyle, this should go out as part of a release next week with #6117.

**Comment by kdaily** [comment]
This is now available, closing!
