### ISSUE TITLE
AWS S3 File merge using CLI

### ISSUE THREAD

**Issue by mesekhar** [aws/aws-cli#5147]
Confirm by changing [ ] to [x] below:
- [X ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ X] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Linux
**Describe the question**
I am trying to combine/merge contents from all the files existing in a S3 bucket folder into a new file. The combine/merge should be done by the ascending order of the Last modified of the S3 file.

I am able to do that manually by having hard coded file names like as follows:
(aws s3 cp s3://bucket1/file1 - && aws s3 cp s3://bucket1/file2 - && aws s3 cp s3://bucket1/file3 - ) | aws s3 cp - s3://bucket1/new-file

But, now I want to change the CLI command so that we can do this file merge based on list of as many files as they exist in a folder, sorted by Last Modified. So ideally, the cp command should receive the list of all files that exist in a S3 bucket folder, sorted by Last Modified and then merge them into a new file. 

I appreciate everyone's help on this.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by KaibaLopez** [comment]
Hey @mesekhar ,
So s3 as a service does not provide a concatenation function, so it's not something we'd implement in the CLI sdk...
That being said, since you're already having the downloading to local step, you could do something like:
```
aws s3 cp s3://bucket1/ . --recursive
cat $(ls -t -r) > extraFilex
aws s3 cp newfile s3://bucket1/new-file
```
