### ISSUE TITLE
AWS S3 CLI creating multiple directories when using mv command

### ISSUE THREAD

**Issue by leoankita** [aws/aws-cli#5154]
I am trying to move s3 bucket files from one folder to an archive folder in the same s3 bucket and I am using mv command to do this. While moving I want to exclude the movement of files in the archive folder.
I am using the following command

`aws s3 mv s3://mybucket/incoming/ s3://mybucket/incoming/archive/ --recursive --exclude incoming/archive/" --include "*.csv"`

but this command is moving the files but also creating multiple hierarchical archive folder when running multiple times

so,

1. 1st run - files moved from /mybucket/incoming/ to /mybucket/incoming/archive/
2. 2nd run - new files moved from /mybucket/incoming/ to /mybucket/incoming/archive/archive/
3. 3rd run - new files moved from /mybucket/incoming/ to /mybucket/incoming/archive/archive/archive/
4. 4th run - new files moved from /mybucket/incoming/ to /mybucket/incoming/archive/archive/archive/archive/

and so on........
can someone suggest/advise what exactly I am doing wrong here?

**Comment by timoschilling** [comment]
Have you tried `aws s3 mv s3://mybucket/incoming/ s3://mybucket/incoming/archive/ --recursive --exclude incoming/archive/* --include "*.csv"`

**Comment by KaibaLopez** [comment]
Hi,
@timoschilling  you're right, the exclude syntax requires you to add the tailing * to signify "everything inside" rather than just the folder itself, thanks for pointing it out!
@leoankita let me know if you have any further questions.
