### ISSUE TITLE
Amazon AppFlow - New Service

### ISSUE THREAD

**Issue by gpongracz** [aws/aws-cli#5156]
Problem: Unable to access Amazon AppFlow (New Service) API via command line

Description:  I would like to automate the creation and management of Amazon AppFlow Pipelines, additionally, I request the capability to wildcard the selection of objects in the source service eg: salesforce objects as well as alter filters per run eg: set last modified date for CDC to S3

Alternatives: https://github.com/simple-salesforce/simple-salesforce library in conjunction with Apache Airflow

**Comment by aws-saleforce-democode** [comment]
Thanks for your comment. We will release our public APIs for creating flows very soon and you would be able to access it via the command line interface. Thanks for your patience.

**Comment by gpongracz** [comment]
Hello again
Is there any update on when this capability might become available?

**Comment by sgulbetekin** [comment]
Please have a look at here: https://docs.aws.amazon.com/cli/latest/reference/appflow/index.html (cli) and https://docs.aws.amazon.com/appflow/1.0/APIReference/Welcome.html (API)

**Comment by gpongracz** [comment]
thank you

**Comment by kdaily** [comment]
Closing, since this is now available. Thanks @sgulbetekin!
