### ISSUE TITLE
SSM PutParameter allow tags when overwriting

### ISSUE THREAD

**Issue by JaydenMaalouf** [aws/aws-cli#5162]
**Is your feature request related to a problem? Please describe.**
Currently the PutParameter doesn't allow tags to be passed in when performing a --overwrite. This causes issues with tagging enforcement policies (even in the AWS Console - you literally can't update a tag there)

**Describe the solution you'd like**
Either an explicit UpdateParameter or the ability to not require the existing tags to be specified when --overwrite is passed.

**Describe alternatives you've considered**
Unless I delete the parameter and recreate it, there is no way to get around the tagging policy.

**Additional context**
Our tagging policy looks like this:
```
{
    "Sid": "DenyManagementServices",
    "Effect": "Deny",
    "Action": [
        "ssm:PutParameter"
    ],
    "Resource": [
        "arn:aws:ssm:*:*:parameter/*"
    ],
    "Condition": {
        "Null": {
            "aws:RequestTag/Owner:Technical": [
                "true"
            ]
        }
    }
}
```

**Comment by kdaily** [comment]
Hi @JaydenMaalouf,

Thanks for your request. The [documentation](https://docs.aws.amazon.com/cli/latest/reference/ssm/put-parameter.html) has this note in it:

> To add tags to an existing Systems Manager parameter, use the AddTagsToResource action.

I think this is one of your desired solutions: "an explicit UpdateParameter".
