### ISSUE TITLE
Allow to pass exact file paths

### ISSUE THREAD

**Issue by bes1002t** [aws/aws-cli#5167]
I want to sync just a few hundred specific files from my bucket to my local machine. The bucket contains about 500 000 files.

Issue1: The sync process needs a lot of time, because aws cli checks each file, in bucket and local, for changes
Solution1: Using 'aws s3api list-objects' and jmespath to query all files which have changed since the last 14 days. 

Issue2: 'aws s3api list-objects' returns a list of file paths. How could I sync each file path?
Solution2: Add each file path as '--include=<FILE_PATH>' to the 'aws s3 sync' command

Issue3: With a few hundred '--include' arguments the sync command takes a lot of time, because for each include, sync is iterating over all files checking whether one file matches the --include pattern.
Solution3: ???

There are two feature requests I want to address here. Fortunately for one of them there is already a ticket for a few days: https://github.com/aws/aws-cli/issues/5160

The other feature request would be a command line argument for 'aws s3 sync' that allows just passing paths instead of patterns. It's needed to iterate over all files if you pass a pattern, but if you are sure that you just pass paths, it's not. This would create a huge speed up for sync processes of large buckets with many files, if you just want to sync a few files.

A alternative would be calling the cp command for each file path, appending the file path to the bucket url. But there are two issues using this way:
1. It is slow as hell, because the whole sync command is executed x times, which includes the connection creation to aws servers.
2. cp does not check whether the file has to be downloaded because it was changed, it just downloads the file, which makes the script also slower

**Comment by bes1002t** [comment]
Maybe one solution would be providing --include and --includePath. This could speed up the whole execution time.

Tried the cp solution, after 6 hours I stopped the script. A simple sync overall files just needs about 40 minutes.

**Comment by dcshapiro** [comment]
same issue here

**Comment by kdaily** [comment]
Thanks @bes1002t, marking as a feature request.

**Comment by bes1002t** [comment]
@kdaily  thanks for adding the feature request label.

Looking forward and hope it will be implemented in the future. I think this could speed up aws cli a lot if large buckets are used.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity in a while. @bes1002t I'll share these articles related to improving s3 sync/cp performance which may be helpful:

- https://aws.amazon.com/premiumsupport/knowledge-center/s3-improve-transfer-sync-command/
- https://aws.amazon.com/premiumsupport/knowledge-center/s3-optimize-transfer/
- https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-sync-instance-bucket/

I'm also not sure if I fully understand what you're asking for in this request. It seems to overlap with that other issue you linked (https://github.com/aws/aws-cli/issues/5160). You can already apply `--include` and `--exclude` filters to file paths and prefix patterns. Please let us know if there are any distinctions you'd like to clarify or expand on.
