### ISSUE TITLE
IAM policy action classification

### ISSUE THREAD

**Issue by reach4bawer** [aws/aws-cli#5168]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

The issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Mac/Windows using Python/CLI

**Describe the question**
Trying to get the information about each IAM actions and which bucket does it fall under -

- **List**: List resources in the service
- **Read**: Read resource content in the service
- **Write**: Create, delete, or modify resources in the service
- **Permissions management**: Grant or modify resource permissions in the service
- **Full access**: Encompasses all the above actions.

This information is available on the GUI (see the screenshots from IAM section). Is there something that I can use in the CLI to get the same information about a particular action for a particular service. For example if I am trying to find out which bucket out of the above does DescribeAddresses for ec2 service fall under or on a broader level if there is like another way to query this information.

![image](https://user-images.githubusercontent.com/52763317/80780048-893c8e80-8b3b-11ea-9500-3f211a9e1388.png)
![image](https://user-images.githubusercontent.com/52763317/80780238-40d1a080-8b3c-11ea-8664-cc181dc98f3d.png)

**Comment by KaibaLopez** [comment]
Hi @reach4bawer ,
Sorry but we don't provide a list or groupings like that on the CLI.
I'll take a closer look see if there is anything similar but I really don't think we do.

**Comment by reach4bawer** [comment]
Thank you for the confirmation @KaibaLopez. If there is another API or location in which this is available please let me know.

**Comment by KaibaLopez** [comment]
Hi @reach4bawer ,
bad news, we at least on the CLI don't have a way to query it. 
Sorry I couldn't be of much help
