### ISSUE TITLE
introduce friction into delete operations

### ISSUE THREAD

**Issue by amit-handda** [aws/aws-cli#5174]
**Is your feature request related to a problem? Please describe.**
I accidentally executed aws cli command to delete an object in production. this is actually very easy to do. looking to introduce abit friction into these (delete) operations

**Describe the solution you'd like**

for starters, would be nice if aws cli could double confirm (deleting ... [y/N]) before executing a delete api.

**Describe alternatives you've considered**
Ideally, it would be nice if we could specify the same in the IAM policy. for all `delete` operations, double confirm from the user. or any other better solution would be nice.

**Additional context**
I checked aws cli doc, github issues, but I could not find anything related.

**Comment by KaibaLopez** [comment]
Hi @amit-handda ,
Just to be clear here, you are referring to S3 objects correct?

**Comment by amit-handda** [comment]
oh, sorry for misunderstanding. I meant all delete operations to any aws object. not just s3.

**Comment by KaibaLopez** [comment]
I'd say this is a reasonable request, but it may also require some discussion, for example, many use the cli operations as part of scripts, so having interactive checks might be problematic. 
I think it's worth considering though.

**Comment by amit-handda** [comment]
thank you. appreciate the prompt response. I think it would make cli a lot more useful. how best it could be done ? you are the best judge.
