### ISSUE TITLE
`aws iot-data publish` doesn't send the correct JSON message

### ISSUE THREAD

**Issue by rynkowsg** [aws/aws-cli#5175]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to pass any json text to `aws iot-data publish`. But it doesn't works it used to work.
Looks like some issue with processing the JSON text.

**SDK version number**
Just CLI:
```
% aws --version
aws-cli/2.0.6 Python/3.8.2 Darwin/19.4.0 botocore/2.0.0dev10
```

**Platform/OS/Hardware/Device**
mac mini
macOS 10.15.4 (19E287)
Both iTerm and system Terminal
brew python
```
% python --version
Python 2.7.16

% python3 --version
Python 3.8.2
```

**To Reproduce (observed behaviour)**
1. From CLI send any JSON to a topic:
```
aws iot-data publish --topic "dev/private/in/200849" --payload "{}"
```
2. Next you could see the additional app that I need to quit by pressing 'q':
![Screenshot 2020-05-04 at 21 42 14](https://user-images.githubusercontent.com/5878299/81006546-0293f400-8e50-11ea-994e-7486ea48c0a3.png)

3. Depends on what was the content of the json string I see something like this when I observe the topic:
![Screenshot 2020-05-04 at 21 46 29](https://user-images.githubusercontent.com/5878299/81006935-9cf43780-8e50-11ea-94c9-d1e1d567dc93.png)

**Expected behavior**
1. the app should not show me the terminal app to quit
2. I should receive a correct message when I observe the topic

**Logs/output**
[log.txt](https://github.com/aws/aws-cli/files/4577063/log.txt)

**Additional context**
It worked before. I had scripts that I was using on Oct. It worked fine. Recently I tried to use it again, and it failing. Looks like some problem with the encoding of the text.

**Comment by KaibaLopez** [comment]
Hi @rynkowsg ,
Thanks for pointing this out, a couple things are going on here:
You may want to read through our [CLI V2 breaking changes](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam) documentation page. You'll find the root of both your problems here.
That being said though, you are still correct that this isn't behaving as I'd expect it to if I'm making the call like you are, and neither the documentation or the error message is very clear on what is the expected call...
To explain what I mean:
`aws iot-data publish --topic "Test_Topic_mine" --payload fileb://test.json`
This works well, but if you do :
`aws iot-data publish --topic "Test_Topic_mine" --payload "{}"`
it publishes as a message but encoded, so that's definitely is not good.
I think you're right to assume it should default to unencoded binary or at least have an option to set it... The least we can do is have an example of the expected input.

**Comment by rynkowsg** [comment]
Thanks @KaibaLopez 

That works, I haven't thought it could be a break of backward compatibility. I tend to think that it is rarely the case.

I tested passing `file://`, `fileb://` and plain text with `--cli-binary-format raw-in-base64-out`, but still, no matter how I pass the payload, I see an additional [window](https://user-images.githubusercontent.com/5878299/81006546-0293f400-8e50-11ea-994e-7486ea48c0a3.png) that I need to quit using 'q'. Any reason why it is there?

**Comment by KaibaLopez** [comment]
Yea, that is also part of the breaking changes, look [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager).

**Comment by rynkowsg** [comment]
Ok, so this is the second rediculus change you've done.

What was was your intention? Both "piping the output to less" and "reading
payload from file and/or base64" (and by that introducing breaking
change) could
be done with piping, less, stream redirection, base64, xargs.

Your should focus on doing SIMPLE, general purpose tools, and what you've
done instead? You had a simple API and you have made it specific, adjusted
for some party, specific user case overlapping features of general purpose
tools.

You had a good and simple API. What was the reasoning behind introducing
those changes?

**Comment by KaibaLopez** [comment]
Hi @rynkowsg,
I mean, thanks for the input but the explanations for the decisions taken on these features are in the same [document](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html).

Keep in mind too that these are only changes to "default" behavior, and reverting back to previous behavior is easily configurable, and the document provides instructions on how to do that too. 

That being said, I kind of see your point too and it is debatable what should be the default and what be hidden under configurable options, but the wording you use makes it sound like we lost features when that is not the case.

**Comment by TheRealTechStacker** [comment]
dont use double quotes around the payload, instead use single

aws --region eu-central-1 iot-data publish --topic "myTopic" --cli-binary-format raw-in-base64-out --payload '{\"uptime\": 123,\"temp\": 44,\"humidity\": 33}'

**Comment by akramIOT** [comment]
> dont use double quotes around the payload, instead use single
> 
> aws --region eu-central-1 iot-data publish --topic "myTopic" --cli-binary-format raw-in-base64-out --payload '{"uptime": 123,"temp": 44,"humidity": 33}'

Yes, i resolved it  earlier  on my own  by removing the  double quotes. Thanks for your response

**Comment by sborsay** [comment]
Glad it was helpful, You can automate things with the IoT data producers
here

https://github.com/sborsay/AWS-IoT/tree/master/IoT_Sample_Data_Publishers
