### ISSUE TITLE
"Network interfaces and an instance-level subnet ID may not be specified on the same request"

### ISSUE THREAD

**Issue by danackerson** [aws/aws-cli#518]
the new --associate-public-ip-address introduced in #479 doesn't seem to work for VPC instances

the error is noted in the title above

**Comment by kbroughton** [comment]
same
(dev)] aws --version
aws-cli/1.7.0 Python/2.7.6 Darwin/14.3.0

aws ec2 run-instances --key-name csbeanstalk --security-groups *****-v1 --instance-type m3.medium --associate-public-ip-address --image-id ami-d05e75b8 --placement Tenancy=dedicated --subnet-id subnet-**********a

A client error (InvalidParameterCombination) occurred when calling the RunInstances operation: Network interfaces and an instance-level security groups may not be specified on the same request
