### ISSUE TITLE
different behavor between codecommit-create-commit--put-files and put-file about "--file-content" args

### ISSUE THREAD

**Issue by gyokutoku** [aws/aws-cli#5180]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
-->Amazon Linux 2 AMI

**Describe the question**
when using "put-file" command, I can use file:// suffix to uploading a local file,
but when creating the first commit using "create-commit", the "fileContent" parameter explain "file://xxx" to a plain string. 
That means we can't upload a local file when first commit? 
But local file uploading can be done via the console page.
So is it possible to support "file://" in "create-commit" command?

`aws codecommit put-file --repository-name repo-sample --branch-name master --parent-commit-id=$commitid --file-content file://./.gitignore  --file-path /.gitignore --commit-message "init"
`
-->upload local ".gitignore" file to the repository
`aws codecommit create-commit --repository-name repo-sample --branch-name master --put-files "filePath=.gitignore,fileContent=file://./.gitignore" `
-->the file contents is exactly "file://./.gitignore“

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @gyokutoku,

In the `put-file` operation, `--file-content` is a separate parameter, so it can be used with a file object. The `create-commit` has the `fileContent` as part of a structure. You could use shell expansion to get the appropriate text there:

```
aws codecommit create-commit --repository-name repo-sample --branch-name master --put-files "filePath=.gitignore,fileContent=$(cat .gitignore)" 
```

You can also provide the `sourceFile` property instead of the `fileContent`, as noted in the documentation:

>The name and full path of the file that contains the changes you want to make as part of the commit, if you are not providing the file content directly.

**Comment by gyokutoku** [comment]
Hi @kdaily ,
Thank you for the reply.
As what I tried, the "fileContent" args meant to the git path.(maybe misstated).
So, we need to create the first commit to get the commit for the other operation, and cannot get the parent commits, isn't it?
Or could you suggest the commands to create the very first commit?
About the following shell expansion, all things come the single line, and the "\n" seems not working.
`aws codecommit create-commit --repository-name repo-sample --branc
aws codecommit create-commit --repository-name repo-sample --branch-name master --put-files "filePath=.gitignore,fileContent=$(cat .gitignore)" 
-name master --put-files "filePath=.gitignore,fileContent=$(cat .gitignore)" 
`

**Comment by kdaily** [comment]
Hi @gyokutoku,

I apologize for the delay in response.

According to the docs, here's how you create the first commit:

https://docs.aws.amazon.com/codecommit/latest/userguide/how-to-create-commit.html#how-to-create-first-commit

You're correct, the `cat` operation does not always preserve newlines. If you need to construct the `put-files` parameter then you're better off at programatically generating that text separately.

**Comment by gyokutoku** [comment]
Hi @kdaily ,
I'm sorry, it's my mistake. 
I didn't read the `[--parent-commit-id]` option of `put-file` command carefully, and thought it's a required parameter.
The `put-file` command can resolve the problem of creating the first commit, and I got the difference of their "file contents" options.
Thank you for your replies!
