### ISSUE TITLE
module 'dateutil.tz' has no attribute 'UTC

### ISSUE THREAD

**Issue by csamarajeewa** [aws/aws-cli#5183]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

a recent update to the cli has broke some s3  calls for us. We are now getting "module 'dateutil.tz' has no attribute 'UTC" for ls, and cp.

**SDK version number**
aws-cli/1.18.53 Python/3.6.9 Linux/4.15.0-1051-aws botocore/1.16.3

**Platform/OS/Hardware/Device**
What are you running the cli on?

Ubuntu 18

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

s3 cp s3://object .
s3 ls s3://object/object/ojbject/

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @csamarajeewa ,
I am not able to reproduce this error... for me these calls are working as expected, is there anything you'd think would be a problem other than the version of the sdk?

**Comment by csamarajeewa** [comment]
Hello Gilberto,

You can close the ticket. I didn't find out the exact cause but I installed
a specific version of awscli to work around the issue.

Thanks
