### ISSUE TITLE
--debug output is written to stderr instead of stdout

### ISSUE THREAD

**Issue by artus** [aws/aws-cli#5187]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution. **I did find one releated issue but this did not answer my question: https://github.com/aws/aws-cli/issues/642**

Issue is about usage on:
- [x ] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
Windows 10 - (Git) Bash

**Describe the question**
When I add the '--debug' flag to the AWS CLI, all debug logging is written to `stderror` instead of `stdout`. This means that when I run my AWS CLI commands as part of my deployment pipeline, all --debug output gets logged as errormessages.

**Comment by artus** [comment]
Redirecting the `stderr` to `stdout` is a possible solution, but this will of course also redirect _real_ errors.

**Comment by kdaily** [comment]
Hi @artus, thanks for your comment. I'm not seeing how what you're requesting is different than the proposals in #642. If you could provide an argument for a file where logs are supposed to go (e.g., `aws service op --debug /tmp/foo.debug`), would that not allow you to separate errors from logs?

**Comment by john-aws** [comment]
Why are debug logs written to stderr at all? Why would anyone want them intermingled with actual errors? This seems to be an unusual choice. Also, https://github.com/aws/aws-cli/issues/642 was closed with no action, so this issue (by which I mean https://github.com/aws/aws-cli/issues/5187) should be reopened.
