### ISSUE TITLE
CLI configure does not run instead it gives me that message.

### ISSUE THREAD

**Issue by riadcsa** [aws/aws-cli#5190]
1. 

Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

**Describe the question**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by KaibaLopez** [comment]
Hello @riadcsa ,
This seems to be an incomplete issue, can you tell me the version you're using and the message you're getting?

**Comment by riadcsa** [comment]
Hello Gilberto,

thanks very much for helping me with this issue. I am still stuck with it.

it is the latest version of  AWSCLI; version 2 i believe .
I was just done with installing awscli and then wanted to call on my s3 bucket using the CLI and i got that message in the image.  I was told to delete that configure file and not sure it is a proper thing to do since it belong to my anaconda python set up.  I truly appreciate your reply. Please let me know if anything i can try to resolve the issue.

**Comment by riadcsa** [comment]
This is also something i got when I ran this command   aws —version 

*******************************************************************************************
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/DarkChild/anaconda3/bin/aws", line 27, in <module>
    sys.exit(main())
********************************************************************************************

**Comment by KaibaLopez** [comment]
Hi @riadcsa ,
when you say  "i got that message in the image", I don't see an image, could you copy and paste the command and error you used?
From the second message though it looks like the cli was not properly installed on your environment, did you have a previous version installed? could you try a reinstalling the newest version?

**Comment by riadcsa** [comment]
Ok, I think you are correct when you say there is something wrong with the installation process.  I also think that there might be a conflict with other application in that case it is the anaconda package that include python program. I believe i will uninstall it and reinstall, but please take a-look at those images and let me know what you think ?

**Comment by KaibaLopez** [comment]
Hi @riadcsa ,
Sorry for the delayed response but, I still never got any images, I don't think any got uploaded.
Did reinstalling work for you?

**Comment by riadcsa** [comment]
Thanks very much for getting back to me. Thankfully, I was able to get it work after a while new installation.
