### ISSUE TITLE
--output yaml 

### ISSUE THREAD

**Issue by manasa32** [aws/aws-cli#5194]
aws ec2 describe-regions --output yaml --query "Regions[*].RegionName"
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --output: Invalid choice, valid choices are:

json                                     | text
table

**Comment by KaibaLopez** [comment]
Hi @manasa32 ,
Can you tell me what version of the CLI you're running? 
On version :
```
aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/17.7.0 botocore/2.0.0dev4
```
I don't get the issue, I'm running : 
```
aws ec2 describe-regions --all-regions --output yaml --query "Regions[].{Name:RegionName}"
- Name: af-south-1
...
- Name: us-west-1
- Name: us-west-2
```

**Comment by manasa32** [comment]
$ aws --version
aws-cli/1.18.39 Python/3.6.0 Windows/10 botocore/1.15.39

**Comment by manasa32** [comment]
i still get the same error

**Comment by manasa32** [comment]
when i upgraded version of awscli ,the command works

$ aws --version
aws-cli/2.0.13 Python/3.7.7 Windows/10 botocore/2.0.0dev17


i have another issue related to following:
commands executed after ssh into ec2 ubuntu instance
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt install php libapache2-mod-php php-mysql -y
sudo systemctl restart apache2
sudo systemctl enable apache2
sudo apt install php-cli -y
sudo vi /var/www/html/info.php => 
<?php
phpinfo();
?>
sudo systemctl restart apache2

when tried to browse 54.191.41.200/info.php

it doesnt work

**Comment by manasa32** [comment]
This site can’t be reached54.191.41.200 took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by manasa32** [comment]
54.191.41.200 : public ip address

**Comment by manasa32** [comment]
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt install php libapache2-mod-php php-mysql -y
sudo systemctl restart apache2
sudo systemctl enable apache2
sudo apt install php-cli -y
sudo vi /var/www/html/info.php => 
<?php
phpinfo();
?>
sudo systemctl restart apache2

**Comment by manasa32** [comment]
sudo vi /var/www/html/info.php =>

<?php
phpinfo();
?>

**Comment by manasa32** [comment]
sudo vi /var/www/html/info.php => 
  <?php
   phpinfo();
    ?>

**Comment by manasa32** [comment]
info.php


<?php
phpinfo();
?>

**Comment by KaibaLopez** [comment]
hi @manasa32 , this error seems unrelated to the aws cli, so not sure I can help you there.
Also, try to get it all under one comment, it is very hard to read what is going on with so many comments.

**Comment by manasa32** [comment]
i have another issue related to following:
commands executed after ssh into ec2 ubuntu instance
sudo apt-get update
sudo apt-get install apache2 -y
sudo apt install php libapache2-mod-php php-mysql -y
sudo systemctl restart apache2
sudo systemctl enable apache2
sudo apt install php-cli -y
sudo vi /var/www/html/info.php =>

sudo systemctl restart apache2

find public ip and navigate to “`http://publicip/info.php“ 

The above step doesnt work .Please assist.

**Comment by KaibaLopez** [comment]
Hi @manasa32 ,
This is again, not related to the cli so I will be closing the issue.
