### ISSUE TITLE
aws acm list-certificates how to list additional domain names asociated 

### ISSUE THREAD

**Issue by ivelikov67** [aws/aws-cli#5201]
Is there a way to list all domain names asociated with a aws certifficate ?

**Comment by KaibaLopez** [comment]
Hi @ivelikov67 ,
No, the only way to filter the list-certificates are on key usage/type and certificate status. This is more of a limitation on the service rather than the cli implementation too which makes it harder to take even as a feature request.

**Comment by ivelikov67** [comment]
Strange... How AWS web based console lists them than ?
It should use same services as CLI...

**Comment by KaibaLopez** [comment]
Right, sorry I did not mean that it's impossible to do, the console probably filters on top of the service's answer...
But since the CLI tries to replicate the service's behaviour we probably wouldn't take it as a feature request unless we see a lot of interest on it.
