### ISSUE TITLE
website-redirect-location should support HttpRedirectCode

### ISSUE THREAD

**Issue by Stefanqn** [aws/aws-cli#5209]
**Is your feature request related to a problem? Please describe.**
CloudFront caches 301 redirects. Using a redirect to point to the latest version of e.g. API documentation doesn't work. 

**Describe the solution you'd like**
add `HttpRedirectCode` to `aws s3api put-object` or at least enable users to control the caching behavior with e.g. `--expires 0 --cache-control max-age=0,no-cache,no-store,must-revalidate`.

**Describe alternatives you've considered**
Setting `cache-control` and `expires`

**Comment by kdaily** [comment]
Hi @Stefanqn,

Have you reviewed this documentation regarding redirects with S3 objects? 

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

This StackOverflow post might be helpful as well:

https://stackoverflow.com/questions/22740084/amazon-s3-redirect-and-cloudfront
