### ISSUE TITLE
Unable to login to ECR using VPC Endpoint

### ISSUE THREAD

**Issue by subaduba** [aws/aws-cli#5212]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

Amazon Linux 2

**Describe the question**
I am trying to use ECR with a VPC Endpoint. I have created endpoints to the following endpoints, both with Private DNS enabled:

com.amazonaws.us-east-1.ecr.api
com.amazonaws.us-east-1.ecr.dkr

I am running the latest AWS CLI (1.18.61) on Python 2.7.16

I am able to run basic **aws ecr XX** commands successfully, but for some reason, I am unable to login to ECR using **docker login**

I can run this successfully:

`aws ecr --region us-east-1 get-login-password`

But if I run this:

`docker login -u AWS -p $(aws ecr --region us-east-1 get-login-password) <vpc_endpoint_url>`

I get the following:

`Error response from daemon: login attempt to https://<endpoint_id>.dkr.ecr.us-east-1.vpce.amazonaws.com/v2/ failed with status: 400 Bad Request`

A couple of notes:

1. I am running this from a private subnet with proxied access to the internet. My http_proxy and https_proxy env variables are set appropriately

2. I tried modifying my no_proxy env variable to include the VPC endpoint URL, but that didn't work either

3. The IAM role assigned to the EC2 instance running the command has ecr:* permissions.

4. I can login and push to the registry from another machine that has internet access using the default endpoint. It appears to be just the VPC endpoint that doesn't work.

Any suggestions on what I might be doing wrong?

**Comment by subaduba** [comment]
Please disregard this! This was an issue with my Docker proxy configuration. I am up & running.

**Comment by yegorski** [comment]
I'm having the exact same issue. Do you remember what was the misconfiguration? AFAIK I have no config beyond what AWS provides, and running docker login fails.

**Comment by s405121** [comment]
Facing the same issue myself. Any info on how this been resolved, would be of great help!! @subaduba 

Thanks,

Vishnu

**Comment by subaduba** [comment]
@s405121 @yegorski - sorry, just seeing this now. Let me see if I can find anything in my notes on this issue and I will update this. Thanks!

**Comment by s405121** [comment]
thank you very much sir!! @subaduba

**Comment by malcolm061990** [comment]
> @s405121 @yegorski - sorry, just seeing this now. Let me see if I can find anything in my notes on this issue and I will update this. Thanks!

Hi. I got the same issue :(
Did you find something?

**Comment by sarath-sankar** [comment]
How to log in to ECR using VPC Endpoint
Please suggest a way to do this 
I'm getting the same issue 

> Error response from daemon: login attempt to https://<endpoint_id>.dkr.ecr.us-east-1.vpce.amazonaws.com/v2/ failed with status: 400 Bad Request

Thanks in advance,

@subaduba @yegorski @malcolm061990 @s405121

**Comment by yegorski** [comment]
Using the VPC endpoint URL just straight-up doesn't work. 

Someone correct me if I'm wrong but I think the purpose of a VPC endpoint is so that internal-to-the-network systems don't have to go out to the public internet (and incur NAT costs) and instead can pull from ECR in the VPC.

But even with VPC endpoint for ECR in place, internal systems still need to use the public URL. I imagine some AWS magic translates the public ECR URL to the internal URL. I imagine it works in the same way as an S3 VPC endpoint: systems still access S3 buckets on the same public URL but without routing to the public internet.

Again, someone correct if I'm off base here.

**Comment by morariu** [comment]
Any news on this? Is there a solution to push to ECR from on-prem via Direct Connect? I know that S3 access is possible via the VPC endpoint.

**Comment by mblacklidge** [comment]
We had this issue with our team city agent and we've managed to find a workaround. 
The docker login command HAS to use the public url for some reason, and our security prevents us from reaching the public IP address of ECR
We updated our hosts file on the team city agent to point the public url of ECR to the VPCE ip address. This seems to have done the trick.
