### ISSUE TITLE
AWS CLI no longer finds shared credentials since 2.0.9

### ISSUE THREAD

**Issue by alanbccoe** [aws/aws-cli#5217]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I have several profiles set up in ~/.aws/config and have credentials in ~/.aws/credentials including some under a `[default]` heading. With version 2.0.6 if I run `aws configure list` it correctly displays my profile:
```
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************AEAU shared-credentials-file    
secret_key     ****************o31b shared-credentials-file    
    region                <not set>             None    None
```

But with 2.0.9 and later it fails to find them, and I get this:
```
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None
```

**SDK version number**
> 2.0.6

**Platform/OS/Hardware/Device**
What are you running the cli on? RHEL UBI8 docker image

**To Reproduce (observed behavior)**
Put credentials under `[default]` in `~/.aws/credentials` and create some profiles in `~/.aws/config`. 

**Expected behavior**
It continues to find shared credentials

**Logs/output**
2.0.6 (working):
```
...
2020-05-20 10:16:01,337 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-05-20 10:16:01,341 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
...
```

2.0.9 (broken):
```
...
2020-05-20 10:22:55,964 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
...
```

**Additional context**
Even if I manually add the credentials to the `[default]` section of `~/.aws/config` it still fails to find the credentials, so the shared config file might be a red herring.

**Comment by KaibaLopez** [comment]
Hi @alanbccoe ,
that is very odd and I'm not really able to reproduce on my side, and before I try to go into version differences, there's a few things I'd like you to check for me:
* Make sure that the files are in the correct path and that the profile name is correct.
* check the environment variables `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` are pointing to the correct path.

If it's neither of those, could you try changing the environment variables to any easily accessible path ( `~/mycreds/config` & `~/mycreds/credentials` for example). and let me know if that also fails.
Lastly does this happen on the newest CLI version as well or is there a reason why you can't upgrade?
