### ISSUE TITLE
Pass environment credential variables to docker image instead of credentials file

### ISSUE THREAD

**Issue by cojack** [aws/aws-cli#5218]
**Is your feature request related to a problem? Please describe.**
Problem exists in CI, whenever I want to use aws-cli official image I have to build a credentials file and mount it to the container.

**Describe the solution you'd like**
I would like to be able to pass these credentials by `-e` argument, fe:

`docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID ... -v $(pwd):/aws amazon/aws-cli s3 ...`

instead of creating credential file 

**Describe alternatives you've considered**
So there is no additional alternatives.

**Additional context**
This will reduce amount of work, that need to be done, it will reduce it to the 1 line instead of build credentials file every time.

Thanks in advance.

**Comment by KaibaLopez** [comment]
Hi @cojack ,
I'm a bit confused here, so maybe I'm missing something but the command you proposed works as is. What is the feature you are asking for ?
For now I'll label this as documentation because we are missing that, but please let me know if I misunderstood something.

**Comment by cojack** [comment]
So @KaibaLopez take a look:

```docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY amazon/aws-cli s3 ls                                                      1 ↵
Unable to locate credentials. You can configure credentials by running "aws configure".
```

looks like it doesn't work for passing just environment variables, so how it's working on your site?

**Comment by nfickas** [comment]
Any update on this? I am also seeing issues where the environment variables don't seem to be being used.

**Comment by cojack** [comment]
@KaibaLopez any feedback?

**Comment by pankaj-dahiya** [comment]
@KaibaLopez many users who want to specify credentials as environment variables are still waiting for any update. We never knew if this is a feature request or documentation!!

**Comment by stobrien89** [comment]
Hi @cojack, @nfickas and @pankaj-dahiya, 

I am so sorry for the delay! After trying a few different combinations, here's what I found:

Either 

`docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY amazon/aws-cli s3 ls`

Or 

`docker run --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY amazon/aws-cli s3 ls`

seem to work for me.  However, if you're using temporary security credentials, you will need to define/pass a AWS_SESSION_TOKEN variable as well. We have a few [examples](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html#cliv2-docker-share-files-config) of passing environment variables (sans temporary security credentials) in the user guide.  

Can't apologize enough for the delay— hate to see that this one slipped through the cracks.  Definitely feel free to let me know if you happen to have any additional questions.

**Comment by cojack** [comment]
@stobrien89 maybe after a year they fix it, who knows.

**Comment by stobrien89** [comment]
@cojack, 

It's quite possible— there have been a lot of changes to the CLI docker image between now and then.  I'm going to close this for now, but please don't hesitate to let me know if you have any additional questions.
