### ISSUE TITLE
aws s3 cp does not produce CompleteMultipartUpload event

### ISSUE THREAD

**Issue by CBielstein** [aws/aws-cli#5219]
### Expected behavior

`aws s3 cp <file> <s3 bucket>` with a file larger than 5 GB should use multipart upload and trigger a CompleteMultipartUpload event

### Actual behavior

`aws s3 cp <file> <s3 bucket> with a file larger than 5 GB uses multipart upload but does NOT trigger a CompleteMultipartUpload event

### Repro Steps

1. Create S3 bucket
1. Create CloudTrail to watch read and write events on that bucket
1. Create a CloudWatch rule to save all S3 events on that bucket to a new CloudWatch log group
1. `aws s3 cp <file> s3://<bucket_name>` where file is larger than 5 GB
1. Wait for file to upload
1. Look at logs and see that CompleteMultipartUpload event is not present

#### Command

`aws s3 cp \\path\to\large_file.zip s3://bucketname`

#### Versions

Tested on both of the following versions:

* aws-cli/2.0.13 Python/3.7.7 Windows/10 botocore/2.0.0dev17
* aws-cli/1.16.256 Python/3.6.0 Windows/10 botocore/1.12.246

#### Debug Output

Here's the last ~3200 lines of the --debug output. I didn't realize it wouldn't write to file. I'm happy to rerun and upload if we need the beginning: [large_file_debug.txt](https://github.com/aws/aws-cli/files/4659855/large_file_debug.txt)

## Discussion

Our current workflow is to use an S3 upload to trigger our ETL pipeline (a Step Function) but that workflow has broken down now that the file sizes have grown above 5 GB.

I have the following setup in my AWS account:

* S3 bucket
* CloudTrail
* CloudWatch rule to log all S3 object events in my bucket // for debugging this problem
* CloudWatch rule to trigger a Step Function on CopyObject, PutObject, CompleteMultipartUpload // for my actual service, not necessary for the reproduction

When uploading a file larger than 5 GB by my S3 bucket via `aws s3 cp`, the CloudWatch logs to not reflect the reception of a CompleteMultipartUpload event and the Step Function is not triggered.

The following methods however *do* produce a CompleteMultipartUpload event in the logs and trigger the Step Function

* Manually sending a CompleteMultipartUpload event with `aws s3api complete-multipart-upload` (even just after the `aws s3 cp` command with a bogus upload ID)
* Uploading the file through the AWS console web UI in the S3 bucket
* Oddly, renaming an existing file in using the AWS console web UI

Thanks in advance for your help and please let me know what I can do to try and debug this further!

**Comment by CBielstein** [comment]
Also meant to write in there that I love the project and use it every day at work. Thanks for the work you've been doing! :)

**Comment by KaibaLopez** [comment]
Hi @CBielstein ,
I think I'm missing something from the explanation, I've tested this on big files and I can't reproduce, also looking at the debug log you provided it is also doing multiplart upload:
`2020-05-20 15:30:46,717 - ThreadPoolExecutor-0_9 - s3transfer.tasks - DEBUG - CompleteMultipartUploadTask(transfer_id=xx, {'bucket': 'bucket-name', 'key': 'large_file.zip', 'extra_args': {}}) about to wait for the following futures`.

So either I'm missing something here or the problem is happening on your cloudwatch rule that is not getting it?

p.s. thanks for the comment!

**Comment by CBielstein** [comment]
Thanks for the quick investigation and response!

Right. To be clear, the problem isn't that it is not doing multipart upload. It is definitely doing that. The problem is that it is not generating the CompleteMultipartUpload. I did see the CompleteMultipartUploadTask lines in the debug output (and in some of the source code I was reading through) and was somewhat surprised to see that.

I also suspected my CloudWatch rule at first and would have bet that it was my mistake before it was yall's. However, the fact that CloudWatch detects, logs, and acts upon the CompleteMultipartUpload after using the web UI tells me that my CloudWatch rule is successfully picking up those events when they happen. So far, `aws s3 cp` is the only scenario I've tried where I am not catching a CompleteMultipartUpload event in CloudWatch. That's the only reason I stopped suspecting it was my own user error in CloudWatch. :)

**Comment by nickdk** [comment]
Any update on this? Running into the same issue, I've got a Cloudwatch rule that doesn't seem to get triggered for larger files where multipart upload is used. Both from the Python SDK and reproducable with the cli (aws s3 cp).

This is my Cloudwatch event rule:

```
{
  "detail-type": [
    "AWS API Call via CloudTrail"
  ],
  "source": [
    "aws.s3"
  ],
  "detail": {
    "eventSource": [
      "s3.amazonaws.com"
    ],
    "requestParameters": {
      "bucketName": [
        "my-bucket-name"
      ],
      "x-amz-server-side-encryption": [
        "aws:kms"
      ]
    },
    "eventName": [
      "PutObject",
      "CompleteMultipartUpload"
    ],
    "additionalEventData": {
      "bytesTransferredIn": [
        {
          "anything-but": 0
        }
      ]
    }
  }
}
```

**Comment by stobrien89** [comment]
Hi @CBielstein,

My apologies for the delay. I know it's been a while since you initially reported this.  I attempted to reproduce this with CLI version `2.2.5` using a 6GB file and was unable to do so— the CompleteMultipartUpload event was triggered: 

```
Making request for OperationModel(name=CompleteMultipartUpload) with params: {'url_path': '/obrinstestbucket/6gbfile.txt', 'query_string': {'uploadId': 'dVsvdAHAvrkHd8qz_dGWV8DaE2aqwam96AUbCySKfzIOIuVEikyN476tlSCj0DDV3FDdk4Mq47.SYT.1DtQQfohLKRgJgF8gCtZw5tIMTW7F0l0l6oiOblnJ7pbZHnUxevUfNewbtzxssS1jxDtBdw--'}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.2.5 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off command/s3.cp'}, 'body': b'<CompleteMultipartUpload
```

Would you be able to test this using a recent version to confirm it's still an issue? Thanks!

**Comment by bhooteshwarrahul** [comment]
> Thanks for the quick investigation and response!
> 
> Right. To be clear, the problem isn't that it is not doing multipart upload. It is definitely doing that. The problem is that it is not generating the CompleteMultipartUpload. I did see the CompleteMultipartUploadTask lines in the debug output (and in some of the source code I was reading through) and was somewhat surprised to see that.
> 
> I also suspected my CloudWatch rule at first and would have bet that it was my mistake before it was yall's. However, the fact that CloudWatch detects, logs, and acts upon the CompleteMultipartUpload after using the web UI tells me that my CloudWatch rule is successfully picking up those events when they happen. So far, `aws s3 cp` is the only scenario I've tried where I am not catching a CompleteMultipartUpload event in CloudWatch. That's the only reason I stopped suspecting it was my own user error in CloudWatch. :)

@stobrien89 this issue is closed automatically! Facing similar issues with our integrations as well. The setup is same as yours.
Did you get a solution around this ?

**Comment by stobrien89** [comment]
Hi @bhooteshwarrahul,

My apologies for the delayed response.  Would you be able to confirm your AWS CLI version and the size of the file(s) this is occurring with?  Thanks!

**Comment by cooper667** [comment]
I've just been tracking down something similar and don't think it's entirely a CLI issue.

The final request to CompleteMultipartUpload contains a list of every part that has been uploaded. For a large file, this can be quite large and _potentially too large for Cloudwatch events_. 

In my testing with the SDK, using larger chunks (and therefore reducing the size of the final event) worked. The event triggered by an S3 renaming seems to contain relatively few chunks, so I would guess that these actions use larger chunks than the SDK/CLI default (5mb?).

The Cloudwatch Events size limit is 256kb, which must also apply to "internal" events, and they fail silently?

**Comment by bhagathbathula** [comment]
Hello @stobrien89 

Need your help.

I'm facing similar kind of issue, let me explain it clearly in next lines.

We have a eventbridge rule with event pattern putobject and completemultipartupload events, when a file lands to a specific  S3 bucket prefix it should trigger the target step function but it doesn't in our case.

We are able to see completemultipartupload event is appearing in the cloudtrail logs, wondering thing is when a file lands in other folder of given path for monitoring in stepfunction it is getting trigger the step function.

The file size is actually 12GB and 13GB files and above - for these file sizes eventbridge is unable to trigger stepfunciton though event are appear in cloud trail log.

can you please check if you find anything to be checked here.

**Comment by Sumanthadinbal** [comment]
Hello @stobrien89 

We are also seeing the same issue when the file size is greater than 10GB. 

AWS Cli version: 2.15.29

Please suggest the remediation for this issue.
