### ISSUE TITLE
aws.exe not signed

### ISSUE THREAD

**Issue by ropman76** [aws/aws-cli#5221]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When I download  AWS CLI MSI installer from https://awscli.amazonaws.com/AWSCLIV2.msi as found on https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html and install it on my Window10 64 bit system, the executable aws.exe is not signed.   The msi file is.  The exe is not.  This is causing issues with the anti-virus software not  allowing accessing to the exe and regarding it as unsafe.

**SDK version number**
{6CD2EA2B-FA0C-4E97-BF19-30446274D3CF} --version number on the msi file

**Platform/OS/Hardware/Device**
Windows 10 64bit

**To Reproduce (observed behavior)**
Download from https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html
install file.  The exe is not signed

**Expected behavior**
The exe is signed.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @ropman76 ,
So this sounds like a reasonable feature request but I'm not convinced it's a necessary one or a particularly useful one...I'd recommend manually whitelisting the .exe on your antivirus.
Windows really just requires digital signatures on drivers so having it on the installer already complies with that.

All that being said, if there is community interest on this (upvotes and/or comments help here) we'll probably revisit the idea.

**Comment by ropman76** [comment]
I do feel this is a useful request for environments that use strong application whitelisting approaches.  My system administrator was able to manually whitelist the application.  However since he had to use the hash of the exe to issue the exception the next time there is an upgrade and the hash of the exe changes, I will have to make another request.  Long term this is not a great solution and counterproductive to keeping up with the latest releases of this tool.     If the exe is signed I can request an exception for Amazon's cert and can upgrade the tool at any point without having to worry about triggering an alert.

**Comment by GregLevenhagen** [comment]
This would be great for enterprise developers. Getting exceptions for each update, per person, is painful. Enterprises don't usually let end-users create exceptions in anti-virus software themselves.

**Comment by joshsleeper** [comment]
worth noting that I don't _think_ this is windows-specific, although lemme know if I'm off-track here.

I've spent a non-trivial amount of time on-and-off for the last couple weeks chasing down why my `aws-cli v2` executions were getting `SIGKILL`ed kinda randomly.

the final conclusion we came to was that it was getting killed by Palo Alto Traps/Cortex XDR, our security agent, which is reporting the following issues:

```
Sample hides the process name | High

Sample is likely using custom packer | Medium
Malicious ELF files will use customer packers to avoid detection.
```

the general advice I was given from my IT dept was that if those issues can't be resolved, the proper solution would be for `aws-cli` executables to be properly signed that way scanners recognize them as trustworthy even if they do things that might look risky to the scanner.

**Comment by kdaily** [comment]
Hi all, as part of #5974 and #6005, AWS CLI v2 executables are now signed, which should resolve this feature request.

> The latest tagged release `2.1.33` automatically published an MSI that was signed with an EV certificate along with its `aws.exe` and `aws_completer.exe` executables. Going forward, there should not be any expected delay between the publication of new tagged releases and their respective MSIs.  Furthermore, new MSIs and their respective executables will continue to be signed with an EV certificate. Closing this issue.
> 
> _Originally posted by @kyleknap in https://github.com/aws/aws-cli/issues/6005#issuecomment-811298404_

@joshsleeper - are you suggesting that having Windows executables signed will help in the *nix case too? If it's something else, you can open up a new issue to discuss, but hopefully Palo Alto Networks will not be flagging this anymore either.

**Comment by kdaily** [comment]
@joshsleeper - Palo Alto Networks is not currently flagging the AWS CLI v2 based on results from VirusTotal, so this may take care of your issues as well.

**Comment by joshsleeper** [comment]
@kdaily thanks for the follow up, it's much appreciated!

what I was saying was that the linux binaries might also benefit from being properly signed.

Palo Alto Traps/Cortex XDR (Traps from hereon for brevity) uses behavioral analysis for detection, and those two items in my code block were the behaviors it detected as "bad", triggering the block. 

it's possible that their systems will learn that aws v2 on linux is a-ok, but my IT guy had told me that having the AWS linux binaries properly signed would also convince Traps that the behavior was alright.

for now I'll go ahead and play the wait-and-see game with the next release, but my guess is Traps will detect and block it just like the previous releases. if that happens again, I'll go ahead and file a new issue though~
