### ISSUE TITLE
Support cloudformation artifact upload for cloudwatch synthetics canaries

### ISSUE THREAD

**Issue by Janpot** [aws/aws-cli#5230]
**Is your feature request related to a problem? Please describe.**

Creating [cloudwatch canaries](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html) with cloudformation requires uploading the [test code](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-code.html) prior to deploying.

**Describe the solution you'd like**

a similar solution [as exists](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/package.html) for lambda functions. Where the `package` command will upload local artifacts and update the template

**Describe alternatives you've considered**

Currently have to add extra ceremony to package, upload and generate a template

**Comment by georgealton** [comment]
Just took a quick look, and this could've been similar to Lambda Function resource, but the path to the Handler is defined in the Canary.Code object. 

When packaging a Lambda function you set Code to the local path, which you can't do in a Canary because you'd lose the Handler reference.

**Comment by kdaily** [comment]
Hi @Janpot, @georgealton - I will notify the code owner for the CloudFormation package and deploy about this request and the associated PR. Thanks!

**Comment by jk2l** [comment]
@kdaily hi any update regarding this new feature?

**Comment by aBurmeseDev** [comment]
Thank you for the PR submission. Upon team discussion, we decided that internal discussions are needed with other SDK teams to keep consistency between SDKs. With that said, we might consider implementing this in the cross-SDK approach in the future and close this for now.
