### ISSUE TITLE
[v2] aws configure corrupts configuration if value contains square brackets

### ISSUE THREAD

**Issue by vngx** [aws/aws-cli#5239]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
If the `aws configure set` command is used to set any values which contain a pair of square brackets ('[', ']'), the configuration may become corrupted and break the AWS CLI. The issue appears to be caused by the [`ConfigFileWriter::_update_section_contents`](https://github.com/aws/aws-cli/blob/4ff0cbacbac69a21d4dd701921fe0759cf7852ed/awscli/customizations/configure/writer.py#L115) method which uses a regular expression to identify the end of the current section by searching if a line contains square brackets; it will incorrectly identify a property value containing brackets as the start of a new section and attempt to insert a duplicate property key.

The scenario was uncovered when attempting to store the session expiration timestamp in ISO 8601 format with a named zone ID (see [Java DateTimeFormatter#ISO_DATE_TIME](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_DATE_TIME)) which formats date strings as `2020-05-28T08:00:13.431-04:00[America/New_York]`. The first `set` command works correctly by inserting a new key/value pair; a subsequent `set` command to update the value will insert a duplicate key instead of updating the existing value. The duplicate keys corrupts the configuration and all future AWS CLI commands will fail until the configuration is fixed.

**SDK version number**
```
$> aws --version
aws-cli/2.0.10 Python/3.7.5 Windows/10 botocore/2.0.0dev14
```

**Platform/OS/Hardware/Device**
Windows/OSX

**To Reproduce (observed behavior)**
First `set` a key/value pair which contains square brackets:
```
$> aws configure set session_expiration 2020-05-28T08:00:13.431-04:00[America/New_York]
```
Then `set` the same key again to attempt an update:
```
$> aws configure set session_expiration 2020-05-28T09:00:13.431-04:00[America/New_York]
```
The `~/.aws/config` is corrupted due to duplicate values; running any additional `aws` commands will fail as follows:
```
$> aws --version
Traceback (most recent call last):
  File "lib\site-packages\botocore\configloader.py", line 149, in raw_config_parse
  File "configparser.py", line 696, in read
  File "configparser.py", line 1091, in _read
configparser.DuplicateOptionError: While reading from 'C:\\redacted/.aws/config' [line  4]: option 'session_expiration' in section 'default' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "lib\site-packages\awscli\clidriver.py", line 90, in main
  File "lib\site-packages\awscli\clidriver.py", line 99, in create_clidriver
  File "lib\site-packages\botocore\session.py", line 350, in full_config
  File "lib\site-packages\botocore\configloader.py", line 106, in load_config
  File "lib\site-packages\botocore\configloader.py", line 152, in raw_config_parse
botocore.exceptions.ConfigParseError: Unable to parse config file: C:\redacted/.aws/config
[11360] Failed to execute script aws
```

**Expected behavior**
A subsequent `set` command for an existing property key should update the existing property value containing square brackets instead of inserting a duplicate key. Alternatively, if property values containing square brackets are not supported, then the `set` command could return an error when attempting to specify a property value with square brackets to avoid corrupting the configuration.

**Comment by KaibaLopez** [comment]
Hi @vngx ,
Thanks for pointing this out for us!
 we'll take a closer look into it.

**Comment by vngx** [comment]
@vz10 Thanks for applying the fix. I confirmed the `aws configure set` command is working as expected for the use case of values containing square brackets.
