### ISSUE TITLE
YAML format mismatch between aws-cli and CloudFormation service

### ISSUE THREAD

**Issue by iamed2** [aws/aws-cli#5245]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

A comment in a previous issue mentioned this but the issue itself was unrelated.

**Describe the bug**
`aws cloudformation package` generates YAML 1.2, but the CloudFormation service expects YAML 1.1. This results in `aws cloudformation package` changing the string `"yes"` to the bare word `yes`, which is then interpreted by the CloudFormation service as `true`.

**SDK version number**
`aws-cli 2.0.17`

**Platform/OS/Hardware/Device**
macOS 10.14.6

**To Reproduce (observed behavior)**
Attached is a simple template [`yes-repro.yaml`](https://github.com/aws/aws-cli/files/4704307/yes-repro.yaml.txt) that will produce the problematic output when run through `aws cloudformation package`. Deploying the packaged template will result in the custom resource failing, and deploying the template without packaging will successfully create the stack.

**Expected behavior**
I expect a `"yes"` to stay quoted in the output of `aws cloudformation package`. 

**Logs/output**
I've attached [template output](https://github.com/aws/aws-cli/files/4704312/yes-repro-packaged.yaml.txt) from `aws cloudformation package`.

**Additional context**
This was not an issue with awscli v1 because it generated YAML 1.1 and maintained the quoting of `"yes"`.

**Comment by kdaily** [comment]
Hi @iamed2, 

This should be fixed now by #5257, available in [version 2.0.19](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#2019).

**Comment by iamed2** [comment]
Thanks!
