### ISSUE TITLE
[v2] aws configure add-model doesn't work with file url 

### ISSUE THREAD

**Issue by shwetasahuit** [aws/aws-cli#5246]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Below command doesn't work, gives "Expecting value: line 1 column 1 (char 0)" error.
```
aws configure add-model \
    --service-name appmesh-preview \
    --service-model https://raw.githubusercontent.com/aws/aws-app-mesh-roadmap/master/appmesh-preview/service-model.json
```
However if a local file is passed in service-model, then it works.
The command works with aws cli v1.

**SDK version number**
2.0.10

**Platform/OS/Hardware/Device**
What are you running the cli on? MacOS

**Comment by KaibaLopez** [comment]
Hi @shwetasahuit ,
hmm, before I try and go deeper into this, can you try adding this line to your profile in the .aws/config file? 
`cli_binary_format=raw-in-base64-out`

**Comment by shwetasahuit** [comment]
done that, still the same error message.

**Comment by kdaily** [comment]
Hi @shwetasahuit,

I think you're running into this:

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-paramfile

> The AWS CLI version 2 no longer performs a GET operation when a parameter value begins with http:// or https://, and then using the returned content as the value of the parameter. If you need to retrieve a URL and pass the contents read from that URL as the value of a parameter, we recommend that you use curl or a similar tool to download the contents of the URL to a local file. Then use the file:// syntax to read the contents of that file and use it as the parameter's value.

**Comment by shwetasahuit** [comment]
Hi @kdaily, 
Yes this answers my issue, thanks for pointing this out.
