### ISSUE TITLE
AWSCL installer should add the path to the environement variable

### ISSUE THREAD

**Issue by WiliTest** [aws/aws-cli#5249]
On  Windows 10 AWSCL does not add the path to the environment variable. 
So we need to add it manually.

Then we need to reboot the computer to apply the change (it's the easiest way to refresh the path)

**Comment by KaibaLopez** [comment]
Hi @WiliTest ,
the [MSI installer](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html) should by default add itself to the PATH.
How are you installing the cli, did you change the location or took any special steps other than just running the msi?

**Comment by WiliTest** [comment]
Sorry for the delay.
 I just ran the windows installer   (on Windows 10, last version). I used the default installation settings. No special steps. My friend did the same, she also had to add the path manually.

**Comment by KaibaLopez** [comment]
hi @WiliTest ,
I'm still not able to reproduce this, I did see that it is in the installation instructions as something that _**may**_ happen, and what to do if it does, basically [add it manually.](https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#awscli-install-windows-path)
So, I don't think there is much else to do here... sorry, I couldn't be of much more help.
