### ISSUE TITLE
Cannot replace EC2 IAM profile while instance is stopped

### ISSUE THREAD

**Issue by llamafilm** [aws/aws-cli#5251]
While an instance is running, I can use `replace-iam-instance-profile-association` to change the role.  When the instance is stopped, this command fails, and I instead have to run two commands.  First `disassociate-iam-instance-profile`, then `associate-iam-instance-profile`.  Is this intentional?  It would be convenient if the replace command works at all times.
aws cli version 2.0.17

```
$ aws ec2 replace-iam-instance-profile-association --iam-instance-profile Name=TKE_render --association-id iip-assoc-07c83b48335ca848d

An error occurred (IncorrectState) when calling the ReplaceIamInstanceProfileAssociation operation: The association iip-assoc-07c83b48335ca848d is not the active association
```

**Comment by kdaily** [comment]
Hi @llamafilm,

According to the documentation, this is intentional:

> Replaces an IAM instance profile for the specified running instance.

In the [IAM user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html), this note explains why:

> An instance profile can contain only one IAM role, although a role can be included in multiple instance profiles. This limit of one role per instance profile cannot be increased. You can remove the existing role and then add a different role to an instance profile. You must then wait for the change to appear across all of AWS because of eventual consistency. To force the change, you must disassociate the instance profile and then associate the instance profile, or you can stop your instance and then restart it.
