### ISSUE TITLE
AWS CLI Command Issue

### ISSUE THREAD

**Issue by meetrij** [aws/aws-cli#5253]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When I try to create schema using AWS CLI command `aws appsync start-schema-creation --api-id xxxxxxxxxxxxxxxxxxxxxxxxxx --definition file://D:\path\to\file\file.graphql --profile xxxx --region us-xxxx`

It's not creating all the schema definitions, the file size is 195 KB and only 152 KB is been generated when checked Appsync console

**SDK version number**
AWS CLI version 2

**Platform/OS/Hardware/Device**
Windows

**To Reproduce (observed behavior)**
Should get message like (PROCESSING, FAILED, SUCCESS, or NOT_APPLICABLE)

**Logs/output**
Displays the partial schema structure

**Additional context**
Contains following number of types
```
{
    "status": "SUCCESS",
    "details": "Successfully created schema with 586 types."
}
```
but getting only
```
{
    "status": "SUCCESS",
    "details": "Successfully created schema with 496 types."
}
```

**Comment by kdaily** [comment]
Hi @meetrij, I think you should be using a `fileb://` prefix for the definition parameter, unless your `file.graphql` is already base64 encoded:

```
aws appsync start-schema-creation --api-id xxxxxxxxxxxxxxxxxxxxxxxxxx --definition fileb://D:\path\to\file\file.graphql --profile xxxx --region us-xxxx
```

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam
