### ISSUE TITLE
Wrong file name in /awscli/examples/rds/

### ISSUE THREAD

**Issue by claytran** [aws/aws-cli#5260]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
There's an example file named modify-db-snapshot-attributes.rst, but the CLI command is modify-db-snapshot-attribute. Please delete the file.

**SDK version number**
N/A

**Platform/OS/Hardware/Device**
N/A

**To Reproduce (observed behavior)**
The file name has an "s" at the end, and the example doesn't show up in the [doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/modify-db-snapshot-attribute.html).

**Expected behavior**
The example file name should be correct, and the example should appear in the doc.

**Logs/output**
N/A

**Additional context**
I've created an updated example with the correct file name, which will be submitted soon with other RDS CLI examples.

**Comment by KaibaLopez** [comment]
Hi @claytran ,
thanks for the heads up

**Comment by kdaily** [comment]
This is fixed, thanks again!
