### ISSUE TITLE
Default value for networkMode for aws ecs register-task-definition --generate-cli-skeleton

### ISSUE THREAD

**Issue by tkumark** [aws/aws-cli#5266]
When running aws ecs register-task-definition --generate-cli-skeleton the neworkMode is set to "host". But according to the documention the default network mode is "Bridge" so I think when we run generate-cli-skeleton the value should be populated with "Bridge" instead of "Host"

**Comment by kdaily** [comment]
Hi @tkumark thanks for reporting! Interestingly, when I run `ecs register-task-definition --generate-cli-skeleton` multiple times, I get different a different value set for `networkMode` each time. This comes from `botocore`:

https://github.com/boto/botocore/blob/develop/botocore/utils.py#L854-L855

I can file a feature request such that this is not random. I'll have to dig a bit deeper to figure out if the stated default value can be set.

**Comment by JohnPreston** [comment]
@tkumark I just ran across this issue. Might be of interest to you as alternative to ecs cli (which as per my documentation, I am not pushing for if [ECS ComposeX](https://docs.ecs-composex.lambda-my-aws.io/) doesn't do what you need it to do).
Very opinionated tool about how to deploy to ECS though.

**Comment by kdaily** [comment]
Bumping this. Since code has changed, adding permalink line to offending code:

https://github.com/boto/botocore/blob/c3731390f7a98c35d13f766ba99e465c2ede9c78/botocore/utils.py#L942

**Comment by tim-finnigan** [comment]
Closing this in favor of https://github.com/aws/aws-cli/issues/6695 to improve functionality/documentation for this behavior.
