### ISSUE TITLE
SignatureDoesNotMatch when calling the ListBuckets operation

### ISSUE THREAD

**Issue by manel00** [aws/aws-cli#5270]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListBuckets operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**SDK version number**
boto3==1.13.23
python 3.6 64bits

**Platform/OS/Hardware/Device**
W10

**To Reproduce (observed behavior)**
#Have "config" and "credentials" files on ~\.aws folder

import boto3
import json

s3 = boto3.resource('s3')

for bucket in s3.buckets.all():
    print(bucket.name)

comprehend = boto3.client(service_name='comprehend', region_name='us-east-2')
text = "It is raining today in Seattle"

print('Calling DetectEntities')
print(json.dumps(comprehend.detect_entities(Text=text, LanguageCode='en'), sort_keys=True, indent=4))
print('End of DetectEntities\n')

**Expected behavior**
No errors jajaja

**Logs/output**

**Additional context**
i've tried already:

         s3 = boto3.resource('s3',
         aws_access_key_id=ACCESS_ID,
         aws_secret_access_key= ACCESS_KEY)

**Comment by KaibaLopez** [comment]
Hi @manel00 ,
Are you maybe looking for the [botocore repository](https://github.com/boto/boto3)?
