### ISSUE TITLE
EKS update-cluster-config does not return code 255 when command failed. 

### ISSUE THREAD

**Issue by rribeiro1** [aws/aws-cli#5272]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When I execute the command twice:
`aws eks --region ${AWS_REGION} update-cluster-config --name ${CLUSTER_NAME} --resources-vpc-config "publicAccessCidrs=${CIDRS}"`

It returns the error: `An error occurred (ResourceInUseException) when calling the UpdateClusterConfig operation: Cannot update because cluster any-cluster-name currently has update 572ddf60-48f7-41ce-96aa-824b18f8f644 in progress`

However, the error code is `0`.

As far as I read on this [page](https://docs.aws.amazon.com/cli/latest/topic/return-codes.html), it should return the code 255 when the CLI or service returns an error. 

**SDK version number**
aws-cli/1.18.57

**Platform/OS/Hardware/Device**
- macOS Catalina 10.15.4

**To Reproduce (observed behavior)**
Command: `aws eks --region ${AWS_REGION} update-cluster-config --name ${CLUSTER_NAME} --resources-vpc-config "publicAccessCidrs=${CIDRS}"`

1. Run the command twice
2. Print the return code: `echo $?`

The first command should update the cluster and the second one should throw the error, both returns code `0`.

**Expected behavior**
It should return the code 255 when receiving the error that the cluster is already being updated.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
I am trying to create a job to update the EKS config and I want to add some logic given an error from the CLI.

**Comment by kdaily** [comment]
I see an error code when encountering a `ResourceInUseException`. I ran the following command twice:

```
$ aws --version
aws-cli/1.18.57 Python/3.8.3 Darwin/19.5.0 botocore/1.16.7

$ aws eks update-cluster-config --name aws-cli-issue-5272 --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true

{
    "update": {
        "id": "96335e42-46f3-470c-8abe-16c9b791876b",
        "status": "InProgress",
        "type": "EndpointAccessUpdate",
        "params": [
            {
                "type": "EndpointPublicAccess",
                "value": "false"
            },
            {
                "type": "EndpointPrivateAccess",
                "value": "true"
            },
            {
                "type": "PublicAccessCidrs",
                "value": "[\"0.0.0.0/0\"]"
            }
        ],
        "createdAt": 1595447332.047,
        "errors": []
    }
}

$ aws eks update-cluster-config --name aws-cli-issue-5272 --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true

An error occurred (ResourceInUseException) when calling the UpdateClusterConfig operation: Cannot update because cluster aws-cli-issue-5272 currently has update 96335e42-46f3-470c-8abe-16c9b791876b in progress
$ echo $?
255
```

Can you please run this with debugging (`aws --debug ecs ...`). I see the following:

```
2020-07-22 12:55:31,750 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/awscli/clidriver.py", line 527, in __call__
    return self._operation_caller.invoke(
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/awscli/clidriver.py", line 649, in invoke
    response = self._make_client_call(
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/awscli/clidriver.py", line 661, in _make_client_call
    response = getattr(client, xform_name(operation_name))(
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/.pyenv/versions/3.8.3/envs/aws-cli-3.8.3-1.18.57/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the UpdateClusterConfig operation: Cannot update because cluster aws-cli-issue-5272 currently has update 96335e42-46f3-470c-8abe-16c9b791876b in progress
2020-07-22 12:55:31,755 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

Thanks!
