### ISSUE TITLE
InternalError when calling the CreateInstanceExportTask operation

### ISSUE THREAD

**Issue by marinoborges** [aws/aws-cli#5275]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windows 7 64 bits

**Describe the question**
 ec2 create-instance-export-task returns:
**"An error occurred (InternalError) when calling the CreateInstanceExportTask operation (reached max retries: 2): An internal error has occurred"**

The instance consists of a 50GB unencrypted volume based on Ubuntu image AMI-ID ami-0d1cd67c26f5fca19 with one disk (root device type ebs) and one network interface attached.
I checked the requirements and considerations (https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport.html) and it seems to meet all of them.

Command:
>aws ec2 create-instance-export-task --description "XXXXXX" --instance-id i-XXXXX --target-environment microsoft --export-to-s3-task DiskImageFormat=VHD,ContainerFormat=ova,S3Bucket=xxxxxx,S3Prefix=vms --debug --region us-west-2 2> Desktop\aws.txt

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
---- Debug log attached [aws.txt](https://github.com/aws/aws-cli/files/4748879/aws.txt)

**Comment by kdaily** [comment]
Hi @marinoborges, I'm not seeing anything jump out at me, but going to investigate further. I only note this is a community image, and while the prerequisites don't mention this specifically, they note that it won't work with Marketplace AMIs. 

I did find this other issue https://github.com/aws/aws-cli/issues/610#issuecomment-33259627 that notes that it only works with imported instances, but I don't see this guidance in the docs anymore so it's probably outdated.

**Comment by kdaily** [comment]
Hi @marinoborges,

Is there any way that you can provide the output of `aws ec2 describe-instances --instance-ids i-XXXXXXX` for this specific instance? Please be aware that this command can output potentially sensitive information, such as IP address ranges, etc. Please review the output before posting. Thanks!

**Comment by marinoborges** [comment]
[describe-instances.txt](https://github.com/aws/aws-cli/files/5084576/describe-instances.txt)
Hi @kdaily, here is the output of the command you asked. Greetings!

**Comment by kdaily** [comment]
Hi @marinoborges,

I'm not seeing anything else that I would identify as an issue with the CLI from what you provided. As far as what you've noted, you should be able to perform this operation. Since your debug output does contain a request ID for the error, you can open an AWS support case to get more details about this, as I cannot see any of that information.

I will pass on the error report to the EC2 team on my side, but can't provide an ETA as to when they might respond.

**Comment by marinoborges** [comment]
Thank you @kdaily
