### ISSUE TITLE
Publish a 2.x tag to DockerHub

### ISSUE THREAD

**Issue by ataylorme** [aws/aws-cli#5276]
**Is your feature request related to a problem? Please describe.**
I am using [the official AWS CLI Dockerfile published on DockerHub](https://hub.docker.com/r/amazon/aws-cli).

There are [tags for each release specific release as well as a `latest` tag](https://hub.docker.com/r/amazon/aws-cli/tags)

I would like to use the most up to date version of `2.x`. However, I do not wish to use the `lastest` tag as it could reference version 3 and breaking changes in the future.

**Describe the solution you'd like**
A `2.x` tag published to DockerHub that references an AWS CLI Dockerfile with the most recent published version of the v2 release.

**Describe alternatives you've considered**
- Pinning a specific tag/version, which mitigates the future release backward compatibility concern but requires more maintenance
- Using the `lastest` tag and crossing my fingers I don't miss an update to v3 in the future

**Additional context**
I think this is still a viable concern even if plans for v3 aren't currently underway. I am building a [Docker based custom GitHub Action](https://help.github.com/en/actions/creating-actions/creating-a-docker-container-action) to wrap the AWS CLI and I would like to implement semantic versioning. I cannot do that while using the `latest` tag of the Dockerfile.

It looks like the currently published tags are published on DockerHub by [`awscliautomation`](https://hub.docker.com/u/awscliautomation). Since you are already publishing tags in an automated way I am hoping this addition won't require significant effort

**Edit:** some background on why I am building a custom GitHub Action.
- The AWS CLI included in [the GitHub Virtual Environments](https://github.com/actions/virtual-environments) is `1.x` and I would like to use the AWS CLI `2.x`
- In addition to a generic action that runs any AWS CLI command I will take commands I frequently run together (e.g. to do a deployment) and bundle them up into their own custom GitHub Actions so they can be centrally maintained rather than chaining together multiple AWS commands [as shown in the `aws-actions/configure-aws-credentials` usage documentation](https://github.com/aws-actions/configure-aws-credentials#usage)

**Comment by kdaily** [comment]
Hi @ataylorme, thanks for the suggestion, I understand what you're requesting. Also, thanks for the information that the GitHub virtual environments are using a `1.x` version, except on Windows, where they are using `2.x`.
