### ISSUE TITLE
AWS CLI CloudTrail Events Results -> EventTime timestamp format changed from Unix/ epoch timestamp to other timetamp format

### ISSUE THREAD

**Issue by benishue** [aws/aws-cli#5279]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The timestamp format for the field (EventTime) in the CloudTrail lookup-events result in the documentation is Unix epoch format 

[https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudtrail/lookup-events.html#examples](url)

> aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=ConsoleLogin
> Output:
> 
> {
>   "Events": [
>      {
>          "EventId": "654ccbc0-ba0d-486a-9076-dbf7274677a7",
>          "Username": "my-session-name",
>          **"EventTime": 1453844532.0,**

_See image below_
While running the same command using the AWS CLI, the format of this field is different

> [bla@bla bla ~]# aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=ConsoleLogin
> {
>     "Events": [
>         {
>             "EventId": "bla-bla-bla",
>             "EventName": "ConsoleLogin",
>             "ReadOnly": "false",
>             "**EventTime": "2020-06-09T12:57:37+02:00**",
>             "EventSource": "bla.amazonaws.com",
>             "Username": "bla@bla.com",
>             "Resources": [], ...
> 
> 
> 
_See image below_
**SDK version number**
aws-cli/2.0.17 Python/3.7.3 Linux/3.10.0-1062.4.1.el7.x86_64 botocore/2.0.0dev21

**Platform/OS/Hardware/Device**
What are you running the cli on?
CentOs 7

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Run the following command from the AWS CLI [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudtrail/lookup-events.html);
`aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=ConsoleLogin`

**Expected behavior**
To get the same timestamp format for the field 

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
![image](https://user-images.githubusercontent.com/55318008/84176234-c0328800-aa89-11ea-9246-5ac0ecdf6f50.png)

**v.s.**

![image](https://user-images.githubusercontent.com/55318008/84176336-e3f5ce00-aa89-11ea-90b9-393d584bf585.png)

**Comment by kdaily** [comment]
Hi @benishue, thanks for the report. I can confirm running this command with `aws-cli/2.0.21` that I see a time format like:

```
"EventTime": "2020-06-17T12:04:36-07:00",
```

Labeling this as a documentation issue.

**Comment by tim-finnigan** [comment]
Hi @benishue, thanks for bringing this to our attention. In the [CloudTrail documentation](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_LookupEvents.html#API_LookupEvents_ResponseSyntax) it says EventTime is a number even though we are seeing a string returned. I reached out to the CloudTrail team to update their documentation. Once that is addressed we can update the example you referred to as well.

**Comment by tim-finnigan** [comment]
V472303385
