### ISSUE TITLE
Required parameter seems optional

### ISSUE THREAD

**Issue by rohangoel96** [aws/aws-cli#5288]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Describe the question**
- For [get-cost-and-usage](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ce/get-cost-and-usage.html?highlight=cost#examples) query, `Metrics` is a required parameter. Event then in the Synopsis it's put inside square brackets making it look like optional. This creates confusion for the customer. I wasn't sure if this is intended, hence didn't raise a bug.

**Comment by KaibaLopez** [comment]
Hi @rohangoel96 ,
Thanks for bringing this up, you're right, there is a typo on the document and we'll take a look at it.

**Comment by rohangoel96** [comment]
Thank you @KaibaLopez, I actually wanted to contribute to the documentation and was trying to fix it and raise a PR myself but was unable to find a way. If you don't mind, can you help me do that?

**Comment by kdaily** [comment]
Hi @rohangoel96, this issue has been passed on to the API documentation team to be addressed. Thanks again for reporting it!

**Comment by stobrien89** [comment]
Documentation has been updated.
