### ISSUE TITLE
aws cloudwatch put-metric-alarm does not set tags properly

### ISSUE THREAD

**Issue by twegener-embertec** [aws/aws-cli#5289]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Providing --tags to `aws cloudwatch put-metric-alarm` results in the a successful response, but the tags are not set, as shown by `aws cloudwatch describe-alarms-for-metric` and `aws cloudwatch list-tags-for-resource`.

**SDK version number**
aws-cli/1.17.17 Python/3.8.3 Linux/5.6.16-300.fc32.x86_64 botocore/1.14.17

**Platform/OS/Hardware/Device**
Fedora 32 Linux

**To Reproduce (observed behavior)**
```
aws cloudwatch put-metric-alarm --region=ap-southeast-2 --alarm-name=foo-dead --evaluation-periods=1 --alarm-description='Foo' --namespace='AWS/EC2' --dimensions='[{"Name": "InstanceId", "Value": "i-redacted"}]' --ok-actions='arn:aws:sns:ap-southeast-2:redacted' --alarm-actions='arn:aws:sns:ap-southeast-2:redacted' --actions-enabled --treat-missing-data=missing --period=300 --statistic=Average --threshold=0 --comparison-operator='GreaterThanThreshold' --metric-name='StatusCheckFailed' --tags='Key=Project,Value=FOO'
...
aws cloudwatch describe-alarms-for-metric --region=ap-southeast-2 --metric-name CPUUtilization --namespace AWS/EC2 --dimensions='[{"Name": "InstanceId", "Value": "i-redacted"}]'
...
aws cloudwatch list-tags-for-resource --region=ap-southeast-2 --resource-arn 'arn:aws:cloudwatch:ap-southeast-2:redacted'
...
```

**Expected behavior**
The Tags should appear in the JSON responses from describe-alarms-for-metric and list-tags-for-resource.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
```
aws cloudwatch describe-alarms-for-metric --region=ap-southeast-2 --metric-name CPUUtilization --namespace AWS/EC2 --dimensions='[{"Name": "InstanceId", "Value": "i-redacted"}]'

{
    "MetricAlarms": [
        {
            "AlarmName": "redacted",
            "AlarmArn": "arn:aws:cloudwatch:ap-southeast-2:redacted",
            "AlarmDescription": "redacted",
            "AlarmConfigurationUpdatedTimestamp": "2019-10-23T03:18:08.402Z",
            "ActionsEnabled": true,
            "OKActions": [
                "arn:aws:sns:ap-southeast-2:redacted"
            ],
            "AlarmActions": [
                "arn:aws:sns:ap-southeast-2:redacted"
            ],
            "InsufficientDataActions": [],
            "StateValue": "OK",
            "StateReason": "Threshold Crossed: 10 datapoints were not greater than or equal to the threshold (90.0). The most recent datapoints which not crossed the threshold: [1.8534917106613311 (18/06/18 13:45:00), 1.8757278256299352 (18/06/18 13:30:00), 1.8789169831135089 (18/06/18 13:15:00), 1.8460992250923987 (18/06/18 13:00:00), 1.8974097743206466 (18/06/18 12:45:00)].",
            "StateReasonData": "{\"version\":\"1.0\",\"queryDate\":\"2018-06-18T14:00:53.449+0000\",\"startDate\":\"2018-06-18T11:30:00.000+0000\",\"statistic\":\"Average\",\"period\":900,\"recentDatapoints\":[1.8759840696499352,1.8663358300431294,1.8673149949062575,1.8570220122870347,1.866394488314004,1.8974097743206466,1.8460992250923987,1.8789169831135089,1.8757278256299352,1.8534917106613311],\"threshold\":90.0}",
            "StateUpdatedTimestamp": "2018-06-18T14:00:53.459Z",
            "MetricName": "CPUUtilization",
            "Namespace": "AWS/EC2",
            "Statistic": "Average",
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "i-redacted"
                }
            ],
            "Period": 300,
            "EvaluationPeriods": 10,
            "Threshold": 90.0,
            "ComparisonOperator": "GreaterThanOrEqualToThreshold",
            "TreatMissingData": "missing"
        }
    ]
}
```

```
aws cloudwatch list-tags-for-resource --region=ap-southeast-2 --resource-arn 'arn:aws:cloudwatch:ap-southeast-2:redacted'
{
    "Tags": []
}
```

**Additional context**
The same problem occurs when using the API via boto3.

**Comment by twegener-embertec** [comment]
Note that setting tags via `aws cloudwatch tag-resource` appears to work to some extent, in that the tags subsequently appear via `aws cloudwatch list-tags-for-resource`. However, the tags still do not appear via `aws cloudwatch describe-alarms-for-metric` in that case, either.

```
aws cloudwatch tag-resource --region=ap-southeast-2 --resource-arn 'arn:aws:cloudwatch:ap-southeast-2:redacted' --tags='Key=Foo,Value=Bar'
```
```
aws cloudwatch list-tags-for-resource --region=ap-southeast-2 --resource-arn 'arn:aws:cloudwatch:ap-southeast-2:redacted'
{
    "Tags": [
        {
            "Key": "Foo",
            "Value": "Bar"
        }
    ]
}
```

**Comment by kdaily** [comment]
Hi @twegener-embertec,

According to the return type of `describe-alarms-for-metric`, that call does not return tags:

https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/describe-alarms-for-metric.html#output

However, I'm unable to reproduce when getting the tags via `list-tags-for-resource`. I tried using `aws-cli==1.17.17` installed in a `pyenv` virtual environment with `pip`, Python 3.8.3, on Mac OSX.

```
(aws-cli-3.8.3-1.17.17) > aws --version
aws-cli/1.17.17 Python/3.8.3 Darwin/19.5.0 botocore/1.14.17
(aws-cli-3.8.3-1.17.17) > aws cloudwatch put-metric-alarm --region=us-west-2 --alarm-name cpu-mon-70 --alarm-description "Alarm when CPU exceeds 70 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 70 --comparison-operator GreaterThanThreshold --dimensions "Name=InstanceId,Value=i-XXXXXXXXX" --evaluation-periods 2 --no-actions-enabled --unit Percent --tags='Key=Project,Value=FOO'
(aws-cli-3.8.3-1.17.17) > aws cloudwatch list-tags-for-resource --region=us-west-2 --resource-arn 'arn:aws:cloudwatch:us-west-2:XXXXXXXXXX:alarm:cpu-mon-70'
{
    "Tags": [
        {
            "Key": "Project",
            "Value": "FOO"
        }
    ]
}
```

**Comment by twegener-embertec** [comment]
Hi @kdaily, you are right regarding tags showing up via list-tags-for-resource after setting them via put-metric-alarm. I tried it again and it worked.
Regarding the docs, okay, I missed that, but seems surprising that put-metric-alarm / describe-alarms-for-metric doesn't round-trip in terms of tags. But sounds like that is just the way it is.
Apologies for the noise.

**Comment by kdaily** [comment]
Received another report of this, reopening.

**Comment by stobrien89** [comment]
Hi @twegener-embertec ,

I was investigating this a bit further and wanted to relay some information (which you may already be aware of): For existing alarms (apparently those that have been utilized or updated in some way), tags will be ignored.  The [documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/put-metric-alarm.html) makes mention of this and recommends using [TagResource](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_TagResource.html) or [UntagResource](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_UntagResource.html) if you wish to update tags for existing alarms.
