### ISSUE TITLE
Provide a simple way of using the functionality provided by this tool as a library

### ISSUE THREAD

**Issue by boosh** [aws/aws-cli#529]
It'd be great if there was a simple way to import the functionality offered by aws cli as a library. Scripts importing that library could then use these functions as primitives making it simple to write custom, higher-level wrappers, etc. without needing to interact directly with boto. This would also let them catch exceptions and handle errors properly. 

Currently the simplest way seems to just be shelling out to aws cli which isn't as flexible, especially from the perspectives of error handling, performance, security, etc.

If this is already possible, please let me know.

**Comment by JordonPhillips** [comment]
```python
from awscli import clidriver


aws = clidriver.create_clidriver()
# Make sure to leave out the 'aws' bit.
# command = "s3 ls".split(" ")
command = ['s3', 'ls']
aws.main(command)
```

This is possible from a fresh install via pip with no special modification. I absolutely cannot recommend this, however. We strive not to make changes that break expectations with regards to the results returned by the CLI, but we make no such promises about the internals. If you need more than what the CLI has to offer, I recommend you make use of one of the many SDKs we have available. The current python SDK, boto3, is quite nice and easy to use. And if you don't want to use python, there's plenty of other languages to choose from.
