### ISSUE TITLE
Add scope option for npm login on CodeArtifact 

### ISSUE THREAD

**Issue by ryansonshine** [aws/aws-cli#5291]
**Is your feature request related to a problem? Please describe.**
When using the `aws codeartifact login --tool npm` command, the configuration is set on the user's global npm profile. If a developer has multiple repositories across different organizations, they will be unable to run an `npm install` on another private npm repo due to the CodeArtifact configuration being set on the user level without scoping applied.

**Describe the solution you'd like**
Add an option for specifying scope when running the `aws codeartifact login --tool npm` command. See: https://docs.npmjs.com/using-npm/scope.html

**Describe alternatives you've considered**
I've considered assigning the output of `aws codeartifact get-authorization-token` to an environment variable, with the corresponding variable referenced in `.npmrc` however, this is harder to automate for developer machines across different operating systems.

**Additional context**
Running
`aws codeartifact login --tool npm --repository my-repo --domain my-domain`

results in
```sh
; userconfig ~/.npmrc
//my-domain-1234567890.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/:always-auth = true
registry = "https://my-domain-1234567890.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/"
```

The feature could look something like this
`aws codeartifact login --tool npm --repository my-repo --domain my-domain --scope "@myscope"`

resulting in:

```sh
; userconfig ~/.npmrc
//my-domain-1234567890.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/:always-auth = true
@myscope-scope:registry = "https://my-domain-1234567890.d.codeartifact.us-east-1.amazonaws.com/npm/my-repo/"
```

**Comment by kdaily** [comment]
Looking into this, @ryansonshine!

**Comment by kdaily** [comment]
Hi @ryansonshine, the CodeArtifact team has been notified about this feature request, but I don't have a date where this will be addressed. Thanks again!

**Comment by ryansonshine** [comment]
Thanks @kdaily , if I open a PR for this change will it be reviewed?

**Comment by kdaily** [comment]
Hi @ryansonshine, the CodeArtifact team is open to a PR - they are going to review the feature and can provide an update tentatively next week (~07/14/2020). I'll check back in then, thanks!

**Comment by ryansonshine** [comment]
Thanks! I'll start working on it this week and will submit a PR.

**Comment by vinaypoddar** [comment]
`--scope` didn't worked for me... solved by using ` --namespace`
```shell
aws codeartifact login --tool npm --repository my-repo --domain my-domain --namespace @myscope
```

**Comment by ryansonshine** [comment]
@vinaypoddar Correct! 

We ended up settling on `--namespace` since the other package managers have concepts similar enough to npm's scope but with different terminology.
