### ISSUE TITLE
Incorrect CloudWatchLogsLogGroupArn validation with DataSync Task

### ISSUE THREAD

**Issue by JuanOI** [aws/aws-cli#5293]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

The AWS CLI reports a verbatim copied version of a CloudWatchLogs log-group ARN as being invalid.

**SDK version number**

aws-cli/1.18.68 Python/2.7.18 Linux/3.10.0-1127.10.1.el7.x86_64 botocore/1.16.18

**Platform/OS/Hardware/Device**

Linux CentOS 7

**To Reproduce (observed behavior)**

1. Create a datasync task
2. Run the following command

```
aws datasync update-task --task-arn <DATASYNC_TASK_ARN> --cloud-watch-log-group-arn <LOG_GROUP_ARN> --options LogLevel=TRANSFER
```

**Expected behavior**

Datasync has been successfully updated to generate logs to the specified log group.

**Logs/output**

An error occurred (ValidationException) when calling the UpdateTask operation: 1 validation error detected: Value '<LOG_GROUP_ARN>' at 'cloudWatchLogGroupArn' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):logs:[a-z\-0-9]*:[0-9]{12}:log-group:([^:\*]*)$

**Additional context**

The command will run successfully if one removes the characters ':*' at the end of the ARN provided by AWS.

**Comment by kdaily** [comment]
@JuanOI, thanks for reporting. From where are you copying the CloudWatchLogs log-group ARN? From this [reference page](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html), a log group ARN should look like:

`arn:aws:logs:region:account-id:log-group:log_group_name`

**Comment by JuanOI** [comment]
Hi @kdaily  thanks for the reply! 

Sorry for the confusion, after I posted this issue I realized this is actually a bug on the AWS side. I'm fetching the ARN directly from the `aws_cloudwatch_log_group` resource. If I check directly on the console, the ARN has the ':*' characters in it. The workaround for now has been to `trimsuffix` on the output of the resource. 

I'll close this issue now.
