### ISSUE TITLE
aws s3 sync --exact-timestamps 

### ISSUE THREAD

**Issue by jrxubio** [aws/aws-cli#5299]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Linux
**Describe the question**
I used the command line: "aws s3 sync --exact-timestamps 1 myDir/ s3://mybucket/myDir/", and got error: Unknown options: s3://mybucket/myDir/. This command line was used before, and I can not identify where the mistake is. 

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by KaibaLopez** [comment]
Hi @jrxubio ,
The --exact-timeline option does not require a value, it is off by default and to turn it on simply add the option to the command.
`aws s3 sync myDir/ s3://mybucket/myDir/ --exact-timestamps`
