### ISSUE TITLE
CLI in CodeBuild image - import awscli.clidriver ModuleNotFoundError: No module named 'awscli'

### ISSUE THREAD

**Issue by Jun711** [aws/aws-cli#5306]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [X] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Image - aws/codebuild/standard:2.0
Environment type - Linux

**Describe the question**
After the container downloads aws-cli 1.18.83, it fails to import clidriver. 
Error message is
```
import awscli.clidriver 
ModuleNotFoundError: No module named 'awscli'
```

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
```

[Container] 2020/06/18 22:45:54 CODEBUILD_SRC_DIR=/codebuild/output/src580743728/src
--
5 | [Container] 2020/06/18 22:45:54 YAML location is /codebuild/output/src580743728/src/buildspec.yml
6 | [Container] 2020/06/18 22:45:54 Processing environment variables
7 | [Container] 2020/06/18 22:45:54 Selecting 'python' runtime version '3.7' based on manual selections...
8 | [Container] 2020/06/18 22:45:54 Running command echo "Installing Python version 3.7 ..."
9 | Installing Python version 3.7 ...
10 |  
11 | [Container] 2020/06/18 22:45:54 Running command pyenv global  $PYTHON_37_VERSION
12 |  
13 | [Container] 2020/06/18 22:45:54 Moving to directory /codebuild/output/src580743728/src
14 | [Container] 2020/06/18 22:45:54 Registering with agent
15 | [Container] 2020/06/18 22:45:54 Phases found in YAML: 3
16 | [Container] 2020/06/18 22:45:54  INSTALL: 1 commands
17 | [Container] 2020/06/18 22:45:54  PRE_BUILD: 1 commands
18 | [Container] 2020/06/18 22:45:54  BUILD: 2 commands
19 | [Container] 2020/06/18 22:45:54 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
20 | [Container] 2020/06/18 22:45:54 Phase context status code:  Message:
21 | [Container] 2020/06/18 22:45:55 Entering phase INSTALL
22 | [Container] 2020/06/18 22:45:55 Running command pip install --upgrade awscli
23 | Collecting awscli
24 | Downloading https://files.pythonhosted.org/packages/d4/21/3779c68cdc2e022aa8a28bba2afa509e6117130680df81a01546c98f53ca/awscli-1.18.83-py2.py3-none-any.whl (3.2MB)
25 | Requirement already satisfied, skipping upgrade: colorama<0.4.4,>=0.2.5; python_version != "3.4" in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from awscli) (0.4.3)
26 | Requirement already satisfied, skipping upgrade: PyYAML<5.4,>=3.10; python_version != "3.4" in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from awscli) (5.1.2)
27 | Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from awscli) (0.15.2)
28 | Collecting botocore==1.17.6
29 | Downloading https://files.pythonhosted.org/packages/1c/76/07b3a38140cff2fb245bb39afd074457600c1cc9502d6129e17b7565ddc9/botocore-1.17.6-py2.py3-none-any.whl (6.3MB)
30 | Requirement already satisfied, skipping upgrade: rsa<=3.5.0,>=3.1.2 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from awscli) (3.4.2)
31 | Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from awscli) (0.3.3)
32 | Requirement already satisfied, skipping upgrade: urllib3<1.26,>=1.20; python_version != "3.4" in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from botocore==1.17.6->awscli) (1.25.9)
33 | Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from botocore==1.17.6->awscli) (2.8.0)
34 | Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from botocore==1.17.6->awscli) (0.9.5)
35 | Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli) (0.4.8)
36 | Requirement already satisfied, skipping upgrade: six>=1.5 in /root/.pyenv/versions/3.7.6/lib/python3.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.17.6->awscli) (1.14.0)
37 | ERROR: boto3 1.12.49 has requirement botocore<1.16.0,>=1.15.49, but you'll have botocore 1.17.6 which is incompatible.
38 | Installing collected packages: botocore, awscli
39 | Found existing installation: botocore 1.15.49
40 | Uninstalling botocore-1.15.49:
41 | Successfully uninstalled botocore-1.15.49
42 | Found existing installation: awscli 1.18.49
43 | Uninstalling awscli-1.18.49:
44 | Successfully uninstalled awscli-1.18.49
45 | Successfully installed awscli-1.18.83 botocore-1.17.6
46 | WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
47 | You should consider upgrading via the 'pip install --upgrade pip' command.
48 |  
49 | [Container] 2020/06/18 22:46:07 Phase complete: INSTALL State: SUCCEEDED
50 | [Container] 2020/06/18 22:46:07 Phase context status code:  Message:
51 | [Container] 2020/06/18 22:46:07 Entering phase PRE_BUILD
52 | [Container] 2020/06/18 22:46:07 Running command
53 |  
54 | [Container] 2020/06/18 22:46:07 Phase complete: PRE_BUILD State: SUCCEEDED
55 | [Container] 2020/06/18 22:46:07 Phase context status code:  Message:
56 | [Container] 2020/06/18 22:46:07 Entering phase BUILD
57 | [Container] 2020/06/18 22:46:07 Running command aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
58 | Traceback (most recent call last):
59 | File "/bin/aws", line 19, in <module>
60 | import awscli.clidriver
61 | ModuleNotFoundError: No module named 'awscli'
62 |  
63 | [Container] 2020/06/18 22:46:08 Command did not exit successfully aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml exit status 1
64 | [Container] 2020/06/18 22:46:08 Phase complete: BUILD State: FAILED
65 | [Container] 2020/06/18 22:46:08 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml. Reason: exit status 1
```

**Comment by kdaily** [comment]
Hi @Jun711, sorry to hear this didn't work!

I tried to build the image locally on an Amazon Linux 2 EC2 and the Python section installed correctly. There was a complaint in my logs about a boto3 conflict but that didn't stop the installation from happening:

```
ERROR: aws-sam-cli 0.53.0 has requirement boto3>=1.13.0,~=1.13.0, but you'll have boto3 1.14.6 which is incompatible.
```

I also tried a very basic CodeBuild project and it built successfully using that image and ran without failure.

Of note, the image you are using (`aws/codebuild/standard:2.0`) will not be supported after June 2020, which is very soon!

https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

**Comment by Jun711** [comment]
@kdaily 
Note that it has built successfully before under the same configuration. 

I just created a new codebuild project and used image `aws/codebuild/standard:4.0`. It had the same problem. Environment type is linux. 

![Screen Shot 2020-06-22 at 12 32 10 PM](https://user-images.githubusercontent.com/6880939/85327783-67e58800-b484-11ea-8fa7-d27225c75fd5.png)

![Screen Shot 2020-06-22 at 12 37 34 PM](https://user-images.githubusercontent.com/6880939/85328192-286b6b80-b485-11ea-90aa-8adc308fd3e0.png)

Let me know if you need more information to reproduce.
What else can I try?

**Comment by kdaily** [comment]
Oh no! I tried again using `aws/codebuild/standard:4.0` and the same things you selected. I ran as a build command `aws ec2 describe-instances` successfully.

Could you add the following two commands to your build:

- `which aws`
- `python -c 'import awscli; print(awscli.__file__)'`

Can you also add the `--debug` flag:

```
aws --debug cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
```

Make sure any output there doesn't have any sensitive information in it before posting here, please!

**Comment by Jun711** [comment]
@kdaily 
I added these 2 commands before aws cloudformation commands and got this error 

```
which aws
python -c 'import awscli; print(awscli.__file__)'
```
Error Message
```
[Container] 2020/06/26 21:03:03 Running command python -c 'import awscli; print(awscli.__file__)'
61 | Traceback (most recent call last):
62 | File "<string>", line 1, in <module>
63 | ModuleNotFoundError: No module named 'awscli'
64
```

<img width="1056" alt="Screen Shot 2020-06-26 at 2 18 15 PM" src="https://user-images.githubusercontent.com/6880939/85902031-e2c9de00-b7b7-11ea-94cc-94d7c7950719.png">

without `python -c 'import awscli; print(awscli.__file__)'`
<img width="1012" alt="Screen Shot 2020-06-26 at 2 33 01 PM" src="https://user-images.githubusercontent.com/6880939/85902904-f413ea00-b7b9-11ea-8d27-4a07fe1686a2.png">

**Comment by Jun711** [comment]
I added `aws --version` command. 

It seems that aws is not in the path? I had never encountered this issue since I started using CodeBuild.

```
[Container] 2020/06/26 21:35:51 Running command aws --version
--
61 | Traceback (most recent call last):
62 | File "/bin/aws", line 19, in <module>
63 | import awscli.clidriver
64 | ModuleNotFoundError: No module named 'awscli'
```

**Comment by kdaily** [comment]
@Jun711,

Thanks for adding that! I should have had you add `pyenv which aws` instead of trying to load the `awscli` in Python - it's clear that it's not finding the library at alI, and points to a local/global Python environment issue.

I **think** I see what might be happening, but it's still odd that I can't replicate it. I see in line 22 of your original log:

```
22 | [Container] 2020/06/18 22:45:55 Running command pip install --upgrade awscli
```

Is there a reason why you are installing the CLI here? This image already has it installed for both Python 3.7 and 3.8:

https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L255
https://github.com/aws/aws-codebuild-docker-images/blob/master/ubuntu/standard/4.0/Dockerfile#L264

I see now that you are also specifying a Python runtime of Python 3.7 - this sets a global Python environment using `pyenv`. I added a section in my buildspec, so now it looks like this:

```
version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
       - which aws
       - pyenv which aws
       - python -c 'import awscli; print(awscli.__file__)'
       - aws ec2 describe-instances
```

Output:

<img width="854" alt="Screen Shot 2020-06-26 at 3 21 25 PM" src="https://user-images.githubusercontent.com/84993/85905771-32f96e00-b7c1-11ea-9cdc-289046f6f492.png">

What I can't determine is that I also tried adding an installation of the CLI client in the `install` phase too, but it still worked.

Build spec:

```
version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
        - pip install --upgrade awscli
  build:
    commands:
       - which aws
       - pyenv which aws
       - python -c 'import awscli; print(awscli.__file__)'
       - aws ec2 describe-instances
```

Output:

<img width="1030" alt="Screen Shot 2020-06-26 at 3 22 04 PM" src="https://user-images.githubusercontent.com/84993/85905743-19f0bd00-b7c1-11ea-9153-76fd7a92ae55.png">

When you run `aws`, it's running from `/bin/aws`, which indicates that the environment that the client is installed in isn't getting used. It should be at `/root/.pyenv/versions/3.7.7/bin/aws`, which is what I get.

So, a couple of things to try, in order of hopefully unblocking you, to determining the root cause of our different experiences.

1. Remove your own installation of `awscli`, as it should be there already.
2. Is there something in your pre-build phase that could influence this?
3. Add `pyenv which aws` to determine which Python environment is being used.

Thanks again for your efforts!

**Comment by Jun711** [comment]
@kdaily Thanks for helping me. It could build successfully after I commented out `pip install --upgrade awscli` so that it uses the awscli installed for that image. 

I created this project with AWS CodeStar probably half a year or so ago. This was automatically set up for me so I haven't modified that buildspec file until today.

1. ok, I commented out `pip install --upgrade awscli`.
2. no pre-build phase command that is being run.
3. `pyenv which aws` 

```
[Container] 2020/06/26 23:32:50 Phase context status code:  Message:
--
31 | [Container] 2020/06/26 23:32:50 Entering phase BUILD
32 | [Container] 2020/06/26 23:32:50 Running command which aws
33 | /root/.pyenv/shims/aws
34 |  
35 | [Container] 2020/06/26 23:32:50 Running command aws --version
36 | aws-cli/1.18.78 Python/3.7.7 Linux/4.14.181-108.257.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.17.1
37 |  
38 | [Container] 2020/06/26 23:32:57 Running command pyenv which aws
39 | /root/.pyenv/versions/3.7.7/bin/aws
40 |  
41 | [Container] 2020/06/26 23:32:57 Running command python -c 'import awscli; print(awscli.__file__)'
42 | /root/.pyenv/versions/3.7.7/lib/python3.7/site-packages/awscli/__init__.py
43 |  
44 | [Container] 2020/06/26 23:32:57 Running command aws --debug cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
```

**Comment by kdaily** [comment]
You're welcome! Thanks for the info on how it was created (CodeStar). I'll give that a try and see what happens now.

**Comment by Jun711** [comment]
@kdaily fyi, I just checked the commit date, it was created about 10 months ago.

<img width="1049" alt="Screen Shot 2020-06-26 at 6 40 50 PM" src="https://user-images.githubusercontent.com/6880939/85911857-baa0a600-b7dc-11ea-9a57-ce287c22d2d0.png">
