### ISSUE TITLE
Docker image for CLI version 1

### ISSUE THREAD

**Issue by keeganwitt** [aws/aws-cli#5307]
Similar to #3553, I'd like an image for version 1 of the CLI.

**Comment by kdaily** [comment]
Hi @keeganwitt, thanks for checking in. Can you describe your requirement for using version 1? Would using the version 2 Docker image be possible?

**Comment by keeganwitt** [comment]
I thought I'd read that [localstack](https://github.com/localstack/localstack) only partially supported V2 currently, but I'm having trouble finding where I read that.  I know there are certain unresolved issues like https://github.com/localstack/localstack/issues/1218.

Some use cases might be
* Docker Compose usage with localstack (assuming I'm correct in my understanding V2 isn't fully supported yet).
* Testing prod scripts that were using CLI V1 locally.
* Running production scripts written for V1 in prod.

The first of these use cases is what triggered my interest.
