### ISSUE TITLE
dangling multipart files?

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-cli#5315]
when doing s3 cp/s3 sync from local ec2 to s3, some multipart files are getting generated under /tmp 

/tmp/multipart-070375447
/tmp/multipart-263464344
/tmp/multipart-140824714

the files are still there after the aws cli command finishes. How to prevent them being created or have aws cli auto-purge them on completion? doing && rm /tmp/multipart-* is risky in case of multiple aws cli commands running in parallel

**Comment by kdaily** [comment]
Hi @tooptoop4,

What is the output of `aws --version`?

Can you run your command in debug mode and post the output (with any sensitive information redacted) For example:

```
aws --debug s3 cp ...
```

Thanks!

**Comment by tooptoop4** [comment]
aws --version
aws-cli/1.16.300 Python/2.7.18 Linux/4.14.181-140.257.amzn2.x86_64 botocore/1.13.36

aws --version
aws-cli/1.16.102 Python/2.7.18 Linux/4.14.181-108.257.amzn1.x86_64 botocore/1.12.92

debug log has nearly 18k lines in it, didn't look easy to redact. try replicating by doing 2 s3 cp commands of diff 6gb files in parallel (local to s3)

**Comment by kdaily** [comment]
Hi @tooptoop4,

I tried to reproduce using the same version and Python 2.7 (as well as the newest version), but I don't see any files named `multipart-*` created in `/tmp` when copying or syncing using the version you noted. Are you sure those files are coming from the CLI?

**Comment by tooptoop4** [comment]
not aws issue, was actually https://github.com/golang/go/issues/20253

**Comment by kdaily** [comment]
Thanks for confirming, @tooptoop4!
