### ISSUE TITLE
Logs not shipping to cloudwatch - Awslog agent errors out

### ISSUE THREAD

**Issue by dinesh-dubey** [aws/aws-cli#5321]
Hello,
We are using ECS based containers on EC2 node. For some reason AWS agent is not able to ship the logs from container to CloudWatch log groups. We are getting error 'awslogs dead but pid file exists' when we check the log agent service status. 

Attached is the AWS config file for logs, where we are shipping logs to different log groups.

When we check '/var/log/awslogs.log' inside those containers, we see below errors in that file. 

mportError: No module named requests
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 68, in main
    driver = create_clidriver()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 78, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/lib/python2.7/dist-packages/awscli/plugin.py", line 49, in load_plugins
    plugin.awscli_initialize(event_hooks)
  File "/usr/lib/python2.7/dist-packages/cwlogs/__init__.py", line 25, in awscli_initialize
    from cwlogs.push import initialize as logs_push_init
  File "/usr/lib/python2.7/dist-packages/cwlogs/push.py", line 34, in <module>
    import requests

The same setup is working fine in other environments. Can anybody please let us know what could be the issue.

**Comment by kdaily** [comment]
Hi @dinesh-dubey, can you provide some more information so I can try and reproduce, please? 

1. The EC2 AMI
2. The base container

Thank you!

**Comment by dinesh-dubey** [comment]
Hi @kdaily 
Please find the details below.
1. The EC2 AMI - ami-cb17d8b6
2. The base container - amazonlinux:2017.03

**Dockerfile for creating docker image.**

FROM amazonlinux:2017.03

RUN yum update -y && yum install -y awslogs && yum clean all


COPY config.properties /

RUN yum -y install sudo

RUN yum -y install java-1.8.0-openjdk

WORKDIR /

COPY *.jar /


**AWS config file configuration for logs**


[general]
state_file = /var/lib/awslogs/agent-state

[xyz-dev-logs]
datetime_format = %Y-%m-%dT%H:%M:%S.%f
file = /var/log/xyz_app*
buffer_duration = 5000
log_stream_name = {instance_id}/{host_name}
initial_position = start_of_file
log_group_name = xyz-dev-logs

#----------------------------------------------------#

[xyz-dev-events-es]
datetime_format = %Y-%m-%dT%H:%M:%S.%f
file = /var/log/xyz_events*
buffer_duration = 5000
log_stream_name = {instance_id}/{host_name}
initial_position = start_of_file
log_group_name = xyz-dev-events-es

#------------------------------------------------------#

[xyz-dev-api-es]
datetime_format = %Y-%m-%dT%H:%M:%S.%f
file = /var/log/xyz_api*
buffer_duration = 5000
log_stream_name = {instance_id}/{host_name}
initial_position = start_of_file
log_group_name = xyz-dev-api-es

Thanks
Dinesh

**Comment by kdaily** [comment]
I was able to reproduce - I received the same error at install time (the logs agent or daemon must be started then). I was able to fix this (the missing import) by changing the installation command to install `python27-requests` before installing `awslogs`:

```
RUN yum install -y python27-requests && yum install -y awslogs && yum clean all
```

**Comment by dinesh-dubey** [comment]
> I was able to reproduce - I received the same error at install time (the logs agent or daemon must be started then). I was able to fix this (the missing import) by changing the installation command to install `python27-requests` before installing `awslogs`:
> 
> ```
> RUN yum install -y python27-requests && yum install -y awslogs && yum clean all
> ```
> 
> Can you let me know if this works for you?

Hi @kdaily , Thank you for your help.  I was also able to fix this (the missing import) by changing the installation command
