### ISSUE TITLE
ASG support for ssm:resolve in  create-launch-configuration call

### ISSUE THREAD

**Issue by leonblueconic** [aws/aws-cli#5325]
**Describe the solution you'd like**
For ECS we would like to automatically use the lastest ECS enhanced AMI in our auto scaling groups.  At the moment on each release of a new ECS enhanced AMI we need to create a new version of the ASG Launch Configuration and update the image-id parameter.  It would be nice to just select the latest available AMI at launch time and not having to update the configurations all the time. This could be done with allowing the use of ssm:resolve in the image-id field.

**Describe alternatives you've considered**
At the moment we have a subscription to the ECS SNS topic which kicks of a script create a new launch configuration and updates the ASG.  But this leads to many launch configuration over time as we have multiple ECS clusters and use separate ASG for them.

**Comment by kdaily** [comment]
Hello @leonblueconic, looking into this. Thanks!

**Comment by kdaily** [comment]
Hi @leonblueconic, 

I found one resource that might help:

https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/

There is a solution for a use case similar to yours in the bottom of this post, which is for a Lambda job to watch the SNS queue for an updated ID and trigger the creation of a new launch template (sounds about like what you may be doing now).

Given that information, it looks like if this isn't the solution you're after, this feature would need to be implemented by the autoscaling team to be able to handle resolving the AMI ID using the `ssm:resolve` value. You can request this through the AWS Forums here:

https://forums.aws.amazon.com/forum.jspa?forumID=187
