### ISSUE TITLE
aws configure sso is not documented in awscli documentation site

### ISSUE THREAD

**Issue by heikkis** [aws/aws-cli#5327]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
"aws configure sso" options are not documented in awscli documentation site.

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/index.html

**Comment by kdaily** [comment]
Thanks for reporting!

**Comment by kdaily** [comment]
Hi @heikkis,

This documentation now exists:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/sso.html

Thanks again for reporting.
