### ISSUE TITLE
aws serverlessrepo create-cloud-formation-change-set does not allow passing a --role-arn

### ISSUE THREAD

**Issue by rojomisin** [aws/aws-cli#5331]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws serverlessrepo create-cloud-formation-change-set` does not allow passing a `--role-arn`, unlike it's sister function `aws cloudformation create-change-set`

I say this is a bug, because after looking at the SAR developer guide (pdf) https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-dg.pdf
I can't understand the reasoning behind not passing in a role-arn, I can only surmise no one has ever tried this with an app that requires a role to be assumed other than the prinicipal launching the sar app or creating the change set.

could be a feature request in some ways too, but it's surprising this ability is omitted

**SDK version number**
aws-cli/1.17.9 Python/2.7.17 Darwin/18.7.0 botocore/1.14.9

**Platform/OS/Hardware/Device**
OS X

**To Reproduce (observed behavior)**
- have a situation, where your IAM users cannot create IAM resources, except using a special cloudformation role that has this ability (the effect of forcing IAM resources to be managed "in a stack")
- create a serverless app that creates IAM resources
- create an entry in the SAR repo using `sam build` and `sam publish`
- create a change set using SAR arn as appid
`aws serverlessrepo create-cloud-formation-change-set --application-id <app arn> ... --role-arn <role that can create IAM resources>`
- execute the change set `aws cloudformation execute-change-set --change-set-name <change set arn>`

**Expected behavior**
I'm really trying to figure out the reusable SAR workflow here, which treats Serverless Application Repo as the storage place for versioned SAR artifacts.  I dont see how SAM package/publish and the aws cli "serverlessrepo" team's cloudformation change-set efforts align, seems disjointed.  I almost think there needs to be a simple `sam launch` command.

**Logs/output**

**Additional context**
seems like this would be simple to add, unless this is designed to not have --role-arn ?

**Comment by kdaily** [comment]
Hi @rojomisin,

Thanks for the feedback. I think this would be a feature request for the SAM team. In terms of the higher level commands (like a `sam launch`), have you checked out the AWS SAM CLI?

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started.html

**Comment by rojomisin** [comment]
hi @kdaily yes use the sam cli a lot.  SAM dev slack is not very active/responsive I've posed the question in there as well. `sam launch` is just an idea, but the passing of the `--role-arn` seems like a bug
