### ISSUE TITLE
Better error reporting for setting an invalid value for cli_pager

### ISSUE THREAD

**Issue by tdmalone** [aws/aws-cli#5332]
**Is your feature request related to a problem? Please describe.**

If the following is set in `~/.aws/config`:

     cli_pager = ''

Some commands (but not all!) fail with:

     ➜  ~ aws sts get-caller-identity
    [Errno 13] Permission denied: ''

This is a confusing error - and it took us quite a while to work out what the problem was! Because it doesn't fail on every command, we had lost the context of immediate feedback after setting this option, and further down the line believed there was something wrong with the user. We went through trying different users, different combinations of permissions, etc. etc. before being fairly confident it was a local issue, and then realising the problem still existed running the AWS CLI in a container (with the ~/.aws directory mounted into it).

(Note: the setting should actually have been `cli_pager =` without the quotes)

**Describe the solution you'd like**

Validation of the `cli_pager` setting. eg. if it's not a valid command, show an error stating that the `cli_pager` setting is incorrect.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by kdaily** [comment]
Hi @tdmalone, I could get it to fail consistently with the commands I tried by doing as you showed but with double quotes:

```
 cli_pager = ""
```

This isn't to do with the pager specifically - the 'ini' configuration format used here treats quotes as part of any string. If you add quotes around `region` for example, you get a similar (but more easily discernable) error:

```
Invalid endpoint: https://ec2."us-west-2".amazonaws.com
```

I'm checking into this to see what is the feasibility of changing the way that the config file is read (that's actually part of `botocore`, not the CLI).

**Comment by tdmalone** [comment]
No worries. Yep, I understand it's part of the ini config but if that's not possible/easy to change I was more just suggesting an error like `cli_pager '' could not be found`, which would - like the region setting - lead to the problem a lot quicker.

**Comment by kdaily** [comment]
I think that given the differences in how operating systems treat quoted commands (e.g., the command `"less" /tmp/file.txt` works on Bash), it would be better to address as validation of the configuration. I'll bump this over to botocore for you and link it here. Thanks!
