### ISSUE TITLE
how to import existing key-pair

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-cli#5336]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

root@Alexey-HP:~# aws --version
aws-cli/2.0.27 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev31

**Describe the question**

in order to create EC2 instance I need a key-pair
I've got a key-pair which I use for any other services (including cloud ones), so I'm not going specific key-pair for AWS
there's an option for me to import key-pair - https://docs.aws.amazon.com/cli/latest/reference/ec2/import-key-pair.html
however, the example of of 'import key-pair' command assumes that I created my key-pair with '-C "my-key"' option
I've created my key-pair with the command 'ssh-keygen -t rsa -b 2048' and it works fine for other cloud services

if I try to import my key-pair without --key-name I got the error (see below).

my question is: how can I use my existing key-pair for AWS ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

root@Alexey-HP:~# aws ec2 import-key-pair --public-key-material fileb://~/.ssh/id_rsa.pub
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: --key-name

**Comment by kdaily** [comment]
Hi @alexeyshishkin01, see this documentation on how to import your own key pairs:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws

I think your key pair needs to be in the `.pem` format. There's a code example in those docs on how to convert an OpenSSH key to that format.

**Comment by alexeyshishkin01** [comment]
hello, @kdaily , could you pls. read my question again ?

it refers to the same documentation you're mentioning and it really does not answer my question.

I'm talking about importing EXISTING key-pair - this key-pair works fine for me with Azure/Alibaba/GCP and these guys don't require any conversion of my EXISTING key-pair.

ok, let's follow AWS documentation:

1)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#how-to-generate-your-own-key-and-import-it-to-aws
as a result of this step I have
~/.ssh/my-key-pair.pub - my public key file which I get using 'cp ~/.ssh/id_rsa.pub ~/.ssh/my-key-pair.pub'
~/.ssh/my-key-pair.pem - my private key file which I get using 'ssh-keygen -e -m PEM -f ~/.ssh/id_rsa > ~/.ssh/my-key-pair.pem'

2)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#aws-cli
sends me to
https://docs.aws.amazon.com/cli/latest/reference/ec2/import-key-pair.html
which says:

First, generate a key pair with the tool of your choice. For example, use this ssh-keygen command:
ssh-keygen -t rsa -C "my-key" -f ~/.ssh/my-key
- sorry, guys, I've already have my key pair for Azure/Alibaba/GCP and I'm not going to create another one specifically for AWS

This example command imports the specified public key.
aws ec2 import-key-pair --key-name "my-key" --public-key-material fileb://~/.ssh/my-key.pub
- since I didn't generate AWS-specific key pair with '-C "my-key"', I cannot use 'aws ec2 import' command since '--key-name' is required

All this leads me to my topic question: 'how to import existing key-pair' ???

**Comment by shaunhickson** [comment]
I can see how that example is confusing. --key-name is required, but it specifies what the key will be called *by AWS* (e.g. if you were to run describe-key-pairs). It does not need to have any relationship to the name of the key you generated or the file name of the public key.

**Comment by kdaily** [comment]
Apologies, @alexeyshishkin01! I think what @shaunhickson provided is the answer. I created a new key without the `-C` flag to `ssh-keygen` and then imported it successfully. I'm going to mark this as an improvement to the documentation or examples to describe this better. Thanks again!

**Comment by alexeyshishkin01** [comment]
ok, guys, may I ask you to read my initial question again ?

it says the following:

"
...
if I try to import my key-pair without --key-name I got the error (see below).
...
root@Alexey-HP:# aws ec2 import-key-pair --public-key-material fileb:///.ssh/id_rsa.pub
usage: aws [options] [ ...] [parameters]
To see help text, you can run:

aws help
aws help
aws help
aws: error: the following arguments are required: --key-name
...
"

and my question is still the same: 'how to import existing key-pair' ?

Am I the first who cannot read AWS documentation correctly :-))))

It's a basic question from my point of view but I'm already scared about next step - how to create CentOS VM instance - another basic question from me - https://github.com/aws/aws-cli/issues/5340

@kdaily you say: 'I created a new key without the -C flag to ssh-keygen and then imported it successfully.'
May I ask you to list your commands which led to successful import of key-pair ?
thanks!

**Comment by kdaily** [comment]
@alexeyshishkin01 ,

The documentation as is worked for me! The only difference is I did not provide the `-C` flag to `ssh-keygen` to replicate your situation.

Here's my session:

```
> ssh-keygen -t rsa -f ~/.ssh/test-for-import
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in ~/.ssh/test-for-import.
Your public key has been saved in ~/.ssh/test-for-import.pub.
The key fingerprint is:
SHA256:aReb4De51qKCyQ1UKjFmgQmdT1WIVqb+WWandUZ1nkI user@zzzzzzzzzzz.com
The key's randomart image is:
+---[RSA 3072]----+
|o+.o ++o.    E. .|
|o B +oo     .. o.|
| o *.o  . . .. ..|
|  ..+  . o *  .  |
|   o.   S X o    |
|    .. * * *     |
|   . =o . + .    |
|    + o  o .     |
|       ..        |
+----[SHA256]-----+
> aws ec2 import-key-pair --key-name "test-for-import" --public-key-material fileb://~/.ssh/test-for-import.pub
{
    "KeyFingerprint": "9c:42:26:fa:dc:23:ef:d0:50:cb:2a:1f:dd:1b:01:85",
    "KeyName": "test-for-import",
    "KeyPairId": "key-0ad6cef85511319a6"
}
> aws2 ec2 delete-key-pair --key-name test-for-import
```

You can see at the end that the `--key-name` parameter ends up as metadata on the imported key in the `KeyName` field. This parameter is required, so any attempt to run without it will not work. The [Synopsis](https://docs.aws.amazon.com/cli/latest/reference/ec2/import-key-pair.html#synopsis) for this command indicates that this parameter is not optional (it is not in square brackets).

Let me know if I'm still missing something here to get you unblocked. Thanks!

**Comment by alexeyshishkin01** [comment]
ok, guys, pls. fix your documentation - it's really misleading

my next step is https://github.com/aws/aws-cli/issues/5340 - it still has no one assigned to it
