### ISSUE TITLE
how to create VM instance with CentOS

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-cli#5340]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

root@Alexey-HP:~# aws --version
aws-cli/2.0.27 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev31

**Describe the question**

I need to create VM instance with CentOS (ex. CentOS 7 with latest updates).
In GCP there's an elegant and simple way to do it:

gcloud compute instances create $INSTANCE_NAME \
--image-family=centos-7 \
--image-project=centos-cloud

Is there anything equivalent in AWS ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @alexeyshishkin01, 

In short there is not a way to create an EC2 with the CentOS operating system in that fashion. The recommended way to identify the appropriate AMI to use is to visit the vendor's own site. The CentOS images are maintained by CentOS themselves. CentOS maintains their AMI list here:

https://wiki.centos.org/Cloud/AWS#Official_and_current_CentOS_Public_Images

You can use the AWS API to search for AMIs, but note that it will search images created by the public and shared with the community. For example, this query lists images with `centos` in their name (returned 156 images when I ran it):

```
aws ec2 describe-images --filters "Name=name,Values=centos*" --query 'Images[*].[ImageId,CreationDate,Name]' --output text
```

You can read more here about how to identify a publicly shared image (including ones owned by Amazon):

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/usingsharedamis-finding.html

You can read here (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html) under "Finding the latest Amazon Linux AMI using Systems Manager" to identify the AMI of the most recent version of the Amazon Linux AMI.

I hope this helps!

**Comment by alexeyshishkin01** [comment]
how are you going to compete with GCP, guys ?

three lines for GCP which one can memorize:

gcloud compute instances create $INSTANCE_NAME
--image-family=centos-7
--image-project=centos-cloud

versus what-it-cannot-be-easily-found-in-documentation for AWS ...

**Comment by alexeyshishkin01** [comment]
btw, another issue - https://github.com/aws/aws-cli/issues/5348

how do you grab such a marketshare with this product ?
