### ISSUE TITLE
aws cloudformation deploy does not implement ClientToken

### ISSUE THREAD

**Issue by rl-michaelbrandeis** [aws/aws-cli#5342]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When running `aws cloudformation deploy` for deployments of approximately 10 stacks the create_change_set can time out and retr. If the initial create_change_set started but the response was not received then on retry it will error out with CREATE_IN_PROGRESS. The documentation for create_change_set suggests using ClientToken to prevent this 

https://github.com/aws/aws-cli/blob/364859c96ad9010a4bdbf32d42a1cbaa275610f2/awscli/customizations/cloudformation/deployer.py#L140

**SDK version number**
aws-cli/2.0.19 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev23

**Platform/OS/Hardware/Device**
What are you running the cli on?
mac-os/10.15.5

**To Reproduce (observed behavior)**
run 'aws cloudformation deploy' and drop the initial response
let retry occur and receive second response

this can be triggered by executing 10 stacks at a time in a loop and hitting cloudformation api limits

**Expected behavior**
I expect ClientToken to be used so on retry it does not try to to create the stack a second time but is smart enough to detect the stack is being created.

**Logs/output**
```
aws cloudformation deploy --template-file packaged.yml

An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:**** is in CREATE_IN_PROGRESS state and can not be updated.
```

**Additional context**

**Comment by kdaily** [comment]
Thanks for reporting, @rl-michaelbrandeis, marking as a feature request.
