### ISSUE TITLE
APigateway-getapikey usage errror

### ISSUE THREAD

**Issue by Vojjalasaikumar** [aws/aws-cli#5344]
I have written this code in CLI and took apikey-id from CLI get-api-key command , when i am passing api key to get-usage command like below command i run i got "An error occurred (NotFoundException) when calling the GetUsage operation: Invalid Key identifier specified" Error . Could you please help me out.

aws apigateway get-usage --usage-plan-id $usageplanid --key-id $apikeyid  --start-date "2020-07-01" --end-date "2020-07-04"

Please give me suggestions.

**Comment by kdaily** [comment]
Hi @Vojjalasaikumar,

Can you provide more information on how you are setting the `apikeyid` variable? Can you confirm that the value is only the API Key ID, and not the output of the `aws apigateway get-api-key` command (which gets more than just the key ID)?

Other information, like your CLI version and operating system, or output of the command in debug mode (`aws --debug apigateway get-usage`) could be helpful as well.

Thanks!
