### ISSUE TITLE
how to get CentOS image-id

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-cli#5346]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

root@Alexey-HP:~# aws --version
aws-cli/2.0.27 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev31

**Describe the question**

I need to create CentOS VM. The command 'aws ec2 run-instances' requires 'image-id'.

How to get CentOS image-id ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @alexeyshishkin01,

I answered this as part of #5340.
