### ISSUE TITLE
All .club domain checks returning UNAVAILABLE

### ISSUE THREAD

**Issue by stephenskinner** [aws/aws-cli#5356]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
AWS CLI is returning "UNAVAILABLE" when checking all .club domains. The web UI is also returning UNAVAILABLE, so I'm presuming the AWS .club domain checking service is down. Using godaddy domain checker shows the domain as available.

**SDK version number**
aws-cli/2.0.28

**Platform/OS/Hardware/Device**
What are you running the cli on?
Python/3.7.3 Linux/5.4.0-40-generic botocore/2.0.0dev32

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Run the cli with any .club domain name:
aws route53domains check-domain-availability --region us-east-1 --domain-name fdsfdlsfjkdlsf.club

**Expected behavior**
There should be an error message or a different status, as UNAVAILABLE should be reserved for when the domain name is already registered. DONT_KNOW should probably be returned.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
[route53debug.txt](https://github.com/aws/aws-cli/files/4892669/route53debug.txt)

**Additional context**

**Comment by kdaily** [comment]
Checking with the Route53 domains service team. Thanks for reporting.

**Comment by kdaily** [comment]
Hi @stephenskinner, thanks again. This was an external bug with a registrar and has since been resolved. I confirmed that the command you supplied returns `AVAILABLE`.

**Comment by stephenskinner** [comment]
Ok thanks for sorting this. Seems strange that this 3rd party issue was confined to AWS since godaddy was unaffected.
Happy to close this issue, appreciate the work in chasing this up quickly.
