### ISSUE TITLE
Missing/Unavailable Library Dependencies on Debian Buster

### ISSUE THREAD

**Issue by alaric728** [aws/aws-cli#5358]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
After install, there are a number of libraries that are unavailable on debian systems. Their listing in the format of file -> missing lib:
_cffi_backend.cpython-37m-x86_64-linux-gnu.so -> libffi-806b1a9d.so.6.0.4
_lzma.cpython-37m-x86_64-linux-gnu-.so -> liblzma.so.0
_ctypes.cpython-37m-x86_64-linux-gnu.so -> libffi.so.5

Going off of `dpkg -S` and some cursory searching, libffi.so.5 is not available post debian wheezy, and libffi-806b1a9d.so.6.0.4 appears to be retrieved only from a particular conda package.

liblzma.so.0 is also an outdated name for the library, and hasn't been in use since around 2010.

Examining the rpath of the broken ELFs, the _lzma and _ctypes have no rpath, and _cffi_backend points to a nonexistent ".libs_cffi_backend" directory.

**SDK version number**

**Platform/OS/Hardware/Device**
Debian Buster, 10.3

**To Reproduce (observed behavior)**
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
find /usr/local/aws-cli/v2/current/ -type f -exec sh -c "ldd {} | grep 'not found' && echo {}" \;

**Expected behavior**
	liblzma.so.0 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_lzma.cpython-37m-x86_64-linux-gnu.so
	libffi-806b1a9d.so.6.0.4 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_cffi_backend.cpython-37m-x86_64-linux-gnu.so
	libffi.so.5 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_ctypes.cpython-37m-x86_64-linux-gnu.so

**Logs/output**
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
find /usr/local/aws-cli/v2/current/ -type f -exec sh -c "ldd {} | grep 'not found' && echo {}" \;
	liblzma.so.0 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_lzma.cpython-37m-x86_64-linux-gnu.so
	libffi-806b1a9d.so.6.0.4 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_cffi_backend.cpython-37m-x86_64-linux-gnu.so
	libffi.so.5 => not found
/usr/local/aws-cli/v2/2.0.27/dist/_ctypes.cpython-37m-x86_64-linux-gnu.so

**Additional context**

**Comment by kdaily** [comment]
Hi @alaric728,

I was able to successfully install the AWS cli v2 on Debian Buster using the EC2 AMI suggested on the distribution web site with no warnings, errors, or messages:

https://wiki.debian.org/Cloud/AmazonEC2Image

```
admin@ip-172-31-13-227:~$ cat /etc/debian_version
10.4
........
admin@ip-172-31-13-227:~$  sudo ./aws/install
You can now run: /usr/local/bin/aws --version
```

Can you confirm if the client works for you successfully, even with the 'not found' messages?

**Comment by alaric728** [comment]
Hi @kdaily, 

I can run `aws --version`, but since I don't know the code paths for the libraries that are missing dependencies (_lzma, _cffi_backend, _ctypes cpython libs), I can't get to the failure points where an unlinked lib would cause an error. 

I've tested the most recent buster AMI and confirmed that awscli is still missing the libs it expects, and they are not available via regular packaging means. In fact, on the debian AMI it's also missing libython3.7 which is not installed by default (and `aws --version` will work with this library missing as wel).

Is there an easy way for me to test if these code paths work? Specifically, whatever uses the _lzma, _cffi_backend, and _ctypes cpython libraries.

**Comment by kdaily** [comment]
Hi @alaric728,

Can you tell me which AMI you are using to test, since I could not reproduce using the Buster AMI specified on the Debian wiki page. Thanks!
