### ISSUE TITLE
easy way to stop/start instance

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-cli#5361]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
root@Alexey-HP:~# aws --version
aws-cli/2.0.29 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev33

**Describe the question**
I need to stop/start instance.
According to https://docs.aws.amazon.com/cli/latest/reference/ec2/stop-instances.html#examples I need its 'instance-ids'.

How to find out 'instance-ids' of particular instance ?

For example, I have 5 instances - test1/test2/test3/test4/test5

In GCP I would run 'gcloud compute instances stop test1/2/3/4/5' - it's really easy-logical-user-friendly.

Is it possible to to the same in AWS ? Say, I have 5 instances as well.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @alexeyshishkin01 ,

The documentation on using the command line with EC2 instances describes this:

https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-instances.html#listing-instances

This section of the user guide walks through many common use cases of the command line with AWS services:

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-services.html

**Comment by alexeyshishkin01** [comment]
thanks, I've read these docs
my question was about 'easy way' to stop/start instance
it looks like there's no such thing in AWS
why? ..

**Comment by kdaily** [comment]
Hi @alexeyshishkin01 ,

You might check out `aws-shell`, which features tab completion of both commands and available AWS resources you have created:

https://github.com/awslabs/aws-shell

See this blog post describing this project, which includes a short discussion on how the command line client is implemented:

https://aws.amazon.com/blogs/developer/super-charge-your-aws-command-line-experience-with-aws-shell/
