### ISSUE TITLE
how to create instance from either snapshot or non-empty volume

### ISSUE THREAD

**Issue by alexeyshishkin01** [aws/aws-cli#5362]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
root@Alexey-HP:~# aws --version
aws-cli/2.0.29 Python/3.7.3 Linux/4.4.0-19041-Microsoft botocore/2.0.0dev33

**Describe the question**
How to create instance from either snapshot or non-empty volume ?
Sounds like an easy question and it's really easy in GCP.
But with AWS almost every single easy question is like a quest for me.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by sasikrish1217** [comment]
you need to create image from ebs snapshot

**Comment by alexeyshishkin01** [comment]
creating an image creates another snapshot :-)
1) GCP way - create snapshot - create instance
2) AWS way - create image (which creates snapshot) - create instance

let's compare the cost: snapshot (GCP) vs snapshot + image (AWS)
btw, I cannot delete AWS snapshot which image was created from due to dependency of image from snapshot :-(

**Comment by kdaily** [comment]
Hi @alexeyshishkin01,

You can read here for how to do this:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-launch-snapshot.html

The CLI command to do this referenced in this doc is at:

https://docs.aws.amazon.com/cli/latest/reference/ec2/register-image.html
