### ISSUE TITLE
What are the correct arguments to create an AWS aurora postgres instance using the AWS CLI?

### ISSUE THREAD

**Issue by docktermj** [aws/aws-cli#5365]
Is there a working example of the following?

```console
aws rds create-db-instance \
    --engine aurora-postgresql \
    :
```

https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html doesn't address the permutations of command-line options needed for `aurora-postgres`

It seems that others can't figure out how to use the AWS CLI to deploy an AWS Aurora-PostgreSQL:

1. https://stackoverflow.com/questions/58066941/what-are-the-correct-arguments-to-create-an-aws-aurora-postgres-instance-using-t

**Comment by docktermj** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-replicas-adding.html is close, but requires a cluster to be defined first.

**Comment by docktermj** [comment]
It would be really nice if at the bottom of a page like https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_GettingStartedAurora.CreatingConnecting.AuroraPostgreSQL.html there would be a link on how to perform the action via AWS CLI.

**Comment by kdaily** [comment]
Does the section "To create an Aurora PostgreSQL DB cluster using the AWS CLI" in this document answer this for you?

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.CreateInstance.html

I'll look into what kinds of cross-references can help here.
