### ISSUE TITLE
aws quicksigh register-user not sending email invitiations when --user-type QUICKSIGHT

### ISSUE THREAD

**Issue by SybaseWrangling** [aws/aws-cli#5368]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When using the following command: `aws quicksight register-user --aws-account-id <my acct id> --email fake@email.com --identity-type QUICKSIGHT --user-role READER --user-name my_test_user --namespace default --profile my_cli_profile`
No email invitation is sent to the intended user.

**SDK version number**
aws-cli/1.18.17

**Platform/OS/Hardware/Device**
What are you running the cli on?
Python/3.6.0 Windows/10 botocore/1.15.17

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Run the above command with the above options

**Expected behavior**
An email invitation is to be sent to the intended newly registered user

**Additional context**
The output from the command does list the invitation URL, which does work.  I just expected that the command would also initiate the invitation email.

If I go to the Quicksight UI, I can do a resend of the invitation, which does work.

If this is intentional, would it be possible to have it changed to a feature request.

**Comment by KaibaLopez** [comment]
Hi @SybaseWrangling ,

Yea, sending the email is not part of the output for register-user, that is expected behavior....

I'll keep this open as a feature request to maybe track interest but being completely honest, I don't see this having a high priority anytime soon, sorry about it.

**Comment by InnRonin** [comment]
Replicating for me when I add a user in another namespace other than the default namespace. How should I send then invitations for registration?
