### ISSUE TITLE
aws s3 sync: inconsistent timestamp precision of Last-Modified and file mtime with Ceph's S3 implementation

### ISSUE THREAD

**Issue by moorglade** [aws/aws-cli#5369]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I'm using *awscli* with a Ceph Object Gateway's S3 API endpoint (set with the `--endpoint-url` parameter).

When syncing data with the following command, all objects are **always** downloaded, although they were **not** modified:

```bash
aws --endpoint-url=https://my.s3.endpoint --exact-timestamps s3 sync s3://my-bucket/ /mnt/data/my-bucket/
```

It seems to me that when setting the file modification time (*mtime*), *awscli* rounds the *Last-Modified* timestamp to whole seconds, but it does not do so when comparing *mtime* with *Last-Modified*, i.e. it compares the **whole** *Last-Modified* value with the previously **rounded** *mtime* value, so they are (almost) never equal and the objects are always downloaded.

I have little experience with AWS, but the problem may stem from the fact that AWS's S3 implementation uses seconds precision for *Last-Modified*, while the Ceph's S3 implementation uses higher precision (e.g. milliseconds).

**SDK version number**
*awscli* 1.18.94
*Python* 3.6.8

**Platform/OS/Hardware/Device**
*CentOS* 7.8.2003
*Ceph* 14.2.8

**To Reproduce (observed behavior)**
Run `aws --exact-timestamps s3 sync` from S3 bucket to a local directory **twice**, using a Ceph's S3 endpoint.

**Expected behavior**
On the second *sync* execution, no objects should be re-downloaded.

**Logs/output**
This log fragment seem to show the different precision used for modification times:

```
MainThread - awscli.customizations.s3.syncstrategy.base - DEBUG - syncing:
  my-bucket/my-object -> /mnt/data/my-bucket/my-object,
  size: 598129502 -> 598129502,
  modified time: 2020-07-02 08:34:53.609000+00:00 -> 2020-07-02 08:34:53+00:00
```

**Additional context**

**Comment by kdaily** [comment]
Hi @moorglade ,

Thanks for the comments. I don't think that S3 stores milliseconds at all and the CLI is not rounding. I looked at a request response, and timestamps returned from the endpoint are in seconds, for example part of the response body for `aws s3 ls` has:

```
<LastModified>2020-07-14T17:18:04.000Z</LastModified>
```

If the Ceph implementation is returning time with millisecond precision, that would not be following the same standard as AWS. I would say that to be compliant this would need to be addressed by the Ceph team.
