### ISSUE TITLE
Both --quite & --only-show-errors are not working for "aws ecr describe-repositories" command

### ISSUE THREAD

**Issue by bjethwan** [aws/aws-cli#5372]
Both --quite & --only-show-errors are not working for "aws ecr describe-repositories" command.

aws --version
aws-cli/2.0.13 Python/3.7.3 Linux/5.3.0-1019-aws botocore/2.0.0dev17

Ubuntu 18.04  -- ec2

**Comment by kdaily** [comment]
Hi @bjethwan , The `aws ecr describe-repositories` does not have flags for `--quiet` and `--only-show-errors`. These are available for `s3` commands.
