### ISSUE TITLE
aws cli should report an error when a plugin is missing

### ISSUE THREAD

**Issue by ers81239** [aws/aws-cli#5391]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When running `aws ssm` commands, the commands fail silently if the ssm plugin is not installed.  Worse, running the command with `--debug` does show a successful handshake with AWS only to see the command terminate without error.

**SDK version number**
aws-cli/2.0.12 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev16

**Platform/OS/Hardware/Device**
Macbook Pro, Catalina 10.15.5 (19F101)

**To Reproduce (observed behavior)**
1. Install aws-cli without the ssm plugin
1. Run `aws ssm` commands.  In my case, my full command was `aws --debug --region=us-west-2  --profile cx-core-shared-services ssm start-session --target i-014f901e73e088e18 --document SSM-SessionManagerRunShell`

**Expected behavior**
1. An error message like `aws ssm requires the ssm plugin to be installed.  See https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

**Logs/output**
N/A

**Additional context**
We had three engineers spend an entire day trying to figure out why Session Manager wasn't working, to find out it was for this lack of plugin.

**Comment by kdaily** [comment]
Hi @ers81239, I raised this with the service team that maintains the SSM features. I'll post here when I get a response. Thanks!

**Comment by ers81239** [comment]
> Hi @ers81239, I raised this with the service team that maintains the SSM features. I'll post here when I get a response. Thanks!

Thank you!

**Comment by izaitsevfb** [comment]
This is still an issue in
```
aws --version
aws-cli/2.8.3 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off
```
