### ISSUE TITLE
Quoted PriceList output obfuscation

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#5397]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
`aws-cli/1.18.100 Python/3.8.3 Linux/5.7.9-arch1-1 botocore/1.17.23`

**Describe the question**
How does one get the price of EBS snapshots for Singapore?

**Logs/output**

```
 aws --region us-east-1 pricing get-products --service-code=AmazonEC2 --filters Type=TERM_MATCH,Field=productFamily,Value="Storage Snapshot"
{
    "PriceList": [
        "{\"product\":{\"productFamily\":\"Storage Snapshot\",\"attributes\":{\"storageMedia\":\"Amazon S3\",\"servicecode\":\"AmazonEC2\",\"usagetype\":\"USW2-EBS:SnapshotUnderBilling\",\"locationType\":\"AWS Region\",\"location\":\"US West (Oregon)\",\"servicename\":\"Amazon Elastic Compute Cloud\",\"operation\":\"\"},\"sku\":\"3AJTRRC7AHBFRH3K\"},\"serviceCode\":\"AmazonEC2\",\"terms\":{\"OnDemand\":{\"3AJTRRC7AHBFRH3K.JRTCKXETXF\":{\"priceDimensions\":{\"3AJTRRC7AHBFRH3K.JRTCKXETXF.6YS6EN2CT7\":{\"unit\":\"GB-Mo\",\"endRange\":\"Inf\",\"description\":\"$0.05 per GB-Month of Snapshot underbilling for August 31st\",\"appliesTo\":[],\"rateCode\":\"3AJTRRC7AHBFRH3K.JRTCKXETXF.6YS6EN2CT7\",\"beginRange\":\"0\",\"pricePerUnit\":{\"USD\":\"0.0500000000\"}}},\"sku\":\"3AJTRRC7AHBFRH3K\",\"effectiveDate\":\"2020-07-01T00:00:00Z\",\"offerTermCode\":\"JRTCKXETXF\",\"termAttributes\":{}}}},\"version\":\"20200709223013\",\"publicationDate\":\"2020-07-09T22:30:13Z\"}",
...
```

I'm trying to get price for Singapore via the AWS cli. Do let me know if v2 makes this any easier. This pricing API doesn't seem bizarrely difficult to work with!

Why is PriceList quoted/stringified JSON?
Is there a straightforward way to get the price for **ap-southeast-1**?

The value which is buried/obfuscated in the output is **0.05** btw. If you can show me how to programmatically retrieve that, it would put be at ease!

**Comment by kdaily** [comment]
Hi, looks like that's the expected format of this field:

https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_pricing_GetProducts.html

If you must do it using the AWS CLI, I would suggest a tool like `jq` (https://stedolan.github.io/jq/) to get out the `pricePerUnit` field.

Here's a guide which would help you to do this using the Python SDK, `boto3` (<https://github.com/boto/boto3>), for which you could write a short Python script also usable from the command line with the same credentials:

https://aws.amazon.com/blogs/aws/aws-price-list-api-update-new-query-and-metadata-functions/

**Comment by kaihendry** [comment]
The response isn't easy to parse the region I'm looking for.

**Comment by kdaily** [comment]
Wow, that price sure is buried in that stringified JSON! I couldn't figure out an explainable `jq` query to get it out either. I also couldn't figure out how to actually get pricing data for the `ap-southeast-1` region - setting my `--region ap-southeast-1` gives me:

```
Could not connect to the endpoint URL: "https://api.pricing.ap-southeast-1.amazonaws.com/"
```

So, that might be a service side bug. I'll follow up on that separately. However, I found an alternative to unblock you. I found these resources that were helpful:

1. https://aws.amazon.com/blogs/aws/aws-price-list-api-update-regional-price-lists/
1. https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-ppslong.html
1. https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/procedures.html#Ondemand-price-ec2

From the second link, I learned that you can get this same data programmatically without logging in in either JSON or CSV format. To answer your specific question, this is what I figured out to do:

```
curl https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-southeast-1/index.csv | grep "Storage Snapshot" | cut -d, -f 10,11
```

This gets the price and units (USD in this case). I pulled out what i thought were some more relevant details with:

```
curl https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-southeast-1/index.csv | grep "Storage Snapshot" | cut -d, -f 10,11,15,16,17,18,29,81
```

Hope this is helpful for you. I'll leave this open for now and check on how it could be performed with the CLI in this region.

**Comment by kdaily** [comment]
@kaihendry ,

If you are able to use Python to do this, here is a short code snipped from a related issue of someone who is doing something very similar:

https://github.com/boto/botocore/issues/2078#issuecomment-644976298
