### ISSUE TITLE
Credential file on win 10 adding "profile" to the name of the profile unexpectedly.

### ISSUE THREAD

**Issue by NM-HBK** [aws/aws-cli#5402]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When creating a credential profile manually,I try:
```
[test-profile-1]
aws_access_key_id = XXX
aws_secret_access_key = XXX
region = us-east-1
```
Then when trying to use the profile, `aws s3 ls --profile test-profile-1`, the cli complains that "The config profile (test-profile-1) could not be found"

However,
When creating using the aws cli (aws configure --profile test-profile-2) the entry in the credentials file looks similar to:
```
[profile test-profile-2]
aws_access_key_id = XXX
aws_secret_access_key = XXX
region = us-east-1
```
NOTE the "profile" at the beginning of the name of the profile.
Now the entry works with  `aws s3 ls --profile test-profile-2`.

The strangest part is that I am only seeing this on one machine. When I try this on several others with the same version and same OS version, I do not see the "profile" added to the name.

**SDK version number**
aws --version
aws-cli/1.18.79 Python/3.7.1 Windows/10 botocore/1.17.2

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
I can't reproduce this on any other machine

**Expected behavior**
That I would not see "profile" in the the profile name and creating the profile manually would also work

**Logs/output**
n/a

**Additional context**
n/a

**Comment by kdaily** [comment]
Hi @NM-HBK, I tried to reproduce but it was OK for me. I didn't try with Python 3.7, but I can do that. If you could confirm it occurs on a newer version of Python, that would be helpful too. Here's my session and output:

```
C:\Users\Administrator>aws --version
aws-cli/1.18.79 Python/3.8.5 Windows/10 botocore/1.17.2

C:\Users\Administrator>aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None

C:\Users\Administrator>aws configure --profile test-profile-2
AWS Access Key ID [None]: TESTPROFILE2
AWS Secret Access Key [None]: testprofile2
Default region name [None]: us-west-2
Default output format [None]: json

C:\Users\Administrator>aws configure --profile test-profile-2 list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile           test-profile-2           manual    --profile
access_key     ****************ILE2 shared-credentials-file
secret_key     ****************ile2 shared-credentials-file
    region                us-west-2      config-file    ~/.aws/config

C:\Users\Administrator\.aws>type credentials
[test-profile-2]
aws_access_key_id = TESTPROFILE2
aws_secret_access_key = testprofile2

C:\Users\Administrator\.aws>type config
[profile test-profile-2]
region = us-west-2
output = json
```

I see that the text you posted is indeed the format of the credentials file. Be aware that the config file *does* have a prefix of `profile` in the INI section header. Kindly confirm that this isn't what you are seeing too, thanks!

**Comment by NM-HBK** [comment]
I confirmed that this is causing the same issue with Python 3.7

**Comment by kdaily** [comment]
Hi @NM-HBK, I'm still not able to reproduce. I'm going to leave it open for a while to see if anyone else encounters it. Your version is relatively recent, but does this occur with the most recent version of the AWS CLI?

**Comment by stobrien89** [comment]
After further review, the issue, as reported is expected behavior.  It's quite possible that the formatting of the configuration has changed over time, but currently, all profiles other than the default profile _must_ be prefixed with "profile" in order to function properly with the CLI, regardless of whether it was created using the CLI or manually entered into the credentials file.
