### ISSUE TITLE
ModifyDBSnapshotAttribute says InvalidParameterValue on the parameter awsbackup:job-* 

### ISSUE THREAD

**Issue by PavanDevops** [aws/aws-cli#5407]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

We are working with AWS Backup for RDS Service. we would like to modify the attribute for DB Snapshot taken by AWS Backup.

"aws rds describe-db-snapshot-attributes" is able to get the details for the Snapshot Identifier "awsbackup:job-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" correctly.

whereas when we modify the attributes with "aws rds modify-db-snapshot-attribute", it gives Error:

An error occurred (InvalidParameterValue) when calling the ModifyDBSnapshotAttribute operation: The parameter awsbackup:job-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is not a valid identifier.

**SDK version number**
aws-cli/2.0.21 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev25

**Platform/OS/Hardware/Device**
What are you running the cli on?
Mac OS

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
1. Generate RDS Snapshot with AWS Backup Service (Make sure you have RDS DB running).
2. Check the attributes of the DB Snapshot generated by AWS Backup. see the results.
`aws rds describe-db-snapshot-attributes --db-snapshot-identifier awsbackup:job-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --region eu-west-1`
3. Try to modify the attribute for DB Snapshot. see the error.
`aws rds modify-db-snapshot-attribute --db-snapshot-identifier "awsbackup:job-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" --attribute-name restore --values-to-add 123456789012 --region eu-west-1`

And the error:
An error occurred (InvalidParameterValue) when calling the ModifyDBSnapshotAttribute operation: The parameter awsbackup:job-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is not a valid identifier.

**Expected behavior**
The modify functionaly should be able to identify the snapshot generated by AWS Backup Service

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @PavanDevops ,

Can you please include the output of running this with debugging enabled (`aws --debug`)? Thank you!
