### ISSUE TITLE
Improve documentation and example usage for aws transfer functionality (esp. create-user)

### ISSUE THREAD

**Issue by TonyLeeVT** [aws/aws-cli#5408]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
- [x] The documentation [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/transfer/create-user.html) lacks usage examples and clarity on the --role parameter

Issue is about usage on:
- [x] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
Ubuntu 16.04

**Describe the question**
Experiencing errors when trying to create a transfer user.  Documentation is lacking a bit on the --role parameter and example usage.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

```
aws transfer create-user --user-name foo --role sftp-transfer-role --server-id s-exxxx

Parameter validation failed:
Invalid length for parameter Role, value: 18, valid range: 20-inf
```

The previous error seems to indicate that the length of the role needs to be 20 characters or greater, so we tried using the ARN and now we experience the iam:PassRole error:
```
aws transfer create-user --user-name foo --role arn:aws:iam::xxx:role/SFTPRole --server-id s-exxxx

An error occurred (AccessDeniedException) when calling the CreateUser operation: User: arn:aws:iam::xxx:user/xxx is not authorized to perform: iam:PassRole on resource: arn:aws:iam::xxx
```

It is probably a silly mistake, but hopefully clearer documentation will help everyone get up and running more quickly.  Thanks for the great tool.

**Comment by kdaily** [comment]
Hi @TonyLeeVT ,

Thanks for taking the time to report. I think that the documentation could be improved in the description to indicate that this parameter expects an ARN, or the addition of an example section, as you suggested, would help clear this up.

Not that this is a replacement for an example here, but the [API documentation](https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html#TransferFamily-CreateUser-request-Role) specifies a pattern expression for the `--role` parameter:

> Type: String
> Length Constraints: Minimum length of 20. Maximum length of 2048.
> Pattern: `arn:.*role/.*`
> Required: Yes

Unfortunately, these are not propagated to the CLI docs! Marking this as a documentation improvement.

**Comment by kdaily** [comment]
@TonyLeeVT,

I found another command that takes a role ARN as a parameter: 

https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html#options

This one (while it is called `--role-arn` which is clearer) has the same kinds of restrictions on the string but a better description.

I've filed an issue with the doc writers, also to assess the `UpdateUser`, `CreateServer`, and `UpdateServer` actions, which also have role parameters.

**Comment by kdaily** [comment]
Hi @TonyLeeVT,

Improvements have been made to the API documentation. It takes a bit longer for the wording to propagate to the SDKs and the AWS CLI - I would expect to see the changes within the next two weeks, but it could take longer. Thanks again for bringing it to our attention.
