### ISSUE TITLE
aws s3 sync --exclude does't work consistently 

### ISSUE THREAD

**Issue by sajee** [aws/aws-cli#541]
On OSX 10.8.5, I'm trying to exclude .DS_Store but --exclude doesn't seem to work as expected.

```
$  aws --version
aws-cli/1.2.7 Python/2.7.2 Darwin/12.5.0

$ ls -Ra
./         ../        .DS_Store  a/         test.txt

./a:
./         ../        .DS_Store

$ aws s3 sync  ./  s3://sajee-sync/  --exclude "*.DS_Store"   --dryrun
(dryrun) upload: ./test.txt to s3://sajee-sync/test.txt

$ cd a
$ aws s3 sync  ../  s3://sajee-sync/  --exclude "*.DS_Store"   --dryrun
(dryrun) upload: ../.DS_Store to s3://sajee-sync/.DS_Store
(dryrun) upload: ../test.txt to s3://sajee-sync/test.txt
```

Why is ../.DS_Store getting uploaded?

Instead of  --exclude "*.DS_Store", I tried --exclude .DS_Store, --exclude *.DS_Store, ".DS_Store" but all produce the same results.

**Comment by thedukeness** [comment]
I'm still receiving this error as well
aws-cli/1.8.9 Python/2.6.6 Linux/2.6.32-573.7.1.el6.x86_64

**Comment by monsur** [comment]
I am still experiencing this issue as well. --exclude patterns that are exact matches (e.g. '.DS_Store'), do not work. I must have a wildcard in order for the --exclude to work.

**Comment by gregsadetsky** [comment]
Same here. I've had to specifically write `--exclude "*.DS_Store*"` for the matching to work. Thanks

**Comment by ericpeters0n** [comment]
This either does not seem to behave logically, or is not well-documented... I can't tell which.
