### ISSUE TITLE
MANPAGER takes precedence over AWS_PAGER

### ISSUE THREAD

**Issue by harrywhite4** [aws/aws-cli#5412]
**Describe the bug**

The MANPAGER environment variable takes precedence over the AWS_PAGER env var or  the cli_pager option in `~/.aws/config`

**Version**

aws-cli/2.0.34 

**Platform/OS/Hardware/Device**

Ubuntu 20.04 with the following output from `aws --version`

aws-cli/2.0.34 Python/3.7.3 Linux/5.4.0-40-generic botocore/2.0.0dev38

**To Reproduce (observed behavior)**

Can reproduce by running a command with both env vars like  `MANPAGER=cat AWS_PAGER=less aws cloudformation help`. This will use cat instead of less.

Setting MANPAGER to an empty string by running `MANPAGER= AWS_PAGER=less aws cloudformation help` also gives a list index out of range error.

**Expected behavior**

I would expect the aws specific variable and config file setting to take precedence

**Comment by kdaily** [comment]
Thanks for reporting, @harrywhite4. I could reproduce on Mac OSX as well.

**Comment by kdaily** [comment]
Hi @harrywhite4,

I talked this over with the other developers. The intention for the `cli_pager` and `AWS_PAGER` is for the output of the AWS commands, not for help documentation, so this is expected behavior. What would you expect to happen to control the output of help documentation at the command line? Other command line programs generally paginate their output as well.

**Comment by harrywhite4** [comment]
Ok that makes sense, mostly this is an issue for me because i use vim as a manpager and the aws cli does not launch it properly, but that is a separate issue.

I did get the impression from reading the docs that AWS_PAGER was used for everything. Maybe MANPAGER should be mentioned here? https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by kdaily** [comment]
Good call, @harrywhite4. Marking this as a documentation improvement. Thanks!

**Comment by kdaily** [comment]
Bumping as I think it's still relevant.
