### ISSUE TITLE
ssm start-session AWS-StartPortForwardingSession not forwarding FIN

### ISSUE THREAD

**Issue by bmteller** [aws/aws-cli#5414]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

AWS-StartPortForwardingSession does not forward TCP FIN packet when the remote side closes the connection.

**SDK version number**
aws-cli/1.18.105 Python/3.7.8 Darwin/19.3.0 botocore/1.17.28

**Platform/OS/Hardware/Device**
OSX 
Darwin XXXX 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**To Reproduce (observed behavior)**
1. Forward local port 8888 to port 8080 on server
```
aws --region "$REGION" ssm start-session --target "$INSTANCE_ID" \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["8080"],"localPortNumber":["8888"]}'
```

2. Make TCP connection to forwarded port locally. 
3. Process at other end of the forwarded port half closes the TCP connection. 
4. Expect the TCP connection to be half closed locally. The TCP connection is not half closed locally.

**Comment by kdaily** [comment]
Hi @bmteller, I'm contacting the SSM team about this. Thanks!
