### ISSUE TITLE
help me out with this vs code faulty AWS installation error 

### ISSUE THREAD

**Issue by Anustup900** [aws/aws-cli#5416]
![npm error](https://user-images.githubusercontent.com/60361231/88634013-6fc3c800-d0d3-11ea-92a1-af358ff52a07.PNG)

**Comment by kdaily** [comment]
Hi @Anustup900, we do not support AWS amplify in this repository. Please check out the [AWS Amplify](https://aws.amazon.com/amplify/) site for more information and for how to contact to get help.
