### ISSUE TITLE
wafv2 list-resources-for-web-acl only fetches load balancers by default - this is not documented

### ISSUE THREAD

**Issue by slushysnowman** [aws/aws-cli#5417]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I have a web ACL which is tied to an Application Load Balancer and an API Gateway

When using 'list-resources-for-web-acl', without specifying ''--resource-type", I would expect to get ALL resources.

However what I actually get is only load balancers. To get API Gateways I need to specify '--resource-type API_GATEWAY'

**SDK version number**
aws-cli/2.0.17 Python/3.7.3 Linux/5.4.0-42-generic botocore/2.0.0dev21

**Platform/OS/Hardware/Device**
What are you running the cli on?
Ubuntu 20.04

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

1 - Create a regional web-acl
2 - Assign web-acl to an ALB and an API Gateway
3 - `aws wafv2 list-resources-for-web-acl --web-acl-arn <ARN_HERE>`

You will only get the ARN of the ALB returned

**Expected behavior**
Preferably the ARNs of all associated resources should be returned if --resource-type is not specified

At minimum, documentation should be adjusted to reflect the fact that ALB is set as default - this is currently not the case - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wafv2/list-resources-for-web-acl.html

**Logs/output**
n/a

**Additional context**
n/a

**Comment by kdaily** [comment]
Hi @slushysnowman, I can see that the documentation can be improved here. I'll pass this request over to the service team that maintains [the documentation](https://docs.aws.amazon.com/waf/latest/APIReference/API_ListResourcesForWebACL.html) to clarify what the default behavior is, and inquire if the behavior could be altered.

**Comment by slushysnowman** [comment]
OK great, thanks!

**Comment by kdaily** [comment]
Bumping this as it's still unresolved.

**Comment by tim-finnigan** [comment]
In the API [documentation](https://docs.aws.amazon.com/waf/latest/APIReference/API_ListResourcesForWebACL.html) referenced earlier, it says ResourceType is not required. So either it should say that ResourceType is required or there is an issue with the API. 

I created an AppSync API and could confirm that it was only returned when I specified `--resource-type APPSYNC` in that command.

I reached out to WAF team to ask for clarity on this and see if it is an issue with the documentation or API itself.

**Comment by tim-finnigan** [comment]
P55460545

**Comment by tim-finnigan** [comment]
I heard back from the service team that the documentation has been updated. There is now a note for `ResourceType` which says: 

> If you don't provide a resource type, the call uses the resource type `APPLICATION_LOAD_BALANCER`.

Thanks again for reporting this! I'll go ahead and close the issue.
