### ISSUE TITLE
Route53Domains.TransferDomainToAnotherAwsAccount generates paswords with single quotes and backticks

### ISSUE THREAD

**Issue by scottcrespo** [aws/aws-cli#5422]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

`route53domains transfer-domain-to-another-aws-account` returns passwords with special characters that are difficult, if not impossible, to escape in bash.  Call it luck of the draw, but I had a password generated that contained single quotes and backticks. 

Escaping those characters with backslashes resulted in authentication failure when calling `route53domains accept-domain-transfer-from-another-aws-account`. 

Only solution was to leverage `--cli-input-json file://path/to/file.json`

This issue could cause intermittent failure of bash scripts for transferring domains when the script attempts to call `route53domains accept-domain-transfer-from-another-aws-account` and cli param `--password`.  Or in my case, about an hour of headache. 

**SDK version number**
```
aws-cli/1.18.69 
Python/3.6.9 
Linux/5.3.0-62-generic 
botocore/1.16.19
```

**Platform/OS/Hardware/Device**
OS:  Linux Mint 19.3 Tricia
Hardware: amd64
Device: Dell M4600

**To Reproduce (observed behavior)**

Step 1: call `aws route53domains transfer-domain-to-another-aws-account --domain-name <domain name> --account-id <account id>`

If you receive password with single quotes or backticks....

Step 2: `aws route53domains accept-domain-transfer-from-another-aws-account --domain-name <domain name> --password <password with backslashes to escape>`

Then password will fail with: `An error occurred (InvalidInput) when calling the AcceptDomainTransferFromAnotherAwsAccount operation: Password is incorrect.
`

**Expected behavior**

1. CLI/API should not generate passwords with characters that will break the CLI. Dollar signs may also be an issue for BASH users.

AND/OR

2. Prominent warnings in documentation 

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @scottcrespo, I can see how that would be frustrating, especially passwords with single quotes (usually the delimiter to use in the console for literal interpretation of a string). This would have to be handled by the service team. I agree at a minimum, this should be clearly documented.

**Comment by scottcrespo** [comment]
@kdaily Thanks for the quick response. Please let me know if you need any more information or action on my end.

**Comment by kdaily** [comment]
Hi @scottcrespo , another option (and more secure) would be to write the password to a file it as the parameter to `--password`. You could use a JMESPath query for the `aws route53domains transfer-domain-to-another-aws-account` (or, pipe the output to a tool like `jq`) to get the password field to a file (say `/tmp/password.txt`). Then you can do:

```
aws route53domains accept-domain-transfer-from-another-aws-account --domain-name <domain name> --password file:///tmp/password.txt
```

This would keep the password out of the console and out of an environment variable as well. Does this solution help you out? The documentation could still be improved to make users aware of the character set available for passwords.

**Comment by scottcrespo** [comment]
@kdaily 

Clever solutions! They would be great additions to the documentation to help anyone else that encounters the issue. I got around using a similar approach: I wrote the parameters to a file and used `--cli-input-json file://path/to/file.json` to accept the domain transfer.

IMHO, a simpler and less error-prone solution (for the long term) might be for the API to return a random alphanumeric string; for example, a random SHA1 or SHA256 hash. When writing a script or doing a copy+paste operation, I don't think users would mind working with a longer password that has a limited and "safer" character set.

**Comment by kdaily** [comment]
Good suggestion, @scottcrespo. Here are the docs for using the `--query` option, which works with all AWS CLI commands.  It Isn't included with every service action because it's a client-side operation:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter

**Comment by kdaily** [comment]
Hi @scottcrespo, I've passed this on to the API team, so going to close this out here as it isn't specific to the AWS CLI. Thanks again for your feedback and suggestions!

**Comment by Aldekein** [comment]
I definitely see a bug there with `aws-cli/2.4.4 Python/3.9.9 Darwin/20.6.0 source/x86_64 prompt/off`

Here's the response I've got from `route53domains transfer-domain-to-another-aws-account` command:
```
{
    "OperationId": "2bc2995d-c8f1-4c1f-b24e-9676f30fd3ac",
    "Password": "xaY7y3w?Ni{V\"E"
}
```

1. I tried different variants of escaping it in the command line.
2. I tried putting it in the environment variable.
3. I tried the `aws route53domains accept-domain-transfer-from-another-aws-account --cli-input-json file://params.json` way.

No mater what I do, the response is the same:
`An error occurred (InvalidInput) when calling the AcceptDomainTransferFromAnotherAwsAccount operation: Password is incorrect.`

This makes me think that some characters are already escaped in the original output I got.

**Comment by fxgx99** [comment]
Hi everyone,

Just here  to add that 2 years after the initial bug was reported, this issue persist. in fact it has gotten worse. One has  to initiate and cancel a domain transfer several times before  getting an acceptable password. Is there a fix to this?

**Comment by ehcloninger** [comment]
@fxgx99 See the above reply from @kdaily about putting the password in a file and then using `--password file://pw.txt` to load it in the CLI. Not perfect and difficult to automate, but you're probably not doing this often.

**Comment by abhinavbom** [comment]
> Hi @scottcrespo , another option (and more secure) would be to write the password to a file and then use it as the parameter to `--password`. You could use a JMESPath query for the `aws route53domains transfer-domain-to-another-aws-account` (or, pipe the output to a tool like `jq`) to get the password field to a file (say `/tmp/password.txt`). Then you can do:
> 
> ```
> aws route53domains accept-domain-transfer-from-another-aws-account --domain-name <domain name> --password file:///tmp/password.txt
> ```
> 
> This would keep the password out of the console and out of an environment variable as well. Does this solution help you out? The documentation could still be improved to make users aware of the character set available for passwords.

this method worked for me.
