### ISSUE TITLE
Non-default vpc: "DNS hostnames are disabled by default."

### ISSUE THREAD

**Issue by mcbain** [aws/aws-cli#543]
I have a non-default vpc where i want to launch instances. The docs http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-vpc.html say:

Non-default vpc: "DNS hostnames are disabled by default."

Currently there is no option to set in during ec2-launch with "aws ec2 run-instances".

http://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html

**Comment by nnt** [comment]
From the [documentation](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html):
> The Amazon DNS server cannot resolve private DNS hostnames if your VPC's IP address range falls outside of the private IP addresses ranges specified by [RFC 1918](http://www.faqs.org/rfcs/rfc1918.html).

And from [RFC 1918](http://www.faqs.org/rfcs/rfc1918.html):
```
   ... the following three blocks of the IP address space for private internets:
     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
```
So you had an invalid range (8.x.x.x) for Amazon DNS server to resolve.
