### ISSUE TITLE
inspector list-assessment-runs --output text returns too many results, --output json works correctly

### ISSUE THREAD

**Issue by jamey-taylor** [aws/aws-cli#5438]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
inspector list-assessment-runs may return too many results when using both the --query option with a JMESPath index expression and --output text.

```
aws inspector list-assessment-runs --region us-east-2--query "assessmentRunArns[0]" --output text

arn:aws:inspector:us-east-2:XXXXXXXXXXX:target/0-gEUPDHIA/template/0-u8wQJc4S/run/0-0eias5Xn
arn:aws:inspector:us-east-2: XXXXXXXXXXX:target/0-gEUPDHIA/template/0-u8wQJc4S/run/0-GH8w0PlL
arn:aws:inspector:us-east-2: XXXXXXXXXXX:target/0-gEUPDHIA/template/0-u8wQJc4S/run/0-WCi1AT4K
arn:aws:inspector:us-east-2: XXXXXXXXXXX:target/0-gEUPDHIA/template/0-u8wQJc4S/run/0-lAv3rZMn
```

Note that the same operation with --output json works as expected.

```
aws inspector list-assessment-runs --region $region --query "assessmentRunArns[0]" --output json 

"arn:aws:inspector:us-east-2:XXXXXXXXXXXX:target/0-gEUPDHIA/template/0-u8wQJc4S/run/0-0eias5Xn"
```

**SDK version number**
aws-cli/2.0.36 Python/3.7.4 Darwin/19.6.0 exe/x86_64

**Platform/OS/Hardware/Device**
What are you running the cli on?
Mac OX X

**To Reproduce (observed behavior)**
Run aws inspector list-assessment runs on an account and region with multiple completed assessment runs. Use --query "assessmentRunArns[0]" to limit results to the first item and --output text. Notice multiple results are returned.

**Expected behavior**
Only the first result should be returned.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @jamey-taylor ,

I think that this is expected behavior. Have a look at this documentation:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter

The section there gives some caveats with the different output types:

> If you specify --output text, the output is paginated before the --query filter is applied, and the AWS CLI runs the query once on each page of the output. This can result in unexpected extra output, especially if your filter specifies an array element using something like [0], because the output then includes the first matching element on each page. To work around the extra output that --output text can produce, you can specify --no-paginate. This causes the filter to apply only to the complete set of results. But it does remove any pagination, so it might result in long output. You can also use other command line tools such as head or tail to additionally filter the output to only the values you want.

**Comment by jamey-taylor** [comment]
@kdaily , thanks for pointing me to the correct space in the CLI user guide! I learned something new today.
