### ISSUE TITLE
aws s3 does not detect proxy

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-cli#5440]
**Describe the bug**
I have aws cli version 1.16~ installed on windows 2012, and after setting the proxy variables as instructed from AWS docs the aws s3 ls times out

**SDK version number**
1.16

**Platform/OS/Hardware/Device**
What are you running the cli on?
aws s3 ls

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Follow instructions per https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html
type aws s3 ls and hit enter
hangs for a bit and then comes back with cannot reach endpoint url

**Expected behavior**
I want to see a response with the list of buckets

**Comment by kdaily** [comment]
Hi @BardiaAfshin, can you please provide the output when running this with debug mode (add the `--debug` flag to your command). Thanks!

**Comment by BardiaAfshin** [comment]
I don't have access to this information, closing ticket since it's vague.
