### ISSUE TITLE
macOS Catalina stucks at flashing "verifying xxx-darwin.so" screen

### ISSUE THREAD

**Issue by dz902** [aws/aws-cli#5441]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

macOS Catalina

**Describe the question**
I used to have v1 CLI installed using `pip`. Then I found it lacks some new APIs so I uninstalled using `pip uninstall` then installed v2 CLI by following official instructions.

After installation when I try to run `aws` bash hangs. Every few seconds there is a quick flash of a security alert window showing "verifying terminos.cpython-37m-darwin.so" or something like that. The window disappear very quickly, but after waiting for a long time the command still hangs.

I looked at the security panel and did not found the "allow" button which usually will be there when the security alert window pops up.

Cloud not find any clue. Please advise. Thanks.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @dz902,

Sorry to hear you're having issues after you tried to get the v2 client. Can you confirm which installation instructions you followed? There are instructions to use the [Mac GUI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-gui) or the [command line](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-cmd). Thanks!

**Comment by dz902** [comment]
> Hi @dz902,
> 
> Sorry to hear you're having issues after you tried to get the v2 client. Can you confirm which installation instructions you followed? There are instructions to use the [Mac GUI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-gui) or the [command line](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-cmd). Thanks!

I actually tried both ways. Did in with command line first, stuck, then uninstall and double clicked on the pkg file, still stuck.

Now it's working, just stuck there for enormous time, with window flashing every now and then. This happens both for the `aws` command and the autocompleter, at first run.
