### ISSUE TITLE
Remove Codeartifact from Pip

### ISSUE THREAD

**Issue by gdj0nes** [aws/aws-cli#5442]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Ubuntu

**Describe the question**

How do I remove a Codeartifact repository from my global pip configuration? I have a number of projects which do not use Codeartifact but it appears to attempt to use it for all projects. How do I stop this behavior? A nice addition to the docs would be how to stop using Codeartifact.

**Comment by gdj0nes** [comment]
On a linux system you need to alter the configuration in two places:
- $HOME/.pypirc
- $HOME/.config/pip/pip.conf

**Comment by kdaily** [comment]
Hi @gdj0nes, looks like you answered your own question! The user guide describes the files that are changed when configuring:

https://docs.aws.amazon.com/codeartifact/latest/ug/python-configure.html

Is this documentation sufficient to indicate what would need to be altered, or something more specific on how to undo any changes made?

**Comment by gdj0nes** [comment]
Thanks for pointing me to that @kdaily. It might be helpful to have directions for removing the configuration in a separate place to increase the likelihood that a user finds that information.

**Comment by vishakha1812** [comment]
Hi @gdj0nes 
I am being prompted to login to aws codeartifact everytime I run `pip install`. Can you please guide me on how to remove this from my pip configuration for Mac?

**Comment by elenaehrlich** [comment]
I am having the error that pip is only looking to my codeartifact repo for packages. I am unable to install public packages, and get the following error:

ERROR: Could not find a version that satisfies the requirement statsmodels (from versions: none)
ERROR: No matching distribution found for statsmodels

**Comment by BranchofApp** [comment]
for those that are interested I have fixed the issue by running: ` pip config unset global.index-url`

**Comment by ravedappeport** [comment]
Additionally, it might be helpful to run `pip config list` first to see all configuration keys before running `pip config unset`
