### ISSUE TITLE
`S3` API behaves differently in HK region (ap-east-1)

### ISSUE THREAD

**Issue by kingkenmark** [aws/aws-cli#5445]
We try to use "aws s3 ls" to list all the objects in specific s3 path, on the same EC2 instance, it works for "s3://SYD-bucket/path" but doesn't work for "s3://HK-bucket/path" and return error:

**An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The ap-east-1 location constraint is incomp atible for the region specific endpoint this request was sent to.**

As a work around, we need to add "--region ap-east-1" to the command, then it works for "s3://HK-bucket/path". Alternatively, we can set the AWS_DEFAULT_REGION. For either way, we need to change quite a few existing scripts, so we really want to understand why does `S3` API behave differently in HK region? Is it a bug in boto3/aws cli?

**Comment by kdaily** [comment]
Hi @kingkenmark,

Sorry to hear of the trouble. I think you are experiencing a known issue. Please see this previous comment for a good description of what is happening, how to fix, and potential for improvement:

https://github.com/boto/boto3/issues/781#issuecomment-241916064

The difference in your case is that you've already created the bucket, so the region that was set when it was created is likely different than your configured default region.

If you would like this feature request, could you comment on that issue? I'll mark this as a duplicate and cross-link it to there. Thanks!
