### ISSUE TITLE
Typo in SNS docs

### ISSUE THREAD

**Issue by nerixim** [aws/aws-cli#5446]
Hi, thanks for your work :octocat: 

I found a typo in the SNS set-endpoint-attributes example (both in v1 and v2)
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sns/set-endpoint-attributes.html#examples
(get -> set)

> The following **set**-endpoint-attributes example disables the specified platform application endpoint.
aws sns **get**-endpoint-attributes \
snip...

**Comment by kdaily** [comment]
Thanks for finding and reporting that, @nerixim! I can pass this on to our docs team.
