### ISSUE TITLE
Support for specifying Ubuntu platform for AWS Cloud9

### ISSUE THREAD

**Issue by RyanQuey** [aws/aws-cli#5450]
**Is your feature request related to a problem? Please describe.**
I want to use Ubuntu 18 rather than the default AWS Linux for my Cloud9 instances.

**Describe the solution you'd like**
Can I do this using the CLI? I would like to add a flag e.g., `--platform ubuntu18-lts`

**Describe alternatives you've considered**
The only other alternative I have thought others to use the GUI directly.

**Comment by kdaily** [comment]
Hi @RyanQuey, this is a known feature request, and it's noted in the getting started guide here:

https://docs.aws.amazon.com/cloud9/latest/user-guide/tutorial-create-environment-cli-step1.html

> Currently, you cannot use the AWS CLI to create an Ubuntu Server-based EC2 environment—only Amazon Linux. Support for Ubuntu Server is expected in the future.

In the [general EC2 environment documentation](https://docs.aws.amazon.com/cloud9/latest/user-guide/create-environment-main.html#create-environment-code), it extends that caveat to all AWS SDKs and the CLI - this feature would need to be implemented by the Cloud9 team.

I can't provide a date as to when this would be implemented though, but I have sent your feature request on to the Cloud9 team. Thanks again!
