### ISSUE TITLE
awsebcli 3.18.2 incompatible with boto3 1.14.37 (both latest)

### ISSUE THREAD

**Issue by matschaffer** [aws/aws-cli#5457]
Seems to work okay if you don't use the 2020 resolver, but if you do you get this conflict.

```
 The conflict is caused by:
      awsebcli 3.18.2 depends on botocore<1.16 and >=1.15
      boto3 1.14.37 depends on botocore<1.18.0 and >=1.17.37
  
  To fix this you could try to:
  1. loosen the range of package versions you've specified
  2. remove package versions to allow pip attempt to solve the dependency conflict
  
  ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by matschaffer** [comment]
For the time being it looks like I can lock boto3 back to 1.12 which had a compatible botocore constraint.

```
boto3==1.12.49
```

**Comment by kdaily** [comment]
Hi! This is an issue for the AWS EB CLI, and it looks like it's been mentioned here already:

https://github.com/aws/aws-elastic-beanstalk-cli/issues/38

If this looks right, I would comment there and request assistance from that team. Thanks!

**Comment by matschaffer** [comment]
Ah, thanks! Googling led me to https://github.com/aws/aws-cli/issues/3557 so I assumed both packages were fed from this repo. Sorry about that 🙏
