### ISSUE TITLE
Secrets Manager create-secret is missing information for the --tags option

### ISSUE THREAD

**Issue by bwcwestlund** [aws/aws-cli#5459]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Ubuntu 18.04 LTS via Windows Subsystem for Linux on Windows 10
aws-cli/2.0.14 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev18

**Describe the question**
[https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/tag-resource.html](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/create-secret.html)
The documentation for `aws secretsmanager create-secret` is missing an additional method of supplying the tags options. It currently only lists the JSON method of writing tag information but the API seems to support the alternative method described on the [Secrets Manager tag-resource page](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/tag-resource.html):
`--Tags Key="Key1",Value="Value1",Key="Key2",Value="Value2"[,…]`

Example working command:
`aws secretsmanager create-secret --name "MySecret" --secret-string "12345" --description
 "description goes here" --region us-west-1 --tags Key="Favorite Food",Value="Cookie" Key="Favorite Color",Value="Gold"`

It would also be helpful if a second example create-secret command was included in the documentation that includes this method of writing tags.

NOTE: while the tag-resource page lists the alternate way to write tags, there is a small bug with the way the page is currently written. [I opened this issue to hopefully fix that](https://github.com/aws/aws-cli/issues/5458).

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Thanks for catching that, I'll pass this on to the Secrets Manager team.

**Comment by stobrien89** [comment]
Closing, as it appears documentation has been updated to reflect shorthand syntax.

**Comment by RohitKasyap-45** [comment]
Thanks a lot. It worked. Hope AWS docs update the examples with all the options available for a CLI command.
