### ISSUE TITLE
S3 presign cli allow url generated more than 7 days (--expires-in greater than 604800)

### ISSUE THREAD

**Issue by kpx-dev** [aws/aws-cli#5464]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
aws s3 presign --expires-in 604801 will allow url to be generated. But when view the url, S3 will said that url is not valid as it's expiring in more than 7 days. 

Error message: 
X-Amz-Expires must be less than a week (in seconds); that is, the given X-Amz-Expires must be less than 604800 seconds

**SDK version number**
aws --version
aws-cli/2.0.17 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev21

**Platform/OS/Hardware/Device**
macOS Catalina 10.15.6

**To Reproduce (observed behavior)**
Run: aws s3 presign --expires-in 604801 s3://any-object

**Expected behavior**
When generate expires-in greater than 604800, it should reports error and not generate any url. 

**Logs/output**
N/A

**Additional context**
N/A

**Comment by kdaily** [comment]
Looking into this, thanks!

**Comment by kdaily** [comment]
Hi @kienpham2000, this maximum time limit is specific to S3 presigned URLs with the SigV4 signing method. Previously (SigV2) a presigned URL could be valid indefinitely. I'm going to mark this as a documentation issue to note the maximum value in the client documentation that is also present in the [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/archive-sigv4-query-string-auth.html).

**Comment by kienpham2000** [comment]
Thanks @kdaily , didn't know that :).

**Comment by tim-finnigan** [comment]
Closing this as the PR mentioned above was merged.
