### ISSUE TITLE
aws cloudformation package support for AWS::ECS::TaskDefinition EnvironmentFile

### ISSUE THREAD

**Issue by michaelwittig** [aws/aws-cli#5479]
**Is your feature request related to a problem? Please describe.**
`AWS::ECS::TaskDefinition` finally supports adding [EnvironmentFile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-environmentfile.html) to a container definition. It would be great if we could upload a file to S3 and replace `Value` with the s3 object ARN with `aws cloudformation package`. 

**Describe the solution you'd like**
Allow us to specify a file path in `Value` that is uploaded to S3 and turned into an S3 object ARN.

**Describe alternatives you've considered**
The workaround is to upload the files manually `aws s3 cp` and pass the S3 Object ARN via a parameter into the stack.

**Comment by kdaily** [comment]
Thanks for the feature request, @michaelwittig. I'll raise this with the CloudFormation team. I can't provide an ETA on a response.

**Comment by tim-finnigan** [comment]
Checking in as this issue hasn't had any activity in a while. We have been advised to refer uses to the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) and the [sam package](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) command going forward. Are you able to accomplish what you're trying to do with the SAM CLI?
