### ISSUE TITLE
AWS::Serverless::StateMachine DefinitionUri support for cloudformation package

### ISSUE THREAD

**Issue by ilyasotkov** [aws/aws-cli#5480]
The feature works with SAM CLI but not `aws cloudformation package`

**Comment by kdaily** [comment]
Hi @ilyasotkov,

Thanks for the feature request. I just want to clarify what you're asking for. It seems that the `aws cloudformation package` supports the feature in the title of this issue:

> This command can upload local artifacts referenced in the following places:
> ...
> DefinitionS3Location property for the AWS::StepFunctions::StateMachine resource

I do see that `AWS::Serverless::StateMachine` does not have this support.

**Comment by ilyasotkov** [comment]
@kdaily Turns out I failed to upgrade AWS CLI to the latest version when trying to use the feature, and I've now re-tested it and can confirm it that it works with `AWS::StepFunctions::StateMachine`.

I've changed the issue title to the only include the part relating to [`AWS::Serverless::StateMachine`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html)

**Comment by justindho** [comment]
#5576 has been merged, which resolves this issue.
