### ISSUE TITLE
No v2 on PyPi?

### ISSUE THREAD

**Issue by arcivanov** [aws/aws-cli#5489]
Release history on PyPi shows no v2 are published. Is that intentional?

![image](https://user-images.githubusercontent.com/5355666/90882039-45cf8f80-e379-11ea-833e-71a3f3edcaad.png)

**Comment by kimmoahokas** [comment]
Yep, that is intentional. Reasoning an longer discussion in https://github.com/aws/aws-cli/issues/4947

**Comment by arcivanov** [comment]
@kimmoahokas thanks! An incredibly puzzling and ... khmmm... _unwise_ decision by the maintainers.
