### ISSUE TITLE
tag filters not working correctly for `aws deploy list-on-premises-instances --tag-filters`

### ISSUE THREAD

**Issue by adespain** [aws/aws-cli#5498]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When I try to find instances with specific tags it returns items that shouldn't be listed.
**SDK version number**
aws-cli/1.18.34
**Platform/OS/Hardware/Device**
What are you running the cli on?
ubuntu 16.04.7
**To Reproduce (observed behavior)**
Steps to reproduce the behavior
```
aws deploy list-on-premises-instances --tag-filters Key=Name,Value=cmsp-codepipeline-staging,Type=KEY_AND_VALUE
{
    "instanceNames": [
        "cmsp-prod1", 
        "cmsp-stage1"
    ]
}
```

**Expected behavior**
I should only see cmsp-stage1 as the host with the cmsp-codepipeline-staging tag however both prod and stage hosts are showing up.

when I list tags for each one I get the following:

```
aws deploy list-tags-for-resource --resource-arn arn:aws:codedeploy:us-west-2:XXXXXXXXXXXX:instance/cmsp-stage1_P4Cy9ZJ1nW
{
    "Tags": [
        {
            "Value": "cmsp-codepipeline-staging", 
            "Key": "Name"
        }
    ]
}
```

```
aws deploy list-tags-for-resource --resource-arn arn:aws:codedeploy:us-west-2:XXXXXXXXXXXX:instance/cmsp-prod1_rEKFFZyjk1
{
    "Tags": [
        {
            "Value": "cmsp-codepipeline-production", 
            "Key": "Name"
        }
    ]
}
```

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by adespain** [comment]
I have tried using aws cli version 1.18.127 as well and it still returns both instances as having the staging tag but should only return the one...

**Comment by kdaily** [comment]
Hi @adespain, sorry to hear you're having trouble. I edited your comment to remove your AWS account number.

If you change the `Type` to `VALUE_ONLY`, do you get the expected behavior?

**Comment by adespain** [comment]
@kdaily Doh thanks!  That was probably it, but I am unable to test it now because I already de-registered it and just used different tags as a work around.  Thanks for the response.
