### ISSUE TITLE
How to efficiently synchronize files from S3 bucket to local file share?

### ISSUE THREAD

**Issue by jzabroski** [aws/aws-cli#5500]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windows 10 Pro / Amazon Workspace

**Describe the question**
I am trying to implement a generic file comparison utility that efficiently checks for changes when synchronizing files.

In reading up on S3 object metadata and checksum approaches, I found the following articles that _seem_ internally inconsistent with one another:

1. [How can I check the integrity of an object uploaded to Amazon S3?](https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/)
    - _This link mentions a `Content-MD5` request header and then refers to the following link for clarification._
2. [AWS CLI S3 FAQ: Q: Does the AWS CLI validate checksums?](https://docs.aws.amazon.com/cli/latest/topic/s3-faq.html#q-does-the-aws-cli-validate-checksums)
3. [Amazon S3 System-defined object metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#SysMetadata)
    - This link does not mention `x-amz-content-sha256` as object metadata, implying to me that `x-amz-content-sha256` is data-in-transit only and is not data-at-rest object metadata.

After reading these links, I have the following questions:

1. While link 2 suggests `x-amz-content-sha256` is used to verify object metadata under certain circumstances, it doesn't _also_ say whether `Content-MD5` will be updated. Link 2 suggests Content-MD5 will always be updated.  Link 1 suggests that Content-MD5 will always be updated to a value that can be used to verify data integrity (because the PUT operation will fail if the checksum does not match).  What is the actual behavior?
2. Link 3 doesn't mention `x-amz-content-sha256` as system-defined object metadata, so is it just a data-in-transit header value and not persisted as data-at-rest object metadata?
3. What happens when set-up cross-region replication from `us-east-1` to one of the Signature Version 4 regions (e.g. `eu-central-1` and `ap-northeast-2`)?  If you're not updating Content-MD5 on every S3 API PUT call, then it seems like that might break Content-MD5 and make it so Content-MD5 lacks _non-repudiation property_.
4. Is there an SDK API call to know what signature version my region supports?
5. Teppen Services (consulting firm) [recommends using `ETag`](https://teppen.io/2018/06/23/aws_s3_etags/#why-arent-they-used-for-comparison) for faster file synchronization. Are S3 ETag values stable? AWS S3 etags are not prefixed with the canonical 'W/' "weak ETag" prefix, so I would expect ETag values to be stable and byte-for-byte identical.

**Logs/output**
n/a - not applicable

**Comment by kdaily** [comment]
Hi @jzabroski,

Since this is not a question or issue with the AWS CLI directly, this question would be better answered by an AWS S3 engineer. Please head over to the AWS Forums for S3. Thanks!

https://forums.aws.amazon.com/forum.jspa?forumID=24

**Comment by jzabroski** [comment]
@kdaily Respectfully, some parts of this question do interface directly with your team's documentation.  I will do as you suggest, but what team owns and is in charge of consistency of documentation if your documentation here:

> 2\. AWS CLI S3 FAQ: Q: Does the AWS CLI validate checksums?

disagrees or is worded in ways that seem inconsistent with other documentation?

**Comment by kdaily** [comment]
Hi @jzabroski,

To answer a one of your questions immediately, I referred to this document:

https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html.

Regarding the SDK API call to know what signature versions are supported in different regions, I don't think so. But the description here gives you the answer: 

> Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, AWS Regions created before January 30, 2014 will continue to support the previous protocol, Signature Version 2. Any new Regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those Regions must be made with Signature Version 4. For more information about AWS Signature Version 2, see Signing and Authenticating REST Requests in the Amazon Simple Storage Service Developer Guide.

I will look into your questions regarding the consistency, but I am not an S3 subject matter expert, so I may not be able to assist. That is why I suggested reaching an S3 engineer to get you the correct answers. The document referred above may provide you more details regarding the workings of S3. Thanks!

**Comment by jzabroski** [comment]
Thank you.  I did create a forum issue, as you suggested I do: https://forums.aws.amazon.com/thread.jspa?threadID=327752&tstart=0

**Comment by kdaily** [comment]
It is also important to note is that Sig V2 is being deprecated. As far as I'm aware, all [recent versions of SDKs and tools](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-move-to-Sig4), including the AWS CLI, use Sig V4 in all regions. Other useful links regarding sig V2 deprecation:

- https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version
- https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/

Reviewing the links you sent definitely raises some concerns about the documentation consistency and coherence. For example, the AWS CLI always uses Sig V4, which is not accurately reflected in that document. I've marked this as a documentation issue, and will review it with our team as well as the S3 service team. 

Your other questions regarding the details of how the headers behave are best answered using the forum post.

Thanks again for your detailed notes.

**Comment by jzabroski** [comment]
Hi @kdaily 

No worries - thanks for re-opening it and doing this follow-up with me!  Much appreciated.  Super stoked to deliver a world class S3 integration!

**Comment by jzabroski** [comment]
By the way, my basic observation in my thread title stands - I couldn't find any document explicitly mentioning how to efficiently synchronize files.  A bunch of third party tools (rclone, s3cmd. [s3s3mirror](https://github.com/cobbzilla/s3s3mirror)) have their own ways, and people reverse engineer the ETag as well.  I think it would benefit the whole ecosystem to just document how to do it, although I acknowledge some people pride themselves on competitive advantage of knowing obscure things.  I'd rather all third party tools just agree with AWS S3 engineers on a canonical, safe, way to efficiently sync files.

**Comment by jzabroski** [comment]
@kdaily

> Reviewing the links you sent definitely raises some concerns about the documentation consistency and coherence. For example, the AWS CLI always uses Sig V4, which is not accurately reflected in that document. I've marked this as a documentation issue, and will review it with our team as well as the S3 service team.

It's interesting that you said that AWSCLI now use Signature Version 4, because the AWSSDK for .NET doesn't, according to the documentation here: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html#config-setting-aws-s3-usesignatureversion4

Quoting that document for posterity:
> By default, this setting is `false`, but signature version 4 may be used by default in some cases or with some regions. When the setting is true, signature version 4 will be used for all requests. Changes to this setting take effect only for new Amazon S3 client instances.
