### ISSUE TITLE
aws codeartifact cli does not allow package names with forward slash

### ISSUE THREAD

**Issue by jmorgancusick** [aws/aws-cli#5501]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
aws codeartifact does not alllow package names containing forward slash (/). However, that is a valid package name in codeartifact and is often used for npm packages in a particular domain.

**SDK version number**

~~~
$ aws --version
aws-cli/2.0.31 Python/3.7.3 Linux/5.3.0-59-generic botocore/2.0.0dev35
~~~

**Platform/OS/Hardware/Device**
What are you running the cli on?

~~~
$uname -a
Linux john-ThinkPad-X1-Carbon-6th 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~~~

**To Reproduce (observed behavior)**

* Create an npm project and in the ```package.json``` name it org/package
* ```npm publish``` the project to codeartifact
* try to run ```aws codeartifact list-package-versions``` on org/package

**Expected behavior**
Package versions of org/package should be printed

**Logs/output**
~~~
An error occurred (ValidationException) when calling the ListPackageVersions operation: 1 validation error detected: Value '@org/package' at 'packageName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^!#/\s]+
~~~

**Additional context**

**Comment by kdaily** [comment]
Hi @jmorgancusick, I see that the regular expression match for the package name does not allow slashes. The NPM package name validator (https://www.npmjs.com/package/validate-npm-package-name) shows that slashes are allowed. I'll raise this to the CodeArtifact team, as this restriction is handled by the CodeArtifact API, not the AWS CLI. I can't give you an ETA as to when this might be addressed.

**Comment by zobzn** [comment]
try to use namespace option
```bash
aws codeartifact list-package-versions --namespace org --package package ...
```

**Comment by joechchung** [comment]
We can't do this with "@" signs either too, could this be raised to fix please?

**Comment by bbcawodu** [comment]
I am having the same issue with get-package-version-asset and package names that have a forward slash. Is there a resolution to this?

**Comment by bbcawodu** [comment]
nevermind. it does indeed work with the namespace argument

**Comment by kdaily** [comment]
P39204887

**Comment by guoliang** [comment]
Looks like my case in #6125 could also be resolved by supplying `--namespace` option. But with a tweak, since my package begins with `@types` I had to take out `@` for it to work.

**Comment by kdaily** [comment]
Hi all, as @zobzn and @guoliang have noted, using the `--namespace` option is the current solution here. Here is the documentation page that describes this behavior:

https://docs.aws.amazon.com/codeartifact/latest/ug/list-packages.html#list-packages-npm

Thanks both of you for identifying this. I confirmed this with the CodeArtifact team as well. They are considering some enhancements to help this scenario, from automatically parsing the syntax with the namespace as part of the package name, or a better error message letting you know to use the `--namespace` argument. I don't have any information on when or if either of those things might be implemented.

**Comment by liam102** [comment]
> try to use namespace option
> 
> ```shell
> aws codeartifact list-package-versions --namespace org --package package ...
> ```

This is correct. Tested with my package `@myorg/mypackage` which translates to `--namespace myorg --package mypackage`
