### ISSUE TITLE
EMR: fail to set step-concurrency-level when creating a cluster

### ISSUE THREAD

**Issue by jane212** [aws/aws-cli#5502]
Hi,

I found the documentation indicated that we can set the step-concurrency-level to more than 1 during creating a cluster.
[https://docs.aws.amazon.com/emr/latest/ManagementGuide/add-step-cli.html](url)

> By default, the step concurrency level is 1. You can set the step concurrency level by using the StepConcurrencyLevel parameter when you create a cluster.

I also found this option is listed in create-cluster command.
[https://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html](url)

> --step-concurrency-level (integer) This command specifies the step concurrency level of the cluster.Default is 1 which is non-concurrent.

However, when I use it in my create-cluster command, it returns error.

> Unknown options: --StepConcurrencyLevel,2

The output screenshot:
![emr cli](https://user-images.githubusercontent.com/14044922/91648947-e3365d80-ea22-11ea-91f2-2557fb362667.png)

Please guide me how to add this option. Thanks.

**Comment by kdaily** [comment]
Hi @jane212,

Thanks for reporting! I'm looking into this. I can see a discrepancy that the parameter is listed in the details section, but not in the overview.

**Comment by kdaily** [comment]
While I follow up on that, it's still odd that you get back the error that you do (with a comma in between the parameter name and the value). Can you double check your command and/or provide a minimal command that gives the same error to verify you aren't missing a quotation mark or some other formatting? Thanks!
