### ISSUE TITLE
Quicksight create-analysis not applying permissions from json file when using --cli-input-json

### ISSUE THREAD

**Issue by SybaseWrangling** [aws/aws-cli#5504]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When ever I attempt to run the new command `aws quicksight create-analysis.....` it appears that the permission options that I supply in the appropriate json file are not being applied.

**SDK version number**
aws-cli/2.0.41 Python/3.7.7 

**Platform/OS/Hardware/Device**
Windows/10 exe/AMD64

**To Reproduce (observed behavior)**
The command I have been running is as follows:
`aws quicksight create-analysis --aws-account-id 9999999999 --cli-input-json file://my_file.json --region ap-southeast-2`

Example of the json:
```{
    "AwsAccountId": "9999999999",
    "AnalysisId": "My-New-Analysis",
    "Name": "My New Analysis",
    "Permissions": [
        {
            "Principal": "arn:aws:quicksight:ap-southeast-2:9999999999:user/default/MyRole/myuser",
            "Actions": [
                "quicksight:RestoreAnalysis",
                "quicksight:UpdateAnalysisPermissions",
                "quicksight:DeleteAnalysis",
                "quicksight:DescribeAnalysisPermissions",
                "quicksight:QueryAnalysis",
                "quicksight:DescribeAnalysis",
                "quicksight:UpdateAnalysis"
            ]
        }
    ],
    "SourceEntity": {
        "SourceTemplate": {
            "DataSetReferences": [
                {
                    "DataSetPlaceholder": "ds-1",
                    "DataSetArn": "arn:aws:quicksight:ap-southeast-2:9999999999:dataset/data-set-a"
                },
                {
                    "DataSetPlaceholder": "ds-2",
                    "DataSetArn": "arn:aws:quicksight:ap-southeast-2:9999999999:dataset/data-set-b"
                }
            ],
            "Arn": "arn:aws:quicksight:ap-southeast-2:8888888888:template/My-Template"
        }
    },
    "Tags": [
        {
            "Key": "Environment",
            "Value": "Development"
        },
        {
            "Key": "Product",
            "Value": "My Product"
        },
        {
            "Key": "Customer",
            "Value": "My Customer"
        }
    ]
}```


**Expected behavior**
Appropriate permissions should be applied to the analysis.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
If I run `aws quicksight update-analysis-permissions.....` with the appropriate string using the option `--grant-permissions` and the appropriate string `Principal=string,Actions=string,string ...` I can successfully update the permissions

**Comment by kdaily** [comment]
Hi @SybaseWrangling,

I think I'll need to see sanitized (remove account identifiers, etc) debug logs (run the command with `aws --debug`). Can you please provide them? Thanks!

**Comment by SybaseWrangling** [comment]
Hi @kdaily ,
Find attached log.  Hope it gives you enough info.
[debug.txt](https://github.com/aws/aws-cli/files/5171913/debug.txt)

Just for your reference, this is the response from `aws quicksight describe-analysis-permissions` when checking the above permissions:

`{
    "Status": 200,
    "AnalysisId": "my-analysis-id",
    "AnalysisArn": "arn:aws:quicksight:ap-southeast-2:999999999999:analysis/my-analysis-id",
    "Permissions": [],
    "RequestId": "<request id>"
}`

**Comment by tintinsnowy** [comment]
I got similar problem. The create_analysis() function seems to not work at all. Because when I put invalid principals as config, it still can generate analysis while I try to do the same to create_template() it reminds me of the wrong principals and actions

**Comment by kdaily** [comment]
Hi @SybaseWrangling and @tintinsnowy,

Does it work properly if you specify the permissions using the `--permissions` parameter to `aws quicksight create-analysis`? It looks to me like the permissions were read from the JSON file fine, they're being passed in the request:

```
2020-09-04 08:56:05,534 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateAnalysis) with params: {'url_path': '/accounts/999999999999/analyses/my-analysis-id', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.0.41 Python/3.7.7 Windows/10 exe/AMD64 command/quicksight.create-analysis'}, 'body': b'{"Name": "My Analysis", "Permissions": [{"Principal": "arn:aws:quicksight:ap-southeast-2:999999999999:user/default/My-Role/MyUser", "Actions": ["quicksight:UpdateAnalysisPermissions", "quicksight:DeleteAnalysis", "quicksight:DescribeAnalysisPermissions", "quicksight:QueryAnalysis", "quicksight:DescribeAnalysis"]}], "SourceEntity": {"SourceTemplate": {"DataSetReferences": [{"DataSetPlaceholder": "data-holder-metrics", ....
```

**Comment by apatlori** [comment]
We are working on deploying a fix for this bug. Until then, as a work-around, please use the [_UpdateAnalysisPermissions_](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateAnalysisPermissions.html) API.

**Comment by tintinsnowy** [comment]
updateAnalysisPermission works for me 👯

**Comment by tintinsnowy** [comment]
> Hi @SybaseWrangling and @tintinsnowy,
> 
> Does it work properly if you specify the permissions using the `--permissions` parameter to `aws quicksight create-analysis`? It looks to me like the permissions were read from the JSON file fine, they're being passed in the request:
> 
> ```
> 2020-09-04 08:56:05,534 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateAnalysis) with params: {'url_path': '/accounts/999999999999/analyses/my-analysis-id', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.0.41 Python/3.7.7 Windows/10 exe/AMD64 command/quicksight.create-analysis'}, 'body': b'{"Name": "My Analysis", "Permissions": [{"Principal": "arn:aws:quicksight:ap-southeast-2:999999999999:user/default/My-Role/MyUser", "Actions": ["quicksight:UpdateAnalysisPermissions", "quicksight:DeleteAnalysis", "quicksight:DescribeAnalysisPermissions", "quicksight:QueryAnalysis", "quicksight:DescribeAnalysis"]}], "SourceEntity": {"SourceTemplate": {"DataSetReferences": [{"DataSetPlaceholder": "data-holder-metrics", ....
> ```

no, not really I used the SDK, got the same issue

**Comment by kdaily** [comment]
@tintinsnowy - as @apatlori notes this is an API bug. Once it's addressed your issue in `botocore` should be resolved as well.

**Comment by tintinsnowy** [comment]
> @tintinsnowy - as @apatlori notes this is an API bug. Once it's addressed your issue in `botocore` should be resolved as well.

yep, I emailed hime already, thanks

**Comment by SybaseWrangling** [comment]
> We are working on deploying a fix for this bug. Until then, as a work-around, please use the [_UpdateAnalysisPermissions_](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateAnalysisPermissions.html) API.

OK, so it is a bug?

FYI, I did use the updateAnalysisPermission API when building my solution.

**Comment by kdaily** [comment]
Hi @SybaseWrangling, yes it is a bug. It's being addressed in the QuickSight service, which separate from the AWS CLI. You would experience this issue using other AWS SDKs (as noted by another user here with `boto3`, the Python SDK). I will leave this issue open to track it's resolution.

**Comment by apatlori** [comment]
This bug has been fixed and deployed. Please feel free to reopen in cases of anyone running into this issue.
