### ISSUE TITLE
aws s3 sync - Website-Redirect-Location not syncing

### ISSUE THREAD

**Issue by rajesh-kumar-c** [aws/aws-cli#5505]
Hi Team,

I have tried syncing from Bucket A to Bucket B using below command. Data & Metadata is syncing, but the "Website-Redirect-Location" metadata in Bucket A objects is not available in Bucket B objects after sync.

aws s3 sync s3://aaaa s3://bbbb

Please suggests a way to sync along with the "Website-Redirect-Location" metadata.

Thanks, in advance.

**Comment by brbernardo** [comment]
I believe that you have not written the Website-Redirect-Location rules in an xml file and therefore you will need to reconfigure the bucket panel.

In order not to have this need in the future, I recommend creating the xml file with the redirection rules for future migrations.

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by brbernardo** [comment]
> Hi Team,
> 
> I have tried syncing from Bucket A to Bucket B using below command. Data & Metadata is syncing, but the "Website-Redirect-Location" metadata in Bucket A objects is not available in Bucket B objects after sync.
> 
> aws s3 sync s3://aaaa s3://bbbb
> 
> Please suggests a way to sync along with the "Website-Redirect-Location" metadata.
> 
> Thanks, in advance.

I believe that you have not written the Website-Redirect-Location rules in an xml file and therefore you will need to reconfigure the bucket panel.

In order not to have this need in the future, I recommend creating the xml file with the redirection rules for future migrations.

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by brbernardo** [comment]
I believe that you have not written the Website-Redirect-Location rules in an xml file and therefore you will need to reconfigure the bucket panel.

In order not to have this need in the future, I recommend creating the xml file with the redirection rules for future migrations.

https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by kdaily** [comment]
Hi @rajesh-kumar-c, are these files large enough to be using a multipart copy? If that is the case, due to API limitations, the AWS CLI v1 may not copy over all metadata. If you use the AWS CLI v2, this is addressed and all metadata will be copied.
