### ISSUE TITLE
Connect Github source code to Docker Hub

### ISSUE THREAD

**Issue by kmturley** [aws/aws-cli#5507]
**Is your feature request related to a problem? Please describe.**
We are looking at using the aws-cli as part of our CI/CD pipelines. As part of this process it's normal to audit the Dockerfile to ensure it's safe/secure and follows best practices. When going to https://hub.docker.com/r/amazon/aws-cli there is no source code and therefor we are unable to see how the Dockerfile was created.

**Describe the solution you'd like**
If you look at the equivalent Google cli tool, you see they have connected the git repo, in order to see the Docker source code:
https://hub.docker.com/r/google/cloud-sdk. This is ideal as you can click through to view the file: https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/Dockerfile

**Describe alternatives you've considered**
I searched through https://github.com/aws/aws-cli looking for the Dockerfile, no matches. Tried searching GitHub for the code, could not find it.

**Additional context**
An open-source Dockerfile allows inspecting for security and performance purposes. It also allow the community to create pull requests to support new features in Docker.

**Comment by kdaily** [comment]
Hi @kmturley, the AWS CLI Docker container image is only built for v2. You can find the Dockerfile on the v2 branch, here:

https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile

**Comment by kmturley** [comment]
Thanks for linking to the Dockerfile, I guess the GitHub repo search only checked the master branch!

The feature request still stands...to link the Docker Hub page to the source somehow, which saves developers time when looking for the source code.
