### ISSUE TITLE
Provide a pypi package from AWS CLI v2

### ISSUE THREAD

**Issue by vemel** [aws/aws-cli#5515]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

Hello!

Thank you for AWS CLI v2! It is way better in production than v1. However, I think it would be better if it would be possible to install it from pip, just as before.

I created a very simple dependency-free [awscliv2](https://pypi.org/project/awscliv2/) package that mimics user experience with v1, while using docker image underneath.

Let me know if you find it useful. Probably, you can release something similar, so feel free to use it.

Regards, Vlad.

**Comment by kdaily** [comment]
Hi @vemel, thanks for the information and this interesting implementation! I don't think we're going to explore this as an option for distributing the CLI. I see that you've linked this to the other issue regarding availability of V2 on PyPI, so any conversation regarding it can be had over there. Thanks!
