### ISSUE TITLE
fails to install over linuxbrew

### ISSUE THREAD

**Issue by andreineculau** [aws/aws-cli#5522]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I believe a bug that I reported on linuxbrew (homebrew for linux) might not be related to linuxbrew but to awscli's python requirements and/or pip, so I'm posting a reference here.

See bug report and steps to reproduce here https://github.com/Homebrew/linuxbrew-core/issues/21062

**SDK version number**
2.0.44

**Platform/OS/Hardware/Device**
Ubuntu 18.04 with linuxbrew

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

```
docker run --rm -it homebrew/ubuntu18.04
brew install awscli
which aws # aws not found

# temporary workaround is to install again
brew uninstall awscli && brew install awscli
which aws # aws found
```

**Expected behavior**

I expect `awscli` to be installed correctly via homebrew.

**Logs/output**
N/A

**Additional context**
N/A

**Comment by kdaily** [comment]
Hi @andreineculau, the Homebrew formula for the AWS CLI is not managed by AWS, but by the Homebrew maintainers. I confirmed that using the [AWS CLI V2 installation guide](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html), the command is immediately available inside the container instance.
