### ISSUE TITLE
aws rds-data execute-statement against an Oracle instance

### ISSUE THREAD

**Issue by tr-patrick** [aws/aws-cli#5524]
quick question:

Is it possible to use the aws cli command-line to run a sql query against an Oracle database like the following?
aws rds-data execute-statement --resource-arn resource-id --secret-arn secret-an-id --sql "select * from dual" 

any example or how to?

thank you
Patrick

**Comment by kdaily** [comment]
Hi @tr-patrick, I'm not aware, but I would suggest asking this in the RDS AWS Forum:

https://forums.aws.amazon.com/forum.jspa?forumID=60

Thanks!
