### ISSUE TITLE
aws cli with shell script: upload failed: Unable to locate credentials

### ISSUE THREAD

**Issue by siddharthcb** [aws/aws-cli#5526]
i am trying to automate file update on s3 using aws cli. when i manually run the code ```aws s3 cp /home/abc/lampdata.json s3://lamp``` it is working completely fine but in shell script file it is giving me an error

#!/bin/sh 
```exec bash -c 'AWS_CONFIG_FILE=/root/.aws/config aws s3 cp /home/abc/lampdata.json s3://lamp' &```

> upload failed: ../../abc/lampdata.json to s3://lamp/lampdata.json Unable to locate credentials

though i have configured using aws configure. is this some problem with the shell script?

**Comment by siddharthcb** [comment]
@kdaily Thanks for the reply. i am running this command as a root user.
this is what i got when debug was turned on
> upload failed: ../../abc/lampdata.json to s3://lamp/lampdata.json Unable to locate credentials
Sep 11 09:33:25 F.sh[11979]: 2020-09-11 09:33:25,322 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result

**Comment by kdaily** [comment]
Hi @siddharthcb,

I'll need to see more of the debug output, specifically the section that notes where it is trying to find credentials. This command can also indicate what's happening (would need to be run inside the same script environment as the command you are running):

https://docs.aws.amazon.com/cli/latest/reference/configure/list.html

**Comment by siddharthcb** [comment]
hi @kdaily 

i tried debugging the entire error code but i could not since i am running it in systemcd service.
maximum i could get was the one i sent above using `journalctl -u myservice`

**Comment by kdaily** [comment]
Hi @siddharthcb,

```
exec bash -c 'AWS_CONFIG_FILE=/root/.aws/config aws configure list'
```

Though if you only get one line of output then this won't help.

A few questions for you:

1. Where are you expecting to find a credentials file as? Which user did you use to run `aws configure`?
1. Can you run this outside of `systemd` as root to diagnose why you aren't finding a credential file?

Thanks!

**Comment by siddharthcb** [comment]
hi @kdaily 
so i was able to debug this time.
and the error
`endpoint URL: "http://169.xxx.xxx.xxx/latest/meta-data/iam/security-credentials/"
UG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
UG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f7b68dd90>
UG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f7b6c0598>
UG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f7b6c0378>
DEBUG - Setting s3 timeout as (60, 60)
s.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
EBUG - Acquiring 0
er.tasks - DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f7a2de550>}) about to wait for the following futures []
er.tasks - DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f7a2de550>}) done waiting for dependent futures
er.tasks - DEBUG - Executing task UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f7a2de550>}) with kwargs {'client': <botocore.client.S3 object at 
er.futures - DEBUG - Submitting task PutObjectTask(transfer_id=0, {'bucket': 'lamp', 'key': 'lampdata.json', 'extra_args': {'ContentType': 'application/json'}}) to executor <s3transfer.futures.BoundedEx
er.utils - DEBUG - Acquiring 0
er.tasks - DEBUG - PutObjectTask(transfer_id=0, {'bucket': 'lamp', 'key': 'data.json', 'extra_args': {'ContentType': 'application/json'}}) about to wait for the following futures []
er.utils - DEBUG - Releasing acquire 0/None
er.tasks - DEBUG - PutObjectTask(transfer_id=0, {'bucket': 'lamp', 'key': 'data.json', 'extra_args': {'ContentType': 'application/json'}}) done waiting for dependent futures
er.tasks - DEBUG - Executing task PutObjectTask(transfer_id=0, {'bucket': 'lamp', 'key': 'data.json', 'extra_args': {'ContentType': 'application/json'}}) with kwargs {'client': <botocore.client.S3 o
.hooks - DEBUG - Event provide-client-params.s3.PutObject: calling handler <function base64_decode_input_blobs at 0x7f7a880048>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7f7b631a60>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7f7b62dea0>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x7f7b632378>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7f7b62de18>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f7a54ff98>>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f7a5112e8>>
.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x7f7b62dc80>
.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7f7b8647b8>
.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7f7b6311e0>
.handlers - DEBUG - Adding expect 100 continue header to request.
.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f7a54ff98>>
.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x7f7b632488>
.endpoint - DEBUG - Making request for OperationModel(name=PutObject) with params: {'url_path': '/lamp/data.json', 'query_string': {}, 'method': 'PUT', 'headers': {'Content-Type': 'application/json'
.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <function signal_not_transferring at 0x7f7ae84f28>
.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f7a54fb00>>
.hooks - DEBUG - Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x7f7b62db70>
.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f7a511358>>
.utils - DEBUG - Defaulting to S3 virtual host style addressing with path style addressing fallback.
.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.amazonaws.com/uvlamp/lampdata.json
.utils - DEBUG - URI updated to: https://uvlamp.s3.amazonaws.com/data.json
er.tasks - DEBUG - Exception raised.

edentials
er.utils - DEBUG - Releasing acquire 0/None
data.json Unable to locate credentials
s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.`

**Comment by siddharthcb** [comment]
> Hi @siddharthcb,
> 
> ```
> exec bash -c 'AWS_CONFIG_FILE=/root/.aws/config aws configure list'
> ```
> 
> Though if you only get one line of output then this won't help.
> 
> A few questions for you:
> 
> 1. Where are you expecting to find a credentials file as? Which user did you use to run `aws configure`?
> 2. Can you run this outside of `systemd` as root to diagnose why you aren't finding a credential file?
> 
> Thanks!

coming to your questions.
1. ```aws configure list``` says the config file is stored in /.aws/config and i am running aws configure as a normal user.
2. when i am running sudo aws configure list outside systemd, it is giving me my credentials as entered. no error.

**Comment by kdaily** [comment]
@siddharthcb,

Your credentials are not stored in the config file (usually), they are in a separate `credentials` file. For example, when I run this command as root, I get the following:

```
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************ABCD shared-credentials-file
secret_key     ****************DEFG shared-credentials-file
    region                us-west-2      config-file    /root/.aws/config
```

You would need to run `aws configure` as root in order to generate the credentials in the right pace to run the script as root. Or, you can move the file you created (probably at `~/.aws/credentials`) to `/root/.aws/` for it to be found when running as root. You could also set up your `systemd` configuration to run as the user you ran `aws configure` as, if for example you were using a dedicated account for this service.
