### ISSUE TITLE
Why does stage name "Stag"  change to "Stage" and "Prod" after deploy.

### ISSUE THREAD

**Issue by mikezang** [aws/aws-cli#5540]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
aws-cli/2.0.5 Python/3.7.5 Windows/7 botocore/2.0.0dev9

**Describe the question**
I run `sam init`, `sam build` to create template as below:
> AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "sam-app\nSample SAM Template for sam-app\n"
Globals:
　Function:
　Timeout: 3
Resources:
　HelloWorldFunction:
　　Type: AWS::Serverless::Function
　　Properties:
　　　CodeUri: s3://my-stag-upload-bucket/14f3e1c87109d66b1eb64d4ad33077ae
　　　Handler: app.lambda_handler
　　　Runtime: python3.8
　　　Events:
　　　HelloWorld:
　　　　Type: Api
　　　　Properties:
　　　　　Path: /hello
　　　　　Method: get
Outputs:
　HelloWorldApi:
　　Description: API Gateway endpoint URL for Prod stage for Hello World function
　　Value:
　　　Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stag/hello/
　HelloWorldFunction:
　　Description: Hello World Lambda Function ARN
　　Value:
　　　Fn::GetAtt:
　　　- HelloWorldFunction
　　　- Arn
　HelloWorldFunctionIamRole:
　　Description: Implicit IAM Role created for Hello World function
　　Value:
　　　Fn::GetAtt:
　　　- HelloWorldFunctionRole
　　　- Arn

Then I run `aws   --no-verify-ssl cloudformation package --template-file   .aws-sam\build\template.yaml --output-template-file serverless-output.yaml   --s3-bucket my-stag-upload-bucket` and `aws --no-verify-ssl cloudformation deploy --template-file serverless-output.yaml --stack-name helloWorld --capabilities CAPABILITY_IAM`, and I found the processed template as below:

> {
　"AWSTemplateFormatVersion": "2010-09-09",
　"Outputs": {
　　"HelloWorldApi": {
　　　"Description": "API Gateway endpoint URL for Prod stage for Hello World function",
　　　"Value": {
　　　　"Fn::Sub": "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stag/hello/"
　　　}
　　},
　　"HelloWorldFunctionIamRole": {
　　　"Description": "Implicit IAM Role created for Hello World function",
　　　"Value": {
　　　　"Fn::GetAtt": [
　　　　　"HelloWorldFunctionRole",
　　　　　"Arn"
　　　　]
　　　}
　　},
　　"HelloWorldFunction": {
　　　"Description": "Hello World Lambda Function ARN",
　　　"Value": {
　　　　"Fn::GetAtt": [
　　　　　"HelloWorldFunction",
　　　　　"Arn"
　　　　]
　　　}
　　}
　},
　"Description": "sam-app\nSample SAM Template for sam-app\n",
　"Resources": {
　　"HelloWorldFunctionHelloWorldPermissionProd": {
　　　"Type": "AWS::Lambda::Permission",
　　　"Properties": {
　　　　"Action": "lambda:InvokeFunction",
　　　　"Principal": "apigateway.amazonaws.com",
　　　　"FunctionName": {
　　　　　"Ref": "HelloWorldFunction"
　　　　},
　　　　"SourceArn": {
　　　　　"Fn::Sub": [
　　　　　　"arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/hello",
　　　　　　{
　　　　　　　"__Stage__": "*",
　　　　　　　"__ApiId__": {
　　　　　　　　"Ref": "ServerlessRestApi"
　　　　　　　}
　　　　　　}
　　　　　]
　　　　}
　　　}
　　},
　　"HelloWorldFunctionRole": {
　　　"Type": "AWS::IAM::Role",
　　　"Properties": {
　　　　"AssumeRolePolicyDocument": {
　　　　　"Version": "2012-10-17",
　　　　　"Statement": [
　　　　　　{
　　　　　　　"Action": [
　　　　　　　　"sts:AssumeRole"
　　　　　　　],
　　　　　　　"Effect": "Allow",
　　　　　　　"Principal": {
　　　　　　　　"Service": [
　　　　　　　　　"lambda.amazonaws.com"
　　　　　　　　]
　　　　　　　}
　　　　　　}
　　　　　]
　　　　},
　　　　"ManagedPolicyArns": [
　　　　　"arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
　　　　],
　　　　"Tags": [
　　　　　{
　　　　　　"Value": "SAM",
　　　　　　"Key": "lambda:createdBy"
　　　　　}
　　　　]
　　　}
　　},
　　"ServerlessRestApiProdStage": {
　　　"Type": "AWS::ApiGateway::Stage",
　　　"Properties": {
　　　　"DeploymentId": {
　　　　　"Ref": "ServerlessRestApiDeployment47fc2d5f9d"
　　　　},
　　　　"RestApiId": {
　　　　　"Ref": "ServerlessRestApi"
　　　　},
　　　　"StageName": "Prod"
　　　}
　　},
　　"ServerlessRestApiDeployment47fc2d5f9d": {
　　　"Type": "AWS::ApiGateway::Deployment",
　　　"Properties": {
　　　　"RestApiId": {
　　　　　"Ref": "ServerlessRestApi"
　　　　},
　　　　"Description": "RestApi deployment id: 47fc2d5f9d21ad56f83937abe2779d0e26d7095e",
　　　　"StageName": "Stage"
　　　}
　　},
　　"ServerlessRestApi": {
　　　"Type": "AWS::ApiGateway::RestApi",
　　　"Properties": {
　　　　"Body": {
　　　　　"info": {
　　　　　　"version": "1.0",
　　　　　　"title": {
　　　　　　　"Ref": "AWS::StackName"
　　　　　　}
　　　　　},
　　　　　"paths": {
　　　　　　"/hello": {
　　　　　　　"get": {
　　　　　　　　"x-amazon-apigateway-integration": {
　　　　　　　　　"httpMethod": "POST",
　　　　　　　　　"type": "aws_proxy",
　　　　　　　　　"uri": {
　　　　　　　　　　"Fn::Sub": "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations"
　　　　　　　　　}
　　　　　　　　},
　　　　　　　　"responses": {}
　　　　　　　}
　　　　　　}
　　　　　},
　　　　　"swagger": "2.0"
　　　　}
　　　}
　　},
　　"HelloWorldFunction": {
　　　"Type": "AWS::Lambda::Function",
　　　"Properties": {
　　　　"Code": {
　　　　　"S3Bucket": "gaia-stag-upload-bucket",
　　　　　"S3Key": "14f3e1c87109d66b1eb64d4ad33077ae"
　　　　},
　　　　"Tags": [
　　　　　{
　　　　　　"Value": "SAM",
　　　　　　"Key": "lambda:createdBy"
　　　　　}
　　　　],
　　　　"Handler": "app.lambda_handler",
　　　　"Role": {
　　　　　"Fn::GetAtt": [
　　　　　　"HelloWorldFunctionRole",
　　　　　　"Arn"
　　　　　]
　　　　},
　　　　"Timeout": 3,
　　　　"Runtime": "python3.8"
　　　}
　　}
　}
}

I want to know how to deploy only `Stag`, not both `Stage` and `Prod`, then my template stag name is `Stag`, why output is `Stage`?

**Logs/output**

**Comment by kdaily** [comment]
Hi @mikezang,

This question would be better for either the AWS SAM GitHub repository or the AWS Forums for CloudFormation, as they will be able to explain what the expected structure will be. Thanks!

- https://forums.aws.amazon.com/forum.jspa?forumID=92&start=0
- https://github.com/aws/serverless-application-model
