### ISSUE TITLE
aws iam tag-role only updates one tag and not a list

### ISSUE THREAD

**Issue by hibbert** [aws/aws-cli#5545]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

 aws iam tag-role only updates one tag and not a list #5545 

**SDK version number**
2.0.4

**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**

```
aws iam tag-role --role-name <rolename> --tags Key=<key1>,Value=<value1>,Key=<key2>,Value=<value2>
```

**Expected behavior**

Each tag is applied

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @hibbert,

I think your command should be:

```
aws iam tag-role --role-name <rolename> --tags Key=<key1>,Value=<value1> Key=<key2>,Value=<value2>
```

There should be a space between your key/value pairs, not another comma. See the examples here for more details on providing shorthand parameters:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-shorthand.html

Let me know that this works for you!
