### ISSUE TITLE
Amplify update-domain-association additive subdomains instead of replacement

### ISSUE THREAD

**Issue by stefkiourk** [aws/aws-cli#5556]
Hi AWS team,

I hope I have not missed anything and that this functionality already exists, kindly feel free to amend / delete this issue if it does. The 'update-domain-association' command for 'aws amplify' seems to be replacing the current subdomains when using the '--sub-domain-settings' parameter. While this does make sense in terms of semantics, I was thinking if it would be possible to have the ability of passing new subdomains without having to get the current ones and include the new one as well, in related automations.

The use case I am working on is allowing the user to register for a subdomain within the root domain, to allow branding. This would trigger the 'update-domain-association' to add the new subdomain.

It would be great if there would be an option like '--add-subdomain' which would add a new subdomain without replacing the rest, or requiring the developer to retrieve the subdomains first, construct the necessary '--sub-domain-settings' payload and include the new subdomain instead, which seems to be the alternative at the moment, unless I am missing something.

On a semi-related noted, the description of the command is 'Creates a new domain association for an Amplify app.', which is partially the same description as it is for 'create-domain-association'.

Thanks!

Stef

**Comment by kdaily** [comment]
Hi @stefkiourk, this would be a request to change the API. I will let the Amplify team know about this feature request. You can also request this issue via the AWS Forums to discuss it more directly with Amplify developers:

https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0

**Comment by MaybeOron** [comment]
hey @stefkiourk, is that added by any chance? i need the same functionality
