### ISSUE TITLE
Update yum package in amazonlinux to 1.18.141 asap

### ISSUE THREAD

**Issue by HarryCaveMan** [aws/aws-cli#5557]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The latest release of boto3 (1.15.0) breaks awscli yum installs if installed with pip. The cause of the break is that the bump from 1.14.63 to 1.15.0 changed the botocore version dependency to a version not compatible with awscli from the rpm.

**SDK version number**
awscli==1.18.101 (should be 1.18.141)
botocore==1.18.0 (breaks awscli 1.18.101)
**Platform/OS/Hardware/Device**
ec2 amazonlinux

**To Reproduce (observed behavior)**
install awscli with yum
install boto3 with pip
try to use `s3 cp` on awscli

**Expected behavior**
works

**Logs/output**
botocore version for sure (can't import docs module)

**Additional context**
upgrading awscli to 1.18.141 resolves the issue
100% linked to the changes in `setup.py` here:
https://github.com/boto/boto3/commit/fbe50eb7de36fa0987fc718c6914d24acd80a4d4

**Comment by kdaily** [comment]
Hi @HarryCaveMan, I will look into this request with the Amazon Linux maintainers. This is related to this `boto3` issue: https://github.com/boto/boto3/issues/2596

In general, it is not advisable to install these two packages in the same environment, as AWS CLI will always use a specific version of `botocore`, which may be different from the version that `boto3` requires.

**Comment by HarryCaveMan** [comment]
Thanks @kdaily! I will note that the latest version of aws-cli supports the more recent botocore, the issue is definitely that the rpm in `amzn2-core` uses an older version of `awscli` which was only broken by their release last week of `boto3 1.15.0`.

**Comment by kdaily** [comment]
H @HarryCaveMan, thanks. I looked at the Amazon Linux release notes, and it seems that they just upgraded on 2020-09-17 to AWS CLI version 1.18.107. I'm not sure why you are getting 1.18.101. It won't help your current situation, but just to let you know about the Amazon Linux upgrade cadence.

https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/

**Comment by HarryCaveMan** [comment]
> 
> 
> H @HarryCaveMan, thanks. I looked at the Amazon Linux release notes, and it seems that they just upgraded on 2020-09-17 to AWS CLI version 1.18.107. I'm not sure why you are getting 1.18.101. It won't help your current situation, but just to let you know about the Amazon Linux upgrade cadence.
> 
> https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/

Sorry that was actually a typo on my part... While the `amazonlinux` docker container is running `1.18.101`, the ec2 ami is running `1.18.107`. Both are affected by this issue.

**Comment by kdaily** [comment]
Thanks for clarifying! Are you able to use AWS CLI v2, and the Docker container image that is published for that?

**Comment by HarryCaveMan** [comment]
Probably, I was just using the amazonlinux image to replicate the issue locally.

**Comment by kdaily** [comment]
I confirmed with the Amazon Linux team that upgrading `botocore` on that image is not advisable. They usually update multiple times per year. I would advise using `boto3` in a virtual environment.
