### ISSUE TITLE
Getting the instance serial console log produces encoding error

### ISSUE THREAD

**Issue by rabits** [aws/aws-cli#5558]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Serial console sometimes contains weird chars and on Windows it could be an issue, because default decoder/encoder could vary.

**SDK version number**
aws-cli/2.0.50 Python/3.7.7 Windows/10 exe/AMD64

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
1. Create instance
2. Request serial console log: `aws.exe --output json --region us-west-1 ec2 get-console-output --instance-id i-064f866083905a5bd`

**Expected behavior**
I think setting the encoding/decoding to utf-8 should fix the issue with cross-platform differences.

**Logs/output**
```
aws.exe --output json --region us-west-1 ec2 get-console-output --instance-id i-064f866083905a5bd
{
    "InstanceId": "i-064f866083905a5bd",
    "Output":
'charmap' codec can't encode character '\u2192' in position 66745: character maps to <undefined>
```

**Additional context**
Actually produced with any output - json or text doesn't matter.

**Comment by kdaily** [comment]
Hi @rabits, thanks for opening. I think I've encountered this before (https://github.com/aws/aws-cli/issues/4778). The current solution is to enable UTF-8 as in the Windows system locale, as described here:

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096

**Comment by rabits** [comment]
Hi @kdaily , yeah I think it's related - but in my case I have no way to rule the host locale. My application just uses the current aws installation. I think the AWS tool should work properly in all the locales available on the host platform, but that's great to know there is a workaround. Thank you

**Comment by kdaily** [comment]
Agree! As noted in the other post is that `set PYTHONIOENCODING=UTF-8` works for the V1 client, but not V2. This needs to be investigated.

**Comment by tim-finnigan** [comment]
This error has been previously reported [a few times](https://github.com/aws/aws-cli/issues?q=is%3Aissue+%27charmap%27+codec+can%27t+encode+character+is%3Aclosed). For the AWS CLI v2 I think https://github.com/aws/aws-cli/issues/5086 addresses the issue, specifically in [this comment](https://github.com/aws/aws-cli/issues/5086#issuecomment-629400114).

You can find a section on Locale [here in the AWS CLI documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/topic/config-vars.html?highlight=locale#locale). For Windows it notes:

>...if you use Windows with default encoding `CP1252`, setting `AWS_CLI_FILE_ENCODING=UTF-8` would make CLI ignore locale encoding and open text files using `UTF-8`.

Based on that I believe this issue can be closed. If the above solution does not work please let us know here or create a new issue and we can revisit this. Thanks!
