### ISSUE TITLE
Allow `aws logs tail` to filter by stream

### ISSUE THREAD

**Issue by mcg** [aws/aws-cli#5560]
**Is your feature request related to a problem? Please describe.**
Currently, `aws logs tail` will show all streams for a log group.

**Describe the solution you'd like**
It would be better if you could specify the stream you wish to tail instead.

**Describe alternatives you've considered**
I am currently piping the output to `grep` but this looses log colorization and complicates automation.

**Comment by kdaily** [comment]
Thanks for the feature request, @mcg.

**Comment by ragebiswas** [comment]
+1 - can we get an update on this please AWS?

**Comment by rnhurt** [comment]
I'm currently using [awslogs](https://github.com/jorgebastida/awslogs) for this type of functionality and I really like it.  Using it I can tail logs, apply filters, and query for exactly what I want to see.  It would be great if this type of thing was available in the native 'aws' command.

**Comment by mlin** [comment]
The [default logging configuration](https://docs.aws.amazon.com/batch/latest/userguide/using_cloudwatch_logs.html#viewing_cwlogs) for AWS Batch sends the logs of each job in its own stream but *all in one log group*. So this feature is rather sorely needed for use with AWS Batch logs.

**Comment by praja96** [comment]
It would be nice to have a way to use sed/awk/grep with the aws logs tail command because when using the follow command and trying to pipe with sed/awk/grep, it was giving weird behavior. Not sure if anyone else has experienced that.

**Comment by dcherman** [comment]
@praja96 Ran into the same thing.  Try setting `PYTHONUNBUFFERED=1` before running your tail command.

**Comment by tim-finnigan** [comment]
Closing this as the PR linked above was merged. 

You can now use the parameters `--log-stream-names` or `--log-stream-name-prefix` to filter logs: 
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/tail.html
