### ISSUE TITLE
Want To Ask #WTA

### ISSUE THREAD

**Issue by kingsalman99** [aws/aws-cli#5561]
hello sir can i Check Ses Get-send-quota using Curl??

**Comment by kdaily** [comment]
@kingsalman99, I'm not sure I have enough information as to what you want to complete with the AWS CLI. If you have a general question about how to access an API endpoint for a service, I would suggest the AWS Forums. The AWS CLI is performing all of the requirements for accessing the endpoint, including authentication, retries, etc.
