### ISSUE TITLE
Aurora support for more regions including Europe, specifically eu-west-1

### ISSUE THREAD

**Issue by kristianmandrup** [aws/aws-cli#5562]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

From the [amplify cli relational documentation](https://docs.amplify.aws/cli/graphql-transformer/relational) it is clear that it currently only supports `us-east-1` region. Why this limitation?

We are based in London in `eu-west-1` and want to use Aurora with Amplify for this region

**Describe the solution you'd like**

Add support for more regions for Aurora in the CLI

**Describe alternatives you've considered**

Not sure

**Additional context**

**Comment by kdaily** [comment]
Hi @kristianmandrup, the AWS Amplify CLI is separate from the AWS CLI. I'm going to copy your comment above and open an issue here, and then close this one:

https://github.com/aws-amplify/amplify-cli

Thanks!

**Comment by kdaily** [comment]
New issue opened at https://github.com/aws-amplify/amplify-cli/issues/5410
