### ISSUE TITLE
aws/cli hangs during amplify push

### ISSUE THREAD

**Issue by arancauchi** [aws/aws-cli#5579]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Using v 4.29.3 of amplify/cli a push from a fresh `init` and `configure` hangs infinitely.
Downgrading to 4.28.0 works.

**SDK version number**
CLI version 4.29.3

**Platform/OS/Hardware/Device**
MacOS Catalina

**To Reproduce (observed behavior)**
Init a new project with defaults
Configure a new project with defaults
Create the standard IAM administrator access account
Call amplify add api (either graphQL or REST with defaults)
Call amplify push

**Expected behavior**
Quickly push the API change to the stack

**Logs/output**
No logs, as the amplify push command fails to progress, and is continually stuck at the pulling changes from cloud to dev initial step.

**Additional context**
None

**Comment by kdaily** [comment]
Hi @arancauchi,

It looks like you are using the AWS Amplify CLI (https://docs.amplify.aws/cli). If so, this would be an issue for a different repository:

https://github.com/aws-amplify/amplify-cli

**Comment by veerendrapatel** [comment]
I am using amplify cli 4.29.3 on MAC-MoJave - it hangs forever-
amplify push
⠋ Fetching updates to backend environment: dev from the cloud.

**Comment by kdaily** [comment]
Hi @veerendrapatel, as noted above this issue should be opened in the AWS Amplify CLI. Thanks!
