### ISSUE TITLE
request-spot-instance should support AssociatePublicIpAddress

### ISSUE THREAD

**Issue by donovanhide** [aws/aws-cli#560]
Hi,

when using request-spot-instance there should either be a flag for associate-public-ip-ddress or the launch specification should provide:

"associatePublicIpAddress":bool

in the top level of the request. It get's very complicated trying to define a network interface correctly with a non-default VPC :-)

Cheers,
Donovan.

**Comment by mtdowling** [comment]
Unfortunately, EC2 operations typically have a large amount of input parameters. Moving certain parameters to the top-level and leaving others would quickly become a game of Whac-a-mole. Examples of associating IP addresses with a non-default VPC spot instance can be found in the CLI documentation: http://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html#examples
