### ISSUE TITLE
Ignore files and folders like .gitignore 

### ISSUE THREAD

**Issue by ugurcemozturk** [aws/aws-cli#5600]
**Is your feature request related to a problem? Please describe.**
When ignoring files while running aws s3 sync, many times --exclude is not the optimal solution.
 
**Describe the solution you'd like**
There can be a file, like .gitignore that we can pass list of file and folder patterns to be ignored.

**Describe alternatives you've considered**
--

**Additional context**
--

Thanks!

**Comment by kdaily** [comment]
Thanks for the feature request, @ugurcemozturk!

**Comment by kdaily** [comment]
Hi @ugurcemozturk, turns out this is a duplicate of #3520. Can you add an upvote to the original post, and any other comments you have there? Thanks!

**Comment by ugurcemozturk** [comment]
Hi @kdaily,
Indeed this is a duplicate one. I've upvoted #3520 so you can close this issue.
Thanks!
