### ISSUE TITLE
Can´t add tags to load balancer rules

### ISSUE THREAD

**Issue by gilvi** [aws/aws-cli#5606]
In the Api reference says: 
"Adds the specified tags to the specified Elastic Load Balancing resource. You can tag your Application Load Balancers, Network Load Balancers, target groups, listeners, and **rules**."
https://docs.aws.amazon.com/cli/latest/reference/elbv2/add-tags.html

but doesn´t work: 

Just add a tag to a listener rule
aws elbv2 add-tags --resource-arns arn:aws:elasticloadbalancing:eu-west-1:~~~:listener-rule/app/~~~/~~~/~~~/~~~ --tags "Key=RuleName,Value=test"

Describe the listener rule tags
aws elbv2 describe-tags --resource-arn arn:aws:elasticloadbalancing:eu-west-1:~~~:listener-rule/app/~~~/~~~/~~~/~~~

and says:
"Tags": []

There is no way to add tags throught the console so I think it's not possible.

Would like to be able to add some tags to ALB rules so I can search them in the json by tag instead of by arn. More human readable in scripts config.

**Comment by kdaily** [comment]
Hi @gilvi,

Can you try to create a new rule and add tags at the same time to see if that is successful? The `create-rule` action shows that you should be able to add tags that way.

https://docs.aws.amazon.com/cli/latest/reference/elbv2/create-rule.html

From there, we should be able to ascertain if you can then add or modify existing tags. If you are not, this is a problem with the API.

**Comment by gilvi** [comment]
It looks it's working now with the same `aws elbv2 add-tags` command (not sure if any changed)

Anyway, I tried to create a rule with tags and neither of these versions (what I've tried) have that option:
aws-cli/1.18.107 Python/2.7.18 Linux/4.14.193-113.317.amzn1.x86_64 botocore/1.17.31
aws-cli/2.0.30 Python/3.7.7 Windows/7 botocore/2.0.0dev34

```
SYNOPSIS
            create-rule
          --listener-arn <value>
          --conditions <value>
          --priority <value>
          --actions <value>
          [--cli-input-json <value>]
          [--generate-cli-skeleton <value>]
```

```
aws elbv2 create-rule --listener-arn arn:aws:elasticloadbalancing:eu-west-1:... --priority 5 --conditions file://conditions.json --actions Type=forward,TargetGroupArn=arn:aws:elasticloadbalancing:eu-west-1:... --tags Key=RuleName,Value=test
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --tags, Key=RuleName,Value=test
```
Can't find any reference about CLI versions and their differences.

**Comment by kdaily** [comment]
Hi @gilvi,

The models used to generate AWS CLI commands are part of the `botocore` package. Tags were recently added to the `CreateRule` command. Both of the versions you mentioned are prior to this change:

https://github.com/boto/botocore/commit/8f873e78495a75c585bdbf2b5f14b803dc507294

**Comment by kdaily** [comment]
While it's not indicative of the exact change made, you can check the `botocore` changelog as well. `elbv2` was updated with version `botocore==1.18.11` (you have `1.17.31`):

https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#11811
