### ISSUE TITLE
SSL issue? awscli site is down

### ISSUE THREAD

**Issue by graemecode** [aws/aws-cli#5611]
Seems like https://awscli.amazonaws.com is down, which affects downloads - notably the command:

```
curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
````

**Comment by bubbajames-docker** [comment]
+1

**Comment by cd-chrisburton** [comment]
Can't download any cli version:

403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: E9y_9pBb8oZD2ww-V4hRyPwKaYUiG6wG-_ffHPWmixgy6QNHuNhe_g==

**Comment by OHR7** [comment]
> +1
> 
> Site not technically down, but the SSL certificate returned is *.cloudfront.net with no alternative subject name for 'awscli.amazonaws.com'
> 
> So one "could" use the curl option `-k, --insecure` but that is never good practice.

I tried that but when installing I get an error so wondering if is downloading the correct .pkg
Error:
installer: Error - the package path specified was invalid: './AWSCLIV2.pkg'.
seems like a problem with the mac installer but opening directly from my downloads folder and still get error so maybe corrupted .pkg?

**Comment by kpkrishnamoorthy** [comment]
+1 re: SSL error. I filed an AWS support ticket for good measure. Below is the output when running the command recommended in the docs, to install AWS CLI v2.

```
$ curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'awscli.amazonaws.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by bubbajames-docker** [comment]
Seems to be resolved.  My instances are once again deploying successfully.

**Comment by stealthycoin** [comment]
This is due to a bad deployment, we rolled back so this should be fixed now.

Please let us know if this is still effecting you.

**Comment by cd-chrisburton** [comment]
Resolved here

**Comment by kpkrishnamoorthy** [comment]
Resolved here, as well.
