### ISSUE TITLE
--cli-read-timeout --cli-connect-timeout are not respected

### ISSUE THREAD

**Issue by JustinLovinger** [aws/aws-cli#5631]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
An upload like

```
zfs send -R --raw "$snapshot_name" | aws s3 cp \
  --cli-read-timeout 0 \
  --cli-connect-timeout 0 \
  --expected-size "$expected_size" \
  - "s3://$bucket/$t-$backup_name"
```

will time out after about 15 minutes of network outage.

**SDK version number**

1.17.13

**Platform/OS/Hardware/Device**

NixOS 20.03

**To Reproduce (observed behavior)**

1. `cat path/to/large/file | aws s3 cp --cli-read-timeout 0 --cli-connect-timeout 0 - s3://$bucket/$file`
2. Disconnect network.
3. Wait about 15 minutes.

**Expected behavior**

With unlimited timeouts, I expect `aws s3 cp` to retry forever.

**Logs/output**

(I am currently waiting on a very large backup and cannot interrupt network to get logs)

**Additional context**

I haven't tested without streaming.

Setting very large timeouts has the same effect as `0`.

It times out after about 5 minutes with default timeouts, so timeouts have some effect, but only up to about 15 minutes.

**Comment by kdaily** [comment]
Hi @JustinLovinger,

These parameters are not going to have the effect you are expecting. These timeout parameters are passed on to the `urllib3` library, as described here:

- https://urllib3.readthedocs.io/en/latest/user-guide.html#using-timeouts
- https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html?highlight=Timeout#urllib3.util.Timeout

As defined there, the `cli-connect-timeout` is for "The maximum amount of time (in seconds) to wait for a connection attempt to a server to succeed.". The `cli-read-timeout` is for "The maximum amount of time (in seconds) to wait between consecutive read operations for a response from the server.". Neither of these will impact the retries made, as they are controlling timing per request.

See the comment (https://github.com/aws/aws-cli/issues/5632#issuecomment-708564462) for more information on how you can better control the CLI behavior in your use case.

**Comment by JustinLovinger** [comment]
@kdaily is it correct to say that if you want to retry indefinitely (or effectively indefinitely), you only need to set `max_attempts`, you do not need to change `--cli-read-timeout` or `--cli-connect-timeout`?

**Comment by kdaily** [comment]
That is correct, changing those values won't have an effect, while max attempts will prolong the amount of time spent retrying. Note that the time between retries is not uniform (it's exponential by a factor of 2, with a maximum time depending on the retry mode).

This is also useful article talking about optimizing large file upload to S3:

https://aws.amazon.com/premiumsupport/knowledge-center/s3-upload-large-files/
