### ISSUE TITLE
"Could not connect to the endpoint URL" during long S3 upload

### ISSUE THREAD

**Issue by JustinLovinger** [aws/aws-cli#5632]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

Several times now, during a very long (32 hour) streaming upload, I have recieved an error like

```
upload failed: - to s3://bucket/file Could not connect to the endpoint URL: "https://bucket.s3.us-east-2.amazonaws.com/file?uploadId=.OdhIrwRiLSzEjp7wnX4DwM1RcTtYr7nHibsR0qmzHNSCrtNnS0InpiYETYOes3OdTxuLcqU08UacubVMu4j6TY69SytgMqL_YfgK_CaGvClYbgUMAR0mFVJidROaypL&partNumber=4591"
```

I can see network activity logged around this time, so it does not appear to be a network outage on my end.

**SDK version number**

aws-cli/1.18.128 Python/3.8.5 Linux/5.4.69 botocore/1.17.51

**Platform/OS/Hardware/Device**

NixOS 20.09

**To Reproduce (observed behavior)**

1. Start a very long S3 upload
2. Wait a couple of days

**Expected behavior**

I expect the upload to continue for as long as it takes to finish.

**Logs/output**

I can see about adding `--debug` to the next attempt, if the current one fails.

**Additional context**

I tried disabling connection timeouts, but ran into issue #5631 .

**Comment by kdaily** [comment]
Hi @JustinLovinger,

This error is generally indicative of a transient network problem. Over the course of a 32-hour upload stream, the client is making thousands (millions maybe?) of requests. Eventually, something is going to fail. The AWS CLI does retry, but it will not retry indefinitely. You can read more about how to configure retries here:

- https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#retry-configuration

Specifically, you could raise the `max_attempts` to keep trying more times.

This section and guide in the `boto3` documentation is also useful for more details about the retry modes and how to verify that they're working:

- https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html

**Comment by Mehar-Shafaat-Ullah** [comment]
upload failed: - to s3://bucket/file Could not connect to the endpoint URL: "https://bucket.s3.us-east-2.amazonaws.com/file?uploadId=.OdhIrwRiLSzEjp7wnX4DwM1RcTtYr7nHibsR0qmzHNSCrtNnS0InpiYETYOes3OdTxuLcqU08UacubVMu4j6TY69SytgMqL_YfgK_CaGvClYbgUMAR0mFVJidROaypL&partNumber=4591"
==============
still getting  failed a
