### ISSUE TITLE
aws s3 sync show rolling progress of how many objects synced so far

### ISSUE THREAD

**Issue by tooptoop4** [aws/aws-cli#5634]
aws s3 sync s3path1 s3path2

currently tells
Completed x GB with ... file(s) remaining

but it doesn't know how many files remaining as the number is inaccurate
whereas it does know how many files have been synced so far

ideally it can print the number synced so far as it goes

**Comment by kdaily** [comment]
Hi @tooptoop4,

Thanks for your request. There is quite a history on this feature, so I will link a few relevant issues and comments. Essentially there are S3 and implementation limitations on this feature that provide a better experience overall.

- https://github.com/aws/aws-cli/issues/4113#issuecomment-488448293
- https://github.com/aws/aws-cli/issues/4113#issuecomment-488448293
