### ISSUE TITLE
npm was not found. Please verify installation.

### ISSUE THREAD

**Issue by truongleeuet** [aws/aws-cli#5646]
I had error "npm was not found. Please verify installation." when run command: `docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli codeartifact login  --tool npm --domain "common" --repository "common"`. Please help me fix error. Thanks!

**Comment by kdaily** [comment]
Hi @truongleeuet,

The login command uses the tool specified to set up login information. Since you specified `npm`, it's required to complete login to use the `npm` package repository by running `npm config`. So, you'll need to install `npm` to use this functionality.

**Comment by bobrossthepainter** [comment]
Hi @truongleeuet,
I'm a bit late to the party, but ran into the same issue.
I'm simply mounting a bash script inside the AWS-CLI docker container under the path `/usr/bin/npm` and the `.npmrc` file. This script offers a super simple version of the `npm set config <param> <value>` api:
```
#!/bin/bash
echo "$3=$4" >> ~/.npmrc
```

**Comment by unacceptable** [comment]
Our team is using a dind container in our Docker CI/CD pipeline.  Initially, I tried this to no avail: 

```
alias npm='docker run -it --entrypoint /usr/local/bin/npm node:14.15.0-alpine3.12'
```

Alas I was able to get this to work (going off of @bobrossthepainter's comment like this:

Creating an `npm` shell script in the `$PATH`:

```
#!/bin/sh
docker run -it --entrypoint /usr/local/bin/npm node:14.15.0-alpine3.12 $@
```

@bobrossthepainter's solution is definitely more lightweight though.
