### ISSUE TITLE
pip3 installation support for cliv2

### ISSUE THREAD

**Issue by manpreetsnehra** [aws/aws-cli#5660]
**Is your feature request related to a problem? Please describe.**
Checking if its possible or is it in the feature plan to allow installation using pip3 for version2 same as version 1.

**Describe the solution you'd like**
pip3 install awscli --> upgrades to v2 or
pip3 install awscli2 --> installs v2 mandating removal or v1.

**Describe alternatives you've considered**
Its good for consistency to maintain and use only one source of installation and updates/upgrades are easier and more consistent and easily automated

**Additional context**

**Comment by kdaily** [comment]
Hi @manpreetsnehra,

Thanks for asking. There are existing issue discussing this here: #4947 and #5345.
