### ISSUE TITLE
[v2][feedback-wanted] Improved CLI auto-prompt mode

### ISSUE THREAD

**Issue by kyleknap** [aws/aws-cli#5664]
Hi everyone. We are re-imagining the AWS CLI auto-prompt mode for v2. We want to get some feedback on this mode before merging it into the v2 branch and making it part of a public release.

# Introduction

Currently, the AWS CLI v2 has the [--cli-auto-prompt parameter](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-prompting.html) for most commands that help you build up a CLI command. While this mode is helpful, there were more productivity improvements we wanted to bake into this feature. Below is an example of how the new auto-prompt mode works:

![render1603302176281](https://user-images.githubusercontent.com/4605355/96820474-ea526a00-13da-11eb-93b7-2472aab7e010.gif)

# How to try it out

## Installation

In order to try it out the improved auto-prompt mode, you can download preview builds for each of the platforms we support and follow its corresponding installation instructions from the [AWS CLI user guide](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html):

* [Linux x86 exe](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/awscli-exe-linux-x86_64.zip) with [detached signature](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/awscli-exe-linux-x86_64.zip.sig)
* [Linux aarch64 exe](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/awscli-exe-linux-aarch64.zip) with [detached signature](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/awscli-exe-linux-aarch64.zip.sig)
* [MSI](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/AWSCLIV2.msi)
* [PKG](https://aws-cli-previews.s3.us-west-2.amazonaws.com/auto-prompt-mode/AWSCLIV2.pkg)

Improvements and bug fixes are being made on the [revamped-auto-prompt](https://github.com/aws/aws-cli/tree/revamped-auto-prompt) branch. You can install it from there as well:
```
$ cd <path_to_awscli_repo> && git checkout revamped-auto-prompt
$ pip install -r requirements.txt
$ pip install -e .
$ ./scripts/gen-ac-index
```
## Usage

To enter auto-prompt mode, you can run:
```
aws --cli-auto-prompt
```
You can also enter auto-prompt from any command level:
```
aws ec2 --cli-auto-prompt
aws ec2 describe-regions --cli-auto-prompt
```
If you do not want to specify `--cli-auto-prompt` every time, you can also configure to always use the mode:
```bash
aws configure set cli_auto_prompt on
aws  # This will now enter auto-prompt mode
```
# Features

Here is a list of features that are available through auto-prompt mode.

### Environment variable
You can also enable it from an environment variable and you will automatically enter auto-prompt mode for any command:
```bash
export AWS_CLI_AUTO_PROMPT=on
aws  # This will immediately enter auto-prompt mode
```
Also note: environment variables override values in the shared config file.

### Turning auto-prompt off
To disable auto-prompt mode for a single command, you can specify `--no-cli-auto-prompt`:
```
aws ec2 describe-regions --no-cli-auto-prompt
```
## `on-partial` mode

**Issue author’s note: As a daily user of the AWS CLI, I have this configured for my system by default. I like this mode because I get the help of auto-prompt mode if I’m unfamiliar with a command, but it does not unnecessarily prompt me if I already know the command or if I’m running a script.**

In this mode, you will only be auto-prompted for commands that are incomplete. This includes partial commands that will never make an API call because of client-side validation errors. This mode is particular useful if you have pre-existing scripts, runbooks, or you already know the command and you do not want to be auto-prompted. You can set it by specifying the mode as `on-partial`:
```
aws configure set cli_auto_prompt on-partial
```
or set the environment variable
```bash
export AWS_CLI_AUTO_PROMPT=on-partial
```
From there you can run commands:
```bash
aws  # Will enter auto-prompt
aws ec2  # Will enter auto-prompt
aws ec2 describe-regions  # Will execute command normally
aws dynamodb create-table   # Will enter auto-prompt. Missing required parameters
```
## Documentation panel

Pull up help documentation for current command (using `F3`):
<img width="1274" alt="doc-panel" src="https://user-images.githubusercontent.com/4605355/96821366-92b4fe00-13dc-11eb-9770-fbc03d73bfd7.png">

## Resource completion

Makes AWS API calls to complete using available AWS resources properties (e.g. Amazon EC2 instance id’s):
<img width="1269" alt="resource-completion" src="https://user-images.githubusercontent.com/4605355/96821399-a1031a00-13dc-11eb-8d28-dd5419a40dfa.png">

## Shorthand completion
<img width="1271" alt="shorthand" src="https://user-images.githubusercontent.com/4605355/96821459-bf691580-13dc-11eb-9000-f74a89b2acba.png">

## File completion

Completion of local files if prefix with `file://` or `fileb://`:
<img width="1273" alt="file-completion" src="https://user-images.githubusercontent.com/4605355/96821496-d576d600-13dc-11eb-92f3-ec3f589719e6.png">

## Region/profile completion

Completion of region names:
<img width="1273" alt="region-completion" src="https://user-images.githubusercontent.com/4605355/96821530-f0e1e100-13dc-11eb-83f0-9cef8316e2eb.png">

Completion of profile names:
<img width="1271" alt="profile-completion" src="https://user-images.githubusercontent.com/4605355/96821551-ff2ffd00-13dc-11eb-9573-6c327d2e9ad9.png">

## Fuzzy searching

Complete commands and values that contain a specific set of characters. For example, search for all `ec2` commands that have `instance` in the name:
<img width="1274" alt="fuzzy-searching" src="https://user-images.githubusercontent.com/4605355/96821589-17a01780-13dd-11eb-9c9b-d7cdd74898ba.png">

## History mode

Re-run commands ran in auto-prompt mode by pressing `CTRL-R` and selecting through its history:
<img width="1275" alt="history-mode" src="https://user-images.githubusercontent.com/4605355/96821658-38686d00-13dd-11eb-9820-3f32e6388a24.png">

# How to give feedback

* If you generally like or dislike the new functionality, please add an appropriate GitHub reaction to the original comment in this issue.
* If you have general feedback or questions about auto-prompt mode, feel free to comment directly in this issue. For example:
    * Would you see yourself using this mode regularly? Would you see yourself configuring your environment permanently to use either `on` or `on-partial` mode?
    * Are there any particular workflows that you had trouble with or found confusing?
* Search across [all auto-prompt mode issues](https://github.com/aws/aws-cli/labels/auto-prompt-mode) and use GitHub reaction to +1 any issues that you agree with.
* If you have feedback about specific functionality (e.g., resource completion, parameter completion, on-partial mode etc.) and there is not already an open issue for it, please open either a feature request or bug report in a new GitHub issue and indicate it is related to the new auto-prompt mode by prefixing the title with `[v2][auto-prompt]`: https://github.com/aws/aws-cli/issues/new/choose.

We are still actively developing this feature, but we are hoping to launch it soon! So let us know what you think. Thanks everyone!

**Comment by kdaily** [comment]
The AWS CLI v2 client with improvements to auto-prompt mode has now been released as of version [`2.1.0`](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#210)! See the installation guide for instructions on how to get it.

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
