### ISSUE TITLE
"aws iam delete-access-key" prompting for user input

### ISSUE THREAD

**Issue by acceptableEngineering** [aws/aws-cli#5668]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When running the command `aws iam delete-access-key` with valid required argument as shown below, user interaction is required, making this command difficult to automate/wrap in scripts, and making it inconsistent with the AWS CLI's normal behavior. Additionally, this behavior is not documented in the user guide: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/delete-access-key.html

**SDK version number**
aws-cli/2.0.58 Python/3.9.0 Darwin/19.6.0 source/x86_64

**Platform/OS/Hardware/Device**
macOS

**To Reproduce (observed behavior)**
```
$  aws iam delete-access-key --access-key-id ACCESS_KEY_ID_HERE
# Prompts for user interaction here, requiring :q to be input
```

**Expected behavior**
No user input required

**Logs/output**
N/A

**Additional context**
N/A

**Comment by kdaily** [comment]
Hi @acceptableEngineering,

I couldn't reproduce it, but I have a hunch that the AWS CLI pager is activating here. It is on by default and for Mac the program used is `less`. The default parameters on Mac for `less` are not the best. Check what your `LESS` environment variable has set. If this variable is unset, the AWS CLI uses `-FRX` as parameters to `less` - the important one is `-F` (or `--quit-if-one-screen`).

You can read more about the configuration of this in the 'How to use pager flags' section of this documentation page:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-clientside

Let me know if that works for you!
