### ISSUE TITLE
Running the installer in ruby, permissions are incorrect

### ISSUE THREAD

**Issue by sudodevnull** [aws/aws-cli#5669]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When running the command 'sudo ./aws/install' with open3, the installer runs but the executables do not have the correct permissions.  I am not sure what all file permissions are incorrect, but the aws binary itself is not executable.

I need to automate the installation of aws cli v2 on 3000 + systems and I have to do this with puppet (in ruby).

I am currently testing on the following:
Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
RUBY_VERSION => "2.4.5"

**SDK version number**
2.0.58

**Platform/OS/Hardware/Device**
What are you running the cli on?
Red Hat Enterprise Linux Server 7.9

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
This issue can be reproduced by simply downloading the zip, unzipping it and then jumping into an irb session as root.
Run the following commands, replace '/path/to/install' with the directory where the zip was unzipped:
require 'open3'
stdout_str, error_str, status = Open3.capture3('sudo /path/to/install/aws/install')

once the above is completed look at the file permissions on the following:
/usr/local/bin/aws
/usr/local/aws-cli/v2/current/dist/aws

I assume there are many other files that are missing execute permissions or have incorrect permissions.

**Expected behavior**
I should be able to utilize the aws cli after the installer completes.  It does not work due to not being executable (permission denied)

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
N/A

**Additional context**
N/A

**Comment by kdaily** [comment]
Hi @sudodevnull, how are you performing the unzip operation? If you are using a Ruby library, it may not be honoring the permissions. This was previously found to be true for the Python unzip library as well.

**Comment by sudodevnull** [comment]
ruby zip is not honoring permissions.  Can you provide a full list of what permissions should be for any files that are not honored?

**Comment by kdaily** [comment]
Hi @sudodevnull,

For unzipping with the Python library, the default is `644`, or whatever your default permissions are from `umask`. I would guess that Ruby does something similar.

If you do a recursive listing of the zip file, you'll find the full permission set - it's quite large so I won't paste it here. From a cursory look, all text (json, xml, Python, etc) are `644` and executables are `755` on my system (Mac OSX Mojave).

Hope that helps!
