### ISSUE TITLE
[v2] CLI auto-prompt mode documentation shows ^M characters on windows

### ISSUE THREAD

**Issue by ppittle** [aws/aws-cli#5670]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

**SDK version number**
aws-cli/2.0.58 Python/3.7.7 Windows/10 exe/AMD64

**Platform/OS/Hardware/Device**
What are you running the cli on? Windows 10

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
1. On a Windows 10 machine open Powershell (pwsh)
2. Type `aws`
3. Press `F3`

**Expected behavior**

Don't show `^M` in place of whitespace:

![image](https://user-images.githubusercontent.com/1190907/97046094-b8045200-152b-11eb-95b1-d90ebbda5cc4.png)

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Thanks @ppittle!

**Comment by stobrien89** [comment]
Closing, as fix has been merged.
