### ISSUE TITLE
aws ec2 describe-network-interfaces --filters Name=addresses.primary,Values=true returns incorrect values

### ISSUE THREAD

**Issue by captainfalcon23** [aws/aws-cli#5672]
If I have a network interface with multiple private addresses associated, I would expect the above filter to only return the IP's marked as the primary i.e true. It appears that if at least one is marked as true, the network interface is returned. This doesn't make sense sense every Network Interface's first IP is set to true.

Example command: 

`aws ec2 describe-network-interfaces --query NetworkInterfaces[*].PrivateIpAddresses[*] --filters Name=addresses.primary,Values=true`

Expected Output:

`
"PrivateIpAddresses": [
                {
                    "Primary": true,
                    "PrivateDnsName": "ip-172-31-48-101.ap-southeast-2.compute.internal",
                    "PrivateIpAddress": "172.31.48.101"
                }
            ]
`

Actual Output:

`
"PrivateIpAddresses": [
                {
                    "Primary": true,
                    "PrivateDnsName": "ip-172-31-48-101.ap-southeast-2.compute.internal",
                    "PrivateIpAddress": "172.31.48.101"
                },
                {
                    "Primary": false,
                    "PrivateDnsName": "ip-172-31-48-119.ap-southeast-2.compute.internal",
                    "PrivateIpAddress": "172.31.48.119"
                }
            ]
`

**Comment by kdaily** [comment]
Hi @captainfalcon23,

The filter operation here is on the server side, so the CLI is not performing anything here.

This documentation page gives some more details about how filtering works:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html

The filters apply to the resource you are filtering for, NOT for parts of the structure returned. To get your desired behavior, I think you'll need to use a [JMESPath filter](https://jmespath.org/proposals/filter-expressions.html) or another utility like `jq` and perform this client-side.

I agree with you that the utility of the `addresses.primary` field is limited if it will always have at least one record with `true`. I'll give this feedback to the EC2 team.

**Comment by captainfalcon23** [comment]
No problems, thanks for the update and feedback to the EC2 team :)
