### ISSUE TITLE
Servicediscovery list-services missing NamespaceId

### ISSUE THREAD

**Issue by cybersn-tdeyarmin** [aws/aws-cli#5676]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Running `aws servicediscovery list-services` does not return the namespace id to which the service is associated.  

**SDK version number**
aws-cli/2.0.59 Python/3.7.4 Darwin/19.5.0 exe/x86_64

**Platform/OS/Hardware/Device**
MacOS

**To Reproduce (observed behavior)**
`aws servicediscovery list-services`

**Expected behavior**
The documentation [here](https://docs.aws.amazon.com/cli/latest/reference/servicediscovery/list-services.html) says the output of the command should have the NamespaceId in the DnsConfig.  This is the structure I expected:
```json
{
  "Services": [
    {
      "Id": "srv-aaaaaaaaaaaaaaaa",
      "Arn": "arn:aws:servicediscovery:.....",
      "Name": "some-app",
      "DnsConfig": {
        "NamespaceId": "<id>",
         ...
      }
    }
  ]    
}
```

**Logs/output**
```json
{ 
    "Services": [
        {
            "Id": "srv-aaaaaaaaaaaaaaaa",
            "Arn": "arn:aws:servicediscovery:us-east-2:111111111111:service/srv-aaaaaaaaaaaaaaaa",
            "Name": "some-app",
            "DnsConfig": {
                "RoutingPolicy": "MULTIVALUE",
                "DnsRecords": [
                    {
                        "Type": "A",
                        "TTL": 60
                    }
                ]
            },
            "HealthCheckCustomConfig": {
                "FailureThreshold": 1
            },
            "CreateDate": "2020-10-27T13:15:51.451000-04:00"
        }
    ]
}
```
**Additional context**
I had created the service through cloudformation:

```json
...
  "Resources": {
    "CloudMapService": {
      "Type" : "AWS::ServiceDiscovery::Service",
      "Properties" : {
        "Name": { "Ref": "ServiceName" },
        "NamespaceId": { "Ref": "NameSpaceId" },
        "DnsConfig": {
          "DnsRecords": [
            {
              "Type": "A",
              "TTL": 300
            }
          ],
          "RoutingPolicy": "MULTIVALUE"
        },
        "HealthCheckCustomConfig": {
          "FailureThreshold": 1
        }
      }
    }
  ...
```

**Comment by kdaily** [comment]
Hi @cybersn-tdeyarmin,

Can you provide logs using the `--debug` flag? Thanks!
