### ISSUE TITLE
How to install awscli version compatible with AWS Lambda

### ISSUE THREAD

**Issue by dazza-codes** [aws/aws-cli#5697]
How can pip install a version of `awscli` that is compatible with the boto* versions in AWS Lambda:
- https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

I'm trying to create a venv that has the AWS Lambda versions of boto*, e.g.

```
$ pip install boto3==1.14.40 botocore==1.17.40 awscli
$ pip check
awscli 1.18.170 has requirement botocore==1.19.10, but you have botocore 1.17.40.
```

If it is all uninstalled and then reinstalled using the command above, it seems to succeed with the warning:
```
awscli 1.18.170 requires botocore==1.19.10, but you'll have botocore 1.17.40 which is incompatible
```

**Comment by kdaily** [comment]
Hi @dazza-codes,

AWS Lambda has the following documented versions of the AWS Python SDK, `boto3`:

https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html

It is not recommended to have `boto3` and the AWS CLI installed in the same environment for exactly the reason you're noting - they may not share the same `botocore` version, which will end up with the incompatibility that you are discovering. To assure compatibility you would have to install the AWS CLI version that has the same underlying dependency of `botocore==1.17.40`, which is `awscli==1.18.117` (https://github.com/aws/aws-cli/blob/1.18.117/setup.py#L27).

What are you intending to accomplish with the AWS CLI in your Lambda runtime environment that you can't do with the `boto3` SDK?

**Comment by dazza-codes** [comment]
Bump

**Comment by kdaily** [comment]
Hi @dazza-codes,

Did you see my previous comment? I posed a couple of questions for you. Thanks!

https://github.com/aws/aws-cli/issues/5697#issuecomment-721408224
