### ISSUE TITLE
Add support for defaulting to GovCloud endpoints

### ISSUE THREAD

**Issue by aiyengar2** [aws/aws-cli#5700]
**Is your feature request related to a problem? Please describe.**
A user setting up AWS GovCloud via the AWS CLI seems to need to provide `--endpoint` and possibly `--region`  for every single request they make to different services.

**Describe the solution you'd like**
It would be nice if it were just possible to set a value that says the current credentials are used for GovCloud (e.g. `AWS_USE_GOVCLOUD`) once as part of `aws configure` and have the endpoints for each service automatically be defaulted to the correct GovCloud service endpoint documented in https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html. 

It would also be nice if, in general, there was a programmatic way to set service endpoint configurations in general so that you don't have to keep supplying `--endpoint`.

**Describe alternatives you've considered**
Documentation somewhere that can explain the process of using the AWS CLI for GovCloud, since the current docs don't seem to cover that use case.

**Additional context**

**Comment by kdaily** [comment]
Hi @aiyengar2,

You should be able to set your region to a GovCloud region and the CLI will determine the endpoints for you. Have you tried using either an environment variable or a configuration parameter to set your region to one of `us-gov-west-1` or `us-gov-east-1`? You can read about your options for configuring the region here:

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

Regarding configuring specific endpoints, there is an existing issue related to this: #1270

**Comment by aiyengar2** [comment]
Ah that works! Thanks @kdaily .

Closing out this issue.
