### ISSUE TITLE
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/send-message.html#examples

### ISSUE THREAD

**Issue by manuelh2410** [aws/aws-cli#5717]
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/send-message.html#examples

Input file (send-message.json):

{
  "City": {
    "DataType": "String",
    "StringValue": "Any City"
  },
  "Greeting": {
    "DataType": "Binary",
    "BinaryValue": "Hello, World!"
  },
  "Population": {
    "DataType": "Number",
    "StringValue": "1250800"
  }
}

====
 Is incorrect. 
Running the command as indicated in the current version of the documentation, yields : 

C:\>aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/"aws account ID #" /manuel_Queue --message-body "testmessageaws" --delay-seconds 10 --message-attributes "file://D:/message.json"

Invalid base64: "Hello, World!"

=== 

  "BinaryValue": "Hello, World!", should be   "StringValue": "Hello, World!"

=== 
After making this change, the command succeeds without issue.

**Comment by kdaily** [comment]
Thanks for the find, @manuelh2410!

**Comment by manuelh2410** [comment]
closing issue
