### ISSUE TITLE
Have a minimal installation package for CI/CD

### ISSUE THREAD

**Issue by hc-danieltiziani** [aws/aws-cli#5725]
**Is your feature request related to a problem? Please describe.**
aws-cli installation package includes too many unnecessary files for CI/CD usage.

**Describe the solution you'd like**
Have a stripped down version to be used on CI/CD (without documentation/examples/etc).

**Comment by kdaily** [comment]
Hi @hc-danieltiziani, looking into this.

**Comment by kdaily** [comment]
The examples themselves are about 18MB may be straightforward to exclude. However, the documentation comes from API models in JSON files from `botocore` which are 38MB, and I'm not sure how easy it would be to support removing the documentation from them before building.

Marking as needs more discussion. If you have more data on the size/time/drawbacks of the current size of the AWS CLI, that would be of interest!

**Comment by hc-danieltiziani** [comment]
Hi @kdaily , I thought it was simpler, because I'm trying to to optimize the usage of a CI, and as it's billed by execution time, anything smaller would help, and I was noticing a lot of files that I though it could be discarded. So if it's a bigger issue, nevermind, just thought this usecase would benefit others :-) 

The bundle I'm basing my comments is this one: [awscli-exe-linux-x86_64.zip](https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip)

**Comment by ermik** [comment]
Was there any progress on lightweight CLI distro?
