### ISSUE TITLE
cannot change route53 hosted zone entry from aws cli

### ISSUE THREAD

**Issue by Yo71MUd2gEu5** [aws/aws-cli#5739]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Hello, i'm trying to change a hosted zone DNS entry from aws cli (from debian)
an entry has routing type `Multivalue answer`
I am typing the command from shell:
aws route53 change-resource-record-sets --hosted-zone-id "<id>" --change-batch file:///root/test_commit2.json

test_commit2.json is the following:
{
      "Changes":[
        {
          "Action":"UPSERT",
          "ResourceRecordSet": {
            "ResourceRecords": [
                {
                    "Value": "127.0.0.10"
                }
            ],
            MultiValueAnswer": true,
            "TTL": 60,
            "Name": "pool.domain.local.",
            "Type": "A",
            "SetIdentifier": "s2.domain.local",
            "HealthCheckId": "<id>"
          }
        }
      ]
}

The output is the following:

Parameter validation failed:
Unknown parameter in ChangeBatch.Changes[0].ResourceRecordSet: "MultiValueAnswer", must be one of: Name, Type, SetIdentifier, Weight, Region, GeoLocation, Failover, TTL, ResourceRecords, AliasTarget, HealthCheckId, TrafficPolicyInstanceId

As following this documentation (https://docs.aws.amazon.com/cli/latest/reference/route53/change-resource-record-sets.html) the "MultiValueAnswer" parameter is located in "ResourceRecordSet", not in Name, Type, SetIdentifier, Weight, Region, GeoLocation, Failover, TTL, ResourceRecords, AliasTarget, HealthCheckId, TrafficPolicyInstanceId.

**Platform/OS/Hardware/Device**
Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux
awscli version 1.11.13-1

**Comment by kdaily** [comment]
Bi @Yo71MUd2gEu5,

You're running quite an old version of the AWS CLI. It's likely that the model has changed since then. If you use a more recent version, do you encounter the same error?

**Comment by Yo71MUd2gEu5** [comment]
@kdaily Yes, i've upgraded to the latest version, and the problem has gone.
