### ISSUE TITLE
RDS  --vpc-security-group-ids does not support multiple groups

### ISSUE THREAD

**Issue by motilevy** [aws/aws-cli#574]
I used to use this command with the old RDS tools: 

```
rds-modify-db-instance myinstance --region=us-west-1 --vpc-security-group-ids sg-one, sg-two
```

When trying to apply the same command using "aws rds" it fails: 

```
aws rds modify-db-instance --db-instance-identifier myinstance --vpc-security-group-ids sg-one, sg-two
```

with the following : 

```
A client error (InvalidParameterValue) occurred when calling the ModifyDBInstance operation: Invalid security group , groupId= sg-one, sg-two,, groupName=.
```

running the command with a single group works fine: 

```
 aws rds modify-db-instance --db-instance-identifier myinstance --vpc-security-group-ids sg-one  
```

**Comment by mikebiglan** [comment]
Worked for me as well. Thanks! The AWS docs here: http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/CLIReference-cmd-CreateDBInstance.html 
are incorrect with this example:
 --vpc-security-group-ids sg-e763f78e, sg-e0690405

This should be space-separated, not comma-separated.
