### ISSUE TITLE
incorrect mime type for WebAssembly files!

### ISSUE THREAD

**Issue by mihaiav** [aws/aws-cli#5743]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The aws cli sets an incorrect mime type for web assembly files (.wasm) . 
Currently it is set to  "`binary/octet-stream`"
It should be "`application/wasm`"

**SDK version number**
latest aws cli 2.x
**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @mihaiav,

What command are you using where the MIME type is not set correctly?

**Comment by mihaiav** [comment]
@kdaily  i use `cp` command to copy recursively a directory.

**Comment by kdaily** [comment]
Can you please provide the debug logs when you run this command? Thanks!

**Comment by kdaily** [comment]
Hi @mihaiav,

Looks like this might be the same as #1249.

**Comment by mihaiav** [comment]
aws cli would be more useful if it would handle the mime type internally freeing the user from dealing with fragmented implementations of mime.types. Perhaps this issue should be labelled as a feature request/improvement.

**Comment by kdaily** [comment]
Hi @mihaiav, #1249 covers this use case and is a feature request. There is no current plan to change how the CLI handles MIME types. If you have a suggestion or want to provide further feedback, please comment on that issue. Thank you!
