### ISSUE TITLE
s3 sync with client-side encryption

### ISSUE THREAD

**Issue by perost-l14** [aws/aws-cli#5748]
**Describe the solution you'd like**
Hi. s3 sync is really great. However, I want to use it for backup and for that I need client-side encryption. If I had that, s3 sync would cover my needs and I did not have to complicate matters involving other software. Furthermore, I would know how to restore data from any platform; I.E. not be dependent upon the lifecycle of the backup software.

I envision --cse-c AES256 and --cse-c-key similar to --sse-c and --sse-c-key.

For completeness, I guess --cse-c-copy-source and --cse-c-copy-source-key should be added as well.

**Describe alternatives you've considered**
The alternative is to run some other software.

**Additional context**
n/a
This is a copy of #3168. I tried to reopen it with a fresh comment, but that did not change its status.

**Comment by kdaily** [comment]
Hi @perost-l14, there is still an open feature request at https://github.com/aws/aws-cli/issues/1686 - is there something different that you need? I appreciate the extra details about what you would like to see. Can you add those things to #1686 if it's in addition to that original request? Thanks!
