### ISSUE TITLE
Add Amazon Managed Workflows for Apache Airflow

### ISSUE THREAD

**Issue by gpongracz** [aws/aws-cli#5752]
Please add Feature - Amazon Managed Workflows for Apache Airflow 

I would like to be able to automate the Amazon Managed Workflows for Apache Airflow service with Cloudformation (v1 & v2)

I am running Apache Airflow on ECS / EC2 but would like to have a more simple solution available for small data teams to be able to easily self administer.

**Comment by kdaily** [comment]
Hi @gpongracz, it looks like this was added to `botocore` yesterday:

https://github.com/boto/botocore/commits/develop/botocore/data/mwaa/2020-07-01/service-2.json

**Comment by kdaily** [comment]
This should be available for use as of AWS CLI version 1.18.185.

**Comment by gpongracz** [comment]
Thank you, I have checked cli v2 and am unable to locate could you also pls consider delivering this in the near future?

**Comment by nkazarian-spokeo** [comment]
Ditto, works on latest `v1` of the CLI, but not `v2`...when can we expect this to arrive on the latter?

**Comment by kdaily** [comment]
Hi @nkazarian-spokeo and @gpongracz - I can see this in the `botocore==v2` models (https://github.com/boto/botocore/commit/793a2a69daa1a9286c419c8c7d896b2da1965837). I tried with the version I had installed, and it's available:

```
$ aws --version
aws-cli/2.1.10 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off
$ aws mwaa help
MWAA()                                                                  MWAA()



NAME
       mwaa -

DESCRIPTION
       This  section  contains the Amazon Managed Workflows for Apache Airflow
       (MWAA) API reference documentation. For more information, see  What  Is
       Amazon MWAA? .

AVAILABLE COMMANDS
       o create-cli-token

       o create-environment
....
```
