### ISSUE TITLE
Warn when a access/secret key contains a whitespace

### ISSUE THREAD

**Issue by jerrinot** [aws/aws-cli#5755]
**Is your feature request related to a problem? Please describe.**
When configuring AWS credentials it's easy to accidentally add an extra space into a secret/access key. 
When this happens then obviously AWS CLI will not work. It will produce an error which is not very helpful:
```
Error: checking AWS STS access – cannot get role ARN for current session: IncompleteSignature: '/20201125/us-east-1/sts/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=<credentials> /20201125/us-east-1/sts/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=<signuture>
	status code: 400, request id: <request id>
```
I am assuming people routinely copy and paste key. It's easy to accidentally add an extra space during this process hence this must be a rather common problem. [This issue](https://github.com/aws/aws-sdk-go/issues/289) confirms it. 

**Describe the solution you'd like**
It would be nice if AWS CLI printed a warning when it detects a whitespace in a key. 

**Describe alternatives you've considered**
AWS CLI could print the warning just when the API returns 400 (and a key contains a space)
or
After a failure AWS CLI could hint which credentails were used. In my case there was no space in a credential file, but in `AWS_ACCESS_KEY_ID` env. variable which has a priority over the file. I was checking the credentials file without realizing it was not used at all. I forget I had (mis-)configured the `AWS_ACCESS_KEY_ID` env. variable in the past. 

**Additional context**
This will make AWS CLI more pleasant to use.

**Comment by kdaily** [comment]
Hi @jerrinot,

This (and similar) issues have come up before, and it's unlikely that we would raise an error or warning specific to this response. However, it's an understandable mistake to make! The ability to check your current setup to identify issues would be useful. It could be a `aws configure validate` command where your current CLI configuration would be checked. Marking this as needs discussion.
