### ISSUE TITLE
Error displayed when BASH_XTRACEFD is set

### ISSUE THREAD

**Issue by AAAlexandre** [aws/aws-cli#5757]
I haven't yet pinned down which version made this problem appear but here is the problem:

```
bash $ exec 42>xtrace.out
bash $ export BASH_XTRACEFD=42
bash $ aws --version
/bin/sh: BASH_XTRACEFD: 42: invalid value for trace file descriptor
/bin/sh: BASH_XTRACEFD: 42: invalid value for trace file descriptor
aws-cli/1.18.39 Python/3.6.10 CYGWIN_NT-6.1-7601/3.1.7-340.x86_64 botocore/1.15.39
bash $
```

Version 1.14 does not have the error messages, version 1.18 and all future versions including 2.* have it.

Could you please unset BASH_XTRACEFD before internally calling /bin/sh?
Or any alternative you can think of?

Thanks!

**Comment by kdaily** [comment]
Hi @AAAlexandre, can you describe what you are trying to accomplish? I'm not familiar with this environment variable. Thank you!

**Comment by AAAlexandre** [comment]
Hello.

https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-BASH_005fXTRACEFD
BASH_XTRACEFD is just a way to tell bash which file descriptor to use for the xtrace (set -x).
/bin/sh uses it as well (because /bin/sh is emulated by bash) and will try to output to it, but since the aws command does not forward the open file descriptors to /bin/sh, it displays an error message.

What I am trying to achieve is to use BASH_XTRACEFD for my program and not have aws display error messages when I do.

**Comment by AAAlexandre** [comment]
Well, it looks like the issue is fixed in cli version 2 so this can be closed

**Comment by Camusensei** [comment]
Precision:
aws-cli/2.0.60 still suffers from the issue
aws-cli/2.3.3 doesn't.

So it must have been fixed at some point inbetween these revisions.
