### ISSUE TITLE
[Bug] --cli-connect-timeout and max_attempts are dysfunctional

### ISSUE THREAD

**Issue by Sjaak01** [aws/aws-cli#5763]
Hello

AWS CLI v2

--cli-connect-timeout and max_attempts are dysfunctional and don't actually do anything. On top of that it seems to default behavior of the cli when it cannot connect to a s3 bucket is to just wait endlessly.

How to reproduce
add max_attempts = 1 (or whatever number you want) to the config
Block port 443 on your firewall

aws s3 --cli-connect-timeout 1 myfile s3://bucket/myfile will take 12 ~ 13 seconds to complete.

**Comment by kdaily** [comment]
Hi @Sjaak01,

Can you provide debug logs to help me determine what's causing this behavior? Thanks!
