### ISSUE TITLE
Introduce new command called "aws login" to enable the user to login with username and password

### ISSUE THREAD

**Issue by SARAVANA1501** [aws/aws-cli#5784]
**Is your feature request related to a problem? Please describe.**
- We can configure credential for aws SDK in so many ways, but non of them allowed me to login use my username and password, like this: https://pypi.org/project/awscli-login/
I believe this is basic functionality of aws cli.

**Comment by kdaily** [comment]
Hi @SARAVANA1501,

Thanks for posting. That plugin works with the AWS plugin system, and is specific for using a SAML Identity Provider (IdP). Is this the feature you're requesting?

**Comment by SARAVANA1501** [comment]
yes, My company using federation authentication system, but we are not allowed to generate programatic key and secret to login aws sdk. Every time we are using some script to do login and save the key in "~/.aws/credentials". For the same case Azure providing better experience in its "az login" command.

**Comment by SARAVANA1501** [comment]
@kdaily Any update on this?

**Comment by kdaily** [comment]
@SARAVANA1501,

The AWS CLI already supports single sign-on (SSO) functionality. Does this satisfy your use case?

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

Users have also used browser-based authentication methods using a credential process as described here. They use JavaScript to return credentials in the appropriate format.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

**Comment by SARAVANA1501** [comment]
Thanks, I went through the document, We are using federation auth system provided by Azure AD, I am not sure how to configure sso on aws cli v2.

**Comment by davidkhala** [comment]
single sign-on (SSO) seems like a workaround but still not seeming-less smooth

**Comment by tim-finnigan** [comment]
AWS IAM Identity Center is now the successor to SSO per this documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html.

@SARAVANA1501 you mentioned using Azure AD, so I think this is the specific documentation you should refer to: https://docs.aws.amazon.com/singlesignon/latest/userguide/azure-ad-idp.html. 

Please let us know if that addresses your use case or if there's anything you wanted to follow up on regarding this. Thanks!
