### ISSUE TITLE
Using ImageConfig Causes SUPERNOVA Launch, Runtime.InvalidEntrypoint Errors

### ISSUE THREAD

**Issue by metaskills** [aws/aws-cli#5785]
While using the latest version of AWS SAM with `sam init` for a Ruby 2.7 container project I noticed that SAM's `template.yaml` file has this section commented out and mentions how you can override the `CMD` in the Dockerfile. This option was attractive for me for reasons. 

```
ImageConfig:
  Command: ['app.lambda_handler']
```

However, I have found that once you do this in our your `AWS::Serverless::Function` and deploy, your entire function is pretty much broken. Errors will be shown like this in CloudWatch.

```
SUPERNOVA Launch error: Couldn't find valid bootstrap(s): [app.lambda_handler] Entrypoint: [] Cmd: [app.lambda_handler] WorkingDir: [/var/task]
{
  "errorMessage": "RequestId: 68c820b5-b141-4d00-bdda-91acda1c74cf Error: Couldn't find valid bootstrap(s): [app.lambda_handler]",
  "errorType": "Runtime.InvalidEntrypoint"
}
```

Removing `ImageConfig` from `template.yaml` and redeploying will not help!!! The configuration is sticky.

<img width="1105" alt="Screen Shot 2020-12-04 at 4 23 11 PM" src="https://user-images.githubusercontent.com/2381/101216847-3cc7ad00-364e-11eb-9ca6-61bf28f2851f.png">

However, I did learn after a lot of trial and error that I can use the Lambda GUI to remove the `CMD override` and the function will start to work again. So unless I did some really wrong, the `ImageConfig` `Command` option looks to be completely broken, at least for me in Ruby 2.7 runtime. Might be for all runtimes tho? I have not checked.

**Comment by kdaily** [comment]
Hi @metaskills,

This repository is for the AWS CLI, not the AWS SAM CLI (confusing, I know). I'll see if I can transfer this issue over to the right place (https://github.com/aws/aws-sam-cli/issues).

**Comment by kdaily** [comment]
Unfortunately, I don't have the permissions to transfer this issue. Could you please re-open at that repository? Thanks!

**Comment by metaskills** [comment]
Sorry... https://github.com/aws/aws-sam-cli/issues/2453

**Comment by metaskills** [comment]
Thank you all! Sorry, my brain is MUSH after dealing with this issue for a few days. Appreciate all y'all do!!!!
