### ISSUE TITLE
Support local AWS::ECS::TaskDefinition EnvironmentFile in `cloudformation package`

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-cli#5794]
**Is your feature request related to a problem? Please describe.**

deploying ECS tasks currently involves juggling between cloudformation & non-cloudformation deployment steps in order to use EnvironmentFiles

**Describe the solution you'd like**

[aws cloudformation package](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/package.html) currently handles local files for a bunch of parameters.  Adding upport for [AWS::ECS::TaskDefinition EnvironmentFile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-environmentfile.html) would simplify ECS task deployment

**Describe alternatives you've considered**

using `Environment` on `AWS::ECS::TaskDefinition ContainerDefinition` to inline the whole file, in a way that is not very re-usable for test automation, rather than using `EnvironmentFiles`

**Comment by kdaily** [comment]
Thanks for the feature request, @hauntingEcho. Looks like this is a duplicate:

https://github.com/aws/aws-cli/issues/5479

Can you make any further comments on that issue, please? Thanks!

**Comment by hauntingEcho** [comment]
good catch - thanks!
