### ISSUE TITLE
aws s3 sync keeps running after "download failed" due to "Error when retrieving credentials"

### ISSUE THREAD

**Issue by alexklibisz** [aws/aws-cli#5796]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I have a job that runs on Kubernetes on EC2 and uses `aws s3 sync` to sync about 500GB from S3 to a local volume.
Occasionally I see errors like this:

```
download failed: s3://foo/bar to local/foo/bar Error when retrieving credentials from iam-role: Credential refresh failed, response did not contain: access_key, secret_key, token, expiry_time 
```

But the sync keeps running.

I'm using KIAM to resolve the credentials, and I've previously seen it occasionally failing to resolve credentials. 
I know I can set some [credential configurations](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials) that tell the CLI to retry the credential request. This usually works. 

But it seems like a bug that the program would keep running after this kind of error. It's clearly saying that it didn't download and sync the specific file, which seems like a clear error to me.

I'd at least like to know if there is a way to tell the CLI to exit immediately when it encounters this?

**SDK version number**

```
# aws --version
aws-cli/1.16.302 Python/3.6.9 Linux/5.4.0-1029-aws botocore/1.13.38
```

**Platform/OS/Hardware/Device**

Kubernetes on EC2, built using Kops.

**To Reproduce (observed behavior)**

The actual command I'm calling is just:
```
aws s3 sync --no-progress s3://$bucket/$prefix . 
```
If you want a full repro, you'd need to find a way to invalidate the credentials while running the program above.
A sometimes-flaky KIAM deployment seems to do the trick.

**Expected behavior**

Sync should exit with non-zero code if it fails to sync.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @alexklibisz, thanks for posting.

I'm not familiar with KIAM. How do you have the AWS CLI configured to get the credentials? It would help to see the output when it fails using `--debug`.

**Comment by alexklibisz** [comment]
> Hi @alexklibisz, thanks for posting.
> 
> I'm not familiar with KIAM. How do you have the AWS CLI configured to get the credentials? It would help to see the output when it fails using `--debug`.

Hi, thanks. I'm not 100% certain how KIAM works either. We basically add an annotation to the k8s pod with our AWS IAM Role, and then KIAM uses that to authorize AWS requests made from the pod. I'll re-run it with --debug and post back.

**Comment by kdaily** [comment]
Thanks! Marking as `response-requested` so I'll know when you get that information.

**Comment by kdaily** [comment]
Sounds good, thanks for the update @alexklibisz!
