### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify only with userdata

### ISSUE THREAD

**Issue by Rinzler081** [aws/aws-cli#5799]
So I created my own vanilla centos image and installed the aws cli tools. All commands including s3 work fine as either ec2-user or root.

My issue: For some reason only when I launch a server, in the user data I'm doing just a simple aws s3 cp command I get the ssl_verify_certificate error.

Understand userdata runs as root. I've reinstalled the tools still no same issue. Any help would be appreciated

Running Centos 7.9

**Comment by kdaily** [comment]
Hi @Rinzler081,

I'd need to see some logs when this fails. Generally this is when you have a certificate in your chain that is not valid. Please re-run and provide the output with `--debug` added to the commands that fail.
