### ISSUE TITLE
Respect user conventions

### ISSUE THREAD

**Issue by monodhs** [aws/aws-cli#5802]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I have investigated the code
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

For decades, there have been conventions on all serious platforms in place that allow
the battle-hardened and educated user to manage application data the way they see fit
and know best, supporting their individual data management policies and practices.
Some of those conventions are rudimentary or archaic even, and some indeed
empower the user; this issue is solely about the latter.

In the Linux and the open source BSD worlds, which are distinct from what's by the
general public referred to as "Unix" and, if by sheer luck, POSIX even, there exists a
standard called the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which, contrary to what the origin
of the specification might suggest, all self-respecting command line tools in these worlds
adhere to.  The very [Git](https://www.kernel.org/pub/software/scm/git) SCM happens to be a prime example of such a tool.

This issue is to raise awareness about the specification and is asking for inclusion of all
users that make use of that specification into the communiy of awscli users.

**SDK version number**

This issue applies to all versions.

**Platform/OS/Hardware/Device**

Any Linux and open source BSD OS of the last decade; this is purely a software matter.

**To Reproduce (observed behavior)**

`/usr/lib/python3/dist-packages/botocore> grep -RE "\.aws(/|')" *.py`

**Expected behavior**

Evaluating and semantically adhering to the environment variables as defined
in the above referenced specification in order to obtain user-specific configuration
data and store user-specific application state -- including cached contents such
as SSO objects.

**Logs/output**

n/a

**Additional context**

**Comment by kdaily** [comment]
Hi @monodhs,

Thanks for your comment. Can you clarify, maybe with a concrete example, of what would change with this convention? What is it about the current implementation of configuration that is not working?

It's also important to note that the AWS CLI is not specifically for Linux/BSD users, but also for Mac OSX and Windows. Also, configuration options can be set in a number of ways - through environment variables, configuration files, and fetched remotely via IMDS.

**Comment by kdaily** [comment]
Hi @monodhs,

I found that this is a duplicate: #2433

This would be a very large change for existing AWS CLI users, and would be a convention that would need to be followed by all AWS SDKs and Tools.

Could you please register your concerns on #2433 - I'm going to move that issue to the central AWS SDK issue tracking repository (https://github.com/aws/aws-sdk).

Thanks again!

**Comment by Jolg42** [comment]
Note: I did find the new issue (still open) at https://github.com/aws/aws-sdk/issues/30
