### ISSUE TITLE
cloudformation "package" command does not rewrite TemplateURL

### ISSUE THREAD

**Issue by jpdev33** [aws/aws-cli#5808]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws cloudformation package` does not rewrite local TemplateURL references in nested stacks to S3 references.

**SDK version number**
2.1.9

**Platform/OS/Hardware/Device**
What are you running the cli on?
Ubuntu

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

1. `test.json`

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Resources":
	{
		"Nested":
		{
			"Type": "AWS::CloudFormation::Stack",
			"TemplateURL": "nested.json"
		}
	}
}
```

2. `aws cloudformation package --template-file test.json --s3-bucket my-bucket --use-json`

**Expected behavior**

Expect "TemplateURL" in output to get re-written as S3 reference to "my-bucket/nested.json".  Actual output is unchanged from input template.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
It took me a while and a pair programming with another engineer to realize that the format is not quite right - you're missing the `Properties` parameter, which is required. It should be:

```
{
"AWSTemplateFormatVersion": "2010-09-09",
"Resources": {
    "Nested": {
        "Type": "AWS::CloudFormation::Stack",
        "Properties": {
            "TemplateURL": "nested.json"
        }
    }
}
```

**Comment by jpdev33** [comment]
Had a feeling I was doing something stupid. Thank you!
