### ISSUE TITLE
Can't sync to Windows when colon in file name (cont..)

### ISSUE THREAD

**Issue by aleemerichxpi** [aws/aws-cli#5813]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Windows 10

**Describe the question**

Hello. I am resuming the problem closed at [1154](https://github.com/aws/aws-cli/issues/1154) because I did not find anything that would solve the problem and I do not believe that it will be able to be solved without the involvement of the AWS CLI.

I have the same problem (I use Windows 10 and files with the same problem on S3). I believe that the AWS CLI could give the option of changing characters as when using the CP or SYNC command. If not, how to solve? If someone used any method and can share. I'm a layman on Linux, but I don't see how to solve this without the AWS CLI, does anyone have any other suggestions?

**Comment by kdaily** [comment]
Hi @aleemerichxpi,

Thanks for your post. This is a common issue on Windows, but not something that the CLI will manage due to unforseen impacts (for example, changing a two filenames to the same one because of different special characters could lead to overwriting files). The S3 documentation warns about this:

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys

> The following characters in a key name might require additional code handling and likely need to be URL encoded or referenced as HEX. Some of these are non-printable characters that your browser might not handle, which also requires special handling: 
> ...
> - Colon (":")

The solution is as stated there - either do not use these problematic characters in object names, or URL encode them.

**Comment by aleemerichxpi** [comment]
I dont understand. If there is a tool to be used on Windows, but there is a problem that is the environment of it that allows the limitation of Windows, what do we do? Do we cry? I cannot prevent the system from creating the name using this character. Exactly because AWS allows it. So I have nothing to do? In the text that was cited there is no alternative. I can't work with a tool that claims to be compatible with Windows? Sad that kind of response.

**Comment by aleemerichxpi** [comment]
I dont understand. If there is a tool to be used on Windows, but there is a problem that is the environment of it that allows the limitation of Windows, what do we do? Do we cry? I cannot prevent the system from creating the name using this symbol. Exactly because AWS allows it. So I have nothing to do? In the text that was cited there is no alternative. I can't work with a tool that claims to be compatible with Windows? Sad that kind of response.

**Comment by kdaily** [comment]
Hi @aleemerichxpi,

Thanks for your feedback. I understand the frustration, especially in the circumstance where external systems allow these names. However there are many things that can go wrong with this scenario. Another that has been mentioned previously (https://github.com/aws/aws-cli/issues/3130#issuecomment-364001673) would be how to do a round trip download and upload - if characters are converted, this would be problematic. For the best user experience, this would also be something that would need to be handled across all AWS SDKs - if you upload a file using one SDK or tool (like the CLI), the experience should be the same in others as well.

The comment mentioned above is from a similar issue that hasn't received much attention (https://github.com/aws/aws-cli/issues/3130). I will work on opening a tracking issue that describes it better to increase visibility and get more information about the impact on other users, and identify any other similar issues related. There is no planned change in behavior for this at the current time, though.

**Comment by aleemerichxpi** [comment]
Thanks for listening. But what if we broke the problem? Rather than attending to everything, was it done in parts? One idea: What if Windows users had the option to exchange problematic symbols only when copying to Windows? It wouldn't have to be via "SYNC", it could be via the CP command with a parameter or other specific option. There would be no need to predict the same scenario from Windows to AWS because it would not have this main problem (returning to AWS by changing symbols again could be thought of later).

If this were used widely, we could think of evolution, but at least we could get files on S3. The big question at the moment is that we have no way to do that about any alternative! There's no way I can get the files, you know? I have a plan on AWS, paid for storage and I can't get my data. This is a very important point that we cannot just ignore, right?

If you know of any solution along with the AWS CLI that will allow me to at least get my data, could you let me know? I really need to work with the data and I can't. Due to my work limitations, I cannot change the operating system.

Thank you again for your attention.

**Comment by jluo926** [comment]
Hi, ran into the exact same issue.
Is there any workaround to download the files programmatically currently?
