### ISSUE TITLE
aws_completer doesn't complete --profile=

### ISSUE THREAD

**Issue by seanorama** [aws/aws-cli#5815]
Confirm by changing [x] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Tab completion (aws_completer) does not complete `--profile=`.

**SDK version number**
```
$ aws --version
aws-cli/2.1.10 Python/3.9.0 Darwin/18.7.0 source/x86_64 prompt/off
```

**Platform/OS/Hardware/Device**
MacOS

**To Reproduce (observed behavior)**
Type `aws --profile=` and then attempt tab completion. Nothing happens.

Oddly, if you remove the `=` tab completion works. However, the `=` is required for the command.

**Expected behavior**
Profile name tab completion.

**Logs/output**

**Additional context**

**Comment by kdaily** [comment]
Hi @seanorama, I just tested on my Mac and it's working OK. The equal sign should not be used - all AWS CLI commands with multi-character parameter names (like `--profile`) use a space after the parameter.

**Comment by seanorama** [comment]
Well, my apologies. I had been using --profile= all this time, thinking it was required. Closing this. Apologies for the false alarm.

**Comment by kdaily** [comment]
No worries @seanorama, glad it's working for you now.
