### ISSUE TITLE
When running logs tail with a named profile referencing a different account, the auto-complete of log-groups is incorrect.

### ISSUE THREAD

**Issue by cdarlast** [aws/aws-cli#5820]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Using Version 2 of the CLI and the Auto Prompt Mode. When using a named profile with a role in a different account and auto prompt mode for the logs tail command, I am presented with the list of log-groups from the default account not the profile account. 

**SDK version number**
aws-cli/2.1.12 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off

**Platform/OS/Hardware/Device**
MacOS Catalina

**To Reproduce (observed behavior)**
Use the command:
`aws --profile <NAMED_PROFILE> logs tail` 

**Expected behavior**
I would expect to see  the list of log groups from the account referenced in the named_profile.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
This behaviour works as expected when using the EC2 stop-instances command with profiles and auto-prompt. 
( `aws --profile <NAMED_PROFILE> ec2 stop-instances --instance-ids` )

**Comment by cdarlast** [comment]
Further investigation on this shows the same issue with `ddb put` or `ddb select` which all have custom_completers.

**Comment by cdarlast** [comment]
The issue appears to incomplete feature development around retrieving the data from the server for the command.
https://github.com/aws/aws-cli/blob/v2/awscli/autocomplete/serverside/servercomp.py#L80-L82

**Comment by vz10** [comment]
Hi @cdarlast ,

this issue has been fixed in AWS CLI version 2.1.14, could you please try it out and let us know if you still experience this issue

Thank you

**Comment by cdarlast** [comment]
I have validated that this is now working as I expected it to work. Thanks.
