### ISSUE TITLE
Cannot find `aws rds start-db-instance-automated-backups-replication`

### ISSUE THREAD

**Issue by cyrusv** [aws/aws-cli#5821]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
aws-cli/2.1.7 Python/3.7.3 Linux/4.15.0-128-generic exe/x86_64.ubuntu.18 prompt/off

**Describe the question**
I see this in the docs: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/start-db-instance-automated-backups-replication.html
But I cannot find it in my aws cli:
```
➜  aws --version
aws-cli/2.1.7 Python/3.7.3 Linux/4.15.0-128-generic exe/x86_64.ubuntu.18 prompt/off
➜  aws vers
➜   aws rds  start-db-instance-automated-backups-replication

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:
```

I read the release notes, can't find any mention of it. Do I have the wrong version? Looking in the wrong place?

**Comment by kdaily** [comment]
Hi @cyrusv, you'll need to bump up at least one more version to `2.1.8` - those API features were added on 2020-12-04, and that release got them added. The documentation page always shows the most recent version. Upgrading to the most recent version will work for you too!
