### ISSUE TITLE
🐳 Publish Docker Image on ECR Public

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-cli#5836]
**Is your feature request related to a problem? Please describe.**

DockerHub implemented [rate limiting](https://www.docker.com/increase-rate-limits) recently which can cause problems when using the aws-cli docker image from DockerHub.

**Describe the solution you'd like**
[ECR Public Registries](https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/) were recently released which provides a free alternative to image pullers. https://gallery.ecr.aws/

The aws-cli docker image should be published to an ECR public registry and marked as verified. 

There are currently several aws-cli's uploaded to ecr public that do not appear official (lacking any Usage instructions and does not include version tags).  https://gallery.ecr.aws/?searchTerm=aws-cli

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kdaily** [comment]
Thanks for the feature request, @bwagner5. I agree having a verified image backed by AWS would help with user confidence in it's availability and stability especially with the recent changes to DockerHub.

**Comment by aittam** [comment]
I would love to see this, I came here exactly because I couldn't find this image on the public ECR.

**Comment by davivcgarcia** [comment]
Do we have any update on this?

**Comment by emersonf** [comment]
> Thanks for the feature request, @bwagner5. I agree having a verified image backed by AWS would help with user confidence in it's availability and stability especially with the recent changes to Docker Hub.

@kdaily any movement on this? We've just started moving over to AWS Public Gallery instead of Docker Hub, and it doesn't speak well for AWS' confidence in AWS Public that its own images aren't on there.

**Comment by DragonStuff** [comment]
It's really surprising that the official AWS CLI tooling is not hosted on ECR Public! Is there any movement on this issue?

**Comment by rlewkowicz** [comment]
@DragonStuff for better or worse, I'm using 
`public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.10.0` 
I had issues with the bitnami image (which btw bitnami is a highly respected community player, that image might work for you)  but this works for me

**Comment by rlewkowicz** [comment]
I lied, that didn't work for us. This honestly feels insane. Maybe I'm starting to feel entitled by the ease of public internet infrastructure, but this feel literally insane that I cannot find an official aws cli image from  amazon on a non docker source

**Comment by kdaily** [comment]
Hi @rlewkowicz and @DragonStuff,

It's on the team's radar, but no ETA as to when it would be completed.

**Comment by KeenanLawrence** [comment]
@kdaily 
I'm failing to understand the reason as to why the `aws-cli` image isn't already published on public ECR. It's an AWS tool, so it should be accessible from an AWS registry, no? I see that Bitnami is a verified account and they've published an image, but I'd much prefer it to be published by AWS themselves.

Can you perhaps explain _**why**_ it isn't already published to public ECR? This issue has been open for over a year!

**Comment by andreaschiappacasse** [comment]
This is a very needed feature, I am ending up in creating my own custom image on a private ecr, but using an official AWS image would be obviously beneficial.

**Comment by jbg** [comment]
FYI, you can use https://github.com/onfido/ecr-mirror to mirror any image, such as this one, into your private ECR repo. But in the case of this image I'd recommend building a custom one anyway. This image runs as root unnecessarily ([issue](https://github.com/aws/aws-cli/issues/5120) just turned 2 years old), is pretty huge, and seems pretty minimally maintained.

**Comment by InbarRose** [comment]
this is somthing that really should exist.
mirroring this image is not something we want to maintain.

**Comment by moltar** [comment]
Mind-boggling that Amazon does not publish their own images on their own registry.

**Comment by ji8k-fjt** [comment]
I noticed aws-cli docker image on ECR public registry by AWS that is marked Verified.
https://gallery.ecr.aws/aws-cli/aws-cli

**Comment by tim-finnigan** [comment]
Hi all - thanks for your patience. There is now documented support for an official AWS CLI v2 ECR Public image: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html (which can be found on ECR public via the [link](https://gallery.ecr.aws/aws-cli/aws-cli) mentioned above). The team is planning to write a blog post soon for an official announcement on this.
