### ISSUE TITLE
documentation should allow us to set a default version

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-cli#5837]
**Is your feature request related to a problem? Please describe.**
Every time I google something related to the CLI, it takes me to the v1.x version of the documentation

**Describe the solution you'd like**
I'd like us to be a be able to choose a default so that when we return to the docs it is already in the version we prefer. i.e. always show version 2.x of the docs. This would be much like a lot of the Cloudformation docs that allow you to choose between yaml/json.

**Comment by kdaily** [comment]
Hi @kidbrax, this would be a nice UX improvement. Currently you can switch between them only on a specific API action page.

**Comment by kdaily** [comment]
D20100209
