### ISSUE TITLE
s3api list-parts --starting-token does not accept input from CLI

### ISSUE THREAD

**Issue by anarchy9388** [aws/aws-cli#5841]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Bug in object type when parsing --starting-token for list-parts operation

**SDK version number**
`aws-cli/2.1.14 Python/3.7.3 Linux/4.19.121-linuxkit docker/x86_64.amzn.2 prompt/off
`
**Platform/OS/Hardware/Device**
What are you running the cli on?
SLES12.4

**To Reproduce (observed behavior)**
Use --starting-token with list-parts API
```
PS C:\Users\mendem> docker run --rm -it -v ~/.aws:/root/.aws amazon/aws-cli s3api list-parts --bucket s3-test-mike --key mpu.test --upload-id Bpo.3GybzNdfudEf3lC9b.ddAbS2fYqtVsX.kJxUrYt.nsC3MDWPD21ZBSvYBe5IMF7Qxos0Uxii4pu0ONOWtt4P0SI4s1HIZJN8HuwYsHo- --starting-token 1

Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: 1, type: <class 'str'>, valid types: <class 'int'>
PS C:\Users\mendem>
```

**Expected behavior**
It should take the unicode object passed in and convert to int/long type before passing to botocore.
this should probably be done in the paginate.py that is already customizing paginate from botocore

**Logs/output**
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 530, in __call__
    call_parameters, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 651, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/local/lib/python2.7/site-packages/awscli/clidriver.py", line 671, in _display_response
    formatter(command_name, response)
  File "/usr/local/lib/python2.7/site-packages/awscli/formatter.py", line 69, in __call__
    response_data = response.build_full_result()
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 298, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: , type: <type 'unicode'>, valid types: <type 'int'>, <type 'long'>
2020-12-23 23:31:38,478 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: , type: <type 'unicode'>, valid types: <type 'int'>, <type 'long'>
```

**Comment by rrhodes** [comment]
The starting token for the above example doesn't look like what I would expect in a multi-part upload. Reading the [pagination documentation for S3](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html), I would be looking for a token like `eyJNYXJrZXIiOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAxfQ==` rather than `1`.

Testing both these values with my own setup, the former works as expected on the latest version of the CLI, whilst the latter reproduces the error trace you have shared above. Can you confirm the starting token in your example is correct and how you fetched that value?

**Comment by kdaily** [comment]
Hi @anarchy9388,

@rrhodes is correct (thanks!). Here's the relevant bit from the `aws s3api list-parts` [documentation page](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-parts.html):

> `--starting-token` (string)
> 
> > A token to specify where to start paginating. This is the NextToken from a previously truncated response.
> > 
> > For usage examples, see [Pagination](https://docs.aws.amazon.com/cli/latest/userguide/pagination.html) in the *AWS Command Line Interface User Guide.*

**Comment by anarchy9388** [comment]
Ahh I see. the parameter I was needing is part-number-marker.
But it looks like there's no param for that in awscli.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html#API_ListParts_RequestSyntax

**Comment by kdaily** [comment]
Hi @anarchy9388,

This is because this API function has a paginator defined:

https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/paginators-1.json#L56-L69

So, you use the unified AWS CLI pagination parameters to interact with this. The other parameters will work, they just will not show up in the CLI documentation.

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html#cli-usage-pagination-serverside

**Comment by anarchy9388** [comment]
@kdaily 
Thanks for the details!
You can close this now, I'm troubleshooting non-aws S3 storage,.. 

I just need to send a request where the "part-number-marker" value is empty to reproduce an issue.

`part-number-marker=`
