### ISSUE TITLE
Add the option for a summary of activity message on storage commands

### ISSUE THREAD

**Issue by wedgef5** [aws/aws-cli#5852]
It would often be useful to know how many files were acted upon and it what way at the end of a storage (e.g. s3, glacier) command. For example, a summary message on an 's3 sync' might say something like "234 files (7.6 MiB) copied to destination. 321 (5.6 MiB) files deleted from source."

I know I could glean this information from the command's output, but it's a tad convoluted to either pipe the output to some other command or have a script to parse log output. It would be much cleaner to have the aws cli be able to furnish this information.

**Comment by kdaily** [comment]
Thanks for the feature request, @wedgef5!
