### ISSUE TITLE
neptune describe-db-instances returns docDB instances

### ISSUE THREAD

**Issue by danostro** [aws/aws-cli#5859]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
describe-db-instances returns docDB instances despite we dont have any neptune instance

**SDK version number**
aws-cli/2.0.40

**Platform/OS/Hardware/Device**
What are you running the cli on?
OS
**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @danostro,

You could have other Document DB instances that are not from Amazon Neptune. I would check in the AWS console in the  Amazon DocumentDB section.

**Comment by danostro** [comment]
Hi @kdaily 
Thank you for your response.
As you said we have number of Document dbs in our account.

How Neptune and documentDB are related?

**Comment by kdaily** [comment]
Hi @danostro,

See the caveat note at the top of the [documentation page](https://docs.aws.amazon.com/cli/latest/reference/neptune/describe-db-instances.html) for `aws neptune describe-db-instances`:

> ### Note
> 
> This operation can also return information for Amazon RDS instances and Amazon DocDB instances.

The `engine` parameter to `filters` can be used to determine which type of instance you want to list. The documentation for this section is incomplete. There is not a complete list of engines that can be used, and there is a section where an example command should be shown that is missing.

I will open this as an issue with the relevant docs teams to improve this. There are also no examples for this command, and this would be useful as well.

I will try to find out what the valid options are for `engine` (other than `neptune`).

**Comment by kdaily** [comment]
To get the neptune instances specifically, you can do:

```
aws2 neptune describe-db-instances --filters Name=engine,Values=neptune
```

To get DocumentDb instances, you can do:

```
aws2 neptune describe-db-instances --filters Name=engine,Values=docdb
```

I'm inquiring what other values are valid here.

**Comment by kdaily** [comment]
0544013888

**Comment by kdaily** [comment]
Hi @danostro,

While this behavior is possible, it's not suggested. Rather, each database service has it's own operation to describe instances. Each of these should have documentation on what engines are available for filtering, generally on the related `create-db-instance` operation, like [here for RDS](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-instance.html). For example:

For RDS Family:

```
aws rds describe-db-instances --filters Name=engine,Values=mysql 
```

For DocDB:

```
aws docdb describe-db-instances --filters Name=engine,Values=docdb 
```

For Neptune:

```
aws neptune describe-db-instances --filters Name=engine,Values=neptune
```

Keeping this as a documentation issue to improve the user experience with more details and better examples.

**Comment by kdaily** [comment]
I've let the documentation team know of the issue, closing this for now. Please open another issue if you are still having difficulty. Thanks for bringing it to our attention!
