### ISSUE TITLE
False positive SNS Topic create/delete API call results

### ISSUE THREAD

**Issue by haleksan** [aws/aws-cli#5864]
The subsequent execution of `create-topic` and `delete-topic` API calls for an SNS resource with identical parameters is not throwing an error saying that the resource is already created / does not exist. Unlike other AWS resources, these API calls always return a success exit code which is a false positive result. 

**Affected AWS CLI version:**
`(venv) % aws --version`                               
`aws-cli/1.18.113 Python/3.7.3 Darwin/19.3.0 botocore/1.17.31`

**CLI output for SNS CreateTopic API Call:**
`(venv) % aws sns create-topic --name my-little-dalek`
`{
    "TopicArn": "arn:aws:sns:us-east-1:ACCOUNT:my-little-dalek"
}`
`(venv) % aws sns create-topic --name my-little-dalek`
`{
    "TopicArn": "arn:aws:sns:us-east-1:ACCOUNT:my:my-little-dalek"
}`

**CLI output for SNS DeleteTopic API Call:**
`(venv) % aws sns delete-topic --topic-arn arn:aws:sns:us-east-1:ACCOUNT:my:my-little-dalek`
`(venv) % aws sns delete-topic --topic-arn arn:aws:sns:us-east-1:ACCOUNT:my:my-little-dalek`

**Comment by kdaily** [comment]
Hi @haleksan,

According to the documentation, these operations are idempotent, so this behavior is controlled by the server-side API and is expected.

For `create-topic` ([documentation](https://docs.aws.amazon.com/cli/latest/reference/sns/create-topic.html)):

> This action is idempotent, so if the requester already owns a topic with the specified name, that topic's ARN is returned without creating a new topic.

For `delete-topic` ([documentation](https://docs.aws.amazon.com/cli/latest/reference/sns/delete-topic.html)):

> This action is idempotent, so deleting a topic that does not exist does not result in an error.
