### ISSUE TITLE
workspaces  list-available-management-cidr-ranges token pattern exception

### ISSUE THREAD

**Issue by mjavadi** [aws/aws-cli#5866]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Unable to get the output of the command.

**SDK version number**
aws --version
aws-cli/1.18.213 Python/3.8.0 Darwin/19.6.0 botocore/1.19.53

**Platform/OS/Hardware/Device**
What are you running the cli on?
OSX Catalina.  can be reproduced in the console cloud shell as well

**To Reproduce (observed behavior)**
aws workspaces list-available-management-cidr-ranges --management-cidr-range-constraint 172.16.0.0/12

An error occurred (ValidationException) when calling the ListAvailableManagementCidrRanges operation: 1 validation error detected: Value 'b8eace04-787e-4eff-adfd-eb8845e6b47e' at 'nextToken' failed to satisfy constraint: Member must satisfy regular expression pattern: [A-Za-z0-9+/=]+

**Expected behavior**
Get a list of available mgmt cdirs

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @mjavadi,

Can you send full debug logs, removing any sensitive information like account numbers? Something's going wrong with the pagination operation (which is what `nextToken` is for) but I'd need to see more about the request and response to narrow it down. Thanks!

**Comment by mjavadi** [comment]
Hello @kdaily.  My apologies for the late reply.  Please let me know if the attached file is what you expect.  I did not remove any info as we use temporary keys and STS tokens.  I just added the --debug to the command.
[cli debug.txt](https://github.com/aws/aws-cli/files/5885165/cli.debug.txt)

Regards

**Comment by kdaily** [comment]
P43497690

**Comment by kdaily** [comment]
Hi @mjavadi, per the Workspaces team, this should be available now!

**Comment by mjavadi** [comment]
@kdaily Thank you very much. will get the latest cli and try later. I am sure it will work.
