### ISSUE TITLE
Documentation: use ids and table of contents

### ISSUE THREAD

**Issue by hcientist** [aws/aws-cli#5867]
**Is your feature request related to a problem? Please describe.**
Please make the docs more usable by adding `id`s to various sections of the resulting html.

**Describe the solution you'd like**
1. I would like the table of contents to include hyperlinks to jump down the very long page to the flag in question
    * e.g. in the [`dynamodb` Synopsis](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dynamodb/query.html#synopsis) I would like `--query-filter` to link to (a currently non-existent) id on the `--query-filter`'s paragraph (`<p>`).
1. I would like to be able to share a "deep link" to a particular cli flag or to a code example or whatever. 

**Describe alternatives you've considered**
N/A

**Comment by kdaily** [comment]
@hcientist, Thanks for the feedback! I would agree it would be useful, especially on long pages like DynamoDB. I'll pass this on to our docs team.
