### ISSUE TITLE
Fetch IP address of secondary adaptor (EC2)

### ISSUE THREAD

**Issue by jijojohn1985** [aws/aws-cli#5868]
Hi There,

I am trying to fetch our ec2 instance details using aws cli ec2 describe command. For some of our instance we have secondary network interface attached. With Ec2 describe query , how can i display both the IP address

This is the command i am using

aws ec2 describe-instances --query 'Reservations[].Instances[].[PrivateIpAddress, InstanceId, Tags[?Key=="Name"].Value | [0], State.Name, InstanceType, Placement.AvailabilityZone]' --output table

Thanks,
Jijo

**Comment by kdaily** [comment]
Hi @jijojohn1985, you'll need to look in the `NetworkInterfaces` field. Something like this:

```
aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId, NetworkInterfaces[].PrivateIpAddress]'
```

Hope this helps!

**Comment by s6-marct** [comment]
this api is better when filtering on a known secondary IP address:
```
aws ec2 describe-network-interfaces  \
    --filters "Name=addresses.private-ip-address,Values=X.X.X.X" \
    --query 'NetworkInterfaces[*].Attachment.InstanceId' \
    --output text
```
