### ISSUE TITLE
Feedback on describe-reserved-instances CLI reference - https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-reserved-instances.html

### ISSUE THREAD

**Issue by dineshrathee12** [aws/aws-cli#5869]
**Feedback on [describe-reserved-instances CLI reference](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-reserved-instances.html)**

It gives the data for a specific value such as **(# aws ec2 describe-reserved-instances --filters Name=end,Values='2021-06-11T13:16:59.000Z')**

`# aws ec2 describe-reserved-instances --filters Name=end,Values='2021-06-11T13:16:59.000Z'
{
    "ReservedInstances": [
        {
            "Duration": 31536000,
            "End": "2021-06-11T13:16:59+00:00",
            "FixedPrice": 976.6,
            "InstanceCount": 2,
            "InstanceType": "r3.xlarge",
            "ProductDescription": "Linux/UNIX (Amazon VPC)",
            "ReservedInstancesId": "1a3xxxxxxxxxxxxxxxxxxxxxxf",
            "Start": "2020-06-11T13:17:00+00:00",
            "State": "active",
            "UsagePrice": 0.0,
            "CurrencyCode": "USD",
            "InstanceTenancy": "default",
            "OfferingClass": "standard",
            "OfferingType": "Partial Upfront",
            "RecurringCharges": [
                {
                    "Amount": 0.05985,
                    "Frequency": "Hourly"
                }
            ],
            "Scope": "Region"
        },`

> But How to get data like for filter like Values greater than or less than xxxx End Value in RI ?  We need more examples in doc.

I think if we would like to use filters like **">" or "< "** , it is not available with our AWS CLI reference 
[+] [https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-reserved-instances.html](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-reserved-instances.html) ,

**Can use "jq" or a python code to achieve so ? If yes, will be great to add this to the CLI reference.**

**Comment by kdaily** [comment]
Hi @dineshrathee12,

This type of filtering for EC2 is performed server-side. You can also do client-side filtering using the `--query` parameter. You can read all about this type of filtering here:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter

A revamp of this content is in the works, so stay tuned and come back to the User Guide in the future for more examples.
