### ISSUE TITLE
mutual authentication

### ISSUE THREAD

**Issue by fdefilippo** [aws/aws-cli#5875]
Hi, Is there the possibility of using a client certificate to authenticate the connection? or there is a plugin that allows me to connect to an endpoint (reverse proxy) that implements client authentication (tls mutual auth)?

thnx  a lot.

**Comment by kdaily** [comment]
Hi @fdefilippo, can you describe more completely your use case and desired behavior? Thank you!

**Comment by fdefilippo** [comment]
Hi, I would like to have the ability to authenticate access to the bucket as well as with the accessKey/scretKey also the connection using x509 certificates, therefore, perform mutual authentication between client and server. Since the s3 engine I use (minio) does not allow it using a reverse proxy I could perform mutual authentication but obviously a client is also needed. Using the API I could implement it at the application level but I would like to use a client for batch processes, so i was wondering if there was an awscli plugin that would allow to use x509 certificates to authenticate the connection.

**Comment by tim-finnigan** [comment]
Isn't MinIO already doing this on their end? I was trying to understand this feature request and saw this related article: https://blog.min.io/certificate-based-authentication-with-s3/. @fdefilippo apologies if I'm not fully understanding your use case but if you can expand any further on what you're trying to do I think that would help. Although to answer your question there is not an AWS CLI plugin that I'm aware of for this purpose.
