### ISSUE TITLE
aws ec2 validation failed: Unknown parameter in BlockDeviceMappings[1].Ebs: "Throughput"

### ISSUE THREAD

**Issue by tossat** [aws/aws-cli#5888]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
If I use aws ec2 run-instances and create volumes via BlockDeviceMappings I get an error about my 'throughput' definition:

Parameter validation failed:
Unknown parameter in BlockDeviceMappings[1].Ebs: "Throughput", must be one of: DeleteOnTermination, Iops, SnapshotId, VolumeSize, VolumeType, KmsKeyId, Encrypted

**SDK version number**
aws-cli/2.0.29

**Platform/OS/Hardware/Device**
 Python/3.7.3 Linux/4.19.0-9-amd64 botocore/2.0.0dev33

**To Reproduce (observed behavior)**
Run AWS CLI 'aws ec2 run-instances --profile PROFILE --cli-input-json file://FILE.json' and define throughput in BlockDeviceMappings or use AWS SDK PHP doing the same.

**Expected behavior**
I expect this param is available in the API for all SDKs (personally PHP) and CLI.
If I read throught the latest API docs: https://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html. Throughput is still a valid param in BlockDeviceMappings.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
My cli-input-json file:
{
    "BlockDeviceMappings": [
        {
            "DeviceName": "/dev/sda1",
            "Ebs": {
                "DeleteOnTermination": true,
                "VolumeSize": 8,
                "VolumeType": "gp3"
            }
        },
        {
            "DeviceName": "/dev/sdb",
            "Ebs": {
                "DeleteOnTermination": true,
                "SnapshotId": "snap-01234567890123456",
                "VolumeSize": 8,
                "VolumeType": "gp3",
                "Throughput": 250
            }
        }
    ],
    "ImageId": "ami-0123456789abcdef0",
    "InstanceType": "t3a.small",
    "MaxCount": 1,
    "MinCount": 1,
    "SecurityGroups": [
        "sg1",
        "sg2"
    ],
    "EbsOptimized": true,
    "KeyName": "secret"
}

**Comment by kdaily** [comment]
Hi @tossat, 

The documentation page always shows the most recent version of the CLI, and much of it is auto-generated from a model of the API. Parameters for GP3 volume types were made available after the release you're using (`2.0.29`). Upgrade to the latest version of the CLI and you'll have them available.

**Comment by tossat** [comment]
Thx for your feedback. It works after an update.
Checked it with 'awscli' and 'aws-sdk-php'.

**Comment by kdaily** [comment]
Glad to hear, @tossat! Closing this, thanks!
