### ISSUE TITLE
AWS CodeArtifact cli does not accept package names with "@" signs

### ISSUE THREAD

**Issue by joechchung** [aws/aws-cli#5889]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I was trying to `list-package-versions` with a package name starting with an "@" sign but aws cli throws an error saying it doesn't match the regex.
I have a package in AWS CodeArtifact with the "@" prefix e.g. "@package/name" but the command fails the regex validator. From the expected Regex, it's not expecting an "@" sign. Can we add in all additional symbols that are possible when creating a CodeArtifact package name please?

**SDK version number**
```
aws-cli/2.1.20 Python/3.9.1 Darwin/20.2.0 source/x86_64
```

**Platform/OS/Hardware/Device**
What are you running the cli on?
MacOS Big Sur 11.1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Run: 
```
aws codeartifact list-package-versions --domain <domain> --repository <repository> --format pypi --package @package/name
```

**Expected behavior**
I expect the cli to return the `list-package-versions` command with the correct outputs

**Logs/output**
```
An error occurred (ValidationException) when calling the ListPackageVersions operation: 1 validation error detected: Value '@package/name' at 'packageName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^!#/\s]+
```

**Additional context**
N/A

**Comment by kdaily** [comment]
Hi @joechchung,

I think this is related to https://github.com/aws/aws-cli/issues/5501, where forward slashes are not allowed either.

**Comment by kdaily** [comment]
Marking as a duplicate of #5501, as I also did for #5633. Please follow and comment there for any updates, and 👍🏻 the initial comment to raise visibility.

**Comment by kdaily** [comment]
Hi @joechchung,

Re-opening this as after discussing with the CodeArtifact team, I think something different is going on. You have a Python package with a leading `@` - is that intentional?

If this is still an issue for you, let us know. If not you can leave it to close or close it yourself. Thank you!

**Comment by joechchung** [comment]
> Hi @joechchung,
> 
> Re-opening this as after discussing with the CodeArtifact team, I think something different is going on. You have a Python package with a leading `@` - is that intentional?
> 
> If this is still an issue for you, let us know. If not you can leave it to close or close it yourself. Thank you!

Hi @kdaily,

Yes this was intentional at the time. We're moving away from it but it's still ingrained into our system right now. It's not a massive issue on the aws-cli but more of an issue with the AWS console now as the search for packages is not very flexible... and it can't actually pick up the "@" sign.
