### ISSUE TITLE
aws ecs wait services-stable --services MyService --cluster MyCluster not accurate

### ISSUE THREAD

**Issue by bungeeskimmer** [aws/aws-cli#5894]
I have begun to experience the `aws ecs wait services-stable --services MyService --cluster MyCluster` to not wait until an ecs services forced update is stable. This first came up with an unhealthy task being deployed. Clearly a scenario where the service deployment is unstable. I also now experience it returning before targets are switched out of the loadbalancer specified. I explicitly remember this working the past. This is in eu-central-1. I have tried both v2 and v1 of the cli.

**Comment by kdaily** [comment]
Hi @bungeeskimmer,

Could you please use the bug template provided when creating a new issue and provide more details? At a minimum, I'll need to know:

1. The exact version of the AWS CLI you are running (`aws --version`).
1. Did this occur after upgrading the AWS CLI? When was it last known to be working?
1. Provide redacted debug logs (add the `--debug` command).

I looked at the API service and waiter model, and they have not changed in a long time. Once I get this information I can troubleshoot further. Thank you!

**Comment by bungeeskimmer** [comment]
This is my bad. I was forcing a restart by stopping a task and not a
service forced update. Updated that and works as usual :)
I'll close this out.

Thanks for getting back to me.

**Comment by kdaily** [comment]
Glad it's working for you, @bungeeskimmer!
