### ISSUE TITLE
`aws docdb create-db-cluster` is broken

### ISSUE THREAD

**Issue by HunterLarco** [aws/aws-cli#5898]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

As per https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-create.html
I ran the example invocation

```sh
aws docdb create-db-cluster \
      --db-cluster-identifier sample-cluster \
      --engine docdb \
      --engine-version 4.0.0 \
      --deletion-protection \
      --master-username master-user \
      --master-user-password password
```

which errors with

```sh
> An error occurred (InvalidParameterValue) when calling the CreateDBCluster operation: Invalid DB engine
```

using `aws docdb create-db-cluster help` explains that `--engine` must be provided and must be `docdb` yet doing so returns `InvalidParameterValue`

**SDK version number**

aws-cli/2.0.62 Python/3.7.4 Darwin/20.1.0 exe/x86_64

**Platform/OS/Hardware/Device**
What are you running the cli on?

Mac OS + Linux (tried both)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

```sh
aws docdb create-db-cluster \
      --db-cluster-identifier sample-cluster \
      --engine docdb \
      --engine-version 4.0.0 \
      --deletion-protection \
      --master-username master-user \
      --master-user-password password
```

**Expected behavior**

A DocumentDB cluster is created.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

https://gist.github.com/HunterLarco/e23b0f2341cf8f99d842b08224ec24aa

**Additional context**

**Comment by theahura** [comment]
+1 this is affecting me too :(

**Comment by kdaily** [comment]
Hi @HunterLarco and @theahura,

I tried this with the most recent AWS CLI v2 and it was successful:

```
> aws --version
aws-cli/2.1.20 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off
```

```
aws docdb create-db-cluster --db-cluster-identifier sample-cluster --engine docdb --master-username "mynewuser" --master-user-password "123mypassword123" --preferred-maintenance-window Sun:20:30-Sun:21:00

{
    "DBCluster": {
        "AvailabilityZones": [
            "us-west-2c",
            "us-west-2b",
            "us-west-2a"
        ],
        "BackupRetentionPeriod": 1,
        "DBClusterIdentifier": "sample-cluster",
        "DBClusterParameterGroup": "default.docdb3.6",
        "DBSubnetGroup": "default",
        "Status": "creating",
......
```

Looking into changes from the version you noted.

**Comment by kdaily** [comment]
This specifically fails in region `us-west-1`. Looks like Document DB is not available in all regions, and `us-west-1` is excluded. Here's a post detailing the regions that are available:

https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-documentdb-available-europe-paris-region/

Their [FAQ](https://aws.amazon.com/documentdb/faqs/#Pricing) says to look at the pricing page for the current list of available regions, which you can see in the dropdown:

https://aws.amazon.com/documentdb/pricing/
