### ISSUE TITLE
aws cli support fault injection simulator

### ISSUE THREAD

**Issue by jhonnatangiladl** [aws/aws-cli#5911]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
On Mac

**Describe the question**
I don't show support for Fault Injection Simulator over aws cli

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by stobrien89** [comment]
Hi @jhonnatangiladl, 

Thanks for writing in! The Fault Injection Simulator has not yet been released, but we realize this is a highly-anticipated service— please feel free to monitor the [Fault Injection Simulator page](https://aws.amazon.com/fis/) for updates concerning the release date.
