### ISSUE TITLE
`aws logs tail` timestamp seconds truncated when microseconds would be "000000"

### ISSUE THREAD

**Issue by forevermatt** [aws/aws-cli#5912]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The timestamps printed out by `aws logs tail` are inconsistent lengths when the microseconds are exactly 0.

**SDK version number**
aws-cli/2.0.12 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev16

**Platform/OS/Hardware/Device**
MacBook Pro (13-inch, 2016)
macOS Mojave 10.14.6

**To Reproduce (observed behavior)**
Run `aws logs tail --since 3h <your log group name>` for a log group with lots of log messages. Scroll through the output looking for entries where the timestamp length is shorter.

Example of the unexpected output:
```
2021-02-02T19:41:34.553000+00:00 ... log message...
2021-02-02T19:41:35+00:00 ... log message...
2021-02-02T19:41:35.592000+00:00 ... log message...
2021-02-02T19:41:36.088000+00:00 ... log message...
```

**Expected behavior**
I expected the timestamps to be a consistent length regardless of whether they represent an exact second (no microseconds) or not.

Example of expected output:
```
2021-02-02T19:41:34.553000+00:00 ... log message...
2021-02-02T19:41:35.000000+00:00 ... log message...
2021-02-02T19:41:35.592000+00:00 ... log message...
2021-02-02T19:41:36.088000+00:00 ... log message...
```

**Logs/output**
This seems unnecessary, and would be very hard to provide without exposing a lot of production log messages. If you need some piece of the debug output, please let me know and I will try to provide it.

**Additional context**
(none)

**Comment by kdaily** [comment]
Hi @forevermatt, thanks for reporting. I can reproduce it.
