### ISSUE TITLE
aws ecr-public is region specific

### ISSUE THREAD

**Issue by bytestream** [aws/aws-cli#5917]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

`aws ecr-public` command does not work when `aws configure` is set to some regions. For example, when `aws configure` is set to `eu-west-2` the output is:
```
Could not connect to the endpoint URL: "https://api.ecr-public.eu-west-2.amazonaws.com/"
```

When `aws configure` is set to `us-east-1` the output is correct.

**SDK version number**

```
$ aws --version
aws-cli/2.1.24 Python/3.7.3 Linux/5.8.0-41-generic exe/x86_64.ubuntu.20 prompt/off
```

**Platform/OS/Hardware/Device**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**To Reproduce (observed behavior)**

```
$ aws configure
AWS Access Key ID [********************]: 
AWS Secret Access Key [********************]: 
Default region name [us-east-1]: eu-west-2
Default output format [None]: 

$ aws ecr-public describe-repositories

Could not connect to the endpoint URL: "https://api.ecr-public.eu-west-2.amazonaws.com/"

$ aws configure
AWS Access Key ID [********************]: 
AWS Secret Access Key [********************]: 
Default region name [eu-west-2]: us-east-1
Default output format [None]: 

$ aws ecr-public describe-repositories
{
    "repositories": [
        {
            ...
        }
    ]
}


```

**Expected behavior**

`aws ecr-public` should work irrespective of region.

**Logs/output**

N/A

**Additional context**

Relates to https://github.com/aws/aws-cli/issues/5895

I struggled to find any documentation but my understanding is that ECR Public is region agnostic. When browsing via the AWS Website the ECR registries and public repositories show irrespective of the selected region.

**Comment by stobrien89** [comment]
Hi @bytestream ,

Thanks for writing in! For right now, it appears ECR-public actions are only supported in the us-east-1 region. adding a `--region us-east-1` to the end of your commands (including batch-delete-image and delete-repository) should do the trick.  I've linked the existing [documentation](https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html), but I'm going to look into this a bit further, because a few things seem unclear.

**Comment by stobrien89** [comment]
Hi @bytestream ,

Thanks again for brining this to our attention! I've ticketed the ECR docs team to ask that they provide more explicit references to the fact that ecr-public actions are only supported when providing us-east-1 as the region when using the AWS CLI.  You'll need to continue providing the region flag and specifying us-east-1 as a region for now.  I'm going to consult the development team about possibly overriding the configured hostname for this command (so users won't have to provide the region flag each time), but I unfortunately can't guarantee when/if something like this will be implemented.

**Comment by bhordupur** [comment]
with `aws-cli versoin 2` the command is `aws ecr `but not `aws ecr-public`. Here is the doc [link](https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-repositories.html).

```
aws --version                                            
aws-cli/2.4.10 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
```

**Comment by kushan-gunasekera** [comment]
this solution is working fine for me,

solution:- https://stackoverflow.com/a/69274999/6194097
