### ISSUE TITLE
Provide Description key-value in ssm get-parameter command

### ISSUE THREAD

**Issue by sumanth712bs** [aws/aws-cli#5918]
Request/Problem:
Please provide a description of the parameter when `aws ssm get-parameter --name "MyStringParameter"` is executed from CLI.

Currently, we get below output. 
```   
{
  "Parameters": {
            "Name": "MyStringParameter",
            "Type": "SecureString",
            "Value": "EncryptedText",
            "Version": 1,
            "LastModifiedDate": 1582154764.222,
            "ARN": "arn:aws:ssm:us-east-2:111222333444:parameter/MyStringParameter"
        }
} 
```

It would be great and really handy if we can see the `Description` key-value in the result of that command.

I did try using `describe-parameter` to get description but I can't decrypt the secure string 😞

**Comment by stobrien89** [comment]
Hi @sumanth712bs,

Thanks for your feature request!  Just out of curiousity, was the `--with-decryption` option not working when you were using the `decribe-parameter` command?

**Comment by sumanth712bs** [comment]
Hello @stobrien89  

Unfortunately no. Since `describe-parameters` doesn't have `--with-decryption` option. 

I would still use `get-parameter` instead of `describe-parameters`.

**Comment by stobrien89** [comment]
Hi @sumanth712bs ,

My apologies! I intended to reference the `get-parameter` command in my last comment, but that option would not apply here— I initially misunderstood your request.  That said, I will raise this with the SSM team, as this would be an API change.

**Comment by stobrien89** [comment]
Hello again @sumanth712bs ,

I was discussing this with my team and the consensus is that it's unlikely a change like this would be implemented by the ssm service team, as `describe-parameters` already yields the description for a parameter.  Though I do agree it would be more convenient to include that in the output for `get-parameter`. Would you be able to describe your use case?  

For the time being, a call like `aws ssm describe-parameters --filters "Key=Name, Values=<parameter name>" --query "Parameters[0].Description"` used in conjunction with `get-parameter` should get close to the desired behavior.

**Comment by sumanth712bs** [comment]
Thank you @stobrien89  for discussing with the team.

We have stored some important information in  `Description` parameter and hence we wanted to see it when we use any command.  Basically we want to decrypt the secure string as well as want to see Description at one shot.

`aws ssm describe-parameters` provides all details apart from decryption of secure string. 
`aws ssm get-parameter --name "MyStringParameter" --with-decryption` provides all necessary details apart from Description 😞

**Comment by stobrien89** [comment]
Hi @sumanth712bs ,

Of course!  I was thinking that may be the case, but just wanted to make sure. I've escalated this to the ssm team— I'll be sure to provide any updates I have, once received.

**Comment by stobrien89** [comment]
P44254672

**Comment by markb-trustifi** [comment]
This issue is still relevant.
As of version 3.535, there are no Description/Tags fields in commands: getParameter, getParameters, GetParametersByPath.
