### ISSUE TITLE
Publish official Docker image to public AWS ECR

### ISSUE THREAD

**Issue by rochacon** [aws/aws-cli#5921]
**Is your feature request related to a problem? Please describe.**

[Now that AWS ECR has a public instance](https://aws.amazon.com/blogs/aws/amazon-ecr-public-a-new-public-container-registry/), the [AWS CLI official Docker image](https://aws.amazon.com/blogs/developer/aws-cli-v2-docker-image/) should be available on it, i.e. `public.ecr.aws/amazon/aws-cli` should exist. This would help AWS EKS users (and ECS) that have tasks/pods using the official image to avoid Docker Hub dependency without having to mirror/vendor the official image themselves.

As an example, I have CI workers that pull the official image to run a few setup/deploy commands and had to vendor the AWS CLI into my own ECR instance to avoid Docker Hub requests limits affecting my CI pipelines (we like ECR and prefer not to have a Docker Hub account just to avoid these limits).

**Describe the solution you'd like**

AWS CLI official Docker Image should be available on `public.ecr.aws`.

**Describe alternatives you've considered**

* Mirroring/vendoring the official AWS-CLI myself in an private ECR repository

**Additional context**

Currently there are Bitnami and other third-party AWS CLI images available on public.ecr.aws, but I prefer to use the AWS upstream imagens since I trust them and don't want audit yet another third-party container image.

**Comment by kdaily** [comment]
Thanks for the feature request!

**Comment by jbg** [comment]
Duplicate of #5836

**Comment by rochacon** [comment]
Closing in favor of #5836.
