### ISSUE TITLE
About using awscli in Hong Kong to obtain the quota of Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances

### ISSUE THREAD

**Issue by yuqingkj** [aws/aws-cli#5925]
root@ip-172-31-46-12:~# aws service-quotas get-service-quota --region ap-east-1 --service-code ec2 --quota-code L-1216C47A
An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation: The request failed because the specified service does not exist.

What is the service-code in Hong Kong？

**Comment by kdaily** [comment]
Hi @yuqingkj, not all service quotas are available in every region - you can confirm this by using the AWS Console to see what quotas are available. I am not opted into the `ap-east-1` region, but I tested with another region (`eu-south-1`) and obtained the same error you did:

```
> aws2 service-quotas get-service-quota --region eu-south-1 --service-code ec2 --quota-code L-1216C47A

An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation:
```

Looking at the console shows this quota is not available in this region. I only see 15 EC2 quotas in `eu-south-1` but 67 in `us-west-2`. I could not identify a complete list of which quotas are available in which region outside of the console, so you need to be logged in there to see.

**Comment by yuqingkj** [comment]
First of all, thank you for your prompt repl.My current problem is that I cannot get the Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances in Hong Kong with aws cli.I confirm that I have activated the Hong Kong area by myself. I can see the quota in the console, but I cannot see it in the aws cli. What's the matter?

**Comment by kdaily** [comment]
Hi @yuqingkj,

Thanks for the details. I'll enable that region and confirm.

**Comment by kdaily** [comment]
Hi @yuqingkj, I do not see that quota in the AWS console for the `ap-east-1` region - I do not think that quota is available. Can you double check your region selection in the console in the upper right corner to be sure it's set to `us-east-1`?
