### ISSUE TITLE
Support pyYAML>=5.4

### ISSUE THREAD

**Issue by GeyseR** [aws/aws-cli#5934]
**Is your feature request related to a problem? Please describe.**
There is no possibility to upgrade pyyaml lib installed near the latest version of aws-cli lib using strict installers that done;t allow versions mismatch (like Pipenv). The reason is that aws-cli is stuck to v. <5.4
https://github.com/aws/aws-cli/blob/ad0829e0947edcf10bdf2f871b9c7db5e3af87db/setup.py#L30

**Describe the solution you'd like**
allow at least 5.4.1 version in setup.py

**Comment by kdaily** [comment]
Hi @GeyseR,

There's an open PR that should get merged in soon for this:

https://github.com/aws/aws-cli/pull/5887

Thanks!
