### ISSUE TITLE
Typo in example page

### ISSUE THREAD

**Issue by senpot** [aws/aws-cli#5952]
Hi,

I found a typo in the example page of authorize-security-group-ingress.

[page]
https://github.com/aws/aws-cli/blob/5aa599949f60b6af554fd5714d7161aa272716f7/awscli/examples/ec2/authorize-security-group-ingress.rst

`aws ec2 authorize-security-group-ingress \\`
( \\\  -> \ )

**Comment by kdaily** [comment]
Thanks for catching that!
