### ISSUE TITLE
load_plugins fails due to python version in path 

### ISSUE THREAD

**Issue by johnlabarge** [aws/aws-cli#5961]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The plugin import code incorrectly derives the plugin package at line 60 of the plugin.py file.  Specifically if there is a version in the path e.g. python3.9 it fails with the following error: ModuleNotFoundError: No module named '/usr/local/opt/awscli/libexec/lib/python3' because it cuts the module name off at the dot.   I'm not sure what the code is intended to prevent regarding the dot or else I would have done the PR already. 

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by stobrien89** [comment]
Hi @johnlabarge,

Thanks for writing in!  I'm not able to reproduce with a version (3.9) in my path.  Would you be able to provide more details about your configuration, as well as debug logs (if applicable)? Also, what installation method was used? Thanks!
