### ISSUE TITLE
RSA Module now missing after having worked for months

### ISSUE THREAD

**Issue by mrowles** [aws/aws-cli#5968]
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
In our pipelines (BitBucket), we install AWS CLI via pip3 (`pip3 install -U awscli`). This has worked for many months without interruption until this morning (we noticed the repo updated 3 hours ago, in line with this disruption). Apparently, the RSA module is not installing sometimes?

❌ Here is an unsuccessful install, note the missing 'rsa' package:

```
Installing collected packages: docutils, PyYAML, colorama, six, python-dateutil, urllib3, jmespath, botocore, s3transfer, awscli
...
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python3.5/dist-packages/awscli/clidriver.py", line 68, in main
    driver = create_clidriver()
  File "/usr/local/lib/python3.5/dist-packages/awscli/clidriver.py", line 78, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/local/lib/python3.5/dist-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python3.5/dist-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python3.5/dist-packages/awscli/handlers.py", line 28, in <module>
    from awscli.customizations.cloudfront import register as register_cloudfront
  File "/usr/local/lib/python3.5/dist-packages/awscli/customizations/cloudfront.py", line 17, in <module>
    import rsa
**ImportError: No module named 'rsa'**
```

✅ Here is a successful install, note the difference with 'collected packages':

```
Installing collected packages: jmespath, urllib3, six, python-dateutil, botocore, docutils, s3transfer, PyYAML, colorama, pyasn1, **rsa**, awscli
```

**SDK version number**
aws-cli/1.19.13 Python/3.5.2 Linux/5.4.92-flatcar botocore/1.20.13

**Platform/OS/Hardware/Device**
Linux on BitBucket Pipelines

**To Reproduce (observed behavior)**
Run aforementioned scripts, potentially need to lock version to 1.19.13

**Expected behavior**
RSA should install, not sure why sometimes (or, all of a sudden) it chooses not to.

**Logs/output**
See above

**Additional context**
We will try and upgrade to aws-cli 2.x in the meantime, but raising this issue in case that does not work or for others who cannot.

**Comment by nateprewitt** [comment]
Hi @mrowles,

Thanks for bringing this to our attention. The change that went out today was adjusting our dependencies for rsa. We've moved our range to versions that no longer support Python 3.5. The AWS CLI did a [deprecation campaign](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-python-3-4-and-3-5-in-the-aws-sdk-for-python-and-aws-cli-v1/) last year for dropping support of 3.4/3.5 at the beginning of Feb 2021.

What's interesting is modern versions of pip for the last several years prevent what's happening here by refusing to install awscli-1.19.0+ on Python 3.5. Do you know offhand what version of pip you environment is using?

In the meantime, we'd encourage you to either migrate to the AWS CLI v2, Python 3.6+, or pin to awscli<1.19.

**Comment by mrowles** [comment]
Yep, sounds good, a quick fix was to manually install some of the newly missing deps and set a roadmap to upgrade to v2. Thanks fo the reply!!!
