### ISSUE TITLE
'aws sso' does not have login command option

### ISSUE THREAD

**Issue by arvindkgs** [aws/aws-cli#5970]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
'aws sso' does not support login command anymore. 

**SDK version number**
aws-cli/1.18.221 Python/3.8.7 Darwin/20.3.0 botocore/1.17.63

**Platform/OS/Hardware/Device**
Zsh, BigSur, MacOS, Macbook Air 2015

**To Reproduce (observed behavior)**
run 'aws sso login'

**Expected behavior**
Invokes login flow to SSO 

**Logs/output**
running 'aws sso login' shows
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument operation: Invalid choice, valid choices are:

get-role-credentials                     | list-account-roles
list-accounts                            | logout
help

**Comment by kdaily** [comment]
Hi @arvindkgs,

Per the documentation page, SSO login is only available in the AWS CLI v2:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

> **This feature is available only with AWS CLI version 2.**
>
> The following feature is available only if you use AWS CLI version 2. It isn't available if you run AWS CLI version 1. For information on how to install version 2, see [Installing, updating, and uninstalling the AWS CLI version 2](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html).
