### ISSUE TITLE
Documentation doesn't specify required botocore version required to use codeartifact

### ISSUE THREAD

**Issue by hans2520** [aws/aws-cli#5975]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Machines deployed to use codeartifact fail, and awscli doesn't recognize the command. The machines were instructed to use awscli >= 1.18.83 or newer, as per the documentation requirements.

**SDK version number**
aws-cli/1.19.9 Python/3.6.9 Linux/5.4.0-1032-aws botocore/1.14.9

**Platform/OS/Hardware/Device**
Linux 5.4.0-1032-aws #33~18.04.1-Ubuntu SMP Thu Dec 10 08:19:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce (observed behavior)**
A version older than 1.18.83 was present on the machine.  Machine instructed to install awscli >= 1.18.83 via pip. 
After doing so, AWS CLI 1.19.9 is installed as mentioned above. Then run the following command:
`aws codeartifact help`
`aws: error: argument command: Invalid choice, valid choices are: 
...`

**Expected behavior**
help page on codeartifact should appear

**Additional context**
Upgrading botocore fixes issue. Not sure which version of botocore is exactly required, but I'm assuming based on the changelogs it's 1.17.0 or newer.

Issuing `pip3 install botocore==1.17.0`, and reloading the shell, we see the following
`aws-cli/1.19.9 Python/3.6.9 Linux/5.4.0-1032-aws botocore/1.17.0`

`aws codeartifact help` then works.

The documentation should specify which version of botocore is required, or else the pip dependency resolver should automatically upgrade the botocore when upgrading awscli.

**Comment by stobrien89** [comment]
Hi @hans2520,

 Thanks for writing in! I just wanted to confirm first that everything is behaving as expected after the botocore upgrade.

We have an open [feature request](https://github.com/aws/aws-cli/issues/5926) to improve/add detail to the changelog that should help to alleviate issues like this. We also have an open issue concerning the pip dependency resolver [here](https://github.com/aws/aws-cli/issues/5173).

**Comment by hans2520** [comment]
Yes, everything works after the separate botocore upgrade

**Comment by stobrien89** [comment]
Hi @hans2520, 

Glad to hear it!  I'm going to close this for now, but we are keeping those suggestions in mind, as they are definitely valid concerns.
