### ISSUE TITLE
v2 install as pip package on git bash

### ISSUE THREAD

**Issue by lmayorga1980** [aws/aws-cli#5983]
I have installed awscliv2 using the MSI for Windows.

```
aws --version
aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

```

When I run it from git bash I get the following message.

```
$ aws configure sso

Found xterm, while expecting a Windows console. Maybe try to run this program using "winpty" or run it in cmd.exe instead. Or otherwise, in case of Cygwin, use the Python executable that is compiled for Cygwin.

```

**Comment by stobrien89** [comment]
Hi @lmayorga1980, 

Thanks for writing in! I'm unable to reproduce on the same configuration using cmd.exe— this appears to me more of a compatibility issue between xterm and git bash.  Have you tried running it using winpty or in cmd.exe with any success?

**Comment by lmayorga1980** [comment]
I will try the `winpty` option and get back here.

**Comment by bharti8085** [comment]
I have the same issue. Is there any solution for this?

**Comment by JaiRaeWiz-DOL** [comment]
Ran into same issue. Using cmd is not an option. Issue is urgent, and I cannot be expected to learn a whole new command scheme to fix the problem. I'm forced to use dangerous methods to accomplish the same task. (manually pasting short term credentials with long running task). This should not happen. This worked for me last week. What would cause this to suddenly stop working?

**Comment by Iovesophy** [comment]
@stobrien89
I have the same issue too. 
try winpty then resolved.
thank you.

Windows 11 Pro
GitBash(git version 2.39.2.windows.1)

```bash
$ aws --version
aws-cli/2.16.6 Python/3.11.8 Windows/10 exe/AMD64
$ winpty aws configure sso
```
