### ISSUE TITLE
MFA prompt not displayed with certain CLI commands

### ISSUE THREAD

**Issue by Pl4nky** [aws/aws-cli#5997]
aws-cli/2.1.18 Python/3.7.9 Windows/7 exe/AMD64 prompt/off

Certain CLI commands will not display an MFA prompt, when MFA is configured in the .aws\config file.  For example,  I have the following configured in .aws\config

```
[profile TEST]
role_arn = arn:aws:iam::1234567890:role/myrole
source_profile = master
mfa_serial = arn:aws:iam::1234567890:mfa/testmfa
region = ap-southeast-2
```

I run the following command:

`aws cloudwatch describe-alarms --profile TEST`

This result in a blinking cursor, no prompt. I had assumed the cmd had hung, as it would never timeout or display an error.  Pressing ctrl + c doesn't appear to do anything, but I found you had to press enter to be returned back to the prompt. 

The expected behavior is for the following text to be displayed:

`Enter MFA code for arn:aws:iam::1234567890:mfa/testmfa`

There are two workarounds:

1. The mfa code can still be entered despite the prompt text not being displayed and the results returned. 
2. Add --no-cli-pager to the the cli command, which then displays the MFA prompt correctly. 

Other commands (such as AWS S3 LS --profile TEST) correctly displays the prompt (assuming MFA auth is required again, which you can force by clearing the .aws\cli\cache folder or wait for the session to timeout)

Tested on Windows 7 and Windows 10 and same behavior occurs.

**Comment by kdaily** [comment]
Hi @Pl4nky,

I think this should now be fixed. Thanks again!
