### ISSUE TITLE
aws eks create-nodegroup support LT directive "latest"

### ISSUE THREAD

**Issue by amrragab8080** [aws/aws-cli#5998]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The AWS CLI v2
`aws eks create-nodegroup` has an option to specify the launch template version, if no version is specified then it uses default. Issue is there is a third option which is not mentioned which is to support the `"latest"` launch template regardless of version.

If i create the nodegroup through cloudformation this is supported but not in the AWS CLI

**SDK version number**
AWS CLI 2.1.29

**Platform/OS/Hardware/Device**
What are you running the cli on?
Linux (Ubuntu)

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**
support version, number, "default", and **"latest"**
**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kdaily** [comment]
Hi @amrragab8080,

Looks like this would be a feature request to the EKS team to support this. I'll check in and see if this is planned or would be a new feature.

**Comment by kdaily** [comment]
V329957265
