### ISSUE TITLE
s3 sync --delete issue

### ISSUE THREAD

**Issue by jansmets** [aws/aws-cli#6000]
s3 sync --delete  --dryrun s3://bucket /local/path/to/bucket    

The dryrun seems to indicate that local files are to be removed.
When the dry-run is executed on a subdirectory of the bucket it does not consider the removal of files.

eg , 
 s3 sync --delete  --dryrun s3://bucket/subdir /local/path/to/bucket/subdir  does not print any to-be-removed files
whereas
s3 sync --delete  --dryrun s3://bucket /local/path/to/bucket     does want to remove files under 'subdir'.

**Comment by stobrien89** [comment]
Hi @jansmets, 

Thanks for writing in!  Can you please provide the CLI version you're using as well as debug logs (by appending `--debug` to the end of your command)?  Please redact any sensitive information such as account numbers.

**Comment by jansmets** [comment]
This issue seems related to Ceph's RGW issue in an older version. Sorry for bothering.

**Comment by stobrien89** [comment]
Hi @jansmets,

No bother at all!  We've seen similar issues with ceph implementations. Couldn't help but notice you posted another issue related to cp being limited to 1000 items— Likely due to a [lack of pagination](https://github.com/aws/aws-cli/issues/5908).
