### ISSUE TITLE
Cloudsearch define-index-field - source field option

### ISSUE THREAD

**Issue by furmandev** [aws/aws-cli#6017]
When adding an index field to CloudSearch, there isn't a way to define a "source field" via cli (like there is in console).

It'd be great if there were a new option like `[--source-field <value>]` for the [define-index-field command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudsearch/define-index-field.html) where this could be defined.

![image](https://user-images.githubusercontent.com/7343697/111168131-251a9180-8578-11eb-81e5-56cf582a5329.png)

**Comment by stobrien89** [comment]
Hi @furmandev,

Thanks for the feature request!

**Comment by pawanakhil** [comment]
Would like to work on this issue. Thanks.

**Comment by stobrien89** [comment]
Hi @pawanakhil,

Thanks for the pull request!  We are pretty backed up on these right now, but we'll have it reviewed as soon as feasibly possible.
