### ISSUE TITLE
bad parameter --public-key-base64 and documentation when importing lightsail public key

### ISSUE THREAD

**Issue by razielvamp666** [aws/aws-cli#6020]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

command

```  
aws lightsail import-key-pair --key-pair-name MY_KEY --public-key-base64 "$(base64 ./key.pub | tr -d '\n')"
```

Returns:

```
An error occurred (InvalidInputException) when calling the ImportKeyPair operation: The format of this public key is not valid.
```

Although command

```  
aws lightsail import-key-pair --key-pair-name MY_KEY --public-key-base64 "$(cat ./key.pub | tr -d '\n')"
```

Working good.

In [documentation](https://docs.aws.amazon.com/cli/latest/reference/lightsail/import-key-pair.html) we can see:

> --public-key-base64 (string)
>    A base64-encoded public key of the ssh-rsa type.

But **base64-encoded public key** not working, we need to provide ssh-rsa public key as is.
The manual and parameter name are wrong. And it is very confusing.

**Comment by stobrien89** [comment]
Hi @razielvamp666,

Thanks for writing in! I was able to test and reproduce myself (with ssh-keygen)— After doing some digging, it appears the keys (the entirety of the .pub file) generated in this fashion are base64 encoded by default.  It's not very well documented, but I'm going to review this with the team tomorrow, as a few things seem unclear.

What was the method you used to generate your public key? And is the key you successfully uploaded working?
