### ISSUE TITLE
json schema different for ecs update-service and ecs create-service

### ISSUE THREAD

**Issue by tkumark** [aws/aws-cli#6021]
aws-cli/2.0.50 Python/3.7.3 Linux/5.4.0-66-generic exe/x86_64.ubuntu.18
when we run 
```
aws ecs create-service --generate-cli-skeleton > service-def.json
aws ecs update-service --generate-cli-skeleton > update-service.json
```
It generate slightly different json template. For example one has **service** and other has **servicename** eventhough both fields are ment for the same purpose. 
Also some fields like loadbalancer and target group are missing in update-service.json. Could it be made so that that both update and create service generate same json skeleton but during update the fields that should not be updated are just ignored and remaining get updated. 
This would help in keeping consistant  json that can be used for both create and update.

**Comment by kdaily** [comment]
Hi @tkumark,

Thanks for your request. The shape of these templates is set by the ECS team in their API model. I will pass this information on as a feature request to that team. There isn't anything that the AWS CLI can do to make this change, including ignoring specific parameters.
