### ISSUE TITLE
Make ecs execute-command available for cliv2

### ISSUE THREAD

**Issue by dimisjim** [aws/aws-cli#6022]
Announced in: https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-ecs-now-allows-you-to-execute-commands-in-a-container-running-on-amazon-ec2-or-aws-fargate/

Option seems to be available in 1.19.28: https://docs.aws.amazon.com/cli/latest/reference/ecs/index.html
but not in 2.1.30: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/index.html

Could you please add it in the new cli version as well?

Thanks

**Comment by kdaily** [comment]
Hi @dimisjim,

Thanks for your request! We're tracking the feature for CLI v2 and it's scheduled to be available in the next release (2.1.31).

**Comment by kdaily** [comment]
Hi @dimisjim and others,

This command is now available in the 2.1.31 release! 🎉 

Note that the Windows MSI for the AWS CLI v2 is still delayed. Read here for more details and updates:

https://github.com/aws/aws-cli/issues/6005
