### ISSUE TITLE
accessanalyzer validate-policy is not available in AWS CLI V2

### ISSUE THREAD

**Issue by lmichelbacher** [aws/aws-cli#6027]
The command `aws accessanalyzer validate-policy` is mentioned in [this AWS blog post](https://aws.amazon.com/blogs/aws/iam-access-analyzer-update-policy-validation/) about IAM Access Analyzer.

With the latest version of AWS CLI, this command is not available. It's only available in V1.

The [V1 documentation](https://docs.aws.amazon.com/cli/latest/reference/accessanalyzer/validate-policy.html) recommends to use V2. It contains a [link](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/accessanalyzer/validate-policy.html) to `validate-policy` in V2 but the link is dead.

**Comment by stobrien89** [comment]
Hi @lmichelbacher, 

I'm going to close this due to Nate's comment regarding this feature being slated for the next release, but please let us know if you need any additional support!
