### ISSUE TITLE
FIPS 140-2 compliance

### ISSUE THREAD

**Issue by oalbrigt** [aws/aws-cli#6038]
**Is your feature request related to a problem? Please describe.**
Some companies and governments require the OS to run in FIPS 140-2 compliant mode, which will make awscli not work without the FIPS patch below.

**Describe the solution you'd like**
Implementation: https://github.com/aws/aws-cli/pull/3078

**Comment by kdaily** [comment]
Hi @oalbrigt, thanks for opening this and providing the proposed change. The AWS CLI V2 has already removed RSA as a dependency and uses `cryptography`. The V1 client cannot rely on this as we cannot use packages with C extensions. Using the V2 client should give you this functionality.

See the following commits:

- https://github.com/aws/aws-cli/commit/c7d52b331dc33da106e3cbc2012bfaf90c4436a0
- https://github.com/aws/aws-cli/commit/b861cbb40f0328827ba065f32ef4b67c95de9106
- https://github.com/aws/aws-cli/commit/92aea2e2dd3d268435ea4e6812363cafcc83f64e

**Comment by oalbrigt** [comment]
Great. When will v2 be available via pip?

**Comment by kdaily** [comment]
Hi @oalbrigt, we are not planning to provide releases of the v2 client through PyPI. However, a source distribution will be provided. You can follow updates on this here for now, pending an announcement of when that would be made available:

https://github.com/aws/aws-cli/issues/4947#issuecomment-793192340
