### ISSUE TITLE
s3 missing 1 file 

### ISSUE THREAD

**Issue by Adblu** [aws/aws-cli#6047]
I have used aws cli tool to move couple of folders named: 2014, 2015, 2016 etc from root directory into 

```
/2015/
```
into:
```
/images/2015/
```
command used:
```
aws s3 sync s3://path/to/bucket/2014 s3://path/to/bucket/2014/images --profile john@smith.com
```

When I moved them it seems that there is one file less in each bucket:

Before copying:

![Screenshot from 2021-03-26 10-33-36](https://user-images.githubusercontent.com/34426707/112804818-21f1cc00-9075-11eb-8843-8565e1cf0ffc.png)

After coping:

![Screenshot from 2021-03-26 10-33-47](https://user-images.githubusercontent.com/34426707/112804860-2fa75180-9075-11eb-9978-7a9eba2db390.png)

Could you help me to understand this phenomena ?

**Comment by stobrien89** [comment]
Hi @Adblu,

Thanks for writing in! Just wanted to confirm before we move forward— did you use `s3 cp` or `s3 sync`?  It sounded like `cp` from what you wrote, but just wanted to be sure.

**Comment by Adblu** [comment]
@stobrien89  I have used sync. Here is a sample command: 

aws s3 sync s3://path/to/bucket/2014 s3://path/to/bucket/2014/images --profile john@smith.com
