### ISSUE TITLE
Lambda Configuration Update results 'Layer conversion failed: Some directories do not have execute permissions'

### ISSUE THREAD

**Issue by DallasP9124** [aws/aws-cli#6049]
I am attempting to upload/update a layer for boto3 to be used by my python lambda function. Upon attempting to use the CLI I get an error message saying **Layer conversion failed: Some directories do not have execute permissions**

I followed this [AWS walkthrough ](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-python-runtime-errors/)of how to do just this and am using the cli to update the layer and attempt to update the function configuration to use the new layer.

## Steps 
I created a new folder to house the boto3 install, making sure to have the *python* folder.
`$ mkdir boto_3_layer/python`

I moved into the python folder and installed boto3 (version 1.17.39)
`$ cd boto_3_layer/python`
`$ pip3 install boto3==1.17.39 -t .`

The installation was successful. I chmod all the files and directories to be accessible and executable:
`chmod -R 755 .`

I move to the root boto_3_layer directory and zip up the directory.
`$ cd ..`
`$ zip -r ../boto_3_layer.zip .`

The directory zips up as expected after checking the contents of the zip (contains the python folder and the boto3 install within it).

I now update the layer using the command:
`$ aws lambda publish-layer-version --layer-name boto-3-layer --zip-file fileb://boto_3_layer.zip`

This shows to be successful with no errors. Not the final step to update the function configuration to use the layer (using fake arn here):
`$ aws lambda update-function-configuration --function-name my-lambda-function --layers arn:aws:lambda:us-xyz-1:2723527234537:layer:boto-3-layer:1`

This is where the update fails. From the previous command I get an error back:
```
An error occurred (InvalidParameterValueException) when calling the UpdateFunctionConfiguration operation: Layer conversion failed: Some directories do not have execute permissions;
```

After seeing this error I did some research that ultimately did not fix the error. One of the supposedly obvious things to check was the actual file permissions of the boto3 install and python directory I created. Listing the files, all of them had `777` permissions so it wouldn't make sense for it to be the file/directory permissions. Are there other permissions that this could be referring to?

I also attempted the configuration update in the AWS console in the browser but received the same message.

**Platform/OS/Hardware/Device**
Windows 10
AWS-CLI 2.0.24
Python 3.8
Boto3 1.17.39

**Comment by stobrien89** [comment]
Hi @DallasP9124,

Thanks for writing in! When you mentioned "Listing all the files", did that include the directory and subdirectories themselves? I'm sure you've come across this, but I would try running `chmod -R 755 <directory>` _or_ `chmod -R 777 <directory>` on `boto_3_layer` if you're not sure.

**Comment by DallasP9124** [comment]
@stobrien89 Yes that did include directories and subdirectories. I ran the command you gave and forgot to add that step to the repro steps. I'll edit to reflect.

I did a search for all directories and files recursively that did not match the 777 or 755 code and nothing came back. I also did some manual traversal to see for myself and all came back as expected.

**Comment by stobrien89** [comment]
Hi @DallasP9124, 

Thanks for confirming.  Would you be able to provide debug logs by appending `--debug` to your command?  Please obscure any sensitive information.  Thanks!
