### ISSUE TITLE
Cannot get AccessTokenValidity from aws cli

### ISSUE THREAD

**Issue by Victoria13835** [aws/aws-cli#6057]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When running aws cognito-idp describe-user-pool-client --user-pool-id <user-pool-id> --client-id <app-client-id> --query UserPoolClient.AccessTokenValidity,
the accessTokenValidity time is missing.
There is a discrepancy in the docs, https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/describe-user-pool-client.html
Under Output, it claims that after running the command, the output should include AccessTokenValidity, but this is not the case when I run it, or in the example output given. 

TokenValidityUnits is also missing in the output

**SDK version number**
aws-cli/2.0.14 

**Platform/OS/Hardware/Device**
4.14.165-131.185.amzn2.x86_64

**To Reproduce (observed behavior)**
Run aws cognito-idp describe-user-pool-client --user-pool-id <user-pool-id> --client-id <app-client-id> --query UserPoolClient.AccessTokenValidity

**Expected behavior**
To be returned the accessTokenValidity in the returned JSON
60
**Logs/output**
When running aws cognito-idp describe-user-pool-client --user-pool-id <user-pool-id> --client-id <app-client-id> --query UserPoolClient.AccessTokenValidity, I get:
null

**Additional context**

**Comment by stobrien89** [comment]
Hi @Victoria13835,

Thanks for writing in! After doing some digging, I found that both `AccessTokenValidity` and `TokenValidityUnits` were added to the response a few months after the release of 2.0.14— bumping up to version 2.0.40 or greater should take care of it. 2.1.33 is the current version.

**Comment by stobrien89** [comment]
Closing for now, but let us know if anything else comes up!

**Comment by Victoria13835** [comment]
It works!
Updating returned the TokenValidityUnits as an empty set {}, but after changing the access token validity settings at least once from the aws console, the command returned the expected non empty results for both TokenValidityUnits.  I suspect this may be because the cognito pool was made before the update.
The docs may also still need updating, but otherwise this issue can be closed. Thanks for the help!
