### ISSUE TITLE
Default "amazon/aws-cli"  container Bind to localhost/127.0.0.0 interface

### ISSUE THREAD

**Issue by dushyant8858** [aws/aws-cli#6059]
**[Is your feature request related to a problem? Please describe.]**
***A clear and concise description of what the problem is:***
By default `amazon/aws-cli`  container Bind to `127.0.0.0` [i.e localhost] interface, which makes the aws-cli access works only from inside the container but not outside **[NO use of Docker with that AWS v2 CLI SSM port forwarding feature]**.

**[Describe the solution you'd like]**
***A clear and concise description of what you want to happen:***
Idea here is to bind the container to `0.0.0.0` [i.e to all interfaces] inside the container. So traffic coming from outside of the container is also accepted.

**Describe alternatives you've considered**
***A clear and concise description of any alternative solutions or features you've considered:***
Currently NO alternatives.

**[Additional context]**
***Add any other context or screenshots about the feature request here:***
#### === Reproduction Steps ===
1) Create/launch a Windows EC2 instance (e.g Windows_Server-2019-English-Full-Base-2021.03.10 - `ami-07817f5d0e3866d32` in `us-east-1`) on AWS 
(SSM agent needs to be up and running on the instance to correctly reproduce the issue)

2) Try running `aws ssm start-session --target i-abc123456789abvxsf --document-name AWS-StartPortForwardingSession --parameters "localPortNumber=3393,portNumber=3389"` to RDP into the instance via `localhost:3393`
Ideally it should work fine if VPC/networking config is not fancy

3) Now to achieve the same via `amazon/aws-cli` image.
a) Create a following Dockerfile
$ cat Dockerfile
```
FROM amazon/aws-cli
RUN cd /tmp \
    && curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm" \
    && yum install -y session-manager-plugin.rpm \
    && rm -rf session-manager-plugin.rpm
```
b) Build a image
```
$ docker build -t ssmwindowsusingdocker/aws-cli:1.0 .
```
c) Run a container using above built image
```
$ docker run --rm -it -p 3393:3393 -v ~/.aws:/root/.aws -v $(pwd):/aws  ssmwindowsusingdocker/aws-cli:1.0 ssm start-session --target "i-abc123456789abvxsf" --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["3389"],"localPortNumber":["3393"]}'
```

d) Try RDP into the instance using `localhost:3393` and it will fail.
**[Reason]**: Laptop request will never be allow to hit container because container only allowing traffic from localhost.
 
=====================

**Comment by kdaily** [comment]
Hi @dushyant8858,

Sorry to hear of the trouble! The AWS CLI container image uses the `amazonlinux:2` as a base, so the behavior is the same. In general, we advise that the container be used solely for running AWS CLI commands in isolation, not used as a long-running process.

I would reach out to the ECS or SSM team to see if they have any suggestions for this scenario.
