### ISSUE TITLE
Cannot install AWS CLI V2, botocore==2.0.0dev102 not found

### ISSUE THREAD

**Issue by hackaprende** [aws/aws-cli#6061]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When trying to install AWS CLI2 I am getting this error
No matching distribution found for botocore==2.0.0dev102 (from awscli==2.1.34)

I have searched for this version but the maximum version available is 1.20

**SDK version number**
2.1.34

**Platform/OS/Hardware/Device**
What are you running the cli on?
Raspbian

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
Followed the instructions here: 
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html

**Expected behavior**
I should be able to run AWS commands

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
Collecting botocore==2.0.0dev102 (from awscli==2.1.34)
No matching distribution found for botocore==2.0.0dev102 (from awscli==2.1.34)

**Additional context**

**Comment by kdaily** [comment]
Hi @hackaprende,

Can you confirm the commands you're running to perform the install? The only supported method of installation for the AWS CLI V2 is through a bundle, which includes `botocore` with it already. The commands for this (as noted on the installation page you linked) look like:

```
$ curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
```
