### ISSUE TITLE
recent aws-cli v2 being killed by Palo Alto Traps/Cortex XDR agent

### ISSUE THREAD

**Issue by joshsleeper** [aws/aws-cli#6065]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

Instead of aws-cli v2 commands succeeding, I'm seeing my company's Palo Alto Traps/Cortex XDR agent killing recent
versions of aws-cli v2 on Ubuntu 18.04 (64-bit) either promptly or after a decent delay. In both cases the `aws`
commands are not successfully completing.

As per the discussion in #5221 I'm opening a new issue to track mitigating it.

Specifically, I'm _fairly_ sure I've seen this issue since version `2.1.28`, which I assume is related to the `pyinstaller`
update and some underlying behavior that must've changed.

**SDK version number**

`2.1.34` unless this is asking for something else and I'm misunderstanding

**Platform/OS/Hardware/Device**

Ubuntu 18.04 (64-bit), fully patched

**To Reproduce (observed behavior)**

1. have a somewhat recent Palo Alto Traps/Cortex XDR agent installed and running properly
    - since this probably isn't readily available unless you're paying for their product, I'm happy to help debug this with guidance
1. install latest aws-cli v2 (`2.1.34` at time of writing) as described the official docs
    - https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
1. run `aws --version` (or in to better demonstrate behavior, `time aws --version`)
1. see a substantial delay before Palo Alto Traps/Cortex XDR decides to kill the process

**Expected behavior**

the standard version output is printed

**Logs/output**

```
$ aws --debug --version
Killed

$ time aws --version
Killed

real    1m1.115s
user    0m0.002s
sys     0m0.001s

$ sudo cat /opt/traps/version.txt
cortex-agent-7.2.2.8227
```

**Additional context**

VirusTotal scan for Linux `2.1.34` binary:

https://www.virustotal.com/gui/file/d990282e0048e6eb9b7300d705c1a53faeb83e400a7f22ce5287707db0bf78eb/detection

Notice that a number of scanners failed to scan the file, including Palo Alto.

That said, it kinda sounds like the Palo Alto scanner for VirusTotal is really focused on only signature-based detection,
and even then only for Windows binaries, at least according to their announcement post for when it was added.

https://blog.virustotal.com/2017/03/virustotal-palo-alto-networks.html

If so, that would explain why it wouldn't detect the same things that Traps is detecting.

**Comment by joshsleeper** [comment]
@kdaily not rushing a response or anything, just tagging for your visibility~

**Comment by kdaily** [comment]
Thanks @joshsleeper, no update yet. We're tracking another similar report for the Linux version of the AWS CLI zip file here: #6259

**Comment by joshsleeper** [comment]
funny enough, basically since my report I haven't seen the Palo Alto agent killing `aws-cli` v2 once 😆, despite the fact that I upgrade to the latest release daily.

unsure if the agent finally wised up about it being alright, or if something it was particularly sensitive to happened to change on your side around that time. ¯\\\_(ツ)\_/¯

**Comment by kdaily** [comment]
I contacted Palo Alto, but haven't heard back; I imagine it cleared up on it's own. Feel free to re-open this if you experience it again. Thanks for letting me know!
