### ISSUE TITLE
dyld: Library not loaded:

### ISSUE THREAD

**Issue by fxgx99** [aws/aws-cli#6075]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

**Describe the question**
I know the problem is not with cli but my system. Since upgrading to Big sur i have more problems than I can count. 
starting `aws --version`... I get the following error message
`dyld: Library not loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
  Reason: image not found
[1]    78537 abort      aws --version`
Initially i thought this would be a small fix so i used `brew update && brew upgrade` that didnt work, I then used `brew uninstall awscli && brew install awscli` I believe the issue has to some linking Libraries but 5 hours later... I haven't found a solution yet. Any help will be very much appreciated 
**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @fxgx99,

We do not maintain the brew installation of the CLI, so unfortunately for issues with that you'll need to head over to the Homebrew repository. We also don't officially support Big Sur at the moment but many users have used it successfully. If these issues reoccur with the supported installation methods, update us here!

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html
