### ISSUE TITLE
aws sts get-caller-identity does not return to shell automatically

### ISSUE THREAD

**Issue by skarungan** [aws/aws-cli#6085]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Mac OS Big Sur (11.2.3)
Shell: on both `zsh` and `bash`
AWS CLI: `aws-cli/2.1.36 Python/3.8.8 Darwin/20.3.0 exe/x86_64 prompt/off`

**Describe the question**
When running `aws sts get-caller-identity` it doesn't automatically return to shell prompt, it shows output similar to 
![image](https://user-images.githubusercontent.com/13727764/114255773-0b336980-99d3-11eb-8a04-7fbe0d64d2bd.png)

Have to press Ctrl + C every time to exit. Is this expected behaviour ? How to make it return to shell automatically ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by skarungan** [comment]
setting `AWS_PAGER="" ` fixed it

**Comment by kdaily** [comment]
Hi @skarungan - also check out the section "How to use pager flags" on this page for how to set your `LESS` flags - this is common on Mac OS.

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html
