### ISSUE TITLE
You can't disable url lib errors with version 2 - why not pip?

### ISSUE THREAD

**Issue by rlewkowicz-rcd** [aws/aws-cli#6089]
If you pass the --no-verify-ssl flag you get unsightly errors and traditionally you would export something like
```
export PYTHONWARNINGS="ignore" 
```
and it would disable url lib warnings

I don't know why we moved away from pip, the agnostic industry standard for installing python packages in favor of platform dependent binaries. This is all still python?

**Comment by stobrien89** [comment]
Hi @rlewkowicz-rcd, 

Thanks for writing in!  This happens for essentially the same reason mentioned in [this comment](https://github.com/aws/aws-cli/issues/5086#issuecomment-618495061) on a similar issue— We are using pyinstaller to freeze Python into our executable and that does not respect various Python env vars at runtime.

Regarding pip, we definitely understand your frustration here— this has been a pretty contentious topic for us and some of the logic behind our decision not to publish to PyPi has been shared [here](https://github.com/aws/aws-cli/issues/4947).

We could potentially mark this as a feature request for another env var (similar to `AWS_CLI_FILE_ENCODING`), but I'd need to check with the team first to see if that's a possibility.  Let me know if that sounds good to you!

**Comment by stobrien89** [comment]
Hi @rlewkowicz-rcd,

Just a follow-up to my mention of a feature request for another env var— The team isn't open to implementing something like this to suppress url lib warnings related to `--no-verify-ssl` alone, as it would technically be bad security practice, but if there are other more compelling reasons that come up in the future, it sounds like something they might explore further.  Let us know if you have any questions!
