### ISSUE TITLE
aws rds generate-db-auth-token creates an empty X-Amz-Security-Token that RDS proxy IAM auth does not like 

### ISSUE THREAD

**Issue by alisade** [aws/aws-cli#6091]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws rds generate-db-auth-token` creates an empty `X-Amz-Security-Token=` that RDS proxy IAM auth does not like and as a result auth fails as below:

```
2021-04-12T23:34:30.377Z [INFO] [proxyEndpoint=default] [clientConnection=288502846] Proxy authentication with IAM authentication failed for user "admin" with TLS on. Reason: The proxy couldn't authenticate using IAM. A value is missing for the parameter "X-Amz-Security-Token". Generate a new authentication token and use it in a new client connection.
```

Using the below code
```
import sys
import boto3
from os import environ

ENDPOINT="XXXXXXXXXXXXX"
PORT="3306"
USR="XXXX"
REGION="us-east-1"
environ['LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN'] = '1'

#gets the credentials from .aws/credentials
client = boto3.client('rds')

token = client.generate_db_auth_token(DBHostname=ENDPOINT, Port=PORT, DBUsername=USR, Region=REGION)

print(token)
```
works and does not create the issue.

**SDK version number**
aws-cli/2.1.36 Python/3.8.8 Linux/5.4.0-1041-aws exe/x86_64.ubuntu.18 prompt/off
**Platform/OS/Hardware/Device**
Linux Ubuntu 18.04 and OSX 1.15.7
What are you running the cli on?
cloud9 terminal and iterm on OSX

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**
1. Create an IAM user that is granted Connect on RDS proxy
2. `P=$(aws rds generate-db-auth-token --hostname XXXXXXX --port 3306 --region us-east-1 --username XXXX)`
3. `mysql -h XXXXX -u XXXX -enable-cleartext-plugin --password=$P`
**Logs/output**

```mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'admin'@'%' (using password: NO)```
Now check cloudwatch logs (enable enhanced logging on the proxy)
```

```
2021-04-12T23:34:30.377Z [INFO] [proxyEndpoint=default] [clientConnection=YYYYYYY] Proxy authentication with IAM authentication failed for user "XXXX" with TLS on. Reason: The proxy couldn't authenticate using IAM. A value is missing for the parameter "X-Amz-Security-Token". Generate a new authentication token and use it in a new client connection.
```

Get full traceback and error logs by adding `--debug` to the command.
no more debugging available 
**Additional context**
run the boto3 based 
`token = client.generate_db_auth_token(DBHostname=ENDPOINT, Port=PORT, DBUsername=USR, Region=REGION)` without the cli and it works like a charm (can connect to db - no more error) and the only difference is the presence of `Amz-Security-Token=&` in the CLI output

**Comment by alisade** [comment]
found the issue it was due to an empty extra `aws_session_token =` and the end of `~/.aws/credentials`

**Comment by ahmari6** [comment]
I think this is a valid and ongoing issue. If you generate auth-token from assumed role session, X-Amz-Security-Token is included in the auth token and connection is successful. If you are using access key and secret from .aws/credentials, X-Amz-Security-Token is missing from auth token and authentication fails. We've overcome this with following wizardy:

```
result="$(aws sts get-session-token)"
export AWS_ACCESS_KEY_ID=`echo ${result} | jq -r '.Credentials.AccessKeyId'`
export AWS_SECRET_ACCESS_KEY=`echo ${result} | jq -r '.Credentials.SecretAccessKey'`
export AWS_SESSION_TOKEN=`echo ${result} | jq -r '.Credentials.SessionToken'`
aws rds generate-db-auth-token --hostname $RDSHOST --port 5432 --region eu-west-1 --username db
unset AWS_ACCESS_KEY_ID; unset AWS_SECRET_ACCESS_KEY; unset AWS_SESSION_TOKEN
```
