### ISSUE TITLE
Windows executables missing Version Resource

### ISSUE THREAD

**Issue by teborbobo** [aws/aws-cli#6102]
Recent CLI versions no longer include a Windows file Version Resource, showing file Details (as seen in the Details tab of File | Properties).  A few years back (prior to the 1.16 release) the Windows CLI aws.exe included a Windows Version Resource with Company, Product, Version, file Description, so maybe someone just dropped the ball on this.

Without a file Version Resource, it's awkward on Windows to track the installed version of aws.exe across computers.

Please put the Version Resource back into the aws.exe executable!

**Comment by kdaily** [comment]
Hi @teborbobo,

I pulled the recent version and confirmed what you see. However I went back to old versions and it doesn't seem to exist there either. I tried 1.18.223 and 1.16.213, and neither of those had those details. I also tried 1.16.1 and 1.15.85, and these versions ship with a Windows command script, not an exe. Can you provide the last known version that displayed the information?

I'll look into it further. Thanks!
