### ISSUE TITLE
AWS cloudformation deploy command unable to create changeset when deleting and recreating dynamic reference

### ISSUE THREAD

**Issue by tongak** [aws/aws-cli#6106]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Updating a dynamic reference in cloudformation stored in parameter store by deleting and recreating the parameter causes the aws cloudformation deploy command to throw the following error when try to create a changeset.

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Parameters: [ssm:parameter:1:16188..] were updated before values were used

**SDK version number**
aws-cli/2.1.19 Python/3.7.3

**Platform/OS/Hardware/Device**
What are you running the cli on?
Linux/WSL Windows Surface Laptop
Also not working in our codebuild project using the image aws/codebuild/standard:4.0.

**To Reproduce (observed behavior)**
1. Deploy a cloudformation template that has a dynamic reference to a parameter stored in parameter store using the aws cloudformation deploy command. (i.e. '{{resolve:ssm:/test/parameter:1}}')
2. Delete the parameter in parameter store and recreate the same parameter with the same name
3. Update the stack using the aws cloudformation deploy command. (You must update a property in one of the resources or cloudformation will think that nothing has changed.)
4. The command will start a changeset and then return the error above.

**Expected behavior**
The aws cloudformation deploy commands updates the stack with the new parameters without any errors.

**Logs/output**
The output is long with the debug command. I am pasting the last bit of the log.
2021-04-20 09:16:45,463 - MainThread - awscli.customizations.cloudformation.deployer - DEBUG - Create changeset waiter exception
Traceback (most recent call last):
  File "awscli/customizations/cloudformation/deployer.py", line 163, in wait_for_changeset
  File "botocore/waiter.py", line 53, in wait
  File "botocore/waiter.py", line 346, in wait
botocore.exceptions.WaiterError: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED"
2021-04-20 09:16:45,469 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/customizations/cloudformation/deployer.py", line 163, in wait_for_changeset
  File "botocore/waiter.py", line 53, in wait
  File "botocore/waiter.py", line 346, in wait
botocore.exceptions.WaiterError: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 457, in main
  File "awscli/clidriver.py", line 586, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/cloudformation/deploy.py", line 357, in _run_main
  File "awscli/customizations/cloudformation/deploy.py", line 372, in deploy
  File "awscli/customizations/cloudformation/deployer.py", line 227, in create_and_wait_for_changeset
  File "awscli/customizations/cloudformation/deployer.py", line 178, in wait_for_changeset
RuntimeError: Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Parameters: [ssm:/test/parameter:1:1618.....] were updated before values were used

**Additional context**
This might be related to the new release of allowing dynamic reference in parameter store to not require a version number. I also used the --no-execute-changeset flag in the command and it still returned the same error.
Using the aws cloudformation update-stack does not cause this error. The error seems to happens when a changeset it required first before deployment.

**Comment by stobrien89** [comment]
Hi @tongak,

Thanks for the report and debug logs!  Currently attempting to reproduce— I'll let you know as soon as I have more info.

**Comment by stobrien89** [comment]
Hi @tongak,

I was able to reproduce using a dynamic reference as a value for `BucketName` on a S3 resource— were you able to successfully run another `deploy` command after deleting and re-adding an ssm parameter previously? 

It doesn't look like this extends to `update-stack`, as I was able to update the stack using the same template (with altered resource properties) with no problems by providing the `--template-body` as a `file://<path_to_template_file>` or `--template-url`, which would be a more efficient/appropriate operation for an update— is there a specific reason you're using another `deploy` to update the stack?

**Comment by tongak** [comment]
Thanks for looking into this @stobrien89.

Were you able to successfully run another deploy command after deleting and re-adding an ssm parameter previously?
Yes, this issue only showed up this week. I would delete and re-add the ssm parameter as a work around on the restriction of needing a version number as part of the dynamic reference. Deleting and re-adding would set the version back to 1 and didn't have to mess with the cloudformation template. This restriction was just resolved recently on Apr. 15. (https://aws.amazon.com/about-aws/whats-new/2021/04/now-reference-latest-aws-systems-manager-parameter-values-in-aws-cloudformation-templates-without-specifying-parameter-versions/). 

Is there a specific reason you're using another deploy to update the stack?
We use the command in our pipelines for deploying cloudformation stacks. The deploy command will create the stack if it does not exist and update the stack when it already exists. It provides simplicity of one command vs multiple commands (i.e. create-stack, create-change-set, update-stack)

**Comment by stobrien89** [comment]
Hi @tongak,

Thanks for the clarification!  That makes sense to me.  I'll reach out to the cloudformation team to see if this is expected behavior.  I can't set any expectations on their behalf in terms of response time, but I'll let you know as soon as I have more information.

**Comment by stobrien89** [comment]
P46478042

**Comment by tongak** [comment]
Thank you @stobrien89. I appreciate the help.

**Comment by JeremySB** [comment]
Hey - this is an known issue by the CFN team and we are currently rolling out a fix, which is live in eu-central-1 if you want to confirm. The workaround until then is to use UpdateStack directly without a change set. Thanks for reporting this!

**Comment by krisb78** [comment]
HI @JeremySB , I have just hit this error when calling update-stack (without a change set)... My exact command is:

```
aws cloudformation update-stack --stack-name staging-legacy-ecs --use-previous-template --parameters "$(aws cloudformation describe-stacks --stack-name staging-legacy-ecs --query 'Stacks[0].Parameters')" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM 2>err.log; then aws cloudformation wait stack-update-complete --stack-name staging-legacy-ecs; else grep 'No updates are to be performed' err.log || (cat err.log && exit 1); fi

An error occurred (ValidationError) when calling the UpdateStack operation: Parameters: [ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id:58:1618453901392] were updated before values were used
```

the stack in question was created using CDK.

**Comment by tongak** [comment]
I tested this a few weeks and it seems to be fixed now. I do not receive the error anymore when following the steps I described when this issue was opened.

**Comment by stobrien89** [comment]
Thanks for the update @tongak.  I was waiting on a definitive resolution to this, as it appeared a fix had been rolled out in select regions.  Is anyone else still experiencing the issue?

**Comment by stobrien89** [comment]
Hi all,

I received confirmation that the patch for this has been released in all available regions.  Please let us know if anything else comes up!
