### ISSUE TITLE
aws sqs list-queues returns incomplete result

### ISSUE THREAD

**Issue by geekingfrog** [aws/aws-cli#6112]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws sqs list-queues` returns up to 1k results, even when the account has more.

**SDK version number**
`aws-cli/2.0.56 Python/3.7.3 Linux/5.11.14-arch1-1 exe/x86_64.arch`

**Platform/OS/Hardware/Device**
archlinux

**To Reproduce (observed behavior)**
`aws sqs list-queues` on an account with more than 1k queues.

**Expected behavior**
```
{
    "QueueUrls": [
        "https://sqs.eu-west-1.amazonaws.com/accountnumber/queue-name",
        ...
    ]
}
```
with `QueueUrls` having *all* the queue here.

**Logs/output**
Same as the expected behavior's output, but only up to 1k urls.

**Comment by kdaily** [comment]
Hello @geekingfrog,

Per the documentation, this looks expected? I can pass along your feedback to the SQS team.

https://docs.aws.amazon.com/cli/latest/reference/sqs/list-queues.html

>  Returns a list of your queues in the current region. The response includes a maximum of 1,000 results.

**Comment by geekingfrog** [comment]
Ah, you're right. Closing then.
It would be nice to have an option to get everything automatically, doing the pagination under the hood, but I guess that's for another ticket.
Thanks.
