### ISSUE TITLE
aws s3 sync ignore open files

### ISSUE THREAD

**Issue by nocentino** [aws/aws-cli#6129]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Windows

**Describe the question**
I'm using aws s3 sync to sync from a Windows server into an s3 bucket and  get intermittent failures because some of the files are in use when the sync process kicks off. Is there a way for aws s3 sync to ignore open files?

**Comment by stobrien89** [comment]
Hi @nocentino,

Sorry to hear about the issues.  I don't believe there's a way to exclude open files specifically, but I'll double-check with the team tomorrow.  Are you trying to upload all files from a given directory to the bucket? If so, I'd be curious to see if you have any better luck with a `s3 cp --recursive`.

**Comment by nocentino** [comment]
HI @stobrien89 - Yes, I'm trying to keep a local directory in sync with what's in an s3 bucket. I run a task every 5 mins and sometimes s3 sync hits a file in use an causes the task to fail.  When s3 sync hits a file it use it stops at that point in time and exits. I don't think cp will work because it would copy files that have been copied out to s3 already.

**Comment by stobrien89** [comment]
Hi @nocentino,

That makes sense— probably best to stick with sync in that case.  Would it be possible for you to share debug logs for an instance where it fails? Please remove any sensitive information, such as account numbers.  Thanks!

**Comment by nocentino** [comment]
Yes. Let me get that going and I'll send over something shortly. Thanks again!
