### ISSUE TITLE
[1.2.11][ec2][run-instances] secondary-private-ip-address-count - InvalidParameterCombination

### ISSUE THREAD

**Issue by marekjagielski** [aws/aws-cli#613]
When running command with --secondary-private-ip-address-count 1:

aws ec2 run-instances --image-id ami-eef31499 --security-group-ids sg-bp8eo6dd --user-data data --instance-type t1.micro --subnet-id subnet-14d4uc63 --iam-instance-profile Name=gateway --count 1 --secondary-private-ip-address-count 1 --region eu-west-1 --profile int

I get:

A client error (InvalidParameterCombination) occurred when calling the RunInstances operation: Network interfaces and an instance-level subnet ID may not be specified on the same request

However setting separately --secondary-private-ip-address-count 1:

aws ec2 assign-private-ip-addresses --network-interface-id eni-243a2357 --secondary-private-ip-address-count 1 --region eu-west-1 --profile int

everything goes fine.

**Comment by jamesls** [comment]
Looks like we need to expand on https://github.com/aws/aws-cli/pull/222 and account for a subnet id being specified.

**Comment by kyleknap** [comment]
Fixed via referenced merged PR.
