### ISSUE TITLE
aws deploy get-application-revision --revision parameter 

### ISSUE THREAD

**Issue by giusmuscolo** [aws/aws-cli#6136]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When launching _aws deploy get-application-revision --application-name $APP_, the command returns the following error message: _Missing required parameter in input: "revision"_

Said parameter is listed as optional in the [CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/deploy/get-application-revision.html#synopsis).

**Platform/OS/Hardware/Device**
What are you running the cli on?

MacOS 11.3

**To Reproduce (observed behavior)**
Run the  _aws deploy get-application-revision_ command specifying the --application-name parameter only

**Expected behavior**
AWS CLI qill return an error saying the revision parameter is required
```
Parameter validation failed:
Missing required parameter in input: "revision"

```

**Comment by stobrien89** [comment]
Hi @giusmuscolo,

Thanks for bringing this to our attention! The [CodeDeploy documentation](https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_GetApplicationRevision.html) lists this as a required parameter— CodeDeploy generates the sdk reference guides, so I'll need to reach out to them to have this corrected.

**Comment by stobrien89** [comment]
P46985349

**Comment by stobrien89** [comment]
Hi @giusmuscolo,

I reviewed this with the team and found that this issue doesn't stem from the service team documentation, but actually has to do with some customizations we applied to this operation: Because `--s3-location` and `--github-location` can be used as substitutes for the `--revision` option, `--revision` is technically not required, but this could definitely be documented better.

**Comment by giusmuscolo** [comment]
Thanks a lot for the clarification @stobrien89 ,

**Comment by stobrien89** [comment]
After further review, since this is how we handle other custom params and it is _technically_ correct, no changes will be made at this time.  Please let me know if there are any questions!
