### ISSUE TITLE
Error in connect! Type: <class 'ssl.SSLCertVerificationError'>

### ISSUE THREAD

**Issue by VishwamShuklaRemote** [aws/aws-cli#6140]
Hi, I am getting this SSL error while trying to connect at Core.
Error in connect!
Type: <class 'ssl.SSLCertVerificationError'>
Error message: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
Trying to connect to core at 172.17.0.1:8883

Help would be appreciated!

**Comment by kdaily** [comment]
Hi @VishwamShuklaRemote,

I don't have enough information to know where this error is coming from. Please use the template provided in the issue to answer the questions that will help us answer your questions.

Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

**Describe the question**


**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
