### ISSUE TITLE
GreenGrass Deployment error

### ISSUE THREAD

**Issue by VishwamShuklaRemote** [aws/aws-cli#6141]
Hi,
I am trying to deploy the GreenGrass group after rotating the certificates of the devices. But the error is We cannot deploy because the group definition is invalid or corrupted for the following reasons: {ErrorSet(errorSet=[ErrorModel(errorCode=THING_CERT_NOT_FOUND_ERROR,. It's taking the older certificate of the device instead of the latest certificate after rotation. Please let me know if this can be solved.
Thanks

**Comment by kdaily** [comment]
Hi @VishwamShuklaRemote,

I don't have enough information to know where this error is coming from. Please use the template provided in the issue to answer the questions that will help us answer your questions.

Confirm by changing [ ] to [x] below:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

**Describe the question**


**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
