### ISSUE TITLE
Make `aws lambda invoke` composable on CLI

### ISSUE THREAD

**Issue by adamcrosby** [aws/aws-cli#6146]
**Is your feature request related to a problem? Please describe.**
`aws lambda invoke` prints the API call metadata to stdout, and the actual function output to `outfile` argument. This means we cannot use lambda in shell pipelines without `mktemp()` and other filesystem hackery, which is painful/dangerous to cleanup if something fails mid-script.

**Describe the solution you'd like**
An option to have invoke, when run synchronously, emit the actual function return payload to stdout OR suppress the metadata from the API return (if you make `outfile` `stdout` you get a race condition with the API response and the metadata about the API call stepping on each other.

**Describe alternatives you've considered**
Currently working around this by making temporary files or using FIFOs on the filesystem.

**Additional context**
n/a

**Comment by stobrien89** [comment]
Hi @adamcrosby,

Thanks for the feature request!
