### ISSUE TITLE
modify-transit-gateway --options AddTransitGatewayCidrBlocks - not working

### ISSUE THREAD

**Issue by mtarnoci** [aws/aws-cli#6151]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windows 10
**Describe the question**
I want to modify Transit Gateway via CLI, add CIDR Bolock and configure Connect Attachement. according documentation:
https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-transit-gateway.html it should be possible by:

The options to modify.

AddTransitGatewayCidrBlocks -> (list)

Adds IPv4 or IPv6 CIDR blocks for the transit gateway. Must be a size /24 CIDR block or larger for IPv4, or a size /64 CIDR block or larger for IPv6.

(string)

when I try it, I get an error
[debug_transit_GW_add_CIDR.txt](https://github.com/aws/aws-cli/files/6445877/debug_transit_GW_add_CIDR.txt)
[debug_transit_GW_add_CIDR.txt](https://github.com/aws/aws-cli/files/6445878/debug_transit_GW_add_CIDR.txt)

:
C:\Users\MarekTarnoci>aws ec2 modify-transit-gateway --transit-gateway-id tgw-05f9f809ad146ac93 --options AddTransitGatewayCidrBlocks=[192.168.24.0/24]

Parameter validation failed:
Unknown parameter in Options: "AddTransitGatewayCidrBlocks", must be one of: VpnEcmpSupport, DnsSupport, AutoAcceptSharedAttachments, DefaultRouteTableAssociation, AssociationDefaultRouteTableId, DefaultRouteTablePropagation, PropagationDefaultRouteTableId

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by stobrien89** [comment]
Hi @mtarnoci,

Thanks for writing in!  I did some digging and it looks like `AddTransitGatewayCidrBlocks` was added as a parameter on 12/10/2020— the day after the version you're using was released.  Bumping up to the latest version (or anything beyond `2.1.10`) should resolve this.
