### ISSUE TITLE
Support short -r flag for recursion

### ISSUE THREAD

**Issue by mcandre** [aws/aws-cli#6159]
For more intuitive workflows based on traditional local `cp -r`.

**Comment by stobrien89** [comment]
Hi @mcandre,

Thanks for the feature request!  Just to clarify, this is intended for s3 operations that support the `--recursive` flag?

**Comment by stobrien89** [comment]
Hi @mcandre, 

Just a heads-up: I'm going to combine this issue with #6160 as they both concern conformance to standard Unix commands.  Let us know if you have any questions!
