### ISSUE TITLE
s3 Unix command compatibility mode

### ISSUE THREAD

**Issue by mcandre** [aws/aws-cli#6160]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

When copying files locally with industry standard UNIX `cp`, then the destination path's folder is intuitively preserved.

E.g., a file `c.txt` in parent folder `b` will be copied to `a/b/c.txt` in `cp -r b a/`.

However, `aws s3 cp --recursive s3://mybucket/b a/` does not preserve the path correctly. `c.txt` will appear in the flatter hierarchy `a/c.txt`.

As a workaround, the user is forced to use the unconventional syntax `aws s3 cp --recursive s3://mybucket/b a/b/`. This is redundant and unintuitive and breaks convention.

When the source contains numerous objects, then the destination will be polluted with hundreds of entries that can even overwrite the wrong path, because of this breakage.

**Comment by kdaily** [comment]
Hi @mcandre, thanks for raising this issue. Having a stricter compatibility mode with standard UNIX commands would be useful. I'm not sure what the standard pattern or behavior is on Windows systems, but that would need to be taken into account as well.
