### ISSUE TITLE
aws s3 sync hanging, both v1 and v2

### ISSUE THREAD

**Issue by pjninnis** [aws/aws-cli#6164]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
As previously reported by others, but no resolution, the s3 sync process is continuallly just hanging on a daily basis. We have a Windows process that frequently syncs from a Windows EC2 instance to an S3 bucket, which has been successfully running for several years, but is now hanging almost once a day (after running succesful multiple times during the day lrior to hanging). The amount on data on the S3 bucket is probably now almost a million small files and on the EC2 instance, much less.
I did notice high cpu usage on the instance, but plently of memory, but it wasn't seemingly doing anything else other than the sync process. The files in question are only less than 5MB at a time.
We need the s3 sync to fail with an error or at least timeout.
There's no error output from command, and it just hangs indefinitely (>4hour) during syncing, with some files previously successfully syncd, and never returns/completes.

**SDK version number**
Started to recently fail on V1, so update to latest V2 CLI,  but same behaviour.

**Platform/OS/Hardware/Device**
What are you running the cli on?
EC2 Windows Server to S3 Bucket (same region).

**To Reproduce (observed behavior)**
Unknown

**Expected behavior**
Work or fail with error or timeout.

**Logs/output**

**Additional context**

**Comment by stobrien89** [comment]
Hi @pjninnis,

Sorry to hear about the issues.  Would it be possible for you to provide debug logs for the period of time leading up to where it hangs?  Just need a bit more information in order to troubleshoot/reproduce this.  If so, please obscure any sensitive information, such as account numbers.  Thanks!

**Comment by pjninnis** [comment]
This is on a productions instance, and we weren't producing debug information. We switched it to a larger EC2 instance and the problem disappears for a number of days, so we were hesitant to turn on the debugging while it was working ok, but we've just had another hang, so we will redeploy with the debugging on and forward the logs the next time it hangs.
Is there any available theories as to why it would be periodically hanging now? We can't be the only people experiencing this.

**Comment by stobrien89** [comment]
Hi @pjninnis, 

Thanks for doing that— I know it's not always easy to do with a production instance.  It's really tough to say without having additional context like logs, but are you using any other flags in addition to `--size-only`? Also, have you set any [s3 configuration values](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) like `max_bandwidth` or `max_concurrent_requests` ? Thanks again!

**Comment by pjninnis** [comment]
The sync cmd we were using is just: aws s3 sync --size-only $syncFolder $s3location --acl bucket-owner-full-control 
and some --excludes. We're now trying without the sizeonly.
We have tried with the defaults, but also tried with:
aws configure set default.s3.max_concurrent_requests 100
aws configure set default.s3.max_queue_size 10000
but both with and without seemed to take about the same time and both examples exhibited the hanging behaviour.

The current configuration has been running successfully for a few days with debug on and no sizeonly option.
It is taking about 30minutes to complete and producing around 120GB of debug each time. Is there a way to limit the amount of debug created and only record problematic debug messages?
Thanks

**Comment by stobrien89** [comment]
Hi @pjninnis,

Thanks for the additional info.  Glad it's been working for a few consecutive days! I think you might be onto something with the `--size-only` flag.  I'll review with the team to get their thoughts on this early next week.  

As for the debug logs, there is unfortunately not an option to make them any less verbose, as much as that would be great for this situation.

**Comment by pjninnis** [comment]
We removed the --size-only option, and were running successfully for a few days, but it hung again last night.
Unfortunately we had turned off the debugging because it was consuming all the diskspace on the instance, so we didn't acquire anymore information.

We've now had to convert the script in question to use aws s3 cp instead of the aws s3 sync, so we probably won't be able to supply any further information to help you track down the intermittent hanging bug.

Thanks for looking into it though.

**Comment by stobrien89** [comment]
@pjninnis,

Sorry to hear that 😞.  I'll review this with the team tomorrow to see if anything stands out, based on information provided so far.

**Comment by stobrien89** [comment]
Hi @pjninnis,

Sorry for the delayed response. I wanted to let you know that I reviewed with the team and unfortunately there was no consensus— They did say that this can often be network-related, but it's nearly impossible for us to tell without having logs to reference.  Has there been any improvement?

**Comment by pjninnis** [comment]
Yes, its unfortunate that it was intermittent, and only occurring in production, otherwise we couldve persisted with trying to provide more debugging to help you track down the issue.
Since switching to use s3 cp instead we havent had an issue and it is much much faster.

**Comment by stobrien89** [comment]
@pjninnis, 

Glad to hear you found a suitable workaround.  Please let us know if you ever have anything else come up!
