### ISSUE TITLE
[v2] Auto-prompt mode doesn't facilitate start/end time parameters

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#6176]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device*
Archlinux aws-cli/2.1.35 Python/3.8.8 Linux/5.12.4-arch1-2 exe/x86_64.arch prompt/off

**Describe the question**
`aws --cli-auto-prompt` with cloudwatch doesn't help to fill in start / end time which is notoriously manual / tedious to fill in!

<img src="https://s.natalian.org/2021-05-18/1621311169_1918x1047.png">

**Comment by kdaily** [comment]
Hi @kaihendry,

Thanks! This sounds like a feature request. That's a timestamp type, so this could be used in any parameter that was a timestamp. What kind of interface for time entry would you like to see?

**Comment by kaihendry** [comment]
Perhaps something like the console affords, like last 1m, 30m, 1h

![image](https://user-images.githubusercontent.com/765871/118743075-3a67b100-b884-11eb-80f1-5fdb1838221b.png)
