### ISSUE TITLE
`amplify push` does not update functions

### ISSUE THREAD

**Issue by pagameba** [aws/aws-cli#6177]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Running `amplify push` shows no change to a function yet the deployed function is not up to date with local code.

**SDK version number**
4.50.2

**Platform/OS/Hardware/Device**
MacOS

**To Reproduce (observed behavior)**
We have included the generated graphql statements in some amplify lambda functions.  Occasionally, after the graphql schema updates, `amplify push` does not seem to update the function and it starts failing because of the schema change, however the local copy of the graphql queries.js and subscriptions.js are definitely updated.

Running `amplify push --force` does not force the function to redeploy.

**Expected behavior**
If there are local changes to files included with the amplify function, then it should get deployed.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

I will try to add this the next time I observe this happening.

**Additional context**

**Comment by kdaily** [comment]
Hi @pagameba,

The Amplify CLI is a separate project. To get support for this, please head over to the following repository to open an issue. Unfortunately it's in a separate GitHub organization so I cannot transfer this issue there. Sorry for the inconvenience!

https://github.com/aws-amplify/amplify-cli

**Comment by pagameba** [comment]
opps!
