### ISSUE TITLE
CLI Team Update

### ISSUE THREAD

**Issue by shaunhickson** [aws/aws-cli#6186]
This is the first of what will be monthly updates on the plan for the AWS CLI team. At the moment, the team is engaged in three primary efforts:

**1) Improve our build and release process.** This work stream includes enhancements to both our internal and external release mechanisms. One of the frustrations shared by both our internal service team customers and our external community is the lack of daily releases. We are in the process of integrating with the AWS SDKs and Tools daily release process, and are automating some of the remaining manual components of our release pipeline. Once this is done, CLI v2 will be available with all new service updates the same day they are released, and will support new service launches immediately.

**2) Provide a source distribution of CLI v2.** We are aware that the community wants the CLI available on platforms and through channels beyond those which the team currently supports. By providing a supported source distribution, we intend to enable the community to effectively build and install the CLI on any platform where it’s needed. We will also work with the maintainers of large and popular distribution channels to ensure that the CLI is available via those channels. We will be releasing a draft plan for providing this source distribution soon, and welcome community feedback on it.

**3) Work on Github Issues.** Our Github backlog is longer than we’d like, and we will be investing throughout the year in reducing the number of open issues. We recently resolved: [pager invoked even when there is no output](https://github.com/aws/aws-cli/issues/5144) and [Configure List command shows wrong source from profile from env](https://github.com/aws/aws-cli/issues/2028). We’re actively working on: [Add --no-overwrite option to aws s3 cp/mv](https://github.com/aws/aws-cli/issues/2874),  [Add tagging support to s3](https://github.com/aws/aws-cli/issues/2458), and [s3 sync does not preserve permissions across buckets](https://github.com/aws/aws-cli/issues/901). We have identified general areas of concern that we continue to focus on, including more work on configuration and s3 sync. We will identify and share specific issues on those fronts in coming updates. We welcome your input in this process, please vote and comment on issues that are important to you.

As I mentioned, these are all priorities for us at this time. We don’t provide estimated completion or availability dates because operational issues or unexpected AWS-wide priorities may take priority over our team’s plans.

There’s one other thing I’d like to call out in this update: [we’re hiring!](https://www.amazon.jobs/en/jobs/1558679/software-development-engineer). **If you’re interested in working on the AWS CLI full-time, we’d love to hear from you.** You can reach out to me directly (send me a message here or @shaunhickson on Twitter), or follow the link and submit your information there. This role can sit in either New York or Seattle. Please let me know if you have any questions about the role.

**Comment by pwillis-els** [comment]
Hi @kdaily , is there an individual breakdown of the above efforts in separate issues? Interested in the draft plan for the source release! Your comments on some other issues hint that it might be coming soon?

**Comment by akumria** [comment]
Hi @shaunhickson ,

It has been a few months since your first update -- do you have a link to the subsequent ones available?

If there are no subsequent updates, could you help me - and the rest of the community - understand when you might (A DfaD if you will) be able to recalibrate your communication timeline to what your team can deliver.

**Comment by kdaily** [comment]
Hi all, see our August team update at https://github.com/aws/aws-cli/issues/6355.

@pwillis-els, we aren't currently breaking down specific efforts for internal efforts, like our release process. The new update provides links to the current status and implementations of the other issues, as well as a proposal for the source distribution for feedback and review.

@akumria - I'll be making subsequent updates, starting with the August one linked above. Thanks!
