### ISSUE TITLE
Lambda outputs environment variables; Add ability to suppress this

### ISSUE THREAD

**Issue by DerekCresswell** [aws/aws-cli#6191]
**Is your feature request related to a problem? Please describe.**
When using `aws lambda update-function-code`, for instance, the output includes an 'Environment' section which lists environment variables. This contains potentially sensitive information such as a database password.

**Describe the solution you'd like**
There should be a command line option to show only errors (non of the json returned) or, better, a `--hide-env-variables` option that simply does not return the environment variables section.

**Describe alternatives you've considered**
For the time being I have piped the output of these commands into `/dev/null` which effectively shows only the errors but it also means I miss out on all other information that might have been useful. While this works, it should be a native option here as it would be easy to forget to add the pipe.

**Additional context**
Discussion of this issue can be found around the internet. For instance, [this SO question](https://stackoverflow.com/questions/56614404/how-to-suppress-aws-lambda-cli-output) which is where I got the `/dev/null` suggestion.

**Comment by stobrien89** [comment]
Hi @DerekCresswell,

Thanks for the feature request!

**Comment by stobrien89** [comment]
Hi @DerekCresswell,

I was able to review this with the team and the consensus is that we would not implement something like this because we already have a way to suppress command output with [client-side filtering](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side).

For instance, something like this:
```
aws lambda update-function-code --function-name exampleFunction --zip-file fileb://lambda.zip --query '{FunctionName:FunctionName,LastUpdateStatus:LastUpdateStatus,PackageType:PackageType}'
```
would yield:

```
{
    "FunctionName": "exampleFunction",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}
```

Or,  you could query an invalid value, which still results in a successful API call, but prints `null` as the output:

```
aws lambda update-function-code --function-name exampleFunction --zip-file fileb://lambda.zip --query 'function.name'
```

Hope this helps!

**Comment by sputnik-adam** [comment]
The larger issue here is that code repos are an attack vector, so even if there is a way to not output this, if an attacker gains access to GitHub repo with a deploy Action that pushes code to a Lambda function, all they have to do is go to the Actions history for the repo and see all the environment variables being spat out into the console output. If they're being hidden by a command switch, that command switch can be removed by committing a change that removes the switch.

The command `aws lambda update-function-code` should not output environment variables at all and there should be no way of turning that behaviour on. A user who is allowed to see environment variables can go to the Lambda Console UI and see them.
