### ISSUE TITLE
longer expiration for eks token

### ISSUE THREAD

**Issue by itaru2622** [aws/aws-cli#6201]
Is it possible to get  longer expiration for eks get-token than 15mins?
related to #2807

In current version, eks token expires every 15mins, as described in develop/awscli/customizations/eks/get_token.py#L70

**Is your feature request related to a problem? Please describe.**

15min is too short in development phase because it needs some tries and errors.
as far as manual operation, we just need to get new token.
but when developing automation script, It becomes terrible work to keep caring about short expiration beside main logic.

**Describe the solution you'd like**
'aws eks get-token' has new optional argument  '--token-expiration' with parameter and its default value is 14min as the same as current.

**Comment by kdaily** [comment]
Hi @itaru2622,

Looks like this is a duplicate request of https://github.com/aws/aws-cli/issues/5185, where it was noted this wasn't going to be changed. According to documentation in the code, this is set like this for a reason (common clients will refresh the token):

https://github.com/aws/aws-cli/blob/a43e128cca183dc2a6e32284705cb3b26552aee6/awscli/customizations/eks/get_token.py#L70-L72

**Comment by itaru2622** [comment]
@kdaily thank you for reference. I will try it.
