### ISSUE TITLE
FR: Add --region flag for aws create-repository

### ISSUE THREAD

**Issue by devrimcavusoglu** [aws/aws-cli#6203]
**Is your feature request related to a problem? Please describe.**
Yes. When try to create an ECR repository with CLI, you are only allowed to do so at region which is your default region captured from `.aws/config` file. There is no --region flag to pass for `aws ecr create-repository`. When automated cycles/scripts where you use cli, it fails to create a repo on regions other than default set on config file. 

**Describe the solution you'd like**
Add a region flag for ECR create-repository. `aws ecr create-repository --region <region>`

**Comment by devrimcavusoglu** [comment]
Apparently; while it is not documented [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/create-repository.html), `--region` flag works on ecr commands.

**Comment by kdaily** [comment]
Hi @devrimcavusoglu,

The `--region` flag applies to the global `aws` command and is available on any of them where region is applicable. The CLI allows you to put that flag anywhere in the command (even after the sub-command, or at the end), but it's parsed the same way.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-options.html
