### ISSUE TITLE
Add maven support for aws codeartifact login command?

### ISSUE THREAD

**Issue by Ghoul-SSZ** [aws/aws-cli#6207]
**Is your feature request related to a problem? Please describe.**
Would like to add maven support for aws codeartifact login command. so far the login command supports pip, twine, npm and nuget. 

**Describe the solution you'd like**
aws codeartifact login command support for maven, which will help set the CODEARTIFACT_AUTH_TOKEN  env variable at least in terminal session.

**Comment by stobrien89** [comment]
Hi @Ghoul-SSZ,

Thanks for the feature request!  I'll pass this along to the members of the codeartifact team that handle this customization.

**Comment by stobrien89** [comment]
P48343202

**Comment by stobrien89** [comment]
Hi @Ghoul-SSZ,

I heard back from the codeartifact team and they did mention that they plan to add maven support at some point in the future— No timeline as of yet, but I'll keep you posted on any updates I receive.

They did provide this suggestion (making use of the `get-authorization-token` operation) to add your token to the environment as a workaround for the time being:

```
export CODEARTIFACT_AUTH_TOKEN=$(aws --region <REGION> codeartifact get-authorization-token --domain <DOMAIN> --domain-owner <DOMAIN_OWNER_ACC_ID> --query authorizationToken --output text) 
```

Hope this helps!

**Comment by bcmedeiros** [comment]
Exporting the environment variable is very annoying to do when using any IDEs as you have to export the variable in the CLI and people usually open the IDE in the GUI, ignoring the environment variable.
Setting the env var in the user profile also doesn't work as the token expires.

Can this issue be reopened, please?
