### ISSUE TITLE
aws sync re-download files with spaces in their name

### ISSUE THREAD

**Issue by flyeee** [aws/aws-cli#6211]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I was trying to sync a large bucket to local. But most of the files keep re-downloading again every time. 
If I do an ls at local, the output is like: /mnt/data/"My File", but the s3 key is /mnt/data/My File
I think that's maybe why the aws s3 sync assumes they are different and keep downloading files every time.
Is there a way to fix that?

**SDK version number**
aws-cli/1.18

**Platform/OS/Hardware/Device**
What are you running the cli on?
ubuntu 20.04

**To Reproduce (observed behavior)**
Put a file to s3 with space in its name and sync to a local folder.

**Expected behavior**
Skip these files when syncing

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @flyeee,

Sorry to hear you're having issues. I was unable to reproduce this on Ubuntu 20.0.4, although I was using version `1.19.92` Would you be able to send debug logs by appending `--debug` to your command?  Please obscure any sensitive information.  Thanks!
