### ISSUE TITLE
S3 cp to copy files to local uses high memory if number of files in million

### ISSUE THREAD

**Issue by ankurshaswat** [aws/aws-cli#6215]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
On running s3 cp to download a folder with number of files in order a million the memory usage of the command is very high (~1GB). I didn't find any option to reduce this usage. This usage can be easily reduced if the downloaded file list is not kept in memory. For eg:- In python boto3, a continuation token is used to keep track of location in list and downloads can be done with low memory usage, albeit very slow. 

**SDK version number**
2.1.29

**Platform/OS/Hardware/Device**
Ubuntu 20.04

**To Reproduce (observed behavior)**
Run aws s3 cp for a bucket with large number of files (>1000000).

**Expected behavior**
Low memory usage.

**Additional context**
This limits usage on low memory devices.

**Comment by stobrien89** [comment]
Hi @ankurshaswat,

Sorry to hear you're having issues.  Is this occurring on a virtual or local machine? And are you noticing any unusual network activity? Thanks!

**Comment by ankurshaswat** [comment]
This is happening on a ec2 virtual machine. No unusual network activity observed.

**Comment by stobrien89** [comment]
Hi @ankurshaswat,

Thanks for confirming.  I was unable to reproduce using the latest CLI version and version `2.1.29` on an Ubuntu 20.0.4 (t2 micro instance type). Memory usage does not exceed 90MB out of 1GB available.  

Can you confirm the instance type, as well as the average size of the files you're copying?
