### ISSUE TITLE
RDS Postgres modify-db-parameter-group

### ISSUE THREAD

**Issue by mixmind** [aws/aws-cli#6219]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Ubuntu 20, golang api

**Describe the question**
Hi, 

I'm trying to change db parameter group via cli and golang API. I have a trouble with changing parameter that his type is list.
How can i pass list of values, if accepteble type of value is string?

For example I'm trying to change shared_preload_libraries:
`
aws rds modify-db-parameter-group --db-parameter-group-name test_group --parameters "ParameterName=shared_preload_libraries,ParameterValue=pg_stat_statemetns,auto-explain,ApplyMethod=pending-reboot"
`
And receiving error :
`
Parameter validation failed:
Invalid type for parameter Parameters[0].ParameterValue, value: [u'pg_stat_statemetns', u'auto-explain'], type: <type 'list'>, valid types: <type 'basestring'>
`

**Comment by stobrien89** [comment]
Hi @mixmind,

I see you're using [short-hand syntax](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-shorthand.html) to provide your parameters— I'm seeing that `auto-explain` is not associated with any of the key-value pairs you're providing.  The valid inputs for the `--parameters` option are listed [here](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Parameter.html) in the RDS documentation.  Hope this helps!

**Comment by mixmind** [comment]
> Hi @mixmind,
> 
> I see you're using [short-hand syntax](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-shorthand.html) to provide your parameters— I'm seeing that `auto-explain` is not associated with any of the key-value pairs you're providing. The valid inputs for the `--parameters` option are listed [here](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Parameter.html) in the RDS documentation. Hope this helps!

Hi, it’s not helped.

The only value that I can provide via cli to change share_preload_libraries it’s string, but I need more than one value.
`aws rds modify-db-parameter-group --db-parameter-group-name test_group --parameters "ParameterName=shared_preload_libraries,ParameterValue=pg_stat_statemetns,ApplyMethod=pending-reboot" "ParameterName=shared_preload_libraries,ParameterValue=auto_explain,ApplyMethod=pending-reboot" `

Also not working.

Can you provide example of modifying db parameter group that its type is list, and you are providing more than one option simultaneously. In classic Amazon web site I can provide more than one parameter

**Comment by stobrien89** [comment]
Hi @mixmind,

My apologies, I misunderstood what you were trying to do here.  From what I understand, it is not possible for a specific parameter to have more than one `ParameterValue`.  I double-checked this in the console as well.  Would you be able to provide an example of you how did this on the website?

Shorthand syntax is limited in that you can't pass the same key-name twice, so if you're attempting to make changes to more than one parameter, it would be best to use JSON input like this:

```   
'[{"ParameterName": "shared_preload_libraries","ParameterValue": "pg_stat_statements", "ApplyMethod": "pending-reboot"}, {"ParameterName": "other_parameter","ParameterValue": "other_value","ApplyMethod": "other_method"}]'
```

note: I did try passing the same `ParameterName` in the above format (similar to your most recent example) as well, but the RDS API returns: 

`An error occurred (InvalidParameterValue) when calling the ModifyDBParameterGroup operation: Duplicate parameters specified in the same call`.

Hope this helps!

**Comment by mixmind** [comment]
Hi @stobrien89 

Sure, I can provide screenshot:
![Screenshot from 2021-06-15 13-25-04](https://user-images.githubusercontent.com/33128809/122136217-aff67b00-ce4a-11eb-8601-a68e131a016a.png)
After adding pg_stat_statements and auto_analyze, Save button works as well.



> note: I did try passing the same `ParameterName` in the above format (similar to your most recent example) as well, but the RDS API returns:
> 
> `An error occurred (InvalidParameterValue) when calling the ModifyDBParameterGroup operation: Duplicate parameters specified in the same call`.
> 
> Hope this helps!

Yes, that what I'm facing too. I want to change one parameter, and pass to it 2 values, only on website it works, can't find any example of dealing with it via rds api.

**Comment by mixmind** [comment]
I also tried something like that

aws rds modify-db-parameter-group --db-parameter-group-name pgpro-12 --parameters "ParameterName=shared_preload_libraries,ParameterValue=[pg_stat_statemetns,auto-explain],ApplyMethod=pending-reboot"
`

And received :
`
Invalid type for parameter Parameters[0].ParameterValue, value: [u'pg_stat_statemetns', u'auto-explain'], type: <type 'list'>, valid types: <type 'basestring'>
`

**Comment by stobrien89** [comment]
Hi @mixmind,

Thanks for providing the example!  I'm seeing what you meant now.  In my console view, it only shows "Value" rather than "Values" like yours, but I can see that the data type is `list`.  I did some testing and although the data type for `shared_preload_libraries` is `list`, you need to provide your values in a string format like the example below:

```
'{"ParameterName": "shared_preload_libraries","ParameterValue": "pg_stat_statements,auto_explain", "ApplyMethod": "pending-reboot"}'
```

I checked to make sure RDS does type conversion/validation of input for `ParameterValue` for this and it appears they do.  When I passed `"ParameterValue": "pg_stat_statements,aaaa` for example, the API returned this error message: 

```
An error occurred (InvalidParameterValue) when calling the ModifyDBParameterGroup operation: Invalid parameter value: aaaa for: shared_preload_libraries allowed values are: auto_explain,orafce,pgaudit,pglogical,pg_bigm,pg_cron,pg_hint_plan,pg_prewarm,pg_similarity,pg_stat_statements,pg_transport,plprofiler.  
```

I also tried passing a list like `"ParameterValue": ["pg_stat_statements","auto_explain"]`, but that returns an error as well.  In this case, multiple values must be provided in a string format.  Hope this helps!

**Comment by mixmind** [comment]
> Hi @mixmind,
> 
> Thanks for providing the example! I'm seeing what you meant now. In my console view, it only shows "Value" rather than "Values" like yours, but I can see that the data type is `list`. I did some testing and although the data type for `shared_preload_libraries` is `list`, you need to provide your values in a string format like the example below:
> 
> ```
> '{"ParameterName": "shared_preload_libraries","ParameterValue": "pg_stat_statements,auto_explain", "ApplyMethod": "pending-reboot"}'
> ```
> 
> I checked to make sure RDS does type conversion/validation of input for `ParameterValue` for this and it appears they do. When I passed `"ParameterValue": "pg_stat_statements,aaaa` for example, the API returned this error message:
> 
> ```
> An error occurred (InvalidParameterValue) when calling the ModifyDBParameterGroup operation: Invalid parameter value: aaaa for: shared_preload_libraries allowed values are: auto_explain,orafce,pgaudit,pglogical,pg_bigm,pg_cron,pg_hint_plan,pg_prewarm,pg_similarity,pg_stat_statements,pg_transport,plprofiler.  
> ```
> 
> I also tried passing a list like `"ParameterValue": ["pg_stat_statements","auto_explain"]`, but that returns an error as well. In this case, multiple values must be provided in a string format. Hope this helps!

Great, Thanks it works with json format. As I understand correct, it's not possible to change that parameter without json format? Plain cli command as I showed will not work, or there is some syntax for use it too?

**Comment by stobrien89** [comment]
Hi @mixmind,

Yes, that is correct— you must use a json string to change that particular parameter (or any parameter that will have more than one `ParameterValue`).  In most cases, shorthand syntax will work, but in the case of having more than one value for a particular key, there is no way for shorthand syntax to determine that the comma between values is not separation for another key/value pair.
