### ISSUE TITLE
enable-image-deprecation missing from Docker and CLI

### ISSUE THREAD

**Issue by agardnerIT** [aws/aws-cli#6221]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to deprecate an image that I own using [these instructions|https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-deprecate.html].

Is this command built into the binary yet? If not, when will it be available? Your articles and docs suggest this capability is available now...

```
aws ec2 enable-image-deprecation \
    --image-id ami-1234567890abcdef0 \
    --deprecate-at "2021-10-15T13:17:12.000Z"
```

I've tried the AWS CLI and docker image:

```
$ docker run --rm -it amazon/aws-cli --version
aws-cli/2.2.11 Python/3.8.8 Linux/5.4.72-microsoft-standard-WSL2 docker/x84_64.amzn.2 prompt/off

$ docker run --rm -it amazon/aws-cli ec2 enable-image-deprecation ....
```

Both windows and

**SDK version number**
```
aws-cli/2.2.11 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
```
**Platform/OS/Hardware/Device**
Windows & Docker

**Logs/output**
```
aws: error: argument operation: Invalid choice, valid choices are:
...
...

```

**Additional context**

**Comment by stobrien89** [comment]
Hi @agardnerIT, 

Thanks for reaching out!  Looks like this documentation was released by the EC2 team a bit too early. This operation was added to the botocore models on 5/11, which was a day after our most recent release.  This should be available sometime this week in the next release.  Hope this helps!
