### ISSUE TITLE
modify-transit-gateway --options AddTransitGatewayCidrBlocks - not working #6151

### ISSUE THREAD

**Issue by mtarnoci** [aws/aws-cli#6222]
This is reference to #6151
modify-transit-gateway --options AddTransitGatewayCidrBlocks - not working #6151

AWS support closed this issue by comment:

Thanks for writing in! I did some digging and it looks like AddTransitGatewayCidrBlocks was added as a parameter on 12/10/2020— the day after the version you're using was released. Bumping up to the latest version (or anything beyond 2.1.10) should resolve this..

This is nice, that AddTransitGatewayCidrBlocks was added to botocore, but still not awailable in AWS CLI version 2 for Windows.
When it will bw available in AWS CLI ?

**Comment by stobrien89** [comment]
Hi @mtarnoci,

Thanks again for reaching out!  As mentioned in the previous issue, `AddTransitGatewayCidrBlocks` should be available as an option for the operation in version 2.1.10 or higher.  Which AWS CLI version are you using?  I would just double-check using `aws --version`, as older versions (of v1 specifically), if not uninstalled before upgrading to version 2, can take precedence over the newer installation, as both v1 and v2 use the same `aws` command name.

I'm using version `2.2.5` and this is working fine for me:

```
aws ec2 modify-transit-gateway --transit-gateway-id <tgw-id> --options 'AddTransitGatewayCidrBlocks=10.0.0.0/16'

**Comment by mtarnoci** [comment]
Hi,

 

Thank you. I can confirm, that after upgrade AWS CLI to most recent version, command is available.

 

Thanks!

 

BR

Marek.

**Comment by stobrien89** [comment]
Hi Marek, 

Of course!  Feel free to reach out at any time if you have any additional questions.
