### ISSUE TITLE
Aliases: 'f' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by FreskimAliu** [aws/aws-cli#6223]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Windows 10
**Describe the question**
When I try to run command that have alias functions, I'm getting this:
![alias](https://user-images.githubusercontent.com/61356832/121887903-a4566780-cd17-11eb-9504-ba3356279ba0.png)
'f' is not recognized as an internal or external command, operable program or batch file.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
![alias_debug](https://user-images.githubusercontent.com/61356832/121887890-a02a4a00-cd17-11eb-9811-4e6d6b465c68.png)

**Comment by kdaily** [comment]
Hi @FreskimAliu,

Sorry to hear you're having trouble. The AWS aliases that are using shell function definitions only work on a bash-like shell, not on a Windows command line. Aliases that are using sub-commands for AWS should function properly (like `running-instances`).

You can read more about the prerequisites and usage here, and specifically about bash-scripting aliases in the section titled "*Creating a bash scripting alias*":

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-alias.html

**Comment by FreskimAliu** [comment]
I installed WSL on my Windows machine and now it works fine.  Thanks for explanation @kdaily.
