### ISSUE TITLE
createdAt Payload is not returning correct type on eks describe-cluster - returning string instead of number

### ISSUE THREAD

**Issue by tmk1991** [aws/aws-cli#6224]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Documentation shows `aws eks describe-cluster` as having `createdAt` payload be The Unix epoch timestamp in seconds for when the cluster was created but returns date string

See docs: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/describe-cluster.html#examples

Says it expects a number for createdAt when actually it returns a string: `2021-06-14T14:28:14.425000-04:00`

**Platform/OS/Hardware/Device**
Centos 8

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
- Describe cluster with v2 CLI and get a date string
- Describe cluster with v1 get UNIX second number

**Expected behavior**
Expect v2 CLI to return createdAt as a UNIX second string

**Comment by stobrien89** [comment]
Hi @tmk1991,

Thanks for pointing this out!  Looking into this a bit further.

**Comment by tim-finnigan** [comment]
The DescribeCluster API does return a UNIX timestamp but the CLI converts it into a ISO 8601 format by default in v2 (see https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-timestamp). I think the v2 documentation example should be updated to reflect that.

**Comment by sumanthst25** [comment]
The same behavior is observed in describe-images ECR CLI command where the document mentions imagePushedAt to be in JavaScript date format but the results are presented in ISO format because of the default behavior of AWS CLI version2.

**Comment by tim-finnigan** [comment]
It looks like the example has since been fixed. As noted earlier here in the issue, the underlying [DescribeCluster API](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeCluster.html) is returning a timestamp, but in v2 the [default behavior](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-timestamp) is to return those in ISO 8601 format.
