### ISSUE TITLE
Cannot run this as a non-essential container on ECS within a task 

### ISSUE THREAD

**Issue by ndtreviv** [aws/aws-cli#6227]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I have a task definition with two containers that share the same data volume, which needs files to synced onto it from S3.
I thought I could add another container to the task definition - ie this one, use the container command override to sync the data down, then set my two main containers to be dependent on this one successfully completing.

I added this container to the task definition with the container *Command* set as something like:

```
s3 sync s3://my-bucket/my-prefix/ /mnt/ --exclude="*" --include="my-specific-file" --include="my-specific-directory/*" --quiet --region us-east-1"
```
But the container always fails with the logs showing usage command:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
...
```

**SDK version number**
`:latest`

**Platform/OS/Hardware/Device**
ECS

**To Reproduce (observed behavior)**
Create a task definition that runs on EC2.
Include a container in the task definition using the image: `amazon/aws-cli`
Set the command on the container to be an s3 command

**Expected behavior**
I expected the command to be passed through to the container and for it to run it successfully.

**Logs/output**
As described above

**Additional context**
-

**Comment by stobrien89** [comment]
Hi @ndtreviv,

Sorry to hear about the issues.  Would you be able to share your task definition? Please obscure any sensitive information, such as account numbers.  Thanks!
