### ISSUE TITLE
ECR: manifest with the same content but with  \r creates a new tag instead of adding tag as expected 

### ISSUE THREAD

**Issue by larroy** [aws/aws-cli#6234]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I was getting the manifest from python as in:

```
    manifest_cmd = f"aws ecr batch-get-image --repository-name {repository} --image-ids imageTag={xai_image_full_version} --query images[].imageManifest --output text".split()
    manifest = check_output(manifest_cmd).decode()
```

Then tagging an image with 

```
aws ecr put-image --repository-name {repository} --image-tag {new_tag} --image-manifest {manifest}
```

I noticed the behaviour was different than when running this from shell, and saw that the manifest as "\r" as an additional character. This creates a new tag in ECR instead of adding to the existing one that had the manifest.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

I would expect blank characters not affecting the hash and not creating a new tag

**Comment by stobrien89** [comment]
Hi @larroy,

Thanks for reaching out!  Would it be possible for you to provide debug logs by appending `--debug` to your command?  Please obscure any sensitive information, such as account numbers.  Thanks!
