### ISSUE TITLE
S3 sync issue with long file name in Windows 

### ISSUE THREAD

**Issue by contiero-roberto** [aws/aws-cli#624]
I have a folder that is synchronized by this CLI command:

aws.exe s3 sync "s3 bucket" "folder"

The Windows CLI version is 1.2.11. The "folder" is in a Windows7 NTFS file system. I think that there is a problem with long path name because I obtain this error when syncing (sorry, my windows is in italian):
[Error 3] Impossibile trovare il percorso specificato: u'C:\\Users\\Server\\Documents\\Server.........................
The path that is searched is 268 characters. If I rename the file and obtain a path name length less than 256 characters, s3 sync works properly. Can be the problem related to Maximum Path Length Limitation as explained here?

http://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx

**Comment by nwohaibi** [comment]
Sorry to bring an old issue up, 
What about using/trying `\\?\` in case of `File does not exist.`

**Comment by UweKeim** [comment]
I'm second this request. Long File Paths FTW!
