### ISSUE TITLE
Amplify Site Created with CLI Doesn’t Show PR Previews

### ISSUE THREAD

**Issue by lynnfaraday** [aws/aws-cli#6244]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

We have been trying to script the creation of Amplify sites using the AWS CLI commands. We patterned the script (see below) with the same options as our existing Amplify sites (which were created manually through the web console).

* Sites created with the AWS CLI commands show “Previews Enabled” in the GUI for all expected branches, but Pull Requests from GitHub do not trigger a preview.
* Sites created manually through the web console with the exact same settings work just fine, creating previews as expected.

**SDK version number**

**Platform/OS/Hardware/Device**

Windows 10 - aws-cli/2.1.25 Python/3.7.9

**To Reproduce (observed behavior)**

Here’s the script:

```
aws amplify create-app --name "docs" --repository "REDACTED_GITHUB_REPO_URL" --access-token "REDACTED_PAT_TOKEN" --enable-branch-auto-build --enable-branch-auto-deletion --enable-auto-branch-creation --auto-branch-creation-patterns "sprint-*" --auto-branch-creation-config "enableAutoBuild=true,enablePullRequestPreview=true,framework=Jekyll" -profile public-infrastructure
--above generated app with ID "APP_ID"
aws amplify create-branch --app-id APP_ID --branch-name "prod" --description "prod" --display-name "prod" --framework "Jekyll" --enable-auto-build --enable-pull-request-preview
aws amplify create-branch --app-id APP_ID --branch-name "master" --description "master" --display-name "master" --framework "Jekyll" --enable-auto-build --enable-pull-request-preview 
```

**Expected behavior**

We expect a Pull Request in GitHub to trigger an Amplify preview.

**Logs/output**

Nothing relevant in the command output.

**Additional context**

- We believe the GitHub webhook and app are being installed correctly. We see no discernible differences between the GitHub webook in the manually-created sites vs. the CLI-created sites, and direct commits to the connected branches do trigger an amplify build. The problem is just with the PR previews. 
- An amplify site created using Terraform demonstrates the same problem.

**Comment by kdaily** [comment]
Hi @lynnfaraday,

Sorry to hear you're having an issue with this! It sounds like something on the Amplify side since the command is completing successfully. It would help me discuss this with the Amplify team if I could see the request and response. You can enable debug logs by providing the `--debug` flag.

While I investigate further, Amplify has a separate CLI specifically for creating and managing apps, including documentation for running this in scripting/headless mode. I'm wondering if this might be useful for you as well:

- https://docs.amplify.aws/cli
- https://docs.amplify.aws/cli/usage/headless

**Comment by lynnfaraday** [comment]
Hi @kdaily - Thanks for the quick response.  I have a debug log, but since there are app IDs and repo names and such in there, is there a support email we can send it to rather than posting it here?

Also, with further debugging we believe that the issue is with one or more of the enable branch detection features: `--enable-auto-branch-creation --auto-branch-creation-patterns "sprint-*" --auto-branch-creation-config "enableAutoBuild=true,enablePullRequestPreview=true,framework=Jekyll"`

From my colleague, who was experimenting with the endpoint using terraform: 

1 create the app with terraform, branch autodetection disabled.  previews work, all is well
2 using terraform, update the app to include branch autodetection. branch autodetection works, previews no longer work

**Comment by kdaily** [comment]
@lynnfaraday,

I think I have reproduced the behavior. I created a boilerplate app and put it in a GitHub repository. I used the commands you described, and then tried to open PRs against tracked branches. It does not trigger previews either. I think I have enough evidence, so your debug logs may not be required. If they are, I'll look further into how you can supply them.

**Comment by kdaily** [comment]
I have reproduced your finding that branch autodetection is somehow involved as well. On a PR that I had already opened, a preview was triggered after I turned off branch autodetection through the Amplify web console.

**Comment by lynnfaraday** [comment]
Thanks for following up. I'm glad you were able to reproduce it.

**Comment by kdaily** [comment]
P49321426

**Comment by kdaily** [comment]
I've contacted the Amplify team, will update when I learn more. Thanks!

**Comment by tim-finnigan** [comment]
We recently heard back that this issue has now been resolved. Please try updating to the latest version of the AWS CLI and if you're still running into issues let us know here or reach out to [AWS Support](https://aws.amazon.com/contact-us/).
