### ISSUE TITLE
s3api put-object fails consistently in linux cli

### ISSUE THREAD

**Issue by viocost** [aws/aws-cli#6245]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Following command fails consistently:
aws s3api put-object --bucket test-bkabkbasa13 --body file:///home/user/Pictures/space-large.jpg --key space-large

Error parsing parameter '--body': Unable to load paramfile (/home/user/Pictures/space-large.jpg), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix.

With fileb prefix or without any prefix:
Error parsing parameter '--body': Blob values must be a path to a file.

Same behavior observed using dockerized aws cli.

**SDK version number**
aws --version output:
aws-cli/2.2.13 Python/3.8.8 Linux/5.11.0-18-generic exe/x86_64.ubuntu.21 prompt/of

**Platform/OS/Hardware/Device**
uname -a
Linux dell 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

OS: Linux Ubuntu 21.04 

**To Reproduce (observed behavior)**
1. Install current aws-cli version 2.2.13
2. Create default s3 bucket.
3. Try uploading a local image file using aws s3api put-object command
4. Observe the bug

**Expected behavior**
Expecting file to be uploaded to s3 bucket without an error.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by stobrien89** [comment]
Hi @viocost, 

Thanks for reaching out!  This should work if you just pass the relative file path (without the preceding forward slash) rather than with the `file://` prefix;  In the CLI V2, by default, files referenced with the `file://` prefix [are treated as base64-encoded text](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-types.html#parameter-type-blob).  Hope this helps!
