### ISSUE TITLE
Provide JumpCoud Agent AMI

### ISSUE THREAD

**Issue by jrolandjc** [aws/aws-cli#6246]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
I would like Amazon to offer Linux 2 and Ubuntu 20.04 AMI with the JumpCloud agent so that I can manage my systems as they're imaged

**Describe alternatives you've considered**
I can install the JumpCloud agent after the system is imaged but it would be much easier and more streamlined if I can use an image with the JumpCloud agent already included

**Additional context**

**Comment by stobrien89** [comment]
Hi @jrolandjc,

Thanks for reaching out!  I think this may be too specific a request for the EC2 team in terms of making a widely-available AMI, but you can create your own AMI for this that has JumpCloud or any other dependencies pre-installed by making an AMI from an existing instance.  Instructions can be found [here](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html).  Hope this helps!
