### ISSUE TITLE
Is there AWS CLI support for creating AWS SSO Users and Groups

### ISSUE THREAD

**Issue by ankitsrao** [aws/aws-cli#6250]
Hi Team,

This is a general question around AWS CLI support.
I'm working on automating creating AWS SSO groups, and currently could not find any CLI support around the same.

Request you to provide help around the same.

Thanks,

**Comment by stobrien89** [comment]
Hi @ankitsrao,

Thanks for reaching out!  For the most part, the AWS CLI and AWS SDK functionality mirrors that of the service APIs— the SSO API does not currently expose a way to create users and groups.  For now, users and groups must be created via the AWS SSO console.

Hope this helps!
