### ISSUE TITLE
How to give revision file location during create deployment on code deploy

### ISSUE THREAD

**Issue by manavalan619** [aws/aws-cli#6267]
**Describe the question**

Hi all, For now, I did with the creation of code deployment by using the below CLI command

   aws deploy create-deployment  --application-name AppECS-sample-cluster-x2 --deployment-config-name  CodeDeployDefault.ECSAllAtOnce --deployment-group-name 	DgpECS-sample-x2	   --s3-location bucket=<Bucket_Name>,bundleType=yaml,key=appspec.yaml 

The above command works fine. Here I need to avoid the S3 bucket, so I try to use revision as a string but no luck.

aws deploy create-deployment  --application-name AppECS-sample-cluster-x2 --deployment-config-name  CodeDeployDefault.ECSAllAtOnce --deployment-group-name 	DgpECS-sample-x2 --revision '{"revisionType": "String", "string": {"content":"version: 0.0 Resources: - TargetService: Type: AWS::ECS::Service Service Properties: TaskDefinition: arn:aws:ecs:us-east-:task-definition/sample LoadBalancerInfo: ContainerName: sampleconatiner ContainerPort: 8080"}}'

Here the error for AWS CodeDeploy

`The deployment failed because the AppSpec file that specifies the deployment configuration is missing or has an invalid configuration. The input AppSpec file is a not well-formed yaml. The template cannot be parsed. `

Any way to do this except S3 bucket storing.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by stobrien89** [comment]
Hi @manavalan619,

Thanks for reaching out!  Would you be able to provide debug logs by appending `--debug` to your command?  Please redact any sensitive information, such as account numbers.  Thanks!
