### ISSUE TITLE
How to automate "Stop and roll back deployment"

### ISSUE THREAD

**Issue by manavalan619** [aws/aws-cli#6272]
Hi all, currently my node application is deployed on AWS ECS farget and configured the blue-green deployment (CodeDeploy).

Here I give 443 port for production on BG deployment and added application load balancer DNS to my domain name (Say https://sample.com).

Based on the target group's health and ECS healthy status, blue-green deployment calls the "stop and roll back deployment"  if any unhealthy occurs.  There is a manual option to do this on CodeDeploy page.

Here my question:

I added the `process.exit(1)` on my node application healthcheck function under the route /health, which means I make a  runtime error on the healthcheck function. That lead to `503 Service Temporarily Unavailable` and my container exits. At that time how to call the "stop and roll back deployment"  automatically. Any approach to do this. Any one could help this.

**Comment by kdaily** [comment]
Hi @manavalan619,

It looks like you're using a Node application - this repository is for the AWS CLI only. It doesn't seem like you're having an issue with the CLI, so this type of question can be asked at the [ASW Developer Forum for ECS](https://forums.aws.amazon.com/forum.jspa?forumID=187).

If you are having a specific issue with the AWS CLI or have a question about a specific command, feel free to open up another issue. Thanks!
