### ISSUE TITLE
What are the default values for `--cli-connect-timeout` and `--cli-read-timeout`?

### ISSUE THREAD

**Issue by My6UoT9** [aws/aws-cli#6277]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
EC2 Amazon2 Linux 

**Describe the question**
What are the default values for `--cli-connect-timeout` and `--cli-read-timeout`?

Please add to the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html) the information about default values. Its not only those 2 which are missing, but this 2 are very important at least.

Many of the defaults can be inferred from the documentation - although I could not find information about timeouts, it would be very nice to have them in the reference.

**Logs/output**

**Comment by My6UoT9** [comment]
The defaults come from botocore https://github.com/boto/botocore/commit/cc51d6b6e9df64983f0493315771f3678ab8de6c

**Comment by kdaily** [comment]
Hi @My6UoT9, We'll check on this. I can see that it's documented in `botocore` here (they both default to 60 seconds):

https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

**Comment by My6UoT9** [comment]
Thanks you, excellent!
