### ISSUE TITLE
Unable to Verify SSL Certificate, AWS EC2 - [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by phpism-soumya** [aws/aws-cli#6278]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?

**Describe the question**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @phpism-soumya,

I don't have enough information from you to troubleshoot this. Feel free to open up another issue and supply the details requested in the issue template for us to help. Thanks!
