### ISSUE TITLE
[SSL: CERTIFICTAE_VERIFY_FAILED] (_ssl.c:727)

### ISSUE THREAD

**Issue by phpism-soumya** [aws/aws-cli#6280]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ x] Service API : I want to do X using Y service, what should I do?
- [x ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
AWS EC2 Linux

**Describe the question**
I have uploaded SSL cert (certificate.crt, chain.crt, private.key all are pem encoded) at ec2 instance, /etc/httpd/conf.d/ssl.conf. Site is working fine. I need to configure AWS codedeploy with GIT, it was working perfectly till I have installed SSL. Since, the installation completed, every time I'm trying deploy it says deployment failed due to Invalid certificated. Now, tried different things to make sure certificate is right, but no luck. Not sure why Im unable to verify certificate.

**Logs/output**
$ aws iam list-server-certificates 
ERROR - SSL validation failed for https://iam.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

$ aws iam upload-server-certificate --server-certificate-name even2021v2 --certificate-body file://Certificate.pem --certificate-chain file://CertificateChain.pem --private-key file://PrivateKey.pem
ERROR - SSL validation failed for https://iam.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by stobrien89** [comment]
Hi @phpism-soumya,

Sorry to hear you've been having issues.  Would you be able to provide debug logs by appening `--debug` to your commands?  Please redact any sensitive information, such as account numbers.  Thanks!

**Comment by phpism-soumya** [comment]
My main objective is to install codedeploy which was working fine till I have installed SSL cert. It seemed like something I'm missing.
Now this is happening:

[root@ip-XX-XX-XX-XX ec2-user]#  sudo ./install auto releases/codedeploy-agent-132.rpm

I, [2021-07-15T16:23:05.858101 #1177]  INFO -- : Starting Ruby version check.
I, [2021-07-15T16:23:05.858217 #1177]  INFO -- : Starting update check.
I, [2021-07-15T16:23:05.858256 #1177]  INFO -- : Attempting to automatically detect supported package manager type for system...
I, [2021-07-15T16:23:05.867473 #1177]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2021-07-15T16:23:05.867587 #1177]  INFO -- : Checking EC2 metadata service for region information...
I, [2021-07-15T16:23:05.914214 #1177]  INFO -- : Downloading version file from bucket aws-codedeploy-us-west-2 and key latest/VERSION...
E, [2021-07-15T16:23:05.927642 #1177] ERROR -- : Unhandled exception: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>
E, [2021-07-15T16:23:05.927717 #1177] ERROR -- :   at /usr/share/ruby/2.0/net/http.rb:921:in `connect'
E, [2021-07-15T16:23:05.927763 #1177] ERROR -- :   at /usr/share/ruby/2.0/net/http.rb:921:in `block in connect'
E, [2021-07-15T16:23:05.927782 #1177] ERROR -- :   at /usr/share/ruby/2.0/timeout.rb:52:in `timeout'
E, [2021-07-15T16:23:05.927797 #1177] ERROR -- :   at /usr/share/ruby/2.0/net/http.rb:921:in `connect'
E, [2021-07-15T16:23:05.927812 #1177] ERROR -- :   at /usr/share/ruby/2.0/net/http.rb:862:in `do_start'
E, [2021-07-15T16:23:05.927828 #1177] ERROR -- :   at /usr/share/ruby/2.0/net/http.rb:851:in `start'
E, [2021-07-15T16:23:05.927841 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:313:in `open_http'
E, [2021-07-15T16:23:05.927856 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:709:in `buffer_open'
E, [2021-07-15T16:23:05.927871 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:210:in `block in open_loop'
E, [2021-07-15T16:23:05.927886 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:208:in `catch'
E, [2021-07-15T16:23:05.927900 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:208:in `open_loop'
E, [2021-07-15T16:23:05.927914 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:149:in `open_uri'
E, [2021-07-15T16:23:05.927934 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:689:in `open'
E, [2021-07-15T16:23:05.927948 #1177] ERROR -- :   at /usr/share/ruby/2.0/open-uri.rb:697:in `read'
E, [2021-07-15T16:23:05.927986 #1177] ERROR -- :   at ./install:273:in `get_version_file_from_s3'
E, [2021-07-15T16:23:05.928002 #1177] ERROR -- :   at ./install:363:in `<main>'

**Comment by phpism-soumya** [comment]
This is what I found with --debug, while uploading certificate to IAM,
aws iam upload-server-certificate --server-certificate-name xxxxx --certificate-body file://Certificate.pem --certificate-chain file://CertificateChain.pem --private-key file://PrivateKey.pem


Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/usr/lib/python2.7/dist-packages/botocore/httpsession.py", line 281, in send
    raise SSLError(endpoint_url=request.url, error=e)
SSLError: SSL validation failed for https://iam.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by phpism-soumya** [comment]
@stobrien89 
[root@ip-172-31-24-114 ec2-user]# aws --version
aws-cli/1.18.107 Python/2.7.18 Linux/4.14.232-123.381.amzn1.x86_64 botocore/1.17.31

**Comment by phpism-soumya** [comment]
I have configured AWS vars.
$ export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
$ export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
$ export AWS_DEFAULT_REGION=us-west-2

Uploaded certificate to iam, and added to load balancer.

Still no luck. aws iam list-server-certificates

$ aws iam list-server-certificates
**Error**
[2021-07-16T07:44:59.910132 #8568] ERROR -- : Unhandled exception: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>

**Comment by stobrien89** [comment]
Hi @phpism-soumya,

Sorry for the delay!  Thanks for providing the additional information. It looks like you'll need to either need to set the `AWS_CA_BUNDLE` to the path of your certificate bundle in order to user it with the CLI.  Alternatively, you can specify this path with the `--ca-bundle` option.  Let me know if this works for you.

**Comment by phpism-soumya** [comment]
Hey @stobrien89,

Thank you for your reply, it's seemed like my cacert.pem and SSL_CERT_FILE was not configured.
These to links helped me to fixed it up.

https://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-read-server-certificate-b-certificat
https://github.com/aws/aws-cli/issues/2690

Also configured, 
export SSL_CERT_FILE=/etc/pki/tls/certs/cacert.pem

Now codedeploy Installed and working perfectly.

Thanks a lot for your help Sir.
Just saved my life :D
 
 Closing the issue.
