### ISSUE TITLE
CI/CD pipeline is unable to read an aws env variable due to concurrent.futures module not available for python 2.7

### ISSUE THREAD

**Issue by paridev** [aws/aws-cli#6293]
My CI/CD pipeline is not able to read the aws access key env variable recently because of concurrent.futures module not being available for python 2.7.

Last time it worked with no error with `awscli-1.19.102`. Now the version is changed to `awscli-1.20.5` and it is not working.

Here is a screenshot of my build failure:
<img width="1323" alt="Screenshot 2021-07-23 at 14 45 33" src="https://user-images.githubusercontent.com/60629905/126784939-7f3189d6-80f7-4f3b-bac9-4505fd974dba.png">

**Comment by lorengordon** [comment]
aws-cli v1.20.0 and later have deprecated support for Python 2.7. You'll need to install using python3, or pin to the older version.

* https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/

**Comment by nateprewitt** [comment]
Hi @paridev, @lorengordon is correct. The blog should provide options for either upgrading or handling installation in your CI environment. At the very least, we'd recommend pinning to `awscli<1.20` in Python 2.7. Please, let us know if you have any other questions.

**Comment by paridev** [comment]
Thanks @lorengordon and @nateprewitt
