### ISSUE TITLE
autocomplete does not work on help

### ISSUE THREAD

**Issue by kidbrax** [aws/aws-cli#6295]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When typing `aws help <tab>`, it does not autocomplete like it does other commands.

**SDK version number**

```
$ aws --version
aws-cli/2.1.25 Python/3.7.4 Darwin/20.4.0 exe/x86_64 prompt/off
```

**Platform/OS/Hardware/Device**
MacOS and ZSH

**To Reproduce (observed behavior)**
type `aws help`, then press <tab>

**Expected behavior**
expect a list of options to appear below prompt like other commands do

**Comment by stobrien89** [comment]
Hi @kidbrax,

Thanks for reaching out! 

`aws help <service>` will also work, but the [documented usage](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html) is `aws <service> help` or `aws <service> <command> help`, with `aws help topics` being an exception.  The autocompleter doesn't extend to `help` in that sense.
