### ISSUE TITLE
describe commands not showing correct information

### ISSUE THREAD

**Issue by adrian-petcu-rm** [aws/aws-cli#6300]
When I run:
`aws rds describe-db-instances`
or
`aws docdb describe-db-clusters`
I get back a list of all of my RDS and DocumentDB instances & clusters instead of them being separated.

I get the same behavior using the describe_db_clusters() functions in boto3 for RDS and DocDB clients.

```
aws --version
aws-cli/2.2.6 Python/3.8.8 Linux/5.11.0-25-generic exe/x86_64.ubuntu.21 prompt/off
```

I found issue #4688 from 2019 with the same problem but no solution provided.

**Comment by stobrien89** [comment]
Hi @adrian-petcu-rm,

Thanks for reaching out!  I can see how this is confusing.  DocumentDB leverages the RDS API to describe instances and clusters, as DocumentDB is essentially just another engine under the RDS control plane.  The same applies to Neptune.

This was added to the [docs](https://docs.aws.amazon.com/cli/latest/reference/docdb/describe-db-clusters.html) a while back in an attempt to clarify:

> For certain management features such as cluster and instance lifecycle management, Amazon DocumentDB leverages operational technology that is shared with Amazon RDS and Amazon Neptune. Use the filterName=engine,Values=docdb filter parameter to return only Amazon DocumentDB clusters.

Hope this helps!
