### ISSUE TITLE
Bucket field `CreationDate` should be optional

### ISSUE THREAD

**Issue by Nugine** [aws/aws-cli#6311]
https://github.com/aws/aws-cli/blob/d754599d03be84a74b1d511f18dfdd3775791561/awscli/customizations/s3/subcommands.py#L546

```
CreationDate

    Date the bucket was created. This date can change when making changes to your bucket, such as editing its bucket policy.

    Type: Timestamp

    Required: No
```

https://docs.aws.amazon.com/AmazonS3/latest/API/API_Bucket.html

https://github.com/datenlord/s3-server/issues/78

**Comment by stobrien89** [comment]
Hi @Nugine,

Thanks for reaching out.  We require `CreationDate` to verify we are receiving a valid [`ListBuckets` response](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html#API_ListBuckets_ResponseSyntax), as `s3 ls` can either perform a `ListBuckets` or `ListObjectsV2` call, depending on whether or not an s3 uri is present.  Could you describe your use case/issue in detail? I'm not familiar with S3-server.

**Comment by Nugine** [comment]
s3-server implements some common s3 api and provides a simple object storage based on the file system.
s3-server's response of `ListBuckets` didn't contain `CreationDate` because I think `CreationDate` is optional.

```
CreationDate

    Date the bucket was created. This date can change when making changes to your bucket, such as editing its bucket policy.

    Type: Timestamp

    Required: No
```

But awscli fails to recognize such response.

```
$ aws --debug --endpoint-url=http://localhost:8014 s3 ls
```

```
2021-08-02 21:18:00,747 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x7ff1fb74eaf0>
2021-08-02 21:18:00,747 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7ff1fa89f8b0>>
2021-08-02 21:18:00,747 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/customizations/commands.py", line 197, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/s3/subcommands.py", line 505, in _run_main
  File "awscli/customizations/s3/subcommands.py", line 573, in _list_all_buckets
KeyError: 'CreationDate'

'CreationDate'
```

Can you explain why `CreationDate` is required? Thanks.

**Comment by stobrien89** [comment]
Hi @Nugine,

Thanks for your patience.  I reviewed this with the team and the consensus is that the s3 documentation is incorrect.  There's not a case I can think of where a Bucket resource does not have either a `CreationDate` or `Name`, which is also listed as not required.  I'll be sending the S3 team an internal ticket to investigate this.  In terms of the s3-server implementation,  it would be possible to work around this by setting the `CreationDate` to an empty string, but I'm sure there are a few other ways this could be handled.

**Comment by Nugine** [comment]
s3-server maps object storage operations to file system operations and keeps some metadata. 
I use `btime` for `CreationDate`, which is a naive solution.
Let's wait for the documentation fix.

**Comment by stobrien89** [comment]
@Nugine,

Thanks for the clarification!  I'd say using `btime` is less naive a solution than using an empty string 😄.  I've sent the ticket I mentioned to the s3 team and will provide an update once I've heard back from them.

**Comment by stobrien89** [comment]
P51016212

**Comment by stobrien89** [comment]
Hi @Nugine,

Thanks for your patience.  I heard back from the EC2 team and while they agree that a bucket will not be returned without a `CreationDate` or `Name`, their stance is that they technically don't list output as required, as that's something that the end user can't control— they reserve that for input only.  That said, the team won't make any changes to requiring the `CreationDate` for ls (bucket) output.
