### ISSUE TITLE
aws sync folders based on subfolders

### ISSUE THREAD

**Issue by DiyaVaka** [aws/aws-cli#6312]
Hi,

I am trying to upload folders to s3 but it should be picking these folders based on sub folders. For example it needs to pick a folders (only current month 2106*) only if the subfolder has certain pattern in it . For example (*ABC*). I tried 

aws s3 sync /source/path/ s3://destinaton-bucket/ --exclude "\*" --include "2106\*/\*ABC\*" --dryrun

The problem is its picking all directories with "ABC" pattern.

How can i include both upper and sub directory in my search

Thanks,

**Comment by stobrien89** [comment]
Hi @DiyaVaka,

Thanks for reaching out!  I may not be understanding correctly, but your `--include` and `--exclude` filters seemed to work for me based on this folder structure: 

```
ls s3sync
21061	21062	21063	21064	21065	21066	4234	4235	4236	ABC
```

I placed a subdirectory named `txtABC` in each directory, except for `21066` , which contains a `txt` directory and `ABC`, which contains nothing.  Each subdirectory contains a file named `sample.txt`

This is the output from the command you provided:

```
(dryrun) upload: 21061/txtABC/sample.txt to s3://myBucket/21061/txtABC/sample.txt
(dryrun) upload: 21062/txtABC/sample.txt to s3://myBucket/21062/txtABC/sample.txt
(dryrun) upload: 21063/txtABC/sample.txt to s3://myBucket/21063/txtABC/sample.txt
(dryrun) upload: 21064/txtABC/sample.txt to s3://myBucket/21064/txtABC/sample.txt
(dryrun) upload: 21065/txtABC/sample.txt to s3://myBucket/21065/txtABC/sample.txt
```

I think I may be missing something here, but let me know when you have a chance.  Sharing a sample folder/file structure along with the output of your command would also be helpful.

**Comment by DiyaVaka** [comment]
Hi,

Thanks for responding. 

My directory structure is  as below

210531_LWQ_111_876/*EX*/
210528_WED_234_765/more_data
210601_XYZ_123_456/*EX*/
210603_EFG_234_578/high/
210604_RST_456_884/*EX*/

Running the above command is pulling data from May month also as it satisfies "EX" . Where as i want only june month data which has subdirectory "*EX*"

Thanks,

**Comment by stobrien89** [comment]
Hi @DiyaVaka,

My apologies for the delayed response.  Thanks for the clarification!  I added another directory `21051` to replicate what you're seeing and I'm still unable to reproduce:

```
21051	21061	21062	21063	21064	21065	21066	4234	4235	4236	ABC
```

```
ls 21051/txtABC
sample.txt
```

```
aws s3 sync . s3://myBucket --exclude "*" --include "2106*/*ABC*" --dryrun
(dryrun) upload: 21061/txtABC/sample.txt to s3://myBucket/21061/txtABC/sample.txt
(dryrun) upload: 21062/txtABC/sample.txt to s3://myBucket/21062/txtABC/sample.txt
(dryrun) upload: 21063/txtABC/sample.txt to s3://myBucket/21063/txtABC/sample.txt
(dryrun) upload: 21064/txtABC/sample.txt to s3://myBucket/21064/txtABC/sample.txt
(dryrun) upload: 21065/txtABC/sample.txt to s3://myBucket/21065/txtABC/sample.txt
```
could you provide the output of `aws --version`?  Thanks!
