### ISSUE TITLE
Add create channel functionality LexV2 model CLI 

### ISSUE THREAD

**Issue by kasun-linz** [aws/aws-cli#6319]
**Is your feature request related to a problem? Please describe.**
- When it comes to Lex V2 APIs, only way you can create new channel is via using the console. 
- However, console assumes all of the KMS keys are created in same account as customer manage keys
- Our organization does not grant access to create KMS keys in application accounts and they are managed in a central account. 
- Therefore, we are unable to use the Console UI to create a channel

**Describe the solution you'd like**
It would be great, if there is a CLI or API option available to create a channel by passing the arn of the KMS key.

**Describe alternatives you've considered**
Otherwise, please provide and option in Console to enter the arn of the KMS key.

**Additional context**

**Comment by stobrien89** [comment]
Hi @kasun-linz,

Thank you for the feature request!  I've created an internal ticket for this and have forwarded it to the Lex team.  I'll let you know as soon as I have an update!

**Comment by stobrien89** [comment]
P50781497
