### ISSUE TITLE
Uninterrupted `start-instance-refresh` Autoscaling Option

### ISSUE THREAD

**Issue by Sean12697** [aws/aws-cli#6327]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on? Ubuntu 20.04 (GitHub Action)

**Describe the question**

I would like to know if there is an ability for the [`start-instance-refresh`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/autoscaling/start-instance-refresh.html) command to initially launch an instance within an Autoscaling Group, then only terminate an existing instance after a certain period (in seconds)? If configured correctly this should allow a seamless transition between instances.

In trials and due to my custom "User Data" Script, after executing `start-instance-refresh` on an Autoscaling Group (attached to an ALB) it takes approximately 30 seconds for the DNS to return a 503 Response (Service Unavailable), then another approximately 30 seconds to respond with a 502 Response (Bad Gateway), only 3 minutes after that does the DNS direct to an available instance (200 Response).

These trials have included experimenting with the instance warmup time of the `start-instance-refresh` command and the life-cycle hooks of the Autoscaling Group.

**Comment by kdaily** [comment]
Hi @Sean12697,

Thanks for your comment. This kind of request is outside our expertise, as it doesn't pertain to the AWS CLI. The AWS CLI is only calling the AutoScaling Group `[StartInstanceRefresh](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_StartInstanceRefresh.html)` API, and we don't make any modification to that behavior.

I see you've found details on instance warmups, but possibly you're looking to use the "Checkpoints" feature mentioned here:

https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html#instance-refresh-core-concepts

For further assistance on this issue, please head over to the AWS Developer Forum for AutoScaling, where a representative of that service can comment:

- https://forums.aws.amazon.com/forum.jspa?forumID=291
