### ISSUE TITLE
Uploading files to S3 from EC2 instances fails on some instance types

### ISSUE THREAD

**Issue by benbc** [aws/aws-cli#634]
We have a very strange problem. We are uploading large (10M) files from an EC2 instance to an S3 bucket in the same region. We use `aws s3 cp` for the upload and instance roles for authentication.

If we use an `m1.small` EC2 instance the upload works fine. But if we increase the instance size (we have tried `m1.large` and `m3.large`) the upload fails.

Here is the error we get:

```
upload failed: <file> to <s3-address>
HTTPSConnectionPool(host='<bucket>.s3.amazonaws.com', port=443): Max retries exceeded with url: <s2-key>?partNumber=2&uploadId=Hw6FZhXeH03ZzzCtxu2XcsspmpN2lx83GxWGzrJ96I81XlajjjNCxsSj0vs0BIbf_xJmzfdZwZY_UzUL3NCT57rpqEwIuLD1qryr7KKjlR6rA0YIW_ltopZQkoo32i0qTPUAlBc55WRAYxjwJ8Iw1A-- (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
```

This is completely reproducible -- we have never had such a upload succeed after tens of attempts. We have never seen the problem on an `m1.small` instance in hundreds of attempts.

We ran into this problem with 10M files. We have found that it is reproducible down to about 1M. Much less than this and it works fine every time.

Any ideas about what is going on would be much appreciated.

**Comment by iongion** [comment]
Got this today, using boto 2.8.0
```
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 1187, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 1121, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 827, in send_file
    query_args=query_args)
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 490, in make_request
    override_num_retries=override_num_retries)
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/connection.py", line 932, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/opt/converter/env/local/lib/python2.7/site-packages/boto/connection.py", line 894, in _mexe
    raise e
error: [Errno 104] Connection reset by peer
```

The file in question is above 5 gb, how can the file be uploaded if the boto s3 **PUT** is not reliable ?

**Comment by KeithTt** [comment]
got the same issue.

```
upload failed: images1/1103/142_b2d35e8005321b582ce891ca835df65d_75.jpg to s3://opgirl-v2/images/images1/1103/142_b2d35e8005321b582ce891ca835df65d_75.jpg A client error (RequestTimeout) occurred when calling the PutObject operation: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
Cleaning up. Please wait...
upload failed: images1/1103/142_d0754d4c8708dc2d7c68cc27da2ad2fa_100.jpg to s3://opgirl-v2/images/images1/1103/142_d0754d4c8708dc2d7c68cc27da2ad2fa_100.jpg The write operation timed out
upload failed: images1/1103/1430_0a6a493f08b693789cba32fbbc6ade83_75.jpg to s3://opgirl-v2/images/images1/1103/1430_0a6a493f08b693789cba32fbbc6ade83_75.jpg ('Connection aborted.', error(104, 'Connection reset by peer'))
```

```
# aws --version
aws-cli/1.9.15 Python/2.6.6 Linux/3.2.0-0.bpo.1-amd64 botocore/1.3.15
```

**Comment by jaakkovarjo** [comment]
I'm experiencing the same issue. This thread is rather old. Is this issue still being investigated?

`('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

`# aws --version
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1055-aws botocore/1.4.70`

**Comment by adilbaig** [comment]
Faced the same issue

````
aws --version
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1049-aws botocore/1.4.70
````

**Comment by bilyum** [comment]
Ditto. +1
Filesize: 1G
`aws-cli/1.15.12 Python/3.4.3 Linux/4.4.0-71-generic botocore/1.10.12`

**Comment by CSRaghunandan** [comment]
I'm having the same issue as well, when I  tried to upload a file to s3 bucket using boto3 python package. 

It used to work fine until about 4 days ago, and since then having problems with uploading.

**Comment by uldall** [comment]
I am having the same issue with a newly created bucket in the eu-west-1 region.

Command used:
`aws s3 sync . s3://<bucket_name> --profile test --region eu-west-1`

```
$ aws --version
aws-cli/1.11.13 Python/3.5.2 Linux/4.13.0-45-generic botocore/1.4.70
```

**Comment by CSRaghunandan** [comment]
Is this problem related to the network I'm connected to? The upload was failing when I had connected to a 4G dongle, whereas when I was connected to my wifi router, everything was fine.

But, the 4G dongle was giving me 10Mbps speed. So, not sure where the problem is

**Comment by chrisairpos** [comment]
@uldall If you haven't already solved this, for me this was fixed by installing the latest version of the aws-cli - the latest version on apt-get is outdated and so you must install using pip. Here's the instructrions:
https://www.slashroot.in/how-to-install-and-configure-aws-cli-on-ubuntu-16-04

**Comment by kenny1323** [comment]
On ubuntu 18
Install python 3
sudo apt-get install python3-pip
pip3 install awscli --upgrade --user
aws s3 sync ./ s3://mybucket01

https://linuxhint.com/install_aws_cli_ubuntu/
https://linuxhint.com/install_aws_cli_ubuntu/

**Comment by haooooooqi** [comment]
Hi,

Seems I am still seeing this issue when downloading 10M small files with multithread.
