### ISSUE TITLE
Windows ssm get-parameter error

### ISSUE THREAD

**Issue by felicienveldema** [aws/aws-cli#6341]
I'm trying to get an ECR image from AWS with the ssm get-parameter in cli.

When running the script I keep receiving the following error:
`An error occurred (ParameterNotFound) when calling the GetParameter operation: `

Adding debug flag to the script shows that the `ssm get-parameter` makes a directory out of the `name` parameter I add.
The script states this `--name "/CodeBuild/Image"` 
but sends to CLI  this  `C:/Program Files/Git/CodeBuild/Image`

On MacOS this problem does not occur and seems to be Windows specific.

Reproduction steps:
In PowerShell run a .sh script containing:
`aws ssm get-parameter \
--name "/parameter_group/parameter_name" \
--with-decryption \
--region "eu-west-1" \
--query Parameter.Value \
--output text`

**Comment by stobrien89** [comment]
Hi @felicienveldema,

Thanks for reaching out!  I think this is a case where Powershell's quoting rules are coming into play.  We detail some of this behavior [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html).  I tried creating a .ps1 script in the same format and was unable to reproduce.  Is the command in your script in the exact same format as what you provided in the reproduction steps?  Thanks!
