### ISSUE TITLE
CLI Team Update August 2021

### ISSUE THREAD

**Issue by kdaily** [aws/aws-cli#6355]
Hello everyone, this is the August 2021 AWS CLI update. I (@kdaily) will be making these updates moving forward on behalf of the AWS CLI team. 👋🏻 I’m a developer support engineer for the AWS CLI and Python (boto3/botocore) repositories. I focus on issue triage, guidance requests, and developer feedback related to the AWS CLI and Python SDK.

First, we filled the position for a software development engineer. Please welcome @justindho to the team!  We also have a new engineer (@tim-finnigan) responsible for issue triage and guidance issues as well.

Our main announcement for this month is the proposal for an AWS CLI v2 source distribution. This installation method will provide users and package maintainers a straightforward way to build and install the AWS CLI v2. Please see this GitHub pull request (https://github.com/aws/aws-cli/pull/6352) for the proposal. You can provide any constructive comments or feedback there as well.

Since our last update, we also [dropped Python 2.7 support](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/) for the AWS CLI v1 (version 1.20). Based off of issue reports, this seems to have gone smoothly! If you need to continue to use Python 2, you’ll get `aws-cli<=1.19.112` when installing. We also updated our [installation guide](https://github.com/aws/aws-cli/#installation) for prerequisites of `pip` (9.0.2 or greater) and `setuptools` (36.2.0 or greater) to ensure compatibility with the packaging features used by the AWS CLI.

The following enhancements and bug fixes were made:

- https://github.com/aws/aws-cli/pull/6241 (issue https://github.com/aws/aws-cli/issues/6225)
- https://github.com/aws/aws-cli/pull/6166 (issue https://github.com/aws/aws-cli/issues/6152)

We’re still reviewing implementations for the following issues:

- https://github.com/aws/aws-cli/pull/6079 (issue https://github.com/aws/aws-cli/issues/2458)
- https://github.com/aws/aws-cli/pull/6095 (issue https://github.com/aws/aws-cli/issues/2874)
- https://github.com/aws/aws-cli/pull/6107 (issue https://github.com/aws/aws-cli/issues/901)

Stay tuned for our next update! We’ll be monitoring the feedback on the source distribution proposal.

**Comment by dan-petty** [comment]
When awscli v2 in pip?
