### ISSUE TITLE
SignatureDoesNotMatch error report

### ISSUE THREAD

**Issue by michaelrodov** [aws/aws-cli#6366]
I tried to use your JS api () for accessing my S3 bucket and failed to do so until I regenerated the secret key not to contain "+"
following this thread https://github.com/aws/aws-cli/issues/602
That is going on since 2014!!!
please handle this ASAP

**Comment by stobrien89** [comment]
Hi @michaelrodov,

Sorry to hear you've been having issues.  This is a service-specific error for which we've been sending additional information to corresponding service teams to investigate.

Would you be able to provide debug logs for the failed operation?  This is what service teams typically need to investigate this.  Thanks!
