### ISSUE TITLE
I want a Cash Saving Account for gold Web Application which customer can Sign up and Deposit Cash via Promp-Pay, Paypal, Credit Card

### ISSUE THREAD

**Issue by Wangchingold** [aws/aws-cli#6371]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kellertk** [comment]
Hi, we closed this issue because it looks like it might be spam or invalid. If you have a specific feature request for the AWS CLI please reword this and open another issue.
