### ISSUE TITLE
aws cloudformation import-stacks-to-stack-set not available in aws-cli version 2 in cloudshell

### ISSUE THREAD

**Issue by fsckyes** [aws/aws-cli#6376]
**Is your feature request related to a problem? Please describe.**
Previously the aws cli version 1 had import-stacks available in cloudformation: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/import-stacks-to-stack-set.html https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-import.html#import-stacks-to-stackset-cli. This doesn't appear to be the case in aws cli version 2 from what I can tell however

**Describe the solution you'd like**
Make the import-stacks feature available in version 2 as well as this seems like a step backwards otherwise

**Describe alternatives you've considered**
I have not yet checked the python sdk if that method is available.

**Additional context**
aws-cli/2.2.15 Python/3.8.8 Linux/4.14.238-182.422.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

aws cloudformation import-stacks-to-stack-set help

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:

activate-type                            | batch-describe-type-configurations      
cancel-update-stack                      | continue-update-rollback                
create-change-set                        | create-stack                            
create-stack-instances                   | create-stack-set                        
deactivate-type                          | delete-change-set                       
delete-stack                             | delete-stack-instances                  
delete-stack-set                         | deregister-type                         
describe-account-limits                  | describe-change-set                     
describe-publisher                       | describe-stack-drift-detection-status   
describe-stack-events                    | describe-stack-instance                 
describe-stack-resource                  | describe-stack-resource-drifts          
describe-stack-resources                 | describe-stack-set                      
describe-stack-set-operation             | describe-stacks                         
describe-type                            | describe-type-registration              
detect-stack-drift                       | detect-stack-resource-drift             
detect-stack-set-drift                   | estimate-template-cost                  
execute-change-set                       | get-stack-policy                        
get-template                             | get-template-summary                    
list-change-sets                         | list-exports                            
list-imports                             | list-stack-instances                    
list-stack-resources                     | list-stack-set-operation-results        
list-stack-set-operations                | list-stack-sets                         
list-stacks                              | list-type-registrations                 
list-type-versions                       | list-types                              
publish-type                             | record-handler-progress                 
register-publisher                       | register-type                           
set-stack-policy                         | set-type-configuration                  
set-type-default-version                 | signal-resource                         
stop-stack-set-operation                 | test-type                               
update-stack                             | update-stack-instances                  
update-stack-set                         | update-termination-protection           
validate-template                        | package                                 
deploy                                   | wait                                    
help

**Comment by stobrien89** [comment]
Hi @fsckyes,

Thanks for reaching out!  This is a fairly new operation (made available in the botocore models on 7/28/21), so it looks like you just need to bump your version up to `2.2.23` or higher in order to have access to it in v2.  Just in case you needed the minimum version for v1 as well, that would be `1.20.8`.  Hope this helps!
