### ISSUE TITLE
help: where do I find the source code of sagemaker-runtime's invoke-endpoint?

### ISSUE THREAD

**Issue by naveen-marthala** [aws/aws-cli#6377]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on? Irrelevant for the issue.

**Describe the question**
PI am trying to send HTTP post requests to a SageMaker endpoint from Pythong using requests package. But, I have been getting signature mis-match error saying that the signature I sent do not match with the one AWS calculated, which everything works fine from Postman([more info and my code](https://stackoverflow.com/questions/69017786/aws-sagemaker-how-to-fix-the-request-signature-we-calculated-does-not-match-t)). So, since AWS CLI is written in python, I wanted to know how AWS CLI is doing it. So, I have looked many folders of the reposity, but couldn't find the code for [invoke-endpoint](https://docs.aws.amazon.com/cli/latest/reference/sagemaker-runtime/invoke-endpoint.html) command. Where do I find the source code for that command?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by tim-finnigan** [comment]
Hi @naveen-marthala, thanks for reaching out. Here is the documentation for the InvokeEndpoint service: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_runtime_InvokeEndpoint.html

It is a service shared across SDKs, and you can find the Python implementation here in this [botocore file](https://github.com/boto/botocore/blob/develop/botocore/data/sagemaker-runtime/2017-05-13/service-2.json).

Sorry to hear you are seeing an issue. Could you provide the debug logs to give us more insight into what’s going on?

Also you might this article on Troubleshooting AWS Signature Version 4 errors helpful: https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

**Comment by naveen-marthala** [comment]
Hello @tim-finnigan, Thanks for trying to help me and your time.

I am able to invoke the endpoint from Postman without any issues and it works just as expected.

the botocore file in the link you shared is a json file. It had all the keys and values necessary for invoking an endpoint. I wanted to know, how aws-cli is signing(or converting to sha256) my api key id and secret access key in order to invoke the endpoint, or the code that is being run to do the signing part. please tell me if i am missing to see something here and the file you had sent the link to had code to do so.

I am trying to send the http post request to invoke the sagemaker endpoint(without lambda and api gateway, but with an iam user's access key id and secret access key) and have been trying to sing api requests, but to no avail. and that is why I wanted to look at the python code being used by aws-cli to sing and send the http post requests to invoke a sagemaker endpoint. This very endpoint works just as expected from postman.

the error i get is:
```
Response code: 403

{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/endpoints/<my-end-point>/invocations\n\nhost:runtime.sagemaker.ap-south-1.amazonaws.com\nx-amz-content-sha256:\nx-amz-date:20210901T182952Z\n\nhost;x-amz-content-sha256;x-amz-date\n4ea75b8f9815505ffbf7ee43eb75b9496cc0641b2ae13efe4d19b1f89ba27751'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20210901T182952Z\n20210901/ap-south-1/sagemaker/aws4_request\n55ab4ae142990e512b0a1c10646b1e7a1be583396f838bbbc543380b155639be'\n"}
```
I have read many questions on stackoverflow where users had similar error. for some users, converting single-quotes to double quotes in PHP helped, but received same error. the error messages that AWS sends are very vague for users to debug.

**Comment by tim-finnigan** [comment]
Hi @naveen-marthala, thanks for that feedback. To my knowledge, the aws-cli signing code is not public facing. But I can point you to this documentation on the Signature Version 4 signing process: https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

Have you tried these troubleshooting tips for signature matching errors? https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-signature-does-not-match

Possible causes it mentions are:
a) Your clock is out of sync with the AWS servers.
b) Your operating system is mishandling AWS secret keys that contain certain special characters.

Please let us know if that helps!

**Comment by naveen-marthala** [comment]
Thanks @tim-finnigan. I didn't know that the code isn't public.

The code I have that fails to sign is actually from python-examples, whose link is available on that very page.

a) I don't think anything is wrong with my clock, because I have sent multiple successful requests with status 200 from Postman.
b) I will look into this character mishandling.
