### ISSUE TITLE
"Parameter validation failed: Unknown parameter in input: "projects", must be one of:"

### ISSUE THREAD

**Issue by F-Sampaio** [aws/aws-cli#6378]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Linux mint 19.3 Tricia
aws-cli/2.2.0 Python/3.8.8 Linux/5.4.0-80-generic exe/x86_64.linuxmint.19
**Describe the question**
I executed the following command to update some environment Variables: 
`aws codebuild update-project --name $PROJECT_NAME --cli-input-json file://codeBuild.json  --profile $PROFILE`
All what I did was change some environment variables with sed command.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
Parameter validation failed:
```
Unknown parameter in input: "projects", must be one of: name, description, source, secondarySources, sourceVersion, secondarySourceVersions, artifacts, secondaryArtifacts, cache, environment, serviceRole, timeoutInMinutes, queuedTimeoutInMinutes, encryptionKey, tags, vpcConfig, badgeEnabled, logsConfig, fileSystemLocations, buildBatchConfig, concurrentBuildLimit
Unknown parameter in input: "projectsNotFound", must be one of: name, description, source, secondarySources, sourceVersion, secondarySourceVersions, artifacts, secondaryArtifacts, cache, environment, serviceRole, timeoutInMinutes, queuedTimeoutInMinutes, encryptionKey, tags, vpcConfig, badgeEnabled, logsConfig, fileSystemLocations, buildBatchConfig, concurrentBuildLimit
```
I got my data on json when I runned this command:
`aws codebuild batch-get-projects --name $project_name > $codeBuild.json --profile $profile
`

**Comment by kdaily** [comment]
Hi @F-Sampaio,

Thanks for writing! You're trying to use an improper input. `batch-get-projects` returns a structure with a top level of `projects` that is a list of projects:

https://docs.aws.amazon.com/cli/latest/reference/codebuild/batch-get-projects.html#output

It is a single dictionary structure, not a list, so you would need to modify the output of `batch-get-projects` to only get one of the projects you wanted to update. You can read more about this here:

https://docs.aws.amazon.com/codebuild/latest/userguide/change-project-cli.html

> The project-info.json file contains an array of projects, so it cannot be used directly to update a project. You can, however, copy the properties that you want to modify from the project-info.json file and paste them into your update file as a baseline for the properties you want to modify. For more information, see View a build project's details (AWS CLI). 

In general, the `--cli-input-json` is used with a structure generated using the parameter `--generate-cli-skeleton`, like such:

```
aws codebuild update-project --generate-cli-skeleton
```

Let us know if you have any further questions!
