### ISSUE TITLE
S3 sync downloads files which should not be downloaded.

### ISSUE THREAD

**Issue by ocakhasan** [aws/aws-cli#6382]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Aws-cli s3 sync downloads files it should not download. Same source object (newer on local) is downloaded when aws sync command called from s3 to local. 

**SDK version number**
aws-cli/2.2.34 

**Platform/OS/Hardware/Device**
WSL2/ Ubuntu 

**To Reproduce (observed behavior)**
```
> mkdir test/ && touch test/main.txt && cd ..
```
```
> aws s3 sync test/ s3://bucket/prefix/
upload: test/main.txt to s3://bucket/prefix/main.txt
```
```
> touch -m -a test/main.txt // update the modified time
```
```
> aws s3 sync  s3://bucket/prefix/ test/
   download: s3://bucket/prefix/main.txt to test/main.txt
```
**Expected behavior**
Local file (newer) should not be downloaded. `test.txt` should not be downloaded  since it's modification time is newer. 

**Logs/output**

**Additional context**

**Comment by tim-finnigan** [comment]
Hi @ocakhasan, thanks for reaching out. 

This is the expected behavior. In the CLI [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html) for `aws s3 sync` in mentions:

> The default behavior is to ignore same-sized items unless the local version is newer than the S3 version.

If you want to ignore the last modified time you could use the `--size-only` parameter:

> `--size-only` (boolean) Makes the size of each key the only criteria used to decide whether to sync from source to destination.

Hope that helps, please let us know if you have any other questions!

**Comment by ocakhasan** [comment]
Hi @tim-finnigan thank you for the response. I see your point but here is a quote from aws-cli s3 documentation.

> A s3 object will require downloading if the size of the s3 object differs from the size of the local file, the last modified time of the s3 object is newer than the last modified time of the local file, or the s3 object does not exist in the local directory

So in my case, s3 object is not newer but the local object is newer. I think this is not the expected behaviour or am I missing something?

**Comment by tim-finnigan** [comment]
Hi @ocakhasan, I see what you’re saying. But if a user is modifying a local file, then in most cases they will change the size of that file. And as it says in the quote you referenced: 

> A s3 object will require downloading if the size of the s3 object differs from the size of the local file.

So I think it is an edge case to handle same size items with different timestamps. But as I said the `--size-only` parameter can handle that.

For more dynamic sync options you could also look into filtering:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html#use-of-exclude-and-include-filters

With filtering you can use `--include` and `--exclude` to ignore specified files as needed.
