### ISSUE TITLE
Allow timestamp format to be specified as a command line argument

### ISSUE THREAD

**Issue by alblue** [aws/aws-cli#6385]
When running the CLI the format for the date options can be configured with a configuration entry:

```
[default]
cli_timestamp_format = iso8601
```

However, this option does not appear as a command line parameter option. As a result, the output that is returned can be location/summer time sensitive.

Although it is possible to specify TZ=UTC to avoid problems with timezones causing issues, ideally the format should be available on the command line so that the result of a command can be consistent and not dependent upon what configuration entries have been set on the machine in which the command line works.

The configurations described in [config-vars.rst](https://github.com/aws/aws-cli/blob/develop/awscli/topics/config-vars.rst) indicate that there is no comparative command-line option to set this.

Something like parsing `aws --cli_timestamp_format=iso8601 ...` would be sufficient.

**Comment by tim-finnigan** [comment]
Hi @alblue, thanks for reaching out. 

May I ask which version of the AWS CLI you are using? Here is documentation on timestamps in v2 of the AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-timestamp. As noted there, AWS CLI v2 now returns all timestamp output values in ISO 8601 format. But you are able to specify timezone offsets.

I think there may be some overlap with your feature request and this one: https://github.com/aws/aws-cli/issues/5045. If there are any more details or use cases you can provide please let us know.

**Comment by alblue** [comment]
Ok; I'm using a recent v2 so this probably isn't relevant. However I was trying to find a way of getting back consistent timestamp formats and hoped this would do it.

There's a few problems with timestamp formatting in the cli:

1. The returned value is sensitive to the time zone by default. So if you are using a script to generate repeatable output (eg to generate the same hash) you need to run with TZ=UTC (though this adds +00:00 instead of Z).
2. The precision seems to vary; for some timestamp where you have ns resolution it will add .123456; if you don't have ns resolution instead of .000000 it simply drops the suffix
3. Ideally it would be possible to post process the timestamp to truncate it so that ns aren't displayed, or even to convert it to a date. Something like to_date(ExampleTimestamp) but I couldn't find out how to do that.
4. One way to increase the flexibility would be to allow the cli to have a --date-format argument/config value which would allow you to set your own printf style arguments.

**Comment by tim-finnigan** [comment]
Hi @alblue, thanks for providing this feedback. I discussed with the team and they said it sounds like a valid ask. Are there any examples of commands you are referring to? It would help us to have some data points on how one would use a --date-format argument/config value.

**Comment by alblue** [comment]
So here's an example of an API query (aws organization list-accounts with a timestamp result) that behaves inconsistently; presumably there's some truncation going on because the ns/ms component is zero:

```
2021-03-18T10:43:50.351000+00:00 
2020-06-12T08:06:51+00:00        
2020-06-22T07:41:46.536000+00:00 
2021-07-01T13:51:09.455000+00:00 
2021-01-20T15:12:47.022000+00:00 
```

It also makes a difference on which machine this is run on, because the environmental TZ could specify a different offset. If I run the same thing with (say) TZ=America/New_York, I see:

```
2021-03-18T06:43:50.351000-04:00
2020-06-12T04:06:51-04:00       
2020-06-22T03:41:46.536000-04:00
2021-07-01T09:51:09.455000-04:00
```

Logically they're the same time, but practically if these are sent via a message or used in a resulting process it's not repeatable. It's worse when you have a summer time change because what worked this week will fail next week and you'll have different results.

So ideally I'd like:

1. Consistency (no changes based on environment variables
2. A way of ensuring all lengths are the same (no auto-truncation, or alternatively no ms/ns precision
3. A way of 'switching off' the timezone support with a flag that I can then document

Right now, I'm documenting:

```
TZ=UTC aws organizations ...
```

just so that we get repeatability on anyone's machine, regardless of where they are.

Ideally I'd like to either be able to say:

1. Give me the times in a format with just yyyy-mm-dd T hh:mm:ss
2. Give me a standard time in Zulu time or with +00:00 for consistency (i.e. 2021-09-09T22:29:00Z or 2021-09-09T22:29:00+00:00)

A flag like `--zulu` would suffice, but a more portable approach might be to have `--date-format yyyy-mm-ddTHH:MM:ss` and `--tz=UTC` to avoid picking up environment variables that will affect the reproducibility of the command's results.

**Comment by tim-finnigan** [comment]
Hi @alblue, thanks for providing these examples. The team will review and we can keep this issue open to track updates.

**Comment by alblue** [comment]
By the way, I re-ran my query with `TZ=Etc/Zulu` hoping that would put the Z on the end, but instead it reproduced the above with the `+00:00` suffix. The one entry with no ns still was truncated.
