### ISSUE TITLE
ModuleNotFoundError: No module named 'botocore' | Windows | AWS CLI

### ISSUE THREAD

**Issue by akshaykhc** [aws/aws-cli#6394]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on? Windows

**Describe the question**

When attempting to execute the "aws --version" command, I am getting the following error: ModuleNotFoundError: No module named 'botocore'
 
C:\Users\Administrator>aws --version
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\aws.cmd", line 50, in <module>
    import awscli.clidriver
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\awscli-1.16.14-py3.9.egg\awscli\
clidriver.py", line 17, in <module>
    import botocore.session
ModuleNotFoundError: No module named 'botocore'

Please help!

**Comment by tim-finnigan** [comment]
Hi @akshaykhc, thanks for reaching out. Have you tried following these AWS CLI installation instructions for Windows? https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html

Please try following the steps there and let us know if you run into any issues.

**Comment by akshaykhc** [comment]
Hello Tim, thank you for looking into this issue. I tried following the above-provided documentation. However, now I am getting the following error:

aws --version resulted in
C:\MGTI\AWS-Snowcone\aws-cli-1.16.14>aws --version Traceback (most recent call last):
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\aws.cmd", line 50, in <module>
   import awscli.clidriver
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\awscli-1.16.14-py3.9.egg\awscli\clidriver.py", line 36, in <module>
   from awscli.help import ProviderHelpCommand
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\awscli-1.16.14-py3.9.egg\awscli\help.py", line 23, in <module>
   from botocore.docs.bcdoc import docevents
ImportError: cannot import name 'docevents' from 'botocore.docs.bcdoc' (C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\botocore\docs\bcdoc\__init__.py)

**Comment by akshaykhc** [comment]
Just an FYI, I was told to use aws cli 1.16.14 for snowball: https://docs.aws.amazon.com/snowball/latest/developer-guide/using-adapter.html#cli-version

**Comment by tim-finnigan** [comment]
Hi @akshaykhc, thanks for following up. It looks like you have an incompatible version of botocore. You should uninstall botocore and the AWS CLI, and reinstall v1.16.14 using the MSI installer following the steps here: https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#msi-on-windows

For more context on botocore comptability, please refer to this comment: https://github.com/boto/boto3/issues/2596#issuecomment-694511182 

> All versions of the CLI released prior to 1.18.141 explicitly require a version of botocore < 1.18.0.

We will work to improve the install guide to account for exceptions such as these. Thanks for bringing this to our attention! Please let us know if you run into any other issues.

**Comment by akshaykhc** [comment]
Hello Tim, thank you!

Incompatible version? Ok. Could you confirm the command to check the current botocore version and the command to uninstall it?

**Comment by tim-finnigan** [comment]
Hi @akshaykhc, I would suggest trying `pip3 show botocore` to see the version and `pip3 uninstall botocore` to uninstall. Instructions on uninstalling aws-cli are included in the [documentation](https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html) mentioned earlier. Please let me know if that works for you.

**Comment by akshaykhc** [comment]
Thank you Tim. I will go through it and let you know the results.

**Comment by akshaykhc** [comment]
So the msi installer has aws cli 1.20.42 and snowball needs 1.16.14

**Comment by tim-finnigan** [comment]
Hi @akshaykhc, to install that specific version using the MSI please try this URL: https://s3.amazonaws.com/aws-cli/AWSCLI64-1.16.14.msi as recommended in this comment https://github.com/aws/aws-cli/issues/1921#issuecomment-210543657. Apologies for not clarifying that earlier.
