### ISSUE TITLE
Create lambda layer error: Invalid choice 'publish-layer-version'

### ISSUE THREAD

**Issue by trungegd** [aws/aws-cli#6395]
I want to create a Layer for the lambda function.
My command is: 
`aws lambda publish-layer-version --layer-name image-magick  --zip-file file://aws/layer/image-magick-layer.zip --compatible-runtimes nodejs14.x`

when I run it, I got the message: Invalid choice: 'publish-layer-version', maybe you meant: publish-version

SDK version number
`aws-cli/1.15.33 Python/3.6.0 Windows/10 botocore/1.10.33`

Platform: Windows 10

Please help me to solve it.

**Comment by stobrien89** [comment]
Hi @trungegd,

Thanks for reaching out!  `publish-layer-version` support was added to the CLI on 11/29/2018, which means you need version `1.16.66` (or any version of CLI v2) to have access to it.  Hope this helps!

**Comment by trungegd** [comment]
Hi, @stobrien89 Thanks for your update.
It works for me.
