### ISSUE TITLE
AWS ECS Describe-clusters - settings [] is empty.

### ISSUE THREAD

**Issue by Guy-Rawsthorn** [aws/aws-cli#6404]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

aws ecs describe-clusters doesn't return the correct "settings" configuration block.
Specifically, it doesn't return whether containerInsights are enabled.

**SDK version number**

aws --version
aws-cli/2.2.38 Python/3.8.8 Linux/4.18.0-80.el8.x86_64 exe/x86_64.centos.8 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?

fedora 30

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

```
resource "aws_ecs_cluster" "main" {
  name = "${var.environment}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}
```
terraform apply

```
aws ecs describe-clusters --cluster abc-cluster --profile dev --region eu-west-2

{
    "clusters": [
        {
            "clusterArn": "arn:aws:ecs:eu-west-2:1234123412:cluster/abc-cluster",
            "clusterName": "abc-cluster",
            "status": "ACTIVE",
            "registeredContainerInstancesCount": 0,
            "runningTasksCount": 7,
            "pendingTasksCount": 0,
            "activeServicesCount": 7,
            "statistics": [],
            "tags": [],
            "settings": [],        # this is wrong
            "capacityProviders": [],
            "defaultCapacityProviderStrategy": []
        }
    ],
    "failures": []
}
```

terraform plan
```
# module.network_efs.aws_ecs_cluster.main will be updated in-place
  ~ resource "aws_ecs_cluster" "main" {
        id                 = "arn:aws:ecs:eu-west-2:1234123412:cluster/abc-cluster"
        name               = "abc-cluster"
        # (3 unchanged attributes hidden)

      + setting {
          + name  = "containerInsights"
          + value = "enabled"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by tim-finnigan** [comment]
Hi @Guy-Rawsthorn thanks for reaching out! In the AWS CLI v2 [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/describe-clusters.html) for `describe-clusters` please note the `--include` tag. To include Settings it says:

> If SETTINGS is specified, the settings for the cluster are included.

So if you just add `--include SETTINGS` to your command then it should provide the information you are looking for. Please let me know if you have any follow up questions.
