### ISSUE TITLE
Docker image 2.2.39 can't install docker or has a breaking change.

### ISSUE THREAD

**Issue by jforand** [aws/aws-cli#6406]
Run the image with `docker run --rm -it --entrypoint "" amazon/aws-cli:latest /bin/bash`
Install docker with `amazon-linux-extras install docker`

Watch as RPM can't find some packages.
```
...
--> Running transaction check
---> Package glibc.i686 0:2.26-48.amzn2 will be installed
--> Processing Dependency: glibc-common = 2.26-48.amzn2 for package: glibc-2.26-48.amzn2.i686
---> Package libgcc.i686 0:7.3.1-13.amzn2 will be installed
---> Package libstdc++.i686 0:7.3.1-13.amzn2 will be installed
--> Finished Dependency Resolution
Error: Package: glibc-2.26-48.amzn2.i686 (amzn2-core)
           Requires: glibc-common = 2.26-48.amzn2
           Installed: glibc-common-2.26-53.amzn2.x86_64 (@amzn2-core)
               glibc-common = 2.26-53.amzn2
           Available: glibc-common-2.25-10.amzn2.0.1.x86_64 (amzn2-core)
               glibc-common = 2.25-10.amzn2.0.1
           Available: glibc-common-2.26-27.amzn2.0.4.x86_64 (amzn2-core)
               glibc-common = 2.26-27.amzn2.0.4
           Available: glibc-common-2.26-27.amzn2.0.5.x86_64 (amzn2-core)
               glibc-common = 2.26-27.amzn2.0.5
           Available: glibc-common-2.26-28.amzn2.0.1.x86_64 (amzn2-core)
               glibc-common = 2.26-28.amzn2.0.1
           Available: glibc-common-2.26-30.amzn2.0.1.x86_64 (amzn2-core)
               glibc-common = 2.26-30.amzn2.0.1
           Available: glibc-common-2.26-32.amzn2.0.1.x86_64 (amzn2-core)
               glibc-common = 2.26-32.amzn2.0.1
...
```

This was working on version 2.2.38

**Comment by yish91** [comment]
Same issue. Any updates on this?

**Comment by clauzf** [comment]
For anyone looking for a temp fix in their CI, rollback to 2.2.37

```
publish-job:
  stage: publish
  image: 
    name: amazon/aws-cli:2.2.37
    entrypoint: [""]
  services:
    - docker:dind
```

**Comment by carlosbustillordguez** [comment]
Same issue. I confirm it's working with the previous version (2.2.38).

**Comment by xxxperimental** [comment]
Same issue, had always been using latest and had to downgrade to `2.2.38` last night:
```
.publish_ecr:
  image:
    name: amazon/aws-cli:2.2.30
```

**Comment by stobrien89** [comment]
Hi all, 

Thanks for the report.  We're looking into this further.

**Comment by stobrien89** [comment]
Thanks for your patience everyone.  This is an issue with the amazonlinux image, which the CLI uses as its base image— the Amazon Linux team is aware and currently working to resolve this.  We don't rebuild tags, but this will very likely be fixed in our next release, which will be next week.  

As an aside, the only tool supported on the image is the AWS CLI.  From our [DockerHub documentation](https://hub.docker.com/r/amazon/aws-cli): 

> Only the aws executable should ever be directly executed. For example even though less and groff are explicitly installed on the image, they should not be executed directly outside of an AWS CLI command.

Of course it's possible to use it as outlined in the original post, but we can't guarantee anything but the `aws` executable works, as the environment is very minimal.  

Let us know if you have any additional questions!

**Comment by kdaily** [comment]
Hi all, with the 2.2.40 release today, this is resolved. Closing, thanks again for bringing it to our attention.
