### ISSUE TITLE
Can't install v2 on windows without admin privileges

### ISSUE THREAD

**Issue by dan-petty** [aws/aws-cli#6412]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the cli on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by tim-finnigan** [comment]
Hi @dan-petty, thanks for reaching out! There is already an open feature request for this here: https://github.com/aws/aws-cli/issues/4633. Someone also provided a workaround in this comment: https://github.com/aws/aws-cli/issues/4633#issuecomment-868583902. Please refer to that open issue to add any feedback or track updates going forward.

**Comment by dan-petty** [comment]
Wow, that's painful. Too bad you don't support basic package management functionality.
