### ISSUE TITLE
Create and publish .deb/.rpm files

### ISSUE THREAD

**Issue by mikael-vandmo-wcar** [aws/aws-cli#6421]
**Is your feature request related to a problem? Please describe.**
Keeping the v2 cli up to date.

**Describe the solution you'd like**
`sudo apt upgrade`

**Describe alternatives you've considered**
Just never upgrade until I am missing a feature that I need.

**Comment by stobrien89** [comment]
Hi @mikael-vandmo-wcar,

Thanks for bringing this up! I'd consider this a duplicate of https://github.com/aws/aws-cli/issues/5282.  We're actively working on a [source distribution ](https://github.com/aws/aws-cli/pull/6352), which should help ease issues with packaging.  We'll post any updates to the linked issue!
