### ISSUE TITLE
v2 Package for Gentoo Linux

### ISSUE THREAD

**Issue by ezzieyguywuf** [aws/aws-cli#6425]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] CLI : passing arguments or cli configurations.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Gentoo Linux

**Describe the question**
This is related to (but hopefully not a duplicate of) issue #4947. In that issue, there is a response from @joguSD  which states (emphasis is mine):

> Lastly, we're looking to continue to improve the installation process for AWS
CLI V2 by potentially integrating with homebrew and **Linux package managers**, and
providing docker images. 

I'm interested in creating such a package to use in gentoo linux. I'm happy to do all the leg work, including setting up the appropriate dependencies etc, however I wanted to start a conversation first to determine whether or not this type of contribution is welcome from the community, or if this is something that the amazon team wanted to do in-house.

**Comment by stobrien89** [comment]
Hi @ezzieyguywuf,

Thanks for reaching out!  As far as I know, this would be a welcome contribution— We're actively working on a [source distribution](https://github.com/aws/aws-cli/pull/6352) , which should help ease issues with packaging, although it doesn’t address adding official support for installing the AWS CLI v2 through them.  

You'll likely have to wait until the source distribution is ready/merged to being working on it, and while we can help with installation issues and things of that nature, we won't be able to provide support on packaging specifics (dependencies, etc.).

**Comment by kdaily** [comment]
@ezzieyguywuf,

I would also follow up with this Gentoo forums post regarding packaging the AWS CLI v2:

https://bugs.gentoo.org/710434

Some of the main concerns raised there should be mitigated by the source distribution, making it straightforward (we hope!) for package maintainers to use. We'd be happy for your, or others from the Gentoo package community, feedback on the source distribution as well.

Closing this for now, but please provide feedback on the proposal and open up any specific issues related to using it.
