### ISSUE TITLE
How can I stay in the auto prompt mode?

### ISSUE THREAD

**Issue by omer-to** [aws/aws-cli#6439]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
macOS Big Sur
**Describe the question**
I have installed AWS CLI v2:

```bash
$ aws --version
aws-cli/2.2.42 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off
```

And I have enabled auto-prompt mode by running the following command:
```bash
aws configure set cli_auto_prompt on
```

When I type `aws`, and then hit ENTER, I indeed get into the auto prompt mode, however, it does not persist. The interactive prompt mode kicks me back after executing a single command.

I am not sure if it is the expected behavior, but if not how can I diagnose and/or fix it?

Additionally I would like to know if I can turn on docs permanently instead of pressing on F3 every time.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

Here is a screen recording showing that I am back to the command prompt after executing `s3 ls`.

https://user-images.githubusercontent.com/63205993/135354729-124fa775-a761-420a-b869-46230571a320.mov

**Comment by tim-finnigan** [comment]
Hi @omer-to, thanks for reaching out! That is the expected behavior. But I agree it would be useful to have the auto-prompt mode persist.

A feature request was already created here to create a persistent shell mode for auto-prompt: https://github.com/aws/aws-cli/issues/5665

Please follow that issue for updates and like the original post to indicate your support for this feature.
