### ISSUE TITLE
Remove all permissions in-line using [] for operations for @auth API Schema

### ISSUE THREAD

**Issue by julien-tamade** [aws/aws-cli#6443]
**Is your feature request related to a problem? Please describe.**
I've found that to be able to query through Model's connections, auth permissions need to be specified at the Model level. But then it's impossible to remove all permissions for an AuthStrategy/Provider in-line. 

For Example:
type Post @model{
  id: ID!
  content: String
  authorId: ID!
  author: User @connection(fields: ["authorId"])
  lastEditDate: String
}

if I have a post model and want a user to query a Post and be able to simultaneously query the Post's author to get their username or profile pic, I would need to specify { allow: private, operations: [read]} at the model Level. However if I want somebody to then not be able to get the Post's last edit date for some reason, I would want to specify something like  { allow: private, operations: []} to remove that read permission. However, specifying the empty array doesn't do anything.

If I had specified previously { allow: private, operations: [read, update]} and then in-line i changed to { allow: private, operations: [update]} it would remove the read.

Being able to specify [] makes a lot of sense to me and would solve a lot of issues.

**Describe the solution you'd like**
I would like the following:
If you specify an empty array [] for operations for an in-line @auth permission, it should remove all permissions for the specified strategy/provider.

**Describe alternatives you've considered**
I've thought about using [create] as the operation specified instead of leaving it blank for the in-line policy, thinking that this will remove the read permission. But I haven't tested it and I'm not sure what having a "create" permission for a specific field of the model would actually do (I'm assuming it would do nothing without having "create" allowed for the whole table??)

**Comment by kdaily** [comment]
Hi @julien-tamade,

I'm not sure what you're referring to here. I see you mention moving off of Amplify - are you using the AWS Amplify CLI? To get help with that, you'll need to head over here:

https://github.com/aws-amplify/amplify-cli/issues

Otherwise if you could provide more detail, that would be great. Thanks!

**Comment by julien-tamade** [comment]
@kdaily oh yeah this was meant for Amplify CLI, not sure how I ended up here.
