### ISSUE TITLE
 `aws s3 ls --recursive` gives duplicated lines

### ISSUE THREAD

**Issue by lldelisle** [aws/aws-cli#6459]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When I run `aws s3 ls --recursive` some lines are duplicated.

**SDK version number**
NA

**Platform/OS/Hardware/Device**
 ```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 ```

**To Reproduce (observed behavior)**
Using a large bucket:
```
aws s3 ls s3://XXXXX-XXX/folderWithALotOfData/ --recursive | awk '{if ($0 == previous){print NR}; previous = $0}'
```

**Expected behavior**
I was expecting an empty line.

**Logs/output**
I got:
```
3001
4001
9001
10001
16001
17001
25001
26001
31001
34001
35001
37001
48001
50001
51001
53001
54001
56001
58001
60001
62001
63001
64001
65001
66001
67001
69001
71001
76001
77001
81001
91001
92001
93001
94001
95001
99001
102001
103001
107001
109001
113001
```

**Additional context**
```
$ aws --version
aws-cli/2.2.43 Python/3.8.8 Linux/5.8.0-59-generic exe/x86_64.ubuntu.20 prompt/off
```
The upload was done by `aws s3 sync`.

**Comment by lldelisle** [comment]
Hi,
Sorry. I forgot to mention that this is not a Amazon aws but a Third-party endpoint.
The host is `--endpoint-url=https://s3.epfl.ch/`
May I send you the full debug by email?
Thanks

**Comment by kdaily** [comment]
Unfortunately we cannot provide debugging or guidance on third party endpoints.

In other cases like this (for example with Ceph and BackBlaze), the endpoints were not written to the specifications that the AWS S3 endpoints do (for example, using `ListObjects` instead of `ListObjectsV2` for some operations). You'll need to reach out to the maintainer of the endpoint to assist further!

**Comment by lldelisle** [comment]
Thanks sorry I did not know.

**Comment by kdaily** [comment]
You're welcome. This issue seems similar, it might help your IT department or endpoint maintainer determine the underlying cause:

https://github.com/aws/aws-cli/issues/4268
