### ISSUE TITLE
ecs run-task often times out or fails when task is defined with s3 environment files

### ISSUE THREAD

**Issue by msporleder** [aws/aws-cli#6470]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
ecs fails to start tasks because:
"stoppedReason": "ResourceInitializationError: failed to download env files: file download command: non empty error stream: RequestCanceled: request context canceled caused by: context deadline exceeded",

this should be retried, etc, as s3 is not so reliable

**SDK version number**
aws-cli/2.2.45 Python/3.8.8 Linux/5.10.47-linuxkit docker/x86_64.amzn.2 prompt/off

**Platform/OS/Hardware/Device**
amazon/aws-cli:latest docker container

**To Reproduce (observed behavior)**
(truncated)
aws --region us-east-1 ecs run-task --cluster default --task-definition dostuff --launch-type FARGATE --overrides "environmentFiles": [{ "type": "s3", "value":"arn:aws:s3:::myenvfiles/prod.env" }]
^^^
Do this a thousand times per day and you will see failures about 1% of the time where ecs times out (I guess) attempting to download that env file from s3.

"stoppedReason": "ResourceInitializationError: failed to download env files: file download command: non empty error stream: RequestCanceled: request context canceled caused by: context deadline exceeded",

**Expected behavior**
task should run like it does the other 98% of the time

**Logs/output**
            "stopCode": "TaskFailedToStart",

**Additional context**
this only happens occasionally.  I am suspicious that it is actually at a lower level like the boto lib but I experience it on the cli.  If there is a timeout/env I can set to work around this that might also work.  The task normally works the next time it is attempted.

**Comment by stobrien89** [comment]
Hi @msporleder,

Sorry to hear about the issues.  I know this would be difficult to capture because of the infrequency, but would it be possible for you to provide debug logs (please obscure any sensitive info) by appending `--debug` to your ecs command?  Even logs from a successful command would be helpful, as we could see if there's anything from a configuration standpoint that we could adjust in terms of retries.  Thanks!

**Comment by msporleder** [comment]
I will see what I can do but --debug logs to stdout so it messes up my parsing of the output to detect this error at all

**Comment by stobrien89** [comment]
Hi @msporleder,

Thanks for the additional information!  It looks like this may be a latency issue between ecs and S3— The CLI isn't making any calls to s3, so we're unable to affect this using s3-specific configuration settings.  I can raise this with the ECS team, but we'll need debug logs for an instance where it fails.  I believe they'll be able to trace the request/response in greater detail with the request id (found in debug logs) on their side.  Let me know what you'd like to do either way!

**Comment by msporleder** [comment]
Yeah I agree that it is between ECS and S3.  Can I really be the only person hitting this?

Anyway do you want request id's from me?  I have a bunch but they are requests to ECS I think -- not the internal requests to s3.  I can provide these all day.  :/

'x-amzn-RequestId': '09a5997c-7df1-4c03-8856-be70c0f74001'
'x-amzn-RequestId': '1ceb7adc-367e-469e-902f-07868c691f24'
'x-amzn-RequestId': '339e209b-e02a-49d9-8bc9-ca5eb5fa1a8a'
'x-amzn-RequestId': '4743d6c2-ac30-40a9-a5da-d0d766375f7c'
'x-amzn-RequestId': '0fffe6b5-f71d-4f98-ab8a-8cb6b1160d5e'

What do you mean by "instance"

**Comment by msporleder** [comment]
@stobrien89 okay those should all be examples of such a case (within the last few hours of posting)

**Comment by msporleder** [comment]
more examples
'x-amzn-RequestId': '0e5395bd-b898-4532-b4a9-324b50daee5e'
'x-amzn-RequestId': '595fe612-0c05-45a7-a149-bb71006f3cc9'

**Comment by msporleder** [comment]
I haven't seen it directly but I am suspicious that secrets manager might have similar timeout issues

**Comment by stobrien89** [comment]
Hi @msporleder,

Thank you so much for your patience.  The ECS team has notified me that this was related to a known issue with s3 retries for which a fix was rolled out on 11/20/21.  Please let us know if you're still experiencing any issues!

**Comment by msporleder** [comment]
I moved all of my jobs to using defined envs so I won't see much test of this.  I appreciate you guys tracking it down!
