### ISSUE TITLE
AWS::ECR::PublicRepository unrecognized resource type

### ISSUE THREAD

**Issue by eichelkrauta** [aws/aws-cli#6491]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I saw that cloudformation has the documentation on their site for [creating a public repo via cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html). I was hoping to use this, however it calls it out as an unrecognized resource type.

**SDK version number**
aws-cli/2.2.46 Python/3.8.8 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.debian.10 prompt/off

**Platform/OS/Hardware/Device**
Microsoft Windows WSL2 w/ Debian installation

**To Reproduce (observed behavior)**
Using this template saved as `stack.yml`
```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  TestRepo:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: "test"
```

and calling 
```
aws cloudformation create-stack --stack-name TESTME  --template-body file://stack.yml
```

I get:
```
An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unrecognized resource types: [AWS::ECR::PublicRepository]
make: *** [Makefile:4: create-stack] Error 254
```

**Expected behavior**
Be able to create/update cloudformation stacks w/ `AWS::ECR::PublicRepository` resource types

**Comment by tim-finnigan** [comment]
Hi @eichelkrauta, thanks for reaching out. Which region is your CLI configured to? If you’re not using us-east-1, then that is likely why you’re seeing this error.

This was addressed in another issue here: https://github.com/awsdocs/aws-cloudformation-user-guide/issues/956

As noted in [this comment](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/956#issuecomment-813501383):

> At this time, our docs reflect valid values for us-east-1 . AWS::ECR::PublicRepository is supported in us-east-1...

That comment also mentions an open request (https://github.com/awsdocs/aws-cloudformation-user-guide/issues/490) to include support across regions.

**Comment by tim-finnigan** [comment]
Glad to hear that helped! I'll go ahead and close this issue then. If you want to add any feedback or comments to that open request linked above then please feel free to do so.
