### ISSUE TITLE
Unable to remove bucket in one step

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#651]
<pre>
[root@sgd ~]# aws --version   
aws-cli/1.2.13 Python/3.3.3 Linux/3.8.4-1-ARCH
[root@sgd ~]# aws s3 rb --recursive s3://resumetest
Unknown options: --recursive
[root@sgd ~]#  aws s3 rb s3://resumetest --recursive
Unknown options: --recursive
[root@sgd ~]#  aws s3 rb s3://resumetest            
remove_bucket failed: s3://resumetest/ A client error (BucketNotEmpty) occurred when calling the DeleteBucket operation: The bucket you tried to delete is not empty
</pre>

What am I missing?

How do I remove a bucket in one step?

**Comment by sureshamk** [comment]
remove_bucket failed: s3://<mybucketName>/ An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty. You must delete all versions in the bucket.

How to remove the versions quickly

**Comment by voycey** [comment]
+1 for this - this is painful

**Comment by lmayorga1980** [comment]
:+1: Sept 2017?

**Comment by alexkravets** [comment]
August 2018

**Comment by madhuravius** [comment]
I am also running into this problem for a versioned bucket. There are some longer scripts people seemed to have posted for this as a resolution (either with boto or cli):

1. https://stackoverflow.com/questions/29809105/how-do-i-delete-a-versioned-bucket-in-aws-s3-using-the-cli
1b. (Same answer as #1 in comments): https://forums.aws.amazon.com/thread.jspa?threadID=167616
2. Gist with cli that does something similar: https://gist.github.com/weavenet/f40b09847ac17dd99d16

These solutions seem very verbose for something that should be pretty simple and in the CLI

**Comment by benhannel** [comment]
The `--force` option still does not work for versioned buckets

**Comment by deimosfr** [comment]
Can we re-open this ticket?

**Comment by benhannel** [comment]
Maybe this behavior is intentional? If you have a versioned bucket, it’s often because you really really don’t want to lose the contents forever. So perhaps deleting it should be quite hard. A force override with a prompt seems like a good idea though.

**Comment by chadReimers** [comment]
please re-open still an issue

**Comment by tim-finnigan** [comment]
There is overlap here with this open issue being tracked: https://github.com/aws/aws-cli/issues/4070

There are workarounds for removing a bucket with versioning enabled discussed here: https://stackoverflow.com/questions/29809105/how-do-i-delete-a-versioned-bucket-in-aws-s3-using-the-cli
