### ISSUE TITLE
Update aws cloudformation package docs to include missing resources

### ISSUE THREAD

**Issue by ConnorKirk** [aws/aws-cli#6516]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [X] Other/Not sure.

It appears that the `aws cloudformation package` command supports more resources than listed in the documentation.

Specifically, I can see these three resources supported, but not mentioned in the docs.

   *  `Location` property of the `ServerlessApplicationResource` (`AWS::Serverless::Application`),
   *  `ContentUri` of the `ServerlessLayerVersionResource` (`AWS::Serverless::LayerVersion`)
   *  `Content` property of the `LambdaLayerVersionResource` (`AWS::Lambda::LayerVersion`)

Resources are taken from https://github.com/aws/aws-cli/blob/daeaf7d46b7d14140a6c96ce931575ccf8dbf2d8/awscli/customizations/cloudformation/artifact_exporter.py#L500

Docs are https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/package.html

I think this file needs to be updated
https://github.com/aws/aws-cli/blob/develop/awscli/examples/cloudformation/_package_description.rst

I'm happy to make the PR, but I'll wait for a maintainer to respond first.

**Comment by kdaily** [comment]
I think that looks correct, @ConnorKirk - go for it and let me know when you have a PR up. Thanks!

**Comment by kdaily** [comment]
Looks like `AWS::AppSync::FunctionConfiguration` might also be missing?
