### ISSUE TITLE
Unable to change content-type on S3 objects

### ISSUE THREAD

**Issue by mlb5000** [aws/aws-cli#652]
I'm trying to use the S3 'cp' command to update the metadata on a large number of existing objects that are already uploaded to S3.  I'm doing this by:

    aws s3 cp s3://path/to/the/bucket s3://path/to/the/bucket --recursive --content-type image/jpeg --include *.jpg

However, whenever I run this command I get the following error:

    copy failed: s3://path/to/the/bucket/_image.jpg A client error (InvalidRequest)
    occurred when calling the CopyObject operation: This copy request is illegal
    because it is trying to copy an object to itself without changing the object's
    metadata, storage class, website redirect location or encryption attributes.
                        
I'm not sure what I'm doing wrong.  Any suggestions?

**Comment by kyleknap** [comment]
This has been a feature in the CLI for a while now. You can achieve what you want to do by using ``--metadata-directive REPLACE`` when trying to copy over the same object. Closing issue.

**Comment by mattboehm** [comment]
Unfortunately, this means that if you have other metadata you want to preserve, you have to read the object from s3 to pass its existing metadata back in. Since Content-Type is not stored inside the Metadata dict, this feels wrong to me.

**Comment by eepstein** [comment]
This is really messed up.
All I want to do is replace 2 of the metadata fields on an existing object using the CLI and now instead I a) have to replace the object and b) replace ALL the metadata.  Why?

**Comment by chinchang** [comment]
I used `--metadata-directive  REPLACE` and my exisiting meta-data remained. And the one i specified in the command just got added to it.
