### ISSUE TITLE
CLIv2 aws batch list-jobs doesn't support --filters switch, despite documentation showing it

### ISSUE THREAD

**Issue by HariSekhon** [aws/aws-cli#6526]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

CLIv2 docs below says there should be a `--filters` switch but it's not supported in my local CLIv2.

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/batch/list-jobs.html

**SDK version number**

```
aws --version
aws-cli/2.2.22 Python/3.8.8 Darwin/17.5.0 exe/x86_64 prompt/off
```

**Platform/OS/Hardware/Device**
Mac

**To Reproduce (observed behavior)**

Switch not visible in:
```
aws batch help
```

```
aws batch list-jobs --job-queue "$name" --filters "name=BEFORE_CREATED_AT,values=1635852396164"

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --filters, name=BEFORE_CREATED_AT,values=1635852396164
```

**Expected behavior**
Expected to return results that had been server side filtered by creation epoch timestamp

**Logs/output**

**Additional context**

**Comment by kdaily** [comment]
Hi @HariSekhon,

Thanks for your question. This parameter was added in August 2021. Your version (`2.2.22`) was released in July 2021, so you'll need to update your AWS CLI v2 version.
