### ISSUE TITLE
SSL hostname error w/ 1.16.14 and snowball edge

### ISSUE THREAD

**Issue by gnieboer** [aws/aws-cli#6534]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Attempting to initiate an SSL connection using port 8443, received the error:
SSL Error: hostname **u**"10.20.10.200" does not match "10.20.10.200"

**SDK version number**
1.16.14 (Most recent Snowball Edge compatible CLI)
installer embeds python 2.7.9 and botocore 1.12.4

**Platform/OS/Hardware/Device**
Windows 2012R2, Powershell or Command line

**To Reproduce (observed behavior)**
open command window, initiate any command similar to:
aws s3 ls s3://mybucket --endpoint https://myip:8443
Command will fail

**Expected behavior**
Expect connection to succeed and copy/list files.

**Logs/output**
Currently unable to attach logs from this internal server, examination clearly showed a hostname comparison being conducted between strings and failing due to encoding issues.  
Error occurs immediately after entry about sending http request.

**Additional context**
Clearly a unicode-related issue, attempting to change encoding passed to command was unsuccessful
Unclear how to upgrade the msi-installed version to python3, and transfer is mission-critical.
All operations are 99.999% successful over http endpoint, but 1:1000000 files require an SSL connection for issues unique to our local environment.

**Comment by kdaily** [comment]
Hi @gnieboer,

Looking into this. Can you confirm that this previously worked and recently start occurring?

**Comment by gnieboer** [comment]
This was the first time we attempted to use the SSL endpoint, so I don't have a scenario where we were able to get SSL to work.  But all *other* transfers/actions/syncing via the HTTP endpoint are working just fine, it's clearly just an SSL issue.

Traceback: Yes I was just looking at that myself actually...  
awsrequest.py line 260
endpoint.py line 218
endpoint.py line 174

**Comment by kdaily** [comment]
Thanks @gnieboer, but I'll need to see farther up the stack trace than that! This might go back to something in `urllib3` or another library we depend on.

We do have a Python 3 MSI available, can you give that a try?

https://s3.amazonaws.com/aws-cli/AWSCLI64PY3-1.16.14.msi

**Comment by gnieboer** [comment]
Ah, I did not know there was an MSI specifically with PY3.  I will give that a try, I suspect that will patch my issue.

**Comment by gnieboer** [comment]
Confirmed transfer completed successfully w/ the PY3 version of 1.16.14 from the URL above.  

I will close and hope this helps others on search, though I hope that the overall team gets the v2 CLI compatible with the Snowball Edge soon.

**Comment by kdaily** [comment]
Thanks @gnieboer, I will definitely pass on the details of this issue and the feedback to the Snowball team.
