### ISSUE TITLE
CLI version 1.22.0 breaks aws eks update-kubeconfig

### ISSUE THREAD

**Issue by toly-k** [aws/aws-cli#6537]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
CI pipeline picked up the latest major version and my build started failing. Downgrading to `1.21.12` solved the issue:
`python -m pip install --upgrade pip awscli==1.21.12`

**SDK version number**
1.22.0

**Platform/OS/Hardware/Device**
Ubuntu 20.04.3 LTS

**To Reproduce (observed behavior)**
Run `aws eks update-kubeconfig`

**Expected behavior**
`aws eks update-kubeconfig` succeeds 

**Logs/output**

```
Installing collected packages: pip, docutils, rsa, python-dateutil, jmespath, botocore, s3transfer, awscli
Successfully installed awscli-1.22.0 botocore-1.23.0 docutils-0.15.2 jmespath-0.10.0 pip-21.3.1 python-dateutil-2.8.2 rsa-4.7.2 s3transfer-0.5.0
```
```
aws eks update-kubeconfig --name ***** \
  --region us-east-1 \
  --role-arn ************
  cat ~/.kube/config
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    region: us-east-1
    accountId: ***
    repo: ***
    namespace: ***
    environment-overlay: ***
    cluster-name: ***
    cluster-authentication-role-arn: ***
    IMAGE_TAG: a21f6cf
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
Traceback (most recent call last):
  File "/home/runner/.local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/home/runner/.local/lib/python3.8/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/home/runner/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'OP_NO_TICKET' from 'urllib3.util.ssl_' (/usr/lib/python3/dist-packages/urllib3/util/ssl_.py)
Error: Process completed with exit code 1.
```

**Additional context**

**Comment by mhlic** [comment]
I am seeing the same error even just running `aws`. Downgrading also fixes it for me.

**Comment by MinhPhu0304** [comment]
I am seeing the same issue with ecr_login command too.

**Comment by nateprewitt** [comment]
Hi everyone,

This is the same issue as boto/botocore#2562. I've replied with info and mitigation steps [here](https://github.com/boto/botocore/issues/2562#issuecomment-963583290).

We're currently working on a fix, but CLI customers can either upgrade to `urllib3 >= 1.26.0` or `awscli < 1.22` to mitigate impact in the short term.

**Comment by nateprewitt** [comment]
Botocore 1.23.1 has been released with fix for this. Please let us know if you're still experiencing issues.

**Comment by nateprewitt** [comment]
Now that we have things patched, I'm going to resolve this in favor of the original [botocore](https://github.com/boto/botocore/issues/2562) ticket. If you have any further concerns or feedback please feel free to add it there. Thanks!
