### ISSUE TITLE
AWS S3 sync it's not fetching files from the specified folder

### ISSUE THREAD

**Issue by Alin-Andrei** [aws/aws-cli#6544]
Hi all,

I have an issue with aws s3(i'm new to this, so bare with me).
It goes like this:
     Let's say that i've added the key with a specific path: e.x. C:\Users\username\Documents\my files. The targeted folder contains X files. When i'm synching with my bucket, it fetches those X files and different files from the pc(system32 files, folder, etc) and i'm not able to find out why.

Do you have any idea of the possible issue?

I didn't find something similar, but if there's an issue opened already, my post can be closed.

Thank you for your help!

**Comment by kdaily** [comment]
Hi @Alin-Andrei,

Sorry to hear you're having trouble. I'm not sure that I can figure out what is going on without some more information.

Can you:

1. reproduce this with a small subset of files, and
2. provide the commands you're running to put files in the bucket and retrieve them, and
2. provide debug logs from the sync command you're running? You can do this by adding the `--debug` parameter to your command. Be sure to redact any sensitive information.

Thanks!

**Comment by Alin-Andrei** [comment]
> Hi @Alin-Andrei,
> 
> Sorry to hear you're having trouble. I'm not sure that I can figure out what is going on without some more information.
> 
> Can you:
> 
> 1. reproduce this with a small subset of files, and
> 2. provide the commands you're running to put files in the bucket and retrieve them, and
> 3. provide debug logs from the sync command you're running? You can do this by adding the `--debug` parameter to your command. Be sure to redact any sensitive information.
> 
> T

**Comment by Alin-Andrei** [comment]
Hello @kdaily,

Thank you for your fast reply.
I've reproduced the process on a test env and it worked just fine(the issue is on a client side). The sync is automatic and it's done at a specific time( X minutes).

I've used the following commands:
-after installing AWS i've used "aws configure" with the specific key
-after the config i've used aws s3 ls to see if the bucket is vizible
-restarted the service that was targetet for the file sync.

I'll see what i can do about the logs.
(the command is "aws s3 --debug"?)

**Comment by Alin-Andrei** [comment]
Hello @kdaily 

I've found generic commands for the debug session:
$ aws servicename commandname options --debug 2> debug.txt
$ aws servicename commandname options --debug 

In this case i'm not sure how to replace the "servicename","commandname" and "options" as i'm not very familiar with AWS.
Do you think you can help me with that?

E.x. of the aws config:

$ aws configure
AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
Default region name [None]: us-west-2
Default output format [None]: json

Also, having multiple buckets on the same account, for each bucket should be used a different key?
Or the sync it's done for each individual bucket as specified in the key added in the config file?

**Comment by kdaily** [comment]
Hi @Alin-Andrei,

No worries! I'll try to help you as much as I can.

One thing I'm unclear about is this part that you noted:

> - restarted the service that was targetet for the file sync

This repository is only to support running commands from the command line, so if you're using some other service to sync files, I'm not sure I'll be able to help you.

I would encourage you to read our [user guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html), specifically the section on using AWS s3 [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html).

An AWS CLI sync command would look like the following, with the `--debug` flag added to output logging:

```
aws s3 sync source s3://bucket-destination --debug
```
Regarding your questions on configuration, I would suggest reviewing the AWS getting started guide [here](https://aws.amazon.com/getting-started/?nc1=f_cc). In general, access keys and secret keys are tied to who or what should have access to your AWS resources.

For the sync operation, it only works with a single source or destination at a time. If you're copying files from a bucket to a local computer, you would need to run a command separately for each bucket.

**Comment by Alin-Andrei** [comment]
Hello @kdaily ,

Thank you for your fast reply.

Regarding the sync operation. This issue(until now) appears only when the files are synced from local computer to a bucket, this is the part that i would like to debug. 

I've read the docs provided by you, but i dind't find much info about my issue or how i can find out the root cause.

Regarding the service, it's just a way to sync the files automaticaly at the time interval provided in a config file.

I don't know how to explain this in a easier manner:(.

Until now did you encounter something similar to this?
At least do you have an idea of what could be a possible cause for the sync between the local computer and aws? Maybe i've missed something and i'm looking at this in the wrong way.

Thank you for your help!

Alin

**Comment by kdaily** [comment]
Hi @Alin-Andrei,

Thanks for the information. There could be different reasons why you're having an issue syncing, but without debug logs I'm not exactly sure what's going on here. Could it be that hidden system files are being transferred?

Reviewing the debug logs is the only way that I can be sure of what is occurring. I encourage you to test this without the automated part and focus on running the same `aws s3 sync` command in a Windows terminal prompt, adding the `--debug` flag to whatever command you are already running. This will show what files are being attempted to sync. 

For example, if I have a directory `/tmp/test/` that I want to sync to `s3://mybucket` and I want to see the debug logs during the transfer, I would run:

```
aws s3 sync /tmp/test/ s3://mybucket/test/ --debug
```

This would print debug logs to standard output. You could capture them by redirecting the output to a file. Please provide the output that is printed during this step.

You can also run the command with the `--dryrun` flag - this will show what the sync would transfer without actually performing the transfer. Using the same example as above, this is the command you would run:

```
aws s3 sync /tmp/test/ s3://mybucket/test/ --dryrun
```

Then you can compare what it shows will be transferred with what you expect to be transferred.

**Comment by Alin-Andrei** [comment]
Hello @kdaily ,

So i've runed the commands and the logs showed what was expected. With the --dryrun command, it returned the correct number of files existing in the targeted folder and with the --debug command, it uploaded the correct number of files.

But without these commands, the other files are still uploaded.

Thank you,
Alon

**Comment by kdaily** [comment]
@Alin-Andrei, thanks for the update. If the command works as intended with the `--debug` flag, there is no difference to running it without it. Without seeing the debug logs, I'm not able to assist any further, as it would just be speculation. Please provide (sanitized, remove any sensitive information) the logs for us to assist. Thanks!
