### ISSUE TITLE
IAM new-role wizard doesn't handle nullable description

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-cli#6545]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
While running the iam `new-role` wizard (e.g. `aws iam wizard new-role`) the description attribute is not required, if a value isn't added, an 'empty' key is added to the generated CloudFormation template - which is invalid - resulting in a failed deployment via cloudformation.

**SDK version number**
aws-cli/2.3.2 Python/3.8.5 Linux/4.14.252-195.483.amzn2.x86_64 source/x86_64.amzn.2 prompt/off

**Platform/OS/Hardware/Device**
Cloud 9

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**
The Description property should just be dropped from the YAML if it's not specified.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by tim-finnigan** [comment]
Thanks @kiiadi for reaching out and bringing this to our attention. I could reproduce the behavior you described. I created the PR linked above to address this.

**Comment by stealthycoin** [comment]
Merged the linked PR.
