### ISSUE TITLE
aws kms -h doesn't work

### ISSUE THREAD

**Issue by ardove** [aws/aws-cli#6546]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Running `aws kms -h` or `aws kms --help` doesn't spit out helpful information. 
![image](https://user-images.githubusercontent.com/5799101/141878663-dccaedae-4f18-4e66-a182-074c36b329ef.png)

**SDK version number**
aws-cli/2.2.29 Python/3.8.8 Windows/10 exe/AMD64 prompt/of

**Platform/OS/Hardware/Device**
aws-cli/2.2.29 Python/3.8.8 Windows/10 exe/AMD64 prompt/of

**To Reproduce (observed behavior)**
Above.  Run `aws kms -h`

**Expected behavior**
I expect the same information to be printed from the `aws kms help` or `aws kms list-keys help` command.

**Logs/output**
See screenshot above

**Additional context**
N/A

**Comment by tim-finnigan** [comment]
Hi @ardove, thanks for reaching out. We do have a long-standing feature request to update the help paradigm here: https://github.com/aws/aws-cli/issues/303. You can like the original post to show your support for this feature or leave a comment in the issue if you have any additional feedback.

In the meantime you can use `aws kms help` and `aws kms list-keys help` as you mentioned.
