### ISSUE TITLE
AWS SSO AccessToken custom expiration time ?

### ISSUE THREAD

**Issue by awoimbee** [aws/aws-cli#6547]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Describe the question**
Hi,
Our issue: having to run `aws sso login` more than once a day (SSO AccessToken TTL is too short), how to get a longer validity time ? or is there a better solution ?

It would be great to simply run `aws sso login` every morning and be done with it. For some workloads we could even have a longer validity time (it would still be much better than IAM access keys).
But I can't figure out how to get a longer expiry time (`expiresAt` in ` ~/.aws/sso/cache/<random-long-file-name>.json` is always 7h in the future).

I feel like I've tried everything, from `AWS_CREDENTIAL_EXPIRATION` to SSO permission set expiration time, but these have no effect on the SSO AccessToken expiration.

We use a SAML provider, but I don't have control over expiration times there either.

EDIT:
Example of a normal usage of the cli where this causes issues:
```bash
aws sso login
aws s3 ls
# wait 8 hours (started work at 9, it's now 17)
aws s3 ls # OK
aws s3 ls --profile superProfile # FAIL

aws sso login
# wait 8 hours
aws s3 ls # FAIL
aws s3 ls --profile superProfile # FAIL
```

**Comment by kdaily** [comment]
Hi @awoimbee,

Thanks for your comment. The access token expiration time is not determined by the AWS CLI or any AWS SDK, it's limited by the AWS SSO implementation. From the documentation:

https://docs.aws.amazon.com/singlesignon/latest/userguide/authconcept.html

> Each time a user signs in to AWS SSO, a sign in session is created with an 8-hour lifetime.

I'll pass along your feedback to the AWS SSO team!
