### ISSUE TITLE
aws s3api get-bucket-notification-configuration --bucket xxx produces no output at all if there is not Event Notifications configured

### ISSUE THREAD

**Issue by ecerulm** [aws/aws-cli#6557]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
macos

**Describe the question**

aws s3api get-bucket-notification-configuration --bucket xxxx --output json
aws s3api get-bucket-notification-configuration --bucket xxxx --output text

produces no output at all, completely empty response. The bucket has not notification configuration, so I was expecting to get either 
`null`
`{}` 
`{ "TopicConfigurations": [], "QueueConfigurations": [], "LambdaFunctionConfigurations": [] }`

but the result is the completely absence of output / empty output 

```
rubelagu@Ruben-Laguna-MacBook-Pro:~$ aws s3api get-bucket-notification-configuration --bucket xxxx --output json
rubelagu@Ruben-Laguna-MacBook-Pro:~$
```

The CLI documentation for [get-bucket-notification-configuration](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/get-bucket-notification-configuration.html) says:

> If notifications are not enabled on the bucket, the action returns an empty NotificationConfiguration element.

which I interpreted as I should return `{}`. So I wonder, is this the expected behaviour? would it be better to be more explicit at least on `--output text` saying `no configuration` or something? 

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by tim-finnigan** [comment]
Hi @ecerulm thanks for reaching out. I could reproduce the behavior that you described. 

As you referenced from the documentation, that action returns an empty NotificationConfiguration element if notifications are not enabled on the bucket. For more context here is the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_NotificationConfiguration.html) for NotificationConfiguration, where it’s described as “A container for specifying the notification configuration of the bucket.”

So returning nothing is expected for the empty NotificationConfiguration element. But I think it would be better as you suggested to return one of those responses you were expecting. Or maybe outputting a message like “No notification configuration exists for [bucket]” would be best. I think we can keep this open as a feature request to improve the response. I’ll reach out to the S3 team and pass along this feedback.

**Comment by tim-finnigan** [comment]
P55554248
