### ISSUE TITLE
libssl.so.1.0.0: cannot open shared object file: No such file or directory when trying to download with curl

### ISSUE THREAD

**Issue by DigeratiOhm** [aws/aws-cli#6561]
Attempting to download aws-cli using the following command on Oracle LInux 6.10:
  #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
Getting a return error of:
  curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Did the following:
  [root@artemis install]# whereis libssl.so.1.0.0
  libssl.so.1.0: /usr/lib64/libssl.so.1.0.1e /opt/VRTSralus/bin/libssl.so.1.0.0
Went to /usr/lib64 and found the symbolic link:
  libssl.so.10 -> libssl.so.1.0.1e
Attempted the same download on Oracle Linux 7.9, which was successful.
  [root@agni lib64]# whereis libssl.so.1.0.0
  libssl.so.1.0: /usr/lib64/libssl.so.1.0.2k
The symbolic link on that machine is:
  libssl.so.10 -> libssl.so.1.0.2k
Does aws-cli require a higher version than libssl.so.1.0.1e, or am I missing something altogether different?

**Comment by kdaily** [comment]
Hi @DigeratiOhm,

Sorry to hear you're having trouble. Unfortunately it looks like this is an issue with your installation of `curl` and it's dependencies, which is something we can't help with.

To unblock you, maybe you can try another mechanism to download the zip file, like `wget`? I would suggest taking a look for issues with `curl` and `openssl` on StackOverflow.

If you have trouble with getting the CLI installed after you have it downloaded, feel free to open up an issue with your questions.

**Comment by DigeratiOhm** [comment]
Thanks Ken.  Pulled it over from the 7.9 server and it installed correctly.
