### ISSUE TITLE
Support for SOCKS proxy

### ISSUE THREAD

**Issue by mengmann** [aws/aws-cli#6570]
**Is your feature request related to a problem? Please describe.**
Currently there is no support for using a SOCKS proxy with aws cli:
```
$> export https_proxy="socks5://localhost:8080" http_proxy="socks5://localhost:8080"
$> aws sts get-session-token
Failed to connect to proxy URL: "http://socks5://localhost:8080"

$> aws eks get-token --cluster-name dev
Failed to connect to proxy URL: "http://socks5://localhost:8080"
```

**Additional context**
Why is this needed?
There are certain use cases where aws cli is involved and API usage or effective permissions are limited to individual ip addresses. for example:
AWS IAM: [IAM roles/policies with with IpAddress Conditon](https://aws.amazon.com/premiumsupport/knowledge-center/iam-restrict-calls-ip-addresses/)
AWS S3: [Bucket Policys with IpAddress Conditon](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html#example-bucket-policies-use-case-3)
AWS EKS: [CIDR blocks for public Endpoint access](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html)

In secured and protected setups, client requests are often allowed from trusted sources such as bastion or proxy hosts only. And here comes SOCKS proxies into play (tunnel via ssh).

Lets take EKS for example:

- I want to limit public endpoint access.
- kubectl already respects `socks5://host:port` url from proxy env vars. So thats fine.
- When you now announce your proxy: `export https_proxy="socks5://localhost:8080"`
- kubectl wants to run `aws eks get-token --cluster-name dev` in the background to gain iam access.
- This fails:
```
$> kubectl get nodes
Failed to connect to proxy URL: "http://socks5://localhost:8080"
```

**Describe the solution you'd like**
I would like to have the possibility to use a socks proxy with aws cli. 
aws cli should evaluate the proxy environment variables so that the socks proxy protocol in the url is respected and used properly.

Using socks proxy with requests: needs [PySocks](https://pypi.org/project/PySocks/)
Using socks proxy with urllib3: https://urllib3.readthedocs.io/en/latest/reference/contrib/socks.html

**Describe alternatives you've considered**
Running and using a real http proxy:
Embedded ssh SOCKS proxys are often preferred as a lightweight and more secure alternative to real http proxies. http proxies needs to be installed, configured, secured, kept running, monitored, maintained and exposed. Devops and admins off course want to reduce operational overhead where-ever possible ;-)

**Comment by tim-finnigan** [comment]
Hi @mengmann, thanks for reaching out and providing all of this context for your feature request. However we are already tracking this feature request here in the botocore repository: https://github.com/boto/botocore/issues/2540. There is a PR linked in that issue but more discussion and review is needed. Please refer to that issue for updates going forward.

**Comment by mheers** [comment]
As a workaround you could put a http proxy in front of your socks5 proxy. Following https://superuser.com/a/1533394/1753627 you can

```bash
pip3 install pproxy
pproxy -r socks5://127.0.0.1:9090
```
Which assumes you run your socks proxy at localhost port 9090. This opens a http proxy on localhost port 8080 which you now can use for the aws cli:

```
export HTTP_PROXY=http://localhost:8080
export HTTPS_PROXY=https://localhost:8080
```

**Comment by ckujau** [comment]
NB: it's `export HTTPS_PROXY=http://localhost:8080`, even for `HTTPS_PROXY`, but yeah -- thanks for sharing this hint!
