### ISSUE TITLE
I am getting this error , not able to resolved after research.

### ISSUE THREAD

**Issue by mosharafkarim** [aws/aws-cli#6580]
denied: Your authorization token has expired. Reauthenticate and try again.
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

in Jenkins previuosly it was working , but i have checked authorization token it is expired , how to reauthenticate existing token.

**Comment by tim-finnigan** [comment]
Hi @mosharafkarim, please provide the following information from our [Bug report template](https://github.com/aws/aws-cli/issues/new?assignees=&labels=needs-triage&template=---bug-report.md&title=) so that we can better assist you:

>Confirm by changing [ ] to [x] below to ensure that it's a bug:
>- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
>- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
>
>**Describe the bug**
A clear and concise description of what the bug is.
>
>**SDK version number**
>
>**Platform/OS/Hardware/Device**
>What are you running the cli on?
>
>**To Reproduce (observed behavior)**
>Steps to reproduce the behavior
>
>**Expected behavior**
>A clear and concise description of what you expected to happen.
>
>**Logs/output**
>Get full traceback and error logs by adding `--debug` to the command.
>
>**Additional context**
>Add any other context about the problem here.

**Comment by shubham-marathia** [comment]
Can you please provide some more information over this token you are referring to ? The information currently provided is insufficient.

**Comment by kdaily** [comment]
@mosharafkarim, If you have further details as requested above, please provide them via the template. Thanks!
