### ISSUE TITLE
Jenkins and aws issue

### ISSUE THREAD

**Issue by mosharafkarim** [aws/aws-cli#6583]
denied: Your authorization token has expired. Reauthenticate and try again.
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

I am getting this after doing build in jenkins for jobs , the particular slave node which i am using for build on that node it's showing the authorization token expired , the slave node i have launched in aws and connected in jenkins to do build previously it was working for 6-8 months or maybe more than that but now it's showing this error. Whenever taking this slave to do build for multiple jons in jenkins its showing same error.If anyone know please help me out 
![issue](https://user-images.githubusercontent.com/69795428/144188246-25141d30-d415-40d1-9de0-177a54e73256.png)

Thanks

**Comment by kdaily** [comment]
Hi @mosharafkarim,

Sorry to hear you are having trouble. Unfortunately we can only provide support for a failure of the AWS CLI. If you can provide debug logs for a failing AWS CLI command (`aws --debug`), please open up a new issue with the details requested in the template. Thanks!
