### ISSUE TITLE
Slow execution of aws lambda update-function-code

### ISSUE THREAD

**Issue by ugofc81** [aws/aws-cli#6585]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Calls to aws lambda update-function-code althought immediately execute take unusual time for the LastUpdateStatus

**SDK version number**

**Platform/OS/Hardware/Device**
Debian GNU/Linux 10 (buster)

**To Reproduce (observed behavior)**
Executing
`aws lambda update-function-code --function-name "${FUNCTION_NAME}" --zip-file "fileb://build/${FUNCTION_NAME}.zip"`
twice at a short interval.

(instead of executing twice the same command, it happened also executing another lambda command, e.g.:
`aws lambda publish-version --function-name "${FUNCTION_NAME}"`)

The second `aws lambda` call fails, with message for instance
`An error occurred (ResourceConflictException) when calling the PublishVersion operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:...`

**Expected behavior**
no failure

**Logs/output**
`An error occurred (ResourceConflictException) when calling the PublishVersion operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:...`

**Additional context**
The script worked for years with no particular issue, since one week it started generating this error.
We made a workaround, but maybe the behavior is a sign of an issue in the backend

**Comment by kdaily** [comment]
Hi @ugofc81,

It looks like this is related to the following change to AWS Lambda, announced in July 2021:

https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

Specifically this section seems relevant to you:

> Nothing is changing about how functions are created, updated, or operate as part of this. However, this change may impact certain workflows that attempt to invoke or modify a function shortly after a create or an update action. Before making API calls to a function that was recently created or modified, confirm it is first in the Active state, and that the LastUpdateStatus is Successful.

There isn't anything to change for the AWS CLI as this is the behavior of the API. If you have further questions about Lambda execution, please check out the AWS Developer Forums for Lambda:

https://forums.aws.amazon.com/forum.jspa?forumID=186&start=0
