### ISSUE TITLE
aws s3 cp with GLACIER_IR storage class

### ISSUE THREAD

**Issue by kjaercasper** [aws/aws-cli#6587]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
aws s3 cp storage class

**Platform/OS/Hardware/Device**
Cent 7.5
aws-cli/2.4.4 

**Describe the question**

Anybody knows when the AWS CLI will suport then new Glacier instant, works with the API, but not via s3 cp

root ~ $ `aws s3 cp --follow-symlinks /data/emfs1/.projects/premiere/test/IMG_6723.MOV s3://XXX --storage-class GLACIER_IR`

```
aws: error: argument --storage-class: Invalid choice, valid choices are:

STANDARD | REDUCED_REDUNDANCY
STANDARD_IA | ONEZONE_IA
INTELLIGENT_TIERING | GLACIER
DEEP_ARCHIVE

Invalid choice: 'GLACIER_IR', maybe you meant:

STANDARD | REDUCED_REDUNDANCY
STANDARD_IA | ONEZONE_IA
INTELLIGENT_TIERING | GLACIER
DEEP_ARCHIVE

GLACIER
```

**Logs/output**

```
Invalid choice: 'GLACIER_IR', maybe you meant:

STANDARD | REDUCED_REDUNDANCY
STANDARD_IA | ONEZONE_IA
INTELLIGENT_TIERING | GLACIER
DEEP_ARCHIVE

```

**Comment by stobrien89** [comment]
Hi @kjaercasper,

Thanks for pointing this out! I do see that S3 APIs accept this as an option now.  I'll see if I can get a fix out within the next week.
