### ISSUE TITLE
Create Grafana (AMG) APIs key over CLI 

### ISSUE THREAD

**Issue by zhang-hy-2016** [aws/aws-cli#6588]
**Is your feature request related to a problem? Please describe.**
I can't create an AMG API key(token) over AWS CLI,  at the moment I can only do this at Amazon Managed Grafana console,see  [AWS User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/Using-Grafana-APIs.html). 

**Describe the solution you'd like**
I can create AMG API key(token) over AWS CLI.

**Comment by kdaily** [comment]
Hi @zhang-hy-2016,

Thanks for your post. Unfortunately the Amazon Managed Grafana API only supports the following operations:

https://docs.aws.amazon.com/grafana/latest/APIReference/API_Operations.html

This would be a feature request for the Grafana team, which I will pass along, but until they support this in the API the AWS CLI (or other AWS SDKs) can't perform it.
