### ISSUE TITLE
AWS CLI call to create Aurora RDS Clone

### ISSUE THREAD

**Issue by CountryNerd** [aws/aws-cli#6589]
**Is your feature request related to a problem? Please describe.**
We use RDS Clone to create copies of our data from production to test every two weeks. So I want to script out the Clone creation. 

**Describe the solution you'd like**
To create an Aurora RDS Clone with an API call

**Comment by kdaily** [comment]
Hi @CountryNerd,

Thanks for the post. The Amazon RDS documentation describes in detail how to use the AWS CLI to perform a clone:

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Clone.html

There isn't a deep link, so you'll need to scroll down some to find the AWS CLI section.

Hope that answers your question! Let us know if you had something else in mind.
