### ISSUE TITLE
cp command does not put utf-8 characters

### ISSUE THREAD

**Issue by jvsteiner** [aws/aws-cli#6606]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
aws s3 cp --content-type "text/plain; charset=utf-8" source_file.txt s3://my-bucket/target_file.txt

fails to copy non-latin characters

**SDK version number**
2.4.5

**Platform/OS/Hardware/Device**
OSX 10.15.7  2019 macbook pro

**To Reproduce (observed behavior)**
command listed above, where source file contains some utf-8 text, for example:
sômé tēxt

**Expected behavior**
"sômé tēxt" to end up in the file in s3
what actually happened:
"s?m? t?xt" ended up in the file in s3

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
no errors

**Additional context**
I tried adding environment variables:
PYTHONIOENCODING=utf8
and
AWS_CLI_FILE_ENCODING=UTF-8
but it didn't help

**Comment by kdaily** [comment]
Hi @jvsteiner,

Thanks for the post. Looks like an issue with your local encoding. Can you show me the output of:

1. `file source_file.txt`
2. `locale`?

I get:

```
> file source_file.txt
test.txt: UTF-8 Unicode text
> locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by jvsteiner** [comment]
`./Users/jamie/.clipboard: ASCII text`
thats the source file - no idea why does it say ASCII - if you look at it, it displays the UTF-8 characters
`locale` yields
```LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by kdaily** [comment]
That's definitely the issue! Whatever tool you used to write that file saved it as ASCII. The CLI does not change the encoding. Make sure you save it as UTF-8 and everything should be good.

**Comment by jvsteiner** [comment]
Leaving a further comment in case it ends up being useful for others having this same problem.  In my case, I was running the `aws s3 cp` command as a part of a shell script that was being run by automator under OSX.  It turns out that such scripts do not inherit the users environment when executing.  It was necessary to add a line: `export LANG=en_US.UTF-8` to the automator script, prior to writing the file that I was trying to copy to s3, in order to make the encoding correct.
