### ISSUE TITLE
Key binding or encoding error on Windows 11

### ISSUE THREAD

**Issue by vectorkovacspeter** [aws/aws-cli#6609]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I use Windows 11 with latest update with Hungarian locale and keyboard settings. In aws cli with session manager the tab and arrow or even backspace key not working, there are cahrs appears when I use them. For example ^[OA or ^[OA for up/down arrows.
I try multiple terminal (Windows Terminal, cmd, mobaxterm, Ubuntu WSL) and evendocker image from amazon/awsci official all works the same, and also the browser based EC2 terminal.
The Pythond and the native windows wersions all do the same.

**SDK version number**
multiple for example: aws-cli/1.22.21

**Platform/OS/Hardware/Device**
multiple on Windows 11 on Dell laptop
WSL Ubuntu shell on Windows
Docker desktop

**To Reproduce (observed behavior)**
1. Install awscli from pip or windows exe
2. install session manager plugin from pop or windows exe
3. try to use arrow keys or tab or backspace

OR
1. from aws consolse open browser based session
2. try to use arrow keys or tab or backspace

**Expected behavior**
standard shell behaviour for example history autocomplete, etc.

**Logs/output**
no error

**Additional context**

**Comment by kdaily** [comment]
Hi @vectorkovacspeter,

Thanks for your post. Can you provide debug logs by adding `--debug` to your command so we can see what is being sent/received from the session manager plugin? Most likely this is an issue for the session manger, but this could help me verify.

Thanks!

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a long time I'm going to go ahead and close this. As mentioned above it sounds like this relates to the session manager, so the https://github.com/aws/session-manager-plugin repository is likely the better place for issues such as these.

**Comment by jmckenna** [comment]
Here, in 2025 :(

**Comment by jmckenna** [comment]
Update, make sure you use the switch `--command "/bin/bash"` and not `--command "/bin/sh"`, such as:
```
aws ecs execute-command --cluster <your-cluster> --task <your-task-ARN> --container <your-container-name>--command "/bin/bash" --interactive
```
