### ISSUE TITLE
project depending on graphql not building on amplify server but works fine when mocking

### ISSUE THREAD

**Issue by kjetilge** [aws/aws-cli#6610]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When deploying via git push the deployment halts at the Build stage

**SDK version number**
no sdk
**Platform/OS/Hardware/Device**
What are you running the cli on?
macos

**To Reproduce (observed behavior)**
in a fresh vue project:
amplify init
amplify add function
cd amplify/backend/api/MyFunction/scr/
yarn add graphqi
cd back to project root
git add/commit/push

**Expected behavior**
Project Should build withou problem

**Logs/output**
In the build section on the app deploment site:
```
There was an error initializing your environment.
2021-12-10T20:52:08.358Z [INFO]: [0mError: Packaging lambda function failed with the error [0m
                                 [0mCommand failed with exit code 1: yarn --production[0m
                                 [0merror graphql@16.1.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.16.0 || >=16.0.0". Got "12.21.0"
```

**Additional context**
My local node version is 16.0.0

**Comment by kdaily** [comment]
Hi @kjetilge,

Thanks for your post! Unfortunately you're looking for the AWS Amplify CLI, which you can find here to open an issue:

https://github.com/aws-amplify/amplify-cli/issues

Closing this out.
