### ISSUE TITLE
documented options of aws s3api list-object-versions bear no relation to available options.

### ISSUE THREAD

**Issue by jonseymour** [aws/aws-cli#6617]
**Describe the bug**

`aws s3api list-object-versions --bucket foo --key bar --profile  baz`

has documented options that don't work (--max-items), has undocumented options that do work (--max-keys) and has extremely misleading error messages when a documented option is used. Forcing the user to read 4 year old GitHub issue (#2555) to understand the root cause of these issues and how workaround them is hardly optimal user interface design.

```
$ aws s3api list-object-versions --bucket foo --key bar --profile  baz --max-items

Cannot specify --no-paginate along with pagination arguments: --max-items
```

Apparently `--max-items` is a valid pagination argument because this message says so and so to does the documentation

```
$ aws s3api list-object-versions help
SYNOPSIS
            list-object-versions
          --bucket <value>
          [--delimiter <value>]
          [--encoding-type <value>]
          [--prefix <value>]
          [--expected-bucket-owner <value>]
          [--cli-input-json | --cli-input-yaml]
          [--starting-token <value>]
          [--page-size <value>]
          [--max-items <value>]
          [--generate-cli-skeleton <value>]


```

But, no, the actual option to use is --max-keys which is not documented anywhere but in un-actioned 4-year old issue (#2555)

Since `--max-items` is no longer supported by this command, it should be removed from the documentation and `--max-keys` added in its place.

**SDK version number**

```
$ aws --version
aws-cli/2.3.6 Python/3.9.8 Darwin/21.1.0 source/x86_64 prompt/off
```

**Platform/OS/Hardware/Device**
OSX

**To Reproduce (observed behavior)**
```
$ aws s3api list-object-versions --bucket foo --key bar --profile  baz --max-items

Cannot specify --no-paginate along with pagination arguments: --max-items
```

Apparently --max-items is a valid pagination argument because this message says so and so to does the documentation

```
$ aws s3api list-object-versions help
SYNOPSIS
            list-object-versions
          --bucket <value>
          [--delimiter <value>]
          [--encoding-type <value>]
          [--prefix <value>]
          [--expected-bucket-owner <value>]
          [--cli-input-json | --cli-input-yaml]
          [--starting-token <value>]
          [--page-size <value>]
          [--max-items <value>]
          [--generate-cli-skeleton <value>]


```

**Expected behavior**

- Error message indicating --max-items is not a supported option
- Documentation which states that the supported option is (e.g. -max-keys) available  in the help of the command itself and not its issues log.
- Timely resolution of this issue so that people are not still flummoxed by it 4 years after it was first reported as an issue

**Logs/output**
As above.

**Additional context**
[The Design Of Everyday Things](https://www.amazon.com.au/Design-Everyday-Things-Revised-Expanded/dp/0465050654), Donald Norman

**Comment by jonseymour** [comment]
I stumbled across the actual problem. 

`--max-items` is supported as per the documentation but only if you use the documented `--prefix` option and not if you use the undocumented (but apparently still supported) `--key` option.

I am not quite sure that the `--key` option does  Either the `--key` option should be documented or support for the '--key` option be removed.  If the `--key` option is meant to do the same thing as `--prefix` then it should support the --max-items option too.

**Comment by tim-finnigan** [comment]
Hi @jonseymour, thanks for reaching out. I agree that the documentation should be updated to address this. It was brought up not just in https://github.com/aws/aws-cli/issues/2555 but also more recently in https://github.com/aws/aws-cli/issues/5616. I think [this comment](https://github.com/aws/aws-cli/issues/2555#issuecomment-295825435) still provides the best explanation of why this occurs. 

This could potentially be documented somewhere like [here in the User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html) so that users don’t have to track down an old issue in GitHub as you mentioned. I’m going to resolve this as a duplicate and we can use the existing issues for tracking and discussion.
