### ISSUE TITLE
python3, list-object-versions -> got an error: 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by kisscelia** [aws/aws-cli#6618]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [√] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [√] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
same to the title

**SDK version number**
python3.8.x

**Platform/OS/Hardware/Device**
Centos 7.9

**To Reproduce (observed behavior)**
![1639646886(1)](https://user-images.githubusercontent.com/13063673/146345256-822fcb57-4ee0-442f-a514-925a9d3fb9c1.jpg)

**Expected behavior**
can list object versions.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
It's fine when i use python2 (centos default)

**Comment by kdaily** [comment]
Hi @kisscelia,

Thanks for the post and sorry to hear you're having an issue. Is the endpoint you're using provided by AWS S3, or is it a third party implementation?

**Comment by kisscelia** [comment]
Hi, @kdaily ,
Thanks for your reply.
It's a third party implementation. a ceph cluster on my local servers.
I got the right response via awscli(python2) which i installed by pip, the same way.
![58520965a2f5cca0722896affce782d](https://user-images.githubusercontent.com/13063673/146475679-a7e58a72-1995-4b67-8df4-db30ed3b3ea5.png)

Thanks.

**Comment by kdaily** [comment]
Hi @kisscelia, I'm sorry to inform you that this looks like a third party issue with Ceph not implementing their S3 API to the same specifications as the AWS API. Unfortunately we do not provide support for other implementations of the S3 API. This is a common occurrence that you'll need to communicate with Ceph maintainers. You can see here for previous issues where Ceph does not implement the same specification:

- https://github.com/aws/aws-cli/issues/6568
- https://github.com/aws/aws-cli/issues/6459
- https://github.com/aws/aws-cli/issues/5908
- https://github.com/aws/aws-cli/issues/4268

If you provide a log (adding `--debug` flag to your command) I can try to provide some guidance on what you'll need to discuss with Ceph, but it looks like the response coming back from the request is not coming in the structure we expect.

**Comment by kisscelia** [comment]
Hi, @kdaily 
Thank you.

**Comment by kisscelia** [comment]
Hi, @kdaily 

I update my awscli, now my version is:
aws-cli/2.4.6 Python/3.8.8 Linux/3.10.0-1062.el7.x86_64 exe/x86_64.centos.7 prompt/off

It's ok. 

Thanks.
