### ISSUE TITLE
beanstalk --info-type undocumented?

### ISSUE THREAD

**Issue by lashex** [aws/aws-cli#662]
Hello I was poking around the beanstalk section of this CLI and I found the ``request-environment-info`` and ``retrieve-environment-info`` commands very un-clear. Specifically I keep getting an error when running either as follows:
````
$ aws elasticbeanstalk request-environment-info --environment-name worker-env
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument --info-type is required
````
...but for the life of me I cannot find out what ``--info-type`` actually expects as a value. I tried using a name space, but had no luck:
````
$ aws elasticbeanstalk retrieve-environment-info --environment-name worker-env --info-type aws:elasticbeanstalk:container:python
A client error (InvalidParameterValue) occurred when calling the RetrieveEnvironmentInfo operation: Key: aws:elasticbeanstalk:container:python in path: aws:elasticbeanstalk:container:python does not exist
````

**Comment by JordonPhillips** [comment]
This is now properly documented in our docs, so I'm gonna close it out.
