### ISSUE TITLE
"aws <command>" does not return expected result

### ISSUE THREAD

**Issue by MortalConfucious** [aws/aws-cli#6627]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
windows
**Describe the question**
Post installation of awscli2, noticed that commands like "aws --version" or "aws configure" can be run successfully.
However, while running any other aws command, let's say "aws help" or "aws iam list-users", get an exception "'more' is not recognized as an internal or external command, operable program or batch file".

This seems to me strange as "PATH" is already configured and "aws --version" seems to be recognized. Anything I'm missing out?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
![image](https://user-images.githubusercontent.com/22875852/147358226-55d9be44-aa77-4bda-a564-25bda8b785e6.png)

**Comment by MortalConfucious** [comment]
It was resolved after I run the "cmd" with elevated privileges. Still intrigued!!

**Comment by hbaghramyan** [comment]
Run msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi on PowerShell (or now it is called terminal). Beware, you must have "C:\Windows\System32" in your environmental variables, otherwise, this won't work. After that, it runs on Powershell and CMD without admin rights.
