### ISSUE TITLE
Allow AWS CLI cache location to be modified by an ENV var

### ISSUE THREAD

**Issue by Volatus** [aws/aws-cli#6628]
**Is your feature request related to a problem? Please describe.**
Currently the cache of cli ends up in `$HOME/.aws/cli/cache` and there is no way to modify this behavior. It'd be nice to have control over this similar to `AWS_CONFIG_FILE` environmental variable for example.

**Describe the solution you'd like**
Allow controlling this behavior with a variable like `AWS_CACHE_FILE` or something similar.

I'd be willing to work on this patch myself if any contributors/maintainers can point me to the part of the codebase that's likely controlling this behavior.

**Comment by kdaily** [comment]
Hi @Volatus,

Looks like this is a duplicate of https://github.com/aws/aws-cli/issues/1804. If you can provide any more details of your use case as to why this would be a desirable change on that issue, it would be greatly appreciated. You can also express your interest for that feature by adding a 👍🏻 reaction to the initial issue comment.

Thanks!
