### ISSUE TITLE
SSM - Node Name exists in the Console but not in the CLI?

### ISSUE THREAD

**Issue by Beinish** [aws/aws-cli#6638]
Confirm by changing [ ] to [x] below:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [X] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Windows 10**

I've noticed that SSM implemented a few new features, especially the way fleet manager shows my instances now. One of the new things I noticed is that I have a column that is called `node name`, which is different from what I was using up until now which was `computer name`.

I have a script that relies on "computer name". It deletes the FQDN and only leaves the real name of the host. So node name would show `server1` but computer name would show `server1.domain.com`.

There's a weird bug that sometimes a hostname of one of my instances is changed to `ip-10-10-110-59` for example. It usually happens when the node is moved to different hardware in AWS. It messes up my script because that node will not be shown as `server1.domain.com` under my SSM fleet manager anymore. Instead, it would be shown as that `ip-10-10-110-59.domain.com` until I manually fix it.

I checked the [docs](https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-instance-information.html) and didn't find `node name` as a possible response for the `describe-instance-information` function.

I'm new to AWS and was wondering if this is normal. Do these things take time to be implemented or am I missing something?

Thanks

**Logs/output**
Running `describe_instance_information` on a certain instance returns:

```
{'InstanceId': 'i-03ce1a534f0d11111', 'PingStatus': 'Online', 'LastPingDateTime': datetime.datetime(2022, 1, 5, 12, 36, 24, 50000, tzinfo=tzlocal()), 'AgentVersion': '3.1.715.0', 'IsLatestVersion': True, 'PlatformType': 'Linux', 'PlatformName': 'Amazon Linux', 'PlatformVersion': '2', 'ResourceType': 'EC2Instance', 'IPAddress': '10.10.10.10', 'ComputerName': 'computer.domain.com', 'AssociationStatus': 'Success', 'LastAssociationExecutionDate': datetime.datetime(2022, 1, 5, 5, 58, 43, 492000, tzinfo=tzlocal()), 'LastSuccessfulAssociationExecutionDate': datetime.datetime(2022, 1, 5, 5, 58, 43, 492000, tzinfo=tzlocal()), 'AssociationOverview': {'DetailedStatus': 'Success', 'InstanceAssociationStatusAggregatedCount': {'Success': 2}}}
```
Same as the docs, no `node name` attribute is returned.

**Comment by tim-finnigan** [comment]
Hi @Beinish, thanks for reaching out. I’m not sure which new features SSM has added, but they shouldn’t have changed existing API behavior as that would cause backwards compatibility issues.

There is a distinction between `ComputerName` and `Name`. But `Name` would not be returned if it doesn’t exist, and this was also discussed here in an older issue:  https://github.com/aws/aws-cli/issues/2278.

The InstanceInformation API Reference gives some more detail: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_InstanceInformation.html

>**ComputerName**
>The fully qualified host name of the managed node.
>
>**Name**
>The name assigned to an on-premises server, edge device, or virtual machine (VM) when it is activated as a Systems Manager managed node. The name is specified as the `DefaultInstanceName` property using the `CreateActivation` command. It is applied to the managed node by specifying the Activation Code and Activation ID when you install SSM Agent on the node, as explained in Install SSM Agent for a hybrid environment (Linux) and Install SSM Agent for a hybrid environment (Windows). To retrieve the `Name` tag of an EC2 instance, use the Amazon EC2 `DescribeInstances` operation. For information, see `DescribeInstances` in the Amazon EC2 API Reference or `describe-instances` in the AWS CLI Command Reference.

Does that help? Please let me know if you have any follow up questions.

**Comment by Beinish** [comment]
Thanks @tim-finnigan,
I've been using SSM for a couple of months now, and when I was referring to "new features" I meant that the console now shows a `Node Name` column, whereas not long ago it didn't exist. [Here's a screenshot](https://i.imgur.com/XbZNrln.png).

As you can see, in the screenshot I can see `Computer name` and `Node name`. I was wondering if the API will allow getting that `Node name` because it shows the name of the host, instead of the FQDN.

Also, as you can see in the screenshot, the `Computer name` field shows the real hostname of the instance in AWS(?), which only happens sometimes when I move instances to different hardware for example. The `Node name` remains true, and I was wondering if I can use that attribute in the CLI.

Maybe that what you were referring to in that quote, but I wasn't 100% sure :)

**Comment by tim-finnigan** [comment]
Hi @Beinish, thanks for following up. I’m not sure when Node name was added, but you can customize which columns are shown by clicking on the gear icon just above the table. It’s possible that the Node name column was an option before but now is displayed by default.

The Node name reflects the Name tag value given to your EC2 instance. (Different than the Name value referenced earlier from documentation). But if you want to get that name value, you could use the [describe-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) command and filter like this:

```
 aws ec2 describe-instances \
 --filters Name=instance-state-name,Values=running \
 --query 'Reservations[*].Instances[].[InstanceId, BlockDeviceMappings[*].{DeviceName:DeviceName,VolumeName:Ebs.VolumeId}, Tags[?Key==`Name`]]'
```

Then you could filter by name value with this command:
```
aws ssm describe-instance-information --filters "Key=tag:Name,Values=your_node_name"
```
