### ISSUE TITLE
ssl validation failed

### ISSUE THREAD

**Issue by mudasirnazir** [aws/aws-cli#6641]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
ssl validation failed for https:// monitoring.ap-southeast-1.amazonaws.com

**SDK version number**

**Platform/OS/Hardware/Device**
Windows

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by tim-finnigan** [comment]
Hi @mudasirnazir, thanks for reaching out. This issue looks similar to this other one you opened recently: https://github.com/aws/aws-cli/issues/6639

We still need some more information there in order to help. We can follow up in that issue. Please let us know if you have any questions.
