### ISSUE TITLE
send-ssh-public-key incorrectly recognises the public key length as 38 bytes, when it is 4096 bytes

### ISSUE THREAD

**Issue by yaz29** [aws/aws-cli#6654]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
aws ec2-instance-connect send-ssh-public-key incorrectly recognises the public key length as 38 bytes, when it is 4096 bytes

**SDK version number**
aws-cli/2.4.10 Python/3.8.8 Darwin/21.2.0 exe/x86_64 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?
MAC OS Monterey 12

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
aws ec2-instance-connect send-ssh-public-key --instance-id "$(aws ec2 describe-instances --filters "Name=tag:Name,Values=bastion-ssm" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[*].[InstanceId]' --output text)" --availability-zone eu-west-1a --instance-os-user ssm-basic --ssh-public-key file:/.ssh/id_rsa.pub

Parameter validation failed:
Invalid length for parameter SSHPublicKey, value: 38, valid min length: 256

**Expected behavior**
I expect my public key to be successfully pushed to the EC2 instance.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
The only similar issues I could find are not related to SSH key length:

#2338
#2337
#5132

**Comment by kdaily** [comment]
Hi @yaz29,

Thanks for your post. You're missing a slash in the file path; `file:/.ssh/id_rsa.pub` should be `file://.ssh/id_rsa.pub`.

Can you reproduce when changing that? Also, can you reproduce if you provide contents of the file as a string?

You can read more about providing parameters via file contents [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-file.html#cli-usage-parameters-file-how).

If you are still experiencing an issue, please provide the output with `--debug` added, and redact any sensitive material. Thanks!

**Comment by yaz29** [comment]
Thank you very much… I didn’t see it.

**Comment by kdaily** [comment]
You're welcome! Please do let us know if you have any more problems by opening a new issue.

**Comment by Dadapeer777** [comment]
│ Error: importing EC2 Key Pair (Dadapeer-west): operation error EC2: ImportKeyPair, https response error StatusCode: 400, RequestID: ad09e83e-9ece-4aea-8356-1282a5223046, api error InvalidParameterValue: Value for parameter PublicKeyMaterial is invalid. Length exceeds maximum of 2048.
│ Error: importing EC2 Key Pair (Dadapeer-west): operation error EC2: ImportKeyPair, https response error StatusCode: 400, RequestID: ad09e83e-9ece-4aea-8356-1282a5223046, api error InvalidParameterValue: Value for parameter PublicKeyMaterial is invalid. Length exceeds maximum of 2048.
