### ISSUE TITLE
v2 ses send-raw-email base64 error

### ISSUE THREAD

**Issue by ring-pete** [aws/aws-cli#6657]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I have an automation which utilizes the ses send-raw-email functionality.  The goal is to send a simple email (with no attachments) after a CI job has completed.  I have noticed recently sending emails have been failing due to an "Invalid base64" error.  Interestingly enough the same email will send without issues using v1 of the AWS CLI (v1.20.61).  Here is an example of the command we execute:

`aws ses send-raw-email --region us-east-1 --raw-message "{ \"Data\": \"From: operations@mycorp.com\nTo: operations@mycorp.com\nSubject: CI Report\n\nCI has completed for MyApp.\nSee s3://mycorp/myapp/test-results/ for full test results.\n\n\" }"`

This will result in an error similar to:
```
Invalid base64: "From: operations@mycorp.com
To: operations@mycorp.com
Subject: CI Report

CI has completed for MyApp.
See s3://mycorp/myapp/test-results/ for full test results.

"
```

As I mentioned it's a bit of a head scratcher since this was working as recently as a month ago using the v2 CLI, and I can run this using the v1 CLI without issues.

**SDK version number**
aws-cli/2.2.0

**Platform/OS/Hardware/Device**
CircleCI
Python/3.8.8 Linux/5.4.0-1021-gcp exe/x86_64.ubuntu.20

**To Reproduce (observed behavior)**
Try to run the above ses command using the v2 CLI

**Expected behavior**
ses email is sent successfully

**Comment by kdaily** [comment]
Hi @ring-pete,

Thanks for your post, sorry to hear you're having an issue!

My first thought of the difference between the AWS CLI v1 and v2 is this change:

https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam

Can you confirm that you didn't change the CLI version you noted (2.2.0)?

I think I'll need to see debug logs, can you add `--debug` to your command and post the output? Please redact any sensitive information.

Thanks!

**Comment by ring-pete** [comment]
Hey there @kdaily thanks for the response and pointing me to that documentation I had missed that.  I am now less sure that this was working prior to 2.2.0 to be honest.  I am going to to put some cycles into seeing what changes i need to make to get this working with the v2 API.

If i'm successful I'll close out this ticket, if I still suspect something funky is happening I'll be sure to post some debug info.

cheers!

**Comment by ring-pete** [comment]
This is indeed due to the aforementioned breaking change in v2.  As described in the link @kdaily provided above one can revert to the old behavior by passing: `--cli-binary-format raw-in-base64-out` to awscli.  This is an OK fix until our code can be updated to properlly implement the v2 API.

Thanks again @kdaily!
-pete
