### ISSUE TITLE
`s3api head-object`  does not return proper error for unknown key

### ISSUE THREAD

**Issue by quiver** [aws/aws-cli#666]
This may not be an issue of `aws-cli` per se, but rather an issue of s3 api in general.

When you execute `s3api head-object` for unknown key, `aws` command just returns `client error (Unknown)`, which makes it difficult to track down the problem.
s3 server returns `404` http status for `HEAD`, but response body is empty.

For comparison, `s3api get-object-acl` returns `A client error (NoSuchKey)` for such case and error message is included in xml formatted response body..

Demonstration(removing unrelated parts)

```
$ aws s3api head-object --bucket my-bucket-name --key unknwon-key  --debug
...
2014-02-22 14:16:49,204 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "HEAD /data/std.pn HTTP/1.1" 404 0
2014-02-22 14:16:49,205 - botocore.response - DEBUG - Response Headers:
x-amz-id-2: cbPyjTjNGQ0bXHi54ZtkarD9yd2mLFsXZT1afXtlxcVtXpwIbqdhynigPOr+LTnS
server: AmazonS3
transfer-encoding: chunked
x-amz-request-id: E965558DECC7D101
date: Sat, 22 Feb 2014 05:16:25 GMT
content-type: application/xml
2014-02-22 14:16:49,206 - botocore.response - DEBUG - Response Body:

...
2014-02-22 14:16:49,207 - awscli.errorhandler - DEBUG - HTTP Response Code: 404
...
2014-02-22 14:16:49,209 - awscli.clidriver - DEBUG - Exiting with rc 255
A client error (Unknown) occurred when calling the HeadObject operation: Unknown
```

**Comment by jamesls** [comment]
This is fixed now in the latest version of the CLI (looks like we forgot to link the fix with this issue):

```
$ aws s3api head-object --bucket mybucket --key bar.txt

A client error (404) occurred when calling the HeadObject operation: Not Found
```

The issue here is that this is a HEAD request, which does not contain a response body.  In these scenarios we just use the status code message as the error message as shown above.

**Comment by pranavgarg** [comment]
usually in my case what was happening was there was an extra slash in the front of the key which was causing this issue. Fixing the key name helped overcome this issue
