### ISSUE TITLE
Can you explicitly tell the awscli to ignore the AWS_PROFILE var when executing the CLI from the command line?

### ISSUE THREAD

**Issue by clanesf** [aws/aws-cli#6677]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
Centos/Linux/K8s/Cloud

**Describe the question**
Ran into this and had a question/feature request.. is there any way to override the AWS_PROFILE value in the CLI to tell it to *not* use a profile. Something like `aws --no-profile` or even honoring `aws --profile=''`.

In my case AWS credentials are set via environment variables in one environment only, and it would be nice to have a way to not have the cli crash if for whatever reason the AWS_PROFILE is set (i.e. to `default`)

I was able to workaround this by stubbing in a ~/.aws/config with 
```
[default]
output=json
```
but touching the file system inside k8s containers isn't as easy as setting an ENV.

My code caused the `AWS_PROFILE` to be set, so the fix is easy -  you can just `unset AWS_PROFILE`, but It would be nice to have the option to explicitly exclude the profile or an option to define the profile _contents_ via an environment variable. 

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

UPDATE:  did a little more digging around and it looks like there has been [discussion](https://github.com/aws/aws-cli/issues/3304)  about when to honor the profile environment and when to honor the CLI argument. 
That might make this "asked and answered"

**Comment by tim-finnigan** [comment]
Hi @clanesf, thanks for reaching out. I think this was addressed to some extent in https://github.com/aws/aws-cli/issues/3304 as you suggested. Specifically with comments [here](https://github.com/aws/aws-cli/issues/3304#issuecomment-388943032) and [here](https://github.com/aws/aws-cli/issues/3304#issuecomment-447509183). And this [documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#id1) provides more context around the credential precedence.

But there is another feature request (https://github.com/aws/aws-cli/issues/3875) that seems to overlap with yours: 

> the use case I'm trying to support is an automated process (or individual end user) that does not want to (or cannot) keep the AWS credentials in a plaintext file and instead needs to put them into temporary environment variables. 

I’m going to close this in favor of that open request but please let us know if there are any distinctions you want to clarify.
