### ISSUE TITLE
how to optimize cli performance for uploading many small files

### ISSUE THREAD

**Issue by satra** [aws/aws-cli#6682]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [X] Service API : I want to upload large directories of small files using s3 service, what should I do?
- [X] CLI : no additional parameters other than default and a specific profile
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
$ aws --version
aws-cli/2.4.15 Python/3.8.8 Linux/5.4.0-77-generic exe/x86_64.ubuntu.20 prompt/off

Ubuntu 20.04.2/Intel(R) Xeon(R) Gold 6258R CPU @ 2.70GHz 2x / 112 cores with hyperthreading

**Describe the question**
I'm trying to optimize the upload of zarr datasets to s3. each dataset contains anywhere from 200k - 800k files of size 40K each. when using aws s3 sync or cp i get a throughput close to 1 MiB/s. this pipe can get up to 120 MiB/s for large file transfers to s3 (the outer pipe is a 10G link). we are trying to estimate best case performance of the CLI,  before embarking on other options. i've tried various settings of the parameters belong, including this crazy one, but almost all are suspiciously close to 1MiB/s.

```
s3 =
  max_concurrent_requests = 1000
  max_queue_size = 100000
```

in addition the summary line of the upload display will constantly drop down to 0 items remaining every few seconds or so. i have tried this upload from two separate clusters and network uplinks and the bandwidth usage is quite similar.

as a somewhat unfair comparison, tarring the directory to create a 13G file and uploading it on a system with a 10G shared pipe gets me up to 150MiB/s
```
$ aws s3 cp test.tar s3://<bucket>/test
Completed 10.2 GiB/12.3 GiB (154.6 MiB/s) with 1 file(s) remaining
```
however the directory-based upload doesn't cross 2 MiB/s. overall tar + upload is many orders of magnitude faster. what i haven't done is to see how long "untarring" (i.e unpacking into keys) in s3 space takes.

**Comment by tim-finnigan** [comment]
Hi @satra, thanks for reaching out. There are a few premium support articles on this topic that might help:

https://aws.amazon.com/premiumsupport/knowledge-center/s3-improve-transfer-sync-command/
https://aws.amazon.com/premiumsupport/knowledge-center/s3-optimize-transfer/
https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-sync-instance-bucket/

Do you have any updates on what you’ve tried doing?

**Comment by satra** [comment]
@tim-finnigan - i've tried:

- changing `max_concurrent_workers`: 10 (default), 30, 50, 100, 200, 1000 (none of them seem to  make a huge difference)
- tried streaming from `/dev/shm` vs filesystem (not really different)
- uploaded tarred version (this 12GB upload went up at 140 MiB/s)
- checked dig configuration. drops to 0 ms after a couple of queries.

i've read through those posts. the third link is the closest, but none of them really look at uploading a large number of tiny files.

--> each dataset contains anywhere from 200k - 800k files of size 40K-150K each.

since we are trying to optimize uploading many small files, our team also wrote an api bandwidth tester. this uses 30 workers (concurrent futures ThreadPoolExecutor) to get 10k presigned urls from our api server and then upload 150KB each to each of those URLs. i have run 4 of these in parallel to max out the local machine and reach about 35 MB/s

```
$ python zarr_upload_benchmark.py 
Presigned in 6.20111870765686 seconds
Uploaded in 107.11597728729248 seconds
Finished in 107.57236075401306 seconds
13.944102272051712 MB/s
836.6461363231027 MB/min
```

we are also considering a tar like operation that uploads large files (which are efficient) and then "untar" on the s3 side using byte range copy into objects.

**Comment by tim-finnigan** [comment]
Hi @satra, thanks for following up. Could you tell us more about how you are measuring network throughput?  I’m curious if you’ve tried any third party tools for Linux to measure this and if so which ones. Also have you tested the tarring/untarring approach yet?

**Comment by satra** [comment]
@AlmightyYakob - since you did the packing/unpacking experiment, do you want to briefly state the results here?

**Comment by AlmightyYakob** [comment]
*Preface: All of these tests were conducted in a `c5n.9xlarge` EC2 instance.*

The results for the tar/untar process (although tar itself wasn't used, it was just file concatenation) are as follows:

**Uploading a 10GB file with 50 threads:**
* Total time taken: 60.6492 s
* Time spent transferring bytes to S3: 59.9925 s
* Overall MBit/s: 1319.0617
* Transfer MBit/s: 1333.5003

**Splitting up a 10GB file into 65,105, 150KB parts using 50 threads:**
* Total time taken: 809.0153 s (13.5 min)
* Average time total per part: 0.6150 s
	* Average time spent creating uploads: 0.1655 s
	* Average time spent copying parts: 0.2232 s
	* Average time spent completing uploads: 0.2263 s

**Splitting up a 10GB file into 2000, 5MB parts using 50 threads:**
* Total time taken: 22.5s
* Average time total per part: 0.5s
	* Average time spent creating uploads: 0.097s
	* Average time spent copying parts: 0.27s
	* Average time spent completing uploads: 0.145s

**Splitting up a 10GB file into 255, ~40MB parts using 50 threads:**
* Total time taken: 4.8s
* Average time total per part: 0.82s
	* Average time spent creating uploads: 0.074s
	* Average time spent copying parts: 0.66s
	* Average time spent completing uploads: 0.094s

**Comment by satra** [comment]
thank you @AlmightyYakob

**Comment by tim-finnigan** [comment]
Thanks for providing those data points. There are several factors that could affect the transfer rate between S3 and an EC2 instance as noted [here](https://aws.amazon.com/premiumsupport/knowledge-center/s3-maximum-transfer-speed-ec2/):

> * The AWS Regions that the instance and S3 bucket are in.
> * The medium of data transfer, such as a transfer through the internet or an Amazon Virtual Private Cloud (Amazon VPC) endpoint.
> * The size of objects to be transferred.
> * The resource utilization, CPU utilization, memory, disk I/O, network capabilities, and network limits of the EC2 instance.

And [here](https://aws.amazon.com/premiumsupport/knowledge-center/s3-transfer-data-bucket-instance/) are some recommendations for improving the transfer speeds between EC2 and S3:

> - Use enhanced networking on the EC2 instance.
> - Use parallel workloads for the data transfer.
> - Customize the upload configurations on the AWS Command Line Interface (AWS CLI).
> - Use an Amazon Virtual Private Cloud (Amazon VPC) endpoint for Amazon S3.
> - Use S3 Transfer Acceleration between geographically distant AWS Regions.
> - Upgrade your EC2 instance type.
> - Use chunked transfers.

I’m curious to know which of these you’ve tried and how well they have worked for you.
