### ISSUE TITLE
aws eks update-kubeconfig creating config in the wrong place? 

### ISSUE THREAD

**Issue by toast-gear** [aws/aws-cli#6688]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [x] Other/Not sure.

**Platform/OS/Hardware/Device**
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ aws --version
aws-cli/2.4.15 Python/3.8.8 Linux/5.11.0-1028-aws exe/x86_64.ubuntu.20 prompt/off
```

**Describe the question**
When I run `aws eks update-kubeconfig --region %MY_REGION% --name %MY_NAME%` my config is being created in `/var/lib/kubectl/kubeconfig` and then being symlinked to my users `~/.kube/config` directory. As a result the command fails because `/var/lib` is owned by `root root` which my user isn't a member of meaning they can read the file but not write to it.

**Logs/output**
```
$ ls -al /home/ubuntu/.kube/config
lrwxrwxrwx 1 ubuntu ubuntu 27 Feb  1 06:47 /home/ubuntu/.kube/config -> /var/lib/kubelet/kubeconfig
$ ls -al /var/lib/kubelet/kubeconfig
-rw-r--r-- 1 root root 1158 Feb  1 06:47 /var/lib/kubelet/kubeconfig
```

I'm currently struggling to understand _why_ it's doing this. https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/update-kubeconfig.html the docs don't mention anything about aws eks symlinking.

**Comment by tim-finnigan** [comment]
Hi @toast-gear thanks for reaching out. I tried to reproduce this on Ubuntu 20.04.3 but was not able to:
```
$ ls -al /home/ubuntu/.kube/config 
-rw------- 1 ubuntu ubuntu 2249 Feb 3 19:57 /home/ubuntu/.kube/config 
$ ls -al /var/lib/kubelet/kubeconfig 
ls: cannot access '/var/lib/kubelet/kubeconfig': No such file or directory
```
Is it possible that  /var/lib/kubelet/kubeconfig was previously set? If you could provide the debug logs by adding `--debug` to your command that might give us more insight into what’s going on.

**Comment by toast-gear** [comment]
short stale bot! :D

`--debug` didn't help really, it just 

```
2022-02-11 17:26:28,838 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/customizations/eks/kubeconfig.py", line 196, in write_kubeconfig
  File "awscli/compat.py", line 154, in compat_open
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/.kube/config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/clidriver.py", line 594, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/eks/update_kubeconfig.py", line 143, in _run_main
  File "awscli/customizations/eks/kubeconfig.py", line 200, in write_kubeconfig
awscli.customizations.eks.kubeconfig.KubeconfigInaccessableError: Can't open kubeconfig for writing: [Errno 13] Permission denied: '/home/ubuntu/.kube/config'

Can't open kubeconfig for writing: [Errno 13] Permission denied: '/home/ubuntu/.kube/config'
```

Any suggestions for how this might happen. We are building this packer image https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/images/ubuntu-focal/github_agent.ubuntu.pkr.hcl which is super duper vanilla so I am at a loss as to how this could happen.

**Comment by tim-finnigan** [comment]
Hi @toast-gear I think you may just need to grant write permissions for the user to write to `.kube/config`. Someone shared a similar issue/solution [here](https://github.com/kubernetes/minikube/issues/5714#issuecomment-549613134) that might help. Can you try that and let us know if that solves the issue for you?

**Comment by toast-gear** [comment]
Acknowledged
