### ISSUE TITLE
Add support for M1 Mac (Apple Silicon) with AWS CLI v2

### ISSUE THREAD

**Issue by sodul** [aws/aws-cli#6689]
**Is your feature request related to a problem? Please describe.**
When installing the latest version of the AWS CLI v2 the python interpreter that is bundled is the Intel version. This forces the user to install Rosetta, which works but is much slower than native and it will be removed by Apple in the future.

**Describe the solution you'd like**
The macOS version should either provide a universal binary, or provide two versions: amd64 vs arm64. Similar to what is provided for Linux.

**Describe alternatives you've considered**
Allowing v2 to be installed from pip would let the user re-use a native python interpreter, just like it is possible with v1. That is not a path that is considered by the project.

**Comment by tim-finnigan** [comment]
Hi @sodul thanks for reaching out. We have several [installation feature requests](https://github.com/aws/aws-cli/issues?q=is%3Aissue+is%3Aopen++label%3Ainstallation+label%3Afeature-request) open at the moment that overlap with your request. There is work actively being done on a source distribution and we will update those issues when that is ready.
