### ISSUE TITLE
S3 Select column names with numbers and special characters

### ISSUE THREAD

**Issue by rrs-bg** [aws/aws-cli#6697]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Hi, I have a csv file which I'm querying via s3 select, some of the columns in the file have special characters and start with a number, example columns: '500+','100-200', '<50'.

If I try to select these columns I get errors like:
An error occurred (ParseUnexpectedOperator) when calling the SelectObjectContent operation: Unexpected operator OPERATOR:UNKNOWN at line 1, column 8.

**SDK version number**
aws-cli/2.4.15

**Platform/OS/Hardware/Device**
Python/3.9.10 Darwin/20.4.0 source/x86_64

**To Reproduce (observed behavior)**
Upload a csv file with a column that starts with a number and has a special character like: '100+'.
Then try to select that column:
select 100+ from s3object limit 10

**Expected behavior**
Return the selected column

**Logs/output**

**Additional context**
I couldn't find answer to this in the docs, I understand this are weird column names, but if not possible it should be clearly stated in the docs what is a valid column name.

**Comment by kdaily** [comment]
Hi @rrs-bg,

Thanks for writing. Here's the docs on S3 Select that talks about column names. Can you try quoting them?

https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-glacier-select-sql-reference-select.html#s3-glacier-select-sql-reference-case-sensitivity

The AWS CLI is a wrapper around the API, and this error is coming back from the server side. I would try quoting, or open an AWS support case so the S3 team could take a look further. You might also get a faster response on the support for this on [repost.aws](https://repost.aws).
