### ISSUE TITLE
aws rds download-db-log-file-portion: 'charmap' codec can't encode characters in position ...

### ISSUE THREAD

**Issue by ecc256** [aws/aws-cli#6701]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
Found old issues only...
  
**Describe the bug**
`aws rds download-db-log-file-portion --db-instance-identifier abc --log-file-name audit/server_audit.log --output text 1>text.txt`
_results in_
`'charmap' codec can't encode characters in position 119315-119326: character maps to <undefined>`

**SDK version number**
```
aws --version
aws-cli/2.4.16 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
```
**Platform/OS/Hardware/Device**
What are you running the cli on?
```
AWS workspaces VM
OS: Windows Server 2019 Windows_NT x64 10.0.17763
```
**To Reproduce (observed behavior)**
Steps to reproduce the behavior
_I assume, run_ 
`aws rds download-db-log-file-portion `
_with UTF-8 characters in the log file_

**Expected behavior**
_It should be able to download log file.
Log content should be the same as when downloaded from AWS RDS portal._

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.
_It dumps downloaded file to screen and then throw error when saving it to the file..._

**Additional context**
_Nothing..._

**Comment by ecc256** [comment]
Tried both below separately and together - no difference:
`chcp 65001`
`set AWS_CLI_FILE_ENCODING=UTF-8`

**Comment by ecc256** [comment]
Although, it's aws cli v2, I've tried also:
`set PYTHONIOENCODING=UTF-8`
It didn't work, obviously...

**Comment by ecc256** [comment]
Just saw new version came out:
```
aws --version
aws-cli/2.4.17 Python/3.8.8 Windows/10 exe/AMD64 prompt/off
```
No luck, same error exactly...

**Comment by kdaily** [comment]
Hi @ecc256,

Looking into this. I think I'll need to see  the `--debug` logs to determine if it's happening because of file input/output or of characters trying to be displayed somewhere. For the latter, the solution has been to change the Windows system-wide encoding to UTF-8. See this similar issue:

https://github.com/aws/aws-cli/issues/4778

Please redact any sensitive information from the logs!

Have you tried (or could you try) with the AWS CLI v1 to see if it still occurs?

**Comment by ecc256** [comment]
I did open support case with AWS and they were able to reproduce it:

> 1. Created RDS DB instance 'mynewdb' with engine version- mysql:5.7.33.
> 2. Created option group with option 'MARIADB_AUDIT_PLUGIN'
> 3. Created a login with username - '汉字' and granted the permissions
> 
> CREATE USER '汉字'@'%' IDENTIFIED BY 'admin123';
> 
> Granted permissions to the new user -
> 
> GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO '汉字'@'%';
> 
> 4. Attempted to connect to the DB instance using the new user.
> 5. Tried to download the audit log file from my Laptop and received the same error -
> 
> C:\Users\subhnk>aws rds download-db-log-file-portion --db-instance-identifier mynewdb --starting-token 0 --output text --log-file-name audit/server_audit.log > C:\Users\subhnk\Desktop\Myfolder\tail.txt
> 
> 'charmap' codec can't encode characters in position 1323-1324: character maps to <undefined>
> 
> C:\Users\subhnk>aws rds download-db-log-file-portion --db-instance-identifier mynewdb --output text --log-file-name audit/server_audit.log > C:\Users\subhnk\Desktop\Myfolder\tail.txt
> 
> **'charmap' codec can't encode characters in position 1323-1324: character maps to <undefined>**

---------------------------------------------------
>For the latter, the solution has been to change the Windows system-wide encoding to UTF-8. See this similar issue:

I know, don't what to mess up my workstation, I have lots of work to do...
I wonder why it's not possible to switch single console window to support UFT-8 via
```
set AWS_CLI_FILE_ENCODING=UTF-8
chcp 65001
```
---------------------------------------------------
>Have you tried (or could you try) with the AWS CLI v1 to see if it still occurs?

Same actually, don't what to mess up my workstation...

**Comment by kdaily** [comment]
Hi @ecc256,

Unfortunately after the text is output as Unicode from the AWS CLI, we can't influence how the console interprets it. Windows does not have another way to force this change other than at the system level. Going to resolve this as there isn't anything for the AWS CLI to change and it's a known limitation of Windows.
