### ISSUE TITLE
Use AWS CLI to Execute Step Functions State Machines from a CDK Cloud Assembly

### ISSUE THREAD

**Issue by misterjoshua** [aws/aws-cli#6717]
**Is your feature request related to a problem? Please describe.**
When working on CDK apps, I often need to perform repetitive tasks to poke and prod the parts of my app. These tasks may include inserting an item into a queue, executing a lambda function with a given payload, putting an event into an event bus, starting a Fargate task from a task definition, or executing a state machine.

I can complete these repetitive tasks using the AWS Console, the AWS CLI, or the AWS SDK. But all cases require manual steps or code that discovers the names of resources in the stack to interact with them. However, these use cases can also be generalized into ASL definitions and run through AWS Step Functions State Machines.

For these tasks, I prefer to use Step Functions because I can define them inside small apps living next to whatever construct I'm working on at the time, they don't take much manual work to run, and they're comparatively low code compared to writing custom scripts to do the same. But, they could be more convenient to run if the AWS CLI provided a command that, given a Construct path in a CDK Cloud Assembly, could locate the appropriate physical resource for the State Machine and execute it.

**Describe the solution you'd like**
I'd like to execute Step Functions state machines in my app with the AWS CLI.

For the app below, the user could type `aws cdk --app cdk.out exec my-thing/TaskRunner` to execute the step function, which in turn executes a Fargate Task, exiting when the state machine execution finishes:

```ts
import { App, Stack } from 'aws-cdk-lib';
import { Cluster, ContainerImage, FargateTaskDefinition } from 'aws-cdk-lib/aws-ecs';
import { IntegrationPattern, StateMachine } from 'aws-cdk-lib/aws-stepfunctions';
import { EcsFargateLaunchTarget, EcsRunTask } from 'aws-cdk-lib/aws-stepfunctions-tasks';

const app = new App();
const stack = new Stack(app, 'my-thing');

const taskDefinition = new FargateTaskDefinition(stack, 'TaskDefinition', {
  cpu: 256,
  memoryLimitMiB: 512,
});

taskDefinition.addContainer('true', {
  image: ContainerImage.fromRegistry('bash'),
  command: ['true'],
});

const cluster = new Cluster(stack, 'Cluster');

// Execute this state machine by running `cdk exec my-thing/TaskRunner`
new StateMachine(stack, 'TaskRunner', {
  definition: new EcsRunTask(stack, 'EcsRunTask', {
    cluster,
    taskDefinition,
    launchTarget: new EcsFargateLaunchTarget(),
    integrationPattern: IntegrationPattern.RUN_JOB,
  }),
});

app.synth();
```

If the Step Function requires input, we could allow a command line argument `aws cdk --app cdk.out exec <path> --input "JSON HERE"`

**Describe alternatives you've considered**
I've considered implementing the same feature in the CDK, but there's some question as to whether this feature would be out of scope for the CDK. If it is out of scope for the CDK, then it seems that it should be in scope here. Otherwise, I'm not sure in which AWS product this capability should live.

The CDK counterpart to this issue is here: https://github.com/aws/aws-cdk/issues/18949

**Additional context**
A reference implementation is available for the CDK, in case it's useful when assessing the work required to implement this feature in the AWS CLI. https://github.com/aws/aws-cdk/pull/18954

**Comment by mrpackethead** [comment]
theres a 3rd option.. 

Its standalone.

**Comment by kdaily** [comment]
Hi @misterjoshua,

Thanks for the post. There currently is no support for anything within the AWS CLI for the AWS CDK, so this would be an entirely new feature or customization. I do not currently know what the correct scope of this feature would be (in the CDK CLI or the AWS CLI) either. I'll talk to one of my colleagues from the CDK team to understand the context better.

**Comment by misterjoshua** [comment]
For now I have released my own tool which runs state machines and lambdas as described in this issue.
 https://github.com/wheatstalk/aws-cdk-exec

**Comment by kdaily** [comment]
Hi @misterjoshua,

Looks like this got quite a bit of discussion over on the AWS CDK repository! I'm glad you posted it there as they have a better sense of this use case. Since it's being tracked there and given some attention, I don't think there's a place for it now in the AWS CLI, so I'm going to close this issue. Thanks!
