### ISSUE TITLE
Deployment fails after an initial success (ResourceConflictException)

### ISSUE THREAD

**Issue by TomerFi** [aws/aws-cli#6718]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

I deployed a _Java_ lambda function today from a CI process using:

```shell
aws lambda publish-version --function-name ...
```

This **worked well the first time**, later on, while deploying again, I received:

```shell
An error occurred (ResourceConflictException) when calling the PublishVersion operation: The operation cannot be performed at this time. An update is in progress for resource:...
```

I would like to emphasize that no modifications were done to the function sources after the first deployment,
I missed any documentation stating this might be a problem.

**SDK version number**
AWS CLI 2.4.16.

**Platform/OS/Hardware/Device**
Ubuntu 20.04.3 using [gh's runner](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md).

**To Reproduce (observed behavior)**
Deploy one time, later on, deploy again with no modifcations.

**Expected behavior**
I expected the deployment process to work well, as it did at the first attempt.

**Logs/output**
I'm deploying from a CI process,
please let me know if the `--debug` flag is required for this issue resolution,
if so I'll happily update my CI process and report back.

**Additional context**
I think the following issue https://github.com/claudiajs/claudia/issues/226 might be similar.

**Comment by TomerFi** [comment]
Adding information:
Before the failing:
```shell
aws lambda publish-version --function-name ...
```

I have a:
```shell
aws lambda update-function-code --function-name ...  --zip-file fileb://...
```

I noticed on another workflow run that this command also failed.

**Comment by tim-finnigan** [comment]
Hi @TomerFi thanks for reaching out. This looks similar to a recent issue: https://github.com/aws/aws-cli/issues/6585. I think [this comment](https://github.com/aws/aws-cli/issues/6585#issuecomment-983901394) may help clarify things. It references an [article](https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/) announcing changes to Lambda with this section worth noting:


> Nothing is changing about how functions are created, updated, or operate as part of this. However, this change may impact certain workflows that attempt to invoke or modify a function shortly after a create or an update action. Before making API calls to a function that was recently created or modified, confirm it is first in the Active state, and that the LastUpdateStatus is Successful.


Can you confirm that your Lambda function is first in the Active state and that the LastUpdateStatus is Successful?

**Comment by TomerFi** [comment]
@tim-finnigan 
This is the same issue I believe, I must have missed it, sorry for that!
