### ISSUE TITLE
describe-cache-clusters return data has no information about the primary endpoint

### ISSUE THREAD

**Issue by forhead** [aws/aws-cli#6732]
**Describe the bug**

I created an redis cluster(cluster model disabled), with zero shard and one node. I can see the primary endpoint from the console like 
 `s1.xxxxxx.0001.apse1.cache.amazonaws.com:6379`
but with the api call 
`aws elasticache   describe-cache-clusters --cache-cluster-id s1`
I get below output
`{
    "CacheClusters": [
        {
            "CacheClusterId": "s1",
            "ClientDownloadLandingPage": "https://console.aws.amazon.com/elasticache/home#client-download:",
            "CacheNodeType": "cache.r6g.large",
            "Engine": "redis",
            "EngineVersion": "6.2.5",
            "CacheClusterStatus": "available",
            "NumCacheNodes": 1,
            "PreferredAvailabilityZone": "ap-southeast-1a",
            "CacheClusterCreateTime": "2022-02-17T02:26:52.198000+00:00",
            "PreferredMaintenanceWindow": "wed:16:00-wed:17:00",
            "PendingModifiedValues": {},
            "CacheSecurityGroups": [],
            "CacheParameterGroup": {
                "CacheParameterGroupName": "default.redis6.x",
                "ParameterApplyStatus": "in-sync",
                "CacheNodeIdsToReboot": []
            },
            "CacheSubnetGroupName": "redis-az2-az3",
            "AutoMinorVersionUpgrade": true,
            "SecurityGroups": [
                {
                    "SecurityGroupId": "sg-0835c3ac726b2f12c",
                    "Status": "active"
                },
                {
                    "SecurityGroupId": "sg-ca4c9eb2",
                    "Status": "active"
                }
            ],
            "SnapshotRetentionLimit": 0,
            "SnapshotWindow": "18:30-19:30",
            "AuthTokenEnabled": false,
            "TransitEncryptionEnabled": false,
            "AtRestEncryptionEnabled": false,
            "ARN": "arn:aws:elasticache:ap-southeast-1:xxxxxxxxxxxx:cluster:s1"
        }
    ]
}
`
there's no output of the primary endpoint, also I tried another api 
`describe-replication-groups`
but get error like this:
`An error occurred (ReplicationGroupNotFoundFault) when calling the DescribeReplicationGroups operation: ReplicationGroup s1 not found`

so, is there a way to get the primary endpoint with aws cli? or this is an bug of the describe api call?
--
 

<br class="Apple-interchange-newline">

**SDK version number**
aws-cli/2.1.23 Python/3.7.4 Darwin/20.6.0 exe/x86_64 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?
macos

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
1. create an redis(cluster model disabled)
2. use aws elasticache describe-cache-clusters --cache-cluster-id id
3. get result but no information of the primary endpoint

**Expected behavior**
I want the return value has the information of the primary endpoint of the redis

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by tim-finnigan** [comment]
Hi @forhead thanks for reaching out. Here is some documentation on finding connection endpoints that might help: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html. It notes there:


> You can use the AWS CLI to discover the endpoints for a cluster and its nodes with the describe-cache-clusters command. For Redis clusters, the command returns the cluster endpoint. If you include the optional parameter --show-cache-node-info, the command will also return the endpoints of the individual nodes in the cluster.


Does that help? If you’re still having issues then providing the debug logs by adding `--debug` to your command would help give us more insight into this.
