### ISSUE TITLE
aws s3 slow upload/download speed for bigfiles 

### ISSUE THREAD

**Issue by royassis** [aws/aws-cli#6736]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
Using aws to upload/download big files  from s3 in same region utilizing <20% of ec2 bandwidth, up to 300mb/s. 

**SDK version number**
aws-cli/2.4.7 Python/3.8.8 Linux/5.4.0-1065-aws exe/x86_64.ubuntu.18 prompt/off

**Platform/OS/Hardware/Device**
 r5n.24xlarge

**To Reproduce (observed behavior)**
1. Create s3 bucket in region us-east1
2. Create ec2 instance of type  r5n.24xlarge in region us-east1.
3. Generate a big file (8gb) : `dd if=/dev/urandom of=bigfile bs=1024k count=8192`
4. Upload file to bucket `aws s3 cp bigfile s3://<bucket-name>/`

**Expected behavior**
Upload speed should be at least 90% of instance bandwith, (100Gb)

**Additional context**
* Tried debug the problem with this :https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-sync-instance-bucket/ - **same problem**
* Tried using the python client - **same problem**
* Tried using the java SDK- **solved problem**
* Tried rising the value of max_concurrent_requests to 1000 - **same problem**
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-where
* Splitting the file and using --recursive - **same problem**
* Splitting the file and using multiple instances of aws s3 cp - **solved problem**

**Comment by kdaily** [comment]
Hi @royassis,

Thanks for your post. I don't think you can expect the AWS CLI to be able to saturate a 100Gb connection; it is written in Python, which is single threaded. This indicates why splitting the file and running multiple calls to `aws s3 cp` would provide an increase in speed.

However, since you're using the AWS CLI v2, there is a new feature, currently in an experimental mode, that uses the AWS Common Runtime (`awscrt`) package to perform S3 operations. You can read more about that here:

- https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#preferred-transfer-client
- https://github.com/awslabs/aws-crt-python

In my test on the same instance using the CRT transfer client, I experienced 5-10x faster upload.

What speed did you get with the Java SDK transfer manager?

**Comment by royassis** [comment]
Hey @kdaily 

I it is suggested that the cli can upload files concurrently as written here :
https://aws.amazon.com/premiumsupport/knowledge-center/s3-multipart-upload-cli/

![image](https://user-images.githubusercontent.com/34189329/155304997-1f819f80-8bff-4619-8a44-224671edc73a.png)

Changing the value of this parameter in the config file did not influence the upload/download speed. 


Also
As for this documentation of boto3, uploading files with concurrent threads is supported. 
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html

![image](https://user-images.githubusercontent.com/34189329/155305519-e2f1b1eb-993b-4e8f-b082-e9f99c486f70.png)

This also did not influence upload/download speed.

Using the java cli I reached steady upload rates of 2.5Gbytes.

**Comment by kdaily** [comment]
Hi @royassis,

Yes give that a try! Please also bump up the `target_bandwidth` [parameter](https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#target-bandwidth) which defaults to 5Gb/s. Closing this as that's the preferred solution to increase the performance. I will review with the documentation team if this option should be added to the knowledge center article as well.

**Comment by kdaily** [comment]
Quick update. Using the following configuration, I was able to get 3GiB/s for a 300GB file:

```
[default]
s3 =
    preferred_transfer_client = crt
    target_bandwidth = 1000Gb/s
    multipart_chunksize = 16MB
```

**Comment by royassis** [comment]
Hey @kdaily 
Tried running with these parameters:

```
[default]
s3 =
    max_concurrent_requests = 3000
    preferred_transfer_client = crt
    target_bandwidth = 100Gb/s
```

For a 8.5GB files on a r5n.24xlarge instance type.

The rate (from the cli output) steadily increased from about 100MB/s to 500MB/s, I guess it could have gone further up if the file size was bigger. 
But oddly on consecutive runs the rate started from 1-1.6GB/s and dropped to 750-650MB/s and fluctuate a bit.

```
(scanpyEnv3.8) roya@IP172-30-3-148:~$ time aws s3 cp /tmp/bigfile_ultra_mega_super s3://{my-bucket}/bigfile_ultra_mega_super | tr '\r' '\n'
Completed 1.5 GiB/8.5 GiB (1.5 GiB/s) with 1 file(s) remaining
Completed 2.7 GiB/8.5 GiB (1.3 GiB/s) with 1 file(s) remaining
Completed 3.1 GiB/8.5 GiB (1.0 GiB/s) with 1 file(s) remaining
Completed 3.4 GiB/8.5 GiB (849.0 MiB/s) with 1 file(s) remaining
Completed 3.8 GiB/8.5 GiB (760.5 MiB/s) with 1 file(s) remaining
Completed 4.5 GiB/8.5 GiB (750.0 MiB/s) with 1 file(s) remaining
Completed 5.1 GiB/8.5 GiB (733.4 MiB/s) with 1 file(s) remaining
Completed 5.9 GiB/8.5 GiB (735.4 MiB/s) with 1 file(s) remaining
Completed 6.7 GiB/8.5 GiB (749.4 MiB/s) with 1 file(s) remaining
Completed 7.9 GiB/8.5 GiB (796.5 MiB/s) with 1 file(s) remaining
Completed 8.5 GiB/8.5 GiB (559.9 MiB/s) with 1 file(s) remaining
upload: ../../tmp/bigfile_ultra_mega_super to s3://1701-royassis-data-bucket/bigfile_ultra_mega_super

real    0m16.441s
user    0m9.424s
```


The total time was 15 seconds. Which is much better 

I'm adding some metrics from my instance, I'm collecting nbetwork_sent_bytes in a resolution of 1seconds to CloudWatch:

![image](https://user-images.githubusercontent.com/34189329/155408393-d1d97225-bd91-4f8b-b40c-1bcab980a38d.png)

These are the consecutive runs, you can see the rate is much faster : 

![image](https://user-images.githubusercontent.com/34189329/155408586-ed7c21ad-6ef6-4bfc-830c-6f373b6dd7b1.png)

But still a rate of 8.5GB/15seconds =~ 500MB/s

Which is  100/8GB/0.5GB = 25 slower then the maximal bandwith

Also take note that the cli rate output did not match the CloudWatch metrics.

**Comment by kdaily** [comment]
Hi @royassis,

The CLI rate is not calculated in the same way as CloudWatch - I would use whatever metric you're sending to CloudWatch (or a tool like `iftop` or `nload`) for a more accurate estimate - it's the ratio between the bytes transferred and the time elapsed:

https://github.com/aws/aws-cli/blob/4229ada0d374758f4f5d387d07928632bcaf0038/awscli/customizations/s3/results.py#L291-L292

However, an r5n.24xlarge has 100 Gbps (not GB/s, note); I tested again and the maximum throughput I saw was around 5.96GB/s (47 Gbps), which is almost half of the total bandwidth. I used `bwm-ng` to calculate. I did see some fluctuation, but a  30 average still was around 4.5 GB/s (35 Gbps).

**Comment by royassis** [comment]
Hey @kdaily 

Thank you for the examination. 

I managed to reach the bandwidth limit for the instance ~12GByte/second rate.
I issued 20 cli calls simultaneously.

**Comment by 0x-2a** [comment]
> [default]
> s3 =
>     max_concurrent_requests = 3000
>     preferred_transfer_client = crt
>     target_bandwidth = 100Gb/s
> ```

Worked through this lately, noticed that the "b" is case sensitive... this config worked better for me... I matched the chunksize/threshold and the max/target bandwidth.

```
aws configure set default.s3.max_concurrent_requests 3000
aws configure set default.s3.preferred_transfer_client crt
aws configure set default.s3.max_queue_size 10000
aws configure set default.s3.multipart_threshold 64MB
aws configure set default.s3.multipart_chunksize 64MB
aws configure set default.s3.max_bandwidth 10GB/s
aws configure set default.s3.target_bandwidth 10GB/s
```

**Comment by bryant1410** [comment]
> I don't think you can expect the AWS CLI to be able to saturate a 100Gb connection; it is written in Python, which is single threaded.

@kdaily do you think it's possible that the AWS CLI would one day support process (and thread) parallelism? Like `gsutil` does.
