### ISSUE TITLE
Query awscliv2 version

### ISSUE THREAD

**Issue by MrAtheist** [aws/aws-cli#6737]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [ ] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
- doesnt matter

**Describe the question**

Building on top of this [thread](https://github.com/aws/aws-cli/issues/4971#issuecomment-624543620), i would like a programmatic way to query the cli version provided by `https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip` (even though im guessing it's supposed to be the latest...) to build out a docker tag. Is there such an API for this?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by kdaily** [comment]
Hi @MrAtheist,

Thanks for the post. The methods to determine the version are either use `aws --version` after the CLI is installed, or check the available or latest tags on the GitHub repository, and use it to download a specific artifact by appending the version number to the file name, like https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.4.1.zip.

There's an open feature request at https://github.com/aws/aws-cli/issues/5471 to be able to use the GitHub latest release feature to query for the most recently published tag or release, which would allow you to get the version.

We also publish our own Dockerfile for the AWS CLI v2 that you could build off of:

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-docker.html

If you're building your own container image, you might be interested in the source distribution for AWS CLI v2 as well, work is ongoing for this:

https://github.com/aws/aws-cli/pull/6352

**Comment by MrAtheist** [comment]
Format like `https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.4.1.zip` works for me, or maybe i can query from 
`https://api.github.com/repos/aws/aws-cli/tags` to grab the latest tag as mentioned in https://github.com/aws/aws-cli/issues/5471

Closing this in favor of https://github.com/aws/aws-cli/issues/5471
