### ISSUE TITLE
s3 subcommand has nebulous error message on some buckets

### ISSUE THREAD

**Issue by mwhooker** [aws/aws-cli#674]
On some buckets (specifically with dots in them), doing `aws s3 ls s3://com.blah/foo` returns this error

`A client error (PermanentRedirect) occurred when calling the ListObjects operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

It would be handy if it told me what the specified end was

**Comment by JordonPhillips** [comment]
I think this can safely be closed. As @kyleknap pointed out, it's probably just an issue where the region of the bucket needs to be specified due to the bucket's incompatibility with the DNS resolver.
