### ISSUE TITLE
Different result from cli commands when using against different Auto sacling groups

### ISSUE THREAD

**Issue by dragonfly8391** [aws/aws-cli#6741]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X ] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**

Different result from cli commands when using against different Auto sacling groups

**SDK version number**
 aws-cli/2.1.36 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?
windows/Mac

**To Reproduce (observed behavior)**
Steps to reproduce the behavior
running the command:
aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[? TargetGroupARNs [? contains(@, '\''arn:aws:elasticloadbalancing:eu-west-1:11111111:targetgroup/xxx-xxx-blue-api/xxxxxxx'\'')]].AutoScalingGroupName' --output text --region eu-west-1

the output is multi-line 
xxx-xxx-blue-api/api
xxx-xxx-blue-api/api_al2

however the Json output of the same command is flat (one []) so the output should be single line.

[ "xxx-xxx-blue-api/api",
"xxx-xxx-blue-api/api_al2"
]

**Expected behavior**
The expected behavior is a single line output 
xxx-xxx-blue-api/api  xxx-xxx-blue-api/api_al2

**Comment by kdaily** [comment]
Hi @dragonfly8391,

This is expected behavior and is due to the differences in how queries are applied to text output and JSON output, explained here:

https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side


> - If you specify --output text, the output is paginated before the --query filter is applied, and the AWS CLI runs the query once on each page of the output. Due to this, the query includes the first matching element on each page which can result in unexpected extra output. To additionally filter the output, you can use other command line tools such as head or tail.
> - If you specify --output json, --output yaml, or --output yaml-stream the output is completely processed as a single, native structure before the --query filter is applied. The AWS CLI runs the query only once against the entire structure, producing a filtered result that is then output.

Because the intentions are different and the parsing is performed differently, there isn't any change that we can make here. Here's a previous issue with the explanation given:

> The difference is mainly due to the fact that output text is intended to stream to stdout, which makes the CLI behave more like a true unix program allowing it to be piped between lots of commands and the chunked responses will be lazily pulled through your pipeline of commands. This is not the case with `--output json` since we would need to buffer up the entire response before we can parse it to one large json document. Which would then be passed a huge chunk to the next program in the pipeline. This has the unfortunate effect on `--query`.
> 
> _Originally posted by @stealthycoin in https://github.com/aws/aws-cli/issues/3298#issuecomment-402305904_
