### ISSUE TITLE
Allow filtering of S3 buckets by tag

### ISSUE THREAD

**Issue by tomelliff** [aws/aws-cli#6744]
**Is your feature request related to a problem? Please describe.**
It's currently very painful to list buckets by tag.

My current company has buckets with certain mutable metadata (such as the team ownership) in the resource name which causes issues when those facts change because now the bucket is named wrong or we need to recreate the bucket.

I'd much prefer to put this mutable metadata into tags so we can easily update this as things change.

**Describe the solution you'd like**
Something like:
```
aws s3api list-buckets --filters Name=tag:Team,Values="foo,bar"
```

**Describe alternatives you've considered**
This horrible bash script that takes ages to run:
```
for bucket in $(aws s3api list-buckets --query 'Buckets[].Name' --output text); do
  team_tag=$(aws s3api get-bucket-tagging --bucket $bucket --query 'TagSet[?Key==`Team`].Value' --output text 2>/dev/null)
  if [[ $team_tag =~ ^(foo|bar)$ ]]; then
    echo $bucket
  fi
done
```

**Comment by kdaily** [comment]
Hi @tomelliff,

Thanks for your post and the information you provided. You should take a look at the Resource Groups and Tagging API:

https://docs.aws.amazon.com/ARG/index.html

Here's the CLI documentation page for the `get-resources` operation:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/resourcegroupstaggingapi/get-resources.html

Any other implementation to do this would be required by the S3 team, as those operations are defined by the service team, not the CLI team.

Hope that answers your question! If you have more questions about how to use the Resource Group tagging, I would suggest using [AWS re:Post](https://repost.aws) to ask questions, as members there will have more experience with this service than the AWS CLI maintainers.
