### ISSUE TITLE
cli_auto_prompt not read from source_profile in ~/.aws/config

### ISSUE THREAD

**Issue by alblue** [aws/aws-cli#6749]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**

The parameter `cli_auto_prompt` can be specified as `{on,on-partial}` in the `[default]` section of the `~/.aws/config` file.

If using multiple profiles defined in the config file, a `source_profile` can be used, which allows one profile to be a subset of another (or default) one, typically used for setting a role to assume:

```
[profile dev]
adfs_role_arn=arn:aws:iam::123412341234:role/Example

[profile dev-test]
role_arn=arn:aws:iam::123412341234:role/Test
source_profile=dev
```

When using the `cli_auto_prompt=on` in the actual profile (e.g. `dev-test`) it works. If the line is moved to the `[profile dev]` section, the `source_profile` isn't followed, and so it doesn't default to finding the parameter.

**SDK version number**
aws-cli/2.4.15 Python/3.8.8 Darwin/20.6.0 exe/x86_64

**Platform/OS/Hardware/Device**
macOS 11.6.1

**To Reproduce (observed behavior)**
Add a new profile section in the ~/.aws/config file:

```
[profile works]
cli_auto_prompt=on

[profile fails]
source_profile=works
```

**Expected behavior**
If the `cli_auto_prompt` is not set in the profile, and there's a `source_profile`, follow that to see if there's a setting for `cli_auto_prompt`

**Logs/output**
N/A

**Additional context**
See https://docs.aws.amazon.com/sdkref/latest/guide/usage-examples-role_from_user.html#usage-examples-role_from_user-config_settings for `source_profile` example

**Comment by tim-finnigan** [comment]
Hi @alblue thanks for reporting this. I think this overlaps with an older issue: https://github.com/aws/aws-cli/issues/3334. As mentioned in [this comment](https://github.com/aws/aws-cli/issues/3334#issuecomment-397371786), the `source_profile` will only pull credentials from the targeted profile. I will make a note in that issue that the documentation should also clarify that configurations such as `cli_auto_prompt` are also not carried over through the `source_profile`.

**Comment by alblue** [comment]
The problem is that it makes using the configuration file slightly pointless when you have multiple profiles. The only way to do this (other than copy and paste) is to use variables instead, as they will apply to all. It also means you end up with a "works on my machine" mentality as you can no longer share or rely on the configuration file.
