### ISSUE TITLE
SSL Validation error when using winpty

### ISSUE THREAD

**Issue by daddyg** [aws/aws-cli#6755]
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on? Git Bash in Windows 10

aws-cli/2.3.6 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

**Describe the question**
Hi,

We have recently had zScaler mandated and so we need to be able to specify a specific zscaler certificate to trust. I am able to get the AWS CLI working in both Git Bash and a standard windows command line by setting the AWS_CA_BUNDLE environment variable. Unfortunately when I use ssm to connect to an instance in Git Bash I need to run it through winpty, and at this point I get an SSL Validation error

For instance
```
$ winpty aws ssm start-session --target i-12345XYZ12345
```

Results in:
```
SSL validation failed for https://ssm.eu-west-1.amazonaws.com/ [Errno 2] No such file or directory
```

If I remove the winpty then the connection is made, but I have various other issues as you might expect.

In order to configure the cert I have added the following to my ~/.bashrc file
```
export AWS_CA_BUNDLE=/c/projects/certs/IS_INFRA_ROOT_PEM.pem
```
I have also now added a windows environment variable similar to the above to get the cli working in a standard windows command line

**Logs/output**
```
Traceback (most recent call last):
  File "awscli\clidriver.py", line 459, in main
  File "awscli\customizations\commands.py", line 197, in __call__
  File "awscli\customizations\commands.py", line 191, in __call__
  File "awscli\customizations\s3\subcommands.py", line 505, in _run_main
  File "awscli\customizations\s3\subcommands.py", line 570, in _list_all_buckets
  File "awscli\botocore\client.py", line 278, in _api_call
  File "awscli\botocore\client.py", line 583, in _make_api_call
  File "awscli\botocore\client.py", line 603, in _make_request
  File "awscli\botocore\endpoint.py", line 102, in make_request
  File "awscli\botocore\endpoint.py", line 156, in _send_request
  File "awscli\botocore\endpoint.py", line 200, in _do_get_response
  File "awscli\botocore\endpoint.py", line 269, in _send
  File "awscli\botocore\httpsession.py", line 371, in send
botocore.exceptions.SSLError: SSL validation failed for https://s3.eu-west-1.amazonaws.com/ [Errno 2] No such file or directory

SSL validation failed for https://s3.eu-west-1.amazonaws.com/ [Errno 2] No such file or directory
```

**Comment by daddyg** [comment]
Thanks Tim, that has been very helpful. If I specify the --ca-bundle parameter using a linux style path then it works, but using a windows style path results in the same error. 

This looks to be a known issue, possibly with git bash, where any unix paths detected are being changed to a windows format path. I'll have to fiddle to get this working, possibly with this work around
```
export MSYS_NO_PATHCONV=1
```

**Comment by tim-finnigan** [comment]
Hi @daddyg thanks for following up, were you able to resolve the path issue?
