### ISSUE TITLE
AWS CLI v2 pulls ancient ruamel library

### ISSUE THREAD

**Issue by draeath** [aws/aws-cli#6756]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
AWS CLI  v2 fails to build on Python 3.10.2 apparently due to it (or a dependency) pulling a [very old version of ruamel.](https://sourceforge.net/p/ruamel-yaml/tickets/419/)

**SDK version number**
N/A

**Platform/OS/Hardware/Device**
RHEL 7.9 /w devtoolset-10

**To Reproduce (observed behavior)**
1. Set up RHEL 7.9 x86_64 /w EPEL and SCL.
2. Install and activate [devtoolset-10](https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/10/html-single/10.0_release_notes/index)
3. Build (or otherwise obtain) a python 3.10.2 interpreter
4. Attempt to build or install aws-cli v2 via pip
5. Observe ruamel 0.15.100 is selected as a dependency, which is *ancient* and will not build

**Expected behavior**
Normal and working AWS CLI v2.

**Logs/output**
N/A - see attachments in the ruamel issue report if you need/want to see the build details

**Additional context**
N/A

**Comment by luisdavim** [comment]
At least change the requirement to

```
ruamel.yaml>=0.15.0,<0.17.18
````

So it can be installed on termux.

**Comment by aureq** [comment]
@tim-finnigan If 3.10 isn't announced yet, I think you may also want to fix the `README.md` for this repo since it states `3.10.x and greater` and it can be a bit confusing.

Also, any progress on changing the `requirements.txt` please ?

**Comment by aureq** [comment]
Related to #5943

**Comment by nateprewitt** [comment]
Hi @aureq,

I think the confusion is both CLI v1 and CLI v2 are housed in this repository. You'll find the README for CLI v1 states support for Python 3.10 which is correct. The CLI v2 does not currently provide support though.

CLI v1 Branch: https://github.com/aws/aws-cli/tree/develop
CLI v2 Branch: https://github.com/aws/aws-cli/tree/v2

**Comment by aureq** [comment]
Ah yes you're right @nateprewitt  Thank you for pointing that out.

Any chances on the updated dependency though please ?

**Comment by nateprewitt** [comment]
I'll have to defer to the CLI v2 engineers on timelines but I do know it's being worked on.

**Comment by kdaily** [comment]
Hi @aureq,

We just bumped the version of ruamel.yaml to <=0.17.21 (latest at the time of deployment). We're still working on Python 3.10 support, which you can track at https://github.com/aws/aws-cli/issues/7004. Thanks again for reporting this!

**Comment by eduardocorral** [comment]
I can now build 2.7.1 in alpine 3.16.

```
aws-cli/2.7.11 Python/3.10.4 Linux/5.4.0-121-generic source/x86_64.alpine.3 prompt/off
```

ruamel installed

```
ruamel.yaml            0.17.21
ruamel.yaml.clib       0.2.6
```
