### ISSUE TITLE
Add flag to automatically use the fips endpoints

### ISSUE THREAD

**Issue by slimm609** [aws/aws-cli#6767]
**Is your feature request related to a problem? Please describe.**
Manually tracking and setting the fips endpoints is very difficult when trying to use the aws cli in govcloud environments. 

**Describe the solution you'd like**
the recent release of the aws provider for terraform added the ability to enforce fips endpoints without having to set each endpoint with the [use_fips_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#use_fips_endpoint) setting.  Having a similar feature such as `--fips` for the aws cli v2 would be very beneficial as the endpoints are all already known and listed in botocore with fips tags https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json

adding the ability to set a flag for all aws cli options to use the fips endpoints (if available) would make it much easier for users

**Comment by kdaily** [comment]
Thanks for the feature request!

**Comment by willfarrell** [comment]
I saw the mention of `AWS_USE_FIPS_ENDPOINT` (https://docs.aws.amazon.com/general/latest/gr/rande.html#FIPS-endpoints). But not sure if one can set to `TRUE` or needs to be set to a specific url.
