### ISSUE TITLE
Transfer Domain To Another Aws Account

### ISSUE THREAD

**Issue by isophel** [aws/aws-cli#6773]
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [x] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- z[ ] Other/Not sure.

**Platform/OS/Hardware/Device**
Windows-10-10.0.19042, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel

I have failed to transfer a domain name form one AWS account to another, am using AWS CLI v2 but It is showing the syntax of the  command is incorrect I have tried these two different commands but none is working 
command 1: 
`aws route53domains transfer-domain-to-another-aws-account --region us-east-1 --domain-name <my-domain> --account-id <destination-account-id>`

command 2:
`aws route53domains transfer-domain-to-another-aws-account --region us-east-1 --domain-name <domain name> --account-id <destination-account-id>`

**Logs/output**
`--debug` The syntax of the command is incorrect
![error](https://user-images.githubusercontent.com/43314566/157471494-2bbc3549-8730-4e6a-a7ab-0c5ca1029e1c.png)

**Comment by aaoswal** [comment]
Hi @isophel,
Can you confirm that the domain is using backslashes instead of slashes and ? That might be causing the syntax error.

I would also like to request you to please provide full debug logs, if the error persists.

Hope this helps!

**Comment by isophel** [comment]
> Hi @isophel, Can you confirm that the domain is using backslashes instead of slashes and ? That might be causing the syntax error.
> 
> I would also like to request you to please provide full debug logs, if the error persists.
> 
> Hope this helps!

I checked my syntax i had put the domains in '<>' and it worked. Thank you
