### ISSUE TITLE
Feature Request: cloudcontrol get-resource-by-arn

### ISSUE THREAD

**Issue by jxn** [aws/aws-cli#6776]
**Is your feature request related to a problem? Please describe.**
It is difficult to get more information about a resource easily given only an arn.  The CLI + CloudControl API could make this easier.

**Describe the solution you'd like**
add an --arn parameter to cloudcontrol get-resource subcommand command and make --type-name optional
 *or*
add a get-resource-by-arn with no --type requirement
```aws cloudcontrol get-resource-by-arn <SOME-ARN-FROM-ANY-RESOURCE-TYPE> ```

**Describe alternatives you've considered**
Use a tool like https://github.com/instacart/arn to convert the arn into the appropriate class. Map classes on to type-names that cloudcontrol api understands, parse out resource id's from the arns (where possible), use both pieces of information to get the information using the get-resource subcommand with the --type-name parameter.

**Comment by tim-finnigan** [comment]
Hi @jxn thanks for the feature request. I will reach out to the CloudControl team and see if this is something they would consider. I’m also going to transfer this to our shared SDK repository since it is a request for new API functionality that would affect other SDKs.
