### ISSUE TITLE
High CPU usage while using AWS CLI from my custom script

### ISSUE THREAD

**Issue by TROUBLE-1** [aws/aws-cli#6782]
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
By just using 1 command CPU usage increases to 10%

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
My script uses multi-threading that runs 20 commands at once, System has 8 core

**Additional context**
![2022-03-13 20_15_23-Window](https://user-images.githubusercontent.com/54508518/158065116-11c3873b-7121-4e24-9158-21676ae6ae96.png)

**Comment by aaoswal** [comment]
Hi @TROUBLE-1,
I would like to request you for some additional information related to the bug you are facing. Could you please provide the following:
- The version of CLI are you using
- Sample code with the command that is being executed
- The debug logs by appending `--debug` to the command and redacting any sensitive information
- Technical specifications like the RAM and processor of the Windows 10 system you are using to run the command

Thank you!
