### ISSUE TITLE
AWS CLI  support AWS SSO Applications

### ISSUE THREAD

**Issue by tomahkvt** [aws/aws-cli#6786]
Good afternoon! Can you please tell me if AWS CLI supports creating AWS SSO Applications?

**Comment by aaoswal** [comment]
Hi @tomahkvt,
Thank you for your patience. 
While the AWS CLI does support AWS SSO, unfortunately [SSO applications](https://docs.aws.amazon.com/singlesignon/latest/userguide/awsapps.html#awsapps-add-config-app) are currently not supported through the CLI  but through the console.

**Comment by aaoswal** [comment]
Hi @tomahkvt,
Thank you for bringing this to our attention.

Creating SSO applications is not available for all the SDKs currently, hence, I created this issue in our shared SDK repository here for tracking: https://github.com/aws/aws-sdk/issues/205

I’ll raise this issue internally and we will update that GitHub issue as we go. Closing this issue now, please refer to that issue if you’re interested in tracking it going forward. Thanks!
