### ISSUE TITLE
AWS CLI support for Control Tower

### ISSUE THREAD

**Issue by marktheskies** [aws/aws-cli#6793]
**Is your feature request related to a problem? Please describe.**

Enabling all strongly recommended and elective guardrails across multiple OUs one at a time in the AWS console is a very time-consuming process. 

**Describe the solution you'd like**

Support to enable a guardrail on an OU via the AWS CLI. This would allow users to implement a script to to bulk-enable guardrails and avoid having to enable one at a time in the console.

**Comment by kdaily** [comment]
Hi @marktheskies,

Thanks for the feature request. It does not appear that there is any public API for AWS Control Tower at this time. I will pass along this feedback to the service team, but until this hapens, it is not available in any AWS SDK or tool.

https://docs.aws.amazon.com/controltower/index.html
