### ISSUE TITLE
aws ec2 create-instance-export-task command creates a ova file with "VM Network", which can not be imported to a vsphere cluster with vDS

### ISSUE THREAD

**Issue by luoymu** [aws/aws-cli#6801]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
aws ec2 create-instance-export-task command creates a ova file with "VM Network", which can not be imported to a vsphere cluster with vDS
The network portion of the ovf file ( contained in the ova file) is like this
<NetworkSection>
    <Info>The list of logical networks</Info>
    <Network ovf:name="VM Network">
      <Description>The VM Network network</Description>
    </Network>
  </NetworkSection>

The import of this ova via some terraform code produces this error
"The provided network mapping between OVF networks and the system network is not supported by any host."

If we change the network section of of the ovf file to 
<NetworkSection>
    <Info>The list of logical networks</Info>
    <Network ovf:name="bridged">
      <Description>The VM Network network</Description>
    </Network>
  </NetworkSection>

Then it will work. 

**SDK version number**
NA

**Platform/OS/Hardware/Device**
What are you running the cli on?
from terraform code
**To Reproduce (observed behavior)**
Steps to reproduce the behavior

**Expected behavior**
the aws ec2 create-instance0export-task command should create an ova file with right configuration of network  It might be related to vDS or vSS

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**

**Comment by kellertk** [comment]
Hi there! Importing external OVAs into vSphere often creates problems with network mapping. Are you using the OVF Tool to specify network maps?

**Comment by kellertk** [comment]
Also, it isn't clear from your message what changes are needed to the OVF...

**Comment by tim-finnigan** [comment]
Hi @luoymu this might be a Terraform issue but I’m not sure. Could you provide debug logs if you’re still experiencing this issue?
