### ISSUE TITLE
Unable to install 1.22.80 via pip

### ISSUE THREAD

**Issue by mildebrandt** [aws/aws-cli#6810]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
I'm unable to download the latest awscli python library using `pip`:
```
$ pip install awscli==1.22.80 -i https://pypi.python.org/simple
ERROR: Could not find a version that satisfies the requirement awscli==1.22.80  (from versions: 0.4.1, 
0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3....

.... 1.22.75, 1.22.76, 1.22.77, 1.22.78, 1.22.79)
ERROR: No matching distribution found for awscli==1.22.80
```

The release exists in pypi: https://pypi.org/project/awscli/1.22.80/
But it's not showing up in the repo: https://pypi.org/simple/awscli/

**Comment by nateprewitt** [comment]
Hi @mildebrandt, unfortunately it appears we've hit another case of https://github.com/pypa/warehouse/issues/10390. Cloudflare fronts PyPI and periodically their cache refresh will fail after we've uploaded new artifacts. That's what causes the discrepancy between the project and simple pages.

We aren't able to force a refresh in PyPI's infrastructure anymore, so we're currently stuck waiting until the cache expires or a PyPA member invokes a refresh. That may be in the next couple hours or by 1pm PT tomorrow at the latest. In the meantime, the best option is going to be to install `awscli<1.22.80`.

**Comment by mildebrandt** [comment]
Thanks for the link to the warehouse bug, I'll be sure to watch that one. I'll close this issue when we see the index updated.

**Comment by ChristophShyper** [comment]
Looks like it's working.

**Comment by nateprewitt** [comment]
It does appear the cache has refreshed overnight. We'll resolve this since the current issue is mitigated and track any progress on PyPI's side in the linked ticket above. Thanks for bringing this to our attention, @mildebrandt!

**Comment by mildebrandt** [comment]
You beat me to it, still early in California. Thanks!
