### ISSUE TITLE
aws cli uses docutils 0.4 which shows vulnerable in blackduck security scan

### ISSUE THREAD

**Issue by kollol-chowdhury-incontact** [aws/aws-cli#6825]
Hi Team,

We are using latest version of aws cli and when we run blackduck scan,it shows docutils0.4(/usr/local/aws-cli/v2/2.4.28/dist/docutils/writers/s5_html/themes/default/slides.js) being used which has critical vulnerability.
It also shows zlib 1.2.3,which is a mediym risk vulnerability.

How to fix those?
Any help will be appreciated.

TIA

**Comment by kdaily** [comment]
Hi @kollol-chowdhury-incontact,

Thanks for writing. I looked into the versions stated, however the AWS CLI v2 does not use these versions of docutils or zlib. The dependency for `docutils` is defined here:

https://github.com/aws/aws-cli/blob/43679b47195d2269fdc6d631c14c6082bc054d8e/setup.cfg#L32

Based on that, there's no way that we're distributing `docutils==0.4`. I took the output of the `docutils` folder and `diff`ed it against a fresh copy of `docutils==0.15.2` and they are identical.

For `zlib`, we only provide a symlink file for the system-provided library, so this would be part of your environment.

For each of these, I would check your local environment to confirm that you do not have these dependencies installed for yourself.
