### ISSUE TITLE
Support multi-region access points for aws s3 sync

### ISSUE THREAD

**Issue by zeleena** [aws/aws-cli#6835]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
Multi-region access points have been supported since 2.2.35 according to the [changelog](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#L917). However, I cannot supply a multi-region access point to the `aws s3 sync` command due to a Parameter Invalidation Error: https://github.com/aws/aws-cli/blob/2.5.1/awscli/customizations/s3/subcommands.py#L1278

**SDK version number**
CLI version: aws-cli/2.2.35 Python/3.8.8 Linux/5.16.13-200.fc35.x86_64 docker/x86_64.amzn.2
Looking at the code, this is also the case for the latest version, 2.5.1

**Platform/OS/Hardware/Device**
Fedora CoreOS 35.20220227.3.0 

**To Reproduce (observed behavior)**
```
aws s3 sync arn:aws:s3::<account>:accesspoint/<accesspoint_name>.mrap/folder/ .
```
gives
```
usage: aws s3 sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
Error: Invalid argument type
```

**Expected behavior**
I expected to be able to sync the existing folder specified with the multi-region access point.

**Logs/output**
```
2022-03-31 17:36:17,754 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.35 Python/3.8.8 Linux/5.16.13-200.fc35.x86_64 docker/x86_64.amzn.2
<redacted>
2022-03-31 17:36:17,817 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 459, in main
  File "awscli/customizations/commands.py", line 197, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/s3/subcommands.py", line 712, in _run_main
  File "awscli/customizations/s3/subcommands.py", line 746, in _get_params
  File "awscli/customizations/s3/subcommands.py", line 1191, in add_paths
  File "awscli/customizations/s3/subcommands.py", line 1278, in check_path_type
awscli.customizations.exceptions.ParamValidationError: usage: aws s3 sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
Error: Invalid argument type

usage: aws s3 sync <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
Error: Invalid argument type
```

**Comment by kdaily** [comment]
Hi @zeleena,

Thanks for writing in! You only need to still add the `s3://` prefix to your S3 URI, even when supplying a multi-region access point ARN. I tested this and it was successful:

```
> aws2 --version
aws-cli/2.5.0 Python/3.9.11 Darwin/19.6.0 exe/x86_64 prompt/off
> aws s3 sync /tmp/mydir/ s3://arn:aws:s3::123456789012:accesspoint/asdfasdf.mrap/mydir
upload: ../../../../tmp/mydir/hello.txt to s3://arn:aws:s3::123456789012:accesspoint/asdfasdf.mrap/mydir/hello.txt
```

**Comment by zeleena** [comment]
Hi @kdaily,

Thanks for the clarification, I can confirm that does work. I was referencing the [multi-region access point docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiRegionAccessPointRequests.html) and didn't see any examples starting with `s3://arn:` and I mistakenly thought that `s3://` and `arn:` were mutually exclusive prefixes, but they are not. Thanks again!

**Comment by kdaily** [comment]
Glad it's working for you!

Understood about the documentation. The AWS CLI provides a few high level operations like `cp` and `sync` which are not managed by the S3 team. That documentation would apply if you were using the low level `aws s3api` operations.

Closing this out! 👋🏻
