### ISSUE TITLE
show ami lastLaunchedTime in ec2 describe-images api

### ISSUE THREAD

**Issue by matanr-orca** [aws/aws-cli#6856]
### Describe the feature

I want to be able to see the amis lastLaunchedTime attribute in the describe images API so I won't need to run a describe-image-attribute request for each ami I want to see this on, also it seems like the describe-image-attribute is broken for this specific attribute anyway so I can't use it either.

### Use Case

i need to be able to see multiple amis lastLaunchedTime and i don't want to send a request for each ami (could be a lot)

### Proposed Solution

you have a way to get this data already, just add it to the list of attribute we get in describe-images

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.4.13 

### Environment details (OS name and version, etc.)

macos big sur 11.5.1 Python/3.8.8 Linux/5.10.76-linuxkit exe/x86_64.debian.11 prompt/off

**Comment by aaoswal** [comment]
Hi @matanr-orca,
Thank you for submitting the feature request. Given that the functionality of getting `lastLaunchedTime` already exists in another API (`describe-image-attribute`), I cannot guarantee the addition of this feature.

Nevertheless, I will raise this issue internally with the respective `service-api` team and post any further updates on the request here.

Also, you mentioned that [`describe-image-attribute`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-image-attribute.html) is broken for this specific attribute, could you please elaborate on the problem you are facing? 
Could you provide some additional details:
- Problem Description
- Reproduction Steps
- Sample Code

I would be glad to help you out to get that working for you.

**Comment by jpriebe** [comment]
Just a note for future reference - this feature was actually added to the AWS CLI in 2.15.41 (April 24, 2024).   If you're not seeing LastLaunchedTime, you may need to update your version of the AWS CLI.  Note that LastLaunchedTime is not added to the the JSON object for images that have never been launched.
