### ISSUE TITLE
aws redshift-data list-databases not working

### ISSUE THREAD

**Issue by Tocha4** [aws/aws-cli#6865]
### Describe the bug

This command expects the required parameter `--database` without needing it. After the execution an error is being raised `aws: error: the following arguments are required: --database`.
![image](https://user-images.githubusercontent.com/30746204/162762935-06f2891c-d877-4744-9e96-a908ab9e640b.png)

Used version on a Windows machine:
`C:\>aws --version
aws-cli/2.5.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off`

### Expected Behavior

This command should follow the documentation: https://docs.aws.amazon.com/cli/latest/reference/redshift-data/list-databases.html

### Current Behavior

![image](https://user-images.githubusercontent.com/30746204/162763887-e5470d82-5f8b-4158-99a2-65d16bb05374.png)

### Reproduction Steps

run `aws redshift-data list-databases`

### CLI version used

aws-cli/2.5.4

### Environment details (OS name and version, etc.)

Windows

**Comment by tim-finnigan** [comment]
Thanks @Tocha4 for reaching out. It looks like database is required because you must first connect to a database as described here: https://aws.amazon.com/blogs/big-data/using-the-amazon-redshift-data-api-to-interact-with-amazon-redshift-clusters/

>**List databases**
>
>Most organizations use a single database in their Amazon Redshift cluster. You can use the following command to list the databases you have in your cluster. This operation requires you to connect to a database and therefore requires database credentials:
>
>`aws redshift-data list-databases  --cluster-identifier <your-cluster-id>--secret-arn  <replace-with-your-secret ARN> --database <your-db-name> --region us-west-2`

In the [CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/redshift-data/list-databases.html) it also notes:

>`--database` *(string)*
> The name of the database. This parameter is required when authenticating using either Secrets Manager or temporary credentials.
