### ISSUE TITLE
aws ssm get-parameter command not working for secure string without version

### ISSUE THREAD

**Issue by kiran-ghuge** [aws/aws-cli#6873]
**not able retrieve secure string without version number** (It is not working for the normal string as well)

running command below: 
`aws ssm get-parameter --name /path/to/some-parameter`

gives an error:
**An error occurred (ParameterNotFound) when calling the GetParameter operation:** 

### Expected Behavior

should able to retrieve secure string without version number

### Current Behavior

**An error occurred (ParameterNotFound) when calling the GetParameter operation:** 

### Reproduction Steps

steps to reproduce this bug

1) open cli
2) run  aws ssm get-parameter --name /some/path/parameter

### CLI version used

aws-cli/2.5.4

### Environment details (OS name and version, etc.)

windows 10

**Comment by kiran-ghuge** [comment]
It is not working for the normal string parameter as well, we need to give version number specifically to get it work, but as per documentation it should retrieve the latest version value in case not given version number

_aws ssm get-parameter --name "/dev/test-ssm:1"_

**Comment by tim-finnigan** [comment]
Hi @kiran-ghuge thanks for reaching out. I tried to reproduce this issue by creating a parameter as [documented here](https://docs.aws.amazon.com/systems-manager/latest/userguide/param-create-cli.html#param-create-cli-string) and then running `aws ssm get-parameter --name parameter-name`, but that command ran successfully for me. Could you share your debug logs by adding `--debug` to the command?

**Comment by kiran-ghuge** [comment]
Hi @tim-finnigan thanks for quick response.
by adding `--debug` I got the issue.
when I run the `aws ssm get-parameter --name parameter-name --debug` from vscode bash terminal, it is taking the ssm paramter path as `C:/Program Files/Git/dev/test-ssm` instead of `/dev/test-ssm` and thats why we are getting this error.

you can see here
` DEBUG - Making request for OperationModel(name=GetParameter) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'X-Amz-Target': 'AmazonSSM.GetParameter', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.5.4 Python/3.9.11 Windows/10 exe/AMD64 prompt/off command/ssm.get-parameter'}, 'body': b'{"Name": "C:/Program Files/Git/dev/test-ssm"}', 'url': 'https://ssm.eu-west-1.amazonaws.com/', 'context': {'client_region': 'eu-west-1', 'client_config': <botocore.config.Config object at 0x0000019734E30280>, 'has_streaming_input': False, 'auth_type': None}}`

but when I run the same command from _windows cmd prompt_ it is working as expected.

**Comment by tim-finnigan** [comment]
Thanks @kiran-ghuge for following up. This looks similar to https://stackoverflow.com/questions/53597272/aws-cli-ssm-get-parameters-invalidparameters-on-windows

Can you try the solutions mentioned there and let us know if any of those work for you?

**Comment by kiran-ghuge** [comment]
Thanks @tim-finnigan, I tried adding a space in front of the name parameter value, one of the solution mention in it and it is working. 
e.g. `aws ssm get-parameter --name " /levelOne/levelTwo"`

**Comment by tim-finnigan** [comment]
Thanks for letting us know, I’m glad that is working for you. We may consider documenting edge cases like this that occur in environments like like MinGW. You could also try setting `MSYS_NO_PATHCONV=1` as some have suggested [here](https://stackoverflow.com/questions/7250130/how-to-stop-mingw-and-msys-from-mangling-path-names-given-at-the-command-line) that solves the problem.

**Comment by myroslavmail** [comment]
in my case I simply configured wrong region :( what a shame ...
