### ISSUE TITLE
Add configuration key for setting default profile name

### ISSUE THREAD

**Issue by hyzyla** [aws/aws-cli#6880]
### Describe the feature

Add configuration key for setting default profile name in `~/.aws/config`
 

### Use Case

I'm always frustrated when write profile name in multi account setup and I'm not one who looking for this future https://stackoverflow.com/questions/31012460/how-do-i-set-the-name-of-the-default-profile-in-aws-cli

```bash
aws --profile 857306286857_Dev-Developer sts get-caller-identity
```

### Proposed Solution

Add configuration key for setting default profile name in `~/.aws/config`. For example, `kubectl` has ability to set default namespace and user profile for accessing Kubernetes.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.4.25 Python/3.8.8 Darwin/21.4.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
Hi @hyzyla thanks for the feature request. Have you considered using the [AWS_PROFILE](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) environment variable?

>AWS_PROFILE
>
>Specifies the name of the AWS CLI profile with the credentials and options to use. This can be the name of a profile stored in a `credentials` or `config` file, or the value default to use the default profile.
> 
>If defined, this environment variable overrides the behavior of using the profile named `[default]` in the configuration file. You can override this environment variable by using the `--profile` command line parameter.

**Comment by hyzyla** [comment]
Yes, I know about environment variable. Setting environment variable is really handy for  automated scripts, but for manually typed user commands it seems for me not user-friendly. I'll give you an example why I'm thinking that using environment variable isn't convenient to use: I have three AWS profile, and I'm constantly switching between them during a day. Right now I have to write `--profile` cli option for specify profile. One way to simplify my workflow is to set environment variable in `~/.bashrc` and every time when I want to switch between profile, I have to edit `~/.bashrc`  and then load them to current shell. Also, I can set environment variable temporary using `export` command or use environment variable managers. But in that case it's seems strange that we have configuration for aws cli into three places: `~/.aws/config`, `~/.aws/credentails`, `~/bashrc`. It would be ideal, if aws cli will have commands:
 * list profiles
 * set current profile
 * get current profile

**Comment by tim-finnigan** [comment]
Hi @hyzyla thanks for following up. There is already a `list-profiles` command [documented here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/list-profiles.html). Also you could use the [get](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/get.html) and [set](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/set.html) commands to quickly update the configurations based on another profile. And you can just run `aws configure` to update the default profile. If the request is for a single command that allows alternating the default profile with another, that is something the team is not considering at this time. There are concerns about adding that functionality to a config file when using environment variables or the methods above should suffice. But please let me know if there’s anything you wanted to clarify or expand on in your request.

**Comment by MacHu-GWU** [comment]
@hyzyla 

I think this tool [awscli_mate](https://github.com/MacHu-GWU/awscli_mate-project#use-awscli_mate-as-a-interactive-cli) is exactly what you are looking for:

1. you can use it as a cli, you can use it in your shell script, just do ``awscli_mate set_profile_as_default --profile=your_profile``
2. you can use it as an interactive UI, just do ``awscli_mate_ui``, see demo below
3. you can use it as a Python library, see the sample below

```python
import boto3
import awscli_mate.api as awscli_mate

awscli_mate.AWSCliConfig().set_profile_as_default(profile="your_profile_name_here")

boto3.client("s3") # this is the named profile you just set as default
```

![](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif)

![](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif)

Hope this could help
