### ISSUE TITLE
Add support to "Activate AWS user-defined 'cost allocation tags' programmatically "

### ISSUE THREAD

**Issue by sindhu890** [aws/aws-cli#6882]
### Describe the feature

I would like to have a feature to "activate" the user-defined cost allocation tags programmatically. 
Unless I can't find it, there doesn't appear to be an available AWS API method

### Use Case

Whenever I want to activate the user-defined/AWS-Generated cost allocation tags, I need to log into my payer account and manually click a button or two to activate the tags.
This seems like a glaringly obvious shortcoming.

I would like to have a feature, where I could maintain / activate the cost-allocation-tags programmatically  

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

AWS CLI Version 2

### Environment details (OS name and version, etc.)

mac (Big sur), RHEL8

**Comment by kdaily** [comment]
Hi @sindhu890,

Thanks for your feature request. This would be a new feature for the billing service team to add, as it is not currently possible to do this. I can pass on your feedback to the cost and billing team, but there isn't any change that we can make directly in the AWS CLI. Closing this out!
