### ISSUE TITLE
AWS Lambda `update-alias` - create the alias if it doesn't exist

### ISSUE THREAD

**Issue by mendhak** [aws/aws-cli#6897]
### Describe the feature

Currently: 
When we want to update an alias, we first check if the alias exists using `list-alias`.  
If it exists, we `update-alias` and if it doesn't exist we `create-alias`.  

The feature request is to make this more convenient from the caller's perspective.  When calling (for example) `update-alias` then that function could check if the alias exists and create it, if it doesn't exist. 

### Use Case

In a multi developer setup we are creating Lambda aliases where the alias matches the branch name.  In our CI/CD pipeline we have to do the list-create-else-update check.  From a purely convenience perspective, it would save some time if the `update-alias` function could do all the work for us.  That would simplify our deployment scripts.  

### Proposed Solution

Just a guess, maybe this would be a `--create-if-not-exists` flag in the `update-alias` function?

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.4.22

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by aaoswal** [comment]
P63331974

**Comment by aaoswal** [comment]
Hi @mendhak,
This request depends on the `service-api`. Hence, I will reached out to the Lambda team on this Feature Request and update the comments with more information.

**Comment by aaoswal** [comment]
Hi @mendhak,
According to the service team, unfortunately, this `feature-request` would not feasible as it will make the create API redundant which would not be a good design choice instead you can perform the necessary validation in your pipeline.
e.g. [list-aliases](https://docs.aws.amazon.com/cli/latest/reference/lambda/list-aliases.html) to check if the given alias already exists.
