### ISSUE TITLE
Response from AWS-CLI in Windows encoded ANSI independent of Terminal encoding

### ISSUE THREAD

**Issue by jeve7** [aws/aws-cli#6900]
### Describe the bug

I installed AWS-CLIv2 in Windows 10 and Git for Windows. Using Command Prompt or Git Bash I am able to execute queries like "aws s3 ls" and "aws connect xxxx". My query response includes a localized character "é". The query works and using --debug parameter I see the response back from the service being encoded as UTF. However when the command writes the response, it's encoded as ANSI. To test, I was redirecting the response to a text file and it is always encoded as ANSI (cp1252). This is what I used: aws s3 ls s3://<BucketName>/Joué-lès > textfile.txt. The character "é" appears encoded as E9 which is ANSI equivalent (cp1252).

### Expected Behavior

I was expecting the result from the command to be encoded UTF-8. The character "é" should be encoded as C3A9 (UTF-8).

### Current Behavior

The result from the command is encoded ANSI (cp1252). The character "é" is encoded as E9.

### Reproduction Steps

-	Install Git For Windows
-	Install AWS CLI v2 for Windows
-	Add a bucket (In the command below replaced by "MyBucketName")
-	Add a folder named “Joué-lès” to the bucket
-	Open Command Prompt and execute “aws s3 ls s3://<BucketName>/Joué-lès > textfile.txt”
       o Read the file with Notepadd++: The file is encoded as ANSI
-	Open Git Bash and execute “aws s3 ls s3://MyBucketName/Joué-lès > textfile.txt”
       o Read the file with Notepadd++: The file is encoded as ANSI
-	Open Git Bash and execute “aws s3 ls s3://MyBucketName/Joué-lès | xxd -u -p -c1 | while read x; do printf "%%%s" "$x"; done”
       o The outcome of the command is: “%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%50%52%45%20%4A%6F%75%E9%2D%6C%E8%73%2F%0D%0A”
       o The string shows the character “é” encoded as E9 and “è” encoded as E8. Those are ANSI encoding. UTF will be encoded as “C3A9” and “C3A8”.

### Possible Solution

I think is something between AWS-CLI and its embedded Python 3.9. Python requires a variable to force UTF for encoding.

### Additional Information/Context

I tested in Windows machines using command prompt and Git Bash at it generates ANSI files consistently.
I tested in Windows using Powershell and it behaves different, the result is UTF-16 but is not encoded well.
I tested in Windows using WSL (Ubuntu) and the bug is not happening, the result is UTF-8.
I tested in Linux and the bug is not happening, the result is UTF-8. 
I tested in MAC and the bug is not happening, the result is UTF-8.

### CLI version used

aws-cli/2.5.8 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 10, Gitbash 2.36

**Comment by aaoswal** [comment]
Hi @jeve7,
CLI uses the default OS locale encoding to encode the files. If needed, you can force the encoding used by using the environment variable [AWS_CLI_FILE_ENCODING](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#:~:text=you%20for%20commands.-,AWS_CLI_FILE_ENCODING,-Specifies%20the%20encoding) to specify a different encoding to be used by AWS.

You can also [change the default locale encoding](https://github.com/aws/aws-cli/issues/6342#issuecomment-902865040) options for Windows as well.

Hope this helps!

**Comment by jeve7** [comment]
Hi @aaoswal, great information! The variable is not working for GitBash (Which is my focus) or Command prompt but the locale parameter in Windows worked!. I am wondering why the environment variable is not working for Command Prompt but it does for Powershell... I'll do more testing since I don't think is a great idea to let Windows running a "Beta" feature.

**Comment by aaoswal** [comment]
Hi @jeve7,
I am not too certain but that might be a Windows related issue. You could try opening an issue there to get appropriate `guidance` towards this problem.
