### ISSUE TITLE
Ecs Execution Command error with a 2 containers Task (Managed Agent STOPPED)

### ISSUE THREAD

**Issue by jgourmelen** [aws/aws-cli#6903]
### Describe the bug

Hi,
I tried to enabled ECS exec configuration inside my task with 2 containers.

But when i deploye my task, only one container is randomly configure with ManagedAgent for ecs execution command

### Expected Behavior

I want to have the Managed agent available for 2 containers.

### Current Behavior

Randomly, the managed agent is available only once : 
(i use this script https://raw.githubusercontent.com/aws-containers/amazon-ecs-exec-checker/main/check-ecs-exec.sh)

Container-Level Checks | 
    ----------
      Managed Agent Status
    ----------
         1. RUNNING for "nginx"
         2. STOPPED (Reason: null) for "api" - LastStartedAt: null

### Reproduction Steps

Deploy task like :
```
[
  {
    "name": "api",
    "image": "xxxxxxx.dkr.ecr.eu-west-3.amazonaws.com/api:78",
    "essential": true,
    "healthCheck": {
      "retries": 3,
      "command": [
        "CMD-SHELL",
        "exit 0"
      ],
      "timeout": 5,
      "interval": 30,
      "startPeriod": null
    },
    "portMappings": [
      {
        "containerPort": 9000,
        "hostPort": 9000
      }
    ],
    "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-group": "${LOG_GROUP}",
        "awslogs-region": "eu-west-3",
        "awslogs-stream-prefix": "ecs"
      }
    },
    "linuxParameters": {
      "initProcessEnabled": true
    },
    "memory": 2048,
    "cpu": 1024
  },
  {
    "name": "nginx",
    "image": "xxxxxxx.dkr.ecr.eu-west-3.amazonaws.com/nginx:78",
    "essential": true,
    "healthCheck": {
      "retries": 3,
      "command": [
        "CMD-SHELL",
        "curl -f http://localhost:80/elb-status || exit 1"
      ],
      "timeout": 5,
      "interval": 30,
      "startPeriod": null
    },
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 80
      }
    ],
    "environment": [
      {
        "name": "variable",
        "value": "value"
      }
    ],
    "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-group": "${LOG_GROUP}",
        "awslogs-region": "eu-west-3",
        "awslogs-stream-prefix": "ecs"
      }
    },
    "linuxParameters": {
      "initProcessEnabled": true
    },
    "memory": 2048,
    "cpu": 1024
  }
]


```

### CLI version used

aws-cli/2.1.38 Python/3.8.8 Linux/5.13.0-39-generic exe/x86_64.ubuntu.21 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 21.10

**Comment by aaoswal** [comment]
Hi @jgourmelen,
Thank you for opening the issue. I apologize but this seems to be related to [aws-containers/amazon-ecs-exec-checker](https://github.com/aws-containers/amazon-ecs-exec-checker).

Hence, I would like to request you to please open an issue in the above repository for the same.

Thanks,
Anish Oswal.
