### ISSUE TITLE
s3api put-object with --sse-customer-key-md5 fails

### ISSUE THREAD

**Issue by keebs** [aws/aws-cli#6906]
### Describe the bug

s3api put-object with --sse-customer-key-md5 fails. Without the --sse-customer-key-md5 is successful.

### Expected Behavior

For the MD5 hash of the received --sse-customer-key to be verified against the provided --sse-customer-key-md5 hash. Upload should continue, if matched, or fail immediately.

### Current Behavior

All tested inputs of  --sse-customer-key-md5 fail upload immediately.

### Upload is successful without the hash:

PS C:\> aws s3api put-object `
  --bucket abc `
  --sse-customer-algorithm AES256 `
  --sse-customer-key "testaes256testaes256testaes25612" `
  --region us-east-2 `
  --key test.pdf `
  --body C:\test.pdf

{
    "ETag": "\"51ffb62dffc2d772a8e5fa6cbe60d150\"",
    "SSECustomerAlgorithm": "AES256",
    "SSECustomerKeyMD5": "ezatpv/Yg0KkjX+5ZcsxdQ=="
}

### I agree with your MD5 hash result:
PS C:\> $key = "testaes256testaes256testaes25612"
$md5 = new-object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
$utf8 = new-object -TypeName System.Text.UTF8Encoding
$hash = $md5.ComputeHash($utf8.GetBytes($key))
$EncodedString =[Convert]::ToBase64String($hash)
Write-Host "Base64 Encoded String: " $EncodedString
Base64 Encoded String:  ezatpv/Yg0KkjX+5ZcsxdQ==

### But if I submit the put-object with --sse-customer-key-md5, it fails:
PS C:\> aws s3api put-object `
  --bucket abc `
  --sse-customer-algorithm AES256 `
  --sse-customer-key "testaes256testaes256testaes25612" `
  --sse-customer-key-md5 "ezatpv/Yg0KkjX+5ZcsxdQ==" `
  --region us-east-2 `
  --key test.pdf `
  --body C:\test.pdf

aws : 
At line:1 char:1
+ aws s3api put-object `
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
An error occurred (InvalidArgument) when calling the PutObject operation: The calculated MD5 hash of the key did not match the hash that was provided.

### Possible Solution

appears to be a bug

### CLI version used

2.6.0

### Environment details (OS name and version, etc.)

Windows 10 Version 10.0.19043.1645

**Comment by tim-finnigan** [comment]
Hi @keebs thanks for reaching out. For reference here is the documentation for that parameter: https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html

> `--sse-customer-key-md5` (string)
>
> Specifies the 128-bit MD5 digest of the encryption key according to RFC 1321. Amazon S3 uses this header for a message integrity check to ensure that the encryption key was transmitted without error.

Can you confirm that your key meets the criteria documented there? For more context here is the S3 documentation on using SSE-C: https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html

**Comment by keebs** [comment]
Tim,

 

Thanks for the reply.

 

RFC1321 specifies the MD5 hash algorithm and the aws documentation specifies Base64 encoding of the hash:

 

If my key is: testaes256testaes256testaes25612

The base64-encoded MD5 hash is: ezatpv/Yg0KkjX+5ZcsxdQ==

Which matches the result returned from the AWS CLI when I don’t specify --sse-customer-key-md5.

 

When providing “ezatpv/Yg0KkjX+5ZcsxdQ==” as input for --sse-customer-key-md5, I receive the error “The calculated MD5 hash of the key did not match the hash that was provided.”. 

 

If I’m missing something, please let me know. Otherwise, I’m open to suggestions.

 

Thanks,

Andrew

**Comment by keebs** [comment]
I figured it out. When using --sse-customer-key-md5, --sse-customer-key also has to be base64 encoded.
Thank you
