### ISSUE TITLE
Add support for mandoc

### ISSUE THREAD

**Issue by justindho** [aws/aws-cli#6918]
### Describe the feature

Linux distros and BSD systems that use `mandoc` instead of `groff` should be supported to display 'help' documentation without the need for installing additional sofware. 

### Use Case

'Help' docs should be able to be displayed on Linux distros and BSD systems that don't use `groff`.

### Proposed Solution

PR #2635 adds support for this feature request.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.6.2

### Environment details (OS name and version, etc.)

aws-cli/2.6.2 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off

**Comment by razamatan** [comment]
i fixed the merge conflict of the original pr as #7406
