### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kellertk** [aws/aws-cli#6919]
### Describe the feature

test

### Use Case

test

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### CLI version used

3

### Environment details (OS name and version, etc.)

windows 25

**Comment by KasonW-ks** [comment]
hi aws, Thankls for your help! i wanted to let you know that in the new version, it looks like the login feature stopped working. is anyone else experiencing this
