### ISSUE TITLE
aws ecr list-images - results to be returned in DESC chronological order

### ISSUE THREAD

**Issue by ceresdarkmatter** [aws/aws-cli#6928]
### Describe the feature

Currently `aws ecr list-images` returns the results in a random order.
Please add the possibility - maybe via a CLI option - to specify the order of the results, on of the available values being ordering by the timestamp when the image has been pushed to the ECR repo in descending order, from newest to oldest.

Basically any way to reproduce out of the box the default ordering ordering already implemented in the AWS console - the `Images` repository page.

### Use Case

I want to be able to retrieve the latest N images published to an ECR repository ordered by "Pushed at" DESC, out of the box, with a single `aws` command execution.

### Proposed Solution

a new optional `--order-by` option for the CLI with at least the "Pushed at" DESC possibility.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.6.3

### Environment details (OS name and version, etc.)

macOS, Linux

**Comment by ceresdarkmatter** [comment]
@aaoswal [aaoswal](https://github.com/aaoswal) - how can one specifically sort the results of `describe-images` by date DESC?
I am specifically asking for order - not filtering or other stuff.

**Comment by aaoswal** [comment]
@ceresdarkmatter I meant that date is a queryable field in `describe-images`, hence it would not be a good design choice to add a new response field to `list-images` pertaining to the date of the image.

Also, I see that you have opened another issue in regard to the same request but with `describe-images`, I provided a workaround for that [here](https://github.com/aws/aws-cli/issues/6929#issuecomment-1121391547).

**Comment by ceresdarkmatter** [comment]
@aaoswal are we speaking the same language?

I do not want that field to be "queryable" - I want to sort based on that field.

If you have 100.000 images you want to retrieve the fist page.

**Comment by aaoswal** [comment]
Hi @ceresdarkmatter,
Have you tried using the workaround provided [here](https://github.com/aws/aws-cli/issues/6929#issuecomment-1121391547) using [JMESPath](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html)?

Also, in regard to the `list-images` having results returned in DESC chronological order, this would only be possible if it had [`imagePushedAt`](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_ImageDetail.html#ECR-Type-ImageDetail-imagePushedAt) in the response as a queryable field instead to be able to sort based on that field.

Given that `describe-images` already does have `imagePushedAt` as a queryable parameter which can be used to get the expected results, the same would not be a good design choice to add a new response field to `list-images` pertaining to the date of the image such as `imagePushedAt` to allow sorting using the parameter.

Hope this helps!

**Comment by Shivam-nagar23** [comment]
Hi @aaoswal , I want to get list the tags according to the last pushed/updated time, Specifically not want to filter the paginated data, want to order the data in the whole data-set according to time, to fetch out latest tag pushed. Could not find anything on this, we get it in random order as of now.

**Comment by sstarcher** [comment]
For very large ECR repos it would be extremely helpful to not have to list out EVERY image in the repo making multiple API calls.  This should support some type of server side ordering or filtering.
