### ISSUE TITLE
aws ecr describe-images - results to be returned in DESC chronological order

### ISSUE THREAD

**Issue by ceresdarkmatter** [aws/aws-cli#6929]
### Describe the feature

Currently `aws ecr describe-images` returns the results in a random order.
Please add the possibility - maybe via a CLI option - to specify the order of the results, on of the available values being ordering by the timestamp when the image has been pushed to the ECR repo in descending order, from newest to oldest.

Basically any way to reproduce out of the box the default ordering ordering already implemented in the AWS console - the `Images` repository page.

### Use Case

I want to be able to retrieve descriptions of the latest N images published to an ECR repository ordered by "Pushed at" DESC, out of the box, with a single aws command execution.

### Proposed Solution

a new optional --order-by option for the CLI with at least the "Pushed at" DESC possibility.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.6.3

### Environment details (OS name and version, etc.)

macOS, Linux

**Comment by ceresdarkmatter** [comment]
Hey - sorry for the late reply!
Please re-open this ticket.
@aaoswal I do not think you have fully understood what I want to achieve.

`--query` is a client-side filtering mechanism, right? If yes - it is not a good solution, what I want to achieve needs to happen on the server-side.

Your solution example:
```
aws ecr describe-images \
	--registry-id "REGISTRY_ID" \
	--repository-name "REPOSITORY_NAME" \
        --max-items 5 \
       --query 'sort_by(imageDetails,& imagePushedAt)[*]'
```

gives me 5 random images from that repository. And sorts the results ascending.

This does NOT return the latest 5.
---

Once again:

From a repository containing a large number of images - let's say tens of thousands, I would like to get the details of the  latest N (between 3 and 20 ?) of those images. 

I want only the latest N images - from the chronological point of view - sorted in a DESC order.

The query would be something similar to this - when N = 5:
```
aws ecr describe-images \
	--registry-id "REGISTRY_ID" \
	--repository-name "REPOSITORY_NAME" \
        --max-items 5 \
       --MAGIC_THAT_IS_NOT_IMPLEMENTED_YET_HERE
```

The ordering filtering + ordering must happen on the server-side. 

Is it clearer now what this ticket was about?

**Comment by Shivam-nagar23** [comment]
I have a similar requirement where i want to deploy the latest image when a new image is pushed in ecr, not able to find the latest as it returns in random order.
Have you found any work-arounds or this has been fixed? Could not find anything related to it.
@ceresdarkmatter

**Comment by ceresdarkmatter** [comment]
@Shivam-nagar23 not as far as I am aware. It is mind-blowing that such a fundamental feature is not available but nothing surprises me anymore regarding AWS.

**Comment by Shivam-nagar23** [comment]
@ceresdarkmatter  I completely agree with you, such a fundamental feature is missing. Do update here if you find any updates?

**Comment by isaquerochak** [comment]
it would be really good

**Comment by isaquerochak** [comment]
This feature would be really very nice.

**Comment by paulotruta** [comment]
If someone's still looking, here's a solution:

`ecr describe-images --repository-name kitchenstories/ultron --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[]' --output text`

cc @Shivam-nagar23

**Comment by Shivam-nagar23** [comment]
HI @paulotruta , what you are suggesting is client side filtering, not server side filtering, if i have 10000's of container images , it will return me paginated response then apply filters on it, thats not my expectations.

**Comment by paulotruta** [comment]
> HI @paulotruta , what you are suggesting is client side filtering, not server side filtering, if i have 10000's of container images , it will return me paginated response then apply filters on it, thats not my expectations.

Yes I realised this a little bit later also when using it. Sorry for the mislead suggestion 👍

**Comment by RHeynsZa** [comment]
Still need this

**Comment by ThomasEg** [comment]
I have the same issue, thousands of images and i need the top N images, but this is not possible without getting list of ALL images first and then do the sorting clientside. 

It is basically the exact same thing as the AWS console does: Show the first "page" ordered by PushedAt descending...this should be the default IMO...

Please re-open the issue...

**Comment by sstarcher** [comment]
For very large ECR repos it would be extremely helpful to not have to list out EVERY image in the repo making multiple API calls.  This should support some type of server side ordering or filtering.

**Comment by ThomasEg** [comment]
Any chance this could be re-opened @aaoswal ?
