### ISSUE TITLE
Lambda SAM deploy with fixed ImageUri don't deploy even after image rebuild

### ISSUE THREAD

**Issue by gokhanoner** [aws/aws-cli#6930]
### Describe the bug

- have a SAM template for Lambda with container image, with predefined `ImageUri`
- Build the image & deploy the lambda, it works for the first run, since lambda doesn't exists.
- Build the image again & push to ECR with same tag.
- Run SAM deploy gets below
```
Initiating deployment

=====================

Waiting for changeset to be created..

No changes to deploy. Stack XXXX is up to date
```

### Expected Behavior

- Even if there's no change in the template, since tag is same, my expectation if build will replace the image tag since image hash is changed.
- I believe this is a valid use case, since even if I update the existing tag, it doesn't effect the lambda, as described in `update-function-code` method -> https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-function-code.html . So `deploy` should be able to understand that image hash is different between Lambda & repo and deploy again.

### Current Behavior

- Nothing happens. Normally deploy fails since there's no change, we're using `--no-fail-on-empty-changeset`

### Reproduction Steps

.

### CLI version used

aws-cli/2.6.1 Python/3.9.11

### Environment details (OS name and version, etc.)

 Linux/4.14.275-207.503.amzn2.x86_64

**Comment by kdaily** [comment]
Hi @gokhanoner,

It looks to me like you're referring to the AWS SAM CLI, which is separate from the AWS CLI. You might need to open up a bug report over here. If so, please let us know and/or close this issue out!

https://github.com/aws/aws-sam-cli/issues

**Comment by gokhanoner** [comment]
Thanks @kdaily , I'll
