### ISSUE TITLE
Improve "aws s3 sync" handling of concurrent bucket modification

### ISSUE THREAD

**Issue by cuu508** [aws/aws-cli#6953]
### Describe the feature

I'm syncing a bucket using `aws s3 sync` to a local filesystem, at the some time other clients are uploading and deleting objects to and from the same bucket. The `aws s3 sync` call sometimes runs into errors about missing keys – the key existed when listing, but was removed immediately after:

```
download failed: s3://src-bucket/dir1/obj1 to dst/dir1/obj1 An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://src-bucket/dir1/obj2 to dst/dir1/obj2 An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

The `aws s3 sync` command continues on, and finishes the task, but *returns exit status 1* at the very end. 

### Use Case

This is problematic when scripting – I have a pipeline of tasks, I would like to abort the pipeline if there's an error, but in my situation NoSuchKey is not really an error.

### Proposed Solution

It would be great if there was a way (a command-line flag?) to ignore NoSuchKey errors. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/1.24.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by boutetnico** [comment]
Also affected by this exact same issue.
