### ISSUE TITLE
Add an export primitive to use with eval to simplify exporting variables

### ISSUE THREAD

**Issue by justindho** [aws/aws-cli#6962]
### Describe the feature

The feature would add an `export` subcommand to the CLI's `aws configure` command. With this feature, I could then switch between profiles that have specific sets of environment variables associated with them easily. For example, to export the environment variables associated with the profile `myprofile`, I could run 

```eval aws configure export --profile myprofile```

To go back to the default profile and its associated environment variables, I could run

```eval aws configure export```

### Use Case

Some of the tools I use require a set of environment varialbe(s) to be set. Switching from one profile to another is painful. This feature would simplify switching profiles (and setting their associated environment variables) by running the single `aws configure export ...` command.

### Proposed Solution

#2454 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

any

### Environment details (OS name and version, etc.)

any

**Comment by tim-finnigan** [comment]
It looks like the feature has now been implemented via https://github.com/aws/aws-cli/pull/7398. Please create a new issue for anything new related to this.
