### ISSUE TITLE
s3api multipart upload unexpected behavior

### ISSUE THREAD

**Issue by TEH30P** [aws/aws-cli#6966]
### Describe the bug

The commands `aws s3api upload-part` and `aws s3api complete-multipart-upload` have unexpected behavior.

### s3api upload-part
Should return error when `--part-number` is out of range `[1-10000]`.

### s3api complete-multipart-upload
Argument `--multipart-upload` must be described as _required_ in **Synopsis** section of [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/complete-multipart-upload.html#synopsis).

### s3api upload-part
Accept invalid (out of range`[1..10000]`) `--part-number` values without error.

### s3api complete-multipart-upload
If `--multipart-upload` argument is omitted then `MalformedXML` error returned which incorrectly describes the problem.

### Reproduction Steps

`s3api complete-multipart-upload` without `--multipart-upload` argument.
``` bash
dd if=/dev/zero of=/tmp/test.bin bs=4k count=1280 # 5M
S3_MPU_ID=$( aws --output text --query 'UploadId' s3api create-multipart-upload --bucket mpu-test --key test.bin )
aws s3api upload-part --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"  --part-number 1 --body /tmp/test.bin
aws s3api upload-part --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"  --part-number 2 --body /tmp/test.bin
aws s3api complete-multipart-upload --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"
```
`s3api upload-part` invalid parameter.
``` bash
dd if=/dev/zero of=/tmp/test.bin bs=4k count=1280 # 5M
S3_MPU_ID=$( aws --output text --query 'UploadId' s3api create-multipart-upload --bucket mpu-test --key test.bin )
aws s3api upload-part --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"  --part-number 0 --body /tmp/test.bin # no error
aws s3api upload-part --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"  --part-number 1 --body /tmp/test.bin
aws s3api abort-multipart-upload --bucket mpu-test --key test.bin --upload-id "$S3_MPU_ID"
```

### Possible Solution

Decribed in _Expected Behavior_ section.

### CLI version used

aws-cli/2.6.4 Python/3.9.11 Linux/3.10.0-1160.53.1.el7.x86_64 exe/x86_64.centos.7 prompt/off

### Environment details (OS name and version, etc.)

Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tim-finnigan** [comment]
Thanks @TEH30P for reaching out. Could you please provide the debug logs by adding `--debug` to your command?

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a couple weeks I'm going to close this. If you're still experiencing the issue please provide the debug logs as requested above and we can revisit this.
