### ISSUE TITLE
Please add a "shell" or "pipe" mode

### ISSUE THREAD

**Issue by nneul** [aws/aws-cli#697]
Something where the usage would be along the lines of:

'aws shell' or 'aws pipe' - with the former leveraging any python readline type support for more interactive friendly usage. 

Then each of the commands that you could normally run via direct execution could be issued interactively:

'ec2 describe-instances ....'

The purpose would be to only do the slower startup once, cache authentication, etc but still let you use all of the same calls.

To make this even more useful - add a '--output jsonsingle' output mode that would do the json all on one line (no formatting), which would allow you to use this in a co-process model where you write one command, read one response, repeat.

**Comment by rayluo** [comment]
Now we have aws-shell https://github.com/awslabs/aws-shell

**Comment by nneul** [comment]
Sweet!
