### ISSUE TITLE
Switch default AWS profile

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [aws/aws-cli#6979]
### Describe the feature

Hi,

Do we have a feature to switch between profiles in AWS cli?

For example, I have several AWS profiles and in order to run a command under a required profile, I need to add a flag `--profile` to the command. Another option is to export/set a variable `AWS_PROFILE`.

What if we don't have all that hassle and just switch between default profiles using cli?
Beside variables and the `--profile` parameter.

So it would be nice to have something like `aws configure --set-default-profile profile_name`
Also, if `aws configure list-profiles` shows the current used profile. 
For example:
```
$ aws s3 ls

An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
```
```
$ aws configure list-profiles
* default
user1
user2
$ aws configure --set-default-profile user1
$ aws configure list-profiles
default
* user1
user2
```
```
$ aws s3 ls
2021-06-03 19:57:23 bucket1
2019-09-03 13:38:20 bucket2
```

### Use Case

I'm always frustrated to run the `--profile` flag or export/set the `AWS_PROFILE` variable.

### CLI version used

aws-cli/2.7.0

### Environment details (OS name and version, etc.)

Windows 11, WSL

**Comment by kferrone** [comment]
As this is the first result in Google for this question and there is no plans for the feature, I have this to share with anyone interested in a bit more user friendly way to switch profiles. 
Just pop this in your bash profile:
```sh
function aws-ctx() {
  export AWS_PROFILE="$(aws configure list-profiles | fzf)"
}
```

**Comment by MacHu-GWU** [comment]
I totally understand why awscli should not provide that feature and agree that the ``AWS_DEFAULT_PROFILE`` environment variable does the trick. However, it does make developer's life easier with this feature.

I think this tool [awscli_mate](https://github.com/MacHu-GWU/awscli_mate-project#use-awscli_mate-as-a-interactive-cli) is exactly what you are looking for:

1. you can use it as a cli, just do ``awscli_mate set_profile_as_default --profile=your_profile``
2. you can use it as a interactive UI, just do ``awscli_mate_ui``
3. you can use it as a Python library.

![](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif)

![](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif)

Hope this could help

**Comment by kalvesolar** [comment]
> @YevheniiPokhvalii I totally understand why awscli should not provide that feature and agree that the `AWS_DEFAULT_PROFILE` environment variable does the trick. However, it does make developer's life easier with this feature.
> 
> I think this tool [awscli_mate](https://github.com/MacHu-GWU/awscli_mate-project#use-awscli_mate-as-a-interactive-cli) is exactly what you are looking for:
> 
>     1. you can use it as a cli, just do `awscli_mate set_profile_as_default --profile=your_profile`
> 
>     2. you can use it as a interactive UI, just do `awscli_mate_ui`
> 
>     3. you can use it as a Python library.
> 
> 
> ![](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif) [ ![274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif) ](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif) [ ](https://user-images.githubusercontent.com/6800411/274720782-c031a52a-2b4e-4dde-85f1-ab558aa1644f.gif)
> 
> ![](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif) [ ![274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif) ](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif) [ ](https://user-images.githubusercontent.com/6800411/274720779-5cc9ddef-18a5-4d76-942f-4be1e97601aa.gif)
> 
> Hope this could help

Nice, seems interesting, thanks

**Comment by faizanakram99** [comment]
> ```shell
> function aws-ctx() {
>   export AWS_PROFILE="$(aws configure list-profiles | fzf)"
>   echo "Switched to profile ""$AWS_PROFILE""."
> }
> ```

didn't work for me, i still need to specify the profile

**Comment by seanmorton** [comment]
@faizanakram99 you probably just need to install [fzf](https://github.com/junegunn/fzf), which is a fantastic tool to get familiar with in general for everything CLI. 

What a great and simple workaround @kferrone, thanks!
