### ISSUE TITLE
Confusing Python version text

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-cli#6987]
### Describe the bug

The README starts:

> The aws-cli package works on Python versions:
>
>  - 3.8.x and greater
>  - 3.9.x and greater

3.9.x is greater than 3.8.x, so isn't it covered by the first point? Does this mean 3.10 and 3.11 are supported or not?

### Expected Behavior

Either just "3.8 and later" or a list of Python versions like "3.8, 3.9, 3.10, 3.11". I don't think it's necessary to mention the `.x` or specific patch versions.

### Current Behavior

See README

### Reproduction Steps

Read README

### CLI version used

-

### Environment details (OS name and version, etc.)

-

**Comment by tim-finnigan** [comment]
Thanks @adamchainz for reaching out. I brought this up with the team and they are open to clarifying that README text. Support for Python 3.10 in v2 is currently being worked on.
