### ISSUE TITLE
AWS CLI v2 compatibility with Python 3.10

### ISSUE THREAD

**Issue by dinapappor** [aws/aws-cli#7004]
### Describe the bug

aws-cli fails to be installed with python 3.10. 

This is due to ruamel.yaml (for which I am unable to track down exactly which module is using it) not having bindings updated for python 3.10.

### Expected Behavior

For it to succeed

### Current Behavior

It failed

### Reproduction Steps

Use alpine

apk install python 3.10

download release tarball
unpack tarbal
python setup.py install

### CLI version used

2.7.5

### Environment details (OS name and version, etc.)

Alpine 3.16, python 3.10,

**Comment by kdaily** [comment]
I've been starting to look at compatibility with the latest version of ruamel (https://github.com/aws/aws-cli/pull/6995), but don't have a timeline when it will be resolved and Python 3.10 support will be available:

**Comment by kdaily** [comment]
HI @dinapappor,

`ruamel.yaml` dependency ceiling was just updated to 0.17.21:

https://github.com/aws/aws-cli/pull/7059

We're still working on the rest of Python 3.10 support.

**Comment by TheEdgeOfRage** [comment]
Considering #7063 has been merged, does that mean 3.10 support is complete, or are there other steps necessary?

**Comment by dinapappor** [comment]
> I can confirm that the build passes. Thank you for this update heart .

This is with `2.7.12`.

**Comment by tim-finnigan** [comment]
Thanks for confirming! I'll go ahead and close this then.
