### ISSUE TITLE
User Name field no longer in access_key.csv

### ISSUE THREAD

**Issue by justin107d** [aws/aws-cli#7017]
### Describe the bug

instructions on the site and error from command state that the csv file with IAM credentials should include the User Name, but it is not there resulting in them loading incorrectly.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-creds-create

### Expected Behavior

Using the following code to input my credentials into the cli
`aws configure import -csv file://C:\filepath\username_access_keys.csv`

### Current Behavior

```
C:\Users\Justin>aws configure import --csv file://C:\Users\Justin\Downloads\Justin_test_accessKeys.csv
Successfully imported 1 profile(s)

C:\Users\Justin>aws iam get-user

An error occurred (InvalidClientTokenId) when calling the GetUser operation: The security token included in the request is invalid.
```

### Reproduction Steps

1. create a new IAM account with AdministratorAccess.
2. go to security credentials and create a new access key
3. save it to the downloads folder
4. edit the csv to add a User Name header on the first row and the user name on the second row
5. use `aws configure import --csv file://C:\Users\Justin\Downloads\Justin_test_accessKeys.csv` to load the keys into the CLI
6. test with `aws iam get-user`

### Possible Solution

correct the mismatch from what is created for the credentials or remove the requirement from both the instructions and the cli

### Additional Information/Context

`aws configure list` lists the wrong credentials than what I am importing.

### CLI version used

aws-cli/2.7.6 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 10

**Comment by tim-finnigan** [comment]
Hi @justin107d thanks for reaching out. I walked through those steps but wasn't able to reproduce the issue.

Can you confirm that you're using the correct profile? You may need to add `--profile <new-user-name>` to your command.

**Comment by justin107d** [comment]
Hi @tim-finnigan 

I tried but I got the following.  I only have one IAM user set up on my account and this is the first time trying to set it up on a machine.

`C:\Users\Justin>aws configure --profile Justin_test import --csv file://C:\Users\Justin\Downloads\Justin_test_accessKeys.csv
Successfully imported 1 profile(s)

C:\Users\Justin>aws iam get-user

An error occurred (InvalidClientTokenId) when calling the GetUser operation: The security token included in the request is invalid.`

**Comment by justin107d** [comment]
Here is something else that might help.  When running `configure list` I get two different sets of keys.

```C:\Users\Justin>aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key     ****************K2NI shared-credentials-file
secret_key     ****************s3oU shared-credentials-file
    region                <not set>             None    None

C:\Users\Justin>aws configure --profile Justin_test
AWS Access Key ID [****************TLUQ]:
AWS Secret Access Key [****************OHKJ]:
Default region name [None]:
Default output format [None]:
```
If I run `configure list-profiles` I get a default and the profile I am trying to set up.  I think I need to find a way to get rid of the default which keeps getting picked up for some reason.

```
C:\Users\Justin>aws configure list-profiles
default
Justin_test

**Comment by justin107d** [comment]
I think this has solved my issue.  Thanks @tim-finnigan 

`C:\Users\Justin>set AWS_DEFAULT_PROFILE=Justin_test`

**Comment by justin107d** [comment]
I think this has solved my issue.  Thanks @tim-finnigan 

`C:\Users\Justin>set AWS_DEFAULT_PROFILE=Justin_test`
