### ISSUE TITLE
aws fms get-policy for security_group_audit_content lists ManagedServiceData 6 times

### ISSUE THREAD

**Issue by jdeluyck** [aws/aws-cli#7033]
### Describe the bug

aws-cli returns the managedServiceData for aws fms policies for security_group_audit_content 5-6 times:

Created in web console:

```json
"ManagedServiceData": "{\"type\":\"SECURITY_GROUPS_CONTENT_AUDIT\",\"securityGroups\":null,\"securityGroupAction\":null,\"preManagedOptions\":[{\"denyProtocolAllValue\":null,\"allowedProtocolsLists\":{\"customListIds\":[\"36a2e5e3-6032-41f4-836d-1599690bc624\"],\"defaultListId\":null,\"defaultListVersion\":null},\"deniedPublicAccessAppLists\":null,\"allowedPublicAccessAppLists\":null,\"allowedPortCountPerSgRule\":null,\"minIpv4CidrPrefixLenPerSgRule\":null,\"minIpv6CidrPrefixLenPerSgRule\":null,\"auditSgDirection\":null},{\"denyProtocolAllValue\":null,\"allowedProtocolsLists\":null,\"deniedPublicAccessAppLists\":null,\"allowedPublicAccessAppLists\":null,\"allowedPortCountPerSgRule\":1,\"minIpv4CidrPrefixLenPerSgRule\":null,\"minIpv6CidrPrefixLenPerSgRule\":null,\"auditSgDirection\":null},{\"denyProtocolAllValue\":null,\"allowedProtocolsLists\":null,\"deniedPublicAccessAppLists\":null,\"allowedPublicAccessAppLists\":null,\"allowedPortCountPerSgRule\":null,\"minIpv4CidrPrefixLenPerSgRule\":20,\"minIpv6CidrPrefixLenPerSgRule\":null,\"auditSgDirection\":null},{\"denyProtocolAllValue\":null,\"allowedProtocolsLists\":null,\"deniedPublicAccessAppLists\":null,\"allowedPublicAccessAppLists\":null,\"allowedPortCountPerSgRule\":null,\"minIpv4CidrPrefixLenPerSgRule\":null,\"minIpv6CidrPrefixLenPerSgRule\":48,\"auditSgDirection\":null},{\"denyProtocolAllValue\":null,\"allowedProtocolsLists\":null,\"deniedPublicAccessAppLists\":null,\"allowedPublicAccessAppLists\":null,\"allowedPortCountPerSgRule\":null,\"minIpv4CidrPrefixLenPerSgRule\":null,\"minIpv6CidrPrefixLenPerSgRule\":null,\"auditSgDirection\":{\"type\":\"INGRESS\"}}]}"
```

Screenshot:
![Screenshot 2022-06-14 at 14 52 37](https://user-images.githubusercontent.com/5451787/173585333-2219a73e-f7d8-4c72-8ca2-824f1e21a823.png)

### Expected Behavior

Just one json map with all parameters

### Current Behavior

Reproduces map once per parameter, each time containing one configuration item

### Reproduction Steps

Create fms policy
run aws fms get-policy --policy-id <id>

### CLI version used

aws-cli/2.7.7 Python/3.9.13 Darwin/21.5.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Macos 12.4

**Comment by tim-finnigan** [comment]
Hi @jdeluyck thanks for reaching out. Could you provide the debug logs by adding `--debug` to your command? That would help give us more insight into what's going on here. Also if you can share the JSON policy used here that would also help us to reproduce the issue.

**Comment by jdeluyck** [comment]
[debug.txt](https://github.com/aws/aws-cli/files/8906210/debug.txt)

The json policy is what came out of using the web ui - I didn't try to create it through the cli client.

**Comment by tim-finnigan** [comment]
@jdeluyck I was looking at this expanded version of ManagedServiceData here: [ManagedServiceData.txt](https://github.com/aws/aws-cli/files/8911291/ManagedServiceData.txt)

It looks like each of the `preManagedOptions` you're getting back are unique. And this appears at least somewhat consistent with the example [here](https://github.com/aws-solutions/aws-firewall-manager-automations-for-aws-organizations/blob/1327a314bfb91888e660ed7c6d2157a4ba375fb8/source/resources/lib/policy_manifest.json#L140). I'm not very familiar with this service but you might want to consider opening an issue in [that repository](https://github.com/aws-solutions/aws-firewall-manager-automations-for-aws-organizations) for more guidance.

**Comment by jdeluyck** [comment]
@tim-finnigan Thanks. It just seems extremely odd to get the full set of parameters each time with just the one parameter that's set. 

I'll open a ticket on the other repo.

Kind regards,

Jan
