### ISSUE TITLE
S3 sync should have optional file-type detection

### ISSUE THREAD

**Issue by thegareth** [aws/aws-cli#7045]
### Describe the feature

When hosting a static website on CloudFront you can achieve clean URLs when by uploading objects without the `.html` extension, and allowing the content-type to guide the browser.

Often in website building workflows, an output folder is created, moved between stages and is potentially then s3 sync is used to place the objects in the bucket. Because we don't have explicit file-types in most filesystems or zip files, objects must have a file extension that indicates the content type.

I would like an optional (disabled by default to match existing behaviour) option to `--inspect-content-type` that would invoke a file-type identification library on files without an extension, and set the content type on upload

This would allow the upload of extensionless html files, allowing finer control of URLs.

### Use Case

I'm frustrated at having to write workarounds in my web publishing workflows:

If I want a URL https://example.com/target

* I can put the object in `target/index.html` and get https://example.com/target/ - the url is almost what I want, but with a trailing /
* I could post process objects in the bucket afterwards, but that's an additional manipulation, and breaks future s3 sync operations as all objects will have been renamed
* I could manually write the upload utility, which is then replicating `s3 sync`

### Proposed Solution

I propose an additional config option, something like `--inspect-content-type`
* The default would be `never`, not changing the existing behaviour and making this an optional feature
* Another option would be `no-extension` and that would invoke a file type inspector, and use that to set the mime type on upload
* I don't think this is a useful option but I include for discussions `all-objects` which would inspect all objects, even those with an extension.

If required, the aws-cli could invoke a library like https://github.com/h2non/filetype.py to infer the type of the object, and use that to set the content-type on upload

Example usage
`aws s3 sync --inspect-content-type no-extension ./my/local/directory s3://my-website-bucket`

I wonder if an option to list the allowed content types would be a safety feature, e.g. `--allowed-mime-types text/html,image/png,image/jpeg`

### Other Information

**Another potential approach:**

An option to set "default content type" for extensionless files - given this really is about setting the content type of html files, that could deliver a lot of the value with less complexity - although less flexible

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2

### Environment details (OS name and version, etc.)

MacOS 12.4

**Comment by tim-finnigan** [comment]
Hi @thegareth thanks for the feature request. I brought this up for discussion with the team  and one concern that came up was relying on another third-party dependency like the one you referenced. Also it looks like the request related to mime types might overlap with this issue: https://github.com/aws/aws-cli/issues/1249. But I think it’s worth getting input from other members of the community and thinking through alternative solutions. Please let us know if there are any points you want to clarify or expand on.

**Comment by thegareth** [comment]
@tim-finnigan the external dependancy point is well taken.

How would the fallback approach of being able to specify a 'default' mime type used for files without a file-extension work do you think?
