### ISSUE TITLE
ssm's command `command-executed` has issue with regex

### ISSUE THREAD

**Issue by andrii-glukhyi** [aws/aws-cli#7048]
### Describe the bug

According to the docs https://docs.aws.amazon.com/cli/latest/reference/ssm/wait/command-executed.html to wait for the command execution run :
```
aws ssm wait command-executed --command-id 6f3bd912-a4f9-487c-98c7-bae4db329857 --instance-id i-083e1601960282cd
```
However cli throws exception: 
```
Waiter CommandExecuted failed: An error occurred (ValidationException): 1 validation error detected: Value 'i-083e1601960282cd' at 'instanceId' failed to satisfy constraint: Member must satisfy regular expression pattern: (^i-(\w{8}|\w{17})$)|(^mi-\w{17}$)
```

### Expected Behavior

Cli should not invalidate valid instanceId

### Current Behavior

Regex fail check correct string

### Reproduction Steps

1. Start any command with SSM
2. try to wait for that command

### Possible Solution

Fix regex

### CLI version used

aws-cli/2.2.38

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
Hi @andrii-glukhyi thanks for reaching out. It looks like a similar error was also reported [here](https://github.com/aws/amazon-ssm-agent/issues/381). You could try walking through the recommendations there (registering/deregistering the machine). I'm going to transfer this issue to that repository, so if those steps don't solve the issue then someone there should have more insight into what to do about this.
