### ISSUE TITLE
Logs Validator is not seeing when user will delete two digest-files in a row

### ISSUE THREAD

**Issue by kmaciagsamsung** [aws/aws-cli#7054]
### Describe the bug

Precondition:
1. You've created a trail using s3-bucket with correct policy, started logging in it
2. You've set the flag enable-log-file-validation to true in your trail to turn on Digests

Steps To Reproduce:
1. Generate Digest for e.g. 12 hours
2. Delete 2 digest-files in a row e.g.
aws s3 rm "s3://bucket-names/AWSLogs/436118225002/CloudTrail-Digest/stg2/2022/06/20/436118225002_CloudTrail-Digest_stg2_test-konrad_stg2_20220620T072811Z.json.gz"
aws s3 rm "s3://bucket-names/AWSLogs/436118225002/CloudTrail-Digest/stg2/2022/06/20/436118225002_CloudTrail-Digest_stg2_test-konrad_stg2_20220620T062811Z.json.gz"
3. Run validate-logs command
aws cloudtrail validate-logs --trail-arn arn:aws:cloudtrail:us-east-1:062317140429:trail/test-konrad --s3-bucket konrad-trail-client-tests --account-id 062317140429 --start-time 2022-06-20T00:00:00

ACTUAL: 
```
Validating log files for trail arn:aws:cloudtrail:us-east-1:062317140429:trail/test-konrad between 2022-06-20T00:00:00Z and 2022-06-20T11:15:06Z

Digest file	s3://konrad-trail-client-tests/AWSLogs/062317140429/CloudTrail-Digest/us-east-1/2022/06/20/062317140429_CloudTrail-Digest_us-east-1_test-konrad_us-east-1_20220620T071049Z.json.gz	INVALID: not found

Results requested for 2022-06-20T00:00:00Z to 2022-06-20T11:15:06Z
Results found for 2022-06-20T00:10:49Z to 2022-06-20T10:10:49Z:

9/10 digest files valid, 1/10 digest files INVALID
```
It should be one more file with status INVALID

### Expected Behavior

```
Validating log files for trail arn:aws:cloudtrail:us-east-1:062317140429:trail/test-konrad between 2022-06-20T00:00:00Z and 2022-06-20T11:15:06Z

Digest file	s3://konrad-trail-client-tests/AWSLogs/062317140429/CloudTrail-Digest/us-east-1/2022/06/20/062317140429_CloudTrail-Digest_us-east-1_test-konrad_us-east-1_20220620T071049Z.json.gz	INVALID: not found
<one more additional file>    INVALID: not found

Results requested for 2022-06-20T00:00:00Z to 2022-06-20T11:15:06Z
Results found for 2022-06-20T00:10:49Z to 2022-06-20T10:10:49Z:

9/11 digest files valid, 2/11 digest files INVALID
```

### Current Behavior

As on description

### Reproduction Steps

As on description

### CLI version used

```

### Environment details (OS name and version, etc.)

Linux Ubuntu 18.04

**Comment by tim-finnigan** [comment]
Hi @kmaciagsamsung thanks for reaching out. Is this reproducible or did you only encounter the issue once? If you can reproduce the issue could you please share your debug logs by adding `--debug` to the cloudtrail command (with any sensitive information redacted)?

**Comment by tim-finnigan** [comment]
Since we haven't heard back in 10 days I'm going to close this. If you're still experiencing this issue please address the questions above.
