### ISSUE TITLE
s3 incorrectly handles whitespace in file name

### ISSUE THREAD

**Issue by fedorl** [aws/aws-cli#706]
Upload file with white space in key, e.g. "test space.txt"

sync parent directory s3->s3, will result in NoSuchKey error
broken both in 1.3.1 and development

1.3.1:
test space.txt A client error (NoSuchKey) occurred when calling the CopyObject operation

development:
test+space.txt A client error (NoSuchKey) occurred when calling the CopyObject operation

**Comment by johnnylyne** [comment]
I am still seeing this issue using Node AWS SDK to process a file upload to an S3 bucket within an AWS Lambda. The lambda is triggered by a file upload to an S3 bucket. When the file uploaded contains whitespace the event.records[].S3.Object.key contains + instead of space.

**Comment by algermakiputin** [comment]
As of today still seeing this issue when triggering s3 upload file to AWS lambda, for now will replace the plus sign to white space to solve this issue

**Comment by AbelGuitian** [comment]
> As of today still seeing this issue when triggering s3 upload file to AWS lambda, for now will replace the plus sign to white space to solve this issue

+1
