### ISSUE TITLE
Test failure on Python 3.11

### ISSUE THREAD

**Issue by limburgher** [aws/aws-cli#7065]
### Describe the bug

=================================== FAILURES ===================================
______ TestDataPipelineQueryObjects.test_list_more_than_one_hundred_runs _______
self = <tests.functional.datapipeline.test_list_runs.TestDataPipelineQueryObjects testMethod=test_list_more_than_one_hundred_runs>
    def test_list_more_than_one_hundred_runs(self):
        start_date = '2017-10-22T00:37:21'
        end_date = '2017-10-26T00:37:21'
        pipeline_id = 'pipeline-id'
        args = '--pipeline-id %s --start-interval %s,%s' % (
            pipeline_id, start_date, end_date
        )
        command = self.prefix + args
        object_ids = ['object-id-%s' % i for i in range(150)]
        objects = self._generate_pipeline_objects(object_ids)
    
        self.parsed_responses = [
            {
                'ids': object_ids[:100],
                'hasMoreResults': True,
                'marker': 'marker'
            },
            {
                'ids': object_ids[100:],
                'hasMoreResults': False
            },
            {'pipelineObjects': objects[:100]},
            {'pipelineObjects': objects[100:]}
        ]
    
>       self.run_cmd(command, expected_rc=None)
tests/functional/datapipeline/test_list_runs.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
awscli/testutils.py:420: in run_cmd
    self.assertEqual(
E   AssertionError: 255 != None : Unexpected rc (expected: None, actual: 255) for command: datapipeline list-runs --pipeline-id pipeline-id --start-interval 2017-10-22T00:37:21,2017-10-26T00:37:21
E   stdout:
E   stderr:
E   
E   '<' not supported between instances of 'NoneType' and 'NoneType'

### Expected Behavior

Successful tests.

### Current Behavior

[Uploading build.log…]()

### Reproduction Steps

Build with Python 3.11, run pytest

### CLI version used

1.25.17

### Environment details (OS name and version, etc.)

Fedora 37 rawhide

**Comment by nateprewitt** [comment]
Thanks for the report @limburgher. We're currently aware of the failure and are working towards resolving it. The CLI doesn't support 3.11 currently but we anticipate it being ready prior to the public release.

**Comment by limburgher** [comment]
Hi! Has there been any progress on this?

**Comment by tim-finnigan** [comment]
Is this still an issue now that https://github.com/aws/aws-cli/pull/7284 was merged?

**Comment by limburgher** [comment]
No, current releases are working.

**Comment by tim-finnigan** [comment]
Thanks @limburgher! I'll go ahead and close this then.

**Comment by limburgher** [comment]
Thank you!

**Comment by tooptoop4** [comment]
Could awscrt be updated as well? Currently aws-cli v2 requires [1] awscrt>=0.12.4,<=0.14.0. I'm looking into installing awscrt from sources on Python 3.11, and apparently 3.11 is supported since awscrt >= 0.15.0 [2].

See: https://bugs.archlinux.org/task/76618

[1] https://github.com/aws/aws-cli/blob/2.9.0/pyproject.toml#L37
[2] https://github.com/awslabs/aws-crt-python/pull/402
