### ISSUE TITLE
install script with --update causes millions of prompts

### ISSUE THREAD

**Issue by AllanZhengYP** [aws/aws-cli#7076]
### Describe the bug

This is not strictly a bug, but more of an annoying hard edge. I followed the [AWS CLI update guidance](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to update my AWS to the latest. When running the `./aws/install` script, there are countless prompts for replacing each of the `.so` files, and I cannot get rid of even with sudo.

```bash
unzip awscliv2.zip
sudo ./aws/install --update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.7M  100 44.7M    0     0   217M      0 --:--:-- --:--:-- --:--:--  218M
Archive:  awscliv2.zip
replace aws/install? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: aws/install             
replace aws/README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: aws/README.md           
replace aws/THIRD_PARTY_LICENSES? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: aws/THIRD_PARTY_LICENSES
...
# million of lines
```

I had to mannually remove the existing `aws/dist` folder to install the new version.

### Expected Behavior

The install script with `--update` should work without prompts. Or a way to get rid of all the prompt with parameter like `--yes`

### Current Behavior

Lots of prompts for replacing local files even if I run it with `sudo`.

### Reproduction Steps

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install --update

### CLI version used

aws-cli/2.7.12

### Environment details (OS name and version, etc.)

Python/3.9.11 Linux/5.4.196-119.356.amzn2int.x86_64 exe/x86_64.amzn.2 prompt/off

**Comment by tim-finnigan** [comment]
Hi @AllanZhengYP thanks for the feature request. Did you try choosing "A" when prompted with this?
`replace aws/install? [y]es, [n]o, [A]ll, [N]one, [r]ename: `

That should skip all of the prompts for you. I'm not sure if you saw that or were requesting something beyond that.

**Comment by TheDanMiller** [comment]
Not sure if this is helpful at all but what you are seeing stems from the unzip (I think). If you pass it the -u flag it should clear 
`curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip -u awscliv2.zip
sudo ./aws/install --update `
