### ISSUE TITLE
Appsync: CreatedAt used in beginsWith with several parameters requires AWSDateTime input instead of a string ==> .beginsWith.createdAt' with value 'StringValue{value=""}' is not a valid 'AWSDateTime

### ISSUE THREAD

**Issue by vincent38wargnier** [aws/aws-cli#7078]
### Describe the bug

Hi, I want to make a @key to make queries that filter "ProductsOrders" by orderId, status, paymentStatus, and that everything is sorted by createdDate.

I tried to reproduce the example from the [aws documentation](https://docs.amplify.aws/cli-legacy/graphql-transformer/key/#example-get-orders-by-customer-email-by-createdat) wich proposes the following solution to create a @key that sorts results by createdAt and at the same time sorting by other parameters.

```
# Get items for order by status by createdAt.
query ListInTransitItemsForOrder {
  listItems(orderId:"order1", statusCreatedAt: { beginsWith: { status: IN_TRANSIT, createdAt: "2019" }}) {
    items {
      orderId
      status
      createdAt
      name
    }
  }
}
```

When I do this in AppSync, I get the following error : 
`Validation error of type WrongType: argument 'createdAtStatusPaymentStatus.beginsWith.createdAt' with value 'StringValue{value='2019'}' is not a valid 'AWSDateTime'`

Why is it expecting a specific type in the beginsWith option, with cannot be a AWSDateTime type while the begins with expects a part of a AWSDateTime.
Here is the exact example I did for trying :

GraphQl Key :
`@key(name: "demo", fields: ["shopId", "createdAt", "status", "paymentStatus" ], queryField: "demo")`
AppSync Request :
<img width="280" alt="image" src="https://user-images.githubusercontent.com/33725800/176887514-7e307f95-5e70-44fc-860b-76d2f153de5b.png">

Error :
<img width="450" alt="image" src="https://user-images.githubusercontent.com/33725800/176887186-708899ea-22e0-4fd5-adb0-14f9df51e45f.png">

Thank you.

### Expected Behavior

Success

### Current Behavior

<img width="450" alt="image" src="https://user-images.githubusercontent.com/33725800/176887186-708899ea-22e0-4fd5-adb0-14f9df51e45f.png">

### Reproduction Steps

Create this GraphQl table :
```

type productsOrder @model 
@key(name: "demo", fields: ["shopId", "createdAt", "status", "paymentStatus" ], queryField: "demo")
 {
    id: ID!
    shopId: String!
    paymentStatus: String
    status: String
    createdAt: AWSDateTime!
  }
```

And make this AppSync Request :
<img width="280" alt="image" src="https://user-images.githubusercontent.com/33725800/176887514-7e307f95-5e70-44fc-860b-76d2f153de5b.png">

### Possible Solution

create a field that stores the createdAt value in a string to sort alphabeticaly by this new field instead of by createdAt field

### CLI version used

7.6.19

### Environment details (OS name and version, etc.)

mac OS

**Comment by tim-finnigan** [comment]
Hi @vincent38wargnier thanks for reaching out. It looks like this issue was meant for [AWS Amplify](https://github.com/aws-amplify), specifically the [Amplify CLI](https://github.com/aws-amplify/amplify-cli/issues) based on the documentation page you linked to. I recommend creating an issue in that repository. Also it looks like that is a legacy documentation page and [this page](https://docs.amplify.aws/cli/graphql/data-modeling/) is the updated version. Hope that helps!
