### ISSUE TITLE
quicksight update-template-permissions gives validation fail and error

### ISSUE THREAD

**Issue by jesperalmstrom** [aws/aws-cli#7079]
### Describe the bug

When following this blob post (https://aws.amazon.com/blogs/big-data/migrate-amazon-quicksight-across-aws-accounts/) to update template permissions it with a template permission json file i get validation failed.

Trying to use the grant permission parameter input works well.

I remember that I have had similar errors with other cli commands where input file fails and input parameters work.

### Expected Behavior

Permission is granted to the quicksight template

### Current Behavior

When using a permission config file
```
aws quicksight update-template-permissions --grant-permissions file://./template_permissions.json --profile myprofile --aws-account-id 87654321 --region eu-central-1 --template-id my_dashboard

Error parsing parameter '--grant-permissions': Expected: '=', received: '[' for input:
arn:aws:quicksight:eu-central-1:87654321:template/cost_dashboard
[
^
  {
    "Principal": "arn:aws:iam::12345678:root",
    "Actions": ["quicksight:UpdateTemplatePermissions","quicksight:DescribeTemplate"]
  }
]
```
This command works as expected
```
aws quicksight update-template-permissions --grant-permissions Pricipal="arn:aws:iam::12345678:root",Actions="quicksight:UpdateTemplatePermissions","quicksight:DescribeTemplate" --profile myprofile --aws-account-id 87654321 --region eu-central-1 --template-id my_dashboard
```

### Reproduction Steps

Follow the blog post. 
https://aws.amazon.com/blogs/big-data/migrate-amazon-quicksight-across-aws-accounts/

### CLI version used

aws-cli/2.7.12 

### Environment details (OS name and version, etc.)

MacOS 12.4

**Comment by jesperalmstrom** [comment]
The blog post is not missing any info regarding permission. Trying to follow the steps 8 and 9 in chapter 2c does not work.
Create a template permission file (step 8):
```
[
{
"Principal": "arn:aws:iam::86*******55:root",
"Actions": ["quicksight:UpdateTemplatePermissions","quicksight:DescribeTemplate"]
}
]
```
Try to run the command (step 9)
```
aws quicksight update-template-permissions --aws-account-id 31********64 --template-id "Sporting_event_ticket_info_template" --grant-permissions file://./TemplatePermission.json --profile default
```

When testing other methods I skipped the TemplatePermission.json file and tried to run the short syntax, it worked

> Shorthand Syntax:
Principal=string,Actions=string,string ...

**Comment by tim-finnigan** [comment]
Thanks @jesperalmstrom for following up and clarifying. That error you referenced (`Expected: '=', received: '[' for input`) has been reported in several [other issues](https://github.com/aws/aws-cli/issues?q=is%3Aissue+%22Expected%3A+%27%3D%27%2C+received%3A+%27%5B%27+for+input%3A%22) and generally is caused by a quoting or encoding issue. I can reach out to the Quicksight team and see if that could be clarified in the blog post. Please let me know if you had any other questions.
