### ISSUE TITLE
Cross account assume role fails because session duration does not have the default value of 1 hour

### ISSUE THREAD

**Issue by hossein-jazayeri** [aws/aws-cli#7100]
### Describe the bug

Accessing resources of a non-SSO account from an `SSO` account fails unless `--duration-seconds` argument is set for the second `assume-role` command.

### Expected Behavior

There should not be a need to explicitly specify `--duration-seconds`.
It should have a default value i.e. 1 hour.

### Current Behavior

Assuming the second role, returns the following error:
```
An error occurred (ExpiredToken) when calling the AssumeRole operation: The security token included in the request is expired
```

### Reproduction Steps

Assuming, we have two accounts: an `SSO` account and a non-SSO, `normal` account.
In order to access resources in the `normal` account from `SSO` account, take the following steps:

In the SSO account, having a role called `sso-role` with the following permissions policies:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::normal-account-id:role/normal-account-role"
        }
    ]
}
```
And the following trust policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::sso-account-id:root"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
In the `normal account`, having `normal-account-role` role with the following trust policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::sso-account-id:role/sso-role"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
Now, in order to access resources in the `normal` account from `SSO` account, first assume `sso-role` using `SSO` account's credentials:
```bash
export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws --profile sso-account sts assume-role --role-arn arn:aws:iam::sso-account-id:role/sso-role --role-session-name session1 --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text ))
```
Confirm it:
```bash
aws sts get-caller-identity

{
    "UserId": "...:session1",
    "Account": "sso-account-id",
    "Arn": "arn:aws:sts::sso-account-id:assumed-role/sso-role/session1"
}
```
Try to assume the second role `normal-account-role` without `--duration-seconds`:
```bash
export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn arn:aws:iam::normal-account-id:role/normal-account-role --role-session-name session2 --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text))
```
The command works when `--duration-seconds` is set and resources in `normal` account can be accessed.

### Possible Solution

Having a default value (i.e. 1 hour) for `--duration-seconds` solves the problem.

### CLI version used

2.4.13

### Environment details (OS name and version, etc.)

Python/3.8.8 Linux/5.10.102.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off

**Comment by tim-finnigan** [comment]
Hi @hossein-jazayeri thanks for reaching out. In the `assume-role` [documentation](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html) it notes that the default value for `--duration-seconds` is 3600 seconds (1 hour). If you can provide your debug logs by adding `--debug` to the command (with any sensitive info redacted) that could give more insight into the behavior here.

**Comment by tim-finnigan** [comment]
Since we haven’t heard back in a few weeks I’m going to close this issue. If you’re still experiencing this issue please let us know and we can revisit it. Thanks!
