### ISSUE TITLE
"latest" docs don't actually point to latest/v2

### ISSUE THREAD

**Issue by umdstu** [aws/aws-cli#7121]
### Describe the bug

It was recently brought to my attention that google search results for aws cli documentation populates results that often point to `latest`. Visiting https://docs.aws.amazon.com/cli/latest/ for documentation however doesn't give you the latest docs (v2), it gives you the previous version of docs (v1).

### Expected Behavior

I expected `latest` to point to your latest docs, in this case `v2`, or redirect to the v2 page.

### Current Behavior

However, currently when you view the docs, it leaves you on `v1` with a big ol banner saying so, and to go look at the v2 docs instead.

### Reproduction Steps

Click on the [docs](https://docs.aws.amazon.com/cli/latest/) url. 

### Possible Solution

Have `latest` point to, or redirect to, v2, instead of v1.

### CLI version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by tim-finnigan** [comment]
Hi @umdstu thanks for reaching out. I agree that it is somewhat confusing to see 'latest' in the v1 link but the v1/v2 documentation URLs are unlikely to change at this point. Maybe when v1 is deprecated the team will consider a new approach here. There was also some discussion about adding documentation links for specific CLI minor versions which I think would be helpful. But for now we will continue using the banner to alert users to the v2 documentation link.
