### ISSUE TITLE
aws s3api silient failure when typo of --version-id option is specified

### ISSUE THREAD

**Issue by cplaws** [aws/aws-cli#7128]
### Describe the bug

When using aws s3api, where options are abbreviated there is inconsistent output where there is expected to be an error.

Outputs captured from 
```
 % aws --version
aws-cli/2.7.18 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off
```

`aws s3api head-object --bucket BUCKET_NAME --key KEY_NAME --version-id KEY_VERSION_ID`
Works as expected 

`aws s3api head-object --bucket BUCKET_NAME --k KEY_NAME --version-id KEY_VERSION_ID`
Works

`aws s3api head-object --bucket BUCKET_NAME --key KEY_NAME --version-id KEY_VERSION_ID`
Works 

`aws s3api head-object --bucket BUCKET_NAME --key KEY_NAME --version-i KEY_VERSION_ID`
Works 

`aws s3api head-object --bucket BUCKET_NAME --key KEY_NAME --version- KEY_VERSION_ID`
Works 

### Expected Behavior

For each option that has a typo, would expect a helpful error message to guide the end-user.
Below is an example from an intentional misspelling of version as versoin

```
aws s3api head-object --bucket BUCKET_NAME --k KEY_NAME --versoin-id KEY_VERSION_ID
Output:

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --versoin-id, KEY_VERSION_ID

```

### Current Behavior

The below examples show the silent failure of the --version-id tag when abbreviated.

`aws s3api head-object --bucket BUCKET_NAME --key KEY_NAME --version KEY_VERSION_ID`
Output:` aws-cli/2.7.18 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off`

Does not work, output is not useful to end-user 

`aws s3api head-object --bucket BUCKET_NAME --k KEY_NAME --versio KEY_VERSION_ID`
Output: `aws-cli/2.7.18 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off`

Does not work,  output is not useful to end-user 

### Reproduction Steps

Above code snippets should suffice to assist with reproduction.

### Possible Solution

Consistent Error for either abbreviated options, typo options to guide the end user.

### CLI version used

aws-cli/2.7.18 Python/3.9.11 Darwin/20.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS, 11.6.5

**Comment by tim-finnigan** [comment]
Hi @cplaws thanks for reporting this. I'm not sure if an error should be thrown for abbreviated parameters but maybe calling out this behavior in the response output or documentation would be helpful.

**Comment by cplaws** [comment]
Thanks for reviewing @tim-finnigan.  I'd think it be useful for the end user to consistently allow for abbreviated parameters or provide useful output that can guide the user when an abbreviation is not recognized by aws cli.  The silent failure scenario leaves the impression that the command worked when it was actually did not.  

Preference would be for the response output to provide real-time guidance.  If the documentation also provides explanation of what parameters can be abbreviated or would be recognized that would also be a plus.

**Comment by tim-finnigan** [comment]
Checking in on this issue again. Is this specific to s3api or what other services/commands have you seen this behavior? Also have you considered using [command completion](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html) or [auto-prompt mode](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-prompting.html)?

**Comment by tim-finnigan** [comment]
Closing as we have not heard back on this issue.
