### ISSUE TITLE
aws configure sso is not working with custom user portal URL

### ISSUE THREAD

**Issue by jagin** [aws/aws-cli#7129]
### Describe the bug

I'm trying to execute `aws configure sso` and getting the bug as follow:

```
❯ aws configure sso
SSO start URL [None]: https://my-custom-url.awsapps.com/start
SSO Region [None]: eu-central-1

An error occurred (InvalidRequestException) when calling the StartDeviceAuthorization operation: 
```

but if I use original (AWS generated) portal URL with Identity store ID like: https://d-##########.awsapps.com/start
everything is working fine

### Expected Behavior

`aws configure sso` is working fine with custom user portal URL in eu-central-1 region (maybe only this region has an issue?)

### Current Behavior

`aws configure sso` with custom user portal URL in eu-central-1 region returns error:

```
An error occurred (InvalidRequestException) when calling the StartDeviceAuthorization operation:
```

### Reproduction Steps

1. Setup SSO in region eu-central-1
2. Setup custom user portal URL
3. Try to `aws configure sso` with custom url

### CLI version used

aws-cli/2.7.18 Python/3.10.5 Darwin/21.5.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS Version 12.4

**Comment by kdufourbe** [comment]
+1 exact same issue since today

**Comment by ArzelaAscoIi** [comment]
Same issue since today 👍

**Comment by tim-finnigan** [comment]
@jagin thanks for reaching out. That error has been reported a few times before (see https://github.com/aws/aws-cli/issues/4710 and https://github.com/aws/aws-cli/issues/4784). Are you all integrating SSO with Google or another third-party service? And are you all using the eu-central-1 region as well? @kdufourbe and @ArzelaAscoIi please let us know if there's any more information you can provide related to this.

**Comment by kdufourbe** [comment]
Hi,

I'm using the AWS SSO Users and not a third party integration for authentication. And yes, I'm using eu-central-1.


Kind regards,
Kristof

**Comment by jagin** [comment]
I'm also using plain AWS SSO on eu-central-1.

**Comment by joa44741** [comment]
I'm having the same issue with AWS SSO connected to Azure AD. 
Region is eu-central-1

**Comment by stefan-schaefer-de** [comment]
WS SSO connected to Azure AD, Region is eu-central-1.

**Comment by stefan-schaefer-de** [comment]
Tested again.. seems to be working again

**Comment by ArzelaAscoIi** [comment]
Can confirm! Works for me too!

**Comment by tim-finnigan** [comment]
Thanks for letting us know! Glad it is working again for some of you. I haven't been able to find any reports related to this issue, either internally or externally. It sounds like the commonality among at least some users involved SSO with Azure AD in eu-central-1. We can keep this issue open for now to see if any more reports come in or if anyone can share any information on why this may have occurred.

**Comment by jagin** [comment]
It looks like it is working now so I can assume that it was not aws-cli bug but some peculiarities with SSO in eu-central-1 region

**Comment by kdufourbe** [comment]
Working again here as well. I also raised a technical support issue on AWS and also got the confirmation that the engineering team resolved the issue.

**Comment by tim-finnigan** [comment]
Ok thanks for following up here. I'll go ahead and close this issue since things are working again.
