### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

### ISSUE THREAD

**Issue by skbkbs** [aws/aws-cli#7132]
### Describe the bug

Error on request:
Traceback (most recent call last):
  File "C:\Users\空白\Desktop\KB\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\空白\Desktop\KB\venv\lib\site-packages\werkzeug\serving.py", line 325, in execute
    write(data)
  File "C:\Users\空白\Desktop\KB\venv\lib\site-packages\werkzeug\serving.py", line 300, in write
    self.wfile.write(data)
  File "C:\Users\空白\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "C:\Users\空白\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\空白\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

### Expected Behavior

I tried to fix the problem, but the error code always reported 2396

### Current Behavior

Errors are filed in the browser to get the server content

### Reproduction Steps

from flask import Flask, render_template

app = Flask(__name__)
app.config['SERVER_NAME'] = 'skbkbs.top:5001'

@app.route('/')
def welcome():
    return 'HELLO WORLD'

if __name__ == '__main__':
    app.run(port=5001, debug=True, ssl_context = (r'C:\Users\空白\Desktop\KB\0\xxxx.crt', r'C:\Users\空白\Desktop\KB\0\xxxx.key'))

### Additional Information/Context

I ran the code when I got it wrong and my python version is 3.10

### CLI version used

 10.0.22622

### Environment details (OS name and version, etc.)

python3.10 flask2.1.3 win11

**Comment by tim-finnigan** [comment]
Hi @skbkbs thanks for reaching out. That error has been reported [several times](https://github.com/aws/aws-cli/issues?q=is%3Aissue+%22EOF+occurred+in+violation+of+protocol%22+is%3Aclosed). Have you tried looking through those issues for solutions? I would first confirm that you're using the correct region. Do you have proxies configured or a custom ca bundle? If you provide the debug logs by adding `--debug` to your command then we could look more into this.

**Comment by skbkbs** [comment]
I didn't configure any proxies as well as the custom ca bundle

**Comment by tim-finnigan** [comment]
Hi - checking in again on this issue. It seems like that error generally occurs due to local system configuration issues. Could you share your debug logs for us to investigate further?

**Comment by tim-finnigan** [comment]
As we haven't heard back in a few weeks I'm going to close this issue. If you're still affected by the issue please let us know and share your debug logs as requested above. Thanks!
