### ISSUE TITLE
aws ec2 no longer accepting vpc-id as filter value for describe-security-groups

### ISSUE THREAD

**Issue by webdog** [aws/aws-cli#7137]
### Describe the bug

Experiencing the same behavior as seen in #3225

The filter worked until approximately a week ago. This command in question is part of an automation script that deletes security groups connected to Load balancers. I noticed this failing after load balancers were no longer deleting from my account because of the associated load balancer still being present, and then noticed the CLI error when checking my logs.

### Expected Behavior

describe-security-groups should accept vpc-id as a filter, as it previously has before.

### Current Behavior

>An error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: vpc-id

Debug log attached:
[debug.log](https://github.com/aws/aws-cli/files/9194422/debug.log)

### Reproduction Steps

`aws ec2 describe-security-groups --filters Name=vpc-id,Values=<vpc_id> --debug`

### CLI version used

aws-cli/2.6.1 Python/3.9.12 Darwin/20.6.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS 11.6.6

**Comment by tim-finnigan** [comment]
Hi @webdog thanks for reaching out. I think you might be getting that InvalidParameterValue error because the command is expecting a vpc-id in the form of "vpc-12345678". Does the VPC you're trying to filter on not follow that format?

**Comment by webdog** [comment]
Yep! That was it. Thanks for the help ✨
