### ISSUE TITLE
Alphabets in secret version id are converted UPPER_CASE only when `--output text` is specified

### ISSUE THREAD

**Issue by goldeneggg** [aws/aws-cli#7138]
### Describe the bug

I can't understand if this behavior is a bug or a spec so please let me know 🙏 

When I ran the `aws secretsmanager list-secrets` or `aws secretsmanager describe-secret` command with `--output text` option, all the alphabets contained in the version id are converted to UPPER_CASE.

```sh
aws secretsmanager list-secrets --query 'SecretList[*].SecretVersionsToStages' --output text
```
```
0123ABCD-XXX1-XXX2-XXX3-XXXXXX444444    AWSPREVIOUS
1234EFGH-XXX1-XXX2-XXX3-XXXXXX444444    AWSCURRENT
```

Other than `text` (e.g. `json`, `yaml` and others), I can get the expected id with lower_case alphabets.

```sh
aws secretsmanager list-secrets --query 'SecretList[*].SecretVersionsToStages' --output json
```
```json
    {
        "0123abcd-xxx1-xxx2-xxx3-xxxxxx444444": [
            "AWSPREVIOUS"
        ],
        "1234efgh-xxx1-xxx2-xxx3-xxxxxx444444": [
            "AWSCURRENT"
        ]
    }
```

### Expected Behavior

All alphabets in version id are lower_case with `--output text` option (like `--output json` option).

### Current Behavior

All alphabets in version id are UPPER_CASE with `--output text` option.

### Reproduction Steps

1. Run `aws secretsmanager list-secrets --query 'SecretList[*].SecretVersionsToStages' --output json`
    - all alphabets in version id are lower_case
2. Run `aws secretsmanager list-secrets --query 'SecretList[*].SecretVersionsToStages' --output text`
    - all alphabets in version id are UPPER_CASE (__is current unexpected behavior__)
3. I can get the same result by running `describe-secret` instead of `list-secrets`

### CLI version used

aws-cli/2.7.17 Python/3.10.5 Darwin/21.5.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

OS X Monterey 12.4 (Intel Mac)

**Comment by tim-finnigan** [comment]
Hi @goldeneggg thanks for reaching out. In terms of the values you're referring to (AWSPREVIOUS, AWSCURRENT), I believe that those are supposed to be uppercase as per the Secrets Manager documentation: https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html.

**Comment by goldeneggg** [comment]
@tim-finnigan 

Thank you for your response.

I was not referring to the strings "AWSPREVIOUS" and "AWSCURRENT".
I was referring to the version id in UUID format.

 For example, as mentioned in the description, if the version id is registered as `0123abcd-xxx1-xxx2-xxx3-xxxxxxxx444444`, then

- If `--output-json` is specified, `0123abcd-xxx1-xxx2-xxx3-xxxxxx444444` will be returned.
- If `--output-text` is specified, `0123ABCD-XXX1-XXX2-XXX3-XXXXXX444444` is returned (all letters are converted to upper case).

I expect the version id to be returned in lower case even if I specify `--output-text`.

**Comment by goldeneggg** [comment]
@tim-finnigan 
Thanks for your reply. I understood your suggestion.

On the other hand, the `--version-id` option of the `aws secretsmanager get-secret-value` command strictly determines the case of the version_id.
For example, if there is a version_id of `1234abcd-xxxx-999999-rrrrrr-22222222ddddddd`, then 

- The `aws secretsmanager get-secret-value --secret-id dummy-secret --version-id 1234abcd-xxxx-999999-rrrrrr-22222222ddddddddddd`(lower case version_id) command will succeed.
- The `aws secretsmanager get-secret-value --secret-id dummy-secret --version-id 1234ABCD-XXXX-9999-RRRRRR-222222DDDDDD`(UPPER CASE version_id) command __will return "An error occurred ( ResourceNotFoundException)".__

In my personal opinion, I thought it would be better to unify either upper or lower case letters, or to not strictly distinguish between upper and lower case letters.

Please see also https://www.uuidtools.com/what-is-uuid#case-sensitive and https://github.com/ramsey/uuid/issues/131

**Comment by tim-finnigan** [comment]
Thanks @goldeneggg for the feedback. I see what you're saying, but any changes involving service API functionality would have to come from that team. I think it's unlikely that the Secrets Manager team would consider changing the version ID to be case insensitive, but I suggest reaching out to that team through the recommended channels here: https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html#support-and-feedback.

**Comment by tim-finnigan** [comment]
Checking in as there hasn't been any activity here for a while. To summarize up to now, the `--output text` option will set the IDENTIFIER in uppercase as documented here: https://docs.aws.amazon.com/cli/v1/userguide/cli-usage-output-format.html#text-output. As an alternative you can use `--output json`. In terms of what the API itself is returning, it would be a breaking change at this point for the service to change how the version IDs are processed.
