### ISSUE TITLE
budgets describe-notifications-for-budget doesn't contains "ThresholdType" field

### ISSUE THREAD

**Issue by takezoux2** [aws/aws-cli#7145]
### Describe the bug

"ThresholdType" field is NOT contained In budgets describe-notifications-for-budget response according to [Reference](https://docs.aws.amazon.com/cli/latest/reference/budgets/describe-notifications-for-budget.html)

### Expected Behavior

ThresholdType will be "PERCENTAGE" or "ABSOLUTE_VALUE".

### Current Behavior

No "ThresholdType" is returned.

### Reproduction Steps

```
aws budgets describe-notifications-for-budget --account-id MY_ACCOUNT_ID --budget-name MY_BUDGET_NAME
```

will return
```
{
    "Notifications": [
        {
            "NotificationType": "ACTUAL",
            "ComparisonOperator": "GREATER_THAN",
            "Threshold": 100.0,
            "NotificationState": "OK"
        },
        {
            "NotificationType": "ACTUAL",
            "ComparisonOperator": "GREATER_THAN",
            "Threshold": 300.0,
            "NotificationState": "OK"
        },
        ...
}

```

### Possible Solution

ThresholdType is contained in response

### CLI version used

aws-cli/2.4.18 Python/3.9.10 Darwin/21.6.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Mac OS

**Comment by aBurmeseDev** [comment]
Hi @takezoux2, thanks for reporting this. It seems to me that `ThresholdType` only returns when it’s set to `ABSOLUTE_VALUE` thresholds and does not return for `PERCENTAGE` thresholds. Could you please confirm that your `ThresholdType` is set to `PERCENTAGE` which is why it didn’t return?

Here’s an example after changing the type to `ABSOLUTE_VALUE` :
```
aws budgets describe-notifications-for-budget --account-id ACCOUNT_ID --budget-name aws-budget
{
    "Notifications": [
        {
            "NotificationType": "ACTUAL",
            "ComparisonOperator": "GREATER_THAN",
            "Threshold": 1.0,
            "ThresholdType": "ABSOLUTE_VALUE",
            "NotificationState": "OK"
        }
    ]
}
```
