### ISSUE TITLE
Incorrect data type reference for  aws iot create-domain-configuration https://docs.aws.amazon.com/cli/latest/reference/iot/create-domain-configuration.html

### ISSUE THREAD

**Issue by ychamare** [aws/aws-cli#7148]
### Describe the bug

Wrong data type reference for API input value 
![Screenshot 2022-07-30 232004](https://user-images.githubusercontent.com/54070011/182011396-6f651c08-7582-48ca-aada-cc7434a7abb8.png)

### Expected Behavior

--domain-name (string)    must be of type STRING

### Current Behavior

--domain-name (string)   does not accept string , only list. 

### Reproduction Steps

 used 

aws iot create-domain-configuration \
--domain-configuration-name "my-custom-domain" \
--domain-name "custom.iot.XYZ.people.aws.dev" \
--server-certificate-arns $CERT_ARN \
--service-type DATA  

Returns -> An error occurred (InvalidRequestException) when calling the CreateDomainConfiguration operation: Must provide a valid domain name to configure.

Then Used 

aws iot create-domain-configuration \
--domain-configuration-name "my-custom-domain" \
--domain-name custom.iot.XYZ.people.ABC.dev  \
--server-certificate-arns $CERT_ARN \
--service-type DATA  

accepted resourced created

### CLI version used

aws-cli/2.0.30 Python/3.7.3 Linux/4.14.287-215.504.amzn2.x86_64 botocore/2.0.0dev34

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by tim-finnigan** [comment]
Hi @ychamare - is "custom.iot.XYZ.people.ABC.dev" a valid domain name? Is there an example you can provide of this command working when you pass a list? 

Also I see that you're a member of AWS so if there is an issue with the API functionality or documentation then you should create an internal ticket with that service team to address it.

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a few weeks I'm going to close this issue. Please follow up on the comment above if you'd like to discuss this further. Thanks!
