### ISSUE TITLE
 aws cognito-idp update-user-pool  AttributesRequireVerificationBeforeUpdate=email does not work

### ISSUE THREAD

**Issue by mkdirJava** [aws/aws-cli#7151]
### Describe the bug

As a AWS cli user
When I execute the command
```
aws cognito-idp update-user-pool --user-pool-id *** --user-attribute-update-settings AttributesRequireVerificationBeforeUpdate=email

```
Then I get the error

```
An error occurred (InvalidParameterException) when calling the UpdateUserPool operation: All attributes in AttributesRequireVerificationBeforeUpdate must exist in AutoVerifiedAttributes

```

Befire I describe the cognito pool I can describe the cognito pool and see

```
...
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": []
        },

...
``` 

### Expected Behavior

As a AWS cli user
When I execute the command
```
aws cognito-idp update-user-pool --user-pool-id *** --user-attribute-update-settings AttributesRequireVerificationBeforeUpdate=email

```
Then I should see this update on my console and have the pool behave appropreiatley
```
aws cognito-idp describe-user-pool --user-pool-id ***
```

### Current Behavior

As a AWS cli user
When I execute the command
```
aws cognito-idp update-user-pool --user-pool-id *** --user-attribute-update-settings AttributesRequireVerificationBeforeUpdate=email

```
Then I get the error

```
An error occurred (InvalidParameterException) when calling the UpdateUserPool operation: All attributes in AttributesRequireVerificationBeforeUpdate must exist in AutoVerifiedAttributes

```

Befire I describe the cognito pool I can describe the cognito pool and see

```
...
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": []
        },

...
``` 

### Reproduction Steps

As a AWS cli user
When I execute the command
```
aws cognito-idp update-user-pool --user-pool-id *** --user-attribute-update-settings AttributesRequireVerificationBeforeUpdate=email

```
Then I get the error

```
An error occurred (InvalidParameterException) when calling the UpdateUserPool operation: All attributes in AttributesRequireVerificationBeforeUpdate must exist in AutoVerifiedAttributes

```

Befire I describe the cognito pool I can describe the cognito pool and see

```
...
        "AutoVerifiedAttributes": [
            "email"
        ],
        "UsernameAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "UserAttributeUpdateSettings": {
            "AttributesRequireVerificationBeforeUpdate": []
        },

...
``` 

### CLI version used

2.7.20

### Environment details (OS name and version, etc.)

Windows 10

**Comment by tim-finnigan** [comment]
Hi @mkdirJava thanks for reaching out. Can you confirm that you're using the correct cognito-idp resource and corresponding region in the AWS CLI? If you could provide your debug logs (with any sensitive info redacted) by adding `--debug` to that command then it might give us more insight into what's going on.

**Comment by mkdirJava** [comment]
Hi there @tim-finnigan 
to supply the below flag as well
--auto-verified-attributes


aws cognito-idp update-user-pool --user-pool-id ***--user-attribute-update-settings=email --auto-verified-attributes=email

**Comment by mkdirJava** [comment]
@tim-finnigan  
I am happy to close this ticket, if you are ?

**Comment by tim-finnigan** [comment]
Hi @mkdirJava thanks for following up, sure I can go ahead and close this. If you had any other questions please let me know.
