### ISSUE TITLE
(ResourceNotFoundException) when calling the UpdateImageGenerationConfiguration operation

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [aws/aws-cli#7159]
### Describe the bug

galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration  --cli-input-
--cli-input-json  --cli-input-yaml  
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration  --cli-input-json help

Error parsing parameter 'cli-input-json': Invalid JSON received.
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ 

### Expected Behavior

aws kinesisvideo update-image-generation-configuration --cli-input-json ./update-image-generation-input.json
i wish this command can work

### Current Behavior

galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration --cli-input-json ./update-image-generation-input.json 

Error parsing parameter 'cli-input-json': Invalid JSON received.
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration  --cli-input-
--cli-input-json  --cli-input-yaml  
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration  --cli-input-json help

Error parsing parameter 'cli-input-json': Invalid JSON received.
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws --version
aws-cli/2.7.20 Python/3.9.11 Linux/5.15.0-25-generic exe/x86_64.ubuntu.22 prompt/off
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$

### Reproduction Steps

the json message:
{
 "StreamName": "ExampleStream",
 "ImageGenerationConfiguration":
 {
  "Status": "ENABLED",
  "DestinationConfig":
  {
   "DestinationRegion": "ap-southeast-1",
   "Uri": "s3://0803picfromkvs"
  },  
  "SamplingInterval": 3000,
  "ImageSelectorType": "PRODUCER_TIMESTAMP",
  "Format": "JPEG",
  "FormatConfig": {
                "JPEGQuality": "80"
       },
  "WidthPixels": 640,
  "HeightPixels": 480 
 }
} 

### Possible Solution

fix the bug

### CLI version used

aws-cli/2.7.20 Python/3.9.11 Linux/5.15.0-25-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

ubuntu 22.04

**Comment by xiaoyaodingchunqiu** [comment]
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ aws kinesisvideo update-image-generation-configuration --cli-input-json file://./update-image-generation-input.json 

An error occurred (ResourceNotFoundException) when calling the UpdateImageGenerationConfiguration operation: The requested stream is not found or not active.
galen@galen-RedmiBook-Pro-14S:~/s3cmdtest$ 

after i change the encode from utf-8 to ansi, it works, but get new err:
An error occurred (ResourceNotFoundException) when calling the UpdateImageGenerationConfiguration operation: The requested stream is not found or not active.

**Comment by tim-finnigan** [comment]
Hi @xiaoyaodingchunqiu thanks for reaching out. A `ResourceNotFoundException` is often caused when your configured region does not match the region where your resource resides. Can you confirm that your AWS CLI environment is configured to use the same region where your resource is located?

**Comment by xiaoyaodingchunqiu** [comment]
i have solved this problem
