### ISSUE TITLE
Allow disabling parameter validation

### ISSUE THREAD

**Issue by phemmer** [aws/aws-cli#717]
It would be nice to have an option to disable parameter validation for JSON parameters.
An example of why this is desired would be the new ELB `ConnectionDraining` parameter. The botocore json data hasn't been updated with this new parameter yet, and so attempting to set it through `aws elb modify-load-balancer-attributes` fails with:

> Unknown key 'ConnectionDraining' for param 'LoadBalancerAttributes'.  Must be one of:  CrossZoneLoadBalancing, AccessLog

After modifying the botocore `2012-06-01.json` file by hand to add the parameter, it works just fine.

**Comment by bowman** [comment]
What if I supply the JSON with `--cli-input-json`?
