### ISSUE TITLE
Set value of a nested field from file

### ISSUE THREAD

**Issue by Strunevskiy** [aws/aws-cli#7171]
### Describe the bug

As a user of CLI, I want to set a value of a nested field in a request from file.

### Expected Behavior

Set a value of a field from file even if a field is nested. So I wanted to set a value to CodeBlock from a file.

```
{
    "InstanceId": "",
    "Description": "",
    "InstanceConfiguration": {
        "CodeBlock": ""
    }
}
```

### Current Behavior

Right now you can do it for top level fields like this
https://aws.amazon.com/blogs/developer/best-practices-for-local-file-parameters/

```
aws ec2 run-instances --image-id ami-b66ed3de 
    --instance-type m3.medium 
    --key-name mykey 
    --security-groups my-security-group 
    --user-data file://myshellscript
```

### Reproduction Steps

Set a value from a file for nested fields

```
aws ec2 run-instances --image-id ami-b66ed3de 
    --instance-type m3.medium 
    --key-name mykey 
    --security-groups my-security-group 
    --user-data file://myshellscript
```

### CLI version used

aws-cli/2.7.0 Python/3.9.11 Darwin/21.4.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MAC

**Comment by tim-finnigan** [comment]
Hi @Strunevskiy thanks for reaching out. I'm not sure if I fully understand your use case - do you need this ability for `aws ec2 run-instances` specifically or is there another command/parameter that you were seeking support for?
