### ISSUE TITLE
prints additional None with --output text, --query and --max-items

### ISSUE THREAD

**Issue by gonrial** [aws/aws-cli#7172]
### Describe the bug

Running a command with `--max-items`, `--output text` and `--query` produce an additional line with the string `None`. Any other combination does not show that string.

Also appeared as #5654

### Expected Behavior

```
arn:aws:ecs:<region>:<account>:task/<cluster>/<taskId>
```

### Current Behavior

```
arn:aws:ecs:<region>:<account>:task/<cluster>/<taskId>
None <-----This is the extra string
```

### Reproduction Steps

```
aws ecs list-tasks --cluster <cluster> --query 'taskArns' --output text --max-items 1
```
Where max-items should be n-1 elements from the existing tasks.

### CLI version used

aws-cli/2.7.21

### Environment details (OS name and version, etc.)

Python/3.9.11 Linux/5.15.0-43-generic exe/x86_64.ubuntu.22 prompt/off

**Comment by tim-finnigan** [comment]
Hi @gonrial thanks for reaching out. I tried to reproduce this issue on v2.7.21 but wasn't able to. Could you share your debug logs (with any sensitive info redacted) by adding `--debug` to your command?

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a few weeks I'm going to close this issue. Please let us know if you're still encountering this issue and if so we can revisit it. Thanks!
