### ISSUE TITLE
aws v2 as snap package for cpus: arm, arm64, amd64.

### ISSUE THREAD

**Issue by talregev** [aws/aws-cli#7177]
### Describe the feature

You have snap package from amazon of aws cli:
https://snapcraft.io/aws-cli

Please update this for v2 and compile for more cpus: arm, arm64 and am64.

I successful compile aws-cli 2 on snap package for arm. 
I can share it with you, also make a package here on the repo. Also make it for the ci.

### Use Case

snap package for arm, arm64, amd64.

### Proposed Solution

snap package. 

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2

### Environment details (OS name and version, etc.)

linux.

**Comment by tim-finnigan** [comment]
Hi @talregev thanks for the feature request and creating those PRs. Unfortunately we cannot accept PRs that involve packaging-related changes. We plan to update our community contribution guide to clarify that as well. There is an existing feature request for v2 snap support we are tracking here: https://github.com/aws/aws-cli/issues/6010. More team discussion is required to determine if and when this would be implemented. Please refer to that issue for updates going forward and 👍 or comment if you had any additional feedback to share.
