### ISSUE TITLE
Feature request -- command-line equivalent of "Download to CSV" option for elements in QuickSight dashboards/analyses

### ISSUE THREAD

**Issue by jackOxbury** [aws/aws-cli#7186]
### Describe the feature

The ability to invoke the QS "Export to CSV" feature 

![kdojklfdj](https://user-images.githubusercontent.com/111055279/184118286-20a972c8-a566-40a5-9fc7-d44ba71ff225.png)

from the command line, e.g. GetDashboardCSV or similar. 

### Use Case

To get data from QS elements as a common data format (CSV, JSON...) and load the data file into whatever platform and then to do custom analytics on that.

As QS offers Custom SQL, calculated fields, JOINS in the UI, _etc._ it creates its own separate "source of truth" if you wish to wish the generated datasets elsewhere. To use the data in QS figures you have to painstakingly recreate the logic that produces the values of that dataset in QS using something like pure SQL or lambda code, and then maintain the two simultaneously. 

My particular use case is that some large amount of time is spent in my organisation manually transferring figures from QS reports to PowerPoint presentations and risk-tracking software. I would like to be able to take a snapshot of the data in QS dashboard figures down as CSV/JSON so they can be automatically pushed to these platforms. I might also want to pull out this data to create custom figures in a plotting library like matplotlib, otherwise I am restricted to what is available in QS. 

### Proposed Solution

I'm by no means qualified to suggest how to implement the solution. I have had a near-exhaustive look at other options, including examining the requests that enable the download from the browser, but I did not see that as a sensible option. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

latest / 2.5.8

### Environment details (OS name and version, etc.)

Windowns 10

**Comment by aBurmeseDev** [comment]
Hi @jackOxbury, 

Thanks for contacting us! Have you tried CLI command `describe-data-set` that might be able to accomplish what you described. [Here's the guide](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/quicksight/describe-data-set.html) for the command and [here's more documentation](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeDataSet.html) about `DescribeDataSet` with QuickSight.

Please let me know if you have any other questions.

**Comment by eddy-kwok** [comment]
@aBurmeseDev your suggestion to describe Dataset means suggesting users to export the raw data and let users to figure out themselves on how to analyse the data again outside QS and have to manage the duplicate dataset in different places.
Just because your team refuse to do the essential works to process QS reporting in automated way.
