### ISSUE TITLE
GreengrassV2: AccessDeniedException when calling CreateComponentVersion

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [aws/aws-cli#7189]
### Describe the bug

$ aws greengrassv2 create-component-version --inline-recipe fileb://recipes/com.example.HelloWorld-1.0.0.json

An error occurred (AccessDeniedException) when calling the CreateComponentVersion operation: User:****** is not authorized to perform: null

### Expected Behavior

The response looks similar to the following example if the request succeeds.

{
  "arn": "arn:aws:greengrass:region:123456789012:components:com.example.HelloWorld:versions:1.0.0",
  "componentName": "com.example.HelloWorld",
  "componentVersion": "1.0.0",
  "creationTimestamp": "Mon Nov 30 09:04:05 UTC 2020",
  "status": {
    "componentState": "REQUESTED",
    "message": "NONE",
    "errors": {}
  }
}

### Current Behavior

$ aws greengrassv2 create-component-version --inline-recipe fileb://recipes/com.example.HelloWorld-1.0.0.json

### Reproduction Steps

https://docs.aws.amazon.com/greengrass/v2/developerguide/getting-started.html#upload-first-component
in:
Getting started

[Step 5: Create your component in the AWS IoT Greengrass service](https://docs.aws.amazon.com/greengrass/v2/developerguide/getting-started.html#upload-first-component)

Create a component resource in AWS IoT Greengrass from the recipe. Run the following command to create the component from the recipe, which you provide as a binary file.

### CLI version used

aws-cli/2.7.20 Python/3.9.11 Linux/5.15.0-25-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

ubuntu 22.04

**Comment by aBurmeseDev** [comment]
Hi @xiaoyaodingchunqiu, thanks for reaching out!

According to [Greengrass documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/troubleshooting.html#greengrass-cloud-issues) for this type of `AccessDeniedException` error, it indicates that your recipe isn't valid JSON or YAML. 

> You might see this error when you create a component version from the AWS IoT Greengrass console or with the [CreateComponentVersion](https://docs.aws.amazon.com/greengrass/v2/APIReference/API_CreateComponentVersion.html) operation.
This error indicates that your recipe isn't valid JSON or YAML. Check the syntax of your recipe, fix any syntax issues, and try again. You can use an online JSON or YAML syntax checker to identify syntax issues in your recipe.

I also found a similar issue [like this](https://github.com/aws/aws-cli/issues/6274) where the user was able to resolve it by replacing the alias with the actual version number as mentioned in the post. 

Let me know if any of this resolves the issue!

**Comment by WilliamCruaud** [comment]
Hello @aBurmeseDev,

I also find the same issue when I want to create a component from gitlab CI.
Like you suggested, I tested if it was linked to JSON syntax.

To do it, i printed the json (with cat command) in the terminal and try to create the component from the componente AWS commande line (with the printed JSON). It worked perfectly.

Do you have any idea what could be the issue ?

Thank you

**Comment by aBurmeseDev** [comment]
Hi @WilliamCruaud, 

I'm glad that I was able to provide some guidance that resolves the issue for you. In your case, it sounded exactly like how it stated in the documentation which is the syntax issue with recipe JSON file. 

Also, for future reference, here's documentation for some common errors with CreateComponentVersion: [Error Reference](https://docs.aws.amazon.com/greengrass/v2/APIReference/API_CreateComponentVersion.html#API_CreateComponentVersion_Errors)
