### ISSUE TITLE
Make an option for `aws eks update-kubeconfig` to exclude and set `env` in kubeconfig

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [aws/aws-cli#7206]
### Describe the feature

Please make an option for `aws eks update-kubeconfig` to exclude and set  `env` in kubeconfig.
For example, I assumed a role and exported all the credentials and then exported some other AWS_PROFILE, which does not have these permissions.
Now I update my kubeconfig with:
```
aws eks update-kubeconfig --region "$aws_profile_region" --name "$cluster_name" --alias "$cluster_alias"
```
And after that I have this not-working kubeconfig file because it refers to the wrong profile:
```
cat .kube/config
```
```
      env:
      - name: AWS_PROFILE
        value: some_wrong_profile
```
There is no such an option as to exclude or set `env` form a kubeconfig as per this doc:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/update-kubeconfig.html

I'd suggest adding the option to exclude and set any `env` in the kubeconfig. I am not sure what other `env` can get into kubeconfig, but I think it might be useful for other `env` as well.
So an additional flags could be something like that:

```
aws eks update-kubeconfig --env-exclude AWS_PROFILE
aws eks update-kubeconfig --env-set AWS_PROFILE='my-awesome-profile'

```

### Use Case

It is useful during updating kubeconfig.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.7.22

### Environment details (OS name and version, etc.)

Windows 11 WSL (Ubuntu)

**Comment by tim-finnigan** [comment]
Hi @YevheniiPokhvalii thanks for reaching out. It looks like this overlaps with https://github.com/aws/aws-cli/issues/7087.  I mentioned there that the EKS team owns this customization and we received this feedback from them:
> I heard back from a member of the EKS team and they are willing to take this request into consideration during their roadmap planning. In the meantime we can leave this open for tracking, and we encourage others who are interested in this feature to 👍 the issue or leave a comment if they have additional use cases to share.

Please let me know if there is anything you want to expand on or clarify regarding your feature request. Otherwise I recommend adding a 👍 to  https://github.com/aws/aws-cli/issues/7087 and tracking that issue for updates going forward.
