### ISSUE TITLE
NAT Gateway deletion option absent

### ISSUE THREAD

**Issue by d3vpasha** [aws/aws-cli#7210]
### Describe the bug

When trying to use aws cli, I see that there is an option to check if NAT Gateway is correctly deleted : [https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/wait/nat-gateway-deleted.html](url)

However, this option is not available on command line when I execute : `aws ec2 wait help`

I'm currently using aws cli version 2.3.0 : 
`aws-cli/2.3.0 Python/3.8.8 Linux/5.15.0-46-generic exe/x86_64.ubuntu.20 prompt/off`

### Expected Behavior

I expected `nat-gateway-deleted` option to exist with aws cli.

### Current Behavior

`nat-gateway-deleted` option does not exist on aws cli.

### Reproduction Steps

`aws ec2 wait nat-gateway-deleted`

### CLI version used

2.3.0

### Environment details (OS name and version, etc.)

Ubuntu 20.04.1 x86_64

**Comment by aBurmeseDev** [comment]
Hi @d3vpasha, thanks for reaching out.

With `aws-cli/2.7.21`, `nat-gateway-deleted` shows up as one of the available commands for me when I run `aws ec2 wait help`. Could you try updating your CLI to recent version and run the command? 

Here's guidance docs on updating CLI version: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

Hope it helps!
