### ISSUE TITLE
Permission issue while creating Amazon Chime Live Transcription

### ISSUE THREAD

**Issue by SahajNew** [aws/aws-cli#7218]
### Describe the bug

I have an aws user which has all aws chime permissions of starting and stopping transcription (please refer ss). I am running the below cli commands to start and stop transcription.

`aws chime start-meeting-transcription --meeting-id MEETING_ID --transcription-configuration {\"EngineTranscribeSettings\":{\"LanguageCode\":\"en-US\"}}`

`aws chime stop-meeting-transcription --meeting-id MEETING_ID`

while running these commands, they are not throwing any error but while opening the transcript files it is giving me below error

`AccessDenied: User:ARN is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::IAM:role/aws-service-role/transcription.chime.amazonaws.com/AWSServiceRoleForAmazonChimeTranscription\n\tstatus code: 403`

### Expected Behavior

transcription file should contain the transcripts

### Current Behavior

transcript file contains the error statement

### Reproduction Steps

you can try starting and stopping the transcription using the commands shared above

### CLI version used

aws-cli/2.5.6 Python/3.9.11 Darwin/21.3.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Monterey ver 12.2.1

**Comment by aBurmeseDev** [comment]
Hi @SahajNew, thanks for reaching out and sorry to hear that you're having an issue.

While the issue seems related to CLI, the error describes more of a concern with IAM role permissions. Please check out this [troubleshoot guide](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-error/) for `AccessDenied` error. Specifically with Chime SDK on IAM policies, here's [documentation](https://docs.aws.amazon.com/chime-sdk/latest/ag/security-iam.html#security_iam_authentication) on creating and managing access using policies that might be worth checking out.

Also I would like to reproduce this behavior if you could share your code snippet along with debug logs by adding `--debug` to your command?

Best,
John

**Comment by vijay6520** [comment]
Hey Guys,
We are also facing the same issue here, instead we are starting the transcription for a meeting in the backend server and in the frontEnd while getting the transcription event we are facing the same issue :-

`server.js` code 
```
await chime
			.startMeetingTranscription({
				MeetingId: meeting.chime_meeting_id,
				TranscriptionConfiguration: transcriptionConfiguration,
			})
			.promise();
```

And in the frontEnd we are using the following package :- `amazon-chime-sdk-component-library-react`
and subscribing to the Transcription event in the following way :-
```
useEffect(() => {
		if (audioVideo) {
			console.log("in if use effect Transcript");
			audioVideo.transcriptionController?.subscribeToTranscriptEvent(transcriptEvent => {
				console.log("transcribe event ", transcriptEvent);
				setTranscripts(transcriptEvent);
			});
		}
	}, [audioVideo]); 
```

Which is raising the following error :-

![image](https://github.com/aws/aws-cli/assets/147024546/aeee6588-85e0-4286-9003-6022a83ff2e7)
 
```
AccessDenied: User: arn:aws:sts::974165711501:assumed-role/lhr1-audtincan-1-0-206368-0-TincanRole-CK7DJ25NMM4P/i-0e7bacb8fc6535562 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::7xxxxxx:role/aws-service-role/transcription.chime.amazonaws.com/AWSServiceRoleForAmazonChimeTranscription
	status code: 403, request id: 89c7b519-29c8-4c8e-b1d8-7b50b65c098d
```

**Comment by vijay6520** [comment]
Hey Was able to fix this issue by adding an service level IAM role in the console for Chime Live Transcription... :sweat_smile: 
yay :partying_face: 

![image](https://github.com/aws/aws-cli/assets/147024546/25776e86-3f1c-416f-ab94-99dd6e315195)
