### ISSUE TITLE
Change default INSTALL_DIR for aws2 to /opt/aws-cli

### ISSUE THREAD

**Issue by lousyd** [aws/aws-cli#7239]
### Describe the feature

Change the default INSTALL_DIR for the aws2 installer to /opt/aws-cli.

### Use Case

In the installer for aws2, the default INSTALL_DIR is /usr/local/aws-cli. I suggest changing it to /opt/aws-cli. The /usr/local hierarchy is not set up for installing whole packages in one subdirectory. It is split into different directories for bin files, source files, libraries, etc. Creating a new directory in /usr/local for aws2 breaks this convention.

### Proposed Solution

I suggest changing the default INSTALL_DIR for the aws2 installer to /opt/aws-cli. Nothing else needs to be changed to support changing that default. The /opt directory works exactly like the installer is expecting.

### Other Information

Also, the Filesystem Hierarchy Standard, for Linux systems, says that no other directories should exist in /usr/local. It does however, specify a place for vendor package trees: /opt.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.7.27

### Environment details (OS name and version, etc.)

All Linux distributions

**Comment by tim-finnigan** [comment]
Thanks @lousyd for the feature request. As mentioned in [this comment](https://github.com/aws/aws-cli/issues/4660#issuecomment-561383598) from the previous related issue you can use the `-i` parameter to customize the install directory. It would be a breaking change to update the default install directory right now. If the current behavior is a major pain point for you please let us know why and others can provide feedback as well.

**Comment by lousyd** [comment]
> It would be a breaking change to update the default install directory right now.

Alas, I had previously suggested this when awscli2 was still being developed, and feedback was explicitly asked for. It wouldn't have been a breaking change then. But I guess it would be now. =/
