### ISSUE TITLE
s3control create-job requires manifest even if manifest-generator is passed

### ISSUE THREAD

**Issue by alexandervandekleutab** [aws/aws-cli#7240]
### Describe the bug

Attempting to create a replication job using the `--manifest-generator` flag without the `--manifest` flag fails, stating that `--manifest` is required.

From the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3control/create-job.html):

> The attribute container for the ManifestGenerator details. Jobs must be created with either a manifest file or a ManifestGenerator, but not both.

### Expected Behavior

I would expect this command to work:

```sh
# pseudo-code showing JSON parameters
MANIFEST_GENERATOR={"S3JobManifestGenerator":{"SourceBucket":"string","ManifestOutputLocation":{"Bucket":"arn:aws:s3:::alex-monorepo-documentap-manifests3bucket6fae49d5-1cqx21soyyjsc","ManifestFormat":"S3InventoryReport_CSV_20211130"},"EnableManifestOutput":true}}

REPORT={"Bucket":"arn:aws:s3:::alex-monorepo-documentap-manifests3bucket6fae49d5-1cqx21soyyjsc","Format":"Report_CSV_20180820","Enabled":false,"ReportScope":"AllTasks"}

aws s3control create-job \
  --account-id $ACCOUNT_ID \
  --no-confirmation-required \
  --operation '{"S3ReplicateObject": {}}' \
  --manifest-generator $MANIFEST_GENERATOR \
  --report $REPORT \
  --priority 0 \
  --role-arn $REPLICATION_ROLE_ARN \
```

### Current Behavior

The output of running the above command is 
```sh
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: --manifest
```

### Reproduction Steps

See above

### CLI version used

aws-cli/2.2.11 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Monterey 12.5

**Comment by tim-finnigan** [comment]
Hi @alexandervandekleutab thanks for reaching out. It looks like you're using an older version of the AWS CLI. Have you tried [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to a newer version and running this? The latest version in the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) is 2.27.28.

**Comment by csarakasidis** [comment]
same here - when I run the command below (aws version is 2.7.28)

```
aws s3control create-job \
    --account-id <my-account-id> \
    --operation '{"LambdaInvoke": {"FunctionArn": "<my-lambda-arn>"}}' \
    --report '{"Bucket": "<my-bucket-arn>","Format": "Report_CSV_20180820","Enabled": true,"Prefix": "<my-prefix>","ReportScope": "AllTasks"}' \
    --manifest-generator '{"S3JobManifestGenerator": {"SourceBucket": "<my-bucket-arn>","ManifestOutputLocation": {"Bucket": "<my-bucket-arn>","ManifestPrefix": "<my-manifest-prefix>","ManifestEncryption": {"SSEKMS": {"KeyId": "<my-key-arn>"}},"ManifestFormat": "S3InventoryReport_CSV_20211130"},"EnableManifestOutput": true}}' \
    --priority 100 \
    --role-arn <my-batch-role>
```
I get the following output
`An error occurred (InvalidRequest) when calling the CreateJob operation: Invalid attribute, ManifestGenerator is not supported for this operation`
Same error I get when using boto3

**Comment by tim-finnigan** [comment]
Thanks @csarakasidis for sharing that. It looks like the error you reported is slightly different than the one @alexandervandekleutab referenced though. I think it would help if we could see debug logs (with any sensitive info redacted) by adding `--debug` to the command. And then the next step would likely involve reaching out to the S3 Control team for confirmation on the expected behavior.

**Comment by tim-finnigan** [comment]
Since we haven't heard back in a few weeks I'm going to close this issue. If you are still affected by this please refer to the comment above and follow up here. Thanks!
