### ISSUE TITLE
Not downloading changes with S3 sync

### ISSUE THREAD

**Issue by Milesy** [aws/aws-cli#7242]
### Describe the bug

When a file is updated locally that only changes the timestamp, the file is uploaded, but when a file is updated remotely that only changes the timestamp that is not synced back locally. 

If someone else remotely updates a file full of account numbers, and a single account number is changed from an incorrect value to a correct one, this file is not synced as the byte counts have not changes. If the account number has an extra digit added or removed this results in the file size changing which causes a sync to local.

### Expected Behavior

There should be a default way of syncing updated same size files

### Current Behavior

Same size updates remotely do not sync locally

### Reproduction Steps

Create a CSV file remotely, and update it by a second person or process to just change one byte in the file
Try and sync bucket to local
Changes are not detected.

### CLI version used

develop

### Environment details (OS name and version, etc.)

Windows Server 2016

**Comment by aBurmeseDev** [comment]
Hi @Milesy, thanks for reaching out and sorry to hear that you're having an issue.

Have you tried using `--exact-timestamps` parameter option as mentioned in the `sync` CLI documentation [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html)?

> --exact-timestamps (boolean) When syncing from S3 to local, same-sized items will be ignored only when the timestamps match exactly. The default behavior is to ignore same-sized items unless the local version is newer than the S3 version.

Hope it helps, but If you're still having an issue, could you share your debug logs by adding `--debug` in your command?

**Comment by Milesy** [comment]
@aBurmeseDev thanks, this seems strange that the operation is not something that can be relied on in all cases. If I am to write scripts around the sync command, I want to be able to ensure that the remote and local side can always synchronise on both sides without needing to have some prior knowledge.

**Comment by aBurmeseDev** [comment]
I understand. This has come up a few times before and I would refer you to check out this older [issue](https://github.com/aws/aws-cli/issues/3415) which might answer your question.
