### ISSUE TITLE
AWS CLI support for Control Tower

### ISSUE THREAD

**Issue by razhamma** [aws/aws-cli#7243]
### Describe the feature

Control Tower does provide Public APIs - https://docs.aws.amazon.com/controltower/latest/APIReference/API_Operations.html

Extending awcli to include controltower would enable users to programmatically interact with Control Tower via awscli.

Boto3 also supports controltower client as well - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/controltower.html 

### Use Case

Same as was described here - https://github.com/aws/aws-cli/issues/6793

### Proposed Solution

Enable awscli to provide controltower actions

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.7.28

### Environment details (OS name and version, etc.)

Mac

**Comment by tim-finnigan** [comment]
Thanks @razhamma for the feature request. This actually just got released earlier today - per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst) the controltower APIs are available stating in CLI v2.7.29. (or 1.25.66 on [v1](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst)). So if you update to the latest version then you should have access to them. Here is the command reference [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/controltower/index.html). I'm going to close this as the service APIs are available but please let us know if you had any follow up questions. Thanks!
