### ISSUE TITLE
Allow PyYAML 6.x

### ISSUE THREAD

**Issue by fbaier-fn** [aws/aws-cli#7276]
### Describe the feature

PyYaml 6.0 was released almost a year ago with various fixes. This is similar to https://github.com/aws/aws-cli/pull/5887

Is it possible to bump or loosen up the version constraint for PyYaml to allow for the use of latest https://github.com/yaml/pyyaml/releases/tag/6.0?

### Use Case

Installing latest PyYaml with respective fixes

### Proposed Solution

Bump PyYaml in setup.cfg and setup.py

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.25.75

### Environment details (OS name and version, etc.)

m1

**Comment by aBurmeseDev** [comment]
Hi @fbaier-fn, thanks for checking in. 

The CLI team is currently working on improving dependency management relates to the AWS CLI v2. There's an issue tracking that here: https://github.com/aws/aws-cli/issues/5943. We can't give a definite timeline but expect that in the near future PyYAML 6.x will be updated as part of this broader work. I would suggest to please 👍 the original post and add any specific use cases as to how critical it is to your workflow there.

Please feel free to check in for future updates under the tracking issue there and reach out for any other questions and concerns.

Best,
John

**Comment by proutyio** [comment]
Can this be re-opened?

Looks unresolved.
https://github.com/aws/aws-cli/blob/master/setup.cfg#L9

**Comment by TNonet** [comment]
Hi @aBurmeseDev,

Can you provide more of an update on the timeline now?  I am seeing very little aws response on this [thread](https://github.com/aws/aws-cli/issues/5943) or this [PR](https://github.com/aws/aws-cli/pull/6648).
