### ISSUE TITLE
logs tail: unknown option --log-stream-names

### ISSUE THREAD

**Issue by wodCZ** [aws/aws-cli#7278]
### Describe the bug

Following the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/logs/tail.html), trying to use any of the options introduced in https://github.com/aws/aws-cli/issues/5560:
- `--log-stream-names`
- `--log-stream-name-prefix`

both return an error `Unknown options: --log-stream-names` or `Unknown options: --log-stream-name-prefix`.

Trying to filter the events using `--filter-pattern` fails with Invalid filter pattern: 
```
aws logs tail mygroup --since 1d --filter-pattern "worker/worker/*"

> An error occurred (InvalidParameterException) when calling the FilterLogEvents operation: Invalid filter pattern
```

### Expected Behavior

I expect to be able to filter logs by the group.

### Current Behavior

I am not able to do that, which is particularly irritating to discover during service outage.

### Reproduction Steps

Install aws cli

Run
```bash
aws logs tail anything --since 1d --log-stream-names something
```

### CLI version used

aws-cli/2.1.3

### Environment details (OS name and version, etc.)

Python/3.7.4 Darwin/21.6.0 exe/x86_64

**Comment by tim-finnigan** [comment]
Hi @wodCZ thanks for reaching out. Per the [CHANGELOG](https://github.com/aws/aws-cli/blob/d80eea9e97f9e13ff1a1860626f9b660b0679ad2/CHANGELOG.rst#L1689) it looks like this was added in version 2.2.33. Can you try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the AWS CLI and using those options again?

**Comment by wodCZ** [comment]
@tim-finnigan you're right, thank you.
