### ISSUE TITLE
update_autoscaling_group error while trying to update a mixed instances policy

### ISSUE THREAD

**Issue by rodrigoa-most** [aws/aws-cli#7281]
### Describe the bug

I got an error while trying to update an auto scaling group with a mixed instance policy.

### Expected Behavior

It should run as described on "Example 6: To define a mixed instances policy and enable capacity rebalancing" mentioned on [documentation page ](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/update-auto-scaling-group.html).

### Current Behavior

```
An error occurred (ValidationError) when calling the UpdateAutoScalingGroup operation: Valid requests must contain either launchTemplateId or LaunchTemplateName
```

### Reproduction Steps

1. Create a file named config.json containing the body:
```json
{
    "AutoScalingGroupName": "cluster-xxxx",
    "MixedInstancesPolicy": {
        "LaunchTemplate": {
            "LaunchTemplateSpecification": {
                "LaunchTemplateId": "lt-xxxx",
                "LaunchTemplateName": "cluster-xxxx-lt",
                "Version": "30"
            },
            "Overrides": [
                {
                    "InstanceType": "m6i.2xlarge",
                    "WeightedCapacity": "4"
                },
                {
                    "InstanceType": "m5.xlarge",
                    "WeightedCapacity": "2"
                },
                {
                    "InstanceType": "m6i.xlarge",
                    "WeightedCapacity": "2"
                }
            ]
        },
        "InstancesDistribution": {
            "OnDemandAllocationStrategy": "prioritized",
            "OnDemandBaseCapacity": 0,
            "OnDemandPercentageAboveBaseCapacity": 0,
            "SpotAllocationStrategy": "capacity-optimized"
        }
    }
}
```
2. Run the command
`aws autoscaling update-auto-scaling-group     --cli-input-json file://./config.json`

### Additional Information/Context

The same error occurs on boto3.

Am I missing something?

Thank you.

### CLI version used

aws-cli/2.7.4 Python/3.9.11 Linux/5.15.0-46-generic exe/x86_64.ubuntu.20

### Environment details (OS name and version, etc.)

ubuntu 20.04

**Comment by tim-finnigan** [comment]
Hi @rodrigoa-most thanks for reaching out. In the [documentation](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/update-auto-scaling-group.html) page you referenced it notes:
> You must specify either a `LaunchTemplateId` or a `LaunchTemplateName`.

However it appears that you specified both a `LaunchTemplateId` and a `LaunchTemplateName`. If you remove one of those then the command should execute as expected.

**Comment by rodrigoa-most** [comment]
I completely misinterpreted the message. :facepalm:

Tim, Thank you!

**Comment by thomasbiddle** [comment]
> I completely misinterpreted the message. 🤦
> 
> Tim, Thank you!

Not your fault! That error message is totally ambiguous. I wouldn't have solved it without this thread, so thank you both of you!

Personally, I was trying to update the `SpotMaxPrice` as I couldn't find a way to do this in the AWS Console even though it was in the documentation for the API; so I described the auto-scaling group and copied over the JSON it spat out, made the change, and went to update it. The describe call spat out both the ID and the name though.
