### ISSUE TITLE
describe-capacity-reservations not showing the placement group even though it is shown in the console for a particular capacity reservation

### ISSUE THREAD

**Issue by dreambeyondorange** [aws/aws-cli#7290]
### Describe the bug

launched an instance from the console using a placement group and capacity reservation that targets the placement group.  When calling `describe-capacity-reservations` from the AWS CLI v2, the PlacementGroupArn is not in the object returned for that capacity reservation.  The PlacementGroupArn is visible from the AWS Console under the details of the capacity reservation.

### Expected Behavior

the PlacementGroupArn should be in the object returned by `describe-capacity-reservations`

### Current Behavior

It is not there

### Reproduction Steps

create a pg
create a capacity reservation targeting that pg
launch an instance

### CLI version used

2

### Environment details (OS name and version, etc.)

Mac OS 12.6

**Comment by aBurmeseDev** [comment]
Hi @dreambeyondorange, thanks for checking in. 

I followed the reproduction steps provided and ran this CLI command `ec2 describe-capacity-reservations --capacity-reservation-id cr-<groupID>`. I received the following output and as you can see, it has `PlacementGroupArn` value at the end of the output. I'm using `aws-cli/2.7.31` and not sure which v2 version you are using but I would update to the recent version. 

```
{
    "CapacityReservations": [
        {
            "CapacityReservationId": "cr-<groupID>",
            "OwnerId": "<accountID>",
            "CapacityReservationArn": "arn:aws:ec2:us-west-1:<accountID>:capacity-reservation/cr-<groupID>",
            "AvailabilityZoneId": "usw1-az3",
            "InstanceType": "c3.large",
            "InstancePlatform": "Linux/UNIX",
            "AvailabilityZone": "us-west-1b",
            "Tenancy": "default",
            "TotalInstanceCount": 1,
            "AvailableInstanceCount": 0,
            "EbsOptimized": false,
            "EphemeralStorage": false,
            "State": "active",
            "StartDate": "2022-09-22T21:54:54+00:00",
            "EndDateType": "unlimited",
            "InstanceMatchCriteria": "open",
            "CreateDate": "2022-09-22T21:54:54+00:00",
            "Tags": [],
            "PlacementGroupArn": "arn:aws:ec2:us-west-1:<accountID>:placement-group/johns-pg"
        }
    ]
}
```

We could look at the debug logs if you add `--debug` to your command and share the logs. Also I see that you're AWS member, please feel free to message me internally if you'd like.

Best,
John

**Comment by dreambeyondorange** [comment]
I launched an instance into this capacity reservation 
<img width="1471" alt="Screen Shot 2022-09-22 at 8 14 24 PM" src="https://user-images.githubusercontent.com/13821971/191872182-1cbb286f-8bfe-4fd7-99a1-fd8dec0eb713.png">
But the output from `describe-capacity-reservations` only shows this info

```
        {
            "CapacityReservationId": "cr-01df19e7c8c6b8566",
            "OwnerId": "944054287730",
            "CapacityReservationArn": "arn:aws:ec2:us-west-2:944054287730:capacity-reservation/cr-01df19e7c8c6b8566",
            "AvailabilityZoneId": "usw2-az1",
            "InstanceType": "c7g.xlarge",
            "InstancePlatform": "Linux/UNIX",
            "AvailabilityZone": "us-west-2a",
            "Tenancy": "default",
            "TotalInstanceCount": 1,
            "AvailableInstanceCount": 1,
            "EbsOptimized": true,
            "EphemeralStorage": false,
            "State": "active",
            "StartDate": "2022-09-22T19:02:44+00:00",
            "EndDateType": "unlimited",
            "InstanceMatchCriteria": "open",
            "CreateDate": "2022-09-22T19:02:44+00:00",
            "Tags": [
                {
                    "Key": "odcr-test",
                    "Value": "true"
                }
            ]
        },
```
Is there another option I need to set in the CLI command to get the placement group to show up?  I am just calling it like this
```
aws ec2 describe-capacity-reservations
```

**Comment by dreambeyondorange** [comment]
The placement group arn is there after upgrading to 2.7.

Thanks!
Ryan
