### ISSUE TITLE
Include resource-explorer Service

### ISSUE THREAD

**Issue by AMMullan** [aws/aws-cli#7293]
### Describe the feature

I want to be able to list all resources within an AWS account. The AWS web console has a way of doing this in Resource Groups -> Tagging -> Tag Editor. But I can find no way of replicating this using code in the CLI.

In the browser dev-console network tab, I can see requests that look like:

- Resources list:
  - URL: https://resource-explorer.eu-west-2.amazonaws.com/resources-list
  - JSON Payload: {"ResourceType":"AWS::EC2::Subnet"}
  - Response: a list of ARNs
- Tags list:
  - URL: https://resource-explorer.eu-west-2.amazonaws.com/tags-list
  - JSON Payload: the list of ARNs returned by the above
  - Response: a list of tags for each of those resources

This service is doing exactly what I need.

### Use Case

At present to get a list of all resources inside your account and their tags, you have to query every individual service and occasionally, query this service multiple times.

The resourcegroupstaggingapi API allows you to retrieve resources that are, or have previously been, tagged but some resources aren't tagged and this is a massive issue for us (something we're working on!)

### Other Information

This ticket is a copy from the Node SDK (https://github.com/aws/aws-sdk-js/issues/3369)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.7.22

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by tim-finnigan** [comment]
Hi @AMMullan thanks for the feature request. I wonder if what you're asking about could be accomplished with the Cloud Control APIs. This service was [just announced last year](https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/) and offers APIs such as GetResource and ListResources that seem relevant here. For example here is the `list-resources` CLI command: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudcontrol/list-resources.html. Is that the functionality you were looking for?

**Comment by AMMullan** [comment]
Hey @tim-finnigan  - I didn't know about that, but it is very useful! I see that the get-resource API in Cloud Control shows tags for S3 buckets, I'll have to check other resource types but if the tags are included in all resources then yeah, Cloud Control seems to be great :)

It's certainly not as clean as the API that AWS have, and it is frustrating that they aren't just making that available because it's so much more useful than what's provided to us via the CLI/API's.

I presume there's no plans to make the resource-explorer API's available to the general public then??

**Comment by AMMullan** [comment]
Also, @tim-finnigan  - I notice that there are some significant gaps in the supported resource types for Cloud Control - i.e. there's no support for AWS::EC2::Instance - that's a pretty major miss :(

**Comment by tim-finnigan** [comment]
Thanks @AMMullan for following up. In the related issue you originally linked to it looks like someone recently received a [thorough response](https://github.com/aws/aws-sdk-js/issues/3369#issuecomment-1256416402) from AWS Support regarding this feature request. I won't paste the full response here but the main point was: 
> Thus, the Resource Explorer service API is not currently available to be used via public release of any AWS SDK. The service owners have marked this as a feature request and they will evaluate the possibility of externalizing the APIs, so that they are available in future public AWS SDK releases. They have added this request to their backlog, but I cannot comment on any ETA of when it will be actioned.

Since the CLI team doesn't manage APIs such as Resource Explorer or Cloud Control, I recommend reaching out to [AWS Support](https://aws.amazon.com/contact-us/) for any further requests or feedback. I hope that helps - I'm going to close this issue but please let me know if there's anything else you wanted to discuss here.
