### ISSUE TITLE
 health describe-event-type - missing some event type code

### ISSUE THREAD

**Issue by RobertoMAlmaviva** [aws/aws-cli#7298]
### Describe the bug

Hello,
I would like to submit this possible bug calling the aws api .
I do not understand how to solve and I hope for your resolution.

Within our organization I have to extract certain events. i am using the describe_events_for_organization method but some event type code are not returned by calling the describe_event_types method (with or without parameter) why?

the describe_event_types method should return ALL events, as indicated in the documentation .... instead some event types are not present.

example:

EVENT ISSUE :

aws health describe-events-for-organization --filter eventTypeCategories="issue",eventTypeCodes="AWS_DYNAMODB_CONTROLPLANE_API_ISSUE",eventStatusCodes="closed"
{
    "events": [
        {
            "arn": "arn:aws:health:eu-south-1::event/DYNAMODB/AWS_DYNAMODB_CONTROLPLANE_API_ISSUE/AWS_DYNAMODB_CONTROLPLANE_API_ISSUE_97003be1-4f99-54bf-a0b8-bd025c332202",
            "service": "DYNAMODB",
            "eventTypeCode": "AWS_DYNAMODB_CONTROLPLANE_API_ISSUE",
            "eventTypeCategory": "issue",
            "eventScopeCode": "ACCOUNT_SPECIFIC",
            "region": "eu-south-1",
            "startTime": "2022-09-09T21:38:00+02:00",
            "endTime": "2022-09-09T22:30:00+02:00",
            "lastUpdatedTime": "2022-09-09T22:53:51.618000+02:00",
            "statusCode": "closed"
        }
    ]
}

EVENT TYPE CODE AWS_DYNAMODB_CONTROLPLANE_API_ISSUE NOT EXIST !!! :  

C:\WINDOWS\system32>aws health describe-event-types --filter eventTypeCategories="issue",services="DYNAMODB"
{
    "eventTypes": [
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_API_ISSUE",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_EAR_INACCESSIBLE_TABLE_ENCRYPTION",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_GT_WCU_MISMATCH",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_GT_WCU_MISMATCH_REPLICATION_THROTTLED",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_OPERATIONAL_ISSUE",
            "category": "issue"
        }
    ]
}

C:\WINDOWS\system32>aws --version
aws-cli/2.7.35 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

C:\WINDOWS\system32>

### Expected Behavior

I expected the describe-event-types method to return the registered event code issue for dynamodb : AWS_DYNAMODB_CONTROLPLANE_API_ISSUE

### Current Behavior

the describe-event-types method does not return the event type code

### Reproduction Steps

aws health describe-events-for-organization --filter eventTypeCategories="issue",eventTypeCodes="AWS_DYNAMODB_CONTROLPLANE_API_ISSUE",eventStatusCodes="closed"
{
    "events": [
        {
            "arn": "arn:aws:health:eu-south-1::event/DYNAMODB/AWS_DYNAMODB_CONTROLPLANE_API_ISSUE/AWS_DYNAMODB_CONTROLPLANE_API_ISSUE_97003be1-4f99-54bf-a0b8-bd025c332202",
            "service": "DYNAMODB",
            "eventTypeCode": "AWS_DYNAMODB_CONTROLPLANE_API_ISSUE",
            "eventTypeCategory": "issue",
            "eventScopeCode": "ACCOUNT_SPECIFIC",
            "region": "eu-south-1",
            "startTime": "2022-09-09T21:38:00+02:00",
            "endTime": "2022-09-09T22:30:00+02:00",
            "lastUpdatedTime": "2022-09-09T22:53:51.618000+02:00",
            "statusCode": "closed"
        }
    ]
}

EVENT TYPE CODE AWS_DYNAMODB_CONTROLPLANE_API_ISSUE NOT EXIST !!! :  

C:\WINDOWS\system32>aws health describe-event-types --filter eventTypeCategories="issue",services="DYNAMODB"
{
    "eventTypes": [
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_API_ISSUE",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_EAR_INACCESSIBLE_TABLE_ENCRYPTION",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_GT_WCU_MISMATCH",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_GT_WCU_MISMATCH_REPLICATION_THROTTLED",
            "category": "issue"
        },
        {
            "service": "DYNAMODB",
            "code": "AWS_DYNAMODB_OPERATIONAL_ISSUE",
            "category": "issue"
        }
    ]
}

### CLI version used

aws-cli/2.7.35

### Environment details (OS name and version, etc.)

 Windows/10 exe/AMD64

**Comment by aBurmeseDev** [comment]
Hi @RobertoMAlmaviva, thank you for opening your first issue and sorry to hear that you're having trouble.

I tried to reproduce but wasn't able to get the same behavior as you described. Would you please share the debug logs by adding `--debug` to your commands?

Best,
John

**Comment by RobertoMAlmaviva** [comment]
hi @aBurmeseDev , thanks for the answer, I am attaching the debugging of the 2 method calls.
in your environment you can check if you get the event type code  AWS_DYNAMODB_CONTROLPLANE_API_ISSUE ?
how many ev type code  (category issue) for dynamodb service do you get?
thanks, Roberto
aws health describe-event-types --filter eventTypeCategories="issue",services="DYNAMODB"

[debugcall.zip](https://github.com/aws/aws-cli/files/9657830/debugcall.zip)

**Comment by RobertoMAlmaviva** [comment]
hi @aBurmeseDev , you have news? in your environment, exists  the event type code AWS_DYNAMODB_CONTROLPLANE_API_ISSUE ? 
aws health describe-event-types --filter eventTypeCategories="issue",services="DYNAMODB"
thanks

**Comment by aBurmeseDev** [comment]
Hi @RobertoMAlmaviva, thank you for following up.

I couldn't find any reported issues or any version issues related to this. Also I attempted to run the command again and can see "AWS_DYNAMODB_CONTROLPLANE_API_ISSUE" as eventTypeCode in the output. Perhaps, could you try running the command without the `--filter` to see if it returns the eventTypeCode?

I suggest reaching out to [AWS Support](https://aws.amazon.com/contact-us/) for help or consider asking in [re:Post](https://repost.aws/) to get more input from the community as well.

**Comment by RobertoMAlmaviva** [comment]
@aBurmeseDev , thanks for your reply. 
Without filter I get 1147 event type code but among them I cannot find AWS_DYNAMODB_CONTROLPLANE_API_ISSUE.
Another event type that I can't find is  AWS_ELASTICLOADBALANCING_INSUFFICIENT_IPS_IN_SUBNET
(event which occurred recently in the same environment, with this event type code). mystery!
I am attaching the list of all event types returned by the method without filters. 
how many event types [code](url) do you get?
i will open a request at support....

![Cattura](https://user-images.githubusercontent.com/106833487/193922940-660eafac-864a-4a88-a30a-5823b8b8204b.JPG)
[all_eventTypes.xlsx](https://github.com/aws/aws-cli/files/9710550/all_eventTypes.xlsx)

**Comment by aBurmeseDev** [comment]
Hi @RobertoMAlmaviva - I wanted to check in to see if you were able to find any other support on this and there's anything we can further help you. Please let me know, thank you!
