### ISSUE TITLE
Slow upload speed in Apple Virtualization Framework VMs on M1

### ISSUE THREAD

**Issue by remarkov** [aws/aws-cli#7299]
### Describe the bug

We noticed that uploading a smaller size file, e.g. 8 MB to S3 using AWS CLI is dramatically slower when used on macOS running on M1 rather than Intel version. Absolutely the same file being uploaded to the same bucket using the same version of AWS CLI (2.7.35) gives totally different speeds, ~150 KiB/s on ARM and ~1.5 MiB/s on Intel. 

The issue does not affect bigger files, most likely due to chunks and parallel uploads.

This is easily reproducible, tried on several different hosts in different networks etc. Trying x86_64 version on M1 does not give any difference and remains slow on upload. Also tried experimenting with different transfer options as specified [here](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html) to no avail. So far I was not able to find any workaround except using Intel host.

### Expected Behavior

The upload speed should be the same when using both Intel and ARM hosts given they have no other difference in network setup, bandwidth limits etc.

### Current Behavior

The upload speed of smaller files (~8 MB) is 10x slower on ARM than on Intel.

### Reproduction Steps

run 

```
> dd if=/dev/urandom of=sample.txt bs=8M count=1
> aws s3 cp sample.txt s3://my-bucket
```
on Intel and on M1 macOS, see the upload speed difference is enormous.

### CLI version used

2.7.35

### Environment details (OS name and version, etc.)

macOS 12.6 M1

**Comment by aBurmeseDev** [comment]
Hi @remarkov, thanks for reaching out.

I followed the steps to reproduce on both M1 mac and Intel EC2. For a ~7MB file, it was uploaded at ~400 KiB/s for both M1 and Intel. Could you tell us more about which specific AMI you're using (for both M2 and Intel) if you're using EC2 instances?

I would also suggest checking out [this comment](https://github.com/aws/aws-cli/issues/6682#issuecomment-1036679517) from a similar issue on how you can improve the transfer speeds and several factors that could affect the transfer rate between EC2 and S3.

**Comment by remarkov** [comment]
Hi @aBurmeseDev , thanks for looking into this!

No, I was trying from local hosts, not from EC2 instances. But first of all I must apologize for opening this issue too quick before I made proper diagnostics on the problem. I was confused by various assumptions I had before I started to work on this task therefore I took the wrong debugging path.

Finally I discovered that it something specific to our virtualization infrastructure and it requires further internal investigation. Most likely it has nothing to do with AWS CLI per se so this issue might be closed.

**Comment by remarkov** [comment]
Sorry I have to reopen the issue as I managed to find more details on the it.

It appears the issue occurs only under native Apple Virtualization Framework VMs on M1. No matter what the file size is, but transfer speed gets 10x+ slow if AWS CLI is used on a virtual machine compared to the same test performed on the host rather than in VM. I tried different hosts and different apps that use Apple virtualization, namely [Tart](https://github.com/cirruslabs/tart/) and [VirtualBuddy](https://github.com/insidegui/VirtualBuddy). 
I would think that the Apple Virtualization has network issues in general but the network performance in other tools like `scp`, `rsync`, `gcloud` etc. stays fine, just AWS CLI gets affected so I believe it may be of interest for the maintainers here to investigate what may cause this.

**Comment by nagypeterjob** [comment]
We experience the same, this is a real issue. I tried to play with different parameters as well, but could not squeeze out more performance from `awscli`. As a comparison, `Minio`'s `mc` is blazing fast, so we are using it as a fallback in the meantime.

**Comment by nagypeterjob** [comment]
@remarkov We should probably open a new issue and reference this one.

**Comment by gregiOS** [comment]
Any update on this one?

**Comment by gregiOS** [comment]
This is blocking us for migrating our CI/CD system into apple silicon machines, which performance is significantly better

**Comment by remarkov** [comment]
Closing in favor of https://github.com/aws/aws-cli/issues/7481
