### ISSUE TITLE
import-table command not found in aws/cli

### ISSUE THREAD

**Issue by mukul-lumi** [aws/aws-cli#7300]
### Describe the bug

According to the documentation v2 of aws/cli supports `aws dynamodb import-table` command, https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dynamodb/import-table.html

but this command is not listed when we tried `aws dynamodb help`.

Our CLI version is `aws-cli/2.7.6 Python/3.9.11 Darwin/21.2.0 exe/x86_64 prompt/off`

### Expected Behavior

Cli should list the command in help and work properly.

### Current Behavior

We are getting

```
aws dynamodb import-table help

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:
```

### Reproduction Steps

Use command `aws dynamodb import-table help`

### CLI version used

aws-cli/2.7.6 Python/3.9.11 Darwin/21.2.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Mac OS

**Comment by tim-finnigan** [comment]
Hi @mukul-lumi thanks for reaching out. It looks like this was added in version 2.7.25 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/a97df2bea10dad432880226c213141e912113f96/CHANGELOG.rst#L166). If you [update](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to that version or above then you should have access to the ImportTable API. Please let us know if you run into any issues.

**Comment by mukul-lumi** [comment]
@tim-finnigan  Thank you for your suggestion. It is working fine now after updating the version.

**Comment by tim-finnigan** [comment]
Thanks for letting us know! I'll go ahead and close this issue.
