### ISSUE TITLE
aws-network-firewall update-rule-group works only for rule_grups in default mode

### ISSUE THREAD

**Issue by mario-nc** [aws/aws-cli#7301]
### Describe the bug

I'm trying to update existing rule-group in AWS Network Firewall. Rule group is set as STATEFUL and ordering mode is STRICT. 

```
update_rule_group = network_firewall.update_rule_group(RuleGroupName="RuleGroupName",
                            Type="STATEFUL",
                            Rules=rules,
                            UpdateToken=token
```

Output: 
raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the UpdateRuleGroup operation: parameter is invalid

### Expected Behavior

Script should be able to update rule-group, however it is only able to update rule-group that is configured with DEFAULT ordering mode. 

### Current Behavior

raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the UpdateRuleGroup operation: parameter is invalid

### Reproduction Steps

```
update_rule_group = network_firewall.update_rule_group(RuleGroupName="RuleGroupName",
                            Type="STATEFUL",
                            Rules=rules,
                            UpdateToken=token
```

### CLI version used

aws-cli/2.7.26

### Environment details (OS name and version, etc.)

MacOS/12.6

**Comment by tim-finnigan** [comment]
Hi @mario-nc thanks for reaching out. I saw that error was reported [here in re:Post](https://www.repost.aws/questions/QUFGZ536SxQECThRgMv3S5kg/aws-cli-updating-network-firewall-rules) as well. Does the response there help with resolving the issue? 
>Have you tried doing a "describe-rule-group" first to retrieve the UpdateToken, and then using the "update-rule-group" command with a new JSON file using --rule-group ?
>
>There's a good step by step guide you could follow to test using Domain-list rule-group here: https://docs.aws.amazon.com/network-firewall/latest/developerguide/stateful-rule-groups-domain-names.html#stateful-rule-groups-domain-names-home-net

If that doesn't address the issue you're seeing could you share your debug logs with any sensitive info redacted? If you're using the AWS CLI by adding `--debug` to the command or if using boto3 by adding `boto3.set_stream_logger('')` to your script. Thanks!

**Comment by tim-finnigan** [comment]
Since we haven't heard back here in over a month I'm going to close this issue. Please refer to the comment above if you're still experiencing the issue. Thanks!

**Comment by FerFabbiano** [comment]
Hi! I'm having the same problem described here, and the comment in [re:Post](https://www.repost.aws/questions/QUFGZ536SxQECThRgMv3S5kg/aws-cli-updating-network-firewall-rules) didn't work for me. Any updates? Thanks!
