### ISSUE TITLE
pyinstaller dependencies breaking installer

### ISSUE THREAD

**Issue by jlembke** [aws/aws-cli#7318]
### Describe the bug

Please refer to [AWS Support Case ID 10897874921](https://console.aws.amazon.com/support/home#/case/?displayId=10897874921&language=en)

Installing aws cli v2 on Ubuntu 20.04.5 LTS, using instructions from [https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html ](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) for Linux x86 (64-bit)

On the `sudo ./aws/install` command and `aws --version` I get the following error:

> [6542] Module object for struct is NULL!
> Traceback (most recent call last):
>   File "struct.py", line 13, in <module>
> ModuleNotFoundError: No module named '_struct'
> [6542] Module object for pyimod01_archive is NULL!
> Traceback (most recent call last):
>   File "PyInstaller/loader/pyimod01_archive.py", line 27, in <module>
> ModuleNotFoundError: No module named 'struct'
> [6542] Module object for pyimod02_importers is NULL!
> Traceback (most recent call last):
>   File "PyInstaller/loader/pyimod02_importers.py", line 28, in <module>
> ModuleNotFoundError: No module named 'pyimod01_archive'
> Traceback (most recent call last):
>   File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
> ModuleNotFoundError: No module named 'pyimod02_importers'
> [6542] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

We initially thought that maybe pyinstaller needed to be reinstalled, and on trying that found that my .local/bin directory was not on PATH. We added that, but it did not fix the problem. `which pyinstaller` shows the correct path of `/home/myuser/.local/bin/pyinstaller`

`pip show pyinstaller` gives the following:

> Name: pyinstaller
> Version: 5.4.1
> Summary: PyInstaller bundles a Python application and all its dependencies into a single package.
> Home-page: https://www.pyinstaller.org/
> Author: Hartmut Goebel, Giovanni Bajo, David Vierra, David Cortesi, Martin Zibricky
> Author-email: None
> License: GPLv2-or-later with a special exception which allows to use PyInstaller to build and distribute non-free programs (including commercial ones)
> Location: /home/jtlembke/.local/lib/python3.8/site-packages
> Requires: altgraph, setuptools, pyinstaller-hooks-contrib
> Required-by:

Looking for help in zeroing in on what happened. The Ubuntu instance has been uninstalled and reinstalled in the process. 

### Expected Behavior

Expected a successful install message after sudo ./aws/install command

### Current Behavior

Currently I get this message:

[6542] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'
[6542] Module object for pyimod01_archive is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod01_archive.py", line 27, in <module>
ModuleNotFoundError: No module named 'struct'
[6542] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 28, in <module>
ModuleNotFoundError: No module named 'pyimod01_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[6542] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

### Reproduction Steps

- Install Ubuntu using WSL found at https://learn.microsoft.com/en-us/windows/wsl/install, using `wsl --install`
- Update and Upgrade packages
- Follow instructions at https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html to install the aws cli v2

### Possible Solution

Can pyinstaller and its dependencies be a part of the awscliv2 install? If someone can point out why we are getting this error that would be helpful

### CLI version used

latest

### Environment details (OS name and version, etc.)

aws cli v2 on Ubuntu 20.04.5 LTS (Windows Subsystem for Linux)

**Comment by tim-finnigan** [comment]
Hi @jlembke thanks for reaching out. We tried to reproduce this issue a Ubuntu 20.04.5 instance but weren't able to. (There was another recent issue related to PyInstaller that just came in as well, not sure if these are related: https://github.com/aws/aws-cli/issues/7314.) Were you able to install previous versions such as [2.7.29](https://github.com/aws/aws-cli/blob/804a179e9edd49031711f81ef339e7690e9e9c75/CHANGELOG.rst#L121) before PyInstaller was upgraded to 5.3? And did you have PyInstaller installed previously in your environment before installing the AWS CLI v2?

**Comment by jlembke** [comment]
Hi @tim-finnigan, This was a brand new environment that I just spun up, so I had never tried the previous versions on this instance, and I don't know if pyinstaller was there for sure, but Michael from AWS support was on with me and seemed to think it was _not_ ever there before.

**Comment by johnnylinfairstoneca** [comment]
Writing to let you know I am also having the same issue on my fresh install in a Virtual Box VM running Ubuntu Server 22.04.1. (CLI, no GUI)

**Comment by tim-finnigan** [comment]
I saw that the corresponding internal support ticket for this was closed so I want to confirm that this is resolved. It sounds like this was an issue with the pyinstaller installed for just the user while the CLI was installed using sudo. Also for reference here are the recommended AWS CLI installation methods: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.
