### ISSUE TITLE
Emojis causing 0 response

### ISSUE THREAD

**Issue by DrewSunn** [aws/aws-cli#7322]
### Describe the bug

Running
"aws polly synthesize-speech --text-type ssml --text file://H:/Videos/StreamV3/TTS/speech.txt --output-format mp3 --voice-id Justin H:\Videos\StreamV3\TTS\speech.mp3"
Causes the command to not make a new file and comes back with
"Error parsing parameter '--text': Unable to load paramfile (H:/Videos/StreamV3/TTS/speech.txt), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix."
If the text file it's reading features emojis like "😀 😃 😄 😁 😆 😅 😂 🤣"
Doesn't seem consistent with all emojis, but most. The ones that don't cause the error written above, aren't read correctly.

### Expected Behavior

Record a response describing the emoji, like "Smiley face, embarrassed smiley face" etc. Works correctly on the Amazon Polly text-to-speech tested on the AWS web browser.

### Current Behavior

Does not create new speech file. Returns with an error or "Error parsing parameter '--text': Unable to load paramfile (H:/Videos/StreamV3/TTS/speech.txt), text contents could not be decoded.  If this is a binary file, please use the fileb:// prefix instead of the file:// prefix." Only happens with the majority of emojis.

### Reproduction Steps

This is the exact .vbs file I am launching to cause this result

"Set oShell = CreateObject("WScript.Shell")
oShell.Run "cmd.exe /C del H:\Videos\StreamV3\TTS\speech.mp3", 0, false

' Run the command dir in a hidden window without waiting for it to finish
oShell.Run "cmd.exe /c aws polly synthesize-speech --text-type ssml --text file://H:/Videos/StreamV3/TTS/speech.txt --output-format mp3 --voice-id Justin H:\Videos\StreamV3\TTS\speech.mp3", 0, false"

However can be tested more efficiently by just using
"aws polly synthesize-speech --text-type ssml --text file://H:/Videos/StreamV3/TTS/speech.txt --output-format mp3 --voice-id Justin H:\Videos\StreamV3\TTS\speech.mp3"
in an already opened command prompt/windows terminal.

### CLI version used

Unsure

### Environment details (OS name and version, etc.)

Windows. Attempted in both Command Prompt and Windows Terminal

**Comment by tim-finnigan** [comment]
Hi @DrewSunn thanks for reaching out. This looks similar to https://github.com/aws/aws-cli/issues/4134. As mentioned there, I think the issue is that the default encoding of your locale isn't UTF-8. Can you try setting the environment variable `AWS_CLI_FILE_ENCODING=UTF-8` as documented [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-encodingenvvar) and let us know if that solves the issue?

**Comment by DrewSunn** [comment]
> Hi @DrewSunn thanks for reaching out. This looks similar to #4134. As mentioned there, I think the issue is that the default encoding of your locale isn't UTF-8. Can you try setting the environment variable `AWS_CLI_FILE_ENCODING=UTF-8` as documented [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-encodingenvvar) and let us know if that solves the issue?

I'm not going to lie to you. I'm pretty new to all of this. Most of what I already have was done by other people and I just edited it along to work for what I needed. The link you sent and the issue you linked to could be written in Japanese and it would make the same amount of sense. I'll keep trying to decode, but as of now I have no idea what I'm looking at.

**Comment by DrewSunn** [comment]
> > Hi @DrewSunn thanks for reaching out. This looks similar to #4134. As mentioned there, I think the issue is that the default encoding of your locale isn't UTF-8. Can you try setting the environment variable `AWS_CLI_FILE_ENCODING=UTF-8` as documented [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-encodingenvvar) and let us know if that solves the issue?
> 
> I'm not going to lie to you. I'm pretty new to all of this. Most of what I already have was done by other people and I just edited it along to work for what I needed. The link you sent and the issue you linked to could be written in Japanese and it would make the same amount of sense. I'll keep trying to decode, but as of now I have no idea what I'm looking at.

Okay I figured it out and that does work. Is there a way to set it to "AWS_CLI_FILE_ENCODING=UTF-8" permanently? setx doesn't seem to be working for me but perhaps I'm not understanding?
