### ISSUE TITLE
Better documentation for UserData in request-spot-instances

### ISSUE THREAD

**Issue by bcliu** [aws/aws-cli#733]
Using file://xxx as UserData in launch-specification doesn't seem to work. AWS console gives me "Bad base64 encoding" error. But when I tried to pass base64 encoded string to it, it worked.
Also I noted that previous posts said that file:// works and CLI will do base64 for us. But it's not the case.
I recommend clearer documentation (both in man page and in AWS website) about this.

**Comment by justnance** [comment]
@bcliu - Thank you for reaching out and requesting improvements to our documentation.  It appears this request may have been resolved but the issue did not get updated and closed.  Our documentation, both the [man page](https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-instances.html) and the [AWS website](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_UserData.html), now specifies to pass the base64 encoded as a string.
