### ISSUE TITLE
Unknown interpreted text role "abc" while calling aws help config-vars

### ISSUE THREAD

**Issue by tlmikulski** [aws/aws-cli#7338]
### Describe the bug

Error is shown instead of information how to configure variables.

### Expected Behavior

Display help how to configure variables.

### Current Behavior

```
<string>:450: (ERROR/3) Unknown interpreted text role "doc".
<string>:567: (SEVERE/4) Title level inconsistent:

==============
Global Options
==============

<string>:567: (SEVERE/4) Title level inconsistent:

==============
Global Options
==============
```

### Reproduction Steps

aws help config-vars

### CLI version used

aws-cli/2.8.2 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 11 Home 22H2 (compilation 22621.608)

**Comment by tim-finnigan** [comment]
Thanks @tlmikulski for bringing this to our attention. I believe this error was introduced in v2.7.26 when some updates were merged involving documentation commands. I think the problem relates to what is described [here](https://stackoverflow.com/questions/24504301/what-does-title-level-inconsistent-mean) involving some hierarchy/precedence rules. The team will need to look further into this.
