### ISSUE TITLE
Allow credential providers to prompt for user input

### ISSUE THREAD

**Issue by BEllis** [aws/aws-cli#7339]
### Describe the feature

Allow credential providers to prompt users and take user input before returning the expected JSON, this will allow for more seamless integration and allow providers to either prompt the user for further information, or, display warnings and errors.

Also, if a provider does currently ask for stdin input, the awscli freezes and will no progress as it's waiting for the provider to provide the credentials JSON.

### Use Case

My Okta credentials have expired or my account is locked, when I call aws I expect to see an error telling me why I can not authenticate.

If my provider prompts for user input, I don't want awscli to hang and would like to be able to provide that input.

### Proposed Solution

There may be a better solution, but the one I can think of would be for awscli to forward stdout and stdin to the credential provider, but not output anything between a line starting with `{` and another line ending with `}` that should be assumed to be the credential JSON.

This should allow existing providers to still work as-is without any changes, while adding support for user interaction.

### Other Information

Another solution might be more of a protocol between the provider and awscli but this would be more involved.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.8.2 Python/3.10.7 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Monterey 12.6

**Comment by tim-finnigan** [comment]
Hi @BEllis thanks for reaching out. I think this might overlap with [another request](https://github.com/boto/botocore/issues/1348) that is currently being tracked here in the cross-SDK repository: https://github.com/aws/aws-sdk/issues/358. As the credentials are used across SDKs there would need be some considerations to allow for consistent behavior. Do you think that issue relates to what you're requesting here? Please let us know if there are any distinctions you'd like to clarify or expand on.

**Comment by BEllis** [comment]
@tim-finnigan I think that ticket would go a long way to addressing this ticket, though other tools (outside of aws cli) may need to be changed to output to stderr instead of stdout for everything but the json. Happy for this to be closed.

**Comment by tim-finnigan** [comment]
Thanks for confirming - I'll go ahead and close this issue but others can 👍 or comment on https://github.com/aws/aws-sdk/issues/358 if they have any additional feedback to share in terms of how this would help their use case.
