### ISSUE TITLE
Default permissions on credentials file are insecure

### ISSUE THREAD

**Issue by rchildress87** [aws/aws-cli#7369]
### Describe the bug

~/.aws/credentials file on MacOS is created with u=rw,g=r,o=r (644) permissions making it readable to everyone in the primary group of the user. On MacOS, this is typically `staff`. In a multi-user scenario, this could allow for an unauthorized user to access secrets.

### Expected Behavior

```
$ ls -lah ~/.aws/                    
total 16
drwxr-xr-x   6 rchildress87  staff   192B Oct 26 15:47 .
drwxr-xr-x+ 52 rchildress87  staff   1.6K Oct 26 16:19 ..
drwxr-xr-x   3 rchildress87  staff    96B Oct  9  2021 cli
-rw-r--r--@  1 rchildress87  staff   3.6K Oct 26 15:59 config
-rw-------@  1 rchildress87  staff   744B Oct 26 15:47 credentials
drwxr-xr-x   3 rchildress87  staff    96B Oct  6  2021 sso
```

### Current Behavior

```
$ ls -lah ~/.aws/                    
total 16
drwxr-xr-x   6 rchildress87  staff   192B Oct 26 15:47 .
drwxr-xr-x+ 52 rchildress87  staff   1.6K Oct 26 16:19 ..
drwxr-xr-x   3 rchildress87  staff    96B Oct  9  2021 cli
-rw-r--r--@  1 rchildress87  staff   3.6K Oct 26 15:59 config
-rw-r--r--@  1 rchildress87  staff   744B Oct 26 15:47 credentials
drwxr-xr-x   3 rchildress87  staff    96B Oct  6  2021 sso
```

### Reproduction Steps

Add your first access key ID and secret access key pair via `aws configure`

### Possible Solution

Because this file contains secrets in plain text, I would think it should default to u=rw,g=,o= (600) which would prevent group and other users from reading the file.

### CLI version used

aws-cli/2.8.5 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS 12.6.1 on MacBook Pro

**Comment by tim-finnigan** [comment]
Thanks @rchildress87 for creating this issue, I brought this up for discussion with the team and they agreed with you. I created a corresponding backlog item for the team to prioritize.

**Comment by rchildress87** [comment]
Thanks for confirming. I appreciate the update!

**Comment by rchildress87** [comment]
It would appear that setting a mode of 600 is actually the default behavior. Just verified on Ubuntu Linux 22.10 and MacOS 12.6.2 machine. I am unable to reproduce with latest version of awscli v2 and do not see a change to relevant source code in many years: https://github.com/aws/aws-cli/blame/v2/awscli/customizations/configure/writer.py#L76.

Probably safe to close this issue unless someone else can reproduce using `aws configure` to create a `credentials` file with mode 644.

**Comment by tim-finnigan** [comment]
Thanks for following up and confirming that, I'll go ahead and close this issue. We can revisit this topic in the future if necessary.
