### ISSUE TITLE
[Tracking issue] `help` functionality broken in macOS Ventura (groff replaced by mandoc)

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-cli#7400]
### Describe the bug

In macOS Ventura groff has been replaced by mandoc which is breaking `aws help` commands.

### Expected Behavior

`aws help` commands to work

### Current Behavior

`Could not find executable named "groff"`

### Reproduction Steps

Upgrade to macOS Ventura. Run command like `aws s3 help`

### Possible Solution

https://github.com/aws/aws-cli/issues/6918

### CLI version used

2.8.2

### Environment details (OS name and version, etc.)

macOS Ventura

**Comment by razamatan** [comment]
can you just bump https://github.com/aws/aws-cli/issues/6918?  the patch works perfectly for me.

**Comment by tim-finnigan** [comment]
The issue referenced above (https://github.com/aws/aws-cli/issues/6918) was just auto-closed as [this pr](https://github.com/aws/aws-cli/pull/7413) was just merged. This should be fixed in the next release which will be available soon. Please refer to the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for release updates. I think this issue can be closed now but if there's anything else to discuss here please let us know.

**Comment by razamatan** [comment]
#7413 only fixes the v1/develop branch.  the v2 branch also needs to be addressed.  please see #7407.

**Comment by tim-finnigan** [comment]
Hi @razamatan thanks for checking in. The v1 changes were merged into v2 so the latest releases should both have the changes. For v2 that is v2.8.11 and for v1 that is v1.27.6. Please let us know if you see any further issues related to this.

**Comment by joshbalfour** [comment]
if you need a workaround `sudo ln -s /usr/bin/mandoc /usr/local/bin/groff` worked for me
