### ISSUE TITLE
describe-images (public) does not work with Filters

### ISSUE THREAD

**Issue by pedrocesar-ti** [aws/aws-cli#7428]
### Describe the bug

When using the `describe-images` sub-command with filters it does not return any values, but when specifying `--image-ids` the search works, which does not seem the correct behaviour for a filter-based search.

### Expected Behavior

Should return a list of images.

### Current Behavior

Returns an empty list

### Reproduction Steps

1. Run the command only with the filters:
```
$ aws ec2 describe-images \
    --region us-east-1 \
    --filters \
    "Name=name,Values=*OpenVPN Access Server*" \
    "Name=root-device-type,Values=ebs" \
    "Name=architecture,Values=x86_64"

{
    "Images": []
}
```
2. Now run the same command but specifying the AMI ID found on the console:
```
$ aws ec2 describe-images \
    --region us-east-1 \
    --filters \
    "Name=name,Values=*OpenVPN Access Server*" \
    "Name=root-device-type,Values=ebs" \
    "Name=architecture,Values=x86_64" \
    --image-ids ami-037ff6453f0855c46

{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-07-31T17:45:49.000Z",
            "ImageId": "ami-037ff6453f0855c46",
            "ImageLocation": "aws-marketplace/OpenVPN Access Server Community Image-fe8020db-5343-4c43-9e65-5ed4a825c931-ami-06585f7cf2fb8855c.4",
            "ImageType": "machine",
...
```

### Possible Solution

I don't know if there is a particular order of the params passed to the API. Or if the first command has a search that is too broad and kind of fail.

### CLI version used

`aws-cli/2.8.11 Python/3.10.8 Darwin/22.2.0 source/x86_64 prompt/off`

### Environment details (OS name and version, etc.)

`macOs Ventura 13.1`

**Comment by aBurmeseDev** [comment]
Hi @pedrocesar-ti, thanks for reaching out. 

I attempted to replicate the problem with same command but I was not able to reproduce. I wanted to see if one of the filter params is blocking the search to return an empty list. Could you try running by removing each filter params alternatively? 

For example, try running with only architecture filter and see if returns anything:
```
aws ec2 describe-images \
    --region us-east-1 \
    --filters \
    "Name=architecture,Values=x86_64"
```
If you're still seeing empty list, please provide debug logs by appending `--debug` to your command.

Best,
John

**Comment by pedrocesar-ti** [comment]
Running with just the architecture filter works, but any other filter added returns empty.

**Comment by pedrocesar-ti** [comment]
Running with just the architecture does return a list of AMIs, but it doesn't return the AMI that I am looking for (ami-037ff6453f0855c46).

**Comment by aBurmeseDev** [comment]
@pedrocesar-ti - thanks for checking. Could you share the debug logs by appending `--debug` to your command? That would give us more insight into finding the cause here.

**Comment by pedrocesar-ti** [comment]
Hey team, sorry for bothering you with this, I checked today and turns out that all the vendor images are way pass the future deprecation date. That was easily fixed by a `--include-deprecated`.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-deprecate.html
