### ISSUE TITLE
aws sts assume-role-with-saml error

### ISSUE THREAD

**Issue by pserrano** [aws/aws-cli#7455]
### Describe the bug

There is an error when we try to execute aws sts assume-role-with-saml in this version of aws cli. 

The last version, aws-cli/2.8.13 works ok with the same command

### Expected Behavior

Expected login with aws 

### Current Behavior

```
No endpoint found for parameters:
UseDualStack: False
UseFIPS: False
Endpoint: https://sts.eu-central-1.amazonaws.com
UseGlobalEndpoint: False
```

### Reproduction Steps

`aws sts assume-role-with-saml --endpoint-url https://sts.eu-central-1.amazonaws.com --role-arn arn:aws:iam::xxxxxxxxx:role/xxx --principal-arn arn:aws:iam::xxxxxxxxxxxx:saml-provider/xxx --saml-assertion xxxxxxx --duration-seconds 14400`

### CLI version used

2.9.0

### Environment details (OS name and version, etc.)

MacOSX Apple M1 Ventura 13.0.1

**Comment by tim-finnigan** [comment]
Thanks @pserrano for reporting this issue. The PR linked above was created to address it. We will update this issue when it gets resolved.
