### ISSUE TITLE
allow generating pre-signed URLs for aribitrary commands

### ISSUE THREAD

**Issue by rittneje** [aws/aws-cli#7458]
### Describe the feature

Any operation can be used in a presigned URL, not just S3. Thus it would be helpful to add a mechanism to every single CLI command to have it output the presigned URL instead of actually executing it.

### Use Case

Sometimes we want to give a user to ability to perform a specific request temporarily, such as IAM CreateAccessKey. Trying to do this via IAM policies is a lot of manual overhead, especially with RBAC. While we could also write a lambda function to do the presigning, it is not particularly convenient either. It would be preferable for the CLI to do it so we can just use Cloud Shell.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.26.5

### Environment details (OS name and version, etc.)

macos 12.6.1

**Comment by tim-finnigan** [comment]
Hi @rittneje thanks for the feature request. I brought this up for team discussion today and the consensus was that this is not something that the CLI team plans to do. It could possibly be a cross-SDK or IAM feature request for creating modeled traits that would allow this though. Did you have any use cases for this feature outside of IAM CreateAccessKey?

**Comment by rittneje** [comment]
We do have a few other use cases:
1. STS GetCallerIdentity (usually but not exclusively covered by `aws eks get-token`)
2. RDS Connect (covered by `aws rds generate-db-auth-token`)

I'm not sure why this would be a cross-SDK or IAM feature requests. The SDKs (including boto3) already support generic pre-signing. And an IAM feature is the opposite of what I would want. Whenever we want to presign a new type of request, it should not involve a new feature request.

**Comment by tim-finnigan** [comment]
Thanks @rittneje for following up and sharing those use cases. In those examples, the service teams STS and RDS would need to update their API models to allow for that behavior. Regarding boto3, [this comment](https://github.com/boto/boto3/issues/3024#issuecomment-933838539) provides more context on the presigning behavior:
>The `generate_presigned_url` method is added to all service clients regardless of if they explicitly support it or not, and unfortunately there is no list of which services do.
>
>The only two services we explicitly know and support presigned URLs now for are S3 and CloudFront. 

So for your requests that relate to specific services you could reach out to through [AWS Support](https://aws.amazon.com/contact-us/) to escalate those or you could also consider creating issues here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues.

**Comment by rittneje** [comment]
That response you quoted is misleading. All AWS services support presigning because it is a feature of SigV4 that is not specific to any particular service. It is possible to generate a presigned URL for any action via botocore. For example: https://github.com/aws-samples/amazon-k8s-node-drainer/blob/a56ca573a84197014d24d02fb4cba8fe8fd99842/drainer/handler.py#L75-L102

In other words, this feature can be implemented generically for all actions.

**Comment by tim-finnigan** [comment]
Closing this issue for the same reasons mentioned in https://github.com/boto/boto3/issues/3512#issuecomment-1366093475. As mentioned above you can reach out to through [AWS Support](https://aws.amazon.com/contact-us/) to escalate service-related feature requests or create an issue in our [cross-SDK repository](https://github.com/aws/aws-sdk/issues).
