### ISSUE TITLE
Able to describe step function express execution 

### ISSUE THREAD

**Issue by lee-butn** [aws/aws-cli#7476]
### Describe the feature

Since UI is now support to get Step Function express , please add this to CLI
https://aws.amazon.com/about-aws/whats-new/2022/10/aws-step-functions-adds-new-execution-observability-features-express-workflows/

### Use Case

Need to debug my application

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.1

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by austin-merkle** [comment]
Realize this ticket has been closed for over a year, but any chance the Step Functions team has plans to extend some of the existing Service API functionality to Express type step functions? `DescribeExecution` would be awesome.
