### ISSUE TITLE
Slow upload speed in Apple Virtualization Framework VMs on M1

### ISSUE THREAD

**Issue by gregiOS** [aws/aws-cli#7478]
### Describe the bug

We are using codemagic.io apple Intel machines for our CI/CD pipelines for iOS project.

As we are using S3 for caching dependencies its fine with Intel devices.

But with Apple m1 machines (virtual instances), all out pipelines timeouts when uploading cache to s3
There is proper issue for codemagic but it looks like AWS issue https://github.com/orgs/codemagic-ci-cd/discussions/955 

### Expected Behavior

AWS s3 CLI performance is similar to Intel machines

### Current Behavior

Cache upload fails 

### Reproduction Steps

Let me know, if you need those

### CLI version used

1.18.105

### Environment details (OS name and version, etc.)

MacOS Monetery

**Comment by rpendleton** [comment]
It looks like #7481 has more information on how to reproduce this.

**Comment by gregiOS** [comment]
Duplicate of: https://github.com/aws/aws-cli/issues/7481 closing now
