### ISSUE TITLE
aws s3 sync does not ignore storage-class of glacier by default

### ISSUE THREAD

**Issue by e0d** [aws/aws-cli#748]
With:

awscli==1.3.6
botocore==0.40.0

While the default param for aws sync for storage-class is documented as STANDARD, files with storage-class of GLACIER are matched when the file list is generated, but throw errors when download is attempted.

```
A client error (InvalidObjectState) occurred when calling the GetObject operation: The operation is not valid for the object's storage class
```

**Comment by gideononline** [comment]
This (InvalidObjectState) error also causes the sync process to be extremely slow.  We have millions of files in an S3 bucket and millions more in glacier.   So although the sync process successfully completes in the end, it takes many hours more than it should because of millions of exceptions.   Any ETA on the fix?

**Comment by joehoyle** [comment]
+1 with this issue, I can't perform a `sync` while using Glacier

**Comment by caedmonjudd** [comment]
+1 on this issue as well.

**Comment by viyh** [comment]
+1, also being able to exclude or include Glacier object types for "ls" would be useful.

**Comment by thomascate** [comment]
+1, has anyone figured out a work around for this?

**Comment by cake-icing** [comment]
+1

**Comment by andacata** [comment]
+1

**Comment by yurasuka** [comment]
+1

**Comment by Argoday** [comment]
+1

**Comment by robbintt** [comment]
it would be so nice if the API provided an MD5 or any equivalent for files in the glacier. Is there any sort of unique ID like an object ID or date + object ID that could be used as a unique ID in order to allow s3 sync to work?
