### ISSUE TITLE
Support multiple repository authentication in CodeArtifact?

### ISSUE THREAD

**Issue by bannarisoftwares** [aws/aws-cli#7483]
### Describe the bug

I have multiple npm package in single project. But i am not able to find out the example. How to authenticate multiple packages in single project what is the syntax?

Single package auth syntax:
`aws codeartifact login --tool npm --repository some-repo --domain somecompany --domain-owner xxxxxx --region ap-south-1`

### Expected Behavior

Able to authenticate multiple packages in single project?

Expected syntax:
`aws codeartifact login --tool npm --repositorys some-repo-1, some-repo-2 --domain somecompany --domain-owner xxxxxx --region ap-south-1`

### Current Behavior

Current syntax:
`aws codeartifact login --tool npm --repository some-repo --domain somecompany --domain-owner xxxxxx --region ap-south-1`

### Reproduction Steps

Current syntax:
`aws codeartifact login --tool npm --repository some-repo --domain somecompany --domain-owner xxxxxx --region ap-south-1`

### CLI version used

latest

### Environment details (OS name and version, etc.)

linux

**Comment by tim-finnigan** [comment]
Hi @bannarisoftwares thanks for reaching out. I think this overlaps with https://github.com/aws/aws-cli/issues/5291 which was resolved when the `--namespace` parameter was added. [Here](https://docs.aws.amazon.com/cli/latest/reference/codeartifact/login.html) is the documentation for reference. Does that parameter address what you're trying to accomplish?

**Comment by bannarisoftwares** [comment]
Yes, Thank you.
