### ISSUE TITLE
Cloudwatch -  File "/usr/lib/python3.7/site-packages/awscli/plugin.py", line 58, in _import_plugins     plugins.append(__import__(path)) ModuleNotFoundError: No module named 'cwlogs'

### ISSUE THREAD

**Issue by zulk85** [aws/aws-cli#7501]
### Describe the bug

Hello...I have situation with Cloudwatch....
My server doesn't pick up the metric from cloudwatch.
I check at awslogs.log file ...
File "/usr/lib/python3.7/site-packages/awscli/plugin.py", line 58, in _import_plugins
plugins.append(__import__(path))
ModuleNotFoundError: No module named 'cwlogs'

What i do is:
Check config file:
/etc/awslogs/awslogs.conf point to correct server - myserver1
/etc/awslogs/awscli.conf point to correct region = my-region

Following the step to re-install cloudwatch:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html
Stuck at 
"To install and configure CloudWatch Logs on an existing Amazon Linux instance" section,
(Optional) Check the /var/log/awslogs.log file for errors logged when starting the service

### Expected Behavior

Hopefully can solve the issue since my EC2 no monitoring

### Current Behavior

I found that when i manually turn the services on,after couple of second,the services automatically down.

[root@ip-xxxxxx ~]# systemctl status awslogsd
● awslogsd.service - awslogs daemon
   Loaded: loaded (/usr/lib/systemd/system/awslogsd.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2022-12-06 11:29:09 +08; 2s ago
  Process: 25072 ExecStart=/usr/sbin/awslogsd (code=exited, status=1/FAILURE)
 Main PID: 25072 (code=exited, status=1/FAILURE)
 
Please advice. 

### Reproduction Steps

-Try re-install python to latest version and no luck
-Looks like API not working between AWS and Server

### CLI version used

aws --version aws-cli/1.24.3 Python/3.7.10 Linux/4.14.296-222.539.amzn2.x86_64 botocore/1.24.33

### Environment details (OS name and version, etc.)

Linux - AMI 2

**Comment by tim-finnigan** [comment]
Hi @zulk85 thanks for reaching out. It looks like this was also asked about here: https://repost.aws/questions/QU33Zxt6teQpelrErHIgHbUA/cloudwatch-issue-module-not-found-error-no-module-named-cwlogs. 

Have you tried using the `sudo` command as recommended there to install the package?

**Comment by zulk85** [comment]
> Hi @zulk85 thanks for reaching out. It looks like this was also asked about here: https://repost.aws/questions/QU33Zxt6teQpelrErHIgHbUA/cloudwatch-issue-module-not-found-error-no-module-named-cwlogs.
> 
> Have you tried using the `sudo` command as recommended there to install the package?

Hello....thanks for reply...really appreciate it...
I have done the installation & upgrade process using sudo.
But the issue still persist.

Results as per images:
sudo pip install awscli-cwlogs
![07122022](https://user-images.githubusercontent.com/80100404/206087570-b8d8869e-0725-46e3-bfb1-8a61b75313af.PNG)

sudo pip install --upgrade awscli-cwlogs
![07122022_2](https://user-images.githubusercontent.com/80100404/206087583-2371f533-1a4c-408f-a679-13ef1b14ae02.PNG)

Not sure what am i missing.
Please advice

**Comment by tim-finnigan** [comment]
Hi @zulk85 thanks for following up. I found another comment that mentioned this plugin was deprecated: https://github.com/aws/aws-cli/issues/5020#issuecomment-824851293. I recommend updating to v2 of the AWS CLI for access to the latest functionality.
