### ISSUE TITLE
AWS CLI can't run normally in WIN10 suddenly 

### ISSUE THREAD

**Issue by Wyifei** [aws/aws-cli#7519]
### Describe the bug

**aws --version**
aws-cli/2.9.6 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

**aws s3 ls --profile dev**

An error occurred (InvalidToken) when calling the ListBuckets operation: The provided token is malformed or otherwise invalid.

The same profile works normally in Linux, but in WIN10 will come across above issue

### Expected Behavior

AWS CLI could run normally in WIN10

### Current Behavior

AWS CLI can't run normally in WIN10 suddenly 

### Reproduction Steps

1. Update the credentials file
2. Run aws s3 ls --profile <profile>
3. System prompt invalid token

### CLI version used

2.9.6

### Environment details (OS name and version, etc.)

WIN10

**Comment by tim-finnigan** [comment]
Hi @Wyifei thanks for reaching out. How did you originally set your credentials? I recommend using the [aws configure](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config) command to set the default profile. If you generate a new profile and set the credentials again do you still see the issue? I'd double-check that you didn't copy any blank space or extra characters when adding the credentials.
