### ISSUE TITLE
Support for Lambda SnapStart runtime hooks

### ISSUE THREAD

**Issue by samdengler** [aws/aws-cli#7525]
### Describe the feature

Add support for the SnapStart CRaC runtime hooks, beforeCheckpoint() and afterRestore(), when running `sam local`.

### Use Case

I would like to test the CRaC runtime hooks locally before deploying my SnapStart-enabled Lambda function to AWS.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.9.2 Python/3.11.0 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Monterey 12.6.1

**Comment by tim-finnigan** [comment]
Hi @samdengler I believe this issue was intended for the SAM CLI (https://github.com/aws/aws-sam-cli/) rather than the AWS CLI. Please let us know if that's not the case, otherwise I recommend closing this and creating an issue in that repository

**Comment by samdengler** [comment]
Thanks so much, @tim-finnigan.  Sorry for the confusion.  I'll close here and open one with the aws-sam-cli repo.
