### ISSUE TITLE
xray get-trace-summaries: --no-paginate enables pagination

### ISSUE THREAD

**Issue by dennis-grunert** [aws/aws-cli#7529]
### Describe the bug

The command `aws xray get-trace-summaries --start-time 1669718100 --end-time 1669718759` results in 6517 traces to be found, but the resulting JSON says `"TracesProcessedCount" :2000'`. It also doesn't provide a `NextToken`, which indicates that it was using _not_ using pagination.

The same command with `--no-paginate` results in only 2000 traces. The resulting JSON provides a `NextToken` indicating that tracing is activated even though `--no-paginate` was given.

It seems that `--no-paginate` does the exact opposite as it is supposed to do.

### Expected Behavior

1. `aws xray get-trace-summaries` should have pagination _enabled_.
2. `aws xray get-trace-summaries --no-paginate` should have pagination _disabled_.

### Current Behavior

1. `aws xray get-trace-summaries` has pagination _disabled_.
2. `aws xray get-trace-summaries --no-paginate` has pagination _enabled_.

### Reproduction Steps

See above.

### CLI version used

2.9.7

### Environment details (OS name and version, etc.)

aws-cli/2.9.7 Python/3.11.0 Darwin/22.1.0 source/x86_64 prompt/off

**Comment by aBurmeseDev** [comment]
Hi @dennis-grunert - thanks for reaching out.

I tried to replicate this behavior by running `aws xray get-trace-summaries` and it returned with pagination along with `NextToken`. I also ran with `--no-paginate` and it behaves as expected. 

Would you be able to share your debug logs by appending `--debug` to your command (with any sensitive info redacted)?

Best,
John

**Comment by dennis-grunert** [comment]
@aBurmeseDev I double check again it is the other way around for me. Please see the attached files that have been created with these commands:

`aws xray get-trace-summaries --start-time 1671109740 --end-time 1671109920 --debug > with_pagination.json 2>debug_with_pagination.log`

`aws xray get-trace-summaries --start-time 1671109740 --end-time 1671109920 --no-paginate --debug > without_pagination.json 2>debug_without_pagination.log`

The file names ("with" vs. "without") represent the expected behavior. The actual behavior is the opposite:
* `with_pagination.json`:
  * `"TracesProcessedCount": 2031`
  * 2071 (i.e., 40 more than announced) exist in the json.
  * No `NextToken` exists.
* `without_pagination.json`:
  * `"TracesProcessedCount": 2031`
  * 2031 traces are contained in the json.
  * `"NextToken": "Bthh/NEYXeYjfXJyZNipIg86iXXt8lKCsKC/nEjbrx8="`

The output jsons are not attached since they contain a lot of sensitive information. But the debug outputs with redacted sensitive information are attached.

[debug_with_pagination.log](https://github.com/aws/aws-cli/files/10336897/debug_with_pagination.log)
[debug_without_pagination.log](https://github.com/aws/aws-cli/files/10336898/debug_without_pagination.log)

**Comment by athielen2** [comment]
Can confirm I am getting the same behavior on the latest CLI for MacOS:

```
aws --version
aws-cli/2.11.27 Python/3.11.3 Darwin/21.6.0 exe/x86_64 prompt/off
```

```
aws iot list-things-in-thing-group --thing-group-name "ABC-123" --no-paginate
{
    "things": [
        "THING-123456",
        .... 24 more things ....
    ],
    "nextToken":  "....."
```

Without the `--no-paginate` flag, it does **not** paginate, and returns several thousand things.
