### ISSUE TITLE
aws ecs register-task-definition fails when using portMappings.name (needed for ECS Service Connect)

### ISSUE THREAD

**Issue by annuh** [aws/aws-cli#7531]
### Describe the bug

Hi,

I'm would like to try the new ECS Service Connect service, but I'm having issues setting up the task-definition.

We are using ECS on EC2 instances. 
Here is the (simplified) CLI command I'm using:

```
/usr/local/bin/aws --output json ecs --region eu-central-1 register-task-definition --cli-input-json '{
  "family": "symfony",
  "volumes": [],
  "containerDefinitions": [
    {
      "name": "symfony",
      "image": "__IMAGE__",
      "cpu": 0,
      "memoryReservation": 500,
      "portMappings": [
        {
          "name": "symfony-8082-tcp",
          "containerPort": 8082,
          "hostPort": 0,
          "protocol": "tcp"
        }
      ],
      "essential": true,
    }
  ],
}'
```

### Expected Behavior

Task-definition is created without error.

### Current Behavior

This triggers the following error:

```
Parameter validation failed:
Unknown parameter in containerDefinitions[0].portMappings[0]: "name", must be one of: containerPort, hostPort, protocol
```

However, according `portMapping.name` is a valid parameter according to https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RegisterTaskDefinition.html

### Reproduction Steps

```
docker run devopscorner/aws-cli aws --output json ecs --region eu-central-1 register-task-definition --cli-input-json '{
  "family": "symfony",
  "volumes": [],
  "containerDefinitions": [
    {
      "name": "symfony",
      "image": "__IMAGE__",
      "cpu": 0,
      "memoryReservation": 500,
      "portMappings": [
        {
          "name": "symfony-8082-tcp",
          "containerPort": 8082,
          "hostPort": 0,
          "protocol": "tcp"
        }
      ],
      "essential": true,
    }
  ],
}'
```

It is possible to create a new task-definition via the AWS Console, using the same JSON.

### CLI version used

2.9.1

### Environment details (OS name and version, etc.)

Amazon ECS optimized Amazon Linux 2

**Comment by aBurmeseDev** [comment]
Hi @annuh - thank you for reaching out.

As you mentioned, `portMappings.name` is valid parameter. However, from looking at the API docs, it mentioned that
>The name that's used for the port mapping. This parameter **only applies** to Service Connect. This parameter is the name that you use in the [serviceConnectConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect.html) of a service. 

That means the `name` parameter isn't required unless for Service Connect. With that said, I tested using the same JSON provided **without** `portMappings.name` and it was created successfully. 

Hope it helps but if you still have followup questions, please let me know.

Best,
John

**Comment by annuh** [comment]
Hi @aBurmeseDev, thanks for your reply. The issue here is that I actually _want_ to use the Service Connect feature. 

According to https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-connect.html, the first step is to add the `portMappings.name` parameter to the task-defintion.

**Comment by aBurmeseDev** [comment]
@annuh - thanks for clarifying that. Looks like Service Connect support was added in CLI 2.9.2, per [changelog](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst) and I was able to confirm it by testing it with the latest CLI version and it worked as expected. 

Here's docs on updating CLI for reference: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

Please let me know if that works out.
Best,
John

**Comment by annuh** [comment]
Thanks, that explains it! 😄 

```
❯ docker run --platform linux/amd64 devopscorner/aws-cli aws --version
aws-cli/2.9.1 Python/3.10.5 Linux/5.15.49-linuxkit exe/x86_64.alpine.3 prompt/off
```

We will switch to the official aws-cli image.
