### ISSUE TITLE
Allow switching of default profile

### ISSUE THREAD

**Issue by markry** [aws/aws-cli#7532]
### Describe the feature

It would make the CLI profile feature far easier to use if the user did not have to specify a non-default profile each time a command was issued. In almost all cases when using profiles, the same profile is used over and over again during a given working session. While the stored values in the default profile can be changed manually or with a script, it would be much more convenient to be able to switch from one profile to another as the default.

### Use Case

It's inefficient and frustrating to continually add the same "--profile foo" to every single command during a given working session. It would be far better to be able to easily change the default. 

### Proposed Solution

I propose a new command for aws configure, for example:

`aws configure switch-default --profile foo
`

Would overwrite the values in the default profile with the values in foo. Or, perhaps for backwards compatibility, the stored values in the default profile would not be over-written, but rather the values in foo would be placed automatically in environment variables, and thus be prior to the default. However, that's possibly over-complicated and confusing because now the configuration and credentials files are no longer the "source of truth" about these settings.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.9.7

### Environment details (OS name and version, etc.)

Windows 11

**Comment by RyanFitzSimmonsAK** [comment]
Hi @markry, thanks for reaching out.  This feature request has actually come up in the past, most recently in this issue ([#6880](https://github.com/aws/aws-cli/issues/6880)).  This [comment](https://github.com/aws/aws-cli/issues/6880#issuecomment-1105774146) provides context as to why the team is not considering this feature currently, and the thread may have details on workarounds you might not have considered.

**Comment by markry** [comment]
FWIW I find the previous response unconvincing. Exporting a new environment variable is relative unnatural in terms of a normal CLI workflow / session compared to using a built-in command. And it's different between Windows and Linux, which I have to remember each time I switch between them. I still think the team should add a "set current default profile" capability as a built-in feature.

**Comment by 0xByteLeon** [comment]
Really need this!!!!!!! Please!
