### ISSUE TITLE
aws glue list-data-quality-rulesets always returns empty results

### ISSUE THREAD

**Issue by ParthaI** [aws/aws-cli#7537]
### Describe the bug

Even if resources are accessible in the console, the CLI command `aws glue list-data-quality-rulesets` returns an empty result.
Also, the get CLI command (`aws glue get-data-quality-ruleset —name test43-1`) gives a 'EntityNotFoundException' even if the resource is available in the console.

<img width="1384" alt="Screenshot 2022-12-20 at 4 57 04 PM" src="https://user-images.githubusercontent.com/47887552/208656385-b43781cc-2beb-4642-9557-761aa342ba2b.png">
<img width="634" alt="Screenshot 2022-12-20 at 4 58 01 PM" src="https://user-images.githubusercontent.com/47887552/208656502-b7dbec3b-712b-4014-ad55-a294bb4eb9e1.png">
<img width="1210" alt="Screenshot 2022-12-20 at 5 00 19 PM" src="https://user-images.githubusercontent.com/47887552/208656911-aa06d733-d42f-40df-941f-642f451c0943.png">

### Expected Behavior

The command `aws glue list-data-quality-rulesets` should return the resources available in console.

### Current Behavior

Glue DataQuality Ruleset resources are available in my console, while trying to get available resources by using CLI command `aws glue list-data-quality-rulesets` it is returning zero results.

### Reproduction Steps

- Create a Glue DataQuality Ruleset resource in console.
-  Run the command `aws glue list-data-quality-rulesets` to list out the resource.

### CLI version used

aws-cli/2.9.4 Python/3.9.11 Darwin/20.5.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Mac, Big Sur, 11.4

**Comment by tim-finnigan** [comment]
Hi @ParthaI thanks for reaching out. Can you confirm that you are using the correct profile and region where your rulesets are located?

**Comment by ParthaI** [comment]
Hello, @tim-finnigan. Thank you for responding so quickly.
Yes, I am using the right profile and the region where the ruleset is situated. I can retrieve the Glue Database and Table information by using the same profile/credential.
Do we need any particular permissions or permits to list the Glue DataQualility Ruleset resources?

**Comment by ParthaI** [comment]
The rule sets were not present in my Glue Table. However, they were available in the Data Brew console. Now I am able to get those resource details.
