### ISSUE TITLE
Does this mean AWS has officially dropped support for awscli v1?

### ISSUE THREAD

**Issue by Dreamypops33** [aws/aws-cli#7556]
https://github.com/actions/starter-workflows/actions/runs/3686706644/jobs/6239306887

**Comment by tim-finnigan** [comment]
Hi @Dreamypops33 - AWS has not dropped support for AWS CLI v1. We recommend using v2 as v1 will get deprecated at some point in the future. But there will be several announcements and a roadmap leading up to that. For more information you can refer to this documentation on the AWS SDKs and Tools maintenance policy: https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html#communication-methods.
