### ISSUE TITLE
ssm start-session messes up the terminal after timeout on WSL

### ISSUE THREAD

**Issue by bencehornak-gls** [aws/aws-cli#7574]
### Describe the bug

On WSL the `aws ssm start-session` command corrupts my terminal after it terminates due to inactivity. Regardless of what key I press, no characters appear in the terminal any more. I have tried Ctrl + C too, but it doesn't change the unresponsiveness of my terminal either.

### Expected Behavior

I should be able to use the terminal for other commands.

### Current Behavior

Regardless of what key I press, nothing appears in the terminal.

### Reproduction Steps

1. Install Ubuntu 2020 using WSL 2 on a Windows Enterprise machine.
2. Install AWS CLI and the SSM plugin
3. Launch a session with `aws ssm start-session --target i-XXXXXXXXXXX`
4. Wait 5 minutes
5. Now the terminal becomes unresponsive

### Additional Information/Context

I start the ssm session like this:
```
aws ssm start-session --target i-0ac4445bb00XXXXXX
Starting session with SessionId: XXXX@YYYY.com
sh-4.2$ id
uid=1001(ssm-user) gid=1007(ssm-user) groups=1007(ssm-user) context=system_u:system_r:unconfined_service_t:s0
```

Then I wait a couple of minutes and press a random key:
```
sh-4.2$ Cannot perform start session: write tcp 172.22.193.94:55404->193.106.225.65:8080: write: broken pipe
```

The session is terminated due to some timeout. The problem occurs _after this_, as my terminal becomes unusable for further commands, nothing appears on my screen any more as I type.

### CLI version used

aws-cli/2.9.12 Python/3.9.11 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

Windows 10 Enterprise, WSL 2, Ubuntu 2020

**Comment by tim-finnigan** [comment]
Hi @bencehornak-gls thanks for reaching out. I think the SSM agent repository (https://github.com/aws/amazon-ssm-agent) is a better place for this, so I recommend creating an issue there. I saw a couple of existing issues there that might overlap with this one: https://github.com/aws/amazon-ssm-agent/issues/354 and https://github.com/aws/amazon-ssm-agent/issues/367. You could consider following up on one of those issues. And if there is something to investigate further on the AWS CLI side then we can revisit this here.

**Comment by bencehornak-gls** [comment]
Hi @tim-finnigan, thanks for the references.
I checked up on both PRs, but they seem to be unrelated to my issue.
- https://github.com/aws/amazon-ssm-agent/issues/354 is related to non-interactive terminals, which cannot be used to execute any commands. In my use case the terminal is interactive, and I can execute commands. This bug happens after the timeout, my bash becomes unresponsive.
- https://github.com/aws/amazon-ssm-agent/issues/367 is related to port forwarding, I don't see how it would be related to this PR.

My gut feeling is that this is a client side issue, probably the aws ssm plugin doesn't release some tty resources, and that's why I can't use my terminal after it. So that's the reason I opened the PR here and not in the agent repository.

Let me know, if you need more information!

**Comment by bencehornak-gls** [comment]
@tim-finnigan did you have a chance to take a look at this? Do you need further input from my side?

**Comment by tim-finnigan** [comment]
@bencehornak-gls actually a better repository for this issue might be https://github.com/aws/session-manager-plugin. Can you open an issue there for further investigation? I'm not sure what the cause of this issue could be but you could try [reinstalling the plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html) and checking your shell config. Can you reproduce this issue in other environments?

**Comment by bencehornak-gls** [comment]
@tim-finnigan thanks for the tip, I will open a similar issue there too. I did restart the plugin before opening this issue, and what reinforced me that this is a generic issue, is that my colleagues have been experiencing the same symptoms.

I have only been working with WSL, I did not try it with a purely Linux machine. I will try to reproduce, when I can get my hands on one.

**Comment by Florent-Mendoza** [comment]
Hello @bencehornak-gls , I have the same issue, it's annoying, but just type "reset" (without the quote) in your terminal and enter => your terminal will be back to normal.
