### ISSUE TITLE
The wait time stated for db-snapshot-available is incorrect

### ISSUE THREAD

**Issue by AndrewCharlesHay** [aws/aws-cli#7578]
### Describe the issue

The documentation states 

```
It will poll every 30 seconds until a successful state has been reached. This will exit with a return code of 255 after 60 failed checks.
```

Unless my math is incorrect `30 seconds * 60 attempts = 30 minutes of attempts`. However this does not appear to be correct. In my experience I have consistently been return the following error after 10 minutes.

```bash
Waiter DBSnapshotCompleted failed: Max attempts exceeded
```

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/wait/db-snapshot-available.html

**Comment by tim-finnigan** [comment]
Hi @AndrewCharlesHay thanks for reaching out. You linked to the `DBSnapshotAvailable` waiter, but the error message references the `DBSnapshotCompleted` completed waiter. Can you confirm that you're using the waiter you intended? 

You can see the waiter model polling logic here in botocore: https://github.com/boto/botocore/blob/develop/botocore/data/rds/2014-10-31/waiters-2.json. Those waiter definitions should be consistent with the CLI documentation. If you're still seeing the issue please share your debug logs by adding `--debug` to the command (with any sensitive info redacted).
