### ISSUE TITLE
Using --query to select tag by value not tab delimitated

### ISSUE THREAD

**Issue by catofclysm** [aws/aws-cli#758]
Previously when I used --query to select a specific tag value by key it's text output was tab delimitated. After updating to the latest aws-cli (from 1.3.1 to 1.3.7) the tag value is now added after other values and on it's own line. For example:

aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId, Tags[?Key==`Name`].Value, State.Name]' --output text 

The output of such is
InstanceID   State
TagValue

Whereas before it would show
InstanceId   TagValue   State

**Comment by Hount** [comment]
Umgh, how come I see the exact same issue with awscli aws-cli/1.9.8 Python/2.7.10 Linux/4.2.6-201.fc22.x86_64+debug botocore/1.3.8?

aws ec2 describe-instances --profile=dev --query  "Reservations[*].Instances[*].[State.Name,InstanceId,InstanceType,Tags[0].Value]" --output table
|  running|  i-idididid |  t2.micro    |  test-machinename                                                |

 aws ec2 describe-instances --profile=dev --query  "Reservations[*].Instances[*].[State.Name,InstanceId,InstanceType,Tags[?Key=='Name'].Value]" --output table

|  running                                    |
|  i-idididid                                 |
|  t2.micro                                   |
|  test-machinename                            |

As a workaround
aws ec2 describe-instances --profile=dev --query  "Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key=='Name'].Value | [0], InstanceType]" --output table
|  i-idididid|  running |  test-machinename                            |  t2.micro     |

**Comment by blueyed** [comment]
@Hount 
The key here is to use `Tags[?Key==`Name`].Value | [0]`.

**Comment by rquadling** [comment]
Just as a way to demonstrate a use case.
```
alias ec2p="aws ec2 describe-instances --profile production --query \"sort_by(Reservations[].Instances[].{Name:Tags[?Key=='Name'].Value|[0],ID:InstanceId,Type:InstanceType,IP:PrivateIpAddress,State:State.Name,AMI:ImageId}, &Type) | []\" --output table"
alias ec2s="aws ec2 describe-instances --profile staging --query \"sort_by(Reservations[].Instances[].{Name:Tags[?Key=='Name'].Value|[0],ID:InstanceId,Type:InstanceType,IP:PrivateIpAddress,State:State.Name,AMI:ImageId}, &Type) | []\" --output table"
```
