### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Abhi-lash19** [aws/aws-cli#7581]
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/home/vagrant/.local/lib/python2.7/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/home/vagrant/.local/lib/python2.7/site-packages/botocore/__init__.py", line 96
    name = f"{name[: -len(matched)]}{sep}{matched.lower()}"
                                                          ^
SyntaxError: invalid syntax
 I am still getting the above error I mentioned. I tried all the ways mentioned above. please help if possible 

_Originally posted by @Abhi-lash19 in https://github.com/aws/aws-cli/issues/2843#issuecomment-1380186400_

**Comment by Abhi-lash19** [comment]
Kind/support

**Comment by nateprewitt** [comment]
Hi @Abhi-lash19, it looks like you're trying to install a recent version of the CLI with Python 2.7. The CLI dropped support for that version of Python in 2021, so you'll need to pin to an older version of the CLI or upgrade your Python interpreter. You can find our[ blog post ](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/) with more information and specific instruction in our CLI [upgrade and migration guide](https://github.com/aws/aws-cli/blob/develop/UPGRADE_PY3.md#if-youre-unable-to-upgrade-to-python-3).
