### ISSUE TITLE
lambda invoke returns an error string that brakes the json

### ISSUE THREAD

**Issue by karlpokus** [aws/aws-cli#7599]
### Describe the bug

If I add `--log-type Tail` to `lambda invoke` I get `LogResult` in the returned json. I'd like to parse this with jq but there is also what looks like a nil-error returned that brakes jq parsing. Can I omit the returned error string and only get proper json?

### Expected Behavior

Only get valid json

### Current Behavior

````
{ull
    "StatusCode": 200,
    "LogResult": <omitted>,
    "ExecutedVersion": "$LATEST"
}
````

### Reproduction Steps

````
aws lambda invoke \
  --function-name my-func \
  --log-type Tail \
  /dev/stdout

{ull
    "StatusCode": 200,
    "LogResult": <omitted>,
    "ExecutedVersion": "$LATEST"
}
````

### Additional Information/Context

My lambda is written in go and only returns a single error

### CLI version used

aws-cli/2.9.1 Python/3.9.11 Linux/5.14.0-1056-oem exe/x86_64.ubuntu.20 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 20.04.5

**Comment by aBurmeseDev** [comment]
Hi @karlpokus - thanks for reaching out.

Upon reading the post, it seems that the issue you're having is the returned 'nil-error'? Could you provide the full returned response (without any sensitive info) including the error along with your lambda function code? I'm trying to understand the overall scope of the workflow before proceeding with the investigation.
Thanks,
John

**Comment by karlpokus** [comment]
> Hi @karlpokus - thanks for reaching out.
> 
> 
> 
> Upon reading the post, it seems that the issue you're having is the returned 'nil-error'? Could you provide the full returned response (without any sensitive info) including the error along with your lambda function code? I'm trying to understand the overall scope of the workflow before proceeding with the investigation.
> 
> Thanks,
> 
> John

Hi!

The full response is included in "current behavior" above. It's the json blob with {ull in the first line.

**Comment by karlpokus** [comment]
The lambda returns a single go error. I expect this is what causes the wierd {ull line when the error is nil.

**Comment by aBurmeseDev** [comment]
@karlpokus - thanks for following up. I wasn't able to reproduce the same behavior on my end. Have you tried reaching out to Go SDK since you mentioned that your lambda is written in go and receives single go error? If you could provide the full debug logs, we might be able to look deeper into it. You could get the logs by appending `--debug` to the command you ran.
