### ISSUE TITLE
Lambda can't decrypt container image after use of "update-function-code"

### ISSUE THREAD

**Issue by mik3fly** [aws/aws-cli#7601]
### Describe the bug

In a multi account context, i have lambdas in different account (A,B,C) that pull an image from an ECR into another account (D)
All permissions, KMS are good. I use cloud formation to deploy theses objects and there is no problem with theses lambdas.

But if i use the "aws lambda update-function-code --function-name complete-arn-of-the-function --image-uri image-ecr-link", all lambdas are immediately broken and cannot works until i erase and recreate all with cloud formation. 

### Expected Behavior

aws lambda update-function-code to works without breaking lambdas

### Current Behavior

`An error occurred (KMSAccessDeniedException) when calling the Invoke operation (reached max retries: 2): Lambda can't decrypt the container image because KMS access is denied. Check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.`

### Reproduction Steps

Multi account context
- IAM User in account D
-- Allowed to do operations "Invoke", "UpdateFunctionCode", "GetFunction", "GetFunctionConfiguration" in lambda A,B, and C.

- An ECR into a different account from lambdas (D), using a Client manged KMS key into the same account
-- Allows to pull from external account

- A Client Managed KMS Key
-- Allows external use from account A,B,C, and D

- Role into account A,B,C
-- Allowed to pull image from ECR into an external account (D)
-- Allowed to use a KMS key from an external account  (D)

- Lambdas in different account A,B,C
-- With following permission "Invoke", "UpdateFunctionCode","GetFunction", "Get-Function-Configuration" for a IAM User in account D
-- With Code from IMAGE pulled from the ECR in Account D

Then 

`aws lambda update-function-code --function-name complete-arn-of-the-function --image-uri`

followed by
`aws lambda wait function-updated --function-name complete-arn-of-the-function`  
`aws lambda invoke --function-name complete-arn-of-the-function output`

Will produce the above text error in "Current Behavior"

### Additional Information/Context

aws lamba UpdateFunctionCode is called from a github action pipeline, but i have the same results from my machine. The command is called with the IAM user in account D credentials.

### CLI version used

ws-cli/2.4.22 Python/3.8.8 Linux/5.15.0-58-generic exe/x86_64.ubuntu.20 prompt/off

### Environment details (OS name and version, etc.)

github actions

**Comment by brbernardo** [comment]
The issue you are encountering is related to the use of a KMS key for encrypting the image in the ECR repository. The lambdas in accounts A, B, and C are unable to decrypt the image using the KMS key, resulting in the "KMSAccessDeniedException" error.

Possible solutions to this issue could include:

- Double-checking that the IAM user in account D has the correct permissions to access the KMS key in account D.
- Double-checking that the KMS key in account D has the correct permissions to be accessed by the lambdas in accounts A, B, and C.
- Double-checking that the role in accounts A, B, and C has the correct permissions to access the ECR repository in account D and the KMS key in account D.
- Verify that the IAM user in account D has the correct permissions to invoke the function in A, B and C.

If the problem persists, it may be necessary to recreate the lambdas in accounts A, B, and C using cloud formation, as you mentioned, to ensure that all necessary permissions and configurations are in place.

**Comment by tim-finnigan** [comment]
Thanks @brbernardo for sharing that information! @mik3fly does that help resolve your issue?
