### ISSUE TITLE
glacier get-job-output is impossible to call with jobId starting with "-"

### ISSUE THREAD

**Issue by dennistruemper** [aws/aws-cli#7608]
### Describe the bug

- use an M1 Mac with zsh
- create ArchiveRetrieval job (jobId starts with "-")
- wait for job to be in status Succeeded
- execute get-job-output command
- error: job-id expects argument

### Expected Behavior

I want to be able to download the archive after the ArchiveRetrieval job is finished

### Current Behavior

I want to Download an Archive from glacier. So I started a job. Here is the list-jobs output (JobId starts with -, I removed some letters in between):

```
 aws glacier list-jobs --account-id 111222333 --vault-name my-vault-name
{
    "JobList": [
        {
            "JobId": "-TKIDUV5zpbmoXw4Zgw_477...uNbOA8-I0yGd",
            "JobDescription": "Get Archive",
            "Action": "ArchiveRetrieval",
            "ArchiveId": "....",
            "VaultARN": "...",
            "CreationDate": "2023-01-23T17:35:55.582Z",
            "Completed": true,
            "StatusCode": "Succeeded",
            "StatusMessage": "Succeeded",
            "ArchiveSizeInBytes": 68770,
            "CompletionDate": "2023-01-23T17:37:00.157Z",
            "SHA256TreeHash": "...",
            "ArchiveSHA256TreeHash": "...",
            "RetrievalByteRange": "0-68769",
            "Tier": "Expedited"
        },
```

No matter the escaping, all I get from calling get-job-output is an error:
```
aws glacier get-job-output --account-id 111222333 --vault-name my-vault-name --job-id '-TKIDUV5zpbmoXw4Zgw_477...uNbOA8-I0yGd' output.yaml
```

Error argument for --job-id is missing:
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --job-id: expected one argument
```

### Reproduction Steps

Well, it is kind of hard to reproduce, you have to get a jobId that starts with "-"

### Possible Solution

As my reporting suggests, I am quite convinced, the reason is the hyphen at the beginning of the jobId

### Additional Information/Context

I repeated the process. The second time my jobId was hlyEkXYxHxZb6ISqhTLJw3ko...imkbU40X8UzY, so no "-" to start with. This time it worked without a problem.

### CLI version used

aws-cli/2.9.12 Python/3.11.1 Darwin/22.1.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOs 13.0 (22A380)

**Comment by tim-finnigan** [comment]
Hi @dennistruemper thanks for reaching out. It looks like this is a duplicate of this older issue: https://github.com/aws/aws-cli/issues/1409. If you provide an equals sign as recommend [here](https://github.com/aws/aws-cli/issues/1409#issuecomment-119738898) then that should resolve the issue. Please let us know if you had any follow up questions.
