### ISSUE TITLE
"aws rds list-tags-for-resource --resource-name arn:xxx" returns no data

### ISSUE THREAD

**Issue by rmgas1** [aws/aws-cli#7610]
### Describe the bug

"aws rds list-tags-for-resource --resource-name arn:xxx" returns no data for a resource with tags.

### Expected Behavior

"aws rds list-tags-for-resource --resource-name arn:xxx" should return data for a resource with tags.

### Current Behavior

The command does not produce any errors, returns no data, i.e.:

```zsh
% aws rds list-tags-for-resource --resource-name arn:xxx
% 
```

### Reproduction Steps

aws rds list-tags-for-resource --resource-name arn:xxx

### Possible Solution

Based on the debug log, could it be that awscli.formatter is not processing the response correctly? Refer to debug log below.

### Additional Information/Context

calling with --debug shows the tags, but these are somehow suppressed in subsequent calls and not returned (actual returned values and keys replaced with VALUEn, KEYn below):
```html
<snip>
...
2023-01-24 19:27:23,179 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ListTagsForResourceResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">\n  <ListTagsForResourceResult>\n    <TagList>\n      <Tag>\n        <Value>VALUE1</Value>\n        <Key>KEY1</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE2</Value>\n        <Key>KEY2</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE3</Value>\n        <Key>KEY3</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE4</Value>\n        <Key>KEY4</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE5</Value>\n        <Key>KEY5</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE6</Value>\n        <Key>KEY6</Key>\n      </Tag>\n      <Tag>\n        <Value>VALUE7</Value>\n        <Key>KEY7</Key>\n      </Tag>\n    </TagList>\n  </ListTagsForResourceResult>\n  <ResponseMetadata>\n    <RequestId>5f531ed2-1f1e-4b45-a203-bc35817d4d88</RequestId>\n  </ResponseMetadata>\n</ListTagsForResourceResponse>\n'
2023-01-24 19:27:23,180 - MainThread - botocore.hooks - DEBUG - Event needs-retry.rds.ListTagsForResource: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x113463890>>
2023-01-24 19:27:23,180 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2023-01-24 19:27:23,180 - MainThread - botocore.hooks - DEBUG - Event after-call.rds.ListTagsForResource: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x113424cd0>>
2023-01-24 19:27:23,180 - MainThread - awscli.formatter - DEBUG - RequestId: 5f531ed2-1f1e-4b45-a203-bc35817d4d88
```

### CLI version used

aws-cli/2.9.17

### Environment details (OS name and version, etc.)

macOS 10.15.7; aws-cli/2.9.17 Python/3.11.1 Darwin/19.6.0 source/x86_64 prompt/off

**Comment by tim-finnigan** [comment]
Hi @rmgas1 thanks for reaching out. I tried to reproduce this issue with the AWS CLI v2.9.17 but wasn't able to. Which kind of RDS resources are you trying to list the tags for? I created tags on an RDS DB cluster snapshot and this command returned the `TagList`:

`aws rds list-tags-for-resource --resource-name arn:aws:rds:us-west-2:<account>:cluster-snapshot:test-123`
```
{
    "TagList": [
        {
            "Key": "test",
            "Value": "123"
        }
    ]
}
```

Are you seeing similar issues with other commands/services? You might consider trying to uninstall/reinstall the AWS CLI.

**Comment by rmgas1** [comment]
Hello @tim-finnigan, thanks for chasing it up.

It was for a Microsoft SQL Server instance via:
``` shell
aws rds list-tags-for-resource --resource-name arn:aws:rds:ap-southeast-2:<account>:db:<database>
```
I had no issues with other commands, just the "rds list-tags-for-resource" ones.

I can get the data via:
``` shell
aws rds describe-db-instances  --db-instance-identifier <database> --query DBInstances[*]."TagList"
```
or by running the original command via nix:
``` shell
$ nix-shell -p awscli
$ export AWS_PROFILE=<profile>
$ aws --version
aws-cli/1.27.40 Python/3.10.9 Darwin/19.6.0 botocore/1.29.40
$ aws rds list-tags-for-resource --resource-name arn:aws:rds:ap-southeast-2:<account>:db:<database>
{
    "TagList": [
...
    ]
}
```
so it looks specific to that macOS version.

Thanks for looking into it.

**Comment by tim-finnigan** [comment]
Hi @rmgas1 thanks for following up. For further investigation into this we'd request that you please share your debug logs (with any sensitive info redacted) by appending `--debug` to the command. Given that I couldn't reproduce the issue, I also recommend re-installing the AWS CLI per the [recommended methods](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and trying this again on the latest version.
