### ISSUE TITLE
aws s3 mv fails when --recursive is used

### ISSUE THREAD

**Issue by david-peters-aitch2o** [aws/aws-cli#7618]
### Describe the bug

I move files periodically to S3 via a cron job which calls below script:

#!/bin/bash
exec > /var/log/attachments_mover_log.log 2>&1

if [ -e /tmp/attssyncjob.lock ]
then
  echo "ATTS job already running...exiting" >> /var/log/cron
  exit
fi

/usr/bin/touch /tmp/attssyncjob.lock
trap 'rm /tmp/attssyncjob.lock' EXIT

/usr/local/bin/aws s3 mv /attachments/ s3://xxxxatts/attachments --no-follow-symlinks --recursive --exclude "/attachments/temp/*" --exclude "/attachments/check"

the output is: 
Completed 65.9 MiB/~65.9 MiB (286.2 KiB/s) with ~0 file(s) remaining (calculating...)

but the process does not exit

if I run the command without the script via bash:

/usr/local/bin/aws s3 mv /attachments/ s3://xxxxatts/attachments --no-follow-symlinks --recursive --exclude "/attachments/temp/*" --exclude "/attachments/check"

I get the same output, I can see all the files being moved but then it gets stuck at:
Completed 65.9 MiB/~65.9 MiB (286.2 KiB/s) with ~0 file(s) remaining (calculating...)

### Expected Behavior

the command to exit cleanly when done

### Current Behavior

the command hangs and does not exit

### Reproduction Steps

/usr/local/bin/aws s3 mv /attachments/ s3://xxxxatts/attachments --no-follow-symlinks --recursive --exclude "/attachments/temp/*" --exclude "/attachments/check"

run a move with --no-follow-symlinks --recursive and --exclude

the system does not run out of memory or is under cpu load, minimal IOPS

### CLI version used

aws-cli/1.20.61 Python/3.9.15 FreeBSD/13.1-RELEASE-p1 botocore/1.21.61

### Environment details (OS name and version, etc.)

FreeBSD 13.1

**Comment by david-peters-aitch2o** [comment]
upgraded to:
aws-cli/1.27.16 Python/3.9.16 FreeBSD/13.1-RELEASE-p1 botocore/1.29.13 


will wait to see if it exits cleanly

**Comment by david-peters-aitch2o** [comment]
it has made no difference, after about 2 hours it's still sitting there with:
Completed 72.5 MiB/~72.5 MiB (986.2 KiB/s) with ~0 file(s) remaining (calculating...)

**Comment by aBurmeseDev** [comment]
Hi @david-peters-aitch2o - thanks for reaching out. Just wanted to clarify on the behavior where the files were moved successfully but the command doesn't exit itself?
