### ISSUE TITLE
get-login-password cannot reach endpoint URL

### ISSUE THREAD

**Issue by jjlin526** [aws/aws-cli#7621]
### Describe the bug

When running the command: `aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`, the following error occurs: `Connection was closed before we received a valid response from endpoint URL: "https://api.ecr.ca-central-1.amazonaws.com/". Error: Cannot perform an interactive login from a non TTY device`. 

### Expected Behavior

Successful authentication after ECR authorization token is passed to the docker login command. 

### Current Behavior

Failed authentication due to no response from URL.

### Reproduction Steps

Run the command `aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com` with AWS for the username and an Amazon ECR registry URI to authenticate to. 

### Possible Solution

Disable firewall

### CLI version used

2.9.16 

### Environment details (OS name and version, etc.)

Microsoft Windows 10 Enterprise; 10.0.19044

**Comment by aBurmeseDev** [comment]
Hi @jjlin526 - thanks for reaching out. 

From looking at the first part of the error `Connection was closed before we received a valid response from endpoint URL`, I think there might be some networking issue like VPN or firewall that's blocking the connection from reaching the endpoint. For the rest of the error `Error: Cannot perform an interactive login from a non TTY device`, there are a few possible causes and here are a couple potential solutions I found:
- https://stackoverflow.com/a/61854312
- https://stackoverflow.com/a/65581294

Please let us know if the issue persists after trying out those suggestions above.
Hope it helps,
John

**Comment by jjlin526** [comment]
Hello @aBurmeseDev. Thanks for the reply. I ran the `docker login` command recommended and I am getting this new error in the terminal: `Error saving credentials: error storing credentials - err: exit status 1, out: `reading response: invalid character '<' looking for beginning of value`. I am also getting a similar error in Docker: `Login failed. Invalid character '<' looking for beginning of value`. When running the command `aws configure list`, I am getting profile with value <not set>, type None and location None. Do you have a recommended solution to the failed login to Docker?

**Comment by aBurmeseDev** [comment]
@jjlin526 - thanks for sharing additional info. It looks like you could configure your profile when running `aws configure list` by adding your profile to the command like this `aws configure list --profile <profile>` and that will show you current configuration data including `Value`, `Type` and `Location`. Once that's done, run the follow get-login-password command with --profile parameter:

```
aws ecr get-login-password \
  --region <region> \
  --profile <profile> \
| docker login \
  --username AWS \
  --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
```
Please let us know how it goes!
