### ISSUE TITLE
Add help to the `--help` output

### ISSUE THREAD

**Issue by calebstewart** [aws/aws-cli#7629]
### Describe the feature

Include some form of help output with the `--help` option to commands. Currently, only a list of options is shown, which isn't very helpful. I know that the `help` subcommand exists which shows basically a man-page-like output, but it feels counter-intuitive to not include any information in the `--help` output, since basically every other command line tool provides this.

### Use Case

First of all, this is very much a preference thing, and I understand that. I understand that those who have used the AWS CLI for a while just know not to ever use `--help`, but given that it's incredibly common elsewhere to have at least summary information about what a command does in that output, it seems like a no-brainer to just include the information there.

The entire point of the larger development community settling on the `--help` argument was to make finding the help quick and easy regardless of the command, but with AWS CLI, newcomers have to run the command with `--help`, then find out it's actually a different command and run that instead. It just feels like a needless bump in the road for productivity, especially when `--help` is so ingrained in many peoples brains. I still type it out of habit even though I know right after I hit enter that I'm not going to get any useful information from the command.

### Proposed Solution

Either:
1. Provide the full identical help output in both the `help` subcommand and the `--help` option (my personal preference).
2. Provide a summary paragraph of the command in the `--help` argument so it's not completely useless.

### Other Information

There's probably differing opinions out there, so if I'm in the minority, then I understand. It just seems like an easy improvement to align with 90% of other CLI utilities and make knowledge more easily transferable for newcomers.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.8.0

### Environment details (OS name and version, etc.)

Python/3.9.11 Linux/6.1.6-arch1-1 exe/x86_64.arch prompt/off

**Comment by tim-finnigan** [comment]
Hi @calebstewart thanks for creating this feature request. I'll link the `help` command documentation here for reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command. 

It describes the distinctions in how the `help` command is use for `aws`, `aws <service>` and `aws <service> <command>`:

![image](https://user-images.githubusercontent.com/87778557/216409658-e4b7bf6b-f0cc-4855-8a92-365197328fdb.png)

It also notes that the help for each command is divided into six sections:
**Name, Synopsis, Description, Options, Examples, and Output.**

Did you have specific feedback as far as the overall structure of that documentation? I'm wondering if your request is to add/remove/change a help section. Some services/commands have better documentation and examples than others but those can be improved on a case-by-case basis.

**Comment by calebstewart** [comment]
Thanks for the links!

The issue is less-so about the content of the documentation provided by the `help` subcommand. That documentation is normally pretty good. This is more of a usage thing. The generally agreed upon standard is to show some help information in response to the `--help` argument. This is commonly a shorter summary of the command than a `man`-page would provide, but enough to understand what the command does and how to use it.

Currently, the `--help` argument to the `aws` command does almost nothing. It always runs in the context of the root command and doesn't even provide any summary information.
![image](https://user-images.githubusercontent.com/7529189/216416261-e32221a2-a739-434d-b658-b37b7e9b56f3.png)

This is not a breaking problem in any way, to be clear. The information is available in the help subcommand. My issue was essentially asking if we could also get summary and option information in the `--help` output. This hurts no one, and makes picking up the AWS CLI a lot easier for anyone familiar with CLI tools since `--help` options are the de-facto standard in getting help information for a command.

For me, when I went to learn to use the AWS CLI, I installed the command, then tried to run `aws --help`, and received no information whatsoever. Then I ran `man aws` and got  nothing either. Then I had to google, and found the help subcommand, and could finally start moving. Making the `--help` argument work like it does in every other CLI utility would remove the second two steps, and let people more naturally explore the tool.

**Comment by tim-finnigan** [comment]
Thanks @calebstewart for following up and expanding on this, I understand better what you're saying now. There is actually a (very old) issue regarding support for `-h/--help`: https://github.com/aws/aws-cli/issues/303. Given that the feature request has been open for almost a decade I don't see the team prioritizing changes to the help paradigm at this point. 

It would probably be helpful to at least include a message when using `-h/--help` such as 
>"These help parameters are not supported, please refer to this documentation for more information on the AWS CLI help command: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command"

Or instead maybe just somehow alias `-h/--help` to `help` if that is possible? I'm not sure of the best solution going forward but I definitely acknowledge that the scenario you're describing is a bad user experience, specifically:

```
caleb@stewie-ryzen ~ % aws sso login --help
usage: aws [-h] [--profile PROFILE] [--debug]

optional arguments:
  -h, --help         show this help message and exit
```

**Comment by tim-finnigan** [comment]
If you have any other suggestions related to this please let us know. We also recommend adding a 👍 to https://github.com/aws/aws-cli/issues/303 to show support and help the team better gauge demand. I think we should close this as a duplicate for the sake of consolidating issues. Also I just updated the title of https://github.com/aws/aws-cli/issues/303 to help others spot this issue if they want to 👍 or comment on it as well.

**Comment by calebstewart** [comment]
If we're drawing the line at "we can't show output specific to the command when `--help` is provided", then this could also work:

```sh
[caleb@stewie-ryzen ~]$ aws sso login --help

To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

For more information, please visit: 

  https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command
```

**Comment by tim-finnigan** [comment]
Good point, I think adding that hint would be a nice alternative as well. I'll mention in https://github.com/aws/aws-cli/issues/303 to refer to this issue for some of these ideas.
