### ISSUE TITLE
`aws sso login` cannot get sso related configurations from `source_profile` 

### ISSUE THREAD

**Issue by LockonS** [aws/aws-cli#7632]
### Describe the bug

This is the demo aws configuration.

```
[profile custom-role]
role_arn = arn:aws:iam::xxxxxx:role/user-roles/xxxxxxxx
region = eu-west-1
output = json
source_profile = base-account

[profile base-account]
sso_start_url = https://xxxxxxxxxxx.awsapps.com/start
sso_region = eu-west-1
sso_account_id = xxxxxxxxxxx
sso_role_name = xxxxxxxxxxx
region = eu-west-1
output = json
```

### Expected Behavior

While trying to do a sso login with profile `custom-role` , I assume aws-cli will read the configuration from `base-account` as it was referenced as `source_profile`.

### Current Behavior

But it gives errors now.

```shell
$ aws sso login --profile custom-profile
Missing the following required SSO configuration values: sso_start_url, sso_region. To make sure this profile is properly configured to use SSO, please run: aws configure sso
```

### Reproduction Steps

Step1. Create a combination with two profiles with this template (also mentioned in the descriptions abov).
Step2. Run command `aws sso login --profile custom-role`

```
[profile custom-role]
role_arn = arn:aws:iam::xxxxxx:role/user-roles/xxxxxxxx
region = eu-west-1
output = json
source_profile = base-account

[profile base-account]
sso_start_url = https://xxxxxxxxxxx.awsapps.com/start
sso_region = eu-west-1
sso_account_id = xxxxxxxxxxx
sso_role_name = xxxxxxxxxxx
region = eu-west-1
output = json
```

### Possible Solution

Is this a designed feature that `source_profile` was not meant to read all the configurations from the referenced profile? 
If so, please update the documentations with usage examples.

### CLI version used

aws-cli/2.9.12 Python/3.9.11 Darwin/22.3.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Ventura 13.2

**Comment by tim-finnigan** [comment]
Hi @LockonS thanks for reaching out. I found another issue related to this (https://github.com/aws/aws-cli/issues/3334), in which @kyleknap mentions that the `source_profile` will only pull credentials from the targeted profile. I think the documentation on `source_profile` still needs an update here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html — and it should also clarify that the SSO configuration is not sourced either.

**Comment by Almenon** [comment]
@jmo-staked The issue that tim said this was a duplicate of, #7496, was fixed back in version 2.10.2.

Personally, I ran into this error with boto3 1.21.32. We upgraded to 1.26.135 and it worked.

**Comment by boogi** [comment]
I just run into it and google took me to this issue. Although it's aws-cli related and I had issue with "terraform init", I will leave a note what worked for me, maybe it will help somebody. So, for me changing the ~/.aws/config file scheme resolved the issue.

Before change: awscli (e.g. "aws sso login" and then "aws s3 ls") worked; but "terraform init" was not working (as it uses aws plugin written in go, not awscli directly).
After change: both awscli commands and "terraform init" work.

Before:
```$ cat ~/.aws/config
[profile MyProfile]
sso_session = MySession
sso_account_id = 123456789
sso_role_name = MyRole
region = us-central-1
output = json
[sso-session MySession]
sso_start_url = https://123.awsapps.com/start
sso_region = us-central-1
sso_registration_scopes = sso:account:access```

After:
```[profile MyProfile]
sso_account_id = 123456789
sso_role_name = MyRole
region = us-central-1
output = json
sso_start_url = https://123.awsapps.com/start
sso_region = us-central-1
sso_registration_scopes = sso:account:access```

**Comment by dave-mitchell** [comment]
The solution @boogi provided worked for me, too.  Thanks!

**Comment by MartinLoeper** [comment]
I ran into this too. It is one of the reasons I still use [aws-vault](https://github.com/99designs/aws-vault) since it provides `include_profile` which does the expected job.

**Comment by eryknn** [comment]
Running into the same problem with a following setup, when trying to run `aws sso login` with profile B exported as AWS_PROFILE:
```
SSO Session <- profile A <- profile B
```

In:
```
aws-cli/2.18.9 Python/3.12.7 Darwin/23.4.0 source/arm64
```
This is still an issue (🥲) and should be **reopened**.


Workaround that's good enough, but still annoying to have to do is to do:
```
aws sso login --sso-session <whatever is the name of your predefined sso session>
```
