### ISSUE TITLE
aws ec2 import-image 

### ISSUE THREAD

**Issue by srg1177** [aws/aws-cli#7638]
### Describe the bug

In aws ec2 import-image command `--boot-mode` parameter is not supported.
But according to documentation it should be 

https://docs.aws.amazon.com/cli/latest/reference/ec2/import-image.html

### Expected Behavior

Set boot-mode to chosen one. 

- legacy-bios
- uefi

### Current Behavior

opption --boot-mode is  unknowen

### Reproduction Steps

aws ec2 import-image  --description my_image  --license-type byol --boot-mode legacy-bios

aws ec2 import-image  --description "my_image"  --license-type "byol" --boot-mode "legacy-bios"

### CLI version used

aws-cli/2.1.38 Python/3.8.8 MacOS

### Environment details (OS name and version, etc.)

MacOS Ventura 13.0.1

**Comment by srg1177** [comment]
Sorry for inconvenience, looks like updating the cli to newer version fixed the issue (aws-cli/2.9.20 Python/3.9.11)

**Comment by tim-finnigan** [comment]
Thanks @srg1177 for letting us know. I'll go ahead and close this issue but if anything else comes up please feel free to reach out.
