### ISSUE TITLE
How do you add list permissions on a S3 bucket?

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#764]
<img src=http://s.natalian.org/2014-05-04/list-permissions.png>

**Comment by JordonPhillips** [comment]
You need to use the [`aws s3api put-bucket-acl`](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-acl.html) command. In your particular case, you can use the canned acl `public-read`. So the full command will be:

`aws s3api put-bucket-acl --bucket bucket-name --acl public-read`
