### ISSUE TITLE
Documentation website UI is broken

### ISSUE THREAD

**Issue by BoscoDomingo** [aws/aws-cli#7642]
### Describe the issue

The AWS CLI docs' UI is broken:
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/46006784/216954213-9639ff9e-7970-44d5-9c92-6bb5effebed9.png">

For some reason a huge vertical gap separating the sidebar and the content appears after loading. I first noticed it about 2 weeks ago, and hoped someone else would notice or have a similar issue, but it seems not.

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/index.html

**Comment by tim-finnigan** [comment]
Hi @BoscoDomingo thanks for reaching out. I tried to reproduce the view in your screenshot but wasn't able to. I tried in Safari, Firefox, and Chrome but still wasn't able to see that gap, even when adjusting my zoom settings to be very far out. 

Could you share any more info to help with reproducing this, such as which browser/zoom settings you are using?

**Comment by BoscoDomingo** [comment]
Zoom's at 100%. Firefox v109.1. So far it happens only on Firefox (Chrome works just fine), and must be an extension, since when using Troubleshooting Mode (didn't know that even existed!) it displays it correctly. Let me find which one may be causing issues and I'll get back to you
