### ISSUE TITLE
"aws configure sso" fails unhelpfully with invalid SSO session names

### ISSUE THREAD

**Issue by gbenson** [aws/aws-cli#7643]
### Describe the bug

`aws configure sso` fails with a cryptic error message if an invalid SSO session name is supplied.

### Expected Behavior

It'd be nice to have an informative error message:
<pre>$ <strong>aws configure sso</strong>
SSO session name (Recommended): AWS on Chromebook

Error: "AWS on Chromebook" is not a valid session name (try "aws-on-chromebook" instead?)</pre>

### Current Behavior

<pre>$ <strong>aws configure sso</strong>
SSO session name (Recommended): AWS on Chromebook
SSO start URL [None]: https://<em>whatever</em>.awsapps.com/start
SSO region [None]: us-east-1
SSO registration scopes [sso:account:access]:

An error occurred (InvalidClientMetadataException) when calling the RegisterClient operation:</pre>
There's nothing more, the command terminates there. Possibly a traceback got eaten somewhere?

### Reproduction Steps

Run `aws configure sso` and give it an SSO session name with whitespace in it.

### CLI version used

aws-cli/2.9.21

### Environment details (OS name and version, etc.)

Python/3.9.11 Linux/5.10.153-20434-g98da1eb2cf9d exe/x86_64.debian.11 prompt/off

**Comment by tim-finnigan** [comment]
Thanks @gbenson for reporting this issue, I could reproduce the behavior you described. It looks like a client-side validator could be added here to ensure that the SSO Session Name doesn't contain spaces: https://github.com/aws/aws-cli/blob/dc53215d2b2eae803907dbd19e22836ec2c26d38/awscli/customizations/configure/sso.py#L209-L228

**Comment by tim-finnigan** [comment]
Upon revisiting this and testing again, it appears that the issue has since been fixed. Please [update](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to a recent version (2.18.16 is the latest per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1)) and let us know if you're still seeing any issues.
