### ISSUE TITLE
Totally inconsistent behaviour on regional endpoints with aws-cli

### ISSUE THREAD

**Issue by gtmtech** [aws/aws-cli#7644]
### Describe the bug

Some services adapt their endpoints when specifying `--region`, and some dont. See for example ec2 vs sts:

```
$ aws --debug ec2 --region eu-west-1 describe-vpcs 2>&1 | grep host:
host:ec2.eu-west-1.amazonaws.com

$ aws --debug sts --region eu-west-1 get-caller-identity 2>&1 | grep host:
host:sts.amazonaws.com
```

### Expected Behavior

I would expect some consistency

### Current Behavior

See above for current behaviour

### Reproduction Steps

See commands above

### Additional Information/Context

The problem is that the docs talk about using sts regional endpoints to get v2 sts tokens, and most people I work with are used to getting regional endpoints using --region on a service. This doesn't work for sts. 

With the sts service you have to use --endpoint-url instead to force it to a regional endpoint. 

This is inconsistent behaviour as for other services you use --region to specify an endpoint. 

This means that to get a v2 sts token, you have to take the following special measures:

```
aws sts --region eu-west-1 --endpoint-url https://sts.eu-west-1.amazonaws.com assume-role --options...
```

This is necessary to work with an opt-in region.

This is not well documented, and in fact --endpoint-url is more traditionally documented as a means to run against a mock aws framework such as localstack rather than a real means of trying to execute specific aws functionality. 

### CLI version used

All of them up to 2.9.21

### Environment details (OS name and version, etc.)

Mac OSX Ventura

**Comment by tim-finnigan** [comment]
Hi @gtmtech thanks for reaching out. Here is the AWS SDKs and Tools documentation on AWS STS regionalized endpoints: https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html. It notes there that the default value is `regional` for the AWS CLI v2. 

When I test that command `aws --debug sts --region eu-west-1 get-caller-identity 2>&1 | grep host:` on v2.9.18 I get `host:sts.eu-west-1.amazonaws.com`. Can you confirm which version you're using and check what configurations you have set? 

For documentation feedback we generally recommend using the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Docs%20SDK%20Reference&topic_url=http://docs.aws.amazon.com/en_us/sdkref/latest/guide/feature-sts-regionalized-endpoints.html) links at the bottom of documentation pages like the one linked above. That helps by directly routing the feedback to the appropriate teams.

**Comment by gtmtech** [comment]
Many thanks @tim-finnigan 

I can see that aws v1 and v2 produce different results as you say

```
$ aws --version
aws-cli/1.22.72 Python/3.9.16 Darwin/22.3.0 botocore/1.24.17
$ aws --debug sts --region eu-west-1 get-caller-identity 2>&1 | grep host:
host:sts.amazonaws.com
$ /usr/local/bin/aws --version
aws-cli/2.9.21 Python/3.9.11 Darwin/22.3.0 exe/x86_64 prompt/off
$ /usr/local/bin/aws --debug sts --region eu-west-1 get-caller-identity 2>&1 | grep host:
host:sts.eu-west-1.amazonaws.com
```
