### ISSUE TITLE
get-open-id-token allowed on identities from pools with no `AllowClassicFlow` value

### ISSUE THREAD

**Issue by jrdavenport** [aws/aws-cli#7652]
### Describe the bug

It is possible to create identity-pools with no `AllowClassicFlow` value as the `[--allow-classic-flow | --no-allow-classic-flow]` flags are optional for `create-identity-pool`.

if an identity's parent pool has `AllowClassicFlow = false`, `get-open-id-token` will return the below error as expected:
```
An error occurred (InvalidParameterException) when calling the GetOpenIdToken operation: Basic (classic) flow is not enabled, please use enhanced flow.
```

However if a pool is created without an explicit `AllowClassicFlow` value, `get-open-id-token` will allow the operation and return a token.

### Expected Behavior

`get-open-id-token` should not allow a token to be generated if an explicit `AllowClassicFlow = true` is not configured on the parent pool.

### Current Behavior

`get-open-id-token` allows a token to be generated if no explicit `AllowClassicFlow` value is configured on the parent pool. 

### Reproduction Steps

behaviour with no explicit `AllowClassicFlow` value:
```
aws cognito-identity create-identity-pool --identity-pool-name TestPool1 --allow-unauthenticated-identities 

{
    "IdentityPoolId": "eu-west-1:redacted-pool-id",
    "IdentityPoolName": "TestPool1",
    "AllowUnauthenticatedIdentities": true,
    "IdentityPoolTags": {}
}


aws cognito-identity get-id --identity-pool-id eu-west-1:redacted-pool-id 

{
    "IdentityId": "eu-west-1:redacted-identity-id"
}

aws cognito-identity get-open-id-token --identity-id eu-west-1:redacted-identity-id 

{
    "IdentityId": "eu-west-1:redacted-identity-id",
    "Token": "redacted-token"
}
```

Comparison of behaviour with an explicit false:
```

aws cognito-identity create-identity-pool --identity-pool-name TestPool2 --allow-unauthenticated-identities --no-allow-classic-flow 

{
    "IdentityPoolId": "eu-west-1:redacted-pool-id",
    "IdentityPoolName": "TestPool2",
    "AllowUnauthenticatedIdentities": true,
    "AllowClassicFlow": false,
    "IdentityPoolTags": {}
}

aws cognito-identity get-id --identity-pool-id eu-west-1:redacted-pool-id 

{
    "IdentityId": "eu-west-1:redacted-identity-id"
}

aws cognito-identity get-open-id-token --identity-id eu-west-1:redacted-identity-id

```
An error occurred (InvalidParameterException) when calling the GetOpenIdToken operation: Basic (classic) flow is not enabled, please use enhanced flow.
```
```

### Possible Solution

Only allow a token to be returned if an explicit `AllowClassicFlow = true` is configured on the parent pool.

### CLI version used

aws-cli/2.7.4 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Mac OS, Montery

**Comment by aBurmeseDev** [comment]
Hi @jrdavenport - thanks for reaching out. I wasn't able to reproduce the same behavior. Could you share your debug logs from both commands by adding `--debug` to them? That would give us more insight into it.

**Comment by aBurmeseDev** [comment]
Sorry for the long silence here. The expected behavior should be that, if the `AllowClassicFlow` value is not explicitly set during the `create-identity-pool` operation, the classic flow should be disabled by default, and the `get-open-id-token` operation should return an error similar to when `AllowClassicFlow` is explicitly set to `false`.

When creating new Cognito Identity pools, can you try setting the `--allow-classic-flow` or `--no-allow-classic-flow` flag to ensure that the behavior is predictable and consistent with your requirements?
