### ISSUE TITLE
aws-cli 2.9.19 snap does not open browser when running sso login

### ISSUE THREAD

**Issue by rafaltrojniak** [aws/aws-cli#7666]
### Describe the bug

When running `aws sso login`, I would expect the web browser to open automatically and present confirmation page. Instead of that, web browser does not open, and I have to open it manually.

### Expected Behavior

Web browser to open and direct to confirmation/verification page of SSO process

### Current Behavior

Web page does not open, and given message is presented:
```
$ aws sso login
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

XXXX-XXX
```

Additionally following error is logged bu auditd
```
lut 13 10:50:58 hostname kernel: audit: type=1400 audit(1676281858.876:4529): apparmor=\"DENIED\" operation=\"exec\" profile=\"snap.aws-cli.aws\" name=\"/usr/bin/xdg-open\" pid=1549889 comm=\"python\" requested_mask=\"x\" denied_mask=\"x\" fsuid=1000 ouid=0
```

### Reproduction Steps

Install aws-cli from snap
```
sudo snap install aws-cli --channel=v2/beta
```

Configure your `sso_start_url` and  `sso_region`
```
$ aws configure set sso_start_url https://XXXXXX/
$ aws configure set sso_region eu-west-1
```

Run the `aws sso login`

### Possible Solution

Add `desktop` plug into the snap configuration, just like done here 
https://github.com/nysasounds/amz-aws-cli/commit/0bf2243bdac80aec3c2a38a8c426f5839b6ad23c

### CLI version used

aws-cli 2.9.19 snap (178)

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by tim-finnigan** [comment]
Hi @rafaltrojniak thanks for reporting this. There is some ongoing work on the AWS CLI Snap package which is being tracked here: https://github.com/aws/aws-cli/issues/6010. As mentioned in [this comment](https://github.com/aws/aws-cli/issues/6010#issuecomment-1430146361) from earlier today, the team is investigating issues caused by strict confinement, but for now we can continue tracking this issue here.

**Comment by tim-finnigan** [comment]
Checking in, the AWS CLI version on Snapcraft is now up to date (https://snapcraft.io/aws-cli). Is this still an issue in the latest version?
