### ISSUE TITLE
If you use fargate type ecs and set the service name to ssh, it will not appear in the task.

### ISSUE THREAD

**Issue by takuya-ogasawara** [aws/aws-cli#7669]
### Describe the bug

```
resource "aws_ecs_service" "service_01" {
  name                   = "ssh"
  ~~~
}
```
To try ssm by ecs fargate, I casually set the ecs service name to "ssh".

After that, the task no longer appears in the aws console, but terraform has been successfully applied and the status in the ecs console is also displayed normally.

### Expected Behavior

![image](https://user-images.githubusercontent.com/75306059/218947529-49988a13-d2be-477b-8a20-9f8fee574e08.png)
I only expect that the tasks I create will be displayed like any other ecs task.

### Current Behavior

There were no specific error logs, and checks were made with aws cli to isolate the front end and other issues.
The cluster name and id are masked, just in case.

At this time, there was one container for each service in 3services. Below is the list task at that time.
```
aws ecs list-tasks --cluster xxx
{
    "taskArns": [
        "arn:aws:ecs:ap-northeast-1:xxx:task/xxx/1b806176600b4560a709bb787dd05e87",
        "arn:aws:ecs:ap-northeast-1:xxx:task/xxx/5f87bd76f23449c0bf975c723e04cf95",
        "arn:aws:ecs:ap-northeast-1:xxx:task/xxx/653f338a8bbc4d39af67e3610e8ac769"
    ]
}
```

Surprisingly, containers seem to exist in cli. Next, I specified the service name and checked the task.
```
aws ecs list-tasks --cluster reg-ecs-01-staging --service-name=ssh
{
    "taskArns": []
}
 aws ecs list-tasks --cluster reg-ecs-01-staging --service-name=cron
{
    "taskArns": [
        "arn:aws:ecs:ap-northeast-1:xxx:task/xxx/5f87bd76f23449c0bf975c723e04cf95"
    ]
}
aws ecs list-tasks --cluster reg-ecs-01-staging --service-name=backend-api
{
    "taskArns": [
        "arn:aws:ecs:ap-northeast-1:xxx:task/xxx/653f338a8bbc4d39af67e3610e8ac769"
    ]
}
```
Then only ssh did not appear.

### Reproduction Steps

```
resource "aws_ecs_service" "service_03" {
  name                   = "ssh"
  cluster                = aws_ecs_cluster.ecs_01.id
  task_definition        = aws_ecs_task_definition.task_definition_03.arn
  desired_count          = 1
  enable_execute_command = true
  #iam_role = AWSServiceRoleForECS
  launch_type = "FARGATE"

  deployment_controller {
    type = "ECS"
  }

  network_configuration {
    subnets          = [module.network_01.private_subnet_01_id, module.network_01.private_subnet_02_id]
    security_groups  = [module.backend_sg_01.sg_id]
    assign_public_ip = false
  }

  platform_version = "1.4.0"
}
```
Here is the terraform code that created the service showing the strange behavior.
Task definitions and other information can be provided if needed.

### Additional Information/Context

I know this is not very relevant, but I have already deployed two other services to the cluster where I deployed the "ssh" service.

### CLI version used

 aws --version aws-cli/2.9.9 Python/3.9.11 Linux/5.10.102.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

WSL/ubuntu 22.04

**Comment by takuya-ogasawara** [comment]
About 10 minutes later, I updated the revision and did the same thing, and the problem was resolved. Maybe the problem was not with cli but with the endpoint providing the information.

**Comment by aBurmeseDev** [comment]
Hi @takuya-ogasawara - thanks for reaching out. 

I'm glad to hear that the issue was resolved with revision update. Please let us know if there's anything else we could help with before closing the issue and feel free to reach out anytime.

**Comment by takuya-ogasawara** [comment]
@aBurmeseDev 
Thank you for your response. It has been working fine since then, so I'll assume it's just a temporary issue and I'll fix the problem myself!

I use aws cli all the time. Thank you very much.
