### ISSUE TITLE
 Unable to connect to EKS cluster with kubectl

### ISSUE THREAD

**Issue by WissemChb** [aws/aws-cli#7672]
### Describe the bug

I faced an issue when trying to connect to the EKS cluster from my MacOS Ventura. The kubectl stay blocked without any output for a long time.  And after that I have this error showed:

```
E0216 15:29:54.595445   57075 memcache.go:238] couldn't get current server API group list: Get "https://XXXXXXXXXXXXXXXXXXXXXXX.eks.amazonaws.com/api?timeout=32s": getting credentials: decoding stdout: yaml: did not find expected comment or line break (Client.Timeout exceeded while awaiting headers)

E0216 15:29:55.660773   57075 memcache.go:238] couldn't get current server API group list: Get "https://XXXXXXXXXXXXXXXXXXXXXX.eks.amazonaws.com/api?timeout=32s": getting credentials: decoding stdout: yaml: did not find expected comment or line break
```

But when I run the command from docker container, It works fine

### Expected Behavior

Able to connect and show the k8s objects

### Current Behavior

 The kubectl stay blocked without any output for a long time.  And after that I have this error showed:

```
E0216 15:29:54.595445   57075 memcache.go:238] couldn't get current server API group list: Get "https://XXXXXXXXXXXXXXXXXXXXXXX.eks.amazonaws.com/api?timeout=32s": getting credentials: decoding stdout: yaml: did not find expected comment or line break (Client.Timeout exceeded while awaiting headers)

E0216 15:29:55.660773   57075 memcache.go:238] couldn't get current server API group list: Get "https://XXXXXXXXXXXXXXXXXXXXXX.eks.amazonaws.com/api?timeout=32s": getting credentials: decoding stdout: yaml: did not find expected comment or line break
```

### Reproduction Steps

1.  Connect to AWS
2.  Get the kubeconfig with 
```
aws eks update-kubeconfig --name <cluster-name> --role-arn <role> --profile=<profile>
```
3. trying to get k8s objects with kubectl.

### Possible Solution

N/A

### Additional Information/Context

kubectl version: 
```
k version --client
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```

### CLI version used

aws-cli/2.10.0 Python/3.9.11 Darwin/22.3.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Macos M1 Ventura 13.2.1

**Comment by aBurmeseDev** [comment]
Hi @WissemChb - thanks for reaching out. I wasn't able to reproduce this behavior on my end and from researching the error, it could be network issue where you might have something like a VPN that's blocking the connection. In order for us to investigate further, would you be able to provide full debug logs by appending `--debug` to CLI command?

Best,
John
