### ISSUE TITLE
RPM Doesn't Have All Required packages in Requirements

### ISSUE THREAD

**Issue by scoleri** [aws/aws-cli#7675]
### Describe the bug

No less required in awscli-2 RPM - but required to run.

### Expected Behavior

```
console: docker run -it amazonlinux:2022
bash-5.2# yum install -yq awscli

Installed:
  aws-c-auth-libs-0.6.5-6.amzn2022.0.2.aarch64       aws-c-cal-libs-0.5.12-7.amzn2022.0.2.aarch64         aws-c-common-libs-0.6.14-6.amzn2022.0.2.aarch64         aws-c-compression-libs-0.2.14-5.amzn2022.0.2.aarch64   aws-c-event-stream-libs-0.2.7-5.amzn2022.0.2.aarch64
  aws-c-http-libs-0.6.8-6.amzn2022.0.2.aarch64       aws-c-io-libs-0.10.12-5.amzn2022.0.7.aarch64         aws-c-mqtt-libs-0.7.8-7.amzn2022.0.2.aarch64            aws-c-s3-libs-0.1.27-5.amzn2022.0.3.aarch64            aws-c-sdkutils-libs-0.1.1-5.amzn2022.0.2.aarch64
  aws-checksums-libs-0.1.12-5.amzn2022.0.2.aarch64   awscli-2-2.7.8-1.amzn2022.0.4.noarch                 openssl-1:3.0.5-1.amzn2022.0.3.aarch64                  python3-awscrt-0.12.6-3.amzn2022.0.3.aarch64           python3-cffi-1.14.5-1.amzn2022.0.1.aarch64
  python3-colorama-0.4.4-2.amzn2022.0.1.noarch       python3-cryptography-36.0.1-1.amzn2022.0.2.aarch64   python3-dateutil-1:2.8.1-3.amzn2022.0.1.noarch          python3-distro-1.5.0-5.amzn2022.0.1.noarch             python3-docutils-0.16-4.amzn2022.0.1.noarch
  python3-idna-2.10-3.amzn2022.0.1.noarch            python3-jmespath-0.10.0-1.amzn2022.0.1.noarch        python3-ply-3.11-11.amzn2022.0.1.noarch                 python3-prompt-toolkit-3.0.24-1.amzn2022.0.1.noarch    python3-pycparser-2.20-3.amzn2022.0.1.noarch
  python3-pysocks-1.7.1-8.amzn2022.0.1.noarch        python3-ruamel-yaml-0.16.6-5.amzn2022.0.1.aarch64    python3-ruamel-yaml-clib-0.1.2-6.amzn2022.0.1.aarch64   python3-setuptools-59.6.0-2.amzn2022.0.2.noarch        python3-six-1.15.0-5.amzn2022.0.1.noarch
  python3-urllib3-1.25.10-5.amzn2022.0.1.noarch      python3-wcwidth-0.2.5-3.amzn2022.0.1.noarch          s2n-tls-1.3.24-1.amzn2022.0.2.aarch64                   s2n-tls-libs-1.3.24-1.amzn2022.0.2.aarch64

bash-5.2# aws sts get-caller-identity
{
    "UserId": "XXXXXXXXXXXXX:i-XXXXXXXXXXXX",
    "Account": "XXXXXXXXXXXX",
    "Arn": "arn:aws:sts::XXXXXXX:assumed-role/role/i-XXXXXXXXXXXX"
}
```

### Current Behavior

```
console: docker run -it amazonlinux:2022
bash-5.2# yum install -yq awscli

Installed:
  aws-c-auth-libs-0.6.5-6.amzn2022.0.2.aarch64       aws-c-cal-libs-0.5.12-7.amzn2022.0.2.aarch64         aws-c-common-libs-0.6.14-6.amzn2022.0.2.aarch64         aws-c-compression-libs-0.2.14-5.amzn2022.0.2.aarch64   aws-c-event-stream-libs-0.2.7-5.amzn2022.0.2.aarch64
  aws-c-http-libs-0.6.8-6.amzn2022.0.2.aarch64       aws-c-io-libs-0.10.12-5.amzn2022.0.7.aarch64         aws-c-mqtt-libs-0.7.8-7.amzn2022.0.2.aarch64            aws-c-s3-libs-0.1.27-5.amzn2022.0.3.aarch64            aws-c-sdkutils-libs-0.1.1-5.amzn2022.0.2.aarch64
  aws-checksums-libs-0.1.12-5.amzn2022.0.2.aarch64   awscli-2-2.7.8-1.amzn2022.0.4.noarch                 openssl-1:3.0.5-1.amzn2022.0.3.aarch64                  python3-awscrt-0.12.6-3.amzn2022.0.3.aarch64           python3-cffi-1.14.5-1.amzn2022.0.1.aarch64
  python3-colorama-0.4.4-2.amzn2022.0.1.noarch       python3-cryptography-36.0.1-1.amzn2022.0.2.aarch64   python3-dateutil-1:2.8.1-3.amzn2022.0.1.noarch          python3-distro-1.5.0-5.amzn2022.0.1.noarch             python3-docutils-0.16-4.amzn2022.0.1.noarch
  python3-idna-2.10-3.amzn2022.0.1.noarch            python3-jmespath-0.10.0-1.amzn2022.0.1.noarch        python3-ply-3.11-11.amzn2022.0.1.noarch                 python3-prompt-toolkit-3.0.24-1.amzn2022.0.1.noarch    python3-pycparser-2.20-3.amzn2022.0.1.noarch
  python3-pysocks-1.7.1-8.amzn2022.0.1.noarch        python3-ruamel-yaml-0.16.6-5.amzn2022.0.1.aarch64    python3-ruamel-yaml-clib-0.1.2-6.amzn2022.0.1.aarch64   python3-setuptools-59.6.0-2.amzn2022.0.2.noarch        python3-six-1.15.0-5.amzn2022.0.1.noarch
  python3-urllib3-1.25.10-5.amzn2022.0.1.noarch      python3-wcwidth-0.2.5-3.amzn2022.0.1.noarch          s2n-tls-1.3.24-1.amzn2022.0.2.aarch64                   s2n-tls-libs-1.3.24-1.amzn2022.0.2.aarch64
bash-5.2# aws sts get-caller-identity

Unable to redirect output to pager. Received the following error when opening pager:
[Errno 2] No such file or directory: 'less'

Learn more about configuring the output pager by running "aws help config-vars".
```

### Reproduction Steps

See above

### Possible Solution

Require less in the awscli-2 RPM

### Additional Information/Context

```
bash-5.2# aws --version
aws-cli/2.7.8 Python/3.9.16 Linux/4.14.231-173.361.amzn2.aarch64 source/aarch64.amzn.2022 prompt/off
```

### CLI version used

aws-cli/2.7.8 Python/3.9.16 Linux/4.14.231-173.361.amzn2.aarch64 source/aarch64.amzn.2022 prompt/off

### Environment details (OS name and version, etc.)

amazonlinux:2022

**Comment by aBurmeseDev** [comment]
Hi @scoleri - thanks for reaching out. We only support the virtualenv, pip or bundled [installation](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) for AWS CLI and don't have control over the rpm for awscli within Amazon Linux. 

However, I investigated the error you're seeing and stumbled upon this stackOverflow [post](https://stackoverflow.com/questions/57953187/aws-cli-has-no-output). I'd recommend trying out those suggestions mentioned in the post.

If you need further assistance, I would suggest contacting AWS Support for additional follow up. 

Hope that helps,
John

**Comment by lorengordon** [comment]
@aBurmeseDev What is the suggested method of interacting with whoever packages the aws-cli RPM to report issues? I know I've had that problem with other AWS tools (SSM Agent in particular), and opened an issue on their GitHub repo to report it. Other AWS teams have been supportive and helped track the fix, even though they also acknowledge they do not directly support the RPM.

**Comment by scoleri** [comment]
Yes exactly.  They just need less packages added as a requirement for the cli pager.On Feb 21, 2023, at 10:35, Loren Gordon ***@***.***> wrote:﻿
@aBurmeseDev What is the suggested method of interacting with whoever packages the aws-cli RPM to report issues? I know I've had that problem with other AWS tools (SSM Agent in particular), and opened an issue on their GitHub repo to report it. Other AWS teams have been supportive and helped track the fix, even though they also acknowledge they do not directly support the RPM.

**Comment by scoleri** [comment]
Which team builds the binary RPM for Amazon Linux?  Yah I installed less - no issues.  If the cli rpm requires less out of the gate it should just have it as a requirement in the SPEC.On Feb 21, 2023, at 11:40, John L. ***@***.***> wrote:﻿
@lorengordon - thanks for your question. Regarding RPM related issues with awscli, we recommend reaching out to amazonlinux/amazon-linux-2022.
Just to clarify with the error @scoleri seeing, you'd probably need to install less or set (PAGER or AWS_PAGER) to the empty string to disable this and those are some of the suggestions from the stackoverflow post I shared above.
Here's similar post I found for more context on it: #4940
I hope you understand that sometimes all we could do is to point you to the right direction or find workaround solutions for the things that our team doesn't have control over.
Best,
John

**Comment by lorengordon** [comment]
@aBurmeseDev AL2022 is still only in preview, it is not GA. We had a number of issues trying to use it as a sufficiently close replacement for RHEL and its derivatives. Is it the same team for the Amazon Linux 2 repositories, as for the Amazon Linux 2022 repositories? Or would we need to open and track issues in multiple places?

**Comment by aBurmeseDev** [comment]
Hi @scoleri @lorengordon - I reached out to Amazon Linux team internally to address your questions and will share updates here once I hear back from them. Thanks again.
`P82138404`

**Comment by aBurmeseDev** [comment]
Hello @scoleri @lorengordon - thanks for your patience. I just heard back from Amazon Linux team that this is on their radar to take a look although we can't give definite timeline at this moment. If less is indeed a required dependency, they will consider adding it. 

As mentioned in my [previous response](https://github.com/aws/aws-cli/issues/7675#issuecomment-1438935655), you could also set `PAGER` or `AWS_PAGER` to empty string as another workaround as well.

I'm going to close this in favor of existing issue https://github.com/aws/aws-cli/issues/4940 and feel free to check in for updates there.

Thanks again,
John
