### ISSUE TITLE
AWS cli: servicecatalog update-provisioned-product "UsePreviousValue": true -> doesn't take previous values.

### ISSUE THREAD

**Issue by sree7k7** [aws/aws-cli#7693]
### Describe the issue

Hi,

While doing an update for an existing provisioned product in AWS service catalog, the **_"UsePreviousValue": true_** api call doesn't work as expected.

**Product:** AWS Control Tower Account Factory or any

**Output:**
Values are updating with given (new) values.

example command shown below:

`aws servicecatalog update-provisioned-product \
--provisioning-parameters '[
        {"Key": "AccountEmail", "Value": "username@example.com", "UsePreviousValue": true},
        {"Key": "AccountName", "Value": "AccName", "UsePreviousValue": true},
        {"Key": "SSOUserFirstName", "Value": "Any", "UsePreviousValue": true},
        {"Key": "SSOUserLastName", "Value": "Any", "UsePreviousValue": true},
        {"Key": "ManagedOrganizationalUnit", "Value": "OuName", "UsePreviousValue": true},
        {"Key": "SSOUserEmail", "Value": "UserEmail", "UsePreviousValue": true}
    ]' \
--provisioned-product-name provisionedProductName \
--path-name "AWS Control Tower Account Factory Portfolio"`

Best,
Sri

### Links

https://docs.aws.amazon.com/cli/latest/reference/servicecatalog/update-provisioned-product.html

**Comment by tim-finnigan** [comment]
Hi @sree7k7 thanks for reaching out. I think we need more information on how this command doesn't work as you expected. Can you elaborate a bit more on what you are trying to do and what the issue is?

If you could provide your debug logs (with any sensitive info redacted) by adding `--debug` to the command then this may also help us see what the problem is.

**Comment by sree7k7** [comment]
Hi Tim

I am trying to update the AWS ServiceCatalog provisioned product i,e AWS account.

for example:  
Product: AWS Control Tower Account Factory
Provisioned products: Accounts

I am using Cli:
Here, I am updating the OU (moving account from one OU to another). I want to keep the **previous values** as it is.

Previous values:
- SSOUserEmail
- AccountEmail

I want to keep these values to previous state, even though I mention the new values. Please see this [doc](https://docs.aws.amazon.com/cli/latest/reference/servicecatalog/update-provisioned-product.html): 
 check the option: _**--provisioning-parameters**_

Hope this helps!

Best,
Sri

**Comment by tim-finnigan** [comment]
Thanks for following up. Do you receive an error when running the command? If you can provide your debug logs (`--debug`) that would help assist with further investigation.
