### ISSUE TITLE
IoT register-ca-certificate registration-config shorthand syntax not working

### ISSUE THREAD

**Issue by riaan-dau** [aws/aws-cli#7694]
### Describe the bug

When registering a CA certificate with a previously created provisioning template, the [documentation](https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html) states that you can use the `--registration-config` parameter with a shorthand syntax to use a `templateName` key for the template to use. The shorthand syntax does not seem to work in this case

### Expected Behavior

When running:

```
aws iot create-provisioning-template \
    --template-name DemoProvTemplate \
    --template-body file://prov-body.json --type JITP \
    --provisioning-role-arn arn:aws:iam::918712141384:role/JITPRole \
    --enabled
```

And then:

```
aws iot register-ca-certificate --ca-certificate file://rootCA/rootCA.pem \
--verification-certificate file://verification/verification_cert.pem \
--set-as-active --allow-auto-registration \
—-registration-config templateName=DemoProvTemplate
```

I expect the CA to be created and the provisioning template to be attached to it.

### Current Behavior

When running the `register-ca-certificate` command, I get the following output:

`Unknown options: templateName=DemoProvTemplate, —-registration-config`

With `--debug`:

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 460, in main
    return command_table[parsed_args.command](remaining, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 595, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/awscli/2.10.1/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 764, in __call__
    raise UnknownArgumentError(
awscli.arguments.UnknownArgumentError: Unknown options: templateName=DemoProvTemplate, —-registration-config
```

### Reproduction Steps

Create a verification certificate, and a root CA certificate that you want to register and run this:

```
aws iot register-ca-certificate --ca-certificate file://rootCA/rootCA.pem \
--verification-certificate file://verification/verification_cert.pem \
--set-as-active --allow-auto-registration \
—-registration-config templateName=DemoProvTemplate
```

### CLI version used

aws-cli/2.10.1

### Environment details (OS name and version, etc.)

Python/3.11.2 Darwin/22.2.0 source/arm64 prompt/off MacOS Ventura 13.1

**Comment by aBurmeseDev** [comment]
Hi @riaan-dau - thanks for reaching out. I wasn't able to reproduce it on my end, though I can see the same error when I copied your command and pasted it in my terminal. It seems like you have dash typo in your `—-registration-config`.
Could you copy/paste the command below in your terminal and confirm if it works?
```
aws iot register-ca-certificate --ca-certificate file://rootCA/rootCA.pem \
--verification-certificate file://verification/verification_cert.pem \
--set-as-active --allow-auto-registration \
--registration-config templateName=DemoProvTemplate
```
Best,
John

**Comment by riaan-dau** [comment]
Wow, that is embarrassing! It works, thanks!
