### ISSUE TITLE
Tab Completion issue when redirecting to a file

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#77]
Though #66 is fixed, it looks like now instead of a traceback, I get undesired behavior.  Running:

```
$ aws ec2 describe-instances > /tmp/[TAB]
```

I get this:

```
$ aws ec2 describe-instances > --
```

Hitting tab a second time I get:

```
$ aws ec2 describe-instances > --[TAB]
--color          --debug          --endpoint-url   --filters        --instance-ids   --no-verify-ssl  --output         --profile        --region         --version
```

The expected behavior would be to complete the contents of the `/tmp/` directory.

**Comment by jamesls** [comment]
Closing old issue.  We now no longer get the unexpected behavior of showing the top level arguments.

**Comment by qa-prog** [comment]
👋 This issue has been inactive for 30 days. Please update or it will be closed automatically.
