### ISSUE TITLE
Please provide a version permalink for the download

### ISSUE THREAD

**Issue by rdbisme** [aws/aws-cli#7703]
### Describe the bug

Hello, I wanted to add awscliv2 to scoop, but currently making it work with hash checking and everything is kinda difficult because there's no version permalink, therefore the hash gets stale as soon as you update the CLI. 

Would it be possible to provide versioning schemes on the URL such that I can create the manifest and implement auto-update? I'd love to avoid building the package using python.

### Expected Behavior

Having access to an url of the time `https://awscli.amazonaws/<version>/AWSCLIv2.msi` or `https://awscli.amazonaws/AWSCLIv<version>.msi

### Current Behavior

Currently, there seems no way of retrieving a specific version from the provided URL

### Reproduction Steps

-

### CLI version used

aws-cli/2.10.2 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 10

**Comment by lorengordon** [comment]
Believe it or not, they do provide versioned urls... It's just not documented _anywhere_ I can find, except an old issue here on GitHub, https://github.com/aws/aws-cli/issues/1921.

Examples for v2.10.2:

* Windows: `https://awscli.amazonaws.com/AWSCLIV2-2.10.2.msi`
* Linux: `https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.10.2.zip`

**Comment by tim-finnigan** [comment]
Hello, thanks for reaching out. Please refer to this documentation for installing past releases of the AWS CLI on Linux, macOS and Windows: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html

**Comment by rdbisme** [comment]
Indeed. Thanks to both.
