### ISSUE TITLE
AWS CLI gives UnauthorizedOperation when running inside a docker container whose host ec2 instance has IAM role to fetch read details of ec2 services.

### ISSUE THREAD

**Issue by TheSwarnim** [aws/aws-cli#7709]
### Describe the bug

I'm working on a project where I've to use AWS cli inside a docker container. The images used for the test are enkins/jenkins:lts-jdk11 and amazon/aws-cli: latest. 
The ec2 host instance has attached with the default EC2ReadPolicy Role attached which allows to describe all ec2 services without adding any secret key and access key inside ec2 instance. The cli is working fine in host instance but when I wanted to do same inside the docker container installed in this ec2 instance, the cli failed to run and gives this error `An error occurred (UnauthorizedOperation) when calling the DescribeInstances operation: You are not authorized to perform this operation.` 
In my case, I've to use the Jenkins container to do my work without adding secret and access keys.  But in order to verify my issue, I've used the official aws-cli docker image to run on the same ec2 instance and it gives the same error.  
I'm not sure is something I'm missing here to follow the best practices but I think this can happen with others in the future as well. I've tried to find my answer on StackOverflow and chatgpt but no one could solve my query.

Also wanted to mention that the curl command
` curl http://169.254.169.254/latest/meta-data/iam/security-credentials/<role_name>` is working fine and is giving me success response inside the container as well like this
```
{
  "Code" : "Success",
  "LastUpdated" : "2023-02-26T06:06:25Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "zzz",
  "SecretAccessKey" : "yyy",
  "Token" : "xxxxx",
  "Expiration" : "2023-02-26T12:22:11Z"
}
```

The IAM policy is
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:Describe*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "cloudwatch:ListMetrics",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:Describe*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "autoscaling:Describe*",
            "Resource": "*"
        }
    ]
}
```

### Expected Behavior

The aws cli which is installed inside the docker-container should works fine as it was working with the host instance when running the docker container inside the ec2 instance that has attached with the IAM to read all ec2 services.

### Current Behavior

An error occurred (UnauthorizedOperation) when calling the DescribeInstances operation: You are not authorized to perform this operation.

### Reproduction Steps

Install docker in Ubuntu 22.04 AMI in AWS.
Create a IAM role that has attached with the AWS managed AmazonEC2ReadOnlyAccess policy.
Attach this role to the instance.
Restart the instance so that the instance policy attached to it.
Run command `docker run -it --rm amazon/aws-cli ec2 describe-instances` inside the instance

### CLI version used

 aws-cli/2.10.3 Python/3.9.11 Linux/5.15.0-1030-aws docker/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 22.04 Official AWS AMI

**Comment by aBurmeseDev** [comment]
Hi @TheSwarnim - thanks for reaching out.

Are you able to run this CLI command without docker `aws ec2 describe-instances --region <region> --profile <profile>`? There are a few possibilities for this error that I would double check:
- your IAM policy and try attaching it to the correct user that you're configured with.
```
{
   "Version": "2012-10-17",
   "Statement": [{
      "Effect": "Allow",
      "Action": "ec2:DescribeInstances",
      "Resource": "*"
   }
   ]
}
```
- if you're targeting the correct region
- if credentials are configured correctly and profile is set

I'm going to share these posts, troubleshoot guides and docs that might be useful: 
- https://github.com/aws/aws-cli/issues/5628
- [New IAM admin user sees "You are not authorized to perform this operation"](https://stackoverflow.com/questions/41621353/new-iam-admin-user-sees-you-are-not-authorized-to-perform-this-operation)
- [AWS Support Troubleshoot Guide](https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-iam-policy-issues/)
- [Granting Required Permission for EC2 Resources](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/ec2-api-permissions.html)
- [Amazon EC2: Allows starting or stopping EC2 instances a user has tagged, programmatically and in the console](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_ec2_tag-owner.html)

If the issue persists, please share full debug logs as that would give us more insight to the error. You can retrieve the logs by adding `--debug` to the command.

Best,
John
