### ISSUE TITLE
aws waf list-web-acls command always return empty result

### ISSUE THREAD

**Issue by ParthaI** [aws/aws-cli#7710]
### Describe the bug

The `aws waf list-web-acls` command always return empty result, even though the Global(Cloudfront) and regional resources are available in the console.

Regional Resources:
<img width="1392" alt="Screenshot 2023-02-27 at 10 42 55 AM" src="https://user-images.githubusercontent.com/47887552/221479894-fb872e08-ae58-4390-b29b-777cf29c86e0.png">

Global(Cloudfront)  Resources:
<img width="1387" alt="Screenshot 2023-02-27 at 10 43 18 AM" src="https://user-images.githubusercontent.com/47887552/221479950-1dc26167-dd4a-44ef-b25f-1f4f19ff2a4c.png">

### Expected Behavior

The command The `aws waf list-web-acls` should return all the available resources.

### Current Behavior

The `aws waf list-web-acls` command always return empty result

### Reproduction Steps

- Create both Global(Cloudfront) and regional WebAcl resources.
- Run the command `aws waf list-web-acls`

### Possible Solution

N/A

### Additional Information/Context

N/A

### CLI version used

aws-cli/2.9.4 Python/3.9.11 Darwin/20.5.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Mac, Big Sur, 11.4

**Comment by ParthaI** [comment]
Hi @tim-finnigan I ran the command `aws waf list-web-acls --region us-east-1 --debug` got empty result. But the command `aws waf-regional list-web-acls --region us-east-1` returning the result.

- If we are creating a regional Web-Acl then the command `aws waf-regional list-web-acls --region us-east-1` will help us for discovering the resources.
- If WAF resources associated with CloudFront distributions then the command `aws waf list-web-acls --region global` is helful.

Appreciate you help.
Thanks!

**Comment by tim-finnigan** [comment]
Thanks for following up to confirm. Based on the [comment](https://github.com/aws/aws-cli/issues/3733#issuecomment-444968494) referenced earlier, this seems to be the expected behavior then. If you have any additional feedback to share please let us know.
