### ISSUE TITLE
cli silently uses default config when AWS_CONFIG_FILE is set but file not found

### ISSUE THREAD

**Issue by lcmgh** [aws/aws-cli#7714]
### Describe the bug

```bash
AWS_CONFIG_FILE=~/.aws/not-exists aws \
--profile my-profile ssm start-session \
--target i-123 \
--document-name AWS-StartPortForwardingSession \
--parameters '{"portNumber":["22"],"localPortNumber":["2222"]}'
```

The cil silently reads the default config file instead of throwing an error that `~/.aws/not-exists` does not exist. I noticed that while developing an app that calls the cli.

That behavior is also not documented in here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
It just says
```
AWS_CONFIG_FILE
Specifies the location of the file that the AWS CLI uses to store configuration profiles. The default path is ~/.aws/config.

You can't specify this value in a named profile setting or by using a command line parameter.
```

My example code
```rust
// For some reason AWS_CONFIG_FILE is not taken into account in here but this is another issue .. 
// for that you may also have an idea?
let mut child = Command::new("aws")
.env("AWS_CONFIG_FILE", config_path())
.env("AWS_PROFILE", &input.profile)
    .args(args)
    .stdout(Stdio::piped())
    .stderr(Stdio::piped())
    .spawn()?;
```

### Expected Behavior

Cli exits with an error code and states that the AWS_CONFIG_FILE file `value of AWS_CONFIG_FILE` could not be found.

### Current Behavior

- No error msg
- Default config file is used

### Reproduction Steps

See "Describe the bug".

### CLI version used

aws-cli/2.9.20 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

aws-cli/2.9.20 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off

**Comment by lcmgh** [comment]
Regarding the second issue I had. What I don't understand is when I call the cli via my Rust program it says the profile is not found.

Manual call works fine:

```bash
AWS_CONFIG_FILE=/Users/abc/.aws/config_custom
AWS_PROFILE=UserRo_nonprod_arn:aws:rds:eu-central-1:12345:cluster:ms-ms-test-eu-central-1-rds
aws ssm start-session --target i-abc --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["22"],"localPortNumber":["2222"]}'
```

Making the same call via Rust fails with "profile not found".

```rust
let mut child = Command::new("aws")
  .env("AWS_CONFIG_FILE", config_path)
  .env("AWS_PROFILE", &input.profile)
      .args(args)
      .stdout(Stdio::piped())
      .stderr(Stdio::piped())
      .spawn()?;
```

I ensured via logging that:
* `AWS_CONFIG_FILE`'s variable `config_path` is set to `/Users/abc/.aws/config_custom`
* `input.profile` is set to `UserRo_nonprod_arn:aws:rds:eu-central-1:12345:cluster:ms-ms-test-eu-central-1-rds`
* args are also the same as via shell: `["ssm", "start-session", "--target", "i-abc", "--document-name", "AWS-StartPortForwardingSession", "--parameters", "{\"portNumber\":[\"22\"],\"localPortNumber\":[\"2222\"]}"]`

However it fails with: 

```
The config profile (profile UserRo_nonprod_arn:aws:rds:eu-central-1:12345:cluster:ms-ms-test-eu-central-1-rds) could not be found    
```

**Comment by tim-finnigan** [comment]
Hi @lcmgh thanks for reaching out. Here is the AWS CLI documentation on credentials precedence: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence. Attempts are made to find credentials in that order. If you add `--debug` to a CLI command, then it will provide more insight into the behavior. And here is the credentials documentation for the Rust SDK: https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credentials.html. 

I think what you're describing is the expected behavior regarding the credential order of precedence. I'm not very familiar with the Rust SDK but it might be worth opening an issue in that repository if this issue is specific to that SDK. Please let us know if the are any details you'd like to elaborate on here related to this issue.

**Comment by lcmgh** [comment]
That's correct. I still would have expected a message when the config file could not be found.

**Comment by Farmbuyer** [comment]
> I still would have expected a message when the config file could not be found.

Agreed!  The user clearly intends a specific file to be used; if the CLI can't find it, silently ignoring the user's direction is wildly unhelpful.

Even more annoying, adding `--debug` doesn't mention anything about trying to find the file and failing.
