### ISSUE TITLE
aws eks update-kubeconfig doesn't generate config with env var AWS_SHARED_CREDENTIALS_FILE

### ISSUE THREAD

**Issue by zhnu** [aws/aws-cli#7724]
### Describe the bug

Hi, when running `aws eks update-kubeconfig --kubeconfig example` the environment variable (if set) `AWS_SHARED_CREDENTIALS_FILE` isn't appended to the generated kubeconfig, while the environment variable  `AWS_PROFILE` is. This causes failures in libraries that use this kubeconfig to authenticate (for example the python kubernetes client library).

### Expected Behavior

Expected to either cli set the environment var on the kubeconfig if exists or documentation warning.

### Current Behavior

Currently the environment variable is read during the command but not written to the kubeconfig file output.

### Reproduction Steps

`
export AWS_SHARED_CREDENTIALS_FILE="~/.aws/test.credentials"
aws --region "something" --profile "something" eks update-kubeconfig --name "example-cluster" --kubeconfig kubeconfig
unset AWS_SHARED_CREDENTIALS_FILE
`
test.py

`from kubernetes import client, config

config.load_kube_config(config_file='./kubeconfig')

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))`

### CLI version used

aws-cli/2.10.1

### Environment details (OS name and version, etc.)

Linux 22.04.1-Ubuntu

**Comment by tim-finnigan** [comment]
This issue should be fixed via the PR linked above (https://github.com/aws/aws-cli/pull/7726). Those changes will be available in the next CLI release.

**Comment by tim-finnigan** [comment]
The fixed version for v1 will be out today and for v2 tomorrow. You will need to regenerate the config with `update-kubeconfig` again.

**Comment by zhnu** [comment]
Thank you for the fast resolution, have a great day.
