### ISSUE TITLE
identitystore list-users documentation inconsistent

### ISSUE THREAD

**Issue by jregovic** [aws/aws-cli#7725]
### Describe the issue

The documentation  for the identitystore list-users commands shows that filters are not required. Using the command in the CLI fails with a message that the filter is required.

`% aws identitystore list-users --identity-store-id d-XXXXXXXXXX --region us-west-2

An error occurred (ValidationException) when calling the ListUsers operation: Filter is required`

`% aws identitystore list-users help
...
SYNOPSIS

            list-users
          --identity-store-id <value>
          [--filters <value>]
...
`

### Links

https://docs.aws.amazon.com/cli/latest/reference/identitystore/list-users.html

**Comment by tim-finnigan** [comment]
Hi @jregovic thanks for reaching out. Which version of the CLI are you using? I wasn't able to reproduce the issue on the latest version (2.11.0). Have you tried [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the CLI?

**Comment by jregovic** [comment]
`# aws --version
aws-cli/2.11.0 Python/3.11.2 Linux/5.10.104-linuxkit exe/x86_64.ubuntu.22 prompt/off`

I tried a fresh install of the of the CLI. I wonder if there is anything causing problems with the identity provider being active directory.
