### ISSUE TITLE
Aws-cli : An error occurred (404) when calling the CreateFunctionUrlConfig 

### ISSUE THREAD

**Issue by 301991Johnson** [aws/aws-cli#7732]
### Describe the bug

ERROR SNAP:

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

C:\Workspace\repo
Command to exec - aws --endpoint-url=http://localhost:4566/ lambda get-function-url-config --function-name myFunction

An error occurred (404) when calling the GetFunctionUrlConfig operation:

<title>404 Not Found</title>
Docker.yaml

version: '3.1'
![Error-log](https://user-images.githubusercontent.com/127124518/223472869-116d8286-1ace-4f9d-95fc-a4277d41a5b3.png)

### Expected Behavior

create function-url should generate url and attached it to the function.

### Current Behavior

getting error while calling the createfunctionurl aws-cli command

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

C:\Workspace\repo
Command to exec - aws --endpoint-url=http://localhost:4566/ lambda get-function-url-config --function-name myFunction

An error occurred (404) when calling the GetFunctionUrlConfig operation:

<title>404 Not Found</title>

### Reproduction Steps

Running the following comands:

1.run create function aws-cli command
2.run createFunctionurl aws-cli command

### CLI version used

aws-cli/2.8.2 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

windows 10 Enterprise , version - 21H2

**Comment by tim-finnigan** [comment]
Hi @301991Johnson thanks for reaching out. Here are a couple of documentation pages for reference:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function-url-config.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/get-function-url-config.html

I don't think you want to pass an `--endpoint-url` parameter when creating the function URL. As noted in the Lambda [Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html): "When you create a function URL, Lambda automatically generates a unique URL endpoint for you," which will be in this format: `https://<url-id>.lambda-url.<region>.on.aws`. 

I hope that helps, please let us know if you have any follow up questions.
