### ISSUE TITLE
aws ec2 accept-vpc-endpoint-connections and reject-vpc-endpoint-connections returns double negative when successful

### ISSUE THREAD

**Issue by cstahl99** [aws/aws-cli#7733]
### Describe the feature

aws ec2 accept-vpc-endpoint-connections and reject-vpc-endpoint-connections returns the following json when successful:

{
    "Unsuccessful": []
}

This is "Unsuccessful" and an empty list. It is  an improper double negative and confusing to the user executing this command.

### Use Case

When the user executes this command and sees this result, the logical conclusion is the command was unsuccessful, when in fact it was successful.

### Proposed Solution

Do not return "Unsuccessful" when the command succeeds.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.1.6

### Environment details (OS name and version, etc.)

RH Linux 7

**Comment by tim-finnigan** [comment]
Hi @cstahl99 thanks for sharing your feedback. Those commands are using the EC2 APIs [AcceptVpcEndpointConnections](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AcceptVpcEndpointConnections.html) and [RejectVpcEndpointConnections](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RejectVpcEndpointConnections.html). Both APIs return the response element:
>unsuccessful
>
>    Information about the interface endpoints that were not accepted, if applicable.
>
>    Type: Array of [UnsuccessfulItem](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_UnsuccessfulItem.html) objects

I agree that this is somewhat confusing, and we can pass that feedback on to the EC2 team. But I think it is unlikely that the current APIs would change given the need to maintain backwards compatibility.
