### ISSUE TITLE
aws ecr get-login-password fails when using --profile, same profile works fine using AWS_PROFILE env var

### ISSUE THREAD

**Issue by hakanai** [aws/aws-cli#7737]
### Describe the bug

The following command fails to login for my account:

```shell
aws ecr get-login-password --profile my-profile
```

The error message I got today is:

```
Error when retrieving token from sso: Token has expired and refresh failed
```

(It's a different error message to what I saw yesterday, but I don't have the history for that anymore.)

This command, however, works fine:

```shell
AWS_PROFILE=my-profile aws ecr get-login-password
```

I didn't see this `AWS_PROFILE` variable mentioned on any documentation pages or help pages for the tool while I was trying to figure this out for myself - it was suggested by another developer at work, who presumably figured out this issue years ago without reporting it.

However, the docs (e.g. `aws ecr get-login-password --help`) only mention the command-line flag, so it would be nice if the documented method also worked.

Maybe this issue only surfaces when using SSO?

### Expected Behavior

Already covered in the description, but I expected the documented `--profile` parameter to work.

### Current Behavior

Also already covered in the description, but using the `--profile` parameter fails with:

```
Error when retrieving token from sso: Token has expired and refresh failed
```

Even though using the equivalent `AWS_PROFILE` environment variable works fine.

### Reproduction Steps

1. Have SSO
2. Make sure the account actually has ECR access
3. Run

    ```shell
    aws ecr get-login-password --profile YOUR-PROFILE
    ```

### CLI version used

aws/2.10.3

### Environment details (OS name and version, etc.)

Python/3.11.2 Darwin/22.3.0 arm64

**Comment by tim-finnigan** [comment]
Hi @hakanai thanks for reaching out. Here is the AWS CLI credential precedence documentation for reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence. 

You can also refer to [this documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) on profile configurations for more information on the `AWS_PROFILE` environment variable. SSO (now known as [Identity Center](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)) is another way of authenticating. It consists of [user sessions](https://docs.aws.amazon.com/singlesignon/latest/userguide/configure-user-session.html) which expire after eight hours by default:
>By default, the duration of a AWS access portal session, which is the maximum length of time that a user can be signed into the AWS access portal without re-authenticating into the portal, is eight hours. You can specify a different duration, from a minimum of 15 minutes to a maximum of seven days.  

If you add `--debug` to your command then it will provide more information on how you are authenticating. Also if you run `aws ecr get-login-password help` it will provide more information about the [get-login-password](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/get-login-password.html) command. I hope that helps, please let us know if you had any follow up questions.

**Comment by hakanai** [comment]
As I alluded to in the initial report, the help text talks about the `--profile` command-line flag. It doesn't mention the `AWS_PROFILE` variable, which appeared to be buried somewhere else in the documentation on the web site.

In case it was unclear, I have figured out how to login using the environment variable, which is why I am filing a bug about the documented way _not_ working.

As a rule of thumb, it's best if the documentation describes the _working_ functionality of a tool, so that people who have to use the tool don't get mislead.

**Comment by tim-finnigan** [comment]
Thanks @hakanai for following up. When I typed `aws ecr get-login-password help` in the CLI I saw `--debug` and `--profile` listed under Global Options which is expected. `AWS_PROFILE` is listed [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list) in the AWS CLI environment variables documentation. Please let us know if you have debug logs to share for looking into this issue further.

**Comment by hakanai** [comment]
I got the output, but pastebin is interfering with me getting the file across to here because something in it is triggering the spam detection. I'll have to comb through it manually to figure out what might be causing that. Probably next work day, because today is finished.

**Comment by hakanai** [comment]
Log files from the run today, but beware: today, the behaviour has _reversed_:
* `AWS_PROFILE=my-profile aws ecr get-login-password` now **FAILS** - [logs](https://github.com/aws/aws-cli/files/11023791/get-login-password-fails.log)
* `aws ecr get-login-password --profile my-profile` now **SUCCEEDS** - [logs](https://github.com/aws/aws-cli/files/11023790/get-login-password-succeeds.log)

Still completely reproducible - same failure and same success behaviour no matter how many times I re-run it.

I also logged in and out of SSO a number of times in the process, trying to get the behaviour from the other day, but it seems that today, this is just how it's deciding to be.

I also compared with another workmate, who swears that the env var is the only one that ever works for him.

Nothing else in my environment has changed since last time - something may have changed on Amazon's end because we have zero visibility of that.

**Comment by tim-finnigan** [comment]
Checking in again, thanks for your patience. It looks like the steps suggested [here](https://stackoverflow.com/a/75989556) might address the issue you're encountering. Can you confirm, or do you have any updates on your end?

**Comment by hakanai** [comment]
I can have a look at it the next time I'm facing the issue. I don't use AWS very actively at work.

But just to clarify, my report was that the two methods of doing "the thing" work differently, even though they are documented as being identical. Clearly they are _not_ identical, and no amount of me working around it is going to fix the bug in the tool.

**Comment by hakanai** [comment]
Just to reiterate, since it didn't seem to get through the first time - 

I was not asking for help to get the command to work because I already found a workaround.

I was reporting _THE BUG_, so that someone could look at properly fixing it and making the tool work as documented. Or, alternatively, updating the docs so that they don't suggest that the two ways work the same way.

**Comment by tim-finnigan** [comment]
Hi @hakani, my apologies for any confusion. In order to address any bug we would need to narrow down the causes and when it occurs. A clear summary of the steps to reproduce the issue is required. If the behavior reversed as you said then I'm wondering if this was something transient involving your session token. 

The CLI team can investigate issues with things like profiles and environment variables. If there is an API issue then we would reroute it to a service team such as [SSO](https://aws.amazon.com/iam/identity-center/). If there is a documentation page that you have feedback on then there are [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Command%20Line%20Interface&topic_url=http://docs.aws.amazon.com/en_us/cli/latest/userguide/cli-configure-files.html) links at the bottom of AWS documentation pages you can use.
