### ISSUE TITLE
`--deletion-protection-enabled` added to AWS CLI V1 but missing from AWS CLI V2

### ISSUE THREAD

**Issue by ylhan** [aws/aws-cli#7740]
### Describe the bug

DynamoDB's `--deletion-protection-enabled` flag was just added ([source](https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/)). It seems like it was added to AWS CLI V1 ([source](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/update-table.html)), but for AWS CLI V2 the option isn't there ([source](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dynamodb/update-table.html)).

### Expected Behavior

The command to succeed and deletion protection enabled.

### Current Behavior

Command fails because option cannot be found

### Reproduction Steps

```
aws dynamodb update-table --table-name my_table --deletion-protection-enabled

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --deletion-protection-enabled
```

### Possible Solution

Add the flag to AWS CLI V2

### CLI version used

aws-cli/2.11.1 Python/3.11.2 Darwin/21.4.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

ProductName:	macOS ProductVersion:	12.3 BuildVersion:	21E230

**Comment by tim-finnigan** [comment]
Hi @ylhan thanks for reaching out. It looks like that parameter was just added in version 2.11.2 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). If you update to that version then you should have access to it. If you run into any issues let us know, otherwise I think this can be closed.

**Comment by landsman** [comment]
I'm using `aws-cli/2.2.5` and it's not there. This is crazy guys...

**Comment by tim-finnigan** [comment]
> I'm using `aws-cli/2.2.5` and it's not there. This is crazy guys...

Please see https://github.com/aws/aws-cli/issues/8155#issuecomment-1706808142.
