### ISSUE TITLE
update-event-source-mapping does not support 'DatabaseName' or 'CollectionName' when specifying 'document-db-event-source-config'

### ISSUE THREAD

**Issue by cod-all** [aws/aws-cli#7756]
### Describe the issue

AWS CLI documentation for Lambda command `update-event-source-mapping` states that parameter `document-db-event-source-config` can be provided with `DatabaseName` and `CollectionName` 

Running the command provides the following error:

`An error occurred (InvalidParameterValueException) when calling the UpdateEventSourceMapping operation: Invalid parameters: collectionName, databaseName`

It is not possible to edit the namespace for an existing Lambda trigger and this parameter is not applicable to this command. 

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/update-event-source-mapping.html?highlight=updateeventsourcemapping

**Comment by tim-finnigan** [comment]
Hi @cod-all thanks for reaching out. Which version of the AWS CLI are you using? Have you tried [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to the latest version of the AWS CLI and running this command? (Currently the latest version is 2.11.4 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1)). 

If you still see the issue after updating then you could add `--debug` to your command to see the full logs, which may provide more insight into the underlying issue.

The command documentation is generated upstream by service teams, so we can reach out to the Lambda team if there are any inaccuracies. (If you click the [AWS API Documentation](https://docs.aws.amazon.com/goto/WebAPI/lambda-2015-03-31/UpdateEventSourceMapping) page from the CLI reference for that command, then you can also send feedback directly via the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=Lambda&topic_url=http://docs.aws.amazon.com/en_us/lambda/latest/dg/API_UpdateEventSourceMapping.html) links at the bottom of those pages.)
