### ISSUE TITLE
Support for aws-crt-python (AWS Common Runtime)

### ISSUE THREAD

**Issue by heri16** [aws/aws-cli#7786]
### Describe the feature

Would like to see the AWS CLI use the AWS Common Runtime [Python Bindings](https://github.com/awslabs/aws-crt-python).

### Use Case

Enables use of [Post-Quantum Cryptography](https://docs.aws.amazon.com/kms/latest/developerguide/pqtls.html#pqtls-details) for `aws kms decrypt`.

### Proposed Solution

Use this library (which includes s2n-tls) : https://github.com/awslabs/aws-crt-python

### Other Information

- https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html
- https://docs.aws.amazon.com/kms/latest/developerguide/pqtls.html#pqtls-details

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.11.6

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Hi @heri16 thanks for reaching out. The AWS CLI does support [awscrt](https://github.com/aws/aws-cli/blob/bf6e8ac99149969c1490bbde3695a9bab940030e/pyproject.toml#L42). For example here is documentation for using the CRT as your S3 transfer client: https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#preferred-transfer-client. Please let us know if you had any follow up questions.
