### ISSUE TITLE
(i has having an error when transferring a file from one bucket to another)

### ISSUE THREAD

**Issue by itsmemidhuz123** [aws/aws-cli#7793]
### Describe the issue

i tried transferring the bucket from one account to another account. I wanted to transfer the complete bucket, but when using the command 

aws s3 cp s3://source-bucket/video2872899822.mp4 s3://destination-bucket --acl bucket-owner-full-control

it shows this error message, i need some help with this

copy failed: s3://bucket/video2872899822.mp4 to s3://destination-bucket/video2872899822.mp4 An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied

### CLI version used

latest 

### Environment details (OS name and version, etc.)

MacOs

**Comment by itsmemidhuz123** [comment]
hi it resolved

**Comment by kiranbakale1talentica** [comment]
Hi @itsmemidhuz123 

can you please let me know , what was the fix for this please

**Comment by itsmemidhuz123** [comment]
As i remember, the AWS bucket are set to disable the transfer from other bucket source. I enabled it to accept the transfer from one to another using cli

https://repost.aws/knowledge-center/s3-access-denied-error-kms

Hope this helps but can be resolved
