### ISSUE TITLE
AWS CLI didn't pop up on windows

### ISSUE THREAD

**Issue by mhasan247** [aws/aws-cli#7799]
### Describe the bug

I have installed the latest version of AWS CLI. While I am trying to open the installed CLI, it's popping up windows for a second and disappearing instantly. I don't know what is the possible reason for that. 

Here is the output while I am entering the command: aws --version
aws-cli/2.11.8 Python/3.11.2 Windows/10 exe/AMD64 prompt/off

N:B: I am using Windows 10 Pro Education (64-bit)

### Expected Behavior

It should prompt the CLI and not to be disappear while I am clicking installed AWS CLI on my windows 10 

### Current Behavior

While I am clicking the installed AWS-CLI it's not popping up properly and suddenly disappearing.

### Reproduction Steps

I don't know what to share about this!!

### CLI version used

aws-cli/2.11.8

### Environment details (OS name and version, etc.)

Windows 10 Pro Education (64-bit)

**Comment by aBurmeseDev** [comment]
Hi @mhasan247 - thanks for reaching out. 
I wanted to clarify a few things with you first. From what you described from running `aws --version`, I can confirm AWS CLI is installed properly on your machine.
>Here is the output while I am entering the command: aws --version
aws-cli/2.11.8 Python/3.11.2 Windows/10 exe/AMD64 prompt/off

When you said you're trying to open the installed CLI and the window disappeared instantly, are you referring to your Windows terminal/command-line?

Does this [discussion post](https://github.com/aws/aws-cli/discussions/7155) address what you're experiencing?

Best,
John

**Comment by mhasan247** [comment]
Hi @aBurmeseDev, 
Thanks for your response. 
I'm not referring to Windows CLI because it's working fine.  The issue I am facing with the AWS CLI MSI installer for Windows (64-bit): https://s3.amazonaws.com/aws-cli/AWSCLI64PY3.msi

**Comment by aBurmeseDev** [comment]
@mhasan247 - thanks for confirming that. I'm still quite confused and have the following questions
- Can you share where you downloaded the link? 
- There's installer link (https://awscli.amazonaws.com/AWSCLIV2.msi) in AWS CLI [installation guide](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) under Windows and it's different from the link you shared.
- From what you initially shared from running `aws --version`, it seems you already have AWS CLI installed in your machine. You should be able to run any CLI commands in your command prompt. Have you tried running any commands?

I'm going to share these installation steps directly from the guide mentioned above:

1. Download and run the AWS CLI MSI installer for Windows (64-bit):
https://awscli.amazonaws.com/AWSCLIV2.msi

2. To confirm the installation, open the Start menu, search for `cmd` to open a command prompt window, and at the command prompt use the `aws --version` command.
```
C:\> aws --version
aws-cli/2.10.0 Python/3.11.2 Windows/10 exe/AMD64 prompt/off
```

Hope that helps,
John
