### ISSUE TITLE
bug: aws eks update-kubeconfig got 'NoneType' object error

### ISSUE THREAD

**Issue by ericsyh** [aws/aws-cli#7801]
### Describe the bug

I used the https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks to provision eks on my aws and after the provision is finished. I ran the command `aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)` to set the kubeconfig but got error as below

```
'NoneType' object is not iterable
```

### Expected Behavior

Should set up the kubeconfig successfully. 

### Current Behavior

Got error as 
```
'NoneType' object is not iterable
```

### Reproduction Steps

1. Use the https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks to provision an eks cluster
2. After the provision, use the command `aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)` to set up the kubeconfig

### CLI version used

aws-cli/2.11.8 Python/3.11.2 Darwin/20.6.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS 11.7.4

**Comment by aBurmeseDev** [comment]
Hi @ericsyh - thanks for reaching out. 
I was able to find a couple similar issues ([here](https://github.com/aws/aws-cli/issues/4843) & [here](https://github.com/aws/aws-cli/issues/5532)) for this issue with `esk update-kubeconfig`. There's a [workaround](https://github.com/aws/aws-cli/issues/4843#issuecomment-575756827) suggested by a user that is to remove the existing ~/.kube/config file and run the same command. Could you please try that and confirm if that works for you?

Best,
John

**Comment by ericsyh** [comment]
> 

Okay, sure. Thanks. But actually I removed my existing and legacy local kube configs with `kc config delete-cluster` commands which should similar to rm the `kube.config` file. 

Seems I can't reproduce this issue recently after my removal.

**Comment by aBurmeseDev** [comment]
Thanks for letting us know that it's working as expected now. I'm going to close this and please feel free to reach out anytime if you have any other questions. 
Best,
John
