### ISSUE TITLE
aws s3 mb sets the ObjectOwnership to different setting per region

### ISSUE THREAD

**Issue by rohith-vallabhaneni** [aws/aws-cli#7838]
### Describe the bug

The ObjectOwnership permission is set to Object writer by default as per the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html) but it is changing per region. 
This is getting set to the **default(ObjectWriter)** in _us-east-1_ but the same setting is getting changed to the **recommended(BucketOwnerEnforced)** in the _us-east-2_ region.

### Expected Behavior

By default, the `aws s3 mb` should set the ObjectOwnership permission to **ObjectWriter** in any region

### Current Behavior

I have tested this on us-east-2 and the ObjectOwnership is getting set to **BucketOwnerEnforced**

### Reproduction Steps

Try running `aws s3 mb s3://mybucket --region=<region>` with us-east-1 & us-east-2 regions and check the ObjectOwnership permission

### Possible Solution

Run the below command after running the aws s3 mb 
`aws s3api put-bucket-ownership-controls --bucket <value> --ownership-controls="Rules=[{ObjectOwnership= ObjectWriter}]" --region=<region>`

### CLI version used

2.8.10

### Environment details (OS name and version, etc.)

I have Python-3.9, OS-Darwin-22.3

**Comment by tim-finnigan** [comment]
Hi @rohith-vallabhaneni thanks for reporting this issue. In the [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html) you linked it notes:

>Starting in April 2023, Amazon S3 will change the default settings for S3 Block Public Access and Object Ownership (ACLs disabled) for all new S3 buckets. For new buckets created after this update, all S3 Block Public Access settings will be enabled, and S3 access control lists (ACLs) will be disabled. These defaults are the recommended best practices for securing data in Amazon S3. You can adjust these settings after creating your bucket. For more information, see[ Default settings for new S3 buckets FAQ](https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-faq.html) and [Heads-Up: Amazon S3 Security Changes Are Coming in April of 2023](http://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/) in the AWS News Blog.

As noted in the pages linked above, the new default settings will gradually be rolled out across all AWS Regions. In the meantime you may see inconsistencies with the default access configurations in different regions. A [What’s New](https://aws.amazon.com/new/) post will be published when the deployment has reached all AWS Regions.
