### ISSUE TITLE
Could not resolve host awscli.amazonaws.com

### ISSUE THREAD

**Issue by TerriblyVexed1** [aws/aws-cli#7841]
### Describe the bug

`curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"` produces error
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: awscli.amazonaws.com`

### Expected Behavior

Should have downloaded the awscli installation zip file.

### Current Behavior

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: awscli.amazonaws.com`

### Reproduction Steps

Run `curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"`

### CLI version used

n/a

### Environment details (OS name and version, etc.)

WSL2 on Windows 10

**Comment by TerriblyVexed1** [comment]
Was a WSL2 issue, not a awscli issue

**Comment by Lalitha23** [comment]
Having the same issue on Ubuntu machine too. 
Getting page not found error for https://awscli.amazonaws.com/

**Comment by lukasnagl** [comment]
If you're encountering this from your friendly neighbordhood search and are using **WSL**, you might have the issue because of a [missing network configuration](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#network-settings). Add the following to `/etc/wsl.conf`:

```
[network]
generateResolvConf = true
```
