### ISSUE TITLE
homebrew dependency problem with awscli formula

### ISSUE THREAD

**Issue by greenchapter** [aws/aws-cli#7843]
### Describe the issue

I installed the `aws-cli` with Homebrew and everything is running well in version `aws-cli/2.11.14`

When I run `brew doctor` I got the following warning

```
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  pycparser
  cffi
```

It looks like there is a dependency problem with the awscli formula.

https://formulae.brew.sh/formula/awscli#default

### CLI version used

aws-cli/2.11.14 Python/3.11.3 Darwin/22.4.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 13.3.1 / aarch64

**Comment by tim-finnigan** [comment]
Hi @greenchapter thanks for reaching out. Here is the documentation for supported installation methods: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. Homebrew is not documented as a supported method, we recommend using one of the alternative installation methods documented there.
