### ISSUE TITLE
stay in aws cli after command execution

### ISSUE THREAD

**Issue by CloudZero458** [aws/aws-cli#7844]
### Describe the feature

you should be able to stay in the aws cli after command execution. This should work in any mode (default, auto-prompt, auto-prompt partial)

### Use Case

I want to be able to issue a command without it exiting the cli and then having to type "aws" every time

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

v2

### Environment details (OS name and version, etc.)

WSL: Debian

**Comment by tim-finnigan** [comment]
Hi @CloudZero458 thanks for the feature request. There is already an issue open for this: https://github.com/aws/aws-cli/issues/5665. I also think this would be a useful feature. Please feel free to add a 👍 to that issue to show support and comment if you had any other related info to share. For the sake of consolidation I think we should close this as a duplicate.
