### ISSUE TITLE
imagebuild list-image-pipeline-images filter on full version

### ISSUE THREAD

**Issue by greg-res** [aws/aws-cli#7853]
### Describe the bug

Filter bug on `aws imagebuild list-image-pipeline-images` when attempting to filter by the full version.

`aws imagebuilder list-image-pipeline-images --image-pipeline-arn $PIPELINE_ARN --filters name=version,values="1.0.4/3"`
results in a list of 0 images

however without the '/3' specific build number a full list of images does return:
`aws imagebuilder list-image-pipeline-images --image-pipeline-arn $PIPELINE_ARN --filters name=version,values="1.0.4"`

Including the '/' seems to break the filter, which is part of the full version.

### Expected Behavior

Being able to filter on the full version of an image pipeline that includes a '/'.

### Current Behavior

0 images are being returned.

### Reproduction Steps

aws imagebuilder list-image-pipeline-images --image-pipeline-arn $PIPELINE_ARN --filters name=version,values="1.0.4"

aws imagebuilder list-image-pipeline-images --image-pipeline-arn $PIPELINE_ARN --filters name=version,values="1.0.4/3"

### CLI version used

aws-cli/2.11.13

### Environment details (OS name and version, etc.)

macOS 13.3.1

**Comment by RyanFitzSimmonsAK** [comment]
Hi @greg-res, thanks for reaching out.  Could you provide some debug logs of runs with and without the full version number?  You can get debug logs by adding --debug to your call, and redacting any sensitive information.  Thanks!
