### ISSUE TITLE
AWS cli auto-prompt breaks kubectl with Amazon EKS

### ISSUE THREAD

**Issue by nicoaws** [aws/aws-cli#7862]
### Describe the bug

When the AWS CLI has auto-prompt enabled by `cli_auto_prompt = on`, any `kubectl` commands against the control plane API of EKS clusters.
Kubectl obtains a cluster token by issuing the following CLI command ` aws eks get-token --region eu-west-1 --cluster-name my-cluster --output json` (see below `kubeconfig` file).

```user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --output
      - json
      command: aws
  ```
      
This command stalls without erroring as it waits for a user prompt (because auto-prompt is enabled). It's something difficult to troubleshoot as it doesn't report any errors.

### Expected Behavior

Auto-prompt is engaged just when commands are thrown in an interactive mode directly from the CLI and not from another executable/command.

### Current Behavior

Kubectl hangs

### Reproduction Steps

See description. 

### CLI version used

aws-cli/2.11.15 Python/3.11.3 Darwin/22.4.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Ventura

**Comment by tim-finnigan** [comment]
Hi @nicoaws thanks for reaching out. Have you tried using the `on-partial` mode documented here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html?

>`on-partial` uses partial auto-prompt mode. If a command is incomplete or cannot be run due to client-side validation errors, auto-prompt is used. This mode is particular useful if you have pre-existing scripts, runbooks, or you only want to be auto-prompted for commands you are unfamiliar with rather than prompted on every command.
