### ISSUE TITLE
set stack policy on the stack

### ISSUE THREAD

**Issue by lesh3000** [aws/aws-cli#7866]
### Describe the issue

I need to set stack policy on the already existent stack to avoid modifying existing resources.
Normally it is possible with aws cli, the documentation is missing this part
Is that possibe with AWS SAM build or deploy methods?

### Links

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html

**Comment by aBurmeseDev** [comment]
Hi @lesh3000 - thanks for reaching out. 
Could you elaborate more on your use case as to which part of CLI documentation needs to be updated? Are you referring to [SetStackPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetStackPolicy.html)? I'm not sure if it's possible with AWS SAM build but I'd be happy to check with the service team if that's what you're looking to do.

**Comment by lesh3000** [comment]
Hi @aBurmeseDev ,
I just supposed it is possible but probably I am wrong.
StackPolicy sets allow or deny on specific resources to allow the stack to update/delete them, you have referred to the right resource.
My SAM template has ec2 declared that contains some installed software that I like to keep. I manually updated the instance type, and now cannot deploy updated lambdas, since SAM will delete the instance first and will create a new one

**Comment by aBurmeseDev** [comment]
Hi @lesh3000 - I'm sorry this fell off my radar. It sounds like it's more of SAM related question rather than AWS CLI. This repo is dedicated to AWS CLI but I'd be happy to find answers to your question if you still need assistance on it?
