### ISSUE TITLE
Permission set / role not being detected 

### ISSUE THREAD

**Issue by juliencol** [aws/aws-cli#7871]
### Describe the bug

Unexpected `ForbiddenException` when running `aws sts get-caller-identity --profile profile-2` for one of my AWS profiles named profile-2 in my config file. 

### Expected Behavior

I would expect `aws sts get-caller-identity --profile profile-2` to return the Role2 permission set every time I run the command and my AWS SSO user has access to the Role2 permission set. 

### Current Behavior

When I run I `aws sts get-caller-identity --profile profile-2` I get a `ForbiddenException` error once in a while even when my user has access to the Role2 permission set. 

### Reproduction Steps

To reproduce, my config file looks like this.
```
[sso-session session]
sso_start_url = https://example.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access

[profile profile-1]
sso_account_id = 111122223333
sso_role_name = Role1
region = us-east-1
output = json
sso_session = session

[profile profile-2]
sso_account_id = 111122223333
sso_role_name = Role2
region = us-east-1
output = json
sso_session = session
```

Then I run the following commands to refresh my session and access my roles. 
- `aws sso logout` - This operation succeeds. It doesn't return anything. 
- `aws sso login --sso-session session` - This operation succeeds. It opens a browser window and then confirms I'm logged in. 
- `aws sts get-caller-identity --profile profile-1` - This operation succeeds. It returns the expected Role1 permission set. 
- `aws sts get-caller-identity --profile profile-2` - This operation fails. It returns a `ForbiddenException` error: `An error occurred (ForbiddenException) when calling the GetRoleCredentials operation: No access`.

I do have access to both Role1 and Role2 permission sets when I open the AWS console in a browser tab. I'm only experiencing this error once in a while. I'm sometimes able to access my second role and sometimes can't, without changing anything in my config file. I've tried logging in profiles instead of sessions and create a session for each profile but no luck. Role1 permission set session duration is set to 12h. Role2 permission set session duration is set to 1h. 

### Possible Solution

I suspect there is a delay in the AWS SSO API after a user is provisioned a permission set / role.

### CLI version used

2.11.6

### Environment details (OS name and version, etc.)

MacOs Monterey v12.6 M1 chip

**Comment by tim-finnigan** [comment]
Hi @juliencol thanks for reaching out. Regarding these points:
>I'm only experiencing this error once in a while
...
> I suspect there is a delay in the AWS SSO API after a user is provisioned a permission set / role.

 Can you share more details on this? How long is that delay, and are you able to reproduce the error consistently?

(I saw that you also asked about this [here](https://github.com/aws/aws-cli/issues/6316#issuecomment-1532779203), although since what you're describing is intermittent I'm not sure it entirely relates with what is discussed there.) 

If you're sometimes able to access Role 2 then I don't think there is an issue with your profile configuration. Maybe it's an issue with your Identity Center or permission set sessions expiring? Here is some general info on Identity Center sessions shared in another issue which may help:

> 1. There is Identity Center itself which 8 hours by default but can now be [configured](https://docs.aws.amazon.com/singlesignon/latest/userguide/configure-user-session.html). As long as this session is active, you can assume roles in accounts. Once it expires, you must re-authenticate.
> 
> 2. Permission Set session duration, which is 1 hour by default and also [configurable](https://docs.aws.amazon.com/singlesignon/latest/userguide/howtosessionduration.html). As long as this session is active, you can issue commands in your active session. On the CLI, this will auto-refresh as long as the Identity Center session is active. In the browser, you have to click on the role again to refresh the session.
