### ISSUE TITLE
Cross account encrypted command clarification

### ISSUE THREAD

**Issue by chefren** [aws/aws-cli#7887]
### Describe the issue

When doing cross account operations on encrypted buckets, ([example](https://repost.aws/knowledge-center/cross-account-access-s3)), and since custom KMS is required, the kms related arguments are needed. However, since the KMS lives in the bucket account, the external account will not be able to use the key ID and will only need to set the SSE parameter to `aws:kms`.

### Links

https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

**Comment by tim-finnigan** [comment]
Thanks @chefren for reaching out and creating that PR. I think we'll want to review the proposed wording with the S3 team before proceeding.

**Comment by chefren** [comment]
Thanks @tim-finnigan , on further testing, I still can't use a cross account key directly - since key ID is not enough and would need key ARN. I will edit it to reflect how it can really be done with `cp`.
