### ISSUE TITLE
AWS CLI Access

### ISSUE THREAD

**Issue by mado-bohsali** [aws/aws-cli#7889]
### Describe the issue

Although I have AdministratorAccess permission on IAM, I am not able to perform any command using CLI. I have tried to go through the troubleshooting steps, but failed with no luck.

### Links

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-access-denied

**Comment by RyanFitzSimmonsAK** [comment]
Hi @mado-bohsali, thanks for reaching out.  Giving your IAM role permission doesn't actually configure your credentials for AWS CLI.  I'd recommend reading through [this documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html).  Let me know how that works for you or if you have any follow-up questions.
