### ISSUE TITLE
Add --dry-run option to aws s3api create-bucket

### ISSUE THREAD

**Issue by yugaraxy** [aws/aws-cli#7915]
### Describe the feature

It would be nice to have a --dry-run option for `aws s3api create-bucket` command, which would check the whole command meets the API Specification.

Of course this logic couldn't be guaranteed by the AWS API, but it would helps some usecases.

### Use Case

I write the documentation for our internal operation which needs to create s3 bucket. I want to ensure the command is correct without creating bucket.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.4.9

### Environment details (OS name and version, etc.)

macOS 12.0.1

**Comment by stalinMeso** [comment]
Can some please confirm if the --dryrun flag has been added to s3api delete-objects ? I am still getting "Unknown options: --dry-run" or "Unknown options: --dryrun"
