### ISSUE TITLE
`describe-instance-information` does not have the `AssociationStatus` key anymore

### ISSUE THREAD

**Issue by nth-block** [aws/aws-cli#7924]
### Describe the issue

In the documentation of the v2 CLI, the output for the `aws ssm describe-instance-information` is documented to have the following schema

```json
{
    "InstanceInformationList": [
        {
            "InstanceId": "i-028ea792daEXAMPLE",
            "PingStatus": "Online",
            "LastPingDateTime": 1582221233.421,
            "AgentVersion": "2.3.842.0",
            "IsLatestVersion": true,
            "PlatformType": "Linux",
            "PlatformName": "SLES",
            "PlatformVersion": "15.1",
            "ResourceType": "EC2Instance",
            "IPAddress": "192.0.2.0",
            "ComputerName": "ip-198.51.100.0.us-east-2.compute.internal",
            "AssociationStatus": "Success",
            "LastAssociationExecutionDate": 1582220806.0,
            "LastSuccessfulAssociationExecutionDate": 1582220806.0,
            "AssociationOverview": {
                "DetailedStatus": "Success",
                "InstanceAssociationStatusAggregatedCount": {
                    "Success": 2
                }
            }
        }
    ]
}
````
whereas the CLI (v `2.11.22` and v `2.11.23`) gives this json as the output for the command

```json
{
    "InstanceInformationList": [
        {
            "InstanceId": "i-0eEXAMPLE",
            "PingStatus": "Online",
            "LastPingDateTime": "2023-05-28T00:29:20.719000+05:30",
            "AgentVersion": "3.2.923.0",
            "IsLatestVersion": true,
            "PlatformType": "Linux",
            "PlatformName": "Ubuntu",
            "PlatformVersion": "20.04",
            "RegistrationDate": "2023-05-26T17:14:57.382000+05:30",
            "ResourceType": "EC2Instance",
            "IPAddress": "x.x.x.x",
            "ComputerName": "xxxxxxxx",
            "SourceId": "i-0eEXAMPLE",
            "SourceType": "AWS::EC2::Instance"
        }
    ]
}
````
I believe the documentation needs to be updated as I am not even sure if `AssociationStatus` key is supported at all anymore.

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/describe-instance-information.html

**Comment by nth-block** [comment]
Oddly when I picked this up from over the weekend, the json schema seems to be back to normal (as documented).  Wonder what caused the transient issue.

**Comment by aBurmeseDev** [comment]
Hi @nth-block - thanks for reaching out.

I attempted to reproduce this on `2.11.23` and it returned the `AssociationStatus` in the output as expected. Let us know if it's still missing from your output.

Best,
John

**Comment by nth-block** [comment]
Hello @aBurmeseDev,his can be closed. I saw the weird behaviour over the weekend and ended up building a much more insightful solution using other APIs. This transient issue was a blessing in disguise. 🤣
