### ISSUE TITLE
--no-paginate is ignored for aws s3 cp --recursive

### ISSUE THREAD

**Issue by mdavis-xyz** [aws/aws-cli#7933]
### Describe the bug

My use case is that I want to do `aws s3 cp s3://... ./ --recursive`. But if my prefix in S3 has lots of files (>100) just stop after 100. (Yeah I could write a python script to do this. But I want to keep it simple.)

I can list files with 

```
aws s3api list-objects --bucket mybucket --no-paginate
```

That will limit the output to 1000. (Alternatively I could use `--max-items`)

(Side note: The cli won't let me use both `--no-paginate` and `--page-size`. I should be able to use both, to do the equivalent of `--max-items`.)

[The documentation for `aws s3 cp`](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) does say that `--no-paginate` is supported. However when I try to use it for prefixes with more than 1000 objects (assuming 1000 is the default page size) the cli will download all objects. 

i.e. The documentation says that `--no-paginate` will disable automatic pagination. but I believe this argument is ignored, and automatic pagination will not be disabled.

### Expected Behavior

`aws s3 cp --recursive --no-paginate s3://... ./` (and `mv` and `rm`) will not process more than 1000 files.

### Current Behavior

`aws s3 cp --recursive --no-paginate s3://... ./` processes more than 1000 files.

### Reproduction Steps

```
# generate many files, >1000
for num in {1..2000} ; do touch $num.dat ; done
# upload to S3, no limit
aws s3 mv ./ s3://mybucket/myprefix/ --recursive
# download only some
aws s3 cp s3://mybucket/myprefix/ ./ --recursive --no-paginate
# count number of files
ls | wc -l
```

### Possible Solution

The quick fix is to remove pagination arguments from `aws s3` documentation, if they aren't implemented.

As a longer term solution, I'd like a `--max-items` for `aws s3`.

### CLI version used

aws-cli/2.11.21 Python/3.11.3 Linux/4.14.255-305-242.531.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Cloud Shell (also tested on Mac OS)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @mdavis-xyz, thanks for reaching out.  When you add the `--no-paginate` flag, does the CLI output 1000 lines of text (i.e `download: s3://mybucket/test1.txt to test1.txt`), or does it both process and output more than 1000 files?  Thanks!

**Comment by mdavis-xyz** [comment]
Both.

Running the little script above results in 2000 files being downloaded, and the progress status says up to:

> Completed 1999 files(s) with ~1 file(s) remaining

**Comment by RyanFitzSimmonsAK** [comment]
Hi @mdavis-xyz, thanks for following up.  I'm not sure this is really a bug.  Pagination is typically used in the context of organizing text output, and it doesn't really make sense for pagination to do anything when an actual action (moving files) is taking place.  Removing the pagination parameters from this documentation also doesn't make much sense, because they are global options that *are* accepted by the CLI, it's just a matter of if they do anything.  Operations that use pagination explicitly mention it in the reference guide.

"list-objects-v2 is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results..."

Please let me know if you have any follow-up questions, or if you want to expand on your use case for this.  Thanks!

**Comment by mdavis-xyz** [comment]
I'm not sure why you say pagination doesn't make sense when doing an actual action. `aws s3 cp --recursive` *does* paginate. It calls `list-objects-v2` (or v1?) with pagination, right? How else can it copy more than 1000 files in one go?

> Multiple API calls may be issued in order to retrieve the entire data set of results...

Yep, that's what the `--recursive` flag does.

As an end user I believe that having arguments in the documentation which are ignored does not make sense. Either they should be unignored, or they should be omitted from the docs.

Having some argument which is not documented, but if passed will be ignored, seems like a better outcome than having an argument which is present in the docs but ignored.

> Operations that use pagination explicitly mention it in the reference guide.

I'm not sure what you mean by the "reference guide". I'm talking about the direct documentation itself. `aws s3 cp help`. Are you referring to the single sentence up the top of that page, or some other document?
That documentation *does* explicitly mentions pagination. I don't think it's reasonable to expect end users to somehow know that they should ignore some explicitly documented arguments if they're not mentioned in the description in the documentation for that operation. Most arguments are not mentioned in the preamble of the docs for that API call. 

How can I as an end user generalise this advice, to know which arguments get ignored for any API call?
