### ISSUE TITLE
Ability to configure cloudwatch settings in order to configure cross-account cross-region settings

### ISSUE THREAD

**Issue by sftim** [aws/aws-cli#7946]
### Describe the feature

 There doesn't seem to be a way to configure CloudWatch settings with the AWS CLI. The only way at the moment to configure these settings is manually via the web console.

### Use Case

Managing CloudWatch sharing settings using CloudFormation, Terraform, etc.

### Proposed Solution

Add an API call to CloudWatch to allow managing settings for CloudWatch.

Implement CLI support for that API call.

### Other Information

This issue is similar to https://github.com/aws/aws-cli/issues/5896 which was closed as completed in January 2022 (GitHub has since added a “closed as not planned” status).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.10.1 Python/3.9.11 Linux/6.1.0-1010-oem exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

Ubuntu 22.04, amd64

**Comment by tim-finnigan** [comment]
Thanks @sftim for bringing that feature request back to our attention. I'm going to reopen https://github.com/aws/aws-cli/issues/5896 and follow up there so that others who commented on that issue can stay in the loop.
