### ISSUE TITLE
aws rds describe-reserved-db-instances-offerings is not respecting --no-multi-az parameter

### ISSUE THREAD

**Issue by DaveB93** [aws/aws-cli#7948]
### Describe the bug

if you run 

`aws rds describe-reserved-db-instances-offerings --region us-west-2 --duration 1 --offering-type "All Upfront" --db-instance-class db.t4g.medium --product-description mysql --no-multi-az`  

you get both db instance offerings ( with and without multi-az )

however if you run with --multi-az you only get one entry 

### Expected Behavior

only one entry should be returned

### Current Behavior

`{
    "ReservedDBInstancesOfferings": [
        {
            "ReservedDBInstancesOfferingId": "10880789-951d-4bf8-a52c-8392bddf7371",
            "DBInstanceClass": "db.t4g.medium",
            "Duration": 31536000,
            "FixedPrice": 422.0,
            "UsagePrice": 0.0,
            "CurrencyCode": "USD",
            "ProductDescription": "aurora-mysql",
            "OfferingType": "All Upfront",
            "MultiAZ": false,
            "RecurringCharges": [
                {
                    "RecurringChargeAmount": 0.0,
                    "RecurringChargeFrequency": "Hourly"
                }
            ]
        },
        {
            "ReservedDBInstancesOfferingId": "cd336434-cb59-4348-903e-657d4b4e32f3",
            "DBInstanceClass": "db.t4g.medium",
            "Duration": 31536000,
            "FixedPrice": 379.0,
            "UsagePrice": 0.0,
            "CurrencyCode": "USD",
            "ProductDescription": "mysql",
            "OfferingType": "All Upfront",
            "MultiAZ": false,
            "RecurringCharges": [
                {
                    "RecurringChargeAmount": 0.0,
                    "RecurringChargeFrequency": "Hourly"
                }
            ]
        }
    ]
}
`

### Reproduction Steps

`aws rds describe-reserved-db-instances-offerings --region us-west-2 --duration 1 --offering-type "All Upfront" --db-instance-class db.t4g.medium --product-description mysql --no-multi-az`

### CLI version used

aws-cli/2.11.25 Python/3.11.3 Linux/5.15.90.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

UBUNTU 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tim-finnigan** [comment]
Hi @DaveB93 thanks for reaching out. Could you share your debug logs (with any sensitive info redacted) by adding `--debug` to that command? If there is an issue here then we will need to reroute it to the RDS team as they own the [DescribeReservedDBInstances API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeReservedDBInstancesOfferings.html).

**Comment by DaveB93** [comment]
I will check on this tomorrow at work.

**Comment by DaveB93** [comment]
My apologies on this. I didn't look closely at the results.  it turns out it isn't a case of it not respecting --no-multi-az  but a case of it finding mysql in the product description for both "aurora-mysql" and "mysql".    It doesn't look like I can write my command to only get one result in this case.
