### ISSUE TITLE
Problem with `ecr get-login-password`

### ISSUE THREAD

**Issue by mathieujobin** [aws/aws-cli#7977]
### Describe the bug

I am using Ubuntu locally to push docker images onto ECR.
I recently upgraded my personal workstation from 22.10 to 23.04 which now ship with aws-cli 2.9.19

only then I discovered `ecr get-login` got removed in 2.0
so I ported my script to use `get-login-password` instead

I am piping the password into docker login as recommended.

```
aws_login_pass=$(aws ecr get-login-password --region $AWS_REGION --profile $AWS_CRED_PROFILE)
echo $aws_login_pass | docker login --username AWS --password-stdin $remote_repo
```

And I get a `Login Succeeded` message, but quickly after, I get the message my token is expired and I need to login again.

I could not find a solution, although I search for several hours online. I downgraded to aws-cli 1.x for now, but I see how this can only be temporary

### Expected Behavior

it should just works :tm:

### Current Behavior

```
Error response from daemon: pull access denied for CUSTID.dkr.ecr.REGION.amazonaws.com/project, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.
rake aborted!
```

### Reproduction Steps

```
aws_login_pass=$(aws ecr get-login-password --region us-west-2 --profile ci)
docker login -u AWS -p $aws_login_pass $remote_repo
docker pull image
```

### CLI version used

2.9.19

### Environment details (OS name and version, etc.)

Kubuntu 23.04

**Comment by mathieujobin** [comment]
downgrading to v1.27.51 (from snap) while keeping using `get-login-password` does not work.

reverting to use `ecr get-login` just works out of the box.

if I use v1 with `get-login` and quickly I install v2, I can use `get-login-password` succesfully.

but after a while, v2 is broken again... 

This is my beanstalk docker-rebuild script https://github.com/mathieujobin/beanstalk-docker-deploy/blob/public/docker-rebuild

**Comment by aBurmeseDev** [comment]
Hi @mathieujobin - thanks for reaching out and for your patience while we investigate. 
Here are a few findings and possible causes for AWS CLI v2 and please note that we recommend using the latest version if possible:
- `get-login` command was deprecated starting `v1.17.10`. Use `get-login-password` if you're on `v1.17.10` or later version.
- The authorization token is only valid for 12 hours and it needs to be refreshed every 12 hours.
- When using `docker pull` command, you'll need to specify `aws_account_id` and region as mentioned here in the [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html). 
`docker pull aws_account_id.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:latest`
- In the same [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-pull-ecr-image.html), note the warning 

> If you receive a repository-url not found: does not exist or no pull access error, you might need to authenticate your Docker client with Amazon ECR. For more information, see [Private registry authentication](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html).
- I would also make sure that correct permissions are set for your IAM user to perform this operation. See [docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html).
- A few users [suggested](https://github.com/aws/aws-cli/issues/2351#issuecomment-699699365) that the removal of ~/.docker/config.json file resolved the issue for them. 

I hope one of these resolves the issue and that you find it helpful.
Best,
John

**Comment by mathieujobin** [comment]
@aBurmeseDev 

- `get-login-password` was introduced in 1.17, you've deprecated `get-login` on the same release? anyway...
- 12 hours is plenty, but in my case, it does not work for 1 second. I get an expiration notice immediately after a successful login.
- I do always specify account-id and region on my ecr URL when pulling and pussing
- the user I use to pull and push images to ECR has full admin access
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```
- the authentication is fresh because my script login and immediatly push
- removing `~/.docker/config.json` would not do anything as it only contains tokens to other ecr urls.

**Comment by alexshtin** [comment]
Seems like not very popular problem but I got it too. Installed latest v1 (1.32.56) and did:
```
aws1 ecr get-login --region us-west-2 
```
It gave me `docker login` command with password. I compared it with what v2 (2.13.3) command output:
```
aws ecr get-login-password --region us-west-2 
```
and it is different! Password from aws v1 worked just fine and I managed to pulled ECR image successfully. But what I really don't understand, after I logout from docker and login with v2 password again it also started to work:
```
docker logout <accountid>.dkr.ecr.us-west-2.amazonaws.com
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <accountid>.dkr.ecr.us-west-2.amazonaws.com
docker pull <accountid>.dkr.ecr.us-west-2.amazonaws.com/<repo>:<tag>
```
Imaged pulled!

Thanks, @mathieujobin for the hint/workaround.

**Comment by mathieujobin** [comment]
@alexshtin I'm glad it worked for you... I just had my computer force upgrade my aws-cli to v2 and I still cannot use it to push images... cc: @aBurmeseDev

```
(public) $ sudo docker logout XXX.dkr.ecr.us-east-1.amazonaws.com
Removing login credentials for XXX.dkr.ecr.us-east-1.amazonaws.com
$ aws ecr get-login-password --region us-east-1 --profile PROFXXX | docker login --username AWS --password-stdin XXX.dkr.ecr.us-east-1.amazonaws.com
Login Succeeded
mathieu:beanstalk-deploy :-) (public) $ sudo docker push XXXX.dkr.ecr.us-east-1.amazonaws.com/appname:c2714ee5-202404161511420900
The push refers to repository [XXX.dkr.ecr.us-east-1.amazonaws.com/lm-staging]
61356892fdda: Preparing 
68702664d455: Preparing 
2a26f25b428a: Preparing 
82582fee11b1: Preparing 
383858563cee: Preparing 
445bafce5056: Waiting 
36b7d163cb83: Waiting 
9117ba3628a1: Waiting 
bbb3c55757a4: Waiting 
4feac4ed3540: Waiting 
207a9d454021: Waiting 
5f70bf18a086: Waiting 
d936107c0306: Preparing 
1af69a82c651: Preparing 
d8fe4d374e3c: Preparing 
e748b6538707: Preparing 
6c2459e92a73: Waiting 
2bc1bb6d95ad: Waiting 
9eebeb919e72: Waiting 
32e061e8f035: Preparing 
dff4f326dde9: Waiting 
6e2b713af791: Waiting 
5f5e8260b3f8: Waiting 
8e478c16644d: Waiting 
63ea072d5704: Waiting 
fff9055bdf2e: Waiting 
0b35c5c91607: Waiting 
68a85fa9d77e: Waiting 
no basic auth credentials
```
