### ISSUE TITLE
iotwireless send-data-to-wireless-device fails with resource not found 

### ISSUE THREAD

**Issue by rabarar** [aws/aws-cli#7979]
### Describe the bug

using AWS CLI to send message to device listed in AWS Console results in Resource not found

`aws iotwireless send-data-to-wireless-device --id 6adcc94e-7924-4727-beae-ff0e891d1433 --transmit-mode 0 --payload-data "a2FyaW5hCg==" --wireless-metadata "Sidewalk={Seq=0,MessageType=CUSTOM_COMMAND_ID_NOTIFY}"`

### Expected Behavior

expect to see a sidewalk message sent (although not necessarily received) to the device

### Current Behavior

results in an error:

`An error occurred (ResourceNotFoundException) when calling the SendDataToWirelessDevice operation: Resource not found.`

### Reproduction Steps

`% aws iotwireless send-data-to-wireless-device \
    --id "6adcc94e-7924-4727-beae-ff0e891d1433" \
    --payload-data "SGVsbG8gVG8gRGV2c2lt" \
    --wireless-metadata Sidewalk={Seq=1} \                            
--transmit-mode 0
`

### CLI version used

awscli: stable 2.12.0 (bottled), HEAD installed with `brew`

### Environment details (OS name and version, etc.)

OSX 13.4

**Comment by rabarar** [comment]
Hi Tim,

So a few things:

if I issue the following AWS cli request: i get back a (mostly) correct response:

	 % aws iotwireless list-destinations

 { "DestinationList": [ { "Arn": "arn:aws:iotwireless:us-east-1:248149010411:Destination/TemplateAppDestination2", "Name": "TemplateAppDestination2" } ] }


and when I attempt to send using: 

% aws iotwireless send-data-to-wireless-device --id 6adcc94e-7924-4727-beae-ff0e891d1433 --transmit-mode 0 --payload-data "a2FyaW5hCg==" --wireless-metadata "Sidewalk={Seq=0,MessageType=CUSTOM_COMMAND_ID_NOTIFY}" --region us-east-1

if fails.

If i send from the device, I see the message come through the network back to my laptop, so connectivity is working between the device, gateway, and AWS ...

nordic/sensor {"MessageId":"07c8f925-6129-45cc-9da6-3d95303f5e0c","WirelessDeviceId":"6adcc94e-7924-4727-beae-ff0e891d1433","PayloadData":"Nzg3ODc4","WirelessMetadata":{"Sidewalk":{"CmdExStatus":"COMMAND_EXEC_STATUS_UNSPECIFIED","MessageType":"CUSTOM_COMMAND_ID_NOTIFY","NackExStatus":[],"Seq":3,"SidewalkId":"BFFFFD2E06"}}}


If I’m missing something, let me know.

Best,
Rob

**Comment by rabarar** [comment]
Tim,

I should add for completeness,

on the device on power up I initiate the following sequence

sid init 3
sid start
sid send xxx

before I attempt to send a packet from AWS -> Device

**Comment by tim-finnigan** [comment]
Closing per https://github.com/aws/aws-cli/issues/7980#issuecomment-1595334598.
