### ISSUE TITLE
aws iotwireless list-destinations doesn't return all destinations

### ISSUE THREAD

**Issue by rabarar** [aws/aws-cli#7980]
### Describe the bug

when calling `aws iotwiress list-destinations` only one destination is returned when there are multiple destinations shown in the AWS Console

### Expected Behavior

show all of them maybe :) 

### Current Behavior

only shows the last one added

### Reproduction Steps

`aws iotwireless list-destinations`

### CLI version used

awscli: stable 2.12.0 (bottled), HEAD installed with home-brew

### Environment details (OS name and version, etc.)

OSX 13.4

**Comment by rabarar** [comment]
Definitely the same regions: us-east-1I’ll run it with debug when I return home and send it to you later this afternoon…On Jun 16, 2023, at 4:12 PM, Ryan F. ***@***.***> wrote:﻿
Hi @rabarar, thanks for reaching out.  Could you double check that the region you're using in CLI is the same you're using in console?  If that isn't it, could you provide debug logs?  You can get debug logs by adding --debug to your command, and redacting any sensitive information.  Thanks!

**Comment by rabarar** [comment]
Tim,

Close this ticket (as well as the ticket for  aws iotwireless list-destinations  — it was pulling the wrong profile…  explicitly specifying the profile worked and it sent the message.

might be a great idea to make the —profile flag mandatory to explicitly pull the correct credential given that there are typically multiple profiles in the credentials file…

Best,
Rob

**Comment by tim-finnigan** [comment]
Hi Rob - thanks for following up. I'm glad you were able to get this working. I'll also note for future reference that you could use the `AWS_PROFILE` environment variable or a configuration file to persist which profile you're using across commands. Here is documentation on that: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
