### ISSUE TITLE
"aws ec2 create-instance-connect-endpoint" not available

### ISSUE THREAD

**Issue by ghaering** [aws/aws-cli#7986]
### Describe the bug

Even in the very latest version of the AWS CLI that I get from Cloud Shell (```aws-cli/2.11.27 Python/3.11.3 Linux/4.14.255-314-253.539.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off```), this command is not available. It is supposed to be there since a few releases and it is mentioned in the official documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/create-ec2-instance-connect-endpoints.html

### Expected Behavior

The command is available.

### Current Behavior

The command is not available and cannot be found using ```aws ec2 help```

### Reproduction Steps

Run command from docs:

aws ec2 create-instance-connect-endpoint --region us-east-1 --subnet-id subnet-0123456789example

### CLI version used

aws-cli/2.11.27 Python/3.11.3 Linux/4.14.255-314-253.539.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Linux/4.14.255-314-253.539.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

**Comment by tim-finnigan** [comment]
Hi @ghaering thanks for reaching out. It appears that the [create-instance-connect-endpoint](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-instance-connect-endpoint.html) command was added in 2.12.0 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/5ed5f8768d4f876b80f0c7b6d5fa65ef8692dd99/CHANGELOG.rst?plain=1#L27). Please try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to that version or above and let us know if you're still running into any issues.
