### ISSUE TITLE
rdk upgrade conflicting dependency

### ISSUE THREAD

**Issue by choman** [aws/aws-cli#7994]
### Describe the issue

While using pip to upgrade to the latest rdk (was rule development kit), there becomes a round-robin of conflicting 
dependencies. 

Currently on rdk==0.9 and awcli==1.27.62

When upgrading to rdk==0.15 (latest as of 2023-06-22), it complains that two dependencies versions are conflicting
for awscli
- boto3
- pyyaml

Naturally, one then upgrades awscli to 1.27.158.  This resolves the boto3 issue, however this is where the round-robin
issue begins.

the latest rdk==0.15 requires pyyaml > 6.0
the latest awscli==1.27.158 requires pyyaml <5.5,>=3.10

### CLI version used

1.27.X

### Environment details (OS name and version, etc.)

Ubuntu 23.04

**Comment by RyanFitzSimmonsAK** [comment]
Hi @choman, thanks for reaching out.  Updating the pinned PyYAML version is something that has been requested in the past, and is on the team's radar.  There is both a [tracking issue](https://github.com/aws/aws-cli/issues/5943) and [open PR ](https://github.com/aws/aws-cli/pull/6648) for this.  I'd encourage you to add your use case in one or both of those threads.  In the meantime, the easiest workaround would be to [update to AWS CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html), which does not use PyYAML, so you could use 6.0 to meet the RDK dependency.  Hope that helps, and please let me know if you have any follow-up questions.

**Comment by choman** [comment]
@ryanfitzsimmonsAK 

> Hi @choman, thanks for reaching out. Updating the pinned PyYAML version is something that has been requested in the past, and is on the team's radar. There is both a [tracking issue](https://github.com/aws/aws-cli/issues/5943) and [open PR ](https://github.com/aws/aws-cli/pull/6648) for this. I'd encourage you to add your use case in one or both of those issues. In the meantime, the easiest workaround would be to [update to AWS CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html), which does not use PyYAML, so you could use 6.0 to meet the RDK dependency. Hope that helps, and please let me know if you have any follow-up questions.

Thanks, did not know there was an awscli2.  I will look into it
