### ISSUE TITLE
Page for v1 shows v2 documentation

### ISSUE THREAD

**Issue by snspinn** [aws/aws-cli#8001]
### Describe the issue

I had v1 aws-cli installed and I went to run `aws ec2 describe-key-pairs ----include-public-key` as per the official docs[1]
Got the error:
`Unknown options: --include-public-key`

Despite the warning on the page that I was viewing v1 docs, the instruction are clearly for v2. I can confirm this because:
- The help option on command line gives different output 
- After updating to v2 and the particular flag worked. 

This is misleading to those using/stuck on v1 still.

Version before update: `aws-cli/1.22.34 Python/3.10.6 Linux/5.19.0-45-generic botocore/1.23.34`
Version after update `aws-cli/2.12.3 Python/3.11.4 Linux/5.19.0-45-generic exe/x86_64.ubuntu.22 prompt/off`

### Links

[1] https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-key-pairs.html

**Comment by tim-finnigan** [comment]
Hi @snspinn thanks for reaching out. Version 1.22.34 is quite old, the latest version of v1 is 1.27.160 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1). If you [update](https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-install.html) to a more recent version of v1 then you shouldn't get that `Unknown options: --include-public-key`. Most commands should be consistent between v1 and v2 (you can find more info on migration changes from v1 to v2 [here](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html)).
