### ISSUE TITLE
(short issue description)SSL validation failed for https://oidc.us-west-2.amazonaws.com/client/register [Errno 13] Permission denied

### ISSUE THREAD

**Issue by KishanPatil** [aws/aws-cli#8003]
### Describe the bug

When I tried to configure AWS SSO, it showed me an error. How can I resolve this issue?
I tried multiple ways to uninstalled and install multiple times  but this issue not solved. 

My version is : aws-cli/2.12.1 Python/3.11.3 Windows/10 exe/AMD64 prompt/off

### Expected Behavior

To verify my account, it will open the URL in a web browser.

### Current Behavior

It showing validation failed.

### Reproduction Steps

I tried multiple ways to uninstalled and install multiple times  but this issue not solved. 

### CLI version used

2.12.1

### Environment details (OS name and version, etc.)

Windows 10

**Comment by RyanFitzSimmonsAK** [comment]
Hi @KishanPatil, thanks for reaching out.  Could you provide debug logs of this behavior?  You can get debug logs by adding `--debug` to your command, and redacting any sensitive information.  Thanks!

**Comment by KishanPatil** [comment]
Hello @RyanFitzSimmonsAK I tried this but I can't understand this error. 
Here the errors
urllib3.exceptions.SSLError: [Errno 13] Permission denied
botocore.exceptions.SSLError: SSL validation failed for https://oidc.us-west-2.amazonaws.com/client/register [Errno 13] Permission denied
Traceback (most recent call last):
  File "urllib3\util\ssl_.py", line 402, in ssl_wrap_socket
PermissionError: [Errno 13] Permission denied
urllib3.exceptions.SSLError: [Errno 13] Permission denied

**Comment by KishanPatil** [comment]
Hello @RyanFitzSimmonsAK thanks. It's working nice. Thanks for your help.

**Comment by KishanPatil** [comment]
Hi @RyanFitzSimmonsAK, the issue came from an environment variable. I provided the correct path to AWS_CA_BUNDLE in the user environment variable, and the issue has been resolved.
