### ISSUE TITLE
s3 ls with path give redirect error

### ISSUE THREAD

**Issue by bedge** [aws/aws-cli#801]
aws s3 ls
2014-05-30 07:42:30 me.dev.xx.xx

that's OK

aws s3 ls  s3://me.dev.xx.xx
A client error (PermanentRedirect) occurred when calling the ListObjects operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

not OK

However this works works s3cmd:

%> s3cmd ls  s3://me.dev.xx.xx
                       DIR   ....

Everything is on us-west-1.

**Comment by balthatrix** [comment]
I got the following when I ran
$ aws s3api get-bucket-location --bucket <bucketname>
> None

BTW I'm trying to simply add files to s3 as custom maintenance pages for our site.  When I run 
$ aws s3 ls s3://<bucketname>
I get 
> A client error (PermanentRedirect) occurred when calling the ListObjects operation: The bucket you are > attempting to access must be addressed using the specified endpoint. Please send all future requests > to this endpoint.
Any ideas?

**Comment by jamesls** [comment]
Can you add a `--debug` log output?

**Comment by HouCoder** [comment]
I've resolved this issue by upgrading to latest aws-cli.

**Comment by styk-tv** [comment]
So that was a silly bug. Thanks for the fix. Just a quick question, what version would that translate to against Xenial repos?

```
awscli is already the newest version (1.11.13-1ubuntu1~16.04.0).
```

```
ubuntu@ip-10-99-101-18:/$ aws s3api get-bucket-location --bucket my-super-bucket
{
    "LocationConstraint": null
}
