### ISSUE TITLE
Latest release does not include latest botocore changes

### ISSUE THREAD

**Issue by tjni** [aws/aws-cli#8011]
### Describe the bug

I am experimenting with `urllib3` 2.0.3, which needs at least https://github.com/boto/botocore/pull/2924 in `botocore`. I notice that the latest release 2.12.4 does not contain this commit. Is this expected?

### Expected Behavior

N/A

### Current Behavior

N/A

### Reproduction Steps

N/A

### CLI version used

2.12.4

### Environment details (OS name and version, etc.)

macOS Ventura 13.3.1

**Comment by tim-finnigan** [comment]
Hi @tjni thanks for reaching out. Yes that is expected — the AWS CLI should have consistent service [models](https://github.com/boto/botocore/tree/develop/botocore/data) with botocore, but other changes like this require further review before they would be pulled in. If you're running into a CLI issue related to this can you provide more details on what you're seeing?

**Comment by tjni** [comment]
Hi Tim,

Thank you for clarifying the process. I was confused because I didn't realize the automated sync bumps only applied to the models, but it makes sense once explained.

I am doing unsupported stuff<sup>TM</sup> so I don't expect any additional support. In case it's of interest, I'm exploring bumping urllib3 in the [nixpkgs](https://github.com/NixOS/nixpkgs) package manager. The nix ecosystem might be able to get away with it earlier than the out of the box cloud ecosystem because most people who use nix will also install new versions of Python with new versions of OpenSSL through nixpkgs (or similar places) as well.

I'm going to close this issue as asked and answered :)
