### ISSUE TITLE
`preferences is wrong type`

### ISSUE THREAD

**Issue by yujiri8** [aws/aws-cli#8018]
### Describe the bug

I ran `aws configure sso`, then `aws eks update-kubeconfig --name $cluster --profile $profile`, and got this error message: `preferences is wrong type: <class 'dict'> (Should be <class 'collections.OrderedDict'>)`.

### Expected Behavior

The `eks` command should work. It works with the same procedure for a friend on MacOS, on aws version 1.12.5.

### Current Behavior

I got this error message after running the `aws eks` command. Note that if I run it with the name of a cluster that doesn't exist, it doesn't give me this error, it gives me a normal error about the cluster not existing.

### Reproduction Steps

```
aws configure sso
# complete the SSO process and set $profile to the profile name
# where $cluster is the name of a cluster that exists
aws eks update-kubeconfig --name $cluster --profile $profile
```

### Additional Information/Context

Installed aws-cli from the Alpine package manger.

### CLI version used

1.12.4 and 1.12.6 both have this problem for me

### Environment details (OS name and version, etc.)

Alpine Linux

**Comment by tim-finnigan** [comment]
Hi @yujiri8 thanks for reaching out. The [aws configure sso](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/sso.html) command is only available in v2, and the v1 versions you referenced are very old. (The latest CLI versions are [1.29.0](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1) and [2.12.7](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1)). We recommend using v2 if possible, and installing the CLI per the documentation here: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html. 

If you're still receiving an error after updating, could you share your debug logs (with any sensitive info redacted) by adding `--debug` to the command?

**Comment by yujiri8** [comment]
Sorry, I accidentally wrote 1.x on all the version numbers when I meant to write 2.x.

I will try building the newest version and getting a debug log later.

**Comment by yujiri8** [comment]
Fixed when building from source. This must've been caused by Alpine packaging the wrong version of dependencies.

**Comment by yujiri8** [comment]
I did not because I wasn't sure which package was responsible, and I have very little motivation to effectively contribute to gross corporate software like this, which I would never use voluntarily.

**Comment by mih-kopylov** [comment]
Faced the same issue with
```
aws-cli/2.13.2 Python/3.11.4 Linux/5.10.184-175.731.amzn2.x86_64 source/x86_64.alpine.3 prompt/off
```

It happened when I run `aws eks update-kubeconfig` command second time, the first run of this command succeeds, but the second causes the following error

```
preferences is wrong type: <class 'dict'> (Should be <class 'collections.OrderedDict'>)
```

The solution helped: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html#source-getting-started-install-workflows-alpine

It seems that the alpine package https://pkgs.alpinelinux.org/package/edge/community/x86_64/aws-cli has an incompatible dependency that causes such an issue.

**Comment by slackfan** [comment]
I filed https://gitlab.alpinelinux.org/alpine/aports/-/issues/15133 for the issue. Feel free to improve it or add details.
