### ISSUE TITLE
Cannot get ELBv2 private IP addresses

### ISSUE THREAD

**Issue by darkn3rd** [aws/aws-cli#8020]
### Describe the bug

The command `aws elbv2 describe-load-balancers` will not show the private IP addresses allocated, and only shows an empty list.  The private IP addresses show up in the web console.  There doesn't seem to be a way to get private IP addresses using AWS CLI.  

### Expected Behavior

I expected to get IP addresses back, such as the private IP addresses used by the load balancer.  

### Current Behavior

I expected to have ip addresses populated, but instead I get an empty list:

```json
[
  {
    "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-west-2:XXXXXXXXXXXX:loadbalancer/net/k8s-server-httpd-a74ce7b774/22056bb66765f5ae",
    "DNSName": "k8s-server-httpd-a74ce7b774-22056bb66765f5ae.elb.us-west-2.amazonaws.com",
    "CanonicalHostedZoneId": "Z18D5FSROUN65G",
    "CreatedTime": "2023-07-04T23:29:59.748000+00:00",
    "LoadBalancerName": "k8s-server-httpd-a74ce7b774",
    "Scheme": "internet-facing",
    "VpcId": "vpc-06960b086db652b46",
    "State": {
      "Code": "active"
    },
    "Type": "network",
    "AvailabilityZones": [
      {
        "ZoneName": "us-west-2c",
        "SubnetId": "subnet-036ec48703481886c",
        "LoadBalancerAddresses": []
      },
      {
        "ZoneName": "us-west-2d",
        "SubnetId": "subnet-05920daca437574de",
        "LoadBalancerAddresses": []
      },
      {
        "ZoneName": "us-west-2a",
        "SubnetId": "subnet-0c10abbe92c547dd9",
        "LoadBalancerAddresses": []
      }
    ],
    "IpAddressType": "ipv4"
  }
]
```

### Reproduction Steps

1. Create NLB, for example, on EKS w/ AWS LB Controller
   ```bash
   kubectl create namespace server
   kubectl create deployment httpd --image=httpd --replicas=3 \
     --port=80 --namespace=server
   cat <<EOF | kubectl apply --namespace server -f -
   apiVersion: v1
   kind: Service
   metadata:
     name: httpd
     annotations:
       service.beta.kubernetes.io/aws-load-balancer-type: external
       service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
       service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
   spec:
     externalTrafficPolicy: Local
     ports:
       - port: 80
         targetPort: 80
         protocol: TCP
     type: LoadBalancer
     selector:
       app: httpd
   EOF
   ```
1. Get information about the service
   ```bash
   export MY_LB=$(kubectl get service httpd --namespace server \
     --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
   aws elbv2 describe-load-balancers --region $EKS_REGION \
     --query "LoadBalancers[?DNSName==\`$MY_LB\`]
   ```

### Possible Solution

The private IP addresses should show up for `AvailabilityZones[*].LoadBalancerAddresses`.  

### CLI version used

aws-cli/2.12.1 Python/3.11.4 Darwin/21.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 12.6.3 build 21G419

**Comment by aBurmeseDev** [comment]
Hi @darkn3rd - thanks for reaching out. I attempted to reproduce this behavior but was unable to. 
I reached out to Service API team to get their inputs and will update once I hear back. I would try running the command without `--query` filter as it's filtering the response data. 
Meanwhile, can you provide debug logs as that would give us more insight into investigating further? You could get the logs by appending `--debug` to you command.

**Comment by darkn3rd** [comment]
I did not use `--filter` as I brought this up in a consistent controlled environment, a filter was not needed.
