### ISSUE TITLE
Test failures on Python 3.12

### ISSUE THREAD

**Issue by limburgher** [aws/aws-cli#8031]
### Describe the bug

Build on Fedora rawhide fails due to test failures. Tests work on f38 with Python 3.11.

### Expected Behavior

Tests pass

### Current Behavior

[build.log](https://github.com/aws/aws-cli/files/12016987/build.log)

### Reproduction Steps

Build botocore and boto3, install, build awscli.

### CLI version used

1.29.2

### Environment details (OS name and version, etc.)

Fedora 39, Python 3.12

**Comment by RyanFitzSimmonsAK** [comment]
Hi @limburgher, thanks for reaching out.  We currently only support up to [Python 3.11](https://github.com/boto/botocore/blob/7143f31ba57b9914e6a0cc0b5beec0fa353a10d9/setup.py#L60), but 3.12 pre-release (see: https://github.com/boto/botocore/pull/2967) testing has begun, so I will leave this open for tracking and update you here if anything changes.

**Comment by limburgher** [comment]
Thank you. We already have 3.12 in Fedora rawhide, so if there's even an rough patch you'd like help testing, let me know.

**Comment by hroncok** [comment]
E               AttributeError: 'called_with' is not a valid assertion. Use a spec for the mock if 'called_with' is meant to be an attribute.

That's here:

https://github.com/aws/aws-cli/blob/f169403243718f89a0ef34858a3c92db5527479f/tests/functional/eks/test_kubeconfig.py#L122-L123
https://github.com/aws/aws-cli/blob/f169403243718f89a0ef34858a3c92db5527479f/tests/functional/eks/test_kubeconfig.py#L131-L132
https://github.com/aws/aws-cli/blob/f169403243718f89a0ef34858a3c92db5527479f/tests/functional/eks/test_kubeconfig.py#L139-L141

The method call does nothing in Python 3.11. If it's meant to do nothing, delete it. If it's meant to assert the call happened, change the method name to `assert_called_with`.

**Comment by nateprewitt** [comment]
This was resolved prior to the release of 3.12 but we missed closing this issue. The CLI test suite should be running properly on 3.12 for all releases since October 4th.
