### ISSUE TITLE
SSM requires Instance ID to be 20 characters...

### ISSUE THREAD

**Issue by Hummdis** [aws/aws-cli#8033]
### Describe the bug

When trying to deregister, or any other action with SSM, it requires the length of the Instance ID to be 20 characters.

### Expected Behavior

Accept the older, shorter, 19-character length Instance IDs.

### Current Behavior

Fails with "Invalid Length".

### Reproduction Steps

```
$ aws ssm deregister-managed-instance --instance-id i-0c123456789012345

Parameter validation failed:
Invalid length for parameter InstanceId, value: 19, valid min length: 20
```
I modified the Instance ID for security, but you get the point.

### Possible Solution

Allow AWS CLI to accept the slightly older 19-character Instance IDs.

### Additional Information/Context

This command works when using newer 20-character instance IDs, but for older instances that are shorter, it fails.

### CLI version used

2.13.1

### Environment details (OS name and version, etc.)

openSUSE Leap 15.5 | Python 3.11.4

**Comment by tim-finnigan** [comment]
Hi @Hummdis thanks for reaching out. That constraint is imposed by the SSM [DeregisterManagedInstance API](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_DeregisterManagedInstance.html). I'm not familiar with this API/command but maybe it's expecting the `mi-*` prefix as documented in the [SSM User Guide](https://docs.aws.amazon.com/systems-manager/latest/userguide/managed_instances.html)? If not then we can reach out to the SSM team for further review.
