### ISSUE TITLE
"--no-paginate" option is not working as expected for "route53 list-resource-record-sets" command

### ISSUE THREAD

**Issue by axcawef** [aws/aws-cli#8050]
### Describe the bug

When running a route53 list-resource-record-sets command with only the option "--no-paginate" other than the required "--hosted-zone-id", the returned list is paginated. Whereas if I don't add this option, the output is not paginated.

### Expected Behavior

The expected behavior is when adding the "--no-paginate" option to the route53 list-resource-record-sets command, I should not have a paginated output.

### Current Behavior

When I run the command :
`aws route53 list-resource-record-sets --hosted-zone-id <zone_id> --no-paginate`
At the end of the output, I see:
```    "IsTruncated": true,
    "NextRecordName": "<a_dns_record>.",
    "NextRecordType": "CNAME",
    "MaxItems": "100"
```
Whereas, if I run the same command, without the "--no-paginate" option, I do not get `"isTruncated": True` in the output.

The documentation available [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/route53/list-resource-record-sets.html), states that :

> list-resource-record-sets is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument.

So the current behavior contradicts the documentation.

### Reproduction Steps

Run `aws route53 list-resource-record-sets --hosted-zone-id <zone_id> --no-paginate` on a domain with enough records to reach the pagination limit. The zone where I experienced this issue has 300+ records.

### Additional Information/Context

I am running this version of AWS CLI:
```
aws --version
aws-cli/2.13.2 Python/3.11.4 Darwin/22.5.0 source/arm64 prompt/off
```

### CLI version used

2.13.2

### Environment details (OS name and version, etc.)

MacOS 13.4.1 (c) (22F770820d)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @axcawef, thanks for reaching out.

> When I run the command :
> aws route53 list-resource-record-sets --hosted-zone-id <zone_id> --no-paginate
> At the end of the output, I see:
> 
>     "NextRecordName": "<a_dns_record>.",
>     "NextRecordType": "CNAME",
>     "MaxItems": "100"
> 

I notice you aren't receiving a NextToken, which implies it's not paginating.  If you want it to print all of your records at once, you'll need to set `--max-items` to a value higher than the number of records you have in your hosted zone.

> Whereas, if I run the same command, without the "--no-paginate" option, I do not get "isTruncated": True in the output.

This is because it's paginating, instead of printing a single page of results.  `IsTruncated` becomes true when your command is returning fewer results (including ones in future pages) than exist in your hosted zone.

I might be misunderstanding something, but I think this is working as intended.  Could you clarify the issue a bit?  Thanks!

**Comment by axcawef** [comment]
Hi @RyanFitzSimmonsAK ,

Thank you for your follow-up.

I have tried adding the `--max-items` options, but it seems that the maximum is 300. See for any value set above 300, I have the following:

```
    "IsTruncated": true,
    "NextRecordName": "<dns_record_x>",
    "NextRecordType": "CNAME",
    "MaxItems": "300"
```

When I set it to `200`, I have:

```
    "IsTruncated": true,
    "NextRecordName": "<dns_record_y>",
    "NextRecordType": "CNAME",
    "MaxItems": "200"
```    
    
Note: this zone contains more than 300 records.

This is interesting: when I only use the required option `--hosted-zone-id` for the command `list-resource-record-sets`, I get my entire zone without the 300 max-items limitations. However, if I use `--no-paginate`, the MaxItems is `100`, unless I specify something else with `--max-items`.

The documentation says this: 
```
ListResourceRecordSets returns up to 300 resource record sets at a time in ASCII order, beginning at a position specified by the name and type elements.
```

Isn't this in contradiction with what I experience when I do not set any option?

**Comment by RyanFitzSimmonsAK** [comment]
Hi @axcawef, thanks for following up.  It looks like this particular operation automatically makes more requests to return more results.  It makes these requests 100 at a time (hence why 100 records get returned when you use --no-paginate), or whatever you've set `--page-size` to.  It then makes the request again and again, until you reached `--max-items` or the end of records.  300 is the limit on `--page-size`. not `--max-items`.  I hope that makes sense, let me know if you have any follow-up questions.
