### ISSUE TITLE
aws wafv2 update-web-acl not updating AWSManagedRulesBotControlRuleSet

### ISSUE THREAD

**Issue by shridharMe** [aws/aws-cli#8051]
### Describe the bug

While updating web acl **AWSManagedRulesBotControlRuleSet** we are providing **ManagedRuleGRoupConfig** in our **rule.json** with following configuration
```
"ManagedRuleGRoupConfig" [{ 
 "AWSManagedRulesBotControlRuleSet" :{
      "InspectionLevel" :"TARGETED"
 }
}]
```
We are getting following error

```
Parameter validation failed:
Unknown parameter in Rules[3].Statement.ManagedRuleGroupStatement.ManagedRuleGroupConfigs[0]: "AWSManagedRulesBotControlRuleSet", must be one of: LoginPath, PayloadType, UsernameField, PasswordField 
```
**aws-cli version is 2.4.20**

following awc-cli command is failing

`aws wafv2 update-web-acl --name FMManagedWebACLV2custom_waf_######### --scope CLOUDFRONT --id ########## --rules [file://rules.json](file://rules.json) --default-action Allow={} --visibility-config SampledRequestsEnabled=false,CloudWatchMetricsEnabled=true,MetricName=######### --lock-token ########## --custom-response-bodies [file://responses.json](file://responses.json) --region us-east-1
`

### Expected Behavior

Rule should be updated with `"InspectionLevel" :"TARGETED"`

### Current Behavior

We are getting following error

```
Parameter validation failed:
Unknown parameter in Rules[3].Statement.ManagedRuleGroupStatement.ManagedRuleGroupConfigs[0]: "AWSManagedRulesBotControlRuleSet", must be one of: LoginPath, PayloadType, UsernameField, PasswordField 

### Reproduction Steps

Run following command with rule.json which has **ManagedRuleGRoupConfig** configured with **AWSManagedRulesBotControlRuleSet** `"InspectionLevel" :"TARGETED"`

 

``aws wafv2 update-web-acl --name FMManagedWebACLV2custom_waf_######### --scope CLOUDFRONT --id ########## --rules [file://rules.json](file://rules.json) --default-action Allow={} --visibility-config SampledRequestsEnabled=false,CloudWatchMetricsEnabled=true,MetricName=######### --lock-token ########## --custom-response-bodies [file://responses.json](file://responses.json) --region us-east-1'`
`

### Possible Solution

_No response_

### Additional Information/Context

We have run this with different cli versions e.g. **1.18.217**, **1.22.25** and **2.4.20**  and getting same error.
 

### CLI version used

 2.4.20

### Environment details (OS name and version, etc.)

linux ,windows, macos

**Comment by tim-finnigan** [comment]
Hi @shridharMe thanks for reaching out. Linking some related documentation for reference:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wafv2/update-web-acl.html
* https://docs.aws.amazon.com/waf/latest/APIReference/API_ManagedRuleGroupConfig.html
* https://docs.aws.amazon.com/waf/latest/APIReference/API_AWSManagedRulesBotControlRuleSet.html

I would also expect what you're describing to work, although the CLI version 2.4.20 is still quite old. The latest version is 2.13.3 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). If you're still seeing the issue after updating please share your debug logs (with any sensitive info redacted) by adding `--debug` to your command.
