### ISSUE TITLE
aws-cli doesnt respect `AWS_ENDPOINT_URL` environment variable

### ISSUE THREAD

**Issue by noahehall** [aws/aws-cli#8052]
### Describe the bug

if the AWS_ENDPOINT_URL is not respected by the aws-cli, its difficult to reuse my existing bash functions and aliases when testing with localstack

- [aws environment variable documentation](https://docs.aws.amazon.com/sdkref/latest/guide/settings-reference.html#EVarSettings)

### Expected Behavior

- i can create a named profile targeting a locally running localstack container
- AWS-CLI respects the AWS_ENDPOINT_URL environment variable
- running `aws configure list` doesnt return the `endpoint_url` setting, so i'm assuming this is an issue with aws-cli?

### Current Behavior

- AWS-CLI responds with the following error

```sh
# set the profile
export AWS_PROFILE=localstack

# $ aws sts get-caller-identity
An error occurred (InvalidClientTokenId) 
when calling the GetCallerIdentity operation: 
The security token included in the request is invalid.

$ aws --endpoint-url=$AWS_ENDPOINT_URL sts get-caller-identity
Account: '000000000000'
Arn: arn:aws:iam::000000000000:root
UserId: AKIAIOSFODNN7EXAMPLE
```

## steps to reproduce
- start a localstack container
- setup your ~/.aws/{config,credentials} files

```sh
# config
[profile localstack]
output = yaml
region = us-east-1 
endpoint_url = http://localhost:4566

# credentials
[localstack]
aws_access_key_id=test
aws_secret_access_key=test
```

- export env vars to your shell and test your access

```sh
## setup env vars
export AWS_PROFILE=localstack
export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile localstack)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile localstack)
export AWS_DEFAULT_REGION=$(aws configure get region --profile localstack)
export AWS_ENDPOINT_URL=$(aws configure get endpoint_url --profile localstack)


## fails: AWS_ENDPOINT_URL not respected
aws sts get-caller-identity

## succeeds: only when we set the endpoint-url param
aws --endpoint-url=$AWS_ENDPOINT_URL sts get-caller-identity
```

### CLI version used

aws-cli/2.9.20 Python/3.9.11 Linux/5.19.0-46-generic exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

No LSB modules are available. Distributor ID:	Ubuntu Description:	Ubuntu 22.04.2 LTS Release:	22.04 Codename:	jammy

![image](https://github.com/aws/aws-cli/assets/10324554/aca97020-dd63-4ba0-b60c-cb5bac424bc4)

**Comment by tim-finnigan** [comment]
Hi @noahehall thanks for reaching out. The endpoint URL environment variable was just recently added in 2.13.0 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). Can you try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to 2.13.0+ and let us know if you run into any issues after that?

**Comment by noahehall** [comment]
Thanks @tim-finnigan will try in the morning and report back
