### ISSUE TITLE
documentation for ec2 run-instances needs some improvments.

### ISSUE THREAD

**Issue by buchs** [aws/aws-cli#8058]
### Describe the issue

1) For the --iam-instance-profile argment, the short syntax is given as Arn=...,Name=... . 

But it throws this error:

An error occurred (InvalidParameterCombination) when calling the RunInstances operation: The parameter 'iamInstanceProfile.name' may not be used in combination with 'iamInstanceProfile.arn'

Also, just using Name does not work. So, I am guessing it might be just Arn? Nope, not that either. It seems silly to require both. But whatever is the case the documentation does not match the code. 

Also, the documentation for --block-device-mappings needs help too. The device name must be provided. But, it is not used for Windows. What if we just want to use the default? 

AND, the documentation page has a hyperlink to Do you have a suggestion? [Give us feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Command%20Line%20Interface&hidden_guide_name=Reference}&topic_url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcli%2Flatest%2Freference/ec2/run-instances.html) - is BROKEN.

### Links

https://awscli.amazonaws.com/v2/documentation/api/2.1.21/reference/ec2/run-instances.html

**Comment by RyanFitzSimmonsAK** [comment]
Hi @buchs, thanks for reaching out.  The documentation that you linked is actually for a very old version of the CLI.  The most recent version of that page can be found at https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/run-instances.html, and has a few of these problems fixed already.

> An error occurred (InvalidParameterCombination) when calling the RunInstances operation: The parameter 'iamInstanceProfile.name' may not be used in combination with 'iamInstanceProfile.arn'
> 
> Also, just using Name does not work. So, I am guessing it might be just Arn? Nope, not that either. It seems silly to require both. But whatever is the case the documentation does not match the code.

This parameter now says "The name **or** Amazon Resource Name...", which does reflect that they can't both be used.  Could you clarify what you mean by using just name or ARN does not work?  I'm able to run this command specifying my instance profile using either of those.

> AND, the documentation page has a hyperlink to Do you have a suggestion? [Give us feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=AWS%20Command%20Line%20Interface&hidden_guide_name=Reference%7D&topic_url=https%3A%2F%2Fdocs.aws.amazon.com%2Fcli%2Flatest%2Freference/ec2/run-instances.html) - is BROKEN.

This is fixed on the current version.

> Also, the documentation for --block-device-mappings needs help too. The device name must be provided. But, it is not used for Windows. What if we just want to use the default?

This section also looks pretty different, but might not directly address your concern.  Could you elaborate a bit on what you'd like changed?

**Comment by buchs** [comment]
@RyanFitzSimmonsAK Thanks. My search engine returned the linked to page in response to this search: aws cli ec2. Interestingly, going to the link you provided, I tried to find a higher level URL I could bookmark by stripping off parts of the URL. None of them returned anything but the search page. 

> Could you clarify what you mean by using just name or ARN does not work?

I had been trying an ARN to the role. Once I found the instance profile ARN (hard to find!), it did work with `Arn=<arn>`.  Secondly I found out I was using the instance profile name from the wrong region. So that works too.

> This section also looks pretty different, but might not directly address your concern. Could you take a look at the most recent version and elaborate a bit on what needs improvement?

Well, in general the device names are not actually used - SSDs result in their own unique device names. So I figured out that if I use the device name "/dev/sda1" I can change the drive size of the boot volume. Maybe a few notes on that case would be nice to insert. 

Thanks.

**Comment by Andr1500** [comment]
hello @buchs ,
is it possible to add to the documentation example of usage IamInstanceProfile during the process of creation any ec2 instance ? I need to be sure how I can use it in my SSM automation document with "aws:runInstances" action. many thanks

**Comment by RyanFitzSimmonsAK** [comment]
> hello @RyanFitzSimmonsAK , is it possible to add to the documentation example of usage IamInstanceProfile during the process of creation any ec2 instance ? I need to be sure how I can use it in my SSM automation document with "aws:runInstances" action. many thanks

Hi @Andr1500, sorry for the late reply on this.  You can add an instance profile during instance creation by using the `--iam-instance-profile` parameter of `[run-instances](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/run-instances.html)`, and attaching an existing IAM role.
