### ISSUE TITLE
Plugin support plans

### ISSUE THREAD

**Issue by pzybe** [aws/aws-cli#8064]
### Describe the feature

I was looking at v1/v2 and saw that support for plugins was removed https://github.com/aws/aws-cli/issues/4650 and https://github.com/aws/aws-cli/pull/4670 because of constraints with the packaged python environment.  I was wondering if any consideration had been given towards adding plugin support back in?

### Use Case

`~/.aws/cli/alias` works for 99% of things, but there are a few scenarios where having the ability to add functionality from a python module plugin is nice.

if I have something like:
```bash
set-profile =
  !f() {
    export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "$1")
    export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile "$1")
    # ...
  }; f
```
Those environment variables won't be available, I think because Python's `subprocess.call` runs in a `SUBSHELL`.
https://github.com/aws/aws-cli/blob/3b93822ec03b2249ef8148e739c3883e0fccde84/awscli/alias.py#L252-L253
There are other ways to accomplish that alias but you get the limitation.  It's also nice to have access to the session object as well for calling out to 3rd-party integrations that expect some kind of credentials to be present.

### Proposed Solution

If the reason that plugins were disabled is because `v2` ships with an isolated environment the only thing I could think would be either allow somebody to just build the tool as if they were developing but with the ability to build in plugins.  Either that or provide some sort of shim over the top of venv if that is how the environment is being isolated.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.3 Python/3.11.4 Linux/6.4.5-arch1-1 exe/x86_64.arch prompt/off

### Environment details (OS name and version, etc.)

6.4.5-arch1-1 GNU/Linux

**Comment by tim-finnigan** [comment]
Hi @ptdel thanks for reaching out. Mentioned in https://github.com/aws/aws-cli/issues/4650#issuecomment-582609291 is this PR: https://github.com/aws/aws-cli/pull/4854, which added a `cli_legacy_plugin_path` setting that you can use. Here is the documentation on that: https://awscli.amazonaws.com/v2/documentation/api/latest/topic/config-vars.html

But please note the warning on that page: 
>Plugin support in the AWS CLI v2 is completely provisional and intended to help users migrate from AWS CLI v1 until a stable plugin interface is released. There are no guarantees that a particular plugin or even the CLI plugin interface will be supported in future versions of the AWS CLI v2. If you are relying on plugins, be sure to lock to a particular version of the CLI and test functionality of your plugin when you do upgrade.

There are plans to support a more comprehensive plugin interface for v2 but we don't have a specific timeline for that. This also overlaps with an older issue, https://github.com/aws/aws-cli/issues/2350, so I think we should continue to track the request there. You can add a 👍 to that issue and comment there if you want to show support for this feature request.

**Comment by ptdel** [comment]
thanks for pointing out the legacy path config @tim-finnigan I'd managed to overlook it.  That solves my problem!
