### ISSUE TITLE
Broken link on CLI v2 ECS execute-command page

### ISSUE THREAD

**Issue by jbma2z** [aws/aws-cli#8066]
### Describe the issue

Broken link at bottom of page for page URI as htm:
`<p>For more information, see <a class="reference external" href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.htm">Using Amazon ECS Exec for debugging</a> in the <em>Amazon ECS Developer Guide</em>.</p>`

should be updated to html:
`<p>For more information, see <a class="reference external" href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html">Using Amazon ECS Exec for debugging</a> in the <em>Amazon ECS Developer Guide</em>.</p>`

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/execute-command.html

**Comment by RyanFitzSimmonsAK** [comment]
Hi @jbma2z, thanks for reaching out.  That link seems to be working fine for me, and it takes me to the ECS Developer Guide as intended.  Is the concern specifically with using `.htm` rather than `.html`, or is the link actually not working for you?  Thanks!

**Comment by fincd-aws** [comment]
The link is broken, it redirects to the service docs homepage (Welcome.html)

Fix https://github.com/aws/aws-cli/pull/8067

**Comment by RyanFitzSimmonsAK** [comment]
Ah, I see.  I've raised the issue with our documentation team, thanks for pointing this out.
