### ISSUE TITLE
SSL validation error with unrecognised domain

### ISSUE THREAD

**Issue by loozhengyuan** [aws/aws-cli#8069]
### Describe the bug

When running `aws sso login`, I encountered SSL validation error but the error message seems to be validating the url to `pink.cat`, which is quite odd. I was not using any VPN, proxy, or under any corporate network.

### Current Behavior

```console
$ aws sso login

SSL validation failed for https://oidc.ap-southeast-1.amazonaws.com/device_authorization hostname 'oidc.ap-southeast-1.amazonaws.com' doesn't match either of 'pink.cat', '*.pink.cat'
```

### Reproduction Steps

Unfortunately, this was only happened once and **I am no longer able to reproduce it**; the `aws sso login` command worked as expected when I tried again.

### CLI version used

aws-cli/2.13.3 Python/3.11.4 Darwin/22.5.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

**Comment by tim-finnigan** [comment]
Hi @loozhengyuan thanks for reaching out. SSL validation errors often indicate an issue with certificate configuration. There is a section on the AWS CLI troubleshooting guide on this topic: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-troubleshooting.html#tshoot-certificate-verify-failed. 

Since this issue happened once and you cannot reproduce it, it may have been caused by some kind of network glitch or DNS caching. If you encounter it again please let us know and share your debug logs (with sensitive info redacted) by adding `--debug` to the command.

**Comment by Nunn4577** [comment]
I'll try to fix this. I'm a rookie, but deeply involved with learning.

**Comment by robbytx** [comment]
FWIW I just encountered a similar issue today, where the AWS CLI returned the error:

> SSL validation failed for https://oidc.us-east-2.amazonaws.com/device_authorization hostname 'oidc.us-east-2.amazonaws.com' doesn't match '*.supplycopia.com'

I similarly am not using any VPN, proxy, or corporate network.  Just a direct connection to the internet via my residential ISP.

**Comment by Dhouti** [comment]
This was observed also occurring with `*.ontrack.global`.
```
SSL validation failed for https://oidc.us-west-2.amazonaws.com/device_authorization hostname 'oidc.us-west-2.amazonaws.com' doesn't match '*.ontrack.global'
```
All of the domains in this thread appear to have or had ACM certs. 
Something somewhere needs fixing.

**Comment by DivineGordon** [comment]
I had the same issue. I have no idea what any of those domains are

```
SSL validation failed for https://oidc.us-west-2.amazonaws.com/device_authorization hostname 'oidc.us-west-2.amazonaws.com' doesn't match either of '*.trilogy.2u.com', '*.stg.trilogy.2u.com', '*.prod.trilogy.2u.com', '*.dev.trilogy.2u.com', '*.uat.trilogy.2u.com'
```
