### ISSUE TITLE
expiresAt attributes still 1 hour even after setting it to 4 on IAM ic

### ISSUE THREAD

**Issue by agennari** [aws/aws-cli#8073]
### Describe the bug

I'm using AWS CLI to auth my developer on AWS environment with aws sso login.
When they auth trough this command, they are able to use services.

I set the session duration to 4 hour but the expiresAt (on .aws/sso/cache/*.json) attribute still at +1 hour...

### Expected Behavior

The expiresAt attributes have to be +4 hour

### Current Behavior

The expiresAt attribute is set to +1 hour

### Reproduction Steps

1. Install AWS CLI
2. Setup IAM Identity Center and create 1 user
3. Create a permission set and set the session duration to 4 hour
4. Check if expiresAt attribute is set to +4 after aws sso login command

### CLI version used

2.13.4

### Environment details (OS name and version, etc.)

WSL Debian 11

**Comment by agennari** [comment]
@RyanFitzSimmonsAK Hi, do you have any idea of whats happening? 
Thanks a lot!

**Comment by rajiv-sah** [comment]
+1

**Comment by RyanFitzSimmonsAK** [comment]
Hi @agennari and @rajiv-sah, thanks for reaching out.  [Here](https://docs.aws.amazon.com/singlesignon/latest/userguide/authconcept.html) is the documentation that might explain this and a [GitHub issue](https://github.com/aws/aws-cli/issues/7104) referring to the same behavior.  

> There are two types of authentication sessions maintained by IAM Identity Center: one to represent the users’ sign in to IAM Identity Center, and another to represent the users’ access to IAM Identity Center enabled applications, such as Amazon SageMaker Studio or Amazon Managed Grafana. Each time a user signs in to IAM Identity Center, a sign in session is created for the duration configured in Identity Center, which can be up to 7 days. For more information, see [Manage IAM Identity Center integrated application sessions](https://docs.aws.amazon.com/singlesignon/latest/userguide/manage-app-session.html). Each time the user accesses an Identity Center enabled application, the IAM Identity Center sign in session is used to obtain an IAM Identity Center application session for that application. IAM Identity Center application sessions have a refreshable 1-hour lifetime – that is, IAM Identity Center application sessions are automatically refreshed every hour as long as the IAM Identity Center sign in session from which they were obtained is still valid. When the user uses IAM Identity Center to access the AWS Management Console or CLI, the IAM Identity Center sign in session is used to obtain an IAM session, as specified in the corresponding IAM Identity Center permission set (more specifically, IAM Identity Center assumes an IAM role, which IAM Identity Center manages, in the target account).

So, the `expiresAt` in the .json file you were looking at is referring to the one hour, refreshable credentials, while the permission set duration is the overall time that a session can exist.  That value can be checked by looking at the role in IAM and checking the `Maximum session duration`.  Hope that helps, please let me know if you have any follow-up questions!
