### ISSUE TITLE
ECS execute-command failed due to an internal error (aws/aws-cli/issues/6834)

### ISSUE THREAD

**Issue by istvanfedak-nbcu** [aws/aws-cli#8080]
### Describe the bug

Related issues:
- https://github.com/aws/aws-cli/issues/6562
- https://github.com/aws/aws-cli/issues/6834
- https://github.com/aws/amazon-ssm-agent/issues/435
- https://github.com/aws-containers/amazon-ecs-exec-checker/issues/47

Unable to run `aws ecs execute-command`.

### Expected Behavior

Open an interactive shell with the container.

### Current Behavior

An error occurred (TargetNotConnectedException) when calling the ExecuteCommand operation: The execute command failed due to an internal error. Try again later.

### Reproduction Steps

1. Make sure that your ECS task execution role has all the required configuration defined in: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html
2. Run:
aws ecs execute-command \
    --cluster MyCluster \
    --task arn:aws:ecs:us-east-1:123456789012:task/MyCluster/d789e94343414c25b9f6bd59eEXAMPLE \
    --container MyContainer \
    --interactive \
    --command "/bin/sh"

### Additional Information/Context

I was able to run `aws ecs execute-command` last week and it stopped working today.
- Amazon ECS-optimized Amazon Linux 2 AMI used in ECS clusters: ami-0507dff4275d8dd6d

### CLI version used

aws-cli/2.11.20 Python/3.11.3 Darwin/20.6.0 source/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS v11.7.8

**Comment by istvanfedak-nbcu** [comment]
I tested the ECS containers that are running on AWS Fargate and they're not affected by this issue (I'm able to open a shell with them).

**Comment by istvanfedak-nbcu** [comment]
## Workaround:
1. Connect to EC2 instance via Session Manager.
2. List out all the containers running in the EC2 instance: `sudo docker ps`.
3. Run the following command to open up a shell with the desired container: `sudo docker exec --interactive --tty <container-id-value> sh`

**Comment by tim-finnigan** [comment]
Hi @istvanfedak-nbcu thanks for reaching out. Can you confirm that the permissions you are using have not changed recently? In this [troubleshooting post](https://repost.aws/knowledge-center/ecs-error-execute-command) for `TargetNotConnectedException` it notes:

>You might get this error due to the following reasons:
>
>    * The Amazon ECS task role doesn't have the required permissions to run the [execute-command](https://docs.aws.amazon.com/cli/latest/reference/ecs/execute-command.html) command.
>    * The AWS Identity and Access Management (IAM) role or user that's running the command doesn't have the required permissions.

This may be a better issue to track in https://github.com/aws-containers/amazon-ecs-exec-checker/issues/47 or the SSM agent repository (https://github.com/aws/amazon-ssm-agent/issues). 

Have you tried updating to a newer version of the SSM Agent? Here are the release notes for reference: https://github.com/aws/amazon-ssm-agent/blob/mainline/RELEASENOTES.md

**Comment by jgasyna** [comment]
Ok holy crap, I found the issue, apparently the execute-command parameter order is important, make sure you run --interactive as the LAST flag:


--command "/bin/sh" \
--interactive


This worked for me...
