### ISSUE TITLE
Update flit-core to 3.9.0

### ISSUE THREAD

**Issue by tjni** [aws/aws-cli#8081]
### Describe the feature

Would it be possible to merge https://github.com/aws/aws-cli/pull/7912?

The release notes for flit-core are here: https://flit.pypa.io/en/latest/history.html#version-3-9

### Use Case

I work on packaging in [nixpkgs](https://github.com/NixOS/nixpkgs), and we carry only the latest version of Python packages. Since the linked PR from Dependabot has been open for several months, I felt it was reasonable to use an issue to ask for an update.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

N/A

### Environment details (OS name and version, etc.)

N/A

**Comment by tjni** [comment]
That PR also needs to update the constraints specified in `pyproject.toml` too.

**Comment by tim-finnigan** [comment]
Thanks @tjni for the feature request. The team is planning to review dependabot PRs like https://github.com/aws/aws-cli/pull/7912 as bandwidth allows. We will want to review the version history of these dependencies to ensure that no breaking changes get introduced to the AWS CLI. In the meantime others can 👍 this issue to help inform prioritization efforts.

**Comment by tjni** [comment]
Thank you for the reply. I hope the team can get to it soon.
