### ISSUE TITLE
Session Manager does not provide support to the parameter reason

### ISSUE THREAD

**Issue by vdyalex** [aws/aws-cli#8082]
### Describe the issue

The documentation of the Session Manager specifies the parameter `reason`:

> `--reason (string)`: The reason for connecting to the instance. This value is included in the details for the Amazon CloudWatch Events event created when you start the session.

However, this command is not recognized using the AWS CLI `v2.0.10` on Mac (`Darwin/23.0.0`):

```bash
$ aws --version
aws-cli/2.0.10 Python/3.7.4 Darwin/23.0.0 botocore/2.0.0dev14
```

The result is:
![CleanShot 2023-08-05 at 18 38 35@2x](https://github.com/aws/aws-cli/assets/1559784/838fa5f4-dc36-49d8-8d8f-a243e56914c2)

The option is omitted from the manual:
![CleanShot 2023-08-05 at 18 48 12@2x](https://github.com/aws/aws-cli/assets/1559784/cab8b962-b31b-47ce-a6f3-ac43b890a4e6)

The most important is **where we can find the parameter `reason`**.

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/start-session.html

**Comment by tim-finnigan** [comment]
Hi @vdyalex thanks for reaching out. 2.0.10 is a very old version of the AWS CLI. The latest version is 2.13.7 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). Can you try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to a more recent version and running that command again?

**Comment by vdyalex** [comment]
Thanks for clarifying it, @tim-finnigan. I was trying to upgrade the AWS CLI via Brew but they dropped the support. Then I had to install via GUI installer. Now it's working well.
