### ISSUE TITLE
does not consider IPv6 endpoints by default

### ISSUE THREAD

**Issue by apparentorder** [aws/aws-cli#8084]
### Describe the bug

Awscli does not automatically and by default consider IPv6 to access API endpoints that are dual stack-enabled.

Only by adding `--endpoint` it will ever use IPv6, even if IPv4 connectivity is not available.

While this could be seen as a feature request, I'd argue that the general expectation is that dual-stack generally Just Works™ when either or both protocols are available. In any IPv6-only deployment, this will certainly cause significant customer frustration until the cause is understood.

Unless awscli (and the SDKs) starts using IPv6 when available, it will be highly impractical to complete any IPv6 migration, as locating and changing every use of awscli is tedious and error-prone (if possible at all).

### Expected Behavior

Awscli can, without additional configuration or arguments, utilize IPv6 on dual-stack enabled API endpoints.

### Current Behavior

Awscli does not ever use IPv6, unless specifically instructed to do so for each invididual AWS API.

### Reproduction Steps

/usr/local/bin/aws --region eu-west-1 ec2 describe-addresses

... does not even try to IPv6, even though ec2@eu-west-1 offers a dual stack endpoint, even when local IPv4 connectivity is not available.

### Possible Solution

use ipv6 when appropriate

### Additional Information/Context

AWS has done some great work to bring IPv6 adoption forward, on AWS and in general, and should continue to be a role model.

### CLI version used

aws-cli/2.13.7 Python/3.11.4 Linux/4.14.291-218.527.amzn2.aarch64 exe/aarch64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

al2/arm

**Comment by tim-finnigan** [comment]
Hi @apparentorder thanks for reaching out. In regard to your request to enforce IPv6 by default, this is not something that the AWS CLI can control. The underlying IP is chosen at DNS resolution. For more context on this you can refer to this documentation: https://docs.aws.amazon.com/whitepapers/latest/ipv6-on-aws/designing-dns-for-ipv6.html

In terms of dual-stack endpoints you can configure the default behavior for the CLI/SDKs as documented here: https://docs.aws.amazon.com/sdkref/latest/guide/feature-endpoints.html. And support for dual-stack/IPv6 is on a per-service basis: https://docs.aws.amazon.com/vpc/latest/userguide/aws-ipv6-support.html#ipv6-service-support

**Comment by apparentorder** [comment]
> The underlying IP is chosen at DNS resolution

Yes, but this doesn't apply here, as AWS API endpoints use different host names.

> https://docs.aws.amazon.com/sdkref/latest/guide/feature-endpoints.html

Ouch. I googled quite a bit, but somehow managed to miss this. Thank you! This already helps.

But:

> If a dual-stack endpoint does not exist for the service and/or AWS Region, the request will fail.

Which means that I cannot just use this as a default setting.

So to re-frame this as feature request(s):

- awscli & SDKs should be aware of which services actually have dual-stack endpoints, instead of blindly synthesizing the `.api.aws` address, possibly causing an error, and

- or at least: `use_dualstack_endpoint` should fall back to using the "normal" endpoint when the dual-stack endpoint connection fails

- `use_dualstack_endpoint` should then be the default setting (I agree this could cause some trouble, so maybe this needs to wait for a new major version)

IPv6 really needs to become the default mode of operation if we ever want to leave IPv4 behind.

Thanks!

**Comment by tim-finnigan** [comment]
Thanks @apparentorder for following up. I do want to highlight that starting in Botocore [1.28.0](https://github.com/boto/botocore/blob/639134f47e07e44128b1f0b9385e15118dc651dc/CHANGELOG.rst?plain=1#L2220C3-L2220C21) there were `endpoint-rule-set-1.json` files added for services (for example: [ec2](https://github.com/boto/botocore/blob/develop/botocore/data/ec2/2016-11-15/endpoint-rule-set-1.json)) which contain a `UseDualStack` value. So this logic is determined on a per-service basis. But we can also reach out to service teams with customer feedback for requests related to this.

**Comment by apparentorder** [comment]
Thanks again! This looks interesting, but I'm not sure I understand that mechanism correctly. As I read the ec2 rule-set (and several others I've checked), it currently only implements the UseDualStack (and FIPS) parameter while checking if the target *partition* supports DualStack at all. But nothing region-specific, so it does not prevent failure e.g. when requesting the dual-stack endpoint of ec2 in, say, eu-central-1 (where ec2 doesn't support dualstack), right? At least in my tests that fails.

By the way, I recently learned that a handful of AWS services (<10) actually do provide dual-stack functionality on the *default* endpoint – some in addition to a separate dual-stack endpoint, some not.

This leads to the weird situation that using `AWS_USE_DUALSTACK_ENDPOINT` on an IPv6-only client would cause some awscli commands to fail that work fine *without* that setting (e.g. `rds pi ...`). It's all rather inconsistent, so I'm not really sure what the best way forward would be.

I guess the proper solution would be for all services to follow the example of those few services and enable IPv6 on the *default* endpoint, too. That would get rid of all the extra config and variations, and it would align well with common expectations. But that's not an awscli issue, of course. And I'm not even sure whom I'd have to address that request to :-)

As that doesn't seem realistic soon, maybe some config setting to better control the behavior makes sense, with modes like "only try default endpoint" and "try dualstack first, with fallback to default endpoint" and "try default endpoint first, with fallback to dualstack endpoint". That would make sense in an IPv6-only VPC and is comparatively easy to configure as default for awscli and SDKs.

**Comment by tim-finnigan** [comment]
Thanks for following up. It does sound like what you're requesting is beyond the scope of the AWS CLI. For feature requests involving things like configuration settings, I recommend creating an issue in our cross-SDK repository (https://github.com/aws/aws-sdk). Requests involving specific services would need to get escalated to those individual service teams. We recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for those kinds of requests if you have a support plan, otherwise we can forward them to service teams on your behalf.
