### ISSUE TITLE
Network interfaces and an instance-level subnet ID may not be specified on the same request

### ISSUE THREAD

**Issue by brdude** [aws/aws-cli#809]
When I run this command:
[user@localhost provision]$ aws ec2 run-instances --image-id ami-1234abcd --subnet-id subnet-abcd1234 --security-group-ids sg-499exxxx sg-439exxxx  --instance-type m1.small  --key-name opskey --private-ip-address 10.x.x.100 --secondary-private-ip-addresses 10.x.x.200

I get the following:
A client error (InvalidParameterCombination) occurred when calling the RunInstances operation: Network interfaces and an instance-level subnet ID may not be specified on the same request

pip packages installed.
[user@localhost provision]$ pip-python3 list installed
awscli (1.3.15)
bcdoc (0.12.2)
Beaker (1.5.4)
botocore (0.49.0)
Brlapi (0.6.0)
colorama (0.2.5)
docutils (0.11)
jmespath (0.4.1)
Mako (0.7.3)
MarkupSafe (0.18)
pip (1.4.1)
pyasn1 (0.1.7)
pygobject (3.10.2)
python-dateutil (2.2)
rsa (3.1.2)
setuptools (1.4.2)
six (1.6.1)

**Comment by jamesls** [comment]
Consolidating issues here.  This is the same error message/root cause as: https://github.com/aws/aws-cli/issues/613.  Tracking this issue in #613
