### ISSUE TITLE
unable to run 'aws autoscaling update-auto-scaling-group' with config containing MixedInstancesPolicy overrides

### ISSUE THREAD

**Issue by dss010101** [aws/aws-cli#8097]
### Describe the bug

Trying to execute the CLI command provided here: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-mixed-instances-groups-launch-template-overrides.html

This fails on the command line with the following error:
`
Unknown parameter in MixedInstancesPolicy.LaunchTemplate.Overrides[0]: "LaunchTemplateSpecification", must be one of: InstanceType, WeightedCapacity`

### Expected Behavior

Should work if the documentation is accurate

### Current Behavior

fails with error:
Unknown parameter in MixedInstancesPolicy.LaunchTemplate.Overrides[0]: "LaunchTemplateSpecification", must be one of: InstanceType, WeightedCapacity`

### Reproduction Steps

execute: 

`aws autoscaling create-auto-scaling-group --cli-input-json file://~/config.json`

With the json specified:
```
{
  "AutoScalingGroupName":"my-asg",
  "MixedInstancesPolicy":{
    "LaunchTemplate":{
      "Overrides":[
        {
          "InstanceType":"c6g.large",
          "LaunchTemplateSpecification": {
            "LaunchTemplateName": "my-launch-template-for-arm",
            "Version": "$Latest"
          }
        },
        {
          "InstanceType":"c5.large"
        },
        {
          "InstanceType":"c5a.large"
        }
      ]
    }
  }
}
```

### CLI version used

aws-cli/2.0.62 Python/3.7.7 Windows/10 exe/AMD64

### Environment details (OS name and version, etc.)

Windows 11

**Comment by nateprewitt** [comment]
Hi @dss010101,

aws-cli/2.0.62 is ~3 years old and does not support newer features like `LaunchTemplateSpecification`. We'd recommend [updating to a recent release](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) (currently 2.13.9) to access new features and patch existing security issues in your current version.

**Comment by dss010101** [comment]
That was the issue @nateprewitt . i was under the impression vscode would might have kept that up-to-date with its aws toolkit extension. not the case.
Thank you
