### ISSUE TITLE
feat:  aws stepfunctions get-execution

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws/aws-cli#8123]
### Describe the feature

In the context of an intelligent document processing pipeline, there is a need to retry failed step function executions. 

The current process involves listing all executions using the ListExecutions API and then iterating through them to find the specific execution by name or ID. This can lead to throttling issues and is not efficient, especially when dealing with a large number of executions.

### Use Case

The use case involves an automated process where documents are processed through various steps, including OCR, text extraction, and writing to a database. 

If a step function execution fails, it needs to be retried with the original input, after the downstream lambda has been patched.

Currently, to retrieve the input of a specific execution, one must call the ListExecutions API and filter through the results, which can be cumbersome and prone to errors/ throttling. 

### Proposed Solution

Introduce a new command in the AWS CLI for Step Functions called GetExecution. This command would allow users to retrieve details of a specific execution by providing either the name or ID of the execution.

```
aws stepfunctions get-execution --execution-name <execution-name> --state-machine-arn <state-machine-arn>
```

or 

```
aws stepfunctions get-execution --execution-id <execution-id> --state-machine-arn <state-machine-arn>
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

1.29.31

### Environment details (OS name and version, etc.)

Cloud9

**Comment by tim-finnigan** [comment]
Hi @MichaelWalker-git thanks for the feature request. The AWS CLI `stepfunctions` [commands](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/stepfunctions/index.html) map to the Step Functions [service APIs](https://docs.aws.amazon.com/step-functions/latest/apireference/API_Operations.html), so API feature requests would get forwarded to the Step Functions team. But in this case it seems like the [describe-execution](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/stepfunctions/describe-execution.html) command might already address your use case, as `input` is part of the [response syntax](https://docs.aws.amazon.com/step-functions/latest/apireference/API_DescribeExecution.html#API_DescribeExecution_ResponseSyntax). Can you confirm if that helps with what you're trying to do?
