### ISSUE TITLE
AWS-CLI v2 installs per default in /usr/local/aws-cli which isn't a valid directory according to FHS

### ISSUE THREAD

**Issue by dmarinuswoodwing** [aws/aws-cli#8128]
### Describe the bug

[FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) describes only the following directories in /usr/local:
```
bin	Local binaries
etc	Host-specific system configuration for local binaries
games	Local game binaries
include	Local C header files
lib	Local libraries
man	Local online manuals
sbin	Local system binaries
share	Local architecture-independent hierarchy
src	Local source code
```

### Expected Behavior

Install aws-cli in /opt/aws-cli as an add-on application software package:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s13.html

### Current Behavior

AWS-CLI is installed per default in /usr/local

### Reproduction Steps

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

### Possible Solution

Install in /opt/aws-cli, create symlinks in /usr/local/bin

### CLI version used

v2

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Hi @dmarinuswoodwing thanks for reaching out. This has come up a couple times before (see https://github.com/aws/aws-cli/issues/4660 and https://github.com/aws/aws-cli/issues/7239). As mentioned in those issues, you can control where the install dir lives using the `-i` parameter. For example:
```
$ ./install -i /opt/aws-cli
```
It would be a breaking change at this point to update the default install directory, so I don't think this is something that would likely get prioritized by the team.
