### ISSUE TITLE
list-object-versions --page-size and --max-items ignored for DeleteMarkers

### ISSUE THREAD

**Issue by deneb42** [aws/aws-cli#8131]
### Describe the bug

When calling
`aws s3api list-object-versions --bucket <bucket>`
with `--max-items` or `--page-size` (or both) those parameters are correctly respected for returned Versions but not for returned DeleteMarkers.

For instance, 
`aws s3api list-object-versions --bucket <bucket> --max-items 5`

Could return 5 Versions, followed by a far greater nomber of DeleteMarkers (not necessarily linked to the same items present in Versions).

This makes the call very slow and consume a lot of bandwidth for nothing, especially when emptying a bucket with a lot of entries before deleting it. 

### Expected Behavior

`aws s3api list-object-versions --bucket <bucket> --max-items 5`
or 
`aws s3api list-object-versions --bucket <bucket> --page-size 5`

Should return at most 5 Versions and 5 DeleteMarkers

### Current Behavior

`aws s3api list-object-versions --bucket <bucket> --max-items 5`
or 
`aws s3api list-object-versions --bucket <bucket> --page-size 5`

Return at most 5 Versions,
but will return way more than 5 DeleteMarkers

Also, I'm not sure that the --starting-token option is usable for the DeleteMarkers

### Reproduction Steps

1. Create a bucket <bucket> with versionning activated
2. Add ~10 items to the bucket, and then delete them
3. `aws s3api list-object-versions --bucket <bucket> --max-items 5`
or 
`aws s3api list-object-versions --bucket <bucket> --page-size 5`

4. Notice that there is 5 versions of the items, but more than 5 DeleteMarkers

### Possible Solution

Limit the quantity of DeleteMarkers returned to the value set by `--max-items` or `--page-size`

### CLI version used

aws-cli/2.13.9 Python/3.11.4 Linux/4.14.255-314-253.539.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off
and 
aws-cli/2.2.45 Python/3.8.8 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

AWS CloudShell 
and
Windows 10 64 bits

**Comment by RyanFitzSimmonsAK** [comment]
Hi @deneb42, thanks for reaching out.  This is known behavior for operations with multiple paginatable keys in the top level of the response.  There are a couple ways you can work around this.

You can use the `--query` option for client side filtering.  For example, `--query "{\"Versions\": Versions[0:5], \"DeleteMarkers\": DeleteMarkers[0:10]}"` would return the first five versions and the first ten delete markers.  However, this won't have any impact on the performance of the call, which you mentioned is a problem.

The `--max-keys` parameter will put a limit on the total number of combined versions and deleted markers returned, but you would get poor control over the number of each one returned.

The best solution would be to reduce the number of delete markers.  I'd recommend taking a look at the [S3 Versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) documentation, and setting up a lifecycle configuration to avoid having a high number of delete markers in a bucket.

Hope that helps, and please let me know if you have any follow-up questions.

**Comment by deneb42** [comment]
Hello,
Thanks for the answer.

A already use the --query to filter out the result, but as you said, the main point for me is the performance of the request (can take several minutes even with --max-keys set to relatively small values.

By the way, when experimenting, --max-key didn't seem to limit the combined number of returned items.
Just to be sure, I just re-tested this with a versionned bucket and 25 deleted items.
    `aws s3api list-object-versions --bucket <test-bucket> --max-items=5`
returns the first 5 Versions, but returns the 25 delete markers

=> If this is not the normal behavior, there may be an issue here.

As for lifecycle, we already had a lifecycle config, but it appears  that it was incorrect, forcing us to manually clean buckets.

Thanks again

**Comment by RyanFitzSimmonsAK** [comment]
> By the way, when experimenting, --max-key didn't seem to limit the combined number of returned items.
Just to be sure, I just re-tested this with a versionned bucket and 25 deleted items.
aws s3api list-object-versions --bucket <test-bucket> --max-items=5
returns the first 5 Versions, but returns the 25 delete markers

What's the output when you do `--max-keys 5`?

**Comment by deneb42** [comment]
Hello,
Using a test bucket containing 25 files, that I then deleted, 

`aws s3api list-object-versions --bucket test-bb-424242 --max-items=5`
outputs 

`{
    "Versions": [
        {
            "ETag": "\"f6072e293bc6c2f229a22c11fb387291\"",
            "Size": 7,
            "StorageClass": "STANDARD",
            "Key": "1",
            "VersionId": "V2j7bCsVN8wmxdNNWv8gUdlGfxpZtFDe",
            "IsLatest": false,
            "LastModified": "2023-09-05T14:27:09+00:00"
        },
        {
            "ETag": "\"f6072e293bc6c2f229a22c11fb387291\"",
            "Size": 7,
            "StorageClass": "STANDARD",
            "Key": "10",
            "VersionId": "yUUMaugeIRlCA07hQVinEZH50Tcdf4vS",
            "IsLatest": false,
            "LastModified": "2023-09-05T14:27:09+00:00"
        },
        {
            "ETag": "\"f6072e293bc6c2f229a22c11fb387291\"",
            "Size": 7,
            "StorageClass": "STANDARD",
            "Key": "11",
            "VersionId": "HJKp3HwCgKReQ5XuhNxtOtoq8dRkV6Ae",
            "IsLatest": false,
            "LastModified": "2023-09-05T14:27:09+00:00"
        },
        {
            "ETag": "\"f6072e293bc6c2f229a22c11fb387291\"",
            "Size": 7,
            "StorageClass": "STANDARD",
            "Key": "12",
            "VersionId": "xCNaz.NaNtaL2UjoEq7zJK9nWnwwTe42",
            "IsLatest": false,
            "LastModified": "2023-09-05T14:27:08+00:00"
        },
        {
            "ETag": "\"f6072e293bc6c2f229a22c11fb387291\"",
            "Size": 7,
            "StorageClass": "STANDARD",
            "Key": "13",
            "VersionId": "DHzzC.aYztR3HAJMUAKDBTmnNETsF2iz",
            "IsLatest": false,
            "LastModified": "2023-09-05T14:27:09+00:00"
        }
    ],
    "DeleteMarkers": [
        {
            "Key": "1",
            "VersionId": "C1ddzOYqvp_905m6wUcpCYsikA6f9_ao",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "10",
            "VersionId": "ctIiptDG5KCpGTo.wVAbJ7EgYVzDtINV",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "11",
            "VersionId": ".Y3W5n8bJ3.XgId7u49EO7yz3A8q89ne",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "12",
            "VersionId": "Gv_cpCqbK9m4zhEJmObN3jwY7ZmVoR5O",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "13",
            "VersionId": "iofpoL4iFeKBiBgJJJ1hE3NHt96k_Ek2",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "14",
            "VersionId": "Gr76l9o73v7iTVfcqIGaDk3ol5GxZZg7",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "15",
            "VersionId": "zDE5gy965yErKPMnIhBzX7fvT0in0Sc0",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "16",
            "VersionId": "7h2iluPAXoqTmgfJshyhhgmbmRkzXQ.0",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "17",
            "VersionId": "TSB2yTEpLyfkC0AW1NlSv9nyYxcJjEAs",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "18",
            "VersionId": "gBtUc3hghjiF_uOFZYFNkznWSvaNpvir",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "19",
            "VersionId": "CtraSI.uYQhmjwjqdPWkuSwwajmCLQl8",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "2",
            "VersionId": "ahsvA9vZAA9S__Rw.pm2G6WpaP1.Bb4p",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "20",
            "VersionId": "mQWUsdMGHaoKzyGHSZwv9QieYLiklhoz",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "21",
            "VersionId": "1iy470ha9T.z9Y0yHPIAx2sCeTXRrvFa",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "22",
            "VersionId": "UKahG9aStgA8bjH5.seK8GQscMiIrj45",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "23",
            "VersionId": "lDfnj7xJ4yKWsZhFKhDPuMEDXq9vIWqQ",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "24",
            "VersionId": "Er.K6u.3s7bJk2PSYvIkNooPB.i1rfx5",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "25",
            "VersionId": "k8F7NdFqnbEvvDdsU5KyQ31B6in68nZR",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "3",
            "VersionId": "K4pURZuO7Kx3xDzuFIvSmuCX1Ou6Guaf",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "4",
            "VersionId": "vq_zi2ETYGxoh1o8.4UkSS.KdVnBkdeN",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "5",
            "VersionId": "YRT9zZs_DY2VogygJSQZSJXXekqtPkMj",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "6",
            "VersionId": "rLmPIXN9aWHOskOGsijtwPiVSDyXVFvS",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "7",
            "VersionId": "S4RP63yfEC0j6E7JGKi0z3pjdf3WuH_l",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "8",
            "VersionId": "WZuPFDWO6DbtwquPlv4mNKVkTDyagU7D",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        },
        {
            "Key": "9",
            "VersionId": "ieUgI65dFnuuIX8.8xJb9OPaEbWy4pgx",
            "IsLatest": true,
            "LastModified": "2023-09-05T14:28:06+00:00"
        }
    ],
    "NextToken": "eyJLZXlNYXJrZXIiOiBudWxsLCAiVmVyc2lvbklkTWFya2VyIjogbnVsbCwgImJvdG9fdHJ1bmNhdGVfYW1vdW50IjogNX0="
}
`

**Comment by RyanFitzSimmonsAK** [comment]
That's `--max-items`, not `--max-keys`.  But regardless, I don't think `--max-keys` will be that useful for the reasons I described in my original response.  Having a lifecycle configured to handle this is definitely the right approach.
