### ISSUE TITLE
AWS CLI --query issues

### ISSUE THREAD

**Issue by cslattery117** [aws/aws-cli#8146]
### Describe the bug

HELLO THERE 

1. I use Secrets Manager to store RDS Oracle secrets.  This is a user and password combination and is stored automatically by RDS. 
2.  I want to use automation to retrieve this secret and use it to perform administrative tasks against the database 
3.  My thinking is to use AWS CLI . 
So aws secretsmanager get-secret-value --secret-id ARNXYZ --output json works OK. 

4. Now I do aws secretsmanager get-secret-value --secret-id ARNXYZ --output json --query "SecretString" 

this works OK - now I get 

"{ \"username\":\"david\",\"password\":\"SECRETME\"}"

however now when i do 

aws secretsmanager get-secret-value --secret-id ARNXYZ --output json --query "SecretString.username"   

I always get "null".  I have looked into JMES syntax and this should be the correct syntax.   

Reading StackOverflow etc seems to suggest using --output text but this does not fix the issue .   I am running this on Windows so JQ or other post-processing tools are NOT available 

What should happen querystring "SecretString.username" or password should correctly extract the password.  

It looks like SecretsManager is storing the value correctly (i.e. without the backslash) so the error must be in how the CLI is extracting the values and adding a backslash -  CLI or JMES should have an option to remove them or fix the issue. 

If I have gotten this wrong and "works as expected" then is there no way of passing a username/password without a post-processor like jq ? 

THanks ! 

### Expected Behavior

cli correctly extracts password in a usable format 

### Current Behavior

it does not do so 

### Reproduction Steps

see above 

### Possible Solution

seems like whatever internal API is working to a standard , Text output correctly strips the backslash but removes the JSON form so JMES client side doesnt work properly - there must be a middle ground. 

### CLI version used

2.13.11

### Environment details (OS name and version, etc.)

AWS workspaces client W10

**Comment by cslattery117** [comment]
Unfortunately this webpage is stripping out the pasted escape characters in the JSON string.   However it is instantly visible by creating a t3.micro oracle rds and ticking the box to store the master user and password in a secret, then using AWS CLI to retrieve the secret - it is then repeatable

**Comment by tim-finnigan** [comment]
Hi @cslattery117 thanks for reaching out. I think what you're looking for is the following:
```
aws secretsmanager get-secret-value --secret-id my-secret --query 'SecretString' --output text | jq -r '.username'
```
Can you confirm? I'll also note that you could use an AWS SDK like Boto3 to run [get_secret_value](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager/client/get_secret_value.html) in a script for more flexibility.

**Comment by tim-finnigan** [comment]
Apologies for missing that. Are you able to use another tool like awk or sed? As an alternative you could also try something like:

```
aws secretsmanager get-secret-value --secret-id my-secret --query 'SecretString' --output text | python -c "import sys, json; print(json.loads(sys.stdin.read())['username'])" 
```

The AWS CLI uses JMESPath as [documented here](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side). Feature requests for that library can be opened here: https://github.com/jmespath/jmespath.py/issues. 

I should also note that the `get-secret-value` CLI command maps to the [GetSecretValue API](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html) which is used across SDKs, and the [SecretString](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#SecretsManager-GetSecretValue-response-SecretString) value is returned directly from the API.

**Comment by cslattery117** [comment]
Hi is there any work going on this , or no ?   thanks
