### ISSUE TITLE
`--deletion-protection-enabled` is missing in dynamodb create-table

### ISSUE THREAD

**Issue by landsman** [aws/aws-cli#8155]
### Describe the bug

I'm not able to create a new dynamodb table with this flag via one command.

### Expected Behavior

One CLI command only, as it's in example here: https://docs.aws.amazon.com/cli/latest/reference/dynamodb/create-table.html

### Current Behavior

```bash
Unknown options: --deletion-protection-enabled
```

### Reproduction Steps

```bash
AWS_PROFILE="hello"
AWS_REGION="eu-west-1"
AWS_DYNAMO_TABLE="terraform-backend-lock"

aws dynamodb create-table \
    --profile ${AWS_PROFILE} \
    --region ${AWS_REGION} \
    --table-name ${AWS_DYNAMO_TABLE} \
    --billing-mode PAY_PER_REQUEST \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --stream-specification StreamEnabled=false \
    --tags Key=Name,Value=${AWS_DYNAMO_TABLE} \
    --deletion-protection-enabled

```

### CLI version used

2.2.5

### Environment details (OS name and version, etc.)

macOS 13.5.1

**Comment by tim-finnigan** [comment]
Hi @landsman, support for `--delete-protection-enabled` was added [here](https://github.com/aws/aws-cli/blob/519043df9a5ff40fd3a95523cad40d29e0cee01a/CHANGELOG.rst?plain=1#L958) in version 2.11.2. The version your using ([2.2.5](https://github.com/aws/aws-cli/blob/519043df9a5ff40fd3a95523cad40d29e0cee01a/CHANGELOG.rst?plain=1#L4040)) is quite a bit older. Please try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the AWS CLI to 2.11.2 to access that parameter.

**Comment by landsman** [comment]
@tim-finnigan oh, my bad sorry I overlooked that bigger version. 🤦‍♂️
