### ISSUE TITLE
Help pages don't correctly show ANSI escape codes

### ISSUE THREAD

**Issue by jamietanna** [aws/aws-cli#8181]
### Describe the bug

When viewing a help page, for instance `aws cloudformation help`, the man pages show the raw ANSI escape codes, rather than actually interpolating them

### Expected Behavior

ANSI escape codes are interpreted by the shell, and picked up as i.e. underlines

### Current Behavior

ANSI escape codes are not interpreted.

A recording of this can be seen at https://asciinema.org/a/KCHn4wMjn6iZfdYTBrDewGLwT

### Reproduction Steps

Unfortunately could not find a way to reproduce it as is

### CLI version used

aws-cli/2.13.15 Python/3.11.5 Linux/6.5.3-arch1-1 source/x86_64.arch prompt/off

### Environment details (OS name and version, etc.)

Arch Linux (package: aws-cli-v2 2.13.15-1)

**Comment by tim-finnigan** [comment]
Hi @jamietanna thanks for reaching out. Can you provide more details on your environment, such as the OS and terminal you're using? I'm not able to reproduce the issue, and if you are also unable to reproduce it then it may have been due to something transient

**Comment by jamietanna** [comment]
Sorry, missed these notifications @tim-finnigan!

I'm running Arch Linux, using the [kitty](https://sw.kovidgoyal.net/kitty) terminal.

I can also reproduce this using [uxterm](https://linux.die.net/man/1/uxterm) and xterm when running:

```sh
env TERM=xterm-256color aws cloudformation help
```

**Comment by ajkessel** [comment]
Same issue with WSL 2.3.17.0, Windows Terminal 1.23.240826001-llm, Ubuntu 24.04.1 LTS.

**Comment by rowantran** [comment]
For anyone else who runs into this issue (this was the first Google result for me), #4472 helped me troubleshoot the root cause on my setup. I also had `PAGER` explicitly set to `less` in my environment, and unsetting `PAGER` displayed the help page with escape codes propertly interpreted.
