### ISSUE TITLE
aws s3 cp failed in UAE when tried to copy files from another region

### ISSUE THREAD

**Issue by wc5858** [aws/aws-cli#8184]
### Describe the bug

The following command failed in UAE:
```
aws s3 cp s3:/xxx/xxx.tar.gz ./
```
The `xxx` bucket locates in us-east-1 region.
The error is:

> An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

**But this command works in other regions.**

And in UAE it could work if we specify the region:
```
aws s3 cp s3:/xxx/xxx.tar.gz ./ --region=us-east-1
```

### Expected Behavior

The command should work without specifying source region of the s3 bucket just like other regions do.

### Current Behavior

The command doesn’t work in UAE without specifying source region of the s3 bucket.

### Reproduction Steps

Use following command in UAE to copy file from a bucket in another region:
```
aws s3 cp s3:/xxx/xxx.tar.gz ./
```

### CLI version used

aws-cli/2.13.17 Python/3.11.5 Linux/5.10.186-179.751.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Linux

**Comment by RyanFitzSimmonsAK** [comment]
Hi @wc5858, thanks for reaching out.  UAE is an [opt-in region](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html), and you need to specify the region for opt-in regions to make this request.  You can either specify `--region us-east-1` or `--endpoint-url https://s3.us-east-1.amazonaws.com`.  The latter should allow you to make this request from the UAE region.  Hope that helps!

**Comment by wc5858** [comment]
> Hi @wc5858, thanks for reaching out. UAE is an [opt-in region](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html), and you need to specify the region for opt-in regions to make this request. You can either specify `--region us-east-1` or `--endpoint-url https://s3.us-east-1.amazonaws.com`. The latter should allow you to make this request from the UAE region. Hope that helps!

Thanks for replying!
