### ISSUE TITLE
EKS Managed Add-ons Not Obeying `replicaCount` + CoreDNS v1.10.1-eksbuild.4 + v1.10.1-eksbuild.3 broken

### ISSUE THREAD

**Issue by ForbiddenEra** [aws/aws-cli#8192]
### Bug Description

Edit: I was able to finally deploy `v1.10.1-eksbuild.2` and see no scaling drift/issues. Both `v1.10.1-eksbuild.4` and `v1.10.1-eksbuild.4` have their readiness probe set to port 8181 (yet the liveness probe is still set to 8080) where nothing is listening.. earlier versions like v1.10.1-eksbuild.2 and previous, have their readiness and liveness probes are set to port 8080 and it deploys fine. Initially I assumed my issue was perhaps purely related to `replicaCount` as I've seen the scaling up/down kind of behavior with what looks like a second deploy right after the first as in the screenshot and scaling up and down but previously it at least hit my desired number and became healthy. This issue happens when adding the addon through the console, but also through the API via terraform.

Not sure if there's a better place for this to be reported; I don't think it's specifically an issue with `awscli` but I don't know where else to report this, if there's a better place I'm happy to be redirected there.

For `coredns`, I set `replicaCount: 3` in the configs.

`aws eks describe-addon-configuration` for both has shown it's been an option for a while, and I haven't really had issues. I have noticed that `coredns` would scale up and down during creation but it would always at least work.

I've just tried updating to the latest versions of the addons, and now `coredns` never finishes creating, because it never hits the 3 desired replicas:

![image](https://github.com/aws/aws-cli/assets/7980490/6c4a246c-b195-432d-88d0-03c748bb1d4a)

Another issue you can see here is that it's seemingly created twice with different names; this happened as well on a previous version.

### Expected Behavior

I expect that if a configuration option is exposed in `describe-addon-configuration` that it is observed.

### Current Behavior

Add on never finishes 'creating' due to insufficient replicas.

### Reproduction Steps

- Create VPC
- Create EKS cluster
- Set `replicaCount: 3` in the managed add-on configuration for `coredns`

### CLI version used

aws-cli/2.12.3 Python/3.11.4 Linux/5.15.90.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off

### Environment details (OS name and version, etc.)

n/a

**Comment by ForbiddenEra** [comment]
A side note on another issue that may be related, at least is what's preventing me from creating add-ons whether through API or console:

CoreDNS past v1.10.1-eksbuild-2 is seemingly broken; even when adding through the console, -3 and -4 result in this error:

`Readiness probe failed: Get "http://10.202.11.32:8181/ready": dial tcp 10.202.11.32:8181: connect: connection refused`

-2 is using a different url for readiness: 
```
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
```
-3 and -4:
```
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
```
which causes the addon to never finish 'creating' and just stall

**Comment by ForbiddenEra** [comment]
Seems like adding .4 works through console when not providing a custom `corefile` config..?

```
.:53 {
    errors
    health
    hosts {
      # some predefined hosts
      fallthrough
    }
    rewrite name suffix .${env_domain} .${cluster_domain}
    rewrite name suffix .${env_domain}.com .${cluster_domain}
    rewrite name suffix .${rewrite_suffix} .${cluster_domain}
    autopath @kubernetes
    kubernetes ${cluster_domain} in-addr.arpa ip6.arpa {
      pods ${pod_mode}
      fallthrough ${fallthrough}
      ${labels}
    }
    forward . /etc/resolv.conf
    forward . ${some upstream dns} {
      health_check 15s
    }
    prometheus :9153
    cache 30
    loop
    reload
    loadbalance
}
```

same config works fine on .2 and earlier.. tried setting prometheus port to 8181 for sags but it gets 404, heh.. not sure where 8181 came from or what the aws default corefile looks like but past -2 readiness probe goes to 8181 where previously it was 8080.. but that does seem to work when I don't specify a corefile.. even specifying a blank corefile results in the same issue..

you should be able to override the corefile w/out issue if it's presented as an option; if there are requirements for the overridden file they should be published/well known? if that is the case, I don't know where it would be..hence me even posting this here

**Comment by ForbiddenEra** [comment]
Seems like on .3 and .4 the default corefile now has the `ready` statement:
>> "By enabling ready an HTTP endpoint on port 8181 will return 200 OK, when all plugins that are able to signal readiness have done so"

That explains 8181.. still an annoying breaking change?

**Comment by tim-finnigan** [comment]
Hi @ForbiddenEra thanks for reaching out. The [describe-addon-configuration](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/describe-addon-configuration.html) command corresponds to the [DescribeAddonConfiguration API](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeAddonConfiguration.html). So this issue does seem to relate to the EKS API rather than the AWS CLI. 

If you have a support plan then we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) for direct assistance with these kinds of issues. We can also escalate potential bugs internally to service teams. Before doing that, could you provide debug logs (with sensitive info redacted) by adding `--debug` to the command? That may help provide more insight into the issue. 

Also here is the AWS CLI [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for reference. If you believe there was a breaking change, could you tell us when that started to occur or in which version this was working as expected?

**Comment by Hronom** [comment]
Same issue for `v1.10.1-eksbuild.5`

**Comment by Hronom** [comment]
Able to resolve, I was having custom `Corefile`:
```
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```
I removed customization and use default:
```
.:53 {
    errors
    health {
        lameduck 5s
      }
    ready
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
```
Difference is this:
```
    health {
        lameduck 5s
      }
    ready
```

**Comment by StevenMonty** [comment]
According to [these docs](https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html#coredns-upgrade), when upgrading:

> In EKS add-on versions v1.9.3-eksbuild.3 and later and v1.10.1-eksbuild.6 and later, the CoreDNS Deployment sets the readinessProbe to use the /ready endpoint. This endpoint is enabled in the Corefile configuration file for CoreDNS.
If you use a custom Corefile, you must add the ready plugin to the config, so that the /ready endpoint is active in CoreDNS for the probe to use.

All I had to do was add a single line to my custom config file. 
From 
```
.:53 {
    errors
    health
    ...
}
```
To
```
.:53 {
    errors
    health
    ready
    ...
}
```
and then after bouncing the pods, all my replicas came online and healthy.

**Comment by ForbiddenEra** [comment]
> Difference is this

Yeah, I eventually figured out that was the issue. I didn't come back and clarify because the response here was basically "Not our problem" :(
