### ISSUE TITLE
Transcription not stored in S3 bucket when using create media capture pipeline

### ISSUE THREAD

**Issue by Bharath-2656** [aws/aws-cli#8199]
### Describe the bug

As per the documentation, transcription messages will be stored inside the sink S3, but transcriptions messages is not there in S3 bucket.
Except transcription other elements such as audio, video, data-channel, meeting-events is stored in the bucket even after starting transcription in the meeting.

### Expected Behavior

Transcription files be present in the sink S3 bucket

### Current Behavior

No transcription-messages folder present in S3

### Reproduction Steps

- Start a Meeting
- Start media capture pipeline with S3 as sink

`aws chime-sdk-media-pipelines create-media-capture-pipeline \
    --source-type ChimeSdkMeeting \
    --source-arn "arn:aws:chime::***:meeting:***" \
    --sink-type S3Bucket \
    --sink-arn "arn:aws:s3:::***" \
    --chime-sdk-meeting-configuration \
        '{
          "ArtifactsConfiguration": {
            "Audio": {
              "MuxType": "AudioOnly"
            },
            "Video": {
              "State": "Enabled",
              "MuxType": "VideoOnly"
            },
            "Content": {
              "State": "Enabled",
              "MuxType": "ContentOnly"
            }
          }
        }`

- Start Transcription

`aws chime start-meeting-transcription --meeting-id *** --transcription-configuration '{"EngineTranscribeSettings": {"LanguageCode": "en-US"}}`

### CLI version used

aws-cli/2.13.5 Python/3.11.4 Darwin/22.1.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS 13.0

**Comment by EnotPoloskun** [comment]
I also follow guide(using ruby sdk) and transcription files are not uploaded to s3 when starting transcription and media capture pipeline
