### ISSUE TITLE
Errors not written to stderr

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-cli#820]
### Description of Issue

errors that prevent file copy operations when running aws s3 commands are written to stdout
### Steps to Reproduce

tested with both invalid s3 credentials and with destination files that could not be written to)
1. Modify credentials to be invalid (example: export `AWS_ACCESS_KEY=xxxxxxxxxxxxxxxxxxx`)
2. Run command, with output piped to stdout, example: aws s3 sync `s3://mybucket/myobjects/ /Temp > /dev/null`
### Expected Output

`(venv)hostname:Temp username$ aws s3 sync aws s3 sync s3://mybucket/myobjects/ /Temp > /dev/null
A client error (InvalidAccessKeyId) occurred when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
Completed 1 part(s) with ... file(s) remaining`
### Actual Output

`(venv)hostname:Temp username$ aws s3 sync aws s3 sync s3://mybucket/myobjects/ /Temp > /dev/null`

The same behavior occurs when running in --quiet mode - although the expectation with quiet mode might be that both stdout and stderr are suppressed.

**Comment by edorivai** [comment]
Could this also be the case for the aws eb CLI? My CI build is passing, while running `aws elasticbeanstalk create-application-version` the CLI outputs

```
A client error (InvalidParameterValue) occurred when calling the CreateApplicationVersion operation: Application Version 1a0a45f1496e5f5fe2fffa6450138c078571e78e already exists.
```

as I would expect. The fact that my CI build passes leads me to believe that the message is printed to stdout instead of stderr.
