### ISSUE TITLE
awscli command fails with echoing the input with repetitive characters and log file not found

### ISSUE THREAD

**Issue by arunapadhu85** [aws/aws-cli#8203]
### Describe the bug

This issue happens intermittently. not always. I am seeing this issue only with aws 2.13.0 but not with aws 1.22.76. 

Input Command:
"aws route53 list-resource-record-sets --hosted-zone-id zoneid --profile profile_name > /tmp/aws_cli_output && echo 'succeeded' || echo 'failed'"

Output: 

"\x07\r:\r\x07\r:\r-\rlog file:   rroouuttee5533  lliisstt--rreessoouurrccee--rreeccoorrdd--sseettss  ----hhoosstteedd--zzoonnee--iidd  zzoonneeiidd  ------hosted-zone-id zoneid --pprrooffiillee  pprrooffiillee__nnaammee  >>  //ttmmpp//aawwss__ccllii__116699rofile profile_name > /tmp/aws_cli_oouuttppuutt  &&&&  eecchhoo  ''output && echo '  ssuucccceeeeddeedd''  ||||  eecchhoo  ''succeeded' || echo 'ffaaiilleedd''\r\rLog file is already in use  (press RETURN)"

Is this a known issue (or) is there any alternatives for this ? 

### Expected Behavior

Should see 'failed' or 'succeeded' in the output.

### Current Behavior

Output: 

"\x07\r:\r\x07\r:\r-\rlog file:   rroouuttee5533  lliisstt--rreessoouurrccee--rreeccoorrdd--sseettss  ----hhoosstteedd--zzoonnee--iidd  zzoonneeiidd  ------hosted-zone-id zoneid --pprrooffiillee  pprrooffiillee__nnaammee  >>  //ttmmpp//aawwss__ccllii__116699rofile profile_name > /tmp/aws_cli_16944991144449911..66666688770066  &&&&  eecchhoo  ''914491.6668706 && echo '  ssuucccceeeeddeedd''  ||||  eecchhoo  ''succeeded' || echo 'ffaaiilleedd''\r\rLog file is already in use  (press RETURN)"

### Reproduction Steps

\\

### CLI version used

2.13.0

### Environment details (OS name and version, etc.)

Centos Linux 7

**Comment by RyanFitzSimmonsAK** [comment]
Hi @arunapadhu85, thanks for reaching out.  Could you provide debug logs of this behavior?  You can get debug logs by adding `--debug` to your command, and redacting any sensitive information.  Thanks!
