### ISSUE TITLE
v2.13.23 is flagged to have a Trojan FVTV by MacAffee

### ISSUE THREAD

**Issue by cnocula-peg** [aws/aws-cli#8219]
### Describe the bug

The current version v2.13.23 has been flagged by McAffee as containing a trojan, thus causing critical alerts in our monitoring infrastructure: 

https://www.virustotal.com/gui/file/a2d89814f1fe981dce1721d07a52f01f9004d457a7d502211154732df0a9da54/detection

Which is most probably a false positive? (As no other scanners are reporting this)

### Expected Behavior

No suspicious findings in malware scanners.

### Current Behavior

MacAffee finding: Trojan-FVTV!4139E39A3B8C

### Reproduction Steps

Scan the binary with MacAffee?

### Additional Information/Context

![image](https://github.com/aws/aws-cli/assets/91733677/48880baa-a575-45bd-8c0e-a4a61c6e12a1)

![image](https://github.com/aws/aws-cli/assets/91733677/316f47fe-b29e-4574-b2c6-f2d9cc730697)

![image](https://github.com/aws/aws-cli/assets/91733677/b0ecc2ba-db06-4415-99f0-c9aaed1ebf7f)

### CLI version used

v2.13.23

### Environment details (OS name and version, etc.)

Ubuntu Jammy20230816

**Comment by cjschroeder** [comment]
I also started getting alerts today from McAfee VirusScan for Linux.  It started with dat_set_version 10852.

```
<!-- Uvscan Results -->
<Uvscan>
        <Preamble>
                <Product_name value="McAfee VirusScan Command Line for Linux64" />
                <Version value="6.1.4.305" />
                <License_info value= />
                <AV_Engine_version value="6100.8979" />
                <Dat_set_version value="10853" />
        </Preamble>
        <Date_Time value="2023-Oct-04 09:22:13" />
        <Options value="--config mcafee.cfg /boot /boot/efi / --analyze --atime-preserve --ignore-links --maxfilesize=10 --norename --one-file-system --sub --summary --xmlpath=/tmp/mcafee.xml " />
        <Summary On-Path="/boot" Total-files="81" Clean="75" Not-Scanned="6" Possibly-Infected="0" />
        <Summary On-Path="/boot/efi" Total-files="9" Clean="9" Not-Scanned="0" Possibly-Infected="0" />
        <File name="/var/lib/docker/overlay2/e3bc7f2270711d4c8dd871bf3f6eefa3000e476428227943893dff140e27eb76/diff/usr/local/aws-cli/v2/2.11.5/dist/aws" status="infected" virus-name="Trojan-FVTV!361A13461140" detection-type="trojan" />
        <File name="/var/lib/docker/overlay2/e3bc7f2270711d4c8dd871bf3f6eefa3000e476428227943893dff140e27eb76/diff/usr/local/aws-cli/v2/2.11.5/dist/aws_completer" status="infected" virus-name="Trojan-FVTV!9447FCB50572" detection-type="trojan" />
        <Summary On-Path="/" Total-files="316662" Clean="314246" Not-Scanned="2414" Possibly-Infected="2" />
        <Time value="01:46:36" />
</Uvscan>
```

**Comment by tim-finnigan** [comment]
Hi @cnocula-peg thanks for reaching out. This _may_ be a false positive — I couldn't find any other reports of this issue but it's something we will want to monitor and look into further. @cjschroeder it looks like you're using 2.11.5 while the original issue references  2.13.23. Are there any other details anyone can provide regarding the security scan information?

**Comment by tim-finnigan** [comment]
Thanks for the report, this is something we are looking into further. If anyone else has related info to share on this please let us know here.

**Comment by cnocula-peg** [comment]
Update: now a second scanner (TrendMicro-HouseCall) is reporting a Trojan:

![image](https://github.com/aws/aws-cli/assets/91733677/eb833306-9276-48d1-8dcd-8a2e19ce413a)

**Comment by hssyoo** [comment]
At this time, we believe this is a false positive. However, in order to confirm it is a false positive and clear the detections, we'll need to submit reports to the AV vendors flagging the executables. We are currently working on this and will keep this issue updated.

**Comment by sys-ops** [comment]
v2.13.15 also flagged by McAffee as containing a trojan.
![image](https://github.com/aws/aws-cli/assets/5460298/3b66d04e-a8cc-4a67-9027-23fb072a1824)

**Comment by axcawef** [comment]
Hi there, 

We are having similar trojan report from Wiz:

<img width="1161" alt="Screenshot 2023-10-05 at 10 40 51" src="https://github.com/aws/aws-cli/assets/75678724/81d240bf-5b03-474d-86aa-835deed1f7a9">

AWS version 2.13.23

**Comment by slimmclovin** [comment]
Hello,

on my side, McAfee started to detect aws and aws_completer as a trojan on Tuesday 3rd (it was OK on Monday), I believe with DATv3 5303.
aws: Trojan-FVTV
aws_completer: Trojan-FVTV

I'm not sure which version I have, probably 2.13.23. 
But I've downloaded 2.13.22 => same result. 
I've tried an even older one: 2.12.7 => same result.

**Comment by zskulcsar** [comment]
:wave: same issue, different version: AWS CLI `2.11.14`

![image](https://github.com/aws/aws-cli/assets/865399/73cca915-149d-4eac-ad05-26cf8638e9eb)

**Comment by mooniesdl3** [comment]
Same issue using versions 2.13.13, 2.11.7 and 2.11.21.

**Comment by DRLDoom** [comment]
Same issue Trellix and aws-cli v2.12.7

**Comment by mooniesdl3** [comment]
Trellix has tested files I sent against today's 10854 definitions and do not get the alert, the definition stack I had that did was 10853

**Comment by TacticalRhino** [comment]
Anyone else experiencing clean scans now? Do we know if the definitions have been updated/corrected?

**Comment by mooniesdl3** [comment]
I'm getting clean scans now with updated definitions after restoring the deleted files

**Comment by slimmclovin** [comment]
Also clean on my side for aws-cli 2.13.24 and with DAT v3 5305.

**Comment by rukender-attree-deel** [comment]
McAfee is not showing now but TrendMicro and skyhigh are still showing this package as malicious. 

<img width="1360" alt="image" src="https://github.com/aws/aws-cli/assets/145525588/f1c492ad-da52-4745-8874-9d2f25f6aa0e">

**Comment by rukender** [comment]
I can still see McAfee and TrendMicro are still reporting this as Malicious.

<img width="1508" alt="image" src="https://github.com/aws/aws-cli/assets/24912962/015b64d9-3f16-428a-b06c-fbacd1adf442">

**Comment by cnocula-peg** [comment]
I do not get any Trojan alerts anymore for the version 2.13.24 via WIZ (and thus VirusTotal) anymore. So @tim-finnigan - at least from my view, this ticket can be closed?

**Comment by rwjack** [comment]
That's odd, because I keep getting alerts for 2.13.24 - SHA256:c140d048f350d70ccdbb10ed5a4f152ad168aca8b586bddd10d94d93abc0497c

**Comment by tim-finnigan** [comment]
Thanks all for reaching out regarding the scan report flagging issues with AWS CLI v2. We are actively working with the virus scanning vendors to investigate the detections. We have not identified any impact and are working to confirm this is a false positive.

**Comment by tim-finnigan** [comment]
It appears that TrendMicro and McAfee are no longer flagging the CLI and we have not received any other reports here. I'll go ahead and close this issue but if anyone is still seeing the CLI flagged in any scans please share those details with us.
