### ISSUE TITLE
aws appsync update-function resets mapping templates

### ISSUE THREAD

**Issue by ggorge-etiqa** [aws/aws-cli#8225]
### Describe the bug

I'm running the command `aws appsync update-function --api-id myApiId --function-id myFunctionId --function-version 2018-05-29 --name MutationMypreUpdate0Function --data-source-name MyLambdaDS` to change the Datasource of an existing AppSync Function.

Although `--request-mapping-template <value>`  and `--response-mapping-template <value>` are supposed to be optional parameters, it came out that Function mapping templates settings are overwritten and switched off.

### Expected Behavior

As I'm not using the `--request-mapping-template <value>`  and `--response-mapping-template <value>` flags in my command, I suppose that those settings are not touched.

### Current Behavior

Although `--request-mapping-template <value>`  and `--response-mapping-template <value>` are supposed to be optional parameters, it came out that Function mapping templates settings are overwritten and switched off.

### Reproduction Steps

* Create an AppSync function with enabled custom mapping templates
* Create an AppSync datasource
* Run `aws appsync update-function --api-id myApiId --function-id myFunctionId --function-version 2018-05-29 --name MutationMypreUpdate0Function --data-source-name MyLambdaDS` to change only the Datasource

### CLI version used

aws-cli/2.7.4

### Environment details (OS name and version, etc.)

Ubuntu Python/3.9.11 Linux/5.14.0-1054-oem exe/x86_64.ubuntu.22 prompt/off

**Comment by RyanFitzSimmonsAK** [comment]
Hi @ggorge-etiqa, thanks for reaching out.  I think this is an issue with the version of AWS CLI you are using; v2.7.4 is *very* out of date, and on the current version, `--request-mapping-template` and `--response-mapping-template` appear to be required parameters, which would avoid this behavior.  Please update your version, and let me know if you are still having this issue.  Thanks!

**Comment by ggorge-etiqa** [comment]
If those parameters are mandatory anyway, that's fine. I will change my script to get the current templates beforehand in order to pass them when issuing the `update-function`.
I will only suggest to probably update the documentation here https://awscli.amazonaws.com/v2/documentation/api/latest/reference/appsync/update-function.html as this behavior is not really clear.

**Comment by RyanFitzSimmonsAK** [comment]
Thanks for the feedback, I've reached out to the service team about getting these parameters marked as required.
