### ISSUE TITLE
list-bot-recommendations fails because of wrong constraint on bot-version parameter

### ISSUE THREAD

**Issue by andrei-at-work** [aws/aws-cli#8237]
### Describe the bug

The constraint on the `bot-version` parameter of the `list-bot-recommendations` API checks for a min length of 5. This causes validation to fail with the following error and no results returned:

```
Parameter validation failed:
Invalid length for parameter botVersion, value: 1, valid min length: 5
```

![list-bot-recommendations](https://github.com/aws/aws-cli/assets/74427636/2675d86e-8e1f-47a6-a4c8-a70593e4bfce)

### Expected Behavior

Validation should succeed and list of bot recommendations returned for --bot-version 1, just as for --bot-version DRAFT (which satisfies the current constraint):

C:\>aws lexv2-models list-bot-recommendations --bot-id LYUB9L9MEI --bot-version DRAFT --locale-id en_US
{
    "botId": "LYUB9L9MEI",
    "botVersion": "DRAFT",
    "localeId": "en_US",
    "botRecommendationSummaries": []
}
C:\>

![draft](https://github.com/aws/aws-cli/assets/74427636/1ac6579d-23b9-48ef-84cf-7eb47a0f3541)

### Current Behavior

C:\>aws lexv2-models list-bot-recommendations --bot-id LYUB9L9MEI --bot-version 1 --locale-id en_US

Parameter validation failed:
Invalid length for parameter botVersion, value: 1, valid min length: 5

### Reproduction Steps

Call the list-bot-recommendations API with a numeric version under 99999

### Possible Solution

Change the constraint from min length: 5 to max length: 5 (and min length: 1)

### CLI version used

2.13.26

### Environment details (OS name and version, etc.)

Windows 10 Pro

**Comment by RyanFitzSimmonsAK** [comment]
Hi @andrei-at-work, thanks for reaching out.  This appears to be intended behavior, as `ListBotRecommendations` is for Automated Chatbot Designer recommendations, and the documentation specifically restrict the `botVersion` to "DRAFT", and not just any value of five or more characters.

**Comment by RyanFitzSimmonsAK** [comment]
In all likelihood, backwards compatibility reasons.  Changing a parameter from optional to required can cause issues in certain SDKs.  Changing the required length of a parameter can also be considered a backwards incompatible change.
