### ISSUE TITLE
Listing S3 Service quota via cli not working 

### ISSUE THREAD

**Issue by rdob2022** [aws/aws-cli#8238]
### Describe the bug

aws service-quotas list-service-quotas --service-code s3 returns empty.  

### Expected Behavior

I expect the list of service quota for S3 bucket

### Current Behavior

 When you run below command, 
`aws service-quotas list-service-quotas --service-code s3 --profile --region us-east-1`
{
"Quotas": []
}

### Reproduction Steps

aws service-quotas list-service-quotas --service-code s3 --profile --region us-east-1

https://docs.aws.amazon.com/cli/latest/reference/service-quotas/list-service-quotas.html

### CLI version used

2.13.26

### Environment details (OS name and version, etc.)

MacOS Ventura 13.5.2

**Comment by RyanFitzSimmonsAK** [comment]
Hi @rdob2022, thanks for reaching out.  `list-service-quotas` is intended to show **account specific applied quotas** of a service.  However, as you pointed out, this operation has varying levels of support on a service-by-service basis.  Note that in the [documentation](https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_ListServiceQuotas.html), it says "For some quotas, only the default values are available. If the applied quota value is not available for a quota, the quota is not retrieved.".  

If you don't have any applied quotas, then `list-aws-default-service-quotas` should work and is functional for all services.  If that isn't sufficient for your use case, I can reach out to the S3 service team for you.  Let me know how you'd like to proceed here.

**Comment by jsoncow** [comment]
@rdob2022, I wrote this post detailing research on what we found here and https://github.com/aws/aws-cli/issues/7962 about Service Quotas.
