### ISSUE TITLE
Rate Exceeded Error when running download-db-log-file-portion and Downloading Large Files

### ISSUE THREAD

**Issue by colinbjohnson** [aws/aws-cli#8251]
### Describe the bug

When running a command such as below:

```
aws rds download-db-log-file-portion --starting-token 0 --db-instance-identifier my-database-instance --log-file-name error/postgresql.log.2023-10-18-21.csv --query LogFileData --output text --region us-west-2 > postgresql.log.2023-10-18-21-2-try.csv
```

Note that the file being downloaded is 5+ GB in size.

I receive an error that states the following:

```
An error occurred (Throttling) when calling the DownloadDBLogFilePortion operation (reached max retries: 4): Rate exceeded
```

### Expected Behavior

I would expect the [https://github.com/aws/aws-cli](aws-cli) tool to handle throttling.

### Current Behavior

I receive an error

```
An error occurred (Throttling) when calling the DownloadDBLogFilePortion operation (reached max retries: 4): Rate exceeded
```

And the download stops.

### Reproduction Steps

Run the command below:

```
aws rds download-db-log-file-portion --starting-token 0 --db-instance-identifier my-database-instance --log-file-name error/postgresql.log.2023-10-18-21.csv --query LogFileData --output text --region us-west-2 > postgresql.log.2023-10-18-21-2-try.csv
```

Where `error/postgresql.log.2023-10-18-21.csv` is a very large file (about 5+ GB)

### Possible Solution

It feels like handling of throttled requests is not implemented for the `aws rds download-db-log-file-portion` command.

### Additional Information/Context

I _can_ get the download to work by running with `--debug` such as `aws rds --debug download-db-log-file-portion --starting-token 0 --db-instance-identifier my-database-instance--log-file-name error/postgresql.log.2023-10-18-21.csv --query LogFileData --output text --region us-west-2 > postgresql.log.2023-10-18-21.csv`

Although I think I may have just gotten lucky in that respect.

This issue also occurs under `aws-cli/1.18.147 Python/2.7.18 Linux/5.10.192-183.736.amzn2.x86_64 botocore/1.18.6`

### CLI version used

aws-cli/2.13.27 Python/3.11.6 Linux/5.10.192-183.736.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

Linux/5.10.192-183.736.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off

**Comment by takesson** [comment]
I am seeing Rate exceeded with this command but works when removing --page-size.

`aws ssm list-documents --page-size 10`

`aws-cli/2.13.27 Python/3.11.6 Darwin/21.6.0 exe/x86_64`

**Comment by tim-finnigan** [comment]
Hi @colinbjohnson thanks for reaching out. The AWS CLI uses a built-in retry mechanism to handle service-side Throttling issues. (See: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-retries.html). Have you try increasing your max retries?

Also as an alternative have you considered publishing the logs to CloudWatch? (See: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Procedural.UploadtoCloudWatch.html). Depending on your use case, that approach may provide more flexibility.
