### ISSUE TITLE
Add `--filters` for iam list-roles

### ISSUE THREAD

**Issue by LozanoMatheus** [aws/aws-cli#8260]
### Describe the feature

Currently, the [iam list-roles](https://docs.aws.amazon.com/cli/latest/reference/iam/list-roles.html) doesn't have the option `--filters`, only the query.

### Use Case

This would be quite handy when using the AWS CLI for scripting. For example, if I want to get certain roles:

```bash
aws iam list-roles --query "Roles[*].RoleName" --filters "Name=role-name,Values=*my-role*"

## or using the tagging

aws iam list-roles --query "Roles[*].RoleName" --filters "Name=tag:Name,Values=*my-role*"
```

### Other Information

Similar to [ec2 describe-instances](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html#options)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.28 Python/3.11.6 Darwin/22.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Ventura 13.6

**Comment by RyanFitzSimmonsAK** [comment]
Hi @LozanoMatheus, thanks for reaching out.  I've reached out to the IAM team about considering this request.  As this is a service team feature request, I'm going to move this issue to our cross-SDK repository (https://github.com/aws/aws-sdk/) for tracking.  Please refer to that issue for any updates.  Thanks!

Ticket # for internal use : P104646561
