### ISSUE TITLE
describe-log-groups: --log-group-name-pattern does not list retentionInDays

### ISSUE THREAD

**Issue by fauxbytes** [aws/aws-cli#8264]
### Describe the bug

retentionInDays is missing from the listing when using --log-group-name-pattern.

### Expected Behavior

Output should be the same when using --log-group-name-pattern as when using --log-group-name-prefix

### Current Behavior

# retentionInDays reported, when using --log-group-name-prefix
$ aws logs describe-log-groups --log-group-name-prefix '/aws/lambda/foo' --query 'logGroups[0].retentionInDays'
60

# retentionInDays missing, when using --log-group-name-pattern
$ aws logs describe-log-groups --log-group-name-pattern 'foo' --query 'logGroups[0].retentionInDays'
null

### Reproduction Steps

See above

### CLI version used

aws-cli/2.13.21 Python/3.11.5

### Environment details (OS name and version, etc.)

 Windows/10 exe/AMD64

**Comment by aBurmeseDev** [comment]
Hi @fauxbytes - thanks for reaching out. 

While researching, I came across this similar [issue](https://github.com/aws/aws-sdk/issues/608) where the service team confirmed that this's expected behavior as mentioned in the docs like follows:

> If you specify logGroupNamePattern in your request, then only arn, creationTime, and logGroupName are included in the response.

Hope that helps and please let me know if you have further questions!
John

**Comment by fauxbytes** [comment]
Thanks @aBurmeseDev.
That does clarify it. Appreciate you looking into it and finding an aswer for me.

In the context of user feedback (merely my opinion here): to me, `logGroupNamePattern` & `logGroupNamePrefix` look like they do quite the same thing: they are filter flags: One searches by prefix. The other - by substring. that sense, I don't see the rationale of those returning different output. If there is one, I'd be keen to understand it. If there isn't, that's fine too, but I wouldn't call it 'expected behavior'.
