### ISSUE TITLE
Error message for help on ec2 create-launch-template-version

### ISSUE THREAD

**Issue by kkumler** [aws/aws-cli#8269]
### Describe the bug

Running the command `aws ec2 create-launch-template-version help` generates an error message with `line-length-limit`.

### Expected Behavior

To display the help document for ec2 create-launch-template-version

### Current Behavior

The output of running `aws ec2 create-launch-template-version help`:

```
<string>:: (ERROR/3) Line 2533 exceeds the line-length-limit.
()                                                                          ()

NAME
        -

       System Message: ERROR/3 (<string>:)
              Line 2533 exceeds the line-length-limit.

                                                                            ()
```

### Reproduction Steps

`aws ec2 create-launch-template-version help`

### Additional Information/Context

`aws --version` output: `aws-cli/2.13.29 Python/3.11.6 Darwin/22.6.0 source/arm64 prompt/off`

Also received the same issue running the command while on CloudShell:
```
aws ec2 create-launch-template-version help
<string>:: (ERROR/3) Line 2533 exceeds the line-length-limit.
```

with version `aws-cli/2.13.27 Python/3.11.6 Linux/4.14.255-322-265.538.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off`

### CLI version used

2.13.29

### Environment details (OS name and version, etc.)

macos 13.5.2

**Comment by aBurmeseDev** [comment]
Hi @kkumler, thanks for reporting this. 
I'm able to reproduce it and doing more investigation into it.

**Comment by aBurmeseDev** [comment]
Thank you for the patience @kkumler. I wanted to post an update that the team have identified the bug and is currently looking into working a fix. Will keep it posted.
