### ISSUE TITLE
Dockerfile does not allow use of environment variables 

### ISSUE THREAD

**Issue by agalazis** [aws/aws-cli#8272]
### Describe the bug

You cannot state environment variables in aws commands

### Expected Behavior

I should be able to use  ["s3" , "cp", "${SOURCE}", "${DESTINATION}" ] for exampled where SOURCE and DESTINATION are environment variables

### Current Behavior

 "${SOURCE}"  and "${DESTINATION}" are taken literally as the strings  "${SOURCE}"  and "${DESTINATION}"

### Reproduction Steps

Make an image that USES environment variables in CMD

### Possible Solution

After reading about a ancient docker issue., I was able to get environment variables to work by overwriting the entrypoint to a file that contains the following 2 lines:
```
#!/bin/bash
bash -c "aws $*"
```

### Additional Information/Context

Related docker issue
https://github.com/moby/moby/issues/5509

### CLI version used

2

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Hi @agalazis thanks for reaching out. I think this is just a limitation of Docker — [here](https://stackoverflow.com/a/40454758) is an explanation.

If you want to pass environment variables you can use the `-e` flag, for example:
```
docker run -e SOURCE_BUCKET -e DEST_BUCKET amazon/aws-cli s3 cp s3://$SOURCE_BUCKET/test.txt s3://$DEST_BUCKET/test.txt
```
Here are more examples in the AWS CLI documentation: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html#cliv2-docker-share-files

You can also use `sh` as the ENTRYPOINT:
```dockerfile
FROM amazon/aws-cli:latest
ENV TARGET_BUCKET='bucket-name'
ENTRYPOINT [ "sh", "-c", "aws s3 ls s3://$TARGET_BUCKET" ]
```

**Comment by agalazis** [comment]
yes that's what I proposed as the default entry point but then when I thought of it it might be a breaking change since people might rely on existing escaping so you can close this ticket. I guess the best option is to extend the base image.
In my case I run fargate tasks and overwriting entrypoint in containerOverrides is not an option...

**Comment by agalazis** [comment]
This might cause a breaking change so closing...
