### ISSUE TITLE
ec2 describe-regions: meaning of `--no-paginate` is unclear

### ISSUE THREAD

**Issue by NotizMe** [aws/aws-cli#8281]
### Describe the issue

# Issue
The documentation for the Global Option `--no-paginate` is unclear. As a reader I thought this was about client-side pagination using a tool like `less`.

# Solution
It would be good to mention it disables making more then one call for fetching of subsequent pages. Please also add a link to [Use AWS CLI pagination options](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html).

# Proposal

> `--no-paginate` (boolean)
> 
> Disables automatically making multiple calls to return all possible results. Disabling pagination has the AWS CLI only call once for the first page of command results.
> 
> See [Use AWS CLI pagination options](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html)

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-regions.html#global-options

**Comment by RyanFitzSimmonsAK** [comment]
Hi @NotizMe, thanks for your patience.  I've cut a PR to add a bit more detail to the description of `no-paginate` parameter.  

> Disable automatic pagination. If automatic pagination is disabled, the AWS CLI will only make one call, for the first page of results.

**Comment by RyanFitzSimmonsAK** [comment]
The PRs were merged; this is done.  Thanks for submitting this!
