### ISSUE TITLE
aws configure export-credentials format powershell add extra quotes for AWS_SESSION_TOKEN=

### ISSUE THREAD

**Issue by rupaks** [aws/aws-cli#8284]
### Describe the bug

1. run `aws configure export-credentials --profile my-profile --format powershell`
2. observe AWS_SESSION_TOKEN having extra " like: $Env:AWS_SESSION_TOKEN=""g==""

### Expected Behavior

`aws configure export-credentials --profile my-profile --format powershell` should export AWS_SESSION_TOKEN as $Env:AWS_SESSION_TOKEN="g==" -- without any extra double quotes

### Current Behavior

1. run `aws configure export-credentials --profile my-profile --format powershell`
2. observe AWS_SESSION_TOKEN having extra " like below: $Env:AWS_SESSION_TOKEN=""g==""

### Reproduction Steps

1. run `aws configure export-credentials --profile my-profile --format powershell`
2. observe AWS_SESSION_TOKEN having extra " like below: $Env:AWS_SESSION_TOKEN=""g==""

### CLI version used

aws-cli/2.13.30 Python/3.11.6 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 10

**Comment by RyanFitzSimmonsAK** [comment]
Hi @rupaks, thanks for reaching out.  I had some trouble reproducing this behavior in both Powershell and Command Prompt.  What shell are you using?  Does this occur every time, even if you log out of SSO and log back in?

**Comment by RyanFitzSimmonsAK** [comment]
Hey @rupaks, thanks for your patience.  I just realized you have quotes around the session token in your configuration file.  That is likely the source of the issue.  From the [short-term credentials documentation](https://docs.aws.amazon.com/sdkref/latest/guide/access-temp-idc.html), it doesn't look like those quotes should be there.  Let me know if that helps.

**Comment by rupaks** [comment]
@RyanFitzSimmonsAK  thanks for pointing out...
finally traced it to NPM package [aws-azure-login](https://github.com/aws-azure-login) we use for authentication.
when we run  ` $ aws-azure-login --profile my-profile` , It adds those quotes to aws_session_token

So looks like a bug for aws-azure-login
