### ISSUE TITLE
eu-central-2: location constraint is incompatible for the region specific endpoint this request was sent to

### ISSUE THREAD

**Issue by SumanthDocupliot** [aws/aws-cli#8289]
### Describe the bug

Trying to copy file to bucket created in eu-central-2 region

aws s3 cp {{file_name}} s3://{{bucket_name}}/{{file_name}}

**Got below error**:

 The eu-central-2 location constraint is incompatible for the region specific endpoint this request was sent to.
 
 It works when I explicitly pass "--region eu-central-2"
 
 But it works for other regions even without giving region explicitly

### Expected Behavior

eu-central-2 region endpoint should be picked automatically

### Current Behavior

eu-central-2 region endpoint not picked automatically while s3 copy

### Reproduction Steps

1. create a S3 bucket in eu-central-2 region
2. copy file using aws cli to same bucket
3. It should throw "location constraint is incompatible" error

### CLI version used

2.13.31

### Environment details (OS name and version, etc.)

Mac Ventura 13.3

**Comment by RyanFitzSimmonsAK** [comment]
Hi @SumanthDocupliot, thanks for reaching out.  `eu-central-2` is an [opt-in region](https://docs.aws.amazon.com/controltower/latest/userguide/opt-in-region-considerations.html), and you need to specify the region for opt-in regions to make this request.  You can either specify `--region eu-central-2` or specify `--endpoint-url https://s3.eu-central-2.amazonaws.com`.  The latter should allow you to make the request from whatever region you want.  Hope that helps!

**Comment by SumanthDocupliot** [comment]
@RyanFitzSimmonsAK Thanks for reviewing this. Yes, I understand that eu-central-2 is part of opt-in region. I have enabled this region manually. But ideally aws-cli should work across regions. Why there is any need to send this `--region eu-central-2 or specify --endpoint-url https://s3.eu-central-2.amazonaws.com` manually ?

Would like to know if there is technical limitation ? Any possibility for this to be supported in near future ?

**Comment by RyanFitzSimmonsAK** [comment]
It isn't actually a limitation of the AWS CLI, but a restriction in place for the entire S3 service.  S3 does not allow cross region calls between opt-in regions and other regions.  This is mentioned in the [S3 user guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html).
> When you create a client, the Region maps to the Region-specific endpoint. The client uses this endpoint to communicate with Amazon S3: [s3.region.amazonaws.com](http://s3.region.amazonaws.com/). If your Region launched after March 20, 2019, your client and bucket must be in the same Region. However, you can use a client in the US East (N. Virginia) Region to create a bucket in any Region that launched before March 20, 2019. For more information, see [Legacy endpoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#s3-legacy-endpoints).

Opt-in regions don't have request rerouting.  There isn't a workaround for this as far as I know, but for what it's worth, including the region in the request is considered best practice, even for non-opt-in regions.
