### ISSUE TITLE
Listing Reserved Instances API inconsistency

### ISSUE THREAD

**Issue by pasolid** [aws/aws-cli#8290]
### Describe the bug

This API works fine in the 99% of the time, but there are strange edge cases when the API returns an error that says:
`The following parameters are missing 'Price Schedule for maximum month remaining(X) on lease`

My suspicion it has something to do with the calculation of the number of months left which is done on the AWS side.

For example:
I tried to sell an RI commitment on the 31 of October, 2023
The RI commitment end date is 2026-02-28 12:30:34.000

Parameters I used to create a request:
```
InstanceCount=1
ReservedInstancesId=67a5992e-xxx-xxxx-xxxx-xxxxxxxxx
PriceSchedules=[{'CurrencyCode': 'USD', 'Price': 0, 'Term': 1}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 2}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 3}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 4}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 5}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 6}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 7}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 8}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 9}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 10}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 11}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 12}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 13}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 14}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 15}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 16}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 17}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 18}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 19}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 20}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 21}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 22}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 23}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 24}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 25}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 26}, {'CurrencyCode': 'USD', 'Price': 0, 'Term': 27}]
```

In total, 27 schedules based on 27 months left.
Execution of create RI listing failed on error:
```
Code: InvalidInput
Message: The following parameters are missing 'Price Schedule for maximum month remaining(28) on lease
```

But then, I made exactly the same request next date, on the 1st of November 2023, and it was listed successfully. So why would 1 day difference make such a change? Especially if RI end date is not start of the month. The amount of months left should be about the same, less 1 day.

Documentation is very basic and doesn't mention anything useful.

Would be nice:
1. Please check why Listing API fails when there is a partial month. Can it be some special cases we should be aware of.
Could you please provide the exact example how we should calculate the period for a dates range we described in the example

### Expected Behavior

Listing API functionality is the same for both scenarios.
The documentation should consist an example that takes into consideration the partial months

### Current Behavior

Request fails in a matter of a few hours difference

### Reproduction Steps

Provided in the description step

### CLI version used

0.0.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
Hi @pasolid thanks for reaching out. We need more information in order to better understand this issue. Can you share the specific command you are running, and which CLI version you're using? Please provide debug logs as well (with any sensitive info redacted) by adding `--debug` to the command.

AWS CLI commands like [create-reserved-instances-listing](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-reserved-instances-listing.html) correspond to services APIs like the EC2 [CreateReservedInstancesListing](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateReservedInstancesListing.html) API. If you're seeing a parameter validation issue, then that is likely due to some requirement from the service API. The `InvalidInput` error is documented [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html), but I couldn't find the specific error message you referenced anywhere.

**Comment by pasolid** [comment]
Hey @tim-finnigan 
Yes, I was using [CreateReservedInstancesListing](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateReservedInstancesListing.html) API.

And I agree with you that the error is not descriptive enough and what even worse, there is no documentation of it anywhere.
The error code is `InvalidInput` but the message itself is unclear and I couldn’t find anywhere the meaning of this error message. So all I could do is to guess.

The issue is when prepare the amount of `--price-schedules`, its like AWS expects 1 more, but just a few hours later, it works fine and while I send same amount of schedules the request passes successfully.
 
 Maybe if there only was an exact example of how to calculate the `--price-schedules`, given the RI expiration date and the now date and the expected result, that would be a half a problem already.
 
AWS CLI version: `aws-cli/2.13.0 Python/3.11.4 Darwin/22.6.0 exe/x86_64 prompt/off`

**Comment by tim-finnigan** [comment]
Thanks for following up and for your patience here. For the issues related to the [CreateReservedInstancesListing](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateReservedInstancesListing.html) API documentation, please use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=EC2%20API&topic_url=http://docs.aws.amazon.com/en_us/AWSEC2/latest/APIReference/API_CreateReservedInstancesListing.html) to send feedback. Any updates to that documentation will automatically be pulled in to the [CLI command documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-reserved-instances-listing.html). (Also - there are [examples](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-reserved-instances-listing.html#examples) for this command including `--price-schedules` which may be helpful.)

For further assistance or to investigate a potential bug, please share your debug logs (with any sensitive info redacted) by adding `--debug` to your command.
