### ISSUE TITLE
data returned for aws elasticache describe-cache-clusters is incomplete

### ISSUE THREAD

**Issue by Dimitry1** [aws/aws-cli#8309]
### Describe the bug

aws elasticache describe-cache-clusters [ --show-cache-node-info] doesn't return cluser name but only nodes.

### Expected Behavior

Expect to find cluster name as part of the returned output.  It appears to be that ReplicationGroupId is mapped and used as cluster name.

### Current Behavior

there is no cluster name returned

### Reproduction Steps

aws elasticache describe-cache-clusters 

### Possible Solution

If ReplicationGroupId can be mapped and used as Cluster name then it should be documented and/or renamed

### CLI version used

aws-cli/2.13.12 Python/3.11.4 Linux/4.18.0-425.3.1.el8.x86_64 exe/x86_64.rhel.8 prompt/off

### Environment details (OS name and version, etc.)

rhel 8

**Comment by tim-finnigan** [comment]
Hi @Dimitry1 thanks for reaching out. 

The AWS CLI [describe-cache-clusters](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/describe-cache-clusters.html) command corresponds to the ElastiCache [DescribeCacheClusters](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html) API. If there is any issue with the API functionality, then we recommend reaching out through [AWS Support](https://aws.amazon.com/contact-us/) if you have a support plan. We can also escalate API issues to service teams. If your feedback relates to the documentation, then please use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?feedback_destination_id=68666466-6b49-4b2d-b91e-3ebc83e32250&topic_url=http://docs.aws.amazon.com/en_us/AmazonElastiCache/latest/APIReference/API_DescribeCacheClusters.html) links at the bottom of API documentation pages to reach the appropriate team.

I found there is a CLI example in the ElastiCache User Guide: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.ViewDetails.html. Is `CacheClusterId` the return value you are looking for?

I also saw that you referenced the `--show-cache-node-info` parameter, which can be used "to retrieve information about the individual cache nodes." If you pass `--no-show-cache-node-info` then do you get the expected results?
