### ISSUE TITLE
Should not be able to mv a remote file onto itself

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#831]
The current s3 mv command is essentially a `cp(src, dst) && rm(src)`.  Normally, if you aren't changing the object's metadata, storage class, website config, or encryption attrs you can't copy and object onto itself.  However, a multipart copy of an object onto itself will work, which happens if the object is over our multipart threshold size, which means that we will also delete the src file which is not what we want.

So we should be adding validation to ensure that we aren't trying to `mv` a file onto itself.

**Comment by rimutaka** [comment]
@jamesls , are you sure you fixed it? I've just run into this problem and ended up loosing a few hundred files.

**CLI command**:
```
aws s3 mv s3://my_bucket/Company/some_firm/dddfiles/Vehicle/ s3://my_bucket/Company/some_firm/dddfiles/Vehicle --exclude "*" --include "*.DDD" --recursive
```
**Output for one of the files**:
```
move: s3://my_bucket/Company/some_firm/dddfiles/Vehicle/M_20200804_0516_181AB1202_YV2XZ22G4JB843351.DDD to s3://my_bucket/Company/some_firm/dddfiles/Vehicle/M_20200804_0516_181AB1202_YV2XZ22G4JB843351.DDD
```
**CLI version**: `aws-cli/2.0.13 Python/3.7.7 Windows/10 botocore/2.0.0dev17`
