### ISSUE TITLE
S3 Bucket created in ap-south-2 location is breaking `aws s3` command

### ISSUE THREAD

**Issue by eldos-dl** [aws/aws-cli#8326]
### Describe the bug

Unable to use aws s3 commands with buckets created with `ap-south-2` as location. 

### Expected Behavior

When the following command is executed for a bucket situated in `ap-south-2` region, 
```
aws s3 ls s3://bucket-name
```

### Current Behavior

Getting the following error.
```
An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The ap-south-2 location constraint is incompatible for the region specific endpoint this request was sent to.
```

### Reproduction Steps

Create a bucket in Hyderabad region `ap-south-2`. Access it programatically using aws cli.

### Possible Solution

Add ap-south-2 in validation enums list.

### CLI version used

aws-cli/2.13.35 Python/3.11.6 

### Environment details (OS name and version, etc.)

Linux/6.2.0-36-generic exe/x86_64.ubuntu.22 prompt/off

**Comment by tim-finnigan** [comment]
Hi @eldos-dl thanks for reaching out. The issue here is likely that you're sending the request to a different region. Can you try running `aws s3 ls s3://bucket-name --region ap-south-2`?  

There are a few other ways you could configure the region as described in the CLI User Guide: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

**Comment by eldos-dl** [comment]
@tim-finnigan So for opt-in regions like `ap-south-2`, it is mandatory to mention the region option, unlike buckets in other regions where it is automatically inferred?

**Comment by tim-finnigan** [comment]
>@tim-finnigan So for opt-in regions like ap-south-2, it is mandatory to mention the region option, unlike buckets in other regions where it is automatically inferred?

Yes, that is my understanding based on the documentation and behavior I observed when testing.
