### ISSUE TITLE
Unable to use aws s3 sync

### ISSUE THREAD

**Issue by h0806449f** [aws/aws-cli#8329]
### Describe the bug

`aws s3 sync s3://test-bucket-for-sync-source s3://test-bucket-for-sync-destination`

can not proceed without turn on the "Transfer Acceleration"

<img width="1345" alt="截圖 2023-11-15 22 14 51" src="https://github.com/aws/aws-cli/assets/74322046/4bf208fb-e030-4e7e-8dd2-72b976395ee7">

### Expected Behavior

`copy s3://test-bucket-for-sync-source to s3://test-bucket-for-sync-destination`

and all object will from source bucket to destination bucket

### Current Behavior

fatal error: An error occurred (InvalidRequest) when calling the ListObjectsV2 operation: S3 Transfer Acceleration is not configured on this bucket

<img width="1345" alt="截圖 2023-11-15 22 14 51" src="https://github.com/aws/aws-cli/assets/74322046/4bf208fb-e030-4e7e-8dd2-72b976395ee7">

### Reproduction Steps

`aws s3 sync s3://test-bucket-for-sync-source s3://test-bucket-for-sync-destination`

### Possible Solution

turn on Transfer acceleration on both source bucket and destination bucket will fix the problem

### Additional Information/Context

Both my bucket in same AZ, I did not want to use Transfer acceleration.

The bucket created on today (2023/11/15) has this issue, if the source bucket and destination bucket are both created on 2023 April won't have this issue.

### CLI version used

aws-cli / 2.13.34

### Environment details (OS name and version, etc.)

AWS CloudShell

**Comment by h0806449f** [comment]
`aws s3 ls s3://test-bucket-for-sync-source` 
will get same error and ask for turn on S3 Transfer Acceleration.


![截圖 2023-11-16 12 15 04](https://github.com/aws/aws-cli/assets/74322046/2b8dbb35-50d3-45d3-a59b-a9ad28d11e24)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @h0806449f, thanks for reaching out.  Could you run `aws configure s3_use_accelerate_endpoint`?  If this value is true, then the CLI is trying to use S3 Transfer Acceleration endpoints for all S3 requests, even on buckets that don't have it enabled.  You can change this value to false with `aws configure set s3_use_accelerate_endpoint false`.  Hope that helps!

Relevant documentation : https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-examples.html

**Comment by h0806449f** [comment]
Thanks, problems solved.
Some instance behind AWS CloudShell set the .aws/config s3_use_accelerate_endpoint = true, some set this value as false

**Comment by h0806449f** [comment]
**Maybe the priority of default value and manual setting is wrong ?**


`cat ./.aws/config`
[default]
s3 = use_accelerate_endpoint = true
s3_use_accelerate_endpoint = false

will cause
`fatal error: An error occurred (InvalidRequest) when calling the ListObjectsV2 operation: S3 Transfer Acceleration is not configured on this bucket `


Have to reset default value by using
`aws configure set default.use_accelerate_endpoint false`
can fix the fatal error

**Comment by RyanFitzSimmonsAK** [comment]
Adding `default.` is specifying that you want to change these settings for the profile named default.  

`s3 = use_accelerate_endpoint = true` is under the `s3` key, and can be modified with the syntax `aws configure set s3.use_accelerate_endpoint false`.  More information can be found [here](https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html).  

`s3_use_accelerate_endpoint = false` is under the name of the profile, and can be modified with the syntax `aws configure set s3_use_accelerate_endpoint false`.  

It looks like the `s3` key takes priority if both are set.
