### ISSUE TITLE
Incremental backups with S3 buckets

### ISSUE THREAD

**Issue by jmreicha** [aws/aws-cli#833]
Is there a way to do incremental backups with the aws-cli in its current form?

Basically, I am looking for a way to use one bucket as a long term backup area for another bucket.  It looks like sync won't work if it works the way I understand it to - if it is keeping buckets synchronized it won't work.

Is there maybe an option to either pass to the aws-cli sync or cp command that can tell it to skip over files that are already contained in the backup bucket if the file is recognized as already existent.

If this won't work, what would be the best way to solve this problem?

**Comment by multitask123** [comment]
I had to solve this problem and created a commercial app for Windows called BucketBacker. It can help you create set & forget scheduled backups of all your buckets. You can try it free for 2 weeks at bucketbacker.com

**Comment by GordonVi** [comment]
7 years, 9 months, 9 days later....  

Was hoping this still existed or was maintained. Gone.

**Comment by lenage** [comment]
9 years
