### ISSUE TITLE
[v2] [autoscaling] [start-instance-refresh] Support parameter in Preferences: "MaxHealthyPercentage"

### ISSUE THREAD

**Issue by p24-max** [aws/aws-cli#8338]
### Describe the feature

Within the AWS console (EC2-Autoscaling Instance-Refresh), it is possible to specify a MaxHealthyPercentage during an instance refresh.

This is how the "preferences" look like in CloudTrail when performing an instance refresh from AWS management console:
```
"requestParameters": {
    "autoScalingGroupName": "Web-2023102407231962040000000c",
    "preferences": {
        "standbyInstances": "Ignore",
        "minHealthyPercentage": 100,
        "scaleInProtectedInstances": "Ignore",
        "autoRollback": false,
        "skipMatching": false,
        "maxHealthyPercentage": 110
    }
},
```

With AWS CLI v2, it is not possible to specify the MaxHealthyPercentage, so please add support for it.

### Use Case

Use the new Instance replacement method

![image](https://github.com/aws/aws-cli/assets/106059119/2dc06ea0-667d-4c3c-a75b-63d641e59e55)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/2.13.36 Python/3.11.6 Darwin/23.1.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS m-chip

**Comment by tim-finnigan** [comment]
Hi @p24-max thanks for reaching out. It looks like `MaxHealthyPerecentage` was just added in version 2.13.37 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/66af26fd0de98269959b5d570ebfd91e8018faef/CHANGELOG.rst?plain=1#L15) (and in [1.30.1](https://github.com/aws/aws-cli/blob/b3606285d50763600ebdda325375eb931214661d/CHANGELOG.rst?plain=1#L80) for v1), and is in the [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/autoscaling/start-instance-refresh.html):

> MaxHealthyPercentage -> (integer)
> 
> Specifies the maximum percentage of the group that can be in service and healthy, or pending, to support your workload when replacing instances. The value is expressed as a percentage of the desired capacity of the Auto Scaling group. Value range is 100 to 200.
> 
> If you specify `MaxHealthyPercentage` , you must also specify `MinHealthyPercentage` , and the difference between them cannot be greater than 100. A larger range increases the number of instances that can be replaced at the same time.
> 
> If you do not specify this property, the default is 100 percent, or the percentage set in the instance maintenance policy for the Auto Scaling group, if defined.


The updated service API models are in [1.32.1+](https://github.com/boto/botocore/blob/91a9d897843535c56a0c02813bd182e4f3335525/CHANGELOG.rst?plain=1#L82) of Botocore, which will update when you [update your version of the CLI](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).
