### ISSUE TITLE
reopen https://github.com/aws/aws-cli/issues/5564

### ISSUE THREAD

**Issue by ElijahLynn** [aws/aws-cli#8346]
### Describe the bug

reopen https://github.com/aws/aws-sdk/issues/647

### Expected Behavior

reopen https://github.com/aws/aws-sdk/issues/647

### Current Behavior

reopen https://github.com/aws/aws-sdk/issues/647

### Reproduction Steps

reopen https://github.com/aws/aws-sdk/issues/647

### Possible Solution

reopen https://github.com/aws/aws-sdk/issues/647

### Additional Information/Context

reopen https://github.com/aws/aws-sdk/issues/647

### CLI version used

reopen https://github.com/aws/aws-sdk/issues/647

### Environment details (OS name and version, etc.)

reopen https://github.com/aws/aws-sdk/issues/647

**Comment by tim-finnigan** [comment]
> ### Describe the bug
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Expected Behavior
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Current Behavior
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Reproduction Steps
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Possible Solution
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Additional Information/Context
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### CLI version used
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)
> ### Environment details (OS name and version, etc.)
> 
> reopen [aws/aws-sdk#647](https://github.com/aws/aws-sdk/issues/647)

Thanks for reaching out. I have reopened and [commented](https://github.com/aws/aws-sdk/issues/647#issuecomment-1821955134) on that issue. Please refer to that issue for updates going forward.
