### ISSUE TITLE
AWS logging of paths still broken

### ISSUE THREAD

**Issue by smacdonald-ppo** [aws/aws-cli#8383]
### Describe the bug

https://github.com/aws/aws-cli/issues/2530

A) It isn't a feature request, it's a bug.
B) Github's text says to reopen the bug, but I don't appear to have that permission.

Still present 6 years after inital report; should be a small and easy fix.

### Expected Behavior

The paths as supplied are logged. See https://github.com/aws/aws-cli/issues/2530#issuecomment-302465043

### Current Behavior

Relative paths are always logged, regardless of what the user specified on the command line.

### Reproduction Steps

Perform any `aws s3 ...` operation that moves a file from local to S3; when the local file is specified via an absolute path.

### Possible Solution

https://github.com/aws/aws-cli/issues/2530#issuecomment-302465043

Log the paths as supplied by the user.

### Additional Information/Context

https://github.com/aws/aws-cli/issues/2530

I checked the Changelog, this isn't fixed in any newer version.

### CLI version used

aws-cli/2.7.33 Python/3.9.11 Linux/4.19.0-5-amd64 exe/x86_64.debian.10 prompt/off

### Environment details (OS name and version, etc.)

Linux Mint 20

**Comment by tim-finnigan** [comment]
Hi @smacdonald-ppo thanks for reaching out. I was not able to reproduce this issue as described. Could you provide your debug logs (with any sensitive info redacted) by adding `--debug` to your command? That may help with further understanding the issue.

Also 2.7.33 is quite an old version - the latest version is 2.14.6 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1). I tested on both versions and couldn't reproduce the issue, so I'm not sure if there were any specific changes related to this between versions, but regardless we recommend using a more up-to-date version for access to the latest fixes and capabilities.

**Comment by smacdonald-ppo** [comment]
Hi @tim-finnigan ,

Sorry for the delay; I was on vacation for large parts of the last few weeks.

Here's my test:
``` studog@laptop:~$ aws --version
aws-cli/2.13.10 Python/3.11.4 Linux/6.2.0-39-generic exe/x86_64.linuxmint.21 prompt/off
studog@laptop:~$ aws s3 cp /home/studog/test.txt s3://test-bucket
upload: ./test.txt to s3://test-bucket/test.txt ```

Note the "upload" output line lists `./test.txt` . Expected `/home/studog/test.txt` instead.

My original report was on an older client due to being on one of many virtual environments. This is with a newer but not newest client.

**Comment by smacdonald-ppo** [comment]
@tim-finnigan Still occurring with the latest:

```
studog@laptop:~$ aws --version
aws-cli/2.15.8 Python/3.11.6 Linux/6.2.0-39-generic exe/x86_64.linuxmint.21 prompt/off
studog@laptop:~$ aws s3 cp /home/studog/test.txt s3://test-bucket
upload: ./test.txt to s3://test-bucket/test.txt
```

**Comment by smacdonald-ppo** [comment]
I can upload the `--debug` output if you _really_ need it, but it'll take me some time to redact.

**Comment by darshanip** [comment]
@tim-finnigan, I'm happy to create a PR for this. Are we expecting absolute path? Could not find conclusion in discussions.

**Comment by tim-finnigan** [comment]
Thanks for your patience, I think we're still waiting on more details here such as debug logs and steps to reproduce.
