### ISSUE TITLE
Error when copying to s3

### ISSUE THREAD

**Issue by mattf10** [aws/aws-cli#8384]
### Describe the bug

Since updating to the latest version (aws-cli/2.14.5 Python/3.11.6 Linux/5.15.0-89-generic exe/x86_64.ubuntu.22 prompt/off), I can no longer copy to s3 via the command line.    The error is:

module '_awscrt' has no attribute 's3_is_crt_s3_optimized_for_system'

### Expected Behavior

I expected files to be copied to s3 bucket

### Current Behavior

Files are not copied

### Reproduction Steps

From the comman line, issue the following command:

aws s3 cp 'path to folder' s3://'bucket' --recursive

### Possible Solution

Problem started happening after upgrading aws-cli v2 to latest version (2.14.5)

### Additional Information/Context

Same problem started happening this morning on two different VPS, both updated to this version before running s3 cp command (other VPS on older versions are fine).

Using previous version (2.13.38) fixes the problem.

### CLI version used

2.14.5

### Environment details (OS name and version, etc.)

Ubuntu 22.04.3

**Comment by ghnp5** [comment]
Getting the same here, but for `ls`:

`aws s3 ls --recursive s3://bucket-xyz/path-xyz/`

**Comment by fkhn** [comment]
Same error for s3 sync
# aws --version  => aws-cli/2.14.5 Python/3.11.6 Linux/6.1.0-13-amd64 exe/x86_64.debian.12 prompt/off

**Comment by mattf10** [comment]
I don't have awscrt installed - it's never been needed until now.   To confirm, I download the latest version of awscli via curl, like so `curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"`. 

So you're saying that this method is no longer sufficient, and that I now need to install pip and also add/update the awscrt package?    If this is a required package, shouldn't it be included in the awscli zip?

Thanks

**Comment by tim-finnigan** [comment]
Thanks for following up. How did you install/update the AWS CLI? Have you tried reinstalling the AWS CLI using one of the [officially supported methods](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) linked earlier? [Here](https://github.com/aws/aws-cli/blob/fb2c527d231b30394d3d31dbff9cef6709950bb7/pyproject.toml#L42C9-L42C9) is where the the version floor was bumped for `awscrt`. Installing/updating the AWS CLI should install the required dependency version unless you're pinning to an earlier version.

**Comment by corybryant** [comment]
@tim-finnigan  That is the officially supported method that was linked. The zip file is the pre-compiled binary containing three `.so` files for awscrt. Dealing with dependencies on our end is not the officially recommended method.

**Comment by corybryant** [comment]
Version 2.14.4 is working correctly. 2.14.5 does  not list any changes for awscrt in the changelog.

Also, the signature file for the officially supported install method has expired so we can't run verification checks when installing/updating the CLI.

**Comment by corybryant** [comment]
Nothing else installed, Alma Linux 8:

# aws --version
aws-cli/2.14.5 Python/3.11.6 Linux/4.18.0-477.27.2.el8_8.x86_64 exe/x86_64.almalinux.8 prompt/off


/bin/curl -s -o awscliv2.sig https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig
/bin/curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
/bin/gpg --verify awscliv2.sig awscliv2.zip && /bin/unzip -uo awscliv2.zip && ./aws/install --update

**Comment by corybryant** [comment]
It seems our automated system tool is leaving the `aws` install directory around and unzipping on top of it when it's time to update so something in 2.14.5 must be conflicting with an old version. Clearing out the install directory and doing a full reinstall seems to have fixed the `s3_is_crt_s3_optimized_for_system` error for us.

I can open a new issue for the expired SIG file.

**Comment by ghnp5** [comment]
> It seems our automated system tool is leaving the aws install directory around and unzipping on top of it when it's time to update so something in 2.14.5 must be conflicting with an old version. Clearing out the install directory and doing a full reinstall seems to have fixed the s3_is_crt_s3_optimized_for_system error for us.


Looks like that was it for me, too!! Thanks!

Added `rm -rf aws` to the update script,  
then also cleared `/usr/local/aws-cli/v2/` so I could re-install the same version,
and looks like I'm no longer getting the issue.

**Comment by tim-finnigan** [comment]
Thanks for letting us know, glad you were able to resolve the issue. @mattf10 can you confirm if removing the aws install directory solves the issue for you as well?

**Comment by fkhn** [comment]
it does for me. thanks.

**Comment by mattf10** [comment]
@tim-finnigan   Yes.   After first removing all versions from the install directory, then installing the latest version (2.14.5), I can now issue commands without the error.

Related:  https://github.com/aws/aws-cli/issues/5979.    Over time, the install directory becomes huge (it was > 10G on my VPS).   I added the following code to the end of my update script to fix: `find /usr/local/aws-cli/v2/ -maxdepth 1 -type d -mtime +14 -exec rm -fr {} \;` - removes all versions more than 2 weeks old.

I suggest that the officially support update method add 'rm -fr' to a)  avoid the old dependency problem and b) not to take up disk space.  Or some flag to that effect.

Thanks

**Comment by ghnp5** [comment]
> Related: #5979. Over time, the install directory becomes huge (it was > 10G on my VPS). I added the following code to the end of my update script to fix: `find /usr/local/aws-cli/v2/ -maxdepth 1 -type d -mtime +14 -exec rm -fr {} \;` - removes all versions more than 2 weeks old.

Yeah, I had noticed this a few months ago, and had to do add a similar command to all my servers!

**Comment by mattf10** [comment]
Hi - this is still a problem on all of my VPS that use version 2.14.5.   I cleared all old versions and tested by checking with 'aws s3 ls' on a bucket.  This command worked so I thought the issue was fixed.

However, my nightly back-ups failed to run with the original error message.   So there must be some other reason why the 'awscrt' lib is missing or outdated.

The command that fails is: `aws s3 cp 'path to folder' s3://'bucket' --recursive`.

The error message is: `module '_awscrt' has no attribute 's3_is_crt_s3_optimized_for_system'`

The awscli version is:  aws-cli/2.14.5 Python/3.11.6 Linux/5.15.0-89-generic exe/x86_64.ubuntu.22 prompt/off

Server version:  Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic x86_64)

The commands used to update awscli:  
`unzip -oq awscliv2.zip 
./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update`


Please check the latest zip to see why the awscrt package is missing or outdated.

**Comment by mattf10** [comment]
Today I upgraded to the latest version 2.15.0 and I can now run aws s3 commands as normal.

**Comment by cash168** [comment]
I encountered the same problem when I didn’t notice that the old version of aws-cli had previously been unpacked into the aws directory
Run **rm -rf aws** before **unzip -oq awscliv2.zip**
