### ISSUE TITLE
AWS_ERROR_S3_INVALID_RESPONSE_STATUS: Invalid response status from request when uploading from pipe

### ISSUE THREAD

**Issue by danylohetmantsev** [aws/aws-cli#8404]
### Describe the bug

Im using tar to create a compressed bundle and upload it to S3. On classic client it works, on CRT it fails at 78.1GB with an error
AWS_ERROR_S3_INVALID_RESPONSE_STATUS: Invalid response status from request.
I've tried to upload the pre-generated and packed tar archived and it succeeded.

### Expected Behavior

upload finishes.

### Current Behavior

upload fails at 78.1GB.

### Reproduction Steps

generate a ~100gb chunk of data and compress it into tar, use that pipe to transfer data to S3.
(i did that with dd if=/dev/zero of=file bs=1M count=102400)

tar -c -I pigz -C /folder/ . | pv | aws s3 cp --debug --expected-size 1319413953331 - s3://bucket-name/a.tar

### Possible Solution

-

### CLI version used

aws-cli/2.15.0 Python/3.11.6 Linux/4.14.268-205.500.amzn2.x86_64 exec-env/AWS_ECS_EC2 exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

ubuntu 22

**Comment by BurtPer** [comment]
This seems very similar to #8435?

**Comment by RyanFitzSimmonsAK** [comment]
Hi @danylohetmantsev, thanks for reaching out and for your patience.  What instance type are you trying to upload to?  The mention issue (https://github.com/aws/aws-cli/issues/8435) does look similar, so could you also verify the region of the bucket and the region you're making the request from.  Debug logs would be helpful here; you can get debug logs by adding `--debug` to your command, and redacting any sensitive information.  Thanks!
