### ISSUE TITLE
aws s3 sync gets NoSuchKey error when key contains ® character

### ISSUE THREAD

**Issue by pdc** [aws/aws-cli#841]
I am using `aws s3 sync s3://SRC s3://DST` to duplicate one bucket in to another. It goes fine except for objects with keys like `profile-images/00/16/51,8f3c060,Dean_Weston_Teeshirt_Pose®-croppable.jpeg`, which gets the following error message:

> copy failed: s3://photocrowdstatic/profile-images/00/16/51,8f3c060,Dean_Weston_Teeshirt_Pose®-croppable.jpeg to s3://static.photocrowd.com/profile-images/00/16/51,8f3c060,Dean_Weston_Teeshirt_Pose®-croppable.jpeg A client error (NoSuchKey) occurred when calling the CopyObject operation: The specified key does not exist.

My guess is the ® character is being differently %-encoded in different places.

**Comment by gmtreacy** [comment]
Are people still using AWS cli or has it been deprecated?

**Comment by szeitlin** [comment]
I'm seeing this error too. We're still using AWS cli.
