### ISSUE TITLE
`The provided token is malformed or otherwise invalid`, accessing optional region

### ISSUE THREAD

**Issue by peteristhegreat** [aws/aws-cli#8413]
### Describe the bug

I opened up a region for an account in my AWS Organization, e.g. ap-east-1 (Hong Kong) for my non-root account,
then I try to run awscli commands against it, I get:

```
aws --profile other --region ap-east-1 ecr describe-repositories

An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
```

I updated my awscli to the latest
```
aws --version
aws-cli/2.15.1 Python/3.11.6 Linux/4.14.193-149.317.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off
```

And tried again, same error.  Other regions work, and going back to ap-east-1 didn't. After consulting a co-worker, we checked IAM permission propagation into the region and saw something off there (maybe related, maybe not), and then cleared the token cache for the cli.
```
rm ~/.aws/cli/cache/*.json
```
After clearing the cache, if I first try to hit the new region, it fails, BUT if I go to a known region then to the new region it successfully gets a token and future commands to the new region works.

```
aws --profile other --region ap-east-1 sts get-caller-identity   # fails (after clearing token cache)
aws --profile other --region us-east-1 sts get-caller-identity   # succeeds
aws --profile other --region ap-east-1 sts get-caller-identity   # succeeds
```

So now as a work around for my scripts, if I am accessing an optional region first, I am adding a token pull from `us-east-1` before attempting calls to the optional region.

### Expected Behavior

A call such as 
```
aws --profile other --region ap-east-1 sts get-caller-identity
```
to an optional region should work on the first try and not require me to get a token with another command first.

### Current Behavior

I opened up an optional region for one account, and cli commands fail to get a token.

I updated awscli and I found I could get it to work with a new token only if I hit a region that my root account had already, e.g. us-east-1.  Then I could do commands against the optional region.

### Reproduction Steps

# open up an optional region on a non-root account for your org
# that account's profile will be "other" in this example
[ec2-user@ip-xxx-xx-xx-xx ~]$ rm ~/.aws/cli/cache/*.json
[ec2-user@ip-xxx-xx-xx-xx ~]$ aws --profile other --region ap-east-1 sts get-caller-identity

An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
[ec2-user@ip-xxx-xx-xx-xx ~]$ aws --profile other --region us-east-1 sts get-caller-identity
{
    "UserId": "XXXXX:botocore-session-YYYYY",
    "Account": "XX-other-account-XX",
    "Arn": "arn:aws:sts::XX-other-account-XX:assumed-role/MyRole/botocore-session-YYYYY"
}
[ec2-user@ip-xxx-xx-xx-xx ~]$ aws --profile other --region ap-east-1 sts get-caller-identity
{
    "UserId": "XXXXX:botocore-session-YYYYY",
    "Account": "XX-other-account-XX",
    "Arn": "arn:aws:sts::XX-other-account-XX:assumed-role/MyRole/botocore-session-YYYYY"
}

### Possible Solution

On a failure to get an initial token from an optional region, print a better warning or get a valid token from the root account beforehand.

### CLI version used

 aws-cli/2.15.1 Python/3.11.6 Linux/4.14.193-149.317.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off

### Environment details (OS name and version, etc.)

MacOS 13.0 and on Amazon Linux 2 x86_64

**Comment by RyanFitzSimmonsAK** [comment]
Hi @peteristhegreat, thanks for reaching out.  Could you provide debug logs of this process?

> aws --profile other --region ap-east-1 sts get-caller-identity   # fails (after clearing token cache)
aws --profile other --region us-east-1 sts get-caller-identity   # succeeds
aws --profile other --region ap-east-1 sts get-caller-identity   # succeeds

You can get debug logs by adding `--debug` to your command, and redacting any sensitive information.  Thanks!

**Comment by peteristhegreat** [comment]
@RyanFitzSimmonsAK Thanks for the reply.
I redacted signatures, account numbers, keys, etc.
[sts-debug.log](https://github.com/aws/aws-cli/files/13690211/sts-debug.log)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @peteristhegreat, thanks for following up.  I was not able to reproduce the issue.  After clearing the cache, my first `aws sts get-caller-identity` call to an opt-in region succeeded.  Could you tell me more about the role you are trying to assume?  Is this a cross-account role?  If so, does that other account have the same opt-in region enabled?

**Comment by peteristhegreat** [comment]
Our terraform scripts were unable to function due to this issue, so we added the optional region to our "root" or billing account, and then the issue went away.  Now I can clear my cli cache json files and do the sts get-caller-identity and it works on the first try.

So in summary (according to my testing), to use an optional region consistently, the account where your IAM user lives seems to need to have that optional region for that account, too, to easily get the tokens for the cross account calls to the optional region.

@RyanFitzSimmonsAK I don't think I can recreate it easily now since adding the optional region to our root account, but the layout of the accounts and IAM before was something like:

root account (123)
  - in us-east-1
  - did NOT have optional region ap-east-1 enabled
  - had my username as an IAM user

other account (345), in the AWS Organization of 123
 - intended to be used in ap-east-1
 - did have the optional region ap-east-1 enabled
 - had my username arn as a trusted relationship in the policies for a cross account role

**Comment by RyanFitzSimmonsAK** [comment]
Glad you have it working now.  Requiring the region to be enabled for both accounts feels like intended behavior, and the `RegionDisabled` error from the [API reference](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) would also indicate that, although I'm unsure why you didn't get that error back.  Do you have any other questions?

**Comment by peteristhegreat** [comment]
No other questions.  Thanks for the attention on the issue.  I suspect someone else may run across this and now a search engine might find this thread in the future.  Needing the optional region is both accounts appears to be the intended design.

Another option could be when you enable an "optional region" in the console or elsewhere, the console could show a recommendation to also "enable the region for accounts where your IAM user lives" to avoid token issues.

Feel free to close the issue.
