### ISSUE TITLE
Segmentation fault on alpine 19

### ISSUE THREAD

**Issue by cloudcode-hungary** [aws/aws-cli#8423]
### Describe the bug

Any command run under alpine 3.19 results in segmentation error.

```
aws --version
Segmentation fault (core dumped)
```

Alpine linux 3.19 has been included in docker images just recently, definietly related.

### Expected Behavior

Works fine under the latest alpine image.

### Current Behavior

Crashes with segmentation fault

### Reproduction Steps

It can be reproduced in a docker image.

```
FROM docker:dind

RUN curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip \
    && unzip awscliv2.zip \
    && aws/install \
    && rm -rf \
        awscliv2.zip \
        aws \
        /usr/local/aws-cli/v2/*/dist/aws_completer \
        /usr/local/aws-cli/v2/*/dist/awscli/data/ac.index \
        /usr/local/aws-cli/v2/*/dist/awscli/examples

RUN aws --version
# errorSegmentation fault (core dumped)
```

Chaging the source image: `FROM docker:24.0.7-dind-alpine3.18` and everything works fine.

### CLI version used

aws-cli/2.13.29 Python/3.11.6 Linux/6.2.0-39-generic exe/x86_64.alpine.3 prompt/off

### Environment details (OS name and version, etc.)

Alpine linux 3.19 (official docker:dind image)

**Comment by LadaVarga** [comment]
Hello,
This version is used on CircleCI when we use aws-s3 orb. Is there any workaround for this.

**Comment by ale-munozarancibia** [comment]
Hi, I found the same segmentation fault problem using Fedora Linux 35 x86-64.

**Comment by RyanFitzSimmonsAK** [comment]
Hi, thanks for reaching out and for your patience.  If it produces meaningful logging before the error, could you provide debug logs of a command resulting in a segmentation fault?  You can get debug logs by adding `--debug` to the command.  Thanks!

**Comment by ale-munozarancibia** [comment]
Thanks @RyanFitzSimmonsAK! I ran `/usr/local/bin/aws --version --debug` but did not get any logs, only output was `Segmentation fault (core dumped)`

**Comment by timothybonci** [comment]
I'm getting seg fault on install, and if I try and run "install --debug", I get "Got an unexpected argument: --debug"

**Comment by cloneluke** [comment]
bump this, I got the error also and did some investigating


on Dec 7, 3.19 alpine came out

[Docker Hub](https://hub.docker.com/_/alpine/tags)


 
![00c673c8-41dd-4e8d-a562-ab66484b1a11](https://github.com/aws/aws-cli/assets/6568361/2d2a2bfc-064f-4a74-8bd7-cd319b39acb1)


terraform uses the latest alpine in its docker hub image here:

[terraform/Dockerfile at 53c34ff49cfbc1f70d7cdd3dca8040551c53737a · hashicorp/terraform (github.com)](https://github.com/hashicorp/terraform/blob/53c34ff49cfbc1f70d7cdd3dca8040551c53737a/Dockerfile#L13)
![image-20240129-192345](https://github.com/aws/aws-cli/assets/6568361/54df4686-249b-4b4f-81e0-1320e6cd4df3)


 

terraform 1.66 came out on dec 13 and built on alpine 3.19

[Tags · hashicorp/terraform (github.com)](https://github.com/hashicorp/terraform/tags)

![fc236446-c94f-42b6-8e9c-2b8a2eb4c7f4](https://github.com/aws/aws-cli/assets/6568361/16ae868c-ddb9-4fec-be64-6084e8f766ed)


I got the error using the above docker hub image in circle ci which is based on alpine 3.19

![image](https://github.com/aws/aws-cli/assets/6568361/1723e859-ba88-47e2-bd39-4d4ce2a31378)

**Comment by kimyu92** [comment]
Running into same issues

**Comment by elliot** [comment]
Could be an issue with the linker

```
cbf3a00de678:~# ldd /usr/local/bin/aws
	/lib64/ld-linux-x86-64.so.2 (0x7f5f68ffc000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f5f68ffc000)
	libz.so.1 => /lib/libz.so.1 (0x7f5f68fe2000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f5f68ffc000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f5f68ffc000)
Error relocating /usr/local/bin/aws: __strcat_chk: symbol not found
Error relocating /usr/local/bin/aws: __snprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __vfprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __realpath_chk: symbol not found
Error relocating /usr/local/bin/aws: __strdup: symbol not found
Error relocating /usr/local/bin/aws: __memcpy_chk: symbol not found
Error relocating /usr/local/bin/aws: __vsnprintf_chk: symbol not found
Error relocating /usr/local/bin/aws: __strcpy_chk: symbol not found
Error relocating /usr/local/bin/aws: __fprintf_chk: symbol not found
```

**Comment by cloneluke** [comment]
if you are on circleci, using the aws cli orb and can go to the latest aws cli 2.13.25 , then you can upgrade your orb:

https://github.com/CircleCI-Public/aws-cli-orb/releases/tag/v4.1.3

@otremblay and @brentmmarks helped fix the orb that had a workaround before for alpine: 

https://github.com/CircleCI-Public/aws-cli-orb/commit/c5a792edba329bfeecc835a1920ee578e6348a65

of specific interest:

![image](https://github.com/aws/aws-cli/assets/6568361/bc7c4897-1f27-41d6-a8dc-e4d8fe75d968)


https://github.com/CircleCI-Public/aws-cli-orb/commit/c5a792edba329bfeecc835a1920ee578e6348a65#diff-f844f8b30ba3e4871302ed76f5c918662bd1e96e57fb7c10ff0cade4ad9e355aL17-L33

upgrade of orb:

![image](https://github.com/aws/aws-cli/assets/6568361/a88acbb3-07a3-416e-adda-635caefcba4f)

also this old issue shows that same method of install here:

apk add --no-cache aws-cli

https://github.com/aws/aws-cli/issues/4971

**Comment by tim-finnigan** [comment]
Please refer to the documentation to [Build and install the AWS CLI from source](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html) for this use case. As noted there, Alpine Linux uses [musl](https://musl.libc.org/), but the current installers require `glibc` causing the pre-built installers to not immediately work. But this approach works for me:
```python3
FROM python:3.11-alpine3.19 AS builder

ENV AWSCLI_VERSION=2.17.21

RUN apk add --no-cache \
    curl \
    make \
    cmake \
    gcc \
    g++ \
    libc-dev \
    libffi-dev \
    openssl-dev \
    && curl https://awscli.amazonaws.com/awscli-${AWSCLI_VERSION}.tar.gz | tar -xz \
    && cd awscli-${AWSCLI_VERSION} \
    && ./configure --prefix=/opt/aws-cli/ --with-download-deps \
    && make \
    && make install

FROM python:3.11-alpine3.19

RUN apk --no-cache add groff

COPY --from=builder /opt/aws-cli/ /opt/aws-cli/

ENTRYPOINT ["/opt/aws-cli/bin/aws"]
```
