### ISSUE TITLE
aws-cli s3 Handling "file voids" issue advisory(short issue description)

### ISSUE THREAD

**Issue by csy97** [aws/aws-cli#8427]
### Describe the bug

I found that when uploading a "hole file' file via aws s3 cp, I was spending a lot more traffic than I actually was.
Although I had a total of 500GB for this file, it actually only took up 5.2GB of storage, but when I uploaded this file it took a long time to finish uploading (because he uploaded the entire 500GB of data).
$ ll centos6.raw
-rw-r--r-- 1 root root 536870912000 Dec 22 07:49 centos6.raw
$ du -sh . /centos6.raw
5.2G . /centos6.raw
$ aws s3 cp . /centos6.raw s3://siyuan-test
Completed 222.6 GiB/500.0 GiB (130.4 MiB/s) with 1 file(s) remaining
upload: . /centos6.raw to s3://siyuan-test/centos6.raw

I also see only 5.2Gb of space occupied in the daily metrics for S3, and I'm not sure why the upload requires 500GB of data. I don't think aws-cli should handle "hole file" this way, but only upload 5.2GB of data. Can anyone help me with this question.

### Expected Behavior

Being able to correctly Handling of "hole file" files

### Current Behavior

Uploading files with "hole file" takes too much traffic and

### Reproduction Steps

1, create a "hole" file
$ truncate -s 200M testfile
$ ll testfile
-rw-r--r-- 1 root root 209715200 Dec 22 09:12 testfile
$ du -sh testfile
0 testfile
2. Upload the "hole file" file to S3 via aws-cli.
$ aws s3 cp testfile s3://test222
upload: . /testfile to s3://test222/testfile

### CLI version used

aws --version aws-cli/1.22.34 Python/3.10.12 Linux/6.2.0-1015-aws botocore/1.23.34

### Environment details (OS name and version, etc.)

Any OS can reproduce the problem (I'm using ubuntu 22.04)

**Comment by tim-finnigan** [comment]
Thanks for reaching out and for your patience here. I saw that you're using version 1.22.34 of the AWS CLI which is very old. Have you tried [migrating to v2](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html), or at least using a more recent version of v1? (The lastest v1 version is 1.32.80 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1)).

I'm not familiar with the issue or use case that you described. If you still see an issue after updating, please provide more information to help us with investigating, such as the complete steps to reproduce and the logs (by adding `--debug` to your command) with any sensitive info redacted.
