### ISSUE TITLE
s3 copy failed 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by lrowe** [aws/aws-cli#845]
Syncing a bucket of WAL-E backups to a new empty bucket in another region (N. California to Oregon) I'm seeing the copy fail for approximately 1 in 10 of the ~1GB backup files and maybe 1 in 50 of the smaller files, always with the same error:

```
copy failed: s3://bucket1/production/basebackups_005/base_000000010000003400000085_00000040/tar_partitions/part_0.tar.lzo to s3://bucket2/production/basebackups_005/base_000000010000003400000085_00000040/tar_partitions/part_0.tar.lzo
'NoneType' object is not iterable
```

Command used:

```
$ aws --profile myprofile s3 sync s3://bucket1/ s3://bucket2/
```

Versions:
- Mac OS 10.9.4
- System Python 2.7.5
- awscli 1.3.14
- botocore 0.48.0

**Comment by sekroots** [comment]
Hello, How can I solve this? I am facing this trying to use a aws s3 cp
