### ISSUE TITLE
IAM Identity Center list-applications is not working 

### ISSUE THREAD

**Issue by dev-travelex** [aws/aws-cli#8474]
### Describe the bug

Referring to this documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso-admin/list-applications.html

My CLI version is 

`aws-cli/2.9.17 Python/3.9.11 Windows/10 exe/AMD64 prompt/off`

### Expected Behavior

Should be as documented here : https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sso-admin/list-applications.html

### Current Behavior

```
aws sso-admin list-applications

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument operation: Invalid choice, valid choices are:
```

### Reproduction Steps

Run the above command where IAM Identity center is set-up with applications registered.

### CLI version used

aws-cli/2.9.17 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows/10 exe/AMD64 prompt

**Comment by RyanFitzSimmonsAK** [comment]
Hi @dev-travelex, thanks for reaching out.  I believe this is an issue with the version of the AWS CLI you're using.  I'm not certain why it's not documented in the changelog, but as far as I can tell, the ListApplication operation was added in CLI version `2.13.37`.  Please update to that version or higher, and let me know how that goes.  Thanks!

**Comment by dev-travelex** [comment]
Thanks, will check it soon and update here.

**Comment by dev-travelex** [comment]
@RyanFitzSimmonsAK : Updated the CLI and it is working now. Thank you!
