### ISSUE TITLE
Add CHANGELOG entry for OpenSSL `1.1.1y`

### ISSUE THREAD

**Issue by alex-rowe** [aws/aws-cli#8485]
### Describe the issue

The Linux ARM/aarch64 version of AWS CLI v2 in `2.15.11` has OpenSSL 1.1.1u in both `dist/libcrypto.so.1.1` and `dist/libssl.so.1.1`

Can this be updated to OpenSSL 1.1.1x?

I only found this one the aarch64 version, the files don't exist in the Linux x86_64 version.

### Additional Information/Context

None in the x86_64 zip file:

```
% curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
% unzip awscliv2.zip
% ls -l aws/dist | grep "libcrypto\|libssl" | wc -l
       0
```

Version in the aarch64 zip file:

```
% curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
% unzip awscliv2.zip
% strings aws/dist/libcrypto.so.1.1 | grep "^OpenSSL 1.1.1" 
OpenSSL 1.1.1u  30 May 2023
```

### CLI version used

2.15.11

### Environment details (OS name and version, etc.)

Linux aarch64

**Comment by alex-rowe** [comment]
In release `2.15.25` it has a changelog for:

```
* enhancement:openssl: Update bundled openssl version to 1.1.1w
```

That resolves one of our issues with the `1.1.1v` release, but not the issue with upgrading it to `1.1.1x`.

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue. Running your script now results in `OpenSSL 1.1.1x  30 Jan 2024`. A [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) entry just needs to be added similar to in https://github.com/aws/aws-cli/pull/7614 and https://github.com/aws/aws-cli/pull/7991. I'll update this issue title to reflect that.

**Comment by alex-rowe** [comment]
Hi @tim-finnigan Thanks for getting this up to `1.1.1x`. Tenable is now producing vulnerabilities for versions before `1.1.1y` in https://www.tenable.com/plugins/nessus/192965.

Are there plans to move from `x` to `y` soon?

**Comment by tim-finnigan** [comment]
1.1.1y supported now as noted in CHANGELOG: https://github.com/aws/aws-cli/pull/8773/files, will close this as resolved.
