### ISSUE TITLE
AWS CLI fails to find a newly created db parameter group

### ISSUE THREAD

**Issue by mariusmanea-selfridges** [aws/aws-cli#8489]
### Describe the bug

After creating a db parameter group, aws cli fails to find it.
When running the command `aws rds describe-db-parameter-groups` it shows the old list of parameter groups (the new one doesn't show up.
When running `aws rds describe-db-parameter-groups --db-parameter-group-name <my_parameter_group_name>`  the command throws the error:
`An error occurred (DBParameterGroupNotFound) when calling the DescribeDBParameterGroups operation: DBParameterGroup not found: <my_parameter_group_name>`
I waited multiple minutes, and still not working.

How long does it take for aws cli to recognize the new parameter group created? Is there a way to speed up this process, to make it refresh quicker?

thanks!

### Expected Behavior

aws cli should be able to find the newly created parameter group right away. I can see it in the AWS Portal, but aws cli cannot find it.

### Current Behavior

aws cli cannot find a newly created db parameter group

### Reproduction Steps

1. Create a new db parameter group (either programatically, or manually from AWS Portal)
2. Run the command `aws rds describe-db-parameter-groups`  and notice the new db parameter group is not there.
3. Alternatively, run `aws rds describe-db-parameter-groups --db-parameter-group-name <my_parameter_group_name>`  and you will receive an error DBParameterGroupNotFound

### CLI version used

aws-cli/2.15.12 Python/3.11.7 Darwin/23.2.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

MacOS (Darwin)

**Comment by RyanFitzSimmonsAK** [comment]
Hi @mariusmanea-selfridges, thanks for reaching out.  This sounds like it might an issue with regions; can you verify that the region in which you've created a parameter group matches the region you're making the describe request from?

**Comment by mariusmanea-selfridges** [comment]
Hi,
I was using crong cli command.. should have been `aws rds describe-db-cluster-parameter-groups` instead.
Everything works as expected :)
thanks!
