### ISSUE TITLE
Sync/Copy fails completely if even one file's timestamp is "out of range".

### ISSUE THREAD

**Issue by ionFish** [aws/aws-cli#855]
**OVERVIEW:**
I wrote an application that interfaces with AWS-CLI to perform various operations such as `sync` and `cp` given parameters that are sent to it from the web application. The client-side code is PHP which runs `system()` calls like `aws s3 ...`. **This is from LOCAL --> BUCKET!** (I do not know if Amazon S3 can store invalid-timestamp files, so I cannot test that it would happen the other way around).

I started a backup on a Friday before I left work, and noticed when I got home that it had "already completed". This was not possible. I initially suspected that the cause was simply a bad filename, possibly containing strange characters and backticks and spaces and other junk. That turned out not to be the case. It's simply *invalid timestamps*. With over a half-million files to upload, having a backup fail on EACH file (then moving/deleting that file or correcting its timestamp) is NOT a feasible approach.

**ANALYSIS:**
Scanning through the error logs of the failed backup returned something like this:

    Completed 499 part(s) with ... file(s) remaining
    Could not retrieve file stat of "\\SHARE\path\to\bad_file.ttf": timestamp out of range for platform localtime()/gmtime() function
    Completed 500 part(s) with ... file(s) remaining

So obviously the file has a bad timestamp (that particular file is from the year 2045, apparently). Manual review of the file reveals (Windows Explorer) that there is no file modification time even displayed. After some more testing, I uncover the following:

![Image of Explorer timestamp threshold](http://i.imgur.com/FaEvSjY.png)

*Please note, that in MS/DOS (and cmd.exe) the use of `dir` returns valid timestamps all the way from 01/01/1601 to some date after the year 2035 (year 5555 failed also).*

The tool I used to manually set these values with can be found [here](https://code.google.com/p/stexbar/downloads/list).

Searching online for "Could not retrieve file stat of : timestamp out of range for platform localtime()/gmtime() function" yielded a large PDF Python book [here](http://marvin.cs.uidaho.edu/Teaching/CS270/pythonLibrary.pdf). Searching the term "out of the range" returns two results, pages 140 and 143 respectively ("fromtimestamp" and "utcfromtimestamp").

I'm not a Python guru, so I do not know where-from Python grabs the times in Windows (if MS/DOS can do it but not Explorer).

A logical next-step would be to grep for those function calls in the AWS-CLI source, which I downloaded from GitHub on 7/28/2014.

    # grep -r "fromtimestamp" .
    ./tests/unit/customizations/s3/test_utils.py:                f.fromtimestamp.side_effect = ValueError(
    ./awscli/customizations/s3/utils.py:        update_time = datetime.fromtimestamp(stats.st_mtime, tzlocal())

And as you can see, these are the two offending files.

**PROPOSAL:**
I suggest that the timestamp is checked that it is in fact in-range, and if it is from PRE-1970 or 1980, simply set it to the lowest valid timestamp possible (according to the PDF book linked above, 1970, but based on my tests, 1980 at the least).

For files that are newer than "now" (when the file is checked by the program), just set the timestamp to the current time.

**REMARKS:**
1. as a result of a failed transfer *due to an invalid timestamp*, other *unrelated* errors will occur shortly after, before the entire process dies **without a specific error**. You might see `unable to read from source or disk` types of things.
2. I will work on a patch tomorrow or tomorrow-evening. **If anyone has any "better" idea (than setting the file to the oldest valid timestamp), PLEASE comment accordingly.**
3. I currently have a semi-working .exe file (easily compiled for Linux; it's in C) that will scan any directory recursively (not sure if it works on network drives yet -- will work on it tomorrow) and checks for valid 32-bit timestamps (though I may have to change that since I believe Windows uses 64-bit timestamps), and prints out bad files by path/name for manual correction.

**Comment by jamesls** [comment]
Closing out issue (the fix didn't link to this issue but it's been fixed for a while).  We now emit a warning and move on when the next file when we can't stat the file.

**Comment by kyleknap** [comment]
Alright I am reopening this issue because there are a few open issues about this. This one will be main issue thread in which we can follow this issue.

**Comment by grantmoxomZoo** [comment]
Anyone had any luck with this? Windows server 2003 aws s3 sync fails for the same reason for me, however the error is prepended with (22, 'Invalid argument') - however it IS due to the same date issue.

**Comment by JordonPhillips** [comment]
This was fixed in #1657 

Now a file with an invalid timestamp will not be skipped. Instead, we will default to epoch time and throw a warning with a non-zero rc.
