### ISSUE TITLE
Command to turn versioning on on Digital Ocean Space/Bucket fails with 'argument of type 'NoneType' is not iterable'

### ISSUE THREAD

**Issue by jmsherry** [aws/aws-cli#8560]
### Describe the bug

I'm trying to enable versioning on my Digital Ocean bucket/space and am following these docs here: https://docs.digitalocean.com/products/spaces/how-to/enable-versioning/

I have done: `aws s3api put-bucket-versioning --bucket "my-assets" --endpoint="https://my-assets.ams3.digitaloceanspaces.com" --versioning-configuration Status=Enabled`

but this does not work (see 'current behaviour')

### Expected Behavior

It should run and complete and then I should be able to check suucess with `aws s3api get-bucket-versioning --bucket "my-assets" --endpoint="https://my-assets.ams3.digitaloceanspaces.com"` (This also fails with the same response, however)

### Current Behavior

Executing the command currently returns `argument of type 'NoneType' is not iterable`

### Reproduction Steps

Have the same environment (with DO space and endpoint set up) and follow the steps in the docs: https://docs.digitalocean.com/products/spaces/how-to/enable-versioning/

### Additional Information/Context

The error suggests that there is an argument not getting passed?! But I can't see an error in it (I've have shell-checked it). It would be great if the error messaged suggested **which** argument was not iterable! 

### CLI version used

aws-cli/2.0.7 Python/3.7.4 Darwin/23.1.0 botocore/2.0.0dev11

### Environment details (OS name and version, etc.)

OSx, using ZSH

**Comment by RyanFitzSimmonsAK** [comment]
Hi @jmsherry, thanks for reaching out.  The AWS SDKs and the CLI are intended for use directly with AWS.  If you are able to reproduce this behavior using AWS S3, I'll be able to help.  

One thing I will mention is that you should probably upgrade your version of the AWS CLI.  `2.0.7` is nearly four years old at this point, and will be missing out on *many* service updates.  Thanks!

**Comment by jmsherry** [comment]
@RyanFitzSimmonsAK Thanks! I upgraded my CLI (I was installing through PIP and thought I had the latest but...). I still get the same error though. I'll raise it through DO support and see what they say. :)
