### ISSUE TITLE
Error out if --output is specified in s3 commands

### ISSUE THREAD

**Issue by jamesls** [aws/aws-cli#858]
The high level `s3` commands do not support the `--output` format, and in many cases like `cp/sync`, the various output formats do not make sense.  If a user provides this currently, we ignore the output.  We should ideally be either generating an error or a warning telling the user that `--output` does nothing.

From https://github.com/aws/aws-cli/issues/371

cc @kyleknap

**Comment by jamesls** [comment]
Closing.  This isn't a change we'd be able to make as it has backwards incompatibility concerns.

**Comment by stawii** [comment]
So.. how about implementing support for `--output` format?
This won't break anything, or is it still backwards incompatibility? :)
