### ISSUE TITLE
ECR command to list repositories

### ISSUE THREAD

**Issue by ligh1yagami** [aws/aws-cli#8598]
### Describe the feature

AWS ecr doesn't have a command to list ecr repositories.

### Use Case

It can be used to list repos present in the aws account.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.15.30

### Environment details (OS name and version, etc.)

linux

**Comment by RyanFitzSimmonsAK** [comment]
Hi @ligh1yagami, thanks for reaching out.  Unless I'm misunderstanding the ask, I think [describe-repositories](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/describe-repositories.html) does what you're looking for here.  Omitting the `--repository-names` parameter will cause the operation to describe all of the repositories in a registry.  Please let me know if that works for you, and if you have any other questions.
