### ISSUE TITLE
I'd like to be able to use content-md5 on puts for S3

### ISSUE THREAD

**Issue by eflee** [aws/aws-cli#860]
So, I have a use case where I'd like to ensure that everything I sync or put  to S3 with the aws cli has the content-md5 header set. I'd also like the ability to use this as my comparison heuristic for syncing from S3. 

According to S3 (https://forums.aws.amazon.com/thread.jspa?messageID=203510#203510) the Etag value they return is not the content md5 for multipart puts which the aws cli uses. It appears that the aws cli uses a combination of modification time and size to determine when a file has changed. 

I'd like to request a flag be added to set the content-md5 on put or sync so that is can be referenced in metadata at a later time. 

In addition, I'd also like the ability to include user-defined metadata.

I'm aware that I could calculate the md5 myself and use the s3api subcommand to include the information, however at that point I may as well code a tool myself (which is what I'm doing). I thought it might be nice to extend the use case of the cli and see if anyone else finds this useful. It could also be used to verify the content upon get.

**Comment by kyleknap** [comment]
Going through some of these older issues. We automatically calculate MD5 checksums now for all uploads (including part uploads). As to sync with MD5 lets track that in this issue: https://github.com/aws/aws-cli/issues/599. As to being able to provide custom metadata, let's track that through: https://github.com/aws/aws-cli/issues/1561. Closing issue. Let me know if I missed anything.

**Comment by MatthewHerbst** [comment]
@kyleknap would it be possible to get some documentation for the `--content-md5` flag for [put-object](http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html)? I've read different things about having to convert it from hex to Base64, etc. It would be great if that could be cleared up.

**Comment by kyleknap** [comment]
So the ``--content-md5`` value is an autopopulated parameter. We will fill it in for you. It is sort of tricky to calculate it, but you need to take the binary, calculate the md5, base64 encode it, and then ensure that the final value is a string as opposed to bytes. If this helps this is where we calculate and auto-populate it in the code: https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L122.

**Comment by MatthewHerbst** [comment]
@kyleknap thanks for the code link. So, `put-object` will automatically fail if the md5 on my local machine (automatically sent) and the md5 of the object on S3 after the put don't match? That's perfect - I thought I had to explicitly set the header for that functionality. Thanks!

**Comment by kyleknap** [comment]
Yeah what will happen is s3 will return a 400 BadDigest error if the MD5's do not match and the CLI will automatically retry the request if it sees that. I think it would be good to put documentation on this.

**Comment by MatthewHerbst** [comment]
@kyleknap the [REST API documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) has the following documentation:

> To ensure that data is not corrupted traversing the network, use the Content-MD5 header. When you use this header, Amazon S3 checks the object against the provided MD5 value and, if they do not match, returns an error. Additionally, you can calculate the MD5 while putting an object to Amazon S3 and compare the returned ETag to the calculated MD5 value.

Of course, since the CLI automatically does this the documentation should be a bit different... I think your comments above form a good basis for the docs.

Maybe something like:

> The --content-md5 header value is an autopopulated parameter. The command will return a 400 BadDigest error if the MD5's do not match. The CLI will automatically retry the request upon receiving error code 400. Additionally, you can calculate the MD5 while putting an object to Amazon S3 and compare the returned ETag to the calculated MD5 value. For more about computing the MD5, see [`calculate_md5`](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L122)

One thing that would need clarification there is the number of retries the CLI will attempt before aborting (and what the exit code is if it aborts due to too many 400 codes).

**Comment by kyleknap** [comment]
Yeah no problem. I just opened up a new issue to track for this documentation update.
