### ISSUE TITLE
Ambiguous JSON object required for `ecr put-image`

### ISSUE THREAD

**Issue by AndrewCharlesHay** [aws/aws-cli#8620]
### Describe the issue

I'm trying to pass the following JSON object in the `--image-manifest` argument to tag a helm chart but I keep getting the following error:

`An error occurred (InvalidParameterException) when calling the PutImage operation: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'`

The documentation gives an example of a JSON object related to Docker that mine JSON closely resembles but there is never any definition of what is required. I just have to guess and hope that it matches the expectations.

```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.cncf.helm.config.v1+json",
    "digest": "sha256:34cd28a1b9b3237128a0dd0f7c03edc36c112887b4e491ea6f3d6fe469ac4a86",
    "size": 151
  },
  "layers": [
    {
      "mediaType": "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
      "digest": "sha256:777d773fa08d8a7b256dc78d9ee5dfa96b2fc8dee66d531f831bd7ef098b2dc2",
      "size": 4513
    }
  ],
  "annotations": {
    "org.opencontainers.image.created": "2024-04-04T14:44:40Z",
    "org.opencontainers.image.description": "BMS | Worflow Platform Service",
    "org.opencontainers.image.title": "svc-bms-wkfptf",
    "org.opencontainers.image.version": "1.6.0"
  },
  "mediaType": "application/vnd.cncf.helm.config.v1+json"
}
```

### Links

https://docs.aws.amazon.com/cli/latest/reference/ecr/put-image.html

**Comment by RyanFitzSimmonsAK** [comment]
Hi @AndrewCharlesHay, thanks for reaching out.  I did some testing, and it seems that the issue is related to `mediaType`.  If I change `"mediaType": "application/vnd.cncf.helm.config.v1+json"` to match the example you referenced, the JSON is accepted as valid.  We have a few related issues (https://github.com/aws/aws-sdk/issues/193, https://github.com/boto/boto3/issues/3295), and they were able to bypass this issue using `ImageManifestMediaType`, rather than having it inside the manifest.  In my testing, that workaround did not work for me.  Assuming it doesn't work for you either, I can reach out to the service team for more information about the intended syntax for Helm charts here.

**Comment by haofeif** [comment]
Hi I have the same issue. In my case i want to apply the "latest" tag to my HELM chart on ECR

```bash
aws ecr put-image --repository-name XXXXXX --image-tag latest --image-manifest "$MANIFEST"

An error occurred (InvalidParameterException) when calling the PutImage operation: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'
```

and my `imageManifest` was getting from 
```bash
MANIFEST=$(aws ecr batch-get-image --repository-name XXXXX --image-ids imageTag="version-number" --output text --query 'images[].imageManifest')
```

the output of my MANIFEST is as below :

```json
{
    "schemaVersion":2,
    "config":{
        "mediaType":"application/vnd.cncf.helm.config.v1+json",
        "digest":"sha256:91df0fe079fe78dasfdsafsadfsadfasdfafdasdfasf",
        "size":126
    },
    "layers":[{
        "mediaType":"application/vnd.cncf.helm.chart.content.v1.tar+gzip",
        "digest":"sha256:a3ead2ddsadfasdfsafaefsfdsfafafsafasasf",
        "size":11223
    }]
 }
 ```
 
 thanks for your help and please keep this response open until you find the root cause. Same here it is for a HELM chart not a docker image

**Comment by RyanFitzSimmonsAK** [comment]
Hey, before I reach out to the service team, could you take a look at https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html, and let me know if this process works for you?

**Comment by haofeif** [comment]
> Hey, before I reach out to the service team, could you take a look at https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html, and let me know if this process works for you?

the problem occurred when following the document as shown above. So it is still the issue @RyanFitzSimmonsAK

**Comment by haofeif** [comment]
can you pls help to reopen the ticket ?

**Comment by RyanFitzSimmonsAK** [comment]
I've reached out to the service team, and will update you when I know more.

Ticket # for internal use : P140579689

**Comment by RyanFitzSimmonsAK** [comment]
The service team confirmed the following : 

The way to push a helm manifest is to not include the `mediaType` in the manifest and specify `--image-manifest-media-type application/vnd.oci.image.manifest.v1+json` in the `put-image `command.  ECR only allows two values for the `mediaType` of the manifest `application/vnd.oci.image.manifest.v1+json` or `application/vnd.docker.distribution.manifest.v2+json` for manifest that is not an image index.

They also suggested looking into the Helm CLI for this use case.

Please let me know if this works for you or if you have any follow-up questions.

**Comment by RealOrko** [comment]
For anyone else coming across this: 

```bash
        # Retrieve the image manifest as a string
        MANIFEST=$(aws ecr batch-get-image \
          --repository-name "${ECR_REPOSITORY}" \
          --image-ids imageTag=${{ steps.chart-info.outputs.version }} \
          --region "${AWS_DEFAULT_REGION}" \
          --query 'images[0].imageManifest' \
          --output text)

        # Fix the manifest by adding the missing top-level mediaType (workaround for AWS CLI bug)
        FIXED_MANIFEST=$(echo "$MANIFEST" | jq '. + {"mediaType": "application/vnd.oci.image.manifest.v1+json"}')

        # Create the new tag
        aws ecr put-image \
          --repository-name "${ECR_REPOSITORY}" \
          --image-tag "cryosharp-application-helm-v${{ steps.chart-info.outputs.version }}" \
          --region "$AWS_DEFAULT_REGION" \
          --image-manifest "$FIXED_MANIFEST"
```
