### ISSUE TITLE
Packaging of AWS::CloudFormation::Stackset resource using AWS CLI clouformation package command

### ISSUE THREAD

**Issue by nafiuyakubu** [aws/aws-cli#8663]
### Describe the feature

The feature request proposes extending the functionality of the AWS CLI's cloudformation package command to support packaging templates specifically designed for AWS CloudFormation StackSets.

Currently, the package command excels at packaging regular CloudFormation templates that might reference local artifacts like Lambda function code or API Gateway definitions. However, it lacks the ability to handle StackSet templates directly.

Feature request breakdown:

**Target audience:** AWS users who deploy infrastructure using CloudFormation StackSets.
**Desired functionality:** The cloudformation package command should be able to process StackSet templates. Ideally, it would:

1. Recognize the _AWS::CloudFormation::StackSet_ resource within the template.
2. Handle any specific requirements for packaging StackSet templates (if applicable).

### Use Case

Scenario:

An organization manages infrastructure across multiple AWS accounts and regions using CloudFormation StackSets. They currently deploy their StackSets by manually uploading the template to S3 and then referencing it in a separate StackSet template. This process is cumbersome and requires managing two separate templates.

Problem:

The current workflow requires additional steps for uploading the template to S3 and managing separate templates for the StackSet configuration and resources.
It can be error-prone to maintain consistency between the two templates.

### Proposed Solution

The aws cloudformation package command could be extended to support packaging CloudFormation StackSet templates. This would involve:

1. Recognizing the AWS::CloudFormation::StackSet resource within the template.
2. Including the StackSet template itself in the packaged output, potentially alongside any referenced artifacts like Lambda functions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

AWS CLI version 2

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
Thanks for the feature request and sharing your use case. The team is already tracking this request here: https://github.com/aws/aws-cli/issues/5590, so I will close this as a duplicate. This feature request is still under consideration but not prioritized at this time. In the meantime, you should be able to use the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html) to address your use case.
