### ISSUE TITLE
cannot import name 'SSOTokenFetcher' from 'botocore.utils' (C:\Python\Python310\lib\site-packages\botocore\utils.py)

### ISSUE THREAD

**Issue by vbtang** [aws/aws-cli#8692]
### Describe the bug

After I install awscli2v2 according to https://github.com/aws/aws-cli/tree/v2
I got error when I run awscli v2 through awslocal 
```bash 
cannot import name 'SSOTokenFetcher' from 'botocore.utils' (C:\Python\Python310\lib\site-packages\botocore\utils.py)
```
the awslocal is a wrapper of awscli 
It seems I don't have a correct version of botocore and boto3, what's the corresponding botocore and boto3 for it?

### Expected Behavior

awscli2v2 works well 

### Current Behavior

I got error when I run awscli v2 through awslocal 
```bash 
cannot import name 'SSOTokenFetcher' from 'botocore.utils' (C:\Python\Python310\lib\site-packages\botocore\utils.py)
```

### Reproduction Steps

install awscli v2 from https://github.com/aws/aws-cli/tree/v2
with botocore-1.34.112 and boto3 installed 

### CLI version used

v2

### Environment details (OS name and version, etc.)

windows10 python3.10.11

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Please use one of the installation methods documented here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. We cannot guarantee support for alternative installation steps. The latest CLI version is [2.16.1](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1), and installing the CLI will automatically install the corresponding compatible version of Botocore.
