### ISSUE TITLE
Upgrade GLIBC > 2.34 on ARM64 image to support IAM Roles Anywhere Credential Helper

### ISSUE THREAD

**Issue by estar-platform-team** [aws/aws-cli#8752]
### Describe the feature

[ IAM Roles Anywhere Credential Helper](https://github.com/aws/rolesanywhere-credential-helper) requires GLIBC version 2.34 or above. The AMD image works ok but ARM64/v8 needs to be updated or signing helper does not work throwing error:
```
Error when retrieving credentials from custom-process: /root/.aws/aws_signing_helper: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /root/.aws/aws_signing_helper)
/root/.aws/aws_signing_helper: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /root/.aws/aws_signing_helper)
```

### Use Case

When using IAM Roles anywhere one can pass the required certificates and the [signing helper](https://github.com/aws/rolesanywhere-credential-helper) to the container so that using a [custom config ](https://docs.aws.amazon.com/sdkref/latest/guide/feature-process-credentials.html) you can use [aws signing helper](https://github.com/aws/rolesanywhere-credential-helper) to authenticate using the certificates. 

### Proposed Solution

Upgrade GLIBC to > 2.34 on the ARM64 image. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.16.11

### Environment details (OS name and version, etc.)

ARM64/V8 image

**Comment by tim-finnigan** [comment]
Thanks for reaching out. `glibc` is at the OS layer and so it would need to be provided by whichever distribution you're using. For `amazonlinux` please consider opening an issue here: https://github.com/amazonlinux. On our end we do have an open feature request for moving to the CLI Docker image to AL2023: https://github.com/aws/aws-cli/issues/8331

**Comment by gtaws** [comment]
For anyone who needs a workaround for now, I simply used the following Dockerfile to build a custom image. Strraight forward and solves the issue for me on linux/amd64 and linux/aarch64. TLDR; - this will build aws_signing_helper against glibc deps in AL2 and copy into amazon/aws-cli base image.
=== BEGIN DOCKERFILE ===
FROM amazon/aws-cli AS builder
RUN yum -y groupinstall 'Development Tools' && yum -y install golang-go && git clone https://github.com/aws/rolesanywhere-credential-helper.git
RUN cd /aws/rolesanywhere-credential-helper && make release

FROM amazon/aws-cli
COPY --from=builder /aws/rolesanywhere-credential-helper/build/bin/* /usr/bin/

WORKDIR /aws
ENTRYPOINT ["/usr/local/bin/aws"]

=== END DOCKERFILE ===
