### ISSUE TITLE
delete stack doesn't have --deletion-mode option

### ISSUE THREAD

**Issue by huyhoang160593** [aws/aws-cli#8756]
### Describe the bug

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/delete-stack.html
as here mention there is --deletion-mode that can be use to some kind of force delete a stack, but when using cli they are unknown option

### Expected Behavior

have --deletion-mode option available

### Current Behavior

Unknown options: --deletion-mode, FORCE_DELETE_STACK

### Reproduction Steps

aws cloudformation delete-stack --stack-name <stack-name> --deletion-mode "FORCE_DELETE_STACK"

### CLI version used

aws-cli/2.13.0 Python/3.11.4 Linux/6.9.4-200.fc40.x86_64 exe/x86_64.fedora.40 prompt/off

### Environment details (OS name and version, etc.)

Linux

**Comment by tim-finnigan** [comment]
It looks like `--deletion-mode` was just added recently in [2.15.56](https://github.com/aws/aws-cli/blob/871c2ed765cf02506345fed56b225e3ef9ce0bdf/CHANGELOG.rst?plain=1#L215). I just tested in 2.16.8 and can confirm the option is recognized. Please update to a more recent version of the AWS CLI, documentation here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
