### ISSUE TITLE
We should be able to change the "Controls" menu name

### ISSUE THREAD

**Issue by dkabal14** [aws/aws-cli#8768]
### Describe the feature

Can we have an option to change the "Controls" label on the top-left of the dashboard?

### Use Case

Based on [this Quicksight community post](https://community.amazonquicksight.com/t/is-it-possible-to-change-the-name-of-the-menu-with-controls/31822).

In the Audit context, the name “Control” defines a process created to mitigate a risk found in the company. I have many customers asking me to change the “Controls” bar name, because it is misleading to them.

### Proposed Solution

Create an "settings/3dots button" on the right side of the opened "Controls" menu. Inside it, an option to change the "Controls" label. Or maybe, we could be able to change the name double clicking the label.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

v2

### Environment details (OS name and version, etc.)

Windows 11 v23H2

**Comment by RyanFitzSimmonsAK** [comment]
Hi @dkabal14, thanks for reaching out.  This repository tracks issues for specifically the AWS CLI.  A feature request about QuickSight's UI would have be directed to the QuickSight service team.  Opening a feature request in QuickSight Community is probably your best path forward.
