### ISSUE TITLE
[SSO] - Add CLI parameters to skip prompted values (`--start-url`, etc.)

### ISSUE THREAD

**Issue by tim-finnigan** [aws/aws-cli#8769]
### Describe the feature

See [TODO item](https://github.com/aws/aws-cli/blob/03be35e71e2e523421b3d809b83769b3876b6808/awscli/customizations/configure/sso.py#L368). 

Related PR with some discussion: https://github.com/aws/aws-cli/pull/6675

**Comment by COMMANDO117** [comment]
Good day! What's the status of this feature request? In looking through [#6675](https://github.com/aws/aws-cli/pull/6675) it appears that the cli parameters were added but need "docs, a changelog entry, as well as tests". Is that still the current status? If this is not currently being developed can I take a stab at adding in those things?

**Comment by COMMANDO117** [comment]
This appears to be a duplicate of [#6693](https://github.com/aws/aws-cli/issues/6693). Can someone confirm and perhaps close this one?
