### ISSUE TITLE
AWS CLI SSO stuck in browser loading state when click Allow

### ISSUE THREAD

**Issue by julianCast** [aws/aws-cli#8788]
The thing is AWS SSO login worked for me until recently but now it looks like the browser is not sending the event back to the CLI or the CLI is not watching properly the allow event.

I have tried:
- Re-installed AWS to latest version
- Removed .aws folder.
- Incognito browser session.
- Use native terminal and iTerm2
## AWS version
`aws-cli/2.17.9 Python/3.11.8 Darwin/23.4.0 exe/x86_64`

<img width="1295" alt="image" src="https://github.com/aws/aws-sdk/assets/559677/e76fffc7-34c3-4896-98a0-e4e646324dd3">
<img width="750" alt="image" src="https://github.com/aws/aws-sdk/assets/559677/f459115b-6054-4ce4-989d-8ff820d451ef">

**Comment by tim-finnigan** [comment]
Having trouble reproducing this. This may have been an issue with the underlying service API request, or perhaps something with your network/proxy configuration. Have you tried reproducing this in other environments?

**Comment by julianCast** [comment]
Thank you for checking it, I was able to fix it by adding the credentials manually into the credentials file, after that I could fetch them automatically, so there was some underlying cause in my configuration that would not allow me to continue.
