### ISSUE TITLE
aws sso login still broken for profiles outside of us-east-1

### ISSUE THREAD

**Issue by mattiamarchesini** [aws/aws-cli#8790]
### Describe the bug

Needed to create another issue since [the original](https://github.com/aws/aws-cli/discussions/8115) went unanswered for over an year and I feel this is a very important feature to be left broken.

Right now sso login is broken cause the web page form always redirects to https://us-east-1.signin.aws/platform/login regardless of the region set in the profile config, thus making it impossible to authenticate for every other region outside of us-east-1.

### Expected Behavior

After pasting the code I should be redirected to the correct login page for my region

### Current Behavior

.aws/config being
```
[profile my-sso]
sso_start_url = https://my-sso-portal.awsapps.com/start
sso_region = eu-north-1
sso_account_id = <My-ID>
sso_role_name = AWSAdministratorAccess
region = eu-north-1
output = json
```

`aws sso login --profile my-sso` initially gives the correct url, but after pasting the code I'm redirected to https://us-east-1.signin.aws/platform/login which does not know about my eu-north-1 account. Manually changing the url to https://eu-north-1.signin.aws/platform/login does not work.

### Reproduction Steps

try to login using `aws sso login` with an account outside of us-east-1

### CLI version used

aws-cli/2.17.10 Python/3.11.8 Linux/5.15.146.1-microsoft-standard-WSL2 docker/x86_64.amzn.2

### Environment details (OS name and version, etc.)

docker under wsl2

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Linking the CLI SSO User Guide page for reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

I tried to reproduce this issue (in `us-west-2`) but was unable to. Maybe try using the `--no-browser` parameter and then paste the link it outputs in your browser? That link should in include a `?user_code` parameter. Mine looks like this `https://device.sso.us-west-2.amazonaws.com/?user_code=WXYZ-ABCD`. The `eu-north-1` region has a documented SSO endpoint here: https://docs.aws.amazon.com/general/latest/gr/sso.html

**Comment by huykon** [comment]
after the link open in browser, I tried to login but it always failed, what's that problem?
