### ISSUE TITLE
--profile mandatory even if there is just one profile

### ISSUE THREAD

**Issue by faizanakram99** [aws/aws-cli#8791]
### Describe the bug

I understood from this issue https://github.com/aws/aws-cli/issues/6880#issuecomment-1105774146 that it won't be possible to specify a default profile but it makes absolutely 0 sense to specify profile if there is just one profile.

It is very annoying, I switched to `aws sso` for better security but the DX is horrible, why do I need to specify --profile for every command.

### Expected Behavior

Make profile non-mandatory if there is just one profile

### Current Behavior

Specifying profile is mandatory even with just 1 profile

### Reproduction Steps

configure aws with sso and try any command like aws s3 ls, it will complain about missing aws token bla bla until u specify profile

### CLI version used

2.15.0

### Environment details (OS name and version, etc.)

Ubuntu 23.10

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Using `--profile` is not actually required. There are various ways you could authenticate to use AWS as documented here: https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-authentication.html. For example you could [configure](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html) a `[default]` profile or set [environment variables](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html).

As mentioned in the [comment](https://github.com/aws/aws-cli/issues/6880#issuecomment-1105774146) you referenced, you can use the [get](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/get.html) and [set](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/set.html) commands to update configuration values. Also the [export-credentials](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configure/export-credentials.html) command can be used to export a profile's credentials. Hope that helps!
