### ISSUE TITLE
aws rds describe-db-instances missing LatestRestorableTime in output

### ISSUE THREAD

**Issue by akuzni2** [aws/aws-cli#8798]
### Describe the bug

command `aws rds describe-db-instances` is not showing the documented LatestRestorableTime field 

- Documentation: https://docs.aws.amazon.com/cli/latest/reference/rds/describe-db-instances.html

### Expected Behavior

It should show the field LatestRestorableTime

### Current Behavior

the field LatestRestorableTime is not present in the CLI output

### Reproduction Steps

- create DB cluster with automated backups that includes point-in-time-recovery 
- wait until automated backups have taken place and the console under RDS > Automated Backups > <DataBaseClusterId> shows the "latest restorable time" field

### CLI version used

aws-cli/2.17.11 Python/3.11.9 Darwin/23.5.0 source/arm64

### Environment details (OS name and version, etc.)

Mac OSX

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Yes the `describe-db-instances` [documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-instances.html) does reference `LatestRestorableTime` here:

![image](https://github.com/user-attachments/assets/445a01f5-5eff-48b0-a973-f64fafbf16d4)

That CLI command involves a call to the RDS [DescribeDBInstances API](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html). Therefore if there something missing from the API response that should be there, then we may need to escalate this to the RDS service team.

To confirm, could you share your debug logs (with any sensitive info redacted) by adding `--debug` to your command?
