### ISSUE TITLE
WSL2 Debian AWS CLI BOTO3 Core - NoCredentialsError - Unable to locate credentials

### ISSUE THREAD

**Issue by juparker37** [aws/aws-cli#8822]
### Describe the bug

When using WSL2/Debian 12 on Windows 10, running Python(VENV) script to make AWS BOTO3 STS Caller request for account credentials, get error `botocore.exceptions.NoCredentialsError: Unable to locate credentials` . When running Python script outside of WSL2 Debian 12 using full Python path on Windows CMD, problem is not seen.

 whereis aws
`aws: /usr/local/bin/aws /home/skynet/.local/bin/aws`

echo $PATH

`(AWS) skynet@*******:~/scripts$ echo $PATH/home/skynet/.virtualenvs/AWS/bin`

### Expected Behavior

Return AWS account information when AWS creds are configured locally using AWS BOTO3 STS.

### Current Behavior

`Traceback (most recent call last):
  File "/home/skynet/cloudmonitor/cloudmonitor/backend/scripts/get_account_info.py", line 13, in <module>
    account = boto3.client('sts').get_caller_identity().get('Account')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/client.py", line 999, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/signers.py", line 197, in sign
    auth.add_auth(request)
  File "/home/skynet/.virtualenvs/AWS/lib/python3.11/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials`

### Additional Information/Context

`(AWS) skynet@******:~$ ./aws/install

Found preexisting AWS CLI installation: /usr/local/aws-cli/v2/current. Please rerun install script with --update flag.

./aws/install --update

Found same AWS CLI version: /usr/local/aws-cli/v2/2.17.18. Skipping install.

pip3 install awscli

Requirement already satisfied: awscli in ./.local/lib/python3.11/site-packages (1.33.31)
Requirement already satisfied: botocore==1.34.149 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from awscli) (1.34.149)
Requirement already satisfied: docutils<0.17,>=0.10 in ./.local/lib/python3.11/site-packages (from awscli) (0.16)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from awscli) (0.10.2)
Requirement already satisfied: PyYAML<6.1,>=3.10 in ./.local/lib/python3.11/site-packages (from awscli) (6.0.1)
Requirement already satisfied: colorama<0.4.7,>=0.2.5 in ./.local/lib/python3.11/site-packages (from awscli) (0.4.6)
Requirement already satisfied: rsa<4.8,>=3.1.2 in ./.local/lib/python3.11/site-packages (from awscli) (4.7.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from botocore==1.34.149->awscli) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from botocore==1.34.149->awscli) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from botocore==1.34.149->awscli) (2.2.2)
Requirement already satisfied: pyasn1>=0.1.3 in ./.local/lib/python3.11/site-packages (from rsa<4.8,>=3.1.2->awscli) (0.6.0)
Requirement already satisfied: six>=1.5 in ./.virtualenvs/AWS/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.34.149->awscli) (1.16.0)
`

### CLI version used

Windows 10 aws-cli/2.17.13 - WSL2 Debian 12 - aws --version aws-cli/1.33.31 Python/3.11.2 Linux/5.15.153.1-microsoft-standard-WSL2 botocore/1.34.149

### Environment details (OS name and version, etc.)

WSL2 Debian 12

**Comment by juparker37** [comment]
![image](https://github.com/user-attachments/assets/d7e02393-b755-45ed-8eb5-78b4e1743618)

**Comment by juparker37** [comment]
So I was not aware/confused that their was a "awscliv2" python package. So I guess this solved my issue. Dont know why awscli version 1 is still lingering. 

`source /home/skynet/.vitualenvs/AWS/bin/activate

pip3 install awscliv2

awscliv2 --install
14:00:06 - awscliv2 - INFO - Installing AWS CLI v2 for Linux
14:00:06 - awscliv2 - INFO - Downloading package from https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip to /tmp/tmp5wigwz_c.zip
14:00:08 - awscliv2 - INFO - Extracting /tmp/tmp5wigwz_c.zip to to /tmp/tmpzcnk5h59
14:00:09 - awscliv2 - INFO - Installing /tmp/tmpzcnk5h59/aws/install to /home/skynet/.awscliv2
14:00:10 - awscliv2 - INFO - Now awsv2 will use this installed version
14:00:10 - awscliv2 - INFO - Running now to check installation: awsv2 --version
aws-cli/2.17.18 Python/3.11.9 Linux/5.15.153.1-microsoft-standard-WSL2 exe/x86_64.debian.12

awsv2 --version
2.3.0
AWS CLI v2 command: /home/skynet/.awscliv2/binaries/aws
aws-cli/2.17.18 Python/3.11.9 Linux/5.15.153.1-microsoft-standard-WSL2 exe/x86_64.debian.12`

**Comment by tim-finnigan** [comment]
Thanks for reaching out. We recommend following the documentation here for supported installation methods for v2: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html. If you're still seeing any issues please let us know.
