### ISSUE TITLE
--add-resources does not exist in aws cloudformation create-generated-template command

### ISSUE THREAD

**Issue by nishikkr** [aws/aws-cli#8856]
### Describe the issue

Following the step4 of Documentation "Create a template from scanned resources (AWS CLI)" [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/iac-generator-create-template-from-scanned-resources.html#create-template-from-scanned-resources-cli](url)

It says
Step 4: Create your stack template
To create a new stack template, use the [create-generated-template](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-generated-template.html) command, specifying your template name and your JSON text file. When the --template-configuration option isn't included, the UpdateReplacePolicy and DeletionPolicy policies are set to Retain by default.

```
aws cloudformation create-generated-template \
  --generated-template-name MyTemplate \
  --add-resources file://resources.json
```

When you actually run this command you will get this error.

```
❯ aws --version                                 
aws-cli/2.17.25 Python/3.11.9 Darwin/23.5.0 source/arm64

❯ aws cloudformation create-generated-template \
  --generated-template-name MyTemplate \
  --resources file://resources.json 
  
  usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --add-resources, file://resources.json

```

You can fix this issue by changing the --add-resources to --resources

### Links

Step4 from this documentation
 https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/iac-generator-create-template-from-scanned-resources.html#create-template-from-scanned-resources-cli : Create a template from scanned resources - Create a template from scanned resources (AWS CLI)

**Comment by tim-finnigan** [comment]
Thanks for reporting this issue. I will report this to the CloudFormation team to update their user guide to change `--add-resources` to `--resources`. In the future you can also use the [Provide feedback](https://docs.aws.amazon.com/forms/aws-doc-feedback?hidden_service_name=CloudFormation&topic_url=https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/iac-generator-create-template-from-scanned-resources.html) link to send documentation feedback directly to the appropriate team.
