### ISSUE TITLE
--endpoint-url does not accept IPv6 addresses

### ISSUE THREAD

**Issue by march-github** [aws/aws-cli#8863]
### Describe the bug

Passing an --endpoint-url option with a URL that contains an IPv6 address makes 'aws' fail with error 'Invalid endpoint'.
An example of a URL that fails is https://[2600:1f70:8000:c0:1ffe:768a:d:8649]:443/ (the IPv6 address of ec2.us-east-1.api.aws).

 

### Expected Behavior

The command should behave the same as with --endpoint-url that has an IPv4 address:

$ `host ec2.us-east-1.api.aws`
ec2.us-east-1.api.aws has address 3.83.171.156
ec2.us-east-1.api.aws has IPv6 address 2600:1f70:8000:a0:41d7:f53b:34f4:5798

$ `aws ec2 describe-instances --endpoint-url 'https://3.83.171.156/' --no-verify-ssl`
urllib3/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host '3.83.171.156'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
$  echo $?
0

`aws ec2 describe-instances --endpoint-url 'https://[2600:1f70:8000:a0:41d7:f53b:34f4:5798]/' --no-verify-ssl`
should produce the same output, status, and warning.

### Current Behavior

see Reproduction Steps below

### Reproduction Steps

$ `host -t AAAA ec2.us-east-1.api.aws`
ec2.us-east-1.api.aws has IPv6 address 2600:1f70:8000:c0:1ffe:768a:d:8649

$ `aws ec2 describe-instances --endpoint-url 'https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/' --no-verify-ssl`

Invalid endpoint: https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/

$ `aws ec2 describe-instances --endpoint-url 'https://[2600:1f70:8000:c0:1ffe:768a:d:8649]:443/' --no-verify-ssl`

Invalid endpoint: https://[2600:1f70:8000:c0:1ffe:768a:d:8649]:443/

$ `aws ec2 describe-instances --debug --endpoint-url 'https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/' --no-verify-ssl`
<...>
2024-08-13 12:19:45,227 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 499, in main
  File "awscli/clidriver.py", line 634, in __call__
  File "awscli/clidriver.py", line 837, in __call__
  File "awscli/clidriver.py", line 959, in invoke
  File "awscli/botocore/session.py", line 873, in create_client
  File "awscli/botocore/client.py", line 129, in create_client
  File "awscli/botocore/client.py", line 318, in _get_client_args
  File "awscli/botocore/args.py", line 96, in get_client_args
  File "awscli/botocore/endpoint.py", line 288, in create_endpoint
ValueError: Invalid endpoint: https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/

Invalid endpoint: https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/

### Possible Solution

A similar issue appears to have been fixed in botocore in https://github.com/boto/botocore/pull/2574. 

### CLI version used

aws-cli/2.17.28 Python/3.11.9 Linux/5.15.0-118-generic exe/x86_64.ubuntu.22

### Environment details (OS name and version, etc.)

Ubuntu Linux 22.04.4

**Comment by nateprewitt** [comment]
Thanks for opening this, @march-github! You're correct that the validation client-side shouldn't be happening in the CLI. I've ported the fix forward from botocore in #8865 to avoid throwing this error unnecessarily.

With that said, we wouldn't generally recommend bypassing DNS and calling AWS services directly with their IP. If this is for local service replicas, we'd expect this endpoint to reach urllib3 after the above patch is merged.

**Comment by nateprewitt** [comment]
Now that #8865 is merged, we'd expect this behavior to go out in the next release. Let us know if you have further concerns or issues after trying the update.

**Comment by march-github** [comment]
Thank you for a quick fix @nateprewitt . My use case is a test environment that simulates network partitioning. Almost all network traffic to the host is blocked, including DNS, but EC2 access over IPv6 is permitted. I will test the next release when it comes out.

**Comment by nateprewitt** [comment]
@march-github [2.17.31](https://github.com/aws/aws-cli/tree/2.17.31) should be available now.

**Comment by march-github** [comment]
With 2.17.31 the REST call now goes through, but the server returns an authorization error:

`$ aws ec2 describe-instances --endpoint-url 'https://[2600:1f70:8000:c0:1ffe:768a:d:8649]/' --no-verify-ssl`

An error occurred (AuthFailure) when calling the DescribeInstances operation: AWS was not able to validate the provided access credentials

However, an exact same call on the same instance but with an IPv4 address in the URL succeeds:

`$ aws ec2 describe-instances --endpoint-url 'https://3.83.170.177/' --no-verify-ssl`

Debug logs of the corresponding --debug runs attached. I guess the API endpoint takes the URL into account when checking credentials?

[ipv4.debug.log](https://github.com/user-attachments/files/16630291/ipv4.debug.log)
[ipv6.debug.log](https://github.com/user-attachments/files/16630292/ipv6.debug.log)

**Comment by nateprewitt** [comment]
Thanks for the update @march-github. It does look like we're missing a series of changes around this from 2021-2022 in the CLI v2. From the logs we can see while we're sending this to the correct address, the `Host` header being produced for signing is having its brackets stripped. This is product of how the Python standard library handles hostnames during parsing. I've put up https://github.com/aws/aws-cli/pull/8869 which should port the existing botocore behavior forward.

**Comment by march-github** [comment]
Tested with aws-cli/2.17.32, and IPv6 URLs worked like a charm. Thanks again for fixing this so quickly. Do you known if/when the latest version of aws-cli will be available on Amazon Linux 2023? At the moment AL2023 appears to install aws-cli 2.15.30.

**Comment by nateprewitt** [comment]
Glad it's working! The AL2023 update cadence is fairly delayed, they're usually 6-9 months behind on updates (AWS CLI 2.15.30 was released March 15, 2024). I would anticipate they'll have a recent version by the end of the year but don't have any hard dates from them.

If you'd like a newer version in the meantime, your best options are likely to [install from source](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-source-install.html) or use the [linux installers](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) until they're able to bring the package up to date.
