### ISSUE TITLE
aws_completer fails to complete sso profiles

### ISSUE THREAD

**Issue by gagbo** [aws/aws-cli#8877]
### Describe the bug

I am using Fish shell on Mac:

```console
$ aws --version
aws-cli/2.17.34 Python/3.11.9 Darwin/23.4.0 exe/x86_64
```

And I’ve only set up the CLI using the SSO provided sessions (so `aws configure sso` multiple times to setup all the accounts with profile names). When trying to complete the profile name after a `--profile` flag in an `aws` subcommand, I get an error message from `aws_completer` instead of having the list of profiles.

### Expected Behavior

Expecting a list of all profiles to appear as completion candidates so I can choose them

### Current Behavior

```console
Unable to locate credentials. You can configure credentials by running "aws configure".
```

gets printed and there’s a new prompt with the same unchanged command

### Reproduction Steps

- Install aws cli
- Set up a sso account only, using `aws configure sso`
- check that s3 works `aws s3 ls --profile ssoProfileName`
- try to complete `aws s3 ls --profile <TAB here>`

### Possible Solution

Does `aws_completer` try to read the sso configurations in `.aws/config`?

### CLI version used

aws-cli/2.17.34 Python/3.11.9 Darwin/23.4.0 exe/x86_64

### Environment details (OS name and version, etc.)

MacOS M3 Pro, Sonoma 14.4

**Comment by tim-finnigan** [comment]
Thanks for reaching out. This appears to be the same issue as https://github.com/aws/aws-cli/issues/7739, and a tab completion issue not with SSO profiles but with commands that expect a positional argument. I will close this as a duplicate and we can continue tracking this in the other issue. Please let us know if you had any additional context to share related to this.
