### ISSUE TITLE
ECS describe-clusters does not include configuration

### ISSUE THREAD

**Issue by drewma2k** [aws/aws-cli#8899]
### Describe the bug

`aws ecs describe-clusters --clusters <cluster> --include CONFIGURATIONS` does not include configuration information

### Expected Behavior

The configuration key to be provided in the output as per [awscli ecs docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/describe-clusters.html)

### Current Behavior

The configuration key is not included

### Reproduction Steps

`aws ecs describe-clusters --clusters <cluster> --include CONFIGURATIONS`

### CLI version used

aws-cli/2.17.44 Python/3.11.8 Darwin/23.6.0 source/arm64

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.6.1

**Comment by drewma2k** [comment]
Thank you for the clarification. Is there any way to find the log group associated with an ECS service? That’s what I thought would be under the configuration section.

**Comment by adev-code** [comment]
Hello @drewma2k, thanks for following up.  To get the log group associated with the cluster using $ aws ecs describe-clusters --clusters <cluster_name> --include CONFIGURATIONS, you must have a cluster log configuration already set. You can use the update_cluster operation to set these configurations on an existing cluster (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs/client/update_cluster.html).
Please let me know if you have any questions, thanks.
