### ISSUE TITLE
AWS CLI 2.15.14-r0 throwing XML_SetReparseDeferralEnabled: symbol not found error

### ISSUE THREAD

**Issue by treyfarmigoni** [aws/aws-cli#8913]
### Describe the bug

AWS CLI throwing an error on aws-cli-2.15.14-r0 when executing
aws --help
Error relocating /usr/lib/python3.11/lib-dynload/pyexpat.cpython-311-x86_64-linux-musl.so: XML_SetReparseDeferralEnabled: symbol not found

### Expected Behavior

No errors to occur. 

### Current Behavior

error is thrown

### Reproduction Steps

docker run -ti --entrypoint /bin/sh registry.gitlab.com/gitlab-org/terraform-images/stable:latest
<inside container>
apk update && apk add --no-cache aws-cli bash
aws --help

### CLI version used

aws-cli-2.15.14-r0 

### Environment details (OS name and version, etc.)

Alpine - 3.18.4

**Comment by gohayon-cls** [comment]
We are getting the same issue

**Comment by tim-finnigan** [comment]
Looks like this is the same as https://github.com/hashicorp/terraform/issues/35715, where a member of Terraform replied:

> The Dockerfile for the build wasn't changed during that time, so any differences would be solely from the upstream image. Your above example works correctly if the package is updated, and I also confirmed that newer images have already updated the problematic packages.
> 
> Closing since there's nothing the Terraform CLI can do to fix the old docker image.

Can you confirm that this is fixed in newer images?
