### ISSUE TITLE
`aws ssm describe-parameters help` gives a wrong explanation about ARN output

### ISSUE THREAD

**Issue by iliguanghui** [aws/aws-cli#8920]
### Describe the issue

Run `aws ssm describe-parameters help`, in the OUTPUT section, the field **ARN** represents the ARN of the parameter itself, not the user who last updated it.

```
~# aws --version
aws-cli/2.17.50 Python/3.11.9 Linux/5.15.0-118-generic exe/x86_64.ubuntu.22
```

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/describe-parameters.html#output

**Comment by adev-code** [comment]
Hi @iliguanghui, thanks for reaching out and finding out the error in the documentation. I have submitted an internal ticket to our SSM Documentation Team for the fix.
Let me know if you have further questions.

Thank you.

Ticket # for internal use : P155391186
