### ISSUE TITLE
Swift modelgen creates wrong decoding initializer with optional custom type in required array 

### ISSUE THREAD

**Issue by marcoboerner** [aws/aws-cli#8937]
### Describe the bug

When running `npx ampx generate graphql-client-code --format modelgen --model-target swift` on my Amplify Swift project, depending on the models defined in `data/resource.ts` the decoding initializer does not compile due to a `Cannot assign value of type '[MyCustomType]?' to type '[MyCustomType?]` error in Xcode.

### Expected Behavior

`myCustomTypes = try values.decode([MyCustomType?].self, forKey: .myCustomTypes)` should be generated

### Current Behavior

`myCustomTypes = try? values.decode([MyCustomType].self, forKey: .myCustomTypes)` is generated

### Reproduction Steps

Define the following models in `data/resource.ts`:
```
// Custom types

MyCustomType: a.customType({
  context: a.string(),
}),

// Models

MyModel: a.model({
  context: a.string(),
  myCustomTypes: a.ref('MyCustomType').array().required(),
  myOtherModelId: a.id().required(),
  myOtherModel: a.belongsTo('MyOtherModel', 'myOtherModelId')
})
  .authorization(allow => [allow.owner()]),

MyOtherModel: a.model({
  context: a.string(),
  myModel: a.hasOne('MyModel', 'myOtherModelId')
})
  .authorization(allow => [allow.owner()]),
```

And run `npx ampx generate graphql-client-code --format modelgen --model-target swift` to create the models.

### Additional Information/Context

When changing the custom type in the array to a non-optional, the decoding is done correctly.
```
// Custom types

MyCustomType: a.customType({
  context: a.string(),
}),

// Models

MyModel: a.model({
  context: a.string(),
  myCustomTypes: a.ref('MyCustomType').required().array().required(), // <-- changed !!!
  myOtherModelId: a.id().required(),
  myOtherModel: a.belongsTo('MyOtherModel', 'myOtherModelId')
})
  .authorization(allow => [allow.owner()]),

MyOtherModel: a.model({
  context: a.string(),
  myModel: a.hasOne('MyModel', 'myOtherModelId')
})
  .authorization(allow => [allow.owner()]),
```

### CLI version used

aws-cli/2.17.56 Python/3.12.6 Darwin/24.1.0 source/arm64

### Environment details (OS name and version, etc.)

macOS 15.1, Xcode 16.1 beta 2, swift-tools-version: 6.0, swiftLanguageModes v5

**Comment by tim-finnigan** [comment]
Thanks for reaching out. I think this was intended for an [AWS Amplify](https://github.com/aws-amplify) repository, such as [amplify-cli](https://github.com/aws-amplify/amplify-cli) or [amplify-swift](https://github.com/aws-amplify/amplify-swift). 

This repository is for the [AWS CLI](https://aws.amazon.com/cli/) — here is the command reference documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/index.html

**Comment by marcoboerner** [comment]
@tim-finnigan thanks for the info! Will close this issue.
