### ISSUE TITLE
Make it possible to add tag to SES Configuration Set

### ISSUE THREAD

**Issue by LozanoMatheus** [aws/aws-cli#8938]
### Describe the feature

To be able to add tags to my SES Configuration Set. At this point, the `CreateConfigurationSet` doesn't seem to support it and I couldn't find an `TagResource` like some resources have (e.g. [Lambda](https://docs.aws.amazon.com/lambda/latest/api/API_TagResource.html)).

### Use Case

* Filtering via billing/cost explorer
* It will make it possible to set policies (SCP/Config) to prevent certain configs based on the tag (e.g. tag Stage = Prod makes TLS required)
* Finding resources based on tag

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.17.56

### Environment details (OS name and version, etc.)

Python/3.11.9 Darwin/23.5.0 exe/x86_64

**Comment by tim-finnigan** [comment]
Thanks for reaching out. I think you are referring to the `aws ses create-configuration-set` command documented here: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ses/create-configuration-set.html

However, there is an SES v2 API, and it looks like you can specify `--tags` when running `aws sesv2 create-configuration-set`: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sesv2/create-configuration-set.html

Have you tried using the the SES v2 command? I don't think the SES team would go back and add a feature to the v1 API that is available in the v2 API.
