### ISSUE TITLE
list-service-quotas gives wrong result

### ISSUE THREAD

**Issue by ddemaret-plaid** [aws/aws-cli#8941]
### Describe the bug

When doing
```
aws service-quotas list-service-quotas --service-code cloudfront
```
You get no quotas. However when you look in the UI there's quotas that can be adjusted.

### Expected Behavior

A list of quotas to be returned

### Current Behavior

```
{
    "Quotas": []
}
```

### Reproduction Steps

Execute `aws service-quotas list-service-quotas --service-code cloudfront`

### CLI version used

aws-cli/2.15.30

### Environment details (OS name and version, etc.)

macOS Darwin

**Comment by adev-code** [comment]
Hi @ddemaret-plaid, thanks for reaching out. list-service-quotas is intended to show account specific applied quotas of a service. This operation has varying levels of support on a service-by-service basis.
For CloudFront, the command would be: 
$ aws service-quotas list-aws-default-service-quotas --service-code cloudfront 
- using the 'list-aws-default-service-quotas' https://awscli.amazonaws.com/v2/documentation/api/latest/reference/service-quotas/list-aws-default-service-quotas.html). 

If that isn't sufficient for your use case, I can reach out to the CloudFront service team for you. Let me know how you'd like to proceed here.

Thank you.

**Comment by ddemaret-plaid** [comment]
For context, I'm trying to implement https://github.com/aws-solutions/quota-monitor-for-aws which is how I found out about this. As far as I understand it `list-aws-default-service-quotas` does not reflect the already increased service quotas of the account so sadly that won't work for us. But it seems like I also can't request any Utilisation metrics for Cloudfront anyways so it seems like there's still a couple features missing.

If you could reach out to the CloudFront team about this that would be great thanks!

**Comment by adev-code** [comment]
Hi @ddemaret-plaid, thanks for the update. I'd just like to mention that I have submitted a feature request to CloudFront Service Quota Team to give a CLI response that reflects the quotas that have been increased. Please let me know if you have any other questions. Thanks!

Ticket for Internal Use Only: P159623587

**Comment by ddemaret-plaid** [comment]
Perfect thanks!
