### ISSUE TITLE
Cloudformation: create/update stack synchronously from the cli

### ISSUE THREAD

**Issue by Michael-Gannon** [aws/aws-cli#895]
CloudFormation is inherently asynchronous in it's implementation so there are a plethora of implementations that create and wait (poll) until one of the many final states of the stack is reached. It would be great if there was an implementation in this tool to wait until your stack creation/update is complete. This would be especially useful when combined with automated deploys and such that can depend on a simple success/failure outcome.

**Comment by alexbartlow** [comment]
James, any word on this? This would be useful in my environment as well.

**Comment by analytically** [comment]
+1

**Comment by paulseddon** [comment]
+1

**Comment by rubenfonseca** [comment]
+1

**Comment by jtheuer** [comment]
+1

**Comment by wjordan** [comment]
For reference, this was implemented by @quiver in boto/botocore#630 (merged via boto/botocore#841), and released in botocore@1.4.4 / aws-cli@1.10.13. It can be used through the [`aws cloudformation wait`](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/wait/index.html) command. Hooray!

**Comment by kyleknap** [comment]
Yep! Thanks again @quiver.

**Comment by jtheuer** [comment]
How reliable does it work? What happens when the Stack update was finished before ```aws cloudformation wait``` is executed? I guess there is no connection between the update and the waiting?

**Comment by ievgeniiVlasyuk** [comment]
Do we have an opportunity to use wait method in aws .net sdk? Or currently only CLI is supported? Thanks.
