### ISSUE TITLE
ls and cp do not work : upload failed: ./screenlog.0 to s3://bucket-test-2/screenlog.0 An HTTP Client raised an unhandled exception: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by sebma** [aws/aws-cli#8963]
### Describe the bug

Hi, I cannot `ls` or `cp` to new empty bucket, I get a `maximum recursion depth exceeded` error.
```shell
$ cat ~/.aws/config
[default]
endpoint_url = http://x.y.z.t
$
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expect to be able to view the new bucket and copy files inside it.

### Current Behavior

I get this : 
```shell
$ du -h screenlog.0
2.1G    screenlog.0
$ aws s3 ls s3://bucket-test-2

maximum recursion depth exceeded
$ echo $?
255
$ aws s3 cp screenlog.0 s3://bucket-test-2
upload failed: ./screenlog.0 to s3://bucket-test-2/screenlog.0 An HTTP Client raised an unhandled exception: maximum recursion depth exceeded
$ echo $?
1
$
```

### Reproduction Steps

```shell
$ aws configure
AWS Access Key ID [****************xxxx]:
AWS Secret Access Key [****************yyyy]:
Default region name [None]:
Default output format [None]:
$ cat ~/.aws/config
[default]
endpoint_url = http://x.y.z.t
$
```
Then I do this : 
```shell
$ aws s3 ls s3://bucket-test-2

maximum recursion depth exceeded
$ echo $?
255
$ aws s3 cp screenlog.0 s3://bucket-test-2
upload failed: ./screenlog.0 to s3://bucket-test-2/screenlog.0 An HTTP Client raised an unhandled exception: maximum recursion depth exceeded
$ echo $?
1
$
```

### CLI version used

aws-cli/2.18.2 (snap version, classic confinement)

### Environment details (OS name and version, etc.)

Ubuntu 22.04.1 LTS

**Comment by adev-code** [comment]
Hello @sebma, thanks for reaching out. I have replicated the same setup and I was not able to reproduce the same issue. Could you provide debug logs of the behavior? You can get debug logs by adding —debug to the command you have entered, and redacting any sensitive information. Thank you.

**Comment by sebma** [comment]
@adev-code Thank you for your time.

My problem is now solved, I was missing the execute (`chmod +x`) permission on the S3 root dir.
