### ISSUE TITLE
Update AWS CLI Command Reference of MWAA

### ISSUE THREAD

**Issue by kv5h** [aws/aws-cli#8989]
### Describe the issue

In the AWS CLI Command Reference of MWAA, some options such as `--startup-script-s3-*` are missing although they are actually available in the AWS CLI.

### Links

They are missing at least in:
- https://awscli.amazonaws.com/v2/documentation/api/2.4.18/reference/mwaa/create-environment.html
- https://awscli.amazonaws.com/v2/documentation/api/2.4.18/reference/mwaa/update-environment.html

**Comment by tim-finnigan** [comment]
Thanks for reaching out. It looks likes the links you're using are specifically referencing `2.4.18` which is quite an old version and must not have included those parameters. In the latest documentation for [create-environment](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/mwaa/create-environment.html) and [update-environment](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/mwaa/update-environment.html) I see those parameters. Here is the [CHANGELOG](https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst?plain=1) for reference, showing which changes were introduced in each version.
