### ISSUE TITLE
Incorrect JMESPath result with text output format

### ISSUE THREAD

**Issue by jack-parsons-bjss** [aws/aws-cli#8998]
### Describe the bug

When the text output format is selected, results returned are inconsistent from the json output (and a test on jmespath.org, which is consistent with the json format).
We are running the following query: `sort_by(imageDetails[? !(contains(imageTags[0], `feature-branch`))], & imagePushedAt)[-1].imageTags[0]` on an `aws ecr describe-images` CLI call which ultimately results in more than one page of results being returned.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expect only the latest non feature branch version to be returned; in our case, 1.0.0-49

### Current Behavior

I get that query executed on every page of results returned - 1.0.0-49 plus 1.0.0-18 by default, but by configuring the `--page-size` argument I can get more results.

### Reproduction Steps

`aws ec2 describe-images --owners amazon --query 'sort_by(Images[], & CreationDate)[-1].ImageId' --output text --page-size 100`

### CLI version used

aws-cli/2.17.42 Python/3.11.9 Darwin/23.6.0 source/arm64

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.7

**Comment by tim-finnigan** [comment]
Thanks for reaching out. Linking relevant AWS CLI v2 documentation for reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output-format.html

As noted there, the difference in behavior between `--output text` and `--output json` is expected:

<img width="731" alt="image" src="https://github.com/user-attachments/assets/908a5129-123b-4b32-83b0-ca43957bd63d">

Regarding pagination, here is documentation with more information on how that works in the AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html

When you specify `--page-size` for the [describe-images command](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-images.html), that parameter is getting sent as `MaxResults` to the underlying [API request](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html). (You can see what the full request looks like when you add the `--debug` command.). Hope that helps, if you have any follow up questions please let us know.
