### ISSUE TITLE
MSI installer doesn't seem to work inside a Docker build.

### ISSUE THREAD

**Issue by jghal** [aws/aws-cli#9010]
I'm trying to build a custom image with the CLI installed and there is an issue with installing the MSI. My Docker host is on Windows Server 2019.

```dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8

SHELL ["powershell", "-Command", "Continue = 'Stop'; SilentlyContinue = 'SilentlyContinue';"]

RUN Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi" -UseBasicParsing ; \
    Start-Process -Wait msiexec.exe -ArgumentList @('/i', 'AWSCLIV2.msi', '/qn', '/L*v', 'C:\\install.log') ; \
    Remove-Item -Force AWSCLIV2.msi

ENTRYPOINT ["signtool.exe"]
```

I think it's not really waiting for the install to complete. The build output looks ok

```
docker build -t code-sign:initial .
Sending build context to Docker daemon  45.62MB
Step 1/4 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
 ---> bec6ad7833f7
Step 2/4 : SHELL ["powershell", "-Command", "Continue = 'Stop'; SilentlyContinue = 'SilentlyContinue';"]
 ---> Using cache
 ---> 54084da07108
Step 3/4 : RUN Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi" -UseBasicParsing ;     Start-Process -Wait msiexec.
exe -ArgumentList @('/i', 'AWSCLIV2.msi', '/qn', '/L*v', 'C:\\install.log') ;     Remove-Item -Force AWSCLIV2.msi
 ---> Using cache
 ---> 5dc86b4aa385
Step 4/4 : ENTRYPOINT ["signtool.exe"]
 ---> Using cache
 ---> 85355ccfad6e
Successfully built 85355ccfad6e
Successfully tagged code-sign:initial
```

But the resulting image doesn't seem to have the CLI installed, or the log file from the installer

```powershell
PS C:\> docker run --rm -it --entrypoint powershell code-sign:initial
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> dir C:\

    Directory: C:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-r---        10/8/2024   5:57 PM                Program Files
d-----        10/8/2024   6:03 PM                Program Files (x86)
d-r---        10/4/2024   9:52 PM                Users
d-----        10/8/2024   5:49 PM                Windows
-a----         9/6/2024   1:02 AM           5647 License.txt

PS C:\> dir 'C:\Program Files\'

    Directory: C:\Program Files

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/15/2018   7:21 AM                common files
d-----        10/8/2024   5:57 PM                dotnet
d-----        10/8/2024   5:57 PM                IIS
d-----        9/15/2018   7:12 AM                internet explorer
d-----        10/8/2024   5:55 PM                NuGet
d-----        9/15/2018   7:12 AM                WindowsPowerShell
```

But if I run the same commands from the dockerfile to manually download and run the MSI installer inside a container and wait a few minutes then it works.

_Originally posted by @jghal in https://github.com/aws/aws-cli/discussions/9000_

**Comment by tim-finnigan** [comment]
Thanks for reaching out — regarding what you said here:
>But if I run the same commands from the dockerfile to manually download and run the MSI installer inside a container and wait a few minutes then it works.

Can you share more details on when it is working versus not working? Also have you tried using the official CLI docker image: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-docker.html#cliv2-docker-install ?

**Comment by jghal** [comment]
Hi @tim-finnigan, sorry I hadn't responded earlier. The official image is Linux-based and I need a Windows one, to use Microsoft's signtool executable. It'd be great if Amazon put a Windows based image.

Using _docker build_ with the Dockerfile I provided, the build command completes without any indicated failure, but the resulting image does not have the AWS CLI installed. If I manually perform _docker run_ with the same base image in the Dockerfile, then I can run the first two powershell commands, then watch the log file (`get-content -wait C:\install.log`) for the install to complete, then it will have worked and I can invoke the `aws` command. This appears to be an issue with MSI returning to the command line while the installation runs in the background.

I was eventually able to get something to work. using a different base image and changing how `powershell` is being invoked as the shell for the `RUN` commands.

```dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG SIGNTOOL="C:/Program Files (x86)/Microsoft SDKs/ClickOnce/SignTool/signtool.exe"

COPY --from=mcr.microsoft.com/dotnet/framework/sdk:4.8 $SIGNTOOL C:/Windows/System32/signtool.exe

RUN powershell -Command \
    $ErrorActionPreference = 'Stop'; \
    $ProgressPreference = 'SilentlyContinue'; \
    (New-Object System.Net.WebClient).DownloadFile( \
        'https://awscli.amazonaws.com/AWSCLIV2.msi', \
        'c:\AWSCLIV2.msi' \
    ); \
    Start-Process -Wait msiexec.exe -ArgumentList @('/i', 'AWSCLIV2.msi', '/qn', '/l*v', 'C:/install.log') ; \
    remove-item C:/AWSCLIV2.msi ; \
    Remove-Item C:/install.log

ENTRYPOINT ["signtool.exe"]
```
