### ISSUE TITLE
Output the full ARN of a freshly created S3 bucket in the result or allow to specify tags of bucket on create-bucket

### ISSUE THREAD

**Issue by chtpl** [aws/aws-cli#9013]
### Describe the feature

Either allow to specify `--tags` on `aws s3api create-bucket ...` similiar to how it is possible on `aws dynamodb create-table ...` or output the `BucketARN` in the output of `aws s3api create-bucket ...` so I can use `jq` to feed the result into `aws s3api   put-bucket-tagging --bucket <ARN_GOES_HERE>` 

### Use Case

I want to programmatically set the tags of a S3 bucket I create in my bash script using awscli

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.18.15

### Environment details (OS name and version, etc.)

debian-bookworm devcontainer

**Comment by RyanFitzSimmonsAK** [comment]
Hi, thank you for this feature request.  This type of feature would have to be implemented at the service team level, rather than specifically for the AWS CLI.  I've forwarded your feedback to the S3 team.  Thanks!
