### ISSUE TITLE
Have 'aws rds wait db-cluster-available' (or similar) return when Aurora serverless v2 endpoints are actually available

### ISSUE THREAD

**Issue by sondresb** [aws/aws-cli#9046]
Not sure if this is a bug report, a feature request or even if I should RTFM more closely.

I am doing this at the end of a database restore of a Aurora serverless v2 cluster for QA and support reasons every night:

```
aws rds wait db-cluster-available \
    --profile $AWS_PROFILE \
    --db-cluster-identifier $CLUSTER_COPY_IDENTIFIER \
    --region $AWS_REGION
```

Where $CLUSTER_COPY_IDENTIFIER is the newly created cluster from a snapshot (with command aws rds restore-db-cluster-to-point-in-time). 

My expectation (and I think the reality for serverless v1) would be for this to return when the cluster is actually up and running, accepting connections. This seems not to be the case, as I now have both the reader and writer instances in "Creating" for 40 mins after the creation, and the command returned after around 15 mins. Even if it was faster (the gap smaller), I would like to be able (preferably without try/fail, polling style) to be **sure** it is available for stuff like anonymization steps on the copy. I get "channel 7: open failed: connect failed: Name or service not known" on the bastion host tunnel. The tunnel works fine once the instance creation operations are complete.

Is there some other command? Sending ARN of the reader instance instead of the cluster? Or how would I go about doing this?

**Comment by sondresb** [comment]
Yeah, I think doing the wait for instance after cluster avail as shown in the linked https://github.com/aws/aws-cli/pull/9048 will do the trick for me.

**Comment by imSanko** [comment]
I gave the solution for this issue [https://github.com/aws/aws-cli/pull/9048](url) and it got merged let me know for the changes would've been required?

**Comment by adev-code** [comment]
@imSanko it looks like your PR (https://github.com/aws/aws-cli/pull/9048) didn't actually include any changes. I'm not sure what happened there but could you highlight the changes you wanted to include or submit another PR? If there is an issue with the existing waiter model then the service team (in this case RDS) would need to implement the fix.
