### ISSUE TITLE
aws ec2 import-snapshot does not set the snapshot description

### ISSUE THREAD

**Issue by rgl** [aws/aws-cli#9047]
### Describe the bug

when using the

```bash
aws_region='eu-west-1'
vmimport_role='arn to a role like the one from https://docs.aws.amazon.com/vm-import/latest/userguide/required-permissions.html#vmimport-role'
talos_version='1.7.2'
s3_bucket='images'
s3_key="talos-$talos_version-aws-amd64.vmdk"
aws ec2 import-snapshot \
    --region "$aws_region" \
    --role-name "$vmimport_role" \
    --description "Talos Linux $talos_version" \
    --disk-container "Description=Talos Linux $talos_version,Format=VMDK,UserBucket={S3Bucket=$s3_bucket,S3Key=$s3_key}"
```

Notice the `--disk-container "Description=Talos Linux $talos_version,` argument.

I would expect that to set the snapshot description. But it does not.

### Expected Behavior

I would expect `--disk-container "Description=Talos Linux $talos_version,` to set the snapshot description.

### Current Behavior

It sets the snapshot description to `Created by AWS-VMImport service for ...` instead of the expected value.

Here's a screenshot of the aws management console while listing the created snapshot:

![image](https://github.com/aws/aws-cli/assets/43356/69f0a92b-a8fc-4049-a230-6f6be59f2aad)

### Reproduction Steps

execute the command as described earlier.

### CLI version used

2.15.53

### Environment details (OS name and version, etc.)

ubuntu 22.04

**Comment by RyanFitzSimmonsAK** [comment]
I've forwarded this feature request to the EC2 team.  Thanks again for reaching out.

**Comment by rgl** [comment]
@RyanFitzSimmonsAK, please, link the aws cli version that fixed this issue.

**Comment by RyanFitzSimmonsAK** [comment]
> @RyanFitzSimmonsAK, please, link the aws cli version that fixed this issue.

This behavior isn't resolved yet; the EC2 team has been made aware of this request, but there's no specific timeline for implementation.
