### ISSUE TITLE
Limit number of parallel s3 transfers

### ISSUE THREAD

**Issue by phemmer** [aws/aws-cli#907]
Can we get a way to limit the number of parallel s3 transfers? As it is, transfer jobs are consuming a lot of system resources (CPU, disk IO, bandwidth) because the `aws s3 sync` command is launching several parallel transfers.

The simplest way I can think of would be to pull constants from environment variables. This would let you override the `MAX_PARTS` from [constants.py](https://github.com/aws/aws-cli/blob/2bdb58ba8ae171fff6467fc9ee39936b5bc1940b/awscli/customizations/s3/constants.py#L17).
With this method, power users could override other constants as well. But for my use case, a `--max-parts` command line option would suffice.

**Comment by jamesls** [comment]
This is now possible via https://github.com/aws/aws-cli/pull/1122, docs are here: https://github.com/aws/aws-cli/blob/develop/awscli/topics/s3-config.rst
