### ISSUE TITLE
AWS SSO CLI fallback to device authorization grant doesn't work

### ISSUE THREAD

**Issue by ikattur-ota** [aws/aws-cli#9092]
### Describe the bug

Running this in a Vagrant box, PKCE-based Authorization for SSO doesn't work as it needs a browser.
Following recommendations in the [official blog post](https://aws.amazon.com/blogs/developer/aws-cli-adds-pkce-based-authorization-for-sso/) and [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#cli-configure-sso-configure), I tried using the `--use-device-code` flag but it doesn't seem to make a difference:

```
vagrant@ubuntu2204:~$ aws configure sso --profile "AWSAdministratorAccess" --use-device-code
SSO session name (Recommended): my-sso
SSO start URL [None]: https://d-xxx.awsapps.com/start
SSO region [None]: us-east-1
SSO registration scopes [sso:account:access]:
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://oidc.us-east-1.amazonaws.com/authorize?response_type=code&client_id=xxxx...
```

**Workaround:**
I had to follow this two-step process, as the `--use-device-code` flag seems to work for the `aws sso login` command:
```
vagrant@ubuntu2204:~$ aws configure sso-session
SSO session name: my-sso
SSO start URL [None]: https://d-xxx.awsapps.com/start
SSO region [None]: us-east-1
SSO registration scopes [sso:account:access]:

Completed configuring SSO session: my-sso
Run the following to login and refresh access token for this session:

aws sso login --sso-session my-sso

vagrant@ubuntu2204:~$ aws sso login --sso-session my-sso --use-device-code
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-1.amazonaws.com/

Then enter the code:

xxxx-xxxx
Successfully logged into Start URL: https://d-xxx.awsapps.com/start
```

And then configure an SSO profile:
```
vagrant@ubuntu2204:~$ aws configure sso --profile "AWSAdministratorAccess"
SSO session name (Recommended): my-sso
There are n AWS accounts available to you.
Using the account ID xxx
There are 2 roles available to you.
Using the role name "AWSAdministratorAccess"
CLI default client Region [None]: us-west-2
CLI default output format [None]: json

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile AWSAdministratorAccess
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

SSO authorization workflow via OAuth 2.0 device authorization grant to work in the `aws configure sso` command when `--use-device-code` option is used.

### Current Behavior

See description

### Reproduction Steps

See description

### CLI version used

2.22.1

### Environment details (OS name and version, etc.)

Linux/5.15.0-91-generic exe/x86_64.ubuntu.22 Python/3.12.6

**Comment by ashovlin** [comment]
Thanks for the report! This is an issue in the flag's introduction in `2.22.0`. https://github.com/aws/aws-cli/pull/9090 addresses it, and is queued up for today's daily release. I'll reply again once the release is finished.

**Comment by ashovlin** [comment]
This should be addressed in `2.22.2` which was released today.
```
% aws configure sso --use-device-code
...
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-1.amazonaws.com/

Then enter the code:
...
```

Let us know if you're still seeing any issues.

**Comment by ashovlin** [comment]
@ntang-tmx the intended behavior is:
* `--no-browser` controls whether the CLI will attempt to open the authorization link in a browser automatically, for both  the device code flow and the new authorization code flow. When this is set, the CLI should just print the link without attempting to open it.
* `--use-device-code` is the new option to fallback to the device code flow, after 2.22.0 change the default behavior to the auth grant with the callback.

Is your first snippet from `2.22.2` as well? I'd expect to see something like this instead:
```
% aws sso login --profile <profile> --no-browser
Browser will not be automatically opened.
Please visit the following URL:

https://oidc.us-east-1.amazonaws.com/authorize?response_type...
```

**Comment by ntang-tmx** [comment]
Indeed, the snippet is from another version. `2.22.2` displays the snippet you showed. 

You're right, I did not check the `2.22.0` change from 2 days ago.

**Comment by ashovlin** [comment]
@ntang-tmx Thanks, so I believe that's working as expected then, but let us know if you're still hitting issues
