### ISSUE TITLE
error in $(aws ec2 modify-instance-attribute help)

### ISSUE THREAD

**Issue by mbailey** [aws/aws-cli#910]
The syntax supported by the CLI for the --groups argument is a list of SecurityGroup Ids as bare tokens, not GroupId.1=sg-1a1a1a1a.

I think the example should read more like:
aws ec2 modify-instance-attribute --instance-id i-2ebd9333 --groups sg-1a1a1a1a sg-9b9b9b9b 

- Mike

$ aws ec2 modify-instance-attribute help
<snip>
       --groups (list)
          [EC2-VPC] Changes the security groups  of  the  instance.  You  must
          specify  at  least one security group, even if it's just the default
          security group for the VPC. You must specify the security group  ID,
          not the security group name.

          For  example,  if  you  want  the  instance to be in sg-1a1a1a1a and
          sg-9b9b9b9b, specify GroupId.1=sg-1a1a1a1a and GroupId.2=sg-9b9b9b9b
          .

       Syntax:

          "string" "string" ...
<snip>

**Comment by kyleknap** [comment]
This looks fixed now: http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html. Closing issue.
