### ISSUE TITLE
s3tables Command Not Found in AWS CLI

### ISSUE THREAD

**Issue by soumilshah1995** [aws/aws-cli#9120]
### Describe the bug

Description
I tried to use the s3tables command with the AWS CLI, but it resulted in an error indicating that the command is not recognized.
Steps to Reproduce

Run the following command:
```
aws s3tables list-table-buckets

```

Observe the error output:
```
aws: error: argument command: Invalid choice, valid choices are:  
... (list of valid AWS CLI commands) ...

```

Expected Behavior
The s3tables command should execute successfully, allowing me to list table buckets in S3 (if this is a valid feature).
Actual Behavior
The CLI returns an error indicating that s3tables is not a valid command.
Environment
AWS CLI Version: 2.21.2
Python Version: 3.12.6
Operating System: Linux/6.1.112-124.190.amzn2023.x86_64 (AWS CloudShell)

#### Additional Context
I could not find documentation or information about the s3tables command in the AWS CLI reference. Is this a deprecated, custom, or region-specific feature?
If this command is part of a plugin or requires additional setup, please provide guidance or documentation to enable it.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

$ aws s3tables list-table-buckets | jq .tableBuckets[].arn
"arn:aws:s3tables:us-east-2:123456789012:bucket/jbarr-table-bucket-1"
"arn:aws:s3tables:us-east-2:123456789012:bucket/jbarr-table-bucket-2"

### Current Behavior

aws: error: argument command: Invalid choice, valid choices are:  
... (list of valid AWS CLI commands) ...

### Reproduction Steps

..........

### Possible Solution

..........

### Additional Information/Context

..........

### CLI version used

2.21.2

### Environment details (OS name and version, etc.)

Mac

**Comment by tim-finnigan** [comment]
Thanks for reaching out. It looks like support for `s3tables` was just added in version 2.22.10.  I just tested and confirmed it is working on 2.22.10. Here is the documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3tables/index.html. Please try [updating](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) your version of the AWS CLI and let us know if you run into any issues.
