### ISSUE TITLE
import-key-pair fails with ASCII key file

### ISSUE THREAD

**Issue by stephenmsachs** [aws/aws-cli#9128]
### Describe the bug

As reported here https://github.com/awslabs/ec2-spot-workshops/issues/48 the aws cli command to upload a key using a file name does not generate base64 as it should per the documentation.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

```
ssh-keygen -f ${CODEBUILD_BUILD_ID} -P ""
aws ec2 import-key-pair --key-name ${CODEBUILD_BUILD_ID} --public-key-material file://${CODEBUILD_BUILD_ID}.pub
```

### Current Behavior

Invalid base64: "ssh-rsa XXXXXXXXXXX"

### Reproduction Steps

Use CodeBuild `aws/codebuild/amazonlinux-x86_64-standard:4.0` container and try to add a keypair via CLI.

### Possible Solution

As suggested in the linked thread `fileb:` is used.

### CLI version used

1.18.147-1.amzn2.0.2

### Environment details (OS name and version, etc.)

AL2

**Comment by adev-code** [comment]
Hi @stephenmsachs, thank you for reaching out. I have replicated the scenario with CodeBuild and having AWS CLI version aws-cli/1.18.147 and with "file://" without the b and it worked. I was able to import key pair and describe it too. For further look, could you please provide full debug logs and also any other relevant steps you may have done. 

In regards to with “b” on "fileb://", it would be for using CLI V2 or you can revert to the v1 behavior with the configuration: cli_binary_format=raw-in-base64-out (https://github.com/aws/aws-cli/issues/4969#issuecomment-592228383). This "fileb://" can be seen also from the current documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/import-key-pair.html#examples. Please let me know if you have any other questions. Thank you.
