### ISSUE TITLE
Missing info from describe-domain and describe-space using aws cli

### ISSUE THREAD

**Issue by HeNeos** [aws/aws-cli#9130]
### Describe the bug

I'm trying to get information about the idle time in my domain and space. It's already setted through aws cdk and I can see those settings from the console.

```ts
    new sagemaker.CfnDomain(this, "CfnDomain", {
      authMode: "IAM",
      domainName,
      vpcId: props.vpcId,
      subnetIds: props.subnetsIds,
      defaultUserSettings: {
        executionRole: sagemakerNotebookRole.roleArn,
        securityGroups: [props.securityGroup],
        sharingSettings: {
          notebookOutputOption: "Allowed",
          s3KmsKeyId: props.customKmsKeyId,
          s3OutputPath: `s3://${sagemakerStudioOutputBucket.bucketName}/`,
        },
        codeEditorAppSettings: {
          appLifecycleManagement: lifecycleConfiguration,
        },
        jupyterLabAppSettings: {
          appLifecycleManagement: lifecycleConfiguration,
        },
      },
      defaultSpaceSettings: {
        executionRole: sagemakerNotebookRole.roleArn,
        securityGroups: [props.securityGroup],
        jupyterLabAppSettings: {
          appLifecycleManagement: lifecycleConfiguration,
        },
      },
      kmsKeyId: props.customKmsKeyId,
    });
  }
```

but using `aws cli` to get information about my domain shows an incomplete configuration:

```
{
    "DefaultUserSettings": {
        "ExecutionRole": "...",
        "SecurityGroups": [
            "..."
        ],
        "SharingSettings": {
            "NotebookOutputOption": "Allowed",
            "S3OutputPath": "...",
            "S3KmsKeyId": "..."
        }
    },
    "DefaultSpaceSettings": {
        "ExecutionRole": "...",
        "SecurityGroups": [
            "..."
        ]
    }
}
```

I would expect it to show configuration for the `jupyterLabAppSettings` as well

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

`aws sagemaker describe-domain` should show the app settings similar than the console.
`aws sagemaker describe-space` should show the settings from the space instead of an empty object.

### Current Behavior

Using `aws sagemaker describe-domain` miss information for the `DefaultSpaceSettings` like the `CodeEditorAppSettings` and `JupyterLabAppSettings`.
Using `aws sagemaker describe-space` miss information for the `SpaceSettings`, it shows an empty object.

### Reproduction Steps

Run `aws sagemaker describe-domain` or `aws sagemaker describe-space` for a domain with custom app settings defined.

### CLI version used

aws-cli/2.13.32 Python/3.11.6 Linux/5.15.167.4-microsoft-standard-WSL2 exe/x86_64.ubuntu.22 prompt/off

### Environment details (OS name and version, etc.)

NAME="Ubuntu" VERSION_ID="22.04" VERSION="22.04.4 LTS (Jammy Jellyfish)"

**Comment by adev-code** [comment]
Hi @HeNeos,

Thanks for reaching out. I see that you are using CLI v2.13.32 which is a little over a year old. I also see, that the `jupyterLabAppSettings` property was introduced a little over a year ago. This leads me to believe that you are just using an older version of the CLI. You can verify that before updating your CLI version by running the same command just with the `--debug` flag. If you inspect the raw http response from the debug flag, you might be able to see that data being returned, but the deserialized response that you see without running that flag might not have that data. That points to a version mismatch. 

Please give it a try, and let me know how it goes.

**Comment by HeNeos** [comment]
@adev-code thanks, I have updated my CLI to 2.22.15 and it shows the correct configuration now for both.
