### ISSUE TITLE
put-bucket-acl appears to put acl's improperly

### ISSUE THREAD

**Issue by daniel-kristjansson** [aws/aws-cli#922]
BUCKET="my.bucket.name"
aws --region us-west-2 s3api put-bucket-acl --bucket $BUCKET --acl "$(aws --region us-west-2 s3api get-bucket-acl --bucket $BUCKET)"

This prints:
The output is: 'str' object has no attribute 'get'

With --debug the key line appears to be:
2014-09-26 11:47:14,293 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /us-west-2.disco.logging.ci?acl HTTP/1.1" 400 None

The output of get-bucket-acl appears to be correct and ACLs constructed using the AWS CLI docs fail as well.

**Comment by jamesls** [comment]
Following up on the issue here.  The main reason the command doesn't round trip is because S3 always converts the grantee to a canonical user id.  Also, S3 does not return the type in its XML response:

```
    <Grant>
      <Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser">
        <ID>id</ID>
        <DisplayName>jamesls</DisplayName>
      </Grantee>
...
```

We'd need an update on S3's end in order to properly round trip.
