### ISSUE TITLE
S3 streaming with s3 cp uses several GB of memory on upload

### ISSUE THREAD

**Issue by rlmcpherson** [aws/aws-cli#923]
In testing the streaming upload feature implemented in #903, it is reading the entire stream into memory, causing large memory usage for the tool. On an ubuntu ec2 instance running the latest master branch, uploading a 9 GB file resulted in 6.5-6.9 GB of real memory usage. 

Test command:

```
cat <large_file> | aws s3 cp - s3://bucket/key
```

**Comment by smboy** [comment]
Its a closed issue, but still commenting. For some reason, this is not working on the EMR isntance I'm using. Could you please let me know what might be wrong?

`cat filename.csv | aws s3 cp - s3://test-store/test-bucket/folder/filename.csv`

**Comment by jamesls** [comment]
What version of the CLI are you using?  In what way is it not working?  Do you have more information you can share?

**Comment by smboy** [comment]
The version of the cli is 
`aws --version
aws-cli/1.3.9 Python/2.6.9 Linux/3.14.20-20.44.amzn1.x86_64`

here is the error:
`cat ins.csv | aws s3 cp - s3://test-store/test-bucket/folder/ins.csv
[Errno 2] No such file or directory: '/home/hadoop/testuser/-'
Completed 1 part(s) with ... file(s) remaining`

**Comment by smboy** [comment]
I just spinned up a new EMR instance and upgraded the aws cli to 1.7. This feature is working as expected. Sorry for the false alarm.

thanks!

**Comment by RRAlex** [comment]
`--expected-size` is only used to used to segment the upload and doesn't have to be the correct file size right?
Because otherwise, doing `tar ... | aws s3 cp s3://...` will become very difficult without writing to disk.
