### ISSUE TITLE
Retrieving the IP address for an EC2 instance given its <instance ID>

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [aws/aws-cli#934]
Does the CLI have any commands that can be used to retrieve the _private IP_ of an EC2 instance given the instance ID ? 

What if I provide a tag instead?

**Comment by cig0** [comment]
Adding on top @jamesls answer:

`aws ec2 describe-instances --instance-id i-0329b8ad --query 'Reservations[].Instances[].PrivateIpAddress' | grep -vE '\[|\]' | awk -F'"' '{ print $2 }' `

This way you end up with a clean output.

**Comment by fearphage** [comment]
> This way you end up with a clean output.

There's also an extra param you can pass to `describe-instances` to accomplish the same thing:

```shell
aws ec2 describe-instances \
  --instance-id i-0329b8ad \
  --query 'Reservations[].Instances[].PrivateIpAddress' \
  --output text
```

**Comment by Zibri** [comment]
thy are all wrong... it seems the --instance.id is ignored and ALL instances are shown always

**Comment by fjaguero** [comment]
> thy are all wrong... it seems the --instance.id is ignored and ALL instances are shown always

It's `instance-id`, not `instance.id`
