### ISSUE TITLE
s3 cp: add option to disable multipart

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-cli#946]
When working with files below 5 GB it would be great to be able to disable multipart in order to guarantee a proper MD5 Etag.

This should be trivial to add. Maybe something similar to s3cmd 's --disable-multipart flag.

Cheers
Axel

**Comment by richfromm** [comment]
Sorry if this is the wrong place to ask, but is this exposed somehow via boto3?

My hope was that maybe I could do this by creating a [boto3.s3.transfer.TransferConfig]( http://boto3.readthedocs.io/en/latest/reference/customizations/s3.html#s3-transfers) with `multipart_threshold=None`, and passing that to [upload_file()](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Bucket.upload_file), but that doesn't work:

`ValueError: Provided parameter multipart_threshold of value None must be greater than 0.`
