### ISSUE TITLE
pem and cer file names must end with '.pem' and '.cer' -- why?

### ISSUE THREAD

**Issue by tilusnet** [aws/aws-cli#969]
Hi,

For a number of times I had my pem files rejected while requesting ssh access until I realised that the code requires them to have a ".pem" extension.

Is this really necessary?

My team members have already registered their private keys with AWS and this artificially looking requirement would make the migration to the aws-cli client somewhat cumbersome.

**Comment by kyleknap** [comment]
I believe this PR fixes this issue: https://github.com/aws/aws-cli/pull/1317

Resolving issue. If that is not the issue you are referring to, please reopen.
