### ISSUE TITLE
Error attempting to create a private hosted zone

### ISSUE THREAD

**Issue by hectcastro** [aws/aws-cli#989]
I'm getting the following error when I attempt to create a private hosted zone:

```
$ aws --version
aws-cli/1.5.6 Python/2.7.8 Darwin/14.0.0
$ aws route53 create-hosted-zone \
  --name nyc-trees.internal \
  --caller-reference create-private-dns-stack-2014-11-07-11:27 \
  --vpc VPCRegion=us-east-1,VPCId=vpc-37098152 \
  --hosted-zone-config Comment=create-private-dns-stack,PrivateZone=true

A client error (InvalidInput) occurred when calling the CreateHostedZone operation: Invalid XML ; cvc-complex-type.2.4.d: Invalid content was found starting with element 'PrivateZone'. No child element is expected at this point.
```

Not entirely sure I have all of the required arguments, but the error message leads me to believe that the `PrivateZone` hosted zone configuration parameter is not being accepted.

**Comment by vielmetti** [comment]
I misread this the same way, which makes me think this is a documentation bug.

**Comment by nicosnyman** [comment]
I know this has been closed - but it is indeed a documentation bug (that really frustrated me). Even the boto3 documentation has PrivateZone as aparameter in the request syntax:
https://boto3.readthedocs.org/en/latest/reference/services/route53.html#Route53.Client.create_hosted_zone
