### ISSUE TITLE
rds download-db-log-file-portion output one character by line

### ISSUE THREAD

**Issue by mtparet** [aws/aws-cli#996]
`aws rds download-db-log-file-portion --db-instance-identifier XXX --log-file-name XXX` output one character by line instead of line by line output:
```ruby
        "`", 
        "k", 
        "e", 
        "y", 
        "`", 
        " ", 
        "=", 
        " ", 
        "'", 
        "l", 
        "o", 
        "g", 
        "o", 
        "'", 
        "\n", 
        "\t", 
        "\t", 
        " ", 
        "6", 
        "6", 
```

**Comment by rayluo** [comment]
@jamesls The usage mentioned in the previous post in Nov 13, 2014, it works. Is there anything else you plan to fix for this issue?

**Comment by jamesls** [comment]
Yes.  To be clear, that suggestion is a workaround not a fix.  We should be fixing the issue at its core which is that we're not handling the case when the result key is a string, not a list.

**Comment by jamesls** [comment]
This should be fixed via https://github.com/boto/botocore/pull/689.

@rayluo please confirm.

**Comment by rodriguezsergio** [comment]
@mtparet Thanks for that workaround.

**Comment by rayluo** [comment]
The boto/botocore#689 changes the behavior of the original question in this issue. Now if you run the same command (i.e. without --output text), you won't see the improper "one character per line" output.

But then the real problem which @mtparet , @quiver , @rodriguezsergio were helping to solve (thanks everyone!), is how to download a big log file. This is addressed by a clear example in `aws rds download-db-log-file-portion help`, in #1617.
